GoogleElectionMap.votesReady({"status":"ok","totals":
{"date":"02-05","votes":[
{"votes":230608,"name":"huckabee"},
{"votes":210989,"name":"mccain"},
{"votes":103295,"name":"romney"},
{"votes":15454,"name":"paul"},
{"votes":2224,"name":"giuliani"},
{"votes":1929,"name":"thompson"},
{"votes":1252,"name":"uncommitted-r"},
{"votes":805,"name":"keyes"},
{"votes":399,"name":"hunter"},
{"votes":95,"name":"tancredo"}],
"precincts":
{"total":2827,"reporting":2821},
"name":"Alabama"},
"state":"AL","party":"gop","total":567050,"locals":
{"Shelby":
{"votes":[
{"votes":14010,"name":"huckabee"},
{"votes":11438,"name":"mccain"},
{"votes":6094,"name":"romney"},
{"votes":863,"name":"paul"},
{"votes":101,"name":"giuliani"},
{"votes":90,"name":"thompson"},
{"votes":59,"name":"uncommitted-r"},
{"votes":42,"name":"keyes"},
{"votes":19,"name":"hunter"},
{"votes":5,"name":"tancredo"}],
"total":32721,"precincts":
{"total":76,"reporting":76},
"name":"Shelby"},
"Perry":
{"votes":[
{"votes":351,"name":"mccain"},
{"votes":296,"name":"huckabee"},
{"votes":47,"name":"romney"},
{"votes":10,"name":"paul"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":712,"precincts":
{"total":18,"reporting":18},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":2629,"name":"huckabee"},
{"votes":1374,"name":"mccain"},
{"votes":727,"name":"romney"},
{"votes":134,"name":"paul"},
{"votes":20,"name":"thompson"},
{"votes":19,"name":"uncommitted-r"},
{"votes":17,"name":"giuliani"},
{"votes":8,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":4931,"precincts":
{"total":40,"reporting":40},
"name":"Jackson"},
"Russell":
{"votes":[
{"votes":1290,"name":"mccain"},
{"votes":995,"name":"huckabee"},
{"votes":731,"name":"romney"},
{"votes":52,"name":"paul"},
{"votes":13,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":9,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":3107,"precincts":
{"total":22,"reporting":22},
"name":"Russell"},
"Blount":
{"votes":[
{"votes":4483,"name":"huckabee"},
{"votes":2657,"name":"mccain"},
{"votes":874,"name":"romney"},
{"votes":165,"name":"paul"},
{"votes":29,"name":"giuliani"},
{"votes":27,"name":"thompson"},
{"votes":15,"name":"uncommitted-r"},
{"votes":10,"name":"hunter"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":8265,"precincts":
{"total":27,"reporting":27},
"name":"Blount"},
"Dallas":
{"votes":[
{"votes":1435,"name":"mccain"},
{"votes":1381,"name":"huckabee"},
{"votes":438,"name":"romney"},
{"votes":63,"name":"paul"},
{"votes":16,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":4,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":3354,"precincts":
{"total":32,"reporting":32},
"name":"Dallas"},
"Cherokee":
{"votes":[
{"votes":1337,"name":"huckabee"},
{"votes":805,"name":"mccain"},
{"votes":423,"name":"romney"},
{"votes":49,"name":"paul"},
{"votes":23,"name":"thompson"},
{"votes":14,"name":"giuliani"},
{"votes":10,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2669,"precincts":
{"total":26,"reporting":26},
"name":"Cherokee"},
"Clarke":
{"votes":[
{"votes":1430,"name":"mccain"},
{"votes":1267,"name":"huckabee"},
{"votes":328,"name":"romney"},
{"votes":46,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":7,"name":"thompson"},
{"votes":5,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":3098,"precincts":
{"total":31,"reporting":30},
"name":"Clarke"},
"Clay":
{"votes":[
{"votes":1127,"name":"huckabee"},
{"votes":803,"name":"mccain"},
{"votes":127,"name":"romney"},
{"votes":37,"name":"paul"},
{"votes":9,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":5,"name":"keyes"},
{"votes":1,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2117,"precincts":
{"total":25,"reporting":25},
"name":"Clay"},
"Colbert":
{"votes":[
{"votes":2885,"name":"huckabee"},
{"votes":1676,"name":"mccain"},
{"votes":1012,"name":"romney"},
{"votes":186,"name":"paul"},
{"votes":36,"name":"thompson"},
{"votes":21,"name":"giuliani"},
{"votes":18,"name":"uncommitted-r"},
{"votes":12,"name":"keyes"},
{"votes":11,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":5858,"precincts":
{"total":35,"reporting":35},
"name":"Colbert"},
"Calhoun":
{"votes":[
{"votes":6348,"name":"huckabee"},
{"votes":5056,"name":"mccain"},
{"votes":2027,"name":"romney"},
{"votes":342,"name":"paul"},
{"votes":37,"name":"giuliani"},
{"votes":31,"name":"uncommitted-r"},
{"votes":27,"name":"thompson"},
{"votes":10,"name":"hunter"},
{"votes":6,"name":"keyes"},
{"votes":3,"name":"tancredo"}],
"total":13887,"precincts":
{"total":50,"reporting":50},
"name":"Calhoun"},
"Cullman":
{"votes":[
{"votes":6568,"name":"huckabee"},
{"votes":4137,"name":"mccain"},
{"votes":1564,"name":"romney"},
{"votes":312,"name":"paul"},
{"votes":48,"name":"thompson"},
{"votes":42,"name":"giuliani"},
{"votes":24,"name":"uncommitted-r"},
{"votes":11,"name":"keyes"},
{"votes":6,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":12715,"precincts":
{"total":54,"reporting":54},
"name":"Cullman"},
"Covington":
{"votes":[
{"votes":2622,"name":"huckabee"},
{"votes":1773,"name":"mccain"},
{"votes":528,"name":"romney"},
{"votes":87,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":9,"name":"keyes"},
{"votes":8,"name":"uncommitted-r"},
{"votes":8,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":5048,"precincts":
{"total":30,"reporting":30},
"name":"Covington"},
"Jefferson":
{"votes":[
{"votes":29183,"name":"huckabee"},
{"votes":28218,"name":"mccain"},
{"votes":12856,"name":"romney"},
{"votes":2009,"name":"paul"},
{"votes":266,"name":"giuliani"},
{"votes":211,"name":"thompson"},
{"votes":152,"name":"uncommitted-r"},
{"votes":103,"name":"keyes"},
{"votes":42,"name":"hunter"},
{"votes":9,"name":"tancredo"}],
"total":73049,"precincts":
{"total":378,"reporting":378},
"name":"Jefferson"},
"Butler":
{"votes":[
{"votes":1082,"name":"mccain"},
{"votes":1040,"name":"huckabee"},
{"votes":291,"name":"romney"},
{"votes":34,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":7,"name":"thompson"},
{"votes":6,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"tancredo"}],
"total":2475,"precincts":
{"total":22,"reporting":22},
"name":"Butler"},
"DeKalb":
{"votes":[
{"votes":3532,"name":"huckabee"},
{"votes":2018,"name":"mccain"},
{"votes":886,"name":"romney"},
{"votes":189,"name":"paul"},
{"votes":24,"name":"thompson"},
{"votes":22,"name":"giuliani"},
{"votes":11,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":6692,"precincts":
{"total":51,"reporting":51},
"name":"DeKalb"},
"Cleburne":
{"votes":[
{"votes":1093,"name":"huckabee"},
{"votes":628,"name":"mccain"},
{"votes":174,"name":"romney"},
{"votes":55,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"uncommitted-r"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":1963,"precincts":
{"total":18,"reporting":18},
"name":"Cleburne"},
"Pickens":
{"votes":[
{"votes":1260,"name":"huckabee"},
{"votes":878,"name":"mccain"},
{"votes":126,"name":"romney"},
{"votes":29,"name":"paul"},
{"votes":7,"name":"giuliani"},
{"votes":4,"name":"hunter"},
{"votes":4,"name":"uncommitted-r"},
{"votes":4,"name":"thompson"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":2315,"precincts":
{"total":27,"reporting":27},
"name":"Pickens"},
"Dale":
{"votes":[
{"votes":2367,"name":"huckabee"},
{"votes":2342,"name":"mccain"},
{"votes":996,"name":"romney"},
{"votes":171,"name":"paul"},
{"votes":23,"name":"giuliani"},
{"votes":19,"name":"uncommitted-r"},
{"votes":18,"name":"thompson"},
{"votes":15,"name":"keyes"},
{"votes":5,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":5958,"precincts":
{"total":26,"reporting":26},
"name":"Dale"},
"Coffee":
{"votes":[
{"votes":2548,"name":"mccain"},
{"votes":2424,"name":"huckabee"},
{"votes":1022,"name":"romney"},
{"votes":100,"name":"paul"},
{"votes":26,"name":"giuliani"},
{"votes":17,"name":"uncommitted-r"},
{"votes":17,"name":"thompson"},
{"votes":11,"name":"keyes"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":6170,"precincts":
{"total":37,"reporting":37},
"name":"Coffee"},
"Marengo":
{"votes":[
{"votes":1175,"name":"huckabee"},
{"votes":1009,"name":"mccain"},
{"votes":185,"name":"romney"},
{"votes":17,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"giuliani"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2406,"precincts":
{"total":27,"reporting":27},
"name":"Marengo"},
"Lee":
{"votes":[
{"votes":5007,"name":"mccain"},
{"votes":4505,"name":"huckabee"},
{"votes":2923,"name":"romney"},
{"votes":575,"name":"paul"},
{"votes":60,"name":"thompson"},
{"votes":38,"name":"uncommitted-r"},
{"votes":36,"name":"giuliani"},
{"votes":19,"name":"keyes"},
{"votes":9,"name":"hunter"},
{"votes":5,"name":"tancredo"}],
"total":13177,"precincts":
{"total":37,"reporting":37},
"name":"Lee"},
"Geneva":
{"votes":[
{"votes":1521,"name":"huckabee"},
{"votes":1489,"name":"mccain"},
{"votes":487,"name":"romney"},
{"votes":105,"name":"paul"},
{"votes":12,"name":"thompson"},
{"votes":10,"name":"uncommitted-r"},
{"votes":10,"name":"giuliani"},
{"votes":8,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":3645,"precincts":
{"total":28,"reporting":28},
"name":"Geneva"},
"Lawrence":
{"votes":[
{"votes":6772,"name":"huckabee"},
{"votes":5342,"name":"mccain"},
{"votes":4060,"name":"romney"},
{"votes":511,"name":"paul"},
{"votes":72,"name":"thompson"},
{"votes":56,"name":"giuliani"},
{"votes":22,"name":"keyes"},
{"votes":8,"name":"uncommitted-r"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":16852,"precincts":
{"total":31,"reporting":31},
"name":"Lawrence"},
"Bibb":
{"votes":[
{"votes":1407,"name":"huckabee"},
{"votes":812,"name":"mccain"},
{"votes":154,"name":"romney"},
{"votes":41,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":5,"name":"keyes"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"uncommitted-r"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2436,"precincts":
{"total":10,"reporting":10},
"name":"Bibb"},
"Fayette":
{"votes":[
{"votes":1338,"name":"huckabee"},
{"votes":716,"name":"mccain"},
{"votes":148,"name":"romney"},
{"votes":31,"name":"paul"},
{"votes":10,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":6,"name":"uncommitted-r"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":2262,"precincts":
{"total":29,"reporting":29},
"name":"Fayette"},
"Coosa":
{"votes":[
{"votes":625,"name":"huckabee"},
{"votes":599,"name":"mccain"},
{"votes":105,"name":"romney"},
{"votes":30,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"tancredo"}],
"total":1373,"precincts":
{"total":14,"reporting":14},
"name":"Coosa"},
"Chilton":
{"votes":[
{"votes":3325,"name":"huckabee"},
{"votes":2055,"name":"mccain"},
{"votes":387,"name":"romney"},
{"votes":91,"name":"paul"},
{"votes":20,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":5897,"precincts":
{"total":20,"reporting":19},
"name":"Chilton"},
"Barbour":
{"votes":[
{"votes":1220,"name":"mccain"},
{"votes":1052,"name":"huckabee"},
{"votes":324,"name":"romney"},
{"votes":52,"name":"paul"},
{"votes":14,"name":"giuliani"},
{"votes":9,"name":"thompson"},
{"votes":8,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":2684,"precincts":
{"total":22,"reporting":22},
"name":"Barbour"},
"Lauderdale":
{"votes":[
{"votes":4672,"name":"huckabee"},
{"votes":2961,"name":"mccain"},
{"votes":2029,"name":"romney"},
{"votes":401,"name":"paul"},
{"votes":65,"name":"thompson"},
{"votes":26,"name":"giuliani"},
{"votes":20,"name":"uncommitted-r"},
{"votes":16,"name":"keyes"},
{"votes":9,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":10201,"precincts":
{"total":33,"reporting":33},
"name":"Lauderdale"},
"Tallapoosa":
{"votes":[
{"votes":2708,"name":"mccain"},
{"votes":2662,"name":"huckabee"},
{"votes":640,"name":"romney"},
{"votes":108,"name":"paul"},
{"votes":19,"name":"thompson"},
{"votes":16,"name":"giuliani"},
{"votes":13,"name":"uncommitted-r"},
{"votes":10,"name":"keyes"},
{"votes":9,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":6186,"precincts":
{"total":31,"reporting":31},
"name":"Tallapoosa"},
"St. Clair":
{"votes":[
{"votes":6081,"name":"huckabee"},
{"votes":4273,"name":"mccain"},
{"votes":1408,"name":"romney"},
{"votes":255,"name":"paul"},
{"votes":40,"name":"giuliani"},
{"votes":38,"name":"thompson"},
{"votes":27,"name":"uncommitted-r"},
{"votes":12,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":12138,"precincts":
{"total":37,"reporting":37},
"name":"St. Clair"},
"Hale":
{"votes":[
{"votes":577,"name":"huckabee"},
{"votes":546,"name":"mccain"},
{"votes":82,"name":"romney"},
{"votes":27,"name":"paul"},
{"votes":5,"name":"giuliani"},
{"votes":3,"name":"keyes"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1244,"precincts":
{"total":17,"reporting":17},
"name":"Hale"},
"Conecuh":
{"votes":[
{"votes":628,"name":"mccain"},
{"votes":544,"name":"huckabee"},
{"votes":148,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":5,"name":"giuliani"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":2,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1347,"precincts":
{"total":28,"reporting":28},
"name":"Conecuh"},
"Pike":
{"votes":[
{"votes":1717,"name":"mccain"},
{"votes":1341,"name":"huckabee"},
{"votes":533,"name":"romney"},
{"votes":52,"name":"paul"},
{"votes":18,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":11,"name":"uncommitted-r"},
{"votes":6,"name":"hunter"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":3693,"precincts":
{"total":29,"reporting":29},
"name":"Pike"},
"Crenshaw":
{"votes":[
{"votes":823,"name":"huckabee"},
{"votes":804,"name":"mccain"},
{"votes":189,"name":"romney"},
{"votes":25,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":9,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1864,"precincts":
{"total":20,"reporting":20},
"name":"Crenshaw"},
"Wilcox":
{"votes":[
{"votes":339,"name":"mccain"},
{"votes":262,"name":"huckabee"},
{"votes":59,"name":"romney"},
{"votes":5,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"uncommitted-r"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":673,"precincts":
{"total":30,"reporting":27},
"name":"Wilcox"},
"Mobile":
{"votes":[
{"votes":17043,"name":"mccain"},
{"votes":9324,"name":"romney"},
{"votes":7271,"name":"huckabee"},
{"votes":1199,"name":"paul"},
{"votes":440,"name":"giuliani"},
{"votes":145,"name":"thompson"},
{"votes":117,"name":"uncommitted-r"},
{"votes":78,"name":"keyes"},
{"votes":19,"name":"hunter"},
{"votes":12,"name":"tancredo"}],
"total":35648,"precincts":
{"total":187,"reporting":187},
"name":"Mobile"},
"Sumter":
{"votes":[
{"votes":306,"name":"mccain"},
{"votes":252,"name":"huckabee"},
{"votes":92,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":671,"precincts":
{"total":15,"reporting":15},
"name":"Sumter"},
"Lamar":
{"votes":[
{"votes":1035,"name":"huckabee"},
{"votes":598,"name":"mccain"},
{"votes":114,"name":"romney"},
{"votes":21,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":8,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":1788,"precincts":
{"total":27,"reporting":27},
"name":"Lamar"},
"Greene":
{"votes":[
{"votes":182,"name":"huckabee"},
{"votes":171,"name":"mccain"},
{"votes":35,"name":"romney"},
{"votes":14,"name":"paul"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"giuliani"}],
"total":405,"precincts":
{"total":16,"reporting":16},
"name":"Greene"},
"Franklin":
{"votes":[
{"votes":1675,"name":"huckabee"},
{"votes":770,"name":"mccain"},
{"votes":248,"name":"romney"},
{"votes":38,"name":"paul"},
{"votes":9,"name":"giuliani"},
{"votes":7,"name":"uncommitted-r"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":2759,"precincts":
{"total":26,"reporting":26},
"name":"Franklin"},
"Morgan":
{"votes":[
{"votes":6772,"name":"huckabee"},
{"votes":5342,"name":"mccain"},
{"votes":4060,"name":"romney"},
{"votes":511,"name":"paul"},
{"votes":72,"name":"thompson"},
{"votes":56,"name":"giuliani"},
{"votes":36,"name":"uncommitted-r"},
{"votes":22,"name":"keyes"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":16880,"precincts":
{"total":59,"reporting":59},
"name":"Morgan"},
"Henry":
{"votes":[
{"votes":1013,"name":"huckabee"},
{"votes":849,"name":"mccain"},
{"votes":307,"name":"romney"},
{"votes":67,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":7,"name":"keyes"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"hunter"},
{"votes":4,"name":"uncommitted-r"},
{"votes":0,"name":"tancredo"}],
"total":2267,"precincts":
{"total":17,"reporting":17},
"name":"Henry"},
"Walker":
{"votes":[
{"votes":4597,"name":"huckabee"},
{"votes":2522,"name":"mccain"},
{"votes":557,"name":"romney"},
{"votes":91,"name":"paul"},
{"votes":21,"name":"uncommitted-r"},
{"votes":21,"name":"giuliani"},
{"votes":16,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":5,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":7838,"precincts":
{"total":47,"reporting":47},
"name":"Walker"},
"Montgomery":
{"votes":[
{"votes":9218,"name":"mccain"},
{"votes":7475,"name":"huckabee"},
{"votes":5172,"name":"romney"},
{"votes":500,"name":"paul"},
{"votes":75,"name":"giuliani"},
{"votes":65,"name":"thompson"},
{"votes":33,"name":"uncommitted-r"},
{"votes":23,"name":"keyes"},
{"votes":10,"name":"hunter"},
{"votes":4,"name":"tancredo"}],
"total":22575,"precincts":
{"total":123,"reporting":123},
"name":"Montgomery"},
"Etowah":
{"votes":[
{"votes":6212,"name":"huckabee"},
{"votes":4084,"name":"mccain"},
{"votes":1821,"name":"romney"},
{"votes":276,"name":"paul"},
{"votes":46,"name":"thompson"},
{"votes":34,"name":"giuliani"},
{"votes":29,"name":"uncommitted-r"},
{"votes":22,"name":"keyes"},
{"votes":10,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":12537,"precincts":
{"total":58,"reporting":58},
"name":"Etowah"},
"Macon":
{"votes":[
{"votes":245,"name":"mccain"},
{"votes":229,"name":"huckabee"},
{"votes":91,"name":"romney"},
{"votes":8,"name":"paul"},
{"votes":7,"name":"uncommitted-r"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"giuliani"},
{"votes":0,"name":"tancredo"}],
"total":584,"precincts":
{"total":20,"reporting":20},
"name":"Macon"},
"Houston":
{"votes":[
{"votes":4875,"name":"huckabee"},
{"votes":4467,"name":"mccain"},
{"votes":2536,"name":"romney"},
{"votes":347,"name":"paul"},
{"votes":31,"name":"giuliani"},
{"votes":26,"name":"uncommitted-r"},
{"votes":24,"name":"thompson"},
{"votes":15,"name":"keyes"},
{"votes":10,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":12331,"precincts":
{"total":38,"reporting":38},
"name":"Houston"},
"Madison":
{"votes":[
{"votes":13406,"name":"huckabee"},
{"votes":12932,"name":"mccain"},
{"votes":12237,"name":"romney"},
{"votes":1697,"name":"paul"},
{"votes":210,"name":"thompson"},
{"votes":144,"name":"giuliani"},
{"votes":88,"name":"uncommitted-r"},
{"votes":86,"name":"keyes"},
{"votes":37,"name":"hunter"},
{"votes":7,"name":"tancredo"}],
"total":40844,"precincts":
{"total":106,"reporting":106},
"name":"Madison"},
"Limestone":
{"votes":[
{"votes":3980,"name":"huckabee"},
{"votes":3030,"name":"mccain"},
{"votes":2891,"name":"romney"},
{"votes":503,"name":"paul"},
{"votes":53,"name":"thompson"},
{"votes":28,"name":"uncommitted-r"},
{"votes":25,"name":"giuliani"},
{"votes":24,"name":"keyes"},
{"votes":6,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":10542,"precincts":
{"total":35,"reporting":35},
"name":"Limestone"},
"Baldwin":
{"votes":[
{"votes":13142,"name":"mccain"},
{"votes":7584,"name":"romney"},
{"votes":7251,"name":"huckabee"},
{"votes":771,"name":"paul"},
{"votes":115,"name":"giuliani"},
{"votes":102,"name":"uncommitted-r"},
{"votes":86,"name":"thompson"},
{"votes":46,"name":"keyes"},
{"votes":8,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":29108,"precincts":
{"total":69,"reporting":69},
"name":"Baldwin"},
"Marshall":
{"votes":[
{"votes":4976,"name":"huckabee"},
{"votes":3530,"name":"mccain"},
{"votes":2200,"name":"romney"},
{"votes":373,"name":"paul"},
{"votes":45,"name":"thompson"},
{"votes":31,"name":"giuliani"},
{"votes":27,"name":"uncommitted-r"},
{"votes":16,"name":"keyes"},
{"votes":7,"name":"hunter"},
{"votes":4,"name":"tancredo"}],
"total":11209,"precincts":
{"total":47,"reporting":47},
"name":"Marshall"},
"Winston":
{"votes":[
{"votes":2224,"name":"huckabee"},
{"votes":1512,"name":"mccain"},
{"votes":362,"name":"romney"},
{"votes":41,"name":"paul"},
{"votes":18,"name":"giuliani"},
{"votes":11,"name":"uncommitted-r"},
{"votes":9,"name":"hunter"},
{"votes":7,"name":"thompson"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":4187,"precincts":
{"total":24,"reporting":24},
"name":"Winston"},
"Washington":
{"votes":[
{"votes":847,"name":"huckabee"},
{"votes":835,"name":"mccain"},
{"votes":185,"name":"romney"},
{"votes":24,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":5,"name":"keyes"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1912,"precincts":
{"total":36,"reporting":36},
"name":"Washington"},
"Talladega":
{"votes":[
{"votes":4100,"name":"huckabee"},
{"votes":3373,"name":"mccain"},
{"votes":695,"name":"romney"},
{"votes":265,"name":"paul"},
{"votes":45,"name":"giuliani"},
{"votes":23,"name":"keyes"},
{"votes":21,"name":"uncommitted-r"},
{"votes":20,"name":"thompson"},
{"votes":9,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":8553,"precincts":
{"total":34,"reporting":34},
"name":"Talladega"},
"Bullock":
{"votes":[
{"votes":293,"name":"mccain"},
{"votes":189,"name":"huckabee"},
{"votes":75,"name":"romney"},
{"votes":10,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":2,"name":"giuliani"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"keyes"}],
"total":573,"precincts":
{"total":18,"reporting":18},
"name":"Bullock"},
"Tuscaloosa":
{"votes":[
{"votes":9168,"name":"huckabee"},
{"votes":6422,"name":"mccain"},
{"votes":2639,"name":"romney"},
{"votes":644,"name":"paul"},
{"votes":53,"name":"giuliani"},
{"votes":49,"name":"thompson"},
{"votes":36,"name":"uncommitted-r"},
{"votes":9,"name":"keyes"},
{"votes":7,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":19030,"precincts":
{"total":100,"reporting":100},
"name":"Tuscaloosa"},
"Elmore":
{"votes":[
{"votes":5561,"name":"huckabee"},
{"votes":5075,"name":"mccain"},
{"votes":1806,"name":"romney"},
{"votes":251,"name":"paul"},
{"votes":46,"name":"giuliani"},
{"votes":44,"name":"thompson"},
{"votes":19,"name":"uncommitted-r"},
{"votes":17,"name":"keyes"},
{"votes":9,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":12829,"precincts":
{"total":31,"reporting":31},
"name":"Elmore"},
"Marion":
{"votes":[
{"votes":2087,"name":"huckabee"},
{"votes":1134,"name":"mccain"},
{"votes":255,"name":"romney"},
{"votes":54,"name":"paul"},
{"votes":14,"name":"thompson"},
{"votes":14,"name":"giuliani"},
{"votes":5,"name":"hunter"},
{"votes":3,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":3568,"precincts":
{"total":23,"reporting":23},
"name":"Marion"},
"Choctaw":
{"votes":[
{"votes":785,"name":"huckabee"},
{"votes":596,"name":"mccain"},
{"votes":130,"name":"romney"},
{"votes":8,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1532,"precincts":
{"total":48,"reporting":47},
"name":"Choctaw"},
"Escambia":
{"votes":[
{"votes":1630,"name":"mccain"},
{"votes":1468,"name":"huckabee"},
{"votes":435,"name":"romney"},
{"votes":59,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":8,"name":"hunter"},
{"votes":7,"name":"uncommitted-r"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":3627,"precincts":
{"total":35,"reporting":35},
"name":"Escambia"},
"Chambers":
{"votes":[
{"votes":1314,"name":"mccain"},
{"votes":1165,"name":"huckabee"},
{"votes":412,"name":"romney"},
{"votes":85,"name":"paul"},
{"votes":16,"name":"thompson"},
{"votes":16,"name":"giuliani"},
{"votes":9,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":3021,"precincts":
{"total":22,"reporting":22},
"name":"Chambers"},
"Lowndes":
{"votes":[
{"votes":343,"name":"mccain"},
{"votes":338,"name":"huckabee"},
{"votes":148,"name":"romney"},
{"votes":20,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"tancredo"}],
"total":865,"precincts":
{"total":15,"reporting":15},
"name":"Lowndes"},
"Randolph":
{"votes":[
{"votes":1249,"name":"huckabee"},
{"votes":1092,"name":"mccain"},
{"votes":281,"name":"romney"},
{"votes":87,"name":"paul"},
{"votes":8,"name":"uncommitted-r"},
{"votes":8,"name":"keyes"},
{"votes":7,"name":"thompson"},
{"votes":6,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2741,"precincts":
{"total":25,"reporting":25},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":1427,"name":"mccain"},
{"votes":1118,"name":"huckabee"},
{"votes":297,"name":"romney"},
{"votes":50,"name":"paul"},
{"votes":18,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":7,"name":"uncommitted-r"},
{"votes":6,"name":"keyes"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":2937,"precincts":
{"total":33,"reporting":33},
"name":"Monroe"},
"Autauga":
{"votes":[
{"votes":3579,"name":"huckabee"},
{"votes":3530,"name":"mccain"},
{"votes":1174,"name":"romney"},
{"votes":155,"name":"paul"},
{"votes":21,"name":"thompson"},
{"votes":21,"name":"giuliani"},
{"votes":16,"name":"uncommitted-r"},
{"votes":6,"name":"keyes"},
{"votes":5,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":8507,"precincts":
{"total":25,"reporting":25},
"name":"Autauga"}}})