GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":206983,"name":"clinton","delegates":27},
{"votes":78898,"name":"obama","delegates":8},
{"votes":5527,"name":"edwards"},
{"votes":3225,"name":"uncommitted-d"},
{"votes":776,"name":"richardson"},
{"votes":494,"name":"biden"},
{"votes":355,"name":"kucinich"},
{"votes":310,"name":"gravel"},
{"votes":253,"name":"dodd"}],
"name":"Arkansas","precincts":
{"total":2480,"reporting":2402},
"delegates":35,"date":"02-05"},
"state":"AR","party":"dem","total":296821,"locals":
{"Saline":
{"votes":[
{"votes":9230,"name":"clinton"},
{"votes":2022,"name":"obama"},
{"votes":232,"name":"edwards"},
{"votes":139,"name":"uncommitted-d"},
{"votes":25,"name":"richardson"},
{"votes":19,"name":"gravel"},
{"votes":15,"name":"kucinich"},
{"votes":9,"name":"biden"},
{"votes":6,"name":"dodd"}],
"total":11697,"precincts":
{"total":37,"reporting":37},
"name":"Saline"},
"Clark":
{"votes":[
{"votes":2385,"name":"clinton"},
{"votes":864,"name":"obama"},
{"votes":74,"name":"edwards"},
{"votes":44,"name":"uncommitted-d"},
{"votes":20,"name":"richardson"},
{"votes":6,"name":"gravel"},
{"votes":4,"name":"biden"},
{"votes":1,"name":"kucinich"}],
"total":3398,"precincts":
{"total":21,"reporting":21},
"name":"Clark"},
"Mississippi":
{"votes":[
{"votes":2762,"name":"clinton"},
{"votes":1170,"name":"obama"},
{"votes":72,"name":"edwards"},
{"votes":22,"name":"uncommitted-d"},
{"votes":8,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":4047,"precincts":
{"total":71,"reporting":71},
"name":"Mississippi"},
"Perry":
{"votes":[
{"votes":1270,"name":"clinton"},
{"votes":198,"name":"obama"},
{"votes":60,"name":"edwards"},
{"votes":30,"name":"uncommitted-d"},
{"votes":9,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":1576,"precincts":
{"total":19,"reporting":19},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":2139,"name":"clinton"},
{"votes":353,"name":"obama"},
{"votes":40,"name":"edwards"},
{"votes":26,"name":"uncommitted-d"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":2583,"precincts":
{"total":19,"reporting":19},
"name":"Jackson"},
"Dallas":
{"votes":[
{"votes":761,"name":"clinton"},
{"votes":428,"name":"obama"},
{"votes":47,"name":"edwards"},
{"votes":19,"name":"uncommitted-d"},
{"votes":7,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"kucinich"}],
"total":1278,"precincts":
{"total":22,"reporting":22},
"name":"Dallas"},
"Union":
{"votes":[
{"votes":2244,"name":"clinton"},
{"votes":1254,"name":"obama"},
{"votes":63,"name":"edwards"},
{"votes":35,"name":"uncommitted-d"},
{"votes":21,"name":"richardson"},
{"votes":10,"name":"kucinich"},
{"votes":8,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":3640,"precincts":
{"total":30,"reporting":30},
"name":"Union"},
"Sevier":
{"votes":[
{"votes":1080,"name":"clinton"},
{"votes":179,"name":"obama"},
{"votes":38,"name":"edwards"},
{"votes":32,"name":"uncommitted-d"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":1344,"precincts":
{"total":19,"reporting":19},
"name":"Sevier"},
"Calhoun":
{"votes":[
{"votes":552,"name":"clinton"},
{"votes":167,"name":"obama"},
{"votes":21,"name":"edwards"},
{"votes":18,"name":"uncommitted-d"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":775,"precincts":
{"total":12,"reporting":12},
"name":"Calhoun"},
"Montgomery":
{"votes":[
{"votes":849,"name":"clinton"},
{"votes":184,"name":"obama"},
{"votes":32,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"biden"}],
"total":1090,"precincts":
{"total":18,"reporting":18},
"name":"Montgomery"},
"Pulaski":
{"votes":[
{"votes":30328,"name":"clinton"},
{"votes":22897,"name":"obama"},
{"votes":470,"name":"edwards"},
{"votes":367,"name":"uncommitted-d"},
{"votes":65,"name":"richardson"},
{"votes":45,"name":"kucinich"},
{"votes":43,"name":"biden"},
{"votes":25,"name":"gravel"},
{"votes":20,"name":"dodd"}],
"total":54260,"precincts":
{"total":133,"reporting":133},
"name":"Pulaski"},
"Phillips":
{"votes":[
{"votes":1357,"name":"obama"},
{"votes":1258,"name":"clinton"},
{"votes":55,"name":"edwards"},
{"votes":28,"name":"uncommitted-d"},
{"votes":10,"name":"biden"},
{"votes":10,"name":"gravel"},
{"votes":6,"name":"richardson"},
{"votes":6,"name":"kucinich"},
{"votes":3,"name":"dodd"}],
"total":2733,"precincts":
{"total":20,"reporting":20},
"name":"Phillips"},
"Jefferson":
{"votes":[
{"votes":6236,"name":"clinton"},
{"votes":4730,"name":"obama"},
{"votes":87,"name":"edwards"},
{"votes":41,"name":"uncommitted-d"},
{"votes":29,"name":"richardson"},
{"votes":10,"name":"biden"},
{"votes":9,"name":"dodd"},
{"votes":7,"name":"kucinich"},
{"votes":3,"name":"gravel"}],
"total":11152,"precincts":
{"total":202,"reporting":202},
"name":"Jefferson"},
"Crittenden":
{"votes":[
{"votes":1987,"name":"obama"},
{"votes":1807,"name":"clinton"},
{"votes":34,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"},
{"votes":7,"name":"dodd"},
{"votes":6,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":3863,"precincts":
{"total":45,"reporting":45},
"name":"Crittenden"},
"Faulkner":
{"votes":[
{"votes":6574,"name":"clinton"},
{"votes":2372,"name":"obama"},
{"votes":177,"name":"edwards"},
{"votes":121,"name":"uncommitted-d"},
{"votes":23,"name":"dodd"},
{"votes":21,"name":"richardson"},
{"votes":13,"name":"kucinich"},
{"votes":13,"name":"gravel"},
{"votes":11,"name":"biden"}],
"total":9325,"precincts":
{"total":48,"reporting":48},
"name":"Faulkner"},
"Crawford":
{"votes":[
{"votes":3977,"name":"clinton"},
{"votes":728,"name":"obama"},
{"votes":140,"name":"edwards"},
{"votes":51,"name":"uncommitted-d"},
{"votes":16,"name":"richardson"},
{"votes":6,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":4930,"precincts":
{"total":44,"reporting":44},
"name":"Crawford"},
"White":
{"votes":[
{"votes":5181,"name":"clinton"},
{"votes":872,"name":"obama"},
{"votes":127,"name":"edwards"},
{"votes":71,"name":"uncommitted-d"},
{"votes":24,"name":"richardson"},
{"votes":14,"name":"biden"},
{"votes":11,"name":"kucinich"},
{"votes":8,"name":"dodd"},
{"votes":8,"name":"gravel"}],
"total":6316,"precincts":
{"total":91,"reporting":91},
"name":"White"},
"Independence":
{"votes":[
{"votes":3422,"name":"clinton"},
{"votes":493,"name":"obama"},
{"votes":84,"name":"edwards"},
{"votes":62,"name":"uncommitted-d"},
{"votes":20,"name":"biden"},
{"votes":19,"name":"richardson"},
{"votes":6,"name":"dodd"},
{"votes":4,"name":"gravel"},
{"votes":1,"name":"kucinich"}],
"total":4111,"precincts":
{"total":31,"reporting":31},
"name":"Independence"},
"Johnson":
{"votes":[
{"votes":2559,"name":"clinton"},
{"votes":420,"name":"obama"},
{"votes":85,"name":"edwards"},
{"votes":39,"name":"uncommitted-d"},
{"votes":8,"name":"richardson"},
{"votes":8,"name":"kucinich"},
{"votes":6,"name":"dodd"},
{"votes":6,"name":"gravel"},
{"votes":4,"name":"biden"}],
"total":3135,"precincts":
{"total":24,"reporting":24},
"name":"Johnson"},
"Polk":
{"votes":[
{"votes":1321,"name":"clinton"},
{"votes":348,"name":"obama"},
{"votes":61,"name":"edwards"},
{"votes":29,"name":"uncommitted-d"},
{"votes":11,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"dodd"}],
"total":1787,"precincts":
{"total":19,"reporting":19},
"name":"Polk"},
"Columbia":
{"votes":[
{"votes":1430,"name":"clinton"},
{"votes":769,"name":"obama"},
{"votes":44,"name":"edwards"},
{"votes":39,"name":"uncommitted-d"},
{"votes":15,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"kucinich"}],
"total":2307,"precincts":
{"total":19,"reporting":19},
"name":"Columbia"},
"Lee":
{"votes":[
{"votes":647,"name":"obama"},
{"votes":609,"name":"clinton"},
{"votes":22,"name":"edwards"},
{"votes":9,"name":"uncommitted-d"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"gravel"}],
"total":1296,"precincts":
{"total":15,"reporting":15},
"name":"Lee"},
"Garland":
{"votes":[
{"votes":8702,"name":"clinton"},
{"votes":2618,"name":"obama"},
{"votes":143,"name":"uncommitted-d"},
{"votes":133,"name":"edwards"},
{"votes":18,"name":"richardson"},
{"votes":15,"name":"kucinich"},
{"votes":8,"name":"dodd"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"gravel"}],
"total":11645,"precincts":
{"total":41,"reporting":41},
"name":"Garland"},
"Lawrence":
{"votes":[
{"votes":2025,"name":"clinton"},
{"votes":188,"name":"obama"},
{"votes":74,"name":"edwards"},
{"votes":26,"name":"uncommitted-d"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"gravel"}],
"total":2325,"precincts":
{"total":28,"reporting":28},
"name":"Lawrence"},
"Saint Francis":
{"votes":[
{"votes":1602,"name":"clinton"},
{"votes":1504,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":22,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":3167,"precincts":
{"total":19,"reporting":19},
"name":"Saint Francis"},
"Howard":
{"votes":[
{"votes":1180,"name":"clinton"},
{"votes":334,"name":"obama"},
{"votes":31,"name":"edwards"},
{"votes":18,"name":"uncommitted-d"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"}],
"total":1574,"precincts":
{"total":21,"reporting":21},
"name":"Howard"},
"Van Buren":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Van Buren"},
"Drew":
{"votes":[
{"votes":1587,"name":"clinton"},
{"votes":654,"name":"obama"},
{"votes":67,"name":"edwards"},
{"votes":27,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":2352,"precincts":
{"total":19,"reporting":19},
"name":"Drew"},
"Craighead":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Craighead"},
"Scott":
{"votes":[
{"votes":1145,"name":"clinton"},
{"votes":212,"name":"obama"},
{"votes":99,"name":"edwards"},
{"votes":67,"name":"uncommitted-d"},
{"votes":14,"name":"richardson"},
{"votes":12,"name":"biden"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":1556,"precincts":
{"total":28,"reporting":28},
"name":"Scott"},
"Grant":
{"votes":[
{"votes":1953,"name":"clinton"},
{"votes":193,"name":"obama"},
{"votes":54,"name":"edwards"},
{"votes":44,"name":"uncommitted-d"},
{"votes":7,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"kucinich"}],
"total":2263,"precincts":
{"total":22,"reporting":22},
"name":"Grant"},
"Izard":
{"votes":[
{"votes":1462,"name":"clinton"},
{"votes":221,"name":"obama"},
{"votes":49,"name":"edwards"},
{"votes":32,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":9,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":1787,"precincts":
{"total":19,"reporting":19},
"name":"Izard"},
"Little River":
{"votes":[
{"votes":1265,"name":"clinton"},
{"votes":359,"name":"obama"},
{"votes":61,"name":"edwards"},
{"votes":51,"name":"uncommitted-d"},
{"votes":9,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"kucinich"}],
"total":1753,"precincts":
{"total":22,"reporting":22},
"name":"Little River"},
"Pike":
{"votes":[
{"votes":1076,"name":"clinton"},
{"votes":99,"name":"obama"},
{"votes":55,"name":"uncommitted-d"},
{"votes":48,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":1290,"precincts":
{"total":15,"reporting":15},
"name":"Pike"},
"Stone":
{"votes":[],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Stone"},
"Ashley":
{"votes":[
{"votes":1823,"name":"clinton"},
{"votes":721,"name":"obama"},
{"votes":51,"name":"edwards"},
{"votes":47,"name":"uncommitted-d"},
{"votes":11,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":3,"name":"kucinich"}],
"total":2678,"precincts":
{"total":24,"reporting":24},
"name":"Ashley"},
"Cleburne":
{"votes":[
{"votes":2779,"name":"clinton"},
{"votes":456,"name":"obama"},
{"votes":107,"name":"edwards"},
{"votes":60,"name":"uncommitted-d"},
{"votes":9,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":5,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":3429,"precincts":
{"total":36,"reporting":36},
"name":"Cleburne"},
"Carroll":
{"votes":[
{"votes":1868,"name":"clinton"},
{"votes":782,"name":"obama"},
{"votes":74,"name":"edwards"},
{"votes":31,"name":"uncommitted-d"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":2775,"precincts":
{"total":31,"reporting":31},
"name":"Carroll"},
"Hot Spring":
{"votes":[
{"votes":3527,"name":"clinton"},
{"votes":725,"name":"obama"},
{"votes":147,"name":"edwards"},
{"votes":102,"name":"uncommitted-d"},
{"votes":16,"name":"richardson"},
{"votes":14,"name":"biden"},
{"votes":7,"name":"dodd"},
{"votes":5,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":4544,"precincts":
{"total":30,"reporting":30},
"name":"Hot Spring"},
"Benton":
{"votes":[
{"votes":8563,"name":"clinton"},
{"votes":3169,"name":"obama"},
{"votes":177,"name":"edwards"},
{"votes":81,"name":"uncommitted-d"},
{"votes":19,"name":"richardson"},
{"votes":18,"name":"kucinich"},
{"votes":16,"name":"biden"},
{"votes":8,"name":"dodd"},
{"votes":8,"name":"gravel"}],
"total":12059,"precincts":
{"total":83,"reporting":83},
"name":"Benton"},
"Cross":
{"votes":[
{"votes":1400,"name":"clinton"},
{"votes":397,"name":"obama"},
{"votes":38,"name":"edwards"},
{"votes":27,"name":"uncommitted-d"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":1876,"precincts":
{"total":8,"reporting":8},
"name":"Cross"},
"Greene":
{"votes":[
{"votes":4111,"name":"clinton"},
{"votes":411,"name":"obama"},
{"votes":118,"name":"edwards"},
{"votes":49,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":4719,"precincts":
{"total":34,"reporting":34},
"name":"Greene"},
"Searcy":
{"votes":[
{"votes":531,"name":"clinton"},
{"votes":84,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":5,"name":"kucinich"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"}],
"total":635,"precincts":
{"total":17,"reporting":17},
"name":"Searcy"},
"Lafayette":
{"votes":[
{"votes":613,"name":"clinton"},
{"votes":281,"name":"obama"},
{"votes":23,"name":"edwards"},
{"votes":21,"name":"uncommitted-d"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":945,"precincts":
{"total":22,"reporting":22},
"name":"Lafayette"},
"Franklin":
{"votes":[
{"votes":1919,"name":"clinton"},
{"votes":284,"name":"obama"},
{"votes":89,"name":"edwards"},
{"votes":16,"name":"richardson"},
{"votes":13,"name":"uncommitted-d"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"biden"}],
"total":2335,"precincts":
{"total":31,"reporting":31},
"name":"Franklin"},
"Boone":
{"votes":[
{"votes":2479,"name":"clinton"},
{"votes":596,"name":"obama"},
{"votes":84,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":3186,"precincts":
{"total":21,"reporting":21},
"name":"Boone"},
"Clay":
{"votes":[
{"votes":2474,"name":"clinton"},
{"votes":209,"name":"obama"},
{"votes":42,"name":"edwards"},
{"votes":31,"name":"uncommitted-d"},
{"votes":18,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"gravel"}],
"total":2788,"precincts":
{"total":17,"reporting":17},
"name":"Clay"},
"Poinsett":
{"votes":[
{"votes":2749,"name":"clinton"},
{"votes":262,"name":"obama"},
{"votes":64,"name":"edwards"},
{"votes":24,"name":"uncommitted-d"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"kucinich"}],
"total":3113,"precincts":
{"total":10,"reporting":10},
"name":"Poinsett"},
"Ouachita":
{"votes":[
{"votes":2236,"name":"clinton"},
{"votes":1371,"name":"obama"},
{"votes":94,"name":"edwards"},
{"votes":74,"name":"uncommitted-d"},
{"votes":12,"name":"biden"},
{"votes":11,"name":"richardson"},
{"votes":10,"name":"kucinich"},
{"votes":8,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":3820,"precincts":
{"total":22,"reporting":22},
"name":"Ouachita"},
"Yell":
{"votes":[
{"votes":1826,"name":"clinton"},
{"votes":257,"name":"obama"},
{"votes":53,"name":"edwards"},
{"votes":23,"name":"uncommitted-d"},
{"votes":6,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":2178,"precincts":
{"total":27,"reporting":27},
"name":"Yell"},
"Sebastian":
{"votes":[
{"votes":7024,"name":"clinton"},
{"votes":2121,"name":"obama"},
{"votes":211,"name":"edwards"},
{"votes":106,"name":"uncommitted-d"},
{"votes":28,"name":"richardson"},
{"votes":16,"name":"biden"},
{"votes":13,"name":"kucinich"},
{"votes":11,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":9533,"precincts":
{"total":52,"reporting":52},
"name":"Sebastian"},
"Arkansas":
{"votes":[
{"votes":2017,"name":"clinton"},
{"votes":499,"name":"obama"},
{"votes":58,"name":"edwards"},
{"votes":35,"name":"uncommitted-d"},
{"votes":15,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":2634,"precincts":
{"total":17,"reporting":17},
"name":"Arkansas"},
"Fulton":
{"votes":[
{"votes":1346,"name":"clinton"},
{"votes":235,"name":"obama"},
{"votes":53,"name":"edwards"},
{"votes":20,"name":"uncommitted-d"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":1674,"precincts":
{"total":14,"reporting":14},
"name":"Fulton"},
"Baxter":
{"votes":[
{"votes":2895,"name":"clinton"},
{"votes":1163,"name":"obama"},
{"votes":114,"name":"edwards"},
{"votes":32,"name":"uncommitted-d"},
{"votes":21,"name":"richardson"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"dodd"}],
"total":4243,"precincts":
{"total":26,"reporting":26},
"name":"Baxter"},
"Woodruff":
{"votes":[
{"votes":1114,"name":"clinton"},
{"votes":271,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":8,"name":"uncommitted-d"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"richardson"}],
"total":1428,"precincts":
{"total":20,"reporting":20},
"name":"Woodruff"},
"Madison":
{"votes":[
{"votes":1621,"name":"clinton"},
{"votes":309,"name":"obama"},
{"votes":46,"name":"edwards"},
{"votes":28,"name":"uncommitted-d"},
{"votes":13,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"biden"}],
"total":2023,"precincts":
{"total":28,"reporting":28},
"name":"Madison"},
"Lincoln":
{"votes":[
{"votes":1110,"name":"clinton"},
{"votes":337,"name":"obama"},
{"votes":29,"name":"uncommitted-d"},
{"votes":24,"name":"edwards"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":1510,"precincts":
{"total":28,"reporting":28},
"name":"Lincoln"},
"Lonoke":
{"votes":[
{"votes":4302,"name":"clinton"},
{"votes":980,"name":"obama"},
{"votes":99,"name":"edwards"},
{"votes":96,"name":"uncommitted-d"},
{"votes":15,"name":"biden"},
{"votes":15,"name":"richardson"},
{"votes":8,"name":"gravel"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"kucinich"}],
"total":5521,"precincts":
{"total":56,"reporting":56},
"name":"Lonoke"},
"Hempstead":
{"votes":[
{"votes":1696,"name":"clinton"},
{"votes":508,"name":"obama"},
{"votes":49,"name":"edwards"},
{"votes":30,"name":"uncommitted-d"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"kucinich"},
{"votes":5,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":2308,"precincts":
{"total":28,"reporting":28},
"name":"Hempstead"},
"Pope":
{"votes":[
{"votes":3346,"name":"clinton"},
{"votes":736,"name":"obama"},
{"votes":138,"name":"edwards"},
{"votes":68,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":9,"name":"biden"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"kucinich"}],
"total":4321,"precincts":
{"total":56,"reporting":56},
"name":"Pope"},
"Conway":
{"votes":[
{"votes":2068,"name":"clinton"},
{"votes":620,"name":"obama"},
{"votes":81,"name":"edwards"},
{"votes":39,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":2833,"precincts":
{"total":32,"reporting":32},
"name":"Conway"},
"Miller":
{"votes":[
{"votes":2254,"name":"clinton"},
{"votes":883,"name":"obama"},
{"votes":50,"name":"edwards"},
{"votes":32,"name":"uncommitted-d"},
{"votes":11,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"kucinich"}],
"total":3239,"precincts":
{"total":27,"reporting":27},
"name":"Miller"},
"Newton":
{"votes":[
{"votes":653,"name":"clinton"},
{"votes":170,"name":"obama"},
{"votes":18,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"kucinich"}],
"total":850,"precincts":
{"total":22,"reporting":22},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":12028,"name":"clinton"},
{"votes":5019,"name":"obama"},
{"votes":208,"name":"edwards"},
{"votes":103,"name":"uncommitted-d"},
{"votes":34,"name":"kucinich"},
{"votes":33,"name":"richardson"},
{"votes":19,"name":"gravel"},
{"votes":17,"name":"biden"},
{"votes":4,"name":"dodd"}],
"total":17465,"precincts":
{"total":122,"reporting":122},
"name":"Washington"},
"Desha":
{"votes":[
{"votes":1185,"name":"clinton"},
{"votes":583,"name":"obama"},
{"votes":18,"name":"uncommitted-d"},
{"votes":18,"name":"edwards"},
{"votes":5,"name":"kucinich"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":1816,"precincts":
{"total":22,"reporting":22},
"name":"Desha"},
"Bradley":
{"votes":[
{"votes":1099,"name":"clinton"},
{"votes":447,"name":"obama"},
{"votes":41,"name":"edwards"},
{"votes":28,"name":"uncommitted-d"},
{"votes":8,"name":"gravel"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":1634,"precincts":
{"total":16,"reporting":16},
"name":"Bradley"},
"Logan":
{"votes":[
{"votes":2117,"name":"clinton"},
{"votes":321,"name":"obama"},
{"votes":80,"name":"edwards"},
{"votes":48,"name":"uncommitted-d"},
{"votes":15,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":5,"name":"gravel"}],
"total":2599,"precincts":
{"total":38,"reporting":38},
"name":"Logan"},
"Prairie":
{"votes":[
{"votes":1101,"name":"clinton"},
{"votes":163,"name":"obama"},
{"votes":38,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":1323,"precincts":
{"total":9,"reporting":9},
"name":"Prairie"},
"Marion":
{"votes":[
{"votes":1201,"name":"clinton"},
{"votes":473,"name":"obama"},
{"votes":63,"name":"edwards"},
{"votes":20,"name":"uncommitted-d"},
{"votes":5,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"biden"}],
"total":1769,"precincts":
{"total":35,"reporting":35},
"name":"Marion"},
"Cleveland":
{"votes":[
{"votes":1116,"name":"clinton"},
{"votes":136,"name":"obama"},
{"votes":27,"name":"uncommitted-d"},
{"votes":27,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"}],
"total":1322,"precincts":
{"total":19,"reporting":19},
"name":"Cleveland"},
"Sharp":
{"votes":[
{"votes":2065,"name":"clinton"},
{"votes":316,"name":"obama"},
{"votes":62,"name":"edwards"},
{"votes":29,"name":"uncommitted-d"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"dodd"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"gravel"}],
"total":2499,"precincts":
{"total":26,"reporting":26},
"name":"Sharp"},
"Chicot":
{"votes":[
{"votes":758,"name":"clinton"},
{"votes":681,"name":"obama"},
{"votes":28,"name":"uncommitted-d"},
{"votes":26,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":1506,"precincts":
{"total":13,"reporting":13},
"name":"Chicot"},
"Nevada":
{"votes":[
{"votes":887,"name":"clinton"},
{"votes":407,"name":"obama"},
{"votes":35,"name":"edwards"},
{"votes":12,"name":"uncommitted-d"},
{"votes":9,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":1364,"precincts":
{"total":21,"reporting":21},
"name":"Nevada"},
"Randolph":
{"votes":[
{"votes":2224,"name":"clinton"},
{"votes":221,"name":"obama"},
{"votes":65,"name":"edwards"},
{"votes":31,"name":"uncommitted-d"},
{"votes":11,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":2565,"precincts":
{"total":29,"reporting":29},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":887,"name":"clinton"},
{"votes":473,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":16,"name":"uncommitted-d"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":1407,"precincts":
{"total":40,"reporting":40},
"name":"Monroe"}}})