GoogleElectionMap.votesReady({"status":"ok","totals":
{"date":"02-05","votes":[
{"votes":2133975,"name":"clinton"},
{"votes":1737807,"name":"obama"},
{"votes":170050,"name":"edwards"},
{"votes":20216,"name":"kucinich"},
{"votes":16964,"name":"richardson"},
{"votes":15474,"name":"biden"},
{"votes":6734,"name":"dodd"},
{"votes":6670,"name":"gravel"}],
"precincts":
{"total":23109,"reporting":23109},
"name":"California"},
"state":"CA","party":"dem","total":4107890,"locals":
{"Fresno":
{"votes":[
{"votes":34320,"name":"clinton"},
{"votes":19352,"name":"obama"},
{"votes":3442,"name":"edwards"},
{"votes":454,"name":"richardson"},
{"votes":265,"name":"kucinich"},
{"votes":226,"name":"biden"},
{"votes":146,"name":"gravel"},
{"votes":86,"name":"dodd"}],
"total":58291,"precincts":
{"total":558,"reporting":558},
"name":"Fresno"},
"Santa Clara":
{"votes":[
{"votes":113032,"name":"clinton"},
{"votes":80946,"name":"obama"},
{"votes":9388,"name":"edwards"},
{"votes":1072,"name":"kucinich"},
{"votes":837,"name":"richardson"},
{"votes":689,"name":"biden"},
{"votes":254,"name":"gravel"},
{"votes":177,"name":"dodd"}],
"total":206395,"precincts":
{"total":929,"reporting":929},
"name":"Santa Clara"},
"Lake":
{"votes":[
{"votes":4789,"name":"clinton"},
{"votes":3083,"name":"obama"},
{"votes":624,"name":"edwards"},
{"votes":97,"name":"kucinich"},
{"votes":42,"name":"richardson"},
{"votes":36,"name":"biden"},
{"votes":13,"name":"gravel"},
{"votes":10,"name":"dodd"}],
"total":8694,"precincts":
{"total":52,"reporting":52},
"name":"Lake"},
"Imperial":
{"votes":[
{"votes":5355,"name":"clinton"},
{"votes":2192,"name":"obama"},
{"votes":272,"name":"edwards"},
{"votes":48,"name":"richardson"},
{"votes":38,"name":"kucinich"},
{"votes":31,"name":"biden"},
{"votes":20,"name":"gravel"},
{"votes":17,"name":"dodd"}],
"total":7973,"precincts":
{"total":94,"reporting":94},
"name":"Imperial"},
"Sierra":
{"votes":[
{"votes":245,"name":"obama"},
{"votes":200,"name":"clinton"},
{"votes":73,"name":"edwards"},
{"votes":10,"name":"kucinich"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":0,"name":"gravel"}],
"total":541,"precincts":
{"total":22,"reporting":22},
"name":"Sierra"},
"Madera":
{"votes":[
{"votes":6020,"name":"clinton"},
{"votes":3592,"name":"obama"},
{"votes":885,"name":"edwards"},
{"votes":93,"name":"richardson"},
{"votes":75,"name":"kucinich"},
{"votes":48,"name":"biden"},
{"votes":34,"name":"gravel"},
{"votes":27,"name":"dodd"}],
"total":10774,"precincts":
{"total":112,"reporting":112},
"name":"Madera"},
"Plumas":
{"votes":[
{"votes":1517,"name":"obama"},
{"votes":1333,"name":"clinton"},
{"votes":357,"name":"edwards"},
{"votes":28,"name":"kucinich"},
{"votes":23,"name":"richardson"},
{"votes":17,"name":"biden"},
{"votes":8,"name":"gravel"},
{"votes":6,"name":"dodd"}],
"total":3289,"precincts":
{"total":29,"reporting":29},
"name":"Plumas"},
"Tuolumne":
{"votes":[
{"votes":3759,"name":"clinton"},
{"votes":2940,"name":"obama"},
{"votes":748,"name":"edwards"},
{"votes":69,"name":"richardson"},
{"votes":67,"name":"kucinich"},
{"votes":39,"name":"biden"},
{"votes":16,"name":"gravel"},
{"votes":10,"name":"dodd"}],
"total":7648,"precincts":
{"total":69,"reporting":69},
"name":"Tuolumne"},
"Napa":
{"votes":[
{"votes":8629,"name":"clinton"},
{"votes":6807,"name":"obama"},
{"votes":1171,"name":"edwards"},
{"votes":106,"name":"kucinich"},
{"votes":97,"name":"richardson"},
{"votes":90,"name":"biden"},
{"votes":32,"name":"gravel"},
{"votes":19,"name":"dodd"}],
"total":16951,"precincts":
{"total":143,"reporting":143},
"name":"Napa"},
"Tulare":
{"votes":[
{"votes":13553,"name":"clinton"},
{"votes":6795,"name":"obama"},
{"votes":1618,"name":"edwards"},
{"votes":174,"name":"richardson"},
{"votes":116,"name":"biden"},
{"votes":102,"name":"gravel"},
{"votes":81,"name":"kucinich"},
{"votes":54,"name":"dodd"}],
"total":22493,"precincts":
{"total":180,"reporting":180},
"name":"Tulare"},
"Orange":
{"votes":[
{"votes":141668,"name":"clinton"},
{"votes":96967,"name":"obama"},
{"votes":12597,"name":"edwards"},
{"votes":1287,"name":"richardson"},
{"votes":1212,"name":"kucinich"},
{"votes":1055,"name":"biden"},
{"votes":437,"name":"gravel"},
{"votes":419,"name":"dodd"}],
"total":255642,"precincts":
{"total":2076,"reporting":2076},
"name":"Orange"},
"San Francisco":
{"votes":[
{"votes":92098,"name":"obama"},
{"votes":78744,"name":"clinton"},
{"votes":4126,"name":"edwards"},
{"votes":1174,"name":"kucinich"},
{"votes":359,"name":"biden"},
{"votes":285,"name":"richardson"},
{"votes":218,"name":"gravel"},
{"votes":84,"name":"dodd"}],
"total":177088,"precincts":
{"total":580,"reporting":580},
"name":"San Francisco"},
"Riverside":
{"votes":[
{"votes":80587,"name":"clinton"},
{"votes":46987,"name":"obama"},
{"votes":7208,"name":"edwards"},
{"votes":744,"name":"richardson"},
{"votes":544,"name":"biden"},
{"votes":529,"name":"kucinich"},
{"votes":270,"name":"gravel"},
{"votes":213,"name":"dodd"}],
"total":137082,"precincts":
{"total":1194,"reporting":1194},
"name":"Riverside"},
"Alameda":
{"votes":[
{"votes":118227,"name":"obama"},
{"votes":103848,"name":"clinton"},
{"votes":8240,"name":"edwards"},
{"votes":1334,"name":"kucinich"},
{"votes":591,"name":"richardson"},
{"votes":549,"name":"biden"},
{"votes":261,"name":"gravel"},
{"votes":194,"name":"dodd"}],
"total":233244,"precincts":
{"total":1204,"reporting":1204},
"name":"Alameda"},
"San Mateo":
{"votes":[
{"votes":49963,"name":"clinton"},
{"votes":42267,"name":"obama"},
{"votes":3840,"name":"edwards"},
{"votes":435,"name":"kucinich"},
{"votes":317,"name":"biden"},
{"votes":241,"name":"richardson"},
{"votes":122,"name":"gravel"},
{"votes":98,"name":"dodd"}],
"total":97283,"precincts":
{"total":553,"reporting":553},
"name":"San Mateo"},
"Trinity":
{"votes":[
{"votes":841,"name":"obama"},
{"votes":732,"name":"clinton"},
{"votes":203,"name":"edwards"},
{"votes":35,"name":"kucinich"},
{"votes":9,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"gravel"},
{"votes":0,"name":"dodd"}],
"total":1830,"precincts":
{"total":24,"reporting":24},
"name":"Trinity"},
"Solano":
{"votes":[
{"votes":25956,"name":"clinton"},
{"votes":23706,"name":"obama"},
{"votes":2828,"name":"edwards"},
{"votes":229,"name":"richardson"},
{"votes":202,"name":"kucinich"},
{"votes":186,"name":"biden"},
{"votes":61,"name":"gravel"},
{"votes":53,"name":"dodd"}],
"total":53221,"precincts":
{"total":189,"reporting":189},
"name":"Solano"},
"Sacramento":
{"votes":[
{"votes":71271,"name":"obama"},
{"votes":68675,"name":"clinton"},
{"votes":6487,"name":"edwards"},
{"votes":666,"name":"kucinich"},
{"votes":594,"name":"richardson"},
{"votes":463,"name":"biden"},
{"votes":250,"name":"gravel"},
{"votes":177,"name":"dodd"}],
"total":148583,"precincts":
{"total":1218,"reporting":1218},
"name":"Sacramento"},
"San Diego":
{"votes":[
{"votes":156630,"name":"clinton"},
{"votes":134813,"name":"obama"},
{"votes":14376,"name":"edwards"},
{"votes":1463,"name":"kucinich"},
{"votes":1404,"name":"richardson"},
{"votes":1151,"name":"biden"},
{"votes":516,"name":"gravel"},
{"votes":360,"name":"dodd"}],
"total":310713,"precincts":
{"total":1801,"reporting":1801},
"name":"San Diego"},
"Colusa":
{"votes":[
{"votes":964,"name":"clinton"},
{"votes":576,"name":"obama"},
{"votes":139,"name":"edwards"},
{"votes":24,"name":"richardson"},
{"votes":10,"name":"biden"},
{"votes":8,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":1730,"precincts":
{"total":18,"reporting":18},
"name":"Colusa"},
"Marin":
{"votes":[
{"votes":32076,"name":"obama"},
{"votes":22517,"name":"clinton"},
{"votes":2801,"name":"edwards"},
{"votes":476,"name":"kucinich"},
{"votes":186,"name":"biden"},
{"votes":137,"name":"richardson"},
{"votes":64,"name":"gravel"},
{"votes":37,"name":"dodd"}],
"total":58294,"precincts":
{"total":183,"reporting":183},
"name":"Marin"},
"Santa Cruz":
{"votes":[
{"votes":27881,"name":"obama"},
{"votes":20742,"name":"clinton"},
{"votes":1730,"name":"edwards"},
{"votes":509,"name":"kucinich"},
{"votes":141,"name":"biden"},
{"votes":103,"name":"richardson"},
{"votes":82,"name":"gravel"},
{"votes":42,"name":"dodd"}],
"total":51230,"precincts":
{"total":192,"reporting":192},
"name":"Santa Cruz"},
"Amador":
{"votes":[
{"votes":2948,"name":"clinton"},
{"votes":2165,"name":"obama"},
{"votes":521,"name":"edwards"},
{"votes":61,"name":"kucinich"},
{"votes":47,"name":"richardson"},
{"votes":43,"name":"biden"},
{"votes":25,"name":"gravel"},
{"votes":16,"name":"dodd"}],
"total":5826,"precincts":
{"total":59,"reporting":59},
"name":"Amador"},
"Los Angeles":
{"votes":[
{"votes":658937,"name":"clinton"},
{"votes":496192,"name":"obama"},
{"votes":25135,"name":"edwards"},
{"votes":4968,"name":"biden"},
{"votes":3925,"name":"richardson"},
{"votes":3869,"name":"kucinich"},
{"votes":3081,"name":"dodd"},
{"votes":1678,"name":"gravel"}],
"total":1197785,"precincts":
{"total":4766,"reporting":4766},
"name":"Los Angeles"},
"Modoc":
{"votes":[
{"votes":478,"name":"clinton"},
{"votes":424,"name":"obama"},
{"votes":126,"name":"edwards"},
{"votes":16,"name":"richardson"},
{"votes":9,"name":"gravel"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"kucinich"}],
"total":1063,"precincts":
{"total":20,"reporting":20},
"name":"Modoc"},
"Lassen":
{"votes":[
{"votes":1111,"name":"clinton"},
{"votes":1107,"name":"obama"},
{"votes":355,"name":"edwards"},
{"votes":36,"name":"richardson"},
{"votes":21,"name":"kucinich"},
{"votes":19,"name":"biden"},
{"votes":8,"name":"dodd"},
{"votes":8,"name":"gravel"}],
"total":2665,"precincts":
{"total":36,"reporting":36},
"name":"Lassen"},
"Butte":
{"votes":[
{"votes":11550,"name":"clinton"},
{"votes":11324,"name":"obama"},
{"votes":2163,"name":"edwards"},
{"votes":208,"name":"kucinich"},
{"votes":155,"name":"richardson"},
{"votes":150,"name":"biden"},
{"votes":84,"name":"gravel"},
{"votes":69,"name":"dodd"}],
"total":25703,"precincts":
{"total":152,"reporting":152},
"name":"Butte"},
"Stanislaus":
{"votes":[
{"votes":23452,"name":"clinton"},
{"votes":12136,"name":"obama"},
{"votes":2790,"name":"edwards"},
{"votes":254,"name":"richardson"},
{"votes":164,"name":"kucinich"},
{"votes":142,"name":"biden"},
{"votes":97,"name":"gravel"},
{"votes":69,"name":"dodd"}],
"total":39104,"precincts":
{"total":413,"reporting":413},
"name":"Stanislaus"},
"Alpine":
{"votes":[
{"votes":127,"name":"obama"},
{"votes":87,"name":"clinton"},
{"votes":10,"name":"edwards"},
{"votes":8,"name":"kucinich"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"gravel"}],
"total":232,"precincts":
{"total":5,"reporting":5},
"name":"Alpine"},
"Shasta":
{"votes":[
{"votes":8636,"name":"clinton"},
{"votes":7027,"name":"obama"},
{"votes":2081,"name":"edwards"},
{"votes":169,"name":"richardson"},
{"votes":117,"name":"biden"},
{"votes":96,"name":"kucinich"},
{"votes":75,"name":"gravel"},
{"votes":63,"name":"dodd"}],
"total":18264,"precincts":
{"total":147,"reporting":147},
"name":"Shasta"},
"Siskiyou":
{"votes":[
{"votes":2786,"name":"obama"},
{"votes":2248,"name":"clinton"},
{"votes":526,"name":"edwards"},
{"votes":77,"name":"kucinich"},
{"votes":48,"name":"richardson"},
{"votes":34,"name":"gravel"},
{"votes":32,"name":"biden"},
{"votes":14,"name":"dodd"}],
"total":5765,"precincts":
{"total":61,"reporting":61},
"name":"Siskiyou"},
"Placer":
{"votes":[
{"votes":19786,"name":"clinton"},
{"votes":17325,"name":"obama"},
{"votes":3126,"name":"edwards"},
{"votes":221,"name":"biden"},
{"votes":194,"name":"richardson"},
{"votes":180,"name":"kucinich"},
{"votes":83,"name":"dodd"},
{"votes":67,"name":"gravel"}],
"total":40982,"precincts":
{"total":345,"reporting":345},
"name":"Placer"},
"Mono":
{"votes":[
{"votes":880,"name":"obama"},
{"votes":605,"name":"clinton"},
{"votes":97,"name":"edwards"},
{"votes":9,"name":"richardson"},
{"votes":9,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":1614,"precincts":
{"total":13,"reporting":13},
"name":"Mono"},
"Contra Costa":
{"votes":[
{"votes":82978,"name":"clinton"},
{"votes":73532,"name":"obama"},
{"votes":7475,"name":"edwards"},
{"votes":794,"name":"kucinich"},
{"votes":591,"name":"richardson"},
{"votes":540,"name":"biden"},
{"votes":208,"name":"gravel"},
{"votes":180,"name":"dodd"}],
"total":166298,"precincts":
{"total":816,"reporting":816},
"name":"Contra Costa"},
"Del Norte":
{"votes":[
{"votes":1277,"name":"clinton"},
{"votes":1048,"name":"obama"},
{"votes":243,"name":"edwards"},
{"votes":23,"name":"kucinich"},
{"votes":20,"name":"gravel"},
{"votes":16,"name":"richardson"},
{"votes":10,"name":"dodd"},
{"votes":8,"name":"biden"}],
"total":2645,"precincts":
{"total":18,"reporting":18},
"name":"Del Norte"},
"Sutter":
{"votes":[
{"votes":3537,"name":"clinton"},
{"votes":2289,"name":"obama"},
{"votes":543,"name":"edwards"},
{"votes":36,"name":"richardson"},
{"votes":29,"name":"gravel"},
{"votes":28,"name":"biden"},
{"votes":17,"name":"kucinich"},
{"votes":15,"name":"dodd"}],
"total":6494,"precincts":
{"total":58,"reporting":58},
"name":"Sutter"},
"Kern":
{"votes":[
{"votes":30615,"name":"clinton"},
{"votes":17535,"name":"obama"},
{"votes":4042,"name":"edwards"},
{"votes":583,"name":"richardson"},
{"votes":259,"name":"biden"},
{"votes":222,"name":"kucinich"},
{"votes":130,"name":"gravel"},
{"votes":87,"name":"dodd"}],
"total":53473,"precincts":
{"total":444,"reporting":444},
"name":"Kern"},
"Ventura":
{"votes":[
{"votes":50903,"name":"clinton"},
{"votes":38069,"name":"obama"},
{"votes":4136,"name":"edwards"},
{"votes":434,"name":"kucinich"},
{"votes":367,"name":"richardson"},
{"votes":352,"name":"biden"},
{"votes":145,"name":"dodd"},
{"votes":145,"name":"gravel"}],
"total":94551,"precincts":
{"total":578,"reporting":578},
"name":"Ventura"},
"Kings":
{"votes":[
{"votes":5182,"name":"clinton"},
{"votes":2725,"name":"obama"},
{"votes":627,"name":"edwards"},
{"votes":76,"name":"richardson"},
{"votes":52,"name":"biden"},
{"votes":31,"name":"kucinich"},
{"votes":20,"name":"dodd"},
{"votes":20,"name":"gravel"}],
"total":8733,"precincts":
{"total":178,"reporting":178},
"name":"Kings"},
"Inyo":
{"votes":[
{"votes":911,"name":"clinton"},
{"votes":839,"name":"obama"},
{"votes":206,"name":"edwards"},
{"votes":26,"name":"kucinich"},
{"votes":23,"name":"richardson"},
{"votes":11,"name":"biden"},
{"votes":8,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":2026,"precincts":
{"total":25,"reporting":25},
"name":"Inyo"},
"San Bernardino":
{"votes":[
{"votes":90931,"name":"clinton"},
{"votes":53209,"name":"obama"},
{"votes":7268,"name":"edwards"},
{"votes":883,"name":"richardson"},
{"votes":666,"name":"biden"},
{"votes":512,"name":"kucinich"},
{"votes":279,"name":"gravel"},
{"votes":264,"name":"dodd"}],
"total":154012,"precincts":
{"total":991,"reporting":991},
"name":"San Bernardino"},
"Monterey":
{"votes":[
{"votes":19819,"name":"clinton"},
{"votes":13900,"name":"obama"},
{"votes":1878,"name":"edwards"},
{"votes":220,"name":"kucinich"},
{"votes":148,"name":"richardson"},
{"votes":120,"name":"biden"},
{"votes":58,"name":"gravel"},
{"votes":48,"name":"dodd"}],
"total":36191,"precincts":
{"total":184,"reporting":184},
"name":"Monterey"},
"Sonoma":
{"votes":[
{"votes":44020,"name":"obama"},
{"votes":40709,"name":"clinton"},
{"votes":5767,"name":"edwards"},
{"votes":1006,"name":"kucinich"},
{"votes":365,"name":"biden"},
{"votes":326,"name":"richardson"},
{"votes":130,"name":"gravel"},
{"votes":87,"name":"dodd"}],
"total":92410,"precincts":
{"total":452,"reporting":452},
"name":"Sonoma"},
"San Joaquin":
{"votes":[
{"votes":32271,"name":"clinton"},
{"votes":20141,"name":"obama"},
{"votes":2865,"name":"edwards"},
{"votes":300,"name":"richardson"},
{"votes":208,"name":"biden"},
{"votes":162,"name":"kucinich"},
{"votes":127,"name":"gravel"},
{"votes":58,"name":"dodd"}],
"total":56132,"precincts":
{"total":434,"reporting":434},
"name":"San Joaquin"},
"Humboldt":
{"votes":[
{"votes":9887,"name":"obama"},
{"votes":7082,"name":"clinton"},
{"votes":954,"name":"edwards"},
{"votes":289,"name":"kucinich"},
{"votes":94,"name":"richardson"},
{"votes":68,"name":"biden"},
{"votes":61,"name":"gravel"},
{"votes":8,"name":"dodd"}],
"total":18443,"precincts":
{"total":132,"reporting":132},
"name":"Humboldt"},
"Glenn":
{"votes":[
{"votes":1361,"name":"clinton"},
{"votes":916,"name":"obama"},
{"votes":350,"name":"edwards"},
{"votes":32,"name":"richardson"},
{"votes":18,"name":"biden"},
{"votes":16,"name":"kucinich"},
{"votes":7,"name":"dodd"},
{"votes":5,"name":"gravel"}],
"total":2705,"precincts":
{"total":30,"reporting":30},
"name":"Glenn"},
"Merced":
{"votes":[
{"votes":11332,"name":"clinton"},
{"votes":6347,"name":"obama"},
{"votes":1050,"name":"edwards"},
{"votes":151,"name":"richardson"},
{"votes":71,"name":"biden"},
{"votes":71,"name":"kucinich"},
{"votes":67,"name":"gravel"},
{"votes":34,"name":"dodd"}],
"total":19123,"precincts":
{"total":117,"reporting":117},
"name":"Merced"},
"Yolo":
{"votes":[
{"votes":14561,"name":"obama"},
{"votes":13873,"name":"clinton"},
{"votes":1321,"name":"edwards"},
{"votes":191,"name":"kucinich"},
{"votes":130,"name":"richardson"},
{"votes":83,"name":"biden"},
{"votes":60,"name":"gravel"},
{"votes":29,"name":"dodd"}],
"total":30248,"precincts":
{"total":146,"reporting":146},
"name":"Yolo"},
"Mariposa":
{"votes":[
{"votes":1164,"name":"clinton"},
{"votes":1041,"name":"obama"},
{"votes":278,"name":"edwards"},
{"votes":26,"name":"kucinich"},
{"votes":15,"name":"biden"},
{"votes":12,"name":"richardson"},
{"votes":9,"name":"gravel"},
{"votes":6,"name":"dodd"}],
"total":2551,"precincts":
{"total":21,"reporting":21},
"name":"Mariposa"},
"Yuba":
{"votes":[
{"votes":2282,"name":"clinton"},
{"votes":1577,"name":"obama"},
{"votes":398,"name":"edwards"},
{"votes":28,"name":"biden"},
{"votes":28,"name":"richardson"},
{"votes":25,"name":"kucinich"},
{"votes":21,"name":"dodd"},
{"votes":12,"name":"gravel"}],
"total":4371,"precincts":
{"total":46,"reporting":46},
"name":"Yuba"},
"El Dorado":
{"votes":[
{"votes":9378,"name":"clinton"},
{"votes":8752,"name":"obama"},
{"votes":1667,"name":"edwards"},
{"votes":135,"name":"richardson"},
{"votes":116,"name":"kucinich"},
{"votes":95,"name":"biden"},
{"votes":49,"name":"dodd"},
{"votes":37,"name":"gravel"}],
"total":20229,"precincts":
{"total":117,"reporting":117},
"name":"El Dorado"},
"San Luis Obispo":
{"votes":[
{"votes":17201,"name":"obama"},
{"votes":14780,"name":"clinton"},
{"votes":2628,"name":"edwards"},
{"votes":441,"name":"kucinich"},
{"votes":198,"name":"richardson"},
{"votes":123,"name":"biden"},
{"votes":59,"name":"gravel"},
{"votes":31,"name":"dodd"}],
"total":35461,"precincts":
{"total":140,"reporting":140},
"name":"San Luis Obispo"},
"Mendocino":
{"votes":[
{"votes":4809,"name":"obama"},
{"votes":4615,"name":"clinton"},
{"votes":931,"name":"edwards"},
{"votes":303,"name":"kucinich"},
{"votes":58,"name":"richardson"},
{"votes":51,"name":"biden"},
{"votes":18,"name":"gravel"},
{"votes":9,"name":"dodd"}],
"total":10794,"precincts":
{"total":235,"reporting":235},
"name":"Mendocino"},
"San Benito":
{"votes":[
{"votes":3829,"name":"clinton"},
{"votes":2087,"name":"obama"},
{"votes":279,"name":"edwards"},
{"votes":30,"name":"biden"},
{"votes":27,"name":"kucinich"},
{"votes":26,"name":"richardson"},
{"votes":11,"name":"gravel"},
{"votes":8,"name":"dodd"}],
"total":6297,"precincts":
{"total":56,"reporting":56},
"name":"San Benito"},
"Tehama":
{"votes":[
{"votes":2735,"name":"clinton"},
{"votes":1691,"name":"obama"},
{"votes":730,"name":"edwards"},
{"votes":52,"name":"richardson"},
{"votes":44,"name":"biden"},
{"votes":31,"name":"kucinich"},
{"votes":31,"name":"gravel"},
{"votes":16,"name":"dodd"}],
"total":5330,"precincts":
{"total":47,"reporting":47},
"name":"Tehama"},
"Calaveras":
{"votes":[
{"votes":2895,"name":"clinton"},
{"votes":2171,"name":"obama"},
{"votes":541,"name":"edwards"},
{"votes":50,"name":"richardson"},
{"votes":46,"name":"kucinich"},
{"votes":28,"name":"biden"},
{"votes":19,"name":"gravel"},
{"votes":8,"name":"dodd"}],
"total":5758,"precincts":
{"total":30,"reporting":30},
"name":"Calaveras"},
"Nevada":
{"votes":[
{"votes":6413,"name":"obama"},
{"votes":5206,"name":"clinton"},
{"votes":1106,"name":"edwards"},
{"votes":149,"name":"kucinich"},
{"votes":64,"name":"richardson"},
{"votes":48,"name":"biden"},
{"votes":26,"name":"dodd"},
{"votes":26,"name":"gravel"}],
"total":13038,"precincts":
{"total":63,"reporting":63},
"name":"Nevada"},
"Santa Barbara":
{"votes":[
{"votes":26375,"name":"obama"},
{"votes":22456,"name":"clinton"},
{"votes":2684,"name":"edwards"},
{"votes":461,"name":"kucinich"},
{"votes":240,"name":"richardson"},
{"votes":196,"name":"biden"},
{"votes":104,"name":"gravel"},
{"votes":64,"name":"dodd"}],
"total":52580,"precincts":
{"total":314,"reporting":314},
"name":"Santa Barbara"}}})