GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":856944,"name":"clinton","delegates":52},
{"votes":568930,"name":"obama","delegates":33},
{"votes":248575,"name":"edwards"},
{"votes":15426,"name":"biden"},
{"votes":14782,"name":"richardson"},
{"votes":9535,"name":"kucinich"},
{"votes":5402,"name":"dodd"},
{"votes":5261,"name":"gravel"}],
"name":"Florida","precincts":
{"total":6913,"reporting":6900},
"delegates":92,"date":"01-29"},
"state":"FL","party":"dem","total":1724855,"locals":
{"Alachua":
{"votes":[
{"votes":14638,"name":"obama"},
{"votes":11681,"name":"clinton"},
{"votes":5310,"name":"edwards"},
{"votes":389,"name":"richardson"},
{"votes":361,"name":"kucinich"},
{"votes":288,"name":"biden"},
{"votes":132,"name":"gravel"},
{"votes":99,"name":"dodd"}],
"total":32898,"precincts":
{"total":69,"reporting":69},
"name":"Alachua"},
"Okaloosa":
{"votes":[
{"votes":3806,"name":"clinton"},
{"votes":3642,"name":"obama"},
{"votes":2380,"name":"edwards"},
{"votes":198,"name":"richardson"},
{"votes":133,"name":"biden"},
{"votes":84,"name":"kucinich"},
{"votes":54,"name":"dodd"},
{"votes":46,"name":"gravel"}],
"total":10343,"precincts":
{"total":52,"reporting":52},
"name":"Okaloosa"},
"Jackson":
{"votes":[
{"votes":2466,"name":"edwards"},
{"votes":2372,"name":"obama"},
{"votes":2308,"name":"clinton"},
{"votes":192,"name":"richardson"},
{"votes":120,"name":"biden"},
{"votes":74,"name":"dodd"},
{"votes":73,"name":"kucinich"},
{"votes":66,"name":"gravel"}],
"total":7671,"precincts":
{"total":25,"reporting":25},
"name":"Jackson"},
"Seminole":
{"votes":[
{"votes":16545,"name":"clinton"},
{"votes":11631,"name":"obama"},
{"votes":4651,"name":"edwards"},
{"votes":222,"name":"biden"},
{"votes":203,"name":"richardson"},
{"votes":186,"name":"kucinich"},
{"votes":79,"name":"dodd"},
{"votes":72,"name":"gravel"}],
"total":33589,"precincts":
{"total":126,"reporting":126},
"name":"Seminole"},
"Gulf":
{"votes":[
{"votes":745,"name":"edwards"},
{"votes":731,"name":"clinton"},
{"votes":495,"name":"obama"},
{"votes":59,"name":"richardson"},
{"votes":45,"name":"biden"},
{"votes":26,"name":"gravel"},
{"votes":15,"name":"kucinich"},
{"votes":14,"name":"dodd"}],
"total":2130,"precincts":
{"total":8,"reporting":8},
"name":"Gulf"},
"Union":
{"votes":[
{"votes":616,"name":"edwards"},
{"votes":447,"name":"clinton"},
{"votes":263,"name":"obama"},
{"votes":45,"name":"richardson"},
{"votes":24,"name":"biden"},
{"votes":24,"name":"gravel"},
{"votes":16,"name":"dodd"},
{"votes":15,"name":"kucinich"}],
"total":1450,"precincts":
{"total":11,"reporting":11},
"name":"Union"},
"Volusia":
{"votes":[
{"votes":26635,"name":"clinton"},
{"votes":13353,"name":"obama"},
{"votes":9205,"name":"edwards"},
{"votes":340,"name":"biden"},
{"votes":319,"name":"richardson"},
{"votes":240,"name":"kucinich"},
{"votes":136,"name":"gravel"},
{"votes":122,"name":"dodd"}],
"total":50350,"precincts":
{"total":179,"reporting":172},
"name":"Volusia"},
"Duval":
{"votes":[
{"votes":40830,"name":"obama"},
{"votes":27238,"name":"clinton"},
{"votes":12125,"name":"edwards"},
{"votes":798,"name":"richardson"},
{"votes":678,"name":"biden"},
{"votes":416,"name":"kucinich"},
{"votes":275,"name":"dodd"},
{"votes":258,"name":"gravel"}],
"total":82618,"precincts":
{"total":303,"reporting":303},
"name":"Duval"},
"Sumter":
{"votes":[
{"votes":5598,"name":"clinton"},
{"votes":2151,"name":"obama"},
{"votes":2121,"name":"edwards"},
{"votes":143,"name":"biden"},
{"votes":122,"name":"richardson"},
{"votes":59,"name":"kucinich"},
{"votes":56,"name":"dodd"},
{"votes":31,"name":"gravel"}],
"total":10281,"precincts":
{"total":42,"reporting":42},
"name":"Sumter"},
"Lake":
{"votes":[
{"votes":14939,"name":"clinton"},
{"votes":6784,"name":"obama"},
{"votes":4752,"name":"edwards"},
{"votes":273,"name":"biden"},
{"votes":220,"name":"richardson"},
{"votes":120,"name":"kucinich"},
{"votes":76,"name":"dodd"},
{"votes":73,"name":"gravel"}],
"total":27237,"precincts":
{"total":102,"reporting":102},
"name":"Lake"},
"Liberty":
{"votes":[
{"votes":459,"name":"edwards"},
{"votes":397,"name":"clinton"},
{"votes":170,"name":"obama"},
{"votes":45,"name":"richardson"},
{"votes":17,"name":"gravel"},
{"votes":12,"name":"biden"},
{"votes":8,"name":"kucinich"},
{"votes":6,"name":"dodd"}],
"total":1114,"precincts":
{"total":8,"reporting":8},
"name":"Liberty"},
"Hillsborough":
{"votes":[
{"votes":42993,"name":"clinton"},
{"votes":36151,"name":"obama"},
{"votes":12770,"name":"edwards"},
{"votes":872,"name":"biden"},
{"votes":813,"name":"richardson"},
{"votes":663,"name":"kucinich"},
{"votes":351,"name":"gravel"},
{"votes":338,"name":"dodd"}],
"total":94951,"precincts":
{"total":361,"reporting":361},
"name":"Hillsborough"},
"Flagler":
{"votes":[
{"votes":5235,"name":"clinton"},
{"votes":3022,"name":"obama"},
{"votes":1517,"name":"edwards"},
{"votes":75,"name":"biden"},
{"votes":54,"name":"richardson"},
{"votes":32,"name":"kucinich"},
{"votes":30,"name":"dodd"},
{"votes":17,"name":"gravel"}],
"total":9982,"precincts":
{"total":36,"reporting":36},
"name":"Flagler"},
"Brevard":
{"votes":[
{"votes":31675,"name":"clinton"},
{"votes":18395,"name":"obama"},
{"votes":10620,"name":"edwards"},
{"votes":564,"name":"biden"},
{"votes":552,"name":"richardson"},
{"votes":362,"name":"kucinich"},
{"votes":238,"name":"dodd"},
{"votes":232,"name":"gravel"}],
"total":62638,"precincts":
{"total":216,"reporting":216},
"name":"Brevard"},
"Miami-Dade":
{"votes":[
{"votes":90846,"name":"clinton"},
{"votes":70012,"name":"obama"},
{"votes":11446,"name":"edwards"},
{"votes":1240,"name":"biden"},
{"votes":1039,"name":"richardson"},
{"votes":742,"name":"kucinich"},
{"votes":410,"name":"gravel"},
{"votes":363,"name":"dodd"}],
"total":176098,"precincts":
{"total":744,"reporting":744},
"name":"Miami-Dade"},
"Santa Rosa":
{"votes":[
{"votes":3725,"name":"clinton"},
{"votes":2881,"name":"edwards"},
{"votes":2497,"name":"obama"},
{"votes":177,"name":"richardson"},
{"votes":108,"name":"biden"},
{"votes":61,"name":"kucinich"},
{"votes":46,"name":"dodd"},
{"votes":46,"name":"gravel"}],
"total":9541,"precincts":
{"total":41,"reporting":41},
"name":"Santa Rosa"},
"Orange":
{"votes":[
{"votes":42602,"name":"clinton"},
{"votes":34452,"name":"obama"},
{"votes":9252,"name":"edwards"},
{"votes":510,"name":"biden"},
{"votes":470,"name":"richardson"},
{"votes":370,"name":"kucinich"},
{"votes":221,"name":"gravel"},
{"votes":177,"name":"dodd"}],
"total":88054,"precincts":
{"total":261,"reporting":261},
"name":"Orange"},
"Pasco":
{"votes":[
{"votes":23440,"name":"clinton"},
{"votes":9091,"name":"obama"},
{"votes":5816,"name":"edwards"},
{"votes":380,"name":"biden"},
{"votes":366,"name":"richardson"},
{"votes":247,"name":"kucinich"},
{"votes":147,"name":"dodd"},
{"votes":123,"name":"gravel"}],
"total":39610,"precincts":
{"total":153,"reporting":153},
"name":"Pasco"},
"Indian River":
{"votes":[
{"votes":5751,"name":"clinton"},
{"votes":3116,"name":"obama"},
{"votes":1810,"name":"edwards"},
{"votes":138,"name":"biden"},
{"votes":101,"name":"richardson"},
{"votes":66,"name":"kucinich"},
{"votes":37,"name":"dodd"},
{"votes":37,"name":"gravel"}],
"total":11056,"precincts":
{"total":54,"reporting":54},
"name":"Indian River"},
"Levy":
{"votes":[
{"votes":2235,"name":"clinton"},
{"votes":1653,"name":"edwards"},
{"votes":1230,"name":"obama"},
{"votes":141,"name":"richardson"},
{"votes":100,"name":"biden"},
{"votes":56,"name":"gravel"},
{"votes":44,"name":"kucinich"},
{"votes":40,"name":"dodd"}],
"total":5499,"precincts":
{"total":20,"reporting":20},
"name":"Levy"},
"Hardee":
{"votes":[
{"votes":830,"name":"clinton"},
{"votes":780,"name":"edwards"},
{"votes":363,"name":"obama"},
{"votes":37,"name":"richardson"},
{"votes":34,"name":"biden"},
{"votes":27,"name":"gravel"},
{"votes":16,"name":"dodd"},
{"votes":14,"name":"kucinich"}],
"total":2101,"precincts":
{"total":12,"reporting":12},
"name":"Hardee"},
"Columbia":
{"votes":[
{"votes":2562,"name":"clinton"},
{"votes":2151,"name":"edwards"},
{"votes":1825,"name":"obama"},
{"votes":157,"name":"richardson"},
{"votes":115,"name":"biden"},
{"votes":65,"name":"kucinich"},
{"votes":60,"name":"gravel"},
{"votes":42,"name":"dodd"}],
"total":6977,"precincts":
{"total":25,"reporting":25},
"name":"Columbia"},
"Lee":
{"votes":[
{"votes":23788,"name":"clinton"},
{"votes":10883,"name":"obama"},
{"votes":6669,"name":"edwards"},
{"votes":426,"name":"biden"},
{"votes":265,"name":"richardson"},
{"votes":218,"name":"kucinich"},
{"votes":133,"name":"dodd"},
{"votes":104,"name":"gravel"}],
"total":42486,"precincts":
{"total":173,"reporting":173},
"name":"Lee"},
"Citrus":
{"votes":[
{"votes":9718,"name":"clinton"},
{"votes":3760,"name":"obama"},
{"votes":3529,"name":"edwards"},
{"votes":187,"name":"richardson"},
{"votes":171,"name":"biden"},
{"votes":85,"name":"kucinich"},
{"votes":74,"name":"dodd"},
{"votes":59,"name":"gravel"}],
"total":17583,"precincts":
{"total":41,"reporting":41},
"name":"Citrus"},
"Okeechobee":
{"votes":[
{"votes":2024,"name":"clinton"},
{"votes":1026,"name":"edwards"},
{"votes":610,"name":"obama"},
{"votes":81,"name":"richardson"},
{"votes":37,"name":"biden"},
{"votes":30,"name":"gravel"},
{"votes":28,"name":"dodd"},
{"votes":20,"name":"kucinich"}],
"total":3856,"precincts":
{"total":18,"reporting":18},
"name":"Okeechobee"},
"Manatee":
{"votes":[
{"votes":14369,"name":"clinton"},
{"votes":8455,"name":"obama"},
{"votes":4155,"name":"edwards"},
{"votes":269,"name":"biden"},
{"votes":182,"name":"richardson"},
{"votes":164,"name":"kucinich"},
{"votes":79,"name":"dodd"},
{"votes":74,"name":"gravel"}],
"total":27747,"precincts":
{"total":136,"reporting":136},
"name":"Manatee"},
"Walton":
{"votes":[
{"votes":1567,"name":"clinton"},
{"votes":1088,"name":"edwards"},
{"votes":1021,"name":"obama"},
{"votes":81,"name":"richardson"},
{"votes":44,"name":"biden"},
{"votes":37,"name":"kucinich"},
{"votes":24,"name":"dodd"},
{"votes":24,"name":"gravel"}],
"total":3886,"precincts":
{"total":36,"reporting":36},
"name":"Walton"},
"Hernando":
{"votes":[
{"votes":12495,"name":"clinton"},
{"votes":4496,"name":"obama"},
{"votes":3143,"name":"edwards"},
{"votes":156,"name":"richardson"},
{"votes":147,"name":"biden"},
{"votes":96,"name":"kucinich"},
{"votes":66,"name":"dodd"},
{"votes":53,"name":"gravel"}],
"total":20652,"precincts":
{"total":56,"reporting":56},
"name":"Hernando"},
"Hamilton":
{"votes":[
{"votes":645,"name":"obama"},
{"votes":574,"name":"edwards"},
{"votes":568,"name":"clinton"},
{"votes":45,"name":"biden"},
{"votes":45,"name":"richardson"},
{"votes":22,"name":"gravel"},
{"votes":14,"name":"dodd"},
{"votes":12,"name":"kucinich"}],
"total":1925,"precincts":
{"total":8,"reporting":8},
"name":"Hamilton"},
"Nassau":
{"votes":[
{"votes":2577,"name":"clinton"},
{"votes":1900,"name":"obama"},
{"votes":1638,"name":"edwards"},
{"votes":91,"name":"richardson"},
{"votes":72,"name":"biden"},
{"votes":34,"name":"kucinich"},
{"votes":33,"name":"dodd"},
{"votes":32,"name":"gravel"}],
"total":6377,"precincts":
{"total":21,"reporting":21},
"name":"Nassau"},
"Broward":
{"votes":[
{"votes":106669,"name":"clinton"},
{"votes":61034,"name":"obama"},
{"votes":15981,"name":"edwards"},
{"votes":1298,"name":"biden"},
{"votes":840,"name":"richardson"},
{"votes":824,"name":"kucinich"},
{"votes":375,"name":"dodd"},
{"votes":264,"name":"gravel"}],
"total":187285,"precincts":
{"total":791,"reporting":785},
"name":"Broward"},
"Putnam":
{"votes":[
{"votes":4057,"name":"clinton"},
{"votes":3073,"name":"edwards"},
{"votes":2546,"name":"obama"},
{"votes":228,"name":"richardson"},
{"votes":127,"name":"biden"},
{"votes":83,"name":"kucinich"},
{"votes":74,"name":"gravel"},
{"votes":73,"name":"dodd"}],
"total":10261,"precincts":
{"total":56,"reporting":56},
"name":"Putnam"},
"St. Lucie":
{"votes":[
{"votes":14817,"name":"clinton"},
{"votes":8076,"name":"obama"},
{"votes":3703,"name":"edwards"},
{"votes":267,"name":"biden"},
{"votes":178,"name":"richardson"},
{"votes":119,"name":"kucinich"},
{"votes":96,"name":"dodd"},
{"votes":66,"name":"gravel"}],
"total":27322,"precincts":
{"total":80,"reporting":80},
"name":"St. Lucie"},
"Bradford":
{"votes":[
{"votes":1128,"name":"edwards"},
{"votes":1081,"name":"clinton"},
{"votes":913,"name":"obama"},
{"votes":117,"name":"richardson"},
{"votes":61,"name":"biden"},
{"votes":39,"name":"gravel"},
{"votes":31,"name":"dodd"},
{"votes":29,"name":"kucinich"}],
"total":3399,"precincts":
{"total":19,"reporting":19},
"name":"Bradford"},
"Suwannee":
{"votes":[
{"votes":1962,"name":"edwards"},
{"votes":1693,"name":"clinton"},
{"votes":1051,"name":"obama"},
{"votes":170,"name":"richardson"},
{"votes":110,"name":"biden"},
{"votes":82,"name":"gravel"},
{"votes":54,"name":"kucinich"},
{"votes":49,"name":"dodd"}],
"total":5171,"precincts":
{"total":16,"reporting":16},
"name":"Suwannee"},
"Hendry":
{"votes":[
{"votes":1105,"name":"clinton"},
{"votes":740,"name":"obama"},
{"votes":652,"name":"edwards"},
{"votes":45,"name":"richardson"},
{"votes":32,"name":"biden"},
{"votes":20,"name":"dodd"},
{"votes":19,"name":"kucinich"},
{"votes":12,"name":"gravel"}],
"total":2625,"precincts":
{"total":23,"reporting":23},
"name":"Hendry"},
"Highlands":
{"votes":[
{"votes":4972,"name":"clinton"},
{"votes":2055,"name":"obama"},
{"votes":1898,"name":"edwards"},
{"votes":100,"name":"biden"},
{"votes":98,"name":"richardson"},
{"votes":41,"name":"kucinich"},
{"votes":35,"name":"dodd"},
{"votes":27,"name":"gravel"}],
"total":9226,"precincts":
{"total":25,"reporting":25},
"name":"Highlands"},
"Gadsden":
{"votes":[
{"votes":5287,"name":"obama"},
{"votes":2456,"name":"clinton"},
{"votes":1470,"name":"edwards"},
{"votes":113,"name":"richardson"},
{"votes":102,"name":"biden"},
{"votes":61,"name":"kucinich"},
{"votes":31,"name":"gravel"},
{"votes":28,"name":"dodd"}],
"total":9548,"precincts":
{"total":25,"reporting":25},
"name":"Gadsden"},
"Baker":
{"votes":[
{"votes":1247,"name":"edwards"},
{"votes":833,"name":"clinton"},
{"votes":507,"name":"obama"},
{"votes":105,"name":"richardson"},
{"votes":43,"name":"gravel"},
{"votes":41,"name":"biden"},
{"votes":36,"name":"kucinich"},
{"votes":26,"name":"dodd"}],
"total":2838,"precincts":
{"total":9,"reporting":9},
"name":"Baker"},
"Osceola":
{"votes":[
{"votes":11113,"name":"clinton"},
{"votes":4470,"name":"obama"},
{"votes":2226,"name":"edwards"},
{"votes":101,"name":"richardson"},
{"votes":91,"name":"biden"},
{"votes":57,"name":"kucinich"},
{"votes":46,"name":"dodd"},
{"votes":26,"name":"gravel"}],
"total":18130,"precincts":
{"total":101,"reporting":101},
"name":"Osceola"},
"Gilchrist":
{"votes":[
{"votes":852,"name":"clinton"},
{"votes":788,"name":"edwards"},
{"votes":365,"name":"obama"},
{"votes":64,"name":"richardson"},
{"votes":27,"name":"biden"},
{"votes":25,"name":"kucinich"},
{"votes":22,"name":"gravel"},
{"votes":15,"name":"dodd"}],
"total":2158,"precincts":
{"total":10,"reporting":10},
"name":"Gilchrist"},
"Palm Beach":
{"votes":[
{"votes":82475,"name":"clinton"},
{"votes":38301,"name":"obama"},
{"votes":13024,"name":"edwards"},
{"votes":1221,"name":"biden"},
{"votes":577,"name":"richardson"},
{"votes":536,"name":"kucinich"},
{"votes":355,"name":"dodd"},
{"votes":207,"name":"gravel"}],
"total":136696,"precincts":
{"total":752,"reporting":752},
"name":"Palm Beach"},
"Glades":
{"votes":[
{"votes":646,"name":"clinton"},
{"votes":367,"name":"edwards"},
{"votes":238,"name":"obama"},
{"votes":28,"name":"richardson"},
{"votes":20,"name":"biden"},
{"votes":15,"name":"kucinich"},
{"votes":14,"name":"dodd"},
{"votes":11,"name":"gravel"}],
"total":1339,"precincts":
{"total":13,"reporting":13},
"name":"Glades"},
"Franklin":
{"votes":[
{"votes":889,"name":"clinton"},
{"votes":639,"name":"edwards"},
{"votes":545,"name":"obama"},
{"votes":56,"name":"richardson"},
{"votes":42,"name":"biden"},
{"votes":18,"name":"kucinich"},
{"votes":17,"name":"gravel"},
{"votes":12,"name":"dodd"}],
"total":2218,"precincts":
{"total":8,"reporting":8},
"name":"Franklin"},
"Pinellas":
{"votes":[
{"votes":48393,"name":"clinton"},
{"votes":30944,"name":"obama"},
{"votes":10777,"name":"edwards"},
{"votes":886,"name":"biden"},
{"votes":622,"name":"richardson"},
{"votes":619,"name":"kucinich"},
{"votes":273,"name":"dodd"},
{"votes":245,"name":"gravel"}],
"total":92759,"precincts":
{"total":371,"reporting":371},
"name":"Pinellas"},
"Martin":
{"votes":[
{"votes":6457,"name":"clinton"},
{"votes":3505,"name":"obama"},
{"votes":1831,"name":"edwards"},
{"votes":168,"name":"biden"},
{"votes":114,"name":"richardson"},
{"votes":86,"name":"kucinich"},
{"votes":46,"name":"dodd"},
{"votes":27,"name":"gravel"}],
"total":12234,"precincts":
{"total":53,"reporting":53},
"name":"Martin"},
"Calhoun":
{"votes":[
{"votes":875,"name":"clinton"},
{"votes":848,"name":"edwards"},
{"votes":407,"name":"obama"},
{"votes":80,"name":"richardson"},
{"votes":29,"name":"biden"},
{"votes":24,"name":"kucinich"},
{"votes":23,"name":"gravel"},
{"votes":12,"name":"dodd"}],
"total":2298,"precincts":
{"total":18,"reporting":18},
"name":"Calhoun"},
"Monroe":
{"votes":[
{"votes":4176,"name":"clinton"},
{"votes":2478,"name":"obama"},
{"votes":1201,"name":"edwards"},
{"votes":72,"name":"biden"},
{"votes":65,"name":"kucinich"},
{"votes":62,"name":"richardson"},
{"votes":21,"name":"dodd"},
{"votes":17,"name":"gravel"}],
"total":8092,"precincts":
{"total":33,"reporting":33},
"name":"Monroe"},
"Bay":
{"votes":[
{"votes":5636,"name":"clinton"},
{"votes":4349,"name":"obama"},
{"votes":3903,"name":"edwards"},
{"votes":278,"name":"richardson"},
{"votes":222,"name":"biden"},
{"votes":103,"name":"kucinich"},
{"votes":91,"name":"gravel"},
{"votes":76,"name":"dodd"}],
"total":14658,"precincts":
{"total":55,"reporting":55},
"name":"Bay"},
"DeSoto":
{"votes":[
{"votes":1261,"name":"clinton"},
{"votes":874,"name":"edwards"},
{"votes":615,"name":"obama"},
{"votes":61,"name":"richardson"},
{"votes":39,"name":"biden"},
{"votes":17,"name":"gravel"},
{"votes":12,"name":"kucinich"},
{"votes":10,"name":"dodd"}],
"total":2889,"precincts":
{"total":15,"reporting":15},
"name":"DeSoto"},
"Holmes":
{"votes":[
{"votes":1363,"name":"edwards"},
{"votes":835,"name":"clinton"},
{"votes":299,"name":"obama"},
{"votes":122,"name":"richardson"},
{"votes":59,"name":"biden"},
{"votes":32,"name":"gravel"},
{"votes":30,"name":"kucinich"},
{"votes":23,"name":"dodd"}],
"total":2763,"precincts":
{"total":8,"reporting":8},
"name":"Holmes"},
"Charlotte":
{"votes":[
{"votes":9236,"name":"clinton"},
{"votes":3130,"name":"obama"},
{"votes":2521,"name":"edwards"},
{"votes":143,"name":"biden"},
{"votes":109,"name":"richardson"},
{"votes":93,"name":"kucinich"},
{"votes":64,"name":"dodd"},
{"votes":30,"name":"gravel"}],
"total":15326,"precincts":
{"total":80,"reporting":80},
"name":"Charlotte"},
"Madison":
{"votes":[
{"votes":1193,"name":"obama"},
{"votes":1083,"name":"clinton"},
{"votes":945,"name":"edwards"},
{"votes":78,"name":"richardson"},
{"votes":60,"name":"biden"},
{"votes":26,"name":"gravel"},
{"votes":23,"name":"dodd"},
{"votes":23,"name":"kucinich"}],
"total":3431,"precincts":
{"total":11,"reporting":11},
"name":"Madison"},
"Taylor":
{"votes":[
{"votes":1222,"name":"edwards"},
{"votes":1181,"name":"clinton"},
{"votes":682,"name":"obama"},
{"votes":130,"name":"richardson"},
{"votes":59,"name":"biden"},
{"votes":34,"name":"dodd"},
{"votes":32,"name":"gravel"},
{"votes":27,"name":"kucinich"}],
"total":3367,"precincts":
{"total":14,"reporting":14},
"name":"Taylor"},
"Dixie":
{"votes":[
{"votes":873,"name":"clinton"},
{"votes":679,"name":"edwards"},
{"votes":300,"name":"obama"},
{"votes":72,"name":"richardson"},
{"votes":26,"name":"gravel"},
{"votes":24,"name":"biden"},
{"votes":23,"name":"kucinich"},
{"votes":21,"name":"dodd"}],
"total":2018,"precincts":
{"total":10,"reporting":10},
"name":"Dixie"},
"Lafayette":
{"votes":[
{"votes":636,"name":"edwards"},
{"votes":404,"name":"clinton"},
{"votes":140,"name":"obama"},
{"votes":41,"name":"richardson"},
{"votes":24,"name":"biden"},
{"votes":12,"name":"gravel"},
{"votes":9,"name":"kucinich"},
{"votes":8,"name":"dodd"}],
"total":1274,"precincts":
{"total":5,"reporting":5},
"name":"Lafayette"},
"Washington":
{"votes":[
{"votes":1075,"name":"edwards"},
{"votes":816,"name":"clinton"},
{"votes":681,"name":"obama"},
{"votes":104,"name":"richardson"},
{"votes":42,"name":"biden"},
{"votes":34,"name":"gravel"},
{"votes":25,"name":"dodd"},
{"votes":21,"name":"kucinich"}],
"total":2798,"precincts":
{"total":18,"reporting":18},
"name":"Washington"},
"St. Johns":
{"votes":[
{"votes":6948,"name":"clinton"},
{"votes":5301,"name":"obama"},
{"votes":2580,"name":"edwards"},
{"votes":146,"name":"richardson"},
{"votes":140,"name":"biden"},
{"votes":114,"name":"kucinich"},
{"votes":50,"name":"gravel"},
{"votes":40,"name":"dodd"}],
"total":15319,"precincts":
{"total":46,"reporting":46},
"name":"St. Johns"},
"Leon":
{"votes":[
{"votes":21082,"name":"obama"},
{"votes":14540,"name":"clinton"},
{"votes":7504,"name":"edwards"},
{"votes":480,"name":"richardson"},
{"votes":400,"name":"biden"},
{"votes":333,"name":"kucinich"},
{"votes":143,"name":"gravel"},
{"votes":114,"name":"dodd"}],
"total":44596,"precincts":
{"total":165,"reporting":165},
"name":"Leon"},
"Sarasota":
{"votes":[
{"votes":21604,"name":"clinton"},
{"votes":12545,"name":"obama"},
{"votes":5511,"name":"edwards"},
{"votes":337,"name":"biden"},
{"votes":282,"name":"kucinich"},
{"votes":226,"name":"richardson"},
{"votes":90,"name":"gravel"},
{"votes":82,"name":"dodd"}],
"total":40677,"precincts":
{"total":157,"reporting":157},
"name":"Sarasota"},
"Jefferson":
{"votes":[
{"votes":1285,"name":"obama"},
{"votes":918,"name":"clinton"},
{"votes":754,"name":"edwards"},
{"votes":59,"name":"richardson"},
{"votes":38,"name":"biden"},
{"votes":18,"name":"kucinich"},
{"votes":16,"name":"gravel"},
{"votes":15,"name":"dodd"}],
"total":3103,"precincts":
{"total":15,"reporting":15},
"name":"Jefferson"},
"Marion":
{"votes":[
{"votes":17980,"name":"clinton"},
{"votes":9719,"name":"obama"},
{"votes":6555,"name":"edwards"},
{"votes":411,"name":"biden"},
{"votes":292,"name":"richardson"},
{"votes":202,"name":"kucinich"},
{"votes":146,"name":"dodd"},
{"votes":128,"name":"gravel"}],
"total":35433,"precincts":
{"total":151,"reporting":151},
"name":"Marion"},
"Wakulla":
{"votes":[
{"votes":1713,"name":"clinton"},
{"votes":1578,"name":"edwards"},
{"votes":1127,"name":"obama"},
{"votes":115,"name":"richardson"},
{"votes":72,"name":"biden"},
{"votes":50,"name":"gravel"},
{"votes":48,"name":"kucinich"},
{"votes":24,"name":"dodd"}],
"total":4727,"precincts":
{"total":12,"reporting":12},
"name":"Wakulla"},
"Escambia":
{"votes":[
{"votes":13031,"name":"obama"},
{"votes":9996,"name":"clinton"},
{"votes":6691,"name":"edwards"},
{"votes":487,"name":"richardson"},
{"votes":322,"name":"biden"},
{"votes":175,"name":"kucinich"},
{"votes":127,"name":"gravel"},
{"votes":106,"name":"dodd"}],
"total":30935,"precincts":
{"total":90,"reporting":90},
"name":"Escambia"},
"Collier":
{"votes":[
{"votes":9759,"name":"clinton"},
{"votes":5119,"name":"obama"},
{"votes":2549,"name":"edwards"},
{"votes":195,"name":"biden"},
{"votes":162,"name":"richardson"},
{"votes":113,"name":"kucinich"},
{"votes":56,"name":"dodd"},
{"votes":28,"name":"gravel"}],
"total":17981,"precincts":
{"total":94,"reporting":94},
"name":"Collier"},
"Polk":
{"votes":[
{"votes":24443,"name":"clinton"},
{"votes":12990,"name":"obama"},
{"votes":9159,"name":"edwards"},
{"votes":493,"name":"richardson"},
{"votes":394,"name":"biden"},
{"votes":209,"name":"kucinich"},
{"votes":196,"name":"gravel"},
{"votes":166,"name":"dodd"}],
"total":48050,"precincts":
{"total":166,"reporting":166},
"name":"Polk"},
"Clay":
{"votes":[
{"votes":4834,"name":"clinton"},
{"votes":3627,"name":"obama"},
{"votes":2313,"name":"edwards"},
{"votes":144,"name":"richardson"},
{"votes":126,"name":"biden"},
{"votes":80,"name":"kucinich"},
{"votes":46,"name":"dodd"},
{"votes":41,"name":"gravel"}],
"total":11211,"precincts":
{"total":61,"reporting":61},
"name":"Clay"}}})