GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":693425,"name":"mccain","delegates":57},
{"votes":598152,"name":"romney"},
{"votes":281755,"name":"giuliani"},
{"votes":259703,"name":"huckabee"},
{"votes":62060,"name":"paul"},
{"votes":22287,"name":"thompson"},
{"votes":4003,"name":"keyes"},
{"votes":2787,"name":"hunter"},
{"votes":1556,"name":"tancredo"}],
"name":"Florida","precincts":
{"total":6913,"reporting":6900},
"delegates":57,"date":"01-29"},
"state":"FL","party":"gop","total":1925728,"locals":
{"Alachua":
{"votes":[
{"votes":6637,"name":"mccain"},
{"votes":5440,"name":"romney"},
{"votes":4166,"name":"huckabee"},
{"votes":1806,"name":"giuliani"},
{"votes":1125,"name":"paul"},
{"votes":321,"name":"thompson"},
{"votes":57,"name":"keyes"},
{"votes":27,"name":"hunter"},
{"votes":7,"name":"tancredo"}],
"total":19586,"precincts":
{"total":69,"reporting":69},
"name":"Alachua"},
"Okaloosa":
{"votes":[
{"votes":13811,"name":"mccain"},
{"votes":9821,"name":"romney"},
{"votes":6568,"name":"huckabee"},
{"votes":2535,"name":"giuliani"},
{"votes":1751,"name":"paul"},
{"votes":505,"name":"thompson"},
{"votes":106,"name":"keyes"},
{"votes":38,"name":"hunter"},
{"votes":12,"name":"tancredo"}],
"total":35147,"precincts":
{"total":52,"reporting":52},
"name":"Okaloosa"},
"Jackson":
{"votes":[
{"votes":1053,"name":"mccain"},
{"votes":1005,"name":"huckabee"},
{"votes":598,"name":"romney"},
{"votes":218,"name":"giuliani"},
{"votes":61,"name":"paul"},
{"votes":54,"name":"thompson"},
{"votes":9,"name":"keyes"},
{"votes":8,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":3007,"precincts":
{"total":25,"reporting":25},
"name":"Jackson"},
"Seminole":
{"votes":[
{"votes":19033,"name":"romney"},
{"votes":17196,"name":"mccain"},
{"votes":9141,"name":"huckabee"},
{"votes":7441,"name":"giuliani"},
{"votes":1722,"name":"paul"},
{"votes":573,"name":"thompson"},
{"votes":93,"name":"keyes"},
{"votes":82,"name":"hunter"},
{"votes":36,"name":"tancredo"}],
"total":55317,"precincts":
{"total":126,"reporting":126},
"name":"Seminole"},
"Gulf":
{"votes":[
{"votes":499,"name":"mccain"},
{"votes":373,"name":"romney"},
{"votes":311,"name":"huckabee"},
{"votes":94,"name":"giuliani"},
{"votes":29,"name":"paul"},
{"votes":20,"name":"thompson"},
{"votes":3,"name":"tancredo"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1331,"precincts":
{"total":8,"reporting":8},
"name":"Gulf"},
"Union":
{"votes":[
{"votes":241,"name":"romney"},
{"votes":172,"name":"mccain"},
{"votes":171,"name":"huckabee"},
{"votes":41,"name":"giuliani"},
{"votes":13,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":651,"precincts":
{"total":11,"reporting":11},
"name":"Union"},
"Volusia":
{"votes":[
{"votes":18332,"name":"mccain"},
{"votes":17557,"name":"romney"},
{"votes":7592,"name":"huckabee"},
{"votes":6583,"name":"giuliani"},
{"votes":1960,"name":"paul"},
{"votes":487,"name":"thompson"},
{"votes":93,"name":"keyes"},
{"votes":71,"name":"hunter"},
{"votes":35,"name":"tancredo"}],
"total":52710,"precincts":
{"total":179,"reporting":172},
"name":"Volusia"},
"Duval":
{"votes":[
{"votes":36645,"name":"romney"},
{"votes":24104,"name":"mccain"},
{"votes":13827,"name":"huckabee"},
{"votes":9541,"name":"giuliani"},
{"votes":2677,"name":"paul"},
{"votes":1221,"name":"thompson"},
{"votes":152,"name":"keyes"},
{"votes":88,"name":"hunter"},
{"votes":41,"name":"tancredo"}],
"total":88296,"precincts":
{"total":303,"reporting":303},
"name":"Duval"},
"Sumter":
{"votes":[
{"votes":6945,"name":"romney"},
{"votes":4835,"name":"mccain"},
{"votes":2860,"name":"giuliani"},
{"votes":1996,"name":"huckabee"},
{"votes":261,"name":"thompson"},
{"votes":208,"name":"paul"},
{"votes":41,"name":"keyes"},
{"votes":21,"name":"hunter"},
{"votes":7,"name":"tancredo"}],
"total":17174,"precincts":
{"total":42,"reporting":42},
"name":"Sumter"},
"Lake":
{"votes":[
{"votes":14881,"name":"romney"},
{"votes":14733,"name":"mccain"},
{"votes":9013,"name":"huckabee"},
{"votes":5141,"name":"giuliani"},
{"votes":1091,"name":"paul"},
{"votes":615,"name":"thompson"},
{"votes":86,"name":"keyes"},
{"votes":75,"name":"hunter"},
{"votes":41,"name":"tancredo"}],
"total":45676,"precincts":
{"total":102,"reporting":102},
"name":"Lake"},
"Liberty":
{"votes":[
{"votes":52,"name":"mccain"},
{"votes":49,"name":"romney"},
{"votes":44,"name":"huckabee"},
{"votes":8,"name":"thompson"},
{"votes":8,"name":"giuliani"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"hunter"}],
"total":165,"precincts":
{"total":8,"reporting":8},
"name":"Liberty"},
"Hillsborough":
{"votes":[
{"votes":37804,"name":"mccain"},
{"votes":30548,"name":"romney"},
{"votes":15849,"name":"giuliani"},
{"votes":12839,"name":"huckabee"},
{"votes":2807,"name":"paul"},
{"votes":1187,"name":"thompson"},
{"votes":229,"name":"keyes"},
{"votes":140,"name":"hunter"},
{"votes":61,"name":"tancredo"}],
"total":101464,"precincts":
{"total":361,"reporting":361},
"name":"Hillsborough"},
"Flagler":
{"votes":[
{"votes":4215,"name":"romney"},
{"votes":3996,"name":"mccain"},
{"votes":1786,"name":"giuliani"},
{"votes":1219,"name":"huckabee"},
{"votes":271,"name":"paul"},
{"votes":85,"name":"thompson"},
{"votes":18,"name":"keyes"},
{"votes":13,"name":"hunter"},
{"votes":7,"name":"tancredo"}],
"total":11610,"precincts":
{"total":36,"reporting":36},
"name":"Flagler"},
"Brevard":
{"votes":[
{"votes":31320,"name":"mccain"},
{"votes":27001,"name":"romney"},
{"votes":12215,"name":"giuliani"},
{"votes":11587,"name":"huckabee"},
{"votes":3621,"name":"paul"},
{"votes":1033,"name":"thompson"},
{"votes":231,"name":"keyes"},
{"votes":160,"name":"hunter"},
{"votes":69,"name":"tancredo"}],
"total":87237,"precincts":
{"total":216,"reporting":216},
"name":"Brevard"},
"Miami-Dade":
{"votes":[
{"votes":75516,"name":"mccain"},
{"votes":40251,"name":"giuliani"},
{"votes":23936,"name":"romney"},
{"votes":9154,"name":"huckabee"},
{"votes":2936,"name":"paul"},
{"votes":1125,"name":"thompson"},
{"votes":390,"name":"keyes"},
{"votes":319,"name":"hunter"},
{"votes":217,"name":"tancredo"}],
"total":153844,"precincts":
{"total":744,"reporting":744},
"name":"Miami-Dade"},
"Santa Rosa":
{"votes":[
{"votes":9596,"name":"mccain"},
{"votes":6704,"name":"romney"},
{"votes":6276,"name":"huckabee"},
{"votes":1696,"name":"giuliani"},
{"votes":1205,"name":"paul"},
{"votes":397,"name":"thompson"},
{"votes":49,"name":"keyes"},
{"votes":36,"name":"hunter"},
{"votes":21,"name":"tancredo"}],
"total":25980,"precincts":
{"total":41,"reporting":41},
"name":"Santa Rosa"},
"Orange":
{"votes":[
{"votes":29592,"name":"mccain"},
{"votes":29145,"name":"romney"},
{"votes":15697,"name":"huckabee"},
{"votes":12741,"name":"giuliani"},
{"votes":2965,"name":"paul"},
{"votes":1084,"name":"thompson"},
{"votes":184,"name":"keyes"},
{"votes":146,"name":"hunter"},
{"votes":69,"name":"tancredo"}],
"total":91623,"precincts":
{"total":261,"reporting":261},
"name":"Orange"},
"Pasco":
{"votes":[
{"votes":18935,"name":"mccain"},
{"votes":15433,"name":"romney"},
{"votes":8572,"name":"giuliani"},
{"votes":6688,"name":"huckabee"},
{"votes":1460,"name":"paul"},
{"votes":607,"name":"thompson"},
{"votes":96,"name":"keyes"},
{"votes":69,"name":"hunter"},
{"votes":34,"name":"tancredo"}],
"total":51894,"precincts":
{"total":153,"reporting":153},
"name":"Pasco"},
"Indian River":
{"votes":[
{"votes":8354,"name":"romney"},
{"votes":8332,"name":"mccain"},
{"votes":3774,"name":"giuliani"},
{"votes":2436,"name":"huckabee"},
{"votes":787,"name":"paul"},
{"votes":270,"name":"thompson"},
{"votes":43,"name":"keyes"},
{"votes":32,"name":"tancredo"},
{"votes":25,"name":"hunter"}],
"total":24053,"precincts":
{"total":54,"reporting":54},
"name":"Indian River"},
"Levy":
{"votes":[
{"votes":1102,"name":"mccain"},
{"votes":930,"name":"huckabee"},
{"votes":928,"name":"romney"},
{"votes":319,"name":"giuliani"},
{"votes":132,"name":"paul"},
{"votes":71,"name":"thompson"},
{"votes":11,"name":"hunter"},
{"votes":9,"name":"keyes"},
{"votes":3,"name":"tancredo"}],
"total":3505,"precincts":
{"total":20,"reporting":20},
"name":"Levy"},
"Hardee":
{"votes":[
{"votes":432,"name":"mccain"},
{"votes":349,"name":"huckabee"},
{"votes":303,"name":"romney"},
{"votes":89,"name":"giuliani"},
{"votes":31,"name":"paul"},
{"votes":22,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1230,"precincts":
{"total":12,"reporting":12},
"name":"Hardee"},
"Columbia":
{"votes":[
{"votes":1886,"name":"romney"},
{"votes":1562,"name":"mccain"},
{"votes":1538,"name":"huckabee"},
{"votes":521,"name":"giuliani"},
{"votes":134,"name":"paul"},
{"votes":119,"name":"thompson"},
{"votes":22,"name":"keyes"},
{"votes":1,"name":"hunter"}],
"total":5783,"precincts":
{"total":25,"reporting":25},
"name":"Columbia"},
"Lee":
{"votes":[
{"votes":34138,"name":"romney"},
{"votes":28096,"name":"mccain"},
{"votes":12067,"name":"giuliani"},
{"votes":7461,"name":"huckabee"},
{"votes":2439,"name":"paul"},
{"votes":1056,"name":"thompson"},
{"votes":141,"name":"keyes"},
{"votes":72,"name":"tancredo"},
{"votes":60,"name":"hunter"}],
"total":85530,"precincts":
{"total":173,"reporting":173},
"name":"Lee"},
"Citrus":
{"votes":[
{"votes":8200,"name":"mccain"},
{"votes":7233,"name":"romney"},
{"votes":3805,"name":"huckabee"},
{"votes":2943,"name":"giuliani"},
{"votes":717,"name":"paul"},
{"votes":353,"name":"thompson"},
{"votes":44,"name":"keyes"},
{"votes":38,"name":"hunter"},
{"votes":24,"name":"tancredo"}],
"total":23357,"precincts":
{"total":41,"reporting":41},
"name":"Citrus"},
"Okeechobee":
{"votes":[
{"votes":969,"name":"mccain"},
{"votes":748,"name":"huckabee"},
{"votes":443,"name":"romney"},
{"votes":254,"name":"giuliani"},
{"votes":40,"name":"paul"},
{"votes":32,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":2,"name":"keyes"}],
"total":2494,"precincts":
{"total":18,"reporting":18},
"name":"Okeechobee"},
"Manatee":
{"votes":[
{"votes":16134,"name":"mccain"},
{"votes":15153,"name":"romney"},
{"votes":6811,"name":"giuliani"},
{"votes":5455,"name":"huckabee"},
{"votes":1398,"name":"paul"},
{"votes":431,"name":"thompson"},
{"votes":91,"name":"keyes"},
{"votes":59,"name":"hunter"},
{"votes":37,"name":"tancredo"}],
"total":45569,"precincts":
{"total":136,"reporting":136},
"name":"Manatee"},
"Walton":
{"votes":[
{"votes":2928,"name":"mccain"},
{"votes":2291,"name":"romney"},
{"votes":1795,"name":"huckabee"},
{"votes":700,"name":"giuliani"},
{"votes":445,"name":"paul"},
{"votes":80,"name":"thompson"},
{"votes":15,"name":"keyes"},
{"votes":12,"name":"hunter"},
{"votes":4,"name":"tancredo"}],
"total":8270,"precincts":
{"total":36,"reporting":36},
"name":"Walton"},
"Hernando":
{"votes":[
{"votes":9042,"name":"mccain"},
{"votes":7259,"name":"romney"},
{"votes":4122,"name":"giuliani"},
{"votes":3285,"name":"huckabee"},
{"votes":812,"name":"paul"},
{"votes":255,"name":"thompson"},
{"votes":54,"name":"keyes"},
{"votes":21,"name":"hunter"},
{"votes":20,"name":"tancredo"}],
"total":24870,"precincts":
{"total":56,"reporting":56},
"name":"Hernando"},
"Hamilton":
{"votes":[
{"votes":201,"name":"mccain"},
{"votes":169,"name":"huckabee"},
{"votes":115,"name":"romney"},
{"votes":37,"name":"giuliani"},
{"votes":14,"name":"paul"},
{"votes":12,"name":"thompson"},
{"votes":1,"name":"tancredo"}],
"total":549,"precincts":
{"total":8,"reporting":8},
"name":"Hamilton"},
"Nassau":
{"votes":[
{"votes":4583,"name":"romney"},
{"votes":3722,"name":"mccain"},
{"votes":2572,"name":"huckabee"},
{"votes":1142,"name":"giuliani"},
{"votes":338,"name":"paul"},
{"votes":183,"name":"thompson"},
{"votes":17,"name":"keyes"},
{"votes":9,"name":"hunter"},
{"votes":7,"name":"tancredo"}],
"total":12573,"precincts":
{"total":21,"reporting":21},
"name":"Nassau"},
"Broward":
{"votes":[
{"votes":40575,"name":"mccain"},
{"votes":23885,"name":"romney"},
{"votes":18636,"name":"giuliani"},
{"votes":10279,"name":"huckabee"},
{"votes":3057,"name":"paul"},
{"votes":860,"name":"thompson"},
{"votes":208,"name":"keyes"},
{"votes":178,"name":"hunter"},
{"votes":114,"name":"tancredo"}],
"total":97792,"precincts":
{"total":791,"reporting":785},
"name":"Broward"},
"Putnam":
{"votes":[
{"votes":2095,"name":"mccain"},
{"votes":1992,"name":"romney"},
{"votes":1457,"name":"huckabee"},
{"votes":474,"name":"giuliani"},
{"votes":169,"name":"paul"},
{"votes":102,"name":"thompson"},
{"votes":16,"name":"keyes"},
{"votes":10,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":6317,"precincts":
{"total":56,"reporting":56},
"name":"Putnam"},
"St. Lucie":
{"votes":[
{"votes":9258,"name":"mccain"},
{"votes":7434,"name":"romney"},
{"votes":5356,"name":"giuliani"},
{"votes":3400,"name":"huckabee"},
{"votes":996,"name":"paul"},
{"votes":465,"name":"thompson"},
{"votes":51,"name":"keyes"},
{"votes":45,"name":"hunter"},
{"votes":27,"name":"tancredo"}],
"total":27032,"precincts":
{"total":80,"reporting":80},
"name":"St. Lucie"},
"Bradford":
{"votes":[
{"votes":721,"name":"romney"},
{"votes":701,"name":"huckabee"},
{"votes":606,"name":"mccain"},
{"votes":145,"name":"giuliani"},
{"votes":54,"name":"paul"},
{"votes":42,"name":"thompson"},
{"votes":9,"name":"keyes"},
{"votes":1,"name":"hunter"}],
"total":2279,"precincts":
{"total":19,"reporting":19},
"name":"Bradford"},
"Suwannee":
{"votes":[
{"votes":1034,"name":"huckabee"},
{"votes":1019,"name":"mccain"},
{"votes":756,"name":"romney"},
{"votes":194,"name":"giuliani"},
{"votes":142,"name":"paul"},
{"votes":82,"name":"thompson"},
{"votes":9,"name":"keyes"},
{"votes":7,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":3246,"precincts":
{"total":16,"reporting":16},
"name":"Suwannee"},
"Hendry":
{"votes":[
{"votes":713,"name":"mccain"},
{"votes":523,"name":"romney"},
{"votes":367,"name":"huckabee"},
{"votes":209,"name":"giuliani"},
{"votes":52,"name":"paul"},
{"votes":22,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":7,"name":"keyes"}],
"total":1900,"precincts":
{"total":23,"reporting":23},
"name":"Hendry"},
"Highlands":
{"votes":[
{"votes":4905,"name":"romney"},
{"votes":4889,"name":"mccain"},
{"votes":1925,"name":"huckabee"},
{"votes":1355,"name":"giuliani"},
{"votes":247,"name":"paul"},
{"votes":161,"name":"thompson"},
{"votes":21,"name":"keyes"},
{"votes":15,"name":"hunter"},
{"votes":7,"name":"tancredo"}],
"total":13525,"precincts":
{"total":25,"reporting":25},
"name":"Highlands"},
"Gadsden":
{"votes":[
{"votes":579,"name":"mccain"},
{"votes":454,"name":"romney"},
{"votes":345,"name":"huckabee"},
{"votes":139,"name":"giuliani"},
{"votes":64,"name":"paul"},
{"votes":30,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":1619,"precincts":
{"total":25,"reporting":25},
"name":"Gadsden"},
"Baker":
{"votes":[
{"votes":742,"name":"romney"},
{"votes":566,"name":"huckabee"},
{"votes":454,"name":"mccain"},
{"votes":124,"name":"giuliani"},
{"votes":57,"name":"paul"},
{"votes":45,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1994,"precincts":
{"total":9,"reporting":9},
"name":"Baker"},
"Osceola":
{"votes":[
{"votes":5558,"name":"mccain"},
{"votes":5356,"name":"romney"},
{"votes":3221,"name":"huckabee"},
{"votes":2269,"name":"giuliani"},
{"votes":426,"name":"paul"},
{"votes":197,"name":"thompson"},
{"votes":31,"name":"keyes"},
{"votes":24,"name":"hunter"},
{"votes":11,"name":"tancredo"}],
"total":17093,"precincts":
{"total":101,"reporting":101},
"name":"Osceola"},
"Gilchrist":
{"votes":[
{"votes":493,"name":"huckabee"},
{"votes":467,"name":"mccain"},
{"votes":461,"name":"romney"},
{"votes":100,"name":"giuliani"},
{"votes":61,"name":"paul"},
{"votes":30,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":1618,"precincts":
{"total":10,"reporting":10},
"name":"Gilchrist"},
"Palm Beach":
{"votes":[
{"votes":38479,"name":"mccain"},
{"votes":29232,"name":"romney"},
{"votes":15975,"name":"giuliani"},
{"votes":8273,"name":"huckabee"},
{"votes":3374,"name":"paul"},
{"votes":535,"name":"thompson"},
{"votes":207,"name":"keyes"},
{"votes":157,"name":"hunter"},
{"votes":93,"name":"tancredo"}],
"total":96325,"precincts":
{"total":752,"reporting":752},
"name":"Palm Beach"},
"Glades":
{"votes":[
{"votes":280,"name":"mccain"},
{"votes":206,"name":"romney"},
{"votes":146,"name":"huckabee"},
{"votes":60,"name":"giuliani"},
{"votes":17,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":713,"precincts":
{"total":13,"reporting":13},
"name":"Glades"},
"Franklin":
{"votes":[
{"votes":299,"name":"mccain"},
{"votes":225,"name":"romney"},
{"votes":132,"name":"huckabee"},
{"votes":86,"name":"giuliani"},
{"votes":25,"name":"thompson"},
{"votes":21,"name":"paul"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":791,"precincts":
{"total":8,"reporting":8},
"name":"Franklin"},
"Pinellas":
{"votes":[
{"votes":43767,"name":"mccain"},
{"votes":34834,"name":"romney"},
{"votes":19188,"name":"giuliani"},
{"votes":12285,"name":"huckabee"},
{"votes":4961,"name":"paul"},
{"votes":1096,"name":"thompson"},
{"votes":210,"name":"keyes"},
{"votes":160,"name":"hunter"},
{"votes":99,"name":"tancredo"}],
"total":116600,"precincts":
{"total":371,"reporting":371},
"name":"Pinellas"},
"Martin":
{"votes":[
{"votes":10115,"name":"mccain"},
{"votes":8386,"name":"romney"},
{"votes":4218,"name":"giuliani"},
{"votes":2868,"name":"huckabee"},
{"votes":1229,"name":"paul"},
{"votes":325,"name":"thompson"},
{"votes":86,"name":"keyes"},
{"votes":60,"name":"hunter"},
{"votes":38,"name":"tancredo"}],
"total":27325,"precincts":
{"total":53,"reporting":53},
"name":"Martin"},
"Calhoun":
{"votes":[
{"votes":216,"name":"mccain"},
{"votes":165,"name":"huckabee"},
{"votes":112,"name":"romney"},
{"votes":29,"name":"giuliani"},
{"votes":18,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":552,"precincts":
{"total":18,"reporting":18},
"name":"Calhoun"},
"Monroe":
{"votes":[
{"votes":4266,"name":"mccain"},
{"votes":2232,"name":"romney"},
{"votes":1507,"name":"giuliani"},
{"votes":729,"name":"huckabee"},
{"votes":291,"name":"paul"},
{"votes":154,"name":"thompson"},
{"votes":19,"name":"hunter"},
{"votes":15,"name":"keyes"},
{"votes":7,"name":"tancredo"}],
"total":9220,"precincts":
{"total":33,"reporting":33},
"name":"Monroe"},
"Bay":
{"votes":[
{"votes":7537,"name":"romney"},
{"votes":7296,"name":"mccain"},
{"votes":4746,"name":"huckabee"},
{"votes":2204,"name":"giuliani"},
{"votes":826,"name":"paul"},
{"votes":405,"name":"thompson"},
{"votes":38,"name":"keyes"},
{"votes":30,"name":"hunter"},
{"votes":11,"name":"tancredo"}],
"total":23093,"precincts":
{"total":55,"reporting":55},
"name":"Bay"},
"DeSoto":
{"votes":[
{"votes":576,"name":"mccain"},
{"votes":566,"name":"romney"},
{"votes":290,"name":"huckabee"},
{"votes":162,"name":"giuliani"},
{"votes":47,"name":"paul"},
{"votes":28,"name":"thompson"},
{"votes":6,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":1679,"precincts":
{"total":15,"reporting":15},
"name":"DeSoto"},
"Holmes":
{"votes":[
{"votes":429,"name":"huckabee"},
{"votes":405,"name":"mccain"},
{"votes":246,"name":"romney"},
{"votes":80,"name":"giuliani"},
{"votes":38,"name":"paul"},
{"votes":22,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1224,"precincts":
{"total":8,"reporting":8},
"name":"Holmes"},
"Charlotte":
{"votes":[
{"votes":9768,"name":"mccain"},
{"votes":8345,"name":"romney"},
{"votes":3823,"name":"giuliani"},
{"votes":2430,"name":"huckabee"},
{"votes":807,"name":"paul"},
{"votes":431,"name":"thompson"},
{"votes":50,"name":"keyes"},
{"votes":27,"name":"hunter"},
{"votes":25,"name":"tancredo"}],
"total":25706,"precincts":
{"total":80,"reporting":80},
"name":"Charlotte"},
"Madison":
{"votes":[
{"votes":306,"name":"mccain"},
{"votes":293,"name":"huckabee"},
{"votes":166,"name":"romney"},
{"votes":45,"name":"giuliani"},
{"votes":26,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"hunter"}],
"total":850,"precincts":
{"total":11,"reporting":11},
"name":"Madison"},
"Taylor":
{"votes":[
{"votes":505,"name":"mccain"},
{"votes":409,"name":"huckabee"},
{"votes":241,"name":"romney"},
{"votes":64,"name":"giuliani"},
{"votes":34,"name":"thompson"},
{"votes":33,"name":"paul"},
{"votes":6,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1294,"precincts":
{"total":14,"reporting":14},
"name":"Taylor"},
"Dixie":
{"votes":[
{"votes":234,"name":"mccain"},
{"votes":227,"name":"romney"},
{"votes":199,"name":"huckabee"},
{"votes":50,"name":"giuliani"},
{"votes":17,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"hunter"}],
"total":747,"precincts":
{"total":10,"reporting":10},
"name":"Dixie"},
"Lafayette":
{"votes":[
{"votes":149,"name":"mccain"},
{"votes":124,"name":"huckabee"},
{"votes":84,"name":"romney"},
{"votes":12,"name":"giuliani"},
{"votes":12,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":393,"precincts":
{"total":5,"reporting":5},
"name":"Lafayette"},
"Washington":
{"votes":[
{"votes":486,"name":"huckabee"},
{"votes":468,"name":"mccain"},
{"votes":375,"name":"romney"},
{"votes":96,"name":"giuliani"},
{"votes":48,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":1494,"precincts":
{"total":18,"reporting":18},
"name":"Washington"},
"St. Johns":
{"votes":[
{"votes":15587,"name":"romney"},
{"votes":10296,"name":"mccain"},
{"votes":4731,"name":"giuliani"},
{"votes":4318,"name":"huckabee"},
{"votes":937,"name":"paul"},
{"votes":397,"name":"thompson"},
{"votes":55,"name":"keyes"},
{"votes":28,"name":"hunter"},
{"votes":23,"name":"tancredo"}],
"total":36372,"precincts":
{"total":46,"reporting":46},
"name":"St. Johns"},
"Leon":
{"votes":[
{"votes":9550,"name":"mccain"},
{"votes":6650,"name":"romney"},
{"votes":4286,"name":"huckabee"},
{"votes":2370,"name":"giuliani"},
{"votes":1111,"name":"paul"},
{"votes":474,"name":"thompson"},
{"votes":68,"name":"keyes"},
{"votes":50,"name":"hunter"},
{"votes":11,"name":"tancredo"}],
"total":24570,"precincts":
{"total":165,"reporting":165},
"name":"Leon"},
"Sarasota":
{"votes":[
{"votes":25685,"name":"mccain"},
{"votes":21727,"name":"romney"},
{"votes":10496,"name":"giuliani"},
{"votes":6082,"name":"huckabee"},
{"votes":2612,"name":"paul"},
{"votes":627,"name":"thompson"},
{"votes":102,"name":"keyes"},
{"votes":82,"name":"hunter"},
{"votes":40,"name":"tancredo"}],
"total":67453,"precincts":
{"total":157,"reporting":157},
"name":"Sarasota"},
"Jefferson":
{"votes":[
{"votes":439,"name":"mccain"},
{"votes":275,"name":"romney"},
{"votes":244,"name":"huckabee"},
{"votes":84,"name":"giuliani"},
{"votes":43,"name":"paul"},
{"votes":17,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1105,"precincts":
{"total":15,"reporting":15},
"name":"Jefferson"},
"Marion":
{"votes":[
{"votes":15715,"name":"romney"},
{"votes":14741,"name":"mccain"},
{"votes":9246,"name":"huckabee"},
{"votes":5025,"name":"giuliani"},
{"votes":1618,"name":"paul"},
{"votes":501,"name":"thompson"},
{"votes":114,"name":"keyes"},
{"votes":107,"name":"hunter"},
{"votes":54,"name":"tancredo"}],
"total":47121,"precincts":
{"total":151,"reporting":151},
"name":"Marion"},
"Wakulla":
{"votes":[
{"votes":826,"name":"mccain"},
{"votes":479,"name":"romney"},
{"votes":462,"name":"huckabee"},
{"votes":200,"name":"giuliani"},
{"votes":64,"name":"paul"},
{"votes":53,"name":"thompson"},
{"votes":10,"name":"keyes"},
{"votes":5,"name":"hunter"}],
"total":2099,"precincts":
{"total":12,"reporting":12},
"name":"Wakulla"},
"Escambia":
{"votes":[
{"votes":15121,"name":"mccain"},
{"votes":11391,"name":"romney"},
{"votes":9491,"name":"huckabee"},
{"votes":3017,"name":"giuliani"},
{"votes":2170,"name":"paul"},
{"votes":872,"name":"thompson"},
{"votes":164,"name":"keyes"},
{"votes":45,"name":"hunter"},
{"votes":26,"name":"tancredo"}],
"total":42297,"precincts":
{"total":90,"reporting":90},
"name":"Escambia"},
"Collier":
{"votes":[
{"votes":23263,"name":"romney"},
{"votes":15052,"name":"mccain"},
{"votes":8591,"name":"giuliani"},
{"votes":3650,"name":"huckabee"},
{"votes":1203,"name":"paul"},
{"votes":739,"name":"thompson"},
{"votes":70,"name":"keyes"},
{"votes":52,"name":"hunter"},
{"votes":36,"name":"tancredo"}],
"total":52656,"precincts":
{"total":94,"reporting":94},
"name":"Collier"},
"Polk":
{"votes":[
{"votes":20112,"name":"mccain"},
{"votes":18127,"name":"romney"},
{"votes":11151,"name":"huckabee"},
{"votes":5547,"name":"giuliani"},
{"votes":1352,"name":"paul"},
{"votes":570,"name":"thompson"},
{"votes":98,"name":"keyes"},
{"votes":65,"name":"hunter"},
{"votes":38,"name":"tancredo"}],
"total":57060,"precincts":
{"total":166,"reporting":166},
"name":"Polk"},
"Clay":
{"votes":[
{"votes":13444,"name":"romney"},
{"votes":9358,"name":"mccain"},
{"votes":5144,"name":"huckabee"},
{"votes":2937,"name":"giuliani"},
{"votes":668,"name":"paul"},
{"votes":402,"name":"thompson"},
{"votes":61,"name":"keyes"},
{"votes":42,"name":"hunter"},
{"votes":23,"name":"tancredo"}],
"total":32079,"precincts":
{"total":61,"reporting":61},
"name":"Clay"}}})