GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":23950,"name":"obama","delegates":15},
{"votes":16102,"name":"clinton","delegates":3},
{"votes":2041,"name":"uncommitted-d"},
{"votes":734,"name":"judd"}],
"name":"Idaho","precincts":
{"total":940,"reporting":938},
"delegates":18,"date":"05-27"},
"state":"ID","party":"dem","total":42827,"locals":
{"Camas":
{"votes":[
{"votes":22,"name":"obama"},
{"votes":17,"name":"clinton"},
{"votes":3,"name":"judd"}],
"total":42,"precincts":
{"total":2,"reporting":2},
"name":"Camas"},
"Nez Perce":
{"votes":[
{"votes":786,"name":"obama"},
{"votes":770,"name":"clinton"},
{"votes":124,"name":"uncommitted-d"},
{"votes":32,"name":"judd"}],
"total":1712,"precincts":
{"total":37,"reporting":37},
"name":"Nez Perce"},
"Gooding":
{"votes":[
{"votes":181,"name":"obama"},
{"votes":155,"name":"clinton"},
{"votes":21,"name":"uncommitted-d"},
{"votes":11,"name":"judd"}],
"total":368,"precincts":
{"total":7,"reporting":7},
"name":"Gooding"},
"Clearwater":
{"votes":[
{"votes":230,"name":"obama"},
{"votes":191,"name":"clinton"},
{"votes":25,"name":"uncommitted-d"},
{"votes":7,"name":"judd"}],
"total":453,"precincts":
{"total":15,"reporting":15},
"name":"Clearwater"},
"Benewah":
{"votes":[
{"votes":269,"name":"obama"},
{"votes":224,"name":"clinton"},
{"votes":41,"name":"uncommitted-d"},
{"votes":17,"name":"judd"}],
"total":551,"precincts":
{"total":11,"reporting":11},
"name":"Benewah"},
"Ada":
{"votes":[
{"votes":7338,"name":"obama"},
{"votes":3633,"name":"clinton"},
{"votes":236,"name":"uncommitted-d"},
{"votes":83,"name":"judd"}],
"total":11290,"precincts":
{"total":141,"reporting":141},
"name":"Ada"},
"Boundary":
{"votes":[
{"votes":273,"name":"obama"},
{"votes":174,"name":"clinton"},
{"votes":6,"name":"judd"}],
"total":453,"precincts":
{"total":7,"reporting":7},
"name":"Boundary"},
"Valley":
{"votes":[
{"votes":249,"name":"obama"},
{"votes":131,"name":"clinton"},
{"votes":7,"name":"uncommitted-d"},
{"votes":2,"name":"judd"}],
"total":389,"precincts":
{"total":9,"reporting":9},
"name":"Valley"},
"Teton":
{"votes":[
{"votes":421,"name":"obama"},
{"votes":166,"name":"clinton"},
{"votes":34,"name":"uncommitted-d"},
{"votes":4,"name":"judd"}],
"total":625,"precincts":
{"total":5,"reporting":5},
"name":"Teton"},
"Idaho":
{"votes":[
{"votes":417,"name":"obama"},
{"votes":295,"name":"clinton"},
{"votes":14,"name":"judd"}],
"total":726,"precincts":
{"total":27,"reporting":27},
"name":"Idaho"},
"Bingham":
{"votes":[
{"votes":428,"name":"obama"},
{"votes":348,"name":"clinton"},
{"votes":61,"name":"uncommitted-d"},
{"votes":22,"name":"judd"}],
"total":859,"precincts":
{"total":27,"reporting":27},
"name":"Bingham"},
"Owyhee":
{"votes":[
{"votes":104,"name":"obama"},
{"votes":91,"name":"clinton"},
{"votes":85,"name":"uncommitted-d"},
{"votes":10,"name":"judd"}],
"total":290,"precincts":
{"total":13,"reporting":13},
"name":"Owyhee"},
"Custer":
{"votes":[
{"votes":118,"name":"obama"},
{"votes":81,"name":"clinton"},
{"votes":10,"name":"judd"},
{"votes":4,"name":"uncommitted-d"}],
"total":213,"precincts":
{"total":9,"reporting":9},
"name":"Custer"},
"Fremont":
{"votes":[
{"votes":106,"name":"obama"},
{"votes":73,"name":"clinton"},
{"votes":7,"name":"judd"}],
"total":186,"precincts":
{"total":14,"reporting":14},
"name":"Fremont"},
"Canyon":
{"votes":[
{"votes":1436,"name":"obama"},
{"votes":1130,"name":"clinton"},
{"votes":130,"name":"uncommitted-d"},
{"votes":72,"name":"judd"}],
"total":2768,"precincts":
{"total":53,"reporting":53},
"name":"Canyon"},
"Boise":
{"votes":[
{"votes":155,"name":"obama"},
{"votes":72,"name":"clinton"},
{"votes":5,"name":"judd"}],
"total":232,"precincts":
{"total":7,"reporting":7},
"name":"Boise"},
"Bonneville":
{"votes":[
{"votes":780,"name":"obama"},
{"votes":512,"name":"clinton"},
{"votes":61,"name":"uncommitted-d"},
{"votes":12,"name":"judd"}],
"total":1365,"precincts":
{"total":52,"reporting":52},
"name":"Bonneville"},
"Butte":
{"votes":[
{"votes":49,"name":"clinton"},
{"votes":47,"name":"obama"},
{"votes":4,"name":"judd"}],
"total":100,"precincts":
{"total":4,"reporting":4},
"name":"Butte"},
"Twin Falls":
{"votes":[
{"votes":622,"name":"obama"},
{"votes":533,"name":"clinton"},
{"votes":36,"name":"uncommitted-d"},
{"votes":23,"name":"judd"}],
"total":1214,"precincts":
{"total":45,"reporting":45},
"name":"Twin Falls"},
"Gem":
{"votes":[
{"votes":201,"name":"obama"},
{"votes":161,"name":"clinton"},
{"votes":8,"name":"uncommitted-d"},
{"votes":4,"name":"judd"}],
"total":374,"precincts":
{"total":13,"reporting":11},
"name":"Gem"},
"Lincoln":
{"votes":[
{"votes":75,"name":"obama"},
{"votes":73,"name":"clinton"},
{"votes":6,"name":"judd"},
{"votes":4,"name":"uncommitted-d"}],
"total":158,"precincts":
{"total":6,"reporting":6},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":107,"name":"obama"},
{"votes":55,"name":"clinton"},
{"votes":1,"name":"judd"}],
"total":163,"precincts":
{"total":6,"reporting":6},
"name":"Adams"},
"Lemhi":
{"votes":[
{"votes":120,"name":"obama"},
{"votes":83,"name":"clinton"},
{"votes":5,"name":"uncommitted-d"}],
"total":208,"precincts":
{"total":9,"reporting":9},
"name":"Lemhi"},
"Oneida":
{"votes":[
{"votes":41,"name":"clinton"},
{"votes":29,"name":"obama"},
{"votes":1,"name":"judd"}],
"total":71,"precincts":
{"total":6,"reporting":6},
"name":"Oneida"},
"Bannock":
{"votes":[
{"votes":1937,"name":"obama"},
{"votes":1590,"name":"clinton"},
{"votes":304,"name":"uncommitted-d"},
{"votes":115,"name":"judd"}],
"total":3946,"precincts":
{"total":58,"reporting":58},
"name":"Bannock"},
"Jefferson":
{"votes":[
{"votes":105,"name":"obama"},
{"votes":92,"name":"clinton"},
{"votes":12,"name":"uncommitted-d"},
{"votes":9,"name":"judd"}],
"total":218,"precincts":
{"total":18,"reporting":18},
"name":"Jefferson"},
"Franklin":
{"votes":[
{"votes":51,"name":"obama"},
{"votes":36,"name":"clinton"},
{"votes":6,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":96,"precincts":
{"total":17,"reporting":17},
"name":"Franklin"},
"Caribou":
{"votes":[
{"votes":65,"name":"obama"},
{"votes":53,"name":"clinton"},
{"votes":7,"name":"judd"},
{"votes":2,"name":"uncommitted-d"}],
"total":127,"precincts":
{"total":10,"reporting":10},
"name":"Caribou"},
"Latah":
{"votes":[
{"votes":705,"name":"obama"},
{"votes":397,"name":"clinton"},
{"votes":41,"name":"uncommitted-d"},
{"votes":8,"name":"judd"}],
"total":1151,"precincts":
{"total":33,"reporting":33},
"name":"Latah"},
"Madison":
{"votes":[
{"votes":94,"name":"obama"},
{"votes":57,"name":"clinton"},
{"votes":15,"name":"uncommitted-d"},
{"votes":6,"name":"judd"}],
"total":172,"precincts":
{"total":19,"reporting":19},
"name":"Madison"},
"Kootenai":
{"votes":[
{"votes":1976,"name":"obama"},
{"votes":1559,"name":"clinton"},
{"votes":91,"name":"uncommitted-d"},
{"votes":25,"name":"judd"}],
"total":3651,"precincts":
{"total":75,"reporting":75},
"name":"Kootenai"},
"Power":
{"votes":[
{"votes":134,"name":"obama"},
{"votes":86,"name":"clinton"},
{"votes":12,"name":"uncommitted-d"},
{"votes":4,"name":"judd"}],
"total":236,"precincts":
{"total":7,"reporting":7},
"name":"Power"},
"Clark":
{"votes":[
{"votes":8,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":3,"name":"judd"},
{"votes":2,"name":"uncommitted-d"}],
"total":17,"precincts":
{"total":3,"reporting":3},
"name":"Clark"},
"Lewis":
{"votes":[
{"votes":128,"name":"obama"},
{"votes":118,"name":"clinton"},
{"votes":8,"name":"judd"},
{"votes":7,"name":"uncommitted-d"}],
"total":261,"precincts":
{"total":8,"reporting":8},
"name":"Lewis"},
"Bear Lake":
{"votes":[
{"votes":85,"name":"obama"},
{"votes":72,"name":"clinton"},
{"votes":7,"name":"judd"},
{"votes":2,"name":"uncommitted-d"}],
"total":166,"precincts":
{"total":14,"reporting":14},
"name":"Bear Lake"},
"Washington":
{"votes":[
{"votes":273,"name":"obama"},
{"votes":200,"name":"clinton"},
{"votes":20,"name":"uncommitted-d"},
{"votes":16,"name":"judd"}],
"total":509,"precincts":
{"total":11,"reporting":11},
"name":"Washington"},
"Elmore":
{"votes":[
{"votes":271,"name":"clinton"},
{"votes":259,"name":"obama"},
{"votes":34,"name":"uncommitted-d"},
{"votes":8,"name":"judd"}],
"total":572,"precincts":
{"total":18,"reporting":18},
"name":"Elmore"},
"Payette":
{"votes":[
{"votes":243,"name":"obama"},
{"votes":200,"name":"clinton"},
{"votes":18,"name":"uncommitted-d"},
{"votes":6,"name":"judd"}],
"total":467,"precincts":
{"total":10,"reporting":10},
"name":"Payette"},
"Blaine":
{"votes":[
{"votes":1177,"name":"obama"},
{"votes":336,"name":"clinton"},
{"votes":49,"name":"uncommitted-d"},
{"votes":6,"name":"judd"}],
"total":1568,"precincts":
{"total":15,"reporting":15},
"name":"Blaine"},
"Bonner":
{"votes":[
{"votes":890,"name":"obama"},
{"votes":551,"name":"clinton"},
{"votes":51,"name":"uncommitted-d"},
{"votes":17,"name":"judd"}],
"total":1509,"precincts":
{"total":33,"reporting":33},
"name":"Bonner"},
"Cassia":
{"votes":[
{"votes":92,"name":"clinton"},
{"votes":89,"name":"obama"},
{"votes":12,"name":"uncommitted-d"},
{"votes":6,"name":"judd"}],
"total":199,"precincts":
{"total":25,"reporting":25},
"name":"Cassia"},
"Minidoka":
{"votes":[
{"votes":145,"name":"clinton"},
{"votes":114,"name":"obama"},
{"votes":12,"name":"uncommitted-d"},
{"votes":7,"name":"judd"}],
"total":278,"precincts":
{"total":11,"reporting":11},
"name":"Minidoka"},
"Jerome":
{"votes":[
{"votes":139,"name":"obama"},
{"votes":135,"name":"clinton"},
{"votes":10,"name":"judd"},
{"votes":5,"name":"uncommitted-d"}],
"total":289,"precincts":
{"total":11,"reporting":11},
"name":"Jerome"},
"Shoshone":
{"votes":[
{"votes":1050,"name":"clinton"},
{"votes":964,"name":"obama"},
{"votes":464,"name":"uncommitted-d"},
{"votes":107,"name":"judd"}],
"total":2585,"precincts":
{"total":19,"reporting":19},
"name":"Shoshone"}}})