GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":9183,"name":"obama","delegates":15},
{"votes":6590,"name":"clinton","delegates":3},
{"votes":505,"name":"uncommitted-d"},
{"votes":234,"name":"judd"}],
"name":"Idaho","precincts":
{"total":940,"reporting":335},
"delegates":18,"date":"05-27"},
"state":"ID","party":"dem","total":16512,"locals":
{"Camas":
{"votes":[
{"votes":22,"name":"obama"},
{"votes":17,"name":"clinton"},
{"votes":3,"name":"judd"}],
"total":42,"precincts":
{"total":2,"reporting":2},
"name":"Camas"},
"Nez Perce":
{"votes":[
{"votes":55,"name":"obama"},
{"votes":33,"name":"clinton"},
{"votes":10,"name":"uncommitted-d"},
{"votes":2,"name":"judd"}],
"total":100,"precincts":
{"total":37,"reporting":4},
"name":"Nez Perce"},
"Gooding":
{"votes":[
{"votes":181,"name":"obama"},
{"votes":155,"name":"clinton"},
{"votes":21,"name":"uncommitted-d"},
{"votes":11,"name":"judd"}],
"total":368,"precincts":
{"total":7,"reporting":7},
"name":"Gooding"},
"Clearwater":
{"votes":[
{"votes":19,"name":"obama"},
{"votes":18,"name":"clinton"},
{"votes":1,"name":"judd"}],
"total":38,"precincts":
{"total":15,"reporting":3},
"name":"Clearwater"},
"Benewah":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Benewah"},
"Ada":
{"votes":[
{"votes":2192,"name":"obama"},
{"votes":1154,"name":"clinton"},
{"votes":92,"name":"uncommitted-d"},
{"votes":30,"name":"judd"}],
"total":3468,"precincts":
{"total":141,"reporting":26},
"name":"Ada"},
"Boundary":
{"votes":[
{"votes":53,"name":"obama"},
{"votes":21,"name":"clinton"}],
"total":74,"precincts":
{"total":7,"reporting":2},
"name":"Boundary"},
"Valley":
{"votes":[
{"votes":60,"name":"obama"},
{"votes":44,"name":"clinton"},
{"votes":2,"name":"uncommitted-d"}],
"total":106,"precincts":
{"total":9,"reporting":3},
"name":"Valley"},
"Teton":
{"votes":[
{"votes":282,"name":"obama"},
{"votes":106,"name":"clinton"},
{"votes":26,"name":"uncommitted-d"},
{"votes":1,"name":"judd"}],
"total":415,"precincts":
{"total":5,"reporting":3},
"name":"Teton"},
"Idaho":
{"votes":[
{"votes":15,"name":"clinton"},
{"votes":13,"name":"obama"},
{"votes":1,"name":"judd"}],
"total":29,"precincts":
{"total":27,"reporting":4},
"name":"Idaho"},
"Bingham":
{"votes":[
{"votes":101,"name":"obama"},
{"votes":93,"name":"clinton"},
{"votes":10,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":207,"precincts":
{"total":27,"reporting":3},
"name":"Bingham"},
"Owyhee":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Owyhee"},
"Custer":
{"votes":[
{"votes":99,"name":"obama"},
{"votes":66,"name":"clinton"},
{"votes":8,"name":"judd"},
{"votes":4,"name":"uncommitted-d"}],
"total":177,"precincts":
{"total":9,"reporting":8},
"name":"Custer"},
"Fremont":
{"votes":[
{"votes":82,"name":"obama"},
{"votes":60,"name":"clinton"},
{"votes":5,"name":"judd"}],
"total":147,"precincts":
{"total":14,"reporting":10},
"name":"Fremont"},
"Canyon":
{"votes":[
{"votes":604,"name":"obama"},
{"votes":479,"name":"clinton"},
{"votes":50,"name":"uncommitted-d"},
{"votes":18,"name":"judd"}],
"total":1151,"precincts":
{"total":53,"reporting":26},
"name":"Canyon"},
"Boise":
{"votes":[
{"votes":111,"name":"obama"},
{"votes":53,"name":"clinton"},
{"votes":3,"name":"judd"}],
"total":167,"precincts":
{"total":7,"reporting":7},
"name":"Boise"},
"Bonneville":
{"votes":[
{"votes":275,"name":"obama"},
{"votes":169,"name":"clinton"},
{"votes":21,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":468,"precincts":
{"total":52,"reporting":24},
"name":"Bonneville"},
"Butte":
{"votes":[
{"votes":2,"name":"clinton"},
{"votes":1,"name":"obama"}],
"total":3,"precincts":
{"total":4,"reporting":1},
"name":"Butte"},
"Twin Falls":
{"votes":[
{"votes":351,"name":"obama"},
{"votes":293,"name":"clinton"},
{"votes":13,"name":"uncommitted-d"},
{"votes":11,"name":"judd"}],
"total":668,"precincts":
{"total":45,"reporting":24},
"name":"Twin Falls"},
"Gem":
{"votes":[
{"votes":29,"name":"clinton"},
{"votes":26,"name":"obama"}],
"total":55,"precincts":
{"total":13,"reporting":1},
"name":"Gem"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":107,"name":"obama"},
{"votes":55,"name":"clinton"},
{"votes":1,"name":"judd"}],
"total":163,"precincts":
{"total":6,"reporting":6},
"name":"Adams"},
"Lemhi":
{"votes":[
{"votes":120,"name":"obama"},
{"votes":83,"name":"clinton"},
{"votes":5,"name":"uncommitted-d"}],
"total":208,"precincts":
{"total":9,"reporting":9},
"name":"Lemhi"},
"Oneida":
{"votes":[
{"votes":41,"name":"clinton"},
{"votes":29,"name":"obama"},
{"votes":1,"name":"judd"}],
"total":71,"precincts":
{"total":6,"reporting":6},
"name":"Oneida"},
"Bannock":
{"votes":[
{"votes":1394,"name":"obama"},
{"votes":1065,"name":"clinton"},
{"votes":70,"name":"judd"}],
"total":2529,"precincts":
{"total":58,"reporting":41},
"name":"Bannock"},
"Jefferson":
{"votes":[
{"votes":30,"name":"clinton"},
{"votes":16,"name":"obama"},
{"votes":3,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":52,"precincts":
{"total":18,"reporting":5},
"name":"Jefferson"},
"Franklin":
{"votes":[
{"votes":20,"name":"clinton"},
{"votes":16,"name":"obama"},
{"votes":3,"name":"uncommitted-d"},
{"votes":1,"name":"judd"}],
"total":40,"precincts":
{"total":17,"reporting":8},
"name":"Franklin"},
"Caribou":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Caribou"},
"Latah":
{"votes":[
{"votes":106,"name":"obama"},
{"votes":62,"name":"clinton"},
{"votes":6,"name":"uncommitted-d"},
{"votes":2,"name":"judd"}],
"total":176,"precincts":
{"total":33,"reporting":5},
"name":"Latah"},
"Madison":
{"votes":[
{"votes":29,"name":"obama"},
{"votes":23,"name":"clinton"},
{"votes":8,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":63,"precincts":
{"total":19,"reporting":8},
"name":"Madison"},
"Kootenai":
{"votes":[
{"votes":1814,"name":"obama"},
{"votes":1493,"name":"clinton"},
{"votes":74,"name":"uncommitted-d"},
{"votes":4,"name":"judd"}],
"total":3385,"precincts":
{"total":75,"reporting":25},
"name":"Kootenai"},
"Power":
{"votes":[
{"votes":134,"name":"obama"},
{"votes":86,"name":"clinton"},
{"votes":12,"name":"uncommitted-d"},
{"votes":4,"name":"judd"}],
"total":236,"precincts":
{"total":7,"reporting":7},
"name":"Power"},
"Clark":
{"votes":[
{"votes":8,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":3,"name":"judd"},
{"votes":2,"name":"uncommitted-d"}],
"total":17,"precincts":
{"total":3,"reporting":3},
"name":"Clark"},
"Lewis":
{"votes":[
{"votes":76,"name":"obama"},
{"votes":73,"name":"clinton"},
{"votes":6,"name":"judd"},
{"votes":3,"name":"uncommitted-d"}],
"total":158,"precincts":
{"total":8,"reporting":5},
"name":"Lewis"},
"Bear Lake":
{"votes":[
{"votes":40,"name":"obama"},
{"votes":29,"name":"clinton"},
{"votes":3,"name":"judd"},
{"votes":1,"name":"uncommitted-d"}],
"total":73,"precincts":
{"total":14,"reporting":8},
"name":"Bear Lake"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Washington"},
"Elmore":
{"votes":[
{"votes":187,"name":"clinton"},
{"votes":173,"name":"obama"},
{"votes":29,"name":"uncommitted-d"},
{"votes":4,"name":"judd"}],
"total":393,"precincts":
{"total":18,"reporting":9},
"name":"Elmore"},
"Payette":
{"votes":[
{"votes":243,"name":"obama"},
{"votes":200,"name":"clinton"},
{"votes":18,"name":"uncommitted-d"},
{"votes":6,"name":"judd"}],
"total":467,"precincts":
{"total":10,"reporting":10},
"name":"Payette"},
"Blaine":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Blaine"},
"Bonner":
{"votes":[
{"votes":93,"name":"obama"},
{"votes":51,"name":"clinton"},
{"votes":3,"name":"uncommitted-d"},
{"votes":2,"name":"judd"}],
"total":149,"precincts":
{"total":33,"reporting":4},
"name":"Bonner"},
"Cassia":
{"votes":[
{"votes":20,"name":"obama"},
{"votes":19,"name":"clinton"},
{"votes":3,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":45,"precincts":
{"total":25,"reporting":10},
"name":"Cassia"},
"Minidoka":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Minidoka"},
"Jerome":
{"votes":[
{"votes":24,"name":"clinton"},
{"votes":19,"name":"obama"},
{"votes":1,"name":"uncommitted-d"}],
"total":44,"precincts":
{"total":11,"reporting":2},
"name":"Jerome"},
"Shoshone":
{"votes":[
{"votes":238,"name":"clinton"},
{"votes":219,"name":"obama"},
{"votes":85,"name":"uncommitted-d"},
{"votes":18,"name":"judd"}],
"total":560,"precincts":
{"total":19,"reporting":6},
"name":"Shoshone"}}})