GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":80490,"name":"mccain"},
{"votes":26815,"name":"paul"},
{"votes":7180,"name":"uncommitted-r"}],
"name":"Idaho","precincts":
{"total":940,"reporting":841},
"delegates":32,"date":"05-27"},
"state":"ID","party":"gop","total":114485,"locals":
{"Camas":
{"votes":[
{"votes":216,"name":"mccain"},
{"votes":73,"name":"paul"}],
"total":289,"precincts":
{"total":2,"reporting":2},
"name":"Camas"},
"Nez Perce":
{"votes":[
{"votes":1470,"name":"mccain"},
{"votes":325,"name":"paul"},
{"votes":107,"name":"uncommitted-r"}],
"total":1902,"precincts":
{"total":37,"reporting":37},
"name":"Nez Perce"},
"Gooding":
{"votes":[
{"votes":1318,"name":"mccain"},
{"votes":331,"name":"paul"},
{"votes":133,"name":"uncommitted-r"}],
"total":1782,"precincts":
{"total":7,"reporting":7},
"name":"Gooding"},
"Clearwater":
{"votes":[
{"votes":401,"name":"mccain"},
{"votes":107,"name":"paul"},
{"votes":34,"name":"uncommitted-r"}],
"total":542,"precincts":
{"total":15,"reporting":15},
"name":"Clearwater"},
"Benewah":
{"votes":[
{"votes":372,"name":"mccain"},
{"votes":199,"name":"paul"},
{"votes":11,"name":"uncommitted-r"}],
"total":582,"precincts":
{"total":11,"reporting":11},
"name":"Benewah"},
"Ada":
{"votes":[
{"votes":12678,"name":"mccain"},
{"votes":4360,"name":"paul"},
{"votes":1170,"name":"uncommitted-r"}],
"total":18208,"precincts":
{"total":141,"reporting":91},
"name":"Ada"},
"Boundary":
{"votes":[
{"votes":879,"name":"mccain"},
{"votes":576,"name":"paul"}],
"total":1455,"precincts":
{"total":7,"reporting":7},
"name":"Boundary"},
"Valley":
{"votes":[
{"votes":1156,"name":"mccain"},
{"votes":440,"name":"paul"},
{"votes":173,"name":"uncommitted-r"}],
"total":1769,"precincts":
{"total":9,"reporting":9},
"name":"Valley"},
"Teton":
{"votes":[
{"votes":542,"name":"mccain"},
{"votes":127,"name":"paul"},
{"votes":61,"name":"uncommitted-r"}],
"total":730,"precincts":
{"total":5,"reporting":5},
"name":"Teton"},
"Idaho":
{"votes":[
{"votes":1724,"name":"mccain"},
{"votes":921,"name":"paul"}],
"total":2645,"precincts":
{"total":27,"reporting":27},
"name":"Idaho"},
"Bingham":
{"votes":[
{"votes":2558,"name":"mccain"},
{"votes":533,"name":"paul"},
{"votes":385,"name":"uncommitted-r"}],
"total":3476,"precincts":
{"total":27,"reporting":15},
"name":"Bingham"},
"Owyhee":
{"votes":[
{"votes":1175,"name":"mccain"},
{"votes":384,"name":"paul"},
{"votes":19,"name":"uncommitted-r"}],
"total":1578,"precincts":
{"total":13,"reporting":13},
"name":"Owyhee"},
"Custer":
{"votes":[
{"votes":648,"name":"mccain"},
{"votes":230,"name":"paul"},
{"votes":33,"name":"uncommitted-r"}],
"total":911,"precincts":
{"total":9,"reporting":9},
"name":"Custer"},
"Fremont":
{"votes":[
{"votes":2221,"name":"mccain"},
{"votes":493,"name":"paul"}],
"total":2714,"precincts":
{"total":14,"reporting":14},
"name":"Fremont"},
"Canyon":
{"votes":[
{"votes":7553,"name":"mccain"},
{"votes":3363,"name":"paul"},
{"votes":1228,"name":"uncommitted-r"}],
"total":12144,"precincts":
{"total":53,"reporting":53},
"name":"Canyon"},
"Boise":
{"votes":[
{"votes":992,"name":"mccain"},
{"votes":461,"name":"paul"},
{"votes":27,"name":"uncommitted-r"}],
"total":1480,"precincts":
{"total":7,"reporting":7},
"name":"Boise"},
"Bonneville":
{"votes":[
{"votes":4403,"name":"mccain"},
{"votes":1270,"name":"paul"},
{"votes":554,"name":"uncommitted-r"}],
"total":6227,"precincts":
{"total":52,"reporting":52},
"name":"Bonneville"},
"Butte":
{"votes":[
{"votes":614,"name":"mccain"},
{"votes":150,"name":"paul"}],
"total":764,"precincts":
{"total":4,"reporting":4},
"name":"Butte"},
"Twin Falls":
{"votes":[
{"votes":3424,"name":"mccain"},
{"votes":1073,"name":"paul"},
{"votes":203,"name":"uncommitted-r"}],
"total":4700,"precincts":
{"total":45,"reporting":45},
"name":"Twin Falls"},
"Gem":
{"votes":[
{"votes":520,"name":"mccain"},
{"votes":186,"name":"paul"},
{"votes":65,"name":"uncommitted-r"}],
"total":771,"precincts":
{"total":13,"reporting":5},
"name":"Gem"},
"Lincoln":
{"votes":[
{"votes":578,"name":"mccain"},
{"votes":137,"name":"paul"},
{"votes":33,"name":"uncommitted-r"}],
"total":748,"precincts":
{"total":6,"reporting":6},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":724,"name":"mccain"},
{"votes":304,"name":"paul"},
{"votes":9,"name":"uncommitted-r"}],
"total":1037,"precincts":
{"total":6,"reporting":6},
"name":"Adams"},
"Lemhi":
{"votes":[
{"votes":1245,"name":"mccain"},
{"votes":379,"name":"paul"},
{"votes":155,"name":"uncommitted-r"}],
"total":1779,"precincts":
{"total":9,"reporting":9},
"name":"Lemhi"},
"Oneida":
{"votes":[
{"votes":992,"name":"mccain"},
{"votes":256,"name":"paul"}],
"total":1248,"precincts":
{"total":6,"reporting":6},
"name":"Oneida"},
"Bannock":
{"votes":[
{"votes":1927,"name":"mccain"},
{"votes":672,"name":"paul"},
{"votes":98,"name":"uncommitted-r"}],
"total":2697,"precincts":
{"total":58,"reporting":58},
"name":"Bannock"},
"Jefferson":
{"votes":[
{"votes":1214,"name":"mccain"},
{"votes":408,"name":"paul"},
{"votes":94,"name":"uncommitted-r"}],
"total":1716,"precincts":
{"total":18,"reporting":18},
"name":"Jefferson"},
"Franklin":
{"votes":[
{"votes":1663,"name":"mccain"},
{"votes":230,"name":"paul"},
{"votes":226,"name":"uncommitted-r"}],
"total":2119,"precincts":
{"total":17,"reporting":17},
"name":"Franklin"},
"Caribou":
{"votes":[
{"votes":1596,"name":"mccain"},
{"votes":257,"name":"paul"},
{"votes":61,"name":"uncommitted-r"}],
"total":1914,"precincts":
{"total":10,"reporting":10},
"name":"Caribou"},
"Latah":
{"votes":[
{"votes":746,"name":"mccain"},
{"votes":302,"name":"paul"},
{"votes":76,"name":"uncommitted-r"}],
"total":1124,"precincts":
{"total":33,"reporting":33},
"name":"Latah"},
"Madison":
{"votes":[
{"votes":2935,"name":"mccain"},
{"votes":651,"name":"paul"},
{"votes":314,"name":"uncommitted-r"}],
"total":3900,"precincts":
{"total":19,"reporting":19},
"name":"Madison"},
"Kootenai":
{"votes":[
{"votes":8785,"name":"mccain"},
{"votes":3560,"name":"paul"},
{"votes":748,"name":"uncommitted-r"}],
"total":13093,"precincts":
{"total":75,"reporting":53},
"name":"Kootenai"},
"Power":
{"votes":[
{"votes":236,"name":"mccain"},
{"votes":60,"name":"paul"},
{"votes":21,"name":"uncommitted-r"}],
"total":317,"precincts":
{"total":7,"reporting":7},
"name":"Power"},
"Clark":
{"votes":[
{"votes":200,"name":"mccain"},
{"votes":26,"name":"paul"},
{"votes":10,"name":"uncommitted-r"}],
"total":236,"precincts":
{"total":3,"reporting":3},
"name":"Clark"},
"Lewis":
{"votes":[
{"votes":412,"name":"mccain"},
{"votes":151,"name":"paul"},
{"votes":15,"name":"uncommitted-r"}],
"total":578,"precincts":
{"total":8,"reporting":8},
"name":"Lewis"},
"Bear Lake":
{"votes":[
{"votes":1121,"name":"mccain"},
{"votes":171,"name":"paul"},
{"votes":23,"name":"uncommitted-r"}],
"total":1315,"precincts":
{"total":14,"reporting":14},
"name":"Bear Lake"},
"Washington":
{"votes":[
{"votes":1115,"name":"mccain"},
{"votes":388,"name":"paul"},
{"votes":42,"name":"uncommitted-r"}],
"total":1545,"precincts":
{"total":11,"reporting":11},
"name":"Washington"},
"Elmore":
{"votes":[
{"votes":1225,"name":"mccain"},
{"votes":345,"name":"paul"},
{"votes":118,"name":"uncommitted-r"}],
"total":1688,"precincts":
{"total":18,"reporting":18},
"name":"Elmore"},
"Payette":
{"votes":[
{"votes":976,"name":"mccain"},
{"votes":439,"name":"paul"},
{"votes":45,"name":"uncommitted-r"}],
"total":1460,"precincts":
{"total":10,"reporting":10},
"name":"Payette"},
"Blaine":
{"votes":[
{"votes":650,"name":"mccain"},
{"votes":109,"name":"paul"},
{"votes":21,"name":"uncommitted-r"}],
"total":780,"precincts":
{"total":15,"reporting":15},
"name":"Blaine"},
"Bonner":
{"votes":[
{"votes":1904,"name":"mccain"},
{"votes":959,"name":"paul"},
{"votes":271,"name":"uncommitted-r"}],
"total":3134,"precincts":
{"total":33,"reporting":26},
"name":"Bonner"},
"Cassia":
{"votes":[
{"votes":2184,"name":"mccain"},
{"votes":501,"name":"paul"},
{"votes":247,"name":"uncommitted-r"}],
"total":2932,"precincts":
{"total":25,"reporting":25},
"name":"Cassia"},
"Minidoka":
{"votes":[
{"votes":1338,"name":"mccain"},
{"votes":349,"name":"paul"},
{"votes":215,"name":"uncommitted-r"}],
"total":1902,"precincts":
{"total":11,"reporting":11},
"name":"Minidoka"},
"Jerome":
{"votes":[
{"votes":1512,"name":"mccain"},
{"votes":433,"name":"paul"},
{"votes":113,"name":"uncommitted-r"}],
"total":2058,"precincts":
{"total":11,"reporting":11},
"name":"Jerome"},
"Shoshone":
{"votes":[
{"votes":348,"name":"mccain"},
{"votes":126,"name":"paul"},
{"votes":22,"name":"uncommitted-r"}],
"total":496,"precincts":
{"total":19,"reporting":19},
"name":"Shoshone"}}})