GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":232630,"name":"clinton","delegates":49},
{"votes":180153,"name":"obama","delegates":44}],
"name":"Indiana","precincts":
{"total":5230,"reporting":1968},
"delegates":72,"date":"05-06"},
"state":"IN","party":"dem","total":412783,"locals":
{"Daviess":
{"votes":[
{"votes":894,"name":"clinton"},
{"votes":547,"name":"obama"}],
"total":1441,"precincts":
{"total":28,"reporting":10},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":4350,"name":"clinton"},
{"votes":2321,"name":"obama"}],
"total":6671,"precincts":
{"total":39,"reporting":39},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":277,"name":"obama"},
{"votes":195,"name":"clinton"}],
"total":472,"precincts":
{"total":27,"reporting":3},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Wayne"},
"Wabash":
{"votes":[
{"votes":2769,"name":"clinton"},
{"votes":2095,"name":"obama"}],
"total":4864,"precincts":
{"total":25,"reporting":25},
"name":"Wabash"},
"White":
{"votes":[
{"votes":710,"name":"clinton"},
{"votes":489,"name":"obama"}],
"total":1199,"precincts":
{"total":23,"reporting":5},
"name":"White"},
"Porter":
{"votes":[],
"total":0,"precincts":
{"total":128,"reporting":0},
"name":"Porter"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Brown"},
"LaPorte":
{"votes":[],
"total":0,"precincts":
{"total":79,"reporting":0},
"name":"LaPorte"},
"Jay":
{"votes":[
{"votes":2256,"name":"clinton"},
{"votes":1379,"name":"obama"}],
"total":3635,"precincts":
{"total":21,"reporting":21},
"name":"Jay"},
"Jennings":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Jennings"},
"Dearborn":
{"votes":[
{"votes":4811,"name":"clinton"},
{"votes":1629,"name":"obama"}],
"total":6440,"precincts":
{"total":45,"reporting":42},
"name":"Dearborn"},
"Miami":
{"votes":[
{"votes":2876,"name":"clinton"},
{"votes":1748,"name":"obama"}],
"total":4624,"precincts":
{"total":31,"reporting":30},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":2684,"name":"clinton"},
{"votes":1628,"name":"obama"}],
"total":4312,"precincts":
{"total":38,"reporting":18},
"name":"Hancock"},
"Henry":
{"votes":[
{"votes":5153,"name":"clinton"},
{"votes":2707,"name":"obama"}],
"total":7860,"precincts":
{"total":42,"reporting":35},
"name":"Henry"},
"Vigo":
{"votes":[
{"votes":15985,"name":"clinton"},
{"votes":10943,"name":"obama"}],
"total":26928,"precincts":
{"total":87,"reporting":87},
"name":"Vigo"},
"Sullivan":
{"votes":[
{"votes":3511,"name":"clinton"},
{"votes":1724,"name":"obama"}],
"total":5235,"precincts":
{"total":20,"reporting":19},
"name":"Sullivan"},
"Dubois":
{"votes":[
{"votes":3831,"name":"clinton"},
{"votes":3095,"name":"obama"}],
"total":6926,"precincts":
{"total":38,"reporting":26},
"name":"Dubois"},
"Newton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":355,"name":"clinton"},
{"votes":135,"name":"obama"}],
"total":490,"precincts":
{"total":22,"reporting":3},
"name":"Washington"},
"Decatur":
{"votes":[
{"votes":763,"name":"clinton"},
{"votes":372,"name":"obama"}],
"total":1135,"precincts":
{"total":20,"reporting":5},
"name":"Decatur"},
"Marion":
{"votes":[
{"votes":26473,"name":"obama"},
{"votes":17261,"name":"clinton"}],
"total":43734,"precincts":
{"total":594,"reporting":183},
"name":"Marion"},
"Jasper":
{"votes":[
{"votes":904,"name":"clinton"},
{"votes":632,"name":"obama"}],
"total":1536,"precincts":
{"total":29,"reporting":13},
"name":"Jasper"},
"Vermillion":
{"votes":[
{"votes":481,"name":"clinton"},
{"votes":260,"name":"obama"}],
"total":741,"precincts":
{"total":17,"reporting":3},
"name":"Vermillion"},
"Allen":
{"votes":[
{"votes":31257,"name":"obama"},
{"votes":25627,"name":"clinton"}],
"total":56884,"precincts":
{"total":294,"reporting":258},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":736,"name":"clinton"},
{"votes":593,"name":"obama"}],
"total":1329,"precincts":
{"total":13,"reporting":12},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":1337,"name":"clinton"},
{"votes":688,"name":"obama"}],
"total":2025,"precincts":
{"total":21,"reporting":5},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":5462,"name":"clinton"},
{"votes":4150,"name":"obama"}],
"total":9612,"precincts":
{"total":71,"reporting":42},
"name":"Howard"},
"Jefferson":
{"votes":[
{"votes":4429,"name":"clinton"},
{"votes":2332,"name":"obama"}],
"total":6761,"precincts":
{"total":26,"reporting":26},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":2188,"name":"clinton"},
{"votes":998,"name":"obama"}],
"total":3186,"precincts":
{"total":22,"reporting":22},
"name":"Orange"},
"St. Joseph":
{"votes":[],
"total":0,"precincts":
{"total":226,"reporting":0},
"name":"St. Joseph"},
"Putnam":
{"votes":[
{"votes":1680,"name":"clinton"},
{"votes":1476,"name":"obama"}],
"total":3156,"precincts":
{"total":29,"reporting":17},
"name":"Putnam"},
"Hamilton":
{"votes":[],
"total":0,"precincts":
{"total":196,"reporting":0},
"name":"Hamilton"},
"Kosciusko":
{"votes":[
{"votes":3896,"name":"clinton"},
{"votes":3607,"name":"obama"}],
"total":7503,"precincts":
{"total":65,"reporting":47},
"name":"Kosciusko"},
"Rush":
{"votes":[
{"votes":1162,"name":"clinton"},
{"votes":761,"name":"obama"}],
"total":1923,"precincts":
{"total":20,"reporting":11},
"name":"Rush"},
"Johnson":
{"votes":[
{"votes":7506,"name":"clinton"},
{"votes":5938,"name":"obama"}],
"total":13444,"precincts":
{"total":107,"reporting":75},
"name":"Johnson"},
"Whitley":
{"votes":[
{"votes":2964,"name":"clinton"},
{"votes":2106,"name":"obama"}],
"total":5070,"precincts":
{"total":34,"reporting":34},
"name":"Whitley"},
"Greene":
{"votes":[
{"votes":908,"name":"clinton"},
{"votes":445,"name":"obama"}],
"total":1353,"precincts":
{"total":32,"reporting":5},
"name":"Greene"},
"Ripley":
{"votes":[
{"votes":2695,"name":"clinton"},
{"votes":1275,"name":"obama"}],
"total":3970,"precincts":
{"total":27,"reporting":25},
"name":"Ripley"},
"LaGrange":
{"votes":[
{"votes":721,"name":"clinton"},
{"votes":571,"name":"obama"}],
"total":1292,"precincts":
{"total":16,"reporting":5},
"name":"LaGrange"},
"Ohio":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Ohio"},
"Gibson":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Gibson"},
"Spencer":
{"votes":[
{"votes":862,"name":"clinton"},
{"votes":422,"name":"obama"}],
"total":1284,"precincts":
{"total":25,"reporting":6},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":816,"name":"clinton"},
{"votes":536,"name":"obama"}],
"total":1352,"precincts":
{"total":17,"reporting":6},
"name":"Fulton"},
"Madison":
{"votes":[
{"votes":6960,"name":"clinton"},
{"votes":5759,"name":"obama"}],
"total":12719,"precincts":
{"total":111,"reporting":56},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":2458,"name":"clinton"},
{"votes":1644,"name":"obama"}],
"total":4102,"precincts":
{"total":39,"reporting":36},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":13893,"name":"clinton"},
{"votes":6858,"name":"obama"}],
"total":20751,"precincts":
{"total":73,"reporting":59},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":83,"name":"clinton"},
{"votes":81,"name":"obama"}],
"total":164,"precincts":
{"total":20,"reporting":1},
"name":"Owen"},
"Huntington":
{"votes":[
{"votes":1804,"name":"clinton"},
{"votes":1345,"name":"obama"}],
"total":3149,"precincts":
{"total":34,"reporting":22},
"name":"Huntington"},
"Clay":
{"votes":[
{"votes":3032,"name":"clinton"},
{"votes":1520,"name":"obama"}],
"total":4552,"precincts":
{"total":23,"reporting":17},
"name":"Clay"},
"Blackford":
{"votes":[
{"votes":1940,"name":"clinton"},
{"votes":1024,"name":"obama"}],
"total":2964,"precincts":
{"total":12,"reporting":12},
"name":"Blackford"},
"Cass":
{"votes":[
{"votes":3685,"name":"clinton"},
{"votes":2338,"name":"obama"}],
"total":6023,"precincts":
{"total":39,"reporting":31},
"name":"Cass"},
"Delaware":
{"votes":[
{"votes":3134,"name":"clinton"},
{"votes":2651,"name":"obama"}],
"total":5785,"precincts":
{"total":75,"reporting":8},
"name":"Delaware"},
"Fountain":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Fountain"},
"Lawrence":
{"votes":[
{"votes":1566,"name":"clinton"},
{"votes":853,"name":"obama"}],
"total":2419,"precincts":
{"total":39,"reporting":17},
"name":"Lawrence"},
"Elkhart":
{"votes":[],
"total":0,"precincts":
{"total":110,"reporting":0},
"name":"Elkhart"},
"Grant":
{"votes":[
{"votes":334,"name":"clinton"},
{"votes":186,"name":"obama"}],
"total":520,"precincts":
{"total":68,"reporting":1},
"name":"Grant"},
"Fayette":
{"votes":[
{"votes":419,"name":"clinton"},
{"votes":127,"name":"obama"}],
"total":546,"precincts":
{"total":28,"reporting":0},
"name":"Fayette"},
"Posey":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Posey"},
"Floyd":
{"votes":[
{"votes":11241,"name":"clinton"},
{"votes":5739,"name":"obama"}],
"total":16980,"precincts":
{"total":60,"reporting":55},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":2467,"name":"clinton"},
{"votes":1077,"name":"obama"}],
"total":3544,"precincts":
{"total":18,"reporting":18},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":931,"name":"clinton"},
{"votes":704,"name":"obama"}],
"total":1635,"precincts":
{"total":25,"reporting":7},
"name":"Adams"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Franklin"},
"Switzerland":
{"votes":[
{"votes":1464,"name":"clinton"},
{"votes":486,"name":"obama"}],
"total":1950,"precincts":
{"total":12,"reporting":12},
"name":"Switzerland"},
"Vanderburgh":
{"votes":[],
"total":0,"precincts":
{"total":131,"reporting":0},
"name":"Vanderburgh"},
"Marshall":
{"votes":[
{"votes":4267,"name":"clinton"},
{"votes":3157,"name":"obama"}],
"total":7424,"precincts":
{"total":27,"reporting":27},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":1579,"name":"clinton"},
{"votes":1301,"name":"obama"}],
"total":2880,"precincts":
{"total":19,"reporting":16},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":1114,"name":"clinton"},
{"votes":417,"name":"obama"}],
"total":1531,"precincts":
{"total":36,"reporting":8},
"name":"Harrison"},
"Boone":
{"votes":[
{"votes":4846,"name":"obama"},
{"votes":4453,"name":"clinton"}],
"total":9299,"precincts":
{"total":49,"reporting":49},
"name":"Boone"},
"Starke":
{"votes":[
{"votes":1444,"name":"clinton"},
{"votes":561,"name":"obama"}],
"total":2005,"precincts":
{"total":21,"reporting":7},
"name":"Starke"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":559,"reporting":0},
"name":"Lake"},
"Pulaski":
{"votes":[
{"votes":1409,"name":"clinton"},
{"votes":911,"name":"obama"}],
"total":2320,"precincts":
{"total":15,"reporting":15},
"name":"Pulaski"},
"Hendricks":
{"votes":[],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Hendricks"},
"Tippecanoe":
{"votes":[
{"votes":521,"name":"obama"},
{"votes":421,"name":"clinton"}],
"total":942,"precincts":
{"total":91,"reporting":91},
"name":"Tippecanoe"},
"Parke":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Parke"},
"DeKalb":
{"votes":[
{"votes":1809,"name":"clinton"},
{"votes":1380,"name":"obama"}],
"total":3189,"precincts":
{"total":39,"reporting":21},
"name":"DeKalb"},
"Crawford":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Crawford"},
"Noble":
{"votes":[
{"votes":2667,"name":"clinton"},
{"votes":1737,"name":"obama"}],
"total":4404,"precincts":
{"total":29,"reporting":18},
"name":"Noble"},
"Wells":
{"votes":[
{"votes":2613,"name":"clinton"},
{"votes":1907,"name":"obama"}],
"total":4520,"precincts":
{"total":22,"reporting":22},
"name":"Wells"},
"Knox":
{"votes":[
{"votes":6407,"name":"clinton"},
{"votes":3260,"name":"obama"}],
"total":9667,"precincts":
{"total":36,"reporting":36},
"name":"Knox"},
"Bartholomew":
{"votes":[
{"votes":5434,"name":"clinton"},
{"votes":4684,"name":"obama"}],
"total":10118,"precincts":
{"total":67,"reporting":52},
"name":"Bartholomew"},
"Tipton":
{"votes":[
{"votes":1848,"name":"clinton"},
{"votes":1324,"name":"obama"}],
"total":3172,"precincts":
{"total":17,"reporting":17},
"name":"Tipton"},
"Benton":
{"votes":[
{"votes":168,"name":"clinton"},
{"votes":156,"name":"obama"}],
"total":324,"precincts":
{"total":15,"reporting":5},
"name":"Benton"},
"Morgan":
{"votes":[
{"votes":1324,"name":"clinton"},
{"votes":769,"name":"obama"}],
"total":2093,"precincts":
{"total":48,"reporting":17},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Martin"},
"Warrick":
{"votes":[
{"votes":1866,"name":"clinton"},
{"votes":1233,"name":"obama"}],
"total":3099,"precincts":
{"total":59,"reporting":7},
"name":"Warrick"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Scott"},
"Randolph":
{"votes":[
{"votes":2846,"name":"clinton"},
{"votes":1748,"name":"obama"}],
"total":4594,"precincts":
{"total":29,"reporting":29},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":217,"name":"obama"},
{"votes":88,"name":"clinton"}],
"total":305,"precincts":
{"total":71,"reporting":1},
"name":"Monroe"},
"Steuben":
{"votes":[
{"votes":2684,"name":"clinton"},
{"votes":2023,"name":"obama"}],
"total":4707,"precincts":
{"total":19,"reporting":15},
"name":"Steuben"}}})