GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":318436,"name":"clinton","delegates":49},
{"votes":261661,"name":"obama","delegates":44}],
"name":"Indiana","precincts":
{"total":5230,"reporting":2590},
"delegates":72,"date":"05-06"},
"state":"IN","party":"dem","total":580097,"locals":
{"Daviess":
{"votes":[
{"votes":1958,"name":"clinton"},
{"votes":1300,"name":"obama"}],
"total":3258,"precincts":
{"total":28,"reporting":24},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":4350,"name":"clinton"},
{"votes":2321,"name":"obama"}],
"total":6671,"precincts":
{"total":39,"reporting":39},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":476,"name":"obama"},
{"votes":406,"name":"clinton"}],
"total":882,"precincts":
{"total":27,"reporting":7},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Wayne"},
"Wabash":
{"votes":[
{"votes":2769,"name":"clinton"},
{"votes":2095,"name":"obama"}],
"total":4864,"precincts":
{"total":25,"reporting":25},
"name":"Wabash"},
"White":
{"votes":[
{"votes":710,"name":"clinton"},
{"votes":489,"name":"obama"}],
"total":1199,"precincts":
{"total":23,"reporting":5},
"name":"White"},
"Porter":
{"votes":[],
"total":0,"precincts":
{"total":128,"reporting":0},
"name":"Porter"},
"Brown":
{"votes":[
{"votes":1637,"name":"obama"},
{"votes":1559,"name":"clinton"}],
"total":3196,"precincts":
{"total":12,"reporting":10},
"name":"Brown"},
"LaPorte":
{"votes":[],
"total":0,"precincts":
{"total":79,"reporting":0},
"name":"LaPorte"},
"Jay":
{"votes":[
{"votes":2256,"name":"clinton"},
{"votes":1379,"name":"obama"}],
"total":3635,"precincts":
{"total":21,"reporting":21},
"name":"Jay"},
"Jennings":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Jennings"},
"Dearborn":
{"votes":[
{"votes":5270,"name":"clinton"},
{"votes":1782,"name":"obama"}],
"total":7052,"precincts":
{"total":45,"reporting":45},
"name":"Dearborn"},
"Miami":
{"votes":[
{"votes":2876,"name":"clinton"},
{"votes":1748,"name":"obama"}],
"total":4624,"precincts":
{"total":31,"reporting":30},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":2684,"name":"clinton"},
{"votes":1628,"name":"obama"}],
"total":4312,"precincts":
{"total":38,"reporting":18},
"name":"Hancock"},
"Henry":
{"votes":[
{"votes":6724,"name":"clinton"},
{"votes":3493,"name":"obama"}],
"total":10217,"precincts":
{"total":42,"reporting":42},
"name":"Henry"},
"Vigo":
{"votes":[
{"votes":15985,"name":"clinton"},
{"votes":10943,"name":"obama"}],
"total":26928,"precincts":
{"total":87,"reporting":87},
"name":"Vigo"},
"Sullivan":
{"votes":[
{"votes":3652,"name":"clinton"},
{"votes":1796,"name":"obama"}],
"total":5448,"precincts":
{"total":20,"reporting":20},
"name":"Sullivan"},
"Dubois":
{"votes":[
{"votes":3831,"name":"clinton"},
{"votes":3095,"name":"obama"}],
"total":6926,"precincts":
{"total":38,"reporting":26},
"name":"Dubois"},
"Newton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":1379,"name":"clinton"},
{"votes":449,"name":"obama"}],
"total":1828,"precincts":
{"total":22,"reporting":8},
"name":"Washington"},
"Decatur":
{"votes":[
{"votes":2326,"name":"clinton"},
{"votes":1274,"name":"obama"}],
"total":3600,"precincts":
{"total":20,"reporting":20},
"name":"Decatur"},
"Marion":
{"votes":[
{"votes":42394,"name":"obama"},
{"votes":25024,"name":"clinton"}],
"total":67418,"precincts":
{"total":594,"reporting":278},
"name":"Marion"},
"Jasper":
{"votes":[
{"votes":904,"name":"clinton"},
{"votes":632,"name":"obama"}],
"total":1536,"precincts":
{"total":29,"reporting":13},
"name":"Jasper"},
"Vermillion":
{"votes":[
{"votes":1066,"name":"clinton"},
{"votes":559,"name":"obama"}],
"total":1625,"precincts":
{"total":17,"reporting":6},
"name":"Vermillion"},
"Allen":
{"votes":[
{"votes":32689,"name":"obama"},
{"votes":26551,"name":"clinton"}],
"total":59240,"precincts":
{"total":294,"reporting":271},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":736,"name":"clinton"},
{"votes":593,"name":"obama"}],
"total":1329,"precincts":
{"total":13,"reporting":12},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":2099,"name":"clinton"},
{"votes":1074,"name":"obama"}],
"total":3173,"precincts":
{"total":21,"reporting":11},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":5462,"name":"clinton"},
{"votes":4150,"name":"obama"}],
"total":9612,"precincts":
{"total":71,"reporting":42},
"name":"Howard"},
"Jefferson":
{"votes":[
{"votes":4429,"name":"clinton"},
{"votes":2332,"name":"obama"}],
"total":6761,"precincts":
{"total":26,"reporting":26},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":2188,"name":"clinton"},
{"votes":998,"name":"obama"}],
"total":3186,"precincts":
{"total":22,"reporting":22},
"name":"Orange"},
"St. Joseph":
{"votes":[],
"total":0,"precincts":
{"total":226,"reporting":0},
"name":"St. Joseph"},
"Putnam":
{"votes":[
{"votes":2705,"name":"clinton"},
{"votes":2072,"name":"obama"}],
"total":4777,"precincts":
{"total":29,"reporting":24},
"name":"Putnam"},
"Hamilton":
{"votes":[
{"votes":3767,"name":"obama"},
{"votes":2258,"name":"clinton"}],
"total":6025,"precincts":
{"total":196,"reporting":10},
"name":"Hamilton"},
"Kosciusko":
{"votes":[
{"votes":4528,"name":"clinton"},
{"votes":4169,"name":"obama"}],
"total":8697,"precincts":
{"total":65,"reporting":65},
"name":"Kosciusko"},
"Rush":
{"votes":[
{"votes":1613,"name":"clinton"},
{"votes":1075,"name":"obama"}],
"total":2688,"precincts":
{"total":20,"reporting":16},
"name":"Rush"},
"Johnson":
{"votes":[
{"votes":10832,"name":"clinton"},
{"votes":8672,"name":"obama"}],
"total":19504,"precincts":
{"total":107,"reporting":103},
"name":"Johnson"},
"Whitley":
{"votes":[
{"votes":2964,"name":"clinton"},
{"votes":2106,"name":"obama"}],
"total":5070,"precincts":
{"total":34,"reporting":34},
"name":"Whitley"},
"Greene":
{"votes":[
{"votes":4326,"name":"clinton"},
{"votes":2343,"name":"obama"}],
"total":6669,"precincts":
{"total":32,"reporting":32},
"name":"Greene"},
"Ripley":
{"votes":[
{"votes":2946,"name":"clinton"},
{"votes":1375,"name":"obama"}],
"total":4321,"precincts":
{"total":27,"reporting":27},
"name":"Ripley"},
"LaGrange":
{"votes":[
{"votes":1205,"name":"clinton"},
{"votes":914,"name":"obama"}],
"total":2119,"precincts":
{"total":16,"reporting":9},
"name":"LaGrange"},
"Ohio":
{"votes":[
{"votes":857,"name":"clinton"},
{"votes":279,"name":"obama"}],
"total":1136,"precincts":
{"total":11,"reporting":11},
"name":"Ohio"},
"Gibson":
{"votes":[
{"votes":174,"name":"clinton"},
{"votes":76,"name":"obama"}],
"total":250,"precincts":
{"total":38,"reporting":1},
"name":"Gibson"},
"Spencer":
{"votes":[
{"votes":1696,"name":"clinton"},
{"votes":974,"name":"obama"}],
"total":2670,"precincts":
{"total":25,"reporting":9},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":2164,"name":"clinton"},
{"votes":1523,"name":"obama"}],
"total":3687,"precincts":
{"total":17,"reporting":17},
"name":"Fulton"},
"Madison":
{"votes":[
{"votes":11607,"name":"clinton"},
{"votes":9118,"name":"obama"}],
"total":20725,"precincts":
{"total":111,"reporting":79},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":2458,"name":"clinton"},
{"votes":1644,"name":"obama"}],
"total":4102,"precincts":
{"total":39,"reporting":36},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":13893,"name":"clinton"},
{"votes":6858,"name":"obama"}],
"total":20751,"precincts":
{"total":73,"reporting":59},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":2215,"name":"clinton"},
{"votes":1459,"name":"obama"}],
"total":3674,"precincts":
{"total":20,"reporting":20},
"name":"Owen"},
"Huntington":
{"votes":[
{"votes":1804,"name":"clinton"},
{"votes":1345,"name":"obama"}],
"total":3149,"precincts":
{"total":34,"reporting":22},
"name":"Huntington"},
"Clay":
{"votes":[
{"votes":4011,"name":"clinton"},
{"votes":2028,"name":"obama"}],
"total":6039,"precincts":
{"total":23,"reporting":23},
"name":"Clay"},
"Blackford":
{"votes":[
{"votes":1940,"name":"clinton"},
{"votes":1024,"name":"obama"}],
"total":2964,"precincts":
{"total":12,"reporting":12},
"name":"Blackford"},
"Cass":
{"votes":[
{"votes":3976,"name":"clinton"},
{"votes":2513,"name":"obama"}],
"total":6489,"precincts":
{"total":39,"reporting":39},
"name":"Cass"},
"Delaware":
{"votes":[
{"votes":6103,"name":"clinton"},
{"votes":5555,"name":"obama"}],
"total":11658,"precincts":
{"total":75,"reporting":29},
"name":"Delaware"},
"Fountain":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Fountain"},
"Lawrence":
{"votes":[
{"votes":2476,"name":"clinton"},
{"votes":1380,"name":"obama"}],
"total":3856,"precincts":
{"total":39,"reporting":27},
"name":"Lawrence"},
"Elkhart":
{"votes":[
{"votes":15326,"name":"obama"},
{"votes":10719,"name":"clinton"}],
"total":26045,"precincts":
{"total":110,"reporting":106},
"name":"Elkhart"},
"Grant":
{"votes":[
{"votes":334,"name":"clinton"},
{"votes":186,"name":"obama"}],
"total":520,"precincts":
{"total":68,"reporting":1},
"name":"Grant"},
"Fayette":
{"votes":[
{"votes":3100,"name":"clinton"},
{"votes":1482,"name":"obama"}],
"total":4582,"precincts":
{"total":28,"reporting":26},
"name":"Fayette"},
"Posey":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Posey"},
"Floyd":
{"votes":[
{"votes":12334,"name":"clinton"},
{"votes":6452,"name":"obama"}],
"total":18786,"precincts":
{"total":60,"reporting":60},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":2467,"name":"clinton"},
{"votes":1077,"name":"obama"}],
"total":3544,"precincts":
{"total":18,"reporting":18},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":3147,"name":"clinton"},
{"votes":2283,"name":"obama"}],
"total":5430,"precincts":
{"total":25,"reporting":25},
"name":"Adams"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Franklin"},
"Switzerland":
{"votes":[
{"votes":1464,"name":"clinton"},
{"votes":486,"name":"obama"}],
"total":1950,"precincts":
{"total":12,"reporting":12},
"name":"Switzerland"},
"Vanderburgh":
{"votes":[
{"votes":12818,"name":"clinton"},
{"votes":11635,"name":"obama"}],
"total":24453,"precincts":
{"total":131,"reporting":72},
"name":"Vanderburgh"},
"Marshall":
{"votes":[
{"votes":4267,"name":"clinton"},
{"votes":3157,"name":"obama"}],
"total":7424,"precincts":
{"total":27,"reporting":27},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":2033,"name":"clinton"},
{"votes":1625,"name":"obama"}],
"total":3658,"precincts":
{"total":19,"reporting":19},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":4515,"name":"clinton"},
{"votes":1750,"name":"obama"}],
"total":6265,"precincts":
{"total":36,"reporting":25},
"name":"Harrison"},
"Boone":
{"votes":[
{"votes":4846,"name":"obama"},
{"votes":4453,"name":"clinton"}],
"total":9299,"precincts":
{"total":49,"reporting":49},
"name":"Boone"},
"Starke":
{"votes":[
{"votes":2173,"name":"clinton"},
{"votes":900,"name":"obama"}],
"total":3073,"precincts":
{"total":21,"reporting":11},
"name":"Starke"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":559,"reporting":0},
"name":"Lake"},
"Pulaski":
{"votes":[
{"votes":1409,"name":"clinton"},
{"votes":911,"name":"obama"}],
"total":2320,"precincts":
{"total":15,"reporting":15},
"name":"Pulaski"},
"Hendricks":
{"votes":[],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Hendricks"},
"Tippecanoe":
{"votes":[],
"total":0,"precincts":
{"total":91,"reporting":0},
"name":"Tippecanoe"},
"Parke":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Parke"},
"DeKalb":
{"votes":[
{"votes":3427,"name":"clinton"},
{"votes":2557,"name":"obama"}],
"total":5984,"precincts":
{"total":39,"reporting":39},
"name":"DeKalb"},
"Crawford":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Crawford"},
"Noble":
{"votes":[
{"votes":3974,"name":"clinton"},
{"votes":2750,"name":"obama"}],
"total":6724,"precincts":
{"total":29,"reporting":29},
"name":"Noble"},
"Wells":
{"votes":[
{"votes":2613,"name":"clinton"},
{"votes":1907,"name":"obama"}],
"total":4520,"precincts":
{"total":22,"reporting":22},
"name":"Wells"},
"Knox":
{"votes":[
{"votes":6407,"name":"clinton"},
{"votes":3260,"name":"obama"}],
"total":9667,"precincts":
{"total":36,"reporting":36},
"name":"Knox"},
"Bartholomew":
{"votes":[
{"votes":6797,"name":"clinton"},
{"votes":5907,"name":"obama"}],
"total":12704,"precincts":
{"total":67,"reporting":65},
"name":"Bartholomew"},
"Tipton":
{"votes":[
{"votes":1848,"name":"clinton"},
{"votes":1324,"name":"obama"}],
"total":3172,"precincts":
{"total":17,"reporting":17},
"name":"Tipton"},
"Benton":
{"votes":[
{"votes":318,"name":"clinton"},
{"votes":285,"name":"obama"}],
"total":603,"precincts":
{"total":15,"reporting":9},
"name":"Benton"},
"Morgan":
{"votes":[
{"votes":1324,"name":"clinton"},
{"votes":769,"name":"obama"}],
"total":2093,"precincts":
{"total":48,"reporting":17},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Martin"},
"Warrick":
{"votes":[
{"votes":4520,"name":"clinton"},
{"votes":2924,"name":"obama"}],
"total":7444,"precincts":
{"total":59,"reporting":29},
"name":"Warrick"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Scott"},
"Randolph":
{"votes":[
{"votes":2846,"name":"clinton"},
{"votes":1748,"name":"obama"}],
"total":4594,"precincts":
{"total":29,"reporting":29},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":217,"name":"obama"},
{"votes":88,"name":"clinton"}],
"total":305,"precincts":
{"total":71,"reporting":1},
"name":"Monroe"},
"Steuben":
{"votes":[
{"votes":3096,"name":"clinton"},
{"votes":2302,"name":"obama"}],
"total":5398,"precincts":
{"total":19,"reporting":19},
"name":"Steuben"}}})