GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":116587,"name":"clinton","delegates":49},
{"votes":87797,"name":"obama","delegates":44}],
"name":"Indiana","precincts":
{"total":5230,"reporting":951},
"delegates":72,"date":"05-06"},
"state":"IN","party":"dem","total":204384,"locals":
{"Daviess":
{"votes":[
{"votes":894,"name":"clinton"},
{"votes":547,"name":"obama"}],
"total":1441,"precincts":
{"total":28,"reporting":10},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":3313,"name":"clinton"},
{"votes":1710,"name":"obama"}],
"total":5023,"precincts":
{"total":39,"reporting":29},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":102,"name":"clinton"},
{"votes":78,"name":"obama"}],
"total":180,"precincts":
{"total":27,"reporting":1},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Wayne"},
"Wabash":
{"votes":[
{"votes":2423,"name":"clinton"},
{"votes":1821,"name":"obama"}],
"total":4244,"precincts":
{"total":25,"reporting":22},
"name":"Wabash"},
"White":
{"votes":[
{"votes":710,"name":"clinton"},
{"votes":489,"name":"obama"}],
"total":1199,"precincts":
{"total":23,"reporting":5},
"name":"White"},
"Porter":
{"votes":[],
"total":0,"precincts":
{"total":128,"reporting":0},
"name":"Porter"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Brown"},
"LaPorte":
{"votes":[],
"total":0,"precincts":
{"total":79,"reporting":0},
"name":"LaPorte"},
"Jay":
{"votes":[
{"votes":2256,"name":"clinton"},
{"votes":1379,"name":"obama"}],
"total":3635,"precincts":
{"total":21,"reporting":21},
"name":"Jay"},
"Jennings":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Jennings"},
"Dearborn":
{"votes":[
{"votes":797,"name":"clinton"},
{"votes":264,"name":"obama"}],
"total":1061,"precincts":
{"total":45,"reporting":5},
"name":"Dearborn"},
"Miami":
{"votes":[
{"votes":166,"name":"clinton"},
{"votes":60,"name":"obama"}],
"total":226,"precincts":
{"total":31,"reporting":25},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":1916,"name":"clinton"},
{"votes":1092,"name":"obama"}],
"total":3008,"precincts":
{"total":38,"reporting":13},
"name":"Hancock"},
"Henry":
{"votes":[
{"votes":2102,"name":"clinton"},
{"votes":1111,"name":"obama"}],
"total":3213,"precincts":
{"total":42,"reporting":14},
"name":"Henry"},
"Vigo":
{"votes":[
{"votes":14619,"name":"clinton"},
{"votes":9969,"name":"obama"}],
"total":24588,"precincts":
{"total":87,"reporting":78},
"name":"Vigo"},
"Sullivan":
{"votes":[
{"votes":3092,"name":"clinton"},
{"votes":1528,"name":"obama"}],
"total":4620,"precincts":
{"total":20,"reporting":17},
"name":"Sullivan"},
"Dubois":
{"votes":[
{"votes":622,"name":"clinton"},
{"votes":411,"name":"obama"}],
"total":1033,"precincts":
{"total":38,"reporting":1},
"name":"Dubois"},
"Newton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":355,"name":"clinton"},
{"votes":135,"name":"obama"}],
"total":490,"precincts":
{"total":22,"reporting":3},
"name":"Washington"},
"Decatur":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Decatur"},
"Marion":
{"votes":[
{"votes":3026,"name":"obama"},
{"votes":2601,"name":"clinton"}],
"total":5627,"precincts":
{"total":594,"reporting":26},
"name":"Marion"},
"Jasper":
{"votes":[
{"votes":290,"name":"clinton"},
{"votes":206,"name":"obama"}],
"total":496,"precincts":
{"total":29,"reporting":2},
"name":"Jasper"},
"Vermillion":
{"votes":[
{"votes":206,"name":"clinton"},
{"votes":99,"name":"obama"}],
"total":305,"precincts":
{"total":17,"reporting":1},
"name":"Vermillion"},
"Allen":
{"votes":[
{"votes":24094,"name":"obama"},
{"votes":19995,"name":"clinton"}],
"total":44089,"precincts":
{"total":294,"reporting":201},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":286,"name":"obama"},
{"votes":261,"name":"clinton"}],
"total":547,"precincts":
{"total":13,"reporting":8},
"name":"Warren"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":2104,"name":"clinton"},
{"votes":1835,"name":"obama"}],
"total":3939,"precincts":
{"total":71,"reporting":18},
"name":"Howard"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":1171,"name":"clinton"},
{"votes":543,"name":"obama"}],
"total":1714,"precincts":
{"total":22,"reporting":12},
"name":"Orange"},
"St. Joseph":
{"votes":[],
"total":0,"precincts":
{"total":226,"reporting":0},
"name":"St. Joseph"},
"Putnam":
{"votes":[
{"votes":226,"name":"obama"},
{"votes":133,"name":"clinton"}],
"total":359,"precincts":
{"total":29,"reporting":2},
"name":"Putnam"},
"Hamilton":
{"votes":[],
"total":0,"precincts":
{"total":196,"reporting":0},
"name":"Hamilton"},
"Kosciusko":
{"votes":[
{"votes":1098,"name":"clinton"},
{"votes":1079,"name":"obama"}],
"total":2177,"precincts":
{"total":65,"reporting":13},
"name":"Kosciusko"},
"Rush":
{"votes":[
{"votes":744,"name":"clinton"},
{"votes":474,"name":"obama"}],
"total":1218,"precincts":
{"total":20,"reporting":7},
"name":"Rush"},
"Johnson":
{"votes":[
{"votes":3472,"name":"clinton"},
{"votes":2664,"name":"obama"}],
"total":6136,"precincts":
{"total":107,"reporting":31},
"name":"Johnson"},
"Whitley":
{"votes":[
{"votes":2136,"name":"clinton"},
{"votes":1463,"name":"obama"}],
"total":3599,"precincts":
{"total":34,"reporting":23},
"name":"Whitley"},
"Greene":
{"votes":[
{"votes":908,"name":"clinton"},
{"votes":445,"name":"obama"}],
"total":1353,"precincts":
{"total":32,"reporting":5},
"name":"Greene"},
"Ripley":
{"votes":[
{"votes":1203,"name":"clinton"},
{"votes":561,"name":"obama"}],
"total":1764,"precincts":
{"total":27,"reporting":11},
"name":"Ripley"},
"LaGrange":
{"votes":[
{"votes":323,"name":"clinton"},
{"votes":215,"name":"obama"}],
"total":538,"precincts":
{"total":16,"reporting":2},
"name":"LaGrange"},
"Ohio":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Ohio"},
"Gibson":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Gibson"},
"Spencer":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":816,"name":"clinton"},
{"votes":536,"name":"obama"}],
"total":1352,"precincts":
{"total":17,"reporting":6},
"name":"Fulton"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":111,"reporting":0},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":1896,"name":"clinton"},
{"votes":1215,"name":"obama"}],
"total":3111,"precincts":
{"total":39,"reporting":27},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":2629,"name":"clinton"},
{"votes":1208,"name":"obama"}],
"total":3837,"precincts":
{"total":73,"reporting":12},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":83,"name":"clinton"},
{"votes":81,"name":"obama"}],
"total":164,"precincts":
{"total":20,"reporting":1},
"name":"Owen"},
"Huntington":
{"votes":[
{"votes":1804,"name":"clinton"},
{"votes":1345,"name":"obama"}],
"total":3149,"precincts":
{"total":34,"reporting":22},
"name":"Huntington"},
"Clay":
{"votes":[
{"votes":1740,"name":"clinton"},
{"votes":866,"name":"obama"}],
"total":2606,"precincts":
{"total":23,"reporting":10},
"name":"Clay"},
"Blackford":
{"votes":[
{"votes":1940,"name":"clinton"},
{"votes":1024,"name":"obama"}],
"total":2964,"precincts":
{"total":12,"reporting":12},
"name":"Blackford"},
"Cass":
{"votes":[
{"votes":3685,"name":"clinton"},
{"votes":2338,"name":"obama"}],
"total":6023,"precincts":
{"total":39,"reporting":31},
"name":"Cass"},
"Delaware":
{"votes":[],
"total":0,"precincts":
{"total":75,"reporting":0},
"name":"Delaware"},
"Fountain":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Fountain"},
"Lawrence":
{"votes":[
{"votes":465,"name":"clinton"},
{"votes":263,"name":"obama"}],
"total":728,"precincts":
{"total":39,"reporting":5},
"name":"Lawrence"},
"Elkhart":
{"votes":[],
"total":0,"precincts":
{"total":110,"reporting":0},
"name":"Elkhart"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":68,"reporting":0},
"name":"Grant"},
"Fayette":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Fayette"},
"Posey":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Posey"},
"Floyd":
{"votes":[
{"votes":5938,"name":"clinton"},
{"votes":2951,"name":"obama"}],
"total":8889,"precincts":
{"total":60,"reporting":31},
"name":"Floyd"},
"Pike":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":931,"name":"clinton"},
{"votes":704,"name":"obama"}],
"total":1635,"precincts":
{"total":25,"reporting":7},
"name":"Adams"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Franklin"},
"Switzerland":
{"votes":[
{"votes":282,"name":"clinton"},
{"votes":82,"name":"obama"}],
"total":364,"precincts":
{"total":12,"reporting":4},
"name":"Switzerland"},
"Vanderburgh":
{"votes":[],
"total":0,"precincts":
{"total":131,"reporting":0},
"name":"Vanderburgh"},
"Marshall":
{"votes":[
{"votes":831,"name":"clinton"},
{"votes":574,"name":"obama"}],
"total":1405,"precincts":
{"total":27,"reporting":3},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":1000,"name":"clinton"},
{"votes":923,"name":"obama"}],
"total":1923,"precincts":
{"total":19,"reporting":10},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":102,"name":"clinton"},
{"votes":36,"name":"obama"}],
"total":138,"precincts":
{"total":36,"reporting":1},
"name":"Harrison"},
"Boone":
{"votes":[
{"votes":1343,"name":"obama"},
{"votes":1167,"name":"clinton"}],
"total":2510,"precincts":
{"total":49,"reporting":6},
"name":"Boone"},
"Starke":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Starke"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":559,"reporting":0},
"name":"Lake"},
"Pulaski":
{"votes":[
{"votes":933,"name":"clinton"},
{"votes":647,"name":"obama"}],
"total":1580,"precincts":
{"total":15,"reporting":9},
"name":"Pulaski"},
"Hendricks":
{"votes":[],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Hendricks"},
"Tippecanoe":
{"votes":[],
"total":0,"precincts":
{"total":91,"reporting":0},
"name":"Tippecanoe"},
"Parke":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Parke"},
"DeKalb":
{"votes":[
{"votes":1809,"name":"clinton"},
{"votes":1380,"name":"obama"}],
"total":3189,"precincts":
{"total":39,"reporting":21},
"name":"DeKalb"},
"Crawford":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Crawford"},
"Noble":
{"votes":[
{"votes":1761,"name":"clinton"},
{"votes":1173,"name":"obama"}],
"total":2934,"precincts":
{"total":29,"reporting":11},
"name":"Noble"},
"Wells":
{"votes":[
{"votes":2613,"name":"clinton"},
{"votes":1907,"name":"obama"}],
"total":4520,"precincts":
{"total":22,"reporting":22},
"name":"Wells"},
"Knox":
{"votes":[
{"votes":6197,"name":"clinton"},
{"votes":3178,"name":"obama"}],
"total":9375,"precincts":
{"total":36,"reporting":34},
"name":"Knox"},
"Bartholomew":
{"votes":[
{"votes":3939,"name":"clinton"},
{"votes":3418,"name":"obama"}],
"total":7357,"precincts":
{"total":67,"reporting":35},
"name":"Bartholomew"},
"Tipton":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Tipton"},
"Benton":
{"votes":[
{"votes":30,"name":"clinton"},
{"votes":27,"name":"obama"}],
"total":57,"precincts":
{"total":15,"reporting":2},
"name":"Benton"},
"Morgan":
{"votes":[
{"votes":273,"name":"clinton"},
{"votes":129,"name":"obama"}],
"total":402,"precincts":
{"total":48,"reporting":2},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Martin"},
"Warrick":
{"votes":[],
"total":0,"precincts":
{"total":59,"reporting":0},
"name":"Warrick"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Scott"},
"Randolph":
{"votes":[
{"votes":1027,"name":"clinton"},
{"votes":616,"name":"obama"}],
"total":1643,"precincts":
{"total":29,"reporting":6},
"name":"Randolph"},
"Monroe":
{"votes":[],
"total":0,"precincts":
{"total":71,"reporting":0},
"name":"Monroe"},
"Steuben":
{"votes":[
{"votes":2684,"name":"clinton"},
{"votes":2023,"name":"obama"}],
"total":4707,"precincts":
{"total":19,"reporting":15},
"name":"Steuben"}}})