GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":10425,"name":"mccain"},
{"votes":1399,"name":"huckabee"},
{"votes":973,"name":"paul"},
{"votes":620,"name":"romney"}],
"name":"Indiana","precincts":
{"total":5230,"reporting":133},
"delegates":57,"date":"05-06"},
"state":"IN","party":"gop","total":13417,"locals":
{"Daviess":
{"votes":[
{"votes":339,"name":"mccain"},
{"votes":26,"name":"huckabee"},
{"votes":18,"name":"romney"},
{"votes":11,"name":"paul"}],
"total":394,"precincts":
{"total":28,"reporting":4},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":409,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":20,"name":"romney"},
{"votes":17,"name":"paul"}],
"total":477,"precincts":
{"total":39,"reporting":1},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Wayne"},
"Wabash":
{"votes":[
{"votes":487,"name":"mccain"},
{"votes":67,"name":"paul"},
{"votes":52,"name":"huckabee"},
{"votes":30,"name":"romney"}],
"total":636,"precincts":
{"total":25,"reporting":2},
"name":"Wabash"},
"White":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"White"},
"Porter":
{"votes":[],
"total":0,"precincts":
{"total":128,"reporting":0},
"name":"Porter"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Brown"},
"LaPorte":
{"votes":[],
"total":0,"precincts":
{"total":79,"reporting":0},
"name":"LaPorte"},
"Jay":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Jay"},
"Jennings":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Jennings"},
"Dearborn":
{"votes":[],
"total":0,"precincts":
{"total":45,"reporting":0},
"name":"Dearborn"},
"Miami":
{"votes":[
{"votes":63,"name":"mccain"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"romney"}],
"total":68,"precincts":
{"total":31,"reporting":0},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":205,"name":"mccain"},
{"votes":22,"name":"paul"},
{"votes":19,"name":"huckabee"},
{"votes":14,"name":"romney"}],
"total":260,"precincts":
{"total":38,"reporting":2},
"name":"Hancock"},
"Henry":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Henry"},
"Vigo":
{"votes":[
{"votes":2426,"name":"mccain"},
{"votes":350,"name":"huckabee"},
{"votes":247,"name":"paul"},
{"votes":110,"name":"romney"}],
"total":3133,"precincts":
{"total":87,"reporting":70},
"name":"Vigo"},
"Sullivan":
{"votes":[
{"votes":74,"name":"mccain"},
{"votes":17,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"paul"}],
"total":96,"precincts":
{"total":20,"reporting":0},
"name":"Sullivan"},
"Dubois":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Dubois"},
"Newton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Newton"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Washington"},
"Decatur":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Decatur"},
"Marion":
{"votes":[],
"total":0,"precincts":
{"total":594,"reporting":0},
"name":"Marion"},
"Jasper":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Jasper"},
"Vermillion":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Vermillion"},
"Allen":
{"votes":[],
"total":0,"precincts":
{"total":294,"reporting":0},
"name":"Allen"},
"Warren":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Warren"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Jackson"},
"Howard":
{"votes":[],
"total":0,"precincts":
{"total":71,"reporting":0},
"name":"Howard"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":51,"name":"mccain"},
{"votes":10,"name":"huckabee"},
{"votes":4,"name":"romney"},
{"votes":3,"name":"paul"}],
"total":68,"precincts":
{"total":22,"reporting":2},
"name":"Orange"},
"St. Joseph":
{"votes":[],
"total":0,"precincts":
{"total":226,"reporting":0},
"name":"St. Joseph"},
"Putnam":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Putnam"},
"Hamilton":
{"votes":[],
"total":0,"precincts":
{"total":196,"reporting":0},
"name":"Hamilton"},
"Kosciusko":
{"votes":[
{"votes":362,"name":"mccain"},
{"votes":44,"name":"huckabee"},
{"votes":28,"name":"romney"},
{"votes":18,"name":"paul"}],
"total":452,"precincts":
{"total":65,"reporting":1},
"name":"Kosciusko"},
"Rush":
{"votes":[
{"votes":32,"name":"mccain"},
{"votes":2,"name":"paul"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":37,"precincts":
{"total":20,"reporting":1},
"name":"Rush"},
"Johnson":
{"votes":[],
"total":0,"precincts":
{"total":107,"reporting":0},
"name":"Johnson"},
"Whitley":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Whitley"},
"Greene":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Greene"},
"Ripley":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Ripley"},
"LaGrange":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"LaGrange"},
"Ohio":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Ohio"},
"Gibson":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Gibson"},
"Spencer":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Spencer"},
"Fulton":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Fulton"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":111,"reporting":0},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":1108,"name":"mccain"},
{"votes":169,"name":"huckabee"},
{"votes":67,"name":"romney"},
{"votes":61,"name":"paul"}],
"total":1405,"precincts":
{"total":39,"reporting":9},
"name":"Clinton"},
"Clark":
{"votes":[],
"total":0,"precincts":
{"total":73,"reporting":0},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":43,"name":"mccain"},
{"votes":7,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":59,"precincts":
{"total":20,"reporting":1},
"name":"Owen"},
"Huntington":
{"votes":[
{"votes":398,"name":"mccain"},
{"votes":52,"name":"huckabee"},
{"votes":39,"name":"paul"},
{"votes":28,"name":"romney"}],
"total":517,"precincts":
{"total":34,"reporting":2},
"name":"Huntington"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Clay"},
"Blackford":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Blackford"},
"Cass":
{"votes":[
{"votes":1431,"name":"mccain"},
{"votes":189,"name":"huckabee"},
{"votes":97,"name":"paul"},
{"votes":73,"name":"romney"}],
"total":1790,"precincts":
{"total":39,"reporting":1},
"name":"Cass"},
"Delaware":
{"votes":[],
"total":0,"precincts":
{"total":75,"reporting":0},
"name":"Delaware"},
"Fountain":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Fountain"},
"Lawrence":
{"votes":[],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Lawrence"},
"Elkhart":
{"votes":[],
"total":0,"precincts":
{"total":110,"reporting":0},
"name":"Elkhart"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":68,"reporting":0},
"name":"Grant"},
"Fayette":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Fayette"},
"Posey":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Posey"},
"Floyd":
{"votes":[],
"total":0,"precincts":
{"total":60,"reporting":0},
"name":"Floyd"},
"Pike":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Pike"},
"Adams":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Adams"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Franklin"},
"Switzerland":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Switzerland"},
"Vanderburgh":
{"votes":[],
"total":0,"precincts":
{"total":131,"reporting":0},
"name":"Vanderburgh"},
"Marshall":
{"votes":[
{"votes":260,"name":"mccain"},
{"votes":33,"name":"huckabee"},
{"votes":16,"name":"paul"},
{"votes":11,"name":"romney"}],
"total":320,"precincts":
{"total":27,"reporting":0},
"name":"Marshall"},
"Carroll":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Carroll"},
"Harrison":
{"votes":[],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Harrison"},
"Boone":
{"votes":[],
"total":0,"precincts":
{"total":49,"reporting":0},
"name":"Boone"},
"Starke":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Starke"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":559,"reporting":0},
"name":"Lake"},
"Pulaski":
{"votes":[
{"votes":238,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":14,"name":"romney"}],
"total":304,"precincts":
{"total":15,"reporting":2},
"name":"Pulaski"},
"Hendricks":
{"votes":[],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Hendricks"},
"Tippecanoe":
{"votes":[],
"total":0,"precincts":
{"total":91,"reporting":0},
"name":"Tippecanoe"},
"Parke":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Parke"},
"DeKalb":
{"votes":[],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"DeKalb"},
"Crawford":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Crawford"},
"Noble":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Noble"},
"Wells":
{"votes":[
{"votes":732,"name":"mccain"},
{"votes":143,"name":"huckabee"},
{"votes":101,"name":"paul"},
{"votes":61,"name":"romney"}],
"total":1037,"precincts":
{"total":22,"reporting":11},
"name":"Wells"},
"Knox":
{"votes":[
{"votes":661,"name":"mccain"},
{"votes":73,"name":"huckabee"},
{"votes":30,"name":"romney"},
{"votes":23,"name":"paul"}],
"total":787,"precincts":
{"total":36,"reporting":13},
"name":"Knox"},
"Bartholomew":
{"votes":[],
"total":0,"precincts":
{"total":67,"reporting":0},
"name":"Bartholomew"},
"Tipton":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Tipton"},
"Benton":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Benton"},
"Morgan":
{"votes":[],
"total":0,"precincts":
{"total":48,"reporting":0},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Martin"},
"Warrick":
{"votes":[],
"total":0,"precincts":
{"total":59,"reporting":0},
"name":"Warrick"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Scott"},
"Randolph":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Randolph"},
"Monroe":
{"votes":[],
"total":0,"precincts":
{"total":71,"reporting":0},
"name":"Monroe"},
"Steuben":
{"votes":[
{"votes":1106,"name":"mccain"},
{"votes":217,"name":"paul"},
{"votes":154,"name":"huckabee"},
{"votes":100,"name":"romney"}],
"total":1577,"precincts":
{"total":19,"reporting":11},
"name":"Steuben"}}})