GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":187574,"name":"clinton"},
{"votes":140838,"name":"obama"},
{"votes":6173,"name":"uncommitted-d"},
{"votes":5159,"name":"edwards"}],
"name":"Kentucky","precincts":
{"total":3532,"reporting":1211},
"delegates":51,"date":"05-20"},
"state":"KY","party":"dem","total":339744,"locals":
{"Metcalfe":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Metcalfe"},
"Daviess":
{"votes":[
{"votes":385,"name":"clinton"},
{"votes":239,"name":"obama"},
{"votes":51,"name":"uncommitted-d"},
{"votes":20,"name":"edwards"}],
"total":695,"precincts":
{"total":84,"reporting":2},
"name":"Daviess"},
"Russell":
{"votes":[
{"votes":60,"name":"clinton"},
{"votes":9,"name":"obama"},
{"votes":1,"name":"edwards"}],
"total":70,"precincts":
{"total":16,"reporting":1},
"name":"Russell"},
"Shelby":
{"votes":[
{"votes":1767,"name":"clinton"},
{"votes":946,"name":"obama"},
{"votes":107,"name":"uncommitted-d"},
{"votes":64,"name":"edwards"}],
"total":2884,"precincts":
{"total":33,"reporting":14},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":1663,"name":"clinton"},
{"votes":214,"name":"obama"},
{"votes":23,"name":"uncommitted-d"},
{"votes":21,"name":"edwards"}],
"total":1921,"precincts":
{"total":19,"reporting":19},
"name":"Wayne"},
"Robertson":
{"votes":[
{"votes":387,"name":"clinton"},
{"votes":90,"name":"obama"},
{"votes":26,"name":"edwards"},
{"votes":20,"name":"uncommitted-d"}],
"total":523,"precincts":
{"total":5,"reporting":5},
"name":"Robertson"},
"Bourbon":
{"votes":[
{"votes":128,"name":"clinton"},
{"votes":40,"name":"obama"},
{"votes":16,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":190,"precincts":
{"total":18,"reporting":1},
"name":"Bourbon"},
"Nicholas":
{"votes":[
{"votes":1520,"name":"clinton"},
{"votes":270,"name":"obama"},
{"votes":65,"name":"uncommitted-d"},
{"votes":39,"name":"edwards"}],
"total":1894,"precincts":
{"total":5,"reporting":5},
"name":"Nicholas"},
"Powell":
{"votes":[
{"votes":104,"name":"clinton"},
{"votes":10,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":3,"name":"uncommitted-d"}],
"total":122,"precincts":
{"total":11,"reporting":1},
"name":"Powell"},
"Boyle":
{"votes":[
{"votes":75,"name":"clinton"},
{"votes":65,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"}],
"total":150,"precincts":
{"total":25,"reporting":0},
"name":"Boyle"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Henderson"},
"Menifee":
{"votes":[
{"votes":1527,"name":"clinton"},
{"votes":143,"name":"obama"},
{"votes":30,"name":"edwards"},
{"votes":25,"name":"uncommitted-d"}],
"total":1725,"precincts":
{"total":6,"reporting":6},
"name":"Menifee"},
"Breckinridge":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Breckinridge"},
"Casey":
{"votes":[
{"votes":616,"name":"clinton"},
{"votes":118,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"}],
"total":776,"precincts":
{"total":15,"reporting":15},
"name":"Casey"},
"Adair":
{"votes":[
{"votes":44,"name":"clinton"},
{"votes":8,"name":"obama"},
{"votes":1,"name":"uncommitted-d"},
{"votes":1,"name":"edwards"}],
"total":54,"precincts":
{"total":16,"reporting":0},
"name":"Adair"},
"McCreary":
{"votes":[
{"votes":27,"name":"clinton"},
{"votes":5,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":35,"precincts":
{"total":18,"reporting":1},
"name":"McCreary"},
"Nelson":
{"votes":[
{"votes":149,"name":"clinton"},
{"votes":81,"name":"obama"},
{"votes":6,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":242,"precincts":
{"total":26,"reporting":1},
"name":"Nelson"},
"Henry":
{"votes":[
{"votes":46,"name":"clinton"},
{"votes":21,"name":"obama"},
{"votes":3,"name":"edwards"}],
"total":70,"precincts":
{"total":20,"reporting":0},
"name":"Henry"},
"Barren":
{"votes":[
{"votes":152,"name":"clinton"},
{"votes":62,"name":"obama"},
{"votes":6,"name":"uncommitted-d"},
{"votes":2,"name":"edwards"}],
"total":222,"precincts":
{"total":24,"reporting":1},
"name":"Barren"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Webster"},
"Bullitt":
{"votes":[
{"votes":192,"name":"clinton"},
{"votes":75,"name":"obama"},
{"votes":7,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":280,"precincts":
{"total":44,"reporting":1},
"name":"Bullitt"},
"Washington":
{"votes":[
{"votes":1828,"name":"clinton"},
{"votes":516,"name":"obama"},
{"votes":62,"name":"edwards"},
{"votes":61,"name":"uncommitted-d"}],
"total":2467,"precincts":
{"total":14,"reporting":14},
"name":"Washington"},
"Trimble":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Trimble"},
"Marion":
{"votes":[
{"votes":3171,"name":"clinton"},
{"votes":866,"name":"obama"},
{"votes":72,"name":"uncommitted-d"},
{"votes":60,"name":"edwards"}],
"total":4169,"precincts":
{"total":16,"reporting":16},
"name":"Marion"},
"Hickman":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Hickman"},
"Allen":
{"votes":[
{"votes":56,"name":"clinton"},
{"votes":8,"name":"obama"},
{"votes":3,"name":"edwards"}],
"total":67,"precincts":
{"total":13,"reporting":0},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":338,"name":"clinton"},
{"votes":149,"name":"obama"},
{"votes":26,"name":"uncommitted-d"},
{"votes":14,"name":"edwards"}],
"total":527,"precincts":
{"total":63,"reporting":0},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":2975,"name":"clinton"},
{"votes":278,"name":"obama"},
{"votes":73,"name":"edwards"},
{"votes":63,"name":"uncommitted-d"}],
"total":3389,"precincts":
{"total":37,"reporting":28},
"name":"Perry"},
"Graves":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Graves"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Grant"},
"Caldwell":
{"votes":[
{"votes":111,"name":"clinton"},
{"votes":23,"name":"obama"},
{"votes":7,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":147,"precincts":
{"total":12,"reporting":0},
"name":"Caldwell"},
"Oldham":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Oldham"},
"Mason":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Mason"},
"Wolfe":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Wolfe"},
"Anderson":
{"votes":[
{"votes":92,"name":"clinton"},
{"votes":27,"name":"obama"},
{"votes":9,"name":"uncommitted-d"},
{"votes":8,"name":"edwards"}],
"total":136,"precincts":
{"total":14,"reporting":1},
"name":"Anderson"},
"Jefferson":
{"votes":[
{"votes":113196,"name":"obama"},
{"votes":105080,"name":"clinton"},
{"votes":3546,"name":"uncommitted-d"},
{"votes":2890,"name":"edwards"}],
"total":224712,"precincts":
{"total":513,"reporting":457},
"name":"Jefferson"},
"Crittenden":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Crittenden"},
"Butler":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Butler"},
"Breathitt":
{"votes":[
{"votes":1612,"name":"clinton"},
{"votes":149,"name":"obama"},
{"votes":39,"name":"edwards"},
{"votes":36,"name":"uncommitted-d"}],
"total":1836,"precincts":
{"total":21,"reporting":10},
"name":"Breathitt"},
"Kenton":
{"votes":[
{"votes":1935,"name":"clinton"},
{"votes":1436,"name":"obama"},
{"votes":116,"name":"uncommitted-d"},
{"votes":57,"name":"edwards"}],
"total":3544,"precincts":
{"total":108,"reporting":26},
"name":"Kenton"},
"Lee":
{"votes":[
{"votes":702,"name":"clinton"},
{"votes":76,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"}],
"total":793,"precincts":
{"total":10,"reporting":10},
"name":"Lee"},
"Boyd":
{"votes":[
{"votes":4110,"name":"clinton"},
{"votes":855,"name":"obama"},
{"votes":182,"name":"uncommitted-d"},
{"votes":113,"name":"edwards"}],
"total":5260,"precincts":
{"total":47,"reporting":23},
"name":"Boyd"},
"Rockcastle":
{"votes":[
{"votes":664,"name":"clinton"},
{"votes":106,"name":"obama"},
{"votes":11,"name":"edwards"},
{"votes":7,"name":"uncommitted-d"}],
"total":788,"precincts":
{"total":14,"reporting":14},
"name":"Rockcastle"},
"McLean":
{"votes":[
{"votes":53,"name":"clinton"},
{"votes":18,"name":"obama"},
{"votes":4,"name":"edwards"}],
"total":75,"precincts":
{"total":8,"reporting":1},
"name":"McLean"},
"Johnson":
{"votes":[
{"votes":1535,"name":"clinton"},
{"votes":170,"name":"obama"},
{"votes":41,"name":"edwards"},
{"votes":31,"name":"uncommitted-d"}],
"total":1777,"precincts":
{"total":31,"reporting":20},
"name":"Johnson"},
"Hopkins":
{"votes":[],
"total":0,"precincts":
{"total":40,"reporting":0},
"name":"Hopkins"},
"Whitley":
{"votes":[
{"votes":1380,"name":"clinton"},
{"votes":198,"name":"obama"},
{"votes":33,"name":"edwards"},
{"votes":29,"name":"uncommitted-d"}],
"total":1640,"precincts":
{"total":36,"reporting":31},
"name":"Whitley"},
"Woodford":
{"votes":[
{"votes":79,"name":"clinton"},
{"votes":63,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":148,"precincts":
{"total":16,"reporting":1},
"name":"Woodford"},
"Green":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Green"},
"Clay":
{"votes":[
{"votes":323,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":7,"name":"uncommitted-d"},
{"votes":5,"name":"edwards"}],
"total":377,"precincts":
{"total":20,"reporting":11},
"name":"Clay"},
"Ohio":
{"votes":[
{"votes":192,"name":"clinton"},
{"votes":72,"name":"obama"},
{"votes":8,"name":"uncommitted-d"},
{"votes":5,"name":"edwards"}],
"total":277,"precincts":
{"total":25,"reporting":1},
"name":"Ohio"},
"Spencer":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Spencer"},
"Fulton":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Fulton"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":56,"reporting":0},
"name":"Madison"},
"Taylor":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Taylor"},
"Clinton":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":106,"name":"clinton"},
{"votes":45,"name":"obama"},
{"votes":7,"name":"uncommitted-d"},
{"votes":5,"name":"edwards"}],
"total":163,"precincts":
{"total":26,"reporting":1},
"name":"Clark"},
"Owen":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Owen"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Todd"},
"Grayson":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Grayson"},
"Hart":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Hart"},
"Carlisle":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Carlisle"},
"Lyon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Lyon"},
"Boone":
{"votes":[
{"votes":3108,"name":"clinton"},
{"votes":1510,"name":"obama"},
{"votes":120,"name":"uncommitted-d"},
{"votes":101,"name":"edwards"}],
"total":4839,"precincts":
{"total":60,"reporting":18},
"name":"Boone"},
"Pendleton":
{"votes":[
{"votes":1644,"name":"clinton"},
{"votes":362,"name":"obama"},
{"votes":75,"name":"edwards"},
{"votes":53,"name":"uncommitted-d"}],
"total":2134,"precincts":
{"total":12,"reporting":12},
"name":"Pendleton"},
"Magoffin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Magoffin"},
"Jessamine":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Jessamine"},
"Letcher":
{"votes":[
{"votes":3765,"name":"clinton"},
{"votes":303,"name":"obama"},
{"votes":94,"name":"edwards"},
{"votes":72,"name":"uncommitted-d"}],
"total":4234,"precincts":
{"total":32,"reporting":30},
"name":"Letcher"},
"Jackson":
{"votes":[
{"votes":318,"name":"clinton"},
{"votes":53,"name":"obama"},
{"votes":11,"name":"uncommitted-d"},
{"votes":4,"name":"edwards"}],
"total":386,"precincts":
{"total":14,"reporting":14},
"name":"Jackson"},
"Lawrence":
{"votes":[
{"votes":1981,"name":"clinton"},
{"votes":253,"name":"obama"},
{"votes":54,"name":"edwards"},
{"votes":40,"name":"uncommitted-d"}],
"total":2328,"precincts":
{"total":18,"reporting":18},
"name":"Lawrence"},
"Trigg":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Trigg"},
"McCracken":
{"votes":[],
"total":0,"precincts":
{"total":54,"reporting":0},
"name":"McCracken"},
"Fayette":
{"votes":[
{"votes":12224,"name":"obama"},
{"votes":11082,"name":"clinton"},
{"votes":428,"name":"uncommitted-d"},
{"votes":328,"name":"edwards"}],
"total":24062,"precincts":
{"total":274,"reporting":149},
"name":"Fayette"},
"Floyd":
{"votes":[
{"votes":2272,"name":"clinton"},
{"votes":135,"name":"obama"},
{"votes":52,"name":"uncommitted-d"},
{"votes":52,"name":"edwards"}],
"total":2511,"precincts":
{"total":42,"reporting":8},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":2259,"name":"clinton"},
{"votes":244,"name":"obama"},
{"votes":41,"name":"uncommitted-d"},
{"votes":38,"name":"edwards"}],
"total":2582,"precincts":
{"total":57,"reporting":15},
"name":"Pike"},
"Lincoln":
{"votes":[
{"votes":641,"name":"clinton"},
{"votes":130,"name":"obama"},
{"votes":26,"name":"uncommitted-d"},
{"votes":14,"name":"edwards"}],
"total":811,"precincts":
{"total":17,"reporting":3},
"name":"Lincoln"},
"Ballard":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Ballard"},
"Livingston":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Livingston"},
"Harlan":
{"votes":[
{"votes":4228,"name":"clinton"},
{"votes":460,"name":"obama"},
{"votes":188,"name":"uncommitted-d"},
{"votes":104,"name":"edwards"}],
"total":4980,"precincts":
{"total":35,"reporting":35},
"name":"Harlan"},
"Franklin":
{"votes":[
{"votes":387,"name":"clinton"},
{"votes":210,"name":"obama"},
{"votes":25,"name":"uncommitted-d"},
{"votes":18,"name":"edwards"}],
"total":640,"precincts":
{"total":44,"reporting":0},
"name":"Franklin"},
"Owsley":
{"votes":[
{"votes":269,"name":"clinton"},
{"votes":24,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":2,"name":"uncommitted-d"}],
"total":300,"precincts":
{"total":8,"reporting":8},
"name":"Owsley"},
"Bell":
{"votes":[
{"votes":1721,"name":"clinton"},
{"votes":224,"name":"obama"},
{"votes":39,"name":"uncommitted-d"},
{"votes":39,"name":"edwards"}],
"total":2023,"precincts":
{"total":33,"reporting":23},
"name":"Bell"},
"Marshall":
{"votes":[
{"votes":247,"name":"clinton"},
{"votes":66,"name":"obama"},
{"votes":13,"name":"uncommitted-d"},
{"votes":10,"name":"edwards"}],
"total":336,"precincts":
{"total":25,"reporting":2},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":1629,"name":"clinton"},
{"votes":469,"name":"obama"},
{"votes":52,"name":"edwards"},
{"votes":46,"name":"uncommitted-d"}],
"total":2196,"precincts":
{"total":11,"reporting":11},
"name":"Carroll"},
"Bath":
{"votes":[
{"votes":38,"name":"clinton"},
{"votes":11,"name":"obama"},
{"votes":2,"name":"edwards"}],
"total":51,"precincts":
{"total":12,"reporting":1},
"name":"Bath"},
"Harrison":
{"votes":[
{"votes":1507,"name":"clinton"},
{"votes":429,"name":"obama"},
{"votes":72,"name":"uncommitted-d"},
{"votes":67,"name":"edwards"}],
"total":2075,"precincts":
{"total":16,"reporting":7},
"name":"Harrison"},
"Campbell":
{"votes":[
{"votes":218,"name":"clinton"},
{"votes":135,"name":"obama"},
{"votes":11,"name":"uncommitted-d"},
{"votes":9,"name":"edwards"}],
"total":373,"precincts":
{"total":66,"reporting":1},
"name":"Campbell"},
"Laurel":
{"votes":[
{"votes":123,"name":"clinton"},
{"votes":29,"name":"obama"},
{"votes":3,"name":"uncommitted-d"},
{"votes":1,"name":"edwards"}],
"total":156,"precincts":
{"total":45,"reporting":1},
"name":"Laurel"},
"Mercer":
{"votes":[
{"votes":61,"name":"clinton"},
{"votes":35,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"}],
"total":107,"precincts":
{"total":17,"reporting":0},
"name":"Mercer"},
"Gallatin":
{"votes":[
{"votes":646,"name":"clinton"},
{"votes":166,"name":"obama"},
{"votes":24,"name":"uncommitted-d"},
{"votes":22,"name":"edwards"}],
"total":858,"precincts":
{"total":7,"reporting":5},
"name":"Gallatin"},
"Cumberland":
{"votes":[
{"votes":6,"name":"clinton"},
{"votes":1,"name":"obama"}],
"total":7,"precincts":
{"total":9,"reporting":1},
"name":"Cumberland"},
"Pulaski":
{"votes":[],
"total":0,"precincts":
{"total":57,"reporting":0},
"name":"Pulaski"},
"Rowan":
{"votes":[
{"votes":3284,"name":"clinton"},
{"votes":704,"name":"obama"},
{"votes":64,"name":"uncommitted-d"},
{"votes":64,"name":"edwards"}],
"total":4116,"precincts":
{"total":18,"reporting":18},
"name":"Rowan"},
"Elliott":
{"votes":[
{"votes":1629,"name":"clinton"},
{"votes":129,"name":"obama"},
{"votes":34,"name":"edwards"},
{"votes":25,"name":"uncommitted-d"}],
"total":1817,"precincts":
{"total":7,"reporting":7},
"name":"Elliott"},
"Estill":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Estill"},
"Christian":
{"votes":[
{"votes":133,"name":"clinton"},
{"votes":108,"name":"obama"},
{"votes":8,"name":"edwards"}],
"total":249,"precincts":
{"total":44,"reporting":1},
"name":"Christian"},
"Greenup":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Greenup"},
"Leslie":
{"votes":[
{"votes":328,"name":"clinton"},
{"votes":34,"name":"obama"},
{"votes":20,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"}],
"total":386,"precincts":
{"total":17,"reporting":17},
"name":"Leslie"},
"Knox":
{"votes":[
{"votes":735,"name":"clinton"},
{"votes":109,"name":"obama"},
{"votes":14,"name":"edwards"},
{"votes":9,"name":"uncommitted-d"}],
"total":867,"precincts":
{"total":30,"reporting":14},
"name":"Knox"},
"Hancock":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Hancock"},
"Hardin":
{"votes":[
{"votes":253,"name":"clinton"},
{"votes":118,"name":"obama"},
{"votes":13,"name":"uncommitted-d"},
{"votes":13,"name":"edwards"}],
"total":397,"precincts":
{"total":55,"reporting":1},
"name":"Hardin"},
"LaRue":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"LaRue"},
"Bracken":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Bracken"},
"Meade":
{"votes":[
{"votes":3152,"name":"clinton"},
{"votes":1031,"name":"obama"},
{"votes":122,"name":"uncommitted-d"},
{"votes":91,"name":"edwards"}],
"total":4396,"precincts":
{"total":18,"reporting":16},
"name":"Meade"},
"Morgan":
{"votes":[
{"votes":2499,"name":"clinton"},
{"votes":199,"name":"obama"},
{"votes":57,"name":"uncommitted-d"},
{"votes":55,"name":"edwards"}],
"total":2810,"precincts":
{"total":12,"reporting":12},
"name":"Morgan"},
"Martin":
{"votes":[
{"votes":580,"name":"clinton"},
{"votes":45,"name":"obama"},
{"votes":16,"name":"edwards"},
{"votes":9,"name":"uncommitted-d"}],
"total":650,"precincts":
{"total":14,"reporting":14},
"name":"Martin"},
"Garrard":
{"votes":[
{"votes":33,"name":"clinton"},
{"votes":6,"name":"obama"}],
"total":39,"precincts":
{"total":13,"reporting":1},
"name":"Garrard"},
"Edmonson":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Edmonson"},
"Simpson":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Simpson"},
"Muhlenberg":
{"votes":[
{"votes":195,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":6,"name":"edwards"}],
"total":243,"precincts":
{"total":26,"reporting":0},
"name":"Muhlenberg"},
"Carter":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Carter"},
"Knott":
{"votes":[
{"votes":1340,"name":"clinton"},
{"votes":128,"name":"obama"},
{"votes":30,"name":"uncommitted-d"},
{"votes":28,"name":"edwards"}],
"total":1526,"precincts":
{"total":30,"reporting":9},
"name":"Knott"},
"Lewis":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Lewis"},
"Calloway":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Calloway"},
"Fleming":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Fleming"},
"Logan":
{"votes":[
{"votes":79,"name":"clinton"},
{"votes":23,"name":"obama"},
{"votes":6,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":114,"precincts":
{"total":20,"reporting":1},
"name":"Logan"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Scott"},
"Monroe":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Monroe"}}})