GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":421627,"name":"clinton"},
{"votes":191187,"name":"obama"},
{"votes":16199,"name":"uncommitted-d"},
{"votes":12763,"name":"edwards"}],
"name":"Kentucky","precincts":
{"total":3532,"reporting":3369},
"delegates":51,"date":"05-20"},
"state":"KY","party":"dem","total":641776,"locals":
{"Metcalfe":
{"votes":[
{"votes":1320,"name":"clinton"},
{"votes":225,"name":"obama"},
{"votes":60,"name":"edwards"},
{"votes":45,"name":"uncommitted-d"}],
"total":1650,"precincts":
{"total":12,"reporting":12},
"name":"Metcalfe"},
"Daviess":
{"votes":[
{"votes":12181,"name":"clinton"},
{"votes":5703,"name":"obama"},
{"votes":1031,"name":"uncommitted-d"},
{"votes":463,"name":"edwards"}],
"total":19378,"precincts":
{"total":84,"reporting":84},
"name":"Daviess"},
"Russell":
{"votes":[
{"votes":1026,"name":"clinton"},
{"votes":168,"name":"obama"},
{"votes":21,"name":"uncommitted-d"},
{"votes":18,"name":"edwards"}],
"total":1233,"precincts":
{"total":16,"reporting":16},
"name":"Russell"},
"Shelby":
{"votes":[
{"votes":4287,"name":"clinton"},
{"votes":2297,"name":"obama"},
{"votes":201,"name":"uncommitted-d"},
{"votes":146,"name":"edwards"}],
"total":6931,"precincts":
{"total":33,"reporting":33},
"name":"Shelby"},
"Union":
{"votes":[
{"votes":2249,"name":"clinton"},
{"votes":848,"name":"obama"},
{"votes":127,"name":"uncommitted-d"},
{"votes":80,"name":"edwards"}],
"total":3304,"precincts":
{"total":16,"reporting":16},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":4796,"name":"clinton"},
{"votes":929,"name":"obama"},
{"votes":178,"name":"uncommitted-d"},
{"votes":135,"name":"edwards"}],
"total":6038,"precincts":
{"total":18,"reporting":18},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":1663,"name":"clinton"},
{"votes":214,"name":"obama"},
{"votes":23,"name":"uncommitted-d"},
{"votes":21,"name":"edwards"}],
"total":1921,"precincts":
{"total":19,"reporting":19},
"name":"Wayne"},
"Robertson":
{"votes":[
{"votes":387,"name":"clinton"},
{"votes":90,"name":"obama"},
{"votes":26,"name":"edwards"},
{"votes":20,"name":"uncommitted-d"}],
"total":523,"precincts":
{"total":5,"reporting":5},
"name":"Robertson"},
"Bourbon":
{"votes":[
{"votes":2334,"name":"clinton"},
{"votes":808,"name":"obama"},
{"votes":140,"name":"uncommitted-d"},
{"votes":93,"name":"edwards"}],
"total":3375,"precincts":
{"total":18,"reporting":18},
"name":"Bourbon"},
"Nicholas":
{"votes":[
{"votes":1520,"name":"clinton"},
{"votes":270,"name":"obama"},
{"votes":65,"name":"uncommitted-d"},
{"votes":39,"name":"edwards"}],
"total":1894,"precincts":
{"total":5,"reporting":5},
"name":"Nicholas"},
"Powell":
{"votes":[
{"votes":2629,"name":"clinton"},
{"votes":336,"name":"obama"},
{"votes":77,"name":"edwards"},
{"votes":67,"name":"uncommitted-d"}],
"total":3109,"precincts":
{"total":11,"reporting":11},
"name":"Powell"},
"Boyle":
{"votes":[
{"votes":3288,"name":"clinton"},
{"votes":1577,"name":"obama"},
{"votes":242,"name":"uncommitted-d"},
{"votes":108,"name":"edwards"}],
"total":5215,"precincts":
{"total":25,"reporting":25},
"name":"Boyle"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Henderson"},
"Menifee":
{"votes":[
{"votes":1527,"name":"clinton"},
{"votes":143,"name":"obama"},
{"votes":30,"name":"edwards"},
{"votes":25,"name":"uncommitted-d"}],
"total":1725,"precincts":
{"total":6,"reporting":6},
"name":"Menifee"},
"Breckinridge":
{"votes":[
{"votes":2264,"name":"clinton"},
{"votes":621,"name":"obama"},
{"votes":81,"name":"edwards"},
{"votes":66,"name":"uncommitted-d"}],
"total":3032,"precincts":
{"total":15,"reporting":15},
"name":"Breckinridge"},
"Casey":
{"votes":[
{"votes":616,"name":"clinton"},
{"votes":118,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"}],
"total":776,"precincts":
{"total":15,"reporting":15},
"name":"Casey"},
"Adair":
{"votes":[
{"votes":1255,"name":"clinton"},
{"votes":232,"name":"obama"},
{"votes":1,"name":"uncommitted-d"},
{"votes":1,"name":"edwards"}],
"total":1489,"precincts":
{"total":16,"reporting":16},
"name":"Adair"},
"McCreary":
{"votes":[
{"votes":819,"name":"clinton"},
{"votes":108,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"}],
"total":969,"precincts":
{"total":18,"reporting":18},
"name":"McCreary"},
"Nelson":
{"votes":[
{"votes":5977,"name":"clinton"},
{"votes":2180,"name":"obama"},
{"votes":163,"name":"uncommitted-d"},
{"votes":146,"name":"edwards"}],
"total":8466,"precincts":
{"total":26,"reporting":26},
"name":"Nelson"},
"Henry":
{"votes":[
{"votes":2291,"name":"clinton"},
{"votes":816,"name":"obama"},
{"votes":121,"name":"uncommitted-d"},
{"votes":115,"name":"edwards"}],
"total":3343,"precincts":
{"total":20,"reporting":20},
"name":"Henry"},
"Barren":
{"votes":[
{"votes":152,"name":"clinton"},
{"votes":62,"name":"obama"},
{"votes":6,"name":"uncommitted-d"},
{"votes":2,"name":"edwards"}],
"total":222,"precincts":
{"total":24,"reporting":1},
"name":"Barren"},
"Webster":
{"votes":[
{"votes":2398,"name":"clinton"},
{"votes":668,"name":"obama"},
{"votes":106,"name":"uncommitted-d"},
{"votes":79,"name":"edwards"}],
"total":3251,"precincts":
{"total":14,"reporting":14},
"name":"Webster"},
"Bullitt":
{"votes":[
{"votes":6047,"name":"clinton"},
{"votes":1353,"name":"obama"},
{"votes":235,"name":"uncommitted-d"},
{"votes":197,"name":"edwards"}],
"total":7832,"precincts":
{"total":44,"reporting":42},
"name":"Bullitt"},
"Washington":
{"votes":[
{"votes":1828,"name":"clinton"},
{"votes":516,"name":"obama"},
{"votes":62,"name":"edwards"},
{"votes":61,"name":"uncommitted-d"}],
"total":2467,"precincts":
{"total":14,"reporting":14},
"name":"Washington"},
"Trimble":
{"votes":[
{"votes":1518,"name":"clinton"},
{"votes":278,"name":"obama"},
{"votes":61,"name":"edwards"},
{"votes":60,"name":"uncommitted-d"}],
"total":1917,"precincts":
{"total":12,"reporting":12},
"name":"Trimble"},
"Marion":
{"votes":[
{"votes":3661,"name":"clinton"},
{"votes":822,"name":"obama"},
{"votes":86,"name":"uncommitted-d"},
{"votes":65,"name":"edwards"}],
"total":4634,"precincts":
{"total":16,"reporting":16},
"name":"Marion"},
"Hickman":
{"votes":[
{"votes":906,"name":"clinton"},
{"votes":240,"name":"obama"},
{"votes":56,"name":"uncommitted-d"},
{"votes":53,"name":"edwards"}],
"total":1255,"precincts":
{"total":6,"reporting":6},
"name":"Hickman"},
"Allen":
{"votes":[
{"votes":1354,"name":"clinton"},
{"votes":247,"name":"obama"},
{"votes":50,"name":"edwards"}],
"total":1651,"precincts":
{"total":13,"reporting":13},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":8919,"name":"clinton"},
{"votes":4702,"name":"obama"},
{"votes":415,"name":"uncommitted-d"},
{"votes":331,"name":"edwards"}],
"total":14367,"precincts":
{"total":63,"reporting":63},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":5466,"name":"clinton"},
{"votes":542,"name":"obama"},
{"votes":137,"name":"edwards"},
{"votes":134,"name":"uncommitted-d"}],
"total":6279,"precincts":
{"total":37,"reporting":37},
"name":"Perry"},
"Graves":
{"votes":[
{"votes":6106,"name":"clinton"},
{"votes":1407,"name":"obama"},
{"votes":376,"name":"uncommitted-d"},
{"votes":267,"name":"edwards"}],
"total":8156,"precincts":
{"total":30,"reporting":30},
"name":"Graves"},
"Grant":
{"votes":[
{"votes":2325,"name":"clinton"},
{"votes":554,"name":"obama"},
{"votes":93,"name":"uncommitted-d"},
{"votes":81,"name":"edwards"}],
"total":3053,"precincts":
{"total":23,"reporting":23},
"name":"Grant"},
"Caldwell":
{"votes":[
{"votes":2171,"name":"clinton"},
{"votes":526,"name":"obama"},
{"votes":98,"name":"uncommitted-d"},
{"votes":86,"name":"edwards"}],
"total":2881,"precincts":
{"total":12,"reporting":12},
"name":"Caldwell"},
"Oldham":
{"votes":[
{"votes":105,"name":"clinton"},
{"votes":73,"name":"obama"},
{"votes":4,"name":"uncommitted-d"},
{"votes":1,"name":"edwards"}],
"total":183,"precincts":
{"total":34,"reporting":34},
"name":"Oldham"},
"Mason":
{"votes":[
{"votes":2399,"name":"clinton"},
{"votes":779,"name":"obama"},
{"votes":80,"name":"uncommitted-d"},
{"votes":56,"name":"edwards"}],
"total":3314,"precincts":
{"total":20,"reporting":20},
"name":"Mason"},
"Wolfe":
{"votes":[
{"votes":1795,"name":"clinton"},
{"votes":143,"name":"obama"},
{"votes":48,"name":"edwards"},
{"votes":40,"name":"uncommitted-d"}],
"total":2026,"precincts":
{"total":8,"reporting":8},
"name":"Wolfe"},
"Anderson":
{"votes":[
{"votes":3481,"name":"clinton"},
{"votes":1130,"name":"obama"},
{"votes":240,"name":"uncommitted-d"},
{"votes":184,"name":"edwards"}],
"total":5035,"precincts":
{"total":14,"reporting":14},
"name":"Anderson"},
"Jefferson":
{"votes":[
{"votes":70424,"name":"obama"},
{"votes":60732,"name":"clinton"},
{"votes":2042,"name":"uncommitted-d"},
{"votes":1620,"name":"edwards"}],
"total":134818,"precincts":
{"total":513,"reporting":484},
"name":"Jefferson"},
"Crittenden":
{"votes":[
{"votes":1071,"name":"clinton"},
{"votes":174,"name":"obama"},
{"votes":41,"name":"edwards"},
{"votes":24,"name":"uncommitted-d"}],
"total":1310,"precincts":
{"total":12,"reporting":12},
"name":"Crittenden"},
"Butler":
{"votes":[
{"votes":598,"name":"clinton"},
{"votes":140,"name":"obama"},
{"votes":15,"name":"edwards"},
{"votes":13,"name":"uncommitted-d"}],
"total":766,"precincts":
{"total":12,"reporting":12},
"name":"Butler"},
"Breathitt":
{"votes":[
{"votes":3350,"name":"clinton"},
{"votes":251,"name":"obama"},
{"votes":69,"name":"uncommitted-d"},
{"votes":53,"name":"edwards"}],
"total":3723,"precincts":
{"total":21,"reporting":21},
"name":"Breathitt"},
"Kenton":
{"votes":[
{"votes":10580,"name":"clinton"},
{"votes":5856,"name":"obama"},
{"votes":537,"name":"uncommitted-d"},
{"votes":308,"name":"edwards"}],
"total":17281,"precincts":
{"total":108,"reporting":108},
"name":"Kenton"},
"Lee":
{"votes":[
{"votes":702,"name":"clinton"},
{"votes":76,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"}],
"total":793,"precincts":
{"total":10,"reporting":10},
"name":"Lee"},
"Boyd":
{"votes":[
{"votes":6741,"name":"clinton"},
{"votes":1490,"name":"obama"},
{"votes":317,"name":"uncommitted-d"},
{"votes":214,"name":"edwards"}],
"total":8762,"precincts":
{"total":47,"reporting":47},
"name":"Boyd"},
"Rockcastle":
{"votes":[
{"votes":664,"name":"clinton"},
{"votes":106,"name":"obama"},
{"votes":11,"name":"edwards"},
{"votes":7,"name":"uncommitted-d"}],
"total":788,"precincts":
{"total":14,"reporting":14},
"name":"Rockcastle"},
"McLean":
{"votes":[
{"votes":1644,"name":"clinton"},
{"votes":395,"name":"obama"},
{"votes":60,"name":"uncommitted-d"},
{"votes":50,"name":"edwards"}],
"total":2149,"precincts":
{"total":8,"reporting":8},
"name":"McLean"},
"Johnson":
{"votes":[
{"votes":2183,"name":"clinton"},
{"votes":226,"name":"obama"},
{"votes":57,"name":"edwards"},
{"votes":45,"name":"uncommitted-d"}],
"total":2511,"precincts":
{"total":31,"reporting":31},
"name":"Johnson"},
"Hopkins":
{"votes":[
{"votes":6739,"name":"clinton"},
{"votes":2118,"name":"obama"},
{"votes":265,"name":"uncommitted-d"},
{"votes":194,"name":"edwards"}],
"total":9316,"precincts":
{"total":40,"reporting":40},
"name":"Hopkins"},
"Whitley":
{"votes":[
{"votes":1831,"name":"clinton"},
{"votes":249,"name":"obama"},
{"votes":47,"name":"edwards"},
{"votes":37,"name":"uncommitted-d"}],
"total":2164,"precincts":
{"total":36,"reporting":36},
"name":"Whitley"},
"Woodford":
{"votes":[
{"votes":2894,"name":"clinton"},
{"votes":1895,"name":"obama"},
{"votes":187,"name":"uncommitted-d"},
{"votes":120,"name":"edwards"}],
"total":5096,"precincts":
{"total":16,"reporting":16},
"name":"Woodford"},
"Green":
{"votes":[
{"votes":1085,"name":"clinton"},
{"votes":204,"name":"obama"},
{"votes":40,"name":"edwards"},
{"votes":30,"name":"uncommitted-d"}],
"total":1359,"precincts":
{"total":10,"reporting":10},
"name":"Green"},
"Clay":
{"votes":[
{"votes":553,"name":"clinton"},
{"votes":68,"name":"obama"},
{"votes":15,"name":"uncommitted-d"},
{"votes":13,"name":"edwards"}],
"total":649,"precincts":
{"total":20,"reporting":20},
"name":"Clay"},
"Ohio":
{"votes":[
{"votes":2224,"name":"clinton"},
{"votes":605,"name":"obama"},
{"votes":80,"name":"uncommitted-d"},
{"votes":79,"name":"edwards"}],
"total":2988,"precincts":
{"total":25,"reporting":20},
"name":"Ohio"},
"Spencer":
{"votes":[
{"votes":2217,"name":"clinton"},
{"votes":630,"name":"obama"},
{"votes":106,"name":"uncommitted-d"},
{"votes":95,"name":"edwards"}],
"total":3048,"precincts":
{"total":11,"reporting":11},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":960,"name":"clinton"},
{"votes":402,"name":"obama"},
{"votes":63,"name":"uncommitted-d"},
{"votes":44,"name":"edwards"}],
"total":1469,"precincts":
{"total":12,"reporting":12},
"name":"Fulton"},
"Madison":
{"votes":[
{"votes":8025,"name":"clinton"},
{"votes":3056,"name":"obama"},
{"votes":240,"name":"uncommitted-d"},
{"votes":209,"name":"edwards"}],
"total":11530,"precincts":
{"total":56,"reporting":56},
"name":"Madison"},
"Taylor":
{"votes":[
{"votes":2875,"name":"clinton"},
{"votes":607,"name":"obama"},
{"votes":90,"name":"uncommitted-d"},
{"votes":76,"name":"edwards"}],
"total":3648,"precincts":
{"total":20,"reporting":20},
"name":"Taylor"},
"Clinton":
{"votes":[
{"votes":529,"name":"clinton"},
{"votes":39,"name":"obama"},
{"votes":5,"name":"uncommitted-d"},
{"votes":3,"name":"edwards"}],
"total":576,"precincts":
{"total":13,"reporting":13},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":4690,"name":"clinton"},
{"votes":1505,"name":"obama"},
{"votes":223,"name":"uncommitted-d"},
{"votes":107,"name":"edwards"}],
"total":6525,"precincts":
{"total":26,"reporting":26},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":1757,"name":"clinton"},
{"votes":406,"name":"obama"},
{"votes":91,"name":"uncommitted-d"},
{"votes":64,"name":"edwards"}],
"total":2318,"precincts":
{"total":13,"reporting":13},
"name":"Owen"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Todd"},
"Grayson":
{"votes":[
{"votes":1767,"name":"clinton"},
{"votes":514,"name":"obama"},
{"votes":47,"name":"uncommitted-d"},
{"votes":45,"name":"edwards"}],
"total":2373,"precincts":
{"total":23,"reporting":23},
"name":"Grayson"},
"Hart":
{"votes":[
{"votes":2448,"name":"clinton"},
{"votes":527,"name":"obama"},
{"votes":75,"name":"edwards"},
{"votes":48,"name":"uncommitted-d"}],
"total":3098,"precincts":
{"total":19,"reporting":19},
"name":"Hart"},
"Carlisle":
{"votes":[
{"votes":1137,"name":"clinton"},
{"votes":178,"name":"obama"},
{"votes":93,"name":"uncommitted-d"},
{"votes":76,"name":"edwards"}],
"total":1484,"precincts":
{"total":6,"reporting":6},
"name":"Carlisle"},
"Lyon":
{"votes":[
{"votes":1643,"name":"clinton"},
{"votes":375,"name":"obama"},
{"votes":85,"name":"uncommitted-d"},
{"votes":65,"name":"edwards"}],
"total":2168,"precincts":
{"total":6,"reporting":6},
"name":"Lyon"},
"Boone":
{"votes":[
{"votes":6305,"name":"clinton"},
{"votes":2997,"name":"obama"},
{"votes":221,"name":"uncommitted-d"},
{"votes":181,"name":"edwards"}],
"total":9704,"precincts":
{"total":60,"reporting":60},
"name":"Boone"},
"Pendleton":
{"votes":[
{"votes":1644,"name":"clinton"},
{"votes":362,"name":"obama"},
{"votes":75,"name":"edwards"},
{"votes":53,"name":"uncommitted-d"}],
"total":2134,"precincts":
{"total":12,"reporting":12},
"name":"Pendleton"},
"Magoffin":
{"votes":[
{"votes":2714,"name":"clinton"},
{"votes":146,"name":"obama"},
{"votes":31,"name":"uncommitted-d"},
{"votes":28,"name":"edwards"}],
"total":2919,"precincts":
{"total":14,"reporting":14},
"name":"Magoffin"},
"Jessamine":
{"votes":[
{"votes":4286,"name":"clinton"},
{"votes":1546,"name":"obama"},
{"votes":204,"name":"uncommitted-d"},
{"votes":164,"name":"edwards"}],
"total":6200,"precincts":
{"total":37,"reporting":37},
"name":"Jessamine"},
"Letcher":
{"votes":[
{"votes":4016,"name":"clinton"},
{"votes":320,"name":"obama"},
{"votes":110,"name":"edwards"},
{"votes":77,"name":"uncommitted-d"}],
"total":4523,"precincts":
{"total":32,"reporting":32},
"name":"Letcher"},
"Jackson":
{"votes":[
{"votes":318,"name":"clinton"},
{"votes":53,"name":"obama"},
{"votes":11,"name":"uncommitted-d"},
{"votes":4,"name":"edwards"}],
"total":386,"precincts":
{"total":14,"reporting":14},
"name":"Jackson"},
"Lawrence":
{"votes":[
{"votes":1981,"name":"clinton"},
{"votes":253,"name":"obama"},
{"votes":54,"name":"edwards"},
{"votes":40,"name":"uncommitted-d"}],
"total":2328,"precincts":
{"total":18,"reporting":18},
"name":"Lawrence"},
"Trigg":
{"votes":[
{"votes":1773,"name":"clinton"},
{"votes":641,"name":"obama"},
{"votes":98,"name":"edwards"},
{"votes":92,"name":"uncommitted-d"}],
"total":2604,"precincts":
{"total":14,"reporting":14},
"name":"Trigg"},
"McCracken":
{"votes":[
{"votes":7770,"name":"clinton"},
{"votes":3572,"name":"obama"},
{"votes":372,"name":"uncommitted-d"},
{"votes":222,"name":"edwards"}],
"total":11936,"precincts":
{"total":54,"reporting":54},
"name":"McCracken"},
"Fayette":
{"votes":[
{"votes":22978,"name":"obama"},
{"votes":20352,"name":"clinton"},
{"votes":737,"name":"uncommitted-d"},
{"votes":618,"name":"edwards"}],
"total":44685,"precincts":
{"total":274,"reporting":274},
"name":"Fayette"},
"Floyd":
{"votes":[
{"votes":11215,"name":"clinton"},
{"votes":653,"name":"obama"},
{"votes":205,"name":"edwards"},
{"votes":176,"name":"uncommitted-d"}],
"total":12249,"precincts":
{"total":42,"reporting":40},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":12915,"name":"clinton"},
{"votes":936,"name":"obama"},
{"votes":196,"name":"uncommitted-d"},
{"votes":164,"name":"edwards"}],
"total":14211,"precincts":
{"total":57,"reporting":57},
"name":"Pike"},
"Lincoln":
{"votes":[
{"votes":2519,"name":"clinton"},
{"votes":443,"name":"obama"},
{"votes":71,"name":"edwards"},
{"votes":67,"name":"uncommitted-d"}],
"total":3100,"precincts":
{"total":17,"reporting":17},
"name":"Lincoln"},
"Ballard":
{"votes":[
{"votes":1659,"name":"clinton"},
{"votes":348,"name":"obama"},
{"votes":109,"name":"uncommitted-d"},
{"votes":106,"name":"edwards"}],
"total":2222,"precincts":
{"total":13,"reporting":13},
"name":"Ballard"},
"Livingston":
{"votes":[
{"votes":1033,"name":"clinton"},
{"votes":142,"name":"obama"},
{"votes":43,"name":"uncommitted-d"},
{"votes":33,"name":"edwards"}],
"total":1251,"precincts":
{"total":10,"reporting":6},
"name":"Livingston"},
"Harlan":
{"votes":[
{"votes":4228,"name":"clinton"},
{"votes":460,"name":"obama"},
{"votes":188,"name":"uncommitted-d"},
{"votes":104,"name":"edwards"}],
"total":4980,"precincts":
{"total":35,"reporting":35},
"name":"Harlan"},
"Franklin":
{"votes":[
{"votes":4883,"name":"clinton"},
{"votes":2581,"name":"obama"},
{"votes":316,"name":"uncommitted-d"},
{"votes":191,"name":"edwards"}],
"total":7971,"precincts":
{"total":44,"reporting":44},
"name":"Franklin"},
"Owsley":
{"votes":[
{"votes":269,"name":"clinton"},
{"votes":24,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":2,"name":"uncommitted-d"}],
"total":300,"precincts":
{"total":8,"reporting":8},
"name":"Owsley"},
"Bell":
{"votes":[
{"votes":2381,"name":"clinton"},
{"votes":323,"name":"obama"},
{"votes":53,"name":"edwards"},
{"votes":48,"name":"uncommitted-d"}],
"total":2805,"precincts":
{"total":33,"reporting":33},
"name":"Bell"},
"Marshall":
{"votes":[
{"votes":5574,"name":"clinton"},
{"votes":1140,"name":"obama"},
{"votes":273,"name":"uncommitted-d"},
{"votes":237,"name":"edwards"}],
"total":7224,"precincts":
{"total":25,"reporting":25},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":1629,"name":"clinton"},
{"votes":469,"name":"obama"},
{"votes":52,"name":"edwards"},
{"votes":46,"name":"uncommitted-d"}],
"total":2196,"precincts":
{"total":11,"reporting":11},
"name":"Carroll"},
"Bath":
{"votes":[
{"votes":2656,"name":"clinton"},
{"votes":401,"name":"obama"},
{"votes":70,"name":"uncommitted-d"},
{"votes":69,"name":"edwards"}],
"total":3196,"precincts":
{"total":12,"reporting":12},
"name":"Bath"},
"Harrison":
{"votes":[
{"votes":2613,"name":"clinton"},
{"votes":761,"name":"obama"},
{"votes":125,"name":"uncommitted-d"},
{"votes":111,"name":"edwards"}],
"total":3610,"precincts":
{"total":16,"reporting":16},
"name":"Harrison"},
"Campbell":
{"votes":[
{"votes":6529,"name":"clinton"},
{"votes":3289,"name":"obama"},
{"votes":278,"name":"uncommitted-d"},
{"votes":205,"name":"edwards"}],
"total":10301,"precincts":
{"total":66,"reporting":66},
"name":"Campbell"},
"Laurel":
{"votes":[
{"votes":2581,"name":"clinton"},
{"votes":406,"name":"obama"},
{"votes":53,"name":"edwards"},
{"votes":41,"name":"uncommitted-d"}],
"total":3081,"precincts":
{"total":45,"reporting":45},
"name":"Laurel"},
"Mercer":
{"votes":[
{"votes":3202,"name":"clinton"},
{"votes":1040,"name":"obama"},
{"votes":193,"name":"uncommitted-d"},
{"votes":156,"name":"edwards"}],
"total":4591,"precincts":
{"total":17,"reporting":17},
"name":"Mercer"},
"Gallatin":
{"votes":[
{"votes":1092,"name":"clinton"},
{"votes":285,"name":"obama"},
{"votes":39,"name":"uncommitted-d"},
{"votes":38,"name":"edwards"}],
"total":1454,"precincts":
{"total":7,"reporting":7},
"name":"Gallatin"},
"Cumberland":
{"votes":[
{"votes":279,"name":"clinton"},
{"votes":68,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"}],
"total":356,"precincts":
{"total":9,"reporting":9},
"name":"Cumberland"},
"Pulaski":
{"votes":[
{"votes":3147,"name":"clinton"},
{"votes":686,"name":"obama"},
{"votes":88,"name":"edwards"},
{"votes":57,"name":"uncommitted-d"}],
"total":3978,"precincts":
{"total":57,"reporting":57},
"name":"Pulaski"},
"Rowan":
{"votes":[
{"votes":3284,"name":"clinton"},
{"votes":704,"name":"obama"},
{"votes":64,"name":"uncommitted-d"},
{"votes":64,"name":"edwards"}],
"total":4116,"precincts":
{"total":18,"reporting":18},
"name":"Rowan"},
"Elliott":
{"votes":[
{"votes":1629,"name":"clinton"},
{"votes":129,"name":"obama"},
{"votes":34,"name":"edwards"},
{"votes":25,"name":"uncommitted-d"}],
"total":1817,"precincts":
{"total":7,"reporting":7},
"name":"Elliott"},
"Estill":
{"votes":[
{"votes":1423,"name":"clinton"},
{"votes":156,"name":"obama"},
{"votes":33,"name":"edwards"},
{"votes":19,"name":"uncommitted-d"}],
"total":1631,"precincts":
{"total":15,"reporting":15},
"name":"Estill"},
"Christian":
{"votes":[
{"votes":4584,"name":"clinton"},
{"votes":3075,"name":"obama"},
{"votes":357,"name":"uncommitted-d"},
{"votes":246,"name":"edwards"}],
"total":8262,"precincts":
{"total":44,"reporting":44},
"name":"Christian"},
"Greenup":
{"votes":[
{"votes":5434,"name":"clinton"},
{"votes":984,"name":"obama"},
{"votes":174,"name":"uncommitted-d"},
{"votes":143,"name":"edwards"}],
"total":6735,"precincts":
{"total":32,"reporting":32},
"name":"Greenup"},
"Leslie":
{"votes":[
{"votes":328,"name":"clinton"},
{"votes":34,"name":"obama"},
{"votes":20,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"}],
"total":386,"precincts":
{"total":17,"reporting":17},
"name":"Leslie"},
"Knox":
{"votes":[
{"votes":2019,"name":"clinton"},
{"votes":292,"name":"obama"},
{"votes":47,"name":"edwards"},
{"votes":29,"name":"uncommitted-d"}],
"total":2387,"precincts":
{"total":30,"reporting":30},
"name":"Knox"},
"Hancock":
{"votes":[
{"votes":1330,"name":"clinton"},
{"votes":499,"name":"obama"},
{"votes":40,"name":"uncommitted-d"},
{"votes":39,"name":"edwards"}],
"total":1908,"precincts":
{"total":10,"reporting":10},
"name":"Hancock"},
"Hardin":
{"votes":[
{"votes":7877,"name":"clinton"},
{"votes":4770,"name":"obama"},
{"votes":482,"name":"uncommitted-d"},
{"votes":342,"name":"edwards"}],
"total":13471,"precincts":
{"total":55,"reporting":55},
"name":"Hardin"},
"LaRue":
{"votes":[
{"votes":1974,"name":"clinton"},
{"votes":544,"name":"obama"},
{"votes":111,"name":"uncommitted-d"},
{"votes":92,"name":"edwards"}],
"total":2721,"precincts":
{"total":12,"reporting":12},
"name":"LaRue"},
"Bracken":
{"votes":[
{"votes":1332,"name":"clinton"},
{"votes":275,"name":"obama"},
{"votes":74,"name":"uncommitted-d"},
{"votes":55,"name":"edwards"}],
"total":1736,"precincts":
{"total":8,"reporting":8},
"name":"Bracken"},
"Meade":
{"votes":[
{"votes":3506,"name":"clinton"},
{"votes":1108,"name":"obama"},
{"votes":133,"name":"uncommitted-d"},
{"votes":100,"name":"edwards"}],
"total":4847,"precincts":
{"total":18,"reporting":18},
"name":"Meade"},
"Morgan":
{"votes":[
{"votes":2499,"name":"clinton"},
{"votes":199,"name":"obama"},
{"votes":57,"name":"uncommitted-d"},
{"votes":55,"name":"edwards"}],
"total":2810,"precincts":
{"total":12,"reporting":12},
"name":"Morgan"},
"Martin":
{"votes":[
{"votes":580,"name":"clinton"},
{"votes":45,"name":"obama"},
{"votes":16,"name":"edwards"},
{"votes":9,"name":"uncommitted-d"}],
"total":650,"precincts":
{"total":14,"reporting":14},
"name":"Martin"},
"Garrard":
{"votes":[
{"votes":1257,"name":"clinton"},
{"votes":299,"name":"obama"},
{"votes":40,"name":"uncommitted-d"},
{"votes":22,"name":"edwards"}],
"total":1618,"precincts":
{"total":13,"reporting":13},
"name":"Garrard"},
"Edmonson":
{"votes":[
{"votes":1040,"name":"clinton"},
{"votes":152,"name":"obama"},
{"votes":14,"name":"edwards"},
{"votes":11,"name":"uncommitted-d"}],
"total":1217,"precincts":
{"total":10,"reporting":10},
"name":"Edmonson"},
"Simpson":
{"votes":[
{"votes":2006,"name":"clinton"},
{"votes":734,"name":"obama"},
{"votes":102,"name":"uncommitted-d"},
{"votes":71,"name":"edwards"}],
"total":2913,"precincts":
{"total":13,"reporting":13},
"name":"Simpson"},
"Muhlenberg":
{"votes":[
{"votes":5602,"name":"clinton"},
{"votes":1176,"name":"obama"},
{"votes":187,"name":"uncommitted-d"},
{"votes":166,"name":"edwards"}],
"total":7131,"precincts":
{"total":26,"reporting":26},
"name":"Muhlenberg"},
"Carter":
{"votes":[
{"votes":3868,"name":"clinton"},
{"votes":412,"name":"obama"},
{"votes":93,"name":"uncommitted-d"},
{"votes":64,"name":"edwards"}],
"total":4437,"precincts":
{"total":23,"reporting":23},
"name":"Carter"},
"Knott":
{"votes":[
{"votes":2069,"name":"clinton"},
{"votes":181,"name":"obama"},
{"votes":55,"name":"edwards"},
{"votes":44,"name":"uncommitted-d"}],
"total":2349,"precincts":
{"total":30,"reporting":15},
"name":"Knott"},
"Lewis":
{"votes":[
{"votes":753,"name":"clinton"},
{"votes":80,"name":"obama"},
{"votes":21,"name":"uncommitted-d"},
{"votes":12,"name":"edwards"}],
"total":866,"precincts":
{"total":14,"reporting":14},
"name":"Lewis"},
"Calloway":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Calloway"},
"Fleming":
{"votes":[
{"votes":2450,"name":"clinton"},
{"votes":381,"name":"obama"},
{"votes":59,"name":"uncommitted-d"},
{"votes":59,"name":"edwards"}],
"total":2949,"precincts":
{"total":18,"reporting":18},
"name":"Fleming"},
"Logan":
{"votes":[
{"votes":3608,"name":"clinton"},
{"votes":1114,"name":"obama"},
{"votes":267,"name":"uncommitted-d"},
{"votes":182,"name":"edwards"}],
"total":5171,"precincts":
{"total":20,"reporting":20},
"name":"Logan"},
"Scott":
{"votes":[
{"votes":4645,"name":"clinton"},
{"votes":2224,"name":"obama"},
{"votes":206,"name":"uncommitted-d"},
{"votes":140,"name":"edwards"}],
"total":7215,"precincts":
{"total":35,"reporting":35},
"name":"Scott"},
"Monroe":
{"votes":[
{"votes":268,"name":"clinton"},
{"votes":56,"name":"obama"},
{"votes":8,"name":"edwards"},
{"votes":2,"name":"uncommitted-d"}],
"total":334,"precincts":
{"total":12,"reporting":12},
"name":"Monroe"}}})