GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":102854,"name":"clinton"},
{"votes":77009,"name":"obama"},
{"votes":3366,"name":"uncommitted-d"},
{"votes":2830,"name":"edwards"}],
"name":"Kentucky","precincts":
{"total":3532,"reporting":874},
"delegates":51,"date":"05-20"},
"state":"KY","party":"dem","total":186059,"locals":
{"Metcalfe":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Metcalfe"},
"Daviess":
{"votes":[],
"total":0,"precincts":
{"total":84,"reporting":0},
"name":"Daviess"},
"Russell":
{"votes":[
{"votes":60,"name":"clinton"},
{"votes":9,"name":"obama"},
{"votes":1,"name":"edwards"}],
"total":70,"precincts":
{"total":16,"reporting":1},
"name":"Russell"},
"Shelby":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":96,"name":"clinton"},
{"votes":8,"name":"obama"},
{"votes":1,"name":"edwards"}],
"total":105,"precincts":
{"total":19,"reporting":1},
"name":"Wayne"},
"Robertson":
{"votes":[
{"votes":387,"name":"clinton"},
{"votes":90,"name":"obama"},
{"votes":26,"name":"edwards"},
{"votes":20,"name":"uncommitted-d"}],
"total":523,"precincts":
{"total":5,"reporting":5},
"name":"Robertson"},
"Bourbon":
{"votes":[
{"votes":128,"name":"clinton"},
{"votes":40,"name":"obama"},
{"votes":16,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":190,"precincts":
{"total":18,"reporting":1},
"name":"Bourbon"},
"Nicholas":
{"votes":[
{"votes":1520,"name":"clinton"},
{"votes":270,"name":"obama"},
{"votes":65,"name":"uncommitted-d"},
{"votes":39,"name":"edwards"}],
"total":1894,"precincts":
{"total":5,"reporting":5},
"name":"Nicholas"},
"Powell":
{"votes":[
{"votes":104,"name":"clinton"},
{"votes":10,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":3,"name":"uncommitted-d"}],
"total":122,"precincts":
{"total":11,"reporting":1},
"name":"Powell"},
"Boyle":
{"votes":[
{"votes":75,"name":"clinton"},
{"votes":65,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"}],
"total":150,"precincts":
{"total":25,"reporting":0},
"name":"Boyle"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Henderson"},
"Menifee":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Menifee"},
"Breckinridge":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Breckinridge"},
"Casey":
{"votes":[
{"votes":251,"name":"clinton"},
{"votes":47,"name":"obama"},
{"votes":7,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":311,"precincts":
{"total":15,"reporting":6},
"name":"Casey"},
"Adair":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Adair"},
"McCreary":
{"votes":[
{"votes":27,"name":"clinton"},
{"votes":5,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":35,"precincts":
{"total":18,"reporting":1},
"name":"McCreary"},
"Nelson":
{"votes":[
{"votes":149,"name":"clinton"},
{"votes":81,"name":"obama"},
{"votes":6,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":242,"precincts":
{"total":26,"reporting":1},
"name":"Nelson"},
"Henry":
{"votes":[
{"votes":46,"name":"clinton"},
{"votes":21,"name":"obama"},
{"votes":3,"name":"edwards"}],
"total":70,"precincts":
{"total":20,"reporting":0},
"name":"Henry"},
"Barren":
{"votes":[
{"votes":152,"name":"clinton"},
{"votes":62,"name":"obama"},
{"votes":6,"name":"uncommitted-d"},
{"votes":2,"name":"edwards"}],
"total":222,"precincts":
{"total":24,"reporting":1},
"name":"Barren"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Webster"},
"Bullitt":
{"votes":[
{"votes":192,"name":"clinton"},
{"votes":75,"name":"obama"},
{"votes":7,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":280,"precincts":
{"total":44,"reporting":1},
"name":"Bullitt"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Washington"},
"Trimble":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Trimble"},
"Marion":
{"votes":[
{"votes":3171,"name":"clinton"},
{"votes":866,"name":"obama"},
{"votes":72,"name":"uncommitted-d"},
{"votes":60,"name":"edwards"}],
"total":4169,"precincts":
{"total":16,"reporting":16},
"name":"Marion"},
"Hickman":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Hickman"},
"Allen":
{"votes":[
{"votes":56,"name":"clinton"},
{"votes":8,"name":"obama"},
{"votes":3,"name":"edwards"}],
"total":67,"precincts":
{"total":13,"reporting":0},
"name":"Allen"},
"Warren":
{"votes":[],
"total":0,"precincts":
{"total":63,"reporting":0},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":1861,"name":"clinton"},
{"votes":183,"name":"obama"},
{"votes":46,"name":"edwards"},
{"votes":40,"name":"uncommitted-d"}],
"total":2130,"precincts":
{"total":37,"reporting":20},
"name":"Perry"},
"Graves":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Graves"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Grant"},
"Caldwell":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Caldwell"},
"Oldham":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Oldham"},
"Mason":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Mason"},
"Wolfe":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Wolfe"},
"Anderson":
{"votes":[
{"votes":92,"name":"clinton"},
{"votes":27,"name":"obama"},
{"votes":9,"name":"uncommitted-d"},
{"votes":8,"name":"edwards"}],
"total":136,"precincts":
{"total":14,"reporting":1},
"name":"Anderson"},
"Jefferson":
{"votes":[
{"votes":58676,"name":"obama"},
{"votes":57573,"name":"clinton"},
{"votes":1934,"name":"uncommitted-d"},
{"votes":1605,"name":"edwards"}],
"total":119788,"precincts":
{"total":513,"reporting":453},
"name":"Jefferson"},
"Crittenden":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Crittenden"},
"Butler":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Butler"},
"Breathitt":
{"votes":[
{"votes":1612,"name":"clinton"},
{"votes":149,"name":"obama"},
{"votes":39,"name":"edwards"},
{"votes":36,"name":"uncommitted-d"}],
"total":1836,"precincts":
{"total":21,"reporting":10},
"name":"Breathitt"},
"Kenton":
{"votes":[
{"votes":787,"name":"clinton"},
{"votes":690,"name":"obama"},
{"votes":48,"name":"uncommitted-d"},
{"votes":32,"name":"edwards"}],
"total":1557,"precincts":
{"total":108,"reporting":8},
"name":"Kenton"},
"Lee":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Lee"},
"Boyd":
{"votes":[
{"votes":308,"name":"clinton"},
{"votes":60,"name":"obama"},
{"votes":17,"name":"uncommitted-d"},
{"votes":4,"name":"edwards"}],
"total":389,"precincts":
{"total":47,"reporting":1},
"name":"Boyd"},
"Rockcastle":
{"votes":[
{"votes":654,"name":"clinton"},
{"votes":106,"name":"obama"},
{"votes":9,"name":"edwards"},
{"votes":6,"name":"uncommitted-d"}],
"total":775,"precincts":
{"total":14,"reporting":13},
"name":"Rockcastle"},
"McLean":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"McLean"},
"Johnson":
{"votes":[
{"votes":927,"name":"clinton"},
{"votes":109,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":22,"name":"uncommitted-d"}],
"total":1083,"precincts":
{"total":31,"reporting":13},
"name":"Johnson"},
"Hopkins":
{"votes":[],
"total":0,"precincts":
{"total":40,"reporting":0},
"name":"Hopkins"},
"Whitley":
{"votes":[],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Whitley"},
"Woodford":
{"votes":[
{"votes":79,"name":"clinton"},
{"votes":63,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":148,"precincts":
{"total":16,"reporting":1},
"name":"Woodford"},
"Green":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Green"},
"Clay":
{"votes":[
{"votes":264,"name":"clinton"},
{"votes":34,"name":"obama"},
{"votes":3,"name":"uncommitted-d"},
{"votes":3,"name":"edwards"}],
"total":304,"precincts":
{"total":20,"reporting":8},
"name":"Clay"},
"Ohio":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Ohio"},
"Spencer":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Spencer"},
"Fulton":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Fulton"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":56,"reporting":0},
"name":"Madison"},
"Taylor":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Taylor"},
"Clinton":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":106,"name":"clinton"},
{"votes":45,"name":"obama"},
{"votes":7,"name":"uncommitted-d"},
{"votes":5,"name":"edwards"}],
"total":163,"precincts":
{"total":26,"reporting":1},
"name":"Clark"},
"Owen":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Owen"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Todd"},
"Grayson":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Grayson"},
"Hart":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Hart"},
"Carlisle":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Carlisle"},
"Lyon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Lyon"},
"Boone":
{"votes":[
{"votes":3108,"name":"clinton"},
{"votes":1510,"name":"obama"},
{"votes":120,"name":"uncommitted-d"},
{"votes":101,"name":"edwards"}],
"total":4839,"precincts":
{"total":60,"reporting":18},
"name":"Boone"},
"Pendleton":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Pendleton"},
"Magoffin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Magoffin"},
"Jessamine":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Jessamine"},
"Letcher":
{"votes":[
{"votes":579,"name":"clinton"},
{"votes":47,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":12,"name":"uncommitted-d"}],
"total":657,"precincts":
{"total":32,"reporting":5},
"name":"Letcher"},
"Jackson":
{"votes":[
{"votes":318,"name":"clinton"},
{"votes":53,"name":"obama"},
{"votes":11,"name":"uncommitted-d"},
{"votes":4,"name":"edwards"}],
"total":386,"precincts":
{"total":14,"reporting":14},
"name":"Jackson"},
"Lawrence":
{"votes":[
{"votes":1870,"name":"clinton"},
{"votes":249,"name":"obama"},
{"votes":49,"name":"edwards"},
{"votes":33,"name":"uncommitted-d"}],
"total":2201,"precincts":
{"total":18,"reporting":17},
"name":"Lawrence"},
"Trigg":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Trigg"},
"McCracken":
{"votes":[],
"total":0,"precincts":
{"total":54,"reporting":0},
"name":"McCracken"},
"Fayette":
{"votes":[
{"votes":10524,"name":"obama"},
{"votes":9362,"name":"clinton"},
{"votes":368,"name":"uncommitted-d"},
{"votes":289,"name":"edwards"}],
"total":20543,"precincts":
{"total":274,"reporting":124},
"name":"Fayette"},
"Floyd":
{"votes":[
{"votes":2272,"name":"clinton"},
{"votes":135,"name":"obama"},
{"votes":52,"name":"uncommitted-d"},
{"votes":52,"name":"edwards"}],
"total":2511,"precincts":
{"total":42,"reporting":8},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":2259,"name":"clinton"},
{"votes":244,"name":"obama"},
{"votes":41,"name":"uncommitted-d"},
{"votes":38,"name":"edwards"}],
"total":2582,"precincts":
{"total":57,"reporting":15},
"name":"Pike"},
"Lincoln":
{"votes":[
{"votes":641,"name":"clinton"},
{"votes":130,"name":"obama"},
{"votes":26,"name":"uncommitted-d"},
{"votes":14,"name":"edwards"}],
"total":811,"precincts":
{"total":17,"reporting":3},
"name":"Lincoln"},
"Ballard":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Ballard"},
"Livingston":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Livingston"},
"Harlan":
{"votes":[
{"votes":1649,"name":"clinton"},
{"votes":137,"name":"obama"},
{"votes":81,"name":"uncommitted-d"},
{"votes":38,"name":"edwards"}],
"total":1905,"precincts":
{"total":35,"reporting":14},
"name":"Harlan"},
"Franklin":
{"votes":[
{"votes":387,"name":"clinton"},
{"votes":210,"name":"obama"},
{"votes":25,"name":"uncommitted-d"},
{"votes":18,"name":"edwards"}],
"total":640,"precincts":
{"total":44,"reporting":0},
"name":"Franklin"},
"Owsley":
{"votes":[
{"votes":269,"name":"clinton"},
{"votes":24,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":2,"name":"uncommitted-d"}],
"total":300,"precincts":
{"total":8,"reporting":8},
"name":"Owsley"},
"Bell":
{"votes":[
{"votes":1721,"name":"clinton"},
{"votes":224,"name":"obama"},
{"votes":39,"name":"uncommitted-d"},
{"votes":39,"name":"edwards"}],
"total":2023,"precincts":
{"total":33,"reporting":23},
"name":"Bell"},
"Marshall":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":189,"name":"clinton"},
{"votes":34,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"}],
"total":234,"precincts":
{"total":11,"reporting":1},
"name":"Carroll"},
"Bath":
{"votes":[
{"votes":38,"name":"clinton"},
{"votes":11,"name":"obama"},
{"votes":2,"name":"edwards"}],
"total":51,"precincts":
{"total":12,"reporting":1},
"name":"Bath"},
"Harrison":
{"votes":[
{"votes":704,"name":"clinton"},
{"votes":238,"name":"obama"},
{"votes":37,"name":"uncommitted-d"},
{"votes":24,"name":"edwards"}],
"total":1003,"precincts":
{"total":16,"reporting":5},
"name":"Harrison"},
"Campbell":
{"votes":[
{"votes":218,"name":"clinton"},
{"votes":135,"name":"obama"},
{"votes":11,"name":"uncommitted-d"},
{"votes":9,"name":"edwards"}],
"total":373,"precincts":
{"total":66,"reporting":1},
"name":"Campbell"},
"Laurel":
{"votes":[
{"votes":123,"name":"clinton"},
{"votes":29,"name":"obama"},
{"votes":3,"name":"uncommitted-d"},
{"votes":1,"name":"edwards"}],
"total":156,"precincts":
{"total":45,"reporting":1},
"name":"Laurel"},
"Mercer":
{"votes":[
{"votes":61,"name":"clinton"},
{"votes":35,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"}],
"total":107,"precincts":
{"total":17,"reporting":0},
"name":"Mercer"},
"Gallatin":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Gallatin"},
"Cumberland":
{"votes":[
{"votes":6,"name":"clinton"},
{"votes":1,"name":"obama"}],
"total":7,"precincts":
{"total":9,"reporting":1},
"name":"Cumberland"},
"Pulaski":
{"votes":[],
"total":0,"precincts":
{"total":57,"reporting":0},
"name":"Pulaski"},
"Rowan":
{"votes":[
{"votes":138,"name":"clinton"},
{"votes":44,"name":"obama"},
{"votes":2,"name":"uncommitted-d"},
{"votes":1,"name":"edwards"}],
"total":185,"precincts":
{"total":18,"reporting":0},
"name":"Rowan"},
"Elliott":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Elliott"},
"Estill":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Estill"},
"Christian":
{"votes":[
{"votes":133,"name":"clinton"},
{"votes":108,"name":"obama"},
{"votes":8,"name":"edwards"}],
"total":249,"precincts":
{"total":44,"reporting":1},
"name":"Christian"},
"Greenup":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Greenup"},
"Leslie":
{"votes":[
{"votes":80,"name":"clinton"},
{"votes":15,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":98,"precincts":
{"total":17,"reporting":5},
"name":"Leslie"},
"Knox":
{"votes":[
{"votes":473,"name":"clinton"},
{"votes":82,"name":"obama"},
{"votes":9,"name":"edwards"},
{"votes":6,"name":"uncommitted-d"}],
"total":570,"precincts":
{"total":30,"reporting":9},
"name":"Knox"},
"Hancock":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Hancock"},
"Hardin":
{"votes":[
{"votes":253,"name":"clinton"},
{"votes":118,"name":"obama"},
{"votes":13,"name":"uncommitted-d"},
{"votes":13,"name":"edwards"}],
"total":397,"precincts":
{"total":55,"reporting":1},
"name":"Hardin"},
"LaRue":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"LaRue"},
"Bracken":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Bracken"},
"Meade":
{"votes":[
{"votes":1552,"name":"clinton"},
{"votes":502,"name":"obama"},
{"votes":59,"name":"uncommitted-d"},
{"votes":44,"name":"edwards"}],
"total":2157,"precincts":
{"total":18,"reporting":9},
"name":"Meade"},
"Morgan":
{"votes":[
{"votes":2499,"name":"clinton"},
{"votes":199,"name":"obama"},
{"votes":57,"name":"uncommitted-d"},
{"votes":55,"name":"edwards"}],
"total":2810,"precincts":
{"total":12,"reporting":12},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Martin"},
"Garrard":
{"votes":[
{"votes":33,"name":"clinton"},
{"votes":6,"name":"obama"}],
"total":39,"precincts":
{"total":13,"reporting":1},
"name":"Garrard"},
"Edmonson":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Edmonson"},
"Simpson":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Simpson"},
"Muhlenberg":
{"votes":[
{"votes":195,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":6,"name":"edwards"}],
"total":243,"precincts":
{"total":26,"reporting":0},
"name":"Muhlenberg"},
"Carter":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Carter"},
"Knott":
{"votes":[
{"votes":968,"name":"clinton"},
{"votes":101,"name":"obama"},
{"votes":21,"name":"uncommitted-d"},
{"votes":19,"name":"edwards"}],
"total":1109,"precincts":
{"total":30,"reporting":7},
"name":"Knott"},
"Lewis":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Lewis"},
"Calloway":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Calloway"},
"Fleming":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Fleming"},
"Logan":
{"votes":[
{"votes":79,"name":"clinton"},
{"votes":23,"name":"obama"},
{"votes":6,"name":"uncommitted-d"},
{"votes":6,"name":"edwards"}],
"total":114,"precincts":
{"total":20,"reporting":1},
"name":"Logan"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Scott"},
"Monroe":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Monroe"}}})