GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":464474,"name":"obama","delegates":42},
{"votes":285440,"name":"clinton","delegates":28},
{"votes":8869,"name":"edwards"},
{"votes":3428,"name":"biden"},
{"votes":1889,"name":"richardson"},
{"votes":1723,"name":"kucinich"},
{"votes":732,"name":"gravel"},
{"votes":720,"name":"dodd"}],
"name":"Maryland","precincts":
{"total":1829,"reporting":1782},
"delegates":70,"date":"02-12"},
"state":"MD","party":"dem","total":767275,"locals":
{"Howard":
{"votes":[
{"votes":24812,"name":"obama"},
{"votes":16854,"name":"clinton"},
{"votes":367,"name":"edwards"},
{"votes":123,"name":"biden"},
{"votes":122,"name":"richardson"},
{"votes":60,"name":"kucinich"},
{"votes":32,"name":"gravel"},
{"votes":27,"name":"dodd"}],
"total":42397,"precincts":
{"total":110,"reporting":110},
"name":"Howard"},
"Washington":
{"votes":[
{"votes":6209,"name":"clinton"},
{"votes":4309,"name":"obama"},
{"votes":501,"name":"edwards"},
{"votes":100,"name":"biden"},
{"votes":63,"name":"richardson"},
{"votes":39,"name":"kucinich"},
{"votes":29,"name":"dodd"},
{"votes":24,"name":"gravel"}],
"total":11274,"precincts":
{"total":50,"reporting":50},
"name":"Washington"},
"Garrett":
{"votes":[
{"votes":927,"name":"clinton"},
{"votes":573,"name":"obama"},
{"votes":71,"name":"edwards"},
{"votes":11,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":7,"name":"dodd"},
{"votes":6,"name":"gravel"},
{"votes":4,"name":"kucinich"}],
"total":1608,"precincts":
{"total":19,"reporting":19},
"name":"Garrett"},
"Montgomery":
{"votes":[
{"votes":84287,"name":"obama"},
{"votes":66192,"name":"clinton"},
{"votes":890,"name":"edwards"},
{"votes":384,"name":"biden"},
{"votes":283,"name":"richardson"},
{"votes":279,"name":"kucinich"},
{"votes":89,"name":"gravel"},
{"votes":76,"name":"dodd"}],
"total":152480,"precincts":
{"total":245,"reporting":245},
"name":"Montgomery"},
"Kent":
{"votes":[
{"votes":1482,"name":"obama"},
{"votes":1170,"name":"clinton"},
{"votes":83,"name":"edwards"},
{"votes":51,"name":"biden"},
{"votes":10,"name":"richardson"},
{"votes":9,"name":"kucinich"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":2811,"precincts":
{"total":10,"reporting":10},
"name":"Kent"},
"Somerset":
{"votes":[
{"votes":1494,"name":"obama"},
{"votes":1204,"name":"clinton"},
{"votes":69,"name":"edwards"},
{"votes":29,"name":"biden"},
{"votes":12,"name":"richardson"},
{"votes":11,"name":"dodd"},
{"votes":10,"name":"kucinich"},
{"votes":10,"name":"gravel"}],
"total":2839,"precincts":
{"total":22,"reporting":22},
"name":"Somerset"},
"Caroline":
{"votes":[
{"votes":1359,"name":"clinton"},
{"votes":1283,"name":"obama"},
{"votes":77,"name":"edwards"},
{"votes":51,"name":"biden"},
{"votes":17,"name":"richardson"},
{"votes":11,"name":"kucinich"},
{"votes":9,"name":"dodd"},
{"votes":8,"name":"gravel"}],
"total":2815,"precincts":
{"total":8,"reporting":8},
"name":"Caroline"},
"Dorchester":
{"votes":[
{"votes":2203,"name":"obama"},
{"votes":1791,"name":"clinton"},
{"votes":86,"name":"edwards"},
{"votes":48,"name":"biden"},
{"votes":21,"name":"richardson"},
{"votes":16,"name":"kucinich"},
{"votes":10,"name":"dodd"},
{"votes":7,"name":"gravel"}],
"total":4182,"precincts":
{"total":31,"reporting":31},
"name":"Dorchester"},
"Prince George's":
{"votes":[
{"votes":94741,"name":"obama"},
{"votes":23965,"name":"clinton"},
{"votes":459,"name":"edwards"},
{"votes":229,"name":"biden"},
{"votes":221,"name":"kucinich"},
{"votes":138,"name":"richardson"},
{"votes":65,"name":"dodd"},
{"votes":65,"name":"gravel"}],
"total":119883,"precincts":
{"total":223,"reporting":181},
"name":"Prince George's"},
"Harford":
{"votes":[
{"votes":12581,"name":"obama"},
{"votes":12486,"name":"clinton"},
{"votes":617,"name":"edwards"},
{"votes":226,"name":"biden"},
{"votes":93,"name":"richardson"},
{"votes":78,"name":"kucinich"},
{"votes":38,"name":"dodd"},
{"votes":33,"name":"gravel"}],
"total":26152,"precincts":
{"total":72,"reporting":72},
"name":"Harford"},
"Anne Arundel":
{"votes":[
{"votes":32959,"name":"obama"},
{"votes":27421,"name":"clinton"},
{"votes":1082,"name":"edwards"},
{"votes":343,"name":"biden"},
{"votes":222,"name":"richardson"},
{"votes":161,"name":"kucinich"},
{"votes":74,"name":"gravel"},
{"votes":68,"name":"dodd"}],
"total":62330,"precincts":
{"total":189,"reporting":187},
"name":"Anne Arundel"},
"Frederick":
{"votes":[
{"votes":11576,"name":"obama"},
{"votes":10891,"name":"clinton"},
{"votes":412,"name":"edwards"},
{"votes":105,"name":"biden"},
{"votes":93,"name":"richardson"},
{"votes":53,"name":"kucinich"},
{"votes":33,"name":"gravel"},
{"votes":21,"name":"dodd"}],
"total":23184,"precincts":
{"total":66,"reporting":66},
"name":"Frederick"},
"Allegany":
{"votes":[
{"votes":3301,"name":"clinton"},
{"votes":1797,"name":"obama"},
{"votes":223,"name":"edwards"},
{"votes":43,"name":"biden"},
{"votes":22,"name":"kucinich"},
{"votes":21,"name":"richardson"},
{"votes":18,"name":"gravel"},
{"votes":12,"name":"dodd"}],
"total":5437,"precincts":
{"total":36,"reporting":36},
"name":"Allegany"},
"St. Mary's":
{"votes":[
{"votes":5031,"name":"obama"},
{"votes":4832,"name":"clinton"},
{"votes":225,"name":"edwards"},
{"votes":73,"name":"biden"},
{"votes":45,"name":"richardson"},
{"votes":26,"name":"kucinich"},
{"votes":23,"name":"gravel"},
{"votes":21,"name":"dodd"}],
"total":10276,"precincts":
{"total":31,"reporting":31},
"name":"St. Mary's"},
"Wicomico":
{"votes":[
{"votes":5871,"name":"obama"},
{"votes":4164,"name":"clinton"},
{"votes":195,"name":"edwards"},
{"votes":112,"name":"biden"},
{"votes":36,"name":"kucinich"},
{"votes":21,"name":"richardson"},
{"votes":17,"name":"gravel"},
{"votes":15,"name":"dodd"}],
"total":10431,"precincts":
{"total":37,"reporting":37},
"name":"Wicomico"},
"Baltimore":
{"votes":[
{"votes":68494,"name":"obama"},
{"votes":49044,"name":"clinton"},
{"votes":1743,"name":"edwards"},
{"votes":595,"name":"biden"},
{"votes":315,"name":"richardson"},
{"votes":264,"name":"kucinich"},
{"votes":136,"name":"dodd"},
{"votes":124,"name":"gravel"}],
"total":120715,"precincts":
{"total":219,"reporting":218},
"name":"Baltimore"},
"Queen Anne's":
{"votes":[
{"votes":2393,"name":"clinton"},
{"votes":2141,"name":"obama"},
{"votes":139,"name":"edwards"},
{"votes":79,"name":"biden"},
{"votes":20,"name":"richardson"},
{"votes":20,"name":"kucinich"},
{"votes":13,"name":"gravel"},
{"votes":10,"name":"dodd"}],
"total":4815,"precincts":
{"total":17,"reporting":17},
"name":"Queen Anne's"},
"Charles":
{"votes":[
{"votes":13952,"name":"obama"},
{"votes":6666,"name":"clinton"},
{"votes":218,"name":"edwards"},
{"votes":69,"name":"biden"},
{"votes":33,"name":"richardson"},
{"votes":28,"name":"kucinich"},
{"votes":13,"name":"dodd"},
{"votes":9,"name":"gravel"}],
"total":20988,"precincts":
{"total":36,"reporting":36},
"name":"Charles"},
"Carroll":
{"votes":[
{"votes":6600,"name":"clinton"},
{"votes":6256,"name":"obama"},
{"votes":347,"name":"edwards"},
{"votes":75,"name":"biden"},
{"votes":59,"name":"richardson"},
{"votes":42,"name":"kucinich"},
{"votes":25,"name":"gravel"},
{"votes":19,"name":"dodd"}],
"total":13423,"precincts":
{"total":46,"reporting":46},
"name":"Carroll"},
"Worcester":
{"votes":[
{"votes":3175,"name":"clinton"},
{"votes":3073,"name":"obama"},
{"votes":130,"name":"edwards"},
{"votes":79,"name":"biden"},
{"votes":32,"name":"richardson"},
{"votes":14,"name":"dodd"},
{"votes":14,"name":"kucinich"},
{"votes":8,"name":"gravel"}],
"total":6525,"precincts":
{"total":18,"reporting":18},
"name":"Worcester"},
"Baltimore City":
{"votes":[
{"votes":75681,"name":"obama"},
{"votes":23830,"name":"clinton"},
{"votes":483,"name":"edwards"},
{"votes":405,"name":"biden"},
{"votes":282,"name":"kucinich"},
{"votes":186,"name":"richardson"},
{"votes":88,"name":"dodd"},
{"votes":80,"name":"gravel"}],
"total":101035,"precincts":
{"total":290,"reporting":288},
"name":"Baltimore City"},
"Talbot":
{"votes":[
{"votes":2696,"name":"obama"},
{"votes":1786,"name":"clinton"},
{"votes":83,"name":"edwards"},
{"votes":26,"name":"biden"},
{"votes":15,"name":"richardson"},
{"votes":9,"name":"kucinich"},
{"votes":6,"name":"dodd"},
{"votes":5,"name":"gravel"}],
"total":4626,"precincts":
{"total":12,"reporting":12},
"name":"Talbot"},
"Calvert":
{"votes":[
{"votes":4593,"name":"obama"},
{"votes":4443,"name":"clinton"},
{"votes":193,"name":"edwards"},
{"votes":43,"name":"biden"},
{"votes":36,"name":"richardson"},
{"votes":22,"name":"kucinich"},
{"votes":11,"name":"gravel"},
{"votes":9,"name":"dodd"}],
"total":9350,"precincts":
{"total":23,"reporting":23},
"name":"Calvert"},
"Cecil":
{"votes":[
{"votes":4737,"name":"clinton"},
{"votes":2589,"name":"obama"},
{"votes":176,"name":"edwards"},
{"votes":129,"name":"biden"},
{"votes":23,"name":"richardson"},
{"votes":17,"name":"kucinich"},
{"votes":14,"name":"dodd"},
{"votes":14,"name":"gravel"}],
"total":7699,"precincts":
{"total":19,"reporting":19},
"name":"Cecil"}}})