GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":163677,"name":"mccain","delegates":"37"},
{"votes":86573,"name":"huckabee"},
{"votes":18728,"name":"romney"},
{"votes":17865,"name":"paul"},
{"votes":3821,"name":"giuliani"},
{"votes":3012,"name":"keyes"},
{"votes":2715,"name":"thompson"},
{"votes":483,"name":"hunter"},
{"votes":343,"name":"tancredo"}],
"name":"Maryland","precincts":
{"total":1829,"reporting":1782},
"delegates":"37","date":"02-12"},
"state":"MD","party":"gop","total":297217,"locals":
{"Howard":
{"votes":[
{"votes":10963,"name":"mccain"},
{"votes":5010,"name":"huckabee"},
{"votes":1322,"name":"romney"},
{"votes":1301,"name":"paul"},
{"votes":207,"name":"giuliani"},
{"votes":160,"name":"thompson"},
{"votes":138,"name":"keyes"},
{"votes":23,"name":"hunter"},
{"votes":22,"name":"tancredo"}],
"total":19146,"precincts":
{"total":110,"reporting":110},
"name":"Howard"},
"Washington":
{"votes":[
{"votes":5785,"name":"mccain"},
{"votes":5636,"name":"huckabee"},
{"votes":487,"name":"romney"},
{"votes":378,"name":"paul"},
{"votes":151,"name":"giuliani"},
{"votes":91,"name":"thompson"},
{"votes":91,"name":"keyes"},
{"votes":25,"name":"hunter"},
{"votes":6,"name":"tancredo"}],
"total":12650,"precincts":
{"total":50,"reporting":50},
"name":"Washington"},
"Garrett":
{"votes":[
{"votes":1613,"name":"mccain"},
{"votes":1549,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":98,"name":"romney"},
{"votes":46,"name":"giuliani"},
{"votes":43,"name":"keyes"},
{"votes":33,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":3522,"precincts":
{"total":19,"reporting":19},
"name":"Garrett"},
"Montgomery":
{"votes":[
{"votes":26111,"name":"mccain"},
{"votes":9101,"name":"huckabee"},
{"votes":2467,"name":"romney"},
{"votes":1776,"name":"paul"},
{"votes":454,"name":"giuliani"},
{"votes":443,"name":"keyes"},
{"votes":393,"name":"thompson"},
{"votes":71,"name":"hunter"},
{"votes":61,"name":"tancredo"}],
"total":40877,"precincts":
{"total":245,"reporting":245},
"name":"Montgomery"},
"Kent":
{"votes":[
{"votes":1144,"name":"mccain"},
{"votes":389,"name":"huckabee"},
{"votes":176,"name":"romney"},
{"votes":91,"name":"paul"},
{"votes":43,"name":"giuliani"},
{"votes":24,"name":"keyes"},
{"votes":21,"name":"thompson"},
{"votes":8,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1896,"precincts":
{"total":10,"reporting":10},
"name":"Kent"},
"Somerset":
{"votes":[
{"votes":847,"name":"mccain"},
{"votes":671,"name":"huckabee"},
{"votes":42,"name":"romney"},
{"votes":29,"name":"keyes"},
{"votes":28,"name":"paul"},
{"votes":22,"name":"giuliani"},
{"votes":14,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":1656,"precincts":
{"total":22,"reporting":22},
"name":"Somerset"},
"Caroline":
{"votes":[
{"votes":1318,"name":"mccain"},
{"votes":988,"name":"huckabee"},
{"votes":229,"name":"romney"},
{"votes":140,"name":"paul"},
{"votes":43,"name":"keyes"},
{"votes":35,"name":"giuliani"},
{"votes":31,"name":"thompson"},
{"votes":6,"name":"tancredo"},
{"votes":4,"name":"hunter"}],
"total":2794,"precincts":
{"total":8,"reporting":8},
"name":"Caroline"},
"Dorchester":
{"votes":[
{"votes":1636,"name":"mccain"},
{"votes":892,"name":"huckabee"},
{"votes":155,"name":"romney"},
{"votes":82,"name":"paul"},
{"votes":43,"name":"giuliani"},
{"votes":37,"name":"keyes"},
{"votes":19,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":4,"name":"tancredo"}],
"total":2875,"precincts":
{"total":31,"reporting":31},
"name":"Dorchester"},
"Prince George's":
{"votes":[
{"votes":4846,"name":"mccain"},
{"votes":3113,"name":"huckabee"},
{"votes":483,"name":"romney"},
{"votes":445,"name":"paul"},
{"votes":209,"name":"keyes"},
{"votes":146,"name":"thompson"},
{"votes":137,"name":"giuliani"},
{"votes":37,"name":"hunter"},
{"votes":28,"name":"tancredo"}],
"total":9444,"precincts":
{"total":223,"reporting":181},
"name":"Prince George's"},
"Harford":
{"votes":[
{"votes":10809,"name":"mccain"},
{"votes":6392,"name":"huckabee"},
{"votes":2144,"name":"paul"},
{"votes":1366,"name":"romney"},
{"votes":264,"name":"giuliani"},
{"votes":179,"name":"keyes"},
{"votes":163,"name":"thompson"},
{"votes":20,"name":"hunter"},
{"votes":14,"name":"tancredo"}],
"total":21351,"precincts":
{"total":72,"reporting":72},
"name":"Harford"},
"Anne Arundel":
{"votes":[
{"votes":23779,"name":"mccain"},
{"votes":10207,"name":"huckabee"},
{"votes":2843,"name":"romney"},
{"votes":2406,"name":"paul"},
{"votes":537,"name":"giuliani"},
{"votes":377,"name":"keyes"},
{"votes":350,"name":"thompson"},
{"votes":59,"name":"hunter"},
{"votes":39,"name":"tancredo"}],
"total":40597,"precincts":
{"total":189,"reporting":187},
"name":"Anne Arundel"},
"Frederick":
{"votes":[
{"votes":10509,"name":"mccain"},
{"votes":7297,"name":"huckabee"},
{"votes":1291,"name":"romney"},
{"votes":961,"name":"paul"},
{"votes":223,"name":"thompson"},
{"votes":223,"name":"giuliani"},
{"votes":181,"name":"keyes"},
{"votes":41,"name":"hunter"},
{"votes":20,"name":"tancredo"}],
"total":20746,"precincts":
{"total":66,"reporting":66},
"name":"Frederick"},
"Allegany":
{"votes":[
{"votes":3098,"name":"mccain"},
{"votes":2409,"name":"huckabee"},
{"votes":217,"name":"romney"},
{"votes":162,"name":"paul"},
{"votes":70,"name":"giuliani"},
{"votes":65,"name":"keyes"},
{"votes":40,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":7,"name":"tancredo"}],
"total":6075,"precincts":
{"total":36,"reporting":36},
"name":"Allegany"},
"St. Mary's":
{"votes":[
{"votes":4682,"name":"mccain"},
{"votes":2453,"name":"huckabee"},
{"votes":312,"name":"paul"},
{"votes":250,"name":"romney"},
{"votes":74,"name":"giuliani"},
{"votes":66,"name":"thompson"},
{"votes":61,"name":"keyes"},
{"votes":10,"name":"hunter"},
{"votes":7,"name":"tancredo"}],
"total":7915,"precincts":
{"total":31,"reporting":31},
"name":"St. Mary's"},
"Wicomico":
{"votes":[
{"votes":4335,"name":"mccain"},
{"votes":3184,"name":"huckabee"},
{"votes":324,"name":"romney"},
{"votes":209,"name":"paul"},
{"votes":110,"name":"giuliani"},
{"votes":85,"name":"keyes"},
{"votes":62,"name":"thompson"},
{"votes":14,"name":"hunter"},
{"votes":9,"name":"tancredo"}],
"total":8332,"precincts":
{"total":37,"reporting":37},
"name":"Wicomico"},
"Baltimore":
{"votes":[
{"votes":20194,"name":"mccain"},
{"votes":9719,"name":"huckabee"},
{"votes":3738,"name":"paul"},
{"votes":3374,"name":"romney"},
{"votes":595,"name":"giuliani"},
{"votes":355,"name":"keyes"},
{"votes":345,"name":"thompson"},
{"votes":49,"name":"hunter"},
{"votes":45,"name":"tancredo"}],
"total":38414,"precincts":
{"total":219,"reporting":218},
"name":"Baltimore"},
"Queen Anne's":
{"votes":[
{"votes":3185,"name":"mccain"},
{"votes":1327,"name":"huckabee"},
{"votes":468,"name":"romney"},
{"votes":295,"name":"paul"},
{"votes":75,"name":"giuliani"},
{"votes":48,"name":"thompson"},
{"votes":48,"name":"keyes"},
{"votes":6,"name":"tancredo"},
{"votes":4,"name":"hunter"}],
"total":5456,"precincts":
{"total":17,"reporting":17},
"name":"Queen Anne's"},
"Charles":
{"votes":[
{"votes":4651,"name":"mccain"},
{"votes":2594,"name":"huckabee"},
{"votes":278,"name":"romney"},
{"votes":278,"name":"paul"},
{"votes":103,"name":"keyes"},
{"votes":91,"name":"thompson"},
{"votes":89,"name":"giuliani"},
{"votes":11,"name":"tancredo"},
{"votes":10,"name":"hunter"}],
"total":8105,"precincts":
{"total":36,"reporting":36},
"name":"Charles"},
"Carroll":
{"votes":[
{"votes":7914,"name":"mccain"},
{"votes":5216,"name":"huckabee"},
{"votes":1438,"name":"paul"},
{"votes":1190,"name":"romney"},
{"votes":193,"name":"giuliani"},
{"votes":158,"name":"thompson"},
{"votes":124,"name":"keyes"},
{"votes":19,"name":"hunter"},
{"votes":12,"name":"tancredo"}],
"total":16264,"precincts":
{"total":46,"reporting":46},
"name":"Carroll"},
"Worcester":
{"votes":[
{"votes":3276,"name":"mccain"},
{"votes":1581,"name":"huckabee"},
{"votes":241,"name":"romney"},
{"votes":154,"name":"paul"},
{"votes":71,"name":"giuliani"},
{"votes":54,"name":"keyes"},
{"votes":43,"name":"thompson"},
{"votes":6,"name":"hunter"},
{"votes":6,"name":"tancredo"}],
"total":5432,"precincts":
{"total":18,"reporting":18},
"name":"Worcester"},
"Baltimore City":
{"votes":[
{"votes":2724,"name":"mccain"},
{"votes":1386,"name":"huckabee"},
{"votes":543,"name":"paul"},
{"votes":476,"name":"romney"},
{"votes":204,"name":"keyes"},
{"votes":155,"name":"giuliani"},
{"votes":56,"name":"thompson"},
{"votes":31,"name":"hunter"},
{"votes":15,"name":"tancredo"}],
"total":5590,"precincts":
{"total":290,"reporting":288},
"name":"Baltimore City"},
"Talbot":
{"votes":[
{"votes":3247,"name":"mccain"},
{"votes":952,"name":"huckabee"},
{"votes":401,"name":"romney"},
{"votes":211,"name":"paul"},
{"votes":50,"name":"giuliani"},
{"votes":42,"name":"thompson"},
{"votes":24,"name":"keyes"},
{"votes":6,"name":"hunter"},
{"votes":5,"name":"tancredo"}],
"total":4938,"precincts":
{"total":12,"reporting":12},
"name":"Talbot"},
"Calvert":
{"votes":[
{"votes":3829,"name":"mccain"},
{"votes":2068,"name":"huckabee"},
{"votes":258,"name":"romney"},
{"votes":228,"name":"paul"},
{"votes":82,"name":"thompson"},
{"votes":80,"name":"giuliani"},
{"votes":54,"name":"keyes"},
{"votes":12,"name":"hunter"},
{"votes":11,"name":"tancredo"}],
"total":6622,"precincts":
{"total":23,"reporting":23},
"name":"Calvert"},
"Cecil":
{"votes":[
{"votes":3182,"name":"mccain"},
{"votes":2439,"name":"huckabee"},
{"votes":415,"name":"paul"},
{"votes":292,"name":"romney"},
{"votes":97,"name":"giuliani"},
{"votes":41,"name":"keyes"},
{"votes":38,"name":"thompson"},
{"votes":11,"name":"hunter"},
{"votes":5,"name":"tancredo"}],
"total":6520,"precincts":
{"total":19,"reporting":19},
"name":"Cecil"}}})