GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":337847,"name":"romney"},
{"votes":257521,"name":"mccain","delegates":24},
{"votes":139699,"name":"huckabee","delegates":4},
{"votes":54434,"name":"paul"},
{"votes":32135,"name":"thompson"},
{"votes":24706,"name":"giuliani"},
{"votes":17971,"name":"uncommitted-r"},
{"votes":2823,"name":"hunter"},
{"votes":458,"name":"tancredo"},
{"votes":354,"name":"brownback"}],
"name":"Michigan","precincts":
{"total":5385,"reporting":5385},
"delegates":30,"date":"01-15"},
"state":"MI","party":"gop","total":867948,"locals":
{"Mackinac":
{"votes":[
{"votes":541,"name":"mccain"},
{"votes":466,"name":"romney"},
{"votes":226,"name":"huckabee"},
{"votes":50,"name":"thompson"},
{"votes":46,"name":"paul"},
{"votes":40,"name":"giuliani"},
{"votes":29,"name":"uncommitted-r"},
{"votes":2,"name":"brownback"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1402,"precincts":
{"total":14,"reporting":14},
"name":"Mackinac"},
"Jackson":
{"votes":[
{"votes":4914,"name":"romney"},
{"votes":4095,"name":"mccain"},
{"votes":2287,"name":"huckabee"},
{"votes":1029,"name":"paul"},
{"votes":577,"name":"thompson"},
{"votes":282,"name":"giuliani"},
{"votes":227,"name":"uncommitted-r"},
{"votes":39,"name":"hunter"},
{"votes":7,"name":"brownback"},
{"votes":5,"name":"tancredo"}],
"total":13462,"precincts":
{"total":76,"reporting":76},
"name":"Jackson"},
"Baraga":
{"votes":[
{"votes":249,"name":"mccain"},
{"votes":155,"name":"romney"},
{"votes":114,"name":"huckabee"},
{"votes":42,"name":"paul"},
{"votes":30,"name":"giuliani"},
{"votes":28,"name":"thompson"},
{"votes":13,"name":"uncommitted-r"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":633,"precincts":
{"total":8,"reporting":8},
"name":"Baraga"},
"Midland":
{"votes":[
{"votes":3180,"name":"romney"},
{"votes":2890,"name":"mccain"},
{"votes":1717,"name":"huckabee"},
{"votes":432,"name":"paul"},
{"votes":304,"name":"thompson"},
{"votes":262,"name":"giuliani"},
{"votes":117,"name":"uncommitted-r"},
{"votes":23,"name":"hunter"},
{"votes":3,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":8928,"precincts":
{"total":51,"reporting":51},
"name":"Midland"},
"Gogebic":
{"votes":[
{"votes":340,"name":"mccain"},
{"votes":224,"name":"romney"},
{"votes":182,"name":"huckabee"},
{"votes":55,"name":"paul"},
{"votes":38,"name":"thompson"},
{"votes":27,"name":"giuliani"},
{"votes":22,"name":"uncommitted-r"},
{"votes":5,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"brownback"}],
"total":896,"precincts":
{"total":12,"reporting":12},
"name":"Gogebic"},
"Ingham":
{"votes":[
{"votes":7405,"name":"romney"},
{"votes":6404,"name":"mccain"},
{"votes":3328,"name":"huckabee"},
{"votes":1490,"name":"paul"},
{"votes":881,"name":"thompson"},
{"votes":627,"name":"giuliani"},
{"votes":365,"name":"uncommitted-r"},
{"votes":78,"name":"hunter"},
{"votes":20,"name":"tancredo"},
{"votes":11,"name":"brownback"}],
"total":20609,"precincts":
{"total":132,"reporting":132},
"name":"Ingham"},
"Barry":
{"votes":[
{"votes":2333,"name":"mccain"},
{"votes":2253,"name":"romney"},
{"votes":1346,"name":"huckabee"},
{"votes":364,"name":"paul"},
{"votes":324,"name":"thompson"},
{"votes":150,"name":"uncommitted-r"},
{"votes":111,"name":"giuliani"},
{"votes":24,"name":"hunter"},
{"votes":3,"name":"tancredo"},
{"votes":2,"name":"brownback"}],
"total":6910,"precincts":
{"total":26,"reporting":26},
"name":"Barry"},
"Lake":
{"votes":[
{"votes":365,"name":"mccain"},
{"votes":228,"name":"romney"},
{"votes":149,"name":"huckabee"},
{"votes":49,"name":"paul"},
{"votes":48,"name":"thompson"},
{"votes":17,"name":"uncommitted-r"},
{"votes":16,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":874,"precincts":
{"total":19,"reporting":19},
"name":"Lake"},
"Calhoun":
{"votes":[
{"votes":4119,"name":"mccain"},
{"votes":3931,"name":"romney"},
{"votes":1691,"name":"huckabee"},
{"votes":732,"name":"paul"},
{"votes":411,"name":"thompson"},
{"votes":224,"name":"giuliani"},
{"votes":159,"name":"uncommitted-r"},
{"votes":46,"name":"hunter"},
{"votes":6,"name":"tancredo"},
{"votes":3,"name":"brownback"}],
"total":11322,"precincts":
{"total":61,"reporting":61},
"name":"Calhoun"},
"Grand Traverse":
{"votes":[
{"votes":4690,"name":"romney"},
{"votes":3647,"name":"mccain"},
{"votes":1359,"name":"huckabee"},
{"votes":570,"name":"paul"},
{"votes":516,"name":"thompson"},
{"votes":378,"name":"giuliani"},
{"votes":255,"name":"uncommitted-r"},
{"votes":31,"name":"hunter"},
{"votes":8,"name":"brownback"},
{"votes":8,"name":"tancredo"}],
"total":11462,"precincts":
{"total":42,"reporting":42},
"name":"Grand Traverse"},
"Gladwin":
{"votes":[
{"votes":750,"name":"romney"},
{"votes":675,"name":"mccain"},
{"votes":413,"name":"huckabee"},
{"votes":100,"name":"paul"},
{"votes":77,"name":"thompson"},
{"votes":36,"name":"uncommitted-r"},
{"votes":33,"name":"giuliani"},
{"votes":5,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"brownback"}],
"total":2092,"precincts":
{"total":21,"reporting":21},
"name":"Gladwin"},
"Huron":
{"votes":[
{"votes":1215,"name":"romney"},
{"votes":1068,"name":"mccain"},
{"votes":532,"name":"huckabee"},
{"votes":214,"name":"paul"},
{"votes":118,"name":"thompson"},
{"votes":88,"name":"uncommitted-r"},
{"votes":63,"name":"giuliani"},
{"votes":17,"name":"hunter"},
{"votes":5,"name":"tancredo"},
{"votes":2,"name":"brownback"}],
"total":3322,"precincts":
{"total":31,"reporting":31},
"name":"Huron"},
"Presque Isle":
{"votes":[
{"votes":501,"name":"romney"},
{"votes":459,"name":"mccain"},
{"votes":154,"name":"huckabee"},
{"votes":83,"name":"paul"},
{"votes":68,"name":"thompson"},
{"votes":16,"name":"giuliani"},
{"votes":15,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":1300,"precincts":
{"total":18,"reporting":18},
"name":"Presque Isle"},
"Allegan":
{"votes":[
{"votes":4071,"name":"mccain"},
{"votes":4000,"name":"romney"},
{"votes":2742,"name":"huckabee"},
{"votes":550,"name":"paul"},
{"votes":467,"name":"thompson"},
{"votes":213,"name":"uncommitted-r"},
{"votes":207,"name":"giuliani"},
{"votes":37,"name":"hunter"},
{"votes":5,"name":"tancredo"},
{"votes":2,"name":"brownback"}],
"total":12294,"precincts":
{"total":46,"reporting":46},
"name":"Allegan"},
"Keweenaw":
{"votes":[
{"votes":113,"name":"mccain"},
{"votes":84,"name":"romney"},
{"votes":27,"name":"huckabee"},
{"votes":26,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":11,"name":"giuliani"},
{"votes":4,"name":"uncommitted-r"},
{"votes":0,"name":"brownback"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":276,"precincts":
{"total":5,"reporting":5},
"name":"Keweenaw"},
"Branch":
{"votes":[
{"votes":1298,"name":"mccain"},
{"votes":1048,"name":"romney"},
{"votes":848,"name":"huckabee"},
{"votes":222,"name":"paul"},
{"votes":151,"name":"thompson"},
{"votes":77,"name":"uncommitted-r"},
{"votes":68,"name":"giuliani"},
{"votes":15,"name":"hunter"},
{"votes":4,"name":"tancredo"},
{"votes":3,"name":"brownback"}],
"total":3734,"precincts":
{"total":22,"reporting":22},
"name":"Branch"},
"Dickinson":
{"votes":[
{"votes":850,"name":"mccain"},
{"votes":548,"name":"romney"},
{"votes":503,"name":"huckabee"},
{"votes":168,"name":"paul"},
{"votes":134,"name":"thompson"},
{"votes":57,"name":"giuliani"},
{"votes":34,"name":"uncommitted-r"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":2303,"precincts":
{"total":16,"reporting":16},
"name":"Dickinson"},
"Ionia":
{"votes":[
{"votes":1767,"name":"romney"},
{"votes":1643,"name":"mccain"},
{"votes":1023,"name":"huckabee"},
{"votes":241,"name":"paul"},
{"votes":206,"name":"thompson"},
{"votes":104,"name":"uncommitted-r"},
{"votes":78,"name":"giuliani"},
{"votes":26,"name":"hunter"},
{"votes":3,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":5091,"precincts":
{"total":32,"reporting":32},
"name":"Ionia"},
"Alpena":
{"votes":[
{"votes":938,"name":"romney"},
{"votes":901,"name":"mccain"},
{"votes":378,"name":"huckabee"},
{"votes":144,"name":"paul"},
{"votes":108,"name":"thompson"},
{"votes":57,"name":"uncommitted-r"},
{"votes":45,"name":"giuliani"},
{"votes":10,"name":"hunter"},
{"votes":2,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":2583,"precincts":
{"total":18,"reporting":18},
"name":"Alpena"},
"Crawford":
{"votes":[
{"votes":568,"name":"mccain"},
{"votes":440,"name":"romney"},
{"votes":201,"name":"huckabee"},
{"votes":57,"name":"paul"},
{"votes":45,"name":"thompson"},
{"votes":32,"name":"giuliani"},
{"votes":19,"name":"uncommitted-r"},
{"votes":5,"name":"hunter"},
{"votes":0,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":1367,"precincts":
{"total":11,"reporting":11},
"name":"Crawford"},
"Benzie":
{"votes":[
{"votes":764,"name":"mccain"},
{"votes":678,"name":"romney"},
{"votes":251,"name":"huckabee"},
{"votes":112,"name":"paul"},
{"votes":83,"name":"thompson"},
{"votes":50,"name":"giuliani"},
{"votes":37,"name":"uncommitted-r"},
{"votes":5,"name":"hunter"},
{"votes":0,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":1980,"precincts":
{"total":13,"reporting":13},
"name":"Benzie"},
"Oscoda":
{"votes":[
{"votes":329,"name":"mccain"},
{"votes":313,"name":"romney"},
{"votes":162,"name":"huckabee"},
{"votes":57,"name":"paul"},
{"votes":31,"name":"thompson"},
{"votes":21,"name":"uncommitted-r"},
{"votes":7,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":924,"precincts":
{"total":7,"reporting":7},
"name":"Oscoda"},
"Mecosta":
{"votes":[
{"votes":1328,"name":"mccain"},
{"votes":1261,"name":"romney"},
{"votes":630,"name":"huckabee"},
{"votes":180,"name":"paul"},
{"votes":122,"name":"thompson"},
{"votes":74,"name":"uncommitted-r"},
{"votes":73,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"brownback"},
{"votes":2,"name":"tancredo"}],
"total":3679,"precincts":
{"total":23,"reporting":23},
"name":"Mecosta"},
"Tuscola":
{"votes":[
{"votes":1741,"name":"romney"},
{"votes":1380,"name":"mccain"},
{"votes":1186,"name":"huckabee"},
{"votes":517,"name":"paul"},
{"votes":182,"name":"thompson"},
{"votes":120,"name":"uncommitted-r"},
{"votes":69,"name":"giuliani"},
{"votes":51,"name":"hunter"},
{"votes":1,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":5248,"precincts":
{"total":32,"reporting":32},
"name":"Tuscola"},
"Alger":
{"votes":[
{"votes":308,"name":"mccain"},
{"votes":170,"name":"romney"},
{"votes":153,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":31,"name":"thompson"},
{"votes":17,"name":"uncommitted-r"},
{"votes":14,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"brownback"}],
"total":730,"precincts":
{"total":9,"reporting":9},
"name":"Alger"},
"Lenawee":
{"votes":[
{"votes":3050,"name":"romney"},
{"votes":2161,"name":"mccain"},
{"votes":1832,"name":"huckabee"},
{"votes":791,"name":"paul"},
{"votes":448,"name":"thompson"},
{"votes":185,"name":"giuliani"},
{"votes":173,"name":"uncommitted-r"},
{"votes":44,"name":"hunter"},
{"votes":4,"name":"brownback"},
{"votes":2,"name":"tancredo"}],
"total":8690,"precincts":
{"total":43,"reporting":43},
"name":"Lenawee"},
"Manistee":
{"votes":[
{"votes":870,"name":"mccain"},
{"votes":777,"name":"romney"},
{"votes":313,"name":"huckabee"},
{"votes":145,"name":"paul"},
{"votes":102,"name":"thompson"},
{"votes":41,"name":"uncommitted-r"},
{"votes":41,"name":"giuliani"},
{"votes":3,"name":"tancredo"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"brownback"}],
"total":2294,"precincts":
{"total":21,"reporting":21},
"name":"Manistee"},
"Cheboygan":
{"votes":[
{"votes":1054,"name":"romney"},
{"votes":1026,"name":"mccain"},
{"votes":409,"name":"huckabee"},
{"votes":175,"name":"paul"},
{"votes":95,"name":"thompson"},
{"votes":49,"name":"giuliani"},
{"votes":48,"name":"uncommitted-r"},
{"votes":12,"name":"hunter"},
{"votes":1,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":2870,"precincts":
{"total":22,"reporting":22},
"name":"Cheboygan"},
"Van Buren":
{"votes":[
{"votes":2557,"name":"mccain"},
{"votes":1736,"name":"romney"},
{"votes":1048,"name":"huckabee"},
{"votes":341,"name":"paul"},
{"votes":203,"name":"thompson"},
{"votes":115,"name":"uncommitted-r"},
{"votes":112,"name":"giuliani"},
{"votes":19,"name":"hunter"},
{"votes":3,"name":"brownback"},
{"votes":2,"name":"tancredo"}],
"total":6136,"precincts":
{"total":34,"reporting":34},
"name":"Van Buren"},
"Ogemaw":
{"votes":[
{"votes":648,"name":"romney"},
{"votes":565,"name":"mccain"},
{"votes":335,"name":"huckabee"},
{"votes":109,"name":"paul"},
{"votes":62,"name":"thompson"},
{"votes":28,"name":"uncommitted-r"},
{"votes":26,"name":"giuliani"},
{"votes":5,"name":"hunter"},
{"votes":3,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":1781,"precincts":
{"total":24,"reporting":24},
"name":"Ogemaw"},
"Macomb":
{"votes":[
{"votes":35020,"name":"romney"},
{"votes":19039,"name":"mccain"},
{"votes":10281,"name":"huckabee"},
{"votes":5417,"name":"paul"},
{"votes":2851,"name":"giuliani"},
{"votes":2560,"name":"thompson"},
{"votes":1727,"name":"uncommitted-r"},
{"votes":228,"name":"hunter"},
{"votes":45,"name":"tancredo"},
{"votes":22,"name":"brownback"}],
"total":77190,"precincts":
{"total":431,"reporting":431},
"name":"Macomb"},
"Roscommon":
{"votes":[
{"votes":1033,"name":"romney"},
{"votes":979,"name":"mccain"},
{"votes":365,"name":"huckabee"},
{"votes":90,"name":"paul"},
{"votes":68,"name":"giuliani"},
{"votes":63,"name":"thompson"},
{"votes":48,"name":"uncommitted-r"},
{"votes":3,"name":"brownback"},
{"votes":3,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":2655,"precincts":
{"total":14,"reporting":14},
"name":"Roscommon"},
"Lapeer":
{"votes":[
{"votes":3415,"name":"romney"},
{"votes":2313,"name":"mccain"},
{"votes":1891,"name":"huckabee"},
{"votes":1265,"name":"paul"},
{"votes":383,"name":"thompson"},
{"votes":190,"name":"giuliani"},
{"votes":164,"name":"uncommitted-r"},
{"votes":50,"name":"hunter"},
{"votes":6,"name":"brownback"},
{"votes":3,"name":"tancredo"}],
"total":9680,"precincts":
{"total":37,"reporting":37},
"name":"Lapeer"},
"Kent":
{"votes":[
{"votes":25326,"name":"romney"},
{"votes":20927,"name":"mccain"},
{"votes":12171,"name":"huckabee"},
{"votes":3011,"name":"paul"},
{"votes":2870,"name":"thompson"},
{"votes":1530,"name":"uncommitted-r"},
{"votes":1446,"name":"giuliani"},
{"votes":178,"name":"hunter"},
{"votes":21,"name":"tancredo"},
{"votes":20,"name":"brownback"}],
"total":67500,"precincts":
{"total":280,"reporting":280},
"name":"Kent"},
"Delta":
{"votes":[
{"votes":877,"name":"mccain"},
{"votes":814,"name":"romney"},
{"votes":451,"name":"huckabee"},
{"votes":128,"name":"thompson"},
{"votes":111,"name":"paul"},
{"votes":90,"name":"giuliani"},
{"votes":44,"name":"uncommitted-r"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":2522,"precincts":
{"total":23,"reporting":23},
"name":"Delta"},
"Oceana":
{"votes":[
{"votes":1047,"name":"mccain"},
{"votes":819,"name":"romney"},
{"votes":598,"name":"huckabee"},
{"votes":136,"name":"paul"},
{"votes":90,"name":"thompson"},
{"votes":51,"name":"uncommitted-r"},
{"votes":51,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":0,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":2799,"precincts":
{"total":18,"reporting":18},
"name":"Oceana"},
"Missaukee":
{"votes":[
{"votes":734,"name":"mccain"},
{"votes":592,"name":"romney"},
{"votes":475,"name":"huckabee"},
{"votes":86,"name":"paul"},
{"votes":66,"name":"thompson"},
{"votes":46,"name":"uncommitted-r"},
{"votes":32,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":2035,"precincts":
{"total":17,"reporting":17},
"name":"Missaukee"},
"Mason":
{"votes":[
{"votes":1161,"name":"mccain"},
{"votes":929,"name":"romney"},
{"votes":595,"name":"huckabee"},
{"votes":139,"name":"thompson"},
{"votes":92,"name":"paul"},
{"votes":73,"name":"giuliani"},
{"votes":40,"name":"uncommitted-r"},
{"votes":4,"name":"hunter"},
{"votes":3,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":3037,"precincts":
{"total":24,"reporting":24},
"name":"Mason"},
"Emmet":
{"votes":[
{"votes":1326,"name":"romney"},
{"votes":1223,"name":"mccain"},
{"votes":583,"name":"huckabee"},
{"votes":262,"name":"paul"},
{"votes":106,"name":"thompson"},
{"votes":64,"name":"giuliani"},
{"votes":59,"name":"uncommitted-r"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":3630,"precincts":
{"total":23,"reporting":23},
"name":"Emmet"},
"Iosco":
{"votes":[
{"votes":933,"name":"romney"},
{"votes":884,"name":"mccain"},
{"votes":333,"name":"huckabee"},
{"votes":107,"name":"paul"},
{"votes":77,"name":"thompson"},
{"votes":68,"name":"giuliani"},
{"votes":43,"name":"uncommitted-r"},
{"votes":8,"name":"hunter"},
{"votes":3,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":2456,"precincts":
{"total":16,"reporting":16},
"name":"Iosco"},
"St. Joseph":
{"votes":[
{"votes":1902,"name":"mccain"},
{"votes":1241,"name":"huckabee"},
{"votes":1224,"name":"romney"},
{"votes":224,"name":"paul"},
{"votes":192,"name":"thompson"},
{"votes":89,"name":"uncommitted-r"},
{"votes":84,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":4964,"precincts":
{"total":26,"reporting":26},
"name":"St. Joseph"},
"Kalkaska":
{"votes":[
{"votes":658,"name":"mccain"},
{"votes":602,"name":"romney"},
{"votes":266,"name":"huckabee"},
{"votes":108,"name":"paul"},
{"votes":94,"name":"thompson"},
{"votes":27,"name":"giuliani"},
{"votes":23,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":3,"name":"tancredo"},
{"votes":1,"name":"brownback"}],
"total":1785,"precincts":
{"total":13,"reporting":13},
"name":"Kalkaska"},
"Houghton":
{"votes":[
{"votes":932,"name":"mccain"},
{"votes":742,"name":"romney"},
{"votes":479,"name":"huckabee"},
{"votes":221,"name":"paul"},
{"votes":136,"name":"thompson"},
{"votes":74,"name":"giuliani"},
{"votes":17,"name":"hunter"},
{"votes":2,"name":"brownback"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"uncommitted-r"}],
"total":2604,"precincts":
{"total":31,"reporting":31},
"name":"Houghton"},
"Saginaw":
{"votes":[
{"votes":6203,"name":"romney"},
{"votes":3867,"name":"mccain"},
{"votes":2300,"name":"huckabee"},
{"votes":725,"name":"paul"},
{"votes":549,"name":"thompson"},
{"votes":383,"name":"giuliani"},
{"votes":287,"name":"uncommitted-r"},
{"votes":58,"name":"hunter"},
{"votes":4,"name":"tancredo"},
{"votes":3,"name":"brownback"}],
"total":14379,"precincts":
{"total":90,"reporting":90},
"name":"Saginaw"},
"Berrien":
{"votes":[
{"votes":5185,"name":"mccain"},
{"votes":3960,"name":"romney"},
{"votes":2640,"name":"huckabee"},
{"votes":784,"name":"paul"},
{"votes":716,"name":"thompson"},
{"votes":527,"name":"giuliani"},
{"votes":469,"name":"uncommitted-r"},
{"votes":54,"name":"hunter"},
{"votes":6,"name":"tancredo"},
{"votes":3,"name":"brownback"}],
"total":14344,"precincts":
{"total":69,"reporting":69},
"name":"Berrien"},
"Gratiot":
{"votes":[
{"votes":1108,"name":"romney"},
{"votes":1097,"name":"mccain"},
{"votes":738,"name":"huckabee"},
{"votes":108,"name":"paul"},
{"votes":100,"name":"thompson"},
{"votes":78,"name":"uncommitted-r"},
{"votes":73,"name":"giuliani"},
{"votes":8,"name":"hunter"},
{"votes":4,"name":"brownback"},
{"votes":3,"name":"tancredo"}],
"total":3317,"precincts":
{"total":23,"reporting":23},
"name":"Gratiot"},
"Muskegon":
{"votes":[
{"votes":4369,"name":"mccain"},
{"votes":3877,"name":"romney"},
{"votes":2192,"name":"huckabee"},
{"votes":536,"name":"paul"},
{"votes":406,"name":"thompson"},
{"votes":324,"name":"uncommitted-r"},
{"votes":265,"name":"giuliani"},
{"votes":31,"name":"hunter"},
{"votes":5,"name":"tancredo"},
{"votes":3,"name":"brownback"}],
"total":12008,"precincts":
{"total":73,"reporting":73},
"name":"Muskegon"},
"Iron":
{"votes":[
{"votes":430,"name":"mccain"},
{"votes":292,"name":"huckabee"},
{"votes":222,"name":"romney"},
{"votes":71,"name":"paul"},
{"votes":49,"name":"thompson"},
{"votes":25,"name":"giuliani"},
{"votes":17,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":1110,"precincts":
{"total":15,"reporting":15},
"name":"Iron"},
"Hillsdale":
{"votes":[
{"votes":1296,"name":"mccain"},
{"votes":1278,"name":"romney"},
{"votes":1010,"name":"huckabee"},
{"votes":815,"name":"paul"},
{"votes":183,"name":"thompson"},
{"votes":120,"name":"uncommitted-r"},
{"votes":93,"name":"giuliani"},
{"votes":14,"name":"hunter"},
{"votes":5,"name":"tancredo"},
{"votes":1,"name":"brownback"}],
"total":4815,"precincts":
{"total":25,"reporting":25},
"name":"Hillsdale"},
"Ottawa":
{"votes":[
{"votes":13127,"name":"romney"},
{"votes":11067,"name":"mccain"},
{"votes":8909,"name":"huckabee"},
{"votes":1413,"name":"paul"},
{"votes":1253,"name":"thompson"},
{"votes":856,"name":"uncommitted-r"},
{"votes":642,"name":"giuliani"},
{"votes":120,"name":"hunter"},
{"votes":17,"name":"tancredo"},
{"votes":15,"name":"brownback"}],
"total":37419,"precincts":
{"total":118,"reporting":118},
"name":"Ottawa"},
"Osceola":
{"votes":[
{"votes":932,"name":"mccain"},
{"votes":751,"name":"romney"},
{"votes":562,"name":"huckabee"},
{"votes":108,"name":"paul"},
{"votes":65,"name":"thompson"},
{"votes":44,"name":"uncommitted-r"},
{"votes":43,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":1,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":2514,"precincts":
{"total":18,"reporting":18},
"name":"Osceola"},
"Isabella":
{"votes":[
{"votes":1347,"name":"mccain"},
{"votes":1283,"name":"romney"},
{"votes":684,"name":"huckabee"},
{"votes":177,"name":"paul"},
{"votes":127,"name":"thompson"},
{"votes":86,"name":"giuliani"},
{"votes":56,"name":"uncommitted-r"},
{"votes":10,"name":"hunter"},
{"votes":3,"name":"brownback"},
{"votes":3,"name":"tancredo"}],
"total":3776,"precincts":
{"total":28,"reporting":28},
"name":"Isabella"},
"St. Clair":
{"votes":[
{"votes":6485,"name":"romney"},
{"votes":4229,"name":"mccain"},
{"votes":2396,"name":"huckabee"},
{"votes":1733,"name":"paul"},
{"votes":591,"name":"thompson"},
{"votes":382,"name":"giuliani"},
{"votes":381,"name":"uncommitted-r"},
{"votes":66,"name":"hunter"},
{"votes":10,"name":"tancredo"},
{"votes":3,"name":"brownback"}],
"total":16276,"precincts":
{"total":72,"reporting":72},
"name":"St. Clair"},
"Antrim":
{"votes":[
{"votes":1384,"name":"romney"},
{"votes":1100,"name":"mccain"},
{"votes":461,"name":"huckabee"},
{"votes":167,"name":"paul"},
{"votes":158,"name":"thompson"},
{"votes":66,"name":"giuliani"},
{"votes":47,"name":"uncommitted-r"},
{"votes":4,"name":"brownback"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":3388,"precincts":
{"total":16,"reporting":16},
"name":"Antrim"},
"Eaton":
{"votes":[
{"votes":3773,"name":"romney"},
{"votes":3252,"name":"mccain"},
{"votes":2112,"name":"huckabee"},
{"votes":667,"name":"paul"},
{"votes":466,"name":"thompson"},
{"votes":285,"name":"giuliani"},
{"votes":211,"name":"uncommitted-r"},
{"votes":38,"name":"hunter"},
{"votes":7,"name":"tancredo"},
{"votes":2,"name":"brownback"}],
"total":10813,"precincts":
{"total":54,"reporting":54},
"name":"Eaton"},
"Alcona":
{"votes":[
{"votes":468,"name":"mccain"},
{"votes":453,"name":"romney"},
{"votes":233,"name":"huckabee"},
{"votes":56,"name":"paul"},
{"votes":42,"name":"thompson"},
{"votes":38,"name":"uncommitted-r"},
{"votes":17,"name":"giuliani"},
{"votes":3,"name":"brownback"},
{"votes":2,"name":"tancredo"},
{"votes":0,"name":"hunter"}],
"total":1312,"precincts":
{"total":12,"reporting":12},
"name":"Alcona"},
"Montmorency":
{"votes":[
{"votes":409,"name":"mccain"},
{"votes":399,"name":"romney"},
{"votes":155,"name":"huckabee"},
{"votes":53,"name":"paul"},
{"votes":31,"name":"thompson"},
{"votes":29,"name":"uncommitted-r"},
{"votes":16,"name":"giuliani"},
{"votes":0,"name":"brownback"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1092,"precincts":
{"total":9,"reporting":9},
"name":"Montmorency"},
"Cass":
{"votes":[
{"votes":1636,"name":"mccain"},
{"votes":1104,"name":"romney"},
{"votes":1010,"name":"huckabee"},
{"votes":283,"name":"paul"},
{"votes":240,"name":"thompson"},
{"votes":168,"name":"giuliani"},
{"votes":167,"name":"uncommitted-r"},
{"votes":16,"name":"hunter"},
{"votes":3,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":4628,"precincts":
{"total":23,"reporting":23},
"name":"Cass"},
"Newaygo":
{"votes":[
{"votes":1824,"name":"mccain"},
{"votes":1582,"name":"romney"},
{"votes":1119,"name":"huckabee"},
{"votes":209,"name":"paul"},
{"votes":156,"name":"thompson"},
{"votes":82,"name":"uncommitted-r"},
{"votes":78,"name":"giuliani"},
{"votes":8,"name":"hunter"},
{"votes":3,"name":"brownback"},
{"votes":2,"name":"tancredo"}],
"total":5063,"precincts":
{"total":30,"reporting":30},
"name":"Newaygo"},
"Bay":
{"votes":[
{"votes":3835,"name":"romney"},
{"votes":2365,"name":"mccain"},
{"votes":1232,"name":"huckabee"},
{"votes":614,"name":"paul"},
{"votes":294,"name":"thompson"},
{"votes":266,"name":"giuliani"},
{"votes":248,"name":"uncommitted-r"},
{"votes":27,"name":"hunter"},
{"votes":6,"name":"tancredo"},
{"votes":4,"name":"brownback"}],
"total":8891,"precincts":
{"total":75,"reporting":75},
"name":"Bay"},
"Montcalm":
{"votes":[
{"votes":1749,"name":"mccain"},
{"votes":1515,"name":"romney"},
{"votes":986,"name":"huckabee"},
{"votes":229,"name":"thompson"},
{"votes":212,"name":"paul"},
{"votes":103,"name":"uncommitted-r"},
{"votes":62,"name":"giuliani"},
{"votes":22,"name":"hunter"},
{"votes":5,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":4884,"precincts":
{"total":31,"reporting":31},
"name":"Montcalm"},
"Charlevoix":
{"votes":[
{"votes":1121,"name":"romney"},
{"votes":1089,"name":"mccain"},
{"votes":358,"name":"huckabee"},
{"votes":146,"name":"paul"},
{"votes":121,"name":"thompson"},
{"votes":60,"name":"giuliani"},
{"votes":51,"name":"uncommitted-r"},
{"votes":13,"name":"hunter"},
{"votes":11,"name":"tancredo"},
{"votes":10,"name":"brownback"}],
"total":2980,"precincts":
{"total":20,"reporting":20},
"name":"Charlevoix"},
"Kalamazoo":
{"votes":[
{"votes":8297,"name":"mccain"},
{"votes":6857,"name":"romney"},
{"votes":3833,"name":"huckabee"},
{"votes":1139,"name":"paul"},
{"votes":813,"name":"thompson"},
{"votes":663,"name":"giuliani"},
{"votes":571,"name":"uncommitted-r"},
{"votes":60,"name":"hunter"},
{"votes":12,"name":"tancredo"},
{"votes":7,"name":"brownback"}],
"total":22252,"precincts":
{"total":115,"reporting":115},
"name":"Kalamazoo"},
"Livingston":
{"votes":[
{"votes":10521,"name":"romney"},
{"votes":5994,"name":"mccain"},
{"votes":3162,"name":"huckabee"},
{"votes":1542,"name":"paul"},
{"votes":923,"name":"thompson"},
{"votes":726,"name":"giuliani"},
{"votes":435,"name":"uncommitted-r"},
{"votes":92,"name":"hunter"},
{"votes":11,"name":"tancredo"},
{"votes":8,"name":"brownback"}],
"total":23414,"precincts":
{"total":82,"reporting":82},
"name":"Livingston"},
"Clinton":
{"votes":[
{"votes":2816,"name":"romney"},
{"votes":2318,"name":"mccain"},
{"votes":1800,"name":"huckabee"},
{"votes":357,"name":"paul"},
{"votes":334,"name":"thompson"},
{"votes":182,"name":"giuliani"},
{"votes":143,"name":"uncommitted-r"},
{"votes":33,"name":"hunter"},
{"votes":8,"name":"brownback"},
{"votes":3,"name":"tancredo"}],
"total":7994,"precincts":
{"total":32,"reporting":32},
"name":"Clinton"},
"Sanilac":
{"votes":[
{"votes":1734,"name":"romney"},
{"votes":1167,"name":"mccain"},
{"votes":754,"name":"huckabee"},
{"votes":392,"name":"paul"},
{"votes":177,"name":"thompson"},
{"votes":100,"name":"uncommitted-r"},
{"votes":87,"name":"giuliani"},
{"votes":17,"name":"hunter"},
{"votes":5,"name":"tancredo"},
{"votes":2,"name":"brownback"}],
"total":4435,"precincts":
{"total":31,"reporting":31},
"name":"Sanilac"},
"Luce":
{"votes":[
{"votes":224,"name":"mccain"},
{"votes":176,"name":"romney"},
{"votes":104,"name":"huckabee"},
{"votes":51,"name":"paul"},
{"votes":22,"name":"thompson"},
{"votes":9,"name":"uncommitted-r"},
{"votes":5,"name":"giuliani"},
{"votes":1,"name":"brownback"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":593,"precincts":
{"total":4,"reporting":4},
"name":"Luce"},
"Clare":
{"votes":[
{"votes":877,"name":"romney"},
{"votes":837,"name":"mccain"},
{"votes":487,"name":"huckabee"},
{"votes":110,"name":"thompson"},
{"votes":84,"name":"paul"},
{"votes":49,"name":"uncommitted-r"},
{"votes":31,"name":"giuliani"},
{"votes":10,"name":"hunter"},
{"votes":3,"name":"brownback"},
{"votes":0,"name":"tancredo"}],
"total":2488,"precincts":
{"total":26,"reporting":26},
"name":"Clare"},
"Schoolcraft":
{"votes":[
{"votes":210,"name":"mccain"},
{"votes":189,"name":"romney"},
{"votes":80,"name":"huckabee"},
{"votes":34,"name":"thompson"},
{"votes":29,"name":"paul"},
{"votes":23,"name":"giuliani"},
{"votes":13,"name":"uncommitted-r"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":581,"precincts":
{"total":10,"reporting":10},
"name":"Schoolcraft"},
"Arenac":
{"votes":[
{"votes":444,"name":"romney"},
{"votes":430,"name":"mccain"},
{"votes":205,"name":"huckabee"},
{"votes":67,"name":"paul"},
{"votes":42,"name":"giuliani"},
{"votes":41,"name":"thompson"},
{"votes":15,"name":"uncommitted-r"},
{"votes":7,"name":"hunter"},
{"votes":4,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":1255,"precincts":
{"total":15,"reporting":15},
"name":"Arenac"},
"Chippewa":
{"votes":[
{"votes":1082,"name":"romney"},
{"votes":1027,"name":"mccain"},
{"votes":486,"name":"huckabee"},
{"votes":175,"name":"thompson"},
{"votes":132,"name":"paul"},
{"votes":71,"name":"giuliani"},
{"votes":52,"name":"uncommitted-r"},
{"votes":8,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":0,"name":"brownback"}],
"total":3035,"precincts":
{"total":20,"reporting":20},
"name":"Chippewa"},
"Leelanau":
{"votes":[
{"votes":1479,"name":"romney"},
{"votes":1152,"name":"mccain"},
{"votes":279,"name":"huckabee"},
{"votes":177,"name":"paul"},
{"votes":115,"name":"thompson"},
{"votes":111,"name":"giuliani"},
{"votes":62,"name":"uncommitted-r"},
{"votes":4,"name":"tancredo"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"brownback"}],
"total":3381,"precincts":
{"total":13,"reporting":13},
"name":"Leelanau"},
"Genesee":
{"votes":[
{"votes":8749,"name":"romney"},
{"votes":7021,"name":"mccain"},
{"votes":5477,"name":"huckabee"},
{"votes":2380,"name":"paul"},
{"votes":894,"name":"thompson"},
{"votes":555,"name":"giuliani"},
{"votes":545,"name":"uncommitted-r"},
{"votes":110,"name":"hunter"},
{"votes":17,"name":"brownback"},
{"votes":12,"name":"tancredo"}],
"total":25760,"precincts":
{"total":233,"reporting":233},
"name":"Genesee"},
"Wayne":
{"votes":[
{"votes":43939,"name":"romney"},
{"votes":25809,"name":"mccain"},
{"votes":13787,"name":"huckabee"},
{"votes":6687,"name":"paul"},
{"votes":3393,"name":"thompson"},
{"votes":3357,"name":"giuliani"},
{"votes":2134,"name":"uncommitted-r"},
{"votes":344,"name":"hunter"},
{"votes":58,"name":"tancredo"},
{"votes":44,"name":"brownback"}],
"total":99552,"precincts":
{"total":1233,"reporting":1233},
"name":"Wayne"},
"Wexford":
{"votes":[
{"votes":1227,"name":"mccain"},
{"votes":1031,"name":"romney"},
{"votes":575,"name":"huckabee"},
{"votes":167,"name":"paul"},
{"votes":134,"name":"thompson"},
{"votes":50,"name":"giuliani"},
{"votes":11,"name":"hunter"},
{"votes":4,"name":"tancredo"},
{"votes":1,"name":"brownback"},
{"votes":0,"name":"uncommitted-r"}],
"total":3200,"precincts":
{"total":20,"reporting":20},
"name":"Wexford"},
"Shiawassee":
{"votes":[
{"votes":2238,"name":"romney"},
{"votes":2101,"name":"mccain"},
{"votes":1802,"name":"huckabee"},
{"votes":553,"name":"paul"},
{"votes":250,"name":"thompson"},
{"votes":207,"name":"uncommitted-r"},
{"votes":160,"name":"giuliani"},
{"votes":22,"name":"hunter"},
{"votes":4,"name":"tancredo"},
{"votes":3,"name":"brownback"}],
"total":7340,"precincts":
{"total":34,"reporting":34},
"name":"Shiawassee"},
"Washtenaw":
{"votes":[
{"votes":10223,"name":"romney"},
{"votes":9318,"name":"mccain"},
{"votes":3572,"name":"huckabee"},
{"votes":2262,"name":"paul"},
{"votes":1059,"name":"thompson"},
{"votes":835,"name":"giuliani"},
{"votes":405,"name":"uncommitted-r"},
{"votes":79,"name":"hunter"},
{"votes":18,"name":"tancredo"},
{"votes":14,"name":"brownback"}],
"total":27785,"precincts":
{"total":154,"reporting":154},
"name":"Washtenaw"},
"Otsego":
{"votes":[
{"votes":1017,"name":"romney"},
{"votes":966,"name":"mccain"},
{"votes":387,"name":"huckabee"},
{"votes":150,"name":"paul"},
{"votes":109,"name":"thompson"},
{"votes":54,"name":"giuliani"},
{"votes":0,"name":"brownback"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"tancredo"}],
"total":2683,"precincts":
{"total":15,"reporting":15},
"name":"Otsego"},
"Ontonagon":
{"votes":[
{"votes":189,"name":"mccain"},
{"votes":127,"name":"romney"},
{"votes":124,"name":"huckabee"},
{"votes":63,"name":"paul"},
{"votes":24,"name":"thompson"},
{"votes":19,"name":"uncommitted-r"},
{"votes":18,"name":"giuliani"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"brownback"}],
"total":567,"precincts":
{"total":14,"reporting":14},
"name":"Ontonagon"},
"Marquette":
{"votes":[
{"votes":1627,"name":"mccain"},
{"votes":1080,"name":"romney"},
{"votes":666,"name":"huckabee"},
{"votes":239,"name":"paul"},
{"votes":169,"name":"thompson"},
{"votes":65,"name":"uncommitted-r"},
{"votes":61,"name":"giuliani"},
{"votes":19,"name":"hunter"},
{"votes":5,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":3932,"precincts":
{"total":35,"reporting":35},
"name":"Marquette"},
"Menominee":
{"votes":[
{"votes":653,"name":"mccain"},
{"votes":400,"name":"romney"},
{"votes":357,"name":"huckabee"},
{"votes":94,"name":"paul"},
{"votes":93,"name":"thompson"},
{"votes":49,"name":"giuliani"},
{"votes":42,"name":"uncommitted-r"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"brownback"},
{"votes":1,"name":"tancredo"}],
"total":1694,"precincts":
{"total":20,"reporting":20},
"name":"Menominee"},
"Oakland":
{"votes":[
{"votes":62118,"name":"romney"},
{"votes":35639,"name":"mccain"},
{"votes":14869,"name":"huckabee"},
{"votes":7926,"name":"paul"},
{"votes":5356,"name":"giuliani"},
{"votes":4003,"name":"thompson"},
{"votes":2622,"name":"uncommitted-r"},
{"votes":407,"name":"hunter"},
{"votes":61,"name":"tancredo"},
{"votes":34,"name":"brownback"}],
"total":133035,"precincts":
{"total":570,"reporting":570},
"name":"Oakland"},
"Monroe":
{"votes":[
{"votes":4350,"name":"romney"},
{"votes":3011,"name":"mccain"},
{"votes":2236,"name":"huckabee"},
{"votes":863,"name":"paul"},
{"votes":662,"name":"thompson"},
{"votes":382,"name":"giuliani"},
{"votes":336,"name":"uncommitted-r"},
{"votes":55,"name":"hunter"},
{"votes":13,"name":"brownback"},
{"votes":6,"name":"tancredo"}],
"total":11914,"precincts":
{"total":66,"reporting":66},
"name":"Monroe"}}})