GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":194304,"name":"mccain","delegates":58},
{"votes":185627,"name":"huckabee"},
{"votes":172564,"name":"romney"},
{"votes":26445,"name":"paul"},
{"votes":3595,"name":"giuliani"},
{"votes":3106,"name":"thompson"},
{"votes":2083,"name":"uncommitted-r"},
{"votes":894,"name":"keyes"},
{"votes":306,"name":"hunter"},
{"votes":108,"name":"tancredo"}],
"name":"Missouri","precincts":
{"total":3371,"reporting":3371},
"delegates":58,"date":"02-05"},
"state":"MO","party":"gop","total":589032,"locals":
{"Daviess":
{"votes":[
{"votes":236,"name":"mccain"},
{"votes":220,"name":"romney"},
{"votes":216,"name":"huckabee"},
{"votes":95,"name":"paul"},
{"votes":9,"name":"giuliani"},
{"votes":4,"name":"uncommitted-r"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":786,"precincts":
{"total":8,"reporting":8},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":321,"name":"huckabee"},
{"votes":206,"name":"mccain"},
{"votes":140,"name":"romney"},
{"votes":18,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":6,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":700,"precincts":
{"total":8,"reporting":8},
"name":"Shelby"},
"Barry":
{"votes":[
{"votes":2396,"name":"huckabee"},
{"votes":1365,"name":"mccain"},
{"votes":739,"name":"romney"},
{"votes":266,"name":"paul"},
{"votes":19,"name":"uncommitted-r"},
{"votes":14,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":6,"name":"keyes"},
{"votes":4,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":4821,"precincts":
{"total":19,"reporting":19},
"name":"Barry"},
"Mississippi":
{"votes":[
{"votes":455,"name":"huckabee"},
{"votes":362,"name":"mccain"},
{"votes":213,"name":"romney"},
{"votes":15,"name":"paul"},
{"votes":7,"name":"uncommitted-r"},
{"votes":6,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"giuliani"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":1064,"precincts":
{"total":9,"reporting":9},
"name":"Mississippi"},
"Montgomery":
{"votes":[
{"votes":537,"name":"mccain"},
{"votes":456,"name":"huckabee"},
{"votes":304,"name":"romney"},
{"votes":65,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":1384,"precincts":
{"total":11,"reporting":11},
"name":"Montgomery"},
"Dunklin":
{"votes":[
{"votes":1309,"name":"huckabee"},
{"votes":480,"name":"mccain"},
{"votes":381,"name":"romney"},
{"votes":36,"name":"paul"},
{"votes":12,"name":"giuliani"},
{"votes":9,"name":"uncommitted-r"},
{"votes":7,"name":"thompson"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2236,"precincts":
{"total":22,"reporting":22},
"name":"Dunklin"},
"Wayne":
{"votes":[
{"votes":740,"name":"huckabee"},
{"votes":499,"name":"mccain"},
{"votes":323,"name":"romney"},
{"votes":46,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":8,"name":"giuliani"},
{"votes":6,"name":"uncommitted-r"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":1635,"precincts":
{"total":18,"reporting":18},
"name":"Wayne"},
"Cooper":
{"votes":[
{"votes":639,"name":"mccain"},
{"votes":545,"name":"romney"},
{"votes":503,"name":"huckabee"},
{"votes":70,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":7,"name":"thompson"},
{"votes":5,"name":"uncommitted-r"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":1783,"precincts":
{"total":11,"reporting":11},
"name":"Cooper"},
"LaClede":
{"votes":[
{"votes":2791,"name":"huckabee"},
{"votes":1656,"name":"mccain"},
{"votes":807,"name":"romney"},
{"votes":142,"name":"paul"},
{"votes":29,"name":"uncommitted-r"},
{"votes":23,"name":"giuliani"},
{"votes":21,"name":"thompson"},
{"votes":11,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":5480,"precincts":
{"total":21,"reporting":21},
"name":"LaClede"},
"Worth":
{"votes":[
{"votes":84,"name":"huckabee"},
{"votes":77,"name":"romney"},
{"votes":73,"name":"mccain"},
{"votes":10,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":254,"precincts":
{"total":8,"reporting":8},
"name":"Worth"},
"Texas":
{"votes":[
{"votes":1727,"name":"huckabee"},
{"votes":954,"name":"mccain"},
{"votes":480,"name":"romney"},
{"votes":234,"name":"paul"},
{"votes":16,"name":"thompson"},
{"votes":13,"name":"giuliani"},
{"votes":11,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":3441,"precincts":
{"total":11,"reporting":11},
"name":"Texas"},
"Hickory":
{"votes":[
{"votes":548,"name":"huckabee"},
{"votes":453,"name":"mccain"},
{"votes":282,"name":"romney"},
{"votes":64,"name":"paul"},
{"votes":7,"name":"thompson"},
{"votes":6,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1363,"precincts":
{"total":11,"reporting":11},
"name":"Hickory"},
"Adair":
{"votes":[
{"votes":735,"name":"huckabee"},
{"votes":558,"name":"mccain"},
{"votes":451,"name":"romney"},
{"votes":158,"name":"paul"},
{"votes":8,"name":"uncommitted-r"},
{"votes":7,"name":"thompson"},
{"votes":5,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":1924,"precincts":
{"total":11,"reporting":11},
"name":"Adair"},
"Henry":
{"votes":[
{"votes":760,"name":"mccain"},
{"votes":708,"name":"huckabee"},
{"votes":480,"name":"romney"},
{"votes":71,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":9,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":2055,"precincts":
{"total":20,"reporting":20},
"name":"Henry"},
"Webster":
{"votes":[
{"votes":2576,"name":"huckabee"},
{"votes":1341,"name":"mccain"},
{"votes":897,"name":"romney"},
{"votes":168,"name":"paul"},
{"votes":24,"name":"thompson"},
{"votes":18,"name":"giuliani"},
{"votes":13,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":5045,"precincts":
{"total":14,"reporting":14},
"name":"Webster"},
"New Madrid":
{"votes":[
{"votes":656,"name":"huckabee"},
{"votes":386,"name":"mccain"},
{"votes":250,"name":"romney"},
{"votes":43,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":1346,"precincts":
{"total":24,"reporting":24},
"name":"New Madrid"},
"Knox":
{"votes":[
{"votes":142,"name":"huckabee"},
{"votes":101,"name":"mccain"},
{"votes":72,"name":"romney"},
{"votes":16,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"uncommitted-r"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":343,"precincts":
{"total":7,"reporting":7},
"name":"Knox"},
"Sullivan":
{"votes":[
{"votes":209,"name":"huckabee"},
{"votes":197,"name":"mccain"},
{"votes":130,"name":"romney"},
{"votes":60,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"tancredo"}],
"total":607,"precincts":
{"total":14,"reporting":14},
"name":"Sullivan"},
"Buchanan":
{"votes":[
{"votes":2216,"name":"romney"},
{"votes":2194,"name":"mccain"},
{"votes":1825,"name":"huckabee"},
{"votes":521,"name":"paul"},
{"votes":57,"name":"uncommitted-r"},
{"votes":57,"name":"giuliani"},
{"votes":48,"name":"thompson"},
{"votes":9,"name":"keyes"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":6933,"precincts":
{"total":36,"reporting":36},
"name":"Buchanan"},
"Newton":
{"votes":[
{"votes":3476,"name":"huckabee"},
{"votes":1983,"name":"mccain"},
{"votes":1744,"name":"romney"},
{"votes":350,"name":"paul"},
{"votes":33,"name":"giuliani"},
{"votes":27,"name":"thompson"},
{"votes":15,"name":"uncommitted-r"},
{"votes":9,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":7640,"precincts":
{"total":25,"reporting":25},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":622,"name":"huckabee"},
{"votes":616,"name":"mccain"},
{"votes":297,"name":"romney"},
{"votes":50,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":7,"name":"giuliani"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1604,"precincts":
{"total":19,"reporting":19},
"name":"Washington"},
"Moniteau":
{"votes":[
{"votes":699,"name":"huckabee"},
{"votes":512,"name":"mccain"},
{"votes":472,"name":"romney"},
{"votes":99,"name":"paul"},
{"votes":10,"name":"giuliani"},
{"votes":9,"name":"thompson"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"keyes"}],
"total":1804,"precincts":
{"total":13,"reporting":13},
"name":"Moniteau"},
"St. Louis County":
{"votes":[
{"votes":39214,"name":"mccain"},
{"votes":34841,"name":"romney"},
{"votes":16175,"name":"huckabee"},
{"votes":3337,"name":"paul"},
{"votes":721,"name":"giuliani"},
{"votes":573,"name":"thompson"},
{"votes":301,"name":"uncommitted-r"},
{"votes":177,"name":"keyes"},
{"votes":45,"name":"hunter"},
{"votes":21,"name":"tancredo"}],
"total":95405,"precincts":
{"total":534,"reporting":534},
"name":"St. Louis County"},
"Camden":
{"votes":[
{"votes":2194,"name":"mccain"},
{"votes":2130,"name":"huckabee"},
{"votes":1842,"name":"romney"},
{"votes":193,"name":"paul"},
{"votes":40,"name":"giuliani"},
{"votes":37,"name":"thompson"},
{"votes":20,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"hunter"}],
"total":6464,"precincts":
{"total":29,"reporting":29},
"name":"Camden"},
"Jasper":
{"votes":[
{"votes":5266,"name":"huckabee"},
{"votes":3246,"name":"romney"},
{"votes":3220,"name":"mccain"},
{"votes":527,"name":"paul"},
{"votes":71,"name":"giuliani"},
{"votes":68,"name":"thompson"},
{"votes":48,"name":"uncommitted-r"},
{"votes":11,"name":"keyes"},
{"votes":6,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":12465,"precincts":
{"total":47,"reporting":47},
"name":"Jasper"},
"Polk":
{"votes":[
{"votes":2317,"name":"huckabee"},
{"votes":1141,"name":"mccain"},
{"votes":842,"name":"romney"},
{"votes":154,"name":"paul"},
{"votes":18,"name":"giuliani"},
{"votes":14,"name":"thompson"},
{"votes":9,"name":"keyes"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"uncommitted-r"},
{"votes":0,"name":"tancredo"}],
"total":4500,"precincts":
{"total":23,"reporting":23},
"name":"Polk"},
"Gasconade":
{"votes":[
{"votes":793,"name":"mccain"},
{"votes":536,"name":"romney"},
{"votes":514,"name":"huckabee"},
{"votes":75,"name":"paul"},
{"votes":18,"name":"uncommitted-r"},
{"votes":18,"name":"thompson"},
{"votes":9,"name":"giuliani"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":1969,"precincts":
{"total":18,"reporting":18},
"name":"Gasconade"},
"Warren":
{"votes":[
{"votes":1192,"name":"mccain"},
{"votes":1139,"name":"romney"},
{"votes":988,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":31,"name":"thompson"},
{"votes":22,"name":"giuliani"},
{"votes":12,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":3518,"precincts":
{"total":23,"reporting":23},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":973,"name":"mccain"},
{"votes":575,"name":"huckabee"},
{"votes":542,"name":"romney"},
{"votes":96,"name":"paul"},
{"votes":22,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":6,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2231,"precincts":
{"total":19,"reporting":19},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":17431,"name":"romney"},
{"votes":17146,"name":"mccain"},
{"votes":11647,"name":"huckabee"},
{"votes":2979,"name":"paul"},
{"votes":357,"name":"giuliani"},
{"votes":276,"name":"thompson"},
{"votes":203,"name":"uncommitted-r"},
{"votes":105,"name":"keyes"},
{"votes":29,"name":"hunter"},
{"votes":25,"name":"tancredo"}],
"total":50198,"precincts":
{"total":389,"reporting":389},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":328,"name":"huckabee"},
{"votes":319,"name":"romney"},
{"votes":283,"name":"mccain"},
{"votes":52,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":995,"precincts":
{"total":10,"reporting":10},
"name":"Howard"},
"Caldwell":
{"votes":[
{"votes":365,"name":"mccain"},
{"votes":306,"name":"huckabee"},
{"votes":242,"name":"romney"},
{"votes":77,"name":"paul"},
{"votes":9,"name":"thompson"},
{"votes":8,"name":"giuliani"},
{"votes":5,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1013,"precincts":
{"total":10,"reporting":10},
"name":"Caldwell"},
"Chariton":
{"votes":[
{"votes":260,"name":"huckabee"},
{"votes":244,"name":"mccain"},
{"votes":167,"name":"romney"},
{"votes":28,"name":"paul"},
{"votes":5,"name":"giuliani"},
{"votes":2,"name":"tancredo"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"keyes"}],
"total":709,"precincts":
{"total":13,"reporting":13},
"name":"Chariton"},
"Wright":
{"votes":[
{"votes":1878,"name":"huckabee"},
{"votes":746,"name":"mccain"},
{"votes":298,"name":"romney"},
{"votes":178,"name":"paul"},
{"votes":15,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":10,"name":"keyes"},
{"votes":6,"name":"uncommitted-r"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":3143,"precincts":
{"total":10,"reporting":10},
"name":"Wright"},
"Jefferson":
{"votes":[
{"votes":6354,"name":"mccain"},
{"votes":5772,"name":"romney"},
{"votes":5724,"name":"huckabee"},
{"votes":747,"name":"paul"},
{"votes":133,"name":"thompson"},
{"votes":115,"name":"giuliani"},
{"votes":61,"name":"uncommitted-r"},
{"votes":29,"name":"keyes"},
{"votes":9,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":18946,"precincts":
{"total":74,"reporting":74},
"name":"Jefferson"},
"Taney":
{"votes":[
{"votes":3846,"name":"huckabee"},
{"votes":1783,"name":"mccain"},
{"votes":976,"name":"romney"},
{"votes":195,"name":"paul"},
{"votes":29,"name":"giuliani"},
{"votes":28,"name":"thompson"},
{"votes":19,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":6883,"precincts":
{"total":24,"reporting":24},
"name":"Taney"},
"Butler":
{"votes":[
{"votes":2215,"name":"huckabee"},
{"votes":1264,"name":"mccain"},
{"votes":1141,"name":"romney"},
{"votes":137,"name":"paul"},
{"votes":31,"name":"thompson"},
{"votes":15,"name":"uncommitted-r"},
{"votes":15,"name":"giuliani"},
{"votes":3,"name":"tancredo"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"hunter"}],
"total":4824,"precincts":
{"total":26,"reporting":26},
"name":"Butler"},
"Putnam":
{"votes":[
{"votes":254,"name":"huckabee"},
{"votes":164,"name":"mccain"},
{"votes":128,"name":"romney"},
{"votes":28,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":584,"precincts":
{"total":9,"reporting":9},
"name":"Putnam"},
"St. Charles":
{"votes":[
{"votes":15868,"name":"romney"},
{"votes":14705,"name":"mccain"},
{"votes":9185,"name":"huckabee"},
{"votes":1612,"name":"paul"},
{"votes":258,"name":"giuliani"},
{"votes":213,"name":"thompson"},
{"votes":137,"name":"uncommitted-r"},
{"votes":63,"name":"keyes"},
{"votes":17,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":42061,"precincts":
{"total":121,"reporting":121},
"name":"St. Charles"},
"Holt":
{"votes":[
{"votes":201,"name":"romney"},
{"votes":194,"name":"huckabee"},
{"votes":190,"name":"mccain"},
{"votes":34,"name":"paul"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":636,"precincts":
{"total":7,"reporting":7},
"name":"Holt"},
"Oregon":
{"votes":[
{"votes":696,"name":"huckabee"},
{"votes":242,"name":"mccain"},
{"votes":134,"name":"romney"},
{"votes":101,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":1181,"precincts":
{"total":12,"reporting":12},
"name":"Oregon"},
"Stoddard":
{"votes":[
{"votes":1589,"name":"huckabee"},
{"votes":779,"name":"mccain"},
{"votes":651,"name":"romney"},
{"votes":91,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":9,"name":"thompson"},
{"votes":8,"name":"giuliani"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":3139,"precincts":
{"total":21,"reporting":21},
"name":"Stoddard"},
"Linn":
{"votes":[
{"votes":451,"name":"huckabee"},
{"votes":361,"name":"mccain"},
{"votes":203,"name":"romney"},
{"votes":66,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1094,"precincts":
{"total":13,"reporting":13},
"name":"Linn"},
"Callaway":
{"votes":[
{"votes":1517,"name":"huckabee"},
{"votes":1457,"name":"romney"},
{"votes":1203,"name":"mccain"},
{"votes":196,"name":"paul"},
{"votes":30,"name":"giuliani"},
{"votes":28,"name":"thompson"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":4442,"precincts":
{"total":27,"reporting":27},
"name":"Callaway"},
"Pettis":
{"votes":[
{"votes":1372,"name":"mccain"},
{"votes":1226,"name":"romney"},
{"votes":994,"name":"huckabee"},
{"votes":110,"name":"paul"},
{"votes":20,"name":"giuliani"},
{"votes":19,"name":"uncommitted-r"},
{"votes":15,"name":"thompson"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":3761,"precincts":
{"total":26,"reporting":26},
"name":"Pettis"},
"Marion":
{"votes":[
{"votes":904,"name":"huckabee"},
{"votes":891,"name":"romney"},
{"votes":714,"name":"mccain"},
{"votes":114,"name":"paul"},
{"votes":19,"name":"thompson"},
{"votes":15,"name":"giuliani"},
{"votes":9,"name":"uncommitted-r"},
{"votes":6,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2673,"precincts":
{"total":18,"reporting":18},
"name":"Marion"},
"Randolph":
{"votes":[
{"votes":824,"name":"huckabee"},
{"votes":632,"name":"romney"},
{"votes":623,"name":"mccain"},
{"votes":95,"name":"paul"},
{"votes":13,"name":"giuliani"},
{"votes":11,"name":"thompson"},
{"votes":8,"name":"uncommitted-r"},
{"votes":6,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2213,"precincts":
{"total":15,"reporting":15},
"name":"Randolph"},
"Stone":
{"votes":[
{"votes":2528,"name":"huckabee"},
{"votes":1787,"name":"mccain"},
{"votes":1056,"name":"romney"},
{"votes":154,"name":"paul"},
{"votes":29,"name":"uncommitted-r"},
{"votes":28,"name":"giuliani"},
{"votes":26,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":5613,"precincts":
{"total":22,"reporting":22},
"name":"Stone"},
"Johnson":
{"votes":[
{"votes":1558,"name":"mccain"},
{"votes":1302,"name":"huckabee"},
{"votes":1149,"name":"romney"},
{"votes":204,"name":"paul"},
{"votes":31,"name":"giuliani"},
{"votes":25,"name":"thompson"},
{"votes":15,"name":"uncommitted-r"},
{"votes":8,"name":"keyes"},
{"votes":5,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":4297,"precincts":
{"total":11,"reporting":11},
"name":"Johnson"},
"St. Louis City":
{"votes":[
{"votes":4363,"name":"mccain"},
{"votes":2846,"name":"romney"},
{"votes":1605,"name":"huckabee"},
{"votes":681,"name":"paul"},
{"votes":95,"name":"giuliani"},
{"votes":84,"name":"uncommitted-r"},
{"votes":68,"name":"thompson"},
{"votes":21,"name":"keyes"},
{"votes":6,"name":"hunter"},
{"votes":6,"name":"tancredo"}],
"total":9775,"precincts":
{"total":204,"reporting":204},
"name":"St. Louis City"},
"Barton":
{"votes":[
{"votes":1188,"name":"huckabee"},
{"votes":525,"name":"mccain"},
{"votes":344,"name":"romney"},
{"votes":45,"name":"paul"},
{"votes":12,"name":"giuliani"},
{"votes":6,"name":"uncommitted-r"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2131,"precincts":
{"total":17,"reporting":17},
"name":"Barton"},
"Maries":
{"votes":[
{"votes":415,"name":"huckabee"},
{"votes":343,"name":"mccain"},
{"votes":321,"name":"romney"},
{"votes":59,"name":"paul"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"keyes"}],
"total":1155,"precincts":
{"total":10,"reporting":10},
"name":"Maries"},
"Greene":
{"votes":[
{"votes":15644,"name":"huckabee"},
{"votes":9979,"name":"mccain"},
{"votes":9271,"name":"romney"},
{"votes":1552,"name":"paul"},
{"votes":134,"name":"giuliani"},
{"votes":107,"name":"thompson"},
{"votes":73,"name":"uncommitted-r"},
{"votes":46,"name":"keyes"},
{"votes":17,"name":"hunter"},
{"votes":5,"name":"tancredo"}],
"total":36828,"precincts":
{"total":87,"reporting":87},
"name":"Greene"},
"Ripley":
{"votes":[
{"votes":750,"name":"huckabee"},
{"votes":329,"name":"mccain"},
{"votes":238,"name":"romney"},
{"votes":52,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":5,"name":"giuliani"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":1391,"precincts":
{"total":14,"reporting":14},
"name":"Ripley"},
"Clay":
{"votes":[
{"votes":6421,"name":"romney"},
{"votes":6003,"name":"mccain"},
{"votes":4486,"name":"huckabee"},
{"votes":1135,"name":"paul"},
{"votes":102,"name":"giuliani"},
{"votes":84,"name":"thompson"},
{"votes":38,"name":"keyes"},
{"votes":35,"name":"uncommitted-r"},
{"votes":12,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":18316,"precincts":
{"total":75,"reporting":75},
"name":"Clay"},
"Macon":
{"votes":[
{"votes":646,"name":"huckabee"},
{"votes":441,"name":"mccain"},
{"votes":390,"name":"romney"},
{"votes":43,"name":"paul"},
{"votes":14,"name":"thompson"},
{"votes":9,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":1550,"precincts":
{"total":15,"reporting":15},
"name":"Macon"},
"Madison":
{"votes":[
{"votes":560,"name":"huckabee"},
{"votes":452,"name":"mccain"},
{"votes":185,"name":"romney"},
{"votes":51,"name":"paul"},
{"votes":11,"name":"uncommitted-r"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":1273,"precincts":
{"total":8,"reporting":8},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":611,"name":"mccain"},
{"votes":606,"name":"romney"},
{"votes":495,"name":"huckabee"},
{"votes":171,"name":"paul"},
{"votes":12,"name":"giuliani"},
{"votes":9,"name":"thompson"},
{"votes":7,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1914,"precincts":
{"total":9,"reporting":9},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":283,"name":"huckabee"},
{"votes":195,"name":"mccain"},
{"votes":121,"name":"romney"},
{"votes":28,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":642,"precincts":
{"total":10,"reporting":10},
"name":"Clark"},
"McDonald":
{"votes":[
{"votes":1285,"name":"huckabee"},
{"votes":674,"name":"mccain"},
{"votes":389,"name":"romney"},
{"votes":233,"name":"paul"},
{"votes":26,"name":"uncommitted-r"},
{"votes":14,"name":"giuliani"},
{"votes":11,"name":"thompson"},
{"votes":5,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2637,"precincts":
{"total":19,"reporting":19},
"name":"McDonald"},
"Ray":
{"votes":[
{"votes":709,"name":"huckabee"},
{"votes":554,"name":"mccain"},
{"votes":495,"name":"romney"},
{"votes":126,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":10,"name":"uncommitted-r"},
{"votes":8,"name":"giuliani"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1917,"precincts":
{"total":14,"reporting":14},
"name":"Ray"},
"Saline":
{"votes":[
{"votes":617,"name":"mccain"},
{"votes":518,"name":"huckabee"},
{"votes":392,"name":"romney"},
{"votes":51,"name":"paul"},
{"votes":12,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":5,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"tancredo"},
{"votes":0,"name":"hunter"}],
"total":1610,"precincts":
{"total":20,"reporting":20},
"name":"Saline"},
"St. Francois":
{"votes":[
{"votes":1727,"name":"mccain"},
{"votes":1631,"name":"huckabee"},
{"votes":949,"name":"romney"},
{"votes":134,"name":"paul"},
{"votes":39,"name":"giuliani"},
{"votes":38,"name":"thompson"},
{"votes":14,"name":"uncommitted-r"},
{"votes":7,"name":"keyes"},
{"votes":4,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":4543,"precincts":
{"total":27,"reporting":27},
"name":"St. Francois"},
"Cass":
{"votes":[
{"votes":3324,"name":"romney"},
{"votes":3195,"name":"mccain"},
{"votes":3033,"name":"huckabee"},
{"votes":477,"name":"paul"},
{"votes":62,"name":"giuliani"},
{"votes":55,"name":"thompson"},
{"votes":30,"name":"uncommitted-r"},
{"votes":22,"name":"keyes"},
{"votes":8,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":10209,"precincts":
{"total":48,"reporting":48},
"name":"Cass"},
"Dallas":
{"votes":[
{"votes":1124,"name":"huckabee"},
{"votes":738,"name":"mccain"},
{"votes":422,"name":"romney"},
{"votes":99,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":9,"name":"giuliani"},
{"votes":8,"name":"uncommitted-r"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":2415,"precincts":
{"total":14,"reporting":14},
"name":"Dallas"},
"Scotland":
{"votes":[
{"votes":185,"name":"huckabee"},
{"votes":129,"name":"mccain"},
{"votes":94,"name":"romney"},
{"votes":16,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"giuliani"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":433,"precincts":
{"total":8,"reporting":8},
"name":"Scotland"},
"Lawrence":
{"votes":[
{"votes":2628,"name":"huckabee"},
{"votes":1412,"name":"mccain"},
{"votes":1022,"name":"romney"},
{"votes":232,"name":"paul"},
{"votes":33,"name":"giuliani"},
{"votes":31,"name":"uncommitted-r"},
{"votes":23,"name":"thompson"},
{"votes":6,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":5389,"precincts":
{"total":21,"reporting":21},
"name":"Lawrence"},
"Vernon":
{"votes":[
{"votes":920,"name":"huckabee"},
{"votes":704,"name":"mccain"},
{"votes":408,"name":"romney"},
{"votes":74,"name":"paul"},
{"votes":20,"name":"giuliani"},
{"votes":13,"name":"thompson"},
{"votes":12,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":2156,"precincts":
{"total":18,"reporting":18},
"name":"Vernon"},
"Ozark":
{"votes":[
{"votes":766,"name":"huckabee"},
{"votes":428,"name":"mccain"},
{"votes":235,"name":"romney"},
{"votes":149,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"giuliani"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1593,"precincts":
{"total":11,"reporting":11},
"name":"Ozark"},
"Gentry":
{"votes":[
{"votes":217,"name":"mccain"},
{"votes":182,"name":"huckabee"},
{"votes":155,"name":"romney"},
{"votes":23,"name":"paul"},
{"votes":3,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":588,"precincts":
{"total":11,"reporting":11},
"name":"Gentry"},
"Cedar":
{"votes":[
{"votes":1051,"name":"huckabee"},
{"votes":709,"name":"mccain"},
{"votes":403,"name":"romney"},
{"votes":63,"name":"paul"},
{"votes":20,"name":"uncommitted-r"},
{"votes":20,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2283,"precincts":
{"total":10,"reporting":10},
"name":"Cedar"},
"Pike":
{"votes":[
{"votes":463,"name":"mccain"},
{"votes":461,"name":"huckabee"},
{"votes":388,"name":"romney"},
{"votes":84,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":8,"name":"giuliani"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":1419,"precincts":
{"total":15,"reporting":15},
"name":"Pike"},
"Lincoln":
{"votes":[
{"votes":1484,"name":"huckabee"},
{"votes":1412,"name":"mccain"},
{"votes":1400,"name":"romney"},
{"votes":216,"name":"paul"},
{"votes":30,"name":"thompson"},
{"votes":21,"name":"giuliani"},
{"votes":11,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":4580,"precincts":
{"total":25,"reporting":25},
"name":"Lincoln"},
"Dade":
{"votes":[
{"votes":769,"name":"huckabee"},
{"votes":418,"name":"mccain"},
{"votes":275,"name":"romney"},
{"votes":43,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":5,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1519,"precincts":
{"total":9,"reporting":9},
"name":"Dade"},
"Dent":
{"votes":[
{"votes":959,"name":"huckabee"},
{"votes":442,"name":"mccain"},
{"votes":411,"name":"romney"},
{"votes":127,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":7,"name":"giuliani"},
{"votes":6,"name":"keyes"},
{"votes":4,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1966,"precincts":
{"total":9,"reporting":9},
"name":"Dent"},
"Nodaway":
{"votes":[
{"votes":571,"name":"mccain"},
{"votes":454,"name":"romney"},
{"votes":451,"name":"huckabee"},
{"votes":81,"name":"paul"},
{"votes":15,"name":"giuliani"},
{"votes":9,"name":"thompson"},
{"votes":7,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1592,"precincts":
{"total":18,"reporting":18},
"name":"Nodaway"},
"Livingston":
{"votes":[
{"votes":488,"name":"mccain"},
{"votes":426,"name":"huckabee"},
{"votes":248,"name":"romney"},
{"votes":75,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1255,"precincts":
{"total":13,"reporting":13},
"name":"Livingston"},
"Franklin":
{"votes":[
{"votes":4032,"name":"mccain"},
{"votes":3447,"name":"romney"},
{"votes":3130,"name":"huckabee"},
{"votes":460,"name":"paul"},
{"votes":84,"name":"giuliani"},
{"votes":67,"name":"thompson"},
{"votes":52,"name":"uncommitted-r"},
{"votes":12,"name":"keyes"},
{"votes":6,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":11292,"precincts":
{"total":51,"reporting":51},
"name":"Franklin"},
"Audrain":
{"votes":[
{"votes":744,"name":"mccain"},
{"votes":708,"name":"huckabee"},
{"votes":649,"name":"romney"},
{"votes":99,"name":"paul"},
{"votes":14,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":7,"name":"uncommitted-r"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":2236,"precincts":
{"total":18,"reporting":18},
"name":"Audrain"},
"Osage":
{"votes":[
{"votes":664,"name":"mccain"},
{"votes":627,"name":"huckabee"},
{"votes":610,"name":"romney"},
{"votes":42,"name":"paul"},
{"votes":17,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":8,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1984,"precincts":
{"total":18,"reporting":18},
"name":"Osage"},
"Carroll":
{"votes":[
{"votes":437,"name":"mccain"},
{"votes":251,"name":"huckabee"},
{"votes":175,"name":"romney"},
{"votes":28,"name":"paul"},
{"votes":13,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":4,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":914,"precincts":
{"total":6,"reporting":6},
"name":"Carroll"},
"Schuyler":
{"votes":[
{"votes":178,"name":"huckabee"},
{"votes":103,"name":"mccain"},
{"votes":84,"name":"romney"},
{"votes":28,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":401,"precincts":
{"total":6,"reporting":6},
"name":"Schuyler"},
"Ralls":
{"votes":[
{"votes":376,"name":"huckabee"},
{"votes":279,"name":"romney"},
{"votes":256,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":948,"precincts":
{"total":8,"reporting":8},
"name":"Ralls"},
"Grundy":
{"votes":[
{"votes":377,"name":"mccain"},
{"votes":361,"name":"huckabee"},
{"votes":210,"name":"paul"},
{"votes":122,"name":"romney"},
{"votes":10,"name":"thompson"},
{"votes":6,"name":"uncommitted-r"},
{"votes":5,"name":"giuliani"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"}],
"total":1094,"precincts":
{"total":12,"reporting":12},
"name":"Grundy"},
"Harrison":
{"votes":[
{"votes":288,"name":"mccain"},
{"votes":277,"name":"huckabee"},
{"votes":207,"name":"romney"},
{"votes":93,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":5,"name":"thompson"},
{"votes":5,"name":"giuliani"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":882,"precincts":
{"total":21,"reporting":21},
"name":"Harrison"},
"Lewis":
{"votes":[
{"votes":285,"name":"huckabee"},
{"votes":279,"name":"mccain"},
{"votes":196,"name":"romney"},
{"votes":32,"name":"paul"},
{"votes":8,"name":"uncommitted-r"},
{"votes":7,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":813,"precincts":
{"total":11,"reporting":11},
"name":"Lewis"},
"Boone":
{"votes":[
{"votes":5684,"name":"romney"},
{"votes":4944,"name":"mccain"},
{"votes":3836,"name":"huckabee"},
{"votes":1047,"name":"paul"},
{"votes":109,"name":"giuliani"},
{"votes":78,"name":"uncommitted-r"},
{"votes":64,"name":"thompson"},
{"votes":40,"name":"keyes"},
{"votes":6,"name":"hunter"},
{"votes":5,"name":"tancredo"}],
"total":15813,"precincts":
{"total":86,"reporting":86},
"name":"Boone"},
"Cole":
{"votes":[
{"votes":3729,"name":"romney"},
{"votes":3247,"name":"huckabee"},
{"votes":2982,"name":"mccain"},
{"votes":227,"name":"paul"},
{"votes":76,"name":"giuliani"},
{"votes":60,"name":"thompson"},
{"votes":32,"name":"uncommitted-r"},
{"votes":13,"name":"keyes"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":10372,"precincts":
{"total":40,"reporting":40},
"name":"Cole"},
"Mercer":
{"votes":[
{"votes":132,"name":"huckabee"},
{"votes":114,"name":"mccain"},
{"votes":91,"name":"paul"},
{"votes":62,"name":"romney"},
{"votes":5,"name":"giuliani"},
{"votes":3,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":411,"precincts":
{"total":10,"reporting":10},
"name":"Mercer"},
"Shannon":
{"votes":[
{"votes":515,"name":"huckabee"},
{"votes":223,"name":"mccain"},
{"votes":109,"name":"paul"},
{"votes":83,"name":"romney"},
{"votes":8,"name":"keyes"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"}],
"total":945,"precincts":
{"total":8,"reporting":8},
"name":"Shannon"},
"Bollinger":
{"votes":[
{"votes":657,"name":"huckabee"},
{"votes":518,"name":"mccain"},
{"votes":384,"name":"romney"},
{"votes":65,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1654,"precincts":
{"total":12,"reporting":12},
"name":"Bollinger"},
"Iron":
{"votes":[
{"votes":354,"name":"huckabee"},
{"votes":269,"name":"mccain"},
{"votes":138,"name":"romney"},
{"votes":43,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":820,"precincts":
{"total":10,"reporting":10},
"name":"Iron"},
"Douglas":
{"votes":[
{"votes":1343,"name":"huckabee"},
{"votes":516,"name":"mccain"},
{"votes":295,"name":"paul"},
{"votes":270,"name":"romney"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"uncommitted-r"},
{"votes":5,"name":"giuliani"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":2440,"precincts":
{"total":25,"reporting":25},
"name":"Douglas"},
"Pulaski":
{"votes":[
{"votes":1216,"name":"huckabee"},
{"votes":1129,"name":"mccain"},
{"votes":641,"name":"romney"},
{"votes":66,"name":"paul"},
{"votes":27,"name":"giuliani"},
{"votes":21,"name":"thompson"},
{"votes":12,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":3120,"precincts":
{"total":10,"reporting":10},
"name":"Pulaski"},
"DeKalb":
{"votes":[
{"votes":337,"name":"romney"},
{"votes":310,"name":"mccain"},
{"votes":276,"name":"huckabee"},
{"votes":81,"name":"paul"},
{"votes":9,"name":"giuliani"},
{"votes":6,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":1026,"precincts":
{"total":12,"reporting":12},
"name":"DeKalb"},
"Crawford":
{"votes":[
{"votes":714,"name":"huckabee"},
{"votes":713,"name":"mccain"},
{"votes":606,"name":"romney"},
{"votes":112,"name":"paul"},
{"votes":18,"name":"thompson"},
{"votes":12,"name":"giuliani"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2183,"precincts":
{"total":7,"reporting":7},
"name":"Crawford"},
"Ste. Genevieve":
{"votes":[
{"votes":518,"name":"mccain"},
{"votes":419,"name":"huckabee"},
{"votes":270,"name":"romney"},
{"votes":47,"name":"paul"},
{"votes":9,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1271,"precincts":
{"total":14,"reporting":14},
"name":"Ste. Genevieve"},
"Christian":
{"votes":[
{"votes":5847,"name":"huckabee"},
{"votes":2943,"name":"mccain"},
{"votes":2748,"name":"romney"},
{"votes":416,"name":"paul"},
{"votes":38,"name":"giuliani"},
{"votes":36,"name":"thompson"},
{"votes":22,"name":"uncommitted-r"},
{"votes":11,"name":"keyes"},
{"votes":8,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":12070,"precincts":
{"total":28,"reporting":28},
"name":"Christian"},
"Phelps":
{"votes":[
{"votes":1728,"name":"huckabee"},
{"votes":1459,"name":"mccain"},
{"votes":1340,"name":"romney"},
{"votes":321,"name":"paul"},
{"votes":23,"name":"thompson"},
{"votes":23,"name":"giuliani"},
{"votes":9,"name":"uncommitted-r"},
{"votes":8,"name":"keyes"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"hunter"}],
"total":4914,"precincts":
{"total":25,"reporting":25},
"name":"Phelps"},
"Andrew":
{"votes":[
{"votes":641,"name":"romney"},
{"votes":501,"name":"mccain"},
{"votes":484,"name":"huckabee"},
{"votes":120,"name":"paul"},
{"votes":16,"name":"giuliani"},
{"votes":11,"name":"uncommitted-r"},
{"votes":10,"name":"thompson"},
{"votes":3,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1788,"precincts":
{"total":20,"reporting":20},
"name":"Andrew"},
"Atchison":
{"votes":[
{"votes":281,"name":"mccain"},
{"votes":230,"name":"romney"},
{"votes":189,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":9,"name":"thompson"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":741,"precincts":
{"total":6,"reporting":6},
"name":"Atchison"},
"St. Clair":
{"votes":[
{"votes":572,"name":"huckabee"},
{"votes":437,"name":"mccain"},
{"votes":246,"name":"romney"},
{"votes":44,"name":"paul"},
{"votes":10,"name":"uncommitted-r"},
{"votes":5,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":1318,"precincts":
{"total":19,"reporting":19},
"name":"St. Clair"},
"Jackson County":
{"votes":[
{"votes":13312,"name":"romney"},
{"votes":12356,"name":"mccain"},
{"votes":8892,"name":"huckabee"},
{"votes":2121,"name":"paul"},
{"votes":281,"name":"giuliani"},
{"votes":206,"name":"thompson"},
{"votes":146,"name":"uncommitted-r"},
{"votes":60,"name":"keyes"},
{"votes":23,"name":"tancredo"},
{"votes":22,"name":"hunter"}],
"total":37419,"precincts":
{"total":257,"reporting":257},
"name":"Jackson County"},
"Platte":
{"votes":[
{"votes":3108,"name":"romney"},
{"votes":2793,"name":"mccain"},
{"votes":1825,"name":"huckabee"},
{"votes":472,"name":"paul"},
{"votes":50,"name":"giuliani"},
{"votes":36,"name":"thompson"},
{"votes":35,"name":"uncommitted-r"},
{"votes":14,"name":"keyes"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":8339,"precincts":
{"total":34,"reporting":34},
"name":"Platte"},
"Pemiscot":
{"votes":[
{"votes":565,"name":"huckabee"},
{"votes":233,"name":"mccain"},
{"votes":149,"name":"romney"},
{"votes":20,"name":"paul"},
{"votes":7,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":980,"precincts":
{"total":17,"reporting":17},
"name":"Pemiscot"},
"Bates":
{"votes":[
{"votes":594,"name":"mccain"},
{"votes":503,"name":"huckabee"},
{"votes":368,"name":"romney"},
{"votes":71,"name":"paul"},
{"votes":13,"name":"giuliani"},
{"votes":11,"name":"thompson"},
{"votes":8,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":1574,"precincts":
{"total":16,"reporting":16},
"name":"Bates"},
"Cape Girardeau":
{"votes":[
{"votes":3922,"name":"romney"},
{"votes":3528,"name":"mccain"},
{"votes":3068,"name":"huckabee"},
{"votes":361,"name":"paul"},
{"votes":89,"name":"giuliani"},
{"votes":63,"name":"thompson"},
{"votes":52,"name":"uncommitted-r"},
{"votes":15,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":11102,"precincts":
{"total":36,"reporting":36},
"name":"Cape Girardeau"},
"Benton":
{"votes":[
{"votes":822,"name":"huckabee"},
{"votes":802,"name":"mccain"},
{"votes":579,"name":"romney"},
{"votes":75,"name":"paul"},
{"votes":16,"name":"giuliani"},
{"votes":11,"name":"thompson"},
{"votes":4,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2311,"precincts":
{"total":13,"reporting":13},
"name":"Benton"},
"Kansas City":
{"votes":[
{"votes":4790,"name":"mccain"},
{"votes":4119,"name":"romney"},
{"votes":2755,"name":"huckabee"},
{"votes":858,"name":"paul"},
{"votes":76,"name":"giuliani"},
{"votes":70,"name":"thompson"},
{"votes":57,"name":"uncommitted-r"},
{"votes":45,"name":"keyes"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":12779,"precincts":
{"total":132,"reporting":132},
"name":"Kansas City"},
"Lafayette":
{"votes":[
{"votes":1148,"name":"mccain"},
{"votes":979,"name":"huckabee"},
{"votes":898,"name":"romney"},
{"votes":160,"name":"paul"},
{"votes":24,"name":"thompson"},
{"votes":17,"name":"giuliani"},
{"votes":15,"name":"uncommitted-r"},
{"votes":6,"name":"hunter"},
{"votes":5,"name":"keyes"},
{"votes":0,"name":"tancredo"}],
"total":3252,"precincts":
{"total":16,"reporting":16},
"name":"Lafayette"},
"Howell":
{"votes":[
{"votes":2881,"name":"huckabee"},
{"votes":1347,"name":"mccain"},
{"votes":793,"name":"romney"},
{"votes":355,"name":"paul"},
{"votes":28,"name":"thompson"},
{"votes":15,"name":"giuliani"},
{"votes":10,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":5437,"precincts":
{"total":21,"reporting":21},
"name":"Howell"},
"Morgan":
{"votes":[
{"votes":896,"name":"huckabee"},
{"votes":857,"name":"mccain"},
{"votes":615,"name":"romney"},
{"votes":76,"name":"paul"},
{"votes":22,"name":"giuliani"},
{"votes":18,"name":"thompson"},
{"votes":10,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":2497,"precincts":
{"total":11,"reporting":11},
"name":"Morgan"},
"Carter":
{"votes":[
{"votes":373,"name":"huckabee"},
{"votes":202,"name":"mccain"},
{"votes":107,"name":"romney"},
{"votes":24,"name":"paul"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"thompson"},
{"votes":2,"name":"giuliani"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"keyes"}],
"total":712,"precincts":
{"total":8,"reporting":8},
"name":"Carter"},
"Miller":
{"votes":[
{"votes":1406,"name":"huckabee"},
{"votes":1094,"name":"mccain"},
{"votes":790,"name":"romney"},
{"votes":109,"name":"paul"},
{"votes":24,"name":"thompson"},
{"votes":22,"name":"giuliani"},
{"votes":16,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":3471,"precincts":
{"total":21,"reporting":21},
"name":"Miller"},
"Scott":
{"votes":[
{"votes":1549,"name":"huckabee"},
{"votes":1389,"name":"mccain"},
{"votes":1076,"name":"romney"},
{"votes":113,"name":"paul"},
{"votes":38,"name":"thompson"},
{"votes":24,"name":"giuliani"},
{"votes":15,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":4208,"precincts":
{"total":22,"reporting":22},
"name":"Scott"},
"Reynolds":
{"votes":[
{"votes":283,"name":"huckabee"},
{"votes":202,"name":"mccain"},
{"votes":93,"name":"romney"},
{"votes":25,"name":"paul"},
{"votes":6,"name":"giuliani"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":614,"precincts":
{"total":14,"reporting":14},
"name":"Reynolds"},
"Monroe":
{"votes":[
{"votes":300,"name":"huckabee"},
{"votes":231,"name":"romney"},
{"votes":221,"name":"mccain"},
{"votes":32,"name":"paul"},
{"votes":7,"name":"thompson"},
{"votes":6,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"tancredo"}],
"total":801,"precincts":
{"total":9,"reporting":9},
"name":"Monroe"}}})