GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":74286,"name":"obama","delegates":17},
{"votes":60653,"name":"clinton","delegates":14},
{"votes":1502,"name":"edwards"},
{"votes":570,"name":"biden"},
{"votes":483,"name":"richardson"},
{"votes":269,"name":"kucinich"},
{"votes":246,"name":"dodd"},
{"votes":183,"name":"gravel"}],
"name":"Mississippi","precincts":
{"total":1912,"reporting":763},
"delegates":33,"date":"03-11"},
"state":"MS","party":"dem","total":138192,"locals":
{"Yalobusha":
{"votes":[
{"votes":1479,"name":"obama"},
{"votes":1094,"name":"clinton"},
{"votes":26,"name":"edwards"},
{"votes":16,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":2632,"precincts":
{"total":11,"reporting":11},
"name":"Yalobusha"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":6340,"name":"obama"},
{"votes":4234,"name":"clinton"},
{"votes":89,"name":"edwards"},
{"votes":39,"name":"biden"},
{"votes":29,"name":"richardson"},
{"votes":19,"name":"kucinich"},
{"votes":14,"name":"dodd"},
{"votes":7,"name":"gravel"}],
"total":10771,"precincts":
{"total":43,"reporting":32},
"name":"Jackson"},
"Sunflower":
{"votes":[
{"votes":521,"name":"obama"},
{"votes":316,"name":"clinton"},
{"votes":7,"name":"richardson"},
{"votes":6,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":858,"precincts":
{"total":18,"reporting":6},
"name":"Sunflower"},
"Leake":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Leake"},
"Union":
{"votes":[
{"votes":2570,"name":"clinton"},
{"votes":980,"name":"obama"},
{"votes":72,"name":"edwards"},
{"votes":19,"name":"biden"},
{"votes":16,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"gravel"}],
"total":3669,"precincts":
{"total":20,"reporting":20},
"name":"Union"},
"Carroll":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Carroll"},
"Clarke":
{"votes":[
{"votes":1012,"name":"obama"},
{"votes":638,"name":"clinton"},
{"votes":11,"name":"richardson"},
{"votes":9,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":1690,"precincts":
{"total":23,"reporting":12},
"name":"Clarke"},
"Tippah":
{"votes":[
{"votes":1377,"name":"clinton"},
{"votes":541,"name":"obama"},
{"votes":30,"name":"edwards"},
{"votes":12,"name":"biden"},
{"votes":11,"name":"richardson"},
{"votes":7,"name":"dodd"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"kucinich"}],
"total":1989,"precincts":
{"total":24,"reporting":16},
"name":"Tippah"},
"Calhoun":
{"votes":[
{"votes":223,"name":"clinton"},
{"votes":140,"name":"obama"},
{"votes":7,"name":"edwards"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"}],
"total":374,"precincts":
{"total":10,"reporting":2},
"name":"Calhoun"},
"Hinds":
{"votes":[
{"votes":9488,"name":"obama"},
{"votes":2044,"name":"clinton"},
{"votes":22,"name":"edwards"},
{"votes":20,"name":"biden"},
{"votes":17,"name":"kucinich"},
{"votes":11,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":11607,"precincts":
{"total":118,"reporting":39},
"name":"Hinds"},
"Bolivar":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Bolivar"},
"Tishomingo":
{"votes":[
{"votes":1216,"name":"clinton"},
{"votes":187,"name":"obama"},
{"votes":41,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":9,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":1470,"precincts":
{"total":19,"reporting":9},
"name":"Tishomingo"},
"Covington":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Covington"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Jefferson"},
"Pearl River":
{"votes":[
{"votes":2222,"name":"clinton"},
{"votes":750,"name":"obama"},
{"votes":30,"name":"edwards"},
{"votes":16,"name":"biden"},
{"votes":8,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":3035,"precincts":
{"total":34,"reporting":28},
"name":"Pearl River"},
"Grenada":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Grenada"},
"Noxubee":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Noxubee"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Lincoln"},
"Newton":
{"votes":[
{"votes":1146,"name":"obama"},
{"votes":832,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":12,"name":"richardson"},
{"votes":8,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":2023,"precincts":
{"total":19,"reporting":16},
"name":"Newton"},
"George":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"George"},
"Leflore":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Leflore"},
"Wilkinson":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Wilkinson"},
"Lee":
{"votes":[
{"votes":4453,"name":"clinton"},
{"votes":2869,"name":"obama"},
{"votes":125,"name":"edwards"},
{"votes":23,"name":"richardson"},
{"votes":19,"name":"biden"},
{"votes":8,"name":"gravel"},
{"votes":7,"name":"dodd"},
{"votes":3,"name":"kucinich"}],
"total":7507,"precincts":
{"total":42,"reporting":35},
"name":"Lee"},
"Lawrence":
{"votes":[
{"votes":623,"name":"obama"},
{"votes":359,"name":"clinton"},
{"votes":9,"name":"biden"},
{"votes":7,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1006,"precincts":
{"total":26,"reporting":13},
"name":"Lawrence"},
"Attala":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Attala"},
"Rankin":
{"votes":[
{"votes":3724,"name":"obama"},
{"votes":2455,"name":"clinton"},
{"votes":35,"name":"edwards"},
{"votes":23,"name":"biden"},
{"votes":19,"name":"richardson"},
{"votes":7,"name":"dodd"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"kucinich"}],
"total":6269,"precincts":
{"total":52,"reporting":36},
"name":"Rankin"},
"Tate":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Tate"},
"Jeff Davis":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Jeff Davis"},
"Lauderdale":
{"votes":[
{"votes":918,"name":"obama"},
{"votes":372,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":1302,"precincts":
{"total":54,"reporting":13},
"name":"Lauderdale"},
"Amite":
{"votes":[
{"votes":1660,"name":"obama"},
{"votes":897,"name":"clinton"},
{"votes":30,"name":"edwards"},
{"votes":30,"name":"richardson"},
{"votes":25,"name":"biden"},
{"votes":13,"name":"dodd"},
{"votes":13,"name":"gravel"},
{"votes":6,"name":"kucinich"}],
"total":2674,"precincts":
{"total":21,"reporting":21},
"name":"Amite"},
"Walthall":
{"votes":[
{"votes":1640,"name":"obama"},
{"votes":913,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":17,"name":"biden"},
{"votes":15,"name":"richardson"},
{"votes":12,"name":"gravel"},
{"votes":11,"name":"kucinich"},
{"votes":10,"name":"dodd"}],
"total":2645,"precincts":
{"total":21,"reporting":21},
"name":"Walthall"},
"DeSoto":
{"votes":[
{"votes":799,"name":"clinton"},
{"votes":695,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1513,"precincts":
{"total":38,"reporting":11},
"name":"DeSoto"},
"Winston":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Winston"},
"Quitman":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Quitman"},
"Pontotoc":
{"votes":[
{"votes":2306,"name":"clinton"},
{"votes":1198,"name":"obama"},
{"votes":65,"name":"edwards"},
{"votes":14,"name":"biden"},
{"votes":12,"name":"richardson"},
{"votes":10,"name":"dodd"},
{"votes":8,"name":"gravel"},
{"votes":7,"name":"kucinich"}],
"total":3620,"precincts":
{"total":29,"reporting":29},
"name":"Pontotoc"},
"Claiborne":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Claiborne"},
"Alcorn":
{"votes":[
{"votes":3588,"name":"clinton"},
{"votes":1016,"name":"obama"},
{"votes":64,"name":"edwards"},
{"votes":30,"name":"biden"},
{"votes":13,"name":"richardson"},
{"votes":10,"name":"dodd"},
{"votes":5,"name":"kucinich"},
{"votes":3,"name":"gravel"}],
"total":4729,"precincts":
{"total":16,"reporting":16},
"name":"Alcorn"},
"Jones":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Jones"},
"Pike":
{"votes":[
{"votes":3515,"name":"obama"},
{"votes":1528,"name":"clinton"},
{"votes":49,"name":"edwards"},
{"votes":25,"name":"biden"},
{"votes":22,"name":"richardson"},
{"votes":17,"name":"kucinich"},
{"votes":7,"name":"gravel"},
{"votes":5,"name":"dodd"}],
"total":5168,"precincts":
{"total":32,"reporting":24},
"name":"Pike"},
"Stone":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Stone"},
"Choctaw":
{"votes":[
{"votes":157,"name":"obama"},
{"votes":20,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":187,"precincts":
{"total":13,"reporting":1},
"name":"Choctaw"},
"Adams":
{"votes":[
{"votes":4529,"name":"obama"},
{"votes":1477,"name":"clinton"},
{"votes":48,"name":"edwards"},
{"votes":19,"name":"kucinich"},
{"votes":13,"name":"biden"},
{"votes":10,"name":"gravel"},
{"votes":9,"name":"dodd"},
{"votes":9,"name":"richardson"}],
"total":6114,"precincts":
{"total":20,"reporting":20},
"name":"Adams"},
"Humphreys":
{"votes":[
{"votes":1038,"name":"obama"},
{"votes":314,"name":"clinton"},
{"votes":10,"name":"edwards"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"}],
"total":1382,"precincts":
{"total":13,"reporting":11},
"name":"Humphreys"},
"Hancock":
{"votes":[
{"votes":910,"name":"clinton"},
{"votes":210,"name":"obama"},
{"votes":22,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":1153,"precincts":
{"total":26,"reporting":11},
"name":"Hancock"},
"Benton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Benton"},
"Lamar":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lamar"},
"Sharkey":
{"votes":[
{"votes":920,"name":"obama"},
{"votes":313,"name":"clinton"},
{"votes":7,"name":"richardson"},
{"votes":6,"name":"edwards"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"biden"}],
"total":1258,"precincts":
{"total":10,"reporting":10},
"name":"Sharkey"},
"Coahoma":
{"votes":[
{"votes":1634,"name":"obama"},
{"votes":1015,"name":"clinton"},
{"votes":48,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":15,"name":"richardson"},
{"votes":11,"name":"kucinich"},
{"votes":9,"name":"dodd"},
{"votes":6,"name":"gravel"}],
"total":2753,"precincts":
{"total":19,"reporting":11},
"name":"Coahoma"},
"Greene":
{"votes":[
{"votes":923,"name":"clinton"},
{"votes":352,"name":"obama"},
{"votes":37,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":6,"name":"dodd"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":1337,"precincts":
{"total":14,"reporting":11},
"name":"Greene"},
"Chickasaw":
{"votes":[
{"votes":885,"name":"obama"},
{"votes":638,"name":"clinton"},
{"votes":13,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1552,"precincts":
{"total":15,"reporting":10},
"name":"Chickasaw"},
"Tallahatchie":
{"votes":[
{"votes":605,"name":"obama"},
{"votes":442,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":9,"name":"dodd"},
{"votes":6,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"gravel"}],
"total":1095,"precincts":
{"total":22,"reporting":11},
"name":"Tallahatchie"},
"Lafayette":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Lafayette"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Franklin"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Clay"},
"Webster":
{"votes":[
{"votes":906,"name":"clinton"},
{"votes":521,"name":"obama"},
{"votes":26,"name":"edwards"},
{"votes":8,"name":"gravel"},
{"votes":7,"name":"dodd"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"richardson"}],
"total":1480,"precincts":
{"total":17,"reporting":16},
"name":"Webster"},
"Montgomery":
{"votes":[
{"votes":298,"name":"obama"},
{"votes":297,"name":"clinton"},
{"votes":7,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"gravel"}],
"total":614,"precincts":
{"total":24,"reporting":10},
"name":"Montgomery"},
"Simpson":
{"votes":[
{"votes":357,"name":"obama"},
{"votes":118,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":4,"name":"kucinich"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":488,"precincts":
{"total":30,"reporting":23},
"name":"Simpson"},
"Kemper":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Kemper"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Madison"},
"Lowndes":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lowndes"},
"Tunica":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Tunica"},
"Smith":
{"votes":[
{"votes":1200,"name":"clinton"},
{"votes":972,"name":"obama"},
{"votes":38,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":2244,"precincts":
{"total":19,"reporting":19},
"name":"Smith"},
"Prentiss":
{"votes":[
{"votes":2461,"name":"clinton"},
{"votes":961,"name":"obama"},
{"votes":149,"name":"edwards"},
{"votes":47,"name":"richardson"},
{"votes":23,"name":"biden"},
{"votes":18,"name":"dodd"},
{"votes":13,"name":"kucinich"},
{"votes":8,"name":"gravel"}],
"total":3680,"precincts":
{"total":15,"reporting":10},
"name":"Prentiss"},
"Marshall":
{"votes":[
{"votes":2732,"name":"obama"},
{"votes":1809,"name":"clinton"},
{"votes":43,"name":"edwards"},
{"votes":33,"name":"biden"},
{"votes":19,"name":"richardson"},
{"votes":13,"name":"kucinich"},
{"votes":7,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":4659,"precincts":
{"total":24,"reporting":19},
"name":"Marshall"},
"Panola":
{"votes":[
{"votes":953,"name":"obama"},
{"votes":491,"name":"clinton"},
{"votes":11,"name":"kucinich"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"dodd"},
{"votes":5,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":1478,"precincts":
{"total":24,"reporting":8},
"name":"Panola"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Washington"},
"Yazoo":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Yazoo"},
"Itawamba":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Itawamba"},
"Neshoba":
{"votes":[
{"votes":653,"name":"clinton"},
{"votes":515,"name":"obama"},
{"votes":16,"name":"edwards"},
{"votes":11,"name":"biden"},
{"votes":8,"name":"gravel"},
{"votes":7,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"kucinich"}],
"total":1216,"precincts":
{"total":27,"reporting":22},
"name":"Neshoba"},
"Holmes":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Holmes"},
"Wayne":
{"votes":[
{"votes":852,"name":"obama"},
{"votes":818,"name":"clinton"},
{"votes":37,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":1738,"precincts":
{"total":24,"reporting":9},
"name":"Wayne"},
"Scott":
{"votes":[
{"votes":802,"name":"obama"},
{"votes":699,"name":"clinton"},
{"votes":22,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":1554,"precincts":
{"total":24,"reporting":12},
"name":"Scott"},
"Jasper":
{"votes":[
{"votes":755,"name":"obama"},
{"votes":272,"name":"clinton"},
{"votes":8,"name":"edwards"},
{"votes":6,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"dodd"}],
"total":1051,"precincts":
{"total":19,"reporting":5},
"name":"Jasper"},
"Harrison":
{"votes":[
{"votes":4587,"name":"clinton"},
{"votes":4158,"name":"obama"},
{"votes":51,"name":"edwards"},
{"votes":19,"name":"richardson"},
{"votes":16,"name":"biden"},
{"votes":5,"name":"dodd"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"kucinich"}],
"total":8841,"precincts":
{"total":66,"reporting":41},
"name":"Harrison"},
"Issaquena":
{"votes":[
{"votes":284,"name":"obama"},
{"votes":129,"name":"clinton"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"edwards"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":431,"precincts":
{"total":5,"reporting":5},
"name":"Issaquena"},
"Oktibbeha":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Oktibbeha"},
"Marion":
{"votes":[
{"votes":1510,"name":"obama"},
{"votes":1273,"name":"clinton"},
{"votes":33,"name":"edwards"},
{"votes":10,"name":"biden"},
{"votes":10,"name":"richardson"},
{"votes":9,"name":"dodd"},
{"votes":9,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":2858,"precincts":
{"total":24,"reporting":15},
"name":"Marion"},
"Forrest":
{"votes":[
{"votes":3237,"name":"obama"},
{"votes":2206,"name":"clinton"},
{"votes":25,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":9,"name":"biden"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"dodd"}],
"total":5506,"precincts":
{"total":33,"reporting":21},
"name":"Forrest"},
"Copiah":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Copiah"},
"Monroe":
{"votes":[
{"votes":1369,"name":"obama"},
{"votes":959,"name":"clinton"},
{"votes":31,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":10,"name":"richardson"},
{"votes":7,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":2394,"precincts":
{"total":25,"reporting":10},
"name":"Monroe"},
"Warren":
{"votes":[
{"votes":3238,"name":"obama"},
{"votes":1287,"name":"clinton"},
{"votes":26,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":6,"name":"gravel"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"kucinich"}],
"total":4578,"precincts":
{"total":22,"reporting":12},
"name":"Warren"}}})