GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":5324,"name":"clinton"},
{"votes":4628,"name":"obama"},
{"votes":117,"name":"edwards"},
{"votes":46,"name":"biden"},
{"votes":37,"name":"richardson"},
{"votes":23,"name":"dodd"},
{"votes":16,"name":"kucinich"},
{"votes":12,"name":"gravel"}],
"name":"Mississippi","precincts":
{"total":1912,"reporting":81},
"delegates":33,"date":"03-11"},
"state":"MS","party":"dem","total":10203,"locals":
{"Yalobusha":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Yalobusha"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":880,"name":"clinton"},
{"votes":855,"name":"obama"},
{"votes":21,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"}],
"total":1771,"precincts":
{"total":43,"reporting":10},
"name":"Jackson"},
"Sunflower":
{"votes":[
{"votes":141,"name":"obama"},
{"votes":78,"name":"clinton"},
{"votes":1,"name":"biden"}],
"total":220,"precincts":
{"total":18,"reporting":1},
"name":"Sunflower"},
"Leake":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Leake"},
"Union":
{"votes":[
{"votes":557,"name":"clinton"},
{"votes":262,"name":"obama"},
{"votes":13,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":847,"precincts":
{"total":20,"reporting":5},
"name":"Union"},
"Carroll":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Carroll"},
"Clarke":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Clarke"},
"Tippah":
{"votes":[
{"votes":422,"name":"clinton"},
{"votes":62,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"richardson"}],
"total":499,"precincts":
{"total":24,"reporting":6},
"name":"Tippah"},
"Calhoun":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Calhoun"},
"Hinds":
{"votes":[],
"total":0,"precincts":
{"total":118,"reporting":0},
"name":"Hinds"},
"Bolivar":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Bolivar"},
"Tishomingo":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Tishomingo"},
"Covington":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Covington"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Jefferson"},
"Pearl River":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Pearl River"},
"Grenada":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Grenada"},
"Noxubee":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Noxubee"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Lincoln"},
"Newton":
{"votes":[
{"votes":202,"name":"obama"},
{"votes":148,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":360,"precincts":
{"total":19,"reporting":4},
"name":"Newton"},
"George":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"George"},
"Leflore":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Leflore"},
"Wilkinson":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Wilkinson"},
"Lee":
{"votes":[
{"votes":732,"name":"clinton"},
{"votes":338,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"gravel"}],
"total":1095,"precincts":
{"total":42,"reporting":11},
"name":"Lee"},
"Lawrence":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Lawrence"},
"Attala":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Attala"},
"Rankin":
{"votes":[
{"votes":190,"name":"clinton"},
{"votes":143,"name":"obama"},
{"votes":1,"name":"gravel"}],
"total":334,"precincts":
{"total":52,"reporting":3},
"name":"Rankin"},
"Tate":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Tate"},
"Jeff Davis":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Jeff Davis"},
"Lauderdale":
{"votes":[],
"total":0,"precincts":
{"total":54,"reporting":0},
"name":"Lauderdale"},
"Amite":
{"votes":[
{"votes":709,"name":"obama"},
{"votes":428,"name":"clinton"},
{"votes":15,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":9,"name":"dodd"},
{"votes":7,"name":"biden"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":1182,"precincts":
{"total":21,"reporting":10},
"name":"Amite"},
"Walthall":
{"votes":[
{"votes":239,"name":"clinton"},
{"votes":236,"name":"obama"},
{"votes":11,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":494,"precincts":
{"total":21,"reporting":5},
"name":"Walthall"},
"DeSoto":
{"votes":[
{"votes":77,"name":"clinton"},
{"votes":40,"name":"obama"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"edwards"}],
"total":120,"precincts":
{"total":38,"reporting":2},
"name":"DeSoto"},
"Winston":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Winston"},
"Quitman":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Quitman"},
"Pontotoc":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Pontotoc"},
"Claiborne":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Claiborne"},
"Alcorn":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Alcorn"},
"Jones":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Jones"},
"Pike":
{"votes":[
{"votes":137,"name":"obama"},
{"votes":29,"name":"clinton"},
{"votes":2,"name":"biden"}],
"total":168,"precincts":
{"total":32,"reporting":1},
"name":"Pike"},
"Stone":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Stone"},
"Choctaw":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Choctaw"},
"Adams":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Adams"},
"Humphreys":
{"votes":[
{"votes":132,"name":"obama"},
{"votes":70,"name":"clinton"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"}],
"total":204,"precincts":
{"total":13,"reporting":1},
"name":"Humphreys"},
"Hancock":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Hancock"},
"Benton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Benton"},
"Lamar":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lamar"},
"Sharkey":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Sharkey"},
"Coahoma":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Coahoma"},
"Greene":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Greene"},
"Chickasaw":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Chickasaw"},
"Tallahatchie":
{"votes":[
{"votes":232,"name":"clinton"},
{"votes":204,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"gravel"}],
"total":462,"precincts":
{"total":22,"reporting":4},
"name":"Tallahatchie"},
"Lafayette":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Lafayette"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Franklin"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Clay"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Webster"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Montgomery"},
"Simpson":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Simpson"},
"Kemper":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Kemper"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Madison"},
"Lowndes":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lowndes"},
"Tunica":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Tunica"},
"Smith":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Smith"},
"Prentiss":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Prentiss"},
"Marshall":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Marshall"},
"Panola":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Panola"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Washington"},
"Yazoo":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Yazoo"},
"Itawamba":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Itawamba"},
"Neshoba":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Neshoba"},
"Holmes":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Holmes"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Wayne"},
"Scott":
{"votes":[
{"votes":277,"name":"clinton"},
{"votes":116,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"kucinich"}],
"total":412,"precincts":
{"total":24,"reporting":6},
"name":"Scott"},
"Jasper":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Jasper"},
"Harrison":
{"votes":[
{"votes":909,"name":"obama"},
{"votes":845,"name":"clinton"},
{"votes":8,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":1772,"precincts":
{"total":66,"reporting":10},
"name":"Harrison"},
"Issaquena":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Issaquena"},
"Oktibbeha":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Oktibbeha"},
"Marion":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Marion"},
"Forrest":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Forrest"},
"Copiah":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Copiah"},
"Monroe":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Monroe"},
"Warren":
{"votes":[
{"votes":142,"name":"obama"},
{"votes":120,"name":"clinton"},
{"votes":1,"name":"richardson"}],
"total":263,"precincts":
{"total":22,"reporting":2},
"name":"Warren"}}})