GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":69242,"name":"mccain"},
{"votes":11120,"name":"huckabee"},
{"votes":3501,"name":"paul"},
{"votes":1341,"name":"romney"},
{"votes":1272,"name":"thompson"},
{"votes":595,"name":"giuliani"},
{"votes":509,"name":"keyes"},
{"votes":251,"name":"hunter"},
{"votes":153,"name":"tancredo"}],
"name":"Mississippi","precincts":
{"total":1912,"reporting":1256},
"delegates":39,"date":"03-11"},
"state":"MS","party":"gop","total":87984,"locals":
{"Yalobusha":
{"votes":[
{"votes":566,"name":"mccain"},
{"votes":99,"name":"huckabee"},
{"votes":15,"name":"paul"},
{"votes":10,"name":"romney"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":2,"name":"keyes"}],
"total":702,"precincts":
{"total":11,"reporting":11},
"name":"Yalobusha"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":2566,"name":"mccain"},
{"votes":416,"name":"huckabee"},
{"votes":264,"name":"paul"},
{"votes":94,"name":"romney"},
{"votes":54,"name":"thompson"},
{"votes":31,"name":"giuliani"},
{"votes":18,"name":"keyes"},
{"votes":15,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":3461,"precincts":
{"total":43,"reporting":32},
"name":"Jackson"},
"Sunflower":
{"votes":[
{"votes":52,"name":"mccain"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"keyes"}],
"total":54,"precincts":
{"total":18,"reporting":6},
"name":"Sunflower"},
"Leake":
{"votes":[
{"votes":742,"name":"mccain"},
{"votes":116,"name":"huckabee"},
{"votes":16,"name":"paul"},
{"votes":9,"name":"thompson"},
{"votes":7,"name":"romney"},
{"votes":5,"name":"keyes"},
{"votes":5,"name":"giuliani"},
{"votes":4,"name":"hunter"}],
"total":904,"precincts":
{"total":21,"reporting":21},
"name":"Leake"},
"Union":
{"votes":[
{"votes":1185,"name":"mccain"},
{"votes":262,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":17,"name":"tancredo"},
{"votes":9,"name":"keyes"},
{"votes":8,"name":"romney"},
{"votes":5,"name":"hunter"},
{"votes":5,"name":"giuliani"}],
"total":1536,"precincts":
{"total":20,"reporting":20},
"name":"Union"},
"Carroll":
{"votes":[
{"votes":230,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":2,"name":"thompson"},
{"votes":2,"name":"keyes"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"tancredo"}],
"total":274,"precincts":
{"total":14,"reporting":14},
"name":"Carroll"},
"Clarke":
{"votes":[
{"votes":751,"name":"mccain"},
{"votes":110,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":6,"name":"romney"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":906,"precincts":
{"total":23,"reporting":23},
"name":"Clarke"},
"Tippah":
{"votes":[
{"votes":775,"name":"mccain"},
{"votes":172,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":13,"name":"thompson"},
{"votes":9,"name":"keyes"},
{"votes":8,"name":"giuliani"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":1028,"precincts":
{"total":24,"reporting":24},
"name":"Tippah"},
"Calhoun":
{"votes":[
{"votes":223,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":11,"name":"paul"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"thompson"}],
"total":288,"precincts":
{"total":10,"reporting":4},
"name":"Calhoun"},
"Hinds":
{"votes":[
{"votes":5773,"name":"mccain"},
{"votes":633,"name":"huckabee"},
{"votes":306,"name":"paul"},
{"votes":157,"name":"romney"},
{"votes":147,"name":"thompson"},
{"votes":56,"name":"giuliani"},
{"votes":45,"name":"keyes"},
{"votes":18,"name":"hunter"},
{"votes":9,"name":"tancredo"}],
"total":7144,"precincts":
{"total":118,"reporting":93},
"name":"Hinds"},
"Bolivar":
{"votes":[
{"votes":272,"name":"mccain"},
{"votes":33,"name":"huckabee"},
{"votes":10,"name":"paul"},
{"votes":5,"name":"tancredo"},
{"votes":4,"name":"romney"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"thompson"}],
"total":327,"precincts":
{"total":28,"reporting":28},
"name":"Bolivar"},
"Tishomingo":
{"votes":[
{"votes":469,"name":"mccain"},
{"votes":101,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":12,"name":"romney"},
{"votes":8,"name":"thompson"},
{"votes":3,"name":"keyes"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"giuliani"}],
"total":618,"precincts":
{"total":19,"reporting":14},
"name":"Tishomingo"},
"Covington":
{"votes":[
{"votes":610,"name":"mccain"},
{"votes":88,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":759,"precincts":
{"total":17,"reporting":16},
"name":"Covington"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Jefferson"},
"Pearl River":
{"votes":[
{"votes":1012,"name":"mccain"},
{"votes":209,"name":"huckabee"},
{"votes":126,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":11,"name":"romney"},
{"votes":11,"name":"keyes"},
{"votes":8,"name":"giuliani"},
{"votes":6,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":1400,"precincts":
{"total":34,"reporting":28},
"name":"Pearl River"},
"Grenada":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Grenada"},
"Noxubee":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Noxubee"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Lincoln"},
"Newton":
{"votes":[
{"votes":1474,"name":"mccain"},
{"votes":199,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":20,"name":"thompson"},
{"votes":14,"name":"romney"},
{"votes":11,"name":"keyes"},
{"votes":9,"name":"giuliani"},
{"votes":7,"name":"hunter"}],
"total":1766,"precincts":
{"total":19,"reporting":16},
"name":"Newton"},
"George":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"George"},
"Leflore":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Leflore"},
"Wilkinson":
{"votes":[
{"votes":172,"name":"mccain"},
{"votes":27,"name":"huckabee"},
{"votes":16,"name":"paul"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":218,"precincts":
{"total":9,"reporting":9},
"name":"Wilkinson"},
"Lee":
{"votes":[
{"votes":4464,"name":"mccain"},
{"votes":664,"name":"huckabee"},
{"votes":142,"name":"paul"},
{"votes":77,"name":"thompson"},
{"votes":74,"name":"romney"},
{"votes":37,"name":"keyes"},
{"votes":22,"name":"giuliani"},
{"votes":9,"name":"hunter"},
{"votes":8,"name":"tancredo"}],
"total":5497,"precincts":
{"total":42,"reporting":42},
"name":"Lee"},
"Lawrence":
{"votes":[
{"votes":705,"name":"mccain"},
{"votes":106,"name":"huckabee"},
{"votes":13,"name":"paul"},
{"votes":9,"name":"thompson"},
{"votes":7,"name":"romney"},
{"votes":3,"name":"hunter"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":847,"precincts":
{"total":26,"reporting":25},
"name":"Lawrence"},
"Attala":
{"votes":[
{"votes":571,"name":"mccain"},
{"votes":75,"name":"huckabee"},
{"votes":10,"name":"paul"},
{"votes":9,"name":"tancredo"},
{"votes":7,"name":"keyes"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"romney"},
{"votes":1,"name":"hunter"}],
"total":683,"precincts":
{"total":21,"reporting":20},
"name":"Attala"},
"Rankin":
{"votes":[
{"votes":12396,"name":"mccain"},
{"votes":1655,"name":"huckabee"},
{"votes":515,"name":"paul"},
{"votes":309,"name":"thompson"},
{"votes":272,"name":"romney"},
{"votes":110,"name":"giuliani"},
{"votes":75,"name":"keyes"},
{"votes":42,"name":"hunter"},
{"votes":12,"name":"tancredo"}],
"total":15386,"precincts":
{"total":52,"reporting":46},
"name":"Rankin"},
"Tate":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Tate"},
"Jeff Davis":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Jeff Davis"},
"Lauderdale":
{"votes":[
{"votes":1906,"name":"mccain"},
{"votes":256,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":28,"name":"thompson"},
{"votes":21,"name":"romney"},
{"votes":17,"name":"keyes"},
{"votes":17,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":2294,"precincts":
{"total":54,"reporting":21},
"name":"Lauderdale"},
"Amite":
{"votes":[
{"votes":762,"name":"mccain"},
{"votes":120,"name":"huckabee"},
{"votes":21,"name":"romney"},
{"votes":12,"name":"paul"},
{"votes":9,"name":"thompson"},
{"votes":6,"name":"keyes"},
{"votes":5,"name":"giuliani"},
{"votes":1,"name":"tancredo"}],
"total":936,"precincts":
{"total":21,"reporting":21},
"name":"Amite"},
"Walthall":
{"votes":[
{"votes":587,"name":"mccain"},
{"votes":76,"name":"huckabee"},
{"votes":22,"name":"paul"},
{"votes":15,"name":"romney"},
{"votes":15,"name":"thompson"},
{"votes":8,"name":"tancredo"},
{"votes":8,"name":"keyes"},
{"votes":4,"name":"hunter"},
{"votes":4,"name":"giuliani"}],
"total":739,"precincts":
{"total":21,"reporting":21},
"name":"Walthall"},
"DeSoto":
{"votes":[
{"votes":5207,"name":"mccain"},
{"votes":1235,"name":"huckabee"},
{"votes":360,"name":"paul"},
{"votes":139,"name":"thompson"},
{"votes":92,"name":"romney"},
{"votes":53,"name":"giuliani"},
{"votes":38,"name":"keyes"},
{"votes":21,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":7148,"precincts":
{"total":38,"reporting":29},
"name":"DeSoto"},
"Winston":
{"votes":[
{"votes":370,"name":"mccain"},
{"votes":56,"name":"huckabee"},
{"votes":9,"name":"paul"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"thompson"}],
"total":441,"precincts":
{"total":13,"reporting":3},
"name":"Winston"},
"Quitman":
{"votes":[
{"votes":26,"name":"mccain"},
{"votes":9,"name":"huckabee"}],
"total":35,"precincts":
{"total":11,"reporting":11},
"name":"Quitman"},
"Pontotoc":
{"votes":[
{"votes":1371,"name":"mccain"},
{"votes":340,"name":"huckabee"},
{"votes":55,"name":"paul"},
{"votes":28,"name":"thompson"},
{"votes":22,"name":"romney"},
{"votes":12,"name":"keyes"},
{"votes":8,"name":"giuliani"},
{"votes":5,"name":"hunter"}],
"total":1841,"precincts":
{"total":29,"reporting":29},
"name":"Pontotoc"},
"Claiborne":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Claiborne"},
"Alcorn":
{"votes":[
{"votes":910,"name":"mccain"},
{"votes":176,"name":"huckabee"},
{"votes":50,"name":"paul"},
{"votes":15,"name":"romney"},
{"votes":13,"name":"keyes"},
{"votes":9,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"tancredo"}],
"total":1181,"precincts":
{"total":16,"reporting":16},
"name":"Alcorn"},
"Jones":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Jones"},
"Pike":
{"votes":[
{"votes":1774,"name":"mccain"},
{"votes":278,"name":"huckabee"},
{"votes":64,"name":"paul"},
{"votes":24,"name":"thompson"},
{"votes":14,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":7,"name":"keyes"},
{"votes":4,"name":"romney"},
{"votes":2,"name":"tancredo"}],
"total":2174,"precincts":
{"total":32,"reporting":32},
"name":"Pike"},
"Stone":
{"votes":[
{"votes":332,"name":"mccain"},
{"votes":61,"name":"huckabee"},
{"votes":39,"name":"paul"},
{"votes":14,"name":"giuliani"},
{"votes":9,"name":"romney"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"thompson"}],
"total":464,"precincts":
{"total":17,"reporting":17},
"name":"Stone"},
"Choctaw":
{"votes":[
{"votes":257,"name":"mccain"},
{"votes":41,"name":"huckabee"},
{"votes":8,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"giuliani"}],
"total":313,"precincts":
{"total":13,"reporting":6},
"name":"Choctaw"},
"Adams":
{"votes":[
{"votes":1028,"name":"mccain"},
{"votes":137,"name":"huckabee"},
{"votes":111,"name":"paul"},
{"votes":30,"name":"romney"},
{"votes":9,"name":"thompson"},
{"votes":5,"name":"keyes"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":1329,"precincts":
{"total":20,"reporting":20},
"name":"Adams"},
"Humphreys":
{"votes":[
{"votes":34,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"giuliani"}],
"total":38,"precincts":
{"total":13,"reporting":11},
"name":"Humphreys"},
"Hancock":
{"votes":[
{"votes":373,"name":"mccain"},
{"votes":67,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":8,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"hunter"}],
"total":516,"precincts":
{"total":26,"reporting":18},
"name":"Hancock"},
"Benton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Benton"},
"Lamar":
{"votes":[
{"votes":973,"name":"mccain"},
{"votes":176,"name":"huckabee"},
{"votes":73,"name":"paul"},
{"votes":39,"name":"romney"},
{"votes":23,"name":"tancredo"},
{"votes":14,"name":"giuliani"},
{"votes":8,"name":"keyes"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"thompson"}],
"total":1310,"precincts":
{"total":22,"reporting":21},
"name":"Lamar"},
"Sharkey":
{"votes":[
{"votes":62,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"giuliani"}],
"total":73,"precincts":
{"total":10,"reporting":10},
"name":"Sharkey"},
"Coahoma":
{"votes":[
{"votes":76,"name":"mccain"},
{"votes":14,"name":"huckabee"},
{"votes":4,"name":"paul"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"giuliani"}],
"total":98,"precincts":
{"total":19,"reporting":19},
"name":"Coahoma"},
"Greene":
{"votes":[
{"votes":304,"name":"mccain"},
{"votes":58,"name":"huckabee"},
{"votes":8,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":381,"precincts":
{"total":14,"reporting":13},
"name":"Greene"},
"Chickasaw":
{"votes":[
{"votes":263,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":8,"name":"paul"},
{"votes":5,"name":"romney"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":334,"precincts":
{"total":15,"reporting":11},
"name":"Chickasaw"},
"Tallahatchie":
{"votes":[
{"votes":130,"name":"mccain"},
{"votes":25,"name":"huckabee"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"giuliani"}],
"total":161,"precincts":
{"total":22,"reporting":18},
"name":"Tallahatchie"},
"Lafayette":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Lafayette"},
"Franklin":
{"votes":[
{"votes":535,"name":"mccain"},
{"votes":86,"name":"huckabee"},
{"votes":9,"name":"paul"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"tancredo"},
{"votes":2,"name":"thompson"},
{"votes":2,"name":"giuliani"}],
"total":642,"precincts":
{"total":14,"reporting":14},
"name":"Franklin"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Clay"},
"Webster":
{"votes":[
{"votes":723,"name":"mccain"},
{"votes":125,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":5,"name":"romney"},
{"votes":5,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":896,"precincts":
{"total":17,"reporting":16},
"name":"Webster"},
"Montgomery":
{"votes":[
{"votes":185,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"thompson"}],
"total":229,"precincts":
{"total":24,"reporting":17},
"name":"Montgomery"},
"Simpson":
{"votes":[
{"votes":683,"name":"mccain"},
{"votes":78,"name":"huckabee"},
{"votes":29,"name":"paul"},
{"votes":12,"name":"tancredo"},
{"votes":8,"name":"romney"},
{"votes":5,"name":"giuliani"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"thompson"}],
"total":818,"precincts":
{"total":30,"reporting":23},
"name":"Simpson"},
"Kemper":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Kemper"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Madison"},
"Lowndes":
{"votes":[
{"votes":1026,"name":"mccain"},
{"votes":119,"name":"huckabee"},
{"votes":23,"name":"paul"},
{"votes":13,"name":"thompson"},
{"votes":13,"name":"keyes"},
{"votes":11,"name":"romney"},
{"votes":10,"name":"giuliani"},
{"votes":4,"name":"tancredo"},
{"votes":1,"name":"hunter"}],
"total":1220,"precincts":
{"total":22,"reporting":11},
"name":"Lowndes"},
"Tunica":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Tunica"},
"Smith":
{"votes":[
{"votes":1005,"name":"mccain"},
{"votes":151,"name":"huckabee"},
{"votes":39,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":7,"name":"romney"},
{"votes":6,"name":"giuliani"},
{"votes":5,"name":"hunter"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":1232,"precincts":
{"total":19,"reporting":19},
"name":"Smith"},
"Prentiss":
{"votes":[
{"votes":447,"name":"mccain"},
{"votes":103,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":18,"name":"romney"},
{"votes":4,"name":"hunter"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"tancredo"}],
"total":603,"precincts":
{"total":15,"reporting":10},
"name":"Prentiss"},
"Marshall":
{"votes":[
{"votes":829,"name":"mccain"},
{"votes":177,"name":"huckabee"},
{"votes":42,"name":"paul"},
{"votes":37,"name":"thompson"},
{"votes":14,"name":"keyes"},
{"votes":12,"name":"romney"},
{"votes":5,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":1119,"precincts":
{"total":24,"reporting":23},
"name":"Marshall"},
"Panola":
{"votes":[
{"votes":208,"name":"mccain"},
{"votes":36,"name":"huckabee"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":4,"name":"paul"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":263,"precincts":
{"total":24,"reporting":8},
"name":"Panola"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Washington"},
"Yazoo":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Yazoo"},
"Itawamba":
{"votes":[
{"votes":947,"name":"mccain"},
{"votes":214,"name":"huckabee"},
{"votes":19,"name":"thompson"},
{"votes":19,"name":"paul"},
{"votes":10,"name":"giuliani"},
{"votes":7,"name":"romney"},
{"votes":7,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":1225,"precincts":
{"total":26,"reporting":26},
"name":"Itawamba"},
"Neshoba":
{"votes":[
{"votes":1043,"name":"mccain"},
{"votes":133,"name":"huckabee"},
{"votes":20,"name":"thompson"},
{"votes":16,"name":"paul"},
{"votes":9,"name":"giuliani"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"hunter"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"tancredo"}],
"total":1238,"precincts":
{"total":27,"reporting":22},
"name":"Neshoba"},
"Holmes":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Holmes"},
"Wayne":
{"votes":[
{"votes":227,"name":"mccain"},
{"votes":33,"name":"huckabee"},
{"votes":8,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"tancredo"}],
"total":278,"precincts":
{"total":24,"reporting":16},
"name":"Wayne"},
"Scott":
{"votes":[
{"votes":1123,"name":"mccain"},
{"votes":128,"name":"huckabee"},
{"votes":17,"name":"thompson"},
{"votes":16,"name":"paul"},
{"votes":7,"name":"keyes"},
{"votes":6,"name":"romney"},
{"votes":6,"name":"hunter"},
{"votes":5,"name":"giuliani"}],
"total":1308,"precincts":
{"total":24,"reporting":19},
"name":"Scott"},
"Jasper":
{"votes":[
{"votes":375,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":5,"name":"keyes"},
{"votes":4,"name":"thompson"},
{"votes":2,"name":"tancredo"},
{"votes":2,"name":"giuliani"}],
"total":456,"precincts":
{"total":19,"reporting":18},
"name":"Jasper"},
"Harrison":
{"votes":[
{"votes":3035,"name":"mccain"},
{"votes":509,"name":"huckabee"},
{"votes":399,"name":"paul"},
{"votes":150,"name":"romney"},
{"votes":63,"name":"thompson"},
{"votes":42,"name":"giuliani"},
{"votes":33,"name":"keyes"},
{"votes":24,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":4258,"precincts":
{"total":66,"reporting":66},
"name":"Harrison"},
"Issaquena":
{"votes":[
{"votes":25,"name":"mccain"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"paul"}],
"total":29,"precincts":
{"total":5,"reporting":5},
"name":"Issaquena"},
"Oktibbeha":
{"votes":[
{"votes":1728,"name":"mccain"},
{"votes":338,"name":"huckabee"},
{"votes":77,"name":"paul"},
{"votes":36,"name":"romney"},
{"votes":31,"name":"thompson"},
{"votes":16,"name":"keyes"},
{"votes":9,"name":"hunter"},
{"votes":9,"name":"giuliani"}],
"total":2244,"precincts":
{"total":21,"reporting":20},
"name":"Oktibbeha"},
"Marion":
{"votes":[
{"votes":606,"name":"mccain"},
{"votes":100,"name":"huckabee"},
{"votes":18,"name":"thompson"},
{"votes":14,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":755,"precincts":
{"total":24,"reporting":22},
"name":"Marion"},
"Forrest":
{"votes":[
{"votes":1010,"name":"mccain"},
{"votes":194,"name":"huckabee"},
{"votes":115,"name":"paul"},
{"votes":36,"name":"romney"},
{"votes":33,"name":"thompson"},
{"votes":12,"name":"giuliani"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":1410,"precincts":
{"total":33,"reporting":30},
"name":"Forrest"},
"Copiah":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Copiah"},
"Monroe":
{"votes":[
{"votes":964,"name":"mccain"},
{"votes":191,"name":"huckabee"},
{"votes":28,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":9,"name":"thompson"},
{"votes":8,"name":"keyes"},
{"votes":7,"name":"giuliani"},
{"votes":6,"name":"hunter"}],
"total":1226,"precincts":
{"total":25,"reporting":20},
"name":"Monroe"},
"Warren":
{"votes":[
{"votes":765,"name":"mccain"},
{"votes":91,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":11,"name":"romney"},
{"votes":4,"name":"keyes"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"hunter"}],
"total":931,"precincts":
{"total":22,"reporting":12},
"name":"Warren"}}})