GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":63852,"name":"obama","delegates":8},
{"votes":43736,"name":"clinton","delegates":5},
{"votes":2674,"name":"nopreference-d"}],
"name":"Montana","precincts":
{"total":871,"reporting":428},
"delegates":16,"date":"06-03"},
"state":"MT","party":"dem","total":110262,"locals":
{"Judith Basin":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Judith Basin"},
"Richland":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Richland"},
"Glacier":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Glacier"},
"Silver Bow":
{"votes":[
{"votes":1201,"name":"clinton"},
{"votes":1048,"name":"obama"},
{"votes":102,"name":"nopreference-d"}],
"total":2351,"precincts":
{"total":45,"reporting":1},
"name":"Silver Bow"},
"Treasure":
{"votes":[
{"votes":93,"name":"obama"},
{"votes":85,"name":"clinton"},
{"votes":1,"name":"nopreference-d"}],
"total":179,"precincts":
{"total":3,"reporting":3},
"name":"Treasure"},
"Petroleum":
{"votes":[
{"votes":38,"name":"clinton"},
{"votes":27,"name":"obama"},
{"votes":4,"name":"nopreference-d"}],
"total":69,"precincts":
{"total":1,"reporting":1},
"name":"Petroleum"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lake"},
"Liberty":
{"votes":[
{"votes":120,"name":"clinton"},
{"votes":119,"name":"obama"},
{"votes":12,"name":"nopreference-d"}],
"total":251,"precincts":
{"total":4,"reporting":3},
"name":"Liberty"},
"Phillips":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Phillips"},
"Jefferson":
{"votes":[
{"votes":732,"name":"obama"},
{"votes":517,"name":"clinton"},
{"votes":27,"name":"nopreference-d"}],
"total":1276,"precincts":
{"total":14,"reporting":5},
"name":"Jefferson"},
"Hill":
{"votes":[
{"votes":112,"name":"obama"},
{"votes":79,"name":"clinton"},
{"votes":6,"name":"nopreference-d"}],
"total":197,"precincts":
{"total":22,"reporting":1},
"name":"Hill"},
"Daniels":
{"votes":[
{"votes":197,"name":"clinton"},
{"votes":167,"name":"obama"},
{"votes":27,"name":"nopreference-d"}],
"total":391,"precincts":
{"total":5,"reporting":5},
"name":"Daniels"},
"Granite":
{"votes":[
{"votes":262,"name":"obama"},
{"votes":211,"name":"clinton"},
{"votes":6,"name":"nopreference-d"}],
"total":479,"precincts":
{"total":4,"reporting":4},
"name":"Granite"},
"Wibaux":
{"votes":[
{"votes":53,"name":"clinton"},
{"votes":49,"name":"obama"},
{"votes":3,"name":"nopreference-d"}],
"total":105,"precincts":
{"total":1,"reporting":1},
"name":"Wibaux"},
"Valley":
{"votes":[
{"votes":345,"name":"clinton"},
{"votes":302,"name":"obama"},
{"votes":22,"name":"nopreference-d"}],
"total":669,"precincts":
{"total":11,"reporting":3},
"name":"Valley"},
"Lincoln":
{"votes":[
{"votes":146,"name":"clinton"},
{"votes":141,"name":"obama"},
{"votes":3,"name":"nopreference-d"}],
"total":290,"precincts":
{"total":14,"reporting":1},
"name":"Lincoln"},
"Powell":
{"votes":[
{"votes":159,"name":"obama"},
{"votes":113,"name":"clinton"},
{"votes":5,"name":"nopreference-d"}],
"total":277,"precincts":
{"total":12,"reporting":2},
"name":"Powell"},
"Golden Valley":
{"votes":[
{"votes":77,"name":"obama"},
{"votes":65,"name":"clinton"},
{"votes":10,"name":"nopreference-d"}],
"total":152,"precincts":
{"total":2,"reporting":2},
"name":"Golden Valley"},
"Powder River":
{"votes":[
{"votes":59,"name":"obama"},
{"votes":52,"name":"clinton"},
{"votes":3,"name":"nopreference-d"}],
"total":114,"precincts":
{"total":8,"reporting":8},
"name":"Powder River"},
"Custer":
{"votes":[
{"votes":1084,"name":"clinton"},
{"votes":860,"name":"obama"},
{"votes":54,"name":"nopreference-d"}],
"total":1998,"precincts":
{"total":14,"reporting":14},
"name":"Custer"},
"Park":
{"votes":[
{"votes":2065,"name":"obama"},
{"votes":999,"name":"clinton"},
{"votes":65,"name":"nopreference-d"}],
"total":3129,"precincts":
{"total":15,"reporting":13},
"name":"Park"},
"Garfield":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Garfield"},
"Chouteau":
{"votes":[
{"votes":438,"name":"obama"},
{"votes":396,"name":"clinton"},
{"votes":16,"name":"nopreference-d"}],
"total":850,"precincts":
{"total":12,"reporting":12},
"name":"Chouteau"},
"Teton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Teton"},
"Musselshell":
{"votes":[
{"votes":237,"name":"clinton"},
{"votes":200,"name":"obama"}],
"total":437,"precincts":
{"total":6,"reporting":4},
"name":"Musselshell"},
"Prairie":
{"votes":[
{"votes":122,"name":"clinton"},
{"votes":90,"name":"obama"},
{"votes":15,"name":"nopreference-d"}],
"total":227,"precincts":
{"total":4,"reporting":4},
"name":"Prairie"},
"Yellowstone":
{"votes":[
{"votes":8515,"name":"obama"},
{"votes":7976,"name":"clinton"},
{"votes":458,"name":"nopreference-d"}],
"total":16949,"precincts":
{"total":69,"reporting":33},
"name":"Yellowstone"},
"Meagher":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Meagher"},
"Carbon":
{"votes":[
{"votes":470,"name":"obama"},
{"votes":450,"name":"clinton"},
{"votes":66,"name":"nopreference-d"}],
"total":986,"precincts":
{"total":16,"reporting":11},
"name":"Carbon"},
"Stillwater":
{"votes":[
{"votes":562,"name":"obama"},
{"votes":424,"name":"clinton"},
{"votes":43,"name":"nopreference-d"}],
"total":1029,"precincts":
{"total":8,"reporting":6},
"name":"Stillwater"},
"Flathead":
{"votes":[
{"votes":5092,"name":"obama"},
{"votes":3142,"name":"clinton"},
{"votes":163,"name":"nopreference-d"}],
"total":8397,"precincts":
{"total":42,"reporting":28},
"name":"Flathead"},
"Sheridan":
{"votes":[
{"votes":79,"name":"clinton"},
{"votes":78,"name":"obama"},
{"votes":7,"name":"nopreference-d"}],
"total":164,"precincts":
{"total":6,"reporting":2},
"name":"Sheridan"},
"Broadwater":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Broadwater"},
"Mineral":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Mineral"},
"Sanders":
{"votes":[
{"votes":26,"name":"obama"},
{"votes":16,"name":"clinton"}],
"total":42,"precincts":
{"total":10,"reporting":1},
"name":"Sanders"},
"Fallon":
{"votes":[
{"votes":163,"name":"obama"},
{"votes":147,"name":"clinton"},
{"votes":13,"name":"nopreference-d"}],
"total":323,"precincts":
{"total":6,"reporting":1},
"name":"Fallon"},
"Fergus":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fergus"},
"Big Horn":
{"votes":[
{"votes":1274,"name":"obama"},
{"votes":390,"name":"clinton"},
{"votes":24,"name":"nopreference-d"}],
"total":1688,"precincts":
{"total":20,"reporting":12},
"name":"Big Horn"},
"Ravalli":
{"votes":[
{"votes":902,"name":"obama"},
{"votes":526,"name":"clinton"}],
"total":1428,"precincts":
{"total":22,"reporting":1},
"name":"Ravalli"},
"Missoula":
{"votes":[
{"votes":16035,"name":"obama"},
{"votes":7949,"name":"clinton"},
{"votes":340,"name":"nopreference-d"}],
"total":24324,"precincts":
{"total":101,"reporting":101},
"name":"Missoula"},
"Cascade":
{"votes":[
{"votes":6190,"name":"obama"},
{"votes":5735,"name":"clinton"},
{"votes":505,"name":"nopreference-d"}],
"total":12430,"precincts":
{"total":38,"reporting":28},
"name":"Cascade"},
"Roosevelt":
{"votes":[
{"votes":736,"name":"obama"},
{"votes":509,"name":"clinton"},
{"votes":47,"name":"nopreference-d"}],
"total":1292,"precincts":
{"total":13,"reporting":10},
"name":"Roosevelt"},
"McCone":
{"votes":[
{"votes":51,"name":"clinton"},
{"votes":42,"name":"obama"}],
"total":93,"precincts":
{"total":3,"reporting":1},
"name":"McCone"},
"Madison":
{"votes":[
{"votes":282,"name":"obama"},
{"votes":155,"name":"clinton"},
{"votes":20,"name":"nopreference-d"}],
"total":457,"precincts":
{"total":8,"reporting":4},
"name":"Madison"},
"Beaverhead":
{"votes":[
{"votes":182,"name":"obama"},
{"votes":83,"name":"clinton"}],
"total":265,"precincts":
{"total":16,"reporting":2},
"name":"Beaverhead"},
"Carter":
{"votes":[
{"votes":70,"name":"obama"},
{"votes":52,"name":"clinton"},
{"votes":6,"name":"nopreference-d"}],
"total":128,"precincts":
{"total":4,"reporting":4},
"name":"Carter"},
"Sweet Grass":
{"votes":[
{"votes":160,"name":"obama"},
{"votes":131,"name":"clinton"},
{"votes":11,"name":"nopreference-d"}],
"total":302,"precincts":
{"total":5,"reporting":1},
"name":"Sweet Grass"},
"Pondera":
{"votes":[
{"votes":639,"name":"obama"},
{"votes":480,"name":"clinton"},
{"votes":35,"name":"nopreference-d"}],
"total":1154,"precincts":
{"total":8,"reporting":8},
"name":"Pondera"},
"Lewis & Clark":
{"votes":[
{"votes":6362,"name":"obama"},
{"votes":3982,"name":"clinton"},
{"votes":244,"name":"nopreference-d"}],
"total":10588,"precincts":
{"total":56,"reporting":30},
"name":"Lewis & Clark"},
"Deer Lodge":
{"votes":[
{"votes":1750,"name":"clinton"},
{"votes":1142,"name":"obama"},
{"votes":84,"name":"nopreference-d"}],
"total":2976,"precincts":
{"total":18,"reporting":18},
"name":"Deer Lodge"},
"Rosebud":
{"votes":[
{"votes":894,"name":"obama"},
{"votes":662,"name":"clinton"},
{"votes":67,"name":"nopreference-d"}],
"total":1623,"precincts":
{"total":12,"reporting":12},
"name":"Rosebud"},
"Wheatland":
{"votes":[
{"votes":128,"name":"clinton"},
{"votes":122,"name":"obama"},
{"votes":1,"name":"nopreference-d"}],
"total":251,"precincts":
{"total":5,"reporting":3},
"name":"Wheatland"},
"Blaine":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":785,"name":"clinton"},
{"votes":643,"name":"obama"},
{"votes":63,"name":"nopreference-d"}],
"total":1491,"precincts":
{"total":12,"reporting":12},
"name":"Dawson"},
"Toole":
{"votes":[
{"votes":19,"name":"clinton"},
{"votes":10,"name":"obama"},
{"votes":1,"name":"nopreference-d"}],
"total":30,"precincts":
{"total":10,"reporting":1},
"name":"Toole"},
"Gallatin":
{"votes":[
{"votes":6261,"name":"obama"},
{"votes":2055,"name":"clinton"},
{"votes":95,"name":"nopreference-d"}],
"total":8411,"precincts":
{"total":46,"reporting":11},
"name":"Gallatin"}}})