GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":42080,"name":"obama","delegates":8},
{"votes":27887,"name":"clinton","delegates":5},
{"votes":1788,"name":"nopreference-d"}],
"name":"Montana","precincts":
{"total":871,"reporting":197},
"delegates":16,"date":"06-03"},
"state":"MT","party":"dem","total":71755,"locals":
{"Judith Basin":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Judith Basin"},
"Richland":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Richland"},
"Glacier":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Glacier"},
"Silver Bow":
{"votes":[],
"total":0,"precincts":
{"total":45,"reporting":0},
"name":"Silver Bow"},
"Treasure":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Treasure"},
"Petroleum":
{"votes":[
{"votes":38,"name":"clinton"},
{"votes":27,"name":"obama"},
{"votes":4,"name":"nopreference-d"}],
"total":69,"precincts":
{"total":1,"reporting":1},
"name":"Petroleum"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lake"},
"Liberty":
{"votes":[
{"votes":39,"name":"clinton"},
{"votes":34,"name":"obama"},
{"votes":3,"name":"nopreference-d"}],
"total":76,"precincts":
{"total":4,"reporting":1},
"name":"Liberty"},
"Phillips":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Phillips"},
"Jefferson":
{"votes":[
{"votes":392,"name":"obama"},
{"votes":261,"name":"clinton"},
{"votes":19,"name":"nopreference-d"}],
"total":672,"precincts":
{"total":14,"reporting":1},
"name":"Jefferson"},
"Hill":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Hill"},
"Daniels":
{"votes":[
{"votes":28,"name":"clinton"},
{"votes":19,"name":"obama"},
{"votes":4,"name":"nopreference-d"}],
"total":51,"precincts":
{"total":5,"reporting":1},
"name":"Daniels"},
"Granite":
{"votes":[
{"votes":262,"name":"obama"},
{"votes":211,"name":"clinton"},
{"votes":6,"name":"nopreference-d"}],
"total":479,"precincts":
{"total":4,"reporting":4},
"name":"Granite"},
"Wibaux":
{"votes":[
{"votes":53,"name":"clinton"},
{"votes":49,"name":"obama"},
{"votes":3,"name":"nopreference-d"}],
"total":105,"precincts":
{"total":1,"reporting":1},
"name":"Wibaux"},
"Valley":
{"votes":[
{"votes":108,"name":"obama"},
{"votes":106,"name":"clinton"},
{"votes":12,"name":"nopreference-d"}],
"total":226,"precincts":
{"total":11,"reporting":1},
"name":"Valley"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Lincoln"},
"Powell":
{"votes":[
{"votes":76,"name":"obama"},
{"votes":45,"name":"clinton"},
{"votes":3,"name":"nopreference-d"}],
"total":124,"precincts":
{"total":12,"reporting":1},
"name":"Powell"},
"Golden Valley":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Golden Valley"},
"Powder River":
{"votes":[
{"votes":12,"name":"clinton"},
{"votes":9,"name":"obama"}],
"total":21,"precincts":
{"total":8,"reporting":2},
"name":"Powder River"},
"Custer":
{"votes":[
{"votes":616,"name":"clinton"},
{"votes":475,"name":"obama"},
{"votes":23,"name":"nopreference-d"}],
"total":1114,"precincts":
{"total":14,"reporting":4},
"name":"Custer"},
"Park":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Park"},
"Garfield":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Garfield"},
"Chouteau":
{"votes":[
{"votes":222,"name":"obama"},
{"votes":208,"name":"clinton"},
{"votes":9,"name":"nopreference-d"}],
"total":439,"precincts":
{"total":12,"reporting":6},
"name":"Chouteau"},
"Teton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Teton"},
"Musselshell":
{"votes":[
{"votes":237,"name":"clinton"},
{"votes":200,"name":"obama"}],
"total":437,"precincts":
{"total":6,"reporting":4},
"name":"Musselshell"},
"Prairie":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Prairie"},
"Yellowstone":
{"votes":[
{"votes":6004,"name":"obama"},
{"votes":5588,"name":"clinton"},
{"votes":386,"name":"nopreference-d"}],
"total":11978,"precincts":
{"total":69,"reporting":10},
"name":"Yellowstone"},
"Meagher":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Meagher"},
"Carbon":
{"votes":[
{"votes":124,"name":"obama"},
{"votes":111,"name":"clinton"},
{"votes":48,"name":"nopreference-d"}],
"total":283,"precincts":
{"total":16,"reporting":2},
"name":"Carbon"},
"Stillwater":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Stillwater"},
"Flathead":
{"votes":[
{"votes":2774,"name":"obama"},
{"votes":1622,"name":"clinton"},
{"votes":95,"name":"nopreference-d"}],
"total":4491,"precincts":
{"total":42,"reporting":10},
"name":"Flathead"},
"Sheridan":
{"votes":[
{"votes":79,"name":"clinton"},
{"votes":78,"name":"obama"},
{"votes":7,"name":"nopreference-d"}],
"total":164,"precincts":
{"total":6,"reporting":2},
"name":"Sheridan"},
"Broadwater":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Broadwater"},
"Mineral":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Mineral"},
"Sanders":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Sanders"},
"Fallon":
{"votes":[
{"votes":40,"name":"clinton"},
{"votes":30,"name":"obama"},
{"votes":3,"name":"nopreference-d"}],
"total":73,"precincts":
{"total":6,"reporting":2},
"name":"Fallon"},
"Fergus":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fergus"},
"Big Horn":
{"votes":[
{"votes":378,"name":"obama"},
{"votes":252,"name":"clinton"},
{"votes":10,"name":"nopreference-d"}],
"total":640,"precincts":
{"total":20,"reporting":7},
"name":"Big Horn"},
"Ravalli":
{"votes":[
{"votes":902,"name":"obama"},
{"votes":526,"name":"clinton"}],
"total":1428,"precincts":
{"total":22,"reporting":1},
"name":"Ravalli"},
"Missoula":
{"votes":[
{"votes":13436,"name":"obama"},
{"votes":6755,"name":"clinton"},
{"votes":290,"name":"nopreference-d"}],
"total":20481,"precincts":
{"total":101,"reporting":86},
"name":"Missoula"},
"Cascade":
{"votes":[
{"votes":4551,"name":"obama"},
{"votes":4254,"name":"clinton"},
{"votes":431,"name":"nopreference-d"}],
"total":9236,"precincts":
{"total":38,"reporting":0},
"name":"Cascade"},
"Roosevelt":
{"votes":[
{"votes":10,"name":"obama"},
{"votes":9,"name":"clinton"},
{"votes":1,"name":"nopreference-d"}],
"total":20,"precincts":
{"total":13,"reporting":1},
"name":"Roosevelt"},
"McCone":
{"votes":[
{"votes":51,"name":"clinton"},
{"votes":42,"name":"obama"}],
"total":93,"precincts":
{"total":3,"reporting":1},
"name":"McCone"},
"Madison":
{"votes":[
{"votes":195,"name":"obama"},
{"votes":112,"name":"clinton"},
{"votes":11,"name":"nopreference-d"}],
"total":318,"precincts":
{"total":8,"reporting":3},
"name":"Madison"},
"Beaverhead":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Beaverhead"},
"Carter":
{"votes":[
{"votes":63,"name":"obama"},
{"votes":48,"name":"clinton"},
{"votes":3,"name":"nopreference-d"}],
"total":114,"precincts":
{"total":4,"reporting":2},
"name":"Carter"},
"Sweet Grass":
{"votes":[
{"votes":160,"name":"obama"},
{"votes":131,"name":"clinton"},
{"votes":11,"name":"nopreference-d"}],
"total":302,"precincts":
{"total":5,"reporting":1},
"name":"Sweet Grass"},
"Pondera":
{"votes":[
{"votes":262,"name":"obama"},
{"votes":196,"name":"clinton"},
{"votes":24,"name":"nopreference-d"}],
"total":482,"precincts":
{"total":8,"reporting":3},
"name":"Pondera"},
"Lewis & Clark":
{"votes":[
{"votes":4937,"name":"obama"},
{"votes":2998,"name":"clinton"},
{"votes":184,"name":"nopreference-d"}],
"total":8119,"precincts":
{"total":56,"reporting":24},
"name":"Lewis & Clark"},
"Deer Lodge":
{"votes":[
{"votes":980,"name":"clinton"},
{"votes":643,"name":"obama"},
{"votes":48,"name":"nopreference-d"}],
"total":1671,"precincts":
{"total":18,"reporting":1},
"name":"Deer Lodge"},
"Rosebud":
{"votes":[
{"votes":598,"name":"obama"},
{"votes":438,"name":"clinton"},
{"votes":51,"name":"nopreference-d"}],
"total":1087,"precincts":
{"total":12,"reporting":7},
"name":"Rosebud"},
"Wheatland":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Wheatland"},
"Blaine":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":310,"name":"clinton"},
{"votes":265,"name":"obama"},
{"votes":15,"name":"nopreference-d"}],
"total":590,"precincts":
{"total":12,"reporting":6},
"name":"Dawson"},
"Toole":
{"votes":[
{"votes":19,"name":"clinton"},
{"votes":10,"name":"obama"},
{"votes":1,"name":"nopreference-d"}],
"total":30,"precincts":
{"total":10,"reporting":1},
"name":"Toole"},
"Gallatin":
{"votes":[
{"votes":4745,"name":"obama"},
{"votes":1514,"name":"clinton"},
{"votes":83,"name":"nopreference-d"}],
"total":6342,"precincts":
{"total":46,"reporting":0},
"name":"Gallatin"}}})