GoogleElectionMap.votesReady({"status":"ok","totals":
{"name":"Montana","precincts":
{"total":56,"reporting":56},
"votes":[
{"votes":71462,"name":"mccain"},
{"votes":19989,"name":"paul"},
{"votes":2019,"name":"nopreference-r"},
{"votes":625,"name":"romney","delegates":25},
{"votes":245,"name":"huckabee"},
{"votes":2,"name":"keyes"}],
"delegates":25,"date":"02-05","type":"caucus"},
"state":"MT","party":"gop","total":94342,"locals":
{"Judith Basin":
{"votes":[
{"votes":297,"name":"mccain"},
{"votes":66,"name":"paul"},
{"votes":17,"name":"nopreference-r"},
{"votes":3,"name":"huckabee"},
{"votes":3,"name":"romney"}],
"total":386,"precincts":
{"total":1,"reporting":1},
"name":"Judith Basin"},
"Richland":
{"votes":[
{"votes":1011,"name":"mccain"},
{"votes":194,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":1211,"precincts":
{"total":1,"reporting":1},
"name":"Richland"},
"Glacier":
{"votes":[
{"votes":289,"name":"mccain"},
{"votes":55,"name":"paul"},
{"votes":14,"name":"nopreference-r"},
{"votes":5,"name":"huckabee"},
{"votes":3,"name":"romney"}],
"total":366,"precincts":
{"total":1,"reporting":1},
"name":"Glacier"},
"Silver Bow":
{"votes":[
{"votes":1757,"name":"mccain"},
{"votes":320,"name":"paul"},
{"votes":63,"name":"nopreference-r"},
{"votes":7,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":2152,"precincts":
{"total":1,"reporting":1},
"name":"Silver Bow"},
"Treasure":
{"votes":[
{"votes":109,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":143,"precincts":
{"total":1,"reporting":1},
"name":"Treasure"},
"Petroleum":
{"votes":[
{"votes":66,"name":"mccain"},
{"votes":22,"name":"paul"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"nopreference-r"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":96,"precincts":
{"total":1,"reporting":1},
"name":"Petroleum"},
"Lake":
{"votes":[
{"votes":2148,"name":"mccain"},
{"votes":1101,"name":"paul"},
{"votes":52,"name":"nopreference-r"},
{"votes":14,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":3318,"precincts":
{"total":1,"reporting":1},
"name":"Lake"},
"Liberty":
{"votes":[
{"votes":264,"name":"mccain"},
{"votes":78,"name":"paul"},
{"votes":19,"name":"nopreference-r"},
{"votes":5,"name":"romney"}],
"total":366,"precincts":
{"total":1,"reporting":1},
"name":"Liberty"},
"Phillips":
{"votes":[
{"votes":422,"name":"mccain"},
{"votes":48,"name":"paul"},
{"votes":11,"name":"nopreference-r"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"romney"}],
"total":486,"precincts":
{"total":1,"reporting":1},
"name":"Phillips"},
"Jefferson":
{"votes":[
{"votes":1134,"name":"mccain"},
{"votes":312,"name":"paul"},
{"votes":25,"name":"nopreference-r"},
{"votes":10,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":1486,"precincts":
{"total":1,"reporting":1},
"name":"Jefferson"},
"Hill":
{"votes":[
{"votes":548,"name":"mccain"},
{"votes":157,"name":"paul"},
{"votes":13,"name":"nopreference-r"},
{"votes":11,"name":"huckabee"},
{"votes":4,"name":"romney"}],
"total":733,"precincts":
{"total":1,"reporting":1},
"name":"Hill"},
"Daniels":
{"votes":[
{"votes":209,"name":"mccain"},
{"votes":71,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":7,"name":"nopreference-r"}],
"total":296,"precincts":
{"total":1,"reporting":1},
"name":"Daniels"},
"Granite":
{"votes":[
{"votes":347,"name":"mccain"},
{"votes":88,"name":"paul"},
{"votes":10,"name":"nopreference-r"},
{"votes":5,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":451,"precincts":
{"total":1,"reporting":1},
"name":"Granite"},
"Wibaux":
{"votes":[
{"votes":158,"name":"mccain"},
{"votes":95,"name":"paul"},
{"votes":15,"name":"nopreference-r"},
{"votes":1,"name":"huckabee"}],
"total":269,"precincts":
{"total":1,"reporting":1},
"name":"Wibaux"},
"Valley":
{"votes":[
{"votes":558,"name":"mccain"},
{"votes":148,"name":"paul"},
{"votes":13,"name":"nopreference-r"},
{"votes":3,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":723,"precincts":
{"total":1,"reporting":1},
"name":"Valley"},
"Lincoln":
{"votes":[
{"votes":1203,"name":"mccain"},
{"votes":445,"name":"paul"},
{"votes":102,"name":"nopreference-r"},
{"votes":17,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":1768,"precincts":
{"total":1,"reporting":1},
"name":"Lincoln"},
"Powell":
{"votes":[
{"votes":659,"name":"mccain"},
{"votes":154,"name":"paul"},
{"votes":27,"name":"nopreference-r"},
{"votes":14,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":856,"precincts":
{"total":1,"reporting":1},
"name":"Powell"},
"Golden Valley":
{"votes":[
{"votes":99,"name":"mccain"},
{"votes":52,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":4,"name":"nopreference-r"},
{"votes":2,"name":"huckabee"}],
"total":163,"precincts":
{"total":1,"reporting":1},
"name":"Golden Valley"},
"Powder River":
{"votes":[
{"votes":442,"name":"mccain"},
{"votes":118,"name":"paul"},
{"votes":18,"name":"nopreference-r"},
{"votes":7,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":587,"precincts":
{"total":1,"reporting":1},
"name":"Powder River"},
"Custer":
{"votes":[
{"votes":1005,"name":"mccain"},
{"votes":133,"name":"paul"},
{"votes":19,"name":"nopreference-r"},
{"votes":15,"name":"huckabee"},
{"votes":11,"name":"romney"}],
"total":1183,"precincts":
{"total":1,"reporting":1},
"name":"Custer"},
"Park":
{"votes":[
{"votes":1505,"name":"mccain"},
{"votes":626,"name":"paul"},
{"votes":37,"name":"nopreference-r"},
{"votes":6,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":2175,"precincts":
{"total":1,"reporting":1},
"name":"Park"},
"Garfield":
{"votes":[
{"votes":306,"name":"mccain"},
{"votes":49,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":5,"name":"huckabee"},
{"votes":4,"name":"nopreference-r"}],
"total":373,"precincts":
{"total":1,"reporting":1},
"name":"Garfield"},
"Chouteau":
{"votes":[
{"votes":860,"name":"mccain"},
{"votes":210,"name":"paul"},
{"votes":57,"name":"nopreference-r"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":1138,"precincts":
{"total":1,"reporting":1},
"name":"Chouteau"},
"Teton":
{"votes":[
{"votes":907,"name":"mccain"},
{"votes":207,"name":"paul"},
{"votes":63,"name":"nopreference-r"},
{"votes":16,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":1195,"precincts":
{"total":1,"reporting":1},
"name":"Teton"},
"Musselshell":
{"votes":[
{"votes":674,"name":"mccain"},
{"votes":203,"name":"paul"},
{"votes":37,"name":"nopreference-r"},
{"votes":13,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":930,"precincts":
{"total":1,"reporting":1},
"name":"Musselshell"},
"Prairie":
{"votes":[
{"votes":220,"name":"mccain"},
{"votes":59,"name":"paul"},
{"votes":14,"name":"nopreference-r"},
{"votes":8,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":303,"precincts":
{"total":1,"reporting":1},
"name":"Prairie"},
"Yellowstone":
{"votes":[
{"votes":9955,"name":"mccain"},
{"votes":1943,"name":"paul"},
{"votes":264,"name":"nopreference-r"},
{"votes":47,"name":"romney"},
{"votes":23,"name":"huckabee"}],
"total":12232,"precincts":
{"total":1,"reporting":1},
"name":"Yellowstone"},
"Meagher":
{"votes":[
{"votes":19,"name":"mccain"},
{"votes":4,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Meagher"},
"Carbon":
{"votes":[
{"votes":779,"name":"mccain"},
{"votes":228,"name":"paul"},
{"votes":26,"name":"nopreference-r"},
{"votes":21,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":1058,"precincts":
{"total":1,"reporting":1},
"name":"Carbon"},
"Stillwater":
{"votes":[
{"votes":966,"name":"mccain"},
{"votes":216,"name":"paul"},
{"votes":26,"name":"nopreference-r"},
{"votes":10,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":1222,"precincts":
{"total":1,"reporting":1},
"name":"Stillwater"},
"Flathead":
{"votes":[
{"votes":7792,"name":"mccain"},
{"votes":3674,"name":"paul"},
{"votes":130,"name":"nopreference-r"},
{"votes":36,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":11637,"precincts":
{"total":1,"reporting":1},
"name":"Flathead"},
"Sheridan":
{"votes":[
{"votes":198,"name":"mccain"},
{"votes":29,"name":"paul"},
{"votes":6,"name":"nopreference-r"},
{"votes":6,"name":"romney"}],
"total":239,"precincts":
{"total":1,"reporting":1},
"name":"Sheridan"},
"Broadwater":
{"votes":[
{"votes":730,"name":"mccain"},
{"votes":121,"name":"paul"},
{"votes":18,"name":"nopreference-r"},
{"votes":5,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":878,"precincts":
{"total":1,"reporting":1},
"name":"Broadwater"},
"Mineral":
{"votes":[
{"votes":292,"name":"mccain"},
{"votes":144,"name":"paul"},
{"votes":14,"name":"nopreference-r"},
{"votes":8,"name":"romney"}],
"total":458,"precincts":
{"total":1,"reporting":1},
"name":"Mineral"},
"Sanders":
{"votes":[
{"votes":1438,"name":"mccain"},
{"votes":650,"name":"paul"},
{"votes":73,"name":"nopreference-r"},
{"votes":9,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":2175,"precincts":
{"total":1,"reporting":1},
"name":"Sanders"},
"Fallon":
{"votes":[
{"votes":433,"name":"mccain"},
{"votes":103,"name":"paul"},
{"votes":36,"name":"nopreference-r"},
{"votes":13,"name":"romney"}],
"total":585,"precincts":
{"total":1,"reporting":1},
"name":"Fallon"},
"Fergus":
{"votes":[
{"votes":1438,"name":"mccain"},
{"votes":370,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":8,"name":"romney"}],
"total":1826,"precincts":
{"total":1,"reporting":1},
"name":"Fergus"},
"Big Horn":
{"votes":[
{"votes":437,"name":"mccain"},
{"votes":70,"name":"paul"},
{"votes":9,"name":"nopreference-r"},
{"votes":7,"name":"huckabee"},
{"votes":6,"name":"romney"}],
"total":529,"precincts":
{"total":1,"reporting":1},
"name":"Big Horn"},
"Ravalli":
{"votes":[
{"votes":4492,"name":"mccain"},
{"votes":1327,"name":"paul"},
{"votes":172,"name":"nopreference-r"},
{"votes":32,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":6027,"precincts":
{"total":1,"reporting":1},
"name":"Ravalli"},
"Missoula":
{"votes":[
{"votes":4127,"name":"mccain"},
{"votes":1215,"name":"paul"},
{"votes":76,"name":"nopreference-r"},
{"votes":42,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":5463,"precincts":
{"total":1,"reporting":1},
"name":"Missoula"},
"Cascade":
{"votes":[
{"votes":4853,"name":"mccain"},
{"votes":847,"name":"paul"},
{"votes":95,"name":"nopreference-r"},
{"votes":15,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":5815,"precincts":
{"total":1,"reporting":1},
"name":"Cascade"},
"Roosevelt":
{"votes":[
{"votes":369,"name":"mccain"},
{"votes":85,"name":"paul"},
{"votes":12,"name":"nopreference-r"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"romney"}],
"total":469,"precincts":
{"total":1,"reporting":1},
"name":"Roosevelt"},
"McCone":
{"votes":[
{"votes":224,"name":"mccain"},
{"votes":83,"name":"paul"},
{"votes":6,"name":"huckabee"},
{"votes":4,"name":"romney"}],
"total":317,"precincts":
{"total":1,"reporting":1},
"name":"McCone"},
"Madison":
{"votes":[
{"votes":1099,"name":"mccain"},
{"votes":211,"name":"paul"},
{"votes":30,"name":"nopreference-r"},
{"votes":3,"name":"romney"}],
"total":1343,"precincts":
{"total":1,"reporting":1},
"name":"Madison"},
"Beaverhead":
{"votes":[
{"votes":1370,"name":"mccain"},
{"votes":280,"name":"paul"},
{"votes":15,"name":"romney"},
{"votes":6,"name":"huckabee"}],
"total":1671,"precincts":
{"total":1,"reporting":1},
"name":"Beaverhead"},
"Carter":
{"votes":[
{"votes":215,"name":"mccain"},
{"votes":86,"name":"paul"},
{"votes":14,"name":"huckabee"},
{"votes":13,"name":"nopreference-r"}],
"total":328,"precincts":
{"total":1,"reporting":1},
"name":"Carter"},
"Sweet Grass":
{"votes":[
{"votes":588,"name":"mccain"},
{"votes":140,"name":"paul"},
{"votes":12,"name":"huckabee"},
{"votes":11,"name":"nopreference-r"},
{"votes":2,"name":"romney"}],
"total":753,"precincts":
{"total":1,"reporting":1},
"name":"Sweet Grass"},
"Pondera":
{"votes":[
{"votes":654,"name":"mccain"},
{"votes":124,"name":"paul"},
{"votes":30,"name":"nopreference-r"},
{"votes":15,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":827,"precincts":
{"total":1,"reporting":1},
"name":"Pondera"},
"Lewis & Clark":
{"votes":[
{"votes":4387,"name":"mccain"},
{"votes":876,"name":"paul"},
{"votes":117,"name":"nopreference-r"},
{"votes":36,"name":"romney"},
{"votes":10,"name":"huckabee"}],
"total":5426,"precincts":
{"total":1,"reporting":1},
"name":"Lewis & Clark"},
"Deer Lodge":
{"votes":[
{"votes":374,"name":"mccain"},
{"votes":57,"name":"paul"},
{"votes":9,"name":"nopreference-r"},
{"votes":3,"name":"huckabee"}],
"total":443,"precincts":
{"total":1,"reporting":1},
"name":"Deer Lodge"},
"Rosebud":
{"votes":[
{"votes":408,"name":"mccain"},
{"votes":90,"name":"paul"},
{"votes":7,"name":"nopreference-r"},
{"votes":6,"name":"romney"}],
"total":511,"precincts":
{"total":1,"reporting":1},
"name":"Rosebud"},
"Wheatland":
{"votes":[
{"votes":197,"name":"mccain"},
{"votes":53,"name":"paul"},
{"votes":18,"name":"romney"},
{"votes":7,"name":"nopreference-r"},
{"votes":3,"name":"huckabee"}],
"total":278,"precincts":
{"total":1,"reporting":1},
"name":"Wheatland"},
"Blaine":
{"votes":[
{"votes":308,"name":"mccain"},
{"votes":89,"name":"paul"},
{"votes":11,"name":"nopreference-r"},
{"votes":5,"name":"huckabee"},
{"votes":3,"name":"romney"}],
"total":416,"precincts":
{"total":1,"reporting":1},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":946,"name":"mccain"},
{"votes":269,"name":"paul"},
{"votes":44,"name":"nopreference-r"},
{"votes":11,"name":"romney"},
{"votes":8,"name":"huckabee"},
{"votes":1,"name":"keyes"}],
"total":1279,"precincts":
{"total":1,"reporting":1},
"name":"Dawson"},
"Toole":
{"votes":[
{"votes":398,"name":"mccain"},
{"votes":95,"name":"paul"},
{"votes":16,"name":"nopreference-r"},
{"votes":10,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":520,"precincts":
{"total":1,"reporting":1},
"name":"Toole"},
"Gallatin":
{"votes":[
{"votes":4798,"name":"mccain"},
{"votes":1479,"name":"paul"},
{"votes":124,"name":"nopreference-r"},
{"votes":47,"name":"romney"},
{"votes":11,"name":"huckabee"}],
"total":6459,"precincts":
{"total":1,"reporting":1},
"name":"Gallatin"}}})