GoogleElectionMap.votesReady({"status":"ok","totals":
{"name":"Montana","precincts":
{"total":56,"reporting":56},
"votes":[
{"votes":10962,"name":"mccain"},
{"votes":2087,"name":"paul"},
{"votes":625,"name":"romney","delegates":25},
{"votes":256,"name":"nopreference-r"},
{"votes":245,"name":"huckabee"},
{"votes":2,"name":"keyes"}],
"delegates":25,"date":"02-05","type":"caucus"},
"state":"MT","party":"gop","total":14177,"locals":
{"Judith Basin":
{"votes":[
{"votes":5,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"mccain"}],
"total":13,"precincts":
{"total":1,"reporting":1},
"name":"Judith Basin"},
"Richland":
{"votes":[
{"votes":14,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"mccain"}],
"total":22,"precincts":
{"total":1,"reporting":1},
"name":"Richland"},
"Glacier":
{"votes":[
{"votes":7,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":16,"precincts":
{"total":1,"reporting":1},
"name":"Glacier"},
"Silver Bow":
{"votes":[
{"votes":7,"name":"romney"},
{"votes":5,"name":"huckabee"},
{"votes":4,"name":"mccain"},
{"votes":3,"name":"paul"}],
"total":19,"precincts":
{"total":1,"reporting":1},
"name":"Silver Bow"},
"Treasure":
{"votes":[
{"votes":13,"name":"mccain"},
{"votes":8,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":23,"precincts":
{"total":1,"reporting":1},
"name":"Treasure"},
"Petroleum":
{"votes":[
{"votes":66,"name":"mccain"},
{"votes":22,"name":"paul"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"nopreference-r"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":96,"precincts":
{"total":1,"reporting":1},
"name":"Petroleum"},
"Lake":
{"votes":[
{"votes":18,"name":"paul"},
{"votes":14,"name":"romney"},
{"votes":8,"name":"mccain"},
{"votes":3,"name":"huckabee"}],
"total":43,"precincts":
{"total":1,"reporting":1},
"name":"Lake"},
"Liberty":
{"votes":[
{"votes":5,"name":"romney"},
{"votes":5,"name":"mccain"}],
"total":10,"precincts":
{"total":1,"reporting":1},
"name":"Liberty"},
"Phillips":
{"votes":[
{"votes":9,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":15,"precincts":
{"total":1,"reporting":1},
"name":"Phillips"},
"Jefferson":
{"votes":[
{"votes":218,"name":"mccain"},
{"votes":64,"name":"paul"},
{"votes":10,"name":"romney"},
{"votes":5,"name":"huckabee"},
{"votes":3,"name":"nopreference-r"}],
"total":300,"precincts":
{"total":1,"reporting":1},
"name":"Jefferson"},
"Hill":
{"votes":[
{"votes":11,"name":"huckabee"},
{"votes":9,"name":"mccain"},
{"votes":6,"name":"paul"},
{"votes":4,"name":"romney"}],
"total":30,"precincts":
{"total":1,"reporting":1},
"name":"Hill"},
"Daniels":
{"votes":[
{"votes":52,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":2,"name":"nopreference-r"}],
"total":87,"precincts":
{"total":1,"reporting":1},
"name":"Daniels"},
"Granite":
{"votes":[
{"votes":8,"name":"mccain"},
{"votes":5,"name":"romney"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"huckabee"}],
"total":17,"precincts":
{"total":1,"reporting":1},
"name":"Granite"},
"Wibaux":
{"votes":[
{"votes":12,"name":"paul"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"mccain"}],
"total":14,"precincts":
{"total":1,"reporting":1},
"name":"Wibaux"},
"Valley":
{"votes":[
{"votes":97,"name":"mccain"},
{"votes":20,"name":"paul"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"nopreference-r"},
{"votes":1,"name":"huckabee"}],
"total":123,"precincts":
{"total":1,"reporting":1},
"name":"Valley"},
"Lincoln":
{"votes":[
{"votes":17,"name":"romney"},
{"votes":14,"name":"paul"},
{"votes":1,"name":"huckabee"}],
"total":32,"precincts":
{"total":1,"reporting":1},
"name":"Lincoln"},
"Powell":
{"votes":[
{"votes":14,"name":"romney"},
{"votes":8,"name":"mccain"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"huckabee"}],
"total":27,"precincts":
{"total":1,"reporting":1},
"name":"Powell"},
"Golden Valley":
{"votes":[
{"votes":6,"name":"romney"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"mccain"}],
"total":12,"precincts":
{"total":1,"reporting":1},
"name":"Golden Valley"},
"Powder River":
{"votes":[
{"votes":7,"name":"romney"},
{"votes":4,"name":"paul"},
{"votes":3,"name":"mccain"},
{"votes":2,"name":"huckabee"}],
"total":16,"precincts":
{"total":1,"reporting":1},
"name":"Powder River"},
"Custer":
{"votes":[
{"votes":15,"name":"huckabee"},
{"votes":11,"name":"romney"},
{"votes":11,"name":"mccain"},
{"votes":2,"name":"paul"}],
"total":39,"precincts":
{"total":1,"reporting":1},
"name":"Custer"},
"Park":
{"votes":[
{"votes":6,"name":"romney"},
{"votes":6,"name":"mccain"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"huckabee"}],
"total":15,"precincts":
{"total":1,"reporting":1},
"name":"Park"},
"Garfield":
{"votes":[
{"votes":9,"name":"romney"},
{"votes":9,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":1,"name":"paul"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Garfield"},
"Chouteau":
{"votes":[
{"votes":72,"name":"mccain"},
{"votes":15,"name":"paul"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"huckabee"},
{"votes":1,"name":"nopreference-r"}],
"total":99,"precincts":
{"total":1,"reporting":1},
"name":"Chouteau"},
"Teton":
{"votes":[
{"votes":16,"name":"romney"},
{"votes":5,"name":"mccain"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"huckabee"}],
"total":26,"precincts":
{"total":1,"reporting":1},
"name":"Teton"},
"Musselshell":
{"votes":[
{"votes":603,"name":"mccain"},
{"votes":179,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":798,"precincts":
{"total":1,"reporting":1},
"name":"Musselshell"},
"Prairie":
{"votes":[
{"votes":8,"name":"romney"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"mccain"}],
"total":12,"precincts":
{"total":1,"reporting":1},
"name":"Prairie"},
"Yellowstone":
{"votes":[
{"votes":5178,"name":"mccain"},
{"votes":766,"name":"paul"},
{"votes":143,"name":"nopreference-r"},
{"votes":47,"name":"romney"},
{"votes":23,"name":"huckabee"}],
"total":6157,"precincts":
{"total":1,"reporting":1},
"name":"Yellowstone"},
"Meagher":
{"votes":[
{"votes":19,"name":"mccain"},
{"votes":4,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Meagher"},
"Carbon":
{"votes":[
{"votes":21,"name":"romney"},
{"votes":10,"name":"mccain"},
{"votes":4,"name":"huckabee"},
{"votes":1,"name":"paul"}],
"total":36,"precincts":
{"total":1,"reporting":1},
"name":"Carbon"},
"Stillwater":
{"votes":[
{"votes":10,"name":"romney"},
{"votes":9,"name":"mccain"},
{"votes":5,"name":"paul"},
{"votes":4,"name":"huckabee"}],
"total":28,"precincts":
{"total":1,"reporting":1},
"name":"Stillwater"},
"Flathead":
{"votes":[
{"votes":1632,"name":"mccain"},
{"votes":459,"name":"paul"},
{"votes":46,"name":"nopreference-r"},
{"votes":36,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":2178,"precincts":
{"total":1,"reporting":1},
"name":"Flathead"},
"Sheridan":
{"votes":[
{"votes":8,"name":"mccain"},
{"votes":6,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":15,"precincts":
{"total":1,"reporting":1},
"name":"Sheridan"},
"Broadwater":
{"votes":[
{"votes":5,"name":"romney"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"paul"},
{"votes":2,"name":"mccain"}],
"total":13,"precincts":
{"total":1,"reporting":1},
"name":"Broadwater"},
"Mineral":
{"votes":[
{"votes":8,"name":"romney"},
{"votes":4,"name":"paul"},
{"votes":2,"name":"mccain"}],
"total":14,"precincts":
{"total":1,"reporting":1},
"name":"Mineral"},
"Sanders":
{"votes":[
{"votes":12,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":5,"name":"huckabee"},
{"votes":3,"name":"mccain"}],
"total":29,"precincts":
{"total":1,"reporting":1},
"name":"Sanders"},
"Fallon":
{"votes":[
{"votes":13,"name":"romney"},
{"votes":8,"name":"paul"},
{"votes":6,"name":"mccain"}],
"total":27,"precincts":
{"total":1,"reporting":1},
"name":"Fallon"},
"Fergus":
{"votes":[
{"votes":11,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":6,"name":"mccain"}],
"total":35,"precincts":
{"total":1,"reporting":1},
"name":"Fergus"},
"Big Horn":
{"votes":[
{"votes":164,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":4,"name":"paul"},
{"votes":1,"name":"nopreference-r"}],
"total":182,"precincts":
{"total":1,"reporting":1},
"name":"Big Horn"},
"Ravalli":
{"votes":[
{"votes":32,"name":"romney"},
{"votes":8,"name":"mccain"},
{"votes":4,"name":"huckabee"},
{"votes":4,"name":"paul"}],
"total":48,"precincts":
{"total":1,"reporting":1},
"name":"Ravalli"},
"Missoula":
{"votes":[
{"votes":860,"name":"mccain"},
{"votes":175,"name":"paul"},
{"votes":42,"name":"romney"},
{"votes":14,"name":"nopreference-r"},
{"votes":3,"name":"huckabee"}],
"total":1094,"precincts":
{"total":1,"reporting":1},
"name":"Missoula"},
"Cascade":
{"votes":[
{"votes":15,"name":"romney"},
{"votes":8,"name":"paul"},
{"votes":7,"name":"mccain"},
{"votes":5,"name":"huckabee"}],
"total":35,"precincts":
{"total":1,"reporting":1},
"name":"Cascade"},
"Roosevelt":
{"votes":[
{"votes":9,"name":"paul"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"mccain"}],
"total":13,"precincts":
{"total":1,"reporting":1},
"name":"Roosevelt"},
"McCone":
{"votes":[
{"votes":6,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":4,"name":"mccain"}],
"total":20,"precincts":
{"total":1,"reporting":1},
"name":"McCone"},
"Madison":
{"votes":[
{"votes":20,"name":"paul"},
{"votes":3,"name":"romney"}],
"total":23,"precincts":
{"total":1,"reporting":1},
"name":"Madison"},
"Beaverhead":
{"votes":[
{"votes":15,"name":"romney"},
{"votes":8,"name":"mccain"},
{"votes":7,"name":"paul"},
{"votes":6,"name":"huckabee"}],
"total":36,"precincts":
{"total":1,"reporting":1},
"name":"Beaverhead"},
"Carter":
{"votes":[
{"votes":14,"name":"huckabee"},
{"votes":4,"name":"mccain"}],
"total":18,"precincts":
{"total":1,"reporting":1},
"name":"Carter"},
"Sweet Grass":
{"votes":[
{"votes":297,"name":"mccain"},
{"votes":70,"name":"paul"},
{"votes":12,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"nopreference-r"}],
"total":382,"precincts":
{"total":1,"reporting":1},
"name":"Sweet Grass"},
"Pondera":
{"votes":[
{"votes":15,"name":"romney"},
{"votes":9,"name":"mccain"},
{"votes":4,"name":"huckabee"}],
"total":28,"precincts":
{"total":1,"reporting":1},
"name":"Pondera"},
"Lewis & Clark":
{"votes":[
{"votes":1529,"name":"mccain"},
{"votes":262,"name":"paul"},
{"votes":36,"name":"romney"},
{"votes":35,"name":"nopreference-r"},
{"votes":10,"name":"huckabee"}],
"total":1872,"precincts":
{"total":1,"reporting":1},
"name":"Lewis & Clark"},
"Deer Lodge":
{"votes":[
{"votes":194,"name":"mccain"},
{"votes":27,"name":"paul"},
{"votes":6,"name":"nopreference-r"},
{"votes":3,"name":"huckabee"}],
"total":230,"precincts":
{"total":1,"reporting":1},
"name":"Deer Lodge"},
"Rosebud":
{"votes":[
{"votes":17,"name":"mccain"},
{"votes":6,"name":"romney"},
{"votes":2,"name":"paul"}],
"total":25,"precincts":
{"total":1,"reporting":1},
"name":"Rosebud"},
"Wheatland":
{"votes":[
{"votes":18,"name":"romney"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"paul"},
{"votes":1,"name":"mccain"}],
"total":23,"precincts":
{"total":1,"reporting":1},
"name":"Wheatland"},
"Blaine":
{"votes":[
{"votes":12,"name":"paul"},
{"votes":6,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":3,"name":"romney"}],
"total":26,"precincts":
{"total":1,"reporting":1},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":12,"name":"paul"},
{"votes":11,"name":"romney"},
{"votes":8,"name":"huckabee"},
{"votes":3,"name":"mccain"},
{"votes":1,"name":"keyes"}],
"total":35,"precincts":
{"total":1,"reporting":1},
"name":"Dawson"},
"Toole":
{"votes":[
{"votes":10,"name":"romney"},
{"votes":9,"name":"mccain"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"paul"}],
"total":21,"precincts":
{"total":1,"reporting":1},
"name":"Toole"},
"Gallatin":
{"votes":[
{"votes":47,"name":"romney"},
{"votes":28,"name":"paul"},
{"votes":14,"name":"mccain"},
{"votes":11,"name":"huckabee"}],
"total":100,"precincts":
{"total":1,"reporting":1},
"name":"Gallatin"}}})