GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":187725,"name":"obama","delegates":50},
{"votes":99786,"name":"clinton","delegates":42},
{"votes":3091,"name":"nopreference-d"},
{"votes":1595,"name":"gravel"}],
"name":"North Carolina","precincts":
{"total":2817,"reporting":261},
"delegates":115,"date":"05-06"},
"state":"NC","party":"dem","total":292197,"locals":
{"Bladen":
{"votes":[
{"votes":1364,"name":"clinton"},
{"votes":1227,"name":"obama"},
{"votes":109,"name":"nopreference-d"},
{"votes":56,"name":"gravel"}],
"total":2756,"precincts":
{"total":17,"reporting":1},
"name":"Bladen"},
"Currituck":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Currituck"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":49,"reporting":0},
"name":"Union"},
"Wilson":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Wilson"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Wayne"},
"Robeson":
{"votes":[
{"votes":2762,"name":"obama"},
{"votes":1851,"name":"clinton"},
{"votes":62,"name":"gravel"}],
"total":4675,"precincts":
{"total":41,"reporting":0},
"name":"Robeson"},
"Brunswick":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Brunswick"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Henderson"},
"Cherokee":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Cherokee"},
"Anson":
{"votes":[
{"votes":1104,"name":"obama"},
{"votes":487,"name":"clinton"},
{"votes":24,"name":"nopreference-d"},
{"votes":8,"name":"gravel"}],
"total":1623,"precincts":
{"total":11,"reporting":1},
"name":"Anson"},
"Catawba":
{"votes":[],
"total":0,"precincts":
{"total":41,"reporting":0},
"name":"Catawba"},
"Yadkin":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Yadkin"},
"Stokes":
{"votes":[
{"votes":439,"name":"clinton"},
{"votes":257,"name":"obama"},
{"votes":12,"name":"nopreference-d"},
{"votes":1,"name":"gravel"}],
"total":709,"precincts":
{"total":23,"reporting":1},
"name":"Stokes"},
"Pasquotank":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pasquotank"},
"Hoke":
{"votes":[
{"votes":1312,"name":"obama"},
{"votes":551,"name":"clinton"},
{"votes":38,"name":"nopreference-d"},
{"votes":21,"name":"gravel"}],
"total":1922,"precincts":
{"total":13,"reporting":1},
"name":"Hoke"},
"Wilkes":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Wilkes"},
"Alamance":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Alamance"},
"Moore":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Moore"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Washington"},
"Duplin":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Duplin"},
"Cabarrus":
{"votes":[
{"votes":1807,"name":"obama"},
{"votes":1381,"name":"clinton"},
{"votes":25,"name":"nopreference-d"},
{"votes":10,"name":"gravel"}],
"total":3223,"precincts":
{"total":49,"reporting":1},
"name":"Cabarrus"},
"Camden":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Camden"},
"New Hanover":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"New Hanover"},
"Polk":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Polk"},
"Warren":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Warren"},
"Watauga":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Watauga"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Jackson"},
"Transylvania":
{"votes":[
{"votes":1236,"name":"clinton"},
{"votes":1152,"name":"obama"},
{"votes":17,"name":"gravel"},
{"votes":1,"name":"nopreference-d"}],
"total":2406,"precincts":
{"total":18,"reporting":1},
"name":"Transylvania"},
"Caldwell":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Caldwell"},
"Onslow":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Onslow"},
"Granville":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":12790,"name":"obama"},
{"votes":3678,"name":"clinton"},
{"votes":111,"name":"nopreference-d"},
{"votes":71,"name":"gravel"}],
"total":16650,"precincts":
{"total":44,"reporting":1},
"name":"Orange"},
"Burke":
{"votes":[],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Burke"},
"Lee":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Lee"},
"Avery":
{"votes":[
{"votes":109,"name":"clinton"},
{"votes":81,"name":"obama"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"nopreference-d"}],
"total":193,"precincts":
{"total":20,"reporting":1},
"name":"Avery"},
"Buncombe":
{"votes":[],
"total":0,"precincts":
{"total":78,"reporting":0},
"name":"Buncombe"},
"Guilford":
{"votes":[
{"votes":18212,"name":"obama"},
{"votes":7149,"name":"clinton"},
{"votes":307,"name":"nopreference-d"},
{"votes":133,"name":"gravel"}],
"total":25801,"precincts":
{"total":163,"reporting":0},
"name":"Guilford"},
"Durham":
{"votes":[
{"votes":39202,"name":"obama"},
{"votes":13231,"name":"clinton"},
{"votes":615,"name":"nopreference-d"},
{"votes":206,"name":"gravel"}],
"total":53254,"precincts":
{"total":61,"reporting":42},
"name":"Durham"},
"Wake":
{"votes":[
{"votes":51039,"name":"obama"},
{"votes":34851,"name":"clinton"},
{"votes":736,"name":"nopreference-d"},
{"votes":378,"name":"gravel"}],
"total":87004,"precincts":
{"total":210,"reporting":143},
"name":"Wake"},
"Chatham":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Chatham"},
"Beaufort":
{"votes":[
{"votes":1062,"name":"obama"},
{"votes":720,"name":"clinton"},
{"votes":42,"name":"nopreference-d"},
{"votes":35,"name":"gravel"}],
"total":1859,"precincts":
{"total":23,"reporting":1},
"name":"Beaufort"},
"Vance":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Vance"},
"Rutherford":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Rutherford"},
"Harnett":
{"votes":[
{"votes":4560,"name":"clinton"},
{"votes":4431,"name":"obama"},
{"votes":127,"name":"nopreference-d"},
{"votes":104,"name":"gravel"}],
"total":9222,"precincts":
{"total":18,"reporting":12},
"name":"Harnett"},
"Davie":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Davie"},
"Greene":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Greene"},
"Pender":
{"votes":[
{"votes":1120,"name":"obama"},
{"votes":1022,"name":"clinton"},
{"votes":36,"name":"nopreference-d"},
{"votes":18,"name":"gravel"}],
"total":2196,"precincts":
{"total":20,"reporting":0},
"name":"Pender"},
"Forsyth":
{"votes":[],
"total":0,"precincts":
{"total":101,"reporting":0},
"name":"Forsyth"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Clay"},
"Macon":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Macon"},
"Chowan":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Chowan"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Madison"},
"Gaston":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Gaston"},
"Northampton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Northampton"},
"Swain":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Swain"},
"Hyde":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Hyde"},
"Stanly":
{"votes":[
{"votes":932,"name":"clinton"},
{"votes":509,"name":"obama"},
{"votes":35,"name":"nopreference-d"},
{"votes":17,"name":"gravel"}],
"total":1493,"precincts":
{"total":24,"reporting":0},
"name":"Stanly"},
"Graham":
{"votes":[
{"votes":286,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":10,"name":"nopreference-d"},
{"votes":3,"name":"gravel"}],
"total":341,"precincts":
{"total":4,"reporting":0},
"name":"Graham"},
"Lenoir":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lenoir"},
"Hertford":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Hertford"},
"Scotland":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Scotland"},
"Richmond":
{"votes":[
{"votes":1239,"name":"clinton"},
{"votes":1043,"name":"obama"},
{"votes":134,"name":"nopreference-d"},
{"votes":63,"name":"gravel"}],
"total":2479,"precincts":
{"total":16,"reporting":1},
"name":"Richmond"},
"Davidson":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Davidson"},
"Columbus":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Columbus"},
"Mitchell":
{"votes":[
{"votes":35,"name":"clinton"},
{"votes":29,"name":"obama"},
{"votes":1,"name":"nopreference-d"}],
"total":65,"precincts":
{"total":9,"reporting":3},
"name":"Mitchell"},
"Bertie":
{"votes":[
{"votes":1667,"name":"obama"},
{"votes":676,"name":"clinton"},
{"votes":39,"name":"nopreference-d"},
{"votes":17,"name":"gravel"}],
"total":2399,"precincts":
{"total":12,"reporting":4},
"name":"Bertie"},
"Alexander":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Alexander"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Lincoln"},
"Sampson":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Sampson"},
"Edgecombe":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Edgecombe"},
"Ashe":
{"votes":[
{"votes":738,"name":"clinton"},
{"votes":275,"name":"obama"},
{"votes":18,"name":"nopreference-d"},
{"votes":5,"name":"gravel"}],
"total":1036,"precincts":
{"total":17,"reporting":3},
"name":"Ashe"},
"Craven":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Craven"},
"Iredell":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Iredell"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Franklin"},
"Carteret":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Carteret"},
"Johnston":
{"votes":[
{"votes":229,"name":"obama"},
{"votes":224,"name":"clinton"},
{"votes":6,"name":"nopreference-d"},
{"votes":6,"name":"gravel"}],
"total":465,"precincts":
{"total":37,"reporting":1},
"name":"Johnston"},
"Nash":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Nash"},
"Tyrrell":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Tyrrell"},
"Caswell":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Caswell"},
"Cleveland":
{"votes":[
{"votes":1913,"name":"obama"},
{"votes":1306,"name":"clinton"},
{"votes":42,"name":"nopreference-d"},
{"votes":11,"name":"gravel"}],
"total":3272,"precincts":
{"total":28,"reporting":1},
"name":"Cleveland"},
"Halifax":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Halifax"},
"Cumberland":
{"votes":[
{"votes":11034,"name":"obama"},
{"votes":3745,"name":"clinton"},
{"votes":159,"name":"nopreference-d"},
{"votes":87,"name":"gravel"}],
"total":15025,"precincts":
{"total":69,"reporting":1},
"name":"Cumberland"},
"Rockingham":
{"votes":[
{"votes":1515,"name":"obama"},
{"votes":1266,"name":"clinton"},
{"votes":91,"name":"nopreference-d"},
{"votes":49,"name":"gravel"}],
"total":2921,"precincts":
{"total":20,"reporting":4},
"name":"Rockingham"},
"Rowan":
{"votes":[],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Rowan"},
"Alleghany":
{"votes":[
{"votes":640,"name":"clinton"},
{"votes":208,"name":"obama"},
{"votes":25,"name":"nopreference-d"},
{"votes":6,"name":"gravel"}],
"total":879,"precincts":
{"total":7,"reporting":0},
"name":"Alleghany"},
"McDowell":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"McDowell"},
"Haywood":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Haywood"},
"Pamlico":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Pamlico"},
"Dare":
{"votes":[
{"votes":683,"name":"clinton"},
{"votes":662,"name":"obama"},
{"votes":36,"name":"nopreference-d"},
{"votes":13,"name":"gravel"}],
"total":1394,"precincts":
{"total":16,"reporting":1},
"name":"Dare"},
"Jones":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Jones"},
"Pitt":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Pitt"},
"Martin":
{"votes":[
{"votes":959,"name":"obama"},
{"votes":458,"name":"clinton"},
{"votes":38,"name":"nopreference-d"},
{"votes":13,"name":"gravel"}],
"total":1468,"precincts":
{"total":13,"reporting":1},
"name":"Martin"},
"Mecklenburg":
{"votes":[
{"votes":27509,"name":"obama"},
{"votes":10030,"name":"clinton"},
{"votes":130,"name":"nopreference-d"},
{"votes":75,"name":"gravel"}],
"total":37744,"precincts":
{"total":198,"reporting":1},
"name":"Mecklenburg"},
"Gates":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Gates"},
"Person":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Person"},
"Yancey":
{"votes":[
{"votes":104,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":9,"name":"nopreference-d"},
{"votes":2,"name":"gravel"}],
"total":157,"precincts":
{"total":11,"reporting":2},
"name":"Yancey"},
"Surry":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Surry"},
"Perquimans":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Perquimans"},
"Randolph":
{"votes":[
{"votes":4795,"name":"clinton"},
{"votes":2531,"name":"obama"},
{"votes":134,"name":"nopreference-d"},
{"votes":106,"name":"gravel"}],
"total":7566,"precincts":
{"total":42,"reporting":32},
"name":"Randolph"}}})