GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":519946,"name":"obama","delegates":50},
{"votes":366610,"name":"clinton","delegates":42},
{"votes":11655,"name":"nopreference-d"},
{"votes":6428,"name":"gravel"}],
"name":"North Carolina","precincts":
{"total":2817,"reporting":1269},
"delegates":115,"date":"05-06"},
"state":"NC","party":"dem","total":904639,"locals":
{"Bladen":
{"votes":[
{"votes":4270,"name":"clinton"},
{"votes":4146,"name":"obama"},
{"votes":284,"name":"nopreference-d"},
{"votes":151,"name":"gravel"}],
"total":8851,"precincts":
{"total":17,"reporting":17},
"name":"Bladen"},
"Currituck":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Currituck"},
"Union":
{"votes":[
{"votes":6044,"name":"obama"},
{"votes":5884,"name":"clinton"},
{"votes":125,"name":"nopreference-d"},
{"votes":75,"name":"gravel"}],
"total":12128,"precincts":
{"total":49,"reporting":25},
"name":"Union"},
"Wilson":
{"votes":[
{"votes":3259,"name":"obama"},
{"votes":1347,"name":"clinton"},
{"votes":61,"name":"nopreference-d"},
{"votes":43,"name":"gravel"}],
"total":4710,"precincts":
{"total":25,"reporting":0},
"name":"Wilson"},
"Montgomery":
{"votes":[
{"votes":1477,"name":"clinton"},
{"votes":972,"name":"obama"},
{"votes":74,"name":"nopreference-d"},
{"votes":60,"name":"gravel"}],
"total":2583,"precincts":
{"total":14,"reporting":6},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":6028,"name":"obama"},
{"votes":2814,"name":"clinton"},
{"votes":235,"name":"nopreference-d"},
{"votes":69,"name":"gravel"}],
"total":9146,"precincts":
{"total":30,"reporting":10},
"name":"Wayne"},
"Robeson":
{"votes":[
{"votes":6551,"name":"obama"},
{"votes":6487,"name":"clinton"},
{"votes":416,"name":"nopreference-d"},
{"votes":184,"name":"gravel"}],
"total":13638,"precincts":
{"total":41,"reporting":22},
"name":"Robeson"},
"Brunswick":
{"votes":[
{"votes":3975,"name":"clinton"},
{"votes":3203,"name":"obama"},
{"votes":86,"name":"nopreference-d"},
{"votes":82,"name":"gravel"}],
"total":7346,"precincts":
{"total":23,"reporting":6},
"name":"Brunswick"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Henderson"},
"Cherokee":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Cherokee"},
"Anson":
{"votes":[
{"votes":2533,"name":"obama"},
{"votes":1881,"name":"clinton"},
{"votes":74,"name":"nopreference-d"},
{"votes":35,"name":"gravel"}],
"total":4523,"precincts":
{"total":11,"reporting":8},
"name":"Anson"},
"Catawba":
{"votes":[
{"votes":9492,"name":"clinton"},
{"votes":7143,"name":"obama"},
{"votes":183,"name":"nopreference-d"},
{"votes":103,"name":"gravel"}],
"total":16921,"precincts":
{"total":41,"reporting":40},
"name":"Catawba"},
"Yadkin":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Yadkin"},
"Stokes":
{"votes":[
{"votes":1791,"name":"clinton"},
{"votes":823,"name":"obama"},
{"votes":46,"name":"nopreference-d"},
{"votes":22,"name":"gravel"}],
"total":2682,"precincts":
{"total":23,"reporting":8},
"name":"Stokes"},
"Pasquotank":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pasquotank"},
"Hoke":
{"votes":[
{"votes":2710,"name":"obama"},
{"votes":1404,"name":"clinton"},
{"votes":81,"name":"nopreference-d"},
{"votes":38,"name":"gravel"}],
"total":4233,"precincts":
{"total":13,"reporting":9},
"name":"Hoke"},
"Wilkes":
{"votes":[
{"votes":5053,"name":"clinton"},
{"votes":1880,"name":"obama"},
{"votes":106,"name":"nopreference-d"},
{"votes":66,"name":"gravel"}],
"total":7105,"precincts":
{"total":28,"reporting":1},
"name":"Wilkes"},
"Alamance":
{"votes":[
{"votes":7912,"name":"obama"},
{"votes":6296,"name":"clinton"},
{"votes":290,"name":"nopreference-d"},
{"votes":162,"name":"gravel"}],
"total":14660,"precincts":
{"total":37,"reporting":26},
"name":"Alamance"},
"Moore":
{"votes":[
{"votes":3956,"name":"obama"},
{"votes":3288,"name":"clinton"},
{"votes":102,"name":"nopreference-d"},
{"votes":57,"name":"gravel"}],
"total":7403,"precincts":
{"total":24,"reporting":12},
"name":"Moore"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Washington"},
"Duplin":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Duplin"},
"Cabarrus":
{"votes":[
{"votes":2977,"name":"obama"},
{"votes":2406,"name":"clinton"},
{"votes":60,"name":"nopreference-d"},
{"votes":30,"name":"gravel"}],
"total":5473,"precincts":
{"total":49,"reporting":6},
"name":"Cabarrus"},
"Camden":
{"votes":[
{"votes":854,"name":"clinton"},
{"votes":648,"name":"obama"},
{"votes":52,"name":"nopreference-d"},
{"votes":28,"name":"gravel"}],
"total":1582,"precincts":
{"total":3,"reporting":3},
"name":"Camden"},
"New Hanover":
{"votes":[
{"votes":8944,"name":"obama"},
{"votes":5871,"name":"clinton"},
{"votes":162,"name":"nopreference-d"},
{"votes":74,"name":"gravel"}],
"total":15051,"precincts":
{"total":43,"reporting":17},
"name":"New Hanover"},
"Polk":
{"votes":[
{"votes":730,"name":"clinton"},
{"votes":707,"name":"obama"},
{"votes":16,"name":"nopreference-d"},
{"votes":13,"name":"gravel"}],
"total":1466,"precincts":
{"total":7,"reporting":1},
"name":"Polk"},
"Warren":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Warren"},
"Watauga":
{"votes":[
{"votes":2952,"name":"obama"},
{"votes":2176,"name":"clinton"},
{"votes":35,"name":"nopreference-d"},
{"votes":17,"name":"gravel"}],
"total":5180,"precincts":
{"total":20,"reporting":10},
"name":"Watauga"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Jackson"},
"Transylvania":
{"votes":[
{"votes":1726,"name":"clinton"},
{"votes":1562,"name":"obama"},
{"votes":52,"name":"nopreference-d"},
{"votes":24,"name":"gravel"}],
"total":3364,"precincts":
{"total":18,"reporting":4},
"name":"Transylvania"},
"Caldwell":
{"votes":[
{"votes":3453,"name":"clinton"},
{"votes":1484,"name":"obama"},
{"votes":127,"name":"nopreference-d"},
{"votes":82,"name":"gravel"}],
"total":5146,"precincts":
{"total":24,"reporting":9},
"name":"Caldwell"},
"Onslow":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Onslow"},
"Granville":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":26885,"name":"obama"},
{"votes":10994,"name":"clinton"},
{"votes":342,"name":"nopreference-d"},
{"votes":235,"name":"gravel"}],
"total":38456,"precincts":
{"total":44,"reporting":42},
"name":"Orange"},
"Burke":
{"votes":[
{"votes":2268,"name":"clinton"},
{"votes":1139,"name":"obama"},
{"votes":36,"name":"gravel"}],
"total":3443,"precincts":
{"total":31,"reporting":3},
"name":"Burke"},
"Lee":
{"votes":[
{"votes":2042,"name":"clinton"},
{"votes":1471,"name":"obama"},
{"votes":50,"name":"gravel"}],
"total":3563,"precincts":
{"total":9,"reporting":1},
"name":"Lee"},
"Avery":
{"votes":[
{"votes":243,"name":"clinton"},
{"votes":120,"name":"obama"},
{"votes":3,"name":"nopreference-d"},
{"votes":3,"name":"gravel"}],
"total":369,"precincts":
{"total":20,"reporting":5},
"name":"Avery"},
"Buncombe":
{"votes":[
{"votes":27743,"name":"obama"},
{"votes":21958,"name":"clinton"},
{"votes":513,"name":"nopreference-d"},
{"votes":315,"name":"gravel"}],
"total":50529,"precincts":
{"total":78,"reporting":78},
"name":"Buncombe"},
"Guilford":
{"votes":[
{"votes":40141,"name":"obama"},
{"votes":17340,"name":"clinton"},
{"votes":743,"name":"nopreference-d"},
{"votes":347,"name":"gravel"}],
"total":58571,"precincts":
{"total":163,"reporting":87},
"name":"Guilford"},
"Durham":
{"votes":[
{"votes":48101,"name":"obama"},
{"votes":15605,"name":"clinton"},
{"votes":679,"name":"nopreference-d"},
{"votes":245,"name":"gravel"}],
"total":64630,"precincts":
{"total":61,"reporting":55},
"name":"Durham"},
"Wake":
{"votes":[
{"votes":121716,"name":"obama"},
{"votes":63581,"name":"clinton"},
{"votes":1241,"name":"nopreference-d"},
{"votes":648,"name":"gravel"}],
"total":187186,"precincts":
{"total":210,"reporting":195},
"name":"Wake"},
"Chatham":
{"votes":[
{"votes":3477,"name":"obama"},
{"votes":1910,"name":"clinton"},
{"votes":85,"name":"nopreference-d"},
{"votes":36,"name":"gravel"}],
"total":5508,"precincts":
{"total":19,"reporting":0},
"name":"Chatham"},
"Beaufort":
{"votes":[
{"votes":3107,"name":"obama"},
{"votes":2832,"name":"clinton"},
{"votes":149,"name":"nopreference-d"},
{"votes":113,"name":"gravel"}],
"total":6201,"precincts":
{"total":23,"reporting":14},
"name":"Beaufort"},
"Vance":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Vance"},
"Rutherford":
{"votes":[
{"votes":2331,"name":"clinton"},
{"votes":1389,"name":"obama"},
{"votes":117,"name":"nopreference-d"},
{"votes":52,"name":"gravel"}],
"total":3889,"precincts":
{"total":20,"reporting":5},
"name":"Rutherford"},
"Harnett":
{"votes":[
{"votes":5985,"name":"clinton"},
{"votes":5469,"name":"obama"},
{"votes":171,"name":"nopreference-d"},
{"votes":140,"name":"gravel"}],
"total":11765,"precincts":
{"total":18,"reporting":15},
"name":"Harnett"},
"Davie":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Davie"},
"Greene":
{"votes":[
{"votes":518,"name":"obama"},
{"votes":371,"name":"clinton"},
{"votes":7,"name":"gravel"}],
"total":896,"precincts":
{"total":10,"reporting":3},
"name":"Greene"},
"Pender":
{"votes":[
{"votes":1120,"name":"obama"},
{"votes":1022,"name":"clinton"},
{"votes":36,"name":"nopreference-d"},
{"votes":18,"name":"gravel"}],
"total":2196,"precincts":
{"total":20,"reporting":0},
"name":"Pender"},
"Forsyth":
{"votes":[
{"votes":17952,"name":"obama"},
{"votes":6770,"name":"clinton"},
{"votes":122,"name":"nopreference-d"},
{"votes":94,"name":"gravel"}],
"total":24938,"precincts":
{"total":101,"reporting":20},
"name":"Forsyth"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Clay"},
"Macon":
{"votes":[
{"votes":2511,"name":"clinton"},
{"votes":1021,"name":"obama"},
{"votes":62,"name":"nopreference-d"},
{"votes":32,"name":"gravel"}],
"total":3626,"precincts":
{"total":15,"reporting":7},
"name":"Macon"},
"Chowan":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Chowan"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Madison"},
"Gaston":
{"votes":[
{"votes":7682,"name":"clinton"},
{"votes":6927,"name":"obama"},
{"votes":173,"name":"nopreference-d"},
{"votes":105,"name":"gravel"}],
"total":14887,"precincts":
{"total":46,"reporting":26},
"name":"Gaston"},
"Northampton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Northampton"},
"Swain":
{"votes":[
{"votes":1718,"name":"clinton"},
{"votes":630,"name":"obama"},
{"votes":77,"name":"nopreference-d"},
{"votes":33,"name":"gravel"}],
"total":2458,"precincts":
{"total":5,"reporting":5},
"name":"Swain"},
"Hyde":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Hyde"},
"Stanly":
{"votes":[
{"votes":2180,"name":"clinton"},
{"votes":1092,"name":"obama"},
{"votes":80,"name":"nopreference-d"},
{"votes":50,"name":"gravel"}],
"total":3402,"precincts":
{"total":24,"reporting":8},
"name":"Stanly"},
"Graham":
{"votes":[
{"votes":956,"name":"clinton"},
{"votes":220,"name":"obama"},
{"votes":40,"name":"nopreference-d"},
{"votes":21,"name":"gravel"}],
"total":1237,"precincts":
{"total":4,"reporting":4},
"name":"Graham"},
"Lenoir":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lenoir"},
"Hertford":
{"votes":[
{"votes":2564,"name":"obama"},
{"votes":966,"name":"clinton"},
{"votes":64,"name":"nopreference-d"},
{"votes":22,"name":"gravel"}],
"total":3616,"precincts":
{"total":13,"reporting":6},
"name":"Hertford"},
"Scotland":
{"votes":[
{"votes":3849,"name":"obama"},
{"votes":2861,"name":"clinton"},
{"votes":181,"name":"nopreference-d"},
{"votes":73,"name":"gravel"}],
"total":6964,"precincts":
{"total":10,"reporting":10},
"name":"Scotland"},
"Richmond":
{"votes":[
{"votes":1239,"name":"clinton"},
{"votes":1043,"name":"obama"},
{"votes":134,"name":"nopreference-d"},
{"votes":63,"name":"gravel"}],
"total":2479,"precincts":
{"total":16,"reporting":1},
"name":"Richmond"},
"Davidson":
{"votes":[
{"votes":7851,"name":"clinton"},
{"votes":5494,"name":"obama"},
{"votes":190,"name":"nopreference-d"},
{"votes":122,"name":"gravel"}],
"total":13657,"precincts":
{"total":43,"reporting":34},
"name":"Davidson"},
"Columbus":
{"votes":[
{"votes":5120,"name":"clinton"},
{"votes":3702,"name":"obama"},
{"votes":177,"name":"nopreference-d"},
{"votes":134,"name":"gravel"}],
"total":9133,"precincts":
{"total":29,"reporting":19},
"name":"Columbus"},
"Mitchell":
{"votes":[
{"votes":108,"name":"clinton"},
{"votes":57,"name":"obama"},
{"votes":2,"name":"nopreference-d"},
{"votes":2,"name":"gravel"}],
"total":169,"precincts":
{"total":9,"reporting":5},
"name":"Mitchell"},
"Bertie":
{"votes":[
{"votes":2238,"name":"obama"},
{"votes":1268,"name":"clinton"},
{"votes":68,"name":"nopreference-d"},
{"votes":34,"name":"gravel"}],
"total":3608,"precincts":
{"total":12,"reporting":8},
"name":"Bertie"},
"Alexander":
{"votes":[
{"votes":1910,"name":"clinton"},
{"votes":687,"name":"obama"},
{"votes":51,"name":"nopreference-d"},
{"votes":23,"name":"gravel"}],
"total":2671,"precincts":
{"total":18,"reporting":11},
"name":"Alexander"},
"Lincoln":
{"votes":[
{"votes":6727,"name":"clinton"},
{"votes":2781,"name":"obama"},
{"votes":144,"name":"nopreference-d"},
{"votes":113,"name":"gravel"}],
"total":9765,"precincts":
{"total":28,"reporting":28},
"name":"Lincoln"},
"Sampson":
{"votes":[
{"votes":3748,"name":"obama"},
{"votes":2930,"name":"clinton"},
{"votes":64,"name":"nopreference-d"},
{"votes":30,"name":"gravel"}],
"total":6772,"precincts":
{"total":23,"reporting":21},
"name":"Sampson"},
"Edgecombe":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Edgecombe"},
"Ashe":
{"votes":[
{"votes":3475,"name":"clinton"},
{"votes":1008,"name":"obama"},
{"votes":82,"name":"nopreference-d"},
{"votes":51,"name":"gravel"}],
"total":4616,"precincts":
{"total":17,"reporting":17},
"name":"Ashe"},
"Craven":
{"votes":[
{"votes":862,"name":"obama"},
{"votes":711,"name":"clinton"},
{"votes":34,"name":"nopreference-d"},
{"votes":26,"name":"gravel"}],
"total":1633,"precincts":
{"total":27,"reporting":5},
"name":"Craven"},
"Iredell":
{"votes":[
{"votes":6933,"name":"clinton"},
{"votes":6017,"name":"obama"},
{"votes":244,"name":"nopreference-d"},
{"votes":155,"name":"gravel"}],
"total":13349,"precincts":
{"total":29,"reporting":19},
"name":"Iredell"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Franklin"},
"Carteret":
{"votes":[
{"votes":3134,"name":"clinton"},
{"votes":1899,"name":"obama"},
{"votes":129,"name":"nopreference-d"},
{"votes":70,"name":"gravel"}],
"total":5232,"precincts":
{"total":34,"reporting":16},
"name":"Carteret"},
"Johnston":
{"votes":[
{"votes":4715,"name":"clinton"},
{"votes":4306,"name":"obama"},
{"votes":218,"name":"nopreference-d"},
{"votes":96,"name":"gravel"}],
"total":9335,"precincts":
{"total":37,"reporting":12},
"name":"Johnston"},
"Nash":
{"votes":[
{"votes":9931,"name":"obama"},
{"votes":6478,"name":"clinton"},
{"votes":277,"name":"nopreference-d"},
{"votes":152,"name":"gravel"}],
"total":16838,"precincts":
{"total":26,"reporting":18},
"name":"Nash"},
"Tyrrell":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Tyrrell"},
"Caswell":
{"votes":[
{"votes":565,"name":"obama"},
{"votes":314,"name":"clinton"},
{"votes":27,"name":"nopreference-d"},
{"votes":14,"name":"gravel"}],
"total":920,"precincts":
{"total":11,"reporting":1},
"name":"Caswell"},
"Cleveland":
{"votes":[
{"votes":4625,"name":"obama"},
{"votes":4459,"name":"clinton"},
{"votes":138,"name":"nopreference-d"},
{"votes":64,"name":"gravel"}],
"total":9286,"precincts":
{"total":28,"reporting":11},
"name":"Cleveland"},
"Halifax":
{"votes":[
{"votes":3323,"name":"obama"},
{"votes":2013,"name":"clinton"},
{"votes":80,"name":"nopreference-d"},
{"votes":65,"name":"gravel"}],
"total":5481,"precincts":
{"total":30,"reporting":11},
"name":"Halifax"},
"Cumberland":
{"votes":[
{"votes":15076,"name":"obama"},
{"votes":8081,"name":"clinton"},
{"votes":318,"name":"nopreference-d"},
{"votes":198,"name":"gravel"}],
"total":23673,"precincts":
{"total":69,"reporting":22},
"name":"Cumberland"},
"Rockingham":
{"votes":[
{"votes":7254,"name":"clinton"},
{"votes":6261,"name":"obama"},
{"votes":428,"name":"nopreference-d"},
{"votes":214,"name":"gravel"}],
"total":14157,"precincts":
{"total":20,"reporting":19},
"name":"Rockingham"},
"Rowan":
{"votes":[
{"votes":4076,"name":"obama"},
{"votes":3448,"name":"clinton"},
{"votes":109,"name":"nopreference-d"},
{"votes":64,"name":"gravel"}],
"total":7697,"precincts":
{"total":44,"reporting":19},
"name":"Rowan"},
"Alleghany":
{"votes":[
{"votes":640,"name":"clinton"},
{"votes":208,"name":"obama"},
{"votes":25,"name":"nopreference-d"},
{"votes":6,"name":"gravel"}],
"total":879,"precincts":
{"total":7,"reporting":0},
"name":"Alleghany"},
"McDowell":
{"votes":[
{"votes":2557,"name":"clinton"},
{"votes":856,"name":"obama"},
{"votes":70,"name":"nopreference-d"},
{"votes":60,"name":"gravel"}],
"total":3543,"precincts":
{"total":17,"reporting":11},
"name":"McDowell"},
"Haywood":
{"votes":[
{"votes":6952,"name":"clinton"},
{"votes":3060,"name":"obama"},
{"votes":333,"name":"nopreference-d"},
{"votes":133,"name":"gravel"}],
"total":10478,"precincts":
{"total":29,"reporting":22},
"name":"Haywood"},
"Pamlico":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Pamlico"},
"Dare":
{"votes":[
{"votes":768,"name":"clinton"},
{"votes":734,"name":"obama"},
{"votes":41,"name":"nopreference-d"},
{"votes":13,"name":"gravel"}],
"total":1556,"precincts":
{"total":16,"reporting":1},
"name":"Dare"},
"Jones":
{"votes":[
{"votes":95,"name":"obama"},
{"votes":80,"name":"clinton"},
{"votes":7,"name":"nopreference-d"},
{"votes":3,"name":"gravel"}],
"total":185,"precincts":
{"total":7,"reporting":1},
"name":"Jones"},
"Pitt":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Pitt"},
"Martin":
{"votes":[
{"votes":1367,"name":"obama"},
{"votes":911,"name":"clinton"},
{"votes":62,"name":"nopreference-d"},
{"votes":34,"name":"gravel"}],
"total":2374,"precincts":
{"total":13,"reporting":3},
"name":"Martin"},
"Mecklenburg":
{"votes":[
{"votes":35872,"name":"obama"},
{"votes":15296,"name":"clinton"},
{"votes":230,"name":"nopreference-d"},
{"votes":124,"name":"gravel"}],
"total":51522,"precincts":
{"total":198,"reporting":34},
"name":"Mecklenburg"},
"Gates":
{"votes":[
{"votes":1329,"name":"obama"},
{"votes":1209,"name":"clinton"},
{"votes":96,"name":"nopreference-d"},
{"votes":38,"name":"gravel"}],
"total":2672,"precincts":
{"total":6,"reporting":6},
"name":"Gates"},
"Person":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Person"},
"Yancey":
{"votes":[
{"votes":2597,"name":"clinton"},
{"votes":1025,"name":"obama"},
{"votes":94,"name":"nopreference-d"},
{"votes":48,"name":"gravel"}],
"total":3764,"precincts":
{"total":11,"reporting":11},
"name":"Yancey"},
"Surry":
{"votes":[
{"votes":5836,"name":"clinton"},
{"votes":2085,"name":"obama"},
{"votes":104,"name":"nopreference-d"},
{"votes":83,"name":"gravel"}],
"total":8108,"precincts":
{"total":32,"reporting":22},
"name":"Surry"},
"Perquimans":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Perquimans"},
"Randolph":
{"votes":[
{"votes":4795,"name":"clinton"},
{"votes":2531,"name":"obama"},
{"votes":134,"name":"nopreference-d"},
{"votes":106,"name":"gravel"}],
"total":7566,"precincts":
{"total":42,"reporting":32},
"name":"Randolph"}}})