GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":334142,"name":"mccain"},
{"votes":55213,"name":"huckabee"},
{"votes":33139,"name":"paul"},
{"votes":17787,"name":"nopreference-r"},
{"votes":12086,"name":"keyes"}],
"name":"North Carolina","precincts":
{"total":2817,"reporting":2401},
"delegates":69,"date":"05-06"},
"state":"NC","party":"gop","total":452367,"locals":
{"Bladen":
{"votes":[
{"votes":450,"name":"mccain"},
{"votes":83,"name":"huckabee"},
{"votes":53,"name":"paul"},
{"votes":26,"name":"nopreference-r"},
{"votes":14,"name":"keyes"}],
"total":626,"precincts":
{"total":17,"reporting":17},
"name":"Bladen"},
"Currituck":
{"votes":[
{"votes":1092,"name":"mccain"},
{"votes":174,"name":"huckabee"},
{"votes":71,"name":"paul"},
{"votes":58,"name":"nopreference-r"},
{"votes":24,"name":"keyes"}],
"total":1419,"precincts":
{"total":11,"reporting":11},
"name":"Currituck"},
"Union":
{"votes":[
{"votes":10311,"name":"mccain"},
{"votes":1910,"name":"huckabee"},
{"votes":1324,"name":"paul"},
{"votes":790,"name":"keyes"},
{"votes":619,"name":"nopreference-r"}],
"total":14954,"precincts":
{"total":49,"reporting":49},
"name":"Union"},
"Wilson":
{"votes":[
{"votes":1020,"name":"mccain"},
{"votes":119,"name":"huckabee"},
{"votes":51,"name":"paul"},
{"votes":50,"name":"nopreference-r"},
{"votes":14,"name":"keyes"}],
"total":1254,"precincts":
{"total":25,"reporting":9},
"name":"Wilson"},
"Montgomery":
{"votes":[
{"votes":1377,"name":"mccain"},
{"votes":323,"name":"huckabee"},
{"votes":69,"name":"paul"},
{"votes":56,"name":"nopreference-r"},
{"votes":27,"name":"keyes"}],
"total":1852,"precincts":
{"total":14,"reporting":14},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":4621,"name":"mccain"},
{"votes":576,"name":"huckabee"},
{"votes":207,"name":"paul"},
{"votes":197,"name":"nopreference-r"},
{"votes":80,"name":"keyes"}],
"total":5681,"precincts":
{"total":30,"reporting":30},
"name":"Wayne"},
"Robeson":
{"votes":[
{"votes":1064,"name":"mccain"},
{"votes":180,"name":"huckabee"},
{"votes":94,"name":"nopreference-r"},
{"votes":74,"name":"paul"},
{"votes":19,"name":"keyes"}],
"total":1431,"precincts":
{"total":41,"reporting":41},
"name":"Robeson"},
"Brunswick":
{"votes":[
{"votes":4396,"name":"mccain"},
{"votes":590,"name":"huckabee"},
{"votes":347,"name":"paul"},
{"votes":194,"name":"nopreference-r"},
{"votes":68,"name":"keyes"}],
"total":5595,"precincts":
{"total":23,"reporting":18},
"name":"Brunswick"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Henderson"},
"Cherokee":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Cherokee"},
"Anson":
{"votes":[
{"votes":276,"name":"mccain"},
{"votes":61,"name":"huckabee"},
{"votes":29,"name":"paul"},
{"votes":16,"name":"keyes"},
{"votes":15,"name":"nopreference-r"}],
"total":397,"precincts":
{"total":11,"reporting":11},
"name":"Anson"},
"Catawba":
{"votes":[
{"votes":10181,"name":"mccain"},
{"votes":1784,"name":"huckabee"},
{"votes":756,"name":"paul"},
{"votes":509,"name":"nopreference-r"},
{"votes":280,"name":"keyes"}],
"total":13510,"precincts":
{"total":41,"reporting":40},
"name":"Catawba"},
"Yadkin":
{"votes":[
{"votes":4234,"name":"mccain"},
{"votes":680,"name":"huckabee"},
{"votes":253,"name":"paul"},
{"votes":220,"name":"nopreference-r"},
{"votes":72,"name":"keyes"}],
"total":5459,"precincts":
{"total":12,"reporting":12},
"name":"Yadkin"},
"Stokes":
{"votes":[
{"votes":2649,"name":"mccain"},
{"votes":515,"name":"huckabee"},
{"votes":188,"name":"paul"},
{"votes":136,"name":"nopreference-r"},
{"votes":85,"name":"keyes"}],
"total":3573,"precincts":
{"total":23,"reporting":23},
"name":"Stokes"},
"Pasquotank":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pasquotank"},
"Hoke":
{"votes":[
{"votes":551,"name":"mccain"},
{"votes":63,"name":"huckabee"},
{"votes":39,"name":"nopreference-r"},
{"votes":32,"name":"paul"},
{"votes":17,"name":"keyes"}],
"total":702,"precincts":
{"total":13,"reporting":13},
"name":"Hoke"},
"Wilkes":
{"votes":[
{"votes":5765,"name":"mccain"},
{"votes":1138,"name":"huckabee"},
{"votes":337,"name":"paul"},
{"votes":332,"name":"nopreference-r"},
{"votes":81,"name":"keyes"}],
"total":7653,"precincts":
{"total":28,"reporting":28},
"name":"Wilkes"},
"Alamance":
{"votes":[
{"votes":5697,"name":"mccain"},
{"votes":976,"name":"huckabee"},
{"votes":631,"name":"paul"},
{"votes":260,"name":"nopreference-r"},
{"votes":145,"name":"keyes"}],
"total":7709,"precincts":
{"total":37,"reporting":37},
"name":"Alamance"},
"Moore":
{"votes":[
{"votes":8864,"name":"mccain"},
{"votes":1043,"name":"huckabee"},
{"votes":549,"name":"paul"},
{"votes":369,"name":"nopreference-r"},
{"votes":108,"name":"keyes"}],
"total":10933,"precincts":
{"total":24,"reporting":24},
"name":"Moore"},
"Washington":
{"votes":[
{"votes":266,"name":"nopreference-r"},
{"votes":210,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":9,"name":"keyes"},
{"votes":9,"name":"paul"}],
"total":525,"precincts":
{"total":6,"reporting":6},
"name":"Washington"},
"Duplin":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Duplin"},
"Cabarrus":
{"votes":[
{"votes":6757,"name":"mccain"},
{"votes":1227,"name":"huckabee"},
{"votes":925,"name":"paul"},
{"votes":442,"name":"keyes"},
{"votes":403,"name":"nopreference-r"}],
"total":9754,"precincts":
{"total":49,"reporting":49},
"name":"Cabarrus"},
"Camden":
{"votes":[
{"votes":275,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":9,"name":"keyes"},
{"votes":6,"name":"nopreference-r"}],
"total":352,"precincts":
{"total":3,"reporting":3},
"name":"Camden"},
"New Hanover":
{"votes":[
{"votes":8022,"name":"mccain"},
{"votes":1096,"name":"huckabee"},
{"votes":1075,"name":"paul"},
{"votes":358,"name":"nopreference-r"},
{"votes":182,"name":"keyes"}],
"total":10733,"precincts":
{"total":43,"reporting":35},
"name":"New Hanover"},
"Polk":
{"votes":[
{"votes":1255,"name":"mccain"},
{"votes":181,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":63,"name":"nopreference-r"},
{"votes":46,"name":"keyes"}],
"total":1675,"precincts":
{"total":7,"reporting":7},
"name":"Polk"},
"Warren":
{"votes":[
{"votes":232,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":9,"name":"paul"},
{"votes":7,"name":"keyes"},
{"votes":4,"name":"nopreference-r"}],
"total":289,"precincts":
{"total":14,"reporting":12},
"name":"Warren"},
"Watauga":
{"votes":[
{"votes":2206,"name":"mccain"},
{"votes":421,"name":"huckabee"},
{"votes":367,"name":"paul"},
{"votes":94,"name":"nopreference-r"},
{"votes":66,"name":"keyes"}],
"total":3154,"precincts":
{"total":20,"reporting":20},
"name":"Watauga"},
"Jackson":
{"votes":[
{"votes":581,"name":"mccain"},
{"votes":110,"name":"huckabee"},
{"votes":62,"name":"paul"},
{"votes":38,"name":"nopreference-r"},
{"votes":18,"name":"keyes"}],
"total":809,"precincts":
{"total":18,"reporting":7},
"name":"Jackson"},
"Transylvania":
{"votes":[
{"votes":1951,"name":"mccain"},
{"votes":395,"name":"huckabee"},
{"votes":217,"name":"paul"},
{"votes":79,"name":"nopreference-r"},
{"votes":61,"name":"keyes"}],
"total":2703,"precincts":
{"total":18,"reporting":15},
"name":"Transylvania"},
"Caldwell":
{"votes":[
{"votes":4848,"name":"mccain"},
{"votes":972,"name":"huckabee"},
{"votes":326,"name":"paul"},
{"votes":306,"name":"nopreference-r"},
{"votes":99,"name":"keyes"}],
"total":6551,"precincts":
{"total":24,"reporting":24},
"name":"Caldwell"},
"Onslow":
{"votes":[
{"votes":3645,"name":"mccain"},
{"votes":415,"name":"huckabee"},
{"votes":317,"name":"keyes"},
{"votes":261,"name":"paul"},
{"votes":163,"name":"nopreference-r"}],
"total":4801,"precincts":
{"total":27,"reporting":19},
"name":"Onslow"},
"Granville":
{"votes":[
{"votes":1220,"name":"mccain"},
{"votes":219,"name":"huckabee"},
{"votes":150,"name":"paul"},
{"votes":80,"name":"nopreference-r"},
{"votes":54,"name":"keyes"}],
"total":1723,"precincts":
{"total":15,"reporting":15},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":3950,"name":"mccain"},
{"votes":725,"name":"paul"},
{"votes":554,"name":"huckabee"},
{"votes":271,"name":"nopreference-r"},
{"votes":122,"name":"keyes"}],
"total":5622,"precincts":
{"total":44,"reporting":44},
"name":"Orange"},
"Burke":
{"votes":[
{"votes":3360,"name":"mccain"},
{"votes":771,"name":"huckabee"},
{"votes":291,"name":"paul"},
{"votes":185,"name":"nopreference-r"},
{"votes":103,"name":"keyes"}],
"total":4710,"precincts":
{"total":31,"reporting":31},
"name":"Burke"},
"Lee":
{"votes":[
{"votes":2500,"name":"mccain"},
{"votes":356,"name":"huckabee"},
{"votes":198,"name":"paul"},
{"votes":128,"name":"nopreference-r"},
{"votes":63,"name":"keyes"}],
"total":3245,"precincts":
{"total":9,"reporting":9},
"name":"Lee"},
"Avery":
{"votes":[
{"votes":2405,"name":"mccain"},
{"votes":505,"name":"huckabee"},
{"votes":200,"name":"paul"},
{"votes":182,"name":"nopreference-r"},
{"votes":36,"name":"keyes"}],
"total":3328,"precincts":
{"total":20,"reporting":20},
"name":"Avery"},
"Buncombe":
{"votes":[
{"votes":7159,"name":"mccain"},
{"votes":1623,"name":"huckabee"},
{"votes":1558,"name":"paul"},
{"votes":482,"name":"nopreference-r"},
{"votes":348,"name":"keyes"}],
"total":11170,"precincts":
{"total":78,"reporting":78},
"name":"Buncombe"},
"Guilford":
{"votes":[
{"votes":24123,"name":"mccain"},
{"votes":3954,"name":"huckabee"},
{"votes":1741,"name":"paul"},
{"votes":1209,"name":"nopreference-r"},
{"votes":849,"name":"keyes"}],
"total":31876,"precincts":
{"total":163,"reporting":162},
"name":"Guilford"},
"Durham":
{"votes":[
{"votes":5133,"name":"mccain"},
{"votes":737,"name":"huckabee"},
{"votes":690,"name":"paul"},
{"votes":341,"name":"nopreference-r"},
{"votes":228,"name":"keyes"}],
"total":7129,"precincts":
{"total":61,"reporting":61},
"name":"Durham"},
"Wake":
{"votes":[
{"votes":34676,"name":"mccain"},
{"votes":5648,"name":"huckabee"},
{"votes":5477,"name":"paul"},
{"votes":1793,"name":"nopreference-r"},
{"votes":1643,"name":"keyes"}],
"total":49237,"precincts":
{"total":210,"reporting":210},
"name":"Wake"},
"Chatham":
{"votes":[
{"votes":1372,"name":"mccain"},
{"votes":201,"name":"huckabee"},
{"votes":154,"name":"paul"},
{"votes":72,"name":"nopreference-r"},
{"votes":34,"name":"keyes"}],
"total":1833,"precincts":
{"total":19,"reporting":11},
"name":"Chatham"},
"Beaufort":
{"votes":[
{"votes":2047,"name":"mccain"},
{"votes":312,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":71,"name":"nopreference-r"},
{"votes":52,"name":"keyes"}],
"total":2612,"precincts":
{"total":23,"reporting":21},
"name":"Beaufort"},
"Vance":
{"votes":[
{"votes":742,"name":"mccain"},
{"votes":91,"name":"huckabee"},
{"votes":55,"name":"nopreference-r"},
{"votes":43,"name":"paul"},
{"votes":23,"name":"keyes"}],
"total":954,"precincts":
{"total":16,"reporting":16},
"name":"Vance"},
"Rutherford":
{"votes":[
{"votes":1992,"name":"mccain"},
{"votes":544,"name":"huckabee"},
{"votes":201,"name":"paul"},
{"votes":92,"name":"keyes"},
{"votes":87,"name":"nopreference-r"}],
"total":2916,"precincts":
{"total":20,"reporting":20},
"name":"Rutherford"},
"Harnett":
{"votes":[
{"votes":3435,"name":"mccain"},
{"votes":550,"name":"huckabee"},
{"votes":297,"name":"paul"},
{"votes":166,"name":"nopreference-r"},
{"votes":89,"name":"keyes"}],
"total":4537,"precincts":
{"total":18,"reporting":18},
"name":"Harnett"},
"Davie":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Davie"},
"Greene":
{"votes":[
{"votes":295,"name":"mccain"},
{"votes":52,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":14,"name":"nopreference-r"},
{"votes":13,"name":"keyes"}],
"total":398,"precincts":
{"total":10,"reporting":10},
"name":"Greene"},
"Pender":
{"votes":[
{"votes":585,"name":"mccain"},
{"votes":62,"name":"huckabee"},
{"votes":54,"name":"paul"},
{"votes":24,"name":"nopreference-r"},
{"votes":8,"name":"keyes"}],
"total":733,"precincts":
{"total":20,"reporting":0},
"name":"Pender"},
"Forsyth":
{"votes":[
{"votes":11660,"name":"mccain"},
{"votes":1907,"name":"huckabee"},
{"votes":932,"name":"paul"},
{"votes":642,"name":"nopreference-r"},
{"votes":429,"name":"keyes"}],
"total":15570,"precincts":
{"total":101,"reporting":76},
"name":"Forsyth"},
"Clay":
{"votes":[
{"votes":697,"name":"mccain"},
{"votes":110,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":12,"name":"nopreference-r"},
{"votes":4,"name":"keyes"}],
"total":868,"precincts":
{"total":9,"reporting":9},
"name":"Clay"},
"Macon":
{"votes":[
{"votes":1943,"name":"mccain"},
{"votes":399,"name":"huckabee"},
{"votes":234,"name":"paul"},
{"votes":87,"name":"nopreference-r"},
{"votes":40,"name":"keyes"}],
"total":2703,"precincts":
{"total":15,"reporting":15},
"name":"Macon"},
"Chowan":
{"votes":[
{"votes":801,"name":"mccain"},
{"votes":89,"name":"huckabee"},
{"votes":35,"name":"nopreference-r"},
{"votes":33,"name":"paul"},
{"votes":17,"name":"keyes"}],
"total":975,"precincts":
{"total":6,"reporting":6},
"name":"Chowan"},
"Madison":
{"votes":[
{"votes":570,"name":"mccain"},
{"votes":179,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":69,"name":"nopreference-r"},
{"votes":45,"name":"keyes"}],
"total":993,"precincts":
{"total":12,"reporting":12},
"name":"Madison"},
"Gaston":
{"votes":[
{"votes":3988,"name":"mccain"},
{"votes":716,"name":"huckabee"},
{"votes":499,"name":"paul"},
{"votes":255,"name":"keyes"},
{"votes":242,"name":"nopreference-r"}],
"total":5700,"precincts":
{"total":46,"reporting":26},
"name":"Gaston"},
"Northampton":
{"votes":[
{"votes":257,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":6,"name":"nopreference-r"},
{"votes":2,"name":"keyes"}],
"total":320,"precincts":
{"total":18,"reporting":18},
"name":"Northampton"},
"Swain":
{"votes":[
{"votes":377,"name":"mccain"},
{"votes":90,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":13,"name":"nopreference-r"},
{"votes":9,"name":"keyes"}],
"total":526,"precincts":
{"total":5,"reporting":5},
"name":"Swain"},
"Hyde":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Hyde"},
"Stanly":
{"votes":[
{"votes":3839,"name":"mccain"},
{"votes":652,"name":"huckabee"},
{"votes":231,"name":"paul"},
{"votes":199,"name":"nopreference-r"},
{"votes":123,"name":"keyes"}],
"total":5044,"precincts":
{"total":24,"reporting":24},
"name":"Stanly"},
"Graham":
{"votes":[
{"votes":741,"name":"mccain"},
{"votes":187,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":21,"name":"nopreference-r"},
{"votes":14,"name":"keyes"}],
"total":988,"precincts":
{"total":4,"reporting":4},
"name":"Graham"},
"Lenoir":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lenoir"},
"Hertford":
{"votes":[
{"votes":155,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":8,"name":"nopreference-r"},
{"votes":6,"name":"paul"},
{"votes":2,"name":"keyes"}],
"total":193,"precincts":
{"total":13,"reporting":6},
"name":"Hertford"},
"Scotland":
{"votes":[
{"votes":544,"name":"mccain"},
{"votes":65,"name":"huckabee"},
{"votes":57,"name":"paul"},
{"votes":27,"name":"nopreference-r"},
{"votes":10,"name":"keyes"}],
"total":703,"precincts":
{"total":10,"reporting":10},
"name":"Scotland"},
"Richmond":
{"votes":[
{"votes":534,"name":"mccain"},
{"votes":60,"name":"huckabee"},
{"votes":59,"name":"paul"},
{"votes":29,"name":"nopreference-r"},
{"votes":10,"name":"keyes"}],
"total":692,"precincts":
{"total":16,"reporting":8},
"name":"Richmond"},
"Davidson":
{"votes":[
{"votes":7775,"name":"mccain"},
{"votes":1601,"name":"huckabee"},
{"votes":531,"name":"paul"},
{"votes":400,"name":"nopreference-r"},
{"votes":170,"name":"keyes"}],
"total":10477,"precincts":
{"total":43,"reporting":43},
"name":"Davidson"},
"Columbus":
{"votes":[
{"votes":868,"name":"mccain"},
{"votes":104,"name":"huckabee"},
{"votes":61,"name":"paul"},
{"votes":58,"name":"nopreference-r"},
{"votes":17,"name":"keyes"}],
"total":1108,"precincts":
{"total":29,"reporting":27},
"name":"Columbus"},
"Mitchell":
{"votes":[
{"votes":1832,"name":"mccain"},
{"votes":442,"name":"huckabee"},
{"votes":279,"name":"paul"},
{"votes":29,"name":"keyes"},
{"votes":15,"name":"nopreference-r"}],
"total":2597,"precincts":
{"total":9,"reporting":9},
"name":"Mitchell"},
"Bertie":
{"votes":[
{"votes":170,"name":"mccain"},
{"votes":20,"name":"huckabee"},
{"votes":11,"name":"nopreference-r"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"keyes"}],
"total":204,"precincts":
{"total":12,"reporting":9},
"name":"Bertie"},
"Alexander":
{"votes":[
{"votes":2157,"name":"mccain"},
{"votes":446,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":95,"name":"nopreference-r"},
{"votes":45,"name":"keyes"}],
"total":2873,"precincts":
{"total":18,"reporting":18},
"name":"Alexander"},
"Lincoln":
{"votes":[
{"votes":5434,"name":"mccain"},
{"votes":976,"name":"huckabee"},
{"votes":538,"name":"paul"},
{"votes":317,"name":"nopreference-r"},
{"votes":202,"name":"keyes"}],
"total":7467,"precincts":
{"total":28,"reporting":28},
"name":"Lincoln"},
"Sampson":
{"votes":[
{"votes":2471,"name":"mccain"},
{"votes":283,"name":"huckabee"},
{"votes":104,"name":"paul"},
{"votes":87,"name":"nopreference-r"},
{"votes":28,"name":"keyes"}],
"total":2973,"precincts":
{"total":23,"reporting":22},
"name":"Sampson"},
"Edgecombe":
{"votes":[
{"votes":422,"name":"mccain"},
{"votes":59,"name":"huckabee"},
{"votes":35,"name":"nopreference-r"},
{"votes":10,"name":"paul"},
{"votes":9,"name":"keyes"}],
"total":535,"precincts":
{"total":21,"reporting":12},
"name":"Edgecombe"},
"Ashe":
{"votes":[
{"votes":2042,"name":"mccain"},
{"votes":378,"name":"huckabee"},
{"votes":145,"name":"paul"},
{"votes":116,"name":"nopreference-r"},
{"votes":29,"name":"keyes"}],
"total":2710,"precincts":
{"total":17,"reporting":17},
"name":"Ashe"},
"Craven":
{"votes":[
{"votes":1996,"name":"mccain"},
{"votes":269,"name":"huckabee"},
{"votes":148,"name":"paul"},
{"votes":108,"name":"nopreference-r"},
{"votes":49,"name":"keyes"}],
"total":2570,"precincts":
{"total":27,"reporting":14},
"name":"Craven"},
"Iredell":
{"votes":[
{"votes":6260,"name":"mccain"},
{"votes":861,"name":"huckabee"},
{"votes":379,"name":"paul"},
{"votes":368,"name":"nopreference-r"},
{"votes":206,"name":"keyes"}],
"total":8074,"precincts":
{"total":29,"reporting":19},
"name":"Iredell"},
"Franklin":
{"votes":[
{"votes":2201,"name":"mccain"},
{"votes":399,"name":"huckabee"},
{"votes":330,"name":"paul"},
{"votes":124,"name":"nopreference-r"},
{"votes":74,"name":"keyes"}],
"total":3128,"precincts":
{"total":18,"reporting":18},
"name":"Franklin"},
"Carteret":
{"votes":[
{"votes":4927,"name":"mccain"},
{"votes":590,"name":"huckabee"},
{"votes":249,"name":"paul"},
{"votes":197,"name":"nopreference-r"},
{"votes":151,"name":"keyes"}],
"total":6114,"precincts":
{"total":34,"reporting":34},
"name":"Carteret"},
"Johnston":
{"votes":[
{"votes":4689,"name":"mccain"},
{"votes":744,"name":"huckabee"},
{"votes":431,"name":"paul"},
{"votes":234,"name":"nopreference-r"},
{"votes":129,"name":"keyes"}],
"total":6227,"precincts":
{"total":37,"reporting":19},
"name":"Johnston"},
"Nash":
{"votes":[
{"votes":4348,"name":"mccain"},
{"votes":698,"name":"huckabee"},
{"votes":338,"name":"paul"},
{"votes":208,"name":"nopreference-r"},
{"votes":94,"name":"keyes"}],
"total":5686,"precincts":
{"total":26,"reporting":26},
"name":"Nash"},
"Tyrrell":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Tyrrell"},
"Caswell":
{"votes":[
{"votes":68,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"nopreference-r"}],
"total":86,"precincts":
{"total":11,"reporting":1},
"name":"Caswell"},
"Cleveland":
{"votes":[
{"votes":3055,"name":"mccain"},
{"votes":622,"name":"huckabee"},
{"votes":334,"name":"paul"},
{"votes":154,"name":"keyes"},
{"votes":146,"name":"nopreference-r"}],
"total":4311,"precincts":
{"total":28,"reporting":28},
"name":"Cleveland"},
"Halifax":
{"votes":[
{"votes":575,"name":"mccain"},
{"votes":81,"name":"huckabee"},
{"votes":22,"name":"nopreference-r"},
{"votes":20,"name":"paul"},
{"votes":13,"name":"keyes"}],
"total":711,"precincts":
{"total":30,"reporting":26},
"name":"Halifax"},
"Cumberland":
{"votes":[
{"votes":6423,"name":"mccain"},
{"votes":840,"name":"huckabee"},
{"votes":378,"name":"paul"},
{"votes":278,"name":"nopreference-r"},
{"votes":188,"name":"keyes"}],
"total":8107,"precincts":
{"total":69,"reporting":45},
"name":"Cumberland"},
"Rockingham":
{"votes":[
{"votes":3372,"name":"mccain"},
{"votes":728,"name":"huckabee"},
{"votes":221,"name":"nopreference-r"},
{"votes":203,"name":"paul"},
{"votes":57,"name":"keyes"}],
"total":4581,"precincts":
{"total":20,"reporting":19},
"name":"Rockingham"},
"Rowan":
{"votes":[
{"votes":7332,"name":"mccain"},
{"votes":1212,"name":"huckabee"},
{"votes":550,"name":"paul"},
{"votes":432,"name":"nopreference-r"},
{"votes":252,"name":"keyes"}],
"total":9778,"precincts":
{"total":44,"reporting":44},
"name":"Rowan"},
"Alleghany":
{"votes":[
{"votes":586,"name":"mccain"},
{"votes":94,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":31,"name":"nopreference-r"},
{"votes":12,"name":"keyes"}],
"total":764,"precincts":
{"total":7,"reporting":7},
"name":"Alleghany"},
"McDowell":
{"votes":[
{"votes":1419,"name":"mccain"},
{"votes":371,"name":"huckabee"},
{"votes":118,"name":"nopreference-r"},
{"votes":111,"name":"paul"},
{"votes":35,"name":"keyes"}],
"total":2054,"precincts":
{"total":17,"reporting":17},
"name":"McDowell"},
"Haywood":
{"votes":[
{"votes":2338,"name":"mccain"},
{"votes":519,"name":"huckabee"},
{"votes":371,"name":"paul"},
{"votes":166,"name":"nopreference-r"},
{"votes":71,"name":"keyes"}],
"total":3465,"precincts":
{"total":29,"reporting":29},
"name":"Haywood"},
"Pamlico":
{"votes":[
{"votes":625,"name":"mccain"},
{"votes":88,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":35,"name":"nopreference-r"},
{"votes":23,"name":"keyes"}],
"total":812,"precincts":
{"total":10,"reporting":10},
"name":"Pamlico"},
"Dare":
{"votes":[
{"votes":1287,"name":"mccain"},
{"votes":166,"name":"huckabee"},
{"votes":114,"name":"paul"},
{"votes":75,"name":"nopreference-r"},
{"votes":30,"name":"keyes"}],
"total":1672,"precincts":
{"total":16,"reporting":16},
"name":"Dare"},
"Jones":
{"votes":[
{"votes":289,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":16,"name":"keyes"},
{"votes":16,"name":"paul"},
{"votes":15,"name":"nopreference-r"}],
"total":373,"precincts":
{"total":7,"reporting":7},
"name":"Jones"},
"Pitt":
{"votes":[
{"votes":4398,"name":"mccain"},
{"votes":590,"name":"huckabee"},
{"votes":250,"name":"nopreference-r"},
{"votes":218,"name":"paul"},
{"votes":73,"name":"keyes"}],
"total":5529,"precincts":
{"total":38,"reporting":38},
"name":"Pitt"},
"Martin":
{"votes":[
{"votes":495,"name":"mccain"},
{"votes":86,"name":"huckabee"},
{"votes":33,"name":"nopreference-r"},
{"votes":18,"name":"paul"},
{"votes":12,"name":"keyes"}],
"total":644,"precincts":
{"total":13,"reporting":13},
"name":"Martin"},
"Mecklenburg":
{"votes":[
{"votes":27802,"name":"mccain"},
{"votes":3361,"name":"paul"},
{"votes":3219,"name":"huckabee"},
{"votes":1839,"name":"keyes"},
{"votes":1423,"name":"nopreference-r"}],
"total":37644,"precincts":
{"total":198,"reporting":155},
"name":"Mecklenburg"},
"Gates":
{"votes":[
{"votes":243,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":13,"name":"nopreference-r"},
{"votes":7,"name":"paul"},
{"votes":2,"name":"keyes"}],
"total":296,"precincts":
{"total":6,"reporting":6},
"name":"Gates"},
"Person":
{"votes":[
{"votes":972,"name":"mccain"},
{"votes":181,"name":"huckabee"},
{"votes":87,"name":"paul"},
{"votes":48,"name":"nopreference-r"},
{"votes":28,"name":"keyes"}],
"total":1316,"precincts":
{"total":14,"reporting":14},
"name":"Person"},
"Yancey":
{"votes":[
{"votes":972,"name":"mccain"},
{"votes":309,"name":"huckabee"},
{"votes":125,"name":"paul"},
{"votes":65,"name":"nopreference-r"},
{"votes":30,"name":"keyes"}],
"total":1501,"precincts":
{"total":11,"reporting":11},
"name":"Yancey"},
"Surry":
{"votes":[
{"votes":2942,"name":"mccain"},
{"votes":526,"name":"huckabee"},
{"votes":163,"name":"paul"},
{"votes":138,"name":"nopreference-r"},
{"votes":55,"name":"keyes"}],
"total":3824,"precincts":
{"total":32,"reporting":32},
"name":"Surry"},
"Perquimans":
{"votes":[
{"votes":448,"name":"mccain"},
{"votes":63,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":21,"name":"nopreference-r"},
{"votes":20,"name":"keyes"}],
"total":577,"precincts":
{"total":7,"reporting":7},
"name":"Perquimans"},
"Randolph":
{"votes":[
{"votes":7279,"name":"mccain"},
{"votes":1734,"name":"huckabee"},
{"votes":670,"name":"paul"},
{"votes":378,"name":"nopreference-r"},
{"votes":126,"name":"keyes"}],
"total":10187,"precincts":
{"total":42,"reporting":42},
"name":"Randolph"}}})