GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":196054,"name":"mccain"},
{"votes":31629,"name":"huckabee"},
{"votes":20900,"name":"paul"},
{"votes":10191,"name":"nopreference-r"},
{"votes":6711,"name":"keyes"}],
"name":"North Carolina","precincts":
{"total":2817,"reporting":1234},
"delegates":69,"date":"05-06"},
"state":"NC","party":"gop","total":265485,"locals":
{"Bladen":
{"votes":[
{"votes":450,"name":"mccain"},
{"votes":83,"name":"huckabee"},
{"votes":53,"name":"paul"},
{"votes":26,"name":"nopreference-r"},
{"votes":14,"name":"keyes"}],
"total":626,"precincts":
{"total":17,"reporting":17},
"name":"Bladen"},
"Currituck":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Currituck"},
"Union":
{"votes":[
{"votes":5019,"name":"mccain"},
{"votes":899,"name":"huckabee"},
{"votes":631,"name":"paul"},
{"votes":322,"name":"keyes"},
{"votes":305,"name":"nopreference-r"}],
"total":7176,"precincts":
{"total":49,"reporting":25},
"name":"Union"},
"Wilson":
{"votes":[
{"votes":431,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":25,"name":"nopreference-r"},
{"votes":16,"name":"paul"},
{"votes":10,"name":"keyes"}],
"total":519,"precincts":
{"total":25,"reporting":0},
"name":"Wilson"},
"Montgomery":
{"votes":[
{"votes":829,"name":"mccain"},
{"votes":137,"name":"huckabee"},
{"votes":42,"name":"paul"},
{"votes":23,"name":"nopreference-r"},
{"votes":13,"name":"keyes"}],
"total":1044,"precincts":
{"total":14,"reporting":6},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":1784,"name":"mccain"},
{"votes":170,"name":"huckabee"},
{"votes":77,"name":"nopreference-r"},
{"votes":71,"name":"paul"},
{"votes":25,"name":"keyes"}],
"total":2127,"precincts":
{"total":30,"reporting":10},
"name":"Wayne"},
"Robeson":
{"votes":[
{"votes":556,"name":"mccain"},
{"votes":98,"name":"huckabee"},
{"votes":52,"name":"nopreference-r"},
{"votes":37,"name":"paul"},
{"votes":8,"name":"keyes"}],
"total":751,"precincts":
{"total":41,"reporting":22},
"name":"Robeson"},
"Brunswick":
{"votes":[
{"votes":2214,"name":"mccain"},
{"votes":250,"name":"huckabee"},
{"votes":147,"name":"paul"},
{"votes":87,"name":"nopreference-r"},
{"votes":35,"name":"keyes"}],
"total":2733,"precincts":
{"total":23,"reporting":6},
"name":"Brunswick"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Henderson"},
"Cherokee":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Cherokee"},
"Anson":
{"votes":[
{"votes":224,"name":"mccain"},
{"votes":57,"name":"huckabee"},
{"votes":22,"name":"paul"},
{"votes":14,"name":"keyes"},
{"votes":10,"name":"nopreference-r"}],
"total":327,"precincts":
{"total":11,"reporting":8},
"name":"Anson"},
"Catawba":
{"votes":[
{"votes":10181,"name":"mccain"},
{"votes":1784,"name":"huckabee"},
{"votes":756,"name":"paul"},
{"votes":509,"name":"nopreference-r"},
{"votes":280,"name":"keyes"}],
"total":13510,"precincts":
{"total":41,"reporting":40},
"name":"Catawba"},
"Yadkin":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Yadkin"},
"Stokes":
{"votes":[
{"votes":1131,"name":"mccain"},
{"votes":206,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":46,"name":"nopreference-r"},
{"votes":39,"name":"keyes"}],
"total":1490,"precincts":
{"total":23,"reporting":8},
"name":"Stokes"},
"Pasquotank":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pasquotank"},
"Hoke":
{"votes":[
{"votes":339,"name":"mccain"},
{"votes":36,"name":"huckabee"},
{"votes":24,"name":"nopreference-r"},
{"votes":17,"name":"paul"},
{"votes":10,"name":"keyes"}],
"total":426,"precincts":
{"total":13,"reporting":9},
"name":"Hoke"},
"Wilkes":
{"votes":[
{"votes":5176,"name":"mccain"},
{"votes":999,"name":"huckabee"},
{"votes":307,"name":"paul"},
{"votes":293,"name":"nopreference-r"},
{"votes":73,"name":"keyes"}],
"total":6848,"precincts":
{"total":28,"reporting":1},
"name":"Wilkes"},
"Alamance":
{"votes":[
{"votes":4291,"name":"mccain"},
{"votes":703,"name":"huckabee"},
{"votes":436,"name":"paul"},
{"votes":188,"name":"nopreference-r"},
{"votes":97,"name":"keyes"}],
"total":5715,"precincts":
{"total":37,"reporting":26},
"name":"Alamance"},
"Moore":
{"votes":[
{"votes":5800,"name":"mccain"},
{"votes":640,"name":"huckabee"},
{"votes":291,"name":"paul"},
{"votes":237,"name":"nopreference-r"},
{"votes":65,"name":"keyes"}],
"total":7033,"precincts":
{"total":24,"reporting":12},
"name":"Moore"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Washington"},
"Duplin":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Duplin"},
"Cabarrus":
{"votes":[
{"votes":1349,"name":"mccain"},
{"votes":208,"name":"huckabee"},
{"votes":187,"name":"paul"},
{"votes":90,"name":"keyes"},
{"votes":73,"name":"nopreference-r"}],
"total":1907,"precincts":
{"total":49,"reporting":6},
"name":"Cabarrus"},
"Camden":
{"votes":[
{"votes":275,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":9,"name":"keyes"},
{"votes":6,"name":"nopreference-r"}],
"total":352,"precincts":
{"total":3,"reporting":3},
"name":"Camden"},
"New Hanover":
{"votes":[
{"votes":3199,"name":"mccain"},
{"votes":370,"name":"huckabee"},
{"votes":298,"name":"paul"},
{"votes":116,"name":"nopreference-r"},
{"votes":55,"name":"keyes"}],
"total":4038,"precincts":
{"total":43,"reporting":17},
"name":"New Hanover"},
"Polk":
{"votes":[
{"votes":473,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":30,"name":"paul"},
{"votes":23,"name":"nopreference-r"},
{"votes":10,"name":"keyes"}],
"total":576,"precincts":
{"total":7,"reporting":1},
"name":"Polk"},
"Warren":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Warren"},
"Watauga":
{"votes":[
{"votes":1187,"name":"mccain"},
{"votes":224,"name":"huckabee"},
{"votes":198,"name":"paul"},
{"votes":37,"name":"nopreference-r"},
{"votes":32,"name":"keyes"}],
"total":1678,"precincts":
{"total":20,"reporting":10},
"name":"Watauga"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Jackson"},
"Transylvania":
{"votes":[
{"votes":968,"name":"mccain"},
{"votes":152,"name":"huckabee"},
{"votes":102,"name":"paul"},
{"votes":35,"name":"keyes"},
{"votes":35,"name":"nopreference-r"}],
"total":1292,"precincts":
{"total":18,"reporting":4},
"name":"Transylvania"},
"Caldwell":
{"votes":[
{"votes":2775,"name":"mccain"},
{"votes":514,"name":"huckabee"},
{"votes":163,"name":"nopreference-r"},
{"votes":156,"name":"paul"},
{"votes":45,"name":"keyes"}],
"total":3653,"precincts":
{"total":24,"reporting":9},
"name":"Caldwell"},
"Onslow":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Onslow"},
"Granville":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":3729,"name":"mccain"},
{"votes":693,"name":"paul"},
{"votes":531,"name":"huckabee"},
{"votes":254,"name":"nopreference-r"},
{"votes":116,"name":"keyes"}],
"total":5323,"precincts":
{"total":44,"reporting":42},
"name":"Orange"},
"Burke":
{"votes":[
{"votes":685,"name":"mccain"},
{"votes":160,"name":"huckabee"},
{"votes":39,"name":"paul"},
{"votes":20,"name":"keyes"}],
"total":904,"precincts":
{"total":31,"reporting":3},
"name":"Burke"},
"Lee":
{"votes":[
{"votes":740,"name":"mccain"},
{"votes":79,"name":"huckabee"},
{"votes":20,"name":"paul"},
{"votes":19,"name":"nopreference-r"},
{"votes":9,"name":"keyes"}],
"total":867,"precincts":
{"total":9,"reporting":1},
"name":"Lee"},
"Avery":
{"votes":[
{"votes":700,"name":"mccain"},
{"votes":143,"name":"huckabee"},
{"votes":54,"name":"paul"},
{"votes":54,"name":"nopreference-r"},
{"votes":8,"name":"keyes"}],
"total":959,"precincts":
{"total":20,"reporting":5},
"name":"Avery"},
"Buncombe":
{"votes":[
{"votes":7063,"name":"mccain"},
{"votes":1593,"name":"huckabee"},
{"votes":1534,"name":"paul"},
{"votes":470,"name":"nopreference-r"},
{"votes":342,"name":"keyes"}],
"total":11002,"precincts":
{"total":78,"reporting":78},
"name":"Buncombe"},
"Guilford":
{"votes":[
{"votes":14793,"name":"mccain"},
{"votes":2231,"name":"huckabee"},
{"votes":1017,"name":"paul"},
{"votes":710,"name":"nopreference-r"},
{"votes":524,"name":"keyes"}],
"total":19275,"precincts":
{"total":163,"reporting":87},
"name":"Guilford"},
"Durham":
{"votes":[
{"votes":4831,"name":"mccain"},
{"votes":686,"name":"huckabee"},
{"votes":639,"name":"paul"},
{"votes":306,"name":"nopreference-r"},
{"votes":212,"name":"keyes"}],
"total":6674,"precincts":
{"total":61,"reporting":55},
"name":"Durham"},
"Wake":
{"votes":[
{"votes":32883,"name":"mccain"},
{"votes":5335,"name":"huckabee"},
{"votes":5204,"name":"paul"},
{"votes":1710,"name":"nopreference-r"},
{"votes":1549,"name":"keyes"}],
"total":46681,"precincts":
{"total":210,"reporting":195},
"name":"Wake"},
"Chatham":
{"votes":[
{"votes":570,"name":"mccain"},
{"votes":44,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":24,"name":"nopreference-r"},
{"votes":8,"name":"keyes"}],
"total":683,"precincts":
{"total":19,"reporting":0},
"name":"Chatham"},
"Beaufort":
{"votes":[
{"votes":1462,"name":"mccain"},
{"votes":223,"name":"huckabee"},
{"votes":91,"name":"paul"},
{"votes":45,"name":"nopreference-r"},
{"votes":34,"name":"keyes"}],
"total":1855,"precincts":
{"total":23,"reporting":14},
"name":"Beaufort"},
"Vance":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Vance"},
"Rutherford":
{"votes":[
{"votes":789,"name":"mccain"},
{"votes":177,"name":"huckabee"},
{"votes":63,"name":"paul"},
{"votes":35,"name":"nopreference-r"},
{"votes":27,"name":"keyes"}],
"total":1091,"precincts":
{"total":20,"reporting":5},
"name":"Rutherford"},
"Harnett":
{"votes":[
{"votes":2833,"name":"mccain"},
{"votes":462,"name":"huckabee"},
{"votes":255,"name":"paul"},
{"votes":148,"name":"nopreference-r"},
{"votes":77,"name":"keyes"}],
"total":3775,"precincts":
{"total":18,"reporting":15},
"name":"Harnett"},
"Davie":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Davie"},
"Greene":
{"votes":[
{"votes":32,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"keyes"}],
"total":38,"precincts":
{"total":10,"reporting":3},
"name":"Greene"},
"Pender":
{"votes":[
{"votes":585,"name":"mccain"},
{"votes":62,"name":"huckabee"},
{"votes":54,"name":"paul"},
{"votes":24,"name":"nopreference-r"},
{"votes":8,"name":"keyes"}],
"total":733,"precincts":
{"total":20,"reporting":0},
"name":"Pender"},
"Forsyth":
{"votes":[
{"votes":4080,"name":"mccain"},
{"votes":651,"name":"huckabee"},
{"votes":292,"name":"paul"},
{"votes":233,"name":"nopreference-r"},
{"votes":133,"name":"keyes"}],
"total":5389,"precincts":
{"total":101,"reporting":20},
"name":"Forsyth"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Clay"},
"Macon":
{"votes":[
{"votes":1201,"name":"mccain"},
{"votes":254,"name":"huckabee"},
{"votes":143,"name":"paul"},
{"votes":56,"name":"nopreference-r"},
{"votes":28,"name":"keyes"}],
"total":1682,"precincts":
{"total":15,"reporting":7},
"name":"Macon"},
"Chowan":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Chowan"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Madison"},
"Gaston":
{"votes":[
{"votes":3988,"name":"mccain"},
{"votes":716,"name":"huckabee"},
{"votes":499,"name":"paul"},
{"votes":255,"name":"keyes"},
{"votes":242,"name":"nopreference-r"}],
"total":5700,"precincts":
{"total":46,"reporting":26},
"name":"Gaston"},
"Northampton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Northampton"},
"Swain":
{"votes":[
{"votes":377,"name":"mccain"},
{"votes":90,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":13,"name":"nopreference-r"},
{"votes":9,"name":"keyes"}],
"total":526,"precincts":
{"total":5,"reporting":5},
"name":"Swain"},
"Hyde":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Hyde"},
"Stanly":
{"votes":[
{"votes":1869,"name":"mccain"},
{"votes":309,"name":"huckabee"},
{"votes":100,"name":"paul"},
{"votes":90,"name":"nopreference-r"},
{"votes":42,"name":"keyes"}],
"total":2410,"precincts":
{"total":24,"reporting":8},
"name":"Stanly"},
"Graham":
{"votes":[
{"votes":741,"name":"mccain"},
{"votes":187,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":21,"name":"nopreference-r"},
{"votes":14,"name":"keyes"}],
"total":988,"precincts":
{"total":4,"reporting":4},
"name":"Graham"},
"Lenoir":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lenoir"},
"Hertford":
{"votes":[
{"votes":155,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":8,"name":"nopreference-r"},
{"votes":6,"name":"paul"},
{"votes":2,"name":"keyes"}],
"total":193,"precincts":
{"total":13,"reporting":6},
"name":"Hertford"},
"Scotland":
{"votes":[
{"votes":544,"name":"mccain"},
{"votes":65,"name":"huckabee"},
{"votes":57,"name":"paul"},
{"votes":27,"name":"nopreference-r"},
{"votes":10,"name":"keyes"}],
"total":703,"precincts":
{"total":10,"reporting":10},
"name":"Scotland"},
"Richmond":
{"votes":[
{"votes":211,"name":"mccain"},
{"votes":16,"name":"paul"},
{"votes":12,"name":"huckabee"},
{"votes":10,"name":"nopreference-r"},
{"votes":3,"name":"keyes"}],
"total":252,"precincts":
{"total":16,"reporting":1},
"name":"Richmond"},
"Davidson":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Davidson"},
"Columbus":
{"votes":[
{"votes":524,"name":"mccain"},
{"votes":59,"name":"huckabee"},
{"votes":41,"name":"nopreference-r"},
{"votes":32,"name":"paul"},
{"votes":10,"name":"keyes"}],
"total":666,"precincts":
{"total":29,"reporting":19},
"name":"Columbus"},
"Mitchell":
{"votes":[
{"votes":462,"name":"mccain"},
{"votes":84,"name":"huckabee"},
{"votes":59,"name":"paul"},
{"votes":15,"name":"nopreference-r"},
{"votes":7,"name":"keyes"}],
"total":627,"precincts":
{"total":9,"reporting":5},
"name":"Mitchell"},
"Bertie":
{"votes":[
{"votes":126,"name":"mccain"},
{"votes":17,"name":"huckabee"},
{"votes":6,"name":"nopreference-r"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"paul"}],
"total":151,"precincts":
{"total":12,"reporting":8},
"name":"Bertie"},
"Alexander":
{"votes":[
{"votes":1307,"name":"mccain"},
{"votes":251,"name":"huckabee"},
{"votes":84,"name":"paul"},
{"votes":53,"name":"nopreference-r"},
{"votes":20,"name":"keyes"}],
"total":1715,"precincts":
{"total":18,"reporting":11},
"name":"Alexander"},
"Lincoln":
{"votes":[
{"votes":5434,"name":"mccain"},
{"votes":976,"name":"huckabee"},
{"votes":538,"name":"paul"},
{"votes":317,"name":"nopreference-r"},
{"votes":202,"name":"keyes"}],
"total":7467,"precincts":
{"total":28,"reporting":28},
"name":"Lincoln"},
"Sampson":
{"votes":[
{"votes":2191,"name":"mccain"},
{"votes":253,"name":"huckabee"},
{"votes":89,"name":"paul"},
{"votes":78,"name":"nopreference-r"},
{"votes":26,"name":"keyes"}],
"total":2637,"precincts":
{"total":23,"reporting":21},
"name":"Sampson"},
"Edgecombe":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Edgecombe"},
"Ashe":
{"votes":[
{"votes":2042,"name":"mccain"},
{"votes":378,"name":"huckabee"},
{"votes":145,"name":"paul"},
{"votes":116,"name":"nopreference-r"},
{"votes":29,"name":"keyes"}],
"total":2710,"precincts":
{"total":17,"reporting":17},
"name":"Ashe"},
"Craven":
{"votes":[
{"votes":509,"name":"mccain"},
{"votes":63,"name":"huckabee"},
{"votes":39,"name":"paul"},
{"votes":22,"name":"nopreference-r"},
{"votes":11,"name":"keyes"}],
"total":644,"precincts":
{"total":27,"reporting":5},
"name":"Craven"},
"Iredell":
{"votes":[
{"votes":6260,"name":"mccain"},
{"votes":861,"name":"huckabee"},
{"votes":379,"name":"paul"},
{"votes":368,"name":"nopreference-r"},
{"votes":206,"name":"keyes"}],
"total":8074,"precincts":
{"total":29,"reporting":19},
"name":"Iredell"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Franklin"},
"Carteret":
{"votes":[
{"votes":2450,"name":"mccain"},
{"votes":263,"name":"huckabee"},
{"votes":123,"name":"paul"},
{"votes":92,"name":"nopreference-r"},
{"votes":77,"name":"keyes"}],
"total":3005,"precincts":
{"total":34,"reporting":16},
"name":"Carteret"},
"Johnston":
{"votes":[
{"votes":1861,"name":"mccain"},
{"votes":1246,"name":"paul"},
{"votes":392,"name":"huckabee"},
{"votes":205,"name":"keyes"},
{"votes":135,"name":"nopreference-r"}],
"total":3839,"precincts":
{"total":37,"reporting":12},
"name":"Johnston"},
"Nash":
{"votes":[
{"votes":3443,"name":"mccain"},
{"votes":549,"name":"huckabee"},
{"votes":258,"name":"paul"},
{"votes":166,"name":"nopreference-r"},
{"votes":82,"name":"keyes"}],
"total":4498,"precincts":
{"total":26,"reporting":18},
"name":"Nash"},
"Tyrrell":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Tyrrell"},
"Caswell":
{"votes":[
{"votes":68,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"nopreference-r"}],
"total":86,"precincts":
{"total":11,"reporting":1},
"name":"Caswell"},
"Cleveland":
{"votes":[
{"votes":1476,"name":"mccain"},
{"votes":278,"name":"huckabee"},
{"votes":165,"name":"paul"},
{"votes":79,"name":"keyes"},
{"votes":69,"name":"nopreference-r"}],
"total":2067,"precincts":
{"total":28,"reporting":11},
"name":"Cleveland"},
"Halifax":
{"votes":[
{"votes":339,"name":"mccain"},
{"votes":45,"name":"huckabee"},
{"votes":16,"name":"nopreference-r"},
{"votes":13,"name":"paul"},
{"votes":6,"name":"keyes"}],
"total":419,"precincts":
{"total":30,"reporting":11},
"name":"Halifax"},
"Cumberland":
{"votes":[
{"votes":3663,"name":"mccain"},
{"votes":455,"name":"huckabee"},
{"votes":189,"name":"paul"},
{"votes":156,"name":"nopreference-r"},
{"votes":114,"name":"keyes"}],
"total":4577,"precincts":
{"total":69,"reporting":21},
"name":"Cumberland"},
"Rockingham":
{"votes":[
{"votes":3372,"name":"mccain"},
{"votes":728,"name":"huckabee"},
{"votes":221,"name":"nopreference-r"},
{"votes":203,"name":"paul"},
{"votes":57,"name":"keyes"}],
"total":4581,"precincts":
{"total":20,"reporting":19},
"name":"Rockingham"},
"Rowan":
{"votes":[
{"votes":3130,"name":"mccain"},
{"votes":463,"name":"huckabee"},
{"votes":243,"name":"paul"},
{"votes":179,"name":"nopreference-r"},
{"votes":93,"name":"keyes"}],
"total":4108,"precincts":
{"total":44,"reporting":19},
"name":"Rowan"},
"Alleghany":
{"votes":[
{"votes":202,"name":"mccain"},
{"votes":17,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":7,"name":"nopreference-r"},
{"votes":1,"name":"keyes"}],
"total":241,"precincts":
{"total":7,"reporting":0},
"name":"Alleghany"},
"McDowell":
{"votes":[
{"votes":855,"name":"mccain"},
{"votes":217,"name":"huckabee"},
{"votes":80,"name":"nopreference-r"},
{"votes":69,"name":"paul"},
{"votes":21,"name":"keyes"}],
"total":1242,"precincts":
{"total":17,"reporting":11},
"name":"McDowell"},
"Haywood":
{"votes":[
{"votes":1838,"name":"mccain"},
{"votes":400,"name":"huckabee"},
{"votes":286,"name":"paul"},
{"votes":130,"name":"nopreference-r"},
{"votes":60,"name":"keyes"}],
"total":2714,"precincts":
{"total":29,"reporting":22},
"name":"Haywood"},
"Pamlico":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Pamlico"},
"Dare":
{"votes":[
{"votes":239,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":15,"name":"nopreference-r"},
{"votes":13,"name":"paul"},
{"votes":11,"name":"keyes"}],
"total":300,"precincts":
{"total":16,"reporting":1},
"name":"Dare"},
"Jones":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"paul"}],
"total":27,"precincts":
{"total":7,"reporting":1},
"name":"Jones"},
"Pitt":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Pitt"},
"Martin":
{"votes":[
{"votes":139,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":8,"name":"nopreference-r"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"keyes"}],
"total":181,"precincts":
{"total":13,"reporting":3},
"name":"Martin"},
"Mecklenburg":
{"votes":[
{"votes":11360,"name":"mccain"},
{"votes":1161,"name":"paul"},
{"votes":1055,"name":"huckabee"},
{"votes":573,"name":"nopreference-r"},
{"votes":494,"name":"keyes"}],
"total":14643,"precincts":
{"total":198,"reporting":34},
"name":"Mecklenburg"},
"Gates":
{"votes":[
{"votes":243,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":13,"name":"nopreference-r"},
{"votes":7,"name":"paul"},
{"votes":2,"name":"keyes"}],
"total":296,"precincts":
{"total":6,"reporting":6},
"name":"Gates"},
"Person":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Person"},
"Yancey":
{"votes":[
{"votes":972,"name":"mccain"},
{"votes":309,"name":"huckabee"},
{"votes":125,"name":"paul"},
{"votes":65,"name":"nopreference-r"},
{"votes":30,"name":"keyes"}],
"total":1501,"precincts":
{"total":11,"reporting":11},
"name":"Yancey"},
"Surry":
{"votes":[
{"votes":2328,"name":"mccain"},
{"votes":404,"name":"huckabee"},
{"votes":126,"name":"paul"},
{"votes":107,"name":"nopreference-r"},
{"votes":47,"name":"keyes"}],
"total":3012,"precincts":
{"total":32,"reporting":22},
"name":"Surry"},
"Perquimans":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Perquimans"},
"Randolph":
{"votes":[
{"votes":5687,"name":"mccain"},
{"votes":1340,"name":"huckabee"},
{"votes":517,"name":"paul"},
{"votes":287,"name":"nopreference-r"},
{"votes":102,"name":"keyes"}],
"total":7933,"precincts":
{"total":42,"reporting":32},
"name":"Randolph"}}})