GoogleElectionMap.votesReady({"status":"ok","totals":
{"name":"Nebraska","precincts":
{"total":1665,"reporting":1665},
"votes":[
{"votes":17321,"name":"clinton","delegates":8},
{"votes":16725,"name":"obama","delegates":16},
{"votes":1399,"name":"gravel"},
{"votes":99,"name":"uncommitted-d"}],
"delegates":24,"date":"02-09","type":"caucus"},
"state":"NE","party":"dem","total":35544,"locals":
{"Colfax":
{"votes":[
{"votes":241,"name":"clinton"},
{"votes":220,"name":"obama"},
{"votes":31,"name":"gravel"}],
"total":492,"precincts":
{"total":6,"reporting":6},
"name":"Colfax"},
"Sherman":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Sherman"},
"Furnas":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Furnas"},
"Frontier":
{"votes":[
{"votes":32,"name":"obama"},
{"votes":25,"name":"clinton"},
{"votes":8,"name":"gravel"}],
"total":65,"precincts":
{"total":6,"reporting":4},
"name":"Frontier"},
"Banner":
{"votes":[
{"votes":8,"name":"obama"},
{"votes":4,"name":"clinton"}],
"total":12,"precincts":
{"total":1,"reporting":1},
"name":"Banner"},
"Otoe":
{"votes":[
{"votes":346,"name":"clinton"},
{"votes":268,"name":"obama"},
{"votes":37,"name":"gravel"}],
"total":651,"precincts":
{"total":17,"reporting":15},
"name":"Otoe"},
"Wayne":
{"votes":[
{"votes":240,"name":"obama"},
{"votes":157,"name":"clinton"},
{"votes":17,"name":"gravel"}],
"total":414,"precincts":
{"total":11,"reporting":5},
"name":"Wayne"},
"Dixon":
{"votes":[
{"votes":58,"name":"clinton"},
{"votes":56,"name":"obama"},
{"votes":5,"name":"gravel"}],
"total":119,"precincts":
{"total":12,"reporting":6},
"name":"Dixon"},
"Hooker":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Hooker"},
"Dodge":
{"votes":[
{"votes":695,"name":"clinton"},
{"votes":505,"name":"obama"},
{"votes":48,"name":"gravel"}],
"total":1248,"precincts":
{"total":32,"reporting":2},
"name":"Dodge"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Brown"},
"Stanton":
{"votes":[
{"votes":26,"name":"obama"},
{"votes":16,"name":"clinton"},
{"votes":2,"name":"gravel"}],
"total":44,"precincts":
{"total":16,"reporting":6},
"name":"Stanton"},
"Sarpy":
{"votes":[
{"votes":690,"name":"clinton"},
{"votes":655,"name":"obama"},
{"votes":59,"name":"gravel"}],
"total":1404,"precincts":
{"total":88,"reporting":0},
"name":"Sarpy"},
"Kearney":
{"votes":[
{"votes":171,"name":"obama"},
{"votes":157,"name":"clinton"},
{"votes":16,"name":"gravel"}],
"total":344,"precincts":
{"total":13,"reporting":12},
"name":"Kearney"},
"Burt":
{"votes":[
{"votes":71,"name":"obama"},
{"votes":70,"name":"clinton"},
{"votes":4,"name":"gravel"}],
"total":145,"precincts":
{"total":12,"reporting":4},
"name":"Burt"},
"York":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"York"},
"Grant":
{"votes":[
{"votes":13,"name":"clinton"},
{"votes":7,"name":"obama"},
{"votes":4,"name":"gravel"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Grant"},
"Hitchcock":
{"votes":[
{"votes":53,"name":"obama"},
{"votes":52,"name":"clinton"},
{"votes":10,"name":"gravel"}],
"total":115,"precincts":
{"total":4,"reporting":3},
"name":"Hitchcock"},
"Loup":
{"votes":[
{"votes":17,"name":"obama"},
{"votes":8,"name":"clinton"},
{"votes":1,"name":"gravel"}],
"total":26,"precincts":
{"total":1,"reporting":0},
"name":"Loup"},
"Morrill":
{"votes":[
{"votes":33,"name":"clinton"},
{"votes":7,"name":"obama"},
{"votes":2,"name":"gravel"}],
"total":42,"precincts":
{"total":10,"reporting":3},
"name":"Morrill"},
"Box Butte":
{"votes":[
{"votes":192,"name":"clinton"},
{"votes":171,"name":"obama"},
{"votes":17,"name":"gravel"}],
"total":380,"precincts":
{"total":9,"reporting":9},
"name":"Box Butte"},
"Webster":
{"votes":[
{"votes":94,"name":"clinton"},
{"votes":63,"name":"obama"},
{"votes":13,"name":"gravel"}],
"total":170,"precincts":
{"total":6,"reporting":3},
"name":"Webster"},
"Seward":
{"votes":[
{"votes":369,"name":"clinton"},
{"votes":341,"name":"obama"},
{"votes":24,"name":"gravel"}],
"total":734,"precincts":
{"total":17,"reporting":17},
"name":"Seward"},
"Kimball":
{"votes":[
{"votes":10,"name":"clinton"},
{"votes":2,"name":"obama"},
{"votes":1,"name":"gravel"}],
"total":13,"precincts":
{"total":6,"reporting":1},
"name":"Kimball"},
"Thomas":
{"votes":[
{"votes":13,"name":"obama"},
{"votes":11,"name":"clinton"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Thomas"},
"Saunders":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Saunders"},
"Dawes":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Dawes"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Washington"},
"Dakota":
{"votes":[
{"votes":262,"name":"clinton"},
{"votes":144,"name":"obama"},
{"votes":11,"name":"gravel"}],
"total":417,"precincts":
{"total":14,"reporting":2},
"name":"Dakota"},
"Polk":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Polk"},
"Chase":
{"votes":[
{"votes":24,"name":"clinton"},
{"votes":15,"name":"obama"},
{"votes":7,"name":"gravel"}],
"total":46,"precincts":
{"total":6,"reporting":2},
"name":"Chase"},
"Deuel":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Deuel"},
"Howard":
{"votes":[
{"votes":11,"name":"obama"},
{"votes":7,"name":"clinton"},
{"votes":1,"name":"gravel"}],
"total":19,"precincts":
{"total":9,"reporting":1},
"name":"Howard"},
"Pierce":
{"votes":[
{"votes":10,"name":"clinton"},
{"votes":3,"name":"obama"}],
"total":13,"precincts":
{"total":6,"reporting":1},
"name":"Pierce"},
"Jefferson":
{"votes":[
{"votes":35,"name":"clinton"},
{"votes":15,"name":"obama"}],
"total":50,"precincts":
{"total":11,"reporting":1},
"name":"Jefferson"},
"Cheyenne":
{"votes":[
{"votes":59,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":10,"name":"gravel"}],
"total":111,"precincts":
{"total":10,"reporting":1},
"name":"Cheyenne"},
"Butler":
{"votes":[
{"votes":279,"name":"clinton"},
{"votes":213,"name":"obama"},
{"votes":48,"name":"gravel"}],
"total":540,"precincts":
{"total":21,"reporting":21},
"name":"Butler"},
"McPherson":
{"votes":[
{"votes":11,"name":"clinton"},
{"votes":5,"name":"obama"},
{"votes":4,"name":"gravel"}],
"total":20,"precincts":
{"total":1,"reporting":1},
"name":"McPherson"},
"Boyd":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Boyd"},
"Holt":
{"votes":[
{"votes":52,"name":"clinton"},
{"votes":32,"name":"obama"},
{"votes":4,"name":"gravel"}],
"total":88,"precincts":
{"total":14,"reporting":2},
"name":"Holt"},
"Hamilton":
{"votes":[
{"votes":81,"name":"obama"},
{"votes":64,"name":"clinton"},
{"votes":15,"name":"gravel"}],
"total":160,"precincts":
{"total":12,"reporting":0},
"name":"Hamilton"},
"Cuming":
{"votes":[
{"votes":76,"name":"obama"},
{"votes":57,"name":"clinton"},
{"votes":9,"name":"gravel"}],
"total":142,"precincts":
{"total":8,"reporting":3},
"name":"Cuming"},
"Keith":
{"votes":[
{"votes":177,"name":"clinton"},
{"votes":156,"name":"obama"},
{"votes":27,"name":"gravel"}],
"total":360,"precincts":
{"total":12,"reporting":0},
"name":"Keith"},
"Sioux":
{"votes":[
{"votes":12,"name":"obama"},
{"votes":11,"name":"clinton"},
{"votes":3,"name":"gravel"}],
"total":26,"precincts":
{"total":2,"reporting":1},
"name":"Sioux"},
"Johnson":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Johnson"},
"Arthur":
{"votes":[
{"votes":15,"name":"obama"},
{"votes":10,"name":"clinton"},
{"votes":2,"name":"gravel"}],
"total":27,"precincts":
{"total":1,"reporting":1},
"name":"Arthur"},
"Clay":
{"votes":[
{"votes":18,"name":"obama"},
{"votes":15,"name":"clinton"},
{"votes":6,"name":"gravel"}],
"total":39,"precincts":
{"total":12,"reporting":1},
"name":"Clay"},
"Buffalo":
{"votes":[
{"votes":85,"name":"clinton"},
{"votes":56,"name":"obama"},
{"votes":9,"name":"gravel"}],
"total":150,"precincts":
{"total":32,"reporting":2},
"name":"Buffalo"},
"Madison":
{"votes":[
{"votes":592,"name":"obama"},
{"votes":494,"name":"clinton"},
{"votes":63,"name":"gravel"}],
"total":1149,"precincts":
{"total":24,"reporting":20},
"name":"Madison"},
"Custer":
{"votes":[
{"votes":163,"name":"clinton"},
{"votes":157,"name":"obama"},
{"votes":17,"name":"gravel"}],
"total":337,"precincts":
{"total":39,"reporting":14},
"name":"Custer"},
"Red Willow":
{"votes":[
{"votes":141,"name":"clinton"},
{"votes":110,"name":"obama"},
{"votes":23,"name":"gravel"}],
"total":274,"precincts":
{"total":16,"reporting":8},
"name":"Red Willow"},
"Blaine":
{"votes":[
{"votes":8,"name":"obama"},
{"votes":5,"name":"clinton"},
{"votes":3,"name":"gravel"}],
"total":16,"precincts":
{"total":1,"reporting":0},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":354,"name":"clinton"},
{"votes":322,"name":"obama"},
{"votes":52,"name":"gravel"}],
"total":728,"precincts":
{"total":20,"reporting":20},
"name":"Dawson"},
"Saline":
{"votes":[
{"votes":204,"name":"clinton"},
{"votes":118,"name":"obama"},
{"votes":9,"name":"gravel"}],
"total":331,"precincts":
{"total":13,"reporting":4},
"name":"Saline"},
"Cass":
{"votes":[
{"votes":143,"name":"clinton"},
{"votes":110,"name":"obama"},
{"votes":16,"name":"gravel"}],
"total":269,"precincts":
{"total":31,"reporting":29},
"name":"Cass"},
"Nemaha":
{"votes":[
{"votes":30,"name":"obama"},
{"votes":28,"name":"clinton"},
{"votes":1,"name":"gravel"}],
"total":59,"precincts":
{"total":10,"reporting":0},
"name":"Nemaha"},
"Rock":
{"votes":[
{"votes":3,"name":"gravel"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"obama"}],
"total":7,"precincts":
{"total":6,"reporting":0},
"name":"Rock"},
"Gage":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Gage"},
"CD1":
{"votes":[
{"votes":10041,"name":"obama"},
{"votes":5288,"name":"clinton"},
{"votes":85,"name":"uncommitted-d"}],
"total":15414,"precincts":
{"total":576,"reporting":576},
"name":"CD1"},
"CD2":
{"votes":[
{"votes":12252,"name":"obama"},
{"votes":3709,"name":"clinton"}],
"total":15961,"precincts":
{"total":422,"reporting":422},
"name":"CD2"},
"CD3":
{"votes":[
{"votes":3833,"name":"obama"},
{"votes":3448,"name":"clinton"},
{"votes":14,"name":"uncommitted-d"}],
"total":7295,"precincts":
{"total":667,"reporting":667},
"name":"CD3"},
"Wheeler":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Wheeler"},
"Cedar":
{"votes":[
{"votes":190,"name":"obama"},
{"votes":129,"name":"clinton"},
{"votes":18,"name":"gravel"}],
"total":337,"precincts":
{"total":17,"reporting":17},
"name":"Cedar"},
"Dundy":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Dundy"},
"Lincoln":
{"votes":[
{"votes":272,"name":"clinton"},
{"votes":183,"name":"obama"},
{"votes":27,"name":"gravel"}],
"total":482,"precincts":
{"total":27,"reporting":4},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":181,"name":"clinton"},
{"votes":149,"name":"obama"},
{"votes":14,"name":"gravel"}],
"total":344,"precincts":
{"total":28,"reporting":7},
"name":"Adams"},
"Hayes":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Hayes"},
"Harlan":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Harlan"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Franklin"},
"Richardson":
{"votes":[
{"votes":59,"name":"clinton"},
{"votes":30,"name":"obama"},
{"votes":5,"name":"gravel"}],
"total":94,"precincts":
{"total":15,"reporting":0},
"name":"Richardson"},
"Antelope":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Antelope"},
"Fillmore":
{"votes":[
{"votes":186,"name":"clinton"},
{"votes":139,"name":"obama"},
{"votes":14,"name":"gravel"}],
"total":339,"precincts":
{"total":11,"reporting":10},
"name":"Fillmore"},
"Greeley":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Greeley"},
"Lancaster":
{"votes":[
{"votes":4131,"name":"clinton"},
{"votes":3663,"name":"obama"},
{"votes":150,"name":"gravel"}],
"total":7944,"precincts":
{"total":223,"reporting":32},
"name":"Lancaster"},
"Cherry":
{"votes":[
{"votes":147,"name":"clinton"},
{"votes":114,"name":"obama"},
{"votes":28,"name":"gravel"}],
"total":289,"precincts":
{"total":21,"reporting":21},
"name":"Cherry"},
"Douglas":
{"votes":[
{"votes":5578,"name":"obama"},
{"votes":4522,"name":"clinton"},
{"votes":325,"name":"gravel"}],
"total":10425,"precincts":
{"total":352,"reporting":123},
"name":"Douglas"},
"Valley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Valley"},
"Garden":
{"votes":[
{"votes":47,"name":"obama"},
{"votes":39,"name":"clinton"},
{"votes":6,"name":"gravel"}],
"total":92,"precincts":
{"total":5,"reporting":4},
"name":"Garden"},
"Phelps":
{"votes":[
{"votes":17,"name":"clinton"},
{"votes":12,"name":"obama"}],
"total":29,"precincts":
{"total":13,"reporting":1},
"name":"Phelps"},
"Thurston":
{"votes":[
{"votes":186,"name":"obama"},
{"votes":135,"name":"clinton"},
{"votes":14,"name":"gravel"}],
"total":335,"precincts":
{"total":10,"reporting":9},
"name":"Thurston"},
"Logan":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Logan"},
"Merrick":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Merrick"},
"Nuckolls":
{"votes":[
{"votes":42,"name":"clinton"},
{"votes":32,"name":"obama"},
{"votes":8,"name":"gravel"}],
"total":82,"precincts":
{"total":9,"reporting":1},
"name":"Nuckolls"},
"Knox":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Knox"},
"Platte":
{"votes":[
{"votes":293,"name":"obama"},
{"votes":231,"name":"clinton"},
{"votes":38,"name":"gravel"}],
"total":562,"precincts":
{"total":31,"reporting":9},
"name":"Platte"},
"Hall":
{"votes":[
{"votes":679,"name":"clinton"},
{"votes":408,"name":"obama"},
{"votes":42,"name":"gravel"}],
"total":1129,"precincts":
{"total":40,"reporting":26},
"name":"Hall"},
"Scotts Bluff":
{"votes":[
{"votes":243,"name":"clinton"},
{"votes":181,"name":"obama"},
{"votes":17,"name":"gravel"}],
"total":441,"precincts":
{"total":31,"reporting":12},
"name":"Scotts Bluff"},
"Sheridan":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Sheridan"},
"Gosper":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Gosper"},
"Nance":
{"votes":[
{"votes":198,"name":"clinton"},
{"votes":138,"name":"obama"},
{"votes":29,"name":"gravel"}],
"total":365,"precincts":
{"total":7,"reporting":7},
"name":"Nance"},
"Boone":
{"votes":[
{"votes":128,"name":"clinton"},
{"votes":74,"name":"obama"},
{"votes":17,"name":"gravel"}],
"total":219,"precincts":
{"total":10,"reporting":5},
"name":"Boone"},
"Keya Paha":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Keya Paha"},
"Pawnee":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Pawnee"},
"Perkins":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Perkins"},
"Garfield":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Garfield"},
"Thayer":
{"votes":[
{"votes":48,"name":"clinton"},
{"votes":40,"name":"obama"},
{"votes":5,"name":"gravel"}],
"total":93,"precincts":
{"total":8,"reporting":3},
"name":"Thayer"}}})