GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[],
"name":"Nebraska","precincts":
{"total":1699,"reporting":0},
"delegates":33,"date":"05-13"},
"state":"NE","party":"gop","total":0,"locals":
{"Colfax":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Colfax"},
"Sherman":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Sherman"},
"Furnas":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Furnas"},
"Frontier":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Frontier"},
"Banner":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Banner"},
"Otoe":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Otoe"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Wayne"},
"Dixon":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Dixon"},
"Hooker":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Hooker"},
"Dodge":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Dodge"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Brown"},
"Stanton":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Stanton"},
"Sarpy":
{"votes":[],
"total":0,"precincts":
{"total":88,"reporting":0},
"name":"Sarpy"},
"Kearney":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Kearney"},
"Burt":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Burt"},
"York":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"York"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Grant"},
"Hitchcock":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Hitchcock"},
"Loup":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Loup"},
"Morrill":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Morrill"},
"Box Butte":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Box Butte"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Webster"},
"Seward":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Seward"},
"Kimball":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Kimball"},
"Thomas":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Thomas"},
"Saunders":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Saunders"},
"Dawes":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Dawes"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Washington"},
"Dakota":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Dakota"},
"Polk":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Polk"},
"Chase":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Chase"},
"Deuel":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Deuel"},
"Howard":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Howard"},
"Pierce":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Pierce"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Jefferson"},
"Cheyenne":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Cheyenne"},
"Butler":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Butler"},
"McPherson":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"McPherson"},
"Boyd":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Boyd"},
"Holt":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Holt"},
"Hamilton":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Hamilton"},
"Cuming":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Cuming"},
"Keith":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Keith"},
"Sioux":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Sioux"},
"Johnson":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Johnson"},
"Arthur":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Arthur"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Clay"},
"Buffalo":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Buffalo"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Madison"},
"Custer":
{"votes":[],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Custer"},
"Red Willow":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Red Willow"},
"Blaine":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Blaine"},
"Dawson":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Dawson"},
"Saline":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Saline"},
"Cass":
{"votes":[],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Cass"},
"Nemaha":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Nemaha"},
"Rock":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Rock"},
"Gage":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Gage"},
"CD1":
{"votes":[],
"total":0,"name":"CD1"},
"CD2":
{"votes":[],
"total":0,"name":"CD2"},
"CD3":
{"votes":[],
"total":0,"name":"CD3"},
"Wheeler":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Wheeler"},
"Cedar":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Cedar"},
"Dundy":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Dundy"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Lincoln"},
"Adams":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Adams"},
"Hayes":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Hayes"},
"Harlan":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Harlan"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Franklin"},
"Richardson":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Richardson"},
"Antelope":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Antelope"},
"Fillmore":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Fillmore"},
"Greeley":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Greeley"},
"Lancaster":
{"votes":[],
"total":0,"precincts":
{"total":223,"reporting":0},
"name":"Lancaster"},
"Cherry":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Cherry"},
"Douglas":
{"votes":[],
"total":0,"precincts":
{"total":352,"reporting":0},
"name":"Douglas"},
"Valley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Valley"},
"Garden":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Garden"},
"Phelps":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Phelps"},
"Thurston":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Thurston"},
"Logan":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Logan"},
"Merrick":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Merrick"},
"Nuckolls":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Nuckolls"},
"Knox":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Knox"},
"Platte":
{"votes":[],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Platte"},
"Hall":
{"votes":[],
"total":0,"precincts":
{"total":40,"reporting":0},
"name":"Hall"},
"Scotts Bluff":
{"votes":[],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Scotts Bluff"},
"Sheridan":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Sheridan"},
"Gosper":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Gosper"},
"Nance":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Nance"},
"Boone":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Boone"},
"Keya Paha":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Keya Paha"},
"Pawnee":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Pawnee"},
"Perkins":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Perkins"},
"Garfield":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Garfield"},
"Thayer":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Thayer"}}})