GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":59707,"name":"mccain"},
{"votes":8294,"name":"paul"}],
"name":"Nebraska","precincts":
{"total":1699,"reporting":770},
"delegates":33,"date":"05-13"},
"state":"NE","party":"gop","total":68001,"locals":
{"Colfax":
{"votes":[
{"votes":631,"name":"mccain"},
{"votes":77,"name":"paul"}],
"total":708,"precincts":
{"total":6,"reporting":6},
"name":"Colfax"},
"Sherman":
{"votes":[
{"votes":195,"name":"mccain"},
{"votes":21,"name":"paul"}],
"total":216,"precincts":
{"total":6,"reporting":4},
"name":"Sherman"},
"Furnas":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Furnas"},
"Frontier":
{"votes":[
{"votes":389,"name":"mccain"},
{"votes":54,"name":"paul"}],
"total":443,"precincts":
{"total":6,"reporting":5},
"name":"Frontier"},
"Banner":
{"votes":[
{"votes":85,"name":"mccain"},
{"votes":15,"name":"paul"}],
"total":100,"precincts":
{"total":1,"reporting":1},
"name":"Banner"},
"Otoe":
{"votes":[
{"votes":854,"name":"mccain"},
{"votes":154,"name":"paul"}],
"total":1008,"precincts":
{"total":17,"reporting":15},
"name":"Otoe"},
"Wayne":
{"votes":[
{"votes":894,"name":"mccain"},
{"votes":114,"name":"paul"}],
"total":1008,"precincts":
{"total":11,"reporting":5},
"name":"Wayne"},
"Dixon":
{"votes":[
{"votes":171,"name":"mccain"},
{"votes":20,"name":"paul"}],
"total":191,"precincts":
{"total":12,"reporting":6},
"name":"Dixon"},
"Hooker":
{"votes":[
{"votes":128,"name":"mccain"},
{"votes":10,"name":"paul"}],
"total":138,"precincts":
{"total":2,"reporting":2},
"name":"Hooker"},
"Dodge":
{"votes":[
{"votes":1621,"name":"mccain"},
{"votes":229,"name":"paul"}],
"total":1850,"precincts":
{"total":32,"reporting":2},
"name":"Dodge"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Brown"},
"Stanton":
{"votes":[
{"votes":211,"name":"mccain"},
{"votes":43,"name":"paul"}],
"total":254,"precincts":
{"total":16,"reporting":10},
"name":"Stanton"},
"Sarpy":
{"votes":[
{"votes":2050,"name":"mccain"},
{"votes":250,"name":"paul"}],
"total":2300,"precincts":
{"total":88,"reporting":0},
"name":"Sarpy"},
"Kearney":
{"votes":[
{"votes":650,"name":"mccain"},
{"votes":90,"name":"paul"}],
"total":740,"precincts":
{"total":13,"reporting":12},
"name":"Kearney"},
"Burt":
{"votes":[
{"votes":143,"name":"mccain"},
{"votes":18,"name":"paul"}],
"total":161,"precincts":
{"total":12,"reporting":4},
"name":"Burt"},
"York":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"York"},
"Grant":
{"votes":[
{"votes":98,"name":"mccain"},
{"votes":5,"name":"paul"}],
"total":103,"precincts":
{"total":1,"reporting":1},
"name":"Grant"},
"Hitchcock":
{"votes":[
{"votes":197,"name":"mccain"},
{"votes":30,"name":"paul"}],
"total":227,"precincts":
{"total":4,"reporting":3},
"name":"Hitchcock"},
"Loup":
{"votes":[
{"votes":101,"name":"mccain"},
{"votes":12,"name":"paul"}],
"total":113,"precincts":
{"total":1,"reporting":1},
"name":"Loup"},
"Morrill":
{"votes":[
{"votes":111,"name":"mccain"},
{"votes":22,"name":"paul"}],
"total":133,"precincts":
{"total":10,"reporting":3},
"name":"Morrill"},
"Box Butte":
{"votes":[
{"votes":631,"name":"mccain"},
{"votes":81,"name":"paul"}],
"total":712,"precincts":
{"total":9,"reporting":9},
"name":"Box Butte"},
"Webster":
{"votes":[
{"votes":431,"name":"mccain"},
{"votes":59,"name":"paul"}],
"total":490,"precincts":
{"total":6,"reporting":6},
"name":"Webster"},
"Seward":
{"votes":[
{"votes":913,"name":"mccain"},
{"votes":188,"name":"paul"}],
"total":1101,"precincts":
{"total":17,"reporting":17},
"name":"Seward"},
"Kimball":
{"votes":[
{"votes":393,"name":"mccain"},
{"votes":31,"name":"paul"}],
"total":424,"precincts":
{"total":6,"reporting":6},
"name":"Kimball"},
"Thomas":
{"votes":[
{"votes":122,"name":"mccain"},
{"votes":12,"name":"paul"}],
"total":134,"precincts":
{"total":1,"reporting":1},
"name":"Thomas"},
"Saunders":
{"votes":[
{"votes":1364,"name":"mccain"},
{"votes":295,"name":"paul"}],
"total":1659,"precincts":
{"total":19,"reporting":19},
"name":"Saunders"},
"Dawes":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Dawes"},
"Washington":
{"votes":[
{"votes":445,"name":"mccain"},
{"votes":69,"name":"paul"}],
"total":514,"precincts":
{"total":16,"reporting":3},
"name":"Washington"},
"Dakota":
{"votes":[
{"votes":815,"name":"mccain"},
{"votes":95,"name":"paul"}],
"total":910,"precincts":
{"total":14,"reporting":14},
"name":"Dakota"},
"Polk":
{"votes":[
{"votes":586,"name":"mccain"},
{"votes":63,"name":"paul"}],
"total":649,"precincts":
{"total":7,"reporting":7},
"name":"Polk"},
"Chase":
{"votes":[
{"votes":335,"name":"mccain"},
{"votes":45,"name":"paul"}],
"total":380,"precincts":
{"total":6,"reporting":4},
"name":"Chase"},
"Deuel":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Deuel"},
"Howard":
{"votes":[
{"votes":34,"name":"mccain"},
{"votes":4,"name":"paul"}],
"total":38,"precincts":
{"total":9,"reporting":1},
"name":"Howard"},
"Pierce":
{"votes":[
{"votes":62,"name":"mccain"},
{"votes":8,"name":"paul"}],
"total":70,"precincts":
{"total":6,"reporting":1},
"name":"Pierce"},
"Jefferson":
{"votes":[
{"votes":59,"name":"mccain"},
{"votes":8,"name":"paul"}],
"total":67,"precincts":
{"total":11,"reporting":1},
"name":"Jefferson"},
"Cheyenne":
{"votes":[
{"votes":841,"name":"mccain"},
{"votes":85,"name":"paul"}],
"total":926,"precincts":
{"total":10,"reporting":10},
"name":"Cheyenne"},
"Butler":
{"votes":[
{"votes":640,"name":"mccain"},
{"votes":102,"name":"paul"}],
"total":742,"precincts":
{"total":21,"reporting":21},
"name":"Butler"},
"McPherson":
{"votes":[
{"votes":96,"name":"mccain"},
{"votes":23,"name":"paul"}],
"total":119,"precincts":
{"total":1,"reporting":1},
"name":"McPherson"},
"Boyd":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Boyd"},
"Holt":
{"votes":[
{"votes":588,"name":"mccain"},
{"votes":99,"name":"paul"}],
"total":687,"precincts":
{"total":14,"reporting":7},
"name":"Holt"},
"Hamilton":
{"votes":[
{"votes":386,"name":"mccain"},
{"votes":53,"name":"paul"}],
"total":439,"precincts":
{"total":12,"reporting":0},
"name":"Hamilton"},
"Cuming":
{"votes":[
{"votes":912,"name":"mccain"},
{"votes":102,"name":"paul"}],
"total":1014,"precincts":
{"total":8,"reporting":6},
"name":"Cuming"},
"Keith":
{"votes":[
{"votes":1175,"name":"mccain"},
{"votes":112,"name":"paul"}],
"total":1287,"precincts":
{"total":12,"reporting":12},
"name":"Keith"},
"Sioux":
{"votes":[
{"votes":137,"name":"mccain"},
{"votes":16,"name":"paul"}],
"total":153,"precincts":
{"total":2,"reporting":1},
"name":"Sioux"},
"Johnson":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Johnson"},
"Arthur":
{"votes":[
{"votes":98,"name":"mccain"},
{"votes":10,"name":"paul"}],
"total":108,"precincts":
{"total":1,"reporting":1},
"name":"Arthur"},
"Clay":
{"votes":[
{"votes":26,"name":"mccain"},
{"votes":4,"name":"paul"}],
"total":30,"precincts":
{"total":12,"reporting":1},
"name":"Clay"},
"Buffalo":
{"votes":[
{"votes":271,"name":"mccain"},
{"votes":16,"name":"paul"}],
"total":287,"precincts":
{"total":32,"reporting":2},
"name":"Buffalo"},
"Madison":
{"votes":[
{"votes":3500,"name":"mccain"},
{"votes":529,"name":"paul"}],
"total":4029,"precincts":
{"total":24,"reporting":23},
"name":"Madison"},
"Custer":
{"votes":[
{"votes":1769,"name":"mccain"},
{"votes":209,"name":"paul"}],
"total":1978,"precincts":
{"total":39,"reporting":31},
"name":"Custer"},
"Red Willow":
{"votes":[
{"votes":473,"name":"mccain"},
{"votes":86,"name":"paul"}],
"total":559,"precincts":
{"total":16,"reporting":8},
"name":"Red Willow"},
"Blaine":
{"votes":[
{"votes":80,"name":"mccain"},
{"votes":15,"name":"paul"}],
"total":95,"precincts":
{"total":1,"reporting":0},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":1822,"name":"mccain"},
{"votes":216,"name":"paul"}],
"total":2038,"precincts":
{"total":20,"reporting":20},
"name":"Dawson"},
"Saline":
{"votes":[
{"votes":143,"name":"mccain"},
{"votes":31,"name":"paul"}],
"total":174,"precincts":
{"total":13,"reporting":4},
"name":"Saline"},
"Cass":
{"votes":[
{"votes":351,"name":"mccain"},
{"votes":47,"name":"paul"}],
"total":398,"precincts":
{"total":31,"reporting":29},
"name":"Cass"},
"Nemaha":
{"votes":[
{"votes":692,"name":"mccain"},
{"votes":93,"name":"paul"}],
"total":785,"precincts":
{"total":10,"reporting":6},
"name":"Nemaha"},
"Rock":
{"votes":[
{"votes":48,"name":"mccain"},
{"votes":1,"name":"paul"}],
"total":49,"precincts":
{"total":6,"reporting":0},
"name":"Rock"},
"Gage":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Gage"},
"CD1":
{"votes":[],
"total":0,"name":"CD1"},
"CD2":
{"votes":[],
"total":0,"name":"CD2"},
"CD3":
{"votes":[],
"total":0,"name":"CD3"},
"Wheeler":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Wheeler"},
"Cedar":
{"votes":[
{"votes":340,"name":"mccain"},
{"votes":88,"name":"paul"}],
"total":428,"precincts":
{"total":17,"reporting":17},
"name":"Cedar"},
"Dundy":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Dundy"},
"Lincoln":
{"votes":[
{"votes":689,"name":"mccain"},
{"votes":97,"name":"paul"}],
"total":786,"precincts":
{"total":27,"reporting":4},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":2006,"name":"mccain"},
{"votes":224,"name":"paul"}],
"total":2230,"precincts":
{"total":28,"reporting":19},
"name":"Adams"},
"Hayes":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Hayes"},
"Harlan":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Harlan"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Franklin"},
"Richardson":
{"votes":[
{"votes":81,"name":"mccain"},
{"votes":17,"name":"paul"}],
"total":98,"precincts":
{"total":15,"reporting":0},
"name":"Richardson"},
"Antelope":
{"votes":[
{"votes":74,"name":"mccain"},
{"votes":14,"name":"paul"}],
"total":88,"precincts":
{"total":14,"reporting":1},
"name":"Antelope"},
"Fillmore":
{"votes":[
{"votes":429,"name":"mccain"},
{"votes":67,"name":"paul"}],
"total":496,"precincts":
{"total":11,"reporting":10},
"name":"Fillmore"},
"Greeley":
{"votes":[
{"votes":159,"name":"mccain"},
{"votes":23,"name":"paul"}],
"total":182,"precincts":
{"total":5,"reporting":3},
"name":"Greeley"},
"Lancaster":
{"votes":[
{"votes":5062,"name":"mccain"},
{"votes":696,"name":"paul"}],
"total":5758,"precincts":
{"total":223,"reporting":32},
"name":"Lancaster"},
"Cherry":
{"votes":[
{"votes":1266,"name":"mccain"},
{"votes":207,"name":"paul"}],
"total":1473,"precincts":
{"total":21,"reporting":21},
"name":"Cherry"},
"Douglas":
{"votes":[
{"votes":14035,"name":"mccain"},
{"votes":2008,"name":"paul"}],
"total":16043,"precincts":
{"total":352,"reporting":211},
"name":"Douglas"},
"Valley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Valley"},
"Garden":
{"votes":[
{"votes":320,"name":"mccain"},
{"votes":53,"name":"paul"}],
"total":373,"precincts":
{"total":5,"reporting":4},
"name":"Garden"},
"Phelps":
{"votes":[
{"votes":96,"name":"mccain"},
{"votes":4,"name":"paul"}],
"total":100,"precincts":
{"total":13,"reporting":1},
"name":"Phelps"},
"Thurston":
{"votes":[
{"votes":280,"name":"mccain"},
{"votes":44,"name":"paul"}],
"total":324,"precincts":
{"total":10,"reporting":9},
"name":"Thurston"},
"Logan":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Logan"},
"Merrick":
{"votes":[
{"votes":1051,"name":"mccain"},
{"votes":149,"name":"paul"}],
"total":1200,"precincts":
{"total":15,"reporting":15},
"name":"Merrick"},
"Nuckolls":
{"votes":[
{"votes":70,"name":"mccain"},
{"votes":11,"name":"paul"}],
"total":81,"precincts":
{"total":9,"reporting":1},
"name":"Nuckolls"},
"Knox":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Knox"},
"Platte":
{"votes":[
{"votes":916,"name":"mccain"},
{"votes":129,"name":"paul"}],
"total":1045,"precincts":
{"total":31,"reporting":9},
"name":"Platte"},
"Hall":
{"votes":[
{"votes":1627,"name":"mccain"},
{"votes":195,"name":"paul"}],
"total":1822,"precincts":
{"total":40,"reporting":26},
"name":"Hall"},
"Scotts Bluff":
{"votes":[
{"votes":924,"name":"mccain"},
{"votes":83,"name":"paul"}],
"total":1007,"precincts":
{"total":31,"reporting":12},
"name":"Scotts Bluff"},
"Sheridan":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Sheridan"},
"Gosper":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Gosper"},
"Nance":
{"votes":[
{"votes":340,"name":"mccain"},
{"votes":72,"name":"paul"}],
"total":412,"precincts":
{"total":7,"reporting":7},
"name":"Nance"},
"Boone":
{"votes":[
{"votes":486,"name":"mccain"},
{"votes":50,"name":"paul"}],
"total":536,"precincts":
{"total":10,"reporting":5},
"name":"Boone"},
"Keya Paha":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Keya Paha"},
"Pawnee":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Pawnee"},
"Perkins":
{"votes":[
{"votes":96,"name":"mccain"},
{"votes":4,"name":"paul"}],
"total":100,"precincts":
{"total":3,"reporting":3},
"name":"Perkins"},
"Garfield":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Garfield"},
"Thayer":
{"votes":[
{"votes":593,"name":"mccain"},
{"votes":88,"name":"paul"}],
"total":681,"precincts":
{"total":8,"reporting":8},
"name":"Thayer"}}})