GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":38109,"name":"mccain"},
{"votes":5268,"name":"paul"}],
"name":"New Mexico","precincts":
{"total":1633,"reporting":566},
"delegates":32,"date":"06-03"},
"state":"NM","party":"gop","total":43377,"locals":
{"San Juan":
{"votes":[
{"votes":2034,"name":"mccain"},
{"votes":308,"name":"paul"}],
"total":2342,"precincts":
{"total":78,"reporting":15},
"name":"San Juan"},
"Colfax":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Colfax"},
"Otero":
{"votes":[
{"votes":3293,"name":"mccain"},
{"votes":474,"name":"paul"}],
"total":3767,"precincts":
{"total":43,"reporting":38},
"name":"Otero"},
"Bernalillo":
{"votes":[
{"votes":14978,"name":"mccain"},
{"votes":1982,"name":"paul"}],
"total":16960,"precincts":
{"total":442,"reporting":42},
"name":"Bernalillo"},
"Grant":
{"votes":[
{"votes":559,"name":"mccain"},
{"votes":98,"name":"paul"}],
"total":657,"precincts":
{"total":47,"reporting":17},
"name":"Grant"},
"Union":
{"votes":[
{"votes":62,"name":"mccain"},
{"votes":20,"name":"paul"}],
"total":82,"precincts":
{"total":8,"reporting":1},
"name":"Union"},
"Rio Arriba":
{"votes":[
{"votes":130,"name":"mccain"},
{"votes":15,"name":"paul"}],
"total":145,"precincts":
{"total":47,"reporting":46},
"name":"Rio Arriba"},
"DeBaca":
{"votes":[
{"votes":20,"name":"mccain"},
{"votes":5,"name":"paul"}],
"total":25,"precincts":
{"total":6,"reporting":2},
"name":"DeBaca"},
"Guadalupe":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Guadalupe"},
"Eddy":
{"votes":[
{"votes":2451,"name":"mccain"},
{"votes":202,"name":"paul"}],
"total":2653,"precincts":
{"total":44,"reporting":36},
"name":"Eddy"},
"CD1":
{"votes":[],
"total":0,"name":"CD1"},
"CD2":
{"votes":[],
"total":0,"name":"CD2"},
"CD3":
{"votes":[],
"total":0,"name":"CD3"},
"Sierra":
{"votes":[
{"votes":514,"name":"mccain"},
{"votes":50,"name":"paul"}],
"total":564,"precincts":
{"total":11,"reporting":3},
"name":"Sierra"},
"Valencia":
{"votes":[
{"votes":2590,"name":"mccain"},
{"votes":525,"name":"paul"}],
"total":3115,"precincts":
{"total":51,"reporting":35},
"name":"Valencia"},
"Mora":
{"votes":[
{"votes":118,"name":"mccain"},
{"votes":9,"name":"paul"}],
"total":127,"precincts":
{"total":13,"reporting":7},
"name":"Mora"},
"Torrance":
{"votes":[
{"votes":280,"name":"mccain"},
{"votes":46,"name":"paul"}],
"total":326,"precincts":
{"total":18,"reporting":2},
"name":"Torrance"},
"Taos":
{"votes":[
{"votes":81,"name":"mccain"},
{"votes":10,"name":"paul"}],
"total":91,"precincts":
{"total":39,"reporting":5},
"name":"Taos"},
"Lea":
{"votes":[
{"votes":789,"name":"mccain"},
{"votes":53,"name":"paul"}],
"total":842,"precincts":
{"total":46,"reporting":45},
"name":"Lea"},
"Cibola":
{"votes":[
{"votes":28,"name":"mccain"},
{"votes":4,"name":"paul"}],
"total":32,"precincts":
{"total":30,"reporting":1},
"name":"Cibola"},
"Quay":
{"votes":[
{"votes":443,"name":"mccain"},
{"votes":71,"name":"paul"}],
"total":514,"precincts":
{"total":25,"reporting":25},
"name":"Quay"},
"Harding":
{"votes":[
{"votes":143,"name":"mccain"},
{"votes":19,"name":"paul"}],
"total":162,"precincts":
{"total":5,"reporting":5},
"name":"Harding"},
"Chaves":
{"votes":[
{"votes":3360,"name":"mccain"},
{"votes":407,"name":"paul"}],
"total":3767,"precincts":
{"total":53,"reporting":50},
"name":"Chaves"},
"Catron":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Catron"},
"Sandoval":
{"votes":[
{"votes":859,"name":"mccain"},
{"votes":168,"name":"paul"}],
"total":1027,"precincts":
{"total":92,"reporting":71},
"name":"Sandoval"},
"San Miguel":
{"votes":[
{"votes":286,"name":"mccain"},
{"votes":31,"name":"paul"}],
"total":317,"precincts":
{"total":41,"reporting":14},
"name":"San Miguel"},
"Socorro":
{"votes":[
{"votes":64,"name":"mccain"},
{"votes":18,"name":"paul"}],
"total":82,"precincts":
{"total":29,"reporting":2},
"name":"Socorro"},
"Dona Ana":
{"votes":[
{"votes":735,"name":"mccain"},
{"votes":108,"name":"paul"}],
"total":843,"precincts":
{"total":136,"reporting":21},
"name":"Dona Ana"},
"Lincoln":
{"votes":[
{"votes":2153,"name":"mccain"},
{"votes":381,"name":"paul"}],
"total":2534,"precincts":
{"total":23,"reporting":23},
"name":"Lincoln"},
"Roosevelt":
{"votes":[
{"votes":728,"name":"mccain"},
{"votes":102,"name":"paul"}],
"total":830,"precincts":
{"total":24,"reporting":22},
"name":"Roosevelt"},
"Los Alamos":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Los Alamos"},
"Curry":
{"votes":[
{"votes":747,"name":"mccain"},
{"votes":52,"name":"paul"}],
"total":799,"precincts":
{"total":48,"reporting":1},
"name":"Curry"},
"Santa Fe":
{"votes":[],
"total":0,"precincts":
{"total":92,"reporting":0},
"name":"Santa Fe"},
"Luna":
{"votes":[
{"votes":397,"name":"mccain"},
{"votes":74,"name":"paul"}],
"total":471,"precincts":
{"total":18,"reporting":18},
"name":"Luna"},
"McKinley":
{"votes":[],
"total":0,"precincts":
{"total":60,"reporting":11},
"name":"McKinley"},
"Hidalgo":
{"votes":[
{"votes":267,"name":"mccain"},
{"votes":36,"name":"paul"}],
"total":303,"precincts":
{"total":8,"reporting":8},
"name":"Hidalgo"}}})