GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":571626,"name":"clinton","delegates":501},
{"votes":420823,"name":"obama","delegates":430},
{"votes":18905,"name":"edwards"}],
"name":"Ohio","precincts":
{"total":11238,"reporting":5306},
"delegates":141,"date":"03-04"},
"state":"OH","party":"dem","total":1011354,"locals":
{"Preble":
{"votes":[
{"votes":4291,"name":"clinton"},
{"votes":1977,"name":"obama"},
{"votes":196,"name":"edwards"}],
"total":6464,"precincts":
{"total":45,"reporting":45},
"name":"Preble"},
"Richland":
{"votes":[
{"votes":11382,"name":"clinton"},
{"votes":8124,"name":"obama"},
{"votes":458,"name":"edwards"}],
"total":19964,"precincts":
{"total":113,"reporting":108},
"name":"Richland"},
"Shelby":
{"votes":[
{"votes":4037,"name":"clinton"},
{"votes":2698,"name":"obama"},
{"votes":249,"name":"edwards"}],
"total":6984,"precincts":
{"total":35,"reporting":35},
"name":"Shelby"},
"Union":
{"votes":[
{"votes":859,"name":"clinton"},
{"votes":634,"name":"obama"},
{"votes":33,"name":"edwards"}],
"total":1526,"precincts":
{"total":45,"reporting":9},
"name":"Union"},
"Paulding":
{"votes":[
{"votes":1333,"name":"clinton"},
{"votes":605,"name":"obama"},
{"votes":94,"name":"edwards"}],
"total":2032,"precincts":
{"total":18,"reporting":14},
"name":"Paulding"},
"Montgomery":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":548,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":9474,"name":"clinton"},
{"votes":6032,"name":"obama"},
{"votes":312,"name":"edwards"}],
"total":15818,"precincts":
{"total":96,"reporting":96},
"name":"Wayne"},
"Brown":
{"votes":[
{"votes":5352,"name":"clinton"},
{"votes":1876,"name":"obama"},
{"votes":271,"name":"edwards"}],
"total":7499,"precincts":
{"total":35,"reporting":35},
"name":"Brown"},
"Champaign":
{"votes":[
{"votes":3513,"name":"clinton"},
{"votes":2197,"name":"obama"},
{"votes":161,"name":"edwards"}],
"total":5871,"precincts":
{"total":28,"reporting":28},
"name":"Champaign"},
"Defiance":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Defiance"},
"Miami":
{"votes":[
{"votes":8817,"name":"clinton"},
{"votes":6312,"name":"obama"},
{"votes":357,"name":"edwards"}],
"total":15486,"precincts":
{"total":82,"reporting":82},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":4781,"name":"clinton"},
{"votes":3706,"name":"obama"},
{"votes":123,"name":"edwards"}],
"total":8610,"precincts":
{"total":63,"reporting":63},
"name":"Hancock"},
"Lorain":
{"votes":[
{"votes":16306,"name":"clinton"},
{"votes":11351,"name":"obama"},
{"votes":531,"name":"edwards"}],
"total":28188,"precincts":
{"total":239,"reporting":98},
"name":"Lorain"},
"Columbiana":
{"votes":[
{"votes":8220,"name":"clinton"},
{"votes":3069,"name":"obama"},
{"votes":316,"name":"edwards"}],
"total":11605,"precincts":
{"total":103,"reporting":60},
"name":"Columbiana"},
"Henry":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Henry"},
"Muskingum":
{"votes":[
{"votes":9263,"name":"clinton"},
{"votes":4224,"name":"obama"},
{"votes":343,"name":"edwards"}],
"total":13830,"precincts":
{"total":85,"reporting":85},
"name":"Muskingum"},
"Washington":
{"votes":[
{"votes":7166,"name":"clinton"},
{"votes":2631,"name":"obama"},
{"votes":277,"name":"edwards"}],
"total":10074,"precincts":
{"total":56,"reporting":50},
"name":"Washington"},
"Gallia":
{"votes":[
{"votes":1665,"name":"clinton"},
{"votes":420,"name":"obama"},
{"votes":65,"name":"edwards"}],
"total":2150,"precincts":
{"total":35,"reporting":17},
"name":"Gallia"},
"Marion":
{"votes":[
{"votes":4153,"name":"clinton"},
{"votes":2023,"name":"obama"},
{"votes":161,"name":"edwards"}],
"total":6337,"precincts":
{"total":84,"reporting":70},
"name":"Marion"},
"Allen":
{"votes":[
{"votes":7023,"name":"clinton"},
{"votes":6499,"name":"obama"},
{"votes":345,"name":"edwards"}],
"total":13867,"precincts":
{"total":121,"reporting":121},
"name":"Allen"},
"Huron":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":52,"reporting":0},
"name":"Huron"},
"Darke":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Darke"},
"Warren":
{"votes":[
{"votes":8813,"name":"clinton"},
{"votes":6778,"name":"obama"},
{"votes":207,"name":"edwards"}],
"total":15798,"precincts":
{"total":182,"reporting":95},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":2579,"name":"clinton"},
{"votes":804,"name":"obama"},
{"votes":108,"name":"edwards"}],
"total":3491,"precincts":
{"total":42,"reporting":30},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Jackson"},
"Belmont":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":83,"reporting":0},
"name":"Belmont"},
"Wyandot":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Wyandot"},
"Jefferson":
{"votes":[
{"votes":2458,"name":"clinton"},
{"votes":1263,"name":"obama"},
{"votes":197,"name":"edwards"}],
"total":3918,"precincts":
{"total":82,"reporting":29},
"name":"Jefferson"},
"Ashtabula":
{"votes":[
{"votes":6737,"name":"clinton"},
{"votes":3383,"name":"obama"},
{"votes":234,"name":"edwards"}],
"total":10354,"precincts":
{"total":127,"reporting":45},
"name":"Ashtabula"},
"Butler":
{"votes":[
{"votes":9342,"name":"clinton"},
{"votes":7497,"name":"obama"},
{"votes":202,"name":"edwards"}],
"total":17041,"precincts":
{"total":302,"reporting":94},
"name":"Butler"},
"Ross":
{"votes":[
{"votes":9190,"name":"clinton"},
{"votes":3712,"name":"obama"},
{"votes":302,"name":"edwards"}],
"total":13204,"precincts":
{"total":76,"reporting":76},
"name":"Ross"},
"Vinton":
{"votes":[
{"votes":1887,"name":"clinton"},
{"votes":448,"name":"obama"},
{"votes":107,"name":"edwards"}],
"total":2442,"precincts":
{"total":20,"reporting":20},
"name":"Vinton"},
"Hamilton":
{"votes":[
{"votes":10211,"name":"obama"},
{"votes":7097,"name":"clinton"},
{"votes":225,"name":"edwards"}],
"total":17533,"precincts":
{"total":880,"reporting":0},
"name":"Hamilton"},
"Scioto":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":92,"reporting":0},
"name":"Scioto"},
"Greene":
{"votes":[
{"votes":12365,"name":"clinton"},
{"votes":11546,"name":"obama"},
{"votes":327,"name":"edwards"}],
"total":24238,"precincts":
{"total":143,"reporting":143},
"name":"Greene"},
"Fulton":
{"votes":[
{"votes":4070,"name":"clinton"},
{"votes":2483,"name":"obama"},
{"votes":93,"name":"edwards"}],
"total":6646,"precincts":
{"total":35,"reporting":35},
"name":"Fulton"},
"Seneca":
{"votes":[
{"votes":2446,"name":"clinton"},
{"votes":1665,"name":"obama"},
{"votes":92,"name":"edwards"}],
"total":4203,"precincts":
{"total":52,"reporting":17},
"name":"Seneca"},
"Madison":
{"votes":[
{"votes":3120,"name":"clinton"},
{"votes":1544,"name":"obama"},
{"votes":88,"name":"edwards"}],
"total":4752,"precincts":
{"total":44,"reporting":44},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":794,"name":"clinton"},
{"votes":463,"name":"obama"},
{"votes":24,"name":"edwards"}],
"total":1281,"precincts":
{"total":38,"reporting":12},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":13731,"name":"clinton"},
{"votes":8945,"name":"obama"},
{"votes":444,"name":"edwards"}],
"total":23120,"precincts":
{"total":100,"reporting":96},
"name":"Clark"},
"Trumbull":
{"votes":[
{"votes":1803,"name":"clinton"},
{"votes":634,"name":"obama"},
{"votes":66,"name":"edwards"}],
"total":2503,"precincts":
{"total":273,"reporting":11},
"name":"Trumbull"},
"Erie":
{"votes":[
{"votes":9742,"name":"clinton"},
{"votes":7231,"name":"obama"},
{"votes":298,"name":"edwards"}],
"total":17271,"precincts":
{"total":62,"reporting":62},
"name":"Erie"},
"Cuyahoga":
{"votes":[
{"votes":32044,"name":"clinton"},
{"votes":29880,"name":"obama"},
{"votes":871,"name":"edwards"}],
"total":62795,"precincts":
{"total":1434,"reporting":37},
"name":"Cuyahoga"},
"Meigs":
{"votes":[
{"votes":2774,"name":"clinton"},
{"votes":733,"name":"obama"},
{"votes":121,"name":"edwards"}],
"total":3628,"precincts":
{"total":27,"reporting":27},
"name":"Meigs"},
"Delaware":
{"votes":[
{"votes":7099,"name":"clinton"},
{"votes":6832,"name":"obama"},
{"votes":109,"name":"edwards"}],
"total":14040,"precincts":
{"total":131,"reporting":79},
"name":"Delaware"},
"Stark":
{"votes":[
{"votes":23220,"name":"clinton"},
{"votes":15110,"name":"obama"},
{"votes":1022,"name":"edwards"}],
"total":39352,"precincts":
{"total":364,"reporting":226},
"name":"Stark"},
"Fairfield":
{"votes":[
{"votes":7499,"name":"clinton"},
{"votes":4025,"name":"obama"},
{"votes":269,"name":"edwards"}],
"total":11793,"precincts":
{"total":125,"reporting":82},
"name":"Fairfield"},
"Geauga":
{"votes":[
{"votes":10309,"name":"clinton"},
{"votes":8299,"name":"obama"},
{"votes":245,"name":"edwards"}],
"total":18853,"precincts":
{"total":96,"reporting":96},
"name":"Geauga"},
"Coshocton":
{"votes":[
{"votes":4054,"name":"clinton"},
{"votes":1952,"name":"obama"},
{"votes":188,"name":"edwards"}],
"total":6194,"precincts":
{"total":43,"reporting":43},
"name":"Coshocton"},
"Lawrence":
{"votes":[
{"votes":6924,"name":"clinton"},
{"votes":1710,"name":"obama"},
{"votes":250,"name":"edwards"}],
"total":8884,"precincts":
{"total":84,"reporting":70},
"name":"Lawrence"},
"Fayette":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Fayette"},
"Medina":
{"votes":[
{"votes":17612,"name":"clinton"},
{"votes":10670,"name":"obama"},
{"votes":437,"name":"edwards"}],
"total":28719,"precincts":
{"total":151,"reporting":150},
"name":"Medina"},
"Van Wert":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Van Wert"},
"Pike":
{"votes":[
{"votes":4216,"name":"clinton"},
{"votes":1140,"name":"obama"},
{"votes":210,"name":"edwards"}],
"total":5566,"precincts":
{"total":24,"reporting":24},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":2793,"name":"clinton"},
{"votes":812,"name":"obama"},
{"votes":142,"name":"edwards"}],
"total":3747,"precincts":
{"total":35,"reporting":35},
"name":"Adams"},
"Clermont":
{"votes":[
{"votes":15285,"name":"clinton"},
{"votes":9382,"name":"obama"},
{"votes":415,"name":"edwards"}],
"total":25082,"precincts":
{"total":200,"reporting":197},
"name":"Clermont"},
"Licking":
{"votes":[
{"votes":6599,"name":"clinton"},
{"votes":3805,"name":"obama"},
{"votes":257,"name":"edwards"}],
"total":10661,"precincts":
{"total":129,"reporting":63},
"name":"Licking"},
"Lake":
{"votes":[
{"votes":23854,"name":"clinton"},
{"votes":13961,"name":"obama"},
{"votes":592,"name":"edwards"}],
"total":38407,"precincts":
{"total":215,"reporting":174},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":3496,"name":"clinton"},
{"votes":1776,"name":"obama"},
{"votes":167,"name":"edwards"}],
"total":5439,"precincts":
{"total":33,"reporting":33},
"name":"Morrow"},
"Summit":
{"votes":[
{"votes":33214,"name":"clinton"},
{"votes":31626,"name":"obama"},
{"votes":966,"name":"edwards"}],
"total":65806,"precincts":
{"total":499,"reporting":234},
"name":"Summit"},
"Franklin":
{"votes":[
{"votes":69073,"name":"obama"},
{"votes":52234,"name":"clinton"},
{"votes":874,"name":"edwards"}],
"total":122181,"precincts":
{"total":879,"reporting":709},
"name":"Franklin"},
"Guernsey":
{"votes":[
{"votes":2091,"name":"clinton"},
{"votes":750,"name":"obama"},
{"votes":101,"name":"edwards"}],
"total":2942,"precincts":
{"total":35,"reporting":20},
"name":"Guernsey"},
"Highland":
{"votes":[
{"votes":1177,"name":"clinton"},
{"votes":397,"name":"obama"},
{"votes":50,"name":"edwards"}],
"total":1624,"precincts":
{"total":37,"reporting":10},
"name":"Highland"},
"Holmes":
{"votes":[
{"votes":624,"name":"clinton"},
{"votes":478,"name":"obama"},
{"votes":35,"name":"edwards"}],
"total":1137,"precincts":
{"total":19,"reporting":8},
"name":"Holmes"},
"Morgan":
{"votes":[
{"votes":295,"name":"clinton"},
{"votes":128,"name":"obama"},
{"votes":11,"name":"edwards"}],
"total":434,"precincts":
{"total":22,"reporting":14},
"name":"Morgan"},
"Carroll":
{"votes":[
{"votes":2832,"name":"clinton"},
{"votes":1358,"name":"obama"},
{"votes":180,"name":"edwards"}],
"total":4370,"precincts":
{"total":26,"reporting":20},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":1098,"name":"clinton"},
{"votes":314,"name":"obama"},
{"votes":80,"name":"edwards"}],
"total":1492,"precincts":
{"total":16,"reporting":10},
"name":"Harrison"},
"Mercer":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":41,"reporting":0},
"name":"Mercer"},
"Mahoning":
{"votes":[
{"votes":23802,"name":"clinton"},
{"votes":16411,"name":"obama"},
{"votes":677,"name":"edwards"}],
"total":40890,"precincts":
{"total":312,"reporting":293},
"name":"Mahoning"},
"Portage":
{"votes":[
{"votes":18012,"name":"clinton"},
{"votes":11120,"name":"obama"},
{"votes":651,"name":"edwards"}],
"total":29783,"precincts":
{"total":131,"reporting":121},
"name":"Portage"},
"Sandusky":
{"votes":[
{"votes":5560,"name":"clinton"},
{"votes":3842,"name":"obama"},
{"votes":184,"name":"edwards"}],
"total":9586,"precincts":
{"total":72,"reporting":68},
"name":"Sandusky"},
"Athens":
{"votes":[
{"votes":5419,"name":"clinton"},
{"votes":4657,"name":"obama"},
{"votes":281,"name":"edwards"}],
"total":10357,"precincts":
{"total":71,"reporting":51},
"name":"Athens"},
"Hocking":
{"votes":[
{"votes":2165,"name":"clinton"},
{"votes":890,"name":"obama"},
{"votes":100,"name":"edwards"}],
"total":3155,"precincts":
{"total":34,"reporting":20},
"name":"Hocking"},
"Wood":
{"votes":[
{"votes":10701,"name":"clinton"},
{"votes":6875,"name":"obama"},
{"votes":222,"name":"edwards"}],
"total":17798,"precincts":
{"total":97,"reporting":87},
"name":"Wood"},
"Crawford":
{"votes":[
{"votes":991,"name":"clinton"},
{"votes":619,"name":"obama"},
{"votes":62,"name":"edwards"}],
"total":1672,"precincts":
{"total":46,"reporting":12},
"name":"Crawford"},
"Williams":
{"votes":[
{"votes":2948,"name":"clinton"},
{"votes":2131,"name":"obama"},
{"votes":86,"name":"edwards"}],
"total":5165,"precincts":
{"total":44,"reporting":44},
"name":"Williams"},
"Noble":
{"votes":[
{"votes":1637,"name":"clinton"},
{"votes":522,"name":"obama"},
{"votes":142,"name":"edwards"}],
"total":2301,"precincts":
{"total":27,"reporting":27},
"name":"Noble"},
"Tuscarawas":
{"votes":[
{"votes":11464,"name":"clinton"},
{"votes":5925,"name":"obama"},
{"votes":705,"name":"edwards"}],
"total":18094,"precincts":
{"total":81,"reporting":79},
"name":"Tuscarawas"},
"Knox":
{"votes":[
{"votes":4595,"name":"clinton"},
{"votes":3484,"name":"obama"},
{"votes":162,"name":"edwards"}],
"total":8241,"precincts":
{"total":58,"reporting":58},
"name":"Knox"},
"Putnam":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Putnam"},
"Hardin":
{"votes":[
{"votes":376,"name":"clinton"},
{"votes":162,"name":"obama"},
{"votes":20,"name":"edwards"}],
"total":558,"precincts":
{"total":38,"reporting":1},
"name":"Hardin"},
"Lucas":
{"votes":[
{"votes":9526,"name":"obama"},
{"votes":5402,"name":"clinton"},
{"votes":98,"name":"edwards"}],
"total":15026,"precincts":
{"total":495,"reporting":100},
"name":"Lucas"},
"Ottawa":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Ottawa"},
"Auglaize":
{"votes":[
{"votes":2668,"name":"clinton"},
{"votes":1823,"name":"obama"},
{"votes":166,"name":"edwards"}],
"total":4657,"precincts":
{"total":40,"reporting":40},
"name":"Auglaize"},
"Ashland":
{"votes":[
{"votes":2817,"name":"clinton"},
{"votes":1812,"name":"obama"},
{"votes":104,"name":"edwards"}],
"total":4733,"precincts":
{"total":65,"reporting":44},
"name":"Ashland"},
"Pickaway":
{"votes":[
{"votes":5903,"name":"clinton"},
{"votes":2497,"name":"obama"},
{"votes":241,"name":"edwards"}],
"total":8641,"precincts":
{"total":48,"reporting":48},
"name":"Pickaway"},
"Logan":
{"votes":[
{"votes":2014,"name":"clinton"},
{"votes":1331,"name":"obama"},
{"votes":106,"name":"edwards"}],
"total":3451,"precincts":
{"total":44,"reporting":27},
"name":"Logan"},
"Monroe":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Monroe"}}})