GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":251712,"name":"mccain"},
{"votes":132981,"name":"huckabee"},
{"votes":20031,"name":"paul"},
{"votes":14025,"name":"romney"},
{"votes":6687,"name":"thompson"}],
"name":"Ohio","precincts":
{"total":11238,"reporting":3584},
"delegates":88,"date":"03-04"},
"state":"OH","party":"gop","total":425436,"locals":
{"Preble":
{"votes":[
{"votes":3285,"name":"mccain"},
{"votes":2569,"name":"huckabee"},
{"votes":219,"name":"paul"},
{"votes":149,"name":"romney"},
{"votes":104,"name":"thompson"}],
"total":6326,"precincts":
{"total":45,"reporting":45},
"name":"Preble"},
"Richland":
{"votes":[
{"votes":6510,"name":"mccain"},
{"votes":4036,"name":"huckabee"},
{"votes":640,"name":"paul"},
{"votes":580,"name":"romney"},
{"votes":203,"name":"thompson"}],
"total":11969,"precincts":
{"total":113,"reporting":87},
"name":"Richland"},
"Shelby":
{"votes":[
{"votes":2724,"name":"mccain"},
{"votes":2139,"name":"huckabee"},
{"votes":275,"name":"paul"},
{"votes":146,"name":"romney"},
{"votes":77,"name":"thompson"}],
"total":5361,"precincts":
{"total":35,"reporting":35},
"name":"Shelby"},
"Union":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":45,"reporting":0},
"name":"Union"},
"Paulding":
{"votes":[
{"votes":599,"name":"mccain"},
{"votes":484,"name":"huckabee"},
{"votes":114,"name":"paul"},
{"votes":38,"name":"romney"},
{"votes":13,"name":"thompson"}],
"total":1248,"precincts":
{"total":18,"reporting":7},
"name":"Paulding"},
"Montgomery":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":548,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":4620,"name":"mccain"},
{"votes":3388,"name":"huckabee"},
{"votes":495,"name":"paul"},
{"votes":321,"name":"romney"},
{"votes":161,"name":"thompson"}],
"total":8985,"precincts":
{"total":96,"reporting":63},
"name":"Wayne"},
"Brown":
{"votes":[
{"votes":2520,"name":"mccain"},
{"votes":1901,"name":"huckabee"},
{"votes":171,"name":"paul"},
{"votes":101,"name":"romney"},
{"votes":69,"name":"thompson"}],
"total":4762,"precincts":
{"total":35,"reporting":35},
"name":"Brown"},
"Champaign":
{"votes":[
{"votes":3530,"name":"mccain"},
{"votes":2287,"name":"huckabee"},
{"votes":196,"name":"paul"},
{"votes":144,"name":"romney"},
{"votes":122,"name":"thompson"}],
"total":6279,"precincts":
{"total":28,"reporting":28},
"name":"Champaign"},
"Defiance":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Defiance"},
"Miami":
{"votes":[
{"votes":9117,"name":"mccain"},
{"votes":5558,"name":"huckabee"},
{"votes":516,"name":"paul"},
{"votes":497,"name":"romney"},
{"votes":214,"name":"thompson"}],
"total":15902,"precincts":
{"total":82,"reporting":82},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":6484,"name":"mccain"},
{"votes":3720,"name":"huckabee"},
{"votes":897,"name":"paul"},
{"votes":420,"name":"romney"},
{"votes":207,"name":"thompson"}],
"total":11728,"precincts":
{"total":63,"reporting":63},
"name":"Hancock"},
"Lorain":
{"votes":[
{"votes":2287,"name":"mccain"},
{"votes":820,"name":"huckabee"},
{"votes":126,"name":"paul"},
{"votes":106,"name":"romney"},
{"votes":46,"name":"thompson"}],
"total":3385,"precincts":
{"total":239,"reporting":31},
"name":"Lorain"},
"Columbiana":
{"votes":[
{"votes":3019,"name":"mccain"},
{"votes":1909,"name":"huckabee"},
{"votes":372,"name":"paul"},
{"votes":168,"name":"romney"},
{"votes":117,"name":"thompson"}],
"total":5585,"precincts":
{"total":103,"reporting":60},
"name":"Columbiana"},
"Henry":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Henry"},
"Muskingum":
{"votes":[
{"votes":4811,"name":"mccain"},
{"votes":3262,"name":"huckabee"},
{"votes":324,"name":"paul"},
{"votes":205,"name":"romney"},
{"votes":129,"name":"thompson"}],
"total":8731,"precincts":
{"total":85,"reporting":71},
"name":"Muskingum"},
"Washington":
{"votes":[
{"votes":2617,"name":"mccain"},
{"votes":1295,"name":"huckabee"},
{"votes":261,"name":"paul"},
{"votes":116,"name":"romney"},
{"votes":54,"name":"thompson"}],
"total":4343,"precincts":
{"total":56,"reporting":28},
"name":"Washington"},
"Gallia":
{"votes":[
{"votes":1429,"name":"mccain"},
{"votes":727,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":42,"name":"thompson"},
{"votes":25,"name":"romney"}],
"total":2266,"precincts":
{"total":35,"reporting":17},
"name":"Gallia"},
"Marion":
{"votes":[
{"votes":2025,"name":"mccain"},
{"votes":1252,"name":"huckabee"},
{"votes":111,"name":"romney"},
{"votes":109,"name":"paul"},
{"votes":67,"name":"thompson"}],
"total":3564,"precincts":
{"total":84,"reporting":70},
"name":"Marion"},
"Allen":
{"votes":[
{"votes":7053,"name":"mccain"},
{"votes":3957,"name":"huckabee"},
{"votes":803,"name":"paul"},
{"votes":637,"name":"romney"},
{"votes":273,"name":"thompson"}],
"total":12723,"precincts":
{"total":121,"reporting":121},
"name":"Allen"},
"Huron":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":52,"reporting":0},
"name":"Huron"},
"Darke":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Darke"},
"Warren":
{"votes":[
{"votes":4258,"name":"mccain"},
{"votes":2297,"name":"huckabee"},
{"votes":275,"name":"romney"},
{"votes":236,"name":"paul"},
{"votes":85,"name":"thompson"}],
"total":7151,"precincts":
{"total":182,"reporting":31},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":1071,"name":"mccain"},
{"votes":784,"name":"huckabee"},
{"votes":75,"name":"paul"},
{"votes":57,"name":"thompson"},
{"votes":40,"name":"romney"}],
"total":2027,"precincts":
{"total":42,"reporting":30},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Jackson"},
"Belmont":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":83,"reporting":0},
"name":"Belmont"},
"Wyandot":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Wyandot"},
"Jefferson":
{"votes":[
{"votes":461,"name":"mccain"},
{"votes":292,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":39,"name":"romney"},
{"votes":28,"name":"thompson"}],
"total":865,"precincts":
{"total":82,"reporting":29},
"name":"Jefferson"},
"Ashtabula":
{"votes":[
{"votes":2824,"name":"mccain"},
{"votes":1773,"name":"huckabee"},
{"votes":410,"name":"paul"},
{"votes":106,"name":"romney"},
{"votes":75,"name":"thompson"}],
"total":5188,"precincts":
{"total":127,"reporting":45},
"name":"Ashtabula"},
"Butler":
{"votes":[
{"votes":2850,"name":"mccain"},
{"votes":1157,"name":"huckabee"},
{"votes":166,"name":"romney"},
{"votes":95,"name":"paul"},
{"votes":39,"name":"thompson"}],
"total":4307,"precincts":
{"total":302,"reporting":1},
"name":"Butler"},
"Ross":
{"votes":[
{"votes":2937,"name":"mccain"},
{"votes":1958,"name":"huckabee"},
{"votes":138,"name":"paul"},
{"votes":138,"name":"romney"},
{"votes":69,"name":"thompson"}],
"total":5240,"precincts":
{"total":76,"reporting":57},
"name":"Ross"},
"Vinton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Vinton"},
"Hamilton":
{"votes":[
{"votes":10981,"name":"mccain"},
{"votes":2730,"name":"huckabee"},
{"votes":665,"name":"romney"},
{"votes":428,"name":"paul"},
{"votes":139,"name":"thompson"}],
"total":14943,"precincts":
{"total":880,"reporting":0},
"name":"Hamilton"},
"Scioto":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":92,"reporting":0},
"name":"Scioto"},
"Greene":
{"votes":[
{"votes":3983,"name":"mccain"},
{"votes":2562,"name":"huckabee"},
{"votes":232,"name":"paul"},
{"votes":194,"name":"romney"},
{"votes":96,"name":"thompson"}],
"total":7067,"precincts":
{"total":143,"reporting":62},
"name":"Greene"},
"Fulton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Fulton"},
"Seneca":
{"votes":[
{"votes":597,"name":"mccain"},
{"votes":208,"name":"huckabee"},
{"votes":52,"name":"romney"},
{"votes":45,"name":"paul"},
{"votes":16,"name":"thompson"}],
"total":918,"precincts":
{"total":52,"reporting":1},
"name":"Seneca"},
"Madison":
{"votes":[
{"votes":994,"name":"mccain"},
{"votes":631,"name":"huckabee"},
{"votes":58,"name":"paul"},
{"votes":44,"name":"romney"},
{"votes":37,"name":"thompson"}],
"total":1764,"precincts":
{"total":44,"reporting":22},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":738,"name":"mccain"},
{"votes":509,"name":"huckabee"},
{"votes":36,"name":"paul"},
{"votes":26,"name":"romney"},
{"votes":20,"name":"thompson"}],
"total":1329,"precincts":
{"total":38,"reporting":12},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":7291,"name":"mccain"},
{"votes":4826,"name":"huckabee"},
{"votes":382,"name":"paul"},
{"votes":346,"name":"romney"},
{"votes":186,"name":"thompson"}],
"total":13031,"precincts":
{"total":100,"reporting":96},
"name":"Clark"},
"Trumbull":
{"votes":[
{"votes":271,"name":"mccain"},
{"votes":163,"name":"huckabee"},
{"votes":29,"name":"paul"},
{"votes":16,"name":"romney"},
{"votes":11,"name":"thompson"}],
"total":490,"precincts":
{"total":273,"reporting":11},
"name":"Trumbull"},
"Erie":
{"votes":[
{"votes":2766,"name":"mccain"},
{"votes":1204,"name":"huckabee"},
{"votes":193,"name":"paul"},
{"votes":155,"name":"romney"},
{"votes":52,"name":"thompson"}],
"total":4370,"precincts":
{"total":62,"reporting":41},
"name":"Erie"},
"Cuyahoga":
{"votes":[
{"votes":14229,"name":"mccain"},
{"votes":3045,"name":"huckabee"},
{"votes":688,"name":"paul"},
{"votes":566,"name":"romney"},
{"votes":135,"name":"thompson"}],
"total":18663,"precincts":
{"total":1434,"reporting":0},
"name":"Cuyahoga"},
"Meigs":
{"votes":[
{"votes":906,"name":"mccain"},
{"votes":434,"name":"huckabee"},
{"votes":56,"name":"paul"},
{"votes":27,"name":"thompson"},
{"votes":23,"name":"romney"}],
"total":1446,"precincts":
{"total":27,"reporting":10},
"name":"Meigs"},
"Delaware":
{"votes":[
{"votes":7005,"name":"mccain"},
{"votes":3098,"name":"huckabee"},
{"votes":504,"name":"paul"},
{"votes":411,"name":"romney"},
{"votes":163,"name":"thompson"}],
"total":11181,"precincts":
{"total":131,"reporting":79},
"name":"Delaware"},
"Stark":
{"votes":[
{"votes":8783,"name":"mccain"},
{"votes":4287,"name":"huckabee"},
{"votes":832,"name":"paul"},
{"votes":561,"name":"romney"},
{"votes":254,"name":"thompson"}],
"total":14717,"precincts":
{"total":364,"reporting":181},
"name":"Stark"},
"Fairfield":
{"votes":[
{"votes":7073,"name":"mccain"},
{"votes":3480,"name":"huckabee"},
{"votes":495,"name":"paul"},
{"votes":295,"name":"romney"},
{"votes":175,"name":"thompson"}],
"total":11518,"precincts":
{"total":125,"reporting":82},
"name":"Fairfield"},
"Geauga":
{"votes":[
{"votes":6300,"name":"mccain"},
{"votes":2196,"name":"huckabee"},
{"votes":592,"name":"paul"},
{"votes":355,"name":"romney"},
{"votes":128,"name":"thompson"}],
"total":9571,"precincts":
{"total":96,"reporting":91},
"name":"Geauga"},
"Coshocton":
{"votes":[
{"votes":2524,"name":"mccain"},
{"votes":1600,"name":"huckabee"},
{"votes":217,"name":"paul"},
{"votes":107,"name":"romney"},
{"votes":81,"name":"thompson"}],
"total":4529,"precincts":
{"total":43,"reporting":43},
"name":"Coshocton"},
"Lawrence":
{"votes":[
{"votes":1955,"name":"mccain"},
{"votes":1268,"name":"huckabee"},
{"votes":89,"name":"paul"},
{"votes":89,"name":"romney"},
{"votes":51,"name":"thompson"}],
"total":3452,"precincts":
{"total":84,"reporting":40},
"name":"Lawrence"},
"Fayette":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Fayette"},
"Medina":
{"votes":[
{"votes":5236,"name":"mccain"},
{"votes":2265,"name":"huckabee"},
{"votes":417,"name":"paul"},
{"votes":315,"name":"romney"},
{"votes":160,"name":"thompson"}],
"total":8393,"precincts":
{"total":151,"reporting":105},
"name":"Medina"},
"Van Wert":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Van Wert"},
"Pike":
{"votes":[
{"votes":1050,"name":"mccain"},
{"votes":913,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":34,"name":"thompson"},
{"votes":26,"name":"romney"}],
"total":2064,"precincts":
{"total":24,"reporting":24},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":1402,"name":"mccain"},
{"votes":1167,"name":"huckabee"},
{"votes":51,"name":"romney"},
{"votes":50,"name":"paul"},
{"votes":17,"name":"thompson"}],
"total":2687,"precincts":
{"total":35,"reporting":28},
"name":"Adams"},
"Clermont":
{"votes":[
{"votes":13901,"name":"mccain"},
{"votes":7780,"name":"huckabee"},
{"votes":903,"name":"paul"},
{"votes":792,"name":"romney"},
{"votes":412,"name":"thompson"}],
"total":23788,"precincts":
{"total":200,"reporting":182},
"name":"Clermont"},
"Licking":
{"votes":[
{"votes":4535,"name":"mccain"},
{"votes":2558,"name":"huckabee"},
{"votes":426,"name":"paul"},
{"votes":224,"name":"romney"},
{"votes":141,"name":"thompson"}],
"total":7884,"precincts":
{"total":129,"reporting":59},
"name":"Licking"},
"Lake":
{"votes":[
{"votes":7685,"name":"mccain"},
{"votes":2658,"name":"huckabee"},
{"votes":562,"name":"paul"},
{"votes":320,"name":"romney"},
{"votes":152,"name":"thompson"}],
"total":11377,"precincts":
{"total":215,"reporting":78},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":2178,"name":"mccain"},
{"votes":1679,"name":"huckabee"},
{"votes":208,"name":"paul"},
{"votes":132,"name":"romney"},
{"votes":77,"name":"thompson"}],
"total":4274,"precincts":
{"total":33,"reporting":30},
"name":"Morrow"},
"Summit":
{"votes":[
{"votes":10225,"name":"mccain"},
{"votes":4360,"name":"huckabee"},
{"votes":836,"name":"paul"},
{"votes":685,"name":"romney"},
{"votes":219,"name":"thompson"}],
"total":16325,"precincts":
{"total":499,"reporting":218},
"name":"Summit"},
"Franklin":
{"votes":[
{"votes":13869,"name":"mccain"},
{"votes":6652,"name":"huckabee"},
{"votes":1224,"name":"paul"},
{"votes":729,"name":"romney"},
{"votes":404,"name":"thompson"}],
"total":22878,"precincts":
{"total":879,"reporting":399},
"name":"Franklin"},
"Guernsey":
{"votes":[
{"votes":1071,"name":"mccain"},
{"votes":745,"name":"huckabee"},
{"votes":70,"name":"paul"},
{"votes":56,"name":"romney"},
{"votes":39,"name":"thompson"}],
"total":1981,"precincts":
{"total":35,"reporting":20},
"name":"Guernsey"},
"Highland":
{"votes":[
{"votes":935,"name":"mccain"},
{"votes":596,"name":"huckabee"},
{"votes":34,"name":"paul"},
{"votes":33,"name":"romney"},
{"votes":29,"name":"thompson"}],
"total":1627,"precincts":
{"total":37,"reporting":10},
"name":"Highland"},
"Holmes":
{"votes":[
{"votes":906,"name":"mccain"},
{"votes":699,"name":"huckabee"},
{"votes":116,"name":"romney"},
{"votes":99,"name":"paul"},
{"votes":53,"name":"thompson"}],
"total":1873,"precincts":
{"total":19,"reporting":8},
"name":"Holmes"},
"Morgan":
{"votes":[
{"votes":345,"name":"mccain"},
{"votes":171,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"romney"}],
"total":561,"precincts":
{"total":22,"reporting":14},
"name":"Morgan"},
"Carroll":
{"votes":[
{"votes":1677,"name":"mccain"},
{"votes":1033,"name":"huckabee"},
{"votes":173,"name":"paul"},
{"votes":87,"name":"romney"},
{"votes":63,"name":"thompson"}],
"total":3033,"precincts":
{"total":26,"reporting":20},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":216,"name":"mccain"},
{"votes":111,"name":"huckabee"},
{"votes":11,"name":"paul"},
{"votes":11,"name":"romney"},
{"votes":4,"name":"thompson"}],
"total":353,"precincts":
{"total":16,"reporting":7},
"name":"Harrison"},
"Mercer":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":41,"reporting":0},
"name":"Mercer"},
"Mahoning":
{"votes":[
{"votes":2420,"name":"mccain"},
{"votes":1299,"name":"huckabee"},
{"votes":221,"name":"paul"},
{"votes":149,"name":"romney"},
{"votes":85,"name":"thompson"}],
"total":4174,"precincts":
{"total":312,"reporting":31},
"name":"Mahoning"},
"Portage":
{"votes":[
{"votes":1529,"name":"mccain"},
{"votes":586,"name":"huckabee"},
{"votes":125,"name":"paul"},
{"votes":86,"name":"romney"},
{"votes":26,"name":"thompson"}],
"total":2352,"precincts":
{"total":131,"reporting":31},
"name":"Portage"},
"Sandusky":
{"votes":[
{"votes":1065,"name":"mccain"},
{"votes":598,"name":"huckabee"},
{"votes":95,"name":"paul"},
{"votes":77,"name":"romney"},
{"votes":40,"name":"thompson"}],
"total":1875,"precincts":
{"total":72,"reporting":21},
"name":"Sandusky"},
"Athens":
{"votes":[
{"votes":745,"name":"mccain"},
{"votes":371,"name":"huckabee"},
{"votes":143,"name":"paul"},
{"votes":28,"name":"romney"},
{"votes":6,"name":"thompson"}],
"total":1293,"precincts":
{"total":71,"reporting":25},
"name":"Athens"},
"Hocking":
{"votes":[
{"votes":474,"name":"mccain"},
{"votes":278,"name":"huckabee"},
{"votes":57,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":10,"name":"romney"}],
"total":829,"precincts":
{"total":34,"reporting":10},
"name":"Hocking"},
"Wood":
{"votes":[
{"votes":5105,"name":"mccain"},
{"votes":2757,"name":"huckabee"},
{"votes":679,"name":"paul"},
{"votes":493,"name":"romney"},
{"votes":217,"name":"thompson"}],
"total":9251,"precincts":
{"total":97,"reporting":87},
"name":"Wood"},
"Crawford":
{"votes":[
{"votes":600,"name":"mccain"},
{"votes":421,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":33,"name":"romney"},
{"votes":25,"name":"thompson"}],
"total":1122,"precincts":
{"total":46,"reporting":12},
"name":"Crawford"},
"Williams":
{"votes":[
{"votes":2745,"name":"mccain"},
{"votes":1662,"name":"huckabee"},
{"votes":269,"name":"paul"},
{"votes":161,"name":"romney"},
{"votes":80,"name":"thompson"}],
"total":4917,"precincts":
{"total":44,"reporting":44},
"name":"Williams"},
"Noble":
{"votes":[
{"votes":1286,"name":"mccain"},
{"votes":725,"name":"huckabee"},
{"votes":73,"name":"paul"},
{"votes":70,"name":"thompson"},
{"votes":40,"name":"romney"}],
"total":2194,"precincts":
{"total":27,"reporting":27},
"name":"Noble"},
"Tuscarawas":
{"votes":[
{"votes":3710,"name":"mccain"},
{"votes":2603,"name":"huckabee"},
{"votes":342,"name":"paul"},
{"votes":191,"name":"romney"},
{"votes":98,"name":"thompson"}],
"total":6944,"precincts":
{"total":81,"reporting":79},
"name":"Tuscarawas"},
"Knox":
{"votes":[
{"votes":3002,"name":"mccain"},
{"votes":1932,"name":"huckabee"},
{"votes":351,"name":"paul"},
{"votes":148,"name":"romney"},
{"votes":93,"name":"thompson"}],
"total":5526,"precincts":
{"total":58,"reporting":58},
"name":"Knox"},
"Putnam":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Putnam"},
"Hardin":
{"votes":[
{"votes":387,"name":"mccain"},
{"votes":168,"name":"huckabee"},
{"votes":31,"name":"paul"},
{"votes":27,"name":"romney"},
{"votes":6,"name":"thompson"}],
"total":619,"precincts":
{"total":38,"reporting":1},
"name":"Hardin"},
"Lucas":
{"votes":[
{"votes":139,"name":"mccain"},
{"votes":62,"name":"huckabee"},
{"votes":15,"name":"paul"},
{"votes":15,"name":"romney"},
{"votes":7,"name":"thompson"}],
"total":238,"precincts":
{"total":495,"reporting":4},
"name":"Lucas"},
"Ottawa":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Ottawa"},
"Auglaize":
{"votes":[
{"votes":2904,"name":"mccain"},
{"votes":1641,"name":"huckabee"},
{"votes":472,"name":"paul"},
{"votes":193,"name":"romney"},
{"votes":68,"name":"thompson"}],
"total":5278,"precincts":
{"total":40,"reporting":40},
"name":"Auglaize"},
"Ashland":
{"votes":[
{"votes":2571,"name":"mccain"},
{"votes":1806,"name":"huckabee"},
{"votes":330,"name":"paul"},
{"votes":167,"name":"romney"},
{"votes":84,"name":"thompson"}],
"total":4958,"precincts":
{"total":65,"reporting":41},
"name":"Ashland"},
"Pickaway":
{"votes":[
{"votes":2783,"name":"mccain"},
{"votes":1907,"name":"huckabee"},
{"votes":162,"name":"paul"},
{"votes":98,"name":"romney"},
{"votes":86,"name":"thompson"}],
"total":5036,"precincts":
{"total":48,"reporting":48},
"name":"Pickaway"},
"Logan":
{"votes":[
{"votes":1589,"name":"mccain"},
{"votes":972,"name":"huckabee"},
{"votes":96,"name":"paul"},
{"votes":95,"name":"romney"},
{"votes":56,"name":"thompson"}],
"total":2808,"precincts":
{"total":44,"reporting":16},
"name":"Logan"},
"Monroe":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Monroe"}}})