GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":36453,"name":"mccain"},
{"votes":19271,"name":"huckabee"},
{"votes":3010,"name":"paul"},
{"votes":2064,"name":"romney"},
{"votes":954,"name":"thompson"}],
"name":"Ohio","precincts":
{"total":11238,"reporting":441},
"delegates":88,"date":"03-04"},
"state":"OH","party":"gop","total":61752,"locals":
{"Preble":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":45,"reporting":0},
"name":"Preble"},
"Richland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":113,"reporting":0},
"name":"Richland"},
"Shelby":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Shelby"},
"Union":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":45,"reporting":0},
"name":"Union"},
"Paulding":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Paulding"},
"Montgomery":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":548,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":96,"reporting":0},
"name":"Wayne"},
"Brown":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Brown"},
"Champaign":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Champaign"},
"Defiance":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Defiance"},
"Miami":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":82,"reporting":0},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":5326,"name":"mccain"},
{"votes":2840,"name":"huckabee"},
{"votes":700,"name":"paul"},
{"votes":339,"name":"romney"},
{"votes":157,"name":"thompson"}],
"total":9362,"precincts":
{"total":63,"reporting":53},
"name":"Hancock"},
"Lorain":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":239,"reporting":0},
"name":"Lorain"},
"Columbiana":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":103,"reporting":0},
"name":"Columbiana"},
"Henry":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Henry"},
"Muskingum":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":85,"reporting":0},
"name":"Muskingum"},
"Washington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":56,"reporting":0},
"name":"Washington"},
"Gallia":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Gallia"},
"Marion":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":84,"reporting":0},
"name":"Marion"},
"Allen":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":121,"reporting":0},
"name":"Allen"},
"Huron":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":52,"reporting":0},
"name":"Huron"},
"Darke":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Darke"},
"Warren":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":182,"reporting":0},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":243,"name":"mccain"},
{"votes":198,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":14,"name":"thompson"},
{"votes":8,"name":"romney"}],
"total":482,"precincts":
{"total":42,"reporting":10},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Jackson"},
"Belmont":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":83,"reporting":0},
"name":"Belmont"},
"Wyandot":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Wyandot"},
"Jefferson":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":82,"reporting":0},
"name":"Jefferson"},
"Ashtabula":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":127,"reporting":0},
"name":"Ashtabula"},
"Butler":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":302,"reporting":0},
"name":"Butler"},
"Ross":
{"votes":[
{"votes":915,"name":"mccain"},
{"votes":355,"name":"huckabee"},
{"votes":38,"name":"romney"},
{"votes":36,"name":"paul"},
{"votes":18,"name":"thompson"}],
"total":1362,"precincts":
{"total":76,"reporting":1},
"name":"Ross"},
"Vinton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Vinton"},
"Hamilton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":880,"reporting":0},
"name":"Hamilton"},
"Scioto":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":92,"reporting":0},
"name":"Scioto"},
"Greene":
{"votes":[
{"votes":3983,"name":"mccain"},
{"votes":2562,"name":"huckabee"},
{"votes":232,"name":"paul"},
{"votes":194,"name":"romney"},
{"votes":96,"name":"thompson"}],
"total":7067,"precincts":
{"total":143,"reporting":62},
"name":"Greene"},
"Fulton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Fulton"},
"Seneca":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":52,"reporting":0},
"name":"Seneca"},
"Madison":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":3986,"name":"mccain"},
{"votes":2626,"name":"huckabee"},
{"votes":218,"name":"paul"},
{"votes":205,"name":"romney"},
{"votes":97,"name":"thompson"}],
"total":7132,"precincts":
{"total":100,"reporting":55},
"name":"Clark"},
"Trumbull":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":273,"reporting":0},
"name":"Trumbull"},
"Erie":
{"votes":[
{"votes":2766,"name":"mccain"},
{"votes":1204,"name":"huckabee"},
{"votes":193,"name":"paul"},
{"votes":155,"name":"romney"},
{"votes":52,"name":"thompson"}],
"total":4370,"precincts":
{"total":62,"reporting":41},
"name":"Erie"},
"Cuyahoga":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1434,"reporting":0},
"name":"Cuyahoga"},
"Meigs":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Meigs"},
"Delaware":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":131,"reporting":0},
"name":"Delaware"},
"Stark":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":364,"reporting":0},
"name":"Stark"},
"Fairfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":125,"reporting":0},
"name":"Fairfield"},
"Geauga":
{"votes":[
{"votes":3922,"name":"mccain"},
{"votes":1410,"name":"huckabee"},
{"votes":369,"name":"paul"},
{"votes":232,"name":"romney"},
{"votes":81,"name":"thompson"}],
"total":6014,"precincts":
{"total":96,"reporting":51},
"name":"Geauga"},
"Coshocton":
{"votes":[
{"votes":1722,"name":"mccain"},
{"votes":967,"name":"huckabee"},
{"votes":122,"name":"paul"},
{"votes":69,"name":"romney"},
{"votes":53,"name":"thompson"}],
"total":2933,"precincts":
{"total":43,"reporting":34},
"name":"Coshocton"},
"Lawrence":
{"votes":[
{"votes":1601,"name":"mccain"},
{"votes":975,"name":"huckabee"},
{"votes":77,"name":"paul"},
{"votes":72,"name":"romney"},
{"votes":41,"name":"thompson"}],
"total":2766,"precincts":
{"total":84,"reporting":30},
"name":"Lawrence"},
"Fayette":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Fayette"},
"Medina":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":151,"reporting":0},
"name":"Medina"},
"Van Wert":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Van Wert"},
"Pike":
{"votes":[
{"votes":974,"name":"mccain"},
{"votes":828,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":33,"name":"thompson"},
{"votes":26,"name":"romney"}],
"total":1898,"precincts":
{"total":24,"reporting":21},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Adams"},
"Clermont":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":200,"reporting":0},
"name":"Clermont"},
"Licking":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":129,"reporting":0},
"name":"Licking"},
"Lake":
{"votes":[
{"votes":3606,"name":"mccain"},
{"votes":1046,"name":"huckabee"},
{"votes":217,"name":"paul"},
{"votes":165,"name":"romney"},
{"votes":64,"name":"thompson"}],
"total":5098,"precincts":
{"total":215,"reporting":0},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":1728,"name":"mccain"},
{"votes":1301,"name":"huckabee"},
{"votes":155,"name":"paul"},
{"votes":106,"name":"romney"},
{"votes":59,"name":"thompson"}],
"total":3349,"precincts":
{"total":33,"reporting":23},
"name":"Morrow"},
"Summit":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":499,"reporting":0},
"name":"Summit"},
"Franklin":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":879,"reporting":0},
"name":"Franklin"},
"Guernsey":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Guernsey"},
"Highland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Highland"},
"Holmes":
{"votes":[
{"votes":906,"name":"mccain"},
{"votes":699,"name":"huckabee"},
{"votes":116,"name":"romney"},
{"votes":99,"name":"paul"},
{"votes":53,"name":"thompson"}],
"total":1873,"precincts":
{"total":19,"reporting":8},
"name":"Holmes"},
"Morgan":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Morgan"},
"Carroll":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Harrison"},
"Mercer":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":41,"reporting":0},
"name":"Mercer"},
"Mahoning":
{"votes":[
{"votes":1228,"name":"mccain"},
{"votes":475,"name":"huckabee"},
{"votes":82,"name":"romney"},
{"votes":73,"name":"paul"},
{"votes":31,"name":"thompson"}],
"total":1889,"precincts":
{"total":312,"reporting":1},
"name":"Mahoning"},
"Portage":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":131,"reporting":0},
"name":"Portage"},
"Sandusky":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":72,"reporting":0},
"name":"Sandusky"},
"Athens":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":71,"reporting":0},
"name":"Athens"},
"Hocking":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Hocking"},
"Wood":
{"votes":[
{"votes":1354,"name":"mccain"},
{"votes":723,"name":"huckabee"},
{"votes":214,"name":"paul"},
{"votes":134,"name":"romney"},
{"votes":64,"name":"thompson"}],
"total":2489,"precincts":
{"total":97,"reporting":30},
"name":"Wood"},
"Crawford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Crawford"},
"Williams":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Williams"},
"Noble":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Noble"},
"Tuscarawas":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":81,"reporting":0},
"name":"Tuscarawas"},
"Knox":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Knox"},
"Putnam":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Putnam"},
"Hardin":
{"votes":[
{"votes":387,"name":"mccain"},
{"votes":168,"name":"huckabee"},
{"votes":31,"name":"paul"},
{"votes":27,"name":"romney"},
{"votes":6,"name":"thompson"}],
"total":619,"precincts":
{"total":38,"reporting":1},
"name":"Hardin"},
"Lucas":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":495,"reporting":0},
"name":"Lucas"},
"Ottawa":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Ottawa"},
"Auglaize":
{"votes":[
{"votes":1534,"name":"mccain"},
{"votes":784,"name":"huckabee"},
{"votes":211,"name":"paul"},
{"votes":93,"name":"romney"},
{"votes":32,"name":"thompson"}],
"total":2654,"precincts":
{"total":40,"reporting":20},
"name":"Auglaize"},
"Ashland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":65,"reporting":0},
"name":"Ashland"},
"Pickaway":
{"votes":[
{"votes":272,"name":"mccain"},
{"votes":110,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":3,"name":"romney"}],
"total":395,"precincts":
{"total":48,"reporting":0},
"name":"Pickaway"},
"Logan":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Logan"},
"Monroe":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Monroe"}}})