GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":330533,"name":"obama","delegates":28},
{"votes":235937,"name":"clinton","delegates":17}],
"name":"Oregon","precincts":
{"total":1000,"reporting":875},
"delegates":52,"date":"05-20"},
"state":"OR","party":"dem","total":566470,"locals":
{"Wheeler":
{"votes":[
{"votes":114,"name":"clinton"},
{"votes":109,"name":"obama"}],
"total":223,"precincts":
{"total":1,"reporting":1},
"name":"Wheeler"},
"Jackson":
{"votes":[
{"votes":16505,"name":"obama"},
{"votes":10949,"name":"clinton"}],
"total":27454,"precincts":
{"total":57,"reporting":57},
"name":"Jackson"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Grant"},
"Union":
{"votes":[
{"votes":1879,"name":"obama"},
{"votes":1495,"name":"clinton"}],
"total":3374,"precincts":
{"total":7,"reporting":7},
"name":"Union"},
"Deschutes":
{"votes":[
{"votes":10731,"name":"obama"},
{"votes":7046,"name":"clinton"}],
"total":17777,"precincts":
{"total":43,"reporting":31},
"name":"Deschutes"},
"Lane":
{"votes":[
{"votes":43471,"name":"obama"},
{"votes":25827,"name":"clinton"}],
"total":69298,"precincts":
{"total":97,"reporting":75},
"name":"Lane"},
"Douglas":
{"votes":[
{"votes":7701,"name":"clinton"},
{"votes":7296,"name":"obama"}],
"total":14997,"precincts":
{"total":31,"reporting":27},
"name":"Douglas"},
"Klamath":
{"votes":[
{"votes":3427,"name":"clinton"},
{"votes":2922,"name":"obama"}],
"total":6349,"precincts":
{"total":17,"reporting":17},
"name":"Klamath"},
"Wasco":
{"votes":[
{"votes":1976,"name":"obama"},
{"votes":1915,"name":"clinton"}],
"total":3891,"precincts":
{"total":7,"reporting":7},
"name":"Wasco"},
"Jefferson":
{"votes":[
{"votes":1157,"name":"obama"},
{"votes":1075,"name":"clinton"}],
"total":2232,"precincts":
{"total":5,"reporting":5},
"name":"Jefferson"},
"Hood River":
{"votes":[
{"votes":2236,"name":"obama"},
{"votes":1465,"name":"clinton"}],
"total":3701,"precincts":
{"total":5,"reporting":5},
"name":"Hood River"},
"Coos":
{"votes":[
{"votes":5218,"name":"clinton"},
{"votes":4359,"name":"obama"}],
"total":9577,"precincts":
{"total":18,"reporting":14},
"name":"Coos"},
"Multnomah":
{"votes":[
{"votes":86613,"name":"obama"},
{"votes":47094,"name":"clinton"}],
"total":133707,"precincts":
{"total":196,"reporting":180},
"name":"Multnomah"},
"Columbia":
{"votes":[
{"votes":4155,"name":"clinton"},
{"votes":3690,"name":"obama"}],
"total":7845,"precincts":
{"total":14,"reporting":14},
"name":"Columbia"},
"Crook":
{"votes":[
{"votes":1388,"name":"clinton"},
{"votes":1239,"name":"obama"}],
"total":2627,"precincts":
{"total":6,"reporting":6},
"name":"Crook"},
"Sherman":
{"votes":[
{"votes":156,"name":"clinton"},
{"votes":115,"name":"obama"}],
"total":271,"precincts":
{"total":1,"reporting":1},
"name":"Sherman"},
"Linn":
{"votes":[
{"votes":7119,"name":"clinton"},
{"votes":6780,"name":"obama"}],
"total":13899,"precincts":
{"total":29,"reporting":25},
"name":"Linn"},
"Lincoln":
{"votes":[
{"votes":5123,"name":"obama"},
{"votes":4437,"name":"clinton"}],
"total":9560,"precincts":
{"total":13,"reporting":13},
"name":"Lincoln"},
"Wallowa":
{"votes":[
{"votes":642,"name":"obama"},
{"votes":454,"name":"clinton"}],
"total":1096,"precincts":
{"total":2,"reporting":2},
"name":"Wallowa"},
"Baker":
{"votes":[
{"votes":1117,"name":"obama"},
{"votes":1086,"name":"clinton"}],
"total":2203,"precincts":
{"total":5,"reporting":5},
"name":"Baker"},
"Clatsop":
{"votes":[
{"votes":3775,"name":"obama"},
{"votes":3241,"name":"clinton"}],
"total":7016,"precincts":
{"total":11,"reporting":9},
"name":"Clatsop"},
"Benton":
{"votes":[
{"votes":12522,"name":"obama"},
{"votes":5496,"name":"clinton"}],
"total":18018,"precincts":
{"total":23,"reporting":23},
"name":"Benton"},
"Lake":
{"votes":[
{"votes":325,"name":"clinton"},
{"votes":280,"name":"obama"}],
"total":605,"precincts":
{"total":2,"reporting":1},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":573,"name":"clinton"},
{"votes":353,"name":"obama"}],
"total":926,"precincts":
{"total":2,"reporting":2},
"name":"Morrow"},
"Malheur":
{"votes":[
{"votes":965,"name":"clinton"},
{"votes":816,"name":"obama"}],
"total":1781,"precincts":
{"total":6,"reporting":5},
"name":"Malheur"},
"Umatilla":
{"votes":[
{"votes":3145,"name":"clinton"},
{"votes":2578,"name":"obama"}],
"total":5723,"precincts":
{"total":16,"reporting":14},
"name":"Umatilla"},
"Curry":
{"votes":[
{"votes":1821,"name":"obama"},
{"votes":1654,"name":"clinton"}],
"total":3475,"precincts":
{"total":7,"reporting":6},
"name":"Curry"},
"Clackamas":
{"votes":[
{"votes":26814,"name":"obama"},
{"votes":22911,"name":"clinton"}],
"total":49725,"precincts":
{"total":103,"reporting":75},
"name":"Clackamas"},
"Gilliam":
{"votes":[
{"votes":184,"name":"obama"},
{"votes":148,"name":"clinton"}],
"total":332,"precincts":
{"total":1,"reporting":1},
"name":"Gilliam"},
"Harney":
{"votes":[
{"votes":365,"name":"clinton"},
{"votes":351,"name":"obama"}],
"total":716,"precincts":
{"total":2,"reporting":2},
"name":"Harney"},
"Josephine":
{"votes":[
{"votes":6001,"name":"obama"},
{"votes":5971,"name":"clinton"}],
"total":11972,"precincts":
{"total":24,"reporting":24},
"name":"Josephine"},
"Washington":
{"votes":[
{"votes":42412,"name":"obama"},
{"votes":29209,"name":"clinton"}],
"total":71621,"precincts":
{"total":127,"reporting":107},
"name":"Washington"},
"Tillamook":
{"votes":[
{"votes":2495,"name":"clinton"},
{"votes":2464,"name":"obama"}],
"total":4959,"precincts":
{"total":7,"reporting":7},
"name":"Tillamook"},
"Yamhill":
{"votes":[
{"votes":6018,"name":"obama"},
{"votes":5285,"name":"clinton"}],
"total":11303,"precincts":
{"total":23,"reporting":17},
"name":"Yamhill"},
"Marion":
{"votes":[
{"votes":20238,"name":"obama"},
{"votes":17241,"name":"clinton"}],
"total":37479,"precincts":
{"total":70,"reporting":70},
"name":"Marion"},
"Polk":
{"votes":[
{"votes":5946,"name":"obama"},
{"votes":4792,"name":"clinton"}],
"total":10738,"precincts":
{"total":20,"reporting":20},
"name":"Polk"}}})