GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":276056,"name":"obama","delegates":22},
{"votes":199736,"name":"clinton","delegates":12}],
"name":"Oregon","precincts":
{"total":1000,"reporting":680},
"delegates":52,"date":"05-20"},
"state":"OR","party":"dem","total":475792,"locals":
{"Wheeler":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wheeler"},
"Jackson":
{"votes":[
{"votes":14262,"name":"obama"},
{"votes":9496,"name":"clinton"}],
"total":23758,"precincts":
{"total":57,"reporting":38},
"name":"Jackson"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Grant"},
"Union":
{"votes":[
{"votes":1670,"name":"obama"},
{"votes":1339,"name":"clinton"}],
"total":3009,"precincts":
{"total":7,"reporting":5},
"name":"Union"},
"Deschutes":
{"votes":[
{"votes":10107,"name":"obama"},
{"votes":6685,"name":"clinton"}],
"total":16792,"precincts":
{"total":43,"reporting":29},
"name":"Deschutes"},
"Lane":
{"votes":[
{"votes":28752,"name":"obama"},
{"votes":17614,"name":"clinton"}],
"total":46366,"precincts":
{"total":97,"reporting":49},
"name":"Lane"},
"Douglas":
{"votes":[
{"votes":6883,"name":"clinton"},
{"votes":6550,"name":"obama"}],
"total":13433,"precincts":
{"total":31,"reporting":24},
"name":"Douglas"},
"Klamath":
{"votes":[
{"votes":3148,"name":"clinton"},
{"votes":2674,"name":"obama"}],
"total":5822,"precincts":
{"total":17,"reporting":14},
"name":"Klamath"},
"Wasco":
{"votes":[
{"votes":1976,"name":"obama"},
{"votes":1915,"name":"clinton"}],
"total":3891,"precincts":
{"total":7,"reporting":7},
"name":"Wasco"},
"Jefferson":
{"votes":[
{"votes":1088,"name":"obama"},
{"votes":1022,"name":"clinton"}],
"total":2110,"precincts":
{"total":5,"reporting":4},
"name":"Jefferson"},
"Hood River":
{"votes":[
{"votes":2236,"name":"obama"},
{"votes":1465,"name":"clinton"}],
"total":3701,"precincts":
{"total":5,"reporting":5},
"name":"Hood River"},
"Coos":
{"votes":[
{"votes":4991,"name":"clinton"},
{"votes":4130,"name":"obama"}],
"total":9121,"precincts":
{"total":18,"reporting":14},
"name":"Coos"},
"Multnomah":
{"votes":[
{"votes":78710,"name":"obama"},
{"votes":43833,"name":"clinton"}],
"total":122543,"precincts":
{"total":196,"reporting":150},
"name":"Multnomah"},
"Columbia":
{"votes":[
{"votes":3225,"name":"clinton"},
{"votes":2817,"name":"obama"}],
"total":6042,"precincts":
{"total":14,"reporting":12},
"name":"Columbia"},
"Crook":
{"votes":[
{"votes":1143,"name":"clinton"},
{"votes":962,"name":"obama"}],
"total":2105,"precincts":
{"total":6,"reporting":4},
"name":"Crook"},
"Sherman":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sherman"},
"Linn":
{"votes":[
{"votes":6118,"name":"clinton"},
{"votes":5723,"name":"obama"}],
"total":11841,"precincts":
{"total":29,"reporting":21},
"name":"Linn"},
"Lincoln":
{"votes":[
{"votes":5123,"name":"obama"},
{"votes":4437,"name":"clinton"}],
"total":9560,"precincts":
{"total":13,"reporting":11},
"name":"Lincoln"},
"Wallowa":
{"votes":[
{"votes":591,"name":"obama"},
{"votes":423,"name":"clinton"}],
"total":1014,"precincts":
{"total":2,"reporting":1},
"name":"Wallowa"},
"Baker":
{"votes":[
{"votes":1117,"name":"obama"},
{"votes":1086,"name":"clinton"}],
"total":2203,"precincts":
{"total":5,"reporting":5},
"name":"Baker"},
"Clatsop":
{"votes":[
{"votes":2252,"name":"obama"},
{"votes":1989,"name":"clinton"}],
"total":4241,"precincts":
{"total":11,"reporting":5},
"name":"Clatsop"},
"Benton":
{"votes":[
{"votes":11132,"name":"obama"},
{"votes":4840,"name":"clinton"}],
"total":15972,"precincts":
{"total":23,"reporting":16},
"name":"Benton"},
"Lake":
{"votes":[
{"votes":325,"name":"clinton"},
{"votes":280,"name":"obama"}],
"total":605,"precincts":
{"total":2,"reporting":1},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":573,"name":"clinton"},
{"votes":353,"name":"obama"}],
"total":926,"precincts":
{"total":2,"reporting":2},
"name":"Morrow"},
"Malheur":
{"votes":[
{"votes":837,"name":"clinton"},
{"votes":706,"name":"obama"}],
"total":1543,"precincts":
{"total":6,"reporting":3},
"name":"Malheur"},
"Umatilla":
{"votes":[
{"votes":3123,"name":"clinton"},
{"votes":2470,"name":"obama"}],
"total":5593,"precincts":
{"total":16,"reporting":13},
"name":"Umatilla"},
"Curry":
{"votes":[
{"votes":1598,"name":"obama"},
{"votes":1492,"name":"clinton"}],
"total":3090,"precincts":
{"total":7,"reporting":4},
"name":"Curry"},
"Clackamas":
{"votes":[
{"votes":18751,"name":"obama"},
{"votes":16670,"name":"clinton"}],
"total":35421,"precincts":
{"total":103,"reporting":53},
"name":"Clackamas"},
"Gilliam":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Gilliam"},
"Harney":
{"votes":[
{"votes":365,"name":"clinton"},
{"votes":351,"name":"obama"}],
"total":716,"precincts":
{"total":2,"reporting":2},
"name":"Harney"},
"Josephine":
{"votes":[
{"votes":5362,"name":"obama"},
{"votes":5155,"name":"clinton"}],
"total":10517,"precincts":
{"total":24,"reporting":20},
"name":"Josephine"},
"Washington":
{"votes":[
{"votes":37639,"name":"obama"},
{"votes":25992,"name":"clinton"}],
"total":63631,"precincts":
{"total":127,"reporting":95},
"name":"Washington"},
"Tillamook":
{"votes":[
{"votes":2037,"name":"clinton"},
{"votes":1974,"name":"obama"}],
"total":4011,"precincts":
{"total":7,"reporting":5},
"name":"Tillamook"},
"Yamhill":
{"votes":[
{"votes":5227,"name":"obama"},
{"votes":4633,"name":"clinton"}],
"total":9860,"precincts":
{"total":23,"reporting":15},
"name":"Yamhill"},
"Marion":
{"votes":[
{"votes":14077,"name":"obama"},
{"votes":12502,"name":"clinton"}],
"total":26579,"precincts":
{"total":70,"reporting":37},
"name":"Marion"},
"Polk":
{"votes":[
{"votes":5396,"name":"obama"},
{"votes":4380,"name":"clinton"}],
"total":9776,"precincts":
{"total":20,"reporting":16},
"name":"Polk"}}})