GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":245467,"name":"mccain"},
{"votes":42448,"name":"paul"}],
"name":"Oregon","precincts":
{"total":1000,"reporting":809},
"delegates":30,"date":"05-20"},
"state":"OR","party":"gop","total":287915,"locals":
{"Wheeler":
{"votes":[
{"votes":213,"name":"mccain"},
{"votes":42,"name":"paul"}],
"total":255,"precincts":
{"total":1,"reporting":1},
"name":"Wheeler"},
"Jackson":
{"votes":[
{"votes":13539,"name":"mccain"},
{"votes":2510,"name":"paul"}],
"total":16049,"precincts":
{"total":57,"reporting":38},
"name":"Jackson"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Grant"},
"Union":
{"votes":[
{"votes":3230,"name":"mccain"},
{"votes":672,"name":"paul"}],
"total":3902,"precincts":
{"total":7,"reporting":7},
"name":"Union"},
"Deschutes":
{"votes":[
{"votes":12697,"name":"mccain"},
{"votes":1591,"name":"paul"}],
"total":14288,"precincts":
{"total":43,"reporting":31},
"name":"Deschutes"},
"Lane":
{"votes":[
{"votes":21959,"name":"mccain"},
{"votes":3505,"name":"paul"}],
"total":25464,"precincts":
{"total":97,"reporting":63},
"name":"Lane"},
"Douglas":
{"votes":[
{"votes":12202,"name":"mccain"},
{"votes":2485,"name":"paul"}],
"total":14687,"precincts":
{"total":31,"reporting":26},
"name":"Douglas"},
"Klamath":
{"votes":[
{"votes":7992,"name":"mccain"},
{"votes":1136,"name":"paul"}],
"total":9128,"precincts":
{"total":17,"reporting":17},
"name":"Klamath"},
"Wasco":
{"votes":[
{"votes":2067,"name":"mccain"},
{"votes":407,"name":"paul"}],
"total":2474,"precincts":
{"total":7,"reporting":7},
"name":"Wasco"},
"Jefferson":
{"votes":[
{"votes":1818,"name":"mccain"},
{"votes":261,"name":"paul"}],
"total":2079,"precincts":
{"total":5,"reporting":5},
"name":"Jefferson"},
"Hood River":
{"votes":[
{"votes":1707,"name":"mccain"},
{"votes":237,"name":"paul"}],
"total":1944,"precincts":
{"total":5,"reporting":5},
"name":"Hood River"},
"Coos":
{"votes":[
{"votes":4903,"name":"mccain"},
{"votes":1162,"name":"paul"}],
"total":6065,"precincts":
{"total":18,"reporting":14},
"name":"Coos"},
"Multnomah":
{"votes":[
{"votes":21974,"name":"mccain"},
{"votes":3977,"name":"paul"}],
"total":25951,"precincts":
{"total":196,"reporting":180},
"name":"Multnomah"},
"Columbia":
{"votes":[
{"votes":2358,"name":"mccain"},
{"votes":467,"name":"paul"}],
"total":2825,"precincts":
{"total":14,"reporting":13},
"name":"Columbia"},
"Crook":
{"votes":[
{"votes":2616,"name":"mccain"},
{"votes":324,"name":"paul"}],
"total":2940,"precincts":
{"total":6,"reporting":6},
"name":"Crook"},
"Sherman":
{"votes":[
{"votes":308,"name":"mccain"},
{"votes":50,"name":"paul"}],
"total":358,"precincts":
{"total":1,"reporting":1},
"name":"Sherman"},
"Linn":
{"votes":[
{"votes":8845,"name":"mccain"},
{"votes":1301,"name":"paul"}],
"total":10146,"precincts":
{"total":29,"reporting":24},
"name":"Linn"},
"Lincoln":
{"votes":[
{"votes":3983,"name":"mccain"},
{"votes":619,"name":"paul"}],
"total":4602,"precincts":
{"total":13,"reporting":13},
"name":"Lincoln"},
"Wallowa":
{"votes":[
{"votes":1262,"name":"mccain"},
{"votes":366,"name":"paul"}],
"total":1628,"precincts":
{"total":2,"reporting":2},
"name":"Wallowa"},
"Baker":
{"votes":[
{"votes":2224,"name":"mccain"},
{"votes":445,"name":"paul"}],
"total":2669,"precincts":
{"total":5,"reporting":5},
"name":"Baker"},
"Clatsop":
{"votes":[
{"votes":2228,"name":"mccain"},
{"votes":394,"name":"paul"}],
"total":2622,"precincts":
{"total":11,"reporting":8},
"name":"Clatsop"},
"Benton":
{"votes":[
{"votes":5970,"name":"mccain"},
{"votes":1147,"name":"paul"}],
"total":7117,"precincts":
{"total":23,"reporting":23},
"name":"Benton"},
"Lake":
{"votes":[
{"votes":980,"name":"mccain"},
{"votes":109,"name":"paul"}],
"total":1089,"precincts":
{"total":2,"reporting":1},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":793,"name":"mccain"},
{"votes":222,"name":"paul"}],
"total":1015,"precincts":
{"total":2,"reporting":2},
"name":"Morrow"},
"Malheur":
{"votes":[
{"votes":2604,"name":"mccain"},
{"votes":559,"name":"paul"}],
"total":3163,"precincts":
{"total":6,"reporting":5},
"name":"Malheur"},
"Umatilla":
{"votes":[
{"votes":4656,"name":"mccain"},
{"votes":713,"name":"paul"}],
"total":5369,"precincts":
{"total":16,"reporting":13},
"name":"Umatilla"},
"Curry":
{"votes":[
{"votes":2776,"name":"mccain"},
{"votes":628,"name":"paul"}],
"total":3404,"precincts":
{"total":7,"reporting":6},
"name":"Curry"},
"Clackamas":
{"votes":[
{"votes":20076,"name":"mccain"},
{"votes":3256,"name":"paul"}],
"total":23332,"precincts":
{"total":103,"reporting":65},
"name":"Clackamas"},
"Gilliam":
{"votes":[
{"votes":301,"name":"mccain"},
{"votes":39,"name":"paul"}],
"total":340,"precincts":
{"total":1,"reporting":1},
"name":"Gilliam"},
"Harney":
{"votes":[
{"votes":1146,"name":"mccain"},
{"votes":157,"name":"paul"}],
"total":1303,"precincts":
{"total":2,"reporting":2},
"name":"Harney"},
"Josephine":
{"votes":[
{"votes":9775,"name":"mccain"},
{"votes":2547,"name":"paul"}],
"total":12322,"precincts":
{"total":24,"reporting":24},
"name":"Josephine"},
"Washington":
{"votes":[
{"votes":29845,"name":"mccain"},
{"votes":4880,"name":"paul"}],
"total":34725,"precincts":
{"total":127,"reporting":103},
"name":"Washington"},
"Tillamook":
{"votes":[
{"votes":2530,"name":"mccain"},
{"votes":525,"name":"paul"}],
"total":3055,"precincts":
{"total":7,"reporting":7},
"name":"Tillamook"},
"Yamhill":
{"votes":[
{"votes":6897,"name":"mccain"},
{"votes":1162,"name":"paul"}],
"total":8059,"precincts":
{"total":23,"reporting":17},
"name":"Yamhill"},
"Marion":
{"votes":[
{"votes":21610,"name":"mccain"},
{"votes":3228,"name":"paul"}],
"total":24838,"precincts":
{"total":70,"reporting":54},
"name":"Marion"},
"Polk":
{"votes":[
{"votes":7383,"name":"mccain"},
{"votes":1325,"name":"paul"}],
"total":8708,"precincts":
{"total":20,"reporting":20},
"name":"Polk"}}})