GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":157906,"name":"mccain"},
{"votes":33615,"name":"paul"},
{"votes":25759,"name":"huckabee"}],
"name":"Pennsylvania","precincts":
{"total":9268,"reporting":3892},
"delegates":74,"date":"04-22"},
"state":"PA","party":"gop","total":217280,"locals":
{"Lancaster":
{"votes":[],
"total":0,"precincts":
{"total":234,"reporting":0},
"name":"Lancaster"},
"Elk":
{"votes":[
{"votes":1332,"name":"mccain"},
{"votes":259,"name":"huckabee"},
{"votes":202,"name":"paul"}],
"total":1793,"precincts":
{"total":32,"reporting":25},
"name":"Elk"},
"Perry":
{"votes":[
{"votes":386,"name":"mccain"},
{"votes":142,"name":"paul"},
{"votes":60,"name":"huckabee"}],
"total":588,"precincts":
{"total":32,"reporting":6},
"name":"Perry"},
"Cumberland":
{"votes":[
{"votes":3991,"name":"mccain"},
{"votes":1144,"name":"paul"},
{"votes":632,"name":"huckabee"}],
"total":5767,"precincts":
{"total":101,"reporting":40},
"name":"Cumberland"},
"Susquehanna":
{"votes":[
{"votes":525,"name":"mccain"},
{"votes":145,"name":"huckabee"},
{"votes":134,"name":"paul"}],
"total":804,"precincts":
{"total":43,"reporting":10},
"name":"Susquehanna"},
"Union":
{"votes":[
{"votes":227,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":34,"name":"paul"}],
"total":310,"precincts":
{"total":27,"reporting":2},
"name":"Union"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Potter"},
"Delaware":
{"votes":[
{"votes":14428,"name":"mccain"},
{"votes":2478,"name":"paul"},
{"votes":1083,"name":"huckabee"}],
"total":17989,"precincts":
{"total":425,"reporting":151},
"name":"Delaware"},
"Philadelphia":
{"votes":[
{"votes":13196,"name":"mccain"},
{"votes":2346,"name":"paul"},
{"votes":1019,"name":"huckabee"}],
"total":16561,"precincts":
{"total":1681,"reporting":1115},
"name":"Philadelphia"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":413,"reporting":0},
"name":"Montgomery"},
"Lawrence":
{"votes":[
{"votes":1991,"name":"mccain"},
{"votes":418,"name":"huckabee"},
{"votes":308,"name":"paul"}],
"total":2717,"precincts":
{"total":106,"reporting":67},
"name":"Lawrence"},
"Jefferson":
{"votes":[
{"votes":3040,"name":"mccain"},
{"votes":662,"name":"huckabee"},
{"votes":442,"name":"paul"}],
"total":4144,"precincts":
{"total":37,"reporting":31},
"name":"Jefferson"},
"Forest":
{"votes":[
{"votes":237,"name":"mccain"},
{"votes":51,"name":"paul"},
{"votes":35,"name":"huckabee"}],
"total":323,"precincts":
{"total":9,"reporting":4},
"name":"Forest"},
"Butler":
{"votes":[
{"votes":1710,"name":"mccain"},
{"votes":382,"name":"paul"},
{"votes":344,"name":"huckabee"}],
"total":2436,"precincts":
{"total":85,"reporting":19},
"name":"Butler"},
"Indiana":
{"votes":[],
"total":0,"precincts":
{"total":69,"reporting":0},
"name":"Indiana"},
"Somerset":
{"votes":[],
"total":0,"precincts":
{"total":68,"reporting":0},
"name":"Somerset"},
"Dauphin":
{"votes":[
{"votes":943,"name":"mccain"},
{"votes":278,"name":"paul"},
{"votes":184,"name":"huckabee"}],
"total":1405,"precincts":
{"total":159,"reporting":22},
"name":"Dauphin"},
"Juniata":
{"votes":[
{"votes":452,"name":"mccain"},
{"votes":230,"name":"paul"},
{"votes":100,"name":"huckabee"}],
"total":782,"precincts":
{"total":20,"reporting":10},
"name":"Juniata"},
"Tioga":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Tioga"},
"Montour":
{"votes":[
{"votes":278,"name":"mccain"},
{"votes":50,"name":"paul"},
{"votes":46,"name":"huckabee"}],
"total":374,"precincts":
{"total":15,"reporting":6},
"name":"Montour"},
"Columbia":
{"votes":[
{"votes":2850,"name":"mccain"},
{"votes":750,"name":"paul"},
{"votes":514,"name":"huckabee"}],
"total":4114,"precincts":
{"total":42,"reporting":39},
"name":"Columbia"},
"Schuylkill":
{"votes":[
{"votes":2271,"name":"mccain"},
{"votes":386,"name":"paul"},
{"votes":307,"name":"huckabee"}],
"total":2964,"precincts":
{"total":167,"reporting":63},
"name":"Schuylkill"},
"Centre":
{"votes":[
{"votes":462,"name":"mccain"},
{"votes":91,"name":"paul"},
{"votes":74,"name":"huckabee"}],
"total":627,"precincts":
{"total":89,"reporting":6},
"name":"Centre"},
"Crawford":
{"votes":[
{"votes":1104,"name":"mccain"},
{"votes":430,"name":"paul"},
{"votes":307,"name":"huckabee"}],
"total":1841,"precincts":
{"total":67,"reporting":24},
"name":"Crawford"},
"Blair":
{"votes":[
{"votes":6043,"name":"mccain"},
{"votes":1450,"name":"huckabee"},
{"votes":1167,"name":"paul"}],
"total":8660,"precincts":
{"total":97,"reporting":75},
"name":"Blair"},
"Fayette":
{"votes":[
{"votes":276,"name":"mccain"},
{"votes":57,"name":"paul"},
{"votes":42,"name":"huckabee"}],
"total":375,"precincts":
{"total":105,"reporting":10},
"name":"Fayette"},
"Cambria":
{"votes":[
{"votes":2847,"name":"mccain"},
{"votes":600,"name":"huckabee"},
{"votes":506,"name":"paul"}],
"total":3953,"precincts":
{"total":165,"reporting":95},
"name":"Cambria"},
"York":
{"votes":[
{"votes":1181,"name":"mccain"},
{"votes":287,"name":"paul"},
{"votes":175,"name":"huckabee"}],
"total":1643,"precincts":
{"total":159,"reporting":13},
"name":"York"},
"Franklin":
{"votes":[
{"votes":761,"name":"mccain"},
{"votes":175,"name":"huckabee"},
{"votes":141,"name":"paul"}],
"total":1077,"precincts":
{"total":74,"reporting":10},
"name":"Franklin"},
"Lebanon":
{"votes":[
{"votes":5278,"name":"mccain"},
{"votes":1556,"name":"paul"},
{"votes":1258,"name":"huckabee"}],
"total":8092,"precincts":
{"total":55,"reporting":39},
"name":"Lebanon"},
"Carbon":
{"votes":[
{"votes":744,"name":"mccain"},
{"votes":137,"name":"huckabee"},
{"votes":126,"name":"paul"}],
"total":1007,"precincts":
{"total":45,"reporting":18},
"name":"Carbon"},
"Venango":
{"votes":[
{"votes":861,"name":"mccain"},
{"votes":273,"name":"huckabee"},
{"votes":265,"name":"paul"}],
"total":1399,"precincts":
{"total":48,"reporting":17},
"name":"Venango"},
"Bradford":
{"votes":[
{"votes":63,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":11,"name":"paul"}],
"total":96,"precincts":
{"total":61,"reporting":1},
"name":"Bradford"},
"Pike":
{"votes":[
{"votes":77,"name":"mccain"},
{"votes":19,"name":"paul"},
{"votes":8,"name":"huckabee"}],
"total":104,"precincts":
{"total":18,"reporting":1},
"name":"Pike"},
"Bucks":
{"votes":[
{"votes":1055,"name":"mccain"},
{"votes":220,"name":"paul"},
{"votes":122,"name":"huckabee"}],
"total":1397,"precincts":
{"total":301,"reporting":19},
"name":"Bucks"},
"Wyoming":
{"votes":[
{"votes":2252,"name":"mccain"},
{"votes":620,"name":"paul"},
{"votes":490,"name":"huckabee"}],
"total":3362,"precincts":
{"total":31,"reporting":30},
"name":"Wyoming"},
"Adams":
{"votes":[
{"votes":982,"name":"mccain"},
{"votes":258,"name":"paul"},
{"votes":197,"name":"huckabee"}],
"total":1437,"precincts":
{"total":48,"reporting":10},
"name":"Adams"},
"Bedford":
{"votes":[
{"votes":1867,"name":"mccain"},
{"votes":470,"name":"huckabee"},
{"votes":197,"name":"paul"}],
"total":2534,"precincts":
{"total":40,"reporting":18},
"name":"Bedford"},
"Clearfield":
{"votes":[
{"votes":2452,"name":"mccain"},
{"votes":581,"name":"huckabee"},
{"votes":391,"name":"paul"}],
"total":3424,"precincts":
{"total":71,"reporting":32},
"name":"Clearfield"},
"Northumberland":
{"votes":[
{"votes":4802,"name":"mccain"},
{"votes":924,"name":"paul"},
{"votes":846,"name":"huckabee"}],
"total":6572,"precincts":
{"total":94,"reporting":86},
"name":"Northumberland"},
"Clarion":
{"votes":[
{"votes":1918,"name":"mccain"},
{"votes":454,"name":"huckabee"},
{"votes":413,"name":"paul"}],
"total":2785,"precincts":
{"total":41,"reporting":25},
"name":"Clarion"},
"Greene":
{"votes":[
{"votes":880,"name":"mccain"},
{"votes":175,"name":"huckabee"},
{"votes":140,"name":"paul"}],
"total":1195,"precincts":
{"total":44,"reporting":34},
"name":"Greene"},
"Washington":
{"votes":[
{"votes":2153,"name":"mccain"},
{"votes":401,"name":"huckabee"},
{"votes":339,"name":"paul"}],
"total":2893,"precincts":
{"total":185,"reporting":60},
"name":"Washington"},
"Westmoreland":
{"votes":[
{"votes":2044,"name":"mccain"},
{"votes":427,"name":"paul"},
{"votes":380,"name":"huckabee"}],
"total":2851,"precincts":
{"total":306,"reporting":61},
"name":"Westmoreland"},
"Snyder":
{"votes":[
{"votes":232,"name":"mccain"},
{"votes":65,"name":"huckabee"},
{"votes":50,"name":"paul"}],
"total":347,"precincts":
{"total":25,"reporting":3},
"name":"Snyder"},
"Berks":
{"votes":[
{"votes":3945,"name":"mccain"},
{"votes":1637,"name":"paul"},
{"votes":647,"name":"huckabee"}],
"total":6229,"precincts":
{"total":193,"reporting":75},
"name":"Berks"},
"Fulton":
{"votes":[
{"votes":5,"name":"mccain"},
{"votes":3,"name":"paul"}],
"total":8,"precincts":
{"total":13,"reporting":1},
"name":"Fulton"},
"Lackawanna":
{"votes":[
{"votes":424,"name":"mccain"},
{"votes":81,"name":"paul"},
{"votes":66,"name":"huckabee"}],
"total":571,"precincts":
{"total":163,"reporting":21},
"name":"Lackawanna"},
"Erie":
{"votes":[
{"votes":6388,"name":"mccain"},
{"votes":1445,"name":"paul"},
{"votes":1328,"name":"huckabee"}],
"total":9161,"precincts":
{"total":155,"reporting":65},
"name":"Erie"},
"Clinton":
{"votes":[
{"votes":1042,"name":"mccain"},
{"votes":197,"name":"huckabee"},
{"votes":123,"name":"paul"}],
"total":1362,"precincts":
{"total":36,"reporting":18},
"name":"Clinton"},
"Armstrong":
{"votes":[
{"votes":2709,"name":"mccain"},
{"votes":558,"name":"paul"},
{"votes":478,"name":"huckabee"}],
"total":3745,"precincts":
{"total":74,"reporting":53},
"name":"Armstrong"},
"Luzerne":
{"votes":[
{"votes":10533,"name":"mccain"},
{"votes":2362,"name":"paul"},
{"votes":1969,"name":"huckabee"}],
"total":14864,"precincts":
{"total":189,"reporting":161},
"name":"Luzerne"},
"Lycoming":
{"votes":[
{"votes":7517,"name":"mccain"},
{"votes":1252,"name":"paul"},
{"votes":1127,"name":"huckabee"}],
"total":9896,"precincts":
{"total":86,"reporting":62},
"name":"Lycoming"},
"Huntingdon":
{"votes":[
{"votes":857,"name":"mccain"},
{"votes":242,"name":"huckabee"},
{"votes":149,"name":"paul"}],
"total":1248,"precincts":
{"total":58,"reporting":19},
"name":"Huntingdon"},
"Northampton":
{"votes":[
{"votes":324,"name":"mccain"},
{"votes":99,"name":"paul"},
{"votes":62,"name":"huckabee"}],
"total":485,"precincts":
{"total":149,"reporting":14},
"name":"Northampton"},
"Mifflin":
{"votes":[
{"votes":1257,"name":"mccain"},
{"votes":274,"name":"huckabee"},
{"votes":171,"name":"paul"}],
"total":1702,"precincts":
{"total":30,"reporting":15},
"name":"Mifflin"},
"Sullivan":
{"votes":[
{"votes":16,"name":"mccain"},
{"votes":6,"name":"paul"},
{"votes":4,"name":"huckabee"}],
"total":26,"precincts":
{"total":15,"reporting":1},
"name":"Sullivan"},
"Chester":
{"votes":[],
"total":0,"precincts":
{"total":224,"reporting":0},
"name":"Chester"},
"Lehigh":
{"votes":[
{"votes":628,"name":"mccain"},
{"votes":175,"name":"paul"},
{"votes":85,"name":"huckabee"}],
"total":888,"precincts":
{"total":151,"reporting":19},
"name":"Lehigh"},
"Wayne":
{"votes":[
{"votes":293,"name":"mccain"},
{"votes":45,"name":"paul"},
{"votes":40,"name":"huckabee"}],
"total":378,"precincts":
{"total":37,"reporting":6},
"name":"Wayne"},
"Cameron":
{"votes":[
{"votes":131,"name":"mccain"},
{"votes":24,"name":"huckabee"},
{"votes":11,"name":"paul"}],
"total":166,"precincts":
{"total":10,"reporting":4},
"name":"Cameron"},
"Beaver":
{"votes":[
{"votes":2672,"name":"mccain"},
{"votes":593,"name":"paul"},
{"votes":469,"name":"huckabee"}],
"total":3734,"precincts":
{"total":129,"reporting":60},
"name":"Beaver"},
"Allegheny":
{"votes":[
{"votes":26352,"name":"mccain"},
{"votes":5894,"name":"paul"},
{"votes":3203,"name":"huckabee"}],
"total":35449,"precincts":
{"total":1321,"reporting":941},
"name":"Allegheny"},
"McKean":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":4,"name":"paul"}],
"total":33,"precincts":
{"total":42,"reporting":1},
"name":"McKean"},
"Mercer":
{"votes":[
{"votes":1687,"name":"mccain"},
{"votes":420,"name":"huckabee"},
{"votes":389,"name":"paul"}],
"total":2496,"precincts":
{"total":100,"reporting":22},
"name":"Mercer"},
"Monroe":
{"votes":[
{"votes":596,"name":"mccain"},
{"votes":114,"name":"paul"},
{"votes":91,"name":"huckabee"}],
"total":801,"precincts":
{"total":50,"reporting":10},
"name":"Monroe"},
"Warren":
{"votes":[
{"votes":2317,"name":"mccain"},
{"votes":512,"name":"paul"},
{"votes":467,"name":"huckabee"}],
"total":3296,"precincts":
{"total":33,"reporting":27},
"name":"Warren"}}})