GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":83728,"name":"clinton"},
{"votes":57467,"name":"obama"},
{"votes":879,"name":"edwards"},
{"votes":749,"name":"uncommitted-d"}],
"name":"Rhode Island","precincts":
{"total":179,"reporting":146},
"delegates":21,"date":"03-04"},
"state":"RI","party":"dem","total":142823,"locals":
{"Middletown":
{"votes":[
{"votes":1195,"name":"clinton"},
{"votes":1096,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":11,"name":"uncommitted-d"}],
"total":2321,"precincts":
{"total":4,"reporting":4},
"name":"Middletown"},
"Cumberland":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Cumberland"},
"Hopkinton":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hopkinton"},
"Central Falls":
{"votes":[
{"votes":1343,"name":"clinton"},
{"votes":550,"name":"obama"},
{"votes":11,"name":"uncommitted-d"},
{"votes":8,"name":"edwards"}],
"total":1912,"precincts":
{"total":5,"reporting":5},
"name":"Central Falls"},
"Barrington":
{"votes":[
{"votes":2031,"name":"obama"},
{"votes":1874,"name":"clinton"},
{"votes":15,"name":"edwards"},
{"votes":12,"name":"uncommitted-d"}],
"total":3932,"precincts":
{"total":3,"reporting":3},
"name":"Barrington"},
"Richmond":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Richmond"},
"Providence":
{"votes":[
{"votes":2248,"name":"obama"},
{"votes":1832,"name":"clinton"},
{"votes":18,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"}],
"total":4115,"precincts":
{"total":31,"reporting":6},
"name":"Providence"},
"Foster":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Foster"},
"Warwick":
{"votes":[
{"votes":10010,"name":"clinton"},
{"votes":6240,"name":"obama"},
{"votes":109,"name":"edwards"},
{"votes":84,"name":"uncommitted-d"}],
"total":16443,"precincts":
{"total":9,"reporting":9},
"name":"Warwick"},
"Jamestown":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Jamestown"},
"Smithfield":
{"votes":[
{"votes":2343,"name":"clinton"},
{"votes":1205,"name":"obama"},
{"votes":32,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"}],
"total":3597,"precincts":
{"total":4,"reporting":4},
"name":"Smithfield"},
"Mail Ballots - CD2":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD2"},
"Cranston":
{"votes":[
{"votes":6192,"name":"clinton"},
{"votes":3863,"name":"obama"},
{"votes":47,"name":"edwards"},
{"votes":39,"name":"uncommitted-d"}],
"total":10141,"precincts":
{"total":10,"reporting":7},
"name":"Cranston"},
"East Providence":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"East Providence"},
"Mail Ballots - CD1":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD1"},
"Glocester":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Glocester"},
"Little Compton":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Little Compton"},
"West Greenwich":
{"votes":[
{"votes":550,"name":"clinton"},
{"votes":353,"name":"obama"},
{"votes":3,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":907,"precincts":
{"total":1,"reporting":1},
"name":"West Greenwich"},
"Charlestown":
{"votes":[
{"votes":697,"name":"clinton"},
{"votes":682,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":3,"name":"uncommitted-d"}],
"total":1392,"precincts":
{"total":3,"reporting":3},
"name":"Charlestown"},
"North Smithfield":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Smithfield"},
"Lincoln":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Lincoln"},
"Coventry":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Coventry"},
"South Kingstown":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"South Kingstown"},
"West Warwick":
{"votes":[
{"votes":2790,"name":"clinton"},
{"votes":1348,"name":"obama"},
{"votes":33,"name":"edwards"},
{"votes":26,"name":"uncommitted-d"}],
"total":4197,"precincts":
{"total":5,"reporting":5},
"name":"West Warwick"},
"Burrillville":
{"votes":[
{"votes":1427,"name":"clinton"},
{"votes":704,"name":"obama"},
{"votes":20,"name":"uncommitted-d"},
{"votes":20,"name":"edwards"}],
"total":2171,"precincts":
{"total":4,"reporting":4},
"name":"Burrillville"},
"Newport":
{"votes":[
{"votes":2162,"name":"obama"},
{"votes":1777,"name":"clinton"},
{"votes":24,"name":"uncommitted-d"},
{"votes":21,"name":"edwards"}],
"total":3984,"precincts":
{"total":4,"reporting":4},
"name":"Newport"},
"Bristol":
{"votes":[
{"votes":2426,"name":"clinton"},
{"votes":1486,"name":"obama"},
{"votes":22,"name":"edwards"},
{"votes":19,"name":"uncommitted-d"}],
"total":3953,"precincts":
{"total":3,"reporting":3},
"name":"Bristol"},
"Johnston":
{"votes":[
{"votes":5018,"name":"clinton"},
{"votes":1539,"name":"obama"},
{"votes":54,"name":"edwards"},
{"votes":53,"name":"uncommitted-d"}],
"total":6664,"precincts":
{"total":5,"reporting":5},
"name":"Johnston"},
"Scituate":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Scituate"},
"New Shoreham":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"New Shoreham"},
"Exeter":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Exeter"},
"North Providence":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Providence"},
"Westerly":
{"votes":[
{"votes":1817,"name":"clinton"},
{"votes":1320,"name":"obama"},
{"votes":19,"name":"uncommitted-d"},
{"votes":14,"name":"edwards"}],
"total":3170,"precincts":
{"total":3,"reporting":3},
"name":"Westerly"},
"North Kingstown":
{"votes":[
{"votes":2528,"name":"clinton"},
{"votes":2451,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":24,"name":"uncommitted-d"}],
"total":5030,"precincts":
{"total":4,"reporting":4},
"name":"North Kingstown"},
"Portsmouth":
{"votes":[
{"votes":1330,"name":"clinton"},
{"votes":1212,"name":"obama"},
{"votes":16,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"}],
"total":2562,"precincts":
{"total":5,"reporting":4},
"name":"Portsmouth"},
"Narragansett":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Narragansett"},
"Tiverton":
{"votes":[
{"votes":1950,"name":"clinton"},
{"votes":1030,"name":"obama"},
{"votes":20,"name":"edwards"},
{"votes":18,"name":"uncommitted-d"}],
"total":3018,"precincts":
{"total":4,"reporting":4},
"name":"Tiverton"},
"Woonsocket":
{"votes":[
{"votes":3705,"name":"clinton"},
{"votes":1827,"name":"obama"},
{"votes":48,"name":"edwards"},
{"votes":44,"name":"uncommitted-d"}],
"total":5624,"precincts":
{"total":8,"reporting":8},
"name":"Woonsocket"},
"East Greenwich":
{"votes":[
{"votes":1227,"name":"obama"},
{"votes":1168,"name":"clinton"},
{"votes":13,"name":"edwards"},
{"votes":7,"name":"uncommitted-d"}],
"total":2415,"precincts":
{"total":2,"reporting":2},
"name":"East Greenwich"},
"Pawtucket":
{"votes":[
{"votes":6680,"name":"clinton"},
{"votes":3654,"name":"obama"},
{"votes":94,"name":"uncommitted-d"},
{"votes":82,"name":"edwards"}],
"total":10510,"precincts":
{"total":17,"reporting":15},
"name":"Pawtucket"},
"Warren":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Warren"}}})