GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":106471,"name":"clinton","delegates":12},
{"votes":73609,"name":"obama","delegates":8},
{"votes":1112,"name":"edwards"},
{"votes":1012,"name":"uncommitted-d"}],
"name":"Rhode Island","precincts":
{"total":179,"reporting":176},
"delegates":21,"date":"03-04"},
"state":"RI","party":"dem","total":182204,"locals":
{"Middletown":
{"votes":[
{"votes":1195,"name":"clinton"},
{"votes":1096,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":11,"name":"uncommitted-d"}],
"total":2321,"precincts":
{"total":4,"reporting":4},
"name":"Middletown"},
"Cumberland":
{"votes":[
{"votes":4537,"name":"clinton"},
{"votes":2587,"name":"obama"},
{"votes":57,"name":"edwards"},
{"votes":45,"name":"uncommitted-d"}],
"total":7226,"precincts":
{"total":5,"reporting":5},
"name":"Cumberland"},
"Hopkinton":
{"votes":[
{"votes":580,"name":"clinton"},
{"votes":519,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"}],
"total":1110,"precincts":
{"total":1,"reporting":1},
"name":"Hopkinton"},
"Central Falls":
{"votes":[
{"votes":1343,"name":"clinton"},
{"votes":550,"name":"obama"},
{"votes":11,"name":"uncommitted-d"},
{"votes":8,"name":"edwards"}],
"total":1912,"precincts":
{"total":5,"reporting":5},
"name":"Central Falls"},
"Barrington":
{"votes":[
{"votes":2031,"name":"obama"},
{"votes":1874,"name":"clinton"},
{"votes":15,"name":"edwards"},
{"votes":12,"name":"uncommitted-d"}],
"total":3932,"precincts":
{"total":3,"reporting":3},
"name":"Barrington"},
"Richmond":
{"votes":[
{"votes":662,"name":"clinton"},
{"votes":505,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"}],
"total":1178,"precincts":
{"total":1,"reporting":1},
"name":"Richmond"},
"Providence":
{"votes":[
{"votes":11634,"name":"obama"},
{"votes":9966,"name":"clinton"},
{"votes":81,"name":"uncommitted-d"},
{"votes":79,"name":"edwards"}],
"total":21760,"precincts":
{"total":31,"reporting":28},
"name":"Providence"},
"Foster":
{"votes":[
{"votes":377,"name":"clinton"},
{"votes":304,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":3,"name":"uncommitted-d"}],
"total":689,"precincts":
{"total":1,"reporting":1},
"name":"Foster"},
"Warwick":
{"votes":[
{"votes":10010,"name":"clinton"},
{"votes":6240,"name":"obama"},
{"votes":109,"name":"edwards"},
{"votes":84,"name":"uncommitted-d"}],
"total":16443,"precincts":
{"total":9,"reporting":9},
"name":"Warwick"},
"Jamestown":
{"votes":[
{"votes":815,"name":"obama"},
{"votes":644,"name":"clinton"},
{"votes":5,"name":"uncommitted-d"},
{"votes":4,"name":"edwards"}],
"total":1468,"precincts":
{"total":1,"reporting":1},
"name":"Jamestown"},
"Smithfield":
{"votes":[
{"votes":2343,"name":"clinton"},
{"votes":1205,"name":"obama"},
{"votes":32,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"}],
"total":3597,"precincts":
{"total":4,"reporting":4},
"name":"Smithfield"},
"Mail Ballots - CD2":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD2"},
"Cranston":
{"votes":[
{"votes":8761,"name":"clinton"},
{"votes":4992,"name":"obama"},
{"votes":65,"name":"edwards"},
{"votes":48,"name":"uncommitted-d"}],
"total":13866,"precincts":
{"total":10,"reporting":10},
"name":"Cranston"},
"East Providence":
{"votes":[
{"votes":5614,"name":"clinton"},
{"votes":3950,"name":"obama"},
{"votes":42,"name":"uncommitted-d"},
{"votes":35,"name":"edwards"}],
"total":9641,"precincts":
{"total":4,"reporting":4},
"name":"East Providence"},
"Mail Ballots - CD1":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD1"},
"Glocester":
{"votes":[
{"votes":907,"name":"clinton"},
{"votes":605,"name":"obama"},
{"votes":12,"name":"edwards"},
{"votes":6,"name":"uncommitted-d"}],
"total":1530,"precincts":
{"total":1,"reporting":1},
"name":"Glocester"},
"Little Compton":
{"votes":[
{"votes":436,"name":"obama"},
{"votes":327,"name":"clinton"},
{"votes":6,"name":"edwards"},
{"votes":2,"name":"uncommitted-d"}],
"total":771,"precincts":
{"total":1,"reporting":1},
"name":"Little Compton"},
"West Greenwich":
{"votes":[
{"votes":550,"name":"clinton"},
{"votes":353,"name":"obama"},
{"votes":3,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":907,"precincts":
{"total":1,"reporting":1},
"name":"West Greenwich"},
"Charlestown":
{"votes":[
{"votes":697,"name":"clinton"},
{"votes":682,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":3,"name":"uncommitted-d"}],
"total":1392,"precincts":
{"total":3,"reporting":3},
"name":"Charlestown"},
"North Smithfield":
{"votes":[
{"votes":1369,"name":"clinton"},
{"votes":693,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":12,"name":"uncommitted-d"}],
"total":2093,"precincts":
{"total":3,"reporting":3},
"name":"North Smithfield"},
"Lincoln":
{"votes":[
{"votes":2560,"name":"clinton"},
{"votes":1456,"name":"obama"},
{"votes":28,"name":"uncommitted-d"},
{"votes":21,"name":"edwards"}],
"total":4065,"precincts":
{"total":5,"reporting":5},
"name":"Lincoln"},
"Coventry":
{"votes":[
{"votes":3736,"name":"clinton"},
{"votes":2152,"name":"obama"},
{"votes":44,"name":"edwards"},
{"votes":40,"name":"uncommitted-d"}],
"total":5972,"precincts":
{"total":5,"reporting":5},
"name":"Coventry"},
"South Kingstown":
{"votes":[
{"votes":2776,"name":"obama"},
{"votes":2401,"name":"clinton"},
{"votes":25,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"}],
"total":5217,"precincts":
{"total":3,"reporting":3},
"name":"South Kingstown"},
"West Warwick":
{"votes":[
{"votes":2790,"name":"clinton"},
{"votes":1348,"name":"obama"},
{"votes":33,"name":"edwards"},
{"votes":26,"name":"uncommitted-d"}],
"total":4197,"precincts":
{"total":5,"reporting":5},
"name":"West Warwick"},
"Burrillville":
{"votes":[
{"votes":1427,"name":"clinton"},
{"votes":704,"name":"obama"},
{"votes":20,"name":"uncommitted-d"},
{"votes":20,"name":"edwards"}],
"total":2171,"precincts":
{"total":4,"reporting":4},
"name":"Burrillville"},
"Newport":
{"votes":[
{"votes":2162,"name":"obama"},
{"votes":1777,"name":"clinton"},
{"votes":24,"name":"uncommitted-d"},
{"votes":21,"name":"edwards"}],
"total":3984,"precincts":
{"total":4,"reporting":4},
"name":"Newport"},
"Bristol":
{"votes":[
{"votes":2426,"name":"clinton"},
{"votes":1486,"name":"obama"},
{"votes":22,"name":"edwards"},
{"votes":19,"name":"uncommitted-d"}],
"total":3953,"precincts":
{"total":3,"reporting":3},
"name":"Bristol"},
"Johnston":
{"votes":[
{"votes":5018,"name":"clinton"},
{"votes":1539,"name":"obama"},
{"votes":54,"name":"edwards"},
{"votes":53,"name":"uncommitted-d"}],
"total":6664,"precincts":
{"total":5,"reporting":5},
"name":"Johnston"},
"Scituate":
{"votes":[
{"votes":939,"name":"clinton"},
{"votes":593,"name":"obama"},
{"votes":12,"name":"uncommitted-d"},
{"votes":11,"name":"edwards"}],
"total":1555,"precincts":
{"total":2,"reporting":2},
"name":"Scituate"},
"New Shoreham":
{"votes":[
{"votes":209,"name":"obama"},
{"votes":117,"name":"clinton"},
{"votes":2,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"}],
"total":328,"precincts":
{"total":1,"reporting":1},
"name":"New Shoreham"},
"Exeter":
{"votes":[
{"votes":492,"name":"clinton"},
{"votes":439,"name":"obama"},
{"votes":4,"name":"uncommitted-d"},
{"votes":4,"name":"edwards"}],
"total":939,"precincts":
{"total":1,"reporting":1},
"name":"Exeter"},
"North Providence":
{"votes":[
{"votes":5566,"name":"clinton"},
{"votes":2332,"name":"obama"},
{"votes":61,"name":"uncommitted-d"},
{"votes":60,"name":"edwards"}],
"total":8019,"precincts":
{"total":3,"reporting":3},
"name":"North Providence"},
"Westerly":
{"votes":[
{"votes":1817,"name":"clinton"},
{"votes":1320,"name":"obama"},
{"votes":19,"name":"uncommitted-d"},
{"votes":14,"name":"edwards"}],
"total":3170,"precincts":
{"total":3,"reporting":3},
"name":"Westerly"},
"North Kingstown":
{"votes":[
{"votes":2528,"name":"clinton"},
{"votes":2451,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":24,"name":"uncommitted-d"}],
"total":5030,"precincts":
{"total":4,"reporting":4},
"name":"North Kingstown"},
"Portsmouth":
{"votes":[
{"votes":1657,"name":"clinton"},
{"votes":1470,"name":"obama"},
{"votes":20,"name":"edwards"},
{"votes":6,"name":"uncommitted-d"}],
"total":3153,"precincts":
{"total":5,"reporting":5},
"name":"Portsmouth"},
"Narragansett":
{"votes":[
{"votes":1549,"name":"clinton"},
{"votes":1361,"name":"obama"},
{"votes":17,"name":"edwards"},
{"votes":16,"name":"uncommitted-d"}],
"total":2943,"precincts":
{"total":2,"reporting":2},
"name":"Narragansett"},
"Tiverton":
{"votes":[
{"votes":1950,"name":"clinton"},
{"votes":1030,"name":"obama"},
{"votes":20,"name":"edwards"},
{"votes":18,"name":"uncommitted-d"}],
"total":3018,"precincts":
{"total":4,"reporting":4},
"name":"Tiverton"},
"Woonsocket":
{"votes":[
{"votes":3705,"name":"clinton"},
{"votes":1827,"name":"obama"},
{"votes":48,"name":"edwards"},
{"votes":44,"name":"uncommitted-d"}],
"total":5624,"precincts":
{"total":8,"reporting":8},
"name":"Woonsocket"},
"East Greenwich":
{"votes":[
{"votes":1227,"name":"obama"},
{"votes":1168,"name":"clinton"},
{"votes":13,"name":"edwards"},
{"votes":7,"name":"uncommitted-d"}],
"total":2415,"precincts":
{"total":2,"reporting":2},
"name":"East Greenwich"},
"Pawtucket":
{"votes":[
{"votes":7253,"name":"clinton"},
{"votes":4062,"name":"obama"},
{"votes":99,"name":"uncommitted-d"},
{"votes":87,"name":"edwards"}],
"total":11501,"precincts":
{"total":17,"reporting":17},
"name":"Pawtucket"},
"Warren":
{"votes":[
{"votes":1256,"name":"clinton"},
{"votes":742,"name":"obama"},
{"votes":14,"name":"edwards"},
{"votes":9,"name":"uncommitted-d"}],
"total":2021,"precincts":
{"total":3,"reporting":3},
"name":"Warren"}}})