GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":48682,"name":"clinton"},
{"votes":30177,"name":"obama"},
{"votes":541,"name":"edwards"},
{"votes":477,"name":"uncommitted-d"}],
"name":"Rhode Island","precincts":
{"total":179,"reporting":87},
"delegates":21,"date":"03-04"},
"state":"RI","party":"dem","total":79877,"locals":
{"Middletown":
{"votes":[
{"votes":1195,"name":"clinton"},
{"votes":1096,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":11,"name":"uncommitted-d"}],
"total":2321,"precincts":
{"total":4,"reporting":4},
"name":"Middletown"},
"Cumberland":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Cumberland"},
"Hopkinton":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hopkinton"},
"Central Falls":
{"votes":[
{"votes":1343,"name":"clinton"},
{"votes":550,"name":"obama"},
{"votes":11,"name":"uncommitted-d"},
{"votes":8,"name":"edwards"}],
"total":1912,"precincts":
{"total":5,"reporting":5},
"name":"Central Falls"},
"Barrington":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Barrington"},
"Richmond":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Richmond"},
"Providence":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Providence"},
"Foster":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Foster"},
"Warwick":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Warwick"},
"Jamestown":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Jamestown"},
"Smithfield":
{"votes":[
{"votes":1977,"name":"clinton"},
{"votes":986,"name":"obama"},
{"votes":29,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"}],
"total":3007,"precincts":
{"total":4,"reporting":3},
"name":"Smithfield"},
"Mail Ballots - CD2":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD2"},
"Cranston":
{"votes":[
{"votes":865,"name":"clinton"},
{"votes":491,"name":"obama"},
{"votes":13,"name":"edwards"},
{"votes":10,"name":"uncommitted-d"}],
"total":1379,"precincts":
{"total":10,"reporting":1},
"name":"Cranston"},
"East Providence":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"East Providence"},
"Mail Ballots - CD1":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD1"},
"Glocester":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Glocester"},
"Little Compton":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Little Compton"},
"West Greenwich":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"West Greenwich"},
"Charlestown":
{"votes":[
{"votes":203,"name":"obama"},
{"votes":202,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":409,"precincts":
{"total":3,"reporting":1},
"name":"Charlestown"},
"North Smithfield":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Smithfield"},
"Lincoln":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Lincoln"},
"Coventry":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Coventry"},
"South Kingstown":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"South Kingstown"},
"West Warwick":
{"votes":[
{"votes":1732,"name":"clinton"},
{"votes":798,"name":"obama"},
{"votes":22,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"}],
"total":2569,"precincts":
{"total":5,"reporting":3},
"name":"West Warwick"},
"Burrillville":
{"votes":[
{"votes":1427,"name":"clinton"},
{"votes":704,"name":"obama"},
{"votes":20,"name":"uncommitted-d"},
{"votes":20,"name":"edwards"}],
"total":2171,"precincts":
{"total":4,"reporting":4},
"name":"Burrillville"},
"Newport":
{"votes":[
{"votes":2162,"name":"obama"},
{"votes":1777,"name":"clinton"},
{"votes":24,"name":"uncommitted-d"},
{"votes":21,"name":"edwards"}],
"total":3984,"precincts":
{"total":4,"reporting":4},
"name":"Newport"},
"Bristol":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Bristol"},
"Johnston":
{"votes":[
{"votes":5018,"name":"clinton"},
{"votes":1539,"name":"obama"},
{"votes":54,"name":"edwards"},
{"votes":53,"name":"uncommitted-d"}],
"total":6664,"precincts":
{"total":5,"reporting":5},
"name":"Johnston"},
"Scituate":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Scituate"},
"New Shoreham":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"New Shoreham"},
"Exeter":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Exeter"},
"North Providence":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Providence"},
"Westerly":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Westerly"},
"North Kingstown":
{"votes":[
{"votes":2528,"name":"clinton"},
{"votes":2451,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":24,"name":"uncommitted-d"}],
"total":5030,"precincts":
{"total":4,"reporting":4},
"name":"North Kingstown"},
"Portsmouth":
{"votes":[
{"votes":1330,"name":"clinton"},
{"votes":1212,"name":"obama"},
{"votes":16,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"}],
"total":2562,"precincts":
{"total":5,"reporting":4},
"name":"Portsmouth"},
"Narragansett":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Narragansett"},
"Tiverton":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Tiverton"},
"Woonsocket":
{"votes":[
{"votes":3233,"name":"clinton"},
{"votes":1595,"name":"obama"},
{"votes":44,"name":"edwards"},
{"votes":38,"name":"uncommitted-d"}],
"total":4910,"precincts":
{"total":8,"reporting":7},
"name":"Woonsocket"},
"East Greenwich":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"East Greenwich"},
"Pawtucket":
{"votes":[
{"votes":4844,"name":"clinton"},
{"votes":2773,"name":"obama"},
{"votes":72,"name":"uncommitted-d"},
{"votes":60,"name":"edwards"}],
"total":7749,"precincts":
{"total":17,"reporting":13},
"name":"Pawtucket"},
"Warren":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Warren"}}})