GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":6348,"name":"mccain"},
{"votes":2167,"name":"huckabee"},
{"votes":653,"name":"paul"},
{"votes":447,"name":"romney"},
{"votes":202,"name":"uncommitted-r"},
{"votes":38,"name":"keyes"},
{"votes":6,"name":"cort"}],
"name":"Rhode Island","precincts":
{"total":179,"reporting":68},
"delegates":20,"date":"03-04"},
"state":"RI","party":"gop","total":9861,"locals":
{"Middletown":
{"votes":[
{"votes":413,"name":"mccain"},
{"votes":106,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":23,"name":"romney"},
{"votes":13,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":590,"precincts":
{"total":4,"reporting":4},
"name":"Middletown"},
"Cumberland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Cumberland"},
"Hopkinton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hopkinton"},
"Central Falls":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Central Falls"},
"Barrington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Barrington"},
"Richmond":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Richmond"},
"Providence":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Providence"},
"Foster":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Foster"},
"Warwick":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Warwick"},
"Jamestown":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Jamestown"},
"Smithfield":
{"votes":[
{"votes":354,"name":"mccain"},
{"votes":148,"name":"huckabee"},
{"votes":38,"name":"romney"},
{"votes":32,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":1,"name":"cort"},
{"votes":1,"name":"keyes"}],
"total":580,"precincts":
{"total":4,"reporting":3},
"name":"Smithfield"},
"Mail Ballots - CD2":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD2"},
"Cranston":
{"votes":[
{"votes":112,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"uncommitted-r"},
{"votes":7,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":184,"precincts":
{"total":10,"reporting":1},
"name":"Cranston"},
"East Providence":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"East Providence"},
"Mail Ballots - CD1":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD1"},
"Glocester":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Glocester"},
"Little Compton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Little Compton"},
"West Greenwich":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"West Greenwich"},
"Charlestown":
{"votes":[
{"votes":60,"name":"mccain"},
{"votes":27,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":3,"name":"romney"},
{"votes":3,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":110,"precincts":
{"total":3,"reporting":1},
"name":"Charlestown"},
"North Smithfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Smithfield"},
"Lincoln":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Lincoln"},
"Coventry":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Coventry"},
"South Kingstown":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"South Kingstown"},
"West Warwick":
{"votes":[
{"votes":194,"name":"mccain"},
{"votes":87,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":17,"name":"romney"},
{"votes":14,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":336,"precincts":
{"total":5,"reporting":3},
"name":"West Warwick"},
"Burrillville":
{"votes":[
{"votes":230,"name":"mccain"},
{"votes":98,"name":"huckabee"},
{"votes":38,"name":"paul"},
{"votes":22,"name":"romney"},
{"votes":11,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":399,"precincts":
{"total":4,"reporting":4},
"name":"Burrillville"},
"Newport":
{"votes":[
{"votes":280,"name":"mccain"},
{"votes":53,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":6,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":372,"precincts":
{"total":4,"reporting":2},
"name":"Newport"},
"Bristol":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Bristol"},
"Johnston":
{"votes":[
{"votes":282,"name":"mccain"},
{"votes":134,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":16,"name":"romney"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":471,"precincts":
{"total":5,"reporting":5},
"name":"Johnston"},
"Scituate":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Scituate"},
"New Shoreham":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"New Shoreham"},
"Exeter":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Exeter"},
"North Providence":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Providence"},
"Westerly":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Westerly"},
"North Kingstown":
{"votes":[
{"votes":657,"name":"mccain"},
{"votes":188,"name":"huckabee"},
{"votes":77,"name":"paul"},
{"votes":45,"name":"romney"},
{"votes":15,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":986,"precincts":
{"total":4,"reporting":3},
"name":"North Kingstown"},
"Portsmouth":
{"votes":[
{"votes":4,"name":"huckabee"},
{"votes":4,"name":"mccain"},
{"votes":2,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":10,"precincts":
{"total":5,"reporting":1},
"name":"Portsmouth"},
"Narragansett":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Narragansett"},
"Tiverton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Tiverton"},
"Woonsocket":
{"votes":[
{"votes":348,"name":"mccain"},
{"votes":159,"name":"huckabee"},
{"votes":55,"name":"paul"},
{"votes":26,"name":"romney"},
{"votes":20,"name":"uncommitted-r"},
{"votes":4,"name":"cort"},
{"votes":3,"name":"keyes"}],
"total":615,"precincts":
{"total":8,"reporting":7},
"name":"Woonsocket"},
"East Greenwich":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"East Greenwich"},
"Pawtucket":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Pawtucket"},
"Warren":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Warren"}}})