GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":17507,"name":"clinton"},
{"votes":13531,"name":"obama"}],
"name":"South Dakota","precincts":
{"total":762,"reporting":220},
"delegates":15,"date":"06-03"},
"state":"SD","party":"dem","total":31038,"locals":
{"Bon Homme":
{"votes":[
{"votes":285,"name":"clinton"},
{"votes":143,"name":"obama"}],
"total":428,"precincts":
{"total":5,"reporting":2},
"name":"Bon Homme"},
"Hughes":
{"votes":[
{"votes":608,"name":"clinton"},
{"votes":601,"name":"obama"}],
"total":1209,"precincts":
{"total":15,"reporting":11},
"name":"Hughes"},
"Deuel":
{"votes":[
{"votes":285,"name":"clinton"},
{"votes":153,"name":"obama"}],
"total":438,"precincts":
{"total":11,"reporting":8},
"name":"Deuel"},
"Lyman":
{"votes":[
{"votes":184,"name":"clinton"},
{"votes":145,"name":"obama"}],
"total":329,"precincts":
{"total":7,"reporting":6},
"name":"Lyman"},
"Grant":
{"votes":[
{"votes":343,"name":"clinton"},
{"votes":128,"name":"obama"}],
"total":471,"precincts":
{"total":11,"reporting":3},
"name":"Grant"},
"Union":
{"votes":[
{"votes":348,"name":"clinton"},
{"votes":282,"name":"obama"}],
"total":630,"precincts":
{"total":13,"reporting":5},
"name":"Union"},
"Clay":
{"votes":[
{"votes":886,"name":"obama"},
{"votes":747,"name":"clinton"}],
"total":1633,"precincts":
{"total":7,"reporting":6},
"name":"Clay"},
"Miner":
{"votes":[
{"votes":293,"name":"clinton"},
{"votes":188,"name":"obama"}],
"total":481,"precincts":
{"total":8,"reporting":8},
"name":"Miner"},
"Edmunds":
{"votes":[
{"votes":222,"name":"clinton"},
{"votes":136,"name":"obama"}],
"total":358,"precincts":
{"total":7,"reporting":4},
"name":"Edmunds"},
"Douglas":
{"votes":[
{"votes":101,"name":"clinton"},
{"votes":63,"name":"obama"}],
"total":164,"precincts":
{"total":5,"reporting":3},
"name":"Douglas"},
"Hamlin":
{"votes":[
{"votes":32,"name":"clinton"},
{"votes":20,"name":"obama"}],
"total":52,"precincts":
{"total":7,"reporting":2},
"name":"Hamlin"},
"Jerauld":
{"votes":[
{"votes":212,"name":"clinton"},
{"votes":148,"name":"obama"}],
"total":360,"precincts":
{"total":5,"reporting":3},
"name":"Jerauld"},
"McCook":
{"votes":[
{"votes":356,"name":"clinton"},
{"votes":209,"name":"obama"}],
"total":565,"precincts":
{"total":6,"reporting":5},
"name":"McCook"},
"Brookings":
{"votes":[
{"votes":282,"name":"obama"},
{"votes":233,"name":"clinton"}],
"total":515,"precincts":
{"total":15,"reporting":3},
"name":"Brookings"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Jackson"},
"McPherson":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"McPherson"},
"Sully":
{"votes":[
{"votes":16,"name":"obama"},
{"votes":15,"name":"clinton"}],
"total":31,"precincts":
{"total":4,"reporting":1},
"name":"Sully"},
"Brown":
{"votes":[
{"votes":163,"name":"clinton"},
{"votes":134,"name":"obama"}],
"total":297,"precincts":
{"total":22,"reporting":1},
"name":"Brown"},
"Minnehaha":
{"votes":[
{"votes":2860,"name":"clinton"},
{"votes":2569,"name":"obama"}],
"total":5429,"precincts":
{"total":66,"reporting":0},
"name":"Minnehaha"},
"Pennington":
{"votes":[],
"total":0,"precincts":
{"total":49,"reporting":0},
"name":"Pennington"},
"Custer":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Custer"},
"Lawrence":
{"votes":[
{"votes":419,"name":"obama"},
{"votes":317,"name":"clinton"}],
"total":736,"precincts":
{"total":12,"reporting":2},
"name":"Lawrence"},
"Yankton":
{"votes":[
{"votes":1045,"name":"clinton"},
{"votes":811,"name":"obama"}],
"total":1856,"precincts":
{"total":13,"reporting":5},
"name":"Yankton"},
"Aurora":
{"votes":[
{"votes":171,"name":"clinton"},
{"votes":115,"name":"obama"}],
"total":286,"precincts":
{"total":7,"reporting":4},
"name":"Aurora"},
"Hand":
{"votes":[
{"votes":172,"name":"clinton"},
{"votes":151,"name":"obama"}],
"total":323,"precincts":
{"total":10,"reporting":6},
"name":"Hand"},
"Walworth":
{"votes":[
{"votes":100,"name":"clinton"},
{"votes":75,"name":"obama"}],
"total":175,"precincts":
{"total":15,"reporting":6},
"name":"Walworth"},
"Codington":
{"votes":[
{"votes":788,"name":"clinton"},
{"votes":612,"name":"obama"}],
"total":1400,"precincts":
{"total":33,"reporting":14},
"name":"Codington"},
"Haakon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Haakon"},
"Butte":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Butte"},
"Day":
{"votes":[
{"votes":182,"name":"clinton"},
{"votes":98,"name":"obama"}],
"total":280,"precincts":
{"total":14,"reporting":3},
"name":"Day"},
"Dewey":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Dewey"},
"Jones":
{"votes":[
{"votes":57,"name":"clinton"},
{"votes":34,"name":"obama"}],
"total":91,"precincts":
{"total":3,"reporting":3},
"name":"Jones"},
"Davison":
{"votes":[
{"votes":1373,"name":"clinton"},
{"votes":936,"name":"obama"}],
"total":2309,"precincts":
{"total":8,"reporting":8},
"name":"Davison"},
"Lincoln":
{"votes":[
{"votes":422,"name":"clinton"},
{"votes":202,"name":"obama"}],
"total":624,"precincts":
{"total":29,"reporting":8},
"name":"Lincoln"},
"Spink":
{"votes":[
{"votes":419,"name":"clinton"},
{"votes":282,"name":"obama"}],
"total":701,"precincts":
{"total":9,"reporting":5},
"name":"Spink"},
"Corson":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Corson"},
"Hutchinson":
{"votes":[
{"votes":192,"name":"clinton"},
{"votes":139,"name":"obama"}],
"total":331,"precincts":
{"total":7,"reporting":5},
"name":"Hutchinson"},
"Lake":
{"votes":[
{"votes":610,"name":"clinton"},
{"votes":370,"name":"obama"}],
"total":980,"precincts":
{"total":10,"reporting":7},
"name":"Lake"},
"Roberts":
{"votes":[
{"votes":408,"name":"obama"},
{"votes":370,"name":"clinton"}],
"total":778,"precincts":
{"total":14,"reporting":4},
"name":"Roberts"},
"Meade":
{"votes":[
{"votes":83,"name":"clinton"},
{"votes":80,"name":"obama"}],
"total":163,"precincts":
{"total":37,"reporting":3},
"name":"Meade"},
"Mellette":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Mellette"},
"Faulk":
{"votes":[
{"votes":112,"name":"clinton"},
{"votes":68,"name":"obama"}],
"total":180,"precincts":
{"total":7,"reporting":3},
"name":"Faulk"},
"Hanson":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Hanson"},
"Gregory":
{"votes":[
{"votes":177,"name":"clinton"},
{"votes":154,"name":"obama"}],
"total":331,"precincts":
{"total":3,"reporting":2},
"name":"Gregory"},
"Buffalo":
{"votes":[
{"votes":49,"name":"clinton"},
{"votes":31,"name":"obama"}],
"total":80,"precincts":
{"total":3,"reporting":2},
"name":"Buffalo"},
"Ziebach":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Ziebach"},
"Tripp":
{"votes":[
{"votes":338,"name":"clinton"},
{"votes":237,"name":"obama"}],
"total":575,"precincts":
{"total":13,"reporting":8},
"name":"Tripp"},
"Brule":
{"votes":[
{"votes":128,"name":"clinton"},
{"votes":71,"name":"obama"}],
"total":199,"precincts":
{"total":5,"reporting":3},
"name":"Brule"},
"Sanborn":
{"votes":[
{"votes":177,"name":"clinton"},
{"votes":106,"name":"obama"}],
"total":283,"precincts":
{"total":4,"reporting":3},
"name":"Sanborn"},
"Harding":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Harding"},
"Clark":
{"votes":[
{"votes":137,"name":"clinton"},
{"votes":78,"name":"obama"}],
"total":215,"precincts":
{"total":13,"reporting":5},
"name":"Clark"},
"Fall River":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fall River"},
"Marshall":
{"votes":[
{"votes":226,"name":"obama"},
{"votes":184,"name":"clinton"}],
"total":410,"precincts":
{"total":9,"reporting":4},
"name":"Marshall"},
"Beadle":
{"votes":[
{"votes":1256,"name":"clinton"},
{"votes":683,"name":"obama"}],
"total":1939,"precincts":
{"total":14,"reporting":11},
"name":"Beadle"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Potter"},
"Charles Mix":
{"votes":[
{"votes":551,"name":"clinton"},
{"votes":503,"name":"obama"}],
"total":1054,"precincts":
{"total":13,"reporting":11},
"name":"Charles Mix"},
"Perkins":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Perkins"},
"Hyde":
{"votes":[
{"votes":31,"name":"clinton"},
{"votes":14,"name":"obama"}],
"total":45,"precincts":
{"total":5,"reporting":1},
"name":"Hyde"},
"Kingsbury":
{"votes":[
{"votes":149,"name":"clinton"},
{"votes":116,"name":"obama"}],
"total":265,"precincts":
{"total":6,"reporting":2},
"name":"Kingsbury"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Todd"},
"Campbell":
{"votes":[
{"votes":18,"name":"clinton"},
{"votes":18,"name":"obama"}],
"total":36,"precincts":
{"total":5,"reporting":3},
"name":"Campbell"},
"Stanley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Stanley"},
"Turner":
{"votes":[
{"votes":354,"name":"clinton"},
{"votes":219,"name":"obama"}],
"total":573,"precincts":
{"total":8,"reporting":5},
"name":"Turner"},
"Moody":
{"votes":[
{"votes":233,"name":"clinton"},
{"votes":151,"name":"obama"}],
"total":384,"precincts":
{"total":6,"reporting":2},
"name":"Moody"},
"Shannon":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Shannon"},
"Bennett":
{"votes":[
{"votes":25,"name":"clinton"},
{"votes":21,"name":"obama"}],
"total":46,"precincts":
{"total":8,"reporting":1},
"name":"Bennett"}}})