GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":28251,"name":"mccain"},
{"votes":5850,"name":"paul"},
{"votes":2907,"name":"huckabee"},
{"votes":1238,"name":"romney"},
{"votes":1163,"name":"uncommitted-r"}],
"name":"South Dakota","precincts":
{"total":762,"reporting":479},
"delegates":27,"date":"06-03"},
"state":"SD","party":"gop","total":39409,"locals":
{"Bon Homme":
{"votes":[
{"votes":243,"name":"mccain"},
{"votes":68,"name":"paul"},
{"votes":42,"name":"huckabee"},
{"votes":10,"name":"romney"},
{"votes":8,"name":"uncommitted-r"}],
"total":371,"precincts":
{"total":5,"reporting":3},
"name":"Bon Homme"},
"Hughes":
{"votes":[
{"votes":2613,"name":"mccain"},
{"votes":314,"name":"paul"},
{"votes":221,"name":"huckabee"},
{"votes":103,"name":"uncommitted-r"},
{"votes":77,"name":"romney"}],
"total":3328,"precincts":
{"total":15,"reporting":15},
"name":"Hughes"},
"Deuel":
{"votes":[
{"votes":187,"name":"mccain"},
{"votes":66,"name":"paul"},
{"votes":28,"name":"huckabee"},
{"votes":12,"name":"uncommitted-r"},
{"votes":9,"name":"romney"}],
"total":302,"precincts":
{"total":11,"reporting":11},
"name":"Deuel"},
"Lyman":
{"votes":[
{"votes":202,"name":"mccain"},
{"votes":54,"name":"paul"},
{"votes":17,"name":"huckabee"},
{"votes":14,"name":"uncommitted-r"},
{"votes":4,"name":"romney"}],
"total":291,"precincts":
{"total":7,"reporting":7},
"name":"Lyman"},
"Grant":
{"votes":[
{"votes":327,"name":"mccain"},
{"votes":81,"name":"paul"},
{"votes":40,"name":"huckabee"},
{"votes":19,"name":"uncommitted-r"},
{"votes":13,"name":"romney"}],
"total":480,"precincts":
{"total":11,"reporting":11},
"name":"Grant"},
"Union":
{"votes":[
{"votes":1085,"name":"mccain"},
{"votes":151,"name":"paul"},
{"votes":112,"name":"huckabee"},
{"votes":75,"name":"romney"},
{"votes":48,"name":"uncommitted-r"}],
"total":1471,"precincts":
{"total":13,"reporting":10},
"name":"Union"},
"Clay":
{"votes":[
{"votes":528,"name":"mccain"},
{"votes":88,"name":"paul"},
{"votes":40,"name":"romney"},
{"votes":39,"name":"huckabee"},
{"votes":23,"name":"uncommitted-r"}],
"total":718,"precincts":
{"total":7,"reporting":7},
"name":"Clay"},
"Miner":
{"votes":[
{"votes":72,"name":"mccain"},
{"votes":23,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":1,"name":"uncommitted-r"}],
"total":126,"precincts":
{"total":8,"reporting":8},
"name":"Miner"},
"Edmunds":
{"votes":[
{"votes":290,"name":"mccain"},
{"votes":55,"name":"paul"},
{"votes":40,"name":"huckabee"},
{"votes":29,"name":"uncommitted-r"},
{"votes":12,"name":"romney"}],
"total":426,"precincts":
{"total":7,"reporting":7},
"name":"Edmunds"},
"Douglas":
{"votes":[
{"votes":264,"name":"mccain"},
{"votes":48,"name":"paul"},
{"votes":34,"name":"huckabee"},
{"votes":12,"name":"romney"},
{"votes":12,"name":"uncommitted-r"}],
"total":370,"precincts":
{"total":5,"reporting":5},
"name":"Douglas"},
"Hamlin":
{"votes":[
{"votes":266,"name":"mccain"},
{"votes":119,"name":"paul"},
{"votes":24,"name":"huckabee"},
{"votes":19,"name":"uncommitted-r"},
{"votes":12,"name":"romney"}],
"total":440,"precincts":
{"total":7,"reporting":7},
"name":"Hamlin"},
"Jerauld":
{"votes":[
{"votes":179,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":9,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":225,"precincts":
{"total":5,"reporting":5},
"name":"Jerauld"},
"McCook":
{"votes":[
{"votes":266,"name":"mccain"},
{"votes":57,"name":"paul"},
{"votes":43,"name":"huckabee"},
{"votes":14,"name":"romney"},
{"votes":10,"name":"uncommitted-r"}],
"total":390,"precincts":
{"total":6,"reporting":6},
"name":"McCook"},
"Brookings":
{"votes":[
{"votes":863,"name":"mccain"},
{"votes":161,"name":"paul"},
{"votes":99,"name":"huckabee"},
{"votes":34,"name":"uncommitted-r"},
{"votes":32,"name":"romney"}],
"total":1189,"precincts":
{"total":15,"reporting":9},
"name":"Brookings"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Jackson"},
"McPherson":
{"votes":[
{"votes":137,"name":"mccain"},
{"votes":18,"name":"paul"},
{"votes":15,"name":"huckabee"},
{"votes":7,"name":"romney"},
{"votes":5,"name":"uncommitted-r"}],
"total":182,"precincts":
{"total":6,"reporting":3},
"name":"McPherson"},
"Sully":
{"votes":[
{"votes":220,"name":"mccain"},
{"votes":43,"name":"paul"},
{"votes":22,"name":"huckabee"},
{"votes":14,"name":"romney"},
{"votes":13,"name":"uncommitted-r"}],
"total":312,"precincts":
{"total":4,"reporting":4},
"name":"Sully"},
"Brown":
{"votes":[
{"votes":290,"name":"mccain"},
{"votes":62,"name":"paul"},
{"votes":24,"name":"huckabee"},
{"votes":18,"name":"romney"},
{"votes":9,"name":"uncommitted-r"}],
"total":403,"precincts":
{"total":22,"reporting":3},
"name":"Brown"},
"Minnehaha":
{"votes":[
{"votes":3512,"name":"mccain"},
{"votes":872,"name":"paul"},
{"votes":399,"name":"huckabee"},
{"votes":219,"name":"romney"},
{"votes":132,"name":"uncommitted-r"}],
"total":5134,"precincts":
{"total":66,"reporting":48},
"name":"Minnehaha"},
"Pennington":
{"votes":[
{"votes":3305,"name":"mccain"},
{"votes":493,"name":"paul"},
{"votes":178,"name":"huckabee"},
{"votes":136,"name":"romney"},
{"votes":133,"name":"uncommitted-r"}],
"total":4245,"precincts":
{"total":49,"reporting":20},
"name":"Pennington"},
"Custer":
{"votes":[
{"votes":321,"name":"mccain"},
{"votes":70,"name":"paul"},
{"votes":17,"name":"romney"},
{"votes":16,"name":"huckabee"},
{"votes":10,"name":"uncommitted-r"}],
"total":434,"precincts":
{"total":10,"reporting":4},
"name":"Custer"},
"Lawrence":
{"votes":[
{"votes":765,"name":"mccain"},
{"votes":207,"name":"paul"},
{"votes":44,"name":"uncommitted-r"},
{"votes":41,"name":"huckabee"},
{"votes":17,"name":"romney"}],
"total":1074,"precincts":
{"total":12,"reporting":4},
"name":"Lawrence"},
"Yankton":
{"votes":[
{"votes":969,"name":"mccain"},
{"votes":303,"name":"paul"},
{"votes":89,"name":"huckabee"},
{"votes":55,"name":"romney"},
{"votes":49,"name":"uncommitted-r"}],
"total":1465,"precincts":
{"total":13,"reporting":13},
"name":"Yankton"},
"Aurora":
{"votes":[
{"votes":158,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":10,"name":"romney"},
{"votes":5,"name":"uncommitted-r"}],
"total":221,"precincts":
{"total":7,"reporting":7},
"name":"Aurora"},
"Hand":
{"votes":[
{"votes":283,"name":"mccain"},
{"votes":50,"name":"paul"},
{"votes":30,"name":"huckabee"},
{"votes":16,"name":"romney"},
{"votes":7,"name":"uncommitted-r"}],
"total":386,"precincts":
{"total":10,"reporting":8},
"name":"Hand"},
"Walworth":
{"votes":[
{"votes":426,"name":"mccain"},
{"votes":112,"name":"paul"},
{"votes":36,"name":"huckabee"},
{"votes":20,"name":"uncommitted-r"},
{"votes":16,"name":"romney"}],
"total":610,"precincts":
{"total":15,"reporting":10},
"name":"Walworth"},
"Codington":
{"votes":[
{"votes":516,"name":"mccain"},
{"votes":168,"name":"paul"},
{"votes":47,"name":"huckabee"},
{"votes":30,"name":"romney"},
{"votes":13,"name":"uncommitted-r"}],
"total":774,"precincts":
{"total":33,"reporting":23},
"name":"Codington"},
"Haakon":
{"votes":[
{"votes":66,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":6,"name":"huckabee"},
{"votes":2,"name":"romney"}],
"total":98,"precincts":
{"total":6,"reporting":1},
"name":"Haakon"},
"Butte":
{"votes":[
{"votes":235,"name":"mccain"},
{"votes":75,"name":"paul"},
{"votes":17,"name":"huckabee"},
{"votes":9,"name":"uncommitted-r"},
{"votes":7,"name":"romney"}],
"total":343,"precincts":
{"total":16,"reporting":5},
"name":"Butte"},
"Day":
{"votes":[
{"votes":78,"name":"mccain"},
{"votes":9,"name":"paul"},
{"votes":5,"name":"huckabee"},
{"votes":1,"name":"uncommitted-r"}],
"total":93,"precincts":
{"total":14,"reporting":4},
"name":"Day"},
"Dewey":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Dewey"},
"Jones":
{"votes":[
{"votes":110,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":11,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":3,"name":"uncommitted-r"}],
"total":148,"precincts":
{"total":3,"reporting":3},
"name":"Jones"},
"Davison":
{"votes":[
{"votes":816,"name":"mccain"},
{"votes":136,"name":"paul"},
{"votes":90,"name":"huckabee"},
{"votes":37,"name":"romney"},
{"votes":33,"name":"uncommitted-r"}],
"total":1112,"precincts":
{"total":8,"reporting":8},
"name":"Davison"},
"Lincoln":
{"votes":[
{"votes":1689,"name":"mccain"},
{"votes":342,"name":"paul"},
{"votes":158,"name":"huckabee"},
{"votes":81,"name":"romney"},
{"votes":60,"name":"uncommitted-r"}],
"total":2330,"precincts":
{"total":29,"reporting":29},
"name":"Lincoln"},
"Spink":
{"votes":[
{"votes":333,"name":"mccain"},
{"votes":50,"name":"paul"},
{"votes":38,"name":"huckabee"},
{"votes":23,"name":"uncommitted-r"},
{"votes":14,"name":"romney"}],
"total":458,"precincts":
{"total":9,"reporting":9},
"name":"Spink"},
"Corson":
{"votes":[
{"votes":38,"name":"mccain"},
{"votes":14,"name":"paul"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"uncommitted-r"}],
"total":54,"precincts":
{"total":17,"reporting":4},
"name":"Corson"},
"Hutchinson":
{"votes":[
{"votes":396,"name":"mccain"},
{"votes":93,"name":"paul"},
{"votes":87,"name":"huckabee"},
{"votes":25,"name":"uncommitted-r"},
{"votes":14,"name":"romney"}],
"total":615,"precincts":
{"total":7,"reporting":7},
"name":"Hutchinson"},
"Lake":
{"votes":[
{"votes":707,"name":"mccain"},
{"votes":153,"name":"paul"},
{"votes":98,"name":"huckabee"},
{"votes":41,"name":"romney"},
{"votes":24,"name":"uncommitted-r"}],
"total":1023,"precincts":
{"total":10,"reporting":10},
"name":"Lake"},
"Roberts":
{"votes":[
{"votes":191,"name":"mccain"},
{"votes":33,"name":"paul"},
{"votes":16,"name":"huckabee"},
{"votes":7,"name":"romney"},
{"votes":5,"name":"uncommitted-r"}],
"total":252,"precincts":
{"total":14,"reporting":7},
"name":"Roberts"},
"Meade":
{"votes":[
{"votes":524,"name":"mccain"},
{"votes":149,"name":"paul"},
{"votes":35,"name":"huckabee"},
{"votes":15,"name":"uncommitted-r"},
{"votes":9,"name":"romney"}],
"total":732,"precincts":
{"total":37,"reporting":7},
"name":"Meade"},
"Mellette":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Mellette"},
"Faulk":
{"votes":[
{"votes":166,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":31,"name":"paul"},
{"votes":12,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":254,"precincts":
{"total":7,"reporting":7},
"name":"Faulk"},
"Hanson":
{"votes":[
{"votes":208,"name":"mccain"},
{"votes":46,"name":"paul"},
{"votes":21,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"uncommitted-r"}],
"total":290,"precincts":
{"total":5,"reporting":5},
"name":"Hanson"},
"Gregory":
{"votes":[
{"votes":251,"name":"mccain"},
{"votes":39,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":10,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":332,"precincts":
{"total":3,"reporting":3},
"name":"Gregory"},
"Buffalo":
{"votes":[
{"votes":17,"name":"mccain"},
{"votes":15,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"uncommitted-r"}],
"total":36,"precincts":
{"total":3,"reporting":3},
"name":"Buffalo"},
"Ziebach":
{"votes":[
{"votes":24,"name":"mccain"},
{"votes":17,"name":"paul"},
{"votes":7,"name":"huckabee"},
{"votes":2,"name":"uncommitted-r"}],
"total":50,"precincts":
{"total":8,"reporting":3},
"name":"Ziebach"},
"Tripp":
{"votes":[
{"votes":699,"name":"mccain"},
{"votes":132,"name":"paul"},
{"votes":70,"name":"huckabee"},
{"votes":21,"name":"uncommitted-r"},
{"votes":14,"name":"romney"}],
"total":936,"precincts":
{"total":13,"reporting":13},
"name":"Tripp"},
"Brule":
{"votes":[
{"votes":41,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":6,"name":"paul"}],
"total":53,"precincts":
{"total":5,"reporting":3},
"name":"Brule"},
"Sanborn":
{"votes":[
{"votes":101,"name":"mccain"},
{"votes":13,"name":"paul"},
{"votes":12,"name":"huckabee"},
{"votes":11,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":143,"precincts":
{"total":4,"reporting":4},
"name":"Sanborn"},
"Harding":
{"votes":[
{"votes":114,"name":"mccain"},
{"votes":60,"name":"paul"},
{"votes":7,"name":"huckabee"},
{"votes":6,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":190,"precincts":
{"total":4,"reporting":4},
"name":"Harding"},
"Clark":
{"votes":[
{"votes":196,"name":"mccain"},
{"votes":53,"name":"paul"},
{"votes":26,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":5,"name":"uncommitted-r"}],
"total":286,"precincts":
{"total":13,"reporting":9},
"name":"Clark"},
"Fall River":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fall River"},
"Marshall":
{"votes":[
{"votes":119,"name":"mccain"},
{"votes":16,"name":"paul"},
{"votes":12,"name":"huckabee"},
{"votes":4,"name":"romney"},
{"votes":4,"name":"uncommitted-r"}],
"total":155,"precincts":
{"total":9,"reporting":5},
"name":"Marshall"},
"Beadle":
{"votes":[
{"votes":633,"name":"mccain"},
{"votes":105,"name":"huckabee"},
{"votes":85,"name":"paul"},
{"votes":29,"name":"romney"},
{"votes":25,"name":"uncommitted-r"}],
"total":877,"precincts":
{"total":14,"reporting":14},
"name":"Beadle"},
"Potter":
{"votes":[
{"votes":478,"name":"mccain"},
{"votes":75,"name":"paul"},
{"votes":44,"name":"huckabee"},
{"votes":16,"name":"romney"},
{"votes":14,"name":"uncommitted-r"}],
"total":627,"precincts":
{"total":6,"reporting":6},
"name":"Potter"},
"Charles Mix":
{"votes":[
{"votes":363,"name":"mccain"},
{"votes":53,"name":"huckabee"},
{"votes":48,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":7,"name":"uncommitted-r"}],
"total":480,"precincts":
{"total":13,"reporting":13},
"name":"Charles Mix"},
"Perkins":
{"votes":[
{"votes":97,"name":"mccain"},
{"votes":72,"name":"paul"},
{"votes":15,"name":"huckabee"},
{"votes":6,"name":"uncommitted-r"},
{"votes":2,"name":"romney"}],
"total":192,"precincts":
{"total":10,"reporting":2},
"name":"Perkins"},
"Hyde":
{"votes":[
{"votes":162,"name":"mccain"},
{"votes":38,"name":"paul"},
{"votes":22,"name":"huckabee"},
{"votes":10,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":237,"precincts":
{"total":5,"reporting":5},
"name":"Hyde"},
"Kingsbury":
{"votes":[
{"votes":238,"name":"mccain"},
{"votes":83,"name":"paul"},
{"votes":26,"name":"huckabee"},
{"votes":9,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":362,"precincts":
{"total":6,"reporting":5},
"name":"Kingsbury"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Todd"},
"Campbell":
{"votes":[
{"votes":209,"name":"mccain"},
{"votes":49,"name":"paul"},
{"votes":24,"name":"huckabee"},
{"votes":14,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":301,"precincts":
{"total":5,"reporting":5},
"name":"Campbell"},
"Stanley":
{"votes":[
{"votes":95,"name":"mccain"},
{"votes":25,"name":"paul"},
{"votes":5,"name":"huckabee"},
{"votes":3,"name":"romney"}],
"total":128,"precincts":
{"total":8,"reporting":3},
"name":"Stanley"},
"Turner":
{"votes":[
{"votes":317,"name":"mccain"},
{"votes":91,"name":"paul"},
{"votes":70,"name":"huckabee"},
{"votes":11,"name":"uncommitted-r"},
{"votes":10,"name":"romney"}],
"total":499,"precincts":
{"total":8,"reporting":7},
"name":"Turner"},
"Moody":
{"votes":[
{"votes":204,"name":"mccain"},
{"votes":43,"name":"paul"},
{"votes":37,"name":"huckabee"},
{"votes":7,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":296,"precincts":
{"total":6,"reporting":6},
"name":"Moody"},
"Shannon":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Shannon"},
"Bennett":
{"votes":[
{"votes":49,"name":"mccain"},
{"votes":5,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"uncommitted-r"}],
"total":60,"precincts":
{"total":8,"reporting":2},
"name":"Bennett"}}})