GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":16913,"name":"mccain"},
{"votes":3305,"name":"paul"},
{"votes":1751,"name":"huckabee"},
{"votes":780,"name":"romney"},
{"votes":741,"name":"uncommitted-r"}],
"name":"South Dakota","precincts":
{"total":762,"reporting":301},
"delegates":27,"date":"06-03"},
"state":"SD","party":"gop","total":23490,"locals":
{"Bon Homme":
{"votes":[
{"votes":243,"name":"mccain"},
{"votes":68,"name":"paul"},
{"votes":42,"name":"huckabee"},
{"votes":10,"name":"romney"},
{"votes":8,"name":"uncommitted-r"}],
"total":371,"precincts":
{"total":5,"reporting":3},
"name":"Bon Homme"},
"Hughes":
{"votes":[
{"votes":2613,"name":"mccain"},
{"votes":314,"name":"paul"},
{"votes":221,"name":"huckabee"},
{"votes":103,"name":"uncommitted-r"},
{"votes":77,"name":"romney"}],
"total":3328,"precincts":
{"total":15,"reporting":15},
"name":"Hughes"},
"Deuel":
{"votes":[
{"votes":187,"name":"mccain"},
{"votes":66,"name":"paul"},
{"votes":28,"name":"huckabee"},
{"votes":12,"name":"uncommitted-r"},
{"votes":9,"name":"romney"}],
"total":302,"precincts":
{"total":11,"reporting":11},
"name":"Deuel"},
"Lyman":
{"votes":[
{"votes":201,"name":"mccain"},
{"votes":49,"name":"paul"},
{"votes":16,"name":"huckabee"},
{"votes":13,"name":"uncommitted-r"},
{"votes":4,"name":"romney"}],
"total":283,"precincts":
{"total":7,"reporting":6},
"name":"Lyman"},
"Grant":
{"votes":[
{"votes":162,"name":"mccain"},
{"votes":40,"name":"paul"},
{"votes":13,"name":"huckabee"},
{"votes":12,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":232,"precincts":
{"total":11,"reporting":3},
"name":"Grant"},
"Union":
{"votes":[
{"votes":638,"name":"mccain"},
{"votes":80,"name":"paul"},
{"votes":62,"name":"huckabee"},
{"votes":61,"name":"romney"},
{"votes":35,"name":"uncommitted-r"}],
"total":876,"precincts":
{"total":13,"reporting":7},
"name":"Union"},
"Clay":
{"votes":[
{"votes":528,"name":"mccain"},
{"votes":88,"name":"paul"},
{"votes":40,"name":"romney"},
{"votes":39,"name":"huckabee"},
{"votes":23,"name":"uncommitted-r"}],
"total":718,"precincts":
{"total":7,"reporting":7},
"name":"Clay"},
"Miner":
{"votes":[
{"votes":72,"name":"mccain"},
{"votes":23,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":1,"name":"uncommitted-r"}],
"total":126,"precincts":
{"total":8,"reporting":8},
"name":"Miner"},
"Edmunds":
{"votes":[
{"votes":162,"name":"mccain"},
{"votes":25,"name":"paul"},
{"votes":23,"name":"uncommitted-r"},
{"votes":20,"name":"huckabee"},
{"votes":3,"name":"romney"}],
"total":233,"precincts":
{"total":7,"reporting":4},
"name":"Edmunds"},
"Douglas":
{"votes":[
{"votes":264,"name":"mccain"},
{"votes":48,"name":"paul"},
{"votes":34,"name":"huckabee"},
{"votes":12,"name":"romney"},
{"votes":12,"name":"uncommitted-r"}],
"total":370,"precincts":
{"total":5,"reporting":5},
"name":"Douglas"},
"Hamlin":
{"votes":[
{"votes":206,"name":"mccain"},
{"votes":90,"name":"paul"},
{"votes":15,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"uncommitted-r"}],
"total":326,"precincts":
{"total":7,"reporting":5},
"name":"Hamlin"},
"Jerauld":
{"votes":[
{"votes":179,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":9,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":225,"precincts":
{"total":5,"reporting":5},
"name":"Jerauld"},
"McCook":
{"votes":[
{"votes":266,"name":"mccain"},
{"votes":57,"name":"paul"},
{"votes":43,"name":"huckabee"},
{"votes":14,"name":"romney"},
{"votes":10,"name":"uncommitted-r"}],
"total":390,"precincts":
{"total":6,"reporting":6},
"name":"McCook"},
"Brookings":
{"votes":[
{"votes":95,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":14,"name":"huckabee"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":141,"precincts":
{"total":15,"reporting":2},
"name":"Brookings"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Jackson"},
"McPherson":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"McPherson"},
"Sully":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Sully"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Brown"},
"Minnehaha":
{"votes":[
{"votes":1919,"name":"mccain"},
{"votes":427,"name":"paul"},
{"votes":189,"name":"huckabee"},
{"votes":121,"name":"romney"},
{"votes":75,"name":"uncommitted-r"}],
"total":2731,"precincts":
{"total":66,"reporting":25},
"name":"Minnehaha"},
"Pennington":
{"votes":[
{"votes":1331,"name":"mccain"},
{"votes":161,"name":"paul"},
{"votes":61,"name":"huckabee"},
{"votes":55,"name":"romney"},
{"votes":53,"name":"uncommitted-r"}],
"total":1661,"precincts":
{"total":49,"reporting":15},
"name":"Pennington"},
"Custer":
{"votes":[
{"votes":113,"name":"mccain"},
{"votes":28,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"huckabee"}],
"total":157,"precincts":
{"total":10,"reporting":2},
"name":"Custer"},
"Lawrence":
{"votes":[
{"votes":479,"name":"mccain"},
{"votes":99,"name":"paul"},
{"votes":29,"name":"huckabee"},
{"votes":24,"name":"uncommitted-r"},
{"votes":10,"name":"romney"}],
"total":641,"precincts":
{"total":12,"reporting":2},
"name":"Lawrence"},
"Yankton":
{"votes":[
{"votes":874,"name":"mccain"},
{"votes":265,"name":"paul"},
{"votes":72,"name":"huckabee"},
{"votes":52,"name":"romney"},
{"votes":42,"name":"uncommitted-r"}],
"total":1305,"precincts":
{"total":13,"reporting":8},
"name":"Yankton"},
"Aurora":
{"votes":[
{"votes":158,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":10,"name":"romney"},
{"votes":5,"name":"uncommitted-r"}],
"total":221,"precincts":
{"total":7,"reporting":7},
"name":"Aurora"},
"Hand":
{"votes":[
{"votes":224,"name":"mccain"},
{"votes":33,"name":"paul"},
{"votes":25,"name":"huckabee"},
{"votes":13,"name":"romney"},
{"votes":3,"name":"uncommitted-r"}],
"total":298,"precincts":
{"total":10,"reporting":6},
"name":"Hand"},
"Walworth":
{"votes":[
{"votes":316,"name":"mccain"},
{"votes":80,"name":"paul"},
{"votes":30,"name":"huckabee"},
{"votes":17,"name":"uncommitted-r"},
{"votes":11,"name":"romney"}],
"total":454,"precincts":
{"total":15,"reporting":8},
"name":"Walworth"},
"Codington":
{"votes":[
{"votes":356,"name":"mccain"},
{"votes":103,"name":"paul"},
{"votes":49,"name":"romney"},
{"votes":37,"name":"huckabee"},
{"votes":6,"name":"uncommitted-r"}],
"total":551,"precincts":
{"total":33,"reporting":14},
"name":"Codington"},
"Haakon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Haakon"},
"Butte":
{"votes":[
{"votes":23,"name":"mccain"},
{"votes":6,"name":"paul"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"romney"}],
"total":34,"precincts":
{"total":16,"reporting":1},
"name":"Butte"},
"Day":
{"votes":[
{"votes":78,"name":"mccain"},
{"votes":9,"name":"paul"},
{"votes":5,"name":"huckabee"},
{"votes":1,"name":"uncommitted-r"}],
"total":93,"precincts":
{"total":14,"reporting":4},
"name":"Day"},
"Dewey":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Dewey"},
"Jones":
{"votes":[
{"votes":110,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":11,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":3,"name":"uncommitted-r"}],
"total":148,"precincts":
{"total":3,"reporting":3},
"name":"Jones"},
"Davison":
{"votes":[
{"votes":816,"name":"mccain"},
{"votes":136,"name":"paul"},
{"votes":90,"name":"huckabee"},
{"votes":37,"name":"romney"},
{"votes":33,"name":"uncommitted-r"}],
"total":1112,"precincts":
{"total":8,"reporting":8},
"name":"Davison"},
"Lincoln":
{"votes":[
{"votes":594,"name":"mccain"},
{"votes":136,"name":"paul"},
{"votes":51,"name":"huckabee"},
{"votes":31,"name":"uncommitted-r"},
{"votes":28,"name":"romney"}],
"total":840,"precincts":
{"total":29,"reporting":15},
"name":"Lincoln"},
"Spink":
{"votes":[
{"votes":200,"name":"mccain"},
{"votes":36,"name":"paul"},
{"votes":26,"name":"huckabee"},
{"votes":15,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":282,"precincts":
{"total":9,"reporting":6},
"name":"Spink"},
"Corson":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Corson"},
"Hutchinson":
{"votes":[
{"votes":396,"name":"mccain"},
{"votes":93,"name":"paul"},
{"votes":87,"name":"huckabee"},
{"votes":25,"name":"uncommitted-r"},
{"votes":14,"name":"romney"}],
"total":615,"precincts":
{"total":7,"reporting":7},
"name":"Hutchinson"},
"Lake":
{"votes":[
{"votes":351,"name":"mccain"},
{"votes":90,"name":"paul"},
{"votes":60,"name":"huckabee"},
{"votes":18,"name":"romney"},
{"votes":14,"name":"uncommitted-r"}],
"total":533,"precincts":
{"total":10,"reporting":7},
"name":"Lake"},
"Roberts":
{"votes":[
{"votes":108,"name":"mccain"},
{"votes":15,"name":"paul"},
{"votes":7,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"uncommitted-r"}],
"total":135,"precincts":
{"total":14,"reporting":4},
"name":"Roberts"},
"Meade":
{"votes":[
{"votes":125,"name":"mccain"},
{"votes":32,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":7,"name":"huckabee"},
{"votes":2,"name":"romney"}],
"total":175,"precincts":
{"total":37,"reporting":3},
"name":"Meade"},
"Mellette":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Mellette"},
"Faulk":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Faulk"},
"Hanson":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Hanson"},
"Gregory":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Gregory"},
"Buffalo":
{"votes":[
{"votes":13,"name":"mccain"},
{"votes":11,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"uncommitted-r"}],
"total":28,"precincts":
{"total":3,"reporting":2},
"name":"Buffalo"},
"Ziebach":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Ziebach"},
"Tripp":
{"votes":[
{"votes":396,"name":"mccain"},
{"votes":71,"name":"paul"},
{"votes":25,"name":"huckabee"},
{"votes":14,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":512,"precincts":
{"total":13,"reporting":5},
"name":"Tripp"},
"Brule":
{"votes":[
{"votes":41,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":6,"name":"paul"}],
"total":53,"precincts":
{"total":5,"reporting":3},
"name":"Brule"},
"Sanborn":
{"votes":[
{"votes":74,"name":"mccain"},
{"votes":8,"name":"paul"},
{"votes":7,"name":"uncommitted-r"},
{"votes":6,"name":"huckabee"},
{"votes":2,"name":"romney"}],
"total":97,"precincts":
{"total":4,"reporting":2},
"name":"Sanborn"},
"Harding":
{"votes":[
{"votes":67,"name":"mccain"},
{"votes":27,"name":"paul"},
{"votes":5,"name":"huckabee"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"romney"}],
"total":104,"precincts":
{"total":4,"reporting":1},
"name":"Harding"},
"Clark":
{"votes":[
{"votes":95,"name":"mccain"},
{"votes":29,"name":"paul"},
{"votes":13,"name":"huckabee"},
{"votes":3,"name":"uncommitted-r"},
{"votes":2,"name":"romney"}],
"total":142,"precincts":
{"total":13,"reporting":5},
"name":"Clark"},
"Fall River":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fall River"},
"Marshall":
{"votes":[
{"votes":106,"name":"mccain"},
{"votes":14,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":4,"name":"romney"},
{"votes":4,"name":"uncommitted-r"}],
"total":138,"precincts":
{"total":9,"reporting":4},
"name":"Marshall"},
"Beadle":
{"votes":[
{"votes":633,"name":"mccain"},
{"votes":105,"name":"huckabee"},
{"votes":85,"name":"paul"},
{"votes":29,"name":"romney"},
{"votes":25,"name":"uncommitted-r"}],
"total":877,"precincts":
{"total":14,"reporting":14},
"name":"Beadle"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Potter"},
"Charles Mix":
{"votes":[
{"votes":287,"name":"mccain"},
{"votes":38,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":4,"name":"uncommitted-r"}],
"total":369,"precincts":
{"total":13,"reporting":12},
"name":"Charles Mix"},
"Perkins":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Perkins"},
"Hyde":
{"votes":[
{"votes":69,"name":"mccain"},
{"votes":20,"name":"paul"},
{"votes":9,"name":"huckabee"},
{"votes":6,"name":"uncommitted-r"},
{"votes":4,"name":"romney"}],
"total":108,"precincts":
{"total":5,"reporting":3},
"name":"Hyde"},
"Kingsbury":
{"votes":[
{"votes":174,"name":"mccain"},
{"votes":65,"name":"paul"},
{"votes":21,"name":"huckabee"},
{"votes":8,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":273,"precincts":
{"total":6,"reporting":3},
"name":"Kingsbury"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Todd"},
"Campbell":
{"votes":[
{"votes":153,"name":"mccain"},
{"votes":40,"name":"paul"},
{"votes":17,"name":"huckabee"},
{"votes":11,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":226,"precincts":
{"total":5,"reporting":4},
"name":"Campbell"},
"Stanley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Stanley"},
"Turner":
{"votes":[
{"votes":317,"name":"mccain"},
{"votes":91,"name":"paul"},
{"votes":70,"name":"huckabee"},
{"votes":11,"name":"uncommitted-r"},
{"votes":10,"name":"romney"}],
"total":499,"precincts":
{"total":8,"reporting":7},
"name":"Turner"},
"Moody":
{"votes":[
{"votes":101,"name":"mccain"},
{"votes":26,"name":"paul"},
{"votes":23,"name":"huckabee"},
{"votes":5,"name":"uncommitted-r"},
{"votes":2,"name":"romney"}],
"total":157,"precincts":
{"total":6,"reporting":4},
"name":"Moody"},
"Shannon":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Shannon"},
"Bennett":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Bennett"}}})