GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":332599,"name":"clinton","delegates":40},
{"votes":250730,"name":"obama","delegates":28},
{"votes":27644,"name":"edwards"},
{"votes":3123,"name":"uncommitted-d"},
{"votes":1522,"name":"biden"},
{"votes":1163,"name":"richardson"},
{"votes":959,"name":"kucinich"},
{"votes":523,"name":"dodd"},
{"votes":460,"name":"gravel"}],
"name":"Tennessee","precincts":
{"total":2290,"reporting":2290},
"delegates":68,"date":"02-05"},
"state":"TN","party":"dem","total":618723,"locals":
{"Wilson":
{"votes":[
{"votes":6666,"name":"clinton"},
{"votes":3218,"name":"obama"},
{"votes":454,"name":"edwards"},
{"votes":46,"name":"uncommitted-d"},
{"votes":24,"name":"biden"},
{"votes":14,"name":"richardson"},
{"votes":12,"name":"dodd"},
{"votes":11,"name":"kucinich"},
{"votes":11,"name":"gravel"}],
"total":10456,"precincts":
{"total":44,"reporting":44},
"name":"Wilson"},
"Blount":
{"votes":[
{"votes":5713,"name":"clinton"},
{"votes":3086,"name":"obama"},
{"votes":397,"name":"edwards"},
{"votes":34,"name":"uncommitted-d"},
{"votes":20,"name":"biden"},
{"votes":18,"name":"kucinich"},
{"votes":17,"name":"richardson"},
{"votes":6,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":9295,"precincts":
{"total":52,"reporting":52},
"name":"Blount"},
"Shelby":
{"votes":[
{"votes":68516,"name":"obama"},
{"votes":27914,"name":"clinton"},
{"votes":886,"name":"edwards"},
{"votes":247,"name":"biden"},
{"votes":144,"name":"kucinich"},
{"votes":109,"name":"uncommitted-d"},
{"votes":97,"name":"richardson"},
{"votes":55,"name":"dodd"},
{"votes":46,"name":"gravel"}],
"total":98014,"precincts":
{"total":283,"reporting":283},
"name":"Shelby"},
"Union":
{"votes":[
{"votes":1322,"name":"clinton"},
{"votes":155,"name":"obama"},
{"votes":48,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"}],
"total":1536,"precincts":
{"total":9,"reporting":9},
"name":"Union"},
"Smith":
{"votes":[
{"votes":2385,"name":"clinton"},
{"votes":343,"name":"obama"},
{"votes":253,"name":"edwards"},
{"votes":28,"name":"uncommitted-d"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":3030,"precincts":
{"total":8,"reporting":8},
"name":"Smith"},
"Montgomery":
{"votes":[
{"votes":6694,"name":"clinton"},
{"votes":5593,"name":"obama"},
{"votes":562,"name":"edwards"},
{"votes":38,"name":"uncommitted-d"},
{"votes":26,"name":"biden"},
{"votes":13,"name":"richardson"},
{"votes":11,"name":"kucinich"},
{"votes":9,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":12950,"precincts":
{"total":24,"reporting":24},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":868,"name":"clinton"},
{"votes":114,"name":"obama"},
{"votes":65,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"}],
"total":1051,"precincts":
{"total":14,"reporting":14},
"name":"Wayne"},
"Robertson":
{"votes":[
{"votes":4478,"name":"clinton"},
{"votes":1523,"name":"obama"},
{"votes":321,"name":"edwards"},
{"votes":20,"name":"biden"},
{"votes":18,"name":"uncommitted-d"},
{"votes":11,"name":"dodd"},
{"votes":9,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"gravel"}],
"total":6386,"precincts":
{"total":19,"reporting":19},
"name":"Robertson"},
"White":
{"votes":[
{"votes":2577,"name":"clinton"},
{"votes":358,"name":"obama"},
{"votes":227,"name":"edwards"},
{"votes":19,"name":"uncommitted-d"},
{"votes":17,"name":"biden"},
{"votes":13,"name":"richardson"},
{"votes":8,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":3223,"precincts":
{"total":11,"reporting":11},
"name":"White"},
"Hamblen":
{"votes":[
{"votes":3302,"name":"clinton"},
{"votes":1094,"name":"obama"},
{"votes":343,"name":"edwards"},
{"votes":27,"name":"uncommitted-d"},
{"votes":13,"name":"richardson"},
{"votes":12,"name":"biden"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"kucinich"}],
"total":4806,"precincts":
{"total":17,"reporting":17},
"name":"Hamblen"},
"Henderson":
{"votes":[
{"votes":1251,"name":"clinton"},
{"votes":442,"name":"obama"},
{"votes":82,"name":"edwards"},
{"votes":7,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"uncommitted-d"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":1798,"precincts":
{"total":15,"reporting":15},
"name":"Henderson"},
"Weakley":
{"votes":[
{"votes":2273,"name":"clinton"},
{"votes":753,"name":"obama"},
{"votes":292,"name":"edwards"},
{"votes":38,"name":"uncommitted-d"},
{"votes":22,"name":"biden"},
{"votes":14,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"gravel"}],
"total":3404,"precincts":
{"total":10,"reporting":10},
"name":"Weakley"},
"Dickson":
{"votes":[
{"votes":4166,"name":"clinton"},
{"votes":974,"name":"obama"},
{"votes":254,"name":"edwards"},
{"votes":20,"name":"uncommitted-d"},
{"votes":9,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":5435,"precincts":
{"total":18,"reporting":18},
"name":"Dickson"},
"Bedford":
{"votes":[
{"votes":2934,"name":"clinton"},
{"votes":900,"name":"obama"},
{"votes":204,"name":"edwards"},
{"votes":26,"name":"uncommitted-d"},
{"votes":11,"name":"biden"},
{"votes":8,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":4092,"precincts":
{"total":18,"reporting":18},
"name":"Bedford"},
"Obion":
{"votes":[
{"votes":2684,"name":"clinton"},
{"votes":801,"name":"obama"},
{"votes":644,"name":"edwards"},
{"votes":265,"name":"uncommitted-d"},
{"votes":33,"name":"richardson"},
{"votes":28,"name":"biden"},
{"votes":20,"name":"kucinich"},
{"votes":10,"name":"dodd"},
{"votes":6,"name":"gravel"}],
"total":4491,"precincts":
{"total":12,"reporting":12},
"name":"Obion"},
"Humphreys":
{"votes":[
{"votes":2499,"name":"clinton"},
{"votes":280,"name":"obama"},
{"votes":274,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"},
{"votes":7,"name":"biden"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":3088,"precincts":
{"total":9,"reporting":9},
"name":"Humphreys"},
"Hancock":
{"votes":[
{"votes":240,"name":"clinton"},
{"votes":56,"name":"obama"},
{"votes":28,"name":"edwards"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":329,"precincts":
{"total":7,"reporting":7},
"name":"Hancock"},
"Henry":
{"votes":[
{"votes":2706,"name":"clinton"},
{"votes":1005,"name":"obama"},
{"votes":274,"name":"edwards"},
{"votes":29,"name":"uncommitted-d"},
{"votes":17,"name":"biden"},
{"votes":10,"name":"kucinich"},
{"votes":8,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":4053,"precincts":
{"total":13,"reporting":13},
"name":"Henry"},
"Trousdale":
{"votes":[
{"votes":778,"name":"clinton"},
{"votes":222,"name":"obama"},
{"votes":68,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"uncommitted-d"}],
"total":1076,"precincts":
{"total":10,"reporting":10},
"name":"Trousdale"},
"Moore":
{"votes":[
{"votes":518,"name":"clinton"},
{"votes":141,"name":"obama"},
{"votes":46,"name":"edwards"},
{"votes":7,"name":"uncommitted-d"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"}],
"total":716,"precincts":
{"total":5,"reporting":5},
"name":"Moore"},
"Sullivan":
{"votes":[
{"votes":6162,"name":"clinton"},
{"votes":2541,"name":"obama"},
{"votes":595,"name":"edwards"},
{"votes":31,"name":"biden"},
{"votes":29,"name":"uncommitted-d"},
{"votes":20,"name":"richardson"},
{"votes":15,"name":"kucinich"},
{"votes":11,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":9407,"precincts":
{"total":29,"reporting":29},
"name":"Sullivan"},
"Maury":
{"votes":[
{"votes":4543,"name":"clinton"},
{"votes":2420,"name":"obama"},
{"votes":365,"name":"edwards"},
{"votes":22,"name":"richardson"},
{"votes":15,"name":"biden"},
{"votes":14,"name":"uncommitted-d"},
{"votes":9,"name":"kucinich"},
{"votes":8,"name":"dodd"},
{"votes":7,"name":"gravel"}],
"total":7403,"precincts":
{"total":21,"reporting":21},
"name":"Maury"},
"Washington":
{"votes":[
{"votes":5731,"name":"clinton"},
{"votes":3258,"name":"obama"},
{"votes":658,"name":"edwards"},
{"votes":67,"name":"uncommitted-d"},
{"votes":23,"name":"kucinich"},
{"votes":17,"name":"biden"},
{"votes":12,"name":"richardson"},
{"votes":11,"name":"dodd"},
{"votes":7,"name":"gravel"}],
"total":9784,"precincts":
{"total":40,"reporting":40},
"name":"Washington"},
"Bradley":
{"votes":[
{"votes":4139,"name":"clinton"},
{"votes":1625,"name":"obama"},
{"votes":377,"name":"edwards"},
{"votes":12,"name":"biden"},
{"votes":10,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":7,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":6186,"precincts":
{"total":17,"reporting":17},
"name":"Bradley"},
"Marion":
{"votes":[
{"votes":3496,"name":"clinton"},
{"votes":688,"name":"obama"},
{"votes":256,"name":"edwards"},
{"votes":32,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":4498,"precincts":
{"total":20,"reporting":20},
"name":"Marion"},
"Hickman":
{"votes":[
{"votes":2171,"name":"clinton"},
{"votes":446,"name":"obama"},
{"votes":121,"name":"edwards"},
{"votes":9,"name":"dodd"},
{"votes":6,"name":"biden"},
{"votes":6,"name":"uncommitted-d"},
{"votes":4,"name":"richardson"},
{"votes":2,"name":"kucinich"}],
"total":2765,"precincts":
{"total":18,"reporting":18},
"name":"Hickman"},
"Polk":
{"votes":[
{"votes":2154,"name":"clinton"},
{"votes":460,"name":"edwards"},
{"votes":348,"name":"obama"},
{"votes":136,"name":"uncommitted-d"},
{"votes":21,"name":"richardson"},
{"votes":18,"name":"biden"},
{"votes":9,"name":"dodd"},
{"votes":9,"name":"kucinich"},
{"votes":9,"name":"gravel"}],
"total":3164,"precincts":
{"total":11,"reporting":11},
"name":"Polk"},
"Warren":
{"votes":[
{"votes":4113,"name":"clinton"},
{"votes":666,"name":"obama"},
{"votes":328,"name":"edwards"},
{"votes":21,"name":"uncommitted-d"},
{"votes":14,"name":"biden"},
{"votes":11,"name":"richardson"},
{"votes":7,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"kucinich"}],
"total":5169,"precincts":
{"total":21,"reporting":21},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":1098,"name":"clinton"},
{"votes":159,"name":"edwards"},
{"votes":152,"name":"obama"},
{"votes":40,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":1479,"precincts":
{"total":10,"reporting":10},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":1723,"name":"clinton"},
{"votes":212,"name":"obama"},
{"votes":71,"name":"edwards"},
{"votes":4,"name":"uncommitted-d"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"biden"}],
"total":2020,"precincts":
{"total":17,"reporting":17},
"name":"Jackson"},
"Anderson":
{"votes":[
{"votes":4886,"name":"clinton"},
{"votes":2558,"name":"obama"},
{"votes":445,"name":"edwards"},
{"votes":30,"name":"richardson"},
{"votes":28,"name":"uncommitted-d"},
{"votes":19,"name":"biden"},
{"votes":15,"name":"kucinich"},
{"votes":11,"name":"gravel"},
{"votes":7,"name":"dodd"}],
"total":7999,"precincts":
{"total":29,"reporting":29},
"name":"Anderson"},
"Jefferson":
{"votes":[
{"votes":2470,"name":"clinton"},
{"votes":775,"name":"obama"},
{"votes":185,"name":"edwards"},
{"votes":11,"name":"uncommitted-d"},
{"votes":6,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":3462,"precincts":
{"total":16,"reporting":16},
"name":"Jefferson"},
"Rhea":
{"votes":[
{"votes":2026,"name":"clinton"},
{"votes":405,"name":"obama"},
{"votes":166,"name":"edwards"},
{"votes":20,"name":"uncommitted-d"},
{"votes":14,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"kucinich"}],
"total":2645,"precincts":
{"total":15,"reporting":15},
"name":"Rhea"},
"Hardin":
{"votes":[
{"votes":1696,"name":"clinton"},
{"votes":311,"name":"obama"},
{"votes":109,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":5,"name":"uncommitted-d"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"}],
"total":2145,"precincts":
{"total":18,"reporting":18},
"name":"Hardin"},
"Putnam":
{"votes":[
{"votes":5546,"name":"clinton"},
{"votes":1758,"name":"obama"},
{"votes":784,"name":"edwards"},
{"votes":148,"name":"uncommitted-d"},
{"votes":38,"name":"richardson"},
{"votes":30,"name":"biden"},
{"votes":23,"name":"kucinich"},
{"votes":15,"name":"gravel"},
{"votes":11,"name":"dodd"}],
"total":8353,"precincts":
{"total":44,"reporting":44},
"name":"Putnam"},
"Coffee":
{"votes":[
{"votes":4163,"name":"clinton"},
{"votes":1110,"name":"obama"},
{"votes":407,"name":"edwards"},
{"votes":48,"name":"uncommitted-d"},
{"votes":28,"name":"biden"},
{"votes":24,"name":"richardson"},
{"votes":21,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":5810,"precincts":
{"total":24,"reporting":24},
"name":"Coffee"},
"Sevier":
{"votes":[
{"votes":3568,"name":"clinton"},
{"votes":1245,"name":"obama"},
{"votes":191,"name":"edwards"},
{"votes":37,"name":"uncommitted-d"},
{"votes":13,"name":"biden"},
{"votes":12,"name":"kucinich"},
{"votes":9,"name":"dodd"},
{"votes":8,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":5085,"precincts":
{"total":24,"reporting":24},
"name":"Sevier"},
"Crockett":
{"votes":[
{"votes":1121,"name":"clinton"},
{"votes":358,"name":"obama"},
{"votes":60,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"uncommitted-d"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":1559,"precincts":
{"total":12,"reporting":12},
"name":"Crockett"},
"Hamilton":
{"votes":[
{"votes":19831,"name":"obama"},
{"votes":16562,"name":"clinton"},
{"votes":1175,"name":"edwards"},
{"votes":112,"name":"uncommitted-d"},
{"votes":53,"name":"biden"},
{"votes":33,"name":"kucinich"},
{"votes":32,"name":"gravel"},
{"votes":24,"name":"richardson"},
{"votes":19,"name":"dodd"}],
"total":37841,"precincts":
{"total":127,"reporting":127},
"name":"Hamilton"},
"Lauderdale":
{"votes":[
{"votes":1570,"name":"clinton"},
{"votes":886,"name":"obama"},
{"votes":89,"name":"edwards"},
{"votes":10,"name":"biden"},
{"votes":4,"name":"uncommitted-d"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":2569,"precincts":
{"total":16,"reporting":16},
"name":"Lauderdale"},
"Johnson":
{"votes":[
{"votes":600,"name":"clinton"},
{"votes":214,"name":"obama"},
{"votes":99,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"uncommitted-d"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"}],
"total":930,"precincts":
{"total":12,"reporting":12},
"name":"Johnson"},
"Rutherford":
{"votes":[
{"votes":11011,"name":"clinton"},
{"votes":9033,"name":"obama"},
{"votes":974,"name":"edwards"},
{"votes":90,"name":"uncommitted-d"},
{"votes":39,"name":"biden"},
{"votes":39,"name":"richardson"},
{"votes":28,"name":"kucinich"},
{"votes":16,"name":"gravel"},
{"votes":15,"name":"dodd"}],
"total":21245,"precincts":
{"total":48,"reporting":48},
"name":"Rutherford"},
"Greene":
{"votes":[
{"votes":3181,"name":"clinton"},
{"votes":1038,"name":"obama"},
{"votes":264,"name":"edwards"},
{"votes":19,"name":"uncommitted-d"},
{"votes":13,"name":"richardson"},
{"votes":12,"name":"biden"},
{"votes":8,"name":"kucinich"},
{"votes":7,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":4546,"precincts":
{"total":39,"reporting":39},
"name":"Greene"},
"Chester":
{"votes":[
{"votes":832,"name":"clinton"},
{"votes":299,"name":"obama"},
{"votes":48,"name":"edwards"},
{"votes":10,"name":"uncommitted-d"},
{"votes":6,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"kucinich"}],
"total":1199,"precincts":
{"total":16,"reporting":16},
"name":"Chester"},
"Overton":
{"votes":[
{"votes":3011,"name":"clinton"},
{"votes":322,"name":"obama"},
{"votes":258,"name":"edwards"},
{"votes":34,"name":"uncommitted-d"},
{"votes":9,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":3651,"precincts":
{"total":13,"reporting":13},
"name":"Overton"},
"Clay":
{"votes":[
{"votes":868,"name":"clinton"},
{"votes":105,"name":"obama"},
{"votes":51,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"uncommitted-d"},
{"votes":2,"name":"dodd"}],
"total":1038,"precincts":
{"total":7,"reporting":7},
"name":"Clay"},
"McMinn":
{"votes":[
{"votes":2637,"name":"clinton"},
{"votes":897,"name":"obama"},
{"votes":272,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"},
{"votes":14,"name":"biden"},
{"votes":7,"name":"dodd"},
{"votes":7,"name":"gravel"},
{"votes":6,"name":"richardson"},
{"votes":2,"name":"kucinich"}],
"total":3859,"precincts":
{"total":15,"reporting":15},
"name":"McMinn"},
"Gibson":
{"votes":[
{"votes":3450,"name":"clinton"},
{"votes":1702,"name":"obama"},
{"votes":535,"name":"edwards"},
{"votes":155,"name":"uncommitted-d"},
{"votes":35,"name":"biden"},
{"votes":32,"name":"richardson"},
{"votes":20,"name":"dodd"},
{"votes":8,"name":"kucinich"},
{"votes":3,"name":"gravel"}],
"total":5940,"precincts":
{"total":36,"reporting":36},
"name":"Gibson"},
"Macon":
{"votes":[
{"votes":1213,"name":"clinton"},
{"votes":211,"name":"edwards"},
{"votes":144,"name":"obama"},
{"votes":17,"name":"uncommitted-d"},
{"votes":8,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"}],
"total":1600,"precincts":
{"total":10,"reporting":10},
"name":"Macon"},
"Madison":
{"votes":[
{"votes":5123,"name":"obama"},
{"votes":3433,"name":"clinton"},
{"votes":218,"name":"edwards"},
{"votes":28,"name":"biden"},
{"votes":19,"name":"richardson"},
{"votes":14,"name":"dodd"},
{"votes":13,"name":"uncommitted-d"},
{"votes":9,"name":"kucinich"},
{"votes":3,"name":"gravel"}],
"total":8860,"precincts":
{"total":33,"reporting":33},
"name":"Madison"},
"Grainger":
{"votes":[
{"votes":1341,"name":"clinton"},
{"votes":249,"name":"obama"},
{"votes":130,"name":"edwards"},
{"votes":16,"name":"uncommitted-d"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":1755,"precincts":
{"total":10,"reporting":10},
"name":"Grainger"},
"Hawkins":
{"votes":[
{"votes":2422,"name":"clinton"},
{"votes":564,"name":"obama"},
{"votes":262,"name":"edwards"},
{"votes":14,"name":"uncommitted-d"},
{"votes":14,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":3296,"precincts":
{"total":26,"reporting":26},
"name":"Hawkins"},
"Meigs":
{"votes":[
{"votes":877,"name":"clinton"},
{"votes":171,"name":"obama"},
{"votes":109,"name":"edwards"},
{"votes":8,"name":"uncommitted-d"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"kucinich"}],
"total":1171,"precincts":
{"total":6,"reporting":6},
"name":"Meigs"},
"Davidson":
{"votes":[
{"votes":49862,"name":"obama"},
{"votes":32067,"name":"clinton"},
{"votes":2137,"name":"edwards"},
{"votes":209,"name":"uncommitted-d"},
{"votes":153,"name":"kucinich"},
{"votes":126,"name":"biden"},
{"votes":110,"name":"richardson"},
{"votes":45,"name":"gravel"},
{"votes":37,"name":"dodd"}],
"total":84746,"precincts":
{"total":171,"reporting":171},
"name":"Davidson"},
"Cheatham":
{"votes":[
{"votes":2751,"name":"clinton"},
{"votes":814,"name":"obama"},
{"votes":206,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"},
{"votes":10,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":3811,"precincts":
{"total":11,"reporting":11},
"name":"Cheatham"},
"Bledsoe":
{"votes":[
{"votes":1399,"name":"clinton"},
{"votes":195,"name":"obama"},
{"votes":132,"name":"edwards"},
{"votes":25,"name":"uncommitted-d"},
{"votes":10,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":1769,"precincts":
{"total":15,"reporting":15},
"name":"Bledsoe"},
"Lawrence":
{"votes":[
{"votes":3200,"name":"clinton"},
{"votes":532,"name":"obama"},
{"votes":235,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"},
{"votes":9,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":4007,"precincts":
{"total":29,"reporting":29},
"name":"Lawrence"},
"Fayette":
{"votes":[
{"votes":1643,"name":"obama"},
{"votes":1294,"name":"clinton"},
{"votes":43,"name":"edwards"},
{"votes":10,"name":"uncommitted-d"},
{"votes":7,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":6,"name":"kucinich"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":3019,"precincts":
{"total":17,"reporting":17},
"name":"Fayette"},
"Claiborne":
{"votes":[
{"votes":2138,"name":"clinton"},
{"votes":276,"name":"obama"},
{"votes":128,"name":"edwards"},
{"votes":6,"name":"uncommitted-d"},
{"votes":5,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":2563,"precincts":
{"total":18,"reporting":18},
"name":"Claiborne"},
"Lincoln":
{"votes":[
{"votes":2464,"name":"clinton"},
{"votes":706,"name":"obama"},
{"votes":267,"name":"edwards"},
{"votes":50,"name":"uncommitted-d"},
{"votes":10,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"gravel"}],
"total":3521,"precincts":
{"total":20,"reporting":20},
"name":"Lincoln"},
"Franklin":
{"votes":[
{"votes":4087,"name":"clinton"},
{"votes":1326,"name":"obama"},
{"votes":339,"name":"edwards"},
{"votes":31,"name":"uncommitted-d"},
{"votes":25,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":5834,"precincts":
{"total":18,"reporting":18},
"name":"Franklin"},
"Dyer":
{"votes":[
{"votes":2009,"name":"clinton"},
{"votes":651,"name":"obama"},
{"votes":133,"name":"edwards"},
{"votes":12,"name":"uncommitted-d"},
{"votes":9,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":2822,"precincts":
{"total":16,"reporting":16},
"name":"Dyer"},
"Sumner":
{"votes":[
{"votes":8605,"name":"clinton"},
{"votes":3993,"name":"obama"},
{"votes":393,"name":"edwards"},
{"votes":34,"name":"uncommitted-d"},
{"votes":25,"name":"richardson"},
{"votes":21,"name":"biden"},
{"votes":14,"name":"kucinich"},
{"votes":9,"name":"dodd"},
{"votes":8,"name":"gravel"}],
"total":13102,"precincts":
{"total":36,"reporting":36},
"name":"Sumner"},
"Marshall":
{"votes":[
{"votes":180,"name":"obama"},
{"votes":133,"name":"clinton"},
{"votes":121,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":445,"precincts":
{"total":9,"reporting":9},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":1982,"name":"clinton"},
{"votes":709,"name":"obama"},
{"votes":157,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":6,"name":"dodd"},
{"votes":5,"name":"uncommitted-d"},
{"votes":5,"name":"kucinich"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":2875,"precincts":
{"total":22,"reporting":22},
"name":"Carroll"},
"Grundy":
{"votes":[
{"votes":1931,"name":"clinton"},
{"votes":158,"name":"obama"},
{"votes":122,"name":"edwards"},
{"votes":22,"name":"uncommitted-d"},
{"votes":8,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":2250,"precincts":
{"total":13,"reporting":13},
"name":"Grundy"},
"Campbell":
{"votes":[
{"votes":2854,"name":"clinton"},
{"votes":326,"name":"obama"},
{"votes":122,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"},
{"votes":17,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":3351,"precincts":
{"total":21,"reporting":21},
"name":"Campbell"},
"Hardeman":
{"votes":[
{"votes":1766,"name":"obama"},
{"votes":1516,"name":"clinton"},
{"votes":61,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":15,"name":"kucinich"},
{"votes":11,"name":"richardson"},
{"votes":6,"name":"uncommitted-d"},
{"votes":5,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":3397,"precincts":
{"total":13,"reporting":13},
"name":"Hardeman"},
"Sequatchie":
{"votes":[
{"votes":1067,"name":"clinton"},
{"votes":210,"name":"obama"},
{"votes":73,"name":"edwards"},
{"votes":3,"name":"uncommitted-d"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1364,"precincts":
{"total":10,"reporting":10},
"name":"Sequatchie"},
"Cumberland":
{"votes":[
{"votes":4549,"name":"clinton"},
{"votes":1709,"name":"obama"},
{"votes":826,"name":"edwards"},
{"votes":168,"name":"uncommitted-d"},
{"votes":38,"name":"biden"},
{"votes":37,"name":"richardson"},
{"votes":27,"name":"kucinich"},
{"votes":12,"name":"dodd"},
{"votes":10,"name":"gravel"}],
"total":7376,"precincts":
{"total":26,"reporting":26},
"name":"Cumberland"},
"McNairy":
{"votes":[
{"votes":1608,"name":"clinton"},
{"votes":342,"name":"obama"},
{"votes":98,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":5,"name":"uncommitted-d"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":2070,"precincts":
{"total":17,"reporting":17},
"name":"McNairy"},
"Lake":
{"votes":[
{"votes":461,"name":"clinton"},
{"votes":136,"name":"obama"},
{"votes":28,"name":"edwards"},
{"votes":5,"name":"dodd"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"uncommitted-d"}],
"total":638,"precincts":
{"total":4,"reporting":4},
"name":"Lake"},
"Roane":
{"votes":[
{"votes":3733,"name":"clinton"},
{"votes":1350,"name":"obama"},
{"votes":410,"name":"edwards"},
{"votes":18,"name":"uncommitted-d"},
{"votes":17,"name":"biden"},
{"votes":14,"name":"richardson"},
{"votes":10,"name":"kucinich"},
{"votes":7,"name":"dodd"},
{"votes":6,"name":"gravel"}],
"total":5565,"precincts":
{"total":25,"reporting":25},
"name":"Roane"},
"DeKalb":
{"votes":[
{"votes":2410,"name":"clinton"},
{"votes":347,"name":"obama"},
{"votes":272,"name":"edwards"},
{"votes":31,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":3088,"precincts":
{"total":16,"reporting":16},
"name":"DeKalb"},
"Loudon":
{"votes":[
{"votes":2459,"name":"clinton"},
{"votes":1027,"name":"obama"},
{"votes":282,"name":"edwards"},
{"votes":18,"name":"uncommitted-d"},
{"votes":9,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":3812,"precincts":
{"total":14,"reporting":14},
"name":"Loudon"},
"Haywood":
{"votes":[
{"votes":1142,"name":"obama"},
{"votes":688,"name":"clinton"},
{"votes":37,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"uncommitted-d"},
{"votes":1,"name":"richardson"}],
"total":1884,"precincts":
{"total":15,"reporting":15},
"name":"Haywood"},
"Williamson":
{"votes":[
{"votes":7246,"name":"obama"},
{"votes":6935,"name":"clinton"},
{"votes":426,"name":"edwards"},
{"votes":33,"name":"uncommitted-d"},
{"votes":21,"name":"biden"},
{"votes":12,"name":"kucinich"},
{"votes":9,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":14690,"precincts":
{"total":44,"reporting":44},
"name":"Williamson"},
"Cannon":
{"votes":[
{"votes":1572,"name":"clinton"},
{"votes":264,"name":"obama"},
{"votes":119,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"},
{"votes":6,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"}],
"total":1980,"precincts":
{"total":9,"reporting":9},
"name":"Cannon"},
"Van Buren":
{"votes":[
{"votes":682,"name":"clinton"},
{"votes":90,"name":"obama"},
{"votes":32,"name":"edwards"},
{"votes":7,"name":"uncommitted-d"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":815,"precincts":
{"total":7,"reporting":7},
"name":"Van Buren"},
"Giles":
{"votes":[
{"votes":2528,"name":"clinton"},
{"votes":866,"name":"obama"},
{"votes":270,"name":"edwards"},
{"votes":34,"name":"uncommitted-d"},
{"votes":14,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":3730,"precincts":
{"total":14,"reporting":14},
"name":"Giles"},
"Knox":
{"votes":[
{"votes":18693,"name":"clinton"},
{"votes":16639,"name":"obama"},
{"votes":2002,"name":"edwards"},
{"votes":251,"name":"uncommitted-d"},
{"votes":86,"name":"richardson"},
{"votes":84,"name":"kucinich"},
{"votes":75,"name":"biden"},
{"votes":32,"name":"gravel"},
{"votes":25,"name":"dodd"}],
"total":37887,"precincts":
{"total":94,"reporting":94},
"name":"Knox"},
"Decatur":
{"votes":[
{"votes":1189,"name":"clinton"},
{"votes":164,"name":"obama"},
{"votes":82,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"uncommitted-d"}],
"total":1449,"precincts":
{"total":19,"reporting":19},
"name":"Decatur"},
"Tipton":
{"votes":[
{"votes":2000,"name":"clinton"},
{"votes":1355,"name":"obama"},
{"votes":152,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":8,"name":"kucinich"},
{"votes":6,"name":"richardson"},
{"votes":4,"name":"uncommitted-d"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":3546,"precincts":
{"total":13,"reporting":13},
"name":"Tipton"},
"Benton":
{"votes":[
{"votes":2199,"name":"clinton"},
{"votes":421,"name":"edwards"},
{"votes":368,"name":"obama"},
{"votes":60,"name":"uncommitted-d"},
{"votes":17,"name":"richardson"},
{"votes":16,"name":"biden"},
{"votes":10,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":3097,"precincts":
{"total":6,"reporting":6},
"name":"Benton"},
"Pickett":
{"votes":[
{"votes":572,"name":"clinton"},
{"votes":66,"name":"obama"},
{"votes":41,"name":"edwards"},
{"votes":7,"name":"uncommitted-d"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":690,"precincts":
{"total":9,"reporting":9},
"name":"Pickett"},
"Morgan":
{"votes":[
{"votes":1331,"name":"clinton"},
{"votes":204,"name":"obama"},
{"votes":124,"name":"edwards"},
{"votes":7,"name":"uncommitted-d"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"richardson"}],
"total":1680,"precincts":
{"total":12,"reporting":12},
"name":"Morgan"},
"Unicoi":
{"votes":[
{"votes":736,"name":"clinton"},
{"votes":205,"name":"obama"},
{"votes":83,"name":"edwards"},
{"votes":9,"name":"uncommitted-d"},
{"votes":8,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":1045,"precincts":
{"total":8,"reporting":8},
"name":"Unicoi"},
"Stewart":
{"votes":[
{"votes":1613,"name":"clinton"},
{"votes":248,"name":"obama"},
{"votes":177,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"},
{"votes":6,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":2066,"precincts":
{"total":9,"reporting":9},
"name":"Stewart"},
"Houston":
{"votes":[
{"votes":1070,"name":"clinton"},
{"votes":150,"name":"obama"},
{"votes":86,"name":"edwards"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"uncommitted-d"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":1319,"precincts":
{"total":7,"reporting":7},
"name":"Houston"},
"Fentress":
{"votes":[
{"votes":1249,"name":"clinton"},
{"votes":180,"name":"obama"},
{"votes":94,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"uncommitted-d"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"}],
"total":1537,"precincts":
{"total":13,"reporting":13},
"name":"Fentress"},
"Carter":
{"votes":[
{"votes":2366,"name":"clinton"},
{"votes":745,"name":"obama"},
{"votes":189,"name":"edwards"},
{"votes":12,"name":"uncommitted-d"},
{"votes":7,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":3332,"precincts":
{"total":21,"reporting":21},
"name":"Carter"},
"Cocke":
{"votes":[
{"votes":1845,"name":"clinton"},
{"votes":432,"name":"obama"},
{"votes":103,"name":"edwards"},
{"votes":8,"name":"richardson"},
{"votes":5,"name":"uncommitted-d"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":2403,"precincts":
{"total":19,"reporting":19},
"name":"Cocke"},
"Lewis":
{"votes":[
{"votes":952,"name":"clinton"},
{"votes":231,"name":"obama"},
{"votes":76,"name":"edwards"},
{"votes":9,"name":"kucinich"},
{"votes":8,"name":"biden"},
{"votes":3,"name":"uncommitted-d"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":1286,"precincts":
{"total":9,"reporting":9},
"name":"Lewis"},
"Scott":
{"votes":[
{"votes":1252,"name":"clinton"},
{"votes":131,"name":"obama"},
{"votes":75,"name":"edwards"},
{"votes":5,"name":"uncommitted-d"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":1472,"precincts":
{"total":10,"reporting":10},
"name":"Scott"},
"Monroe":
{"votes":[
{"votes":2628,"name":"clinton"},
{"votes":718,"name":"obama"},
{"votes":316,"name":"edwards"},
{"votes":29,"name":"uncommitted-d"},
{"votes":10,"name":"richardson"},
{"votes":9,"name":"biden"},
{"votes":8,"name":"dodd"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":3728,"precincts":
{"total":13,"reporting":13},
"name":"Monroe"}}})