GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":255218,"name":"romney","delegates":36},
{"votes":15264,"name":"mccain"},
{"votes":8295,"name":"paul"},
{"votes":4054,"name":"huckabee"},
{"votes":928,"name":"giuliani"},
{"votes":575,"name":"thompson"},
{"votes":252,"name":"keyes"},
{"votes":204,"name":"hunter"}],
"name":"Utah","precincts":
{"total":2257,"reporting":2256},
"delegates":36,"date":"02-05"},
"state":"UT","party":"gop","total":284790,"locals":
{"San Juan":
{"votes":[
{"votes":1023,"name":"romney"},
{"votes":142,"name":"mccain"},
{"votes":33,"name":"huckabee"},
{"votes":18,"name":"paul"},
{"votes":10,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1232,"precincts":
{"total":20,"reporting":20},
"name":"San Juan"},
"Morgan":
{"votes":[
{"votes":1307,"name":"romney"},
{"votes":62,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":9,"name":"huckabee"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"giuliani"}],
"total":1407,"precincts":
{"total":13,"reporting":13},
"name":"Morgan"},
"Juab":
{"votes":[
{"votes":972,"name":"romney"},
{"votes":99,"name":"paul"},
{"votes":50,"name":"mccain"},
{"votes":8,"name":"huckabee"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"thompson"}],
"total":1135,"precincts":
{"total":7,"reporting":7},
"name":"Juab"},
"Utah":
{"votes":[
{"votes":50756,"name":"romney"},
{"votes":1820,"name":"paul"},
{"votes":1104,"name":"mccain"},
{"votes":222,"name":"huckabee"},
{"votes":58,"name":"giuliani"},
{"votes":53,"name":"keyes"},
{"votes":45,"name":"thompson"},
{"votes":17,"name":"hunter"}],
"total":54075,"precincts":
{"total":288,"reporting":288},
"name":"Utah"},
"Millard":
{"votes":[
{"votes":1706,"name":"romney"},
{"votes":144,"name":"paul"},
{"votes":124,"name":"mccain"},
{"votes":34,"name":"huckabee"},
{"votes":15,"name":"thompson"},
{"votes":14,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":2042,"precincts":
{"total":17,"reporting":17},
"name":"Millard"},
"Cache":
{"votes":[
{"votes":11814,"name":"romney"},
{"votes":417,"name":"mccain"},
{"votes":349,"name":"paul"},
{"votes":116,"name":"huckabee"},
{"votes":21,"name":"thompson"},
{"votes":17,"name":"giuliani"},
{"votes":14,"name":"keyes"},
{"votes":4,"name":"hunter"}],
"total":12752,"precincts":
{"total":83,"reporting":83},
"name":"Cache"},
"Wayne":
{"votes":[
{"votes":496,"name":"romney"},
{"votes":44,"name":"mccain"},
{"votes":9,"name":"paul"},
{"votes":4,"name":"huckabee"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":558,"precincts":
{"total":7,"reporting":7},
"name":"Wayne"},
"Rich":
{"votes":[
{"votes":334,"name":"romney"},
{"votes":14,"name":"mccain"},
{"votes":3,"name":"thompson"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"giuliani"}],
"total":355,"precincts":
{"total":4,"reporting":4},
"name":"Rich"},
"Grand":
{"votes":[
{"votes":534,"name":"romney"},
{"votes":154,"name":"mccain"},
{"votes":76,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":7,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":807,"precincts":
{"total":14,"reporting":14},
"name":"Grand"},
"Weber":
{"votes":[
{"votes":15526,"name":"romney"},
{"votes":1395,"name":"mccain"},
{"votes":346,"name":"huckabee"},
{"votes":334,"name":"paul"},
{"votes":44,"name":"thompson"},
{"votes":42,"name":"giuliani"},
{"votes":20,"name":"hunter"},
{"votes":10,"name":"keyes"}],
"total":17717,"precincts":
{"total":154,"reporting":154},
"name":"Weber"},
"Wasatch":
{"votes":[
{"votes":2158,"name":"romney"},
{"votes":131,"name":"mccain"},
{"votes":54,"name":"paul"},
{"votes":22,"name":"huckabee"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":2378,"precincts":
{"total":23,"reporting":23},
"name":"Wasatch"},
"Tooele":
{"votes":[
{"votes":4936,"name":"romney"},
{"votes":415,"name":"mccain"},
{"votes":137,"name":"huckabee"},
{"votes":137,"name":"paul"},
{"votes":29,"name":"giuliani"},
{"votes":17,"name":"thompson"},
{"votes":14,"name":"hunter"},
{"votes":10,"name":"keyes"}],
"total":5695,"precincts":
{"total":58,"reporting":58},
"name":"Tooele"},
"Sevier":
{"votes":[
{"votes":2990,"name":"romney"},
{"votes":195,"name":"mccain"},
{"votes":80,"name":"paul"},
{"votes":50,"name":"huckabee"},
{"votes":7,"name":"hunter"},
{"votes":7,"name":"giuliani"},
{"votes":4,"name":"thompson"}],
"total":3333,"precincts":
{"total":23,"reporting":23},
"name":"Sevier"},
"Sanpete":
{"votes":[
{"votes":3028,"name":"romney"},
{"votes":181,"name":"paul"},
{"votes":164,"name":"mccain"},
{"votes":41,"name":"huckabee"},
{"votes":10,"name":"thompson"},
{"votes":5,"name":"giuliani"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"hunter"}],
"total":3435,"precincts":
{"total":17,"reporting":17},
"name":"Sanpete"},
"Carbon":
{"votes":[
{"votes":1017,"name":"romney"},
{"votes":143,"name":"mccain"},
{"votes":60,"name":"huckabee"},
{"votes":28,"name":"paul"},
{"votes":12,"name":"giuliani"},
{"votes":3,"name":"thompson"}],
"total":1263,"precincts":
{"total":23,"reporting":23},
"name":"Carbon"},
"Piute":
{"votes":[
{"votes":305,"name":"romney"},
{"votes":30,"name":"mccain"},
{"votes":23,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":1,"name":"giuliani"}],
"total":376,"precincts":
{"total":5,"reporting":5},
"name":"Piute"},
"Emery":
{"votes":[
{"votes":1363,"name":"romney"},
{"votes":118,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":22,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1572,"precincts":
{"total":12,"reporting":12},
"name":"Emery"},
"Duchesne":
{"votes":[
{"votes":1837,"name":"romney"},
{"votes":109,"name":"mccain"},
{"votes":43,"name":"paul"},
{"votes":20,"name":"huckabee"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"keyes"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":2026,"precincts":
{"total":25,"reporting":25},
"name":"Duchesne"},
"Iron":
{"votes":[
{"votes":5246,"name":"romney"},
{"votes":355,"name":"mccain"},
{"votes":314,"name":"paul"},
{"votes":152,"name":"huckabee"},
{"votes":44,"name":"giuliani"},
{"votes":29,"name":"thompson"},
{"votes":11,"name":"keyes"},
{"votes":3,"name":"hunter"}],
"total":6154,"precincts":
{"total":33,"reporting":33},
"name":"Iron"},
"Davis":
{"votes":[
{"votes":32411,"name":"romney"},
{"votes":1775,"name":"mccain"},
{"votes":682,"name":"paul"},
{"votes":419,"name":"huckabee"},
{"votes":74,"name":"giuliani"},
{"votes":54,"name":"thompson"},
{"votes":22,"name":"hunter"},
{"votes":20,"name":"keyes"}],
"total":35457,"precincts":
{"total":220,"reporting":220},
"name":"Davis"},
"Daggett":
{"votes":[
{"votes":140,"name":"romney"},
{"votes":25,"name":"mccain"},
{"votes":6,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"thompson"}],
"total":178,"precincts":
{"total":3,"reporting":3},
"name":"Daggett"},
"Kane":
{"votes":[
{"votes":1140,"name":"romney"},
{"votes":161,"name":"mccain"},
{"votes":72,"name":"paul"},
{"votes":41,"name":"huckabee"},
{"votes":7,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"thompson"},
{"votes":2,"name":"keyes"}],
"total":1428,"precincts":
{"total":10,"reporting":10},
"name":"Kane"},
"Washington":
{"votes":[
{"votes":17447,"name":"romney"},
{"votes":1107,"name":"mccain"},
{"votes":610,"name":"paul"},
{"votes":355,"name":"huckabee"},
{"votes":78,"name":"giuliani"},
{"votes":52,"name":"thompson"},
{"votes":20,"name":"keyes"},
{"votes":18,"name":"hunter"}],
"total":19687,"precincts":
{"total":89,"reporting":89},
"name":"Washington"},
"Garfield":
{"votes":[
{"votes":948,"name":"romney"},
{"votes":100,"name":"mccain"},
{"votes":27,"name":"paul"},
{"votes":18,"name":"huckabee"},
{"votes":3,"name":"thompson"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":1100,"precincts":
{"total":10,"reporting":10},
"name":"Garfield"},
"Summit":
{"votes":[
{"votes":2122,"name":"romney"},
{"votes":463,"name":"mccain"},
{"votes":90,"name":"huckabee"},
{"votes":87,"name":"paul"},
{"votes":13,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"keyes"},
{"votes":2,"name":"hunter"}],
"total":2784,"precincts":
{"total":36,"reporting":36},
"name":"Summit"},
"Salt Lake":
{"votes":[
{"votes":83664,"name":"romney"},
{"votes":5787,"name":"mccain"},
{"votes":2862,"name":"paul"},
{"votes":1506,"name":"huckabee"},
{"votes":441,"name":"giuliani"},
{"votes":198,"name":"thompson"},
{"votes":83,"name":"keyes"},
{"votes":66,"name":"hunter"}],
"total":94607,"precincts":
{"total":977,"reporting":977},
"name":"Salt Lake"},
"Beaver":
{"votes":[
{"votes":745,"name":"romney"},
{"votes":48,"name":"mccain"},
{"votes":22,"name":"paul"},
{"votes":16,"name":"huckabee"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"giuliani"}],
"total":835,"precincts":
{"total":11,"reporting":11},
"name":"Beaver"},
"Uintah":
{"votes":[
{"votes":2787,"name":"romney"},
{"votes":246,"name":"mccain"},
{"votes":103,"name":"huckabee"},
{"votes":94,"name":"paul"},
{"votes":16,"name":"giuliani"},
{"votes":9,"name":"thompson"},
{"votes":6,"name":"hunter"}],
"total":3261,"precincts":
{"total":26,"reporting":26},
"name":"Uintah"},
"Box Elder":
{"votes":[
{"votes":6466,"name":"romney"},
{"votes":386,"name":"mccain"},
{"votes":133,"name":"paul"},
{"votes":101,"name":"huckabee"},
{"votes":24,"name":"thompson"},
{"votes":20,"name":"giuliani"},
{"votes":6,"name":"hunter"},
{"votes":5,"name":"keyes"}],
"total":7141,"precincts":
{"total":49,"reporting":48},
"name":"Box Elder"}}})