GoogleElectionMap.votesReady({"status":"ok","totals":
{"name":"Washington","precincts":
{"total":7150,"reporting":6856},
"votes":[
{"votes":327553,"name":"obama","delegates":53},
{"votes":294718,"name":"clinton","delegates":25},
{"votes":10983,"name":"edwards"},
{"votes":3988,"name":"biden"},
{"votes":3688,"name":"kucinich"},
{"votes":1866,"name":"richardson"},
{"votes":975,"name":"gravel"},
{"votes":567,"name":"dodd"},
{"votes":363,"name":"uncommitted-d"}],
"delegates":78,"date":"02-09","type":"caucus"},
"state":"WA","party":"dem","total":644701,"locals":
{"San Juan":
{"votes":[
{"votes":2770,"name":"obama"},
{"votes":1143,"name":"clinton"},
{"votes":91,"name":"kucinich"},
{"votes":59,"name":"edwards"},
{"votes":31,"name":"richardson"},
{"votes":12,"name":"biden"},
{"votes":11,"name":"gravel"},
{"votes":3,"name":"dodd"},
{"votes":1,"name":"uncommitted-d"}],
"total":4121,"precincts":
{"total":21,"reporting":17},
"name":"San Juan"},
"Pend Oreille":
{"votes":[
{"votes":765,"name":"clinton"},
{"votes":715,"name":"obama"},
{"votes":48,"name":"edwards"},
{"votes":8,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":0,"name":"uncommitted-d"}],
"total":1554,"precincts":
{"total":14,"reporting":14},
"name":"Pend Oreille"},
"Snohomish":
{"votes":[
{"votes":32794,"name":"obama"},
{"votes":31750,"name":"clinton"},
{"votes":980,"name":"edwards"},
{"votes":285,"name":"kucinich"},
{"votes":169,"name":"richardson"},
{"votes":134,"name":"biden"},
{"votes":97,"name":"gravel"},
{"votes":53,"name":"dodd"},
{"votes":26,"name":"uncommitted-d"}],
"total":66288,"precincts":
{"total":712,"reporting":448},
"name":"Snohomish"},
"Grant":
{"votes":[
{"votes":2566,"name":"clinton"},
{"votes":2133,"name":"obama"},
{"votes":102,"name":"edwards"},
{"votes":25,"name":"biden"},
{"votes":25,"name":"gravel"},
{"votes":20,"name":"richardson"},
{"votes":16,"name":"kucinich"},
{"votes":8,"name":"dodd"},
{"votes":0,"name":"uncommitted-d"}],
"total":4895,"precincts":
{"total":62,"reporting":62},
"name":"Grant"},
"Lincoln":
{"votes":[
{"votes":616,"name":"obama"},
{"votes":569,"name":"clinton"},
{"votes":44,"name":"edwards"},
{"votes":8,"name":"kucinich"},
{"votes":5,"name":"gravel"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"dodd"}],
"total":1246,"precincts":
{"total":13,"reporting":13},
"name":"Lincoln"},
"Douglas":
{"votes":[
{"votes":1384,"name":"obama"},
{"votes":1334,"name":"clinton"},
{"votes":54,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"kucinich"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":0,"name":"uncommitted-d"}],
"total":2815,"precincts":
{"total":32,"reporting":32},
"name":"Douglas"},
"Kittitas":
{"votes":[
{"votes":2120,"name":"obama"},
{"votes":2069,"name":"clinton"},
{"votes":82,"name":"edwards"},
{"votes":26,"name":"kucinich"},
{"votes":19,"name":"biden"},
{"votes":16,"name":"richardson"},
{"votes":11,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":2,"name":"uncommitted-d"}],
"total":4350,"precincts":
{"total":38,"reporting":38},
"name":"Kittitas"},
"Jefferson":
{"votes":[
{"votes":4144,"name":"obama"},
{"votes":2621,"name":"clinton"},
{"votes":183,"name":"kucinich"},
{"votes":92,"name":"edwards"},
{"votes":24,"name":"richardson"},
{"votes":18,"name":"biden"},
{"votes":14,"name":"gravel"},
{"votes":8,"name":"uncommitted-d"},
{"votes":6,"name":"dodd"}],
"total":7110,"precincts":
{"total":40,"reporting":40},
"name":"Jefferson"},
"Whatcom":
{"votes":[
{"votes":14402,"name":"obama"},
{"votes":8978,"name":"clinton"},
{"votes":352,"name":"edwards"},
{"votes":277,"name":"kucinich"},
{"votes":97,"name":"richardson"},
{"votes":67,"name":"biden"},
{"votes":57,"name":"gravel"},
{"votes":21,"name":"dodd"},
{"votes":18,"name":"uncommitted-d"}],
"total":24269,"precincts":
{"total":202,"reporting":161},
"name":"Whatcom"},
"Wahkiakum":
{"votes":[
{"votes":296,"name":"clinton"},
{"votes":294,"name":"obama"},
{"votes":11,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"gravel"}],
"total":609,"precincts":
{"total":5,"reporting":5},
"name":"Wahkiakum"},
"Cowlitz":
{"votes":[
{"votes":5747,"name":"clinton"},
{"votes":3940,"name":"obama"},
{"votes":224,"name":"edwards"},
{"votes":34,"name":"richardson"},
{"votes":34,"name":"kucinich"},
{"votes":26,"name":"biden"},
{"votes":15,"name":"gravel"},
{"votes":12,"name":"dodd"},
{"votes":6,"name":"uncommitted-d"}],
"total":10038,"precincts":
{"total":103,"reporting":103},
"name":"Cowlitz"},
"Columbia":
{"votes":[
{"votes":264,"name":"obama"},
{"votes":195,"name":"clinton"},
{"votes":21,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"kucinich"},
{"votes":0,"name":"uncommitted-d"}],
"total":493,"precincts":
{"total":5,"reporting":5},
"name":"Columbia"},
"Thurston":
{"votes":[
{"votes":18952,"name":"obama"},
{"votes":15063,"name":"clinton"},
{"votes":640,"name":"edwards"},
{"votes":319,"name":"kucinich"},
{"votes":142,"name":"richardson"},
{"votes":89,"name":"biden"},
{"votes":49,"name":"gravel"},
{"votes":30,"name":"uncommitted-d"},
{"votes":30,"name":"dodd"}],
"total":35314,"precincts":
{"total":263,"reporting":263},
"name":"Thurston"},
"Yakima":
{"votes":[
{"votes":8348,"name":"clinton"},
{"votes":6693,"name":"obama"},
{"votes":304,"name":"edwards"},
{"votes":62,"name":"biden"},
{"votes":55,"name":"richardson"},
{"votes":35,"name":"kucinich"},
{"votes":21,"name":"gravel"},
{"votes":17,"name":"dodd"},
{"votes":14,"name":"uncommitted-d"}],
"total":15549,"precincts":
{"total":185,"reporting":185},
"name":"Yakima"},
"Klickitat":
{"votes":[
{"votes":1333,"name":"obama"},
{"votes":1272,"name":"clinton"},
{"votes":77,"name":"edwards"},
{"votes":15,"name":"kucinich"},
{"votes":12,"name":"richardson"},
{"votes":11,"name":"gravel"},
{"votes":10,"name":"biden"},
{"votes":5,"name":"dodd"},
{"votes":1,"name":"uncommitted-d"}],
"total":2736,"precincts":
{"total":23,"reporting":23},
"name":"Klickitat"},
"Okanogan":
{"votes":[
{"votes":2234,"name":"biden"},
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"gravel"},
{"votes":0,"name":"obama"}],
"total":2234,"precincts":
{"total":38,"reporting":17},
"name":"Okanogan"},
"Kitsap":
{"votes":[
{"votes":16668,"name":"obama"},
{"votes":12955,"name":"clinton"},
{"votes":514,"name":"edwards"},
{"votes":156,"name":"kucinich"},
{"votes":155,"name":"richardson"},
{"votes":102,"name":"biden"},
{"votes":61,"name":"gravel"},
{"votes":32,"name":"dodd"},
{"votes":17,"name":"uncommitted-d"}],
"total":30660,"precincts":
{"total":265,"reporting":265},
"name":"Kitsap"},
"Clallam":
{"votes":[
{"votes":5224,"name":"obama"},
{"votes":4345,"name":"clinton"},
{"votes":191,"name":"edwards"},
{"votes":99,"name":"kucinich"},
{"votes":40,"name":"richardson"},
{"votes":31,"name":"biden"},
{"votes":23,"name":"gravel"},
{"votes":14,"name":"dodd"},
{"votes":7,"name":"uncommitted-d"}],
"total":9974,"precincts":
{"total":83,"reporting":66},
"name":"Clallam"},
"King":
{"votes":[
{"votes":90829,"name":"obama"},
{"votes":69569,"name":"clinton"},
{"votes":1977,"name":"edwards"},
{"votes":1022,"name":"kucinich"},
{"votes":344,"name":"richardson"},
{"votes":304,"name":"biden"},
{"votes":176,"name":"gravel"},
{"votes":92,"name":"uncommitted-d"},
{"votes":80,"name":"dodd"}],
"total":164393,"precincts":
{"total":2553,"reporting":2189},
"name":"King"},
"Pierce":
{"votes":[
{"votes":36163,"name":"clinton"},
{"votes":32411,"name":"obama"},
{"votes":1215,"name":"edwards"},
{"votes":232,"name":"kucinich"},
{"votes":177,"name":"biden"},
{"votes":148,"name":"richardson"},
{"votes":88,"name":"gravel"},
{"votes":52,"name":"dodd"},
{"votes":39,"name":"uncommitted-d"}],
"total":70525,"precincts":
{"total":708,"reporting":311},
"name":"Pierce"},
"Spokane":
{"votes":[
{"votes":27349,"name":"obama"},
{"votes":27014,"name":"clinton"},
{"votes":1137,"name":"edwards"},
{"votes":215,"name":"kucinich"},
{"votes":212,"name":"biden"},
{"votes":147,"name":"richardson"},
{"votes":87,"name":"gravel"},
{"votes":57,"name":"dodd"},
{"votes":12,"name":"uncommitted-d"}],
"total":56230,"precincts":
{"total":479,"reporting":479},
"name":"Spokane"},
"Adams":
{"votes":[
{"votes":529,"name":"clinton"},
{"votes":410,"name":"obama"},
{"votes":30,"name":"edwards"},
{"votes":7,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"uncommitted-d"},
{"votes":0,"name":"dodd"}],
"total":987,"precincts":
{"total":12,"reporting":12},
"name":"Adams"},
"Grays Harbor":
{"votes":[
{"votes":4251,"name":"clinton"},
{"votes":3244,"name":"obama"},
{"votes":165,"name":"edwards"},
{"votes":48,"name":"kucinich"},
{"votes":23,"name":"biden"},
{"votes":19,"name":"richardson"},
{"votes":16,"name":"dodd"},
{"votes":9,"name":"gravel"},
{"votes":8,"name":"uncommitted-d"}],
"total":7783,"precincts":
{"total":70,"reporting":70},
"name":"Grays Harbor"},
"Island":
{"votes":[
{"votes":6227,"name":"obama"},
{"votes":4630,"name":"clinton"},
{"votes":211,"name":"edwards"},
{"votes":79,"name":"kucinich"},
{"votes":37,"name":"richardson"},
{"votes":33,"name":"biden"},
{"votes":17,"name":"gravel"},
{"votes":10,"name":"dodd"},
{"votes":2,"name":"uncommitted-d"}],
"total":11246,"precincts":
{"total":83,"reporting":83},
"name":"Island"},
"Benton":
{"votes":[
{"votes":5876,"name":"clinton"},
{"votes":5468,"name":"obama"},
{"votes":321,"name":"edwards"},
{"votes":51,"name":"richardson"},
{"votes":41,"name":"kucinich"},
{"votes":36,"name":"biden"},
{"votes":21,"name":"dodd"},
{"votes":14,"name":"gravel"},
{"votes":9,"name":"uncommitted-d"}],
"total":11837,"precincts":
{"total":163,"reporting":163},
"name":"Benton"},
"Franklin":
{"votes":[
{"votes":1535,"name":"clinton"},
{"votes":1288,"name":"obama"},
{"votes":84,"name":"edwards"},
{"votes":21,"name":"richardson"},
{"votes":11,"name":"biden"},
{"votes":7,"name":"gravel"},
{"votes":6,"name":"dodd"},
{"votes":6,"name":"kucinich"},
{"votes":1,"name":"uncommitted-d"}],
"total":2959,"precincts":
{"total":40,"reporting":40},
"name":"Franklin"},
"Ferry":
{"votes":[
{"votes":414,"name":"obama"},
{"votes":362,"name":"clinton"},
{"votes":17,"name":"edwards"},
{"votes":11,"name":"kucinich"},
{"votes":6,"name":"gravel"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"uncommitted-d"},
{"votes":2,"name":"biden"}],
"total":820,"precincts":
{"total":8,"reporting":8},
"name":"Ferry"},
"Mason":
{"votes":[
{"votes":4415,"name":"clinton"},
{"votes":4125,"name":"obama"},
{"votes":185,"name":"edwards"},
{"votes":47,"name":"biden"},
{"votes":40,"name":"kucinich"},
{"votes":24,"name":"richardson"},
{"votes":14,"name":"gravel"},
{"votes":8,"name":"dodd"},
{"votes":4,"name":"uncommitted-d"}],
"total":8862,"precincts":
{"total":59,"reporting":59},
"name":"Mason"},
"Whitman":
{"votes":[
{"votes":1839,"name":"obama"},
{"votes":1251,"name":"clinton"},
{"votes":44,"name":"edwards"},
{"votes":21,"name":"kucinich"},
{"votes":15,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"uncommitted-d"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":3181,"precincts":
{"total":40,"reporting":38},
"name":"Whitman"},
"Skagit":
{"votes":[
{"votes":5454,"name":"obama"},
{"votes":4040,"name":"clinton"},
{"votes":189,"name":"edwards"},
{"votes":92,"name":"kucinich"},
{"votes":25,"name":"biden"},
{"votes":25,"name":"richardson"},
{"votes":23,"name":"gravel"},
{"votes":12,"name":"dodd"},
{"votes":11,"name":"uncommitted-d"}],
"total":9871,"precincts":
{"total":120,"reporting":120},
"name":"Skagit"},
"Skamania":
{"votes":[
{"votes":598,"name":"obama"},
{"votes":554,"name":"clinton"},
{"votes":47,"name":"edwards"},
{"votes":6,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"gravel"},
{"votes":0,"name":"uncommitted-d"}],
"total":1218,"precincts":
{"total":12,"reporting":12},
"name":"Skamania"},
"Clark":
{"votes":[
{"votes":21308,"name":"clinton"},
{"votes":19722,"name":"obama"},
{"votes":893,"name":"edwards"},
{"votes":190,"name":"kucinich"},
{"votes":118,"name":"biden"},
{"votes":117,"name":"richardson"},
{"votes":62,"name":"gravel"},
{"votes":31,"name":"dodd"},
{"votes":4,"name":"uncommitted-d"}],
"total":42445,"precincts":
{"total":396,"reporting":396},
"name":"Clark"},
"Stevens":
{"votes":[
{"votes":1625,"name":"obama"},
{"votes":1486,"name":"clinton"},
{"votes":77,"name":"edwards"},
{"votes":21,"name":"biden"},
{"votes":14,"name":"kucinich"},
{"votes":6,"name":"dodd"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"richardson"},
{"votes":2,"name":"uncommitted-d"}],
"total":3242,"precincts":
{"total":54,"reporting":54},
"name":"Stevens"},
"Lewis":
{"votes":[
{"votes":3557,"name":"clinton"},
{"votes":3468,"name":"obama"},
{"votes":183,"name":"edwards"},
{"votes":32,"name":"kucinich"},
{"votes":30,"name":"biden"},
{"votes":27,"name":"richardson"},
{"votes":25,"name":"gravel"},
{"votes":15,"name":"dodd"},
{"votes":5,"name":"uncommitted-d"}],
"total":7342,"precincts":
{"total":72,"reporting":72},
"name":"Lewis"},
"Walla Walla":
{"votes":[
{"votes":2375,"name":"obama"},
{"votes":2112,"name":"clinton"},
{"votes":131,"name":"edwards"},
{"votes":27,"name":"biden"},
{"votes":16,"name":"kucinich"},
{"votes":8,"name":"richardson"},
{"votes":7,"name":"gravel"},
{"votes":6,"name":"dodd"},
{"votes":0,"name":"uncommitted-d"}],
"total":4682,"precincts":
{"total":56,"reporting":56},
"name":"Walla Walla"},
"Pacific":
{"votes":[
{"votes":2266,"name":"clinton"},
{"votes":1847,"name":"obama"},
{"votes":123,"name":"edwards"},
{"votes":26,"name":"kucinich"},
{"votes":22,"name":"richardson"},
{"votes":20,"name":"biden"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"gravel"},
{"votes":0,"name":"uncommitted-d"}],
"total":4313,"precincts":
{"total":25,"reporting":25},
"name":"Pacific"},
"Garfield":
{"votes":[
{"votes":121,"name":"clinton"},
{"votes":100,"name":"obama"},
{"votes":9,"name":"dodd"},
{"votes":9,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":1,"name":"gravel"},
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"kucinich"}],
"total":244,"precincts":
{"total":3,"reporting":3},
"name":"Garfield"},
"Chelan":
{"votes":[
{"votes":3028,"name":"obama"},
{"votes":2334,"name":"clinton"},
{"votes":77,"name":"edwards"},
{"votes":25,"name":"kucinich"},
{"votes":19,"name":"richardson"},
{"votes":15,"name":"biden"},
{"votes":7,"name":"dodd"},
{"votes":6,"name":"gravel"},
{"votes":1,"name":"uncommitted-d"}],
"total":5512,"precincts":
{"total":71,"reporting":71},
"name":"Chelan"},
"Asotin":
{"votes":[
{"votes":1329,"name":"clinton"},
{"votes":1286,"name":"obama"},
{"votes":73,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"uncommitted-d"}],
"total":2720,"precincts":
{"total":22,"reporting":22},
"name":"Asotin"}}})