GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":83621,"name":"mccain"},
{"votes":11360,"name":"huckabee","delegates":18},
{"votes":5578,"name":"paul"},
{"votes":4866,"name":"romney"},
{"votes":2664,"name":"giuliani"},
{"votes":1333,"name":"keyes"},
{"votes":687,"name":"curry"}],
"name":"West Virginia","precincts":
{"total":1,"reporting":1},
"delegates":18,"date":"05-13"},
"state":"WV","party":"gop","total":110109,"locals":
{"Summers":
{"votes":[
{"votes":412,"name":"mccain"},
{"votes":89,"name":"huckabee"},
{"votes":18,"name":"paul"},
{"votes":14,"name":"romney"},
{"votes":8,"name":"giuliani"},
{"votes":5,"name":"curry"},
{"votes":4,"name":"keyes"}],
"total":550,"precincts":
{"total":15,"reporting":15},
"name":"Summers"},
"Jackson":
{"votes":[
{"votes":2538,"name":"mccain"},
{"votes":349,"name":"huckabee"},
{"votes":177,"name":"paul"},
{"votes":124,"name":"romney"},
{"votes":84,"name":"giuliani"},
{"votes":28,"name":"keyes"},
{"votes":14,"name":"curry"}],
"total":3314,"precincts":
{"total":34,"reporting":34},
"name":"Jackson"},
"Braxton":
{"votes":[
{"votes":541,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":14,"name":"romney"},
{"votes":4,"name":"keyes"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"curry"}],
"total":637,"precincts":
{"total":22,"reporting":18},
"name":"Braxton"},
"Grant":
{"votes":[
{"votes":2097,"name":"mccain"},
{"votes":212,"name":"huckabee"},
{"votes":62,"name":"romney"},
{"votes":48,"name":"giuliani"},
{"votes":40,"name":"curry"},
{"votes":37,"name":"paul"},
{"votes":15,"name":"keyes"}],
"total":2511,"precincts":
{"total":15,"reporting":15},
"name":"Grant"},
"Pendleton":
{"votes":[
{"votes":336,"name":"mccain"},
{"votes":28,"name":"huckabee"},
{"votes":23,"name":"romney"},
{"votes":18,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":7,"name":"curry"},
{"votes":5,"name":"keyes"}],
"total":425,"precincts":
{"total":13,"reporting":13},
"name":"Pendleton"},
"Wyoming":
{"votes":[
{"votes":344,"name":"mccain"},
{"votes":30,"name":"huckabee"},
{"votes":9,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":6,"name":"giuliani"},
{"votes":2,"name":"curry"},
{"votes":1,"name":"keyes"}],
"total":398,"precincts":
{"total":36,"reporting":34},
"name":"Wyoming"},
"Calhoun":
{"votes":[
{"votes":270,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":28,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":11,"name":"giuliani"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"curry"}],
"total":364,"precincts":
{"total":10,"reporting":10},
"name":"Calhoun"},
"Hampshire":
{"votes":[
{"votes":114,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":10,"name":"romney"},
{"votes":8,"name":"paul"},
{"votes":6,"name":"giuliani"},
{"votes":2,"name":"curry"}],
"total":153,"precincts":
{"total":23,"reporting":4},
"name":"Hampshire"},
"Mason":
{"votes":[
{"votes":1775,"name":"mccain"},
{"votes":287,"name":"huckabee"},
{"votes":83,"name":"paul"},
{"votes":81,"name":"romney"},
{"votes":48,"name":"giuliani"},
{"votes":15,"name":"keyes"},
{"votes":14,"name":"curry"}],
"total":2303,"precincts":
{"total":38,"reporting":38},
"name":"Mason"},
"Roane":
{"votes":[
{"votes":1083,"name":"mccain"},
{"votes":151,"name":"huckabee"},
{"votes":66,"name":"paul"},
{"votes":57,"name":"romney"},
{"votes":31,"name":"giuliani"},
{"votes":9,"name":"curry"},
{"votes":5,"name":"keyes"}],
"total":1402,"precincts":
{"total":20,"reporting":20},
"name":"Roane"},
"Wirt":
{"votes":[
{"votes":428,"name":"mccain"},
{"votes":57,"name":"huckabee"},
{"votes":34,"name":"paul"},
{"votes":20,"name":"giuliani"},
{"votes":12,"name":"romney"},
{"votes":6,"name":"curry"},
{"votes":3,"name":"keyes"}],
"total":560,"precincts":
{"total":9,"reporting":9},
"name":"Wirt"},
"Wood":
{"votes":[
{"votes":5766,"name":"mccain"},
{"votes":849,"name":"huckabee"},
{"votes":502,"name":"romney"},
{"votes":458,"name":"paul"},
{"votes":203,"name":"giuliani"},
{"votes":99,"name":"keyes"},
{"votes":40,"name":"curry"}],
"total":7917,"precincts":
{"total":84,"reporting":84},
"name":"Wood"},
"Ohio":
{"votes":[
{"votes":3019,"name":"mccain"},
{"votes":294,"name":"huckabee"},
{"votes":260,"name":"romney"},
{"votes":164,"name":"paul"},
{"votes":89,"name":"giuliani"},
{"votes":71,"name":"keyes"},
{"votes":12,"name":"curry"}],
"total":3909,"precincts":
{"total":39,"reporting":39},
"name":"Ohio"},
"Nicholas":
{"votes":[
{"votes":870,"name":"mccain"},
{"votes":189,"name":"huckabee"},
{"votes":74,"name":"paul"},
{"votes":35,"name":"giuliani"},
{"votes":24,"name":"romney"},
{"votes":18,"name":"curry"},
{"votes":9,"name":"keyes"}],
"total":1219,"precincts":
{"total":28,"reporting":28},
"name":"Nicholas"},
"Putnam":
{"votes":[
{"votes":2496,"name":"mccain"},
{"votes":343,"name":"huckabee"},
{"votes":206,"name":"paul"},
{"votes":155,"name":"romney"},
{"votes":57,"name":"giuliani"},
{"votes":43,"name":"keyes"},
{"votes":14,"name":"curry"}],
"total":3314,"precincts":
{"total":48,"reporting":32},
"name":"Putnam"},
"McDowell":
{"votes":[
{"votes":174,"name":"mccain"},
{"votes":20,"name":"huckabee"},
{"votes":6,"name":"keyes"},
{"votes":6,"name":"giuliani"},
{"votes":5,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":4,"name":"curry"}],
"total":219,"precincts":
{"total":42,"reporting":42},
"name":"McDowell"},
"Greenbrier":
{"votes":[
{"votes":1039,"name":"mccain"},
{"votes":157,"name":"huckabee"},
{"votes":61,"name":"romney"},
{"votes":59,"name":"paul"},
{"votes":35,"name":"giuliani"},
{"votes":11,"name":"keyes"},
{"votes":11,"name":"curry"}],
"total":1373,"precincts":
{"total":36,"reporting":24},
"name":"Greenbrier"},
"Gilmer":
{"votes":[
{"votes":294,"name":"mccain"},
{"votes":58,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"curry"}],
"total":383,"precincts":
{"total":12,"reporting":12},
"name":"Gilmer"},
"Fayette":
{"votes":[
{"votes":1022,"name":"mccain"},
{"votes":126,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":29,"name":"romney"},
{"votes":22,"name":"giuliani"},
{"votes":18,"name":"keyes"},
{"votes":7,"name":"curry"}],
"total":1267,"precincts":
{"total":39,"reporting":30},
"name":"Fayette"},
"Monongalia":
{"votes":[
{"votes":2839,"name":"mccain"},
{"votes":415,"name":"huckabee"},
{"votes":274,"name":"paul"},
{"votes":264,"name":"romney"},
{"votes":141,"name":"giuliani"},
{"votes":60,"name":"keyes"},
{"votes":19,"name":"curry"}],
"total":4012,"precincts":
{"total":72,"reporting":72},
"name":"Monongalia"},
"Tucker":
{"votes":[
{"votes":414,"name":"mccain"},
{"votes":61,"name":"huckabee"},
{"votes":24,"name":"giuliani"},
{"votes":23,"name":"paul"},
{"votes":12,"name":"romney"},
{"votes":6,"name":"keyes"},
{"votes":4,"name":"curry"}],
"total":544,"precincts":
{"total":11,"reporting":11},
"name":"Tucker"},
"Barbour":
{"votes":[
{"votes":1155,"name":"mccain"},
{"votes":177,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":43,"name":"romney"},
{"votes":40,"name":"giuliani"},
{"votes":21,"name":"keyes"},
{"votes":6,"name":"curry"}],
"total":1487,"precincts":
{"total":22,"reporting":22},
"name":"Barbour"},
"Berkeley":
{"votes":[
{"votes":5731,"name":"mccain"},
{"votes":631,"name":"paul"},
{"votes":611,"name":"huckabee"},
{"votes":294,"name":"romney"},
{"votes":144,"name":"giuliani"},
{"votes":95,"name":"keyes"},
{"votes":39,"name":"curry"}],
"total":7545,"precincts":
{"total":66,"reporting":66},
"name":"Berkeley"},
"Brooke":
{"votes":[
{"votes":856,"name":"mccain"},
{"votes":99,"name":"huckabee"},
{"votes":64,"name":"romney"},
{"votes":60,"name":"paul"},
{"votes":32,"name":"giuliani"},
{"votes":14,"name":"keyes"},
{"votes":3,"name":"curry"}],
"total":1128,"precincts":
{"total":27,"reporting":27},
"name":"Brooke"},
"Ritchie":
{"votes":[
{"votes":1411,"name":"mccain"},
{"votes":150,"name":"huckabee"},
{"votes":98,"name":"paul"},
{"votes":81,"name":"romney"},
{"votes":44,"name":"giuliani"},
{"votes":20,"name":"keyes"},
{"votes":12,"name":"curry"}],
"total":1816,"precincts":
{"total":15,"reporting":15},
"name":"Ritchie"},
"Pocahontas":
{"votes":[
{"votes":500,"name":"mccain"},
{"votes":78,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":22,"name":"romney"},
{"votes":10,"name":"giuliani"},
{"votes":10,"name":"curry"},
{"votes":5,"name":"keyes"}],
"total":652,"precincts":
{"total":15,"reporting":15},
"name":"Pocahontas"},
"Wayne":
{"votes":[
{"votes":1568,"name":"mccain"},
{"votes":227,"name":"huckabee"},
{"votes":88,"name":"paul"},
{"votes":82,"name":"romney"},
{"votes":43,"name":"giuliani"},
{"votes":35,"name":"keyes"},
{"votes":9,"name":"curry"}],
"total":2052,"precincts":
{"total":37,"reporting":37},
"name":"Wayne"},
"Lincoln":
{"votes":[
{"votes":545,"name":"mccain"},
{"votes":77,"name":"huckabee"},
{"votes":28,"name":"paul"},
{"votes":16,"name":"giuliani"},
{"votes":14,"name":"romney"},
{"votes":9,"name":"curry"},
{"votes":2,"name":"keyes"}],
"total":691,"precincts":
{"total":35,"reporting":35},
"name":"Lincoln"},
"Mineral":
{"votes":[
{"votes":784,"name":"mccain"},
{"votes":76,"name":"huckabee"},
{"votes":35,"name":"romney"},
{"votes":29,"name":"giuliani"},
{"votes":28,"name":"paul"},
{"votes":14,"name":"keyes"},
{"votes":6,"name":"curry"}],
"total":972,"precincts":
{"total":32,"reporting":1},
"name":"Mineral"},
"Harrison":
{"votes":[
{"votes":3174,"name":"mccain"},
{"votes":434,"name":"huckabee"},
{"votes":202,"name":"romney"},
{"votes":157,"name":"paul"},
{"votes":122,"name":"giuliani"},
{"votes":111,"name":"keyes"},
{"votes":23,"name":"curry"}],
"total":4223,"precincts":
{"total":89,"reporting":89},
"name":"Harrison"},
"Hancock":
{"votes":[
{"votes":1280,"name":"mccain"},
{"votes":173,"name":"huckabee"},
{"votes":100,"name":"romney"},
{"votes":79,"name":"paul"},
{"votes":55,"name":"giuliani"},
{"votes":34,"name":"keyes"},
{"votes":9,"name":"curry"}],
"total":1730,"precincts":
{"total":28,"reporting":28},
"name":"Hancock"},
"Kanawha":
{"votes":[
{"votes":8455,"name":"mccain"},
{"votes":1093,"name":"huckabee"},
{"votes":832,"name":"paul"},
{"votes":604,"name":"romney"},
{"votes":276,"name":"giuliani"},
{"votes":130,"name":"keyes"},
{"votes":91,"name":"curry"}],
"total":11481,"precincts":
{"total":160,"reporting":160},
"name":"Kanawha"},
"Pleasants":
{"votes":[
{"votes":413,"name":"mccain"},
{"votes":61,"name":"huckabee"},
{"votes":36,"name":"paul"},
{"votes":26,"name":"romney"},
{"votes":12,"name":"giuliani"},
{"votes":5,"name":"keyes"},
{"votes":1,"name":"curry"}],
"total":554,"precincts":
{"total":11,"reporting":11},
"name":"Pleasants"},
"Raleigh":
{"votes":[
{"votes":2774,"name":"mccain"},
{"votes":462,"name":"huckabee"},
{"votes":116,"name":"paul"},
{"votes":105,"name":"romney"},
{"votes":44,"name":"giuliani"},
{"votes":23,"name":"keyes"},
{"votes":12,"name":"curry"}],
"total":3536,"precincts":
{"total":63,"reporting":63},
"name":"Raleigh"},
"Morgan":
{"votes":[
{"votes":1767,"name":"mccain"},
{"votes":239,"name":"huckabee"},
{"votes":118,"name":"paul"},
{"votes":84,"name":"romney"},
{"votes":34,"name":"giuliani"},
{"votes":18,"name":"keyes"},
{"votes":9,"name":"curry"}],
"total":2269,"precincts":
{"total":13,"reporting":13},
"name":"Morgan"},
"Clay":
{"votes":[
{"votes":309,"name":"mccain"},
{"votes":46,"name":"huckabee"},
{"votes":11,"name":"keyes"},
{"votes":9,"name":"romney"},
{"votes":7,"name":"giuliani"},
{"votes":7,"name":"paul"},
{"votes":5,"name":"curry"}],
"total":394,"precincts":
{"total":13,"reporting":13},
"name":"Clay"},
"Webster":
{"votes":[
{"votes":130,"name":"mccain"},
{"votes":21,"name":"huckabee"},
{"votes":8,"name":"giuliani"},
{"votes":8,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":2,"name":"curry"},
{"votes":1,"name":"keyes"}],
"total":176,"precincts":
{"total":13,"reporting":13},
"name":"Webster"},
"Wetzel":
{"votes":[
{"votes":696,"name":"mccain"},
{"votes":94,"name":"huckabee"},
{"votes":47,"name":"romney"},
{"votes":22,"name":"paul"},
{"votes":15,"name":"giuliani"},
{"votes":12,"name":"keyes"},
{"votes":1,"name":"curry"}],
"total":887,"precincts":
{"total":22,"reporting":22},
"name":"Wetzel"},
"Upshur":
{"votes":[
{"votes":2626,"name":"mccain"},
{"votes":413,"name":"huckabee"},
{"votes":100,"name":"romney"},
{"votes":71,"name":"giuliani"},
{"votes":71,"name":"paul"},
{"votes":32,"name":"curry"},
{"votes":28,"name":"keyes"}],
"total":3341,"precincts":
{"total":29,"reporting":29},
"name":"Upshur"},
"Taylor":
{"votes":[
{"votes":498,"name":"mccain"},
{"votes":77,"name":"huckabee"},
{"votes":38,"name":"romney"},
{"votes":20,"name":"paul"},
{"votes":16,"name":"giuliani"},
{"votes":12,"name":"keyes"},
{"votes":4,"name":"curry"}],
"total":665,"precincts":
{"total":18,"reporting":11},
"name":"Taylor"},
"Lewis":
{"votes":[
{"votes":954,"name":"mccain"},
{"votes":104,"name":"huckabee"},
{"votes":49,"name":"giuliani"},
{"votes":43,"name":"romney"},
{"votes":33,"name":"paul"},
{"votes":12,"name":"keyes"},
{"votes":8,"name":"curry"}],
"total":1203,"precincts":
{"total":24,"reporting":23},
"name":"Lewis"},
"Marshall":
{"votes":[
{"votes":1078,"name":"mccain"},
{"votes":147,"name":"huckabee"},
{"votes":65,"name":"romney"},
{"votes":55,"name":"paul"},
{"votes":47,"name":"giuliani"},
{"votes":11,"name":"keyes"},
{"votes":8,"name":"curry"}],
"total":1411,"precincts":
{"total":45,"reporting":30},
"name":"Marshall"},
"Mingo":
{"votes":[
{"votes":296,"name":"mccain"},
{"votes":41,"name":"huckabee"},
{"votes":14,"name":"romney"},
{"votes":9,"name":"giuliani"},
{"votes":5,"name":"paul"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"curry"}],
"total":372,"precincts":
{"total":39,"reporting":39},
"name":"Mingo"},
"Cabell":
{"votes":[
{"votes":4323,"name":"mccain"},
{"votes":550,"name":"huckabee"},
{"votes":318,"name":"paul"},
{"votes":304,"name":"romney"},
{"votes":143,"name":"giuliani"},
{"votes":57,"name":"keyes"},
{"votes":27,"name":"curry"}],
"total":5722,"precincts":
{"total":71,"reporting":71},
"name":"Cabell"},
"Tyler":
{"votes":[
{"votes":1202,"name":"mccain"},
{"votes":177,"name":"huckabee"},
{"votes":65,"name":"paul"},
{"votes":60,"name":"romney"},
{"votes":41,"name":"giuliani"},
{"votes":25,"name":"keyes"},
{"votes":19,"name":"curry"}],
"total":1589,"precincts":
{"total":12,"reporting":12},
"name":"Tyler"},
"Hardy":
{"votes":[
{"votes":543,"name":"mccain"},
{"votes":71,"name":"huckabee"},
{"votes":20,"name":"romney"},
{"votes":13,"name":"giuliani"},
{"votes":12,"name":"paul"},
{"votes":7,"name":"curry"},
{"votes":6,"name":"keyes"}],
"total":672,"precincts":
{"total":18,"reporting":18},
"name":"Hardy"},
"Logan":
{"votes":[
{"votes":371,"name":"mccain"},
{"votes":39,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":14,"name":"giuliani"},
{"votes":10,"name":"romney"},
{"votes":8,"name":"keyes"},
{"votes":4,"name":"curry"}],
"total":463,"precincts":
{"total":35,"reporting":35},
"name":"Logan"},
"Jefferson":
{"votes":[
{"votes":1658,"name":"mccain"},
{"votes":196,"name":"paul"},
{"votes":171,"name":"huckabee"},
{"votes":115,"name":"romney"},
{"votes":42,"name":"giuliani"},
{"votes":30,"name":"keyes"},
{"votes":7,"name":"curry"}],
"total":2219,"precincts":
{"total":31,"reporting":31},
"name":"Jefferson"},
"Marion":
{"votes":[
{"votes":2418,"name":"mccain"},
{"votes":346,"name":"huckabee"},
{"votes":158,"name":"romney"},
{"votes":136,"name":"giuliani"},
{"votes":125,"name":"paul"},
{"votes":49,"name":"keyes"},
{"votes":17,"name":"curry"}],
"total":3249,"precincts":
{"total":76,"reporting":76},
"name":"Marion"},
"Doddridge":
{"votes":[
{"votes":1133,"name":"mccain"},
{"votes":134,"name":"huckabee"},
{"votes":70,"name":"paul"},
{"votes":60,"name":"romney"},
{"votes":28,"name":"giuliani"},
{"votes":15,"name":"keyes"},
{"votes":12,"name":"curry"}],
"total":1452,"precincts":
{"total":12,"reporting":12},
"name":"Doddridge"},
"Boone":
{"votes":[
{"votes":432,"name":"mccain"},
{"votes":53,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":33,"name":"romney"},
{"votes":13,"name":"giuliani"},
{"votes":2,"name":"curry"},
{"votes":1,"name":"keyes"}],
"total":574,"precincts":
{"total":37,"reporting":37},
"name":"Boone"},
"Mercer":
{"votes":[
{"votes":1740,"name":"mccain"},
{"votes":274,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":55,"name":"romney"},
{"votes":39,"name":"keyes"},
{"votes":37,"name":"giuliani"},
{"votes":7,"name":"curry"}],
"total":2220,"precincts":
{"total":61,"reporting":50},
"name":"Mercer"},
"Randolph":
{"votes":[
{"votes":1195,"name":"mccain"},
{"votes":150,"name":"huckabee"},
{"votes":69,"name":"romney"},
{"votes":58,"name":"paul"},
{"votes":36,"name":"giuliani"},
{"votes":7,"name":"curry"},
{"votes":6,"name":"keyes"}],
"total":1521,"precincts":
{"total":27,"reporting":27},
"name":"Randolph"},
"Preston":
{"votes":[
{"votes":2754,"name":"mccain"},
{"votes":541,"name":"huckabee"},
{"votes":147,"name":"paul"},
{"votes":132,"name":"giuliani"},
{"votes":131,"name":"romney"},
{"votes":63,"name":"keyes"},
{"votes":36,"name":"curry"}],
"total":3804,"precincts":
{"total":35,"reporting":35},
"name":"Preston"},
"Monroe":
{"votes":[
{"votes":981,"name":"mccain"},
{"votes":138,"name":"huckabee"},
{"votes":72,"name":"paul"},
{"votes":39,"name":"romney"},
{"votes":16,"name":"giuliani"},
{"votes":10,"name":"keyes"},
{"votes":9,"name":"curry"}],
"total":1265,"precincts":
{"total":17,"reporting":17},
"name":"Monroe"}}})