GoogleElectionMap.votesReady({"status":"ok","totals":
{"name":"Wyoming","precincts":
{"total":12,"reporting":12},
"votes":[
{"votes":8,"name":"romney","delegates":8},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"delegates":12,"date":"01-05","type":"caucus"},
"state":"WY","party":"gop","total":12,"locals":
{"Sublette":
{"votes":[],
"total":0,"name":"Sublette"},
"Albany":
{"votes":[],
"total":0,"name":"Albany"},
"Converse":
{"votes":[],
"total":0,"name":"Converse"},
"Natrona":
{"votes":[],
"total":0,"name":"Natrona"},
"Park":
{"votes":[],
"total":0,"name":"Park"},
"Uinta-Lincoln":
{"votes":[
{"votes":1,"name":"romney"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Uinta-Lincoln"},
"Lincoln":
{"votes":[],
"total":0,"name":"Lincoln"},
"Laramie":
{"votes":[
{"votes":1,"name":"romney"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Laramie"},
"Converse-Niobrara":
{"votes":[
{"votes":1,"name":"romney"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Converse-Niobrara"},
"Teton":
{"votes":[],
"total":0,"name":"Teton"},
"Washakie":
{"votes":[],
"total":0,"name":"Washakie"},
"Hot Springs-Washakie":
{"votes":[
{"votes":1,"name":"thompson"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Hot Springs-Washakie"},
"Fremont":
{"votes":[],
"total":0,"name":"Fremont"},
"Hot Springs":
{"votes":[],
"total":0,"name":"Hot Springs"},
"Carbon":
{"votes":[],
"total":0,"name":"Carbon"},
"Platte":
{"votes":[],
"total":0,"name":"Platte"},
"Sheridan":
{"votes":[],
"total":0,"name":"Sheridan"},
"Sheridan-Big Horn":
{"votes":[
{"votes":1,"name":"hunter"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Sheridan-Big Horn"},
"Johnson":
{"votes":[],
"total":0,"name":"Johnson"},
"Fremont-Park":
{"votes":[
{"votes":1,"name":"romney"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Fremont-Park"},
"Big Horn":
{"votes":[],
"total":0,"name":"Big Horn"},
"Goshen-Platte":
{"votes":[
{"votes":1,"name":"thompson"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Goshen-Platte"},
"Sweetwater-Carbon":
{"votes":[
{"votes":1,"name":"romney"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Sweetwater-Carbon"},
"Campbell-Johnson":
{"votes":[
{"votes":1,"name":"romney"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Campbell-Johnson"},
"Goshen":
{"votes":[],
"total":0,"name":"Goshen"},
"Crook-Weston":
{"votes":[
{"votes":1,"name":"thompson"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Crook-Weston"},
"Sweetwater":
{"votes":[],
"total":0,"name":"Sweetwater"},
"Weston":
{"votes":[],
"total":0,"name":"Weston"},
"Crook":
{"votes":[],
"total":0,"name":"Crook"},
"Uinta":
{"votes":[],
"total":0,"name":"Uinta"},
"Albany-Natrona":
{"votes":[
{"votes":1,"name":"romney"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Albany-Natrona"},
"Campbell":
{"votes":[],
"total":0,"name":"Campbell"},
"Teton-Sublette":
{"votes":[
{"votes":1,"name":"romney"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Teton-Sublette"},
"Niobrara":
{"votes":[],
"total":0,"name":"Niobrara"}}})