GoogleElectionMap.votesReady({"status":"ok","totals":
{"date":"01-05","precincts":
{"total":12,"reporting":12},
"votes":[
{"votes":8,"name":"romney"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"type":"caucus","name":"Wyoming"},
"state":"WY","party":"gop","total":12,"locals":
{"Crook-Weston":
{"votes":[
{"votes":1,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Crook-Weston"},
"Fremont-Park":
{"votes":[
{"votes":1,"name":"romney"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Fremont-Park"},
"Uinta-Lincoln":
{"votes":[
{"votes":1,"name":"romney"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Uinta-Lincoln"},
"Hot Springs-Washakie":
{"votes":[
{"votes":1,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Hot Springs-Washakie"},
"Laramie":
{"votes":[
{"votes":1,"name":"romney"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Laramie"},
"Goshen-Platte":
{"votes":[
{"votes":1,"name":"thompson"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Goshen-Platte"},
"Campbell-Johnson":
{"votes":[
{"votes":1,"name":"romney"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Campbell-Johnson"},
"Sheridan-Big Horn":
{"votes":[
{"votes":1,"name":"hunter"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Sheridan-Big Horn"},
"Albany-Natrona":
{"votes":[
{"votes":1,"name":"romney"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Albany-Natrona"},
"Sweetwater-Carbon":
{"votes":[
{"votes":1,"name":"romney"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Sweetwater-Carbon"},
"Converse-Niobrara":
{"votes":[
{"votes":1,"name":"romney"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Converse-Niobrara"},
"Teton-Sublette":
{"votes":[
{"votes":1,"name":"romney"},
{"votes":0,"name":"hunter"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"tancredo"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":1,"precincts":
{"total":1,"reporting":1},
"name":"Teton-Sublette"}}})