GoogleElectionMap.votesReady({"status":"ok","totals":
{"date":"02-05","votes":[
{"votes":130541,"name":"huckabee"},
{"votes":44091,"name":"mccain"},
{"votes":29359,"name":"romney"},
{"votes":10401,"name":"paul"},
{"votes":933,"name":"uncommitted-r"},
{"votes":625,"name":"giuliani"},
{"votes":600,"name":"thompson"}],
"precincts":
{"total":2480,"reporting":2402},
"name":"Arkansas"},
"state":"AR","party":"gop","total":216550,"locals":
{"Saline":
{"votes":[
{"votes":6746,"name":"huckabee"},
{"votes":2710,"name":"mccain"},
{"votes":1789,"name":"romney"},
{"votes":528,"name":"paul"},
{"votes":58,"name":"uncommitted-r"},
{"votes":35,"name":"giuliani"},
{"votes":34,"name":"thompson"}],
"total":11900,"precincts":
{"total":37,"reporting":37},
"name":"Saline"},
"Clark":
{"votes":[
{"votes":1044,"name":"huckabee"},
{"votes":286,"name":"mccain"},
{"votes":88,"name":"romney"},
{"votes":33,"name":"paul"},
{"votes":10,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"giuliani"}],
"total":1466,"precincts":
{"total":21,"reporting":21},
"name":"Clark"},
"Mississippi":
{"votes":[
{"votes":1311,"name":"huckabee"},
{"votes":329,"name":"mccain"},
{"votes":199,"name":"romney"},
{"votes":25,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"thompson"}],
"total":1873,"precincts":
{"total":71,"reporting":71},
"name":"Mississippi"},
"Perry":
{"votes":[
{"votes":569,"name":"huckabee"},
{"votes":185,"name":"mccain"},
{"votes":107,"name":"romney"},
{"votes":62,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"giuliani"}],
"total":930,"precincts":
{"total":19,"reporting":19},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":612,"name":"huckabee"},
{"votes":200,"name":"mccain"},
{"votes":51,"name":"romney"},
{"votes":17,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"giuliani"}],
"total":894,"precincts":
{"total":19,"reporting":19},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":566,"name":"huckabee"},
{"votes":165,"name":"mccain"},
{"votes":59,"name":"romney"},
{"votes":20,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"uncommitted-r"},
{"votes":4,"name":"giuliani"}],
"total":825,"precincts":
{"total":21,"reporting":21},
"name":"Howard"},
"Union":
{"votes":[
{"votes":2181,"name":"huckabee"},
{"votes":643,"name":"mccain"},
{"votes":412,"name":"romney"},
{"votes":90,"name":"paul"},
{"votes":10,"name":"uncommitted-r"},
{"votes":7,"name":"thompson"},
{"votes":7,"name":"giuliani"}],
"total":3350,"precincts":
{"total":30,"reporting":30},
"name":"Union"},
"Sevier":
{"votes":[
{"votes":525,"name":"huckabee"},
{"votes":181,"name":"mccain"},
{"votes":98,"name":"romney"},
{"votes":18,"name":"paul"},
{"votes":3,"name":"uncommitted-r"},
{"votes":3,"name":"giuliani"},
{"votes":0,"name":"thompson"}],
"total":828,"precincts":
{"total":19,"reporting":19},
"name":"Sevier"},
"Calhoun":
{"votes":[
{"votes":321,"name":"huckabee"},
{"votes":65,"name":"mccain"},
{"votes":30,"name":"romney"},
{"votes":22,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"uncommitted-r"}],
"total":445,"precincts":
{"total":12,"reporting":12},
"name":"Calhoun"},
"Montgomery":
{"votes":[
{"votes":570,"name":"huckabee"},
{"votes":185,"name":"mccain"},
{"votes":93,"name":"romney"},
{"votes":63,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"thompson"}],
"total":919,"precincts":
{"total":18,"reporting":18},
"name":"Montgomery"},
"Pulaski":
{"votes":[
{"votes":14766,"name":"huckabee"},
{"votes":7176,"name":"mccain"},
{"votes":4781,"name":"romney"},
{"votes":1579,"name":"paul"},
{"votes":207,"name":"uncommitted-r"},
{"votes":83,"name":"thompson"},
{"votes":83,"name":"giuliani"}],
"total":28675,"precincts":
{"total":133,"reporting":133},
"name":"Pulaski"},
"Phillips":
{"votes":[
{"votes":643,"name":"huckabee"},
{"votes":225,"name":"mccain"},
{"votes":53,"name":"romney"},
{"votes":19,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"thompson"}],
"total":950,"precincts":
{"total":20,"reporting":20},
"name":"Phillips"},
"Jefferson":
{"votes":[
{"votes":2397,"name":"huckabee"},
{"votes":658,"name":"mccain"},
{"votes":365,"name":"romney"},
{"votes":127,"name":"paul"},
{"votes":16,"name":"uncommitted-r"},
{"votes":10,"name":"thompson"},
{"votes":7,"name":"giuliani"}],
"total":3580,"precincts":
{"total":202,"reporting":202},
"name":"Jefferson"},
"Crittenden":
{"votes":[
{"votes":1260,"name":"huckabee"},
{"votes":326,"name":"mccain"},
{"votes":271,"name":"romney"},
{"votes":35,"name":"paul"},
{"votes":12,"name":"thompson"},
{"votes":7,"name":"uncommitted-r"},
{"votes":6,"name":"giuliani"}],
"total":1917,"precincts":
{"total":45,"reporting":45},
"name":"Crittenden"},
"Cleburne":
{"votes":[
{"votes":2134,"name":"huckabee"},
{"votes":635,"name":"mccain"},
{"votes":435,"name":"romney"},
{"votes":170,"name":"paul"},
{"votes":16,"name":"uncommitted-r"},
{"votes":9,"name":"giuliani"},
{"votes":5,"name":"thompson"}],
"total":3404,"precincts":
{"total":36,"reporting":36},
"name":"Cleburne"},
"Crawford":
{"votes":[
{"votes":3579,"name":"huckabee"},
{"votes":1014,"name":"mccain"},
{"votes":716,"name":"romney"},
{"votes":233,"name":"paul"},
{"votes":25,"name":"giuliani"},
{"votes":15,"name":"uncommitted-r"},
{"votes":14,"name":"thompson"}],
"total":5596,"precincts":
{"total":44,"reporting":44},
"name":"Crawford"},
"Faulkner":
{"votes":[
{"votes":4752,"name":"huckabee"},
{"votes":1523,"name":"mccain"},
{"votes":1010,"name":"romney"},
{"votes":408,"name":"paul"},
{"votes":26,"name":"thompson"},
{"votes":25,"name":"uncommitted-r"},
{"votes":16,"name":"giuliani"}],
"total":7760,"precincts":
{"total":48,"reporting":48},
"name":"Faulkner"},
"Independence":
{"votes":[
{"votes":1849,"name":"huckabee"},
{"votes":504,"name":"mccain"},
{"votes":243,"name":"romney"},
{"votes":86,"name":"paul"},
{"votes":10,"name":"uncommitted-r"},
{"votes":6,"name":"giuliani"},
{"votes":2,"name":"thompson"}],
"total":2700,"precincts":
{"total":31,"reporting":31},
"name":"Independence"},
"Polk":
{"votes":[
{"votes":1307,"name":"huckabee"},
{"votes":374,"name":"mccain"},
{"votes":156,"name":"romney"},
{"votes":123,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":13,"name":"giuliani"},
{"votes":10,"name":"uncommitted-r"}],
"total":1998,"precincts":
{"total":19,"reporting":19},
"name":"Polk"},
"Columbia":
{"votes":[
{"votes":1280,"name":"huckabee"},
{"votes":429,"name":"mccain"},
{"votes":151,"name":"romney"},
{"votes":58,"name":"paul"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":3,"name":"uncommitted-r"}],
"total":1933,"precincts":
{"total":19,"reporting":19},
"name":"Columbia"},
"Lee":
{"votes":[
{"votes":273,"name":"huckabee"},
{"votes":89,"name":"mccain"},
{"votes":26,"name":"romney"},
{"votes":6,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"giuliani"}],
"total":399,"precincts":
{"total":15,"reporting":15},
"name":"Lee"},
"Garland":
{"votes":[
{"votes":5791,"name":"huckabee"},
{"votes":1741,"name":"mccain"},
{"votes":1571,"name":"romney"},
{"votes":462,"name":"paul"},
{"votes":65,"name":"uncommitted-r"},
{"votes":31,"name":"giuliani"},
{"votes":17,"name":"thompson"}],
"total":9678,"precincts":
{"total":41,"reporting":41},
"name":"Garland"},
"Lawrence":
{"votes":[
{"votes":602,"name":"huckabee"},
{"votes":166,"name":"mccain"},
{"votes":89,"name":"romney"},
{"votes":39,"name":"paul"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"uncommitted-r"}],
"total":909,"precincts":
{"total":28,"reporting":28},
"name":"Lawrence"},
"Saint Francis":
{"votes":[
{"votes":844,"name":"huckabee"},
{"votes":304,"name":"mccain"},
{"votes":132,"name":"romney"},
{"votes":16,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"uncommitted-r"}],
"total":1305,"precincts":
{"total":19,"reporting":19},
"name":"Saint Francis"},
"Dallas":
{"votes":[
{"votes":421,"name":"huckabee"},
{"votes":122,"name":"mccain"},
{"votes":37,"name":"romney"},
{"votes":22,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"giuliani"}],
"total":608,"precincts":
{"total":22,"reporting":22},
"name":"Dallas"},
"Van Buren":
{"votes":[
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Van Buren"},
"Drew":
{"votes":[
{"votes":836,"name":"huckabee"},
{"votes":269,"name":"mccain"},
{"votes":93,"name":"romney"},
{"votes":31,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":5,"name":"thompson"},
{"votes":0,"name":"giuliani"}],
"total":1239,"precincts":
{"total":19,"reporting":19},
"name":"Drew"},
"Craighead":
{"votes":[
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Craighead"},
"Scott":
{"votes":[
{"votes":674,"name":"huckabee"},
{"votes":201,"name":"mccain"},
{"votes":85,"name":"romney"},
{"votes":60,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"giuliani"}],
"total":1032,"precincts":
{"total":28,"reporting":28},
"name":"Scott"},
"Grant":
{"votes":[
{"votes":1248,"name":"huckabee"},
{"votes":349,"name":"mccain"},
{"votes":141,"name":"romney"},
{"votes":99,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"thompson"}],
"total":1853,"precincts":
{"total":22,"reporting":22},
"name":"Grant"},
"Izard":
{"votes":[
{"votes":627,"name":"huckabee"},
{"votes":226,"name":"mccain"},
{"votes":175,"name":"romney"},
{"votes":62,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":6,"name":"uncommitted-r"},
{"votes":3,"name":"giuliani"}],
"total":1107,"precincts":
{"total":19,"reporting":19},
"name":"Izard"},
"Little River":
{"votes":[
{"votes":696,"name":"huckabee"},
{"votes":173,"name":"mccain"},
{"votes":94,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"giuliani"}],
"total":985,"precincts":
{"total":22,"reporting":22},
"name":"Little River"},
"Pike":
{"votes":[
{"votes":639,"name":"huckabee"},
{"votes":122,"name":"mccain"},
{"votes":35,"name":"romney"},
{"votes":28,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"giuliani"}],
"total":833,"precincts":
{"total":15,"reporting":15},
"name":"Pike"},
"Stone":
{"votes":[
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Stone"},
"Ashley":
{"votes":[
{"votes":1163,"name":"huckabee"},
{"votes":298,"name":"mccain"},
{"votes":100,"name":"romney"},
{"votes":23,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"thompson"}],
"total":1596,"precincts":
{"total":24,"reporting":24},
"name":"Ashley"},
"White":
{"votes":[
{"votes":4083,"name":"huckabee"},
{"votes":1066,"name":"mccain"},
{"votes":626,"name":"romney"},
{"votes":202,"name":"paul"},
{"votes":17,"name":"uncommitted-r"},
{"votes":16,"name":"thompson"},
{"votes":11,"name":"giuliani"}],
"total":6021,"precincts":
{"total":91,"reporting":91},
"name":"White"},
"Johnson":
{"votes":[
{"votes":1187,"name":"huckabee"},
{"votes":344,"name":"mccain"},
{"votes":224,"name":"romney"},
{"votes":81,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"giuliani"}],
"total":1854,"precincts":
{"total":24,"reporting":24},
"name":"Johnson"},
"Carroll":
{"votes":[
{"votes":1598,"name":"huckabee"},
{"votes":600,"name":"mccain"},
{"votes":258,"name":"romney"},
{"votes":205,"name":"paul"},
{"votes":11,"name":"uncommitted-r"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"giuliani"}],
"total":2681,"precincts":
{"total":31,"reporting":31},
"name":"Carroll"},
"Hot Spring":
{"votes":[
{"votes":1429,"name":"huckabee"},
{"votes":436,"name":"mccain"},
{"votes":216,"name":"romney"},
{"votes":112,"name":"paul"},
{"votes":14,"name":"uncommitted-r"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"giuliani"}],
"total":2216,"precincts":
{"total":30,"reporting":30},
"name":"Hot Spring"},
"Benton":
{"votes":[
{"votes":11305,"name":"huckabee"},
{"votes":4192,"name":"mccain"},
{"votes":3583,"name":"romney"},
{"votes":1244,"name":"paul"},
{"votes":69,"name":"giuliani"},
{"votes":51,"name":"uncommitted-r"},
{"votes":31,"name":"thompson"}],
"total":20475,"precincts":
{"total":83,"reporting":83},
"name":"Benton"},
"Cross":
{"votes":[
{"votes":916,"name":"huckabee"},
{"votes":222,"name":"mccain"},
{"votes":96,"name":"romney"},
{"votes":17,"name":"paul"},
{"votes":9,"name":"thompson"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"uncommitted-r"}],
"total":1265,"precincts":
{"total":8,"reporting":8},
"name":"Cross"},
"Greene":
{"votes":[
{"votes":1868,"name":"huckabee"},
{"votes":329,"name":"mccain"},
{"votes":246,"name":"romney"},
{"votes":59,"name":"paul"},
{"votes":11,"name":"uncommitted-r"},
{"votes":8,"name":"thompson"},
{"votes":4,"name":"giuliani"}],
"total":2525,"precincts":
{"total":34,"reporting":34},
"name":"Greene"},
"Searcy":
{"votes":[
{"votes":417,"name":"huckabee"},
{"votes":188,"name":"mccain"},
{"votes":132,"name":"paul"},
{"votes":77,"name":"romney"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"uncommitted-r"},
{"votes":0,"name":"giuliani"}],
"total":817,"precincts":
{"total":17,"reporting":17},
"name":"Searcy"},
"Lafayette":
{"votes":[
{"votes":359,"name":"huckabee"},
{"votes":75,"name":"mccain"},
{"votes":44,"name":"romney"},
{"votes":23,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"giuliani"}],
"total":507,"precincts":
{"total":22,"reporting":22},
"name":"Lafayette"},
"Franklin":
{"votes":[
{"votes":911,"name":"huckabee"},
{"votes":318,"name":"mccain"},
{"votes":180,"name":"romney"},
{"votes":71,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":2,"name":"uncommitted-r"}],
"total":1495,"precincts":
{"total":31,"reporting":31},
"name":"Franklin"},
"Boone":
{"votes":[
{"votes":2432,"name":"huckabee"},
{"votes":772,"name":"mccain"},
{"votes":342,"name":"romney"},
{"votes":237,"name":"paul"},
{"votes":12,"name":"thompson"},
{"votes":8,"name":"giuliani"},
{"votes":0,"name":"uncommitted-r"}],
"total":3803,"precincts":
{"total":21,"reporting":21},
"name":"Boone"},
"Clay":
{"votes":[
{"votes":798,"name":"huckabee"},
{"votes":147,"name":"mccain"},
{"votes":92,"name":"romney"},
{"votes":33,"name":"paul"},
{"votes":3,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"giuliani"}],
"total":1078,"precincts":
{"total":17,"reporting":17},
"name":"Clay"},
"Poinsett":
{"votes":[
{"votes":959,"name":"huckabee"},
{"votes":210,"name":"mccain"},
{"votes":141,"name":"romney"},
{"votes":19,"name":"paul"},
{"votes":7,"name":"uncommitted-r"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"thompson"}],
"total":1340,"precincts":
{"total":10,"reporting":10},
"name":"Poinsett"},
"Ouachita":
{"votes":[
{"votes":1419,"name":"huckabee"},
{"votes":453,"name":"mccain"},
{"votes":188,"name":"romney"},
{"votes":92,"name":"paul"},
{"votes":16,"name":"uncommitted-r"},
{"votes":9,"name":"giuliani"},
{"votes":8,"name":"thompson"}],
"total":2185,"precincts":
{"total":22,"reporting":22},
"name":"Ouachita"},
"Yell":
{"votes":[
{"votes":682,"name":"huckabee"},
{"votes":186,"name":"mccain"},
{"votes":130,"name":"romney"},
{"votes":75,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":6,"name":"giuliani"},
{"votes":3,"name":"thompson"}],
"total":1091,"precincts":
{"total":27,"reporting":27},
"name":"Yell"},
"Sebastian":
{"votes":[
{"votes":5858,"name":"huckabee"},
{"votes":2263,"name":"mccain"},
{"votes":1624,"name":"romney"},
{"votes":501,"name":"paul"},
{"votes":42,"name":"uncommitted-r"},
{"votes":41,"name":"giuliani"},
{"votes":33,"name":"thompson"}],
"total":10362,"precincts":
{"total":52,"reporting":52},
"name":"Sebastian"},
"Arkansas":
{"votes":[
{"votes":844,"name":"huckabee"},
{"votes":296,"name":"mccain"},
{"votes":83,"name":"romney"},
{"votes":40,"name":"paul"},
{"votes":17,"name":"thompson"},
{"votes":6,"name":"uncommitted-r"},
{"votes":5,"name":"giuliani"}],
"total":1291,"precincts":
{"total":17,"reporting":17},
"name":"Arkansas"},
"Fulton":
{"votes":[
{"votes":526,"name":"huckabee"},
{"votes":178,"name":"mccain"},
{"votes":117,"name":"romney"},
{"votes":62,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"uncommitted-r"},
{"votes":2,"name":"giuliani"}],
"total":896,"precincts":
{"total":14,"reporting":14},
"name":"Fulton"},
"Baxter":
{"votes":[
{"votes":2155,"name":"huckabee"},
{"votes":1261,"name":"romney"},
{"votes":1184,"name":"mccain"},
{"votes":234,"name":"paul"},
{"votes":24,"name":"uncommitted-r"},
{"votes":21,"name":"thompson"},
{"votes":14,"name":"giuliani"}],
"total":4893,"precincts":
{"total":26,"reporting":26},
"name":"Baxter"},
"Woodruff":
{"votes":[
{"votes":191,"name":"huckabee"},
{"votes":70,"name":"mccain"},
{"votes":17,"name":"romney"},
{"votes":12,"name":"paul"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"giuliani"},
{"votes":0,"name":"thompson"}],
"total":293,"precincts":
{"total":20,"reporting":20},
"name":"Woodruff"},
"Madison":
{"votes":[
{"votes":1110,"name":"huckabee"},
{"votes":281,"name":"mccain"},
{"votes":181,"name":"romney"},
{"votes":151,"name":"paul"},
{"votes":12,"name":"uncommitted-r"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"giuliani"}],
"total":1738,"precincts":
{"total":28,"reporting":28},
"name":"Madison"},
"Lincoln":
{"votes":[
{"votes":450,"name":"huckabee"},
{"votes":109,"name":"mccain"},
{"votes":29,"name":"romney"},
{"votes":19,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"giuliani"}],
"total":616,"precincts":
{"total":28,"reporting":28},
"name":"Lincoln"},
"Lonoke":
{"votes":[
{"votes":3004,"name":"huckabee"},
{"votes":1109,"name":"mccain"},
{"votes":873,"name":"romney"},
{"votes":269,"name":"paul"},
{"votes":21,"name":"uncommitted-r"},
{"votes":18,"name":"thompson"},
{"votes":13,"name":"giuliani"}],
"total":5307,"precincts":
{"total":56,"reporting":56},
"name":"Lonoke"},
"Hempstead":
{"votes":[
{"votes":994,"name":"huckabee"},
{"votes":179,"name":"mccain"},
{"votes":96,"name":"romney"},
{"votes":17,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":2,"name":"thompson"},
{"votes":2,"name":"giuliani"}],
"total":1294,"precincts":
{"total":28,"reporting":28},
"name":"Hempstead"},
"Pope":
{"votes":[
{"votes":3163,"name":"huckabee"},
{"votes":872,"name":"mccain"},
{"votes":560,"name":"romney"},
{"votes":212,"name":"paul"},
{"votes":12,"name":"giuliani"},
{"votes":11,"name":"uncommitted-r"},
{"votes":5,"name":"thompson"}],
"total":4835,"precincts":
{"total":56,"reporting":56},
"name":"Pope"},
"Conway":
{"votes":[
{"votes":819,"name":"huckabee"},
{"votes":175,"name":"mccain"},
{"votes":98,"name":"romney"},
{"votes":59,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":5,"name":"giuliani"},
{"votes":3,"name":"thompson"}],
"total":1164,"precincts":
{"total":32,"reporting":32},
"name":"Conway"},
"Miller":
{"votes":[
{"votes":2794,"name":"huckabee"},
{"votes":412,"name":"mccain"},
{"votes":358,"name":"romney"},
{"votes":77,"name":"paul"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"uncommitted-r"},
{"votes":4,"name":"thompson"}],
"total":3657,"precincts":
{"total":27,"reporting":27},
"name":"Miller"},
"Newton":
{"votes":[
{"votes":551,"name":"huckabee"},
{"votes":191,"name":"mccain"},
{"votes":78,"name":"romney"},
{"votes":70,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"giuliani"}],
"total":895,"precincts":
{"total":22,"reporting":22},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":8724,"name":"huckabee"},
{"votes":3153,"name":"mccain"},
{"votes":2666,"name":"romney"},
{"votes":1072,"name":"paul"},
{"votes":62,"name":"uncommitted-r"},
{"votes":49,"name":"giuliani"},
{"votes":45,"name":"thompson"}],
"total":15771,"precincts":
{"total":122,"reporting":122},
"name":"Washington"},
"Desha":
{"votes":[
{"votes":370,"name":"huckabee"},
{"votes":99,"name":"mccain"},
{"votes":29,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":3,"name":"uncommitted-r"},
{"votes":3,"name":"thompson"},
{"votes":0,"name":"giuliani"}],
"total":517,"precincts":
{"total":22,"reporting":22},
"name":"Desha"},
"Bradley":
{"votes":[
{"votes":556,"name":"huckabee"},
{"votes":150,"name":"mccain"},
{"votes":60,"name":"romney"},
{"votes":9,"name":"paul"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"giuliani"},
{"votes":0,"name":"uncommitted-r"}],
"total":777,"precincts":
{"total":16,"reporting":16},
"name":"Bradley"},
"Logan":
{"votes":[
{"votes":1051,"name":"huckabee"},
{"votes":367,"name":"mccain"},
{"votes":175,"name":"romney"},
{"votes":100,"name":"paul"},
{"votes":10,"name":"uncommitted-r"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"thompson"}],
"total":1715,"precincts":
{"total":38,"reporting":38},
"name":"Logan"},
"Prairie":
{"votes":[
{"votes":448,"name":"huckabee"},
{"votes":118,"name":"mccain"},
{"votes":53,"name":"romney"},
{"votes":26,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"giuliani"}],
"total":652,"precincts":
{"total":9,"reporting":9},
"name":"Prairie"},
"Marion":
{"votes":[
{"votes":873,"name":"huckabee"},
{"votes":392,"name":"mccain"},
{"votes":341,"name":"romney"},
{"votes":101,"name":"paul"},
{"votes":8,"name":"uncommitted-r"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"thompson"}],
"total":1722,"precincts":
{"total":35,"reporting":35},
"name":"Marion"},
"Cleveland":
{"votes":[
{"votes":571,"name":"huckabee"},
{"votes":163,"name":"mccain"},
{"votes":52,"name":"romney"},
{"votes":34,"name":"paul"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"thompson"}],
"total":825,"precincts":
{"total":19,"reporting":19},
"name":"Cleveland"},
"Sharp":
{"votes":[
{"votes":1006,"name":"huckabee"},
{"votes":388,"name":"mccain"},
{"votes":194,"name":"romney"},
{"votes":64,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":7,"name":"giuliani"},
{"votes":3,"name":"thompson"}],
"total":1671,"precincts":
{"total":26,"reporting":26},
"name":"Sharp"},
"Chicot":
{"votes":[
{"votes":333,"name":"huckabee"},
{"votes":93,"name":"mccain"},
{"votes":54,"name":"romney"},
{"votes":6,"name":"paul"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"giuliani"}],
"total":489,"precincts":
{"total":13,"reporting":13},
"name":"Chicot"},
"Nevada":
{"votes":[
{"votes":373,"name":"huckabee"},
{"votes":139,"name":"mccain"},
{"votes":56,"name":"romney"},
{"votes":18,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":2,"name":"uncommitted-r"},
{"votes":0,"name":"giuliani"}],
"total":592,"precincts":
{"total":21,"reporting":21},
"name":"Nevada"},
"Randolph":
{"votes":[
{"votes":738,"name":"huckabee"},
{"votes":194,"name":"mccain"},
{"votes":145,"name":"romney"},
{"votes":41,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":4,"name":"thompson"},
{"votes":4,"name":"giuliani"}],
"total":1131,"precincts":
{"total":29,"reporting":29},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":450,"name":"huckabee"},
{"votes":105,"name":"mccain"},
{"votes":31,"name":"romney"},
{"votes":15,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"thompson"},
{"votes":0,"name":"uncommitted-r"}],
"total":607,"precincts":
{"total":40,"reporting":40},
"name":"Monroe"}}})