GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":227764,"name":"mccain","delegates":"53"},
{"votes":163967,"name":"romney"},
{"votes":43118,"name":"huckabee"},
{"votes":20197,"name":"paul"},
{"votes":12716,"name":"giuliani"},
{"votes":8860,"name":"thompson"},
{"votes":982,"name":"hunter"},
{"votes":854,"name":"keyes"}],
"name":"Arizona","precincts":
{"total":957,"reporting":935},
"delegates":"53","date":"02-05"},
"state":"AZ","party":"gop","total":478458,"locals":
{"Yuma":
{"votes":[
{"votes":2710,"name":"mccain"},
{"votes":2120,"name":"romney"},
{"votes":799,"name":"huckabee"},
{"votes":269,"name":"thompson"},
{"votes":223,"name":"giuliani"},
{"votes":154,"name":"paul"},
{"votes":32,"name":"hunter"},
{"votes":16,"name":"keyes"}],
"total":6323,"precincts":
{"total":9,"reporting":9},
"name":"Yuma"},
"Pinal":
{"votes":[
{"votes":8301,"name":"mccain"},
{"votes":7598,"name":"romney"},
{"votes":1811,"name":"huckabee"},
{"votes":810,"name":"paul"},
{"votes":309,"name":"giuliani"},
{"votes":269,"name":"thompson"},
{"votes":31,"name":"hunter"},
{"votes":29,"name":"keyes"}],
"total":19158,"precincts":
{"total":41,"reporting":41},
"name":"Pinal"},
"Greenlee":
{"votes":[
{"votes":154,"name":"mccain"},
{"votes":136,"name":"romney"},
{"votes":53,"name":"huckabee"},
{"votes":7,"name":"thompson"},
{"votes":7,"name":"paul"},
{"votes":6,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":367,"precincts":
{"total":6,"reporting":6},
"name":"Greenlee"},
"Maricopa":
{"votes":[
{"votes":153609,"name":"mccain"},
{"votes":103677,"name":"romney"},
{"votes":25624,"name":"huckabee"},
{"votes":13649,"name":"paul"},
{"votes":11117,"name":"giuliani"},
{"votes":7289,"name":"thompson"},
{"votes":744,"name":"hunter"},
{"votes":554,"name":"keyes"}],
"total":316263,"precincts":
{"total":403,"reporting":397},
"name":"Maricopa"},
"Mohave":
{"votes":[
{"votes":7784,"name":"mccain"},
{"votes":4985,"name":"romney"},
{"votes":1915,"name":"huckabee"},
{"votes":757,"name":"paul"},
{"votes":273,"name":"thompson"},
{"votes":204,"name":"giuliani"},
{"votes":45,"name":"hunter"},
{"votes":17,"name":"keyes"}],
"total":15980,"precincts":
{"total":55,"reporting":51},
"name":"Mohave"},
"Gila":
{"votes":[
{"votes":2780,"name":"mccain"},
{"votes":1412,"name":"romney"},
{"votes":678,"name":"huckabee"},
{"votes":221,"name":"paul"},
{"votes":118,"name":"thompson"},
{"votes":114,"name":"giuliani"},
{"votes":18,"name":"keyes"},
{"votes":12,"name":"hunter"}],
"total":5353,"precincts":
{"total":22,"reporting":18},
"name":"Gila"},
"Santa Cruz":
{"votes":[
{"votes":728,"name":"mccain"},
{"votes":515,"name":"romney"},
{"votes":125,"name":"huckabee"},
{"votes":62,"name":"paul"},
{"votes":30,"name":"giuliani"},
{"votes":16,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1480,"precincts":
{"total":9,"reporting":9},
"name":"Santa Cruz"},
"Cochise":
{"votes":[
{"votes":4228,"name":"mccain"},
{"votes":4131,"name":"romney"},
{"votes":1326,"name":"huckabee"},
{"votes":430,"name":"paul"},
{"votes":93,"name":"giuliani"},
{"votes":80,"name":"thompson"},
{"votes":39,"name":"keyes"},
{"votes":16,"name":"hunter"}],
"total":10343,"precincts":
{"total":18,"reporting":18},
"name":"Cochise"},
"La Paz":
{"votes":[
{"votes":688,"name":"mccain"},
{"votes":356,"name":"romney"},
{"votes":151,"name":"huckabee"},
{"votes":38,"name":"paul"},
{"votes":17,"name":"thompson"},
{"votes":14,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":3,"name":"keyes"}],
"total":1274,"precincts":
{"total":12,"reporting":12},
"name":"La Paz"},
"Coconino":
{"votes":[
{"votes":4015,"name":"mccain"},
{"votes":2136,"name":"romney"},
{"votes":1029,"name":"huckabee"},
{"votes":395,"name":"paul"},
{"votes":71,"name":"giuliani"},
{"votes":60,"name":"thompson"},
{"votes":18,"name":"keyes"},
{"votes":10,"name":"hunter"}],
"total":7734,"precincts":
{"total":49,"reporting":45},
"name":"Coconino"},
"Pima":
{"votes":[
{"votes":27859,"name":"mccain"},
{"votes":23429,"name":"romney"},
{"votes":5717,"name":"huckabee"},
{"votes":2352,"name":"paul"},
{"votes":265,"name":"giuliani"},
{"votes":191,"name":"thompson"},
{"votes":112,"name":"keyes"},
{"votes":35,"name":"hunter"}],
"total":59960,"precincts":
{"total":200,"reporting":200},
"name":"Pima"},
"Apache":
{"votes":[
{"votes":868,"name":"romney"},
{"votes":756,"name":"mccain"},
{"votes":194,"name":"huckabee"},
{"votes":116,"name":"paul"},
{"votes":15,"name":"giuliani"},
{"votes":14,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1969,"precincts":
{"total":41,"reporting":41},
"name":"Apache"},
"Navajo":
{"votes":[
{"votes":3792,"name":"romney"},
{"votes":2418,"name":"mccain"},
{"votes":540,"name":"huckabee"},
{"votes":229,"name":"paul"},
{"votes":36,"name":"giuliani"},
{"votes":28,"name":"thompson"},
{"votes":14,"name":"keyes"},
{"votes":7,"name":"hunter"}],
"total":7064,"precincts":
{"total":57,"reporting":55},
"name":"Navajo"},
"Graham":
{"votes":[
{"votes":1845,"name":"romney"},
{"votes":696,"name":"mccain"},
{"votes":167,"name":"huckabee"},
{"votes":58,"name":"paul"},
{"votes":13,"name":"thompson"},
{"votes":8,"name":"giuliani"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":2792,"precincts":
{"total":9,"reporting":9},
"name":"Graham"},
"Yavapai":
{"votes":[
{"votes":11038,"name":"mccain"},
{"votes":6967,"name":"romney"},
{"votes":2989,"name":"huckabee"},
{"votes":919,"name":"paul"},
{"votes":216,"name":"thompson"},
{"votes":211,"name":"giuliani"},
{"votes":31,"name":"hunter"},
{"votes":27,"name":"keyes"}],
"total":22398,"precincts":
{"total":26,"reporting":24},
"name":"Yavapai"}}})