GoogleElectionMap.votesReady({"status":"ok","totals":
{"date":"02-05","votes":[
{"votes":51124,"name":"obama"},
{"votes":40751,"name":"clinton"},
{"votes":2863,"name":"biden"},
{"votes":1241,"name":"edwards"},
{"votes":192,"name":"kucinich"},
{"votes":170,"name":"dodd"}],
"precincts":
{"total":312,"reporting":312},
"name":"Delaware"},
"state":"DE","party":"dem","total":96341,"locals":
{"New Castle":
{"votes":[
{"votes":37795,"name":"obama"},
{"votes":26564,"name":"clinton"},
{"votes":1785,"name":"biden"},
{"votes":575,"name":"edwards"},
{"votes":116,"name":"kucinich"},
{"votes":82,"name":"dodd"}],
"total":66917,"precincts":
{"total":204,"reporting":204},
"name":"New Castle"},
"Sussex":
{"votes":[
{"votes":8654,"name":"clinton"},
{"votes":6594,"name":"obama"},
{"votes":670,"name":"biden"},
{"votes":393,"name":"edwards"},
{"votes":56,"name":"dodd"},
{"votes":44,"name":"kucinich"}],
"total":16411,"precincts":
{"total":64,"reporting":64},
"name":"Sussex"},
"Kent":
{"votes":[
{"votes":6735,"name":"obama"},
{"votes":5533,"name":"clinton"},
{"votes":408,"name":"biden"},
{"votes":273,"name":"edwards"},
{"votes":32,"name":"dodd"},
{"votes":32,"name":"kucinich"}],
"total":13013,"precincts":
{"total":44,"reporting":44},
"name":"Kent"}}})