GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":700366,"name":"obama","delegates":61},
{"votes":328129,"name":"clinton","delegates":26},
{"votes":17990,"name":"edwards"},
{"votes":2531,"name":"biden"},
{"votes":2088,"name":"kucinich"},
{"votes":1880,"name":"richardson"},
{"votes":947,"name":"gravel"},
{"votes":900,"name":"dodd"}],
"name":"Georgia","precincts":
{"total":3157,"reporting":3154},
"delegates":87,"date":"02-05"},
"state":"GA","party":"dem","total":1054831,"locals":
{"Union":
{"votes":[
{"votes":1483,"name":"clinton"},
{"votes":740,"name":"obama"},
{"votes":207,"name":"edwards"},
{"votes":18,"name":"richardson"},
{"votes":13,"name":"biden"},
{"votes":10,"name":"dodd"},
{"votes":7,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":2482,"precincts":
{"total":12,"reporting":12},
"name":"Union"},
"Paulding":
{"votes":[
{"votes":6094,"name":"obama"},
{"votes":3876,"name":"clinton"},
{"votes":268,"name":"edwards"},
{"votes":19,"name":"richardson"},
{"votes":13,"name":"biden"},
{"votes":12,"name":"kucinich"},
{"votes":11,"name":"gravel"},
{"votes":10,"name":"dodd"}],
"total":10303,"precincts":
{"total":29,"reporting":29},
"name":"Paulding"},
"Montgomery":
{"votes":[
{"votes":380,"name":"obama"},
{"votes":311,"name":"clinton"},
{"votes":16,"name":"edwards"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"kucinich"}],
"total":724,"precincts":
{"total":8,"reporting":8},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":1117,"name":"clinton"},
{"votes":721,"name":"obama"},
{"votes":111,"name":"edwards"},
{"votes":11,"name":"biden"},
{"votes":8,"name":"dodd"},
{"votes":5,"name":"richardson"},
{"votes":5,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":1979,"precincts":
{"total":16,"reporting":16},
"name":"Wayne"},
"Screven":
{"votes":[
{"votes":1137,"name":"obama"},
{"votes":542,"name":"clinton"},
{"votes":25,"name":"edwards"},
{"votes":11,"name":"biden"},
{"votes":8,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":1727,"precincts":
{"total":13,"reporting":13},
"name":"Screven"},
"Pickens":
{"votes":[
{"votes":1419,"name":"clinton"},
{"votes":647,"name":"obama"},
{"votes":96,"name":"edwards"},
{"votes":12,"name":"richardson"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":2187,"precincts":
{"total":13,"reporting":13},
"name":"Pickens"},
"Wilkinson":
{"votes":[
{"votes":1061,"name":"obama"},
{"votes":389,"name":"clinton"},
{"votes":32,"name":"edwards"},
{"votes":7,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":1503,"precincts":
{"total":10,"reporting":10},
"name":"Wilkinson"},
"Ben Hill":
{"votes":[
{"votes":852,"name":"obama"},
{"votes":554,"name":"clinton"},
{"votes":62,"name":"edwards"},
{"votes":12,"name":"kucinich"},
{"votes":11,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1500,"precincts":
{"total":6,"reporting":6},
"name":"Ben Hill"},
"Worth":
{"votes":[
{"votes":825,"name":"obama"},
{"votes":797,"name":"clinton"},
{"votes":71,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":1718,"precincts":
{"total":16,"reporting":16},
"name":"Worth"},
"Appling":
{"votes":[
{"votes":671,"name":"clinton"},
{"votes":561,"name":"obama"},
{"votes":44,"name":"edwards"},
{"votes":11,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":1297,"precincts":
{"total":18,"reporting":18},
"name":"Appling"},
"McDuffie":
{"votes":[
{"votes":1485,"name":"obama"},
{"votes":723,"name":"clinton"},
{"votes":50,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":10,"name":"kucinich"},
{"votes":9,"name":"biden"},
{"votes":6,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":2298,"precincts":
{"total":11,"reporting":11},
"name":"McDuffie"},
"Dodge":
{"votes":[
{"votes":804,"name":"clinton"},
{"votes":746,"name":"obama"},
{"votes":52,"name":"edwards"},
{"votes":15,"name":"richardson"},
{"votes":9,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":1638,"precincts":
{"total":17,"reporting":17},
"name":"Dodge"},
"Columbia":
{"votes":[
{"votes":5402,"name":"obama"},
{"votes":3568,"name":"clinton"},
{"votes":174,"name":"edwards"},
{"votes":15,"name":"richardson"},
{"votes":14,"name":"biden"},
{"votes":12,"name":"kucinich"},
{"votes":12,"name":"gravel"},
{"votes":8,"name":"dodd"}],
"total":9205,"precincts":
{"total":46,"reporting":46},
"name":"Columbia"},
"Bibb":
{"votes":[
{"votes":16678,"name":"obama"},
{"votes":5083,"name":"clinton"},
{"votes":281,"name":"edwards"},
{"votes":45,"name":"biden"},
{"votes":43,"name":"richardson"},
{"votes":42,"name":"kucinich"},
{"votes":17,"name":"gravel"},
{"votes":15,"name":"dodd"}],
"total":22204,"precincts":
{"total":43,"reporting":43},
"name":"Bibb"},
"Brooks":
{"votes":[
{"votes":723,"name":"obama"},
{"votes":423,"name":"clinton"},
{"votes":43,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":1207,"precincts":
{"total":10,"reporting":10},
"name":"Brooks"},
"Cherokee":
{"votes":[
{"votes":6651,"name":"obama"},
{"votes":5888,"name":"clinton"},
{"votes":309,"name":"edwards"},
{"votes":27,"name":"biden"},
{"votes":25,"name":"richardson"},
{"votes":19,"name":"gravel"},
{"votes":11,"name":"dodd"},
{"votes":10,"name":"kucinich"}],
"total":12940,"precincts":
{"total":45,"reporting":45},
"name":"Cherokee"},
"Harris":
{"votes":[
{"votes":1478,"name":"obama"},
{"votes":1224,"name":"clinton"},
{"votes":78,"name":"edwards"},
{"votes":14,"name":"biden"},
{"votes":7,"name":"dodd"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":2811,"precincts":
{"total":13,"reporting":13},
"name":"Harris"},
"Chattooga":
{"votes":[
{"votes":1402,"name":"clinton"},
{"votes":574,"name":"obama"},
{"votes":107,"name":"edwards"},
{"votes":16,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":7,"name":"gravel"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"biden"}],
"total":2121,"precincts":
{"total":14,"reporting":14},
"name":"Chattooga"},
"Coweta":
{"votes":[
{"votes":5449,"name":"obama"},
{"votes":3618,"name":"clinton"},
{"votes":219,"name":"edwards"},
{"votes":29,"name":"biden"},
{"votes":28,"name":"richardson"},
{"votes":23,"name":"kucinich"},
{"votes":13,"name":"dodd"},
{"votes":6,"name":"gravel"}],
"total":9385,"precincts":
{"total":29,"reporting":29},
"name":"Coweta"},
"Dougherty":
{"votes":[
{"votes":11227,"name":"obama"},
{"votes":3323,"name":"clinton"},
{"votes":241,"name":"edwards"},
{"votes":53,"name":"biden"},
{"votes":25,"name":"richardson"},
{"votes":23,"name":"kucinich"},
{"votes":16,"name":"dodd"},
{"votes":10,"name":"gravel"}],
"total":14918,"precincts":
{"total":29,"reporting":29},
"name":"Dougherty"},
"Crisp":
{"votes":[
{"votes":955,"name":"obama"},
{"votes":563,"name":"clinton"},
{"votes":38,"name":"edwards"},
{"votes":7,"name":"richardson"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":1573,"precincts":
{"total":7,"reporting":7},
"name":"Crisp"},
"Hancock":
{"votes":[
{"votes":1288,"name":"obama"},
{"votes":263,"name":"clinton"},
{"votes":18,"name":"edwards"},
{"votes":10,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":1602,"precincts":
{"total":8,"reporting":8},
"name":"Hancock"},
"Cook":
{"votes":[
{"votes":616,"name":"obama"},
{"votes":500,"name":"clinton"},
{"votes":52,"name":"edwards"},
{"votes":10,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":5,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1191,"precincts":
{"total":9,"reporting":9},
"name":"Cook"},
"Gordon":
{"votes":[
{"votes":2269,"name":"clinton"},
{"votes":829,"name":"obama"},
{"votes":139,"name":"edwards"},
{"votes":14,"name":"richardson"},
{"votes":13,"name":"biden"},
{"votes":10,"name":"dodd"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":3284,"precincts":
{"total":15,"reporting":15},
"name":"Gordon"},
"Henry":
{"votes":[
{"votes":16692,"name":"obama"},
{"votes":5817,"name":"clinton"},
{"votes":389,"name":"edwards"},
{"votes":32,"name":"biden"},
{"votes":28,"name":"kucinich"},
{"votes":26,"name":"richardson"},
{"votes":12,"name":"dodd"},
{"votes":11,"name":"gravel"}],
"total":23007,"precincts":
{"total":39,"reporting":39},
"name":"Henry"},
"Webster":
{"votes":[
{"votes":280,"name":"obama"},
{"votes":136,"name":"clinton"},
{"votes":15,"name":"richardson"},
{"votes":14,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":457,"precincts":
{"total":5,"reporting":5},
"name":"Webster"},
"Wilkes":
{"votes":[
{"votes":843,"name":"obama"},
{"votes":429,"name":"clinton"},
{"votes":23,"name":"edwards"},
{"votes":9,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":7,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":1323,"precincts":
{"total":8,"reporting":8},
"name":"Wilkes"},
"Thomas":
{"votes":[
{"votes":2437,"name":"obama"},
{"votes":1265,"name":"clinton"},
{"votes":111,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":12,"name":"richardson"},
{"votes":12,"name":"kucinich"},
{"votes":8,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":3860,"precincts":
{"total":21,"reporting":21},
"name":"Thomas"},
"Chatham":
{"votes":[
{"votes":26142,"name":"obama"},
{"votes":9033,"name":"clinton"},
{"votes":368,"name":"edwards"},
{"votes":86,"name":"kucinich"},
{"votes":82,"name":"biden"},
{"votes":55,"name":"richardson"},
{"votes":34,"name":"dodd"},
{"votes":18,"name":"gravel"}],
"total":35818,"precincts":
{"total":92,"reporting":92},
"name":"Chatham"},
"Stephens":
{"votes":[
{"votes":1185,"name":"clinton"},
{"votes":644,"name":"obama"},
{"votes":181,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":8,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"dodd"}],
"total":2037,"precincts":
{"total":9,"reporting":9},
"name":"Stephens"},
"Newton":
{"votes":[
{"votes":8313,"name":"obama"},
{"votes":2851,"name":"clinton"},
{"votes":165,"name":"edwards"},
{"votes":20,"name":"richardson"},
{"votes":18,"name":"biden"},
{"votes":14,"name":"kucinich"},
{"votes":11,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":11394,"precincts":
{"total":23,"reporting":23},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":1733,"name":"obama"},
{"votes":762,"name":"clinton"},
{"votes":66,"name":"edwards"},
{"votes":26,"name":"biden"},
{"votes":24,"name":"richardson"},
{"votes":22,"name":"kucinich"},
{"votes":8,"name":"dodd"},
{"votes":5,"name":"gravel"}],
"total":2646,"precincts":
{"total":9,"reporting":9},
"name":"Washington"},
"Hall":
{"votes":[
{"votes":4268,"name":"obama"},
{"votes":4062,"name":"clinton"},
{"votes":227,"name":"edwards"},
{"votes":40,"name":"biden"},
{"votes":31,"name":"kucinich"},
{"votes":23,"name":"richardson"},
{"votes":10,"name":"dodd"},
{"votes":9,"name":"gravel"}],
"total":8670,"precincts":
{"total":40,"reporting":40},
"name":"Hall"},
"Heard":
{"votes":[
{"votes":600,"name":"clinton"},
{"votes":316,"name":"obama"},
{"votes":44,"name":"edwards"},
{"votes":9,"name":"kucinich"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":1,"name":"gravel"}],
"total":985,"precincts":
{"total":10,"reporting":10},
"name":"Heard"},
"Upson":
{"votes":[
{"votes":1540,"name":"obama"},
{"votes":999,"name":"clinton"},
{"votes":73,"name":"edwards"},
{"votes":18,"name":"biden"},
{"votes":14,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"gravel"}],
"total":2657,"precincts":
{"total":11,"reporting":11},
"name":"Upson"},
"Jasper":
{"votes":[
{"votes":715,"name":"obama"},
{"votes":509,"name":"clinton"},
{"votes":47,"name":"edwards"},
{"votes":6,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":1291,"precincts":
{"total":8,"reporting":8},
"name":"Jasper"},
"Effingham":
{"votes":[
{"votes":1974,"name":"clinton"},
{"votes":1759,"name":"obama"},
{"votes":172,"name":"edwards"},
{"votes":28,"name":"biden"},
{"votes":14,"name":"kucinich"},
{"votes":11,"name":"gravel"},
{"votes":8,"name":"richardson"},
{"votes":7,"name":"dodd"}],
"total":3973,"precincts":
{"total":22,"reporting":22},
"name":"Effingham"},
"Lowndes":
{"votes":[
{"votes":5166,"name":"obama"},
{"votes":2303,"name":"clinton"},
{"votes":183,"name":"edwards"},
{"votes":45,"name":"biden"},
{"votes":33,"name":"richardson"},
{"votes":15,"name":"kucinich"},
{"votes":10,"name":"gravel"},
{"votes":8,"name":"dodd"}],
"total":7763,"precincts":
{"total":37,"reporting":37},
"name":"Lowndes"},
"Polk":
{"votes":[
{"votes":2063,"name":"clinton"},
{"votes":1207,"name":"obama"},
{"votes":188,"name":"edwards"},
{"votes":17,"name":"biden"},
{"votes":16,"name":"richardson"},
{"votes":14,"name":"kucinich"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":3512,"precincts":
{"total":12,"reporting":12},
"name":"Polk"},
"Warren":
{"votes":[
{"votes":563,"name":"obama"},
{"votes":252,"name":"clinton"},
{"votes":17,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":846,"precincts":
{"total":7,"reporting":7},
"name":"Warren"},
"Camden":
{"votes":[
{"votes":1894,"name":"obama"},
{"votes":1138,"name":"clinton"},
{"votes":68,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"richardson"}],
"total":3120,"precincts":
{"total":15,"reporting":15},
"name":"Camden"},
"Jackson":
{"votes":[
{"votes":1987,"name":"clinton"},
{"votes":1493,"name":"obama"},
{"votes":137,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":10,"name":"kucinich"},
{"votes":8,"name":"gravel"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"dodd"}],
"total":3658,"precincts":
{"total":17,"reporting":17},
"name":"Jackson"},
"McIntosh":
{"votes":[
{"votes":1198,"name":"obama"},
{"votes":568,"name":"clinton"},
{"votes":49,"name":"edwards"},
{"votes":17,"name":"biden"},
{"votes":8,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":1856,"precincts":
{"total":8,"reporting":8},
"name":"McIntosh"},
"Bacon":
{"votes":[
{"votes":358,"name":"clinton"},
{"votes":190,"name":"obama"},
{"votes":35,"name":"edwards"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":595,"precincts":
{"total":6,"reporting":6},
"name":"Bacon"},
"Liberty":
{"votes":[
{"votes":3534,"name":"obama"},
{"votes":1148,"name":"clinton"},
{"votes":66,"name":"edwards"},
{"votes":16,"name":"kucinich"},
{"votes":11,"name":"biden"},
{"votes":8,"name":"richardson"},
{"votes":6,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":4792,"precincts":
{"total":14,"reporting":14},
"name":"Liberty"},
"Lee":
{"votes":[
{"votes":1146,"name":"obama"},
{"votes":923,"name":"clinton"},
{"votes":71,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":2161,"precincts":
{"total":11,"reporting":11},
"name":"Lee"},
"Jefferson":
{"votes":[
{"votes":1598,"name":"obama"},
{"votes":624,"name":"clinton"},
{"votes":41,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":12,"name":"kucinich"},
{"votes":9,"name":"richardson"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":2308,"precincts":
{"total":9,"reporting":9},
"name":"Jefferson"},
"Seminole":
{"votes":[
{"votes":469,"name":"obama"},
{"votes":416,"name":"clinton"},
{"votes":49,"name":"edwards"},
{"votes":10,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":958,"precincts":
{"total":6,"reporting":6},
"name":"Seminole"},
"Jenkins":
{"votes":[
{"votes":548,"name":"obama"},
{"votes":306,"name":"clinton"},
{"votes":24,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":896,"precincts":
{"total":6,"reporting":6},
"name":"Jenkins"},
"White":
{"votes":[
{"votes":1042,"name":"clinton"},
{"votes":626,"name":"obama"},
{"votes":103,"name":"edwards"},
{"votes":9,"name":"kucinich"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"biden"}],
"total":1791,"precincts":
{"total":12,"reporting":12},
"name":"White"},
"Burke":
{"votes":[
{"votes":1956,"name":"obama"},
{"votes":717,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":14,"name":"biden"},
{"votes":11,"name":"kucinich"},
{"votes":9,"name":"gravel"},
{"votes":7,"name":"richardson"},
{"votes":4,"name":"dodd"}],
"total":2745,"precincts":
{"total":16,"reporting":16},
"name":"Burke"},
"Putnam":
{"votes":[
{"votes":1145,"name":"obama"},
{"votes":827,"name":"clinton"},
{"votes":60,"name":"edwards"},
{"votes":9,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":2055,"precincts":
{"total":10,"reporting":10},
"name":"Putnam"},
"Coffee":
{"votes":[
{"votes":1281,"name":"obama"},
{"votes":1047,"name":"clinton"},
{"votes":84,"name":"edwards"},
{"votes":17,"name":"biden"},
{"votes":9,"name":"kucinich"},
{"votes":7,"name":"richardson"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":2454,"precincts":
{"total":7,"reporting":7},
"name":"Coffee"},
"Glynn":
{"votes":[
{"votes":3618,"name":"obama"},
{"votes":2067,"name":"clinton"},
{"votes":123,"name":"edwards"},
{"votes":18,"name":"biden"},
{"votes":15,"name":"kucinich"},
{"votes":13,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":5861,"precincts":
{"total":21,"reporting":21},
"name":"Glynn"},
"Dooly":
{"votes":[
{"votes":794,"name":"obama"},
{"votes":338,"name":"clinton"},
{"votes":23,"name":"edwards"},
{"votes":14,"name":"biden"},
{"votes":10,"name":"kucinich"},
{"votes":6,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":1189,"precincts":
{"total":8,"reporting":8},
"name":"Dooly"},
"Catoosa":
{"votes":[
{"votes":3106,"name":"clinton"},
{"votes":952,"name":"obama"},
{"votes":166,"name":"edwards"},
{"votes":12,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":4258,"precincts":
{"total":13,"reporting":13},
"name":"Catoosa"},
"Butts":
{"votes":[
{"votes":1169,"name":"obama"},
{"votes":761,"name":"clinton"},
{"votes":68,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":2025,"precincts":
{"total":6,"reporting":6},
"name":"Butts"},
"Oconee":
{"votes":[
{"votes":1816,"name":"obama"},
{"votes":1358,"name":"clinton"},
{"votes":111,"name":"edwards"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":3302,"precincts":
{"total":14,"reporting":14},
"name":"Oconee"},
"Jeff Davis":
{"votes":[
{"votes":533,"name":"clinton"},
{"votes":387,"name":"obama"},
{"votes":59,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":1000,"precincts":
{"total":10,"reporting":10},
"name":"Jeff Davis"},
"Toombs":
{"votes":[
{"votes":833,"name":"obama"},
{"votes":805,"name":"clinton"},
{"votes":46,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":8,"name":"kucinich"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"richardson"}],
"total":1712,"precincts":
{"total":15,"reporting":15},
"name":"Toombs"},
"Marion":
{"votes":[
{"votes":516,"name":"obama"},
{"votes":366,"name":"clinton"},
{"votes":19,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"}],
"total":917,"precincts":
{"total":8,"reporting":8},
"name":"Marion"},
"Ware":
{"votes":[
{"votes":1166,"name":"obama"},
{"votes":969,"name":"clinton"},
{"votes":89,"name":"edwards"},
{"votes":17,"name":"richardson"},
{"votes":13,"name":"biden"},
{"votes":11,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":2272,"precincts":
{"total":13,"reporting":13},
"name":"Ware"},
"Colquitt":
{"votes":[
{"votes":1241,"name":"clinton"},
{"votes":1204,"name":"obama"},
{"votes":146,"name":"edwards"},
{"votes":24,"name":"biden"},
{"votes":20,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":2651,"precincts":
{"total":20,"reporting":20},
"name":"Colquitt"},
"Barrow":
{"votes":[
{"votes":1948,"name":"obama"},
{"votes":1667,"name":"clinton"},
{"votes":112,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":12,"name":"richardson"},
{"votes":11,"name":"kucinich"},
{"votes":7,"name":"gravel"},
{"votes":5,"name":"dodd"}],
"total":3777,"precincts":
{"total":17,"reporting":17},
"name":"Barrow"},
"Schley":
{"votes":[
{"votes":165,"name":"clinton"},
{"votes":155,"name":"obama"},
{"votes":17,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"biden"}],
"total":346,"precincts":
{"total":2,"reporting":2},
"name":"Schley"},
"Johnson":
{"votes":[
{"votes":384,"name":"obama"},
{"votes":321,"name":"clinton"},
{"votes":32,"name":"edwards"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"richardson"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"kucinich"}],
"total":758,"precincts":
{"total":8,"reporting":8},
"name":"Johnson"},
"Candler":
{"votes":[
{"votes":394,"name":"obama"},
{"votes":313,"name":"clinton"},
{"votes":28,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":750,"precincts":
{"total":3,"reporting":3},
"name":"Candler"},
"Baker":
{"votes":[
{"votes":317,"name":"obama"},
{"votes":199,"name":"clinton"},
{"votes":36,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":568,"precincts":
{"total":7,"reporting":6},
"name":"Baker"},
"Oglethorpe":
{"votes":[
{"votes":747,"name":"obama"},
{"votes":585,"name":"clinton"},
{"votes":36,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":7,"name":"gravel"},
{"votes":4,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"richardson"}],
"total":1390,"precincts":
{"total":11,"reporting":11},
"name":"Oglethorpe"},
"Irwin":
{"votes":[
{"votes":404,"name":"clinton"},
{"votes":381,"name":"obama"},
{"votes":38,"name":"edwards"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":834,"precincts":
{"total":11,"reporting":11},
"name":"Irwin"},
"Greene":
{"votes":[
{"votes":1243,"name":"obama"},
{"votes":518,"name":"clinton"},
{"votes":34,"name":"edwards"},
{"votes":12,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":1820,"precincts":
{"total":9,"reporting":9},
"name":"Greene"},
"Bartow":
{"votes":[
{"votes":3472,"name":"clinton"},
{"votes":2887,"name":"obama"},
{"votes":240,"name":"edwards"},
{"votes":19,"name":"richardson"},
{"votes":13,"name":"biden"},
{"votes":12,"name":"dodd"},
{"votes":12,"name":"kucinich"},
{"votes":11,"name":"gravel"}],
"total":6666,"precincts":
{"total":18,"reporting":18},
"name":"Bartow"},
"Forsyth":
{"votes":[
{"votes":4551,"name":"clinton"},
{"votes":4537,"name":"obama"},
{"votes":324,"name":"edwards"},
{"votes":22,"name":"biden"},
{"votes":20,"name":"richardson"},
{"votes":13,"name":"kucinich"},
{"votes":13,"name":"gravel"},
{"votes":8,"name":"dodd"}],
"total":9488,"precincts":
{"total":33,"reporting":33},
"name":"Forsyth"},
"Clay":
{"votes":[
{"votes":282,"name":"obama"},
{"votes":157,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"}],
"total":451,"precincts":
{"total":5,"reporting":5},
"name":"Clay"},
"Fulton":
{"votes":[
{"votes":106692,"name":"obama"},
{"votes":34290,"name":"clinton"},
{"votes":645,"name":"edwards"},
{"votes":223,"name":"biden"},
{"votes":191,"name":"kucinich"},
{"votes":103,"name":"richardson"},
{"votes":79,"name":"gravel"},
{"votes":68,"name":"dodd"}],
"total":142291,"precincts":
{"total":349,"reporting":347},
"name":"Fulton"},
"Macon":
{"votes":[
{"votes":1277,"name":"obama"},
{"votes":440,"name":"clinton"},
{"votes":33,"name":"edwards"},
{"votes":9,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":5,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":1777,"precincts":
{"total":6,"reporting":6},
"name":"Macon"},
"Madison":
{"votes":[
{"votes":1059,"name":"clinton"},
{"votes":896,"name":"obama"},
{"votes":113,"name":"edwards"},
{"votes":13,"name":"kucinich"},
{"votes":10,"name":"biden"},
{"votes":8,"name":"richardson"},
{"votes":6,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":2108,"precincts":
{"total":13,"reporting":13},
"name":"Madison"},
"Taylor":
{"votes":[
{"votes":555,"name":"obama"},
{"votes":330,"name":"clinton"},
{"votes":22,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"kucinich"}],
"total":920,"precincts":
{"total":7,"reporting":7},
"name":"Taylor"},
"Evans":
{"votes":[
{"votes":480,"name":"obama"},
{"votes":413,"name":"clinton"},
{"votes":38,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"dodd"}],
"total":944,"precincts":
{"total":11,"reporting":11},
"name":"Evans"},
"Clinch":
{"votes":[
{"votes":214,"name":"obama"},
{"votes":208,"name":"clinton"},
{"votes":21,"name":"edwards"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"kucinich"}],
"total":449,"precincts":
{"total":6,"reporting":6},
"name":"Clinch"},
"Charlton":
{"votes":[
{"votes":341,"name":"obama"},
{"votes":270,"name":"clinton"},
{"votes":30,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":656,"precincts":
{"total":10,"reporting":10},
"name":"Charlton"},
"Echols":
{"votes":[
{"votes":80,"name":"clinton"},
{"votes":49,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"dodd"}],
"total":138,"precincts":
{"total":2,"reporting":2},
"name":"Echols"},
"Grady":
{"votes":[
{"votes":1032,"name":"obama"},
{"votes":791,"name":"clinton"},
{"votes":93,"name":"edwards"},
{"votes":20,"name":"richardson"},
{"votes":16,"name":"biden"},
{"votes":12,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1970,"precincts":
{"total":14,"reporting":14},
"name":"Grady"},
"Dawson":
{"votes":[
{"votes":735,"name":"clinton"},
{"votes":439,"name":"obama"},
{"votes":61,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"dodd"}],
"total":1247,"precincts":
{"total":9,"reporting":9},
"name":"Dawson"},
"Hart":
{"votes":[
{"votes":1332,"name":"clinton"},
{"votes":899,"name":"obama"},
{"votes":87,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":9,"name":"biden"},
{"votes":7,"name":"gravel"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"dodd"}],
"total":2351,"precincts":
{"total":8,"reporting":8},
"name":"Hart"},
"Baldwin":
{"votes":[
{"votes":3547,"name":"obama"},
{"votes":1470,"name":"clinton"},
{"votes":106,"name":"edwards"},
{"votes":21,"name":"biden"},
{"votes":15,"name":"richardson"},
{"votes":9,"name":"dodd"},
{"votes":7,"name":"kucinich"},
{"votes":4,"name":"gravel"}],
"total":5179,"precincts":
{"total":16,"reporting":16},
"name":"Baldwin"},
"Lumpkin":
{"votes":[
{"votes":1249,"name":"clinton"},
{"votes":703,"name":"obama"},
{"votes":108,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":10,"name":"kucinich"},
{"votes":7,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":2097,"precincts":
{"total":16,"reporting":16},
"name":"Lumpkin"},
"Lanier":
{"votes":[
{"votes":297,"name":"obama"},
{"votes":282,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":1,"name":"richardson"}],
"total":618,"precincts":
{"total":4,"reporting":4},
"name":"Lanier"},
"Haralson":
{"votes":[
{"votes":1501,"name":"clinton"},
{"votes":454,"name":"obama"},
{"votes":88,"name":"edwards"},
{"votes":12,"name":"biden"},
{"votes":12,"name":"richardson"},
{"votes":7,"name":"dodd"},
{"votes":7,"name":"kucinich"},
{"votes":5,"name":"gravel"}],
"total":2086,"precincts":
{"total":13,"reporting":13},
"name":"Haralson"},
"Rockdale":
{"votes":[
{"votes":9180,"name":"obama"},
{"votes":2807,"name":"clinton"},
{"votes":163,"name":"edwards"},
{"votes":22,"name":"biden"},
{"votes":14,"name":"richardson"},
{"votes":11,"name":"gravel"},
{"votes":10,"name":"dodd"},
{"votes":10,"name":"kucinich"}],
"total":12217,"precincts":
{"total":18,"reporting":18},
"name":"Rockdale"},
"Elbert":
{"votes":[
{"votes":961,"name":"clinton"},
{"votes":901,"name":"obama"},
{"votes":96,"name":"edwards"},
{"votes":8,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":1982,"precincts":
{"total":12,"reporting":12},
"name":"Elbert"},
"Decatur":
{"votes":[
{"votes":1466,"name":"obama"},
{"votes":804,"name":"clinton"},
{"votes":75,"name":"edwards"},
{"votes":22,"name":"biden"},
{"votes":14,"name":"richardson"},
{"votes":14,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"gravel"}],
"total":2405,"precincts":
{"total":16,"reporting":16},
"name":"Decatur"},
"Clarke":
{"votes":[
{"votes":10663,"name":"obama"},
{"votes":4257,"name":"clinton"},
{"votes":218,"name":"edwards"},
{"votes":49,"name":"kucinich"},
{"votes":33,"name":"biden"},
{"votes":24,"name":"richardson"},
{"votes":22,"name":"gravel"},
{"votes":5,"name":"dodd"}],
"total":15271,"precincts":
{"total":25,"reporting":25},
"name":"Clarke"},
"Richmond":
{"votes":[
{"votes":20377,"name":"obama"},
{"votes":6099,"name":"clinton"},
{"votes":223,"name":"edwards"},
{"votes":47,"name":"kucinich"},
{"votes":40,"name":"biden"},
{"votes":36,"name":"richardson"},
{"votes":16,"name":"dodd"},
{"votes":15,"name":"gravel"}],
"total":26853,"precincts":
{"total":73,"reporting":73},
"name":"Richmond"},
"Lamar":
{"votes":[
{"votes":1013,"name":"obama"},
{"votes":762,"name":"clinton"},
{"votes":41,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"gravel"}],
"total":1844,"precincts":
{"total":7,"reporting":7},
"name":"Lamar"},
"Cobb":
{"votes":[
{"votes":55574,"name":"obama"},
{"votes":23714,"name":"clinton"},
{"votes":1015,"name":"edwards"},
{"votes":109,"name":"biden"},
{"votes":108,"name":"kucinich"},
{"votes":75,"name":"richardson"},
{"votes":67,"name":"gravel"},
{"votes":32,"name":"dodd"}],
"total":80694,"precincts":
{"total":188,"reporting":188},
"name":"Cobb"},
"Morgan":
{"votes":[
{"votes":1236,"name":"obama"},
{"votes":671,"name":"clinton"},
{"votes":57,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":1992,"precincts":
{"total":11,"reporting":11},
"name":"Morgan"},
"Glascock":
{"votes":[
{"votes":138,"name":"clinton"},
{"votes":40,"name":"obama"},
{"votes":15,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"kucinich"}],
"total":197,"precincts":
{"total":5,"reporting":5},
"name":"Glascock"},
"Treutlen":
{"votes":[
{"votes":376,"name":"obama"},
{"votes":286,"name":"clinton"},
{"votes":30,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":703,"precincts":
{"total":7,"reporting":7},
"name":"Treutlen"},
"Walton":
{"votes":[
{"votes":2774,"name":"obama"},
{"votes":2298,"name":"clinton"},
{"votes":109,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":10,"name":"dodd"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"kucinich"},
{"votes":7,"name":"gravel"}],
"total":5228,"precincts":
{"total":20,"reporting":20},
"name":"Walton"},
"Muscogee":
{"votes":[
{"votes":16911,"name":"obama"},
{"votes":6677,"name":"clinton"},
{"votes":283,"name":"edwards"},
{"votes":43,"name":"biden"},
{"votes":37,"name":"richardson"},
{"votes":35,"name":"kucinich"},
{"votes":13,"name":"gravel"},
{"votes":12,"name":"dodd"}],
"total":24011,"precincts":
{"total":49,"reporting":49},
"name":"Muscogee"},
"Wheeler":
{"votes":[
{"votes":254,"name":"obama"},
{"votes":188,"name":"clinton"},
{"votes":9,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"biden"}],
"total":464,"precincts":
{"total":3,"reporting":3},
"name":"Wheeler"},
"Fayette":
{"votes":[
{"votes":9222,"name":"obama"},
{"votes":4171,"name":"clinton"},
{"votes":228,"name":"edwards"},
{"votes":30,"name":"biden"},
{"votes":19,"name":"kucinich"},
{"votes":18,"name":"richardson"},
{"votes":9,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":13701,"precincts":
{"total":37,"reporting":37},
"name":"Fayette"},
"Early":
{"votes":[
{"votes":680,"name":"obama"},
{"votes":406,"name":"clinton"},
{"votes":30,"name":"edwards"},
{"votes":6,"name":"biden"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"richardson"}],
"total":1130,"precincts":
{"total":12,"reporting":12},
"name":"Early"},
"Floyd":
{"votes":[
{"votes":3858,"name":"clinton"},
{"votes":3433,"name":"obama"},
{"votes":305,"name":"edwards"},
{"votes":39,"name":"biden"},
{"votes":29,"name":"richardson"},
{"votes":14,"name":"kucinich"},
{"votes":13,"name":"dodd"},
{"votes":13,"name":"gravel"}],
"total":7704,"precincts":
{"total":26,"reporting":26},
"name":"Floyd"},
"Chattahoochee":
{"votes":[
{"votes":233,"name":"obama"},
{"votes":159,"name":"clinton"},
{"votes":7,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":406,"precincts":
{"total":2,"reporting":2},
"name":"Chattahoochee"},
"Towns":
{"votes":[
{"votes":718,"name":"clinton"},
{"votes":311,"name":"obama"},
{"votes":77,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":1119,"precincts":
{"total":5,"reporting":5},
"name":"Towns"},
"Bryan":
{"votes":[
{"votes":1077,"name":"obama"},
{"votes":984,"name":"clinton"},
{"votes":52,"name":"edwards"},
{"votes":12,"name":"biden"},
{"votes":7,"name":"kucinich"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":2142,"precincts":
{"total":11,"reporting":11},
"name":"Bryan"},
"Lincoln":
{"votes":[
{"votes":595,"name":"obama"},
{"votes":409,"name":"clinton"},
{"votes":26,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":4,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":1051,"precincts":
{"total":8,"reporting":8},
"name":"Lincoln"},
"Dade":
{"votes":[
{"votes":909,"name":"clinton"},
{"votes":226,"name":"obama"},
{"votes":45,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"kucinich"}],
"total":1194,"precincts":
{"total":8,"reporting":8},
"name":"Dade"},
"Franklin":
{"votes":[
{"votes":1093,"name":"clinton"},
{"votes":370,"name":"obama"},
{"votes":79,"name":"edwards"},
{"votes":8,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1563,"precincts":
{"total":14,"reporting":14},
"name":"Franklin"},
"Walker":
{"votes":[
{"votes":3306,"name":"clinton"},
{"votes":1118,"name":"obama"},
{"votes":219,"name":"edwards"},
{"votes":13,"name":"richardson"},
{"votes":12,"name":"biden"},
{"votes":9,"name":"dodd"},
{"votes":9,"name":"kucinich"},
{"votes":8,"name":"gravel"}],
"total":4694,"precincts":
{"total":19,"reporting":19},
"name":"Walker"},
"Terrell":
{"votes":[
{"votes":876,"name":"obama"},
{"votes":372,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":7,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"}],
"total":1298,"precincts":
{"total":7,"reporting":7},
"name":"Terrell"},
"Carroll":
{"votes":[
{"votes":4547,"name":"obama"},
{"votes":3883,"name":"clinton"},
{"votes":236,"name":"edwards"},
{"votes":27,"name":"kucinich"},
{"votes":19,"name":"biden"},
{"votes":17,"name":"richardson"},
{"votes":12,"name":"gravel"},
{"votes":8,"name":"dodd"}],
"total":8749,"precincts":
{"total":33,"reporting":33},
"name":"Carroll"},
"Murray":
{"votes":[
{"votes":1847,"name":"clinton"},
{"votes":318,"name":"obama"},
{"votes":86,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":4,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":2273,"precincts":
{"total":8,"reporting":8},
"name":"Murray"},
"Talbot":
{"votes":[
{"votes":878,"name":"obama"},
{"votes":314,"name":"clinton"},
{"votes":11,"name":"edwards"},
{"votes":7,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1223,"precincts":
{"total":9,"reporting":9},
"name":"Talbot"},
"Tift":
{"votes":[
{"votes":1300,"name":"obama"},
{"votes":1164,"name":"clinton"},
{"votes":92,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":7,"name":"dodd"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"kucinich"}],
"total":2580,"precincts":
{"total":13,"reporting":13},
"name":"Tift"},
"Peach":
{"votes":[
{"votes":2075,"name":"obama"},
{"votes":727,"name":"clinton"},
{"votes":45,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":2880,"precincts":
{"total":8,"reporting":8},
"name":"Peach"},
"Pike":
{"votes":[
{"votes":639,"name":"clinton"},
{"votes":607,"name":"obama"},
{"votes":54,"name":"edwards"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":1317,"precincts":
{"total":9,"reporting":9},
"name":"Pike"},
"Sumter":
{"votes":[
{"votes":2402,"name":"obama"},
{"votes":1001,"name":"clinton"},
{"votes":137,"name":"edwards"},
{"votes":13,"name":"kucinich"},
{"votes":12,"name":"biden"},
{"votes":11,"name":"richardson"},
{"votes":9,"name":"dodd"},
{"votes":7,"name":"gravel"}],
"total":3592,"precincts":
{"total":12,"reporting":12},
"name":"Sumter"},
"Calhoun":
{"votes":[
{"votes":545,"name":"obama"},
{"votes":207,"name":"clinton"},
{"votes":13,"name":"edwards"},
{"votes":7,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":782,"precincts":
{"total":6,"reporting":6},
"name":"Calhoun"},
"Douglas":
{"votes":[
{"votes":11503,"name":"obama"},
{"votes":4007,"name":"clinton"},
{"votes":215,"name":"edwards"},
{"votes":18,"name":"richardson"},
{"votes":17,"name":"biden"},
{"votes":12,"name":"gravel"},
{"votes":11,"name":"kucinich"},
{"votes":4,"name":"dodd"}],
"total":15787,"precincts":
{"total":25,"reporting":25},
"name":"Douglas"},
"Pulaski":
{"votes":[
{"votes":427,"name":"obama"},
{"votes":336,"name":"clinton"},
{"votes":34,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":814,"precincts":
{"total":4,"reporting":4},
"name":"Pulaski"},
"Atkinson":
{"votes":[
{"votes":241,"name":"obama"},
{"votes":235,"name":"clinton"},
{"votes":15,"name":"edwards"},
{"votes":6,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"richardson"}],
"total":505,"precincts":
{"total":5,"reporting":5},
"name":"Atkinson"},
"DeKalb":
{"votes":[
{"votes":113192,"name":"obama"},
{"votes":34077,"name":"clinton"},
{"votes":940,"name":"edwards"},
{"votes":248,"name":"kucinich"},
{"votes":182,"name":"biden"},
{"votes":114,"name":"richardson"},
{"votes":90,"name":"gravel"},
{"votes":44,"name":"dodd"}],
"total":148887,"precincts":
{"total":193,"reporting":193},
"name":"DeKalb"},
"Wilcox":
{"votes":[
{"votes":287,"name":"obama"},
{"votes":260,"name":"clinton"},
{"votes":24,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":590,"precincts":
{"total":7,"reporting":7},
"name":"Wilcox"},
"Troup":
{"votes":[
{"votes":3552,"name":"obama"},
{"votes":2014,"name":"clinton"},
{"votes":150,"name":"edwards"},
{"votes":16,"name":"kucinich"},
{"votes":14,"name":"richardson"},
{"votes":12,"name":"biden"},
{"votes":6,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":5766,"precincts":
{"total":17,"reporting":17},
"name":"Troup"},
"Crawford":
{"votes":[
{"votes":705,"name":"obama"},
{"votes":537,"name":"clinton"},
{"votes":29,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"gravel"}],
"total":1286,"precincts":
{"total":7,"reporting":7},
"name":"Crawford"},
"Long":
{"votes":[
{"votes":298,"name":"clinton"},
{"votes":293,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"kucinich"}],
"total":627,"precincts":
{"total":6,"reporting":6},
"name":"Long"},
"Gilmer":
{"votes":[
{"votes":1366,"name":"clinton"},
{"votes":584,"name":"obama"},
{"votes":86,"name":"edwards"},
{"votes":8,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":2062,"precincts":
{"total":14,"reporting":14},
"name":"Gilmer"},
"Bleckley":
{"votes":[
{"votes":430,"name":"obama"},
{"votes":398,"name":"clinton"},
{"votes":41,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"biden"}],
"total":882,"precincts":
{"total":2,"reporting":2},
"name":"Bleckley"},
"Gwinnett":
{"votes":[
{"votes":46890,"name":"obama"},
{"votes":20703,"name":"clinton"},
{"votes":918,"name":"edwards"},
{"votes":93,"name":"biden"},
{"votes":85,"name":"kucinich"},
{"votes":65,"name":"richardson"},
{"votes":47,"name":"gravel"},
{"votes":31,"name":"dodd"}],
"total":68832,"precincts":
{"total":163,"reporting":163},
"name":"Gwinnett"},
"Clayton":
{"votes":[
{"votes":36306,"name":"obama"},
{"votes":7456,"name":"clinton"},
{"votes":359,"name":"edwards"},
{"votes":56,"name":"kucinich"},
{"votes":54,"name":"biden"},
{"votes":34,"name":"richardson"},
{"votes":18,"name":"gravel"},
{"votes":14,"name":"dodd"}],
"total":44297,"precincts":
{"total":60,"reporting":60},
"name":"Clayton"},
"Brantley":
{"votes":[
{"votes":510,"name":"clinton"},
{"votes":181,"name":"obama"},
{"votes":76,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"kucinich"}],
"total":776,"precincts":
{"total":10,"reporting":10},
"name":"Brantley"},
"Quitman":
{"votes":[
{"votes":239,"name":"obama"},
{"votes":109,"name":"clinton"},
{"votes":11,"name":"edwards"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":366,"precincts":
{"total":3,"reporting":3},
"name":"Quitman"},
"Meriwether":
{"votes":[
{"votes":1679,"name":"obama"},
{"votes":993,"name":"clinton"},
{"votes":69,"name":"edwards"},
{"votes":15,"name":"richardson"},
{"votes":13,"name":"kucinich"},
{"votes":12,"name":"biden"},
{"votes":7,"name":"gravel"},
{"votes":5,"name":"dodd"}],
"total":2793,"precincts":
{"total":15,"reporting":15},
"name":"Meriwether"},
"Jones":
{"votes":[
{"votes":1988,"name":"obama"},
{"votes":1174,"name":"clinton"},
{"votes":130,"name":"edwards"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":3320,"precincts":
{"total":12,"reporting":12},
"name":"Jones"},
"Pierce":
{"votes":[
{"votes":477,"name":"clinton"},
{"votes":252,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":6,"name":"biden"},
{"votes":6,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":773,"precincts":
{"total":9,"reporting":9},
"name":"Pierce"},
"Laurens":
{"votes":[
{"votes":2848,"name":"obama"},
{"votes":1726,"name":"clinton"},
{"votes":125,"name":"edwards"},
{"votes":19,"name":"biden"},
{"votes":18,"name":"kucinich"},
{"votes":17,"name":"richardson"},
{"votes":11,"name":"gravel"},
{"votes":9,"name":"dodd"}],
"total":4773,"precincts":
{"total":21,"reporting":21},
"name":"Laurens"},
"Berrien":
{"votes":[
{"votes":654,"name":"clinton"},
{"votes":421,"name":"obama"},
{"votes":61,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"kucinich"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"}],
"total":1151,"precincts":
{"total":10,"reporting":10},
"name":"Berrien"},
"Taliaferro":
{"votes":[
{"votes":252,"name":"obama"},
{"votes":109,"name":"clinton"},
{"votes":6,"name":"edwards"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":372,"precincts":
{"total":3,"reporting":3},
"name":"Taliaferro"},
"Emanuel":
{"votes":[
{"votes":1000,"name":"obama"},
{"votes":773,"name":"clinton"},
{"votes":53,"name":"edwards"},
{"votes":9,"name":"kucinich"},
{"votes":8,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":5,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":1857,"precincts":
{"total":13,"reporting":13},
"name":"Emanuel"},
"Telfair":
{"votes":[
{"votes":551,"name":"obama"},
{"votes":484,"name":"clinton"},
{"votes":24,"name":"edwards"},
{"votes":7,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":1082,"precincts":
{"total":7,"reporting":7},
"name":"Telfair"},
"Banks":
{"votes":[
{"votes":693,"name":"clinton"},
{"votes":232,"name":"obama"},
{"votes":64,"name":"edwards"},
{"votes":9,"name":"biden"},
{"votes":6,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"richardson"}],
"total":1011,"precincts":
{"total":14,"reporting":14},
"name":"Banks"},
"Mitchell":
{"votes":[
{"votes":1497,"name":"obama"},
{"votes":789,"name":"clinton"},
{"votes":57,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":15,"name":"richardson"},
{"votes":6,"name":"dodd"},
{"votes":5,"name":"kucinich"}],
"total":2384,"precincts":
{"total":12,"reporting":12},
"name":"Mitchell"},
"Stewart":
{"votes":[
{"votes":462,"name":"obama"},
{"votes":237,"name":"clinton"},
{"votes":13,"name":"edwards"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":731,"precincts":
{"total":6,"reporting":6},
"name":"Stewart"},
"Houston":
{"votes":[
{"votes":8105,"name":"obama"},
{"votes":3609,"name":"clinton"},
{"votes":266,"name":"edwards"},
{"votes":32,"name":"kucinich"},
{"votes":25,"name":"biden"},
{"votes":24,"name":"richardson"},
{"votes":16,"name":"gravel"},
{"votes":7,"name":"dodd"}],
"total":12084,"precincts":
{"total":25,"reporting":25},
"name":"Houston"},
"Whitfield":
{"votes":[
{"votes":3428,"name":"clinton"},
{"votes":1636,"name":"obama"},
{"votes":148,"name":"edwards"},
{"votes":20,"name":"biden"},
{"votes":12,"name":"richardson"},
{"votes":8,"name":"kucinich"},
{"votes":7,"name":"gravel"},
{"votes":5,"name":"dodd"}],
"total":5264,"precincts":
{"total":24,"reporting":24},
"name":"Whitfield"},
"Spalding":
{"votes":[
{"votes":3572,"name":"obama"},
{"votes":2048,"name":"clinton"},
{"votes":146,"name":"edwards"},
{"votes":17,"name":"biden"},
{"votes":17,"name":"richardson"},
{"votes":9,"name":"kucinich"},
{"votes":6,"name":"dodd"},
{"votes":5,"name":"gravel"}],
"total":5820,"precincts":
{"total":22,"reporting":22},
"name":"Spalding"},
"Miller":
{"votes":[
{"votes":310,"name":"clinton"},
{"votes":162,"name":"obama"},
{"votes":28,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"kucinich"},
{"votes":1,"name":"dodd"}],
"total":506,"precincts":
{"total":2,"reporting":2},
"name":"Miller"},
"Habersham":
{"votes":[
{"votes":1394,"name":"clinton"},
{"votes":773,"name":"obama"},
{"votes":153,"name":"edwards"},
{"votes":11,"name":"kucinich"},
{"votes":9,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":2352,"precincts":
{"total":15,"reporting":15},
"name":"Habersham"},
"Rabun":
{"votes":[
{"votes":963,"name":"clinton"},
{"votes":503,"name":"obama"},
{"votes":172,"name":"edwards"},
{"votes":15,"name":"biden"},
{"votes":13,"name":"richardson"},
{"votes":7,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"gravel"}],
"total":1683,"precincts":
{"total":10,"reporting":10},
"name":"Rabun"},
"Bulloch":
{"votes":[
{"votes":2668,"name":"obama"},
{"votes":1761,"name":"clinton"},
{"votes":91,"name":"edwards"},
{"votes":22,"name":"biden"},
{"votes":18,"name":"kucinich"},
{"votes":9,"name":"richardson"},
{"votes":6,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":4579,"precincts":
{"total":17,"reporting":17},
"name":"Bulloch"},
"Fannin":
{"votes":[
{"votes":1264,"name":"clinton"},
{"votes":504,"name":"obama"},
{"votes":95,"name":"edwards"},
{"votes":12,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":6,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"gravel"}],
"total":1892,"precincts":
{"total":13,"reporting":13},
"name":"Fannin"},
"Tattnall":
{"votes":[
{"votes":614,"name":"clinton"},
{"votes":594,"name":"obama"},
{"votes":31,"name":"edwards"},
{"votes":10,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":1268,"precincts":
{"total":12,"reporting":12},
"name":"Tattnall"},
"Turner":
{"votes":[
{"votes":425,"name":"obama"},
{"votes":329,"name":"clinton"},
{"votes":35,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"gravel"}],
"total":805,"precincts":
{"total":4,"reporting":4},
"name":"Turner"},
"Twiggs":
{"votes":[
{"votes":1054,"name":"obama"},
{"votes":497,"name":"clinton"},
{"votes":40,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":13,"name":"richardson"},
{"votes":7,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"kucinich"}],
"total":1634,"precincts":
{"total":6,"reporting":6},
"name":"Twiggs"},
"Randolph":
{"votes":[
{"votes":726,"name":"obama"},
{"votes":265,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":7,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"kucinich"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":1031,"precincts":
{"total":10,"reporting":10},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":1634,"name":"obama"},
{"votes":906,"name":"clinton"},
{"votes":66,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":6,"name":"dodd"},
{"votes":4,"name":"gravel"},
{"votes":1,"name":"kucinich"}],
"total":2639,"precincts":
{"total":15,"reporting":15},
"name":"Monroe"}}})