GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":6121,"name":"obama","delegates":15},
{"votes":4273,"name":"clinton","delegates":3},
{"votes":269,"name":"judd"},
{"votes":258,"name":"uncommitted-d"}],
"name":"Idaho","precincts":
{"total":940,"reporting":223},
"delegates":18,"date":"05-27"},
"state":"ID","party":"dem","total":10921,"locals":
{"Camas":
{"votes":[
{"votes":22,"name":"obama"},
{"votes":17,"name":"clinton"},
{"votes":3,"name":"judd"}],
"total":42,"precincts":
{"total":2,"reporting":2},
"name":"Camas"},
"Nez Perce":
{"votes":[
{"votes":55,"name":"obama"},
{"votes":33,"name":"clinton"},
{"votes":10,"name":"uncommitted-d"},
{"votes":2,"name":"judd"}],
"total":100,"precincts":
{"total":37,"reporting":4},
"name":"Nez Perce"},
"Gooding":
{"votes":[
{"votes":113,"name":"clinton"},
{"votes":109,"name":"obama"},
{"votes":10,"name":"uncommitted-d"},
{"votes":8,"name":"judd"}],
"total":240,"precincts":
{"total":7,"reporting":5},
"name":"Gooding"},
"Clearwater":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Clearwater"},
"Benewah":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Benewah"},
"Ada":
{"votes":[
{"votes":2192,"name":"obama"},
{"votes":1154,"name":"clinton"},
{"votes":92,"name":"uncommitted-d"},
{"votes":30,"name":"judd"}],
"total":3468,"precincts":
{"total":141,"reporting":26},
"name":"Ada"},
"Boundary":
{"votes":[
{"votes":53,"name":"obama"},
{"votes":21,"name":"clinton"}],
"total":74,"precincts":
{"total":7,"reporting":2},
"name":"Boundary"},
"Valley":
{"votes":[
{"votes":60,"name":"obama"},
{"votes":44,"name":"clinton"},
{"votes":2,"name":"uncommitted-d"}],
"total":106,"precincts":
{"total":9,"reporting":3},
"name":"Valley"},
"Teton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Teton"},
"Idaho":
{"votes":[
{"votes":15,"name":"clinton"},
{"votes":13,"name":"obama"},
{"votes":1,"name":"judd"}],
"total":29,"precincts":
{"total":27,"reporting":4},
"name":"Idaho"},
"Bingham":
{"votes":[
{"votes":19,"name":"clinton"},
{"votes":12,"name":"obama"},
{"votes":4,"name":"uncommitted-d"}],
"total":35,"precincts":
{"total":27,"reporting":1},
"name":"Bingham"},
"Owyhee":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Owyhee"},
"Custer":
{"votes":[
{"votes":99,"name":"obama"},
{"votes":66,"name":"clinton"},
{"votes":8,"name":"judd"},
{"votes":4,"name":"uncommitted-d"}],
"total":177,"precincts":
{"total":9,"reporting":8},
"name":"Custer"},
"Fremont":
{"votes":[
{"votes":49,"name":"obama"},
{"votes":41,"name":"clinton"},
{"votes":4,"name":"judd"}],
"total":94,"precincts":
{"total":14,"reporting":7},
"name":"Fremont"},
"Canyon":
{"votes":[
{"votes":87,"name":"obama"},
{"votes":67,"name":"clinton"},
{"votes":8,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":165,"precincts":
{"total":53,"reporting":5},
"name":"Canyon"},
"Boise":
{"votes":[
{"votes":44,"name":"obama"},
{"votes":19,"name":"clinton"},
{"votes":2,"name":"judd"}],
"total":65,"precincts":
{"total":7,"reporting":1},
"name":"Boise"},
"Bonneville":
{"votes":[
{"votes":275,"name":"obama"},
{"votes":169,"name":"clinton"},
{"votes":21,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":468,"precincts":
{"total":52,"reporting":24},
"name":"Bonneville"},
"Butte":
{"votes":[
{"votes":2,"name":"clinton"},
{"votes":1,"name":"obama"}],
"total":3,"precincts":
{"total":4,"reporting":1},
"name":"Butte"},
"Twin Falls":
{"votes":[
{"votes":351,"name":"obama"},
{"votes":293,"name":"clinton"},
{"votes":13,"name":"uncommitted-d"},
{"votes":11,"name":"judd"}],
"total":668,"precincts":
{"total":45,"reporting":24},
"name":"Twin Falls"},
"Gem":
{"votes":[
{"votes":29,"name":"clinton"},
{"votes":26,"name":"obama"}],
"total":55,"precincts":
{"total":13,"reporting":1},
"name":"Gem"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":36,"name":"obama"},
{"votes":19,"name":"clinton"},
{"votes":1,"name":"judd"}],
"total":56,"precincts":
{"total":6,"reporting":3},
"name":"Adams"},
"Lemhi":
{"votes":[
{"votes":132,"name":"obama"},
{"votes":94,"name":"judd"},
{"votes":83,"name":"clinton"},
{"votes":4,"name":"uncommitted-d"}],
"total":313,"precincts":
{"total":9,"reporting":9},
"name":"Lemhi"},
"Oneida":
{"votes":[
{"votes":41,"name":"clinton"},
{"votes":29,"name":"obama"},
{"votes":1,"name":"judd"}],
"total":71,"precincts":
{"total":6,"reporting":6},
"name":"Oneida"},
"Bannock":
{"votes":[
{"votes":1394,"name":"obama"},
{"votes":1065,"name":"clinton"},
{"votes":70,"name":"judd"}],
"total":2529,"precincts":
{"total":58,"reporting":41},
"name":"Bannock"},
"Jefferson":
{"votes":[
{"votes":8,"name":"clinton"},
{"votes":2,"name":"obama"},
{"votes":1,"name":"uncommitted-d"}],
"total":11,"precincts":
{"total":18,"reporting":1},
"name":"Jefferson"},
"Franklin":
{"votes":[
{"votes":20,"name":"clinton"},
{"votes":16,"name":"obama"},
{"votes":3,"name":"uncommitted-d"},
{"votes":1,"name":"judd"}],
"total":40,"precincts":
{"total":17,"reporting":8},
"name":"Franklin"},
"Caribou":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Caribou"},
"Latah":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Latah"},
"Madison":
{"votes":[
{"votes":13,"name":"obama"},
{"votes":10,"name":"clinton"},
{"votes":2,"name":"judd"},
{"votes":1,"name":"uncommitted-d"}],
"total":26,"precincts":
{"total":19,"reporting":4},
"name":"Madison"},
"Kootenai":
{"votes":[
{"votes":703,"name":"obama"},
{"votes":602,"name":"clinton"},
{"votes":26,"name":"uncommitted-d"},
{"votes":1,"name":"judd"}],
"total":1332,"precincts":
{"total":75,"reporting":1},
"name":"Kootenai"},
"Power":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Power"},
"Clark":
{"votes":[
{"votes":8,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":3,"name":"judd"},
{"votes":2,"name":"uncommitted-d"}],
"total":17,"precincts":
{"total":3,"reporting":3},
"name":"Clark"},
"Lewis":
{"votes":[
{"votes":62,"name":"obama"},
{"votes":49,"name":"clinton"},
{"votes":4,"name":"judd"},
{"votes":3,"name":"uncommitted-d"}],
"total":118,"precincts":
{"total":8,"reporting":3},
"name":"Lewis"},
"Bear Lake":
{"votes":[
{"votes":40,"name":"obama"},
{"votes":29,"name":"clinton"},
{"votes":3,"name":"judd"},
{"votes":1,"name":"uncommitted-d"}],
"total":73,"precincts":
{"total":14,"reporting":8},
"name":"Bear Lake"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Washington"},
"Elmore":
{"votes":[
{"votes":136,"name":"obama"},
{"votes":129,"name":"clinton"},
{"votes":16,"name":"uncommitted-d"},
{"votes":2,"name":"judd"}],
"total":283,"precincts":
{"total":18,"reporting":5},
"name":"Elmore"},
"Payette":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Payette"},
"Blaine":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Blaine"},
"Bonner":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Bonner"},
"Cassia":
{"votes":[
{"votes":20,"name":"obama"},
{"votes":19,"name":"clinton"},
{"votes":3,"name":"uncommitted-d"},
{"votes":3,"name":"judd"}],
"total":45,"precincts":
{"total":25,"reporting":10},
"name":"Cassia"},
"Minidoka":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Minidoka"},
"Jerome":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Jerome"},
"Shoshone":
{"votes":[
{"votes":93,"name":"clinton"},
{"votes":82,"name":"obama"},
{"votes":34,"name":"uncommitted-d"},
{"votes":9,"name":"judd"}],
"total":218,"precincts":
{"total":19,"reporting":3},
"name":"Shoshone"}}})