GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":8941,"name":"mccain"},
{"votes":2462,"name":"paul"},
{"votes":694,"name":"uncommitted-r"}],
"name":"Idaho","precincts":
{"total":940,"reporting":96},
"delegates":32,"date":"05-27"},
"state":"ID","party":"gop","total":12097,"locals":
{"Camas":
{"votes":[
{"votes":216,"name":"mccain"},
{"votes":73,"name":"paul"}],
"total":289,"precincts":
{"total":2,"reporting":2},
"name":"Camas"},
"Nez Perce":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Nez Perce"},
"Gooding":
{"votes":[
{"votes":736,"name":"mccain"},
{"votes":189,"name":"paul"},
{"votes":79,"name":"uncommitted-r"}],
"total":1004,"precincts":
{"total":7,"reporting":5},
"name":"Gooding"},
"Clearwater":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Clearwater"},
"Benewah":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Benewah"},
"Ada":
{"votes":[],
"total":0,"precincts":
{"total":141,"reporting":0},
"name":"Ada"},
"Boundary":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Boundary"},
"Valley":
{"votes":[
{"votes":187,"name":"mccain"},
{"votes":55,"name":"paul"}],
"total":242,"precincts":
{"total":9,"reporting":1},
"name":"Valley"},
"Teton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Teton"},
"Idaho":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Idaho"},
"Bingham":
{"votes":[
{"votes":92,"name":"mccain"},
{"votes":34,"name":"paul"},
{"votes":22,"name":"uncommitted-r"}],
"total":148,"precincts":
{"total":27,"reporting":1},
"name":"Bingham"},
"Owyhee":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Owyhee"},
"Custer":
{"votes":[
{"votes":368,"name":"mccain"},
{"votes":112,"name":"paul"},
{"votes":9,"name":"uncommitted-r"}],
"total":489,"precincts":
{"total":9,"reporting":5},
"name":"Custer"},
"Fremont":
{"votes":[
{"votes":716,"name":"mccain"},
{"votes":152,"name":"paul"}],
"total":868,"precincts":
{"total":14,"reporting":5},
"name":"Fremont"},
"Canyon":
{"votes":[
{"votes":887,"name":"mccain"},
{"votes":335,"name":"paul"},
{"votes":164,"name":"uncommitted-r"}],
"total":1386,"precincts":
{"total":53,"reporting":5},
"name":"Canyon"},
"Boise":
{"votes":[
{"votes":241,"name":"mccain"},
{"votes":99,"name":"paul"},
{"votes":6,"name":"uncommitted-r"}],
"total":346,"precincts":
{"total":7,"reporting":1},
"name":"Boise"},
"Bonneville":
{"votes":[
{"votes":1411,"name":"mccain"},
{"votes":336,"name":"paul"},
{"votes":164,"name":"uncommitted-r"}],
"total":1911,"precincts":
{"total":52,"reporting":24},
"name":"Bonneville"},
"Butte":
{"votes":[
{"votes":87,"name":"mccain"},
{"votes":14,"name":"paul"}],
"total":101,"precincts":
{"total":4,"reporting":1},
"name":"Butte"},
"Twin Falls":
{"votes":[],
"total":0,"precincts":
{"total":45,"reporting":0},
"name":"Twin Falls"},
"Gem":
{"votes":[
{"votes":93,"name":"mccain"},
{"votes":29,"name":"paul"},
{"votes":9,"name":"uncommitted-r"}],
"total":131,"precincts":
{"total":13,"reporting":1},
"name":"Gem"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":269,"name":"mccain"},
{"votes":105,"name":"paul"}],
"total":374,"precincts":
{"total":6,"reporting":3},
"name":"Adams"},
"Lemhi":
{"votes":[
{"votes":1245,"name":"mccain"},
{"votes":379,"name":"paul"},
{"votes":155,"name":"uncommitted-r"}],
"total":1779,"precincts":
{"total":9,"reporting":9},
"name":"Lemhi"},
"Oneida":
{"votes":[
{"votes":992,"name":"mccain"},
{"votes":256,"name":"paul"}],
"total":1248,"precincts":
{"total":6,"reporting":6},
"name":"Oneida"},
"Bannock":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Bannock"},
"Jefferson":
{"votes":[
{"votes":69,"name":"mccain"},
{"votes":19,"name":"paul"},
{"votes":4,"name":"uncommitted-r"}],
"total":92,"precincts":
{"total":18,"reporting":1},
"name":"Jefferson"},
"Franklin":
{"votes":[
{"votes":134,"name":"mccain"},
{"votes":11,"name":"paul"}],
"total":145,"precincts":
{"total":17,"reporting":1},
"name":"Franklin"},
"Caribou":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Caribou"},
"Latah":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Latah"},
"Madison":
{"votes":[
{"votes":179,"name":"mccain"},
{"votes":45,"name":"paul"},
{"votes":23,"name":"uncommitted-r"}],
"total":247,"precincts":
{"total":19,"reporting":4},
"name":"Madison"},
"Kootenai":
{"votes":[],
"total":0,"precincts":
{"total":75,"reporting":0},
"name":"Kootenai"},
"Power":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Power"},
"Clark":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Clark"},
"Lewis":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Lewis"},
"Bear Lake":
{"votes":[
{"votes":430,"name":"mccain"},
{"votes":71,"name":"paul"},
{"votes":9,"name":"uncommitted-r"}],
"total":510,"precincts":
{"total":14,"reporting":8},
"name":"Bear Lake"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Washington"},
"Elmore":
{"votes":[
{"votes":149,"name":"mccain"},
{"votes":38,"name":"paul"},
{"votes":17,"name":"uncommitted-r"}],
"total":204,"precincts":
{"total":18,"reporting":0},
"name":"Elmore"},
"Payette":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Payette"},
"Blaine":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Blaine"},
"Bonner":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Bonner"},
"Cassia":
{"votes":[
{"votes":386,"name":"mccain"},
{"votes":83,"name":"paul"},
{"votes":31,"name":"uncommitted-r"}],
"total":500,"precincts":
{"total":25,"reporting":10},
"name":"Cassia"},
"Minidoka":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Minidoka"},
"Jerome":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Jerome"},
"Shoshone":
{"votes":[
{"votes":54,"name":"mccain"},
{"votes":27,"name":"paul"},
{"votes":2,"name":"uncommitted-r"}],
"total":83,"precincts":
{"total":19,"reporting":3},
"name":"Shoshone"}}})