GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":31743,"name":"mccain"},
{"votes":10002,"name":"paul"},
{"votes":2602,"name":"uncommitted-r"}],
"name":"Idaho","precincts":
{"total":940,"reporting":323},
"delegates":32,"date":"05-27"},
"state":"ID","party":"gop","total":44347,"locals":
{"Camas":
{"votes":[
{"votes":216,"name":"mccain"},
{"votes":73,"name":"paul"}],
"total":289,"precincts":
{"total":2,"reporting":2},
"name":"Camas"},
"Nez Perce":
{"votes":[
{"votes":63,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":10,"name":"uncommitted-r"}],
"total":94,"precincts":
{"total":37,"reporting":4},
"name":"Nez Perce"},
"Gooding":
{"votes":[
{"votes":1318,"name":"mccain"},
{"votes":331,"name":"paul"},
{"votes":133,"name":"uncommitted-r"}],
"total":1782,"precincts":
{"total":7,"reporting":7},
"name":"Gooding"},
"Clearwater":
{"votes":[
{"votes":33,"name":"mccain"},
{"votes":10,"name":"paul"},
{"votes":1,"name":"uncommitted-r"}],
"total":44,"precincts":
{"total":15,"reporting":3},
"name":"Clearwater"},
"Benewah":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Benewah"},
"Ada":
{"votes":[
{"votes":5124,"name":"mccain"},
{"votes":1579,"name":"paul"},
{"votes":446,"name":"uncommitted-r"}],
"total":7149,"precincts":
{"total":141,"reporting":26},
"name":"Ada"},
"Boundary":
{"votes":[
{"votes":150,"name":"mccain"},
{"votes":83,"name":"paul"}],
"total":233,"precincts":
{"total":7,"reporting":2},
"name":"Boundary"},
"Valley":
{"votes":[
{"votes":467,"name":"mccain"},
{"votes":132,"name":"paul"},
{"votes":53,"name":"uncommitted-r"}],
"total":652,"precincts":
{"total":9,"reporting":3},
"name":"Valley"},
"Teton":
{"votes":[
{"votes":379,"name":"mccain"},
{"votes":98,"name":"paul"},
{"votes":29,"name":"uncommitted-r"}],
"total":506,"precincts":
{"total":5,"reporting":3},
"name":"Teton"},
"Idaho":
{"votes":[
{"votes":115,"name":"mccain"},
{"votes":50,"name":"paul"}],
"total":165,"precincts":
{"total":27,"reporting":4},
"name":"Idaho"},
"Bingham":
{"votes":[
{"votes":623,"name":"mccain"},
{"votes":120,"name":"paul"},
{"votes":104,"name":"uncommitted-r"}],
"total":847,"precincts":
{"total":27,"reporting":3},
"name":"Bingham"},
"Owyhee":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Owyhee"},
"Custer":
{"votes":[
{"votes":516,"name":"mccain"},
{"votes":181,"name":"paul"},
{"votes":18,"name":"uncommitted-r"}],
"total":715,"precincts":
{"total":9,"reporting":8},
"name":"Custer"},
"Fremont":
{"votes":[
{"votes":1725,"name":"mccain"},
{"votes":380,"name":"paul"}],
"total":2105,"precincts":
{"total":14,"reporting":10},
"name":"Fremont"},
"Canyon":
{"votes":[
{"votes":3038,"name":"mccain"},
{"votes":1047,"name":"paul"},
{"votes":485,"name":"uncommitted-r"}],
"total":4570,"precincts":
{"total":53,"reporting":26},
"name":"Canyon"},
"Boise":
{"votes":[
{"votes":751,"name":"mccain"},
{"votes":362,"name":"paul"},
{"votes":21,"name":"uncommitted-r"}],
"total":1134,"precincts":
{"total":7,"reporting":7},
"name":"Boise"},
"Bonneville":
{"votes":[
{"votes":1411,"name":"mccain"},
{"votes":336,"name":"paul"},
{"votes":164,"name":"uncommitted-r"}],
"total":1911,"precincts":
{"total":52,"reporting":24},
"name":"Bonneville"},
"Butte":
{"votes":[
{"votes":87,"name":"mccain"},
{"votes":14,"name":"paul"}],
"total":101,"precincts":
{"total":4,"reporting":1},
"name":"Butte"},
"Twin Falls":
{"votes":[
{"votes":1749,"name":"mccain"},
{"votes":550,"name":"paul"},
{"votes":111,"name":"uncommitted-r"}],
"total":2410,"precincts":
{"total":45,"reporting":24},
"name":"Twin Falls"},
"Gem":
{"votes":[
{"votes":93,"name":"mccain"},
{"votes":29,"name":"paul"},
{"votes":9,"name":"uncommitted-r"}],
"total":131,"precincts":
{"total":13,"reporting":1},
"name":"Gem"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":724,"name":"mccain"},
{"votes":304,"name":"paul"}],
"total":1028,"precincts":
{"total":6,"reporting":6},
"name":"Adams"},
"Lemhi":
{"votes":[
{"votes":1245,"name":"mccain"},
{"votes":379,"name":"paul"},
{"votes":155,"name":"uncommitted-r"}],
"total":1779,"precincts":
{"total":9,"reporting":9},
"name":"Lemhi"},
"Oneida":
{"votes":[
{"votes":992,"name":"mccain"},
{"votes":256,"name":"paul"}],
"total":1248,"precincts":
{"total":6,"reporting":6},
"name":"Oneida"},
"Bannock":
{"votes":[
{"votes":1226,"name":"mccain"},
{"votes":449,"name":"paul"},
{"votes":67,"name":"uncommitted-r"}],
"total":1742,"precincts":
{"total":58,"reporting":41},
"name":"Bannock"},
"Jefferson":
{"votes":[
{"votes":268,"name":"mccain"},
{"votes":94,"name":"paul"},
{"votes":26,"name":"uncommitted-r"}],
"total":388,"precincts":
{"total":18,"reporting":5},
"name":"Jefferson"},
"Franklin":
{"votes":[
{"votes":770,"name":"mccain"},
{"votes":108,"name":"uncommitted-r"},
{"votes":96,"name":"paul"}],
"total":974,"precincts":
{"total":17,"reporting":8},
"name":"Franklin"},
"Caribou":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Caribou"},
"Latah":
{"votes":[
{"votes":139,"name":"mccain"},
{"votes":13,"name":"uncommitted-r"}],
"total":152,"precincts":
{"total":33,"reporting":5},
"name":"Latah"},
"Madison":
{"votes":[
{"votes":179,"name":"mccain"},
{"votes":45,"name":"paul"},
{"votes":23,"name":"uncommitted-r"}],
"total":247,"precincts":
{"total":19,"reporting":4},
"name":"Madison"},
"Kootenai":
{"votes":[
{"votes":4984,"name":"mccain"},
{"votes":1941,"name":"paul"},
{"votes":434,"name":"uncommitted-r"}],
"total":7359,"precincts":
{"total":75,"reporting":25},
"name":"Kootenai"},
"Power":
{"votes":[
{"votes":236,"name":"mccain"},
{"votes":60,"name":"paul"},
{"votes":21,"name":"uncommitted-r"}],
"total":317,"precincts":
{"total":7,"reporting":7},
"name":"Power"},
"Clark":
{"votes":[
{"votes":200,"name":"mccain"},
{"votes":26,"name":"paul"},
{"votes":10,"name":"uncommitted-r"}],
"total":236,"precincts":
{"total":3,"reporting":3},
"name":"Clark"},
"Lewis":
{"votes":[
{"votes":264,"name":"mccain"},
{"votes":105,"name":"paul"},
{"votes":5,"name":"uncommitted-r"}],
"total":374,"precincts":
{"total":8,"reporting":5},
"name":"Lewis"},
"Bear Lake":
{"votes":[
{"votes":430,"name":"mccain"},
{"votes":71,"name":"paul"},
{"votes":9,"name":"uncommitted-r"}],
"total":510,"precincts":
{"total":14,"reporting":8},
"name":"Bear Lake"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Washington"},
"Elmore":
{"votes":[
{"votes":544,"name":"mccain"},
{"votes":161,"name":"paul"},
{"votes":56,"name":"uncommitted-r"}],
"total":761,"precincts":
{"total":18,"reporting":5},
"name":"Elmore"},
"Payette":
{"votes":[
{"votes":976,"name":"mccain"},
{"votes":439,"name":"paul"},
{"votes":45,"name":"uncommitted-r"}],
"total":1460,"precincts":
{"total":10,"reporting":10},
"name":"Payette"},
"Blaine":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Blaine"},
"Bonner":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Bonner"},
"Cassia":
{"votes":[
{"votes":386,"name":"mccain"},
{"votes":83,"name":"paul"},
{"votes":31,"name":"uncommitted-r"}],
"total":500,"precincts":
{"total":25,"reporting":10},
"name":"Cassia"},
"Minidoka":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Minidoka"},
"Jerome":
{"votes":[
{"votes":225,"name":"mccain"},
{"votes":53,"name":"paul"},
{"votes":13,"name":"uncommitted-r"}],
"total":291,"precincts":
{"total":11,"reporting":2},
"name":"Jerome"},
"Shoshone":
{"votes":[
{"votes":97,"name":"mccain"},
{"votes":44,"name":"paul"},
{"votes":2,"name":"uncommitted-r"}],
"total":143,"precincts":
{"total":19,"reporting":6},
"name":"Shoshone"}}})