GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":169547,"name":"clinton","delegates":49},
{"votes":126210,"name":"obama","delegates":44}],
"name":"Indiana","precincts":
{"total":5230,"reporting":1382},
"delegates":72,"date":"05-06"},
"state":"IN","party":"dem","total":295757,"locals":
{"Daviess":
{"votes":[
{"votes":894,"name":"clinton"},
{"votes":547,"name":"obama"}],
"total":1441,"precincts":
{"total":28,"reporting":10},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":3313,"name":"clinton"},
{"votes":1710,"name":"obama"}],
"total":5023,"precincts":
{"total":39,"reporting":29},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":277,"name":"obama"},
{"votes":195,"name":"clinton"}],
"total":472,"precincts":
{"total":27,"reporting":3},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Wayne"},
"Wabash":
{"votes":[
{"votes":2423,"name":"clinton"},
{"votes":1821,"name":"obama"}],
"total":4244,"precincts":
{"total":25,"reporting":22},
"name":"Wabash"},
"White":
{"votes":[
{"votes":710,"name":"clinton"},
{"votes":489,"name":"obama"}],
"total":1199,"precincts":
{"total":23,"reporting":5},
"name":"White"},
"Porter":
{"votes":[],
"total":0,"precincts":
{"total":128,"reporting":0},
"name":"Porter"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Brown"},
"LaPorte":
{"votes":[],
"total":0,"precincts":
{"total":79,"reporting":0},
"name":"LaPorte"},
"Jay":
{"votes":[
{"votes":2256,"name":"clinton"},
{"votes":1379,"name":"obama"}],
"total":3635,"precincts":
{"total":21,"reporting":21},
"name":"Jay"},
"Jennings":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Jennings"},
"Dearborn":
{"votes":[
{"votes":4811,"name":"clinton"},
{"votes":1629,"name":"obama"}],
"total":6440,"precincts":
{"total":45,"reporting":42},
"name":"Dearborn"},
"Miami":
{"votes":[
{"votes":166,"name":"clinton"},
{"votes":60,"name":"obama"}],
"total":226,"precincts":
{"total":31,"reporting":25},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":1916,"name":"clinton"},
{"votes":1092,"name":"obama"}],
"total":3008,"precincts":
{"total":38,"reporting":13},
"name":"Hancock"},
"Henry":
{"votes":[
{"votes":5153,"name":"clinton"},
{"votes":2707,"name":"obama"}],
"total":7860,"precincts":
{"total":42,"reporting":35},
"name":"Henry"},
"Vigo":
{"votes":[
{"votes":15985,"name":"clinton"},
{"votes":10943,"name":"obama"}],
"total":26928,"precincts":
{"total":87,"reporting":87},
"name":"Vigo"},
"Sullivan":
{"votes":[
{"votes":3511,"name":"clinton"},
{"votes":1724,"name":"obama"}],
"total":5235,"precincts":
{"total":20,"reporting":19},
"name":"Sullivan"},
"Dubois":
{"votes":[
{"votes":1102,"name":"clinton"},
{"votes":991,"name":"obama"}],
"total":2093,"precincts":
{"total":38,"reporting":7},
"name":"Dubois"},
"Newton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":355,"name":"clinton"},
{"votes":135,"name":"obama"}],
"total":490,"precincts":
{"total":22,"reporting":3},
"name":"Washington"},
"Decatur":
{"votes":[
{"votes":763,"name":"clinton"},
{"votes":372,"name":"obama"}],
"total":1135,"precincts":
{"total":20,"reporting":5},
"name":"Decatur"},
"Marion":
{"votes":[
{"votes":7629,"name":"obama"},
{"votes":5086,"name":"clinton"}],
"total":12715,"precincts":
{"total":594,"reporting":67},
"name":"Marion"},
"Jasper":
{"votes":[
{"votes":290,"name":"clinton"},
{"votes":206,"name":"obama"}],
"total":496,"precincts":
{"total":29,"reporting":2},
"name":"Jasper"},
"Vermillion":
{"votes":[
{"votes":481,"name":"clinton"},
{"votes":260,"name":"obama"}],
"total":741,"precincts":
{"total":17,"reporting":3},
"name":"Vermillion"},
"Allen":
{"votes":[
{"votes":29355,"name":"obama"},
{"votes":24560,"name":"clinton"}],
"total":53915,"precincts":
{"total":294,"reporting":243},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":286,"name":"obama"},
{"votes":261,"name":"clinton"}],
"total":547,"precincts":
{"total":13,"reporting":8},
"name":"Warren"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":2956,"name":"clinton"},
{"votes":2450,"name":"obama"}],
"total":5406,"precincts":
{"total":71,"reporting":23},
"name":"Howard"},
"Jefferson":
{"votes":[
{"votes":3878,"name":"clinton"},
{"votes":2102,"name":"obama"}],
"total":5980,"precincts":
{"total":26,"reporting":23},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":1869,"name":"clinton"},
{"votes":862,"name":"obama"}],
"total":2731,"precincts":
{"total":22,"reporting":20},
"name":"Orange"},
"St. Joseph":
{"votes":[],
"total":0,"precincts":
{"total":226,"reporting":0},
"name":"St. Joseph"},
"Putnam":
{"votes":[
{"votes":760,"name":"obama"},
{"votes":745,"name":"clinton"}],
"total":1505,"precincts":
{"total":29,"reporting":9},
"name":"Putnam"},
"Hamilton":
{"votes":[],
"total":0,"precincts":
{"total":196,"reporting":0},
"name":"Hamilton"},
"Kosciusko":
{"votes":[
{"votes":1098,"name":"clinton"},
{"votes":1079,"name":"obama"}],
"total":2177,"precincts":
{"total":65,"reporting":13},
"name":"Kosciusko"},
"Rush":
{"votes":[
{"votes":1162,"name":"clinton"},
{"votes":761,"name":"obama"}],
"total":1923,"precincts":
{"total":20,"reporting":11},
"name":"Rush"},
"Johnson":
{"votes":[
{"votes":5348,"name":"clinton"},
{"votes":4178,"name":"obama"}],
"total":9526,"precincts":
{"total":107,"reporting":53},
"name":"Johnson"},
"Whitley":
{"votes":[
{"votes":2964,"name":"clinton"},
{"votes":2106,"name":"obama"}],
"total":5070,"precincts":
{"total":34,"reporting":34},
"name":"Whitley"},
"Greene":
{"votes":[
{"votes":908,"name":"clinton"},
{"votes":445,"name":"obama"}],
"total":1353,"precincts":
{"total":32,"reporting":5},
"name":"Greene"},
"Ripley":
{"votes":[
{"votes":2695,"name":"clinton"},
{"votes":1275,"name":"obama"}],
"total":3970,"precincts":
{"total":27,"reporting":25},
"name":"Ripley"},
"LaGrange":
{"votes":[
{"votes":323,"name":"clinton"},
{"votes":215,"name":"obama"}],
"total":538,"precincts":
{"total":16,"reporting":2},
"name":"LaGrange"},
"Ohio":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Ohio"},
"Gibson":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Gibson"},
"Spencer":
{"votes":[
{"votes":364,"name":"clinton"},
{"votes":173,"name":"obama"}],
"total":537,"precincts":
{"total":25,"reporting":1},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":816,"name":"clinton"},
{"votes":536,"name":"obama"}],
"total":1352,"precincts":
{"total":17,"reporting":6},
"name":"Fulton"},
"Madison":
{"votes":[
{"votes":6960,"name":"clinton"},
{"votes":5759,"name":"obama"}],
"total":12719,"precincts":
{"total":111,"reporting":56},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":1896,"name":"clinton"},
{"votes":1215,"name":"obama"}],
"total":3111,"precincts":
{"total":39,"reporting":27},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":8650,"name":"clinton"},
{"votes":4404,"name":"obama"}],
"total":13054,"precincts":
{"total":73,"reporting":40},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":83,"name":"clinton"},
{"votes":81,"name":"obama"}],
"total":164,"precincts":
{"total":20,"reporting":1},
"name":"Owen"},
"Huntington":
{"votes":[
{"votes":1804,"name":"clinton"},
{"votes":1345,"name":"obama"}],
"total":3149,"precincts":
{"total":34,"reporting":22},
"name":"Huntington"},
"Clay":
{"votes":[
{"votes":1740,"name":"clinton"},
{"votes":866,"name":"obama"}],
"total":2606,"precincts":
{"total":23,"reporting":10},
"name":"Clay"},
"Blackford":
{"votes":[
{"votes":1940,"name":"clinton"},
{"votes":1024,"name":"obama"}],
"total":2964,"precincts":
{"total":12,"reporting":12},
"name":"Blackford"},
"Cass":
{"votes":[
{"votes":3685,"name":"clinton"},
{"votes":2338,"name":"obama"}],
"total":6023,"precincts":
{"total":39,"reporting":31},
"name":"Cass"},
"Delaware":
{"votes":[],
"total":0,"precincts":
{"total":75,"reporting":0},
"name":"Delaware"},
"Fountain":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Fountain"},
"Lawrence":
{"votes":[
{"votes":949,"name":"clinton"},
{"votes":527,"name":"obama"}],
"total":1476,"precincts":
{"total":39,"reporting":10},
"name":"Lawrence"},
"Elkhart":
{"votes":[],
"total":0,"precincts":
{"total":110,"reporting":0},
"name":"Elkhart"},
"Grant":
{"votes":[
{"votes":334,"name":"clinton"},
{"votes":186,"name":"obama"}],
"total":520,"precincts":
{"total":68,"reporting":1},
"name":"Grant"},
"Fayette":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Fayette"},
"Posey":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Posey"},
"Floyd":
{"votes":[
{"votes":5938,"name":"clinton"},
{"votes":2951,"name":"obama"}],
"total":8889,"precincts":
{"total":60,"reporting":31},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":2467,"name":"clinton"},
{"votes":1077,"name":"obama"}],
"total":3544,"precincts":
{"total":18,"reporting":18},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":931,"name":"clinton"},
{"votes":704,"name":"obama"}],
"total":1635,"precincts":
{"total":25,"reporting":7},
"name":"Adams"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Franklin"},
"Switzerland":
{"votes":[
{"votes":282,"name":"clinton"},
{"votes":82,"name":"obama"}],
"total":364,"precincts":
{"total":12,"reporting":4},
"name":"Switzerland"},
"Vanderburgh":
{"votes":[],
"total":0,"precincts":
{"total":131,"reporting":0},
"name":"Vanderburgh"},
"Marshall":
{"votes":[
{"votes":831,"name":"clinton"},
{"votes":574,"name":"obama"}],
"total":1405,"precincts":
{"total":27,"reporting":3},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":1000,"name":"clinton"},
{"votes":923,"name":"obama"}],
"total":1923,"precincts":
{"total":19,"reporting":10},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":1114,"name":"clinton"},
{"votes":417,"name":"obama"}],
"total":1531,"precincts":
{"total":36,"reporting":8},
"name":"Harrison"},
"Boone":
{"votes":[
{"votes":3564,"name":"obama"},
{"votes":3249,"name":"clinton"}],
"total":6813,"precincts":
{"total":49,"reporting":16},
"name":"Boone"},
"Starke":
{"votes":[
{"votes":1131,"name":"clinton"},
{"votes":440,"name":"obama"}],
"total":1571,"precincts":
{"total":21,"reporting":5},
"name":"Starke"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":559,"reporting":0},
"name":"Lake"},
"Pulaski":
{"votes":[
{"votes":933,"name":"clinton"},
{"votes":647,"name":"obama"}],
"total":1580,"precincts":
{"total":15,"reporting":9},
"name":"Pulaski"},
"Hendricks":
{"votes":[],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Hendricks"},
"Tippecanoe":
{"votes":[],
"total":0,"precincts":
{"total":91,"reporting":0},
"name":"Tippecanoe"},
"Parke":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Parke"},
"DeKalb":
{"votes":[
{"votes":1809,"name":"clinton"},
{"votes":1380,"name":"obama"}],
"total":3189,"precincts":
{"total":39,"reporting":21},
"name":"DeKalb"},
"Crawford":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Crawford"},
"Noble":
{"votes":[
{"votes":1761,"name":"clinton"},
{"votes":1173,"name":"obama"}],
"total":2934,"precincts":
{"total":29,"reporting":11},
"name":"Noble"},
"Wells":
{"votes":[
{"votes":2613,"name":"clinton"},
{"votes":1907,"name":"obama"}],
"total":4520,"precincts":
{"total":22,"reporting":22},
"name":"Wells"},
"Knox":
{"votes":[
{"votes":6197,"name":"clinton"},
{"votes":3178,"name":"obama"}],
"total":9375,"precincts":
{"total":36,"reporting":34},
"name":"Knox"},
"Bartholomew":
{"votes":[
{"votes":3939,"name":"clinton"},
{"votes":3418,"name":"obama"}],
"total":7357,"precincts":
{"total":67,"reporting":35},
"name":"Bartholomew"},
"Tipton":
{"votes":[
{"votes":1848,"name":"clinton"},
{"votes":1324,"name":"obama"}],
"total":3172,"precincts":
{"total":17,"reporting":17},
"name":"Tipton"},
"Benton":
{"votes":[
{"votes":30,"name":"clinton"},
{"votes":27,"name":"obama"}],
"total":57,"precincts":
{"total":15,"reporting":2},
"name":"Benton"},
"Morgan":
{"votes":[
{"votes":1324,"name":"clinton"},
{"votes":769,"name":"obama"}],
"total":2093,"precincts":
{"total":48,"reporting":17},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Martin"},
"Warrick":
{"votes":[],
"total":0,"precincts":
{"total":59,"reporting":0},
"name":"Warrick"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Scott"},
"Randolph":
{"votes":[
{"votes":1980,"name":"clinton"},
{"votes":1116,"name":"obama"}],
"total":3096,"precincts":
{"total":29,"reporting":12},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":217,"name":"obama"},
{"votes":88,"name":"clinton"}],
"total":305,"precincts":
{"total":71,"reporting":1},
"name":"Monroe"},
"Steuben":
{"votes":[
{"votes":2684,"name":"clinton"},
{"votes":2023,"name":"obama"}],
"total":4707,"precincts":
{"total":19,"reporting":15},
"name":"Steuben"}}})