GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":133504,"name":"mccain"},
{"votes":18402,"name":"huckabee"},
{"votes":13849,"name":"paul"},
{"votes":8603,"name":"romney"}],
"name":"Indiana","precincts":
{"total":5230,"reporting":2010},
"delegates":57,"date":"05-06"},
"state":"IN","party":"gop","total":174358,"locals":
{"Daviess":
{"votes":[
{"votes":960,"name":"mccain"},
{"votes":92,"name":"huckabee"},
{"votes":38,"name":"romney"},
{"votes":33,"name":"paul"}],
"total":1123,"precincts":
{"total":28,"reporting":10},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":3648,"name":"mccain"},
{"votes":426,"name":"huckabee"},
{"votes":280,"name":"paul"},
{"votes":210,"name":"romney"}],
"total":4564,"precincts":
{"total":39,"reporting":39},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":263,"name":"mccain"},
{"votes":42,"name":"huckabee"},
{"votes":26,"name":"paul"},
{"votes":17,"name":"romney"}],
"total":348,"precincts":
{"total":27,"reporting":3},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Wayne"},
"Wabash":
{"votes":[
{"votes":2859,"name":"mccain"},
{"votes":537,"name":"paul"},
{"votes":515,"name":"huckabee"},
{"votes":184,"name":"romney"}],
"total":4095,"precincts":
{"total":25,"reporting":25},
"name":"Wabash"},
"White":
{"votes":[
{"votes":448,"name":"mccain"},
{"votes":70,"name":"huckabee"},
{"votes":30,"name":"paul"},
{"votes":29,"name":"romney"}],
"total":577,"precincts":
{"total":23,"reporting":5},
"name":"White"},
"Porter":
{"votes":[],
"total":0,"precincts":
{"total":128,"reporting":0},
"name":"Porter"},
"Brown":
{"votes":[
{"votes":890,"name":"mccain"},
{"votes":106,"name":"romney"},
{"votes":105,"name":"huckabee"},
{"votes":45,"name":"paul"}],
"total":1146,"precincts":
{"total":12,"reporting":10},
"name":"Brown"},
"LaPorte":
{"votes":[],
"total":0,"precincts":
{"total":79,"reporting":0},
"name":"LaPorte"},
"Jay":
{"votes":[
{"votes":1123,"name":"mccain"},
{"votes":191,"name":"huckabee"},
{"votes":138,"name":"paul"},
{"votes":77,"name":"romney"}],
"total":1529,"precincts":
{"total":21,"reporting":21},
"name":"Jay"},
"Jennings":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Jennings"},
"Dearborn":
{"votes":[
{"votes":3470,"name":"mccain"},
{"votes":387,"name":"huckabee"},
{"votes":269,"name":"paul"},
{"votes":225,"name":"romney"}],
"total":4351,"precincts":
{"total":45,"reporting":42},
"name":"Dearborn"},
"Miami":
{"votes":[
{"votes":2545,"name":"mccain"},
{"votes":474,"name":"huckabee"},
{"votes":364,"name":"paul"},
{"votes":141,"name":"romney"}],
"total":3524,"precincts":
{"total":31,"reporting":30},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":3043,"name":"mccain"},
{"votes":325,"name":"huckabee"},
{"votes":253,"name":"paul"},
{"votes":178,"name":"romney"}],
"total":3799,"precincts":
{"total":38,"reporting":18},
"name":"Hancock"},
"Henry":
{"votes":[
{"votes":2808,"name":"mccain"},
{"votes":376,"name":"huckabee"},
{"votes":225,"name":"paul"},
{"votes":136,"name":"romney"}],
"total":3545,"precincts":
{"total":42,"reporting":35},
"name":"Henry"},
"Vigo":
{"votes":[
{"votes":2878,"name":"mccain"},
{"votes":435,"name":"huckabee"},
{"votes":301,"name":"paul"},
{"votes":133,"name":"romney"}],
"total":3747,"precincts":
{"total":87,"reporting":87},
"name":"Vigo"},
"Sullivan":
{"votes":[
{"votes":614,"name":"mccain"},
{"votes":103,"name":"huckabee"},
{"votes":44,"name":"paul"},
{"votes":23,"name":"romney"}],
"total":784,"precincts":
{"total":20,"reporting":19},
"name":"Sullivan"},
"Dubois":
{"votes":[
{"votes":806,"name":"mccain"},
{"votes":87,"name":"huckabee"},
{"votes":60,"name":"romney"},
{"votes":53,"name":"paul"}],
"total":1006,"precincts":
{"total":38,"reporting":26},
"name":"Dubois"},
"Newton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":187,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":8,"name":"romney"}],
"total":240,"precincts":
{"total":22,"reporting":3},
"name":"Washington"},
"Decatur":
{"votes":[
{"votes":760,"name":"mccain"},
{"votes":72,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":28,"name":"romney"}],
"total":901,"precincts":
{"total":20,"reporting":5},
"name":"Decatur"},
"Marion":
{"votes":[
{"votes":12137,"name":"mccain"},
{"votes":878,"name":"huckabee"},
{"votes":854,"name":"paul"},
{"votes":677,"name":"romney"}],
"total":14546,"precincts":
{"total":594,"reporting":199},
"name":"Marion"},
"Jasper":
{"votes":[
{"votes":1011,"name":"mccain"},
{"votes":148,"name":"huckabee"},
{"votes":98,"name":"paul"},
{"votes":73,"name":"romney"}],
"total":1330,"precincts":
{"total":29,"reporting":13},
"name":"Jasper"},
"Vermillion":
{"votes":[
{"votes":45,"name":"mccain"},
{"votes":10,"name":"huckabee"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"paul"}],
"total":66,"precincts":
{"total":17,"reporting":3},
"name":"Vermillion"},
"Allen":
{"votes":[
{"votes":13395,"name":"mccain"},
{"votes":2734,"name":"paul"},
{"votes":1967,"name":"huckabee"},
{"votes":1357,"name":"romney"}],
"total":19453,"precincts":
{"total":294,"reporting":271},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":609,"name":"mccain"},
{"votes":115,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":40,"name":"romney"}],
"total":804,"precincts":
{"total":13,"reporting":12},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":202,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":12,"name":"romney"}],
"total":250,"precincts":
{"total":21,"reporting":11},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":2416,"name":"mccain"},
{"votes":391,"name":"huckabee"},
{"votes":312,"name":"paul"},
{"votes":142,"name":"romney"}],
"total":3261,"precincts":
{"total":71,"reporting":42},
"name":"Howard"},
"Jefferson":
{"votes":[
{"votes":1112,"name":"mccain"},
{"votes":135,"name":"huckabee"},
{"votes":72,"name":"romney"},
{"votes":55,"name":"paul"}],
"total":1374,"precincts":
{"total":26,"reporting":26},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":1643,"name":"mccain"},
{"votes":271,"name":"huckabee"},
{"votes":133,"name":"paul"},
{"votes":84,"name":"romney"}],
"total":2131,"precincts":
{"total":22,"reporting":22},
"name":"Orange"},
"St. Joseph":
{"votes":[],
"total":0,"precincts":
{"total":226,"reporting":0},
"name":"St. Joseph"},
"Putnam":
{"votes":[
{"votes":1182,"name":"mccain"},
{"votes":175,"name":"huckabee"},
{"votes":88,"name":"paul"},
{"votes":64,"name":"romney"}],
"total":1509,"precincts":
{"total":29,"reporting":17},
"name":"Putnam"},
"Hamilton":
{"votes":[
{"votes":1627,"name":"mccain"},
{"votes":102,"name":"huckabee"},
{"votes":91,"name":"romney"},
{"votes":87,"name":"paul"}],
"total":1907,"precincts":
{"total":196,"reporting":1},
"name":"Hamilton"},
"Kosciusko":
{"votes":[
{"votes":4750,"name":"mccain"},
{"votes":978,"name":"huckabee"},
{"votes":638,"name":"paul"},
{"votes":361,"name":"romney"}],
"total":6727,"precincts":
{"total":65,"reporting":47},
"name":"Kosciusko"},
"Rush":
{"votes":[
{"votes":827,"name":"mccain"},
{"votes":93,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":33,"name":"romney"}],
"total":1021,"precincts":
{"total":20,"reporting":11},
"name":"Rush"},
"Johnson":
{"votes":[
{"votes":6367,"name":"mccain"},
{"votes":721,"name":"huckabee"},
{"votes":504,"name":"paul"},
{"votes":372,"name":"romney"}],
"total":7964,"precincts":
{"total":107,"reporting":75},
"name":"Johnson"},
"Whitley":
{"votes":[
{"votes":2029,"name":"mccain"},
{"votes":410,"name":"paul"},
{"votes":406,"name":"huckabee"},
{"votes":168,"name":"romney"}],
"total":3013,"precincts":
{"total":34,"reporting":34},
"name":"Whitley"},
"Greene":
{"votes":[
{"votes":446,"name":"mccain"},
{"votes":82,"name":"huckabee"},
{"votes":18,"name":"romney"},
{"votes":17,"name":"paul"}],
"total":563,"precincts":
{"total":32,"reporting":5},
"name":"Greene"},
"Ripley":
{"votes":[
{"votes":1842,"name":"mccain"},
{"votes":286,"name":"huckabee"},
{"votes":123,"name":"paul"},
{"votes":79,"name":"romney"}],
"total":2330,"precincts":
{"total":27,"reporting":27},
"name":"Ripley"},
"LaGrange":
{"votes":[
{"votes":538,"name":"mccain"},
{"votes":80,"name":"paul"},
{"votes":76,"name":"huckabee"},
{"votes":48,"name":"romney"}],
"total":742,"precincts":
{"total":16,"reporting":5},
"name":"LaGrange"},
"Ohio":
{"votes":[
{"votes":199,"name":"mccain"},
{"votes":32,"name":"huckabee"},
{"votes":12,"name":"romney"},
{"votes":11,"name":"paul"}],
"total":254,"precincts":
{"total":11,"reporting":11},
"name":"Ohio"},
"Gibson":
{"votes":[
{"votes":15,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"romney"}],
"total":23,"precincts":
{"total":38,"reporting":1},
"name":"Gibson"},
"Spencer":
{"votes":[
{"votes":328,"name":"mccain"},
{"votes":45,"name":"huckabee"},
{"votes":17,"name":"romney"},
{"votes":9,"name":"paul"}],
"total":399,"precincts":
{"total":25,"reporting":6},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":400,"name":"mccain"},
{"votes":65,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":22,"name":"romney"}],
"total":527,"precincts":
{"total":17,"reporting":6},
"name":"Fulton"},
"Madison":
{"votes":[
{"votes":4236,"name":"mccain"},
{"votes":470,"name":"huckabee"},
{"votes":314,"name":"paul"},
{"votes":233,"name":"romney"}],
"total":5253,"precincts":
{"total":111,"reporting":79},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":2972,"name":"mccain"},
{"votes":498,"name":"huckabee"},
{"votes":206,"name":"paul"},
{"votes":182,"name":"romney"}],
"total":3858,"precincts":
{"total":39,"reporting":36},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":2028,"name":"mccain"},
{"votes":231,"name":"huckabee"},
{"votes":98,"name":"romney"},
{"votes":91,"name":"paul"}],
"total":2448,"precincts":
{"total":73,"reporting":59},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":43,"name":"mccain"},
{"votes":7,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":59,"precincts":
{"total":20,"reporting":1},
"name":"Owen"},
"Huntington":
{"votes":[
{"votes":2198,"name":"mccain"},
{"votes":335,"name":"huckabee"},
{"votes":288,"name":"paul"},
{"votes":169,"name":"romney"}],
"total":2990,"precincts":
{"total":34,"reporting":22},
"name":"Huntington"},
"Clay":
{"votes":[
{"votes":1022,"name":"mccain"},
{"votes":206,"name":"huckabee"},
{"votes":99,"name":"paul"},
{"votes":38,"name":"romney"}],
"total":1365,"precincts":
{"total":23,"reporting":17},
"name":"Clay"},
"Blackford":
{"votes":[
{"votes":406,"name":"mccain"},
{"votes":60,"name":"huckabee"},
{"votes":48,"name":"paul"},
{"votes":28,"name":"romney"}],
"total":542,"precincts":
{"total":12,"reporting":12},
"name":"Blackford"},
"Cass":
{"votes":[
{"votes":2702,"name":"mccain"},
{"votes":367,"name":"huckabee"},
{"votes":218,"name":"paul"},
{"votes":141,"name":"romney"}],
"total":3428,"precincts":
{"total":39,"reporting":31},
"name":"Cass"},
"Delaware":
{"votes":[
{"votes":1049,"name":"mccain"},
{"votes":95,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":51,"name":"romney"}],
"total":1263,"precincts":
{"total":75,"reporting":8},
"name":"Delaware"},
"Fountain":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Fountain"},
"Lawrence":
{"votes":[
{"votes":1048,"name":"mccain"},
{"votes":209,"name":"paul"},
{"votes":182,"name":"huckabee"},
{"votes":67,"name":"romney"}],
"total":1506,"precincts":
{"total":39,"reporting":17},
"name":"Lawrence"},
"Elkhart":
{"votes":[],
"total":0,"precincts":
{"total":110,"reporting":0},
"name":"Elkhart"},
"Grant":
{"votes":[
{"votes":287,"name":"mccain"},
{"votes":15,"name":"huckabee"},
{"votes":9,"name":"romney"},
{"votes":7,"name":"paul"}],
"total":318,"precincts":
{"total":68,"reporting":1},
"name":"Grant"},
"Fayette":
{"votes":[
{"votes":166,"name":"mccain"},
{"votes":19,"name":"huckabee"},
{"votes":9,"name":"paul"},
{"votes":4,"name":"romney"}],
"total":198,"precincts":
{"total":28,"reporting":0},
"name":"Fayette"},
"Posey":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Posey"},
"Floyd":
{"votes":[
{"votes":2561,"name":"mccain"},
{"votes":270,"name":"huckabee"},
{"votes":130,"name":"romney"},
{"votes":121,"name":"paul"}],
"total":3082,"precincts":
{"total":60,"reporting":60},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":768,"name":"mccain"},
{"votes":95,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":24,"name":"romney"}],
"total":911,"precincts":
{"total":18,"reporting":18},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":1735,"name":"mccain"},
{"votes":403,"name":"huckabee"},
{"votes":292,"name":"paul"},
{"votes":141,"name":"romney"}],
"total":2571,"precincts":
{"total":25,"reporting":25},
"name":"Adams"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Franklin"},
"Switzerland":
{"votes":[
{"votes":223,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":13,"name":"romney"},
{"votes":6,"name":"paul"}],
"total":282,"precincts":
{"total":12,"reporting":12},
"name":"Switzerland"},
"Vanderburgh":
{"votes":[],
"total":0,"precincts":
{"total":131,"reporting":0},
"name":"Vanderburgh"},
"Marshall":
{"votes":[
{"votes":2262,"name":"mccain"},
{"votes":362,"name":"huckabee"},
{"votes":193,"name":"paul"},
{"votes":143,"name":"romney"}],
"total":2960,"precincts":
{"total":27,"reporting":27},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":1103,"name":"mccain"},
{"votes":197,"name":"huckabee"},
{"votes":97,"name":"paul"},
{"votes":65,"name":"romney"}],
"total":1462,"precincts":
{"total":19,"reporting":16},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":839,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":30,"name":"romney"}],
"total":963,"precincts":
{"total":36,"reporting":8},
"name":"Harrison"},
"Boone":
{"votes":[
{"votes":4744,"name":"mccain"},
{"votes":500,"name":"huckabee"},
{"votes":282,"name":"paul"},
{"votes":274,"name":"romney"}],
"total":5800,"precincts":
{"total":49,"reporting":49},
"name":"Boone"},
"Starke":
{"votes":[
{"votes":277,"name":"mccain"},
{"votes":36,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":16,"name":"romney"}],
"total":361,"precincts":
{"total":21,"reporting":7},
"name":"Starke"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":559,"reporting":0},
"name":"Lake"},
"Pulaski":
{"votes":[
{"votes":1197,"name":"mccain"},
{"votes":225,"name":"huckabee"},
{"votes":77,"name":"paul"},
{"votes":55,"name":"romney"}],
"total":1554,"precincts":
{"total":15,"reporting":15},
"name":"Pulaski"},
"Hendricks":
{"votes":[],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Hendricks"},
"Tippecanoe":
{"votes":[],
"total":0,"precincts":
{"total":91,"reporting":0},
"name":"Tippecanoe"},
"Parke":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Parke"},
"DeKalb":
{"votes":[
{"votes":2483,"name":"mccain"},
{"votes":498,"name":"paul"},
{"votes":489,"name":"huckabee"},
{"votes":227,"name":"romney"}],
"total":3697,"precincts":
{"total":39,"reporting":39},
"name":"DeKalb"},
"Crawford":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Crawford"},
"Noble":
{"votes":[
{"votes":1719,"name":"mccain"},
{"votes":336,"name":"paul"},
{"votes":317,"name":"huckabee"},
{"votes":139,"name":"romney"}],
"total":2511,"precincts":
{"total":29,"reporting":23},
"name":"Noble"},
"Wells":
{"votes":[
{"votes":1468,"name":"mccain"},
{"votes":282,"name":"huckabee"},
{"votes":232,"name":"paul"},
{"votes":111,"name":"romney"}],
"total":2093,"precincts":
{"total":22,"reporting":22},
"name":"Wells"},
"Knox":
{"votes":[
{"votes":1738,"name":"mccain"},
{"votes":214,"name":"huckabee"},
{"votes":73,"name":"romney"},
{"votes":72,"name":"paul"}],
"total":2097,"precincts":
{"total":36,"reporting":36},
"name":"Knox"},
"Bartholomew":
{"votes":[
{"votes":3956,"name":"mccain"},
{"votes":532,"name":"huckabee"},
{"votes":294,"name":"romney"},
{"votes":193,"name":"paul"}],
"total":4975,"precincts":
{"total":67,"reporting":52},
"name":"Bartholomew"},
"Tipton":
{"votes":[
{"votes":1603,"name":"mccain"},
{"votes":260,"name":"huckabee"},
{"votes":165,"name":"paul"},
{"votes":66,"name":"romney"}],
"total":2094,"precincts":
{"total":17,"reporting":17},
"name":"Tipton"},
"Benton":
{"votes":[
{"votes":283,"name":"mccain"},
{"votes":44,"name":"huckabee"},
{"votes":35,"name":"paul"},
{"votes":22,"name":"romney"}],
"total":384,"precincts":
{"total":15,"reporting":5},
"name":"Benton"},
"Morgan":
{"votes":[
{"votes":1428,"name":"mccain"},
{"votes":196,"name":"huckabee"},
{"votes":79,"name":"paul"},
{"votes":72,"name":"romney"}],
"total":1775,"precincts":
{"total":48,"reporting":17},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Martin"},
"Warrick":
{"votes":[
{"votes":667,"name":"mccain"},
{"votes":71,"name":"huckabee"},
{"votes":47,"name":"romney"},
{"votes":42,"name":"paul"}],
"total":827,"precincts":
{"total":59,"reporting":7},
"name":"Warrick"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Scott"},
"Randolph":
{"votes":[
{"votes":2093,"name":"mccain"},
{"votes":356,"name":"huckabee"},
{"votes":155,"name":"paul"},
{"votes":140,"name":"romney"}],
"total":2744,"precincts":
{"total":29,"reporting":29},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":8,"name":"mccain"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"paul"}],
"total":12,"precincts":
{"total":71,"reporting":1},
"name":"Monroe"},
"Steuben":
{"votes":[
{"votes":1770,"name":"mccain"},
{"votes":332,"name":"paul"},
{"votes":249,"name":"huckabee"},
{"votes":151,"name":"romney"}],
"total":2502,"precincts":
{"total":19,"reporting":19},
"name":"Steuben"}}})