GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":236649,"name":"mccain"},
{"votes":31824,"name":"huckabee"},
{"votes":23443,"name":"paul"},
{"votes":14781,"name":"romney"}],
"name":"Indiana","precincts":
{"total":5230,"reporting":3628},
"delegates":57,"date":"05-06"},
"state":"IN","party":"gop","total":306697,"locals":
{"Daviess":
{"votes":[
{"votes":2375,"name":"mccain"},
{"votes":317,"name":"huckabee"},
{"votes":92,"name":"paul"},
{"votes":87,"name":"romney"}],
"total":2871,"precincts":
{"total":28,"reporting":24},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":3648,"name":"mccain"},
{"votes":426,"name":"huckabee"},
{"votes":280,"name":"paul"},
{"votes":210,"name":"romney"}],
"total":4564,"precincts":
{"total":39,"reporting":39},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":1503,"name":"mccain"},
{"votes":251,"name":"huckabee"},
{"votes":113,"name":"paul"},
{"votes":97,"name":"romney"}],
"total":1964,"precincts":
{"total":27,"reporting":12},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Wayne"},
"Wabash":
{"votes":[
{"votes":2859,"name":"mccain"},
{"votes":537,"name":"paul"},
{"votes":515,"name":"huckabee"},
{"votes":184,"name":"romney"}],
"total":4095,"precincts":
{"total":25,"reporting":25},
"name":"Wabash"},
"White":
{"votes":[
{"votes":1805,"name":"mccain"},
{"votes":263,"name":"huckabee"},
{"votes":150,"name":"paul"},
{"votes":131,"name":"romney"}],
"total":2349,"precincts":
{"total":23,"reporting":23},
"name":"White"},
"Porter":
{"votes":[
{"votes":1598,"name":"mccain"},
{"votes":263,"name":"paul"},
{"votes":155,"name":"huckabee"},
{"votes":85,"name":"romney"}],
"total":2101,"precincts":
{"total":128,"reporting":34},
"name":"Porter"},
"Brown":
{"votes":[
{"votes":1076,"name":"mccain"},
{"votes":144,"name":"huckabee"},
{"votes":84,"name":"paul"},
{"votes":57,"name":"romney"}],
"total":1361,"precincts":
{"total":12,"reporting":12},
"name":"Brown"},
"LaPorte":
{"votes":[],
"total":0,"precincts":
{"total":79,"reporting":0},
"name":"LaPorte"},
"Jay":
{"votes":[
{"votes":1123,"name":"mccain"},
{"votes":191,"name":"huckabee"},
{"votes":138,"name":"paul"},
{"votes":77,"name":"romney"}],
"total":1529,"precincts":
{"total":21,"reporting":21},
"name":"Jay"},
"Jennings":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Jennings"},
"Dearborn":
{"votes":[
{"votes":3827,"name":"mccain"},
{"votes":432,"name":"huckabee"},
{"votes":287,"name":"paul"},
{"votes":246,"name":"romney"}],
"total":4792,"precincts":
{"total":45,"reporting":45},
"name":"Dearborn"},
"Miami":
{"votes":[
{"votes":2747,"name":"mccain"},
{"votes":510,"name":"huckabee"},
{"votes":391,"name":"paul"},
{"votes":153,"name":"romney"}],
"total":3801,"precincts":
{"total":31,"reporting":31},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":6800,"name":"mccain"},
{"votes":708,"name":"huckabee"},
{"votes":573,"name":"paul"},
{"votes":412,"name":"romney"}],
"total":8493,"precincts":
{"total":38,"reporting":37},
"name":"Hancock"},
"Henry":
{"votes":[
{"votes":3882,"name":"mccain"},
{"votes":484,"name":"huckabee"},
{"votes":300,"name":"paul"},
{"votes":185,"name":"romney"}],
"total":4851,"precincts":
{"total":42,"reporting":42},
"name":"Henry"},
"Vigo":
{"votes":[
{"votes":2878,"name":"mccain"},
{"votes":435,"name":"huckabee"},
{"votes":301,"name":"paul"},
{"votes":133,"name":"romney"}],
"total":3747,"precincts":
{"total":87,"reporting":87},
"name":"Vigo"},
"Sullivan":
{"votes":[
{"votes":653,"name":"mccain"},
{"votes":122,"name":"huckabee"},
{"votes":51,"name":"paul"},
{"votes":23,"name":"romney"}],
"total":849,"precincts":
{"total":20,"reporting":20},
"name":"Sullivan"},
"Dubois":
{"votes":[
{"votes":1160,"name":"mccain"},
{"votes":133,"name":"huckabee"},
{"votes":86,"name":"romney"},
{"votes":76,"name":"paul"}],
"total":1455,"precincts":
{"total":38,"reporting":38},
"name":"Dubois"},
"Newton":
{"votes":[
{"votes":655,"name":"mccain"},
{"votes":71,"name":"huckabee"},
{"votes":57,"name":"paul"},
{"votes":33,"name":"romney"}],
"total":816,"precincts":
{"total":18,"reporting":11},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":1273,"name":"mccain"},
{"votes":357,"name":"huckabee"},
{"votes":54,"name":"romney"},
{"votes":51,"name":"paul"}],
"total":1735,"precincts":
{"total":22,"reporting":13},
"name":"Washington"},
"Decatur":
{"votes":[
{"votes":2407,"name":"mccain"},
{"votes":319,"name":"huckabee"},
{"votes":136,"name":"paul"},
{"votes":125,"name":"romney"}],
"total":2987,"precincts":
{"total":20,"reporting":20},
"name":"Decatur"},
"Marion":
{"votes":[
{"votes":27707,"name":"mccain"},
{"votes":2051,"name":"huckabee"},
{"votes":1926,"name":"paul"},
{"votes":1627,"name":"romney"}],
"total":33311,"precincts":
{"total":594,"reporting":455},
"name":"Marion"},
"Jasper":
{"votes":[
{"votes":2454,"name":"mccain"},
{"votes":427,"name":"huckabee"},
{"votes":298,"name":"paul"},
{"votes":146,"name":"romney"}],
"total":3325,"precincts":
{"total":29,"reporting":29},
"name":"Jasper"},
"Vermillion":
{"votes":[
{"votes":248,"name":"mccain"},
{"votes":59,"name":"huckabee"},
{"votes":26,"name":"paul"},
{"votes":19,"name":"romney"}],
"total":352,"precincts":
{"total":17,"reporting":13},
"name":"Vermillion"},
"Allen":
{"votes":[
{"votes":13842,"name":"mccain"},
{"votes":2821,"name":"paul"},
{"votes":2044,"name":"huckabee"},
{"votes":1415,"name":"romney"}],
"total":20122,"precincts":
{"total":294,"reporting":294},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":664,"name":"mccain"},
{"votes":123,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":41,"name":"romney"}],
"total":873,"precincts":
{"total":13,"reporting":13},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":363,"name":"mccain"},
{"votes":54,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":19,"name":"romney"}],
"total":461,"precincts":
{"total":21,"reporting":21},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":3102,"name":"mccain"},
{"votes":509,"name":"huckabee"},
{"votes":410,"name":"paul"},
{"votes":186,"name":"romney"}],
"total":4207,"precincts":
{"total":71,"reporting":52},
"name":"Howard"},
"Jefferson":
{"votes":[
{"votes":1112,"name":"mccain"},
{"votes":135,"name":"huckabee"},
{"votes":72,"name":"romney"},
{"votes":55,"name":"paul"}],
"total":1374,"precincts":
{"total":26,"reporting":26},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":1643,"name":"mccain"},
{"votes":271,"name":"huckabee"},
{"votes":133,"name":"paul"},
{"votes":84,"name":"romney"}],
"total":2131,"precincts":
{"total":22,"reporting":22},
"name":"Orange"},
"St. Joseph":
{"votes":[
{"votes":6197,"name":"mccain"},
{"votes":854,"name":"paul"},
{"votes":825,"name":"huckabee"},
{"votes":405,"name":"romney"}],
"total":8281,"precincts":
{"total":226,"reporting":226},
"name":"St. Joseph"},
"Putnam":
{"votes":[
{"votes":2260,"name":"mccain"},
{"votes":323,"name":"huckabee"},
{"votes":186,"name":"paul"},
{"votes":123,"name":"romney"}],
"total":2892,"precincts":
{"total":29,"reporting":29},
"name":"Putnam"},
"Hamilton":
{"votes":[
{"votes":10751,"name":"mccain"},
{"votes":864,"name":"huckabee"},
{"votes":766,"name":"paul"},
{"votes":738,"name":"romney"}],
"total":13119,"precincts":
{"total":196,"reporting":69},
"name":"Hamilton"},
"Kosciusko":
{"votes":[
{"votes":5424,"name":"mccain"},
{"votes":1110,"name":"huckabee"},
{"votes":772,"name":"paul"},
{"votes":413,"name":"romney"}],
"total":7719,"precincts":
{"total":65,"reporting":65},
"name":"Kosciusko"},
"Rush":
{"votes":[
{"votes":1490,"name":"mccain"},
{"votes":178,"name":"huckabee"},
{"votes":137,"name":"paul"},
{"votes":70,"name":"romney"}],
"total":1875,"precincts":
{"total":20,"reporting":20},
"name":"Rush"},
"Johnson":
{"votes":[
{"votes":9637,"name":"mccain"},
{"votes":1051,"name":"huckabee"},
{"votes":718,"name":"paul"},
{"votes":574,"name":"romney"}],
"total":11980,"precincts":
{"total":107,"reporting":107},
"name":"Johnson"},
"Whitley":
{"votes":[
{"votes":2029,"name":"mccain"},
{"votes":410,"name":"paul"},
{"votes":406,"name":"huckabee"},
{"votes":168,"name":"romney"}],
"total":3013,"precincts":
{"total":34,"reporting":34},
"name":"Whitley"},
"Greene":
{"votes":[
{"votes":2217,"name":"mccain"},
{"votes":371,"name":"huckabee"},
{"votes":146,"name":"paul"},
{"votes":88,"name":"romney"}],
"total":2822,"precincts":
{"total":32,"reporting":32},
"name":"Greene"},
"Ripley":
{"votes":[
{"votes":1842,"name":"mccain"},
{"votes":286,"name":"huckabee"},
{"votes":123,"name":"paul"},
{"votes":79,"name":"romney"}],
"total":2330,"precincts":
{"total":27,"reporting":27},
"name":"Ripley"},
"LaGrange":
{"votes":[
{"votes":1464,"name":"mccain"},
{"votes":239,"name":"huckabee"},
{"votes":201,"name":"paul"},
{"votes":116,"name":"romney"}],
"total":2020,"precincts":
{"total":16,"reporting":16},
"name":"LaGrange"},
"Ohio":
{"votes":[
{"votes":199,"name":"mccain"},
{"votes":32,"name":"huckabee"},
{"votes":12,"name":"romney"},
{"votes":11,"name":"paul"}],
"total":254,"precincts":
{"total":11,"reporting":11},
"name":"Ohio"},
"Gibson":
{"votes":[
{"votes":138,"name":"mccain"},
{"votes":17,"name":"huckabee"},
{"votes":9,"name":"romney"},
{"votes":8,"name":"paul"}],
"total":172,"precincts":
{"total":38,"reporting":8},
"name":"Gibson"},
"Spencer":
{"votes":[
{"votes":1209,"name":"mccain"},
{"votes":177,"name":"huckabee"},
{"votes":64,"name":"romney"},
{"votes":53,"name":"paul"}],
"total":1503,"precincts":
{"total":25,"reporting":25},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":1094,"name":"mccain"},
{"votes":169,"name":"huckabee"},
{"votes":103,"name":"paul"},
{"votes":62,"name":"romney"}],
"total":1428,"precincts":
{"total":17,"reporting":17},
"name":"Fulton"},
"Madison":
{"votes":[
{"votes":6718,"name":"mccain"},
{"votes":785,"name":"huckabee"},
{"votes":549,"name":"paul"},
{"votes":367,"name":"romney"}],
"total":8419,"precincts":
{"total":111,"reporting":110},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":3088,"name":"mccain"},
{"votes":505,"name":"huckabee"},
{"votes":219,"name":"paul"},
{"votes":184,"name":"romney"}],
"total":3996,"precincts":
{"total":39,"reporting":39},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":2412,"name":"mccain"},
{"votes":273,"name":"huckabee"},
{"votes":113,"name":"romney"},
{"votes":110,"name":"paul"}],
"total":2908,"precincts":
{"total":73,"reporting":65},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":952,"name":"mccain"},
{"votes":158,"name":"huckabee"},
{"votes":131,"name":"paul"},
{"votes":43,"name":"romney"}],
"total":1284,"precincts":
{"total":20,"reporting":20},
"name":"Owen"},
"Huntington":
{"votes":[
{"votes":3695,"name":"mccain"},
{"votes":553,"name":"huckabee"},
{"votes":503,"name":"paul"},
{"votes":290,"name":"romney"}],
"total":5041,"precincts":
{"total":34,"reporting":34},
"name":"Huntington"},
"Clay":
{"votes":[
{"votes":1333,"name":"mccain"},
{"votes":270,"name":"huckabee"},
{"votes":132,"name":"paul"},
{"votes":53,"name":"romney"}],
"total":1788,"precincts":
{"total":23,"reporting":23},
"name":"Clay"},
"Blackford":
{"votes":[
{"votes":406,"name":"mccain"},
{"votes":60,"name":"huckabee"},
{"votes":48,"name":"paul"},
{"votes":28,"name":"romney"}],
"total":542,"precincts":
{"total":12,"reporting":12},
"name":"Blackford"},
"Cass":
{"votes":[
{"votes":2934,"name":"mccain"},
{"votes":408,"name":"huckabee"},
{"votes":243,"name":"paul"},
{"votes":153,"name":"romney"}],
"total":3738,"precincts":
{"total":39,"reporting":39},
"name":"Cass"},
"Delaware":
{"votes":[
{"votes":5450,"name":"mccain"},
{"votes":591,"name":"huckabee"},
{"votes":415,"name":"paul"},
{"votes":303,"name":"romney"}],
"total":6759,"precincts":
{"total":75,"reporting":75},
"name":"Delaware"},
"Fountain":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Fountain"},
"Lawrence":
{"votes":[
{"votes":2996,"name":"mccain"},
{"votes":461,"name":"huckabee"},
{"votes":451,"name":"paul"},
{"votes":157,"name":"romney"}],
"total":4065,"precincts":
{"total":39,"reporting":39},
"name":"Lawrence"},
"Elkhart":
{"votes":[
{"votes":12123,"name":"mccain"},
{"votes":2168,"name":"huckabee"},
{"votes":1333,"name":"paul"},
{"votes":763,"name":"romney"}],
"total":16387,"precincts":
{"total":110,"reporting":106},
"name":"Elkhart"},
"Grant":
{"votes":[
{"votes":5066,"name":"mccain"},
{"votes":852,"name":"huckabee"},
{"votes":428,"name":"paul"},
{"votes":322,"name":"romney"}],
"total":6668,"precincts":
{"total":68,"reporting":67},
"name":"Grant"},
"Fayette":
{"votes":[
{"votes":1256,"name":"mccain"},
{"votes":167,"name":"huckabee"},
{"votes":78,"name":"paul"},
{"votes":45,"name":"romney"}],
"total":1546,"precincts":
{"total":28,"reporting":28},
"name":"Fayette"},
"Posey":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Posey"},
"Floyd":
{"votes":[
{"votes":2561,"name":"mccain"},
{"votes":270,"name":"huckabee"},
{"votes":130,"name":"romney"},
{"votes":121,"name":"paul"}],
"total":3082,"precincts":
{"total":60,"reporting":60},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":768,"name":"mccain"},
{"votes":95,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":24,"name":"romney"}],
"total":911,"precincts":
{"total":18,"reporting":18},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":1735,"name":"mccain"},
{"votes":403,"name":"huckabee"},
{"votes":292,"name":"paul"},
{"votes":141,"name":"romney"}],
"total":2571,"precincts":
{"total":25,"reporting":25},
"name":"Adams"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Franklin"},
"Switzerland":
{"votes":[
{"votes":223,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":13,"name":"romney"},
{"votes":6,"name":"paul"}],
"total":282,"precincts":
{"total":12,"reporting":12},
"name":"Switzerland"},
"Vanderburgh":
{"votes":[
{"votes":4048,"name":"mccain"},
{"votes":538,"name":"paul"},
{"votes":380,"name":"huckabee"},
{"votes":251,"name":"romney"}],
"total":5217,"precincts":
{"total":131,"reporting":124},
"name":"Vanderburgh"},
"Marshall":
{"votes":[
{"votes":2262,"name":"mccain"},
{"votes":362,"name":"huckabee"},
{"votes":193,"name":"paul"},
{"votes":143,"name":"romney"}],
"total":2960,"precincts":
{"total":27,"reporting":27},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":1466,"name":"mccain"},
{"votes":254,"name":"huckabee"},
{"votes":117,"name":"paul"},
{"votes":85,"name":"romney"}],
"total":1922,"precincts":
{"total":19,"reporting":19},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":1879,"name":"mccain"},
{"votes":233,"name":"huckabee"},
{"votes":94,"name":"paul"},
{"votes":73,"name":"romney"}],
"total":2279,"precincts":
{"total":36,"reporting":36},
"name":"Harrison"},
"Boone":
{"votes":[
{"votes":4744,"name":"mccain"},
{"votes":500,"name":"huckabee"},
{"votes":282,"name":"paul"},
{"votes":274,"name":"romney"}],
"total":5800,"precincts":
{"total":49,"reporting":49},
"name":"Boone"},
"Starke":
{"votes":[
{"votes":819,"name":"mccain"},
{"votes":127,"name":"huckabee"},
{"votes":118,"name":"paul"},
{"votes":49,"name":"romney"}],
"total":1113,"precincts":
{"total":21,"reporting":21},
"name":"Starke"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":559,"reporting":0},
"name":"Lake"},
"Pulaski":
{"votes":[
{"votes":1197,"name":"mccain"},
{"votes":225,"name":"huckabee"},
{"votes":77,"name":"paul"},
{"votes":55,"name":"romney"}],
"total":1554,"precincts":
{"total":15,"reporting":15},
"name":"Pulaski"},
"Hendricks":
{"votes":[],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Hendricks"},
"Tippecanoe":
{"votes":[],
"total":0,"precincts":
{"total":91,"reporting":0},
"name":"Tippecanoe"},
"Parke":
{"votes":[
{"votes":1264,"name":"mccain"},
{"votes":234,"name":"huckabee"},
{"votes":93,"name":"paul"},
{"votes":58,"name":"romney"}],
"total":1649,"precincts":
{"total":17,"reporting":17},
"name":"Parke"},
"DeKalb":
{"votes":[
{"votes":2558,"name":"mccain"},
{"votes":502,"name":"paul"},
{"votes":500,"name":"huckabee"},
{"votes":230,"name":"romney"}],
"total":3790,"precincts":
{"total":39,"reporting":39},
"name":"DeKalb"},
"Crawford":
{"votes":[
{"votes":436,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":16,"name":"paul"},
{"votes":10,"name":"romney"}],
"total":510,"precincts":
{"total":17,"reporting":17},
"name":"Crawford"},
"Noble":
{"votes":[
{"votes":2122,"name":"mccain"},
{"votes":403,"name":"paul"},
{"votes":382,"name":"huckabee"},
{"votes":179,"name":"romney"}],
"total":3086,"precincts":
{"total":29,"reporting":29},
"name":"Noble"},
"Wells":
{"votes":[
{"votes":1468,"name":"mccain"},
{"votes":282,"name":"huckabee"},
{"votes":232,"name":"paul"},
{"votes":111,"name":"romney"}],
"total":2093,"precincts":
{"total":22,"reporting":22},
"name":"Wells"},
"Knox":
{"votes":[
{"votes":1738,"name":"mccain"},
{"votes":214,"name":"huckabee"},
{"votes":73,"name":"romney"},
{"votes":72,"name":"paul"}],
"total":2097,"precincts":
{"total":36,"reporting":36},
"name":"Knox"},
"Bartholomew":
{"votes":[
{"votes":4999,"name":"mccain"},
{"votes":658,"name":"huckabee"},
{"votes":380,"name":"romney"},
{"votes":266,"name":"paul"}],
"total":6303,"precincts":
{"total":67,"reporting":67},
"name":"Bartholomew"},
"Tipton":
{"votes":[
{"votes":1603,"name":"mccain"},
{"votes":260,"name":"huckabee"},
{"votes":165,"name":"paul"},
{"votes":66,"name":"romney"}],
"total":2094,"precincts":
{"total":17,"reporting":17},
"name":"Tipton"},
"Benton":
{"votes":[
{"votes":1124,"name":"mccain"},
{"votes":177,"name":"huckabee"},
{"votes":120,"name":"paul"},
{"votes":82,"name":"romney"}],
"total":1503,"precincts":
{"total":15,"reporting":15},
"name":"Benton"},
"Morgan":
{"votes":[
{"votes":2391,"name":"mccain"},
{"votes":331,"name":"huckabee"},
{"votes":152,"name":"paul"},
{"votes":122,"name":"romney"}],
"total":2996,"precincts":
{"total":48,"reporting":24},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Martin"},
"Warrick":
{"votes":[
{"votes":2581,"name":"mccain"},
{"votes":352,"name":"huckabee"},
{"votes":233,"name":"paul"},
{"votes":167,"name":"romney"}],
"total":3333,"precincts":
{"total":59,"reporting":56},
"name":"Warrick"},
"Scott":
{"votes":[
{"votes":477,"name":"mccain"},
{"votes":43,"name":"huckabee"},
{"votes":29,"name":"paul"},
{"votes":18,"name":"romney"}],
"total":567,"precincts":
{"total":16,"reporting":16},
"name":"Scott"},
"Randolph":
{"votes":[
{"votes":2093,"name":"mccain"},
{"votes":356,"name":"huckabee"},
{"votes":155,"name":"paul"},
{"votes":140,"name":"romney"}],
"total":2744,"precincts":
{"total":29,"reporting":29},
"name":"Randolph"},
"Monroe":
{"votes":[
{"votes":539,"name":"mccain"},
{"votes":64,"name":"paul"},
{"votes":44,"name":"huckabee"},
{"votes":27,"name":"romney"}],
"total":674,"precincts":
{"total":71,"reporting":17},
"name":"Monroe"},
"Steuben":
{"votes":[
{"votes":1770,"name":"mccain"},
{"votes":332,"name":"paul"},
{"votes":249,"name":"huckabee"},
{"votes":151,"name":"romney"}],
"total":2502,"precincts":
{"total":19,"reporting":19},
"name":"Steuben"}}})