GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":81345,"name":"mccain"},
{"votes":11187,"name":"huckabee"},
{"votes":8460,"name":"paul"},
{"votes":5200,"name":"romney"}],
"name":"Indiana","precincts":
{"total":5230,"reporting":1252},
"delegates":57,"date":"05-06"},
"state":"IN","party":"gop","total":106192,"locals":
{"Daviess":
{"votes":[
{"votes":960,"name":"mccain"},
{"votes":92,"name":"huckabee"},
{"votes":38,"name":"romney"},
{"votes":33,"name":"paul"}],
"total":1123,"precincts":
{"total":28,"reporting":10},
"name":"Daviess"},
"Shelby":
{"votes":[
{"votes":2702,"name":"mccain"},
{"votes":305,"name":"huckabee"},
{"votes":180,"name":"paul"},
{"votes":146,"name":"romney"}],
"total":3333,"precincts":
{"total":39,"reporting":29},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":94,"name":"mccain"},
{"votes":15,"name":"huckabee"},
{"votes":8,"name":"paul"},
{"votes":5,"name":"romney"}],
"total":122,"precincts":
{"total":27,"reporting":1},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":58,"reporting":0},
"name":"Wayne"},
"Wabash":
{"votes":[
{"votes":2430,"name":"mccain"},
{"votes":438,"name":"huckabee"},
{"votes":438,"name":"paul"},
{"votes":150,"name":"romney"}],
"total":3456,"precincts":
{"total":25,"reporting":22},
"name":"Wabash"},
"White":
{"votes":[
{"votes":448,"name":"mccain"},
{"votes":70,"name":"huckabee"},
{"votes":30,"name":"paul"},
{"votes":29,"name":"romney"}],
"total":577,"precincts":
{"total":23,"reporting":5},
"name":"White"},
"Porter":
{"votes":[],
"total":0,"precincts":
{"total":128,"reporting":0},
"name":"Porter"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Brown"},
"LaPorte":
{"votes":[],
"total":0,"precincts":
{"total":79,"reporting":0},
"name":"LaPorte"},
"Jay":
{"votes":[
{"votes":1123,"name":"mccain"},
{"votes":191,"name":"huckabee"},
{"votes":138,"name":"paul"},
{"votes":77,"name":"romney"}],
"total":1529,"precincts":
{"total":21,"reporting":21},
"name":"Jay"},
"Jennings":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Jennings"},
"Dearborn":
{"votes":[
{"votes":441,"name":"mccain"},
{"votes":32,"name":"huckabee"},
{"votes":31,"name":"paul"},
{"votes":25,"name":"romney"}],
"total":529,"precincts":
{"total":45,"reporting":5},
"name":"Dearborn"},
"Miami":
{"votes":[
{"votes":120,"name":"mccain"},
{"votes":12,"name":"huckabee"},
{"votes":5,"name":"paul"},
{"votes":3,"name":"romney"}],
"total":140,"precincts":
{"total":31,"reporting":25},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":2165,"name":"mccain"},
{"votes":226,"name":"huckabee"},
{"votes":191,"name":"paul"},
{"votes":140,"name":"romney"}],
"total":2722,"precincts":
{"total":38,"reporting":13},
"name":"Hancock"},
"Henry":
{"votes":[
{"votes":2808,"name":"mccain"},
{"votes":376,"name":"huckabee"},
{"votes":225,"name":"paul"},
{"votes":136,"name":"romney"}],
"total":3545,"precincts":
{"total":42,"reporting":35},
"name":"Henry"},
"Vigo":
{"votes":[
{"votes":2729,"name":"mccain"},
{"votes":405,"name":"huckabee"},
{"votes":287,"name":"paul"},
{"votes":129,"name":"romney"}],
"total":3550,"precincts":
{"total":87,"reporting":78},
"name":"Vigo"},
"Sullivan":
{"votes":[
{"votes":517,"name":"mccain"},
{"votes":96,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":18,"name":"romney"}],
"total":674,"precincts":
{"total":20,"reporting":17},
"name":"Sullivan"},
"Dubois":
{"votes":[
{"votes":296,"name":"mccain"},
{"votes":25,"name":"huckabee"},
{"votes":21,"name":"romney"},
{"votes":10,"name":"paul"}],
"total":352,"precincts":
{"total":38,"reporting":7},
"name":"Dubois"},
"Newton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Newton"},
"Washington":
{"votes":[
{"votes":187,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":8,"name":"romney"}],
"total":240,"precincts":
{"total":22,"reporting":3},
"name":"Washington"},
"Decatur":
{"votes":[
{"votes":760,"name":"mccain"},
{"votes":72,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":28,"name":"romney"}],
"total":901,"precincts":
{"total":20,"reporting":5},
"name":"Decatur"},
"Marion":
{"votes":[
{"votes":3529,"name":"mccain"},
{"votes":238,"name":"paul"},
{"votes":211,"name":"huckabee"},
{"votes":204,"name":"romney"}],
"total":4182,"precincts":
{"total":594,"reporting":67},
"name":"Marion"},
"Jasper":
{"votes":[
{"votes":345,"name":"mccain"},
{"votes":53,"name":"huckabee"},
{"votes":29,"name":"paul"},
{"votes":20,"name":"romney"}],
"total":447,"precincts":
{"total":29,"reporting":2},
"name":"Jasper"},
"Vermillion":
{"votes":[
{"votes":45,"name":"mccain"},
{"votes":10,"name":"huckabee"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"paul"}],
"total":66,"precincts":
{"total":17,"reporting":3},
"name":"Vermillion"},
"Allen":
{"votes":[
{"votes":9847,"name":"mccain"},
{"votes":1930,"name":"paul"},
{"votes":1435,"name":"huckabee"},
{"votes":953,"name":"romney"}],
"total":14165,"precincts":
{"total":294,"reporting":201},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":259,"name":"mccain"},
{"votes":59,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":16,"name":"romney"}],
"total":359,"precincts":
{"total":13,"reporting":8},
"name":"Warren"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Jackson"},
"Howard":
{"votes":[
{"votes":1372,"name":"mccain"},
{"votes":217,"name":"huckabee"},
{"votes":176,"name":"paul"},
{"votes":92,"name":"romney"}],
"total":1857,"precincts":
{"total":71,"reporting":23},
"name":"Howard"},
"Jefferson":
{"votes":[
{"votes":943,"name":"mccain"},
{"votes":107,"name":"huckabee"},
{"votes":55,"name":"romney"},
{"votes":51,"name":"paul"}],
"total":1156,"precincts":
{"total":26,"reporting":23},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":1458,"name":"mccain"},
{"votes":232,"name":"huckabee"},
{"votes":115,"name":"paul"},
{"votes":72,"name":"romney"}],
"total":1877,"precincts":
{"total":22,"reporting":20},
"name":"Orange"},
"St. Joseph":
{"votes":[],
"total":0,"precincts":
{"total":226,"reporting":0},
"name":"St. Joseph"},
"Putnam":
{"votes":[
{"votes":562,"name":"mccain"},
{"votes":69,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":30,"name":"romney"}],
"total":704,"precincts":
{"total":29,"reporting":9},
"name":"Putnam"},
"Hamilton":
{"votes":[],
"total":0,"precincts":
{"total":196,"reporting":0},
"name":"Hamilton"},
"Kosciusko":
{"votes":[
{"votes":1592,"name":"mccain"},
{"votes":337,"name":"huckabee"},
{"votes":180,"name":"paul"},
{"votes":127,"name":"romney"}],
"total":2236,"precincts":
{"total":65,"reporting":13},
"name":"Kosciusko"},
"Rush":
{"votes":[
{"votes":617,"name":"mccain"},
{"votes":66,"name":"huckabee"},
{"votes":52,"name":"paul"},
{"votes":24,"name":"romney"}],
"total":759,"precincts":
{"total":20,"reporting":9},
"name":"Rush"},
"Johnson":
{"votes":[
{"votes":4446,"name":"mccain"},
{"votes":524,"name":"huckabee"},
{"votes":386,"name":"paul"},
{"votes":264,"name":"romney"}],
"total":5620,"precincts":
{"total":107,"reporting":53},
"name":"Johnson"},
"Whitley":
{"votes":[
{"votes":2029,"name":"mccain"},
{"votes":410,"name":"paul"},
{"votes":406,"name":"huckabee"},
{"votes":168,"name":"romney"}],
"total":3013,"precincts":
{"total":34,"reporting":34},
"name":"Whitley"},
"Greene":
{"votes":[
{"votes":446,"name":"mccain"},
{"votes":82,"name":"huckabee"},
{"votes":18,"name":"romney"},
{"votes":17,"name":"paul"}],
"total":563,"precincts":
{"total":32,"reporting":5},
"name":"Greene"},
"Ripley":
{"votes":[
{"votes":1278,"name":"mccain"},
{"votes":190,"name":"huckabee"},
{"votes":80,"name":"paul"},
{"votes":60,"name":"romney"}],
"total":1608,"precincts":
{"total":27,"reporting":19},
"name":"Ripley"},
"LaGrange":
{"votes":[
{"votes":234,"name":"mccain"},
{"votes":34,"name":"huckabee"},
{"votes":28,"name":"paul"},
{"votes":27,"name":"romney"}],
"total":323,"precincts":
{"total":16,"reporting":2},
"name":"LaGrange"},
"Ohio":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Ohio"},
"Gibson":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Gibson"},
"Spencer":
{"votes":[
{"votes":170,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"paul"}],
"total":194,"precincts":
{"total":25,"reporting":1},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":400,"name":"mccain"},
{"votes":65,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":22,"name":"romney"}],
"total":527,"precincts":
{"total":17,"reporting":6},
"name":"Fulton"},
"Madison":
{"votes":[
{"votes":2858,"name":"mccain"},
{"votes":232,"name":"huckabee"},
{"votes":197,"name":"paul"},
{"votes":165,"name":"romney"}],
"total":3452,"precincts":
{"total":111,"reporting":56},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":2374,"name":"mccain"},
{"votes":403,"name":"huckabee"},
{"votes":159,"name":"paul"},
{"votes":150,"name":"romney"}],
"total":3086,"precincts":
{"total":39,"reporting":27},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":1312,"name":"mccain"},
{"votes":140,"name":"huckabee"},
{"votes":62,"name":"romney"},
{"votes":51,"name":"paul"}],
"total":1565,"precincts":
{"total":73,"reporting":40},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":43,"name":"mccain"},
{"votes":7,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":59,"precincts":
{"total":20,"reporting":1},
"name":"Owen"},
"Huntington":
{"votes":[
{"votes":2198,"name":"mccain"},
{"votes":335,"name":"huckabee"},
{"votes":288,"name":"paul"},
{"votes":169,"name":"romney"}],
"total":2990,"precincts":
{"total":34,"reporting":22},
"name":"Huntington"},
"Clay":
{"votes":[
{"votes":619,"name":"mccain"},
{"votes":124,"name":"huckabee"},
{"votes":61,"name":"paul"},
{"votes":24,"name":"romney"}],
"total":828,"precincts":
{"total":23,"reporting":10},
"name":"Clay"},
"Blackford":
{"votes":[
{"votes":406,"name":"mccain"},
{"votes":60,"name":"huckabee"},
{"votes":48,"name":"paul"},
{"votes":28,"name":"romney"}],
"total":542,"precincts":
{"total":12,"reporting":12},
"name":"Blackford"},
"Cass":
{"votes":[
{"votes":2702,"name":"mccain"},
{"votes":367,"name":"huckabee"},
{"votes":218,"name":"paul"},
{"votes":141,"name":"romney"}],
"total":3428,"precincts":
{"total":39,"reporting":31},
"name":"Cass"},
"Delaware":
{"votes":[],
"total":0,"precincts":
{"total":75,"reporting":0},
"name":"Delaware"},
"Fountain":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Fountain"},
"Lawrence":
{"votes":[
{"votes":639,"name":"mccain"},
{"votes":118,"name":"huckabee"},
{"votes":116,"name":"paul"},
{"votes":36,"name":"romney"}],
"total":909,"precincts":
{"total":39,"reporting":10},
"name":"Lawrence"},
"Elkhart":
{"votes":[],
"total":0,"precincts":
{"total":110,"reporting":0},
"name":"Elkhart"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":68,"reporting":0},
"name":"Grant"},
"Fayette":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Fayette"},
"Posey":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Posey"},
"Floyd":
{"votes":[
{"votes":1070,"name":"mccain"},
{"votes":105,"name":"huckabee"},
{"votes":54,"name":"paul"},
{"votes":48,"name":"romney"}],
"total":1277,"precincts":
{"total":60,"reporting":31},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":768,"name":"mccain"},
{"votes":95,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":24,"name":"romney"}],
"total":911,"precincts":
{"total":18,"reporting":18},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":608,"name":"mccain"},
{"votes":128,"name":"huckabee"},
{"votes":101,"name":"paul"},
{"votes":45,"name":"romney"}],
"total":882,"precincts":
{"total":25,"reporting":7},
"name":"Adams"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Franklin"},
"Switzerland":
{"votes":[
{"votes":23,"name":"mccain"},
{"votes":8,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":34,"precincts":
{"total":12,"reporting":4},
"name":"Switzerland"},
"Vanderburgh":
{"votes":[],
"total":0,"precincts":
{"total":131,"reporting":0},
"name":"Vanderburgh"},
"Marshall":
{"votes":[
{"votes":453,"name":"mccain"},
{"votes":74,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":19,"name":"romney"}],
"total":573,"precincts":
{"total":27,"reporting":3},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":678,"name":"mccain"},
{"votes":112,"name":"huckabee"},
{"votes":60,"name":"paul"},
{"votes":43,"name":"romney"}],
"total":893,"precincts":
{"total":19,"reporting":10},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":839,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":30,"name":"romney"}],
"total":963,"precincts":
{"total":36,"reporting":8},
"name":"Harrison"},
"Boone":
{"votes":[
{"votes":3407,"name":"mccain"},
{"votes":354,"name":"huckabee"},
{"votes":206,"name":"romney"},
{"votes":204,"name":"paul"}],
"total":4171,"precincts":
{"total":49,"reporting":16},
"name":"Boone"},
"Starke":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Starke"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":559,"reporting":0},
"name":"Lake"},
"Pulaski":
{"votes":[
{"votes":815,"name":"mccain"},
{"votes":175,"name":"huckabee"},
{"votes":60,"name":"paul"},
{"votes":46,"name":"romney"}],
"total":1096,"precincts":
{"total":15,"reporting":9},
"name":"Pulaski"},
"Hendricks":
{"votes":[],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Hendricks"},
"Tippecanoe":
{"votes":[],
"total":0,"precincts":
{"total":91,"reporting":0},
"name":"Tippecanoe"},
"Parke":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Parke"},
"DeKalb":
{"votes":[
{"votes":1365,"name":"mccain"},
{"votes":242,"name":"huckabee"},
{"votes":233,"name":"paul"},
{"votes":119,"name":"romney"}],
"total":1959,"precincts":
{"total":39,"reporting":21},
"name":"DeKalb"},
"Crawford":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Crawford"},
"Noble":
{"votes":[
{"votes":896,"name":"mccain"},
{"votes":173,"name":"paul"},
{"votes":146,"name":"huckabee"},
{"votes":62,"name":"romney"}],
"total":1277,"precincts":
{"total":29,"reporting":11},
"name":"Noble"},
"Wells":
{"votes":[
{"votes":1468,"name":"mccain"},
{"votes":282,"name":"huckabee"},
{"votes":232,"name":"paul"},
{"votes":111,"name":"romney"}],
"total":2093,"precincts":
{"total":22,"reporting":22},
"name":"Wells"},
"Knox":
{"votes":[
{"votes":1684,"name":"mccain"},
{"votes":206,"name":"huckabee"},
{"votes":70,"name":"romney"},
{"votes":69,"name":"paul"}],
"total":2029,"precincts":
{"total":36,"reporting":34},
"name":"Knox"},
"Bartholomew":
{"votes":[
{"votes":2845,"name":"mccain"},
{"votes":385,"name":"huckabee"},
{"votes":208,"name":"romney"},
{"votes":130,"name":"paul"}],
"total":3568,"precincts":
{"total":67,"reporting":35},
"name":"Bartholomew"},
"Tipton":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Tipton"},
"Benton":
{"votes":[
{"votes":170,"name":"mccain"},
{"votes":24,"name":"huckabee"},
{"votes":20,"name":"paul"},
{"votes":11,"name":"romney"}],
"total":225,"precincts":
{"total":15,"reporting":2},
"name":"Benton"},
"Morgan":
{"votes":[
{"votes":1428,"name":"mccain"},
{"votes":196,"name":"huckabee"},
{"votes":79,"name":"paul"},
{"votes":72,"name":"romney"}],
"total":1775,"precincts":
{"total":48,"reporting":17},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Martin"},
"Warrick":
{"votes":[],
"total":0,"precincts":
{"total":59,"reporting":0},
"name":"Warrick"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Scott"},
"Randolph":
{"votes":[
{"votes":812,"name":"mccain"},
{"votes":117,"name":"huckabee"},
{"votes":54,"name":"romney"},
{"votes":48,"name":"paul"}],
"total":1031,"precincts":
{"total":29,"reporting":6},
"name":"Randolph"},
"Monroe":
{"votes":[],
"total":0,"precincts":
{"total":71,"reporting":0},
"name":"Monroe"},
"Steuben":
{"votes":[
{"votes":1513,"name":"mccain"},
{"votes":273,"name":"paul"},
{"votes":211,"name":"huckabee"},
{"votes":130,"name":"romney"}],
"total":2127,"precincts":
{"total":19,"reporting":15},
"name":"Steuben"}}})