GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":28744,"name":"mccain"},
{"votes":2753,"name":"paul"},
{"votes":2407,"name":"uncommitted-r"},
{"votes":2141,"name":"huckabee"},
{"votes":1908,"name":"romney"},
{"votes":736,"name":"giuliani"},
{"votes":304,"name":"keyes"}],
"name":"Kentucky","precincts":
{"total":3532,"reporting":559},
"delegates":45,"date":"05-20"},
"state":"KY","party":"gop","total":38993,"locals":
{"Metcalfe":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Metcalfe"},
"Daviess":
{"votes":[],
"total":0,"precincts":
{"total":84,"reporting":0},
"name":"Daviess"},
"Russell":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Russell"},
"Shelby":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Shelby"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Union"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":26,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":40,"precincts":
{"total":19,"reporting":1},
"name":"Wayne"},
"Robertson":
{"votes":[
{"votes":23,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":32,"precincts":
{"total":5,"reporting":5},
"name":"Robertson"},
"Bourbon":
{"votes":[
{"votes":20,"name":"mccain"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"romney"}],
"total":26,"precincts":
{"total":18,"reporting":1},
"name":"Bourbon"},
"Nicholas":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Nicholas"},
"Powell":
{"votes":[
{"votes":17,"name":"mccain"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"romney"}],
"total":19,"precincts":
{"total":11,"reporting":1},
"name":"Powell"},
"Boyle":
{"votes":[
{"votes":43,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":1,"name":"paul"},
{"votes":1,"name":"romney"}],
"total":50,"precincts":
{"total":25,"reporting":0},
"name":"Boyle"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Henderson"},
"Menifee":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Menifee"},
"Breckinridge":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Breckinridge"},
"Casey":
{"votes":[
{"votes":477,"name":"mccain"},
{"votes":36,"name":"huckabee"},
{"votes":27,"name":"uncommitted-r"},
{"votes":19,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":5,"name":"keyes"},
{"votes":4,"name":"giuliani"}],
"total":577,"precincts":
{"total":15,"reporting":6},
"name":"Casey"},
"Adair":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Adair"},
"McCreary":
{"votes":[
{"votes":50,"name":"mccain"},
{"votes":4,"name":"huckabee"},
{"votes":3,"name":"uncommitted-r"},
{"votes":2,"name":"paul"}],
"total":59,"precincts":
{"total":18,"reporting":1},
"name":"McCreary"},
"Nelson":
{"votes":[
{"votes":27,"name":"mccain"},
{"votes":7,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"}],
"total":43,"precincts":
{"total":26,"reporting":1},
"name":"Nelson"},
"Henry":
{"votes":[
{"votes":23,"name":"mccain"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"giuliani"}],
"total":26,"precincts":
{"total":20,"reporting":0},
"name":"Henry"},
"Barren":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Barren"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Webster"},
"Bullitt":
{"votes":[
{"votes":53,"name":"mccain"},
{"votes":10,"name":"huckabee"},
{"votes":5,"name":"paul"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"}],
"total":73,"precincts":
{"total":44,"reporting":1},
"name":"Bullitt"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Washington"},
"Trimble":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Trimble"},
"Marion":
{"votes":[
{"votes":217,"name":"mccain"},
{"votes":26,"name":"huckabee"},
{"votes":21,"name":"uncommitted-r"},
{"votes":21,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":7,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":306,"precincts":
{"total":16,"reporting":13},
"name":"Marion"},
"Hickman":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Hickman"},
"Allen":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Allen"},
"Warren":
{"votes":[],
"total":0,"precincts":
{"total":63,"reporting":0},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":192,"name":"mccain"},
{"votes":18,"name":"huckabee"},
{"votes":11,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":235,"precincts":
{"total":37,"reporting":20},
"name":"Perry"},
"Graves":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Graves"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Grant"},
"Caldwell":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Caldwell"},
"Oldham":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Oldham"},
"Mason":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Mason"},
"Wolfe":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Wolfe"},
"Anderson":
{"votes":[
{"votes":21,"name":"mccain"},
{"votes":3,"name":"romney"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"paul"}],
"total":30,"precincts":
{"total":14,"reporting":1},
"name":"Anderson"},
"Jefferson":
{"votes":[
{"votes":21728,"name":"mccain"},
{"votes":2108,"name":"paul"},
{"votes":1821,"name":"uncommitted-r"},
{"votes":1553,"name":"romney"},
{"votes":1516,"name":"huckabee"},
{"votes":607,"name":"giuliani"},
{"votes":214,"name":"keyes"}],
"total":29547,"precincts":
{"total":513,"reporting":342},
"name":"Jefferson"},
"Crittenden":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Crittenden"},
"Butler":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Butler"},
"Breathitt":
{"votes":[
{"votes":27,"name":"mccain"},
{"votes":4,"name":"huckabee"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"giuliani"}],
"total":35,"precincts":
{"total":21,"reporting":5},
"name":"Breathitt"},
"Kenton":
{"votes":[
{"votes":414,"name":"mccain"},
{"votes":36,"name":"uncommitted-r"},
{"votes":35,"name":"paul"},
{"votes":28,"name":"romney"},
{"votes":21,"name":"huckabee"},
{"votes":13,"name":"giuliani"},
{"votes":5,"name":"keyes"}],
"total":552,"precincts":
{"total":108,"reporting":8},
"name":"Kenton"},
"Lee":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Lee"},
"Boyd":
{"votes":[
{"votes":104,"name":"mccain"},
{"votes":12,"name":"huckabee"},
{"votes":5,"name":"uncommitted-r"},
{"votes":5,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":133,"precincts":
{"total":47,"reporting":1},
"name":"Boyd"},
"Rockcastle":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Rockcastle"},
"McLean":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"McLean"},
"Johnson":
{"votes":[
{"votes":75,"name":"mccain"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"paul"}],
"total":88,"precincts":
{"total":31,"reporting":1},
"name":"Johnson"},
"Hopkins":
{"votes":[],
"total":0,"precincts":
{"total":40,"reporting":0},
"name":"Hopkins"},
"Whitley":
{"votes":[],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Whitley"},
"Woodford":
{"votes":[
{"votes":20,"name":"mccain"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"keyes"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"uncommitted-r"}],
"total":29,"precincts":
{"total":16,"reporting":1},
"name":"Woodford"},
"Green":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Green"},
"Clay":
{"votes":[
{"votes":532,"name":"mccain"},
{"votes":62,"name":"uncommitted-r"},
{"votes":60,"name":"huckabee"},
{"votes":42,"name":"paul"},
{"votes":19,"name":"romney"},
{"votes":5,"name":"keyes"},
{"votes":3,"name":"giuliani"}],
"total":723,"precincts":
{"total":20,"reporting":8},
"name":"Clay"},
"Ohio":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Ohio"},
"Spencer":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Spencer"},
"Fulton":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Fulton"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":56,"reporting":0},
"name":"Madison"},
"Taylor":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Taylor"},
"Clinton":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"paul"}],
"total":25,"precincts":
{"total":26,"reporting":1},
"name":"Clark"},
"Owen":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Owen"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Todd"},
"Grayson":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Grayson"},
"Hart":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Hart"},
"Carlisle":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Carlisle"},
"Lyon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Lyon"},
"Boone":
{"votes":[],
"total":0,"precincts":
{"total":60,"reporting":0},
"name":"Boone"},
"Pendleton":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Pendleton"},
"Magoffin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Magoffin"},
"Jessamine":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Jessamine"},
"Letcher":
{"votes":[
{"votes":103,"name":"mccain"},
{"votes":10,"name":"uncommitted-r"},
{"votes":9,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"giuliani"}],
"total":132,"precincts":
{"total":32,"reporting":5},
"name":"Letcher"},
"Jackson":
{"votes":[
{"votes":61,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":74,"precincts":
{"total":14,"reporting":1},
"name":"Jackson"},
"Lawrence":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Lawrence"},
"Trigg":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Trigg"},
"McCracken":
{"votes":[],
"total":0,"precincts":
{"total":54,"reporting":0},
"name":"McCracken"},
"Fayette":
{"votes":[
{"votes":1978,"name":"mccain"},
{"votes":357,"name":"paul"},
{"votes":180,"name":"uncommitted-r"},
{"votes":177,"name":"huckabee"},
{"votes":155,"name":"romney"},
{"votes":54,"name":"giuliani"},
{"votes":43,"name":"keyes"}],
"total":2944,"precincts":
{"total":274,"reporting":74},
"name":"Fayette"},
"Floyd":
{"votes":[
{"votes":19,"name":"mccain"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"romney"}],
"total":23,"precincts":
{"total":42,"reporting":1},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":36,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":3,"name":"uncommitted-r"}],
"total":42,"precincts":
{"total":57,"reporting":1},
"name":"Pike"},
"Lincoln":
{"votes":[
{"votes":67,"name":"uncommitted-r"},
{"votes":27,"name":"mccain"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"romney"}],
"total":98,"precincts":
{"total":17,"reporting":0},
"name":"Lincoln"},
"Ballard":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Ballard"},
"Livingston":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Livingston"},
"Harlan":
{"votes":[
{"votes":317,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":14,"name":"uncommitted-r"},
{"votes":13,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":1,"name":"giuliani"}],
"total":387,"precincts":
{"total":35,"reporting":17},
"name":"Harlan"},
"Franklin":
{"votes":[
{"votes":68,"name":"mccain"},
{"votes":8,"name":"huckabee"},
{"votes":8,"name":"paul"},
{"votes":5,"name":"romney"},
{"votes":5,"name":"uncommitted-r"}],
"total":94,"precincts":
{"total":44,"reporting":0},
"name":"Franklin"},
"Owsley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Owsley"},
"Bell":
{"votes":[
{"votes":754,"name":"mccain"},
{"votes":86,"name":"huckabee"},
{"votes":43,"name":"uncommitted-r"},
{"votes":36,"name":"romney"},
{"votes":28,"name":"paul"},
{"votes":8,"name":"keyes"},
{"votes":6,"name":"giuliani"}],
"total":961,"precincts":
{"total":33,"reporting":23},
"name":"Bell"},
"Marshall":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":8,"name":"mccain"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"paul"}],
"total":10,"precincts":
{"total":11,"reporting":1},
"name":"Carroll"},
"Bath":
{"votes":[
{"votes":3,"name":"paul"},
{"votes":2,"name":"mccain"},
{"votes":1,"name":"huckabee"}],
"total":6,"precincts":
{"total":12,"reporting":1},
"name":"Bath"},
"Harrison":
{"votes":[
{"votes":102,"name":"mccain"},
{"votes":15,"name":"paul"},
{"votes":9,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":6,"name":"uncommitted-r"},
{"votes":3,"name":"giuliani"}],
"total":141,"precincts":
{"total":16,"reporting":5},
"name":"Harrison"},
"Campbell":
{"votes":[
{"votes":155,"name":"mccain"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"huckabee"},
{"votes":5,"name":"paul"},
{"votes":3,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":182,"precincts":
{"total":66,"reporting":1},
"name":"Campbell"},
"Laurel":
{"votes":[
{"votes":324,"name":"mccain"},
{"votes":27,"name":"uncommitted-r"},
{"votes":21,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":5,"name":"romney"},
{"votes":5,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":390,"precincts":
{"total":45,"reporting":1},
"name":"Laurel"},
"Mercer":
{"votes":[
{"votes":18,"name":"mccain"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"paul"}],
"total":25,"precincts":
{"total":17,"reporting":0},
"name":"Mercer"},
"Gallatin":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Gallatin"},
"Cumberland":
{"votes":[
{"votes":3,"name":"mccain"}],
"total":3,"precincts":
{"total":9,"reporting":1},
"name":"Cumberland"},
"Pulaski":
{"votes":[],
"total":0,"precincts":
{"total":57,"reporting":0},
"name":"Pulaski"},
"Rowan":
{"votes":[
{"votes":13,"name":"mccain"},
{"votes":4,"name":"paul"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"uncommitted-r"}],
"total":21,"precincts":
{"total":18,"reporting":0},
"name":"Rowan"},
"Elliott":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Elliott"},
"Estill":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Estill"},
"Christian":
{"votes":[],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Christian"},
"Greenup":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Greenup"},
"Leslie":
{"votes":[
{"votes":420,"name":"mccain"},
{"votes":33,"name":"huckabee"},
{"votes":25,"name":"uncommitted-r"},
{"votes":22,"name":"paul"},
{"votes":14,"name":"romney"},
{"votes":8,"name":"giuliani"},
{"votes":3,"name":"keyes"}],
"total":525,"precincts":
{"total":17,"reporting":5},
"name":"Leslie"},
"Knox":
{"votes":[
{"votes":77,"name":"mccain"},
{"votes":7,"name":"uncommitted-r"},
{"votes":7,"name":"huckabee"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"paul"}],
"total":94,"precincts":
{"total":30,"reporting":1},
"name":"Knox"},
"Hancock":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Hancock"},
"Hardin":
{"votes":[
{"votes":109,"name":"mccain"},
{"votes":10,"name":"paul"},
{"votes":9,"name":"huckabee"},
{"votes":6,"name":"giuliani"},
{"votes":5,"name":"keyes"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":146,"precincts":
{"total":55,"reporting":1},
"name":"Hardin"},
"LaRue":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"LaRue"},
"Bracken":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Bracken"},
"Meade":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Meade"},
"Morgan":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Morgan"},
"Martin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Martin"},
"Garrard":
{"votes":[
{"votes":35,"name":"mccain"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"paul"}],
"total":43,"precincts":
{"total":13,"reporting":1},
"name":"Garrard"},
"Edmonson":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Edmonson"},
"Simpson":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Simpson"},
"Muhlenberg":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Muhlenberg"},
"Carter":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Carter"},
"Knott":
{"votes":[
{"votes":4,"name":"mccain"}],
"total":4,"precincts":
{"total":30,"reporting":1},
"name":"Knott"},
"Lewis":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Lewis"},
"Calloway":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Calloway"},
"Fleming":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Fleming"},
"Logan":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Logan"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Scott"},
"Monroe":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Monroe"}}})