GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":125394,"name":"mccain"},
{"votes":14138,"name":"huckabee"},
{"votes":11699,"name":"paul"},
{"votes":9362,"name":"uncommitted-r"},
{"votes":7933,"name":"romney"},
{"votes":2734,"name":"giuliani"},
{"votes":1848,"name":"keyes"}],
"name":"Kentucky","precincts":
{"total":3532,"reporting":3139},
"delegates":45,"date":"05-20"},
"state":"KY","party":"gop","total":173108,"locals":
{"Metcalfe":
{"votes":[
{"votes":411,"name":"mccain"},
{"votes":44,"name":"huckabee"},
{"votes":33,"name":"paul"},
{"votes":20,"name":"romney"},
{"votes":12,"name":"giuliani"},
{"votes":11,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"}],
"total":534,"precincts":
{"total":12,"reporting":10},
"name":"Metcalfe"},
"Daviess":
{"votes":[
{"votes":2194,"name":"mccain"},
{"votes":275,"name":"huckabee"},
{"votes":248,"name":"uncommitted-r"},
{"votes":138,"name":"romney"},
{"votes":103,"name":"paul"},
{"votes":50,"name":"keyes"},
{"votes":47,"name":"giuliani"}],
"total":3055,"precincts":
{"total":84,"reporting":60},
"name":"Daviess"},
"Russell":
{"votes":[
{"votes":53,"name":"mccain"},
{"votes":5,"name":"uncommitted-r"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"paul"}],
"total":61,"precincts":
{"total":16,"reporting":1},
"name":"Russell"},
"Shelby":
{"votes":[
{"votes":1272,"name":"mccain"},
{"votes":165,"name":"huckabee"},
{"votes":146,"name":"paul"},
{"votes":107,"name":"romney"},
{"votes":75,"name":"uncommitted-r"},
{"votes":23,"name":"keyes"},
{"votes":20,"name":"giuliani"}],
"total":1808,"precincts":
{"total":33,"reporting":33},
"name":"Shelby"},
"Union":
{"votes":[
{"votes":97,"name":"mccain"},
{"votes":15,"name":"huckabee"},
{"votes":10,"name":"uncommitted-r"},
{"votes":9,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":3,"name":"keyes"},
{"votes":2,"name":"giuliani"}],
"total":144,"precincts":
{"total":16,"reporting":16},
"name":"Union"},
"Montgomery":
{"votes":[
{"votes":392,"name":"mccain"},
{"votes":67,"name":"huckabee"},
{"votes":30,"name":"paul"},
{"votes":25,"name":"romney"},
{"votes":25,"name":"uncommitted-r"},
{"votes":6,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":546,"precincts":
{"total":18,"reporting":18},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":658,"name":"mccain"},
{"votes":101,"name":"huckabee"},
{"votes":35,"name":"romney"},
{"votes":33,"name":"uncommitted-r"},
{"votes":29,"name":"paul"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"keyes"}],
"total":866,"precincts":
{"total":19,"reporting":19},
"name":"Wayne"},
"Robertson":
{"votes":[
{"votes":23,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"romney"}],
"total":30,"precincts":
{"total":5,"reporting":5},
"name":"Robertson"},
"Bourbon":
{"votes":[
{"votes":222,"name":"mccain"},
{"votes":33,"name":"paul"},
{"votes":31,"name":"huckabee"},
{"votes":25,"name":"uncommitted-r"},
{"votes":15,"name":"romney"},
{"votes":5,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":333,"precincts":
{"total":18,"reporting":18},
"name":"Bourbon"},
"Nicholas":
{"votes":[
{"votes":52,"name":"mccain"},
{"votes":16,"name":"paul"},
{"votes":7,"name":"uncommitted-r"},
{"votes":6,"name":"huckabee"},
{"votes":5,"name":"romney"},
{"votes":1,"name":"giuliani"}],
"total":87,"precincts":
{"total":5,"reporting":5},
"name":"Nicholas"},
"Powell":
{"votes":[
{"votes":251,"name":"mccain"},
{"votes":23,"name":"huckabee"},
{"votes":15,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":8,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":4,"name":"giuliani"}],
"total":313,"precincts":
{"total":11,"reporting":11},
"name":"Powell"},
"Boyle":
{"votes":[
{"votes":842,"name":"mccain"},
{"votes":90,"name":"huckabee"},
{"votes":84,"name":"paul"},
{"votes":65,"name":"uncommitted-r"},
{"votes":59,"name":"romney"},
{"votes":18,"name":"giuliani"},
{"votes":10,"name":"keyes"}],
"total":1168,"precincts":
{"total":25,"reporting":25},
"name":"Boyle"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Henderson"},
"Menifee":
{"votes":[
{"votes":68,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":6,"name":"uncommitted-r"},
{"votes":4,"name":"romney"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":96,"precincts":
{"total":6,"reporting":6},
"name":"Menifee"},
"Breckinridge":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Breckinridge"},
"Casey":
{"votes":[
{"votes":1431,"name":"mccain"},
{"votes":131,"name":"huckabee"},
{"votes":75,"name":"uncommitted-r"},
{"votes":49,"name":"romney"},
{"votes":49,"name":"paul"},
{"votes":14,"name":"keyes"},
{"votes":13,"name":"giuliani"}],
"total":1762,"precincts":
{"total":15,"reporting":15},
"name":"Casey"},
"Adair":
{"votes":[
{"votes":1162,"name":"mccain"},
{"votes":100,"name":"keyes"},
{"votes":79,"name":"giuliani"},
{"votes":79,"name":"paul"},
{"votes":50,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":2,"name":"uncommitted-r"}],
"total":1478,"precincts":
{"total":16,"reporting":15},
"name":"Adair"},
"McCreary":
{"votes":[
{"votes":921,"name":"mccain"},
{"votes":168,"name":"huckabee"},
{"votes":53,"name":"uncommitted-r"},
{"votes":41,"name":"romney"},
{"votes":34,"name":"paul"},
{"votes":13,"name":"keyes"},
{"votes":9,"name":"giuliani"}],
"total":1239,"precincts":
{"total":18,"reporting":18},
"name":"McCreary"},
"Nelson":
{"votes":[
{"votes":667,"name":"mccain"},
{"votes":215,"name":"paul"},
{"votes":87,"name":"huckabee"},
{"votes":72,"name":"romney"},
{"votes":68,"name":"uncommitted-r"},
{"votes":25,"name":"giuliani"},
{"votes":11,"name":"keyes"}],
"total":1145,"precincts":
{"total":26,"reporting":26},
"name":"Nelson"},
"Henry":
{"votes":[
{"votes":389,"name":"mccain"},
{"votes":60,"name":"huckabee"},
{"votes":44,"name":"paul"},
{"votes":29,"name":"romney"},
{"votes":24,"name":"uncommitted-r"},
{"votes":10,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":558,"precincts":
{"total":20,"reporting":20},
"name":"Henry"},
"Barren":
{"votes":[
{"votes":94,"name":"mccain"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":101,"precincts":
{"total":24,"reporting":1},
"name":"Barren"},
"Webster":
{"votes":[
{"votes":1,"name":"keyes"},
{"votes":1,"name":"mccain"}],
"total":2,"precincts":
{"total":14,"reporting":1},
"name":"Webster"},
"Bullitt":
{"votes":[
{"votes":1160,"name":"mccain"},
{"votes":184,"name":"huckabee"},
{"votes":129,"name":"paul"},
{"votes":73,"name":"romney"},
{"votes":73,"name":"uncommitted-r"},
{"votes":28,"name":"giuliani"},
{"votes":9,"name":"keyes"}],
"total":1656,"precincts":
{"total":44,"reporting":42},
"name":"Bullitt"},
"Washington":
{"votes":[
{"votes":246,"name":"mccain"},
{"votes":29,"name":"paul"},
{"votes":25,"name":"huckabee"},
{"votes":18,"name":"uncommitted-r"},
{"votes":16,"name":"romney"},
{"votes":4,"name":"keyes"},
{"votes":4,"name":"giuliani"}],
"total":342,"precincts":
{"total":14,"reporting":14},
"name":"Washington"},
"Trimble":
{"votes":[
{"votes":135,"name":"mccain"},
{"votes":16,"name":"huckabee"},
{"votes":12,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":6,"name":"giuliani"},
{"votes":5,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":184,"precincts":
{"total":12,"reporting":12},
"name":"Trimble"},
"Marion":
{"votes":[
{"votes":272,"name":"mccain"},
{"votes":38,"name":"huckabee"},
{"votes":31,"name":"paul"},
{"votes":28,"name":"uncommitted-r"},
{"votes":23,"name":"romney"},
{"votes":7,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":401,"precincts":
{"total":16,"reporting":16},
"name":"Marion"},
"Hickman":
{"votes":[
{"votes":52,"name":"mccain"},
{"votes":11,"name":"huckabee"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"giuliani"}],
"total":73,"precincts":
{"total":6,"reporting":6},
"name":"Hickman"},
"Allen":
{"votes":[
{"votes":485,"name":"mccain"},
{"votes":76,"name":"huckabee"},
{"votes":46,"name":"paul"},
{"votes":27,"name":"romney"},
{"votes":8,"name":"keyes"},
{"votes":7,"name":"giuliani"},
{"votes":1,"name":"uncommitted-r"}],
"total":650,"precincts":
{"total":13,"reporting":5},
"name":"Allen"},
"Warren":
{"votes":[
{"votes":2314,"name":"mccain"},
{"votes":437,"name":"paul"},
{"votes":314,"name":"huckabee"},
{"votes":177,"name":"romney"},
{"votes":133,"name":"uncommitted-r"},
{"votes":51,"name":"keyes"},
{"votes":48,"name":"giuliani"}],
"total":3474,"precincts":
{"total":63,"reporting":40},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":380,"name":"mccain"},
{"votes":32,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":11,"name":"uncommitted-r"},
{"votes":9,"name":"giuliani"},
{"votes":8,"name":"romney"},
{"votes":4,"name":"keyes"}],
"total":463,"precincts":
{"total":37,"reporting":36},
"name":"Perry"},
"Graves":
{"votes":[
{"votes":419,"name":"mccain"},
{"votes":88,"name":"huckabee"},
{"votes":36,"name":"uncommitted-r"},
{"votes":21,"name":"paul"},
{"votes":20,"name":"romney"},
{"votes":6,"name":"giuliani"},
{"votes":3,"name":"keyes"}],
"total":593,"precincts":
{"total":30,"reporting":30},
"name":"Graves"},
"Grant":
{"votes":[
{"votes":351,"name":"mccain"},
{"votes":74,"name":"huckabee"},
{"votes":38,"name":"romney"},
{"votes":34,"name":"uncommitted-r"},
{"votes":30,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":9,"name":"keyes"}],
"total":547,"precincts":
{"total":23,"reporting":23},
"name":"Grant"},
"Caldwell":
{"votes":[
{"votes":210,"name":"mccain"},
{"votes":43,"name":"huckabee"},
{"votes":16,"name":"uncommitted-r"},
{"votes":15,"name":"paul"},
{"votes":12,"name":"romney"},
{"votes":7,"name":"giuliani"},
{"votes":3,"name":"keyes"}],
"total":306,"precincts":
{"total":12,"reporting":12},
"name":"Caldwell"},
"Oldham":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Oldham"},
"Mason":
{"votes":[
{"votes":284,"name":"mccain"},
{"votes":41,"name":"huckabee"},
{"votes":29,"name":"romney"},
{"votes":27,"name":"paul"},
{"votes":26,"name":"uncommitted-r"},
{"votes":11,"name":"keyes"},
{"votes":7,"name":"giuliani"}],
"total":425,"precincts":
{"total":20,"reporting":20},
"name":"Mason"},
"Wolfe":
{"votes":[
{"votes":51,"name":"mccain"},
{"votes":14,"name":"huckabee"},
{"votes":5,"name":"romney"},
{"votes":5,"name":"paul"},
{"votes":3,"name":"keyes"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"uncommitted-r"}],
"total":81,"precincts":
{"total":8,"reporting":8},
"name":"Wolfe"},
"Anderson":
{"votes":[
{"votes":666,"name":"mccain"},
{"votes":100,"name":"huckabee"},
{"votes":83,"name":"paul"},
{"votes":47,"name":"uncommitted-r"},
{"votes":38,"name":"romney"},
{"votes":21,"name":"giuliani"},
{"votes":11,"name":"keyes"}],
"total":966,"precincts":
{"total":14,"reporting":14},
"name":"Anderson"},
"Jefferson":
{"votes":[
{"votes":30551,"name":"mccain"},
{"votes":2971,"name":"paul"},
{"votes":2617,"name":"uncommitted-r"},
{"votes":2167,"name":"huckabee"},
{"votes":2146,"name":"romney"},
{"votes":813,"name":"giuliani"},
{"votes":298,"name":"keyes"}],
"total":41563,"precincts":
{"total":513,"reporting":484},
"name":"Jefferson"},
"Crittenden":
{"votes":[
{"votes":344,"name":"mccain"},
{"votes":81,"name":"huckabee"},
{"votes":23,"name":"uncommitted-r"},
{"votes":15,"name":"romney"},
{"votes":14,"name":"paul"},
{"votes":5,"name":"keyes"},
{"votes":3,"name":"giuliani"}],
"total":485,"precincts":
{"total":12,"reporting":12},
"name":"Crittenden"},
"Butler":
{"votes":[
{"votes":622,"name":"mccain"},
{"votes":85,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":37,"name":"uncommitted-r"},
{"votes":31,"name":"romney"},
{"votes":15,"name":"giuliani"},
{"votes":9,"name":"keyes"}],
"total":867,"precincts":
{"total":12,"reporting":12},
"name":"Butler"},
"Breathitt":
{"votes":[
{"votes":75,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":10,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":4,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"giuliani"}],
"total":121,"precincts":
{"total":21,"reporting":21},
"name":"Breathitt"},
"Kenton":
{"votes":[
{"votes":5098,"name":"mccain"},
{"votes":549,"name":"romney"},
{"votes":436,"name":"huckabee"},
{"votes":435,"name":"paul"},
{"votes":425,"name":"uncommitted-r"},
{"votes":126,"name":"keyes"},
{"votes":96,"name":"giuliani"}],
"total":7165,"precincts":
{"total":108,"reporting":107},
"name":"Kenton"},
"Lee":
{"votes":[
{"votes":389,"name":"mccain"},
{"votes":25,"name":"huckabee"},
{"votes":15,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":12,"name":"uncommitted-r"},
{"votes":7,"name":"keyes"},
{"votes":4,"name":"giuliani"}],
"total":465,"precincts":
{"total":10,"reporting":10},
"name":"Lee"},
"Boyd":
{"votes":[
{"votes":2085,"name":"mccain"},
{"votes":229,"name":"huckabee"},
{"votes":174,"name":"uncommitted-r"},
{"votes":115,"name":"paul"},
{"votes":92,"name":"romney"},
{"votes":39,"name":"giuliani"},
{"votes":24,"name":"keyes"}],
"total":2758,"precincts":
{"total":47,"reporting":47},
"name":"Boyd"},
"Rockcastle":
{"votes":[
{"votes":813,"name":"mccain"},
{"votes":116,"name":"huckabee"},
{"votes":44,"name":"uncommitted-r"},
{"votes":43,"name":"paul"},
{"votes":39,"name":"romney"},
{"votes":14,"name":"keyes"},
{"votes":10,"name":"giuliani"}],
"total":1079,"precincts":
{"total":14,"reporting":14},
"name":"Rockcastle"},
"McLean":
{"votes":[
{"votes":10,"name":"mccain"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":15,"precincts":
{"total":8,"reporting":1},
"name":"McLean"},
"Johnson":
{"votes":[
{"votes":1065,"name":"mccain"},
{"votes":145,"name":"huckabee"},
{"votes":74,"name":"uncommitted-r"},
{"votes":44,"name":"paul"},
{"votes":42,"name":"romney"},
{"votes":12,"name":"giuliani"},
{"votes":9,"name":"keyes"}],
"total":1391,"precincts":
{"total":31,"reporting":31},
"name":"Johnson"},
"Hopkins":
{"votes":[
{"votes":484,"name":"mccain"},
{"votes":111,"name":"huckabee"},
{"votes":56,"name":"paul"},
{"votes":50,"name":"uncommitted-r"},
{"votes":44,"name":"romney"},
{"votes":15,"name":"keyes"},
{"votes":7,"name":"giuliani"}],
"total":767,"precincts":
{"total":40,"reporting":40},
"name":"Hopkins"},
"Whitley":
{"votes":[
{"votes":3009,"name":"mccain"},
{"votes":437,"name":"huckabee"},
{"votes":288,"name":"uncommitted-r"},
{"votes":169,"name":"paul"},
{"votes":117,"name":"romney"},
{"votes":42,"name":"giuliani"},
{"votes":35,"name":"keyes"}],
"total":4097,"precincts":
{"total":36,"reporting":35},
"name":"Whitley"},
"Woodford":
{"votes":[
{"votes":667,"name":"mccain"},
{"votes":92,"name":"paul"},
{"votes":79,"name":"huckabee"},
{"votes":43,"name":"romney"},
{"votes":43,"name":"uncommitted-r"},
{"votes":16,"name":"keyes"},
{"votes":12,"name":"giuliani"}],
"total":952,"precincts":
{"total":16,"reporting":16},
"name":"Woodford"},
"Green":
{"votes":[
{"votes":1145,"name":"mccain"},
{"votes":171,"name":"huckabee"},
{"votes":56,"name":"paul"},
{"votes":38,"name":"romney"},
{"votes":31,"name":"uncommitted-r"},
{"votes":28,"name":"giuliani"},
{"votes":6,"name":"keyes"}],
"total":1475,"precincts":
{"total":10,"reporting":10},
"name":"Green"},
"Clay":
{"votes":[
{"votes":1897,"name":"mccain"},
{"votes":220,"name":"uncommitted-r"},
{"votes":216,"name":"huckabee"},
{"votes":137,"name":"paul"},
{"votes":48,"name":"romney"},
{"votes":31,"name":"giuliani"},
{"votes":20,"name":"keyes"}],
"total":2569,"precincts":
{"total":20,"reporting":20},
"name":"Clay"},
"Ohio":
{"votes":[
{"votes":648,"name":"mccain"},
{"votes":104,"name":"huckabee"},
{"votes":49,"name":"paul"},
{"votes":47,"name":"uncommitted-r"},
{"votes":27,"name":"romney"},
{"votes":19,"name":"giuliani"},
{"votes":12,"name":"keyes"}],
"total":906,"precincts":
{"total":25,"reporting":16},
"name":"Ohio"},
"Spencer":
{"votes":[
{"votes":577,"name":"mccain"},
{"votes":83,"name":"paul"},
{"votes":70,"name":"huckabee"},
{"votes":34,"name":"romney"},
{"votes":34,"name":"uncommitted-r"},
{"votes":16,"name":"giuliani"},
{"votes":14,"name":"keyes"}],
"total":828,"precincts":
{"total":11,"reporting":11},
"name":"Spencer"},
"Fulton":
{"votes":[
{"votes":67,"name":"mccain"},
{"votes":12,"name":"huckabee"},
{"votes":8,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":97,"precincts":
{"total":12,"reporting":12},
"name":"Fulton"},
"Madison":
{"votes":[
{"votes":2006,"name":"mccain"},
{"votes":291,"name":"huckabee"},
{"votes":251,"name":"paul"},
{"votes":123,"name":"romney"},
{"votes":110,"name":"uncommitted-r"},
{"votes":35,"name":"giuliani"},
{"votes":30,"name":"keyes"}],
"total":2846,"precincts":
{"total":56,"reporting":56},
"name":"Madison"},
"Taylor":
{"votes":[
{"votes":2135,"name":"mccain"},
{"votes":231,"name":"huckabee"},
{"votes":125,"name":"paul"},
{"votes":105,"name":"uncommitted-r"},
{"votes":52,"name":"romney"},
{"votes":28,"name":"giuliani"},
{"votes":23,"name":"keyes"}],
"total":2699,"precincts":
{"total":20,"reporting":20},
"name":"Taylor"},
"Clinton":
{"votes":[
{"votes":399,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":15,"name":"paul"},
{"votes":14,"name":"romney"},
{"votes":8,"name":"uncommitted-r"},
{"votes":6,"name":"keyes"},
{"votes":4,"name":"giuliani"}],
"total":494,"precincts":
{"total":13,"reporting":13},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":711,"name":"mccain"},
{"votes":108,"name":"paul"},
{"votes":96,"name":"huckabee"},
{"votes":62,"name":"uncommitted-r"},
{"votes":42,"name":"romney"},
{"votes":17,"name":"keyes"},
{"votes":11,"name":"giuliani"}],
"total":1047,"precincts":
{"total":26,"reporting":26},
"name":"Clark"},
"Owen":
{"votes":[
{"votes":219,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":23,"name":"uncommitted-r"},
{"votes":19,"name":"paul"},
{"votes":12,"name":"romney"},
{"votes":6,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":311,"precincts":
{"total":13,"reporting":13},
"name":"Owen"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Todd"},
"Grayson":
{"votes":[
{"votes":1185,"name":"mccain"},
{"votes":186,"name":"huckabee"},
{"votes":125,"name":"paul"},
{"votes":72,"name":"uncommitted-r"},
{"votes":60,"name":"romney"},
{"votes":32,"name":"giuliani"},
{"votes":10,"name":"keyes"}],
"total":1670,"precincts":
{"total":23,"reporting":23},
"name":"Grayson"},
"Hart":
{"votes":[
{"votes":365,"name":"mccain"},
{"votes":45,"name":"huckabee"},
{"votes":34,"name":"paul"},
{"votes":21,"name":"romney"},
{"votes":15,"name":"uncommitted-r"},
{"votes":8,"name":"keyes"},
{"votes":6,"name":"giuliani"}],
"total":494,"precincts":
{"total":19,"reporting":19},
"name":"Hart"},
"Carlisle":
{"votes":[
{"votes":49,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":5,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":69,"precincts":
{"total":6,"reporting":6},
"name":"Carlisle"},
"Lyon":
{"votes":[
{"votes":156,"name":"mccain"},
{"votes":15,"name":"huckabee"},
{"votes":12,"name":"uncommitted-r"},
{"votes":11,"name":"romney"},
{"votes":6,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":2,"name":"giuliani"}],
"total":204,"precincts":
{"total":6,"reporting":6},
"name":"Lyon"},
"Boone":
{"votes":[
{"votes":5394,"name":"mccain"},
{"votes":524,"name":"romney"},
{"votes":520,"name":"huckabee"},
{"votes":512,"name":"paul"},
{"votes":408,"name":"uncommitted-r"},
{"votes":95,"name":"keyes"},
{"votes":95,"name":"giuliani"}],
"total":7548,"precincts":
{"total":60,"reporting":60},
"name":"Boone"},
"Pendleton":
{"votes":[
{"votes":220,"name":"mccain"},
{"votes":54,"name":"huckabee"},
{"votes":25,"name":"uncommitted-r"},
{"votes":25,"name":"paul"},
{"votes":16,"name":"romney"},
{"votes":4,"name":"giuliani"}],
"total":344,"precincts":
{"total":12,"reporting":12},
"name":"Pendleton"},
"Magoffin":
{"votes":[
{"votes":244,"name":"mccain"},
{"votes":44,"name":"huckabee"},
{"votes":10,"name":"uncommitted-r"},
{"votes":8,"name":"romney"},
{"votes":6,"name":"giuliani"},
{"votes":5,"name":"paul"},
{"votes":3,"name":"keyes"}],
"total":320,"precincts":
{"total":14,"reporting":14},
"name":"Magoffin"},
"Jessamine":
{"votes":[
{"votes":1492,"name":"mccain"},
{"votes":280,"name":"huckabee"},
{"votes":239,"name":"paul"},
{"votes":144,"name":"romney"},
{"votes":101,"name":"uncommitted-r"},
{"votes":33,"name":"keyes"},
{"votes":30,"name":"giuliani"}],
"total":2319,"precincts":
{"total":37,"reporting":37},
"name":"Jessamine"},
"Letcher":
{"votes":[
{"votes":470,"name":"mccain"},
{"votes":64,"name":"huckabee"},
{"votes":49,"name":"paul"},
{"votes":34,"name":"uncommitted-r"},
{"votes":12,"name":"romney"},
{"votes":11,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":642,"precincts":
{"total":32,"reporting":32},
"name":"Letcher"},
"Jackson":
{"votes":[
{"votes":1118,"name":"mccain"},
{"votes":168,"name":"huckabee"},
{"votes":68,"name":"uncommitted-r"},
{"votes":43,"name":"paul"},
{"votes":32,"name":"romney"},
{"votes":15,"name":"keyes"},
{"votes":9,"name":"giuliani"}],
"total":1453,"precincts":
{"total":14,"reporting":14},
"name":"Jackson"},
"Lawrence":
{"votes":[
{"votes":517,"name":"mccain"},
{"votes":66,"name":"huckabee"},
{"votes":30,"name":"uncommitted-r"},
{"votes":26,"name":"romney"},
{"votes":19,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":664,"precincts":
{"total":18,"reporting":18},
"name":"Lawrence"},
"Trigg":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Trigg"},
"McCracken":
{"votes":[
{"votes":685,"name":"mccain"},
{"votes":82,"name":"huckabee"},
{"votes":78,"name":"paul"},
{"votes":47,"name":"romney"},
{"votes":42,"name":"uncommitted-r"},
{"votes":10,"name":"giuliani"},
{"votes":9,"name":"keyes"}],
"total":953,"precincts":
{"total":54,"reporting":54},
"name":"McCracken"},
"Fayette":
{"votes":[
{"votes":7271,"name":"mccain"},
{"votes":1341,"name":"paul"},
{"votes":766,"name":"huckabee"},
{"votes":662,"name":"uncommitted-r"},
{"votes":589,"name":"romney"},
{"votes":203,"name":"giuliani"},
{"votes":158,"name":"keyes"}],
"total":10990,"precincts":
{"total":274,"reporting":274},
"name":"Fayette"},
"Floyd":
{"votes":[
{"votes":276,"name":"mccain"},
{"votes":45,"name":"huckabee"},
{"votes":16,"name":"romney"},
{"votes":16,"name":"uncommitted-r"},
{"votes":14,"name":"paul"},
{"votes":5,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":374,"precincts":
{"total":42,"reporting":33},
"name":"Floyd"},
"Pike":
{"votes":[
{"votes":1126,"name":"mccain"},
{"votes":118,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":39,"name":"uncommitted-r"},
{"votes":37,"name":"romney"},
{"votes":10,"name":"giuliani"},
{"votes":5,"name":"keyes"}],
"total":1375,"precincts":
{"total":57,"reporting":57},
"name":"Pike"},
"Lincoln":
{"votes":[
{"votes":598,"name":"mccain"},
{"votes":110,"name":"huckabee"},
{"votes":55,"name":"uncommitted-r"},
{"votes":42,"name":"romney"},
{"votes":36,"name":"paul"},
{"votes":15,"name":"giuliani"},
{"votes":8,"name":"keyes"}],
"total":864,"precincts":
{"total":17,"reporting":17},
"name":"Lincoln"},
"Ballard":
{"votes":[
{"votes":70,"name":"mccain"},
{"votes":19,"name":"huckabee"},
{"votes":9,"name":"paul"},
{"votes":5,"name":"romney"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"giuliani"}],
"total":111,"precincts":
{"total":13,"reporting":13},
"name":"Ballard"},
"Livingston":
{"votes":[
{"votes":7,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"romney"}],
"total":13,"precincts":
{"total":10,"reporting":2},
"name":"Livingston"},
"Harlan":
{"votes":[
{"votes":685,"name":"mccain"},
{"votes":66,"name":"huckabee"},
{"votes":49,"name":"uncommitted-r"},
{"votes":38,"name":"paul"},
{"votes":23,"name":"romney"},
{"votes":8,"name":"giuliani"},
{"votes":7,"name":"keyes"}],
"total":876,"precincts":
{"total":35,"reporting":35},
"name":"Harlan"},
"Franklin":
{"votes":[
{"votes":786,"name":"mccain"},
{"votes":102,"name":"huckabee"},
{"votes":94,"name":"paul"},
{"votes":67,"name":"uncommitted-r"},
{"votes":58,"name":"romney"},
{"votes":25,"name":"giuliani"},
{"votes":16,"name":"keyes"}],
"total":1148,"precincts":
{"total":44,"reporting":44},
"name":"Franklin"},
"Owsley":
{"votes":[
{"votes":315,"name":"mccain"},
{"votes":46,"name":"huckabee"},
{"votes":20,"name":"uncommitted-r"},
{"votes":13,"name":"romney"},
{"votes":11,"name":"paul"},
{"votes":4,"name":"giuliani"}],
"total":409,"precincts":
{"total":8,"reporting":8},
"name":"Owsley"},
"Bell":
{"votes":[
{"votes":992,"name":"mccain"},
{"votes":128,"name":"huckabee"},
{"votes":68,"name":"uncommitted-r"},
{"votes":45,"name":"romney"},
{"votes":40,"name":"paul"},
{"votes":14,"name":"keyes"},
{"votes":9,"name":"giuliani"}],
"total":1296,"precincts":
{"total":33,"reporting":33},
"name":"Bell"},
"Marshall":
{"votes":[
{"votes":534,"name":"mccain"},
{"votes":96,"name":"huckabee"},
{"votes":48,"name":"paul"},
{"votes":45,"name":"uncommitted-r"},
{"votes":30,"name":"romney"},
{"votes":12,"name":"giuliani"},
{"votes":10,"name":"keyes"}],
"total":775,"precincts":
{"total":25,"reporting":25},
"name":"Marshall"},
"Carroll":
{"votes":[
{"votes":91,"name":"mccain"},
{"votes":13,"name":"romney"},
{"votes":11,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":5,"name":"uncommitted-r"},
{"votes":2,"name":"giuliani"}],
"total":129,"precincts":
{"total":11,"reporting":11},
"name":"Carroll"},
"Bath":
{"votes":[
{"votes":82,"name":"mccain"},
{"votes":11,"name":"paul"},
{"votes":8,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":6,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":3,"name":"giuliani"}],
"total":119,"precincts":
{"total":12,"reporting":12},
"name":"Bath"},
"Harrison":
{"votes":[
{"votes":368,"name":"mccain"},
{"votes":52,"name":"paul"},
{"votes":44,"name":"huckabee"},
{"votes":22,"name":"romney"},
{"votes":21,"name":"uncommitted-r"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"keyes"}],
"total":517,"precincts":
{"total":16,"reporting":16},
"name":"Harrison"},
"Campbell":
{"votes":[
{"votes":2818,"name":"mccain"},
{"votes":291,"name":"romney"},
{"votes":288,"name":"huckabee"},
{"votes":223,"name":"uncommitted-r"},
{"votes":219,"name":"paul"},
{"votes":73,"name":"giuliani"},
{"votes":71,"name":"keyes"}],
"total":3983,"precincts":
{"total":66,"reporting":66},
"name":"Campbell"},
"Laurel":
{"votes":[
{"votes":4314,"name":"mccain"},
{"votes":537,"name":"huckabee"},
{"votes":230,"name":"uncommitted-r"},
{"votes":195,"name":"paul"},
{"votes":124,"name":"romney"},
{"votes":66,"name":"giuliani"},
{"votes":42,"name":"keyes"}],
"total":5508,"precincts":
{"total":45,"reporting":45},
"name":"Laurel"},
"Mercer":
{"votes":[
{"votes":523,"name":"mccain"},
{"votes":80,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":38,"name":"uncommitted-r"},
{"votes":36,"name":"romney"},
{"votes":8,"name":"giuliani"},
{"votes":7,"name":"keyes"}],
"total":760,"precincts":
{"total":17,"reporting":17},
"name":"Mercer"},
"Gallatin":
{"votes":[
{"votes":125,"name":"mccain"},
{"votes":21,"name":"huckabee"},
{"votes":20,"name":"romney"},
{"votes":16,"name":"uncommitted-r"},
{"votes":11,"name":"paul"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":198,"precincts":
{"total":7,"reporting":7},
"name":"Gallatin"},
"Cumberland":
{"votes":[
{"votes":328,"name":"mccain"},
{"votes":46,"name":"huckabee"},
{"votes":29,"name":"romney"},
{"votes":27,"name":"uncommitted-r"},
{"votes":26,"name":"paul"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":460,"precincts":
{"total":9,"reporting":9},
"name":"Cumberland"},
"Pulaski":
{"votes":[
{"votes":3562,"name":"mccain"},
{"votes":456,"name":"huckabee"},
{"votes":185,"name":"uncommitted-r"},
{"votes":181,"name":"romney"},
{"votes":144,"name":"paul"},
{"votes":51,"name":"giuliani"},
{"votes":47,"name":"keyes"}],
"total":4626,"precincts":
{"total":57,"reporting":57},
"name":"Pulaski"},
"Rowan":
{"votes":[
{"votes":373,"name":"mccain"},
{"votes":64,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":26,"name":"uncommitted-r"},
{"votes":20,"name":"romney"},
{"votes":7,"name":"giuliani"},
{"votes":3,"name":"keyes"}],
"total":534,"precincts":
{"total":18,"reporting":18},
"name":"Rowan"},
"Elliott":
{"votes":[
{"votes":13,"name":"mccain"},
{"votes":10,"name":"romney"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"paul"}],
"total":25,"precincts":
{"total":7,"reporting":7},
"name":"Elliott"},
"Estill":
{"votes":[
{"votes":741,"name":"mccain"},
{"votes":90,"name":"huckabee"},
{"votes":40,"name":"paul"},
{"votes":33,"name":"uncommitted-r"},
{"votes":20,"name":"romney"},
{"votes":13,"name":"giuliani"},
{"votes":6,"name":"keyes"}],
"total":943,"precincts":
{"total":15,"reporting":15},
"name":"Estill"},
"Christian":
{"votes":[
{"votes":857,"name":"mccain"},
{"votes":102,"name":"huckabee"},
{"votes":77,"name":"paul"},
{"votes":70,"name":"uncommitted-r"},
{"votes":59,"name":"romney"},
{"votes":27,"name":"keyes"},
{"votes":12,"name":"giuliani"}],
"total":1204,"precincts":
{"total":44,"reporting":44},
"name":"Christian"},
"Greenup":
{"votes":[
{"votes":1101,"name":"mccain"},
{"votes":198,"name":"huckabee"},
{"votes":83,"name":"paul"},
{"votes":80,"name":"romney"},
{"votes":74,"name":"uncommitted-r"},
{"votes":18,"name":"giuliani"},
{"votes":14,"name":"keyes"}],
"total":1568,"precincts":
{"total":32,"reporting":32},
"name":"Greenup"},
"Leslie":
{"votes":[
{"votes":1108,"name":"mccain"},
{"votes":92,"name":"uncommitted-r"},
{"votes":82,"name":"huckabee"},
{"votes":69,"name":"paul"},
{"votes":31,"name":"romney"},
{"votes":22,"name":"giuliani"},
{"votes":8,"name":"keyes"}],
"total":1412,"precincts":
{"total":17,"reporting":17},
"name":"Leslie"},
"Knox":
{"votes":[
{"votes":1981,"name":"mccain"},
{"votes":265,"name":"huckabee"},
{"votes":125,"name":"paul"},
{"votes":88,"name":"uncommitted-r"},
{"votes":77,"name":"romney"},
{"votes":46,"name":"giuliani"},
{"votes":24,"name":"keyes"}],
"total":2606,"precincts":
{"total":30,"reporting":30},
"name":"Knox"},
"Hancock":
{"votes":[
{"votes":81,"name":"mccain"},
{"votes":23,"name":"huckabee"},
{"votes":4,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":4,"name":"paul"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"giuliani"}],
"total":121,"precincts":
{"total":10,"reporting":2},
"name":"Hancock"},
"Hardin":
{"votes":[
{"votes":2626,"name":"mccain"},
{"votes":386,"name":"paul"},
{"votes":311,"name":"huckabee"},
{"votes":218,"name":"uncommitted-r"},
{"votes":149,"name":"romney"},
{"votes":77,"name":"giuliani"},
{"votes":47,"name":"keyes"}],
"total":3814,"precincts":
{"total":55,"reporting":55},
"name":"Hardin"},
"LaRue":
{"votes":[
{"votes":267,"name":"mccain"},
{"votes":93,"name":"paul"},
{"votes":57,"name":"huckabee"},
{"votes":17,"name":"uncommitted-r"},
{"votes":12,"name":"romney"},
{"votes":6,"name":"giuliani"},
{"votes":3,"name":"keyes"}],
"total":455,"precincts":
{"total":12,"reporting":12},
"name":"LaRue"},
"Bracken":
{"votes":[
{"votes":126,"name":"mccain"},
{"votes":15,"name":"uncommitted-r"},
{"votes":12,"name":"huckabee"},
{"votes":9,"name":"romney"},
{"votes":7,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":2,"name":"giuliani"}],
"total":173,"precincts":
{"total":8,"reporting":8},
"name":"Bracken"},
"Meade":
{"votes":[
{"votes":662,"name":"mccain"},
{"votes":88,"name":"huckabee"},
{"votes":71,"name":"paul"},
{"votes":55,"name":"uncommitted-r"},
{"votes":39,"name":"romney"},
{"votes":23,"name":"giuliani"},
{"votes":9,"name":"keyes"}],
"total":947,"precincts":
{"total":18,"reporting":18},
"name":"Meade"},
"Morgan":
{"votes":[
{"votes":65,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":4,"name":"uncommitted-r"},
{"votes":4,"name":"paul"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":91,"precincts":
{"total":12,"reporting":12},
"name":"Morgan"},
"Martin":
{"votes":[
{"votes":644,"name":"mccain"},
{"votes":71,"name":"huckabee"},
{"votes":54,"name":"uncommitted-r"},
{"votes":21,"name":"romney"},
{"votes":19,"name":"paul"},
{"votes":13,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":824,"precincts":
{"total":14,"reporting":14},
"name":"Martin"},
"Garrard":
{"votes":[
{"votes":609,"name":"mccain"},
{"votes":76,"name":"huckabee"},
{"votes":61,"name":"uncommitted-r"},
{"votes":58,"name":"paul"},
{"votes":28,"name":"romney"},
{"votes":17,"name":"giuliani"},
{"votes":5,"name":"keyes"}],
"total":854,"precincts":
{"total":13,"reporting":13},
"name":"Garrard"},
"Edmonson":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Edmonson"},
"Simpson":
{"votes":[
{"votes":268,"name":"mccain"},
{"votes":38,"name":"huckabee"},
{"votes":38,"name":"paul"},
{"votes":27,"name":"uncommitted-r"},
{"votes":16,"name":"romney"},
{"votes":6,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":394,"precincts":
{"total":13,"reporting":13},
"name":"Simpson"},
"Muhlenberg":
{"votes":[
{"votes":242,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":17,"name":"romney"},
{"votes":16,"name":"uncommitted-r"},
{"votes":11,"name":"paul"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"keyes"}],
"total":325,"precincts":
{"total":26,"reporting":10},
"name":"Muhlenberg"},
"Carter":
{"votes":[
{"votes":736,"name":"mccain"},
{"votes":105,"name":"huckabee"},
{"votes":61,"name":"uncommitted-r"},
{"votes":52,"name":"paul"},
{"votes":40,"name":"romney"},
{"votes":19,"name":"giuliani"},
{"votes":12,"name":"keyes"}],
"total":1025,"precincts":
{"total":23,"reporting":23},
"name":"Carter"},
"Knott":
{"votes":[
{"votes":24,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"paul"}],
"total":32,"precincts":
{"total":30,"reporting":12},
"name":"Knott"},
"Lewis":
{"votes":[
{"votes":808,"name":"mccain"},
{"votes":121,"name":"huckabee"},
{"votes":84,"name":"uncommitted-r"},
{"votes":56,"name":"romney"},
{"votes":42,"name":"paul"},
{"votes":16,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":1128,"precincts":
{"total":14,"reporting":14},
"name":"Lewis"},
"Calloway":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Calloway"},
"Fleming":
{"votes":[
{"votes":351,"name":"mccain"},
{"votes":46,"name":"huckabee"},
{"votes":22,"name":"uncommitted-r"},
{"votes":21,"name":"paul"},
{"votes":19,"name":"romney"},
{"votes":8,"name":"giuliani"},
{"votes":7,"name":"keyes"}],
"total":474,"precincts":
{"total":18,"reporting":18},
"name":"Fleming"},
"Logan":
{"votes":[
{"votes":17,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"paul"}],
"total":25,"precincts":
{"total":20,"reporting":1},
"name":"Logan"},
"Scott":
{"votes":[
{"votes":1282,"name":"mccain"},
{"votes":182,"name":"paul"},
{"votes":171,"name":"huckabee"},
{"votes":104,"name":"uncommitted-r"},
{"votes":98,"name":"romney"},
{"votes":34,"name":"giuliani"},
{"votes":21,"name":"keyes"}],
"total":1892,"precincts":
{"total":35,"reporting":35},
"name":"Scott"},
"Monroe":
{"votes":[
{"votes":405,"name":"mccain"},
{"votes":54,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":26,"name":"uncommitted-r"},
{"votes":16,"name":"romney"},
{"votes":12,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":547,"precincts":
{"total":12,"reporting":12},
"name":"Monroe"}}})