GoogleElectionMap.votesReady({"status":"ok","totals":
{"date":"02-05","precincts":
{"total":4122,"reporting":4122},
"votes":[
{"votes":25990,"name":"romney"},
{"votes":13813,"name":"mccain"},
{"votes":12525,"name":"huckabee"},
{"votes":9856,"name":"paul"},
{"votes":369,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"type":"caucus","name":"Minnesota"},
"state":"MN","party":"gop","total":62553,"locals":
{"Red Lake":
{"votes":[
{"votes":19,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":4,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":30,"precincts":
{"total":21,"reporting":21},
"name":"Red Lake"},
"Goodhue":
{"votes":[
{"votes":201,"name":"romney"},
{"votes":122,"name":"mccain"},
{"votes":87,"name":"paul"},
{"votes":86,"name":"huckabee"},
{"votes":7,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":503,"precincts":
{"total":44,"reporting":44},
"name":"Goodhue"},
"Olmsted":
{"votes":[
{"votes":600,"name":"romney"},
{"votes":399,"name":"mccain"},
{"votes":387,"name":"huckabee"},
{"votes":289,"name":"paul"},
{"votes":12,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":1687,"precincts":
{"total":74,"reporting":74},
"name":"Olmsted"},
"Pine":
{"votes":[
{"votes":98,"name":"romney"},
{"votes":58,"name":"paul"},
{"votes":55,"name":"mccain"},
{"votes":53,"name":"huckabee"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":265,"precincts":
{"total":47,"reporting":47},
"name":"Pine"},
"Mower":
{"votes":[
{"votes":98,"name":"huckabee"},
{"votes":59,"name":"mccain"},
{"votes":52,"name":"romney"},
{"votes":40,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":251,"precincts":
{"total":39,"reporting":39},
"name":"Mower"},
"Nicollet":
{"votes":[
{"votes":91,"name":"huckabee"},
{"votes":89,"name":"mccain"},
{"votes":73,"name":"romney"},
{"votes":56,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":309,"precincts":
{"total":33,"reporting":33},
"name":"Nicollet"},
"Dodge":
{"votes":[
{"votes":77,"name":"romney"},
{"votes":61,"name":"huckabee"},
{"votes":56,"name":"mccain"},
{"votes":39,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":233,"precincts":
{"total":19,"reporting":19},
"name":"Dodge"},
"Brown":
{"votes":[
{"votes":94,"name":"mccain"},
{"votes":69,"name":"romney"},
{"votes":53,"name":"paul"},
{"votes":44,"name":"huckabee"},
{"votes":8,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":268,"precincts":
{"total":32,"reporting":32},
"name":"Brown"},
"Pennington":
{"votes":[
{"votes":36,"name":"huckabee"},
{"votes":26,"name":"romney"},
{"votes":25,"name":"mccain"},
{"votes":18,"name":"paul"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":108,"precincts":
{"total":34,"reporting":34},
"name":"Pennington"},
"Mahnomen":
{"votes":[
{"votes":10,"name":"romney"},
{"votes":8,"name":"paul"},
{"votes":7,"name":"huckabee"},
{"votes":4,"name":"mccain"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":29,"precincts":
{"total":19,"reporting":19},
"name":"Mahnomen"},
"Freeborn":
{"votes":[
{"votes":102,"name":"romney"},
{"votes":66,"name":"huckabee"},
{"votes":63,"name":"mccain"},
{"votes":26,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":258,"precincts":
{"total":40,"reporting":40},
"name":"Freeborn"},
"Kittson":
{"votes":[
{"votes":13,"name":"huckabee"},
{"votes":10,"name":"mccain"},
{"votes":3,"name":"romney"},
{"votes":1,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":27,"precincts":
{"total":38,"reporting":38},
"name":"Kittson"},
"Renville":
{"votes":[
{"votes":45,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":23,"name":"romney"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":122,"precincts":
{"total":37,"reporting":37},
"name":"Renville"},
"Chippewa":
{"votes":[
{"votes":20,"name":"huckabee"},
{"votes":19,"name":"romney"},
{"votes":16,"name":"mccain"},
{"votes":7,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":62,"precincts":
{"total":23,"reporting":23},
"name":"Chippewa"},
"Washington":
{"votes":[
{"votes":1509,"name":"romney"},
{"votes":697,"name":"mccain"},
{"votes":433,"name":"paul"},
{"votes":378,"name":"huckabee"},
{"votes":14,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":3031,"precincts":
{"total":87,"reporting":87},
"name":"Washington"},
"Itasca":
{"votes":[
{"votes":168,"name":"huckabee"},
{"votes":106,"name":"romney"},
{"votes":78,"name":"mccain"},
{"votes":54,"name":"paul"},
{"votes":4,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":410,"precincts":
{"total":79,"reporting":79},
"name":"Itasca"},
"Dakota":
{"votes":[
{"votes":2542,"name":"romney"},
{"votes":1171,"name":"mccain"},
{"votes":887,"name":"huckabee"},
{"votes":802,"name":"paul"},
{"votes":34,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":5436,"precincts":
{"total":141,"reporting":141},
"name":"Dakota"},
"Polk":
{"votes":[
{"votes":78,"name":"romney"},
{"votes":67,"name":"huckabee"},
{"votes":33,"name":"mccain"},
{"votes":15,"name":"paul"},
{"votes":5,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":198,"precincts":
{"total":82,"reporting":82},
"name":"Polk"},
"Kandiyohi":
{"votes":[
{"votes":200,"name":"romney"},
{"votes":140,"name":"huckabee"},
{"votes":87,"name":"mccain"},
{"votes":63,"name":"paul"},
{"votes":11,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":501,"precincts":
{"total":47,"reporting":47},
"name":"Kandiyohi"},
"Jackson":
{"votes":[
{"votes":51,"name":"romney"},
{"votes":27,"name":"huckabee"},
{"votes":20,"name":"mccain"},
{"votes":8,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":106,"precincts":
{"total":30,"reporting":30},
"name":"Jackson"},
"Waseca":
{"votes":[
{"votes":76,"name":"romney"},
{"votes":64,"name":"huckabee"},
{"votes":41,"name":"mccain"},
{"votes":22,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":203,"precincts":
{"total":22,"reporting":22},
"name":"Waseca"},
"Grant":
{"votes":[
{"votes":54,"name":"romney"},
{"votes":28,"name":"mccain"},
{"votes":6,"name":"paul"},
{"votes":4,"name":"huckabee"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":92,"precincts":
{"total":23,"reporting":23},
"name":"Grant"},
"Lac Qui Parle":
{"votes":[
{"votes":20,"name":"huckabee"},
{"votes":19,"name":"mccain"},
{"votes":12,"name":"romney"},
{"votes":9,"name":"paul"},
{"votes":5,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":65,"precincts":
{"total":31,"reporting":31},
"name":"Lac Qui Parle"},
"Wright":
{"votes":[
{"votes":858,"name":"romney"},
{"votes":307,"name":"huckabee"},
{"votes":289,"name":"paul"},
{"votes":272,"name":"mccain"},
{"votes":15,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":1741,"precincts":
{"total":40,"reporting":40},
"name":"Wright"},
"Wilkin":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":19,"name":"huckabee"},
{"votes":17,"name":"romney"},
{"votes":16,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":74,"precincts":
{"total":33,"reporting":33},
"name":"Wilkin"},
"Rice":
{"votes":[
{"votes":295,"name":"romney"},
{"votes":169,"name":"mccain"},
{"votes":164,"name":"huckabee"},
{"votes":127,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":755,"precincts":
{"total":33,"reporting":33},
"name":"Rice"},
"Morrison":
{"votes":[
{"votes":81,"name":"mccain"},
{"votes":79,"name":"romney"},
{"votes":77,"name":"huckabee"},
{"votes":71,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":309,"precincts":
{"total":48,"reporting":48},
"name":"Morrison"},
"Redwood":
{"votes":[
{"votes":65,"name":"mccain"},
{"votes":42,"name":"paul"},
{"votes":34,"name":"romney"},
{"votes":34,"name":"huckabee"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":175,"precincts":
{"total":43,"reporting":43},
"name":"Redwood"},
"Cook":
{"votes":[
{"votes":23,"name":"romney"},
{"votes":19,"name":"huckabee"},
{"votes":18,"name":"mccain"},
{"votes":8,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":68,"precincts":
{"total":12,"reporting":12},
"name":"Cook"},
"Swift":
{"votes":[
{"votes":31,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":29,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":104,"precincts":
{"total":31,"reporting":31},
"name":"Swift"},
"Mille Lacs":
{"votes":[
{"votes":134,"name":"romney"},
{"votes":99,"name":"huckabee"},
{"votes":44,"name":"paul"},
{"votes":43,"name":"mccain"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":322,"precincts":
{"total":25,"reporting":25},
"name":"Mille Lacs"},
"Hennepin":
{"votes":[
{"votes":7231,"name":"romney"},
{"votes":3777,"name":"mccain"},
{"votes":2410,"name":"paul"},
{"votes":2204,"name":"huckabee"},
{"votes":45,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":15667,"precincts":
{"total":425,"reporting":425},
"name":"Hennepin"},
"Rock":
{"votes":[
{"votes":40,"name":"huckabee"},
{"votes":33,"name":"romney"},
{"votes":11,"name":"mccain"},
{"votes":9,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":93,"precincts":
{"total":24,"reporting":24},
"name":"Rock"},
"Meeker":
{"votes":[
{"votes":83,"name":"paul"},
{"votes":67,"name":"huckabee"},
{"votes":55,"name":"romney"},
{"votes":43,"name":"mccain"},
{"votes":7,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":255,"precincts":
{"total":30,"reporting":30},
"name":"Meeker"},
"Traverse":
{"votes":[
{"votes":15,"name":"huckabee"},
{"votes":13,"name":"romney"},
{"votes":12,"name":"mccain"},
{"votes":5,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":47,"precincts":
{"total":20,"reporting":20},
"name":"Traverse"},
"Carver":
{"votes":[
{"votes":759,"name":"romney"},
{"votes":266,"name":"mccain"},
{"votes":210,"name":"huckabee"},
{"votes":167,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":1404,"precincts":
{"total":34,"reporting":34},
"name":"Carver"},
"Todd":
{"votes":[
{"votes":84,"name":"romney"},
{"votes":69,"name":"huckabee"},
{"votes":53,"name":"paul"},
{"votes":50,"name":"mccain"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":256,"precincts":
{"total":39,"reporting":39},
"name":"Todd"},
"Clay":
{"votes":[
{"votes":196,"name":"romney"},
{"votes":157,"name":"paul"},
{"votes":128,"name":"huckabee"},
{"votes":119,"name":"mccain"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":602,"precincts":
{"total":55,"reporting":55},
"name":"Clay"},
"Le Sueur":
{"votes":[
{"votes":121,"name":"romney"},
{"votes":68,"name":"mccain"},
{"votes":42,"name":"paul"},
{"votes":41,"name":"huckabee"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":272,"precincts":
{"total":26,"reporting":26},
"name":"Le Sueur"},
"Lyon":
{"votes":[
{"votes":80,"name":"huckabee"},
{"votes":77,"name":"mccain"},
{"votes":75,"name":"romney"},
{"votes":33,"name":"paul"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":268,"precincts":
{"total":33,"reporting":33},
"name":"Lyon"},
"Chisago":
{"votes":[
{"votes":351,"name":"romney"},
{"votes":143,"name":"huckabee"},
{"votes":141,"name":"mccain"},
{"votes":88,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":725,"precincts":
{"total":24,"reporting":24},
"name":"Chisago"},
"Otter Tail":
{"votes":[
{"votes":278,"name":"romney"},
{"votes":194,"name":"huckabee"},
{"votes":151,"name":"mccain"},
{"votes":68,"name":"paul"},
{"votes":6,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":697,"precincts":
{"total":91,"reporting":91},
"name":"Otter Tail"},
"Clearwater":
{"votes":[
{"votes":61,"name":"huckabee"},
{"votes":41,"name":"romney"},
{"votes":19,"name":"mccain"},
{"votes":4,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":125,"precincts":
{"total":29,"reporting":29},
"name":"Clearwater"},
"Norman":
{"votes":[
{"votes":15,"name":"romney"},
{"votes":15,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":5,"name":"mccain"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":41,"precincts":
{"total":33,"reporting":33},
"name":"Norman"},
"Koochiching":
{"votes":[
{"votes":26,"name":"huckabee"},
{"votes":16,"name":"paul"},
{"votes":10,"name":"romney"},
{"votes":5,"name":"mccain"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":57,"precincts":
{"total":35,"reporting":35},
"name":"Koochiching"},
"Winona":
{"votes":[
{"votes":127,"name":"romney"},
{"votes":125,"name":"mccain"},
{"votes":112,"name":"huckabee"},
{"votes":104,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":469,"precincts":
{"total":48,"reporting":48},
"name":"Winona"},
"Ramsey":
{"votes":[
{"votes":2169,"name":"romney"},
{"votes":1462,"name":"mccain"},
{"votes":1012,"name":"paul"},
{"votes":927,"name":"huckabee"},
{"votes":23,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":5593,"precincts":
{"total":178,"reporting":178},
"name":"Ramsey"},
"Big Stone":
{"votes":[
{"votes":14,"name":"romney"},
{"votes":10,"name":"mccain"},
{"votes":10,"name":"huckabee"},
{"votes":2,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":36,"precincts":
{"total":23,"reporting":23},
"name":"Big Stone"},
"Kanabec":
{"votes":[
{"votes":67,"name":"romney"},
{"votes":67,"name":"huckabee"},
{"votes":37,"name":"mccain"},
{"votes":37,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":209,"precincts":
{"total":20,"reporting":20},
"name":"Kanabec"},
"Lincoln":
{"votes":[
{"votes":15,"name":"paul"},
{"votes":10,"name":"romney"},
{"votes":9,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":40,"precincts":
{"total":20,"reporting":20},
"name":"Lincoln"},
"Sherburne":
{"votes":[
{"votes":509,"name":"romney"},
{"votes":259,"name":"huckabee"},
{"votes":208,"name":"mccain"},
{"votes":176,"name":"paul"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":1155,"precincts":
{"total":32,"reporting":32},
"name":"Sherburne"},
"Roseau":
{"votes":[
{"votes":125,"name":"huckabee"},
{"votes":34,"name":"romney"},
{"votes":32,"name":"mccain"},
{"votes":22,"name":"paul"},
{"votes":5,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":218,"precincts":
{"total":44,"reporting":44},
"name":"Roseau"},
"McLeod":
{"votes":[
{"votes":186,"name":"romney"},
{"votes":117,"name":"paul"},
{"votes":88,"name":"mccain"},
{"votes":84,"name":"huckabee"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":478,"precincts":
{"total":28,"reporting":28},
"name":"McLeod"},
"Fillmore":
{"votes":[
{"votes":76,"name":"huckabee"},
{"votes":68,"name":"romney"},
{"votes":62,"name":"mccain"},
{"votes":47,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":254,"precincts":
{"total":37,"reporting":37},
"name":"Fillmore"},
"Pope":
{"votes":[
{"votes":54,"name":"huckabee"},
{"votes":38,"name":"romney"},
{"votes":22,"name":"mccain"},
{"votes":11,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":125,"precincts":
{"total":30,"reporting":30},
"name":"Pope"},
"Marshall":
{"votes":[
{"votes":21,"name":"huckabee"},
{"votes":17,"name":"romney"},
{"votes":9,"name":"mccain"},
{"votes":4,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":51,"precincts":
{"total":60,"reporting":60},
"name":"Marshall"},
"Yellow Medicine":
{"votes":[
{"votes":35,"name":"huckabee"},
{"votes":31,"name":"romney"},
{"votes":17,"name":"mccain"},
{"votes":16,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":99,"precincts":
{"total":31,"reporting":31},
"name":"Yellow Medicine"},
"Steele":
{"votes":[
{"votes":131,"name":"romney"},
{"votes":110,"name":"huckabee"},
{"votes":88,"name":"paul"},
{"votes":84,"name":"mccain"},
{"votes":4,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":417,"precincts":
{"total":26,"reporting":26},
"name":"Steele"},
"Murray":
{"votes":[
{"votes":32,"name":"mccain"},
{"votes":28,"name":"huckabee"},
{"votes":23,"name":"romney"},
{"votes":11,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":95,"precincts":
{"total":29,"reporting":29},
"name":"Murray"},
"Hubbard":
{"votes":[
{"votes":134,"name":"huckabee"},
{"votes":109,"name":"romney"},
{"votes":37,"name":"mccain"},
{"votes":36,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":316,"precincts":
{"total":34,"reporting":34},
"name":"Hubbard"},
"Lake":
{"votes":[
{"votes":54,"name":"huckabee"},
{"votes":31,"name":"mccain"},
{"votes":23,"name":"romney"},
{"votes":6,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":114,"precincts":
{"total":18,"reporting":18},
"name":"Lake"},
"Douglas":
{"votes":[
{"votes":147,"name":"huckabee"},
{"votes":130,"name":"romney"},
{"votes":91,"name":"mccain"},
{"votes":25,"name":"paul"},
{"votes":7,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":400,"precincts":
{"total":38,"reporting":38},
"name":"Douglas"},
"Nobles":
{"votes":[
{"votes":52,"name":"huckabee"},
{"votes":48,"name":"romney"},
{"votes":28,"name":"mccain"},
{"votes":14,"name":"paul"},
{"votes":4,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":146,"precincts":
{"total":40,"reporting":40},
"name":"Nobles"},
"Watonwan":
{"votes":[
{"votes":33,"name":"huckabee"},
{"votes":31,"name":"mccain"},
{"votes":28,"name":"romney"},
{"votes":9,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":101,"precincts":
{"total":21,"reporting":21},
"name":"Watonwan"},
"Crow Wing":
{"votes":[
{"votes":242,"name":"romney"},
{"votes":200,"name":"huckabee"},
{"votes":149,"name":"mccain"},
{"votes":59,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":650,"precincts":
{"total":62,"reporting":62},
"name":"Crow Wing"},
"Pipestone":
{"votes":[
{"votes":73,"name":"huckabee"},
{"votes":36,"name":"romney"},
{"votes":15,"name":"mccain"},
{"votes":12,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":137,"precincts":
{"total":22,"reporting":22},
"name":"Pipestone"},
"Wadena":
{"votes":[
{"votes":60,"name":"huckabee"},
{"votes":55,"name":"romney"},
{"votes":50,"name":"mccain"},
{"votes":34,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":199,"precincts":
{"total":24,"reporting":24},
"name":"Wadena"},
"Faribault":
{"votes":[
{"votes":65,"name":"huckabee"},
{"votes":37,"name":"mccain"},
{"votes":32,"name":"romney"},
{"votes":31,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":165,"precincts":
{"total":33,"reporting":33},
"name":"Faribault"},
"Lake of the Woods":
{"votes":[
{"votes":16,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"paul"},
{"votes":0,"name":"giuliani"}],
"total":39,"precincts":
{"total":15,"reporting":15},
"name":"Lake of the Woods"},
"Cottonwood":
{"votes":[
{"votes":59,"name":"romney"},
{"votes":58,"name":"huckabee"},
{"votes":20,"name":"mccain"},
{"votes":12,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":149,"precincts":
{"total":28,"reporting":28},
"name":"Cottonwood"},
"Wabasha":
{"votes":[
{"votes":85,"name":"romney"},
{"votes":76,"name":"huckabee"},
{"votes":56,"name":"mccain"},
{"votes":33,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":251,"precincts":
{"total":33,"reporting":33},
"name":"Wabasha"},
"Isanti":
{"votes":[
{"votes":229,"name":"romney"},
{"votes":126,"name":"huckabee"},
{"votes":81,"name":"mccain"},
{"votes":55,"name":"paul"},
{"votes":10,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":501,"precincts":
{"total":17,"reporting":17},
"name":"Isanti"},
"Stearns":
{"votes":[
{"votes":524,"name":"romney"},
{"votes":358,"name":"paul"},
{"votes":319,"name":"mccain"},
{"votes":289,"name":"huckabee"},
{"votes":6,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":1496,"precincts":
{"total":103,"reporting":103},
"name":"Stearns"},
"Aitkin":
{"votes":[
{"votes":70,"name":"romney"},
{"votes":52,"name":"huckabee"},
{"votes":46,"name":"mccain"},
{"votes":18,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":186,"precincts":
{"total":54,"reporting":54},
"name":"Aitkin"},
"Benton":
{"votes":[
{"votes":107,"name":"romney"},
{"votes":90,"name":"paul"},
{"votes":56,"name":"huckabee"},
{"votes":53,"name":"mccain"},
{"votes":7,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":313,"precincts":
{"total":31,"reporting":31},
"name":"Benton"},
"Cass":
{"votes":[
{"votes":103,"name":"romney"},
{"votes":93,"name":"huckabee"},
{"votes":73,"name":"mccain"},
{"votes":9,"name":"paul"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":278,"precincts":
{"total":72,"reporting":72},
"name":"Cass"},
"Martin":
{"votes":[
{"votes":100,"name":"huckabee"},
{"votes":59,"name":"romney"},
{"votes":36,"name":"mccain"},
{"votes":32,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":228,"precincts":
{"total":37,"reporting":37},
"name":"Martin"},
"Becker":
{"votes":[
{"votes":108,"name":"huckabee"},
{"votes":101,"name":"romney"},
{"votes":82,"name":"mccain"},
{"votes":35,"name":"paul"},
{"votes":6,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":332,"precincts":
{"total":46,"reporting":46},
"name":"Becker"},
"Anoka":
{"votes":[
{"votes":2007,"name":"romney"},
{"votes":814,"name":"huckabee"},
{"votes":681,"name":"mccain"},
{"votes":510,"name":"paul"},
{"votes":35,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":4047,"precincts":
{"total":123,"reporting":123},
"name":"Anoka"},
"Beltrami":
{"votes":[
{"votes":250,"name":"huckabee"},
{"votes":146,"name":"romney"},
{"votes":92,"name":"mccain"},
{"votes":68,"name":"paul"},
{"votes":20,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":576,"precincts":
{"total":62,"reporting":62},
"name":"Beltrami"},
"St. Louis":
{"votes":[
{"votes":457,"name":"romney"},
{"votes":335,"name":"huckabee"},
{"votes":320,"name":"mccain"},
{"votes":319,"name":"paul"},
{"votes":10,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":1441,"precincts":
{"total":184,"reporting":184},
"name":"St. Louis"},
"Houston":
{"votes":[
{"votes":82,"name":"romney"},
{"votes":76,"name":"huckabee"},
{"votes":48,"name":"mccain"},
{"votes":25,"name":"paul"},
{"votes":6,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":237,"precincts":
{"total":27,"reporting":27},
"name":"Houston"},
"Stevens":
{"votes":[
{"votes":39,"name":"romney"},
{"votes":36,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":129,"precincts":
{"total":26,"reporting":26},
"name":"Stevens"},
"Carlton":
{"votes":[
{"votes":100,"name":"romney"},
{"votes":76,"name":"huckabee"},
{"votes":62,"name":"mccain"},
{"votes":28,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":268,"precincts":
{"total":39,"reporting":39},
"name":"Carlton"},
"Scott":
{"votes":[
{"votes":786,"name":"romney"},
{"votes":264,"name":"huckabee"},
{"votes":259,"name":"mccain"},
{"votes":230,"name":"paul"},
{"votes":10,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":1549,"precincts":
{"total":45,"reporting":45},
"name":"Scott"},
"Blue Earth":
{"votes":[
{"votes":208,"name":"paul"},
{"votes":172,"name":"mccain"},
{"votes":159,"name":"huckabee"},
{"votes":134,"name":"romney"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":675,"precincts":
{"total":53,"reporting":53},
"name":"Blue Earth"},
"Sibley":
{"votes":[
{"votes":51,"name":"romney"},
{"votes":35,"name":"mccain"},
{"votes":27,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"giuliani"}],
"total":140,"precincts":
{"total":24,"reporting":24},
"name":"Sibley"}}})