GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[],
"name":"Mississippi","precincts":
{"total":1912,"reporting":0},
"delegates":33,"date":"03-11"},
"state":"MS","party":"dem","total":0,"locals":
{"Yalobusha":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Yalobusha"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Jackson"},
"Sunflower":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Sunflower"},
"Leake":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Leake"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Union"},
"Carroll":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Carroll"},
"Clarke":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Clarke"},
"Tippah":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Tippah"},
"Calhoun":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Calhoun"},
"Hinds":
{"votes":[],
"total":0,"precincts":
{"total":118,"reporting":0},
"name":"Hinds"},
"Bolivar":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Bolivar"},
"Tishomingo":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Tishomingo"},
"Covington":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Covington"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Jefferson"},
"Pearl River":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Pearl River"},
"Grenada":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Grenada"},
"Noxubee":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Noxubee"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Lincoln"},
"Newton":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Newton"},
"George":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"George"},
"Leflore":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Leflore"},
"Wilkinson":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Wilkinson"},
"Lee":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Lee"},
"Lawrence":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Lawrence"},
"Attala":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Attala"},
"Rankin":
{"votes":[],
"total":0,"precincts":
{"total":52,"reporting":0},
"name":"Rankin"},
"Tate":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Tate"},
"Jeff Davis":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Jeff Davis"},
"Lauderdale":
{"votes":[],
"total":0,"precincts":
{"total":54,"reporting":0},
"name":"Lauderdale"},
"Amite":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Amite"},
"Walthall":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Walthall"},
"DeSoto":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"DeSoto"},
"Winston":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Winston"},
"Quitman":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Quitman"},
"Pontotoc":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Pontotoc"},
"Claiborne":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Claiborne"},
"Alcorn":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Alcorn"},
"Jones":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Jones"},
"Pike":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Pike"},
"Stone":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Stone"},
"Choctaw":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Choctaw"},
"Adams":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Adams"},
"Humphreys":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Humphreys"},
"Hancock":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Hancock"},
"Benton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Benton"},
"Lamar":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lamar"},
"Sharkey":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Sharkey"},
"Coahoma":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Coahoma"},
"Greene":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Greene"},
"Chickasaw":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Chickasaw"},
"Tallahatchie":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Tallahatchie"},
"Lafayette":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Lafayette"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Franklin"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Clay"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Webster"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Montgomery"},
"Simpson":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Simpson"},
"Kemper":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Kemper"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Madison"},
"Lowndes":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lowndes"},
"Tunica":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Tunica"},
"Smith":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Smith"},
"Prentiss":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Prentiss"},
"Marshall":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Marshall"},
"Panola":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Panola"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Washington"},
"Yazoo":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Yazoo"},
"Itawamba":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Itawamba"},
"Neshoba":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Neshoba"},
"Holmes":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Holmes"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Wayne"},
"Scott":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Scott"},
"Jasper":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Jasper"},
"Harrison":
{"votes":[],
"total":0,"precincts":
{"total":66,"reporting":0},
"name":"Harrison"},
"Issaquena":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Issaquena"},
"Oktibbeha":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Oktibbeha"},
"Marion":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Marion"},
"Forrest":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Forrest"},
"Copiah":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Copiah"},
"Monroe":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Monroe"},
"Warren":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Warren"}}})