GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":16705,"name":"mccain"},
{"votes":2525,"name":"huckabee"},
{"votes":825,"name":"paul"},
{"votes":292,"name":"romney"},
{"votes":279,"name":"thompson"},
{"votes":139,"name":"giuliani"},
{"votes":117,"name":"keyes"},
{"votes":68,"name":"hunter"},
{"votes":37,"name":"tancredo"}],
"name":"Mississippi","precincts":
{"total":1912,"reporting":343},
"delegates":39,"date":"03-11"},
"state":"MS","party":"gop","total":20987,"locals":
{"Yalobusha":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Yalobusha"},
"Perry":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":1439,"name":"mccain"},
{"votes":225,"name":"huckabee"},
{"votes":142,"name":"paul"},
{"votes":41,"name":"romney"},
{"votes":31,"name":"thompson"},
{"votes":15,"name":"giuliani"},
{"votes":11,"name":"hunter"},
{"votes":8,"name":"keyes"},
{"votes":2,"name":"tancredo"}],
"total":1914,"precincts":
{"total":43,"reporting":20},
"name":"Jackson"},
"Sunflower":
{"votes":[
{"votes":52,"name":"mccain"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"keyes"}],
"total":54,"precincts":
{"total":18,"reporting":6},
"name":"Sunflower"},
"Leake":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Leake"},
"Union":
{"votes":[
{"votes":879,"name":"mccain"},
{"votes":194,"name":"huckabee"},
{"votes":38,"name":"paul"},
{"votes":12,"name":"tancredo"},
{"votes":7,"name":"keyes"},
{"votes":5,"name":"romney"},
{"votes":5,"name":"hunter"},
{"votes":5,"name":"giuliani"}],
"total":1145,"precincts":
{"total":20,"reporting":16},
"name":"Union"},
"Carroll":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Carroll"},
"Clarke":
{"votes":[
{"votes":279,"name":"mccain"},
{"votes":39,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":339,"precincts":
{"total":23,"reporting":7},
"name":"Clarke"},
"Tippah":
{"votes":[
{"votes":437,"name":"mccain"},
{"votes":108,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":7,"name":"keyes"},
{"votes":6,"name":"thompson"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":591,"precincts":
{"total":24,"reporting":16},
"name":"Tippah"},
"Calhoun":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Calhoun"},
"Hinds":
{"votes":[
{"votes":280,"name":"mccain"},
{"votes":36,"name":"huckabee"},
{"votes":31,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":7,"name":"romney"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":378,"precincts":
{"total":118,"reporting":8},
"name":"Hinds"},
"Bolivar":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Bolivar"},
"Tishomingo":
{"votes":[
{"votes":212,"name":"mccain"},
{"votes":42,"name":"huckabee"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":270,"precincts":
{"total":19,"reporting":6},
"name":"Tishomingo"},
"Covington":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Covington"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Jefferson"},
"Pearl River":
{"votes":[
{"votes":124,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":18,"name":"paul"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"giuliani"}],
"total":182,"precincts":
{"total":34,"reporting":5},
"name":"Pearl River"},
"Grenada":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Grenada"},
"Noxubee":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Noxubee"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Lincoln"},
"Newton":
{"votes":[
{"votes":602,"name":"mccain"},
{"votes":78,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":7,"name":"romney"},
{"votes":6,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"giuliani"}],
"total":714,"precincts":
{"total":19,"reporting":8},
"name":"Newton"},
"George":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"George"},
"Leflore":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Leflore"},
"Wilkinson":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Wilkinson"},
"Lee":
{"votes":[
{"votes":1399,"name":"mccain"},
{"votes":213,"name":"huckabee"},
{"votes":36,"name":"paul"},
{"votes":21,"name":"thompson"},
{"votes":17,"name":"romney"},
{"votes":10,"name":"keyes"},
{"votes":7,"name":"giuliani"},
{"votes":3,"name":"tancredo"},
{"votes":1,"name":"hunter"}],
"total":1707,"precincts":
{"total":42,"reporting":26},
"name":"Lee"},
"Lawrence":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Lawrence"},
"Attala":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Attala"},
"Rankin":
{"votes":[
{"votes":4279,"name":"mccain"},
{"votes":565,"name":"huckabee"},
{"votes":177,"name":"paul"},
{"votes":101,"name":"thompson"},
{"votes":75,"name":"romney"},
{"votes":30,"name":"keyes"},
{"votes":27,"name":"giuliani"},
{"votes":18,"name":"hunter"},
{"votes":3,"name":"tancredo"}],
"total":5275,"precincts":
{"total":52,"reporting":21},
"name":"Rankin"},
"Tate":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Tate"},
"Jeff Davis":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Jeff Davis"},
"Lauderdale":
{"votes":[
{"votes":196,"name":"mccain"},
{"votes":15,"name":"huckabee"},
{"votes":5,"name":"hunter"},
{"votes":5,"name":"paul"},
{"votes":2,"name":"tancredo"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"giuliani"}],
"total":227,"precincts":
{"total":54,"reporting":6},
"name":"Lauderdale"},
"Amite":
{"votes":[
{"votes":762,"name":"mccain"},
{"votes":120,"name":"huckabee"},
{"votes":21,"name":"romney"},
{"votes":12,"name":"paul"},
{"votes":9,"name":"thompson"},
{"votes":6,"name":"keyes"},
{"votes":5,"name":"giuliani"},
{"votes":1,"name":"tancredo"}],
"total":936,"precincts":
{"total":21,"reporting":21},
"name":"Amite"},
"Walthall":
{"votes":[
{"votes":502,"name":"mccain"},
{"votes":51,"name":"huckabee"},
{"votes":11,"name":"paul"},
{"votes":7,"name":"romney"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"hunter"}],
"total":584,"precincts":
{"total":21,"reporting":15},
"name":"Walthall"},
"DeSoto":
{"votes":[
{"votes":100,"name":"mccain"},
{"votes":17,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"hunter"}],
"total":126,"precincts":
{"total":38,"reporting":2},
"name":"DeSoto"},
"Winston":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Winston"},
"Quitman":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Quitman"},
"Pontotoc":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Pontotoc"},
"Claiborne":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Claiborne"},
"Alcorn":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Alcorn"},
"Jones":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Jones"},
"Pike":
{"votes":[
{"votes":944,"name":"mccain"},
{"votes":123,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":10,"name":"giuliani"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"tancredo"}],
"total":1132,"precincts":
{"total":32,"reporting":18},
"name":"Pike"},
"Stone":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Stone"},
"Choctaw":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Choctaw"},
"Adams":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Adams"},
"Humphreys":
{"votes":[
{"votes":34,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"giuliani"}],
"total":38,"precincts":
{"total":13,"reporting":11},
"name":"Humphreys"},
"Hancock":
{"votes":[
{"votes":97,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":13,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"hunter"}],
"total":136,"precincts":
{"total":26,"reporting":6},
"name":"Hancock"},
"Benton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Benton"},
"Lamar":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lamar"},
"Sharkey":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Sharkey"},
"Coahoma":
{"votes":[
{"votes":41,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":2,"name":"paul"}],
"total":48,"precincts":
{"total":19,"reporting":5},
"name":"Coahoma"},
"Greene":
{"votes":[
{"votes":135,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"paul"}],
"total":170,"precincts":
{"total":14,"reporting":4},
"name":"Greene"},
"Chickasaw":
{"votes":[
{"votes":11,"name":"mccain"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":14,"precincts":
{"total":15,"reporting":1},
"name":"Chickasaw"},
"Tallahatchie":
{"votes":[
{"votes":66,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":3,"name":"paul"}],
"total":82,"precincts":
{"total":22,"reporting":8},
"name":"Tallahatchie"},
"Lafayette":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Lafayette"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Franklin"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Clay"},
"Webster":
{"votes":[
{"votes":309,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":7,"name":"giuliani"},
{"votes":6,"name":"paul"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":374,"precincts":
{"total":17,"reporting":8},
"name":"Webster"},
"Montgomery":
{"votes":[
{"votes":95,"name":"mccain"},
{"votes":12,"name":"huckabee"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"paul"}],
"total":110,"precincts":
{"total":24,"reporting":10},
"name":"Montgomery"},
"Simpson":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Simpson"},
"Kemper":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Kemper"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Madison"},
"Lowndes":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lowndes"},
"Tunica":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Tunica"},
"Smith":
{"votes":[
{"votes":221,"name":"mccain"},
{"votes":36,"name":"huckabee"},
{"votes":5,"name":"tancredo"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"giuliani"}],
"total":266,"precincts":
{"total":19,"reporting":6},
"name":"Smith"},
"Prentiss":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Prentiss"},
"Marshall":
{"votes":[
{"votes":337,"name":"mccain"},
{"votes":62,"name":"huckabee"},
{"votes":12,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":5,"name":"keyes"},
{"votes":4,"name":"romney"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"hunter"}],
"total":435,"precincts":
{"total":24,"reporting":10},
"name":"Marshall"},
"Panola":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Panola"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Washington"},
"Yazoo":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Yazoo"},
"Itawamba":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Itawamba"},
"Neshoba":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Neshoba"},
"Holmes":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Holmes"},
"Wayne":
{"votes":[
{"votes":162,"name":"mccain"},
{"votes":21,"name":"huckabee"},
{"votes":5,"name":"paul"},
{"votes":3,"name":"giuliani"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"thompson"}],
"total":195,"precincts":
{"total":24,"reporting":9},
"name":"Wayne"},
"Scott":
{"votes":[
{"votes":329,"name":"mccain"},
{"votes":45,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"giuliani"}],
"total":391,"precincts":
{"total":24,"reporting":6},
"name":"Scott"},
"Jasper":
{"votes":[
{"votes":128,"name":"mccain"},
{"votes":24,"name":"huckabee"},
{"votes":5,"name":"paul"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":164,"precincts":
{"total":19,"reporting":4},
"name":"Jasper"},
"Harrison":
{"votes":[
{"votes":1215,"name":"mccain"},
{"votes":212,"name":"huckabee"},
{"votes":161,"name":"paul"},
{"votes":66,"name":"romney"},
{"votes":29,"name":"thompson"},
{"votes":21,"name":"giuliani"},
{"votes":14,"name":"keyes"},
{"votes":9,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":1728,"precincts":
{"total":66,"reporting":30},
"name":"Harrison"},
"Issaquena":
{"votes":[
{"votes":25,"name":"mccain"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"paul"}],
"total":29,"precincts":
{"total":5,"reporting":5},
"name":"Issaquena"},
"Oktibbeha":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Oktibbeha"},
"Marion":
{"votes":[
{"votes":255,"name":"mccain"},
{"votes":41,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"paul"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":317,"precincts":
{"total":24,"reporting":6},
"name":"Marion"},
"Forrest":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Forrest"},
"Copiah":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Copiah"},
"Monroe":
{"votes":[
{"votes":204,"name":"mccain"},
{"votes":21,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":5,"name":"romney"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"thompson"},
{"votes":2,"name":"giuliani"}],
"total":244,"precincts":
{"total":25,"reporting":5},
"name":"Monroe"},
"Warren":
{"votes":[
{"votes":555,"name":"mccain"},
{"votes":70,"name":"huckabee"},
{"votes":22,"name":"paul"},
{"votes":12,"name":"thompson"},
{"votes":8,"name":"romney"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":672,"precincts":
{"total":22,"reporting":8},
"name":"Warren"}}})