GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[],
"name":"Montana","precincts":
{"total":871,"reporting":0},
"delegates":16,"date":"06-03"},
"state":"MT","party":"dem","total":0,"locals":
{"Judith Basin":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Judith Basin"},
"Richland":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Richland"},
"Glacier":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Glacier"},
"Silver Bow":
{"votes":[],
"total":0,"precincts":
{"total":45,"reporting":0},
"name":"Silver Bow"},
"Treasure":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Treasure"},
"Petroleum":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Petroleum"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lake"},
"Liberty":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Liberty"},
"Phillips":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Phillips"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Jefferson"},
"Hill":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Hill"},
"Daniels":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Daniels"},
"Granite":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Granite"},
"Wibaux":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wibaux"},
"Valley":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Valley"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Lincoln"},
"Powell":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Powell"},
"Golden Valley":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Golden Valley"},
"Powder River":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Powder River"},
"Custer":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Custer"},
"Park":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Park"},
"Garfield":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Garfield"},
"Chouteau":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Chouteau"},
"Teton":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Teton"},
"Musselshell":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Musselshell"},
"Prairie":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Prairie"},
"Yellowstone":
{"votes":[],
"total":0,"precincts":
{"total":69,"reporting":0},
"name":"Yellowstone"},
"Meagher":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Meagher"},
"Carbon":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Carbon"},
"Stillwater":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Stillwater"},
"Flathead":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Flathead"},
"Sheridan":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Sheridan"},
"Broadwater":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Broadwater"},
"Mineral":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Mineral"},
"Sanders":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Sanders"},
"Fallon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Fallon"},
"Fergus":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fergus"},
"Big Horn":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Big Horn"},
"Ravalli":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Ravalli"},
"Missoula":
{"votes":[],
"total":0,"precincts":
{"total":101,"reporting":0},
"name":"Missoula"},
"Cascade":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Cascade"},
"Roosevelt":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Roosevelt"},
"McCone":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"McCone"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Madison"},
"Beaverhead":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Beaverhead"},
"Carter":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Carter"},
"Sweet Grass":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Sweet Grass"},
"Pondera":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Pondera"},
"Lewis & Clark":
{"votes":[],
"total":0,"precincts":
{"total":56,"reporting":0},
"name":"Lewis & Clark"},
"Deer Lodge":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Deer Lodge"},
"Rosebud":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Rosebud"},
"Wheatland":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Wheatland"},
"Blaine":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Blaine"},
"Dawson":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Dawson"},
"Toole":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Toole"},
"Gallatin":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Gallatin"}}})