GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":101016,"name":"obama","delegates":8},
{"votes":73966,"name":"clinton","delegates":5},
{"votes":4198,"name":"nopreference-d"}],
"name":"Montana","precincts":
{"total":871,"reporting":859},
"delegates":16,"date":"06-03"},
"state":"MT","party":"dem","total":179180,"locals":
{"Judith Basin":
{"votes":[
{"votes":228,"name":"obama"},
{"votes":204,"name":"clinton"},
{"votes":15,"name":"nopreference-d"}],
"total":447,"precincts":
{"total":4,"reporting":4},
"name":"Judith Basin"},
"Richland":
{"votes":[
{"votes":534,"name":"clinton"},
{"votes":463,"name":"obama"}],
"total":997,"precincts":
{"total":15,"reporting":15},
"name":"Richland"},
"Glacier":
{"votes":[
{"votes":1408,"name":"obama"},
{"votes":1096,"name":"clinton"},
{"votes":100,"name":"nopreference-d"}],
"total":2604,"precincts":
{"total":16,"reporting":13},
"name":"Glacier"},
"Silver Bow":
{"votes":[
{"votes":6264,"name":"clinton"},
{"votes":5174,"name":"obama"},
{"votes":311,"name":"nopreference-d"}],
"total":11749,"precincts":
{"total":45,"reporting":45},
"name":"Silver Bow"},
"Treasure":
{"votes":[
{"votes":93,"name":"obama"},
{"votes":85,"name":"clinton"},
{"votes":1,"name":"nopreference-d"}],
"total":179,"precincts":
{"total":3,"reporting":3},
"name":"Treasure"},
"Petroleum":
{"votes":[
{"votes":38,"name":"clinton"},
{"votes":27,"name":"obama"},
{"votes":4,"name":"nopreference-d"}],
"total":69,"precincts":
{"total":1,"reporting":1},
"name":"Petroleum"},
"Lake":
{"votes":[
{"votes":2914,"name":"obama"},
{"votes":2251,"name":"clinton"},
{"votes":77,"name":"nopreference-d"}],
"total":5242,"precincts":
{"total":22,"reporting":22},
"name":"Lake"},
"Liberty":
{"votes":[
{"votes":176,"name":"obama"},
{"votes":163,"name":"clinton"},
{"votes":16,"name":"nopreference-d"}],
"total":355,"precincts":
{"total":4,"reporting":4},
"name":"Liberty"},
"Phillips":
{"votes":[
{"votes":335,"name":"clinton"},
{"votes":329,"name":"obama"},
{"votes":29,"name":"nopreference-d"}],
"total":693,"precincts":
{"total":13,"reporting":13},
"name":"Phillips"},
"Jefferson":
{"votes":[
{"votes":1377,"name":"obama"},
{"votes":991,"name":"clinton"},
{"votes":48,"name":"nopreference-d"}],
"total":2416,"precincts":
{"total":14,"reporting":14},
"name":"Jefferson"},
"Hill":
{"votes":[
{"votes":1504,"name":"obama"},
{"votes":1282,"name":"clinton"},
{"votes":92,"name":"nopreference-d"}],
"total":2878,"precincts":
{"total":22,"reporting":22},
"name":"Hill"},
"Daniels":
{"votes":[
{"votes":197,"name":"clinton"},
{"votes":167,"name":"obama"},
{"votes":27,"name":"nopreference-d"}],
"total":391,"precincts":
{"total":5,"reporting":5},
"name":"Daniels"},
"Granite":
{"votes":[
{"votes":325,"name":"obama"},
{"votes":262,"name":"clinton"},
{"votes":11,"name":"nopreference-d"}],
"total":598,"precincts":
{"total":4,"reporting":4},
"name":"Granite"},
"Wibaux":
{"votes":[
{"votes":53,"name":"clinton"},
{"votes":49,"name":"obama"},
{"votes":3,"name":"nopreference-d"}],
"total":105,"precincts":
{"total":1,"reporting":1},
"name":"Wibaux"},
"Valley":
{"votes":[
{"votes":833,"name":"clinton"},
{"votes":750,"name":"obama"},
{"votes":90,"name":"nopreference-d"}],
"total":1673,"precincts":
{"total":11,"reporting":11},
"name":"Valley"},
"Lincoln":
{"votes":[
{"votes":506,"name":"obama"},
{"votes":492,"name":"clinton"},
{"votes":26,"name":"nopreference-d"}],
"total":1024,"precincts":
{"total":14,"reporting":6},
"name":"Lincoln"},
"Powell":
{"votes":[
{"votes":504,"name":"obama"},
{"votes":409,"name":"clinton"},
{"votes":19,"name":"nopreference-d"}],
"total":932,"precincts":
{"total":12,"reporting":12},
"name":"Powell"},
"Golden Valley":
{"votes":[
{"votes":77,"name":"obama"},
{"votes":65,"name":"clinton"},
{"votes":10,"name":"nopreference-d"}],
"total":152,"precincts":
{"total":2,"reporting":2},
"name":"Golden Valley"},
"Powder River":
{"votes":[
{"votes":59,"name":"obama"},
{"votes":52,"name":"clinton"},
{"votes":3,"name":"nopreference-d"}],
"total":114,"precincts":
{"total":8,"reporting":8},
"name":"Powder River"},
"Custer":
{"votes":[
{"votes":1084,"name":"clinton"},
{"votes":860,"name":"obama"},
{"votes":54,"name":"nopreference-d"}],
"total":1998,"precincts":
{"total":14,"reporting":14},
"name":"Custer"},
"Park":
{"votes":[
{"votes":2253,"name":"obama"},
{"votes":1090,"name":"clinton"},
{"votes":73,"name":"nopreference-d"}],
"total":3416,"precincts":
{"total":15,"reporting":15},
"name":"Park"},
"Garfield":
{"votes":[
{"votes":67,"name":"clinton"},
{"votes":64,"name":"obama"},
{"votes":10,"name":"nopreference-d"}],
"total":141,"precincts":
{"total":7,"reporting":7},
"name":"Garfield"},
"Chouteau":
{"votes":[
{"votes":438,"name":"obama"},
{"votes":396,"name":"clinton"},
{"votes":16,"name":"nopreference-d"}],
"total":850,"precincts":
{"total":12,"reporting":12},
"name":"Chouteau"},
"Teton":
{"votes":[
{"votes":585,"name":"obama"},
{"votes":486,"name":"clinton"},
{"votes":37,"name":"nopreference-d"}],
"total":1108,"precincts":
{"total":5,"reporting":5},
"name":"Teton"},
"Musselshell":
{"votes":[
{"votes":259,"name":"clinton"},
{"votes":220,"name":"obama"},
{"votes":11,"name":"nopreference-d"}],
"total":490,"precincts":
{"total":6,"reporting":6},
"name":"Musselshell"},
"Prairie":
{"votes":[
{"votes":122,"name":"clinton"},
{"votes":90,"name":"obama"},
{"votes":15,"name":"nopreference-d"}],
"total":227,"precincts":
{"total":4,"reporting":4},
"name":"Prairie"},
"Yellowstone":
{"votes":[
{"votes":12089,"name":"obama"},
{"votes":11475,"name":"clinton"},
{"votes":575,"name":"nopreference-d"}],
"total":24139,"precincts":
{"total":69,"reporting":69},
"name":"Yellowstone"},
"Meagher":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Meagher"},
"Carbon":
{"votes":[
{"votes":1137,"name":"obama"},
{"votes":866,"name":"clinton"},
{"votes":44,"name":"nopreference-d"}],
"total":2047,"precincts":
{"total":16,"reporting":16},
"name":"Carbon"},
"Stillwater":
{"votes":[
{"votes":863,"name":"obama"},
{"votes":713,"name":"clinton"},
{"votes":61,"name":"nopreference-d"}],
"total":1637,"precincts":
{"total":8,"reporting":8},
"name":"Stillwater"},
"Flathead":
{"votes":[
{"votes":6588,"name":"obama"},
{"votes":4096,"name":"clinton"},
{"votes":202,"name":"nopreference-d"}],
"total":10886,"precincts":
{"total":42,"reporting":42},
"name":"Flathead"},
"Sheridan":
{"votes":[
{"votes":210,"name":"obama"},
{"votes":208,"name":"clinton"},
{"votes":22,"name":"nopreference-d"}],
"total":440,"precincts":
{"total":6,"reporting":6},
"name":"Sheridan"},
"Broadwater":
{"votes":[
{"votes":446,"name":"obama"},
{"votes":380,"name":"clinton"},
{"votes":42,"name":"nopreference-d"}],
"total":868,"precincts":
{"total":5,"reporting":5},
"name":"Broadwater"},
"Mineral":
{"votes":[
{"votes":417,"name":"obama"},
{"votes":383,"name":"clinton"},
{"votes":29,"name":"nopreference-d"}],
"total":829,"precincts":
{"total":6,"reporting":6},
"name":"Mineral"},
"Sanders":
{"votes":[
{"votes":787,"name":"obama"},
{"votes":660,"name":"clinton"},
{"votes":61,"name":"nopreference-d"}],
"total":1508,"precincts":
{"total":10,"reporting":10},
"name":"Sanders"},
"Fallon":
{"votes":[
{"votes":163,"name":"obama"},
{"votes":147,"name":"clinton"},
{"votes":13,"name":"nopreference-d"}],
"total":323,"precincts":
{"total":6,"reporting":6},
"name":"Fallon"},
"Fergus":
{"votes":[
{"votes":943,"name":"obama"},
{"votes":758,"name":"clinton"}],
"total":1701,"precincts":
{"total":16,"reporting":16},
"name":"Fergus"},
"Big Horn":
{"votes":[
{"votes":2134,"name":"obama"},
{"votes":564,"name":"clinton"},
{"votes":38,"name":"nopreference-d"}],
"total":2736,"precincts":
{"total":20,"reporting":20},
"name":"Big Horn"},
"Ravalli":
{"votes":[
{"votes":3834,"name":"obama"},
{"votes":2786,"name":"clinton"},
{"votes":114,"name":"nopreference-d"}],
"total":6734,"precincts":
{"total":22,"reporting":22},
"name":"Ravalli"},
"Missoula":
{"votes":[
{"votes":16035,"name":"obama"},
{"votes":7949,"name":"clinton"},
{"votes":340,"name":"nopreference-d"}],
"total":24324,"precincts":
{"total":101,"reporting":101},
"name":"Missoula"},
"Cascade":
{"votes":[
{"votes":7788,"name":"obama"},
{"votes":7220,"name":"clinton"},
{"votes":603,"name":"nopreference-d"}],
"total":15611,"precincts":
{"total":38,"reporting":38},
"name":"Cascade"},
"Roosevelt":
{"votes":[
{"votes":904,"name":"obama"},
{"votes":642,"name":"clinton"},
{"votes":64,"name":"nopreference-d"}],
"total":1610,"precincts":
{"total":13,"reporting":13},
"name":"Roosevelt"},
"McCone":
{"votes":[
{"votes":169,"name":"obama"},
{"votes":161,"name":"clinton"}],
"total":330,"precincts":
{"total":3,"reporting":3},
"name":"McCone"},
"Madison":
{"votes":[
{"votes":815,"name":"obama"},
{"votes":435,"name":"clinton"},
{"votes":44,"name":"nopreference-d"}],
"total":1294,"precincts":
{"total":8,"reporting":8},
"name":"Madison"},
"Beaverhead":
{"votes":[
{"votes":747,"name":"obama"},
{"votes":405,"name":"clinton"}],
"total":1152,"precincts":
{"total":16,"reporting":16},
"name":"Beaverhead"},
"Carter":
{"votes":[
{"votes":70,"name":"obama"},
{"votes":52,"name":"clinton"},
{"votes":6,"name":"nopreference-d"}],
"total":128,"precincts":
{"total":4,"reporting":4},
"name":"Carter"},
"Sweet Grass":
{"votes":[
{"votes":247,"name":"obama"},
{"votes":199,"name":"clinton"},
{"votes":6,"name":"nopreference-d"}],
"total":452,"precincts":
{"total":5,"reporting":5},
"name":"Sweet Grass"},
"Pondera":
{"votes":[
{"votes":639,"name":"obama"},
{"votes":480,"name":"clinton"},
{"votes":35,"name":"nopreference-d"}],
"total":1154,"precincts":
{"total":8,"reporting":8},
"name":"Pondera"},
"Lewis & Clark":
{"votes":[
{"votes":9017,"name":"obama"},
{"votes":5758,"name":"clinton"},
{"votes":341,"name":"nopreference-d"}],
"total":15116,"precincts":
{"total":56,"reporting":56},
"name":"Lewis & Clark"},
"Deer Lodge":
{"votes":[
{"votes":1750,"name":"clinton"},
{"votes":1142,"name":"obama"},
{"votes":84,"name":"nopreference-d"}],
"total":2976,"precincts":
{"total":18,"reporting":18},
"name":"Deer Lodge"},
"Rosebud":
{"votes":[
{"votes":894,"name":"obama"},
{"votes":662,"name":"clinton"},
{"votes":67,"name":"nopreference-d"}],
"total":1623,"precincts":
{"total":12,"reporting":12},
"name":"Rosebud"},
"Wheatland":
{"votes":[
{"votes":162,"name":"clinton"},
{"votes":157,"name":"obama"},
{"votes":13,"name":"nopreference-d"}],
"total":332,"precincts":
{"total":5,"reporting":5},
"name":"Wheatland"},
"Blaine":
{"votes":[
{"votes":698,"name":"obama"},
{"votes":568,"name":"clinton"},
{"votes":56,"name":"nopreference-d"}],
"total":1322,"precincts":
{"total":10,"reporting":10},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":785,"name":"clinton"},
{"votes":643,"name":"obama"},
{"votes":63,"name":"nopreference-d"}],
"total":1491,"precincts":
{"total":12,"reporting":12},
"name":"Dawson"},
"Toole":
{"votes":[
{"votes":454,"name":"clinton"},
{"votes":390,"name":"obama"},
{"votes":27,"name":"nopreference-d"}],
"total":871,"precincts":
{"total":10,"reporting":10},
"name":"Toole"},
"Gallatin":
{"votes":[
{"votes":10410,"name":"obama"},
{"votes":4138,"name":"clinton"},
{"votes":150,"name":"nopreference-d"}],
"total":14698,"precincts":
{"total":46,"reporting":46},
"name":"Gallatin"}}})