GoogleElectionMap.votesReady({"status":"ok","totals":
{"name":"Montana","precincts":
{"total":56,"reporting":56},
"votes":[
{"votes":42070,"name":"mccain"},
{"votes":11092,"name":"paul"},
{"votes":1186,"name":"nopreference-r"},
{"votes":625,"name":"romney","delegates":25},
{"votes":245,"name":"huckabee"},
{"votes":2,"name":"keyes"}],
"delegates":25,"date":"02-05","type":"caucus"},
"state":"MT","party":"gop","total":55220,"locals":
{"Judith Basin":
{"votes":[
{"votes":5,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"mccain"}],
"total":13,"precincts":
{"total":1,"reporting":1},
"name":"Judith Basin"},
"Richland":
{"votes":[
{"votes":14,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"mccain"}],
"total":22,"precincts":
{"total":1,"reporting":1},
"name":"Richland"},
"Glacier":
{"votes":[
{"votes":11,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":4,"name":"paul"},
{"votes":3,"name":"romney"}],
"total":23,"precincts":
{"total":1,"reporting":1},
"name":"Glacier"},
"Silver Bow":
{"votes":[
{"votes":378,"name":"mccain"},
{"votes":56,"name":"paul"},
{"votes":17,"name":"nopreference-r"},
{"votes":7,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":463,"precincts":
{"total":1,"reporting":1},
"name":"Silver Bow"},
"Treasure":
{"votes":[
{"votes":109,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":143,"precincts":
{"total":1,"reporting":1},
"name":"Treasure"},
"Petroleum":
{"votes":[
{"votes":66,"name":"mccain"},
{"votes":22,"name":"paul"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"nopreference-r"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":96,"precincts":
{"total":1,"reporting":1},
"name":"Petroleum"},
"Lake":
{"votes":[
{"votes":18,"name":"paul"},
{"votes":14,"name":"romney"},
{"votes":8,"name":"mccain"},
{"votes":3,"name":"huckabee"}],
"total":43,"precincts":
{"total":1,"reporting":1},
"name":"Lake"},
"Liberty":
{"votes":[
{"votes":209,"name":"mccain"},
{"votes":70,"name":"paul"},
{"votes":12,"name":"nopreference-r"},
{"votes":5,"name":"romney"}],
"total":296,"precincts":
{"total":1,"reporting":1},
"name":"Liberty"},
"Phillips":
{"votes":[
{"votes":9,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":15,"precincts":
{"total":1,"reporting":1},
"name":"Phillips"},
"Jefferson":
{"votes":[
{"votes":563,"name":"mccain"},
{"votes":141,"name":"paul"},
{"votes":10,"name":"nopreference-r"},
{"votes":10,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":729,"precincts":
{"total":1,"reporting":1},
"name":"Jefferson"},
"Hill":
{"votes":[
{"votes":29,"name":"mccain"},
{"votes":11,"name":"huckabee"},
{"votes":11,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":2,"name":"nopreference-r"}],
"total":57,"precincts":
{"total":1,"reporting":1},
"name":"Hill"},
"Daniels":
{"votes":[
{"votes":209,"name":"mccain"},
{"votes":71,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":7,"name":"nopreference-r"}],
"total":296,"precincts":
{"total":1,"reporting":1},
"name":"Daniels"},
"Granite":
{"votes":[
{"votes":244,"name":"mccain"},
{"votes":55,"name":"paul"},
{"votes":6,"name":"nopreference-r"},
{"votes":5,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":311,"precincts":
{"total":1,"reporting":1},
"name":"Granite"},
"Wibaux":
{"votes":[
{"votes":158,"name":"mccain"},
{"votes":95,"name":"paul"},
{"votes":15,"name":"nopreference-r"},
{"votes":1,"name":"huckabee"}],
"total":269,"precincts":
{"total":1,"reporting":1},
"name":"Wibaux"},
"Valley":
{"votes":[
{"votes":193,"name":"mccain"},
{"votes":40,"name":"paul"},
{"votes":3,"name":"nopreference-r"},
{"votes":3,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":240,"precincts":
{"total":1,"reporting":1},
"name":"Valley"},
"Lincoln":
{"votes":[
{"votes":352,"name":"mccain"},
{"votes":136,"name":"paul"},
{"votes":46,"name":"nopreference-r"},
{"votes":17,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":552,"precincts":
{"total":1,"reporting":1},
"name":"Lincoln"},
"Powell":
{"votes":[
{"votes":195,"name":"mccain"},
{"votes":30,"name":"paul"},
{"votes":14,"name":"romney"},
{"votes":8,"name":"nopreference-r"},
{"votes":2,"name":"huckabee"}],
"total":249,"precincts":
{"total":1,"reporting":1},
"name":"Powell"},
"Golden Valley":
{"votes":[
{"votes":99,"name":"mccain"},
{"votes":52,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":4,"name":"nopreference-r"},
{"votes":2,"name":"huckabee"}],
"total":163,"precincts":
{"total":1,"reporting":1},
"name":"Golden Valley"},
"Powder River":
{"votes":[
{"votes":442,"name":"mccain"},
{"votes":118,"name":"paul"},
{"votes":18,"name":"nopreference-r"},
{"votes":7,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":587,"precincts":
{"total":1,"reporting":1},
"name":"Powder River"},
"Custer":
{"votes":[
{"votes":1005,"name":"mccain"},
{"votes":133,"name":"paul"},
{"votes":19,"name":"nopreference-r"},
{"votes":15,"name":"huckabee"},
{"votes":11,"name":"romney"}],
"total":1183,"precincts":
{"total":1,"reporting":1},
"name":"Custer"},
"Park":
{"votes":[
{"votes":1505,"name":"mccain"},
{"votes":626,"name":"paul"},
{"votes":37,"name":"nopreference-r"},
{"votes":6,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":2175,"precincts":
{"total":1,"reporting":1},
"name":"Park"},
"Garfield":
{"votes":[
{"votes":9,"name":"romney"},
{"votes":9,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":1,"name":"paul"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Garfield"},
"Chouteau":
{"votes":[
{"votes":860,"name":"mccain"},
{"votes":210,"name":"paul"},
{"votes":57,"name":"nopreference-r"},
{"votes":7,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":1138,"precincts":
{"total":1,"reporting":1},
"name":"Chouteau"},
"Teton":
{"votes":[
{"votes":16,"name":"romney"},
{"votes":5,"name":"mccain"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"huckabee"}],
"total":26,"precincts":
{"total":1,"reporting":1},
"name":"Teton"},
"Musselshell":
{"votes":[
{"votes":603,"name":"mccain"},
{"votes":179,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":798,"precincts":
{"total":1,"reporting":1},
"name":"Musselshell"},
"Prairie":
{"votes":[
{"votes":220,"name":"mccain"},
{"votes":59,"name":"paul"},
{"votes":14,"name":"nopreference-r"},
{"votes":8,"name":"romney"},
{"votes":2,"name":"huckabee"}],
"total":303,"precincts":
{"total":1,"reporting":1},
"name":"Prairie"},
"Yellowstone":
{"votes":[
{"votes":7484,"name":"mccain"},
{"votes":1323,"name":"paul"},
{"votes":195,"name":"nopreference-r"},
{"votes":47,"name":"romney"},
{"votes":23,"name":"huckabee"}],
"total":9072,"precincts":
{"total":1,"reporting":1},
"name":"Yellowstone"},
"Meagher":
{"votes":[
{"votes":19,"name":"mccain"},
{"votes":4,"name":"romney"},
{"votes":1,"name":"huckabee"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Meagher"},
"Carbon":
{"votes":[
{"votes":429,"name":"mccain"},
{"votes":140,"name":"paul"},
{"votes":21,"name":"romney"},
{"votes":13,"name":"nopreference-r"},
{"votes":4,"name":"huckabee"}],
"total":607,"precincts":
{"total":1,"reporting":1},
"name":"Carbon"},
"Stillwater":
{"votes":[
{"votes":618,"name":"mccain"},
{"votes":117,"name":"paul"},
{"votes":10,"name":"romney"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"nopreference-r"}],
"total":751,"precincts":
{"total":1,"reporting":1},
"name":"Stillwater"},
"Flathead":
{"votes":[
{"votes":6637,"name":"mccain"},
{"votes":3040,"name":"paul"},
{"votes":232,"name":"nopreference-r"},
{"votes":36,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":9950,"precincts":
{"total":1,"reporting":1},
"name":"Flathead"},
"Sheridan":
{"votes":[
{"votes":71,"name":"mccain"},
{"votes":11,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":2,"name":"nopreference-r"}],
"total":90,"precincts":
{"total":1,"reporting":1},
"name":"Sheridan"},
"Broadwater":
{"votes":[
{"votes":5,"name":"romney"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"paul"},
{"votes":2,"name":"mccain"}],
"total":13,"precincts":
{"total":1,"reporting":1},
"name":"Broadwater"},
"Mineral":
{"votes":[
{"votes":8,"name":"romney"},
{"votes":4,"name":"paul"},
{"votes":2,"name":"mccain"}],
"total":14,"precincts":
{"total":1,"reporting":1},
"name":"Mineral"},
"Sanders":
{"votes":[
{"votes":61,"name":"mccain"},
{"votes":13,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":88,"precincts":
{"total":1,"reporting":1},
"name":"Sanders"},
"Fallon":
{"votes":[
{"votes":433,"name":"mccain"},
{"votes":103,"name":"paul"},
{"votes":36,"name":"nopreference-r"},
{"votes":13,"name":"romney"}],
"total":585,"precincts":
{"total":1,"reporting":1},
"name":"Fallon"},
"Fergus":
{"votes":[
{"votes":11,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":6,"name":"mccain"}],
"total":35,"precincts":
{"total":1,"reporting":1},
"name":"Fergus"},
"Big Horn":
{"votes":[
{"votes":338,"name":"mccain"},
{"votes":56,"name":"paul"},
{"votes":7,"name":"huckabee"},
{"votes":7,"name":"nopreference-r"},
{"votes":6,"name":"romney"}],
"total":414,"precincts":
{"total":1,"reporting":1},
"name":"Big Horn"},
"Ravalli":
{"votes":[
{"votes":976,"name":"mccain"},
{"votes":187,"name":"paul"},
{"votes":32,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":1199,"precincts":
{"total":1,"reporting":1},
"name":"Ravalli"},
"Missoula":
{"votes":[
{"votes":4127,"name":"mccain"},
{"votes":1215,"name":"paul"},
{"votes":76,"name":"nopreference-r"},
{"votes":42,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":5463,"precincts":
{"total":1,"reporting":1},
"name":"Missoula"},
"Cascade":
{"votes":[
{"votes":3848,"name":"mccain"},
{"votes":647,"name":"paul"},
{"votes":77,"name":"nopreference-r"},
{"votes":15,"name":"romney"},
{"votes":5,"name":"huckabee"}],
"total":4592,"precincts":
{"total":1,"reporting":1},
"name":"Cascade"},
"Roosevelt":
{"votes":[
{"votes":227,"name":"mccain"},
{"votes":58,"name":"paul"},
{"votes":8,"name":"nopreference-r"},
{"votes":2,"name":"huckabee"},
{"votes":1,"name":"romney"}],
"total":296,"precincts":
{"total":1,"reporting":1},
"name":"Roosevelt"},
"McCone":
{"votes":[
{"votes":224,"name":"mccain"},
{"votes":83,"name":"paul"},
{"votes":6,"name":"huckabee"},
{"votes":4,"name":"romney"}],
"total":317,"precincts":
{"total":1,"reporting":1},
"name":"McCone"},
"Madison":
{"votes":[
{"votes":673,"name":"mccain"},
{"votes":120,"name":"paul"},
{"votes":18,"name":"nopreference-r"},
{"votes":3,"name":"romney"}],
"total":814,"precincts":
{"total":1,"reporting":1},
"name":"Madison"},
"Beaverhead":
{"votes":[
{"votes":205,"name":"mccain"},
{"votes":37,"name":"paul"},
{"votes":15,"name":"romney"},
{"votes":6,"name":"huckabee"}],
"total":263,"precincts":
{"total":1,"reporting":1},
"name":"Beaverhead"},
"Carter":
{"votes":[
{"votes":215,"name":"mccain"},
{"votes":86,"name":"paul"},
{"votes":14,"name":"huckabee"},
{"votes":13,"name":"nopreference-r"}],
"total":328,"precincts":
{"total":1,"reporting":1},
"name":"Carter"},
"Sweet Grass":
{"votes":[
{"votes":588,"name":"mccain"},
{"votes":140,"name":"paul"},
{"votes":12,"name":"huckabee"},
{"votes":11,"name":"nopreference-r"},
{"votes":2,"name":"romney"}],
"total":753,"precincts":
{"total":1,"reporting":1},
"name":"Sweet Grass"},
"Pondera":
{"votes":[
{"votes":654,"name":"mccain"},
{"votes":124,"name":"paul"},
{"votes":30,"name":"nopreference-r"},
{"votes":15,"name":"romney"},
{"votes":4,"name":"huckabee"}],
"total":827,"precincts":
{"total":1,"reporting":1},
"name":"Pondera"},
"Lewis & Clark":
{"votes":[
{"votes":2454,"name":"mccain"},
{"votes":433,"name":"paul"},
{"votes":59,"name":"nopreference-r"},
{"votes":36,"name":"romney"},
{"votes":10,"name":"huckabee"}],
"total":2992,"precincts":
{"total":1,"reporting":1},
"name":"Lewis & Clark"},
"Deer Lodge":
{"votes":[
{"votes":374,"name":"mccain"},
{"votes":57,"name":"paul"},
{"votes":9,"name":"nopreference-r"},
{"votes":3,"name":"huckabee"}],
"total":443,"precincts":
{"total":1,"reporting":1},
"name":"Deer Lodge"},
"Rosebud":
{"votes":[
{"votes":408,"name":"mccain"},
{"votes":90,"name":"paul"},
{"votes":7,"name":"nopreference-r"},
{"votes":6,"name":"romney"}],
"total":511,"precincts":
{"total":1,"reporting":1},
"name":"Rosebud"},
"Wheatland":
{"votes":[
{"votes":152,"name":"mccain"},
{"votes":35,"name":"paul"},
{"votes":18,"name":"romney"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"nopreference-r"}],
"total":209,"precincts":
{"total":1,"reporting":1},
"name":"Wheatland"},
"Blaine":
{"votes":[
{"votes":12,"name":"paul"},
{"votes":6,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":3,"name":"romney"}],
"total":26,"precincts":
{"total":1,"reporting":1},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":946,"name":"mccain"},
{"votes":269,"name":"paul"},
{"votes":44,"name":"nopreference-r"},
{"votes":11,"name":"romney"},
{"votes":8,"name":"huckabee"},
{"votes":1,"name":"keyes"}],
"total":1279,"precincts":
{"total":1,"reporting":1},
"name":"Dawson"},
"Toole":
{"votes":[
{"votes":13,"name":"mccain"},
{"votes":10,"name":"romney"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"nopreference-r"},
{"votes":1,"name":"paul"}],
"total":26,"precincts":
{"total":1,"reporting":1},
"name":"Toole"},
"Gallatin":
{"votes":[
{"votes":2465,"name":"mccain"},
{"votes":575,"name":"paul"},
{"votes":68,"name":"nopreference-r"},
{"votes":47,"name":"romney"},
{"votes":11,"name":"huckabee"}],
"total":3166,"precincts":
{"total":1,"reporting":1},
"name":"Gallatin"}}})