GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":890695,"name":"obama","delegates":65},
{"votes":657920,"name":"clinton","delegates":50},
{"votes":22722,"name":"nopreference-d"},
{"votes":12486,"name":"gravel"}],
"name":"North Carolina","precincts":
{"total":2817,"reporting":2807},
"delegates":115,"date":"05-06"},
"state":"NC","party":"dem","total":1583823,"locals":
{"Bladen":
{"votes":[
{"votes":4270,"name":"clinton"},
{"votes":4146,"name":"obama"},
{"votes":284,"name":"nopreference-d"},
{"votes":151,"name":"gravel"}],
"total":8851,"precincts":
{"total":17,"reporting":17},
"name":"Bladen"},
"Currituck":
{"votes":[
{"votes":2167,"name":"clinton"},
{"votes":1231,"name":"obama"},
{"votes":178,"name":"nopreference-d"},
{"votes":77,"name":"gravel"}],
"total":3653,"precincts":
{"total":11,"reporting":11},
"name":"Currituck"},
"Union":
{"votes":[
{"votes":10090,"name":"clinton"},
{"votes":9616,"name":"obama"},
{"votes":209,"name":"nopreference-d"},
{"votes":118,"name":"gravel"}],
"total":20033,"precincts":
{"total":49,"reporting":49},
"name":"Union"},
"Wilson":
{"votes":[
{"votes":9556,"name":"obama"},
{"votes":5474,"name":"clinton"},
{"votes":217,"name":"nopreference-d"},
{"votes":126,"name":"gravel"}],
"total":15373,"precincts":
{"total":25,"reporting":25},
"name":"Wilson"},
"Montgomery":
{"votes":[
{"votes":2775,"name":"clinton"},
{"votes":2103,"name":"obama"},
{"votes":142,"name":"nopreference-d"},
{"votes":95,"name":"gravel"}],
"total":5115,"precincts":
{"total":14,"reporting":14},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":10402,"name":"obama"},
{"votes":6783,"name":"clinton"},
{"votes":450,"name":"nopreference-d"},
{"votes":190,"name":"gravel"}],
"total":17825,"precincts":
{"total":30,"reporting":30},
"name":"Wayne"},
"Robeson":
{"votes":[
{"votes":12673,"name":"clinton"},
{"votes":9758,"name":"obama"},
{"votes":835,"name":"nopreference-d"},
{"votes":356,"name":"gravel"}],
"total":23622,"precincts":
{"total":41,"reporting":41},
"name":"Robeson"},
"Brunswick":
{"votes":[
{"votes":9104,"name":"clinton"},
{"votes":7216,"name":"obama"},
{"votes":224,"name":"nopreference-d"},
{"votes":168,"name":"gravel"}],
"total":16712,"precincts":
{"total":23,"reporting":23},
"name":"Brunswick"},
"Henderson":
{"votes":[
{"votes":8394,"name":"clinton"},
{"votes":5913,"name":"obama"},
{"votes":125,"name":"nopreference-d"},
{"votes":77,"name":"gravel"}],
"total":14509,"precincts":
{"total":35,"reporting":35},
"name":"Henderson"},
"Cherokee":
{"votes":[
{"votes":2350,"name":"clinton"},
{"votes":792,"name":"obama"},
{"votes":46,"name":"nopreference-d"},
{"votes":36,"name":"gravel"}],
"total":3224,"precincts":
{"total":16,"reporting":16},
"name":"Cherokee"},
"Anson":
{"votes":[
{"votes":3187,"name":"obama"},
{"votes":2374,"name":"clinton"},
{"votes":94,"name":"nopreference-d"},
{"votes":46,"name":"gravel"}],
"total":5701,"precincts":
{"total":11,"reporting":11},
"name":"Anson"},
"Catawba":
{"votes":[
{"votes":9746,"name":"clinton"},
{"votes":7251,"name":"obama"},
{"votes":188,"name":"nopreference-d"},
{"votes":107,"name":"gravel"}],
"total":17292,"precincts":
{"total":41,"reporting":41},
"name":"Catawba"},
"Yadkin":
{"votes":[
{"votes":2276,"name":"clinton"},
{"votes":964,"name":"obama"},
{"votes":98,"name":"gravel"},
{"votes":49,"name":"nopreference-d"}],
"total":3387,"precincts":
{"total":12,"reporting":12},
"name":"Yadkin"},
"Stokes":
{"votes":[
{"votes":3901,"name":"clinton"},
{"votes":1706,"name":"obama"},
{"votes":96,"name":"nopreference-d"},
{"votes":65,"name":"gravel"}],
"total":5768,"precincts":
{"total":23,"reporting":23},
"name":"Stokes"},
"Pasquotank":
{"votes":[
{"votes":4490,"name":"obama"},
{"votes":2463,"name":"clinton"},
{"votes":144,"name":"nopreference-d"},
{"votes":59,"name":"gravel"}],
"total":7156,"precincts":
{"total":13,"reporting":13},
"name":"Pasquotank"},
"Hoke":
{"votes":[
{"votes":4142,"name":"obama"},
{"votes":2050,"name":"clinton"},
{"votes":99,"name":"nopreference-d"},
{"votes":56,"name":"gravel"}],
"total":6347,"precincts":
{"total":13,"reporting":13},
"name":"Hoke"},
"Wilkes":
{"votes":[
{"votes":5514,"name":"clinton"},
{"votes":1986,"name":"obama"},
{"votes":118,"name":"nopreference-d"},
{"votes":81,"name":"gravel"}],
"total":7699,"precincts":
{"total":28,"reporting":28},
"name":"Wilkes"},
"Alamance":
{"votes":[
{"votes":11655,"name":"obama"},
{"votes":8338,"name":"clinton"},
{"votes":375,"name":"nopreference-d"},
{"votes":214,"name":"gravel"}],
"total":20582,"precincts":
{"total":37,"reporting":37},
"name":"Alamance"},
"Moore":
{"votes":[
{"votes":6492,"name":"obama"},
{"votes":5453,"name":"clinton"},
{"votes":174,"name":"nopreference-d"},
{"votes":98,"name":"gravel"}],
"total":12217,"precincts":
{"total":24,"reporting":24},
"name":"Moore"},
"Washington":
{"votes":[
{"votes":2218,"name":"obama"},
{"votes":1479,"name":"clinton"},
{"votes":87,"name":"nopreference-d"},
{"votes":60,"name":"gravel"}],
"total":3844,"precincts":
{"total":6,"reporting":6},
"name":"Washington"},
"Duplin":
{"votes":[
{"votes":4004,"name":"clinton"},
{"votes":3680,"name":"obama"},
{"votes":202,"name":"nopreference-d"},
{"votes":99,"name":"gravel"}],
"total":7985,"precincts":
{"total":20,"reporting":18},
"name":"Duplin"},
"Cabarrus":
{"votes":[
{"votes":10648,"name":"obama"},
{"votes":9875,"name":"clinton"},
{"votes":272,"name":"nopreference-d"},
{"votes":145,"name":"gravel"}],
"total":20940,"precincts":
{"total":49,"reporting":49},
"name":"Cabarrus"},
"Camden":
{"votes":[
{"votes":854,"name":"clinton"},
{"votes":648,"name":"obama"},
{"votes":52,"name":"nopreference-d"},
{"votes":28,"name":"gravel"}],
"total":1582,"precincts":
{"total":3,"reporting":3},
"name":"Camden"},
"New Hanover":
{"votes":[
{"votes":18304,"name":"obama"},
{"votes":13367,"name":"clinton"},
{"votes":363,"name":"nopreference-d"},
{"votes":200,"name":"gravel"}],
"total":32234,"precincts":
{"total":43,"reporting":43},
"name":"New Hanover"},
"Polk":
{"votes":[
{"votes":1871,"name":"clinton"},
{"votes":1548,"name":"obama"},
{"votes":30,"name":"nopreference-d"},
{"votes":26,"name":"gravel"}],
"total":3475,"precincts":
{"total":7,"reporting":7},
"name":"Polk"},
"Warren":
{"votes":[
{"votes":3648,"name":"obama"},
{"votes":1627,"name":"clinton"},
{"votes":86,"name":"nopreference-d"},
{"votes":66,"name":"gravel"}],
"total":5427,"precincts":
{"total":14,"reporting":14},
"name":"Warren"},
"Watauga":
{"votes":[
{"votes":4570,"name":"obama"},
{"votes":3645,"name":"clinton"},
{"votes":62,"name":"nopreference-d"},
{"votes":32,"name":"gravel"}],
"total":8309,"precincts":
{"total":20,"reporting":20},
"name":"Watauga"},
"Jackson":
{"votes":[
{"votes":4341,"name":"clinton"},
{"votes":2448,"name":"obama"},
{"votes":165,"name":"nopreference-d"},
{"votes":75,"name":"gravel"}],
"total":7029,"precincts":
{"total":18,"reporting":18},
"name":"Jackson"},
"Transylvania":
{"votes":[
{"votes":3138,"name":"clinton"},
{"votes":2656,"name":"obama"},
{"votes":95,"name":"nopreference-d"},
{"votes":52,"name":"gravel"}],
"total":5941,"precincts":
{"total":18,"reporting":18},
"name":"Transylvania"},
"Caldwell":
{"votes":[
{"votes":6096,"name":"clinton"},
{"votes":2521,"name":"obama"},
{"votes":217,"name":"nopreference-d"},
{"votes":139,"name":"gravel"}],
"total":8973,"precincts":
{"total":24,"reporting":24},
"name":"Caldwell"},
"Onslow":
{"votes":[
{"votes":5717,"name":"obama"},
{"votes":5442,"name":"clinton"},
{"votes":338,"name":"nopreference-d"},
{"votes":201,"name":"gravel"}],
"total":11698,"precincts":
{"total":27,"reporting":27},
"name":"Onslow"},
"Granville":
{"votes":[
{"votes":6497,"name":"obama"},
{"votes":4273,"name":"clinton"},
{"votes":233,"name":"nopreference-d"},
{"votes":104,"name":"gravel"}],
"total":11107,"precincts":
{"total":15,"reporting":15},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":27824,"name":"obama"},
{"votes":11540,"name":"clinton"},
{"votes":363,"name":"nopreference-d"},
{"votes":249,"name":"gravel"}],
"total":39976,"precincts":
{"total":44,"reporting":44},
"name":"Orange"},
"Burke":
{"votes":[
{"votes":8170,"name":"clinton"},
{"votes":3633,"name":"obama"},
{"votes":141,"name":"nopreference-d"},
{"votes":103,"name":"gravel"}],
"total":12047,"precincts":
{"total":31,"reporting":31},
"name":"Burke"},
"Lee":
{"votes":[
{"votes":5288,"name":"clinton"},
{"votes":4193,"name":"obama"},
{"votes":324,"name":"nopreference-d"},
{"votes":139,"name":"gravel"}],
"total":9944,"precincts":
{"total":9,"reporting":9},
"name":"Lee"},
"Avery":
{"votes":[
{"votes":724,"name":"clinton"},
{"votes":417,"name":"obama"},
{"votes":13,"name":"nopreference-d"},
{"votes":7,"name":"gravel"}],
"total":1161,"precincts":
{"total":20,"reporting":20},
"name":"Avery"},
"Buncombe":
{"votes":[
{"votes":27899,"name":"obama"},
{"votes":22290,"name":"clinton"},
{"votes":523,"name":"nopreference-d"},
{"votes":321,"name":"gravel"}],
"total":51033,"precincts":
{"total":78,"reporting":78},
"name":"Buncombe"},
"Guilford":
{"votes":[
{"votes":63852,"name":"obama"},
{"votes":28033,"name":"clinton"},
{"votes":1199,"name":"nopreference-d"},
{"votes":557,"name":"gravel"}],
"total":93641,"precincts":
{"total":163,"reporting":163},
"name":"Guilford"},
"Durham":
{"votes":[
{"votes":53096,"name":"obama"},
{"votes":16601,"name":"clinton"},
{"votes":711,"name":"nopreference-d"},
{"votes":250,"name":"gravel"}],
"total":70658,"precincts":
{"total":61,"reporting":61},
"name":"Durham"},
"Wake":
{"votes":[
{"votes":127942,"name":"obama"},
{"votes":66580,"name":"clinton"},
{"votes":1299,"name":"nopreference-d"},
{"votes":684,"name":"gravel"}],
"total":196505,"precincts":
{"total":210,"reporting":210},
"name":"Wake"},
"Chatham":
{"votes":[
{"votes":8712,"name":"obama"},
{"votes":6175,"name":"clinton"},
{"votes":279,"name":"nopreference-d"},
{"votes":150,"name":"gravel"}],
"total":15316,"precincts":
{"total":19,"reporting":19},
"name":"Chatham"},
"Beaufort":
{"votes":[
{"votes":4581,"name":"obama"},
{"votes":4087,"name":"clinton"},
{"votes":205,"name":"nopreference-d"},
{"votes":151,"name":"gravel"}],
"total":9024,"precincts":
{"total":23,"reporting":21},
"name":"Beaufort"},
"Vance":
{"votes":[
{"votes":6905,"name":"obama"},
{"votes":4014,"name":"clinton"},
{"votes":243,"name":"nopreference-d"},
{"votes":91,"name":"gravel"}],
"total":11253,"precincts":
{"total":16,"reporting":16},
"name":"Vance"},
"Rutherford":
{"votes":[
{"votes":5765,"name":"clinton"},
{"votes":3133,"name":"obama"},
{"votes":304,"name":"nopreference-d"},
{"votes":110,"name":"gravel"}],
"total":9312,"precincts":
{"total":20,"reporting":20},
"name":"Rutherford"},
"Harnett":
{"votes":[
{"votes":7106,"name":"clinton"},
{"votes":6058,"name":"obama"},
{"votes":214,"name":"nopreference-d"},
{"votes":165,"name":"gravel"}],
"total":13543,"precincts":
{"total":18,"reporting":18},
"name":"Harnett"},
"Davie":
{"votes":[
{"votes":2544,"name":"clinton"},
{"votes":1804,"name":"obama"},
{"votes":76,"name":"nopreference-d"},
{"votes":47,"name":"gravel"}],
"total":4471,"precincts":
{"total":14,"reporting":14},
"name":"Davie"},
"Greene":
{"votes":[
{"votes":2184,"name":"clinton"},
{"votes":1953,"name":"obama"},
{"votes":47,"name":"gravel"}],
"total":4184,"precincts":
{"total":10,"reporting":10},
"name":"Greene"},
"Pender":
{"votes":[
{"votes":4053,"name":"obama"},
{"votes":3685,"name":"clinton"},
{"votes":135,"name":"nopreference-d"},
{"votes":95,"name":"gravel"}],
"total":7968,"precincts":
{"total":20,"reporting":20},
"name":"Pender"},
"Forsyth":
{"votes":[
{"votes":41186,"name":"obama"},
{"votes":19266,"name":"clinton"},
{"votes":407,"name":"nopreference-d"},
{"votes":251,"name":"gravel"}],
"total":61110,"precincts":
{"total":101,"reporting":101},
"name":"Forsyth"},
"Clay":
{"votes":[
{"votes":1222,"name":"clinton"},
{"votes":420,"name":"obama"},
{"votes":18,"name":"nopreference-d"},
{"votes":17,"name":"gravel"}],
"total":1677,"precincts":
{"total":9,"reporting":9},
"name":"Clay"},
"Macon":
{"votes":[
{"votes":3533,"name":"clinton"},
{"votes":1617,"name":"obama"},
{"votes":96,"name":"nopreference-d"},
{"votes":61,"name":"gravel"}],
"total":5307,"precincts":
{"total":15,"reporting":15},
"name":"Macon"},
"Chowan":
{"votes":[
{"votes":1652,"name":"obama"},
{"votes":1472,"name":"clinton"},
{"votes":78,"name":"nopreference-d"},
{"votes":28,"name":"gravel"}],
"total":3230,"precincts":
{"total":6,"reporting":6},
"name":"Chowan"},
"Madison":
{"votes":[
{"votes":2326,"name":"clinton"},
{"votes":1242,"name":"obama"},
{"votes":72,"name":"nopreference-d"},
{"votes":54,"name":"gravel"}],
"total":3694,"precincts":
{"total":12,"reporting":12},
"name":"Madison"},
"Gaston":
{"votes":[
{"votes":11980,"name":"clinton"},
{"votes":9997,"name":"obama"},
{"votes":279,"name":"nopreference-d"},
{"votes":175,"name":"gravel"}],
"total":22431,"precincts":
{"total":46,"reporting":46},
"name":"Gaston"},
"Northampton":
{"votes":[
{"votes":3891,"name":"obama"},
{"votes":2116,"name":"clinton"},
{"votes":101,"name":"nopreference-d"},
{"votes":61,"name":"gravel"}],
"total":6169,"precincts":
{"total":18,"reporting":18},
"name":"Northampton"},
"Swain":
{"votes":[
{"votes":1718,"name":"clinton"},
{"votes":630,"name":"obama"},
{"votes":77,"name":"nopreference-d"},
{"votes":33,"name":"gravel"}],
"total":2458,"precincts":
{"total":5,"reporting":5},
"name":"Swain"},
"Hyde":
{"votes":[
{"votes":719,"name":"clinton"},
{"votes":676,"name":"obama"},
{"votes":61,"name":"nopreference-d"},
{"votes":31,"name":"gravel"}],
"total":1487,"precincts":
{"total":7,"reporting":7},
"name":"Hyde"},
"Stanly":
{"votes":[
{"votes":4732,"name":"clinton"},
{"votes":2747,"name":"obama"},
{"votes":178,"name":"nopreference-d"},
{"votes":112,"name":"gravel"}],
"total":7769,"precincts":
{"total":24,"reporting":24},
"name":"Stanly"},
"Graham":
{"votes":[
{"votes":956,"name":"clinton"},
{"votes":220,"name":"obama"},
{"votes":40,"name":"nopreference-d"},
{"votes":21,"name":"gravel"}],
"total":1237,"precincts":
{"total":4,"reporting":4},
"name":"Graham"},
"Lenoir":
{"votes":[
{"votes":6778,"name":"obama"},
{"votes":5101,"name":"clinton"},
{"votes":257,"name":"nopreference-d"},
{"votes":130,"name":"gravel"}],
"total":12266,"precincts":
{"total":22,"reporting":22},
"name":"Lenoir"},
"Hertford":
{"votes":[
{"votes":3944,"name":"obama"},
{"votes":1460,"name":"clinton"},
{"votes":103,"name":"nopreference-d"},
{"votes":40,"name":"gravel"}],
"total":5547,"precincts":
{"total":13,"reporting":13},
"name":"Hertford"},
"Scotland":
{"votes":[
{"votes":3849,"name":"obama"},
{"votes":2861,"name":"clinton"},
{"votes":181,"name":"nopreference-d"},
{"votes":73,"name":"gravel"}],
"total":6964,"precincts":
{"total":10,"reporting":10},
"name":"Scotland"},
"Richmond":
{"votes":[
{"votes":5037,"name":"clinton"},
{"votes":4262,"name":"obama"},
{"votes":437,"name":"nopreference-d"},
{"votes":224,"name":"gravel"}],
"total":9960,"precincts":
{"total":16,"reporting":16},
"name":"Richmond"},
"Davidson":
{"votes":[
{"votes":9602,"name":"clinton"},
{"votes":7077,"name":"obama"},
{"votes":231,"name":"nopreference-d"},
{"votes":151,"name":"gravel"}],
"total":17061,"precincts":
{"total":43,"reporting":43},
"name":"Davidson"},
"Columbus":
{"votes":[
{"votes":8074,"name":"clinton"},
{"votes":5341,"name":"obama"},
{"votes":292,"name":"nopreference-d"},
{"votes":218,"name":"gravel"}],
"total":13925,"precincts":
{"total":29,"reporting":29},
"name":"Columbus"},
"Mitchell":
{"votes":[
{"votes":778,"name":"clinton"},
{"votes":422,"name":"obama"},
{"votes":14,"name":"nopreference-d"},
{"votes":9,"name":"gravel"}],
"total":1223,"precincts":
{"total":9,"reporting":9},
"name":"Mitchell"},
"Bertie":
{"votes":[
{"votes":3554,"name":"obama"},
{"votes":1821,"name":"clinton"},
{"votes":91,"name":"nopreference-d"},
{"votes":49,"name":"gravel"}],
"total":5515,"precincts":
{"total":12,"reporting":12},
"name":"Bertie"},
"Alexander":
{"votes":[
{"votes":3356,"name":"clinton"},
{"votes":1090,"name":"obama"},
{"votes":95,"name":"nopreference-d"},
{"votes":55,"name":"gravel"}],
"total":4596,"precincts":
{"total":18,"reporting":18},
"name":"Alexander"},
"Lincoln":
{"votes":[
{"votes":6727,"name":"clinton"},
{"votes":2781,"name":"obama"},
{"votes":144,"name":"nopreference-d"},
{"votes":113,"name":"gravel"}],
"total":9765,"precincts":
{"total":28,"reporting":28},
"name":"Lincoln"},
"Sampson":
{"votes":[
{"votes":5047,"name":"obama"},
{"votes":3962,"name":"clinton"},
{"votes":87,"name":"nopreference-d"},
{"votes":43,"name":"gravel"}],
"total":9139,"precincts":
{"total":23,"reporting":23},
"name":"Sampson"},
"Edgecombe":
{"votes":[
{"votes":9294,"name":"obama"},
{"votes":4074,"name":"clinton"},
{"votes":173,"name":"nopreference-d"},
{"votes":110,"name":"gravel"}],
"total":13651,"precincts":
{"total":21,"reporting":21},
"name":"Edgecombe"},
"Ashe":
{"votes":[
{"votes":3475,"name":"clinton"},
{"votes":1008,"name":"obama"},
{"votes":82,"name":"nopreference-d"},
{"votes":51,"name":"gravel"}],
"total":4616,"precincts":
{"total":17,"reporting":17},
"name":"Ashe"},
"Craven":
{"votes":[
{"votes":6226,"name":"obama"},
{"votes":4798,"name":"clinton"},
{"votes":306,"name":"nopreference-d"},
{"votes":143,"name":"gravel"}],
"total":11473,"precincts":
{"total":27,"reporting":27},
"name":"Craven"},
"Iredell":
{"votes":[
{"votes":10065,"name":"clinton"},
{"votes":8344,"name":"obama"},
{"votes":342,"name":"nopreference-d"},
{"votes":218,"name":"gravel"}],
"total":18969,"precincts":
{"total":29,"reporting":29},
"name":"Iredell"},
"Franklin":
{"votes":[
{"votes":5735,"name":"obama"},
{"votes":5055,"name":"clinton"},
{"votes":172,"name":"nopreference-d"},
{"votes":120,"name":"gravel"}],
"total":11082,"precincts":
{"total":18,"reporting":18},
"name":"Franklin"},
"Carteret":
{"votes":[
{"votes":6120,"name":"clinton"},
{"votes":3758,"name":"obama"},
{"votes":251,"name":"nopreference-d"},
{"votes":133,"name":"gravel"}],
"total":10262,"precincts":
{"total":34,"reporting":34},
"name":"Carteret"},
"Johnston":
{"votes":[
{"votes":11638,"name":"clinton"},
{"votes":9449,"name":"obama"},
{"votes":464,"name":"nopreference-d"},
{"votes":235,"name":"gravel"}],
"total":21786,"precincts":
{"total":37,"reporting":37},
"name":"Johnston"},
"Nash":
{"votes":[
{"votes":11552,"name":"obama"},
{"votes":7684,"name":"clinton"},
{"votes":333,"name":"nopreference-d"},
{"votes":183,"name":"gravel"}],
"total":19752,"precincts":
{"total":26,"reporting":26},
"name":"Nash"},
"Tyrrell":
{"votes":[
{"votes":630,"name":"clinton"},
{"votes":437,"name":"obama"},
{"votes":63,"name":"nopreference-d"},
{"votes":29,"name":"gravel"}],
"total":1159,"precincts":
{"total":6,"reporting":6},
"name":"Tyrrell"},
"Caswell":
{"votes":[
{"votes":3134,"name":"obama"},
{"votes":1868,"name":"clinton"},
{"votes":142,"name":"nopreference-d"},
{"votes":84,"name":"gravel"}],
"total":5228,"precincts":
{"total":11,"reporting":11},
"name":"Caswell"},
"Cleveland":
{"votes":[
{"votes":8426,"name":"clinton"},
{"votes":7211,"name":"obama"},
{"votes":275,"name":"nopreference-d"},
{"votes":154,"name":"gravel"}],
"total":16066,"precincts":
{"total":28,"reporting":28},
"name":"Cleveland"},
"Halifax":
{"votes":[
{"votes":7880,"name":"obama"},
{"votes":4877,"name":"clinton"},
{"votes":191,"name":"nopreference-d"},
{"votes":149,"name":"gravel"}],
"total":13097,"precincts":
{"total":30,"reporting":30},
"name":"Halifax"},
"Cumberland":
{"votes":[
{"votes":33212,"name":"obama"},
{"votes":16125,"name":"clinton"},
{"votes":545,"name":"nopreference-d"},
{"votes":372,"name":"gravel"}],
"total":50254,"precincts":
{"total":69,"reporting":69},
"name":"Cumberland"},
"Rockingham":
{"votes":[
{"votes":7567,"name":"clinton"},
{"votes":6971,"name":"obama"},
{"votes":446,"name":"nopreference-d"},
{"votes":222,"name":"gravel"}],
"total":15206,"precincts":
{"total":20,"reporting":20},
"name":"Rockingham"},
"Rowan":
{"votes":[
{"votes":8143,"name":"obama"},
{"votes":7811,"name":"clinton"},
{"votes":298,"name":"nopreference-d"},
{"votes":177,"name":"gravel"}],
"total":16429,"precincts":
{"total":44,"reporting":44},
"name":"Rowan"},
"Alleghany":
{"votes":[
{"votes":1690,"name":"clinton"},
{"votes":473,"name":"obama"},
{"votes":57,"name":"nopreference-d"},
{"votes":34,"name":"gravel"}],
"total":2254,"precincts":
{"total":7,"reporting":7},
"name":"Alleghany"},
"McDowell":
{"votes":[
{"votes":4170,"name":"clinton"},
{"votes":1487,"name":"obama"},
{"votes":125,"name":"nopreference-d"},
{"votes":98,"name":"gravel"}],
"total":5880,"precincts":
{"total":17,"reporting":17},
"name":"McDowell"},
"Haywood":
{"votes":[
{"votes":8551,"name":"clinton"},
{"votes":3759,"name":"obama"},
{"votes":415,"name":"nopreference-d"},
{"votes":160,"name":"gravel"}],
"total":12885,"precincts":
{"total":29,"reporting":29},
"name":"Haywood"},
"Pamlico":
{"votes":[
{"votes":1330,"name":"obama"},
{"votes":1185,"name":"clinton"},
{"votes":82,"name":"nopreference-d"},
{"votes":51,"name":"gravel"}],
"total":2648,"precincts":
{"total":10,"reporting":10},
"name":"Pamlico"},
"Dare":
{"votes":[
{"votes":3190,"name":"clinton"},
{"votes":2617,"name":"obama"},
{"votes":173,"name":"nopreference-d"},
{"votes":83,"name":"gravel"}],
"total":6063,"precincts":
{"total":16,"reporting":16},
"name":"Dare"},
"Jones":
{"votes":[
{"votes":1422,"name":"obama"},
{"votes":1149,"name":"clinton"},
{"votes":63,"name":"nopreference-d"},
{"votes":31,"name":"gravel"}],
"total":2665,"precincts":
{"total":7,"reporting":7},
"name":"Jones"},
"Pitt":
{"votes":[
{"votes":16295,"name":"obama"},
{"votes":10214,"name":"clinton"},
{"votes":414,"name":"nopreference-d"},
{"votes":201,"name":"gravel"}],
"total":27124,"precincts":
{"total":38,"reporting":38},
"name":"Pitt"},
"Martin":
{"votes":[
{"votes":3707,"name":"obama"},
{"votes":2938,"name":"clinton"},
{"votes":171,"name":"nopreference-d"},
{"votes":86,"name":"gravel"}],
"total":6902,"precincts":
{"total":13,"reporting":13},
"name":"Martin"},
"Mecklenburg":
{"votes":[
{"votes":101390,"name":"obama"},
{"votes":42256,"name":"clinton"},
{"votes":679,"name":"nopreference-d"},
{"votes":350,"name":"gravel"}],
"total":144675,"precincts":
{"total":198,"reporting":192},
"name":"Mecklenburg"},
"Gates":
{"votes":[
{"votes":1329,"name":"obama"},
{"votes":1209,"name":"clinton"},
{"votes":96,"name":"nopreference-d"},
{"votes":38,"name":"gravel"}],
"total":2672,"precincts":
{"total":6,"reporting":6},
"name":"Gates"},
"Person":
{"votes":[
{"votes":4060,"name":"clinton"},
{"votes":4048,"name":"obama"},
{"votes":235,"name":"nopreference-d"},
{"votes":85,"name":"gravel"}],
"total":8428,"precincts":
{"total":14,"reporting":14},
"name":"Person"},
"Yancey":
{"votes":[
{"votes":2597,"name":"clinton"},
{"votes":1025,"name":"obama"},
{"votes":94,"name":"nopreference-d"},
{"votes":48,"name":"gravel"}],
"total":3764,"precincts":
{"total":11,"reporting":11},
"name":"Yancey"},
"Surry":
{"votes":[
{"votes":7129,"name":"clinton"},
{"votes":2604,"name":"obama"},
{"votes":133,"name":"nopreference-d"},
{"votes":101,"name":"gravel"}],
"total":9967,"precincts":
{"total":32,"reporting":32},
"name":"Surry"},
"Perquimans":
{"votes":[
{"votes":1341,"name":"clinton"},
{"votes":1242,"name":"obama"},
{"votes":108,"name":"nopreference-d"},
{"votes":35,"name":"gravel"}],
"total":2726,"precincts":
{"total":7,"reporting":7},
"name":"Perquimans"},
"Randolph":
{"votes":[
{"votes":6216,"name":"clinton"},
{"votes":3426,"name":"obama"},
{"votes":177,"name":"nopreference-d"},
{"votes":145,"name":"gravel"}],
"total":9964,"precincts":
{"total":42,"reporting":42},
"name":"Randolph"}}})