GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":105862,"name":"obama","delegates":50},
{"votes":56099,"name":"clinton","delegates":42},
{"votes":1555,"name":"nopreference-d"},
{"votes":764,"name":"gravel"}],
"name":"North Carolina","precincts":
{"total":2817,"reporting":122},
"delegates":115,"date":"05-06"},
"state":"NC","party":"dem","total":164280,"locals":
{"Bladen":
{"votes":[
{"votes":1364,"name":"clinton"},
{"votes":1227,"name":"obama"},
{"votes":109,"name":"nopreference-d"},
{"votes":56,"name":"gravel"}],
"total":2756,"precincts":
{"total":17,"reporting":1},
"name":"Bladen"},
"Currituck":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Currituck"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":49,"reporting":0},
"name":"Union"},
"Wilson":
{"votes":[],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Wilson"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Wayne"},
"Robeson":
{"votes":[],
"total":0,"precincts":
{"total":41,"reporting":0},
"name":"Robeson"},
"Brunswick":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Brunswick"},
"Henderson":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Henderson"},
"Cherokee":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Cherokee"},
"Anson":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Anson"},
"Catawba":
{"votes":[],
"total":0,"precincts":
{"total":41,"reporting":0},
"name":"Catawba"},
"Yadkin":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Yadkin"},
"Stokes":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Stokes"},
"Pasquotank":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pasquotank"},
"Hoke":
{"votes":[
{"votes":1312,"name":"obama"},
{"votes":551,"name":"clinton"},
{"votes":38,"name":"nopreference-d"},
{"votes":21,"name":"gravel"}],
"total":1922,"precincts":
{"total":13,"reporting":1},
"name":"Hoke"},
"Wilkes":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Wilkes"},
"Alamance":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Alamance"},
"Moore":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Moore"},
"Washington":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Washington"},
"Duplin":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Duplin"},
"Cabarrus":
{"votes":[],
"total":0,"precincts":
{"total":49,"reporting":0},
"name":"Cabarrus"},
"Camden":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Camden"},
"New Hanover":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"New Hanover"},
"Polk":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Polk"},
"Warren":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Warren"},
"Watauga":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Watauga"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Jackson"},
"Transylvania":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Transylvania"},
"Caldwell":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Caldwell"},
"Onslow":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Onslow"},
"Granville":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":12790,"name":"obama"},
{"votes":3678,"name":"clinton"},
{"votes":111,"name":"nopreference-d"},
{"votes":71,"name":"gravel"}],
"total":16650,"precincts":
{"total":44,"reporting":1},
"name":"Orange"},
"Burke":
{"votes":[],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Burke"},
"Lee":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Lee"},
"Avery":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Avery"},
"Buncombe":
{"votes":[],
"total":0,"precincts":
{"total":78,"reporting":0},
"name":"Buncombe"},
"Guilford":
{"votes":[
{"votes":18212,"name":"obama"},
{"votes":7149,"name":"clinton"},
{"votes":307,"name":"nopreference-d"},
{"votes":133,"name":"gravel"}],
"total":25801,"precincts":
{"total":163,"reporting":0},
"name":"Guilford"},
"Durham":
{"votes":[],
"total":0,"precincts":
{"total":61,"reporting":0},
"name":"Durham"},
"Wake":
{"votes":[
{"votes":37069,"name":"obama"},
{"votes":26392,"name":"clinton"},
{"votes":559,"name":"nopreference-d"},
{"votes":284,"name":"gravel"}],
"total":64304,"precincts":
{"total":210,"reporting":109},
"name":"Wake"},
"Chatham":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Chatham"},
"Beaufort":
{"votes":[
{"votes":1062,"name":"obama"},
{"votes":720,"name":"clinton"},
{"votes":42,"name":"nopreference-d"},
{"votes":35,"name":"gravel"}],
"total":1859,"precincts":
{"total":23,"reporting":1},
"name":"Beaufort"},
"Vance":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Vance"},
"Rutherford":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Rutherford"},
"Harnett":
{"votes":[
{"votes":1512,"name":"clinton"},
{"votes":1379,"name":"obama"},
{"votes":57,"name":"nopreference-d"},
{"votes":21,"name":"gravel"}],
"total":2969,"precincts":
{"total":18,"reporting":0},
"name":"Harnett"},
"Davie":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Davie"},
"Greene":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Greene"},
"Pender":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Pender"},
"Forsyth":
{"votes":[],
"total":0,"precincts":
{"total":101,"reporting":0},
"name":"Forsyth"},
"Clay":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Clay"},
"Macon":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Macon"},
"Chowan":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Chowan"},
"Madison":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Madison"},
"Gaston":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Gaston"},
"Northampton":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Northampton"},
"Swain":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Swain"},
"Hyde":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Hyde"},
"Stanly":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Stanly"},
"Graham":
{"votes":[
{"votes":286,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":10,"name":"nopreference-d"},
{"votes":3,"name":"gravel"}],
"total":341,"precincts":
{"total":4,"reporting":0},
"name":"Graham"},
"Lenoir":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Lenoir"},
"Hertford":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Hertford"},
"Scotland":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Scotland"},
"Richmond":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Richmond"},
"Davidson":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Davidson"},
"Columbus":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Columbus"},
"Mitchell":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Mitchell"},
"Bertie":
{"votes":[
{"votes":1014,"name":"obama"},
{"votes":368,"name":"clinton"},
{"votes":27,"name":"nopreference-d"},
{"votes":11,"name":"gravel"}],
"total":1420,"precincts":
{"total":12,"reporting":1},
"name":"Bertie"},
"Alexander":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Alexander"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Lincoln"},
"Sampson":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Sampson"},
"Edgecombe":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Edgecombe"},
"Ashe":
{"votes":[
{"votes":738,"name":"clinton"},
{"votes":275,"name":"obama"},
{"votes":18,"name":"nopreference-d"},
{"votes":5,"name":"gravel"}],
"total":1036,"precincts":
{"total":17,"reporting":3},
"name":"Ashe"},
"Craven":
{"votes":[],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Craven"},
"Iredell":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Iredell"},
"Franklin":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Franklin"},
"Carteret":
{"votes":[],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Carteret"},
"Johnston":
{"votes":[
{"votes":229,"name":"obama"},
{"votes":224,"name":"clinton"},
{"votes":6,"name":"nopreference-d"},
{"votes":6,"name":"gravel"}],
"total":465,"precincts":
{"total":37,"reporting":1},
"name":"Johnston"},
"Nash":
{"votes":[],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Nash"},
"Tyrrell":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Tyrrell"},
"Caswell":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Caswell"},
"Cleveland":
{"votes":[
{"votes":1913,"name":"obama"},
{"votes":1306,"name":"clinton"},
{"votes":42,"name":"nopreference-d"},
{"votes":11,"name":"gravel"}],
"total":3272,"precincts":
{"total":28,"reporting":1},
"name":"Cleveland"},
"Halifax":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Halifax"},
"Cumberland":
{"votes":[],
"total":0,"precincts":
{"total":69,"reporting":0},
"name":"Cumberland"},
"Rockingham":
{"votes":[],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Rockingham"},
"Rowan":
{"votes":[],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Rowan"},
"Alleghany":
{"votes":[
{"votes":640,"name":"clinton"},
{"votes":208,"name":"obama"},
{"votes":25,"name":"nopreference-d"},
{"votes":6,"name":"gravel"}],
"total":879,"precincts":
{"total":7,"reporting":0},
"name":"Alleghany"},
"McDowell":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"McDowell"},
"Haywood":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Haywood"},
"Pamlico":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Pamlico"},
"Dare":
{"votes":[
{"votes":683,"name":"clinton"},
{"votes":662,"name":"obama"},
{"votes":36,"name":"nopreference-d"},
{"votes":13,"name":"gravel"}],
"total":1394,"precincts":
{"total":16,"reporting":1},
"name":"Dare"},
"Jones":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Jones"},
"Pitt":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Pitt"},
"Martin":
{"votes":[
{"votes":959,"name":"obama"},
{"votes":458,"name":"clinton"},
{"votes":38,"name":"nopreference-d"},
{"votes":13,"name":"gravel"}],
"total":1468,"precincts":
{"total":13,"reporting":1},
"name":"Martin"},
"Mecklenburg":
{"votes":[
{"votes":27509,"name":"obama"},
{"votes":10030,"name":"clinton"},
{"votes":130,"name":"nopreference-d"},
{"votes":75,"name":"gravel"}],
"total":37744,"precincts":
{"total":198,"reporting":1},
"name":"Mecklenburg"},
"Gates":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Gates"},
"Person":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Person"},
"Yancey":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Yancey"},
"Surry":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Surry"},
"Perquimans":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Perquimans"},
"Randolph":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Randolph"}}})