GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":381139,"name":"mccain"},
{"votes":62918,"name":"huckabee"},
{"votes":40275,"name":"paul"},
{"votes":20307,"name":"nopreference-r"},
{"votes":13589,"name":"keyes"}],
"name":"North Carolina","precincts":
{"total":2817,"reporting":2807},
"delegates":69,"date":"05-06"},
"state":"NC","party":"gop","total":518228,"locals":
{"Bladen":
{"votes":[
{"votes":450,"name":"mccain"},
{"votes":83,"name":"huckabee"},
{"votes":53,"name":"paul"},
{"votes":26,"name":"nopreference-r"},
{"votes":14,"name":"keyes"}],
"total":626,"precincts":
{"total":17,"reporting":17},
"name":"Bladen"},
"Currituck":
{"votes":[
{"votes":1092,"name":"mccain"},
{"votes":174,"name":"huckabee"},
{"votes":71,"name":"paul"},
{"votes":58,"name":"nopreference-r"},
{"votes":24,"name":"keyes"}],
"total":1419,"precincts":
{"total":11,"reporting":11},
"name":"Currituck"},
"Union":
{"votes":[
{"votes":10311,"name":"mccain"},
{"votes":1910,"name":"huckabee"},
{"votes":1324,"name":"paul"},
{"votes":790,"name":"keyes"},
{"votes":619,"name":"nopreference-r"}],
"total":14954,"precincts":
{"total":49,"reporting":49},
"name":"Union"},
"Wilson":
{"votes":[
{"votes":2601,"name":"mccain"},
{"votes":357,"name":"huckabee"},
{"votes":139,"name":"paul"},
{"votes":130,"name":"nopreference-r"},
{"votes":41,"name":"keyes"}],
"total":3268,"precincts":
{"total":25,"reporting":25},
"name":"Wilson"},
"Montgomery":
{"votes":[
{"votes":1377,"name":"mccain"},
{"votes":323,"name":"huckabee"},
{"votes":69,"name":"paul"},
{"votes":56,"name":"nopreference-r"},
{"votes":27,"name":"keyes"}],
"total":1852,"precincts":
{"total":14,"reporting":14},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":4621,"name":"mccain"},
{"votes":576,"name":"huckabee"},
{"votes":207,"name":"paul"},
{"votes":197,"name":"nopreference-r"},
{"votes":80,"name":"keyes"}],
"total":5681,"precincts":
{"total":30,"reporting":30},
"name":"Wayne"},
"Robeson":
{"votes":[
{"votes":1064,"name":"mccain"},
{"votes":180,"name":"huckabee"},
{"votes":94,"name":"nopreference-r"},
{"votes":74,"name":"paul"},
{"votes":19,"name":"keyes"}],
"total":1431,"precincts":
{"total":41,"reporting":41},
"name":"Robeson"},
"Brunswick":
{"votes":[
{"votes":5129,"name":"mccain"},
{"votes":688,"name":"huckabee"},
{"votes":420,"name":"paul"},
{"votes":227,"name":"nopreference-r"},
{"votes":81,"name":"keyes"}],
"total":6545,"precincts":
{"total":23,"reporting":23},
"name":"Brunswick"},
"Henderson":
{"votes":[
{"votes":8358,"name":"mccain"},
{"votes":1466,"name":"huckabee"},
{"votes":833,"name":"paul"},
{"votes":469,"name":"nopreference-r"},
{"votes":251,"name":"keyes"}],
"total":11377,"precincts":
{"total":35,"reporting":35},
"name":"Henderson"},
"Cherokee":
{"votes":[
{"votes":1076,"name":"mccain"},
{"votes":255,"name":"huckabee"},
{"votes":81,"name":"paul"},
{"votes":49,"name":"nopreference-r"},
{"votes":33,"name":"keyes"}],
"total":1494,"precincts":
{"total":16,"reporting":16},
"name":"Cherokee"},
"Anson":
{"votes":[
{"votes":276,"name":"mccain"},
{"votes":61,"name":"huckabee"},
{"votes":29,"name":"paul"},
{"votes":16,"name":"keyes"},
{"votes":15,"name":"nopreference-r"}],
"total":397,"precincts":
{"total":11,"reporting":11},
"name":"Anson"},
"Catawba":
{"votes":[
{"votes":10377,"name":"mccain"},
{"votes":1843,"name":"huckabee"},
{"votes":773,"name":"paul"},
{"votes":522,"name":"nopreference-r"},
{"votes":287,"name":"keyes"}],
"total":13802,"precincts":
{"total":41,"reporting":41},
"name":"Catawba"},
"Yadkin":
{"votes":[
{"votes":4234,"name":"mccain"},
{"votes":680,"name":"huckabee"},
{"votes":253,"name":"paul"},
{"votes":220,"name":"nopreference-r"},
{"votes":72,"name":"keyes"}],
"total":5459,"precincts":
{"total":12,"reporting":12},
"name":"Yadkin"},
"Stokes":
{"votes":[
{"votes":2649,"name":"mccain"},
{"votes":515,"name":"huckabee"},
{"votes":188,"name":"paul"},
{"votes":136,"name":"nopreference-r"},
{"votes":85,"name":"keyes"}],
"total":3573,"precincts":
{"total":23,"reporting":23},
"name":"Stokes"},
"Pasquotank":
{"votes":[
{"votes":703,"name":"mccain"},
{"votes":138,"name":"huckabee"},
{"votes":59,"name":"nopreference-r"},
{"votes":47,"name":"paul"},
{"votes":16,"name":"keyes"}],
"total":963,"precincts":
{"total":13,"reporting":13},
"name":"Pasquotank"},
"Hoke":
{"votes":[
{"votes":551,"name":"mccain"},
{"votes":63,"name":"huckabee"},
{"votes":39,"name":"nopreference-r"},
{"votes":32,"name":"paul"},
{"votes":17,"name":"keyes"}],
"total":702,"precincts":
{"total":13,"reporting":13},
"name":"Hoke"},
"Wilkes":
{"votes":[
{"votes":5765,"name":"mccain"},
{"votes":1138,"name":"huckabee"},
{"votes":337,"name":"paul"},
{"votes":332,"name":"nopreference-r"},
{"votes":81,"name":"keyes"}],
"total":7653,"precincts":
{"total":28,"reporting":28},
"name":"Wilkes"},
"Alamance":
{"votes":[
{"votes":5697,"name":"mccain"},
{"votes":976,"name":"huckabee"},
{"votes":631,"name":"paul"},
{"votes":260,"name":"nopreference-r"},
{"votes":145,"name":"keyes"}],
"total":7709,"precincts":
{"total":37,"reporting":37},
"name":"Alamance"},
"Moore":
{"votes":[
{"votes":8864,"name":"mccain"},
{"votes":1043,"name":"huckabee"},
{"votes":549,"name":"paul"},
{"votes":369,"name":"nopreference-r"},
{"votes":108,"name":"keyes"}],
"total":10933,"precincts":
{"total":24,"reporting":24},
"name":"Moore"},
"Washington":
{"votes":[
{"votes":210,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":9,"name":"keyes"},
{"votes":9,"name":"nopreference-r"},
{"votes":7,"name":"paul"}],
"total":266,"precincts":
{"total":6,"reporting":6},
"name":"Washington"},
"Duplin":
{"votes":[
{"votes":1119,"name":"mccain"},
{"votes":155,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":52,"name":"nopreference-r"},
{"votes":25,"name":"keyes"}],
"total":1419,"precincts":
{"total":20,"reporting":18},
"name":"Duplin"},
"Cabarrus":
{"votes":[
{"votes":6757,"name":"mccain"},
{"votes":1227,"name":"huckabee"},
{"votes":925,"name":"paul"},
{"votes":442,"name":"keyes"},
{"votes":403,"name":"nopreference-r"}],
"total":9754,"precincts":
{"total":49,"reporting":49},
"name":"Cabarrus"},
"Camden":
{"votes":[
{"votes":275,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":15,"name":"nopreference-r"},
{"votes":9,"name":"keyes"}],
"total":361,"precincts":
{"total":3,"reporting":3},
"name":"Camden"},
"New Hanover":
{"votes":[
{"votes":9299,"name":"mccain"},
{"votes":1315,"name":"huckabee"},
{"votes":1231,"name":"paul"},
{"votes":420,"name":"nopreference-r"},
{"votes":213,"name":"keyes"}],
"total":12478,"precincts":
{"total":43,"reporting":43},
"name":"New Hanover"},
"Polk":
{"votes":[
{"votes":1255,"name":"mccain"},
{"votes":181,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":63,"name":"nopreference-r"},
{"votes":46,"name":"keyes"}],
"total":1675,"precincts":
{"total":7,"reporting":7},
"name":"Polk"},
"Warren":
{"votes":[
{"votes":301,"name":"mccain"},
{"votes":50,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":12,"name":"keyes"},
{"votes":10,"name":"nopreference-r"}],
"total":387,"precincts":
{"total":14,"reporting":14},
"name":"Warren"},
"Watauga":
{"votes":[
{"votes":2206,"name":"mccain"},
{"votes":421,"name":"huckabee"},
{"votes":367,"name":"paul"},
{"votes":90,"name":"nopreference-r"},
{"votes":66,"name":"keyes"}],
"total":3150,"precincts":
{"total":20,"reporting":20},
"name":"Watauga"},
"Jackson":
{"votes":[
{"votes":903,"name":"mccain"},
{"votes":184,"name":"huckabee"},
{"votes":117,"name":"paul"},
{"votes":50,"name":"nopreference-r"},
{"votes":25,"name":"keyes"}],
"total":1279,"precincts":
{"total":18,"reporting":18},
"name":"Jackson"},
"Transylvania":
{"votes":[
{"votes":2098,"name":"mccain"},
{"votes":427,"name":"huckabee"},
{"votes":242,"name":"paul"},
{"votes":83,"name":"nopreference-r"},
{"votes":63,"name":"keyes"}],
"total":2913,"precincts":
{"total":18,"reporting":18},
"name":"Transylvania"},
"Caldwell":
{"votes":[
{"votes":4848,"name":"mccain"},
{"votes":972,"name":"huckabee"},
{"votes":326,"name":"paul"},
{"votes":306,"name":"nopreference-r"},
{"votes":99,"name":"keyes"}],
"total":6551,"precincts":
{"total":24,"reporting":24},
"name":"Caldwell"},
"Onslow":
{"votes":[
{"votes":4872,"name":"mccain"},
{"votes":547,"name":"huckabee"},
{"votes":358,"name":"paul"},
{"votes":231,"name":"nopreference-r"},
{"votes":194,"name":"keyes"}],
"total":6202,"precincts":
{"total":27,"reporting":27},
"name":"Onslow"},
"Granville":
{"votes":[
{"votes":1220,"name":"mccain"},
{"votes":219,"name":"huckabee"},
{"votes":150,"name":"paul"},
{"votes":80,"name":"nopreference-r"},
{"votes":54,"name":"keyes"}],
"total":1723,"precincts":
{"total":15,"reporting":15},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":3950,"name":"mccain"},
{"votes":725,"name":"paul"},
{"votes":554,"name":"huckabee"},
{"votes":271,"name":"nopreference-r"},
{"votes":122,"name":"keyes"}],
"total":5622,"precincts":
{"total":44,"reporting":44},
"name":"Orange"},
"Burke":
{"votes":[
{"votes":3360,"name":"mccain"},
{"votes":771,"name":"huckabee"},
{"votes":219,"name":"paul"},
{"votes":185,"name":"nopreference-r"},
{"votes":103,"name":"keyes"}],
"total":4638,"precincts":
{"total":31,"reporting":31},
"name":"Burke"},
"Lee":
{"votes":[
{"votes":2500,"name":"mccain"},
{"votes":356,"name":"huckabee"},
{"votes":198,"name":"paul"},
{"votes":128,"name":"nopreference-r"},
{"votes":63,"name":"keyes"}],
"total":3245,"precincts":
{"total":9,"reporting":9},
"name":"Lee"},
"Avery":
{"votes":[
{"votes":2405,"name":"mccain"},
{"votes":505,"name":"huckabee"},
{"votes":200,"name":"paul"},
{"votes":182,"name":"nopreference-r"},
{"votes":36,"name":"keyes"}],
"total":3328,"precincts":
{"total":20,"reporting":20},
"name":"Avery"},
"Buncombe":
{"votes":[
{"votes":7159,"name":"mccain"},
{"votes":1623,"name":"huckabee"},
{"votes":1558,"name":"paul"},
{"votes":482,"name":"nopreference-r"},
{"votes":348,"name":"keyes"}],
"total":11170,"precincts":
{"total":78,"reporting":78},
"name":"Buncombe"},
"Guilford":
{"votes":[
{"votes":25392,"name":"mccain"},
{"votes":4183,"name":"huckabee"},
{"votes":1852,"name":"paul"},
{"votes":1269,"name":"nopreference-r"},
{"votes":904,"name":"keyes"}],
"total":33600,"precincts":
{"total":163,"reporting":163},
"name":"Guilford"},
"Durham":
{"votes":[
{"votes":5133,"name":"mccain"},
{"votes":737,"name":"huckabee"},
{"votes":690,"name":"paul"},
{"votes":341,"name":"nopreference-r"},
{"votes":228,"name":"keyes"}],
"total":7129,"precincts":
{"total":61,"reporting":61},
"name":"Durham"},
"Wake":
{"votes":[
{"votes":34676,"name":"mccain"},
{"votes":5648,"name":"huckabee"},
{"votes":5477,"name":"paul"},
{"votes":1793,"name":"nopreference-r"},
{"votes":1643,"name":"keyes"}],
"total":49237,"precincts":
{"total":210,"reporting":210},
"name":"Wake"},
"Chatham":
{"votes":[
{"votes":2328,"name":"mccain"},
{"votes":322,"name":"huckabee"},
{"votes":263,"name":"paul"},
{"votes":116,"name":"nopreference-r"},
{"votes":75,"name":"keyes"}],
"total":3104,"precincts":
{"total":19,"reporting":19},
"name":"Chatham"},
"Beaufort":
{"votes":[
{"votes":2047,"name":"mccain"},
{"votes":312,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":71,"name":"nopreference-r"},
{"votes":52,"name":"keyes"}],
"total":2612,"precincts":
{"total":23,"reporting":21},
"name":"Beaufort"},
"Vance":
{"votes":[
{"votes":742,"name":"mccain"},
{"votes":91,"name":"huckabee"},
{"votes":55,"name":"nopreference-r"},
{"votes":43,"name":"paul"},
{"votes":23,"name":"keyes"}],
"total":954,"precincts":
{"total":16,"reporting":16},
"name":"Vance"},
"Rutherford":
{"votes":[
{"votes":1992,"name":"mccain"},
{"votes":544,"name":"huckabee"},
{"votes":201,"name":"paul"},
{"votes":92,"name":"keyes"},
{"votes":87,"name":"nopreference-r"}],
"total":2916,"precincts":
{"total":20,"reporting":20},
"name":"Rutherford"},
"Harnett":
{"votes":[
{"votes":3435,"name":"mccain"},
{"votes":550,"name":"huckabee"},
{"votes":297,"name":"paul"},
{"votes":166,"name":"nopreference-r"},
{"votes":89,"name":"keyes"}],
"total":4537,"precincts":
{"total":18,"reporting":18},
"name":"Harnett"},
"Davie":
{"votes":[
{"votes":4876,"name":"mccain"},
{"votes":708,"name":"huckabee"},
{"votes":247,"name":"paul"},
{"votes":236,"name":"nopreference-r"},
{"votes":91,"name":"keyes"}],
"total":6158,"precincts":
{"total":14,"reporting":14},
"name":"Davie"},
"Greene":
{"votes":[
{"votes":295,"name":"mccain"},
{"votes":52,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":14,"name":"nopreference-r"},
{"votes":13,"name":"keyes"}],
"total":398,"precincts":
{"total":10,"reporting":10},
"name":"Greene"},
"Pender":
{"votes":[
{"votes":2063,"name":"mccain"},
{"votes":323,"name":"huckabee"},
{"votes":265,"name":"paul"},
{"votes":93,"name":"nopreference-r"},
{"votes":43,"name":"keyes"}],
"total":2787,"precincts":
{"total":20,"reporting":20},
"name":"Pender"},
"Forsyth":
{"votes":[
{"votes":14061,"name":"mccain"},
{"votes":2343,"name":"huckabee"},
{"votes":1094,"name":"paul"},
{"votes":793,"name":"nopreference-r"},
{"votes":537,"name":"keyes"}],
"total":18828,"precincts":
{"total":101,"reporting":101},
"name":"Forsyth"},
"Clay":
{"votes":[
{"votes":697,"name":"mccain"},
{"votes":110,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":12,"name":"nopreference-r"},
{"votes":4,"name":"keyes"}],
"total":868,"precincts":
{"total":9,"reporting":9},
"name":"Clay"},
"Macon":
{"votes":[
{"votes":1943,"name":"mccain"},
{"votes":399,"name":"huckabee"},
{"votes":234,"name":"paul"},
{"votes":87,"name":"nopreference-r"},
{"votes":40,"name":"keyes"}],
"total":2703,"precincts":
{"total":15,"reporting":15},
"name":"Macon"},
"Chowan":
{"votes":[
{"votes":801,"name":"mccain"},
{"votes":89,"name":"huckabee"},
{"votes":35,"name":"nopreference-r"},
{"votes":33,"name":"paul"},
{"votes":17,"name":"keyes"}],
"total":975,"precincts":
{"total":6,"reporting":6},
"name":"Chowan"},
"Madison":
{"votes":[
{"votes":570,"name":"mccain"},
{"votes":179,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":69,"name":"nopreference-r"},
{"votes":45,"name":"keyes"}],
"total":993,"precincts":
{"total":12,"reporting":12},
"name":"Madison"},
"Gaston":
{"votes":[
{"votes":6378,"name":"mccain"},
{"votes":1176,"name":"huckabee"},
{"votes":833,"name":"paul"},
{"votes":446,"name":"keyes"},
{"votes":387,"name":"nopreference-r"}],
"total":9220,"precincts":
{"total":46,"reporting":46},
"name":"Gaston"},
"Northampton":
{"votes":[
{"votes":257,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":6,"name":"nopreference-r"},
{"votes":2,"name":"keyes"}],
"total":320,"precincts":
{"total":18,"reporting":18},
"name":"Northampton"},
"Swain":
{"votes":[
{"votes":377,"name":"mccain"},
{"votes":90,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":13,"name":"nopreference-r"},
{"votes":9,"name":"keyes"}],
"total":526,"precincts":
{"total":5,"reporting":5},
"name":"Swain"},
"Hyde":
{"votes":[
{"votes":100,"name":"mccain"},
{"votes":11,"name":"huckabee"},
{"votes":10,"name":"paul"},
{"votes":9,"name":"nopreference-r"},
{"votes":3,"name":"keyes"}],
"total":133,"precincts":
{"total":7,"reporting":7},
"name":"Hyde"},
"Stanly":
{"votes":[
{"votes":3839,"name":"mccain"},
{"votes":652,"name":"huckabee"},
{"votes":231,"name":"paul"},
{"votes":199,"name":"nopreference-r"},
{"votes":123,"name":"keyes"}],
"total":5044,"precincts":
{"total":24,"reporting":24},
"name":"Stanly"},
"Graham":
{"votes":[
{"votes":741,"name":"mccain"},
{"votes":187,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":21,"name":"nopreference-r"},
{"votes":14,"name":"keyes"}],
"total":988,"precincts":
{"total":4,"reporting":4},
"name":"Graham"},
"Lenoir":
{"votes":[
{"votes":1753,"name":"mccain"},
{"votes":224,"name":"huckabee"},
{"votes":81,"name":"paul"},
{"votes":78,"name":"nopreference-r"},
{"votes":32,"name":"keyes"}],
"total":2168,"precincts":
{"total":22,"reporting":22},
"name":"Lenoir"},
"Hertford":
{"votes":[
{"votes":244,"name":"mccain"},
{"votes":35,"name":"huckabee"},
{"votes":19,"name":"nopreference-r"},
{"votes":11,"name":"paul"},
{"votes":6,"name":"keyes"}],
"total":315,"precincts":
{"total":13,"reporting":13},
"name":"Hertford"},
"Scotland":
{"votes":[
{"votes":544,"name":"mccain"},
{"votes":65,"name":"huckabee"},
{"votes":57,"name":"paul"},
{"votes":27,"name":"nopreference-r"},
{"votes":10,"name":"keyes"}],
"total":703,"precincts":
{"total":10,"reporting":10},
"name":"Scotland"},
"Richmond":
{"votes":[
{"votes":939,"name":"mccain"},
{"votes":124,"name":"huckabee"},
{"votes":92,"name":"paul"},
{"votes":50,"name":"nopreference-r"},
{"votes":18,"name":"keyes"}],
"total":1223,"precincts":
{"total":16,"reporting":16},
"name":"Richmond"},
"Davidson":
{"votes":[
{"votes":7773,"name":"mccain"},
{"votes":1601,"name":"huckabee"},
{"votes":531,"name":"paul"},
{"votes":400,"name":"nopreference-r"},
{"votes":170,"name":"keyes"}],
"total":10475,"precincts":
{"total":43,"reporting":43},
"name":"Davidson"},
"Columbus":
{"votes":[
{"votes":932,"name":"mccain"},
{"votes":114,"name":"huckabee"},
{"votes":65,"name":"paul"},
{"votes":61,"name":"nopreference-r"},
{"votes":21,"name":"keyes"}],
"total":1193,"precincts":
{"total":29,"reporting":29},
"name":"Columbus"},
"Mitchell":
{"votes":[
{"votes":1832,"name":"mccain"},
{"votes":442,"name":"huckabee"},
{"votes":279,"name":"paul"},
{"votes":198,"name":"nopreference-r"},
{"votes":29,"name":"keyes"}],
"total":2780,"precincts":
{"total":9,"reporting":9},
"name":"Mitchell"},
"Bertie":
{"votes":[
{"votes":196,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":11,"name":"nopreference-r"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"keyes"}],
"total":232,"precincts":
{"total":12,"reporting":12},
"name":"Bertie"},
"Alexander":
{"votes":[
{"votes":2157,"name":"mccain"},
{"votes":446,"name":"huckabee"},
{"votes":130,"name":"paul"},
{"votes":95,"name":"nopreference-r"},
{"votes":45,"name":"keyes"}],
"total":2873,"precincts":
{"total":18,"reporting":18},
"name":"Alexander"},
"Lincoln":
{"votes":[
{"votes":5434,"name":"mccain"},
{"votes":976,"name":"huckabee"},
{"votes":538,"name":"paul"},
{"votes":317,"name":"nopreference-r"},
{"votes":202,"name":"keyes"}],
"total":7467,"precincts":
{"total":28,"reporting":28},
"name":"Lincoln"},
"Sampson":
{"votes":[
{"votes":2883,"name":"mccain"},
{"votes":329,"name":"huckabee"},
{"votes":111,"name":"paul"},
{"votes":102,"name":"nopreference-r"},
{"votes":30,"name":"keyes"}],
"total":3455,"precincts":
{"total":23,"reporting":23},
"name":"Sampson"},
"Edgecombe":
{"votes":[
{"votes":919,"name":"mccain"},
{"votes":125,"name":"huckabee"},
{"votes":71,"name":"nopreference-r"},
{"votes":39,"name":"paul"},
{"votes":14,"name":"keyes"}],
"total":1168,"precincts":
{"total":21,"reporting":21},
"name":"Edgecombe"},
"Ashe":
{"votes":[
{"votes":2042,"name":"mccain"},
{"votes":378,"name":"huckabee"},
{"votes":145,"name":"paul"},
{"votes":116,"name":"nopreference-r"},
{"votes":29,"name":"keyes"}],
"total":2710,"precincts":
{"total":17,"reporting":17},
"name":"Ashe"},
"Craven":
{"votes":[
{"votes":3716,"name":"mccain"},
{"votes":477,"name":"huckabee"},
{"votes":255,"name":"paul"},
{"votes":202,"name":"nopreference-r"},
{"votes":88,"name":"keyes"}],
"total":4738,"precincts":
{"total":27,"reporting":27},
"name":"Craven"},
"Iredell":
{"votes":[
{"votes":9339,"name":"mccain"},
{"votes":1421,"name":"huckabee"},
{"votes":623,"name":"paul"},
{"votes":549,"name":"nopreference-r"},
{"votes":346,"name":"keyes"}],
"total":12278,"precincts":
{"total":29,"reporting":29},
"name":"Iredell"},
"Franklin":
{"votes":[
{"votes":2201,"name":"mccain"},
{"votes":399,"name":"huckabee"},
{"votes":330,"name":"paul"},
{"votes":124,"name":"nopreference-r"},
{"votes":74,"name":"keyes"}],
"total":3128,"precincts":
{"total":18,"reporting":18},
"name":"Franklin"},
"Carteret":
{"votes":[
{"votes":4927,"name":"mccain"},
{"votes":590,"name":"huckabee"},
{"votes":249,"name":"paul"},
{"votes":197,"name":"nopreference-r"},
{"votes":151,"name":"keyes"}],
"total":6114,"precincts":
{"total":34,"reporting":34},
"name":"Carteret"},
"Johnston":
{"votes":[
{"votes":8288,"name":"mccain"},
{"votes":1278,"name":"huckabee"},
{"votes":767,"name":"paul"},
{"votes":420,"name":"nopreference-r"},
{"votes":242,"name":"keyes"}],
"total":10995,"precincts":
{"total":37,"reporting":37},
"name":"Johnston"},
"Nash":
{"votes":[
{"votes":4348,"name":"mccain"},
{"votes":698,"name":"huckabee"},
{"votes":338,"name":"paul"},
{"votes":208,"name":"nopreference-r"},
{"votes":94,"name":"keyes"}],
"total":5686,"precincts":
{"total":26,"reporting":26},
"name":"Nash"},
"Tyrrell":
{"votes":[
{"votes":104,"name":"mccain"},
{"votes":11,"name":"huckabee"},
{"votes":5,"name":"nopreference-r"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"paul"}],
"total":126,"precincts":
{"total":6,"reporting":6},
"name":"Tyrrell"},
"Caswell":
{"votes":[
{"votes":451,"name":"mccain"},
{"votes":96,"name":"huckabee"},
{"votes":48,"name":"paul"},
{"votes":20,"name":"nopreference-r"},
{"votes":15,"name":"keyes"}],
"total":630,"precincts":
{"total":11,"reporting":11},
"name":"Caswell"},
"Cleveland":
{"votes":[
{"votes":2673,"name":"mccain"},
{"votes":572,"name":"huckabee"},
{"votes":310,"name":"paul"},
{"votes":144,"name":"keyes"},
{"votes":138,"name":"nopreference-r"}],
"total":3837,"precincts":
{"total":28,"reporting":28},
"name":"Cleveland"},
"Halifax":
{"votes":[
{"votes":749,"name":"mccain"},
{"votes":104,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":24,"name":"nopreference-r"},
{"votes":14,"name":"keyes"}],
"total":916,"precincts":
{"total":30,"reporting":30},
"name":"Halifax"},
"Cumberland":
{"votes":[
{"votes":8258,"name":"mccain"},
{"votes":1109,"name":"huckabee"},
{"votes":494,"name":"paul"},
{"votes":390,"name":"nopreference-r"},
{"votes":236,"name":"keyes"}],
"total":10487,"precincts":
{"total":69,"reporting":69},
"name":"Cumberland"},
"Rockingham":
{"votes":[
{"votes":3495,"name":"mccain"},
{"votes":742,"name":"huckabee"},
{"votes":230,"name":"nopreference-r"},
{"votes":216,"name":"paul"},
{"votes":60,"name":"keyes"}],
"total":4743,"precincts":
{"total":20,"reporting":20},
"name":"Rockingham"},
"Rowan":
{"votes":[
{"votes":7332,"name":"mccain"},
{"votes":1212,"name":"huckabee"},
{"votes":550,"name":"paul"},
{"votes":432,"name":"nopreference-r"},
{"votes":252,"name":"keyes"}],
"total":9778,"precincts":
{"total":44,"reporting":44},
"name":"Rowan"},
"Alleghany":
{"votes":[
{"votes":586,"name":"mccain"},
{"votes":94,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":31,"name":"nopreference-r"},
{"votes":12,"name":"keyes"}],
"total":764,"precincts":
{"total":7,"reporting":7},
"name":"Alleghany"},
"McDowell":
{"votes":[
{"votes":1419,"name":"mccain"},
{"votes":371,"name":"huckabee"},
{"votes":118,"name":"nopreference-r"},
{"votes":111,"name":"paul"},
{"votes":35,"name":"keyes"}],
"total":2054,"precincts":
{"total":17,"reporting":17},
"name":"McDowell"},
"Haywood":
{"votes":[
{"votes":2338,"name":"mccain"},
{"votes":519,"name":"huckabee"},
{"votes":371,"name":"paul"},
{"votes":166,"name":"nopreference-r"},
{"votes":71,"name":"keyes"}],
"total":3465,"precincts":
{"total":29,"reporting":29},
"name":"Haywood"},
"Pamlico":
{"votes":[
{"votes":625,"name":"mccain"},
{"votes":88,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":35,"name":"nopreference-r"},
{"votes":23,"name":"keyes"}],
"total":812,"precincts":
{"total":10,"reporting":10},
"name":"Pamlico"},
"Dare":
{"votes":[
{"votes":1287,"name":"mccain"},
{"votes":166,"name":"huckabee"},
{"votes":114,"name":"paul"},
{"votes":75,"name":"nopreference-r"},
{"votes":30,"name":"keyes"}],
"total":1672,"precincts":
{"total":16,"reporting":16},
"name":"Dare"},
"Jones":
{"votes":[
{"votes":289,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":16,"name":"keyes"},
{"votes":16,"name":"paul"},
{"votes":15,"name":"nopreference-r"}],
"total":373,"precincts":
{"total":7,"reporting":7},
"name":"Jones"},
"Pitt":
{"votes":[
{"votes":4398,"name":"mccain"},
{"votes":590,"name":"huckabee"},
{"votes":250,"name":"nopreference-r"},
{"votes":218,"name":"paul"},
{"votes":73,"name":"keyes"}],
"total":5529,"precincts":
{"total":38,"reporting":38},
"name":"Pitt"},
"Martin":
{"votes":[
{"votes":495,"name":"mccain"},
{"votes":86,"name":"huckabee"},
{"votes":33,"name":"nopreference-r"},
{"votes":18,"name":"paul"},
{"votes":12,"name":"keyes"}],
"total":644,"precincts":
{"total":13,"reporting":13},
"name":"Martin"},
"Mecklenburg":
{"votes":[
{"votes":30631,"name":"mccain"},
{"votes":6842,"name":"paul"},
{"votes":3733,"name":"huckabee"},
{"votes":2120,"name":"keyes"},
{"votes":1626,"name":"nopreference-r"}],
"total":44952,"precincts":
{"total":198,"reporting":192},
"name":"Mecklenburg"},
"Gates":
{"votes":[
{"votes":243,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":13,"name":"nopreference-r"},
{"votes":7,"name":"paul"},
{"votes":2,"name":"keyes"}],
"total":296,"precincts":
{"total":6,"reporting":6},
"name":"Gates"},
"Person":
{"votes":[
{"votes":972,"name":"mccain"},
{"votes":181,"name":"huckabee"},
{"votes":87,"name":"paul"},
{"votes":48,"name":"nopreference-r"},
{"votes":28,"name":"keyes"}],
"total":1316,"precincts":
{"total":14,"reporting":14},
"name":"Person"},
"Yancey":
{"votes":[
{"votes":972,"name":"mccain"},
{"votes":309,"name":"huckabee"},
{"votes":125,"name":"paul"},
{"votes":65,"name":"nopreference-r"},
{"votes":30,"name":"keyes"}],
"total":1501,"precincts":
{"total":11,"reporting":11},
"name":"Yancey"},
"Surry":
{"votes":[
{"votes":2953,"name":"mccain"},
{"votes":528,"name":"huckabee"},
{"votes":163,"name":"paul"},
{"votes":140,"name":"nopreference-r"},
{"votes":55,"name":"keyes"}],
"total":3839,"precincts":
{"total":32,"reporting":32},
"name":"Surry"},
"Perquimans":
{"votes":[
{"votes":448,"name":"mccain"},
{"votes":63,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":21,"name":"nopreference-r"},
{"votes":20,"name":"keyes"}],
"total":577,"precincts":
{"total":7,"reporting":7},
"name":"Perquimans"},
"Randolph":
{"votes":[
{"votes":7279,"name":"mccain"},
{"votes":1734,"name":"huckabee"},
{"votes":670,"name":"paul"},
{"votes":378,"name":"nopreference-r"},
{"votes":126,"name":"keyes"}],
"total":10187,"precincts":
{"total":42,"reporting":42},
"name":"Randolph"}}})