GoogleElectionMap.votesReady({"status":"ok","totals":
{"name":"Nebraska","precincts":
{"total":1665,"reporting":1665},
"votes":[
{"votes":31457,"name":"obama","delegates":16},
{"votes":30222,"name":"clinton","delegates":8},
{"votes":2639,"name":"gravel"},
{"votes":99,"name":"uncommitted-d"}],
"delegates":24,"date":"02-09","type":"caucus"},
"state":"NE","party":"dem","total":64417,"locals":
{"Colfax":
{"votes":[
{"votes":241,"name":"clinton"},
{"votes":220,"name":"obama"},
{"votes":31,"name":"gravel"}],
"total":492,"precincts":
{"total":6,"reporting":6},
"name":"Colfax"},
"Sherman":
{"votes":[
{"votes":172,"name":"clinton"},
{"votes":145,"name":"obama"},
{"votes":26,"name":"gravel"}],
"total":343,"precincts":
{"total":6,"reporting":4},
"name":"Sherman"},
"Furnas":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Furnas"},
"Frontier":
{"votes":[
{"votes":56,"name":"obama"},
{"votes":42,"name":"clinton"},
{"votes":9,"name":"gravel"}],
"total":107,"precincts":
{"total":6,"reporting":5},
"name":"Frontier"},
"Banner":
{"votes":[
{"votes":8,"name":"obama"},
{"votes":4,"name":"clinton"}],
"total":12,"precincts":
{"total":1,"reporting":1},
"name":"Banner"},
"Otoe":
{"votes":[
{"votes":453,"name":"clinton"},
{"votes":385,"name":"obama"},
{"votes":44,"name":"gravel"}],
"total":882,"precincts":
{"total":17,"reporting":17},
"name":"Otoe"},
"Wayne":
{"votes":[
{"votes":240,"name":"obama"},
{"votes":157,"name":"clinton"},
{"votes":17,"name":"gravel"}],
"total":414,"precincts":
{"total":11,"reporting":11},
"name":"Wayne"},
"Dixon":
{"votes":[
{"votes":213,"name":"clinton"},
{"votes":166,"name":"obama"},
{"votes":23,"name":"gravel"}],
"total":402,"precincts":
{"total":12,"reporting":12},
"name":"Dixon"},
"Hooker":
{"votes":[
{"votes":14,"name":"clinton"},
{"votes":12,"name":"obama"},
{"votes":1,"name":"gravel"}],
"total":27,"precincts":
{"total":2,"reporting":2},
"name":"Hooker"},
"Dodge":
{"votes":[
{"votes":1063,"name":"clinton"},
{"votes":959,"name":"obama"},
{"votes":85,"name":"gravel"}],
"total":2107,"precincts":
{"total":32,"reporting":32},
"name":"Dodge"},
"Brown":
{"votes":[
{"votes":60,"name":"clinton"},
{"votes":52,"name":"obama"},
{"votes":11,"name":"gravel"}],
"total":123,"precincts":
{"total":4,"reporting":4},
"name":"Brown"},
"Stanton":
{"votes":[
{"votes":47,"name":"obama"},
{"votes":33,"name":"clinton"},
{"votes":3,"name":"gravel"}],
"total":83,"precincts":
{"total":16,"reporting":10},
"name":"Stanton"},
"Sarpy":
{"votes":[
{"votes":690,"name":"clinton"},
{"votes":655,"name":"obama"},
{"votes":59,"name":"gravel"}],
"total":1404,"precincts":
{"total":88,"reporting":81},
"name":"Sarpy"},
"Kearney":
{"votes":[
{"votes":171,"name":"obama"},
{"votes":157,"name":"clinton"},
{"votes":16,"name":"gravel"}],
"total":344,"precincts":
{"total":13,"reporting":12},
"name":"Kearney"},
"Burt":
{"votes":[
{"votes":271,"name":"clinton"},
{"votes":240,"name":"obama"},
{"votes":21,"name":"gravel"}],
"total":532,"precincts":
{"total":12,"reporting":12},
"name":"Burt"},
"York":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"York"},
"Grant":
{"votes":[
{"votes":13,"name":"clinton"},
{"votes":7,"name":"obama"},
{"votes":4,"name":"gravel"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Grant"},
"Hitchcock":
{"votes":[
{"votes":53,"name":"obama"},
{"votes":52,"name":"clinton"},
{"votes":10,"name":"gravel"}],
"total":115,"precincts":
{"total":4,"reporting":3},
"name":"Hitchcock"},
"Loup":
{"votes":[
{"votes":17,"name":"obama"},
{"votes":8,"name":"clinton"},
{"votes":1,"name":"gravel"}],
"total":26,"precincts":
{"total":1,"reporting":1},
"name":"Loup"},
"Morrill":
{"votes":[
{"votes":33,"name":"clinton"},
{"votes":7,"name":"obama"},
{"votes":2,"name":"gravel"}],
"total":42,"precincts":
{"total":10,"reporting":3},
"name":"Morrill"},
"Box Butte":
{"votes":[
{"votes":192,"name":"clinton"},
{"votes":171,"name":"obama"},
{"votes":17,"name":"gravel"}],
"total":380,"precincts":
{"total":9,"reporting":9},
"name":"Box Butte"},
"Webster":
{"votes":[
{"votes":181,"name":"clinton"},
{"votes":138,"name":"obama"},
{"votes":29,"name":"gravel"}],
"total":348,"precincts":
{"total":6,"reporting":6},
"name":"Webster"},
"Seward":
{"votes":[
{"votes":369,"name":"clinton"},
{"votes":341,"name":"obama"},
{"votes":24,"name":"gravel"}],
"total":734,"precincts":
{"total":17,"reporting":17},
"name":"Seward"},
"Kimball":
{"votes":[
{"votes":81,"name":"clinton"},
{"votes":31,"name":"obama"},
{"votes":2,"name":"gravel"}],
"total":114,"precincts":
{"total":6,"reporting":6},
"name":"Kimball"},
"Thomas":
{"votes":[
{"votes":13,"name":"obama"},
{"votes":11,"name":"clinton"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Thomas"},
"Saunders":
{"votes":[
{"votes":627,"name":"obama"},
{"votes":575,"name":"clinton"},
{"votes":93,"name":"gravel"}],
"total":1295,"precincts":
{"total":19,"reporting":19},
"name":"Saunders"},
"Dawes":
{"votes":[
{"votes":103,"name":"clinton"},
{"votes":102,"name":"obama"},
{"votes":4,"name":"gravel"}],
"total":209,"precincts":
{"total":12,"reporting":6},
"name":"Dawes"},
"Washington":
{"votes":[
{"votes":407,"name":"obama"},
{"votes":385,"name":"clinton"},
{"votes":37,"name":"gravel"}],
"total":829,"precincts":
{"total":16,"reporting":16},
"name":"Washington"},
"Dakota":
{"votes":[
{"votes":650,"name":"clinton"},
{"votes":404,"name":"obama"},
{"votes":46,"name":"gravel"}],
"total":1100,"precincts":
{"total":14,"reporting":14},
"name":"Dakota"},
"Polk":
{"votes":[
{"votes":130,"name":"obama"},
{"votes":116,"name":"clinton"},
{"votes":15,"name":"gravel"}],
"total":261,"precincts":
{"total":7,"reporting":7},
"name":"Polk"},
"Chase":
{"votes":[
{"votes":71,"name":"clinton"},
{"votes":61,"name":"obama"},
{"votes":11,"name":"gravel"}],
"total":143,"precincts":
{"total":6,"reporting":5},
"name":"Chase"},
"Deuel":
{"votes":[
{"votes":34,"name":"clinton"},
{"votes":31,"name":"obama"},
{"votes":2,"name":"gravel"}],
"total":67,"precincts":
{"total":4,"reporting":4},
"name":"Deuel"},
"Howard":
{"votes":[
{"votes":11,"name":"obama"},
{"votes":7,"name":"clinton"},
{"votes":1,"name":"gravel"}],
"total":19,"precincts":
{"total":9,"reporting":1},
"name":"Howard"},
"Pierce":
{"votes":[
{"votes":98,"name":"obama"},
{"votes":63,"name":"clinton"},
{"votes":13,"name":"gravel"}],
"total":174,"precincts":
{"total":6,"reporting":5},
"name":"Pierce"},
"Jefferson":
{"votes":[
{"votes":35,"name":"clinton"},
{"votes":15,"name":"obama"}],
"total":50,"precincts":
{"total":11,"reporting":1},
"name":"Jefferson"},
"Cheyenne":
{"votes":[
{"votes":163,"name":"clinton"},
{"votes":140,"name":"obama"},
{"votes":27,"name":"gravel"}],
"total":330,"precincts":
{"total":10,"reporting":10},
"name":"Cheyenne"},
"Butler":
{"votes":[
{"votes":279,"name":"clinton"},
{"votes":213,"name":"obama"},
{"votes":48,"name":"gravel"}],
"total":540,"precincts":
{"total":21,"reporting":21},
"name":"Butler"},
"McPherson":
{"votes":[
{"votes":11,"name":"clinton"},
{"votes":5,"name":"obama"},
{"votes":4,"name":"gravel"}],
"total":20,"precincts":
{"total":1,"reporting":1},
"name":"McPherson"},
"Boyd":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Boyd"},
"Holt":
{"votes":[
{"votes":135,"name":"clinton"},
{"votes":123,"name":"obama"},
{"votes":18,"name":"gravel"}],
"total":276,"precincts":
{"total":14,"reporting":10},
"name":"Holt"},
"Hamilton":
{"votes":[
{"votes":81,"name":"obama"},
{"votes":64,"name":"clinton"},
{"votes":15,"name":"gravel"}],
"total":160,"precincts":
{"total":12,"reporting":0},
"name":"Hamilton"},
"Cuming":
{"votes":[
{"votes":182,"name":"obama"},
{"votes":147,"name":"clinton"},
{"votes":19,"name":"gravel"}],
"total":348,"precincts":
{"total":8,"reporting":6},
"name":"Cuming"},
"Keith":
{"votes":[
{"votes":177,"name":"clinton"},
{"votes":156,"name":"obama"},
{"votes":27,"name":"gravel"}],
"total":360,"precincts":
{"total":12,"reporting":11},
"name":"Keith"},
"Sioux":
{"votes":[
{"votes":12,"name":"obama"},
{"votes":11,"name":"clinton"},
{"votes":3,"name":"gravel"}],
"total":26,"precincts":
{"total":2,"reporting":1},
"name":"Sioux"},
"Johnson":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Johnson"},
"Arthur":
{"votes":[
{"votes":15,"name":"obama"},
{"votes":10,"name":"clinton"},
{"votes":2,"name":"gravel"}],
"total":27,"precincts":
{"total":1,"reporting":1},
"name":"Arthur"},
"Clay":
{"votes":[
{"votes":98,"name":"clinton"},
{"votes":95,"name":"obama"},
{"votes":10,"name":"gravel"}],
"total":203,"precincts":
{"total":12,"reporting":7},
"name":"Clay"},
"Buffalo":
{"votes":[
{"votes":85,"name":"clinton"},
{"votes":56,"name":"obama"},
{"votes":9,"name":"gravel"}],
"total":150,"precincts":
{"total":32,"reporting":2},
"name":"Buffalo"},
"Madison":
{"votes":[
{"votes":819,"name":"obama"},
{"votes":649,"name":"clinton"},
{"votes":78,"name":"gravel"}],
"total":1546,"precincts":
{"total":24,"reporting":24},
"name":"Madison"},
"Custer":
{"votes":[
{"votes":303,"name":"clinton"},
{"votes":295,"name":"obama"},
{"votes":41,"name":"gravel"}],
"total":639,"precincts":
{"total":39,"reporting":31},
"name":"Custer"},
"Red Willow":
{"votes":[
{"votes":141,"name":"clinton"},
{"votes":110,"name":"obama"},
{"votes":23,"name":"gravel"}],
"total":274,"precincts":
{"total":16,"reporting":8},
"name":"Red Willow"},
"Blaine":
{"votes":[
{"votes":11,"name":"obama"},
{"votes":7,"name":"clinton"},
{"votes":3,"name":"gravel"}],
"total":21,"precincts":
{"total":1,"reporting":1},
"name":"Blaine"},
"Dawson":
{"votes":[
{"votes":354,"name":"clinton"},
{"votes":322,"name":"obama"},
{"votes":52,"name":"gravel"}],
"total":728,"precincts":
{"total":20,"reporting":20},
"name":"Dawson"},
"Saline":
{"votes":[
{"votes":283,"name":"clinton"},
{"votes":177,"name":"obama"},
{"votes":13,"name":"gravel"}],
"total":473,"precincts":
{"total":13,"reporting":6},
"name":"Saline"},
"Cass":
{"votes":[
{"votes":143,"name":"clinton"},
{"votes":110,"name":"obama"},
{"votes":16,"name":"gravel"}],
"total":269,"precincts":
{"total":31,"reporting":29},
"name":"Cass"},
"Nemaha":
{"votes":[
{"votes":230,"name":"clinton"},
{"votes":202,"name":"obama"},
{"votes":32,"name":"gravel"}],
"total":464,"precincts":
{"total":10,"reporting":6},
"name":"Nemaha"},
"Rock":
{"votes":[
{"votes":3,"name":"gravel"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"obama"}],
"total":7,"precincts":
{"total":6,"reporting":0},
"name":"Rock"},
"Gage":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Gage"},
"CD1":
{"votes":[
{"votes":10041,"name":"obama"},
{"votes":5288,"name":"clinton"},
{"votes":85,"name":"uncommitted-d"}],
"total":15414,"precincts":
{"total":576,"reporting":576},
"name":"CD1"},
"CD2":
{"votes":[
{"votes":12252,"name":"obama"},
{"votes":3709,"name":"clinton"}],
"total":15961,"precincts":
{"total":422,"reporting":422},
"name":"CD2"},
"CD3":
{"votes":[
{"votes":3833,"name":"obama"},
{"votes":3448,"name":"clinton"},
{"votes":14,"name":"uncommitted-d"}],
"total":7295,"precincts":
{"total":667,"reporting":667},
"name":"CD3"},
"Wheeler":
{"votes":[
{"votes":31,"name":"clinton"},
{"votes":18,"name":"obama"},
{"votes":1,"name":"gravel"}],
"total":50,"precincts":
{"total":2,"reporting":2},
"name":"Wheeler"},
"Cedar":
{"votes":[
{"votes":190,"name":"obama"},
{"votes":129,"name":"clinton"},
{"votes":18,"name":"gravel"}],
"total":337,"precincts":
{"total":17,"reporting":17},
"name":"Cedar"},
"Dundy":
{"votes":[
{"votes":58,"name":"clinton"},
{"votes":51,"name":"obama"},
{"votes":6,"name":"gravel"}],
"total":115,"precincts":
{"total":4,"reporting":4},
"name":"Dundy"},
"Lincoln":
{"votes":[
{"votes":272,"name":"clinton"},
{"votes":183,"name":"obama"},
{"votes":27,"name":"gravel"}],
"total":482,"precincts":
{"total":27,"reporting":4},
"name":"Lincoln"},
"Adams":
{"votes":[
{"votes":860,"name":"clinton"},
{"votes":844,"name":"obama"},
{"votes":90,"name":"gravel"}],
"total":1794,"precincts":
{"total":28,"reporting":26},
"name":"Adams"},
"Hayes":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Hayes"},
"Harlan":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Harlan"},
"Franklin":
{"votes":[
{"votes":85,"name":"clinton"},
{"votes":72,"name":"obama"},
{"votes":10,"name":"gravel"}],
"total":167,"precincts":
{"total":5,"reporting":5},
"name":"Franklin"},
"Richardson":
{"votes":[
{"votes":349,"name":"clinton"},
{"votes":253,"name":"obama"},
{"votes":50,"name":"gravel"}],
"total":652,"precincts":
{"total":15,"reporting":15},
"name":"Richardson"},
"Antelope":
{"votes":[
{"votes":58,"name":"clinton"},
{"votes":35,"name":"obama"},
{"votes":10,"name":"gravel"}],
"total":103,"precincts":
{"total":14,"reporting":2},
"name":"Antelope"},
"Fillmore":
{"votes":[
{"votes":212,"name":"clinton"},
{"votes":156,"name":"obama"},
{"votes":17,"name":"gravel"}],
"total":385,"precincts":
{"total":11,"reporting":11},
"name":"Fillmore"},
"Greeley":
{"votes":[
{"votes":185,"name":"clinton"},
{"votes":175,"name":"obama"},
{"votes":40,"name":"gravel"}],
"total":400,"precincts":
{"total":5,"reporting":3},
"name":"Greeley"},
"Lancaster":
{"votes":[
{"votes":7489,"name":"obama"},
{"votes":7121,"name":"clinton"},
{"votes":278,"name":"gravel"}],
"total":14888,"precincts":
{"total":223,"reporting":134},
"name":"Lancaster"},
"Cherry":
{"votes":[
{"votes":147,"name":"clinton"},
{"votes":114,"name":"obama"},
{"votes":28,"name":"gravel"}],
"total":289,"precincts":
{"total":21,"reporting":21},
"name":"Cherry"},
"Douglas":
{"votes":[
{"votes":9516,"name":"obama"},
{"votes":7114,"name":"clinton"},
{"votes":505,"name":"gravel"}],
"total":17135,"precincts":
{"total":352,"reporting":211},
"name":"Douglas"},
"Valley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Valley"},
"Garden":
{"votes":[
{"votes":52,"name":"obama"},
{"votes":48,"name":"clinton"},
{"votes":6,"name":"gravel"}],
"total":106,"precincts":
{"total":5,"reporting":5},
"name":"Garden"},
"Phelps":
{"votes":[
{"votes":17,"name":"clinton"},
{"votes":12,"name":"obama"}],
"total":29,"precincts":
{"total":13,"reporting":1},
"name":"Phelps"},
"Thurston":
{"votes":[
{"votes":186,"name":"obama"},
{"votes":135,"name":"clinton"},
{"votes":14,"name":"gravel"}],
"total":335,"precincts":
{"total":10,"reporting":9},
"name":"Thurston"},
"Logan":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Logan"},
"Merrick":
{"votes":[
{"votes":240,"name":"clinton"},
{"votes":208,"name":"obama"},
{"votes":37,"name":"gravel"}],
"total":485,"precincts":
{"total":15,"reporting":15},
"name":"Merrick"},
"Nuckolls":
{"votes":[
{"votes":192,"name":"clinton"},
{"votes":161,"name":"obama"},
{"votes":21,"name":"gravel"}],
"total":374,"precincts":
{"total":9,"reporting":9},
"name":"Nuckolls"},
"Knox":
{"votes":[
{"votes":166,"name":"clinton"},
{"votes":162,"name":"obama"},
{"votes":30,"name":"gravel"}],
"total":358,"precincts":
{"total":9,"reporting":6},
"name":"Knox"},
"Platte":
{"votes":[
{"votes":546,"name":"obama"},
{"votes":438,"name":"clinton"},
{"votes":84,"name":"gravel"}],
"total":1068,"precincts":
{"total":31,"reporting":20},
"name":"Platte"},
"Hall":
{"votes":[
{"votes":1274,"name":"clinton"},
{"votes":864,"name":"obama"},
{"votes":107,"name":"gravel"}],
"total":2245,"precincts":
{"total":40,"reporting":37},
"name":"Hall"},
"Scotts Bluff":
{"votes":[
{"votes":388,"name":"clinton"},
{"votes":321,"name":"obama"},
{"votes":30,"name":"gravel"}],
"total":739,"precincts":
{"total":31,"reporting":22},
"name":"Scotts Bluff"},
"Sheridan":
{"votes":[
{"votes":69,"name":"clinton"},
{"votes":68,"name":"obama"},
{"votes":20,"name":"gravel"}],
"total":157,"precincts":
{"total":9,"reporting":9},
"name":"Sheridan"},
"Gosper":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Gosper"},
"Nance":
{"votes":[
{"votes":198,"name":"clinton"},
{"votes":138,"name":"obama"},
{"votes":29,"name":"gravel"}],
"total":365,"precincts":
{"total":7,"reporting":7},
"name":"Nance"},
"Boone":
{"votes":[
{"votes":262,"name":"clinton"},
{"votes":212,"name":"obama"},
{"votes":47,"name":"gravel"}],
"total":521,"precincts":
{"total":10,"reporting":10},
"name":"Boone"},
"Keya Paha":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Keya Paha"},
"Pawnee":
{"votes":[
{"votes":133,"name":"clinton"},
{"votes":108,"name":"obama"},
{"votes":10,"name":"gravel"}],
"total":251,"precincts":
{"total":6,"reporting":6},
"name":"Pawnee"},
"Perkins":
{"votes":[
{"votes":18,"name":"clinton"},
{"votes":13,"name":"obama"},
{"votes":5,"name":"gravel"}],
"total":36,"precincts":
{"total":3,"reporting":3},
"name":"Perkins"},
"Garfield":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Garfield"},
"Thayer":
{"votes":[
{"votes":181,"name":"clinton"},
{"votes":165,"name":"obama"},
{"votes":19,"name":"gravel"}],
"total":365,"precincts":
{"total":8,"reporting":8},
"name":"Thayer"}}})