GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":88447,"name":"mccain","delegates":7},
{"votes":75202,"name":"romney","delegates":4},
{"votes":26760,"name":"huckabee","delegates":1},
{"votes":20387,"name":"giuliani"},
{"votes":18276,"name":"paul"},
{"votes":2884,"name":"thompson"},
{"votes":1220,"name":"hunter"},
{"votes":220,"name":"keyes"},
{"votes":68,"name":"tancredo"}],
"name":"New Hampshire","precincts":
{"total":301,"reporting":300},
"delegates":12,"date":"01-08"},
"state":"NH","party":"gop","total":233464,"locals":
{"Albany":
{"votes":[
{"votes":46,"name":"mccain"},
{"votes":17,"name":"paul"},
{"votes":13,"name":"huckabee"},
{"votes":13,"name":"giuliani"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":92,"precincts":
{"total":1,"reporting":1},
"name":"Albany"},
"New London":
{"votes":[
{"votes":531,"name":"mccain"},
{"votes":372,"name":"romney"},
{"votes":84,"name":"giuliani"},
{"votes":76,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"hunter"}],
"total":1117,"precincts":
{"total":1,"reporting":1},
"name":"New London"},
"Lyman":
{"votes":[
{"votes":42,"name":"mccain"},
{"votes":31,"name":"paul"},
{"votes":15,"name":"huckabee"},
{"votes":13,"name":"romney"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"hunter"}],
"total":105,"precincts":
{"total":1,"reporting":1},
"name":"Lyman"},
"Ossipee":
{"votes":[
{"votes":301,"name":"mccain"},
{"votes":232,"name":"romney"},
{"votes":107,"name":"huckabee"},
{"votes":83,"name":"paul"},
{"votes":54,"name":"giuliani"},
{"votes":13,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":794,"precincts":
{"total":1,"reporting":1},
"name":"Ossipee"},
"Harrisville":
{"votes":[
{"votes":63,"name":"mccain"},
{"votes":48,"name":"romney"},
{"votes":15,"name":"huckabee"},
{"votes":13,"name":"paul"},
{"votes":7,"name":"giuliani"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":150,"precincts":
{"total":1,"reporting":1},
"name":"Harrisville"},
"Fitzwilliam":
{"votes":[
{"votes":166,"name":"mccain"},
{"votes":125,"name":"romney"},
{"votes":59,"name":"huckabee"},
{"votes":52,"name":"paul"},
{"votes":26,"name":"giuliani"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"thompson"}],
"total":434,"precincts":
{"total":1,"reporting":1},
"name":"Fitzwilliam"},
"Kensington":
{"votes":[
{"votes":228,"name":"mccain"},
{"votes":160,"name":"romney"},
{"votes":49,"name":"giuliani"},
{"votes":30,"name":"paul"},
{"votes":29,"name":"huckabee"},
{"votes":6,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":505,"precincts":
{"total":1,"reporting":1},
"name":"Kensington"},
"Clarksville":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":16,"name":"romney"},
{"votes":16,"name":"huckabee"},
{"votes":13,"name":"paul"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"thompson"}],
"total":72,"precincts":
{"total":1,"reporting":1},
"name":"Clarksville"},
"Gorham":
{"votes":[
{"votes":142,"name":"mccain"},
{"votes":87,"name":"romney"},
{"votes":70,"name":"huckabee"},
{"votes":32,"name":"giuliani"},
{"votes":26,"name":"paul"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"thompson"}],
"total":361,"precincts":
{"total":1,"reporting":1},
"name":"Gorham"},
"Walpole":
{"votes":[
{"votes":275,"name":"mccain"},
{"votes":177,"name":"romney"},
{"votes":51,"name":"giuliani"},
{"votes":50,"name":"huckabee"},
{"votes":47,"name":"paul"},
{"votes":9,"name":"hunter"}],
"total":609,"precincts":
{"total":1,"reporting":1},
"name":"Walpole"},
"Rindge":
{"votes":[
{"votes":367,"name":"romney"},
{"votes":351,"name":"mccain"},
{"votes":287,"name":"huckabee"},
{"votes":120,"name":"paul"},
{"votes":49,"name":"giuliani"},
{"votes":11,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":1189,"precincts":
{"total":1,"reporting":1},
"name":"Rindge"},
"Hill":
{"votes":[
{"votes":102,"name":"mccain"},
{"votes":47,"name":"romney"},
{"votes":30,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":20,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":231,"precincts":
{"total":1,"reporting":1},
"name":"Hill"},
"Enfield":
{"votes":[
{"votes":309,"name":"mccain"},
{"votes":119,"name":"romney"},
{"votes":74,"name":"huckabee"},
{"votes":69,"name":"paul"},
{"votes":41,"name":"giuliani"},
{"votes":18,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":631,"precincts":
{"total":1,"reporting":1},
"name":"Enfield"},
"Concord":
{"votes":[
{"votes":2684,"name":"mccain"},
{"votes":1577,"name":"romney"},
{"votes":781,"name":"huckabee"},
{"votes":601,"name":"paul"},
{"votes":565,"name":"giuliani"},
{"votes":49,"name":"thompson"},
{"votes":24,"name":"hunter"},
{"votes":3,"name":"keyes"}],
"total":6284,"precincts":
{"total":10,"reporting":10},
"name":"Concord"},
"Allenstown":
{"votes":[
{"votes":241,"name":"mccain"},
{"votes":181,"name":"romney"},
{"votes":84,"name":"huckabee"},
{"votes":78,"name":"giuliani"},
{"votes":75,"name":"paul"},
{"votes":7,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":671,"precincts":
{"total":1,"reporting":1},
"name":"Allenstown"},
"Shelburne":
{"votes":[
{"votes":29,"name":"mccain"},
{"votes":27,"name":"romney"},
{"votes":11,"name":"huckabee"},
{"votes":10,"name":"giuliani"},
{"votes":7,"name":"paul"},
{"votes":5,"name":"thompson"}],
"total":89,"precincts":
{"total":1,"reporting":1},
"name":"Shelburne"},
"Cornish":
{"votes":[
{"votes":115,"name":"mccain"},
{"votes":54,"name":"romney"},
{"votes":42,"name":"paul"},
{"votes":32,"name":"huckabee"},
{"votes":17,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":272,"precincts":
{"total":1,"reporting":1},
"name":"Cornish"},
"Milford":
{"votes":[
{"votes":978,"name":"mccain"},
{"votes":867,"name":"romney"},
{"votes":512,"name":"huckabee"},
{"votes":204,"name":"giuliani"},
{"votes":200,"name":"paul"},
{"votes":23,"name":"thompson"},
{"votes":19,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":2805,"precincts":
{"total":1,"reporting":1},
"name":"Milford"},
"Sandwich":
{"votes":[
{"votes":150,"name":"mccain"},
{"votes":101,"name":"romney"},
{"votes":36,"name":"giuliani"},
{"votes":33,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":11,"name":"thompson"}],
"total":356,"precincts":
{"total":1,"reporting":1},
"name":"Sandwich"},
"Columbia":
{"votes":[
{"votes":72,"name":"mccain"},
{"votes":26,"name":"romney"},
{"votes":26,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":7,"name":"giuliani"},
{"votes":2,"name":"thompson"}],
"total":154,"precincts":
{"total":1,"reporting":1},
"name":"Columbia"},
"Dixville":
{"votes":[
{"votes":4,"name":"mccain"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"giuliani"}],
"total":7,"precincts":
{"total":1,"reporting":1},
"name":"Dixville"},
"Marlborough":
{"votes":[
{"votes":120,"name":"mccain"},
{"votes":80,"name":"romney"},
{"votes":37,"name":"huckabee"},
{"votes":30,"name":"paul"},
{"votes":26,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":300,"precincts":
{"total":1,"reporting":1},
"name":"Marlborough"},
"Fremont":
{"votes":[
{"votes":326,"name":"mccain"},
{"votes":313,"name":"romney"},
{"votes":80,"name":"giuliani"},
{"votes":77,"name":"huckabee"},
{"votes":46,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":862,"precincts":
{"total":1,"reporting":1},
"name":"Fremont"},
"Newfields":
{"votes":[
{"votes":158,"name":"romney"},
{"votes":138,"name":"mccain"},
{"votes":34,"name":"huckabee"},
{"votes":33,"name":"giuliani"},
{"votes":32,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":401,"precincts":
{"total":1,"reporting":1},
"name":"Newfields"},
"Brookline":
{"votes":[
{"votes":507,"name":"romney"},
{"votes":395,"name":"mccain"},
{"votes":128,"name":"huckabee"},
{"votes":117,"name":"giuliani"},
{"votes":92,"name":"paul"},
{"votes":19,"name":"thompson"},
{"votes":7,"name":"hunter"}],
"total":1265,"precincts":
{"total":1,"reporting":1},
"name":"Brookline"},
"Newmarket":
{"votes":[
{"votes":477,"name":"mccain"},
{"votes":323,"name":"romney"},
{"votes":138,"name":"huckabee"},
{"votes":138,"name":"giuliani"},
{"votes":137,"name":"paul"},
{"votes":21,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1239,"precincts":
{"total":1,"reporting":1},
"name":"Newmarket"},
"Swanzey":
{"votes":[
{"votes":413,"name":"mccain"},
{"votes":248,"name":"romney"},
{"votes":145,"name":"huckabee"},
{"votes":88,"name":"giuliani"},
{"votes":69,"name":"paul"},
{"votes":17,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":990,"precincts":
{"total":1,"reporting":1},
"name":"Swanzey"},
"Madbury":
{"votes":[
{"votes":135,"name":"mccain"},
{"votes":87,"name":"romney"},
{"votes":39,"name":"giuliani"},
{"votes":31,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":5,"name":"hunter"},
{"votes":4,"name":"thompson"}],
"total":325,"precincts":
{"total":1,"reporting":1},
"name":"Madbury"},
"Charlestown":
{"votes":[
{"votes":253,"name":"mccain"},
{"votes":120,"name":"romney"},
{"votes":111,"name":"huckabee"},
{"votes":70,"name":"paul"},
{"votes":39,"name":"giuliani"},
{"votes":16,"name":"thompson"},
{"votes":9,"name":"hunter"}],
"total":618,"precincts":
{"total":1,"reporting":1},
"name":"Charlestown"},
"Easton":
{"votes":[
{"votes":25,"name":"mccain"},
{"votes":12,"name":"romney"},
{"votes":7,"name":"huckabee"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"thompson"}],
"total":52,"precincts":
{"total":1,"reporting":1},
"name":"Easton"},
"Bedford":
{"votes":[
{"votes":2479,"name":"romney"},
{"votes":2148,"name":"mccain"},
{"votes":579,"name":"giuliani"},
{"votes":434,"name":"huckabee"},
{"votes":263,"name":"paul"},
{"votes":51,"name":"thompson"},
{"votes":16,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":5973,"precincts":
{"total":1,"reporting":1},
"name":"Bedford"},
"Newbury":
{"votes":[
{"votes":211,"name":"mccain"},
{"votes":150,"name":"romney"},
{"votes":62,"name":"huckabee"},
{"votes":43,"name":"giuliani"},
{"votes":34,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":519,"precincts":
{"total":1,"reporting":1},
"name":"Newbury"},
"Boscawen":
{"votes":[
{"votes":220,"name":"mccain"},
{"votes":145,"name":"romney"},
{"votes":95,"name":"huckabee"},
{"votes":62,"name":"giuliani"},
{"votes":59,"name":"paul"},
{"votes":7,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":594,"precincts":
{"total":1,"reporting":1},
"name":"Boscawen"},
"Sanbornton":
{"votes":[
{"votes":226,"name":"romney"},
{"votes":224,"name":"mccain"},
{"votes":62,"name":"huckabee"},
{"votes":61,"name":"paul"},
{"votes":56,"name":"giuliani"},
{"votes":7,"name":"thompson"},
{"votes":4,"name":"hunter"}],
"total":640,"precincts":
{"total":1,"reporting":1},
"name":"Sanbornton"},
"Hancock":
{"votes":[
{"votes":189,"name":"mccain"},
{"votes":120,"name":"romney"},
{"votes":36,"name":"paul"},
{"votes":32,"name":"huckabee"},
{"votes":30,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":414,"precincts":
{"total":1,"reporting":1},
"name":"Hancock"},
"Dublin":
{"votes":[
{"votes":151,"name":"mccain"},
{"votes":109,"name":"romney"},
{"votes":83,"name":"huckabee"},
{"votes":22,"name":"paul"},
{"votes":17,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":394,"precincts":
{"total":1,"reporting":1},
"name":"Dublin"},
"Wakefield":
{"votes":[
{"votes":377,"name":"mccain"},
{"votes":271,"name":"romney"},
{"votes":111,"name":"huckabee"},
{"votes":93,"name":"giuliani"},
{"votes":82,"name":"paul"},
{"votes":28,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":966,"precincts":
{"total":1,"reporting":1},
"name":"Wakefield"},
"Carroll":
{"votes":[
{"votes":61,"name":"mccain"},
{"votes":44,"name":"romney"},
{"votes":28,"name":"huckabee"},
{"votes":10,"name":"giuliani"},
{"votes":9,"name":"paul"},
{"votes":1,"name":"hunter"}],
"total":153,"precincts":
{"total":1,"reporting":1},
"name":"Carroll"},
"Greenville":
{"votes":[
{"votes":86,"name":"mccain"},
{"votes":32,"name":"huckabee"},
{"votes":16,"name":"giuliani"},
{"votes":5,"name":"hunter"}],
"total":139,"precincts":
{"total":1,"reporting":1},
"name":"Greenville"},
"Antrim":
{"votes":[
{"votes":187,"name":"mccain"},
{"votes":165,"name":"romney"},
{"votes":91,"name":"huckabee"},
{"votes":71,"name":"paul"},
{"votes":41,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":569,"precincts":
{"total":1,"reporting":1},
"name":"Antrim"},
"Eaton":
{"votes":[
{"votes":41,"name":"mccain"},
{"votes":26,"name":"romney"},
{"votes":8,"name":"giuliani"},
{"votes":7,"name":"huckabee"},
{"votes":5,"name":"paul"}],
"total":87,"precincts":
{"total":1,"reporting":1},
"name":"Eaton"},
"Nelson":
{"votes":[
{"votes":43,"name":"mccain"},
{"votes":39,"name":"romney"},
{"votes":11,"name":"huckabee"},
{"votes":10,"name":"paul"},
{"votes":8,"name":"giuliani"},
{"votes":3,"name":"hunter"}],
"total":114,"precincts":
{"total":1,"reporting":1},
"name":"Nelson"},
"Hooksett":
{"votes":[
{"votes":994,"name":"mccain"},
{"votes":991,"name":"romney"},
{"votes":309,"name":"giuliani"},
{"votes":295,"name":"huckabee"},
{"votes":169,"name":"paul"},
{"votes":29,"name":"thompson"},
{"votes":14,"name":"hunter"},
{"votes":4,"name":"keyes"}],
"total":2805,"precincts":
{"total":1,"reporting":1},
"name":"Hooksett"},
"Webster":
{"votes":[
{"votes":159,"name":"mccain"},
{"votes":92,"name":"romney"},
{"votes":46,"name":"huckabee"},
{"votes":40,"name":"giuliani"},
{"votes":40,"name":"paul"}],
"total":377,"precincts":
{"total":1,"reporting":1},
"name":"Webster"},
"Chesterfield":
{"votes":[
{"votes":243,"name":"mccain"},
{"votes":166,"name":"romney"},
{"votes":95,"name":"huckabee"},
{"votes":52,"name":"giuliani"},
{"votes":48,"name":"paul"},
{"votes":9,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":615,"precincts":
{"total":1,"reporting":1},
"name":"Chesterfield"},
"Exeter":
{"votes":[
{"votes":1203,"name":"mccain"},
{"votes":891,"name":"romney"},
{"votes":241,"name":"giuliani"},
{"votes":224,"name":"huckabee"},
{"votes":167,"name":"paul"},
{"votes":27,"name":"thompson"},
{"votes":8,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":2763,"precincts":
{"total":1,"reporting":1},
"name":"Exeter"},
"Goshen":
{"votes":[
{"votes":57,"name":"mccain"},
{"votes":29,"name":"paul"},
{"votes":25,"name":"huckabee"},
{"votes":24,"name":"romney"},
{"votes":21,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"thompson"}],
"total":160,"precincts":
{"total":1,"reporting":1},
"name":"Goshen"},
"Alexandria":
{"votes":[
{"votes":148,"name":"mccain"},
{"votes":62,"name":"romney"},
{"votes":48,"name":"huckabee"},
{"votes":30,"name":"giuliani"},
{"votes":29,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":329,"precincts":
{"total":1,"reporting":1},
"name":"Alexandria"},
"Gilsum":
{"votes":[
{"votes":53,"name":"mccain"},
{"votes":46,"name":"romney"},
{"votes":17,"name":"huckabee"},
{"votes":10,"name":"giuliani"},
{"votes":10,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"hunter"}],
"total":145,"precincts":
{"total":1,"reporting":1},
"name":"Gilsum"},
"Sullivan":
{"votes":[
{"votes":35,"name":"romney"},
{"votes":32,"name":"mccain"},
{"votes":21,"name":"huckabee"},
{"votes":14,"name":"paul"},
{"votes":5,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"thompson"}],
"total":109,"precincts":
{"total":1,"reporting":1},
"name":"Sullivan"},
"Groton":
{"votes":[
{"votes":48,"name":"mccain"},
{"votes":24,"name":"romney"},
{"votes":14,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":7,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":1,"name":"tancredo"}],
"total":109,"precincts":
{"total":1,"reporting":1},
"name":"Groton"},
"Belmont":
{"votes":[
{"votes":456,"name":"mccain"},
{"votes":329,"name":"romney"},
{"votes":180,"name":"huckabee"},
{"votes":102,"name":"paul"},
{"votes":96,"name":"giuliani"},
{"votes":30,"name":"thompson"},
{"votes":11,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":1207,"precincts":
{"total":1,"reporting":1},
"name":"Belmont"},
"Andover":
{"votes":[
{"votes":186,"name":"mccain"},
{"votes":95,"name":"romney"},
{"votes":73,"name":"huckabee"},
{"votes":44,"name":"giuliani"},
{"votes":42,"name":"paul"},
{"votes":8,"name":"hunter"},
{"votes":7,"name":"thompson"}],
"total":455,"precincts":
{"total":1,"reporting":1},
"name":"Andover"},
"Tilton":
{"votes":[
{"votes":254,"name":"mccain"},
{"votes":162,"name":"romney"},
{"votes":92,"name":"huckabee"},
{"votes":52,"name":"paul"},
{"votes":44,"name":"giuliani"},
{"votes":11,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":618,"precincts":
{"total":1,"reporting":1},
"name":"Tilton"},
"Nottingham":
{"votes":[
{"votes":371,"name":"mccain"},
{"votes":289,"name":"romney"},
{"votes":140,"name":"huckabee"},
{"votes":74,"name":"paul"},
{"votes":65,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":959,"precincts":
{"total":1,"reporting":1},
"name":"Nottingham"},
"Milan":
{"votes":[
{"votes":82,"name":"mccain"},
{"votes":56,"name":"huckabee"},
{"votes":33,"name":"romney"},
{"votes":25,"name":"paul"},
{"votes":21,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":222,"precincts":
{"total":1,"reporting":1},
"name":"Milan"},
"Durham":
{"votes":[
{"votes":472,"name":"mccain"},
{"votes":292,"name":"romney"},
{"votes":96,"name":"paul"},
{"votes":94,"name":"huckabee"},
{"votes":93,"name":"giuliani"},
{"votes":20,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":1068,"precincts":
{"total":1,"reporting":1},
"name":"Durham"},
"Manchester":
{"votes":[
{"votes":5119,"name":"mccain"},
{"votes":4935,"name":"romney"},
{"votes":1640,"name":"huckabee"},
{"votes":1454,"name":"giuliani"},
{"votes":1230,"name":"paul"},
{"votes":139,"name":"thompson"},
{"votes":94,"name":"hunter"},
{"votes":16,"name":"keyes"},
{"votes":6,"name":"tancredo"}],
"total":14633,"precincts":
{"total":12,"reporting":12},
"name":"Manchester"},
"Canterbury":
{"votes":[
{"votes":224,"name":"mccain"},
{"votes":126,"name":"romney"},
{"votes":51,"name":"huckabee"},
{"votes":50,"name":"paul"},
{"votes":27,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":494,"precincts":
{"total":1,"reporting":1},
"name":"Canterbury"},
"Dalton":
{"votes":[
{"votes":77,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":23,"name":"romney"},
{"votes":18,"name":"paul"},
{"votes":17,"name":"giuliani"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":187,"precincts":
{"total":1,"reporting":1},
"name":"Dalton"},
"Effingham":
{"votes":[
{"votes":89,"name":"mccain"},
{"votes":63,"name":"romney"},
{"votes":44,"name":"huckabee"},
{"votes":34,"name":"paul"},
{"votes":17,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":249,"precincts":
{"total":1,"reporting":1},
"name":"Effingham"},
"Franconia":
{"votes":[
{"votes":116,"name":"mccain"},
{"votes":54,"name":"romney"},
{"votes":22,"name":"huckabee"},
{"votes":22,"name":"giuliani"},
{"votes":5,"name":"paul"},
{"votes":1,"name":"hunter"}],
"total":220,"precincts":
{"total":1,"reporting":1},
"name":"Franconia"},
"Waterville Valley":
{"votes":[
{"votes":32,"name":"mccain"},
{"votes":24,"name":"romney"},
{"votes":9,"name":"huckabee"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"paul"}],
"total":69,"precincts":
{"total":1,"reporting":1},
"name":"Waterville Valley"},
"Center Harbor":
{"votes":[
{"votes":125,"name":"mccain"},
{"votes":100,"name":"romney"},
{"votes":36,"name":"paul"},
{"votes":35,"name":"huckabee"},
{"votes":21,"name":"giuliani"},
{"votes":5,"name":"tancredo"},
{"votes":1,"name":"hunter"}],
"total":323,"precincts":
{"total":1,"reporting":1},
"name":"Center Harbor"},
"Sugar Hill":
{"votes":[
{"votes":66,"name":"mccain"},
{"votes":39,"name":"romney"},
{"votes":12,"name":"paul"},
{"votes":5,"name":"huckabee"},
{"votes":4,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":131,"precincts":
{"total":1,"reporting":1},
"name":"Sugar Hill"},
"Newton":
{"votes":[
{"votes":290,"name":"romney"},
{"votes":242,"name":"mccain"},
{"votes":82,"name":"huckabee"},
{"votes":65,"name":"giuliani"},
{"votes":55,"name":"paul"},
{"votes":12,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":752,"precincts":
{"total":1,"reporting":1},
"name":"Newton"},
"Rochester":
{"votes":[
{"votes":1498,"name":"mccain"},
{"votes":1123,"name":"romney"},
{"votes":712,"name":"huckabee"},
{"votes":379,"name":"giuliani"},
{"votes":348,"name":"paul"},
{"votes":87,"name":"thompson"},
{"votes":31,"name":"hunter"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"tancredo"}],
"total":4184,"precincts":
{"total":6,"reporting":6},
"name":"Rochester"},
"Campton":
{"votes":[
{"votes":252,"name":"mccain"},
{"votes":124,"name":"romney"},
{"votes":80,"name":"paul"},
{"votes":59,"name":"huckabee"},
{"votes":55,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":581,"precincts":
{"total":1,"reporting":1},
"name":"Campton"},
"Winchester":
{"votes":[
{"votes":173,"name":"mccain"},
{"votes":98,"name":"romney"},
{"votes":89,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":28,"name":"giuliani"},
{"votes":1,"name":"hunter"}],
"total":430,"precincts":
{"total":1,"reporting":1},
"name":"Winchester"},
"Washington":
{"votes":[
{"votes":97,"name":"mccain"},
{"votes":61,"name":"romney"},
{"votes":37,"name":"huckabee"},
{"votes":28,"name":"paul"},
{"votes":25,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":249,"precincts":
{"total":1,"reporting":1},
"name":"Washington"},
"Bridgewater":
{"votes":[
{"votes":124,"name":"mccain"},
{"votes":90,"name":"romney"},
{"votes":33,"name":"huckabee"},
{"votes":22,"name":"paul"},
{"votes":20,"name":"giuliani"},
{"votes":2,"name":"thompson"}],
"total":291,"precincts":
{"total":1,"reporting":1},
"name":"Bridgewater"},
"Wentworth's Location":
{"votes":[
{"votes":3,"name":"mccain"},
{"votes":2,"name":"romney"}],
"total":5,"precincts":
{"total":1,"reporting":1},
"name":"Wentworth's Location"},
"Bennington":
{"votes":[
{"votes":106,"name":"mccain"},
{"votes":70,"name":"romney"},
{"votes":37,"name":"huckabee"},
{"votes":37,"name":"giuliani"},
{"votes":35,"name":"paul"},
{"votes":3,"name":"hunter"},
{"votes":2,"name":"thompson"}],
"total":290,"precincts":
{"total":1,"reporting":1},
"name":"Bennington"},
"Mason":
{"votes":[
{"votes":136,"name":"romney"},
{"votes":109,"name":"mccain"},
{"votes":45,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":20,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":362,"precincts":
{"total":1,"reporting":1},
"name":"Mason"},
"Hillsborough":
{"votes":[
{"votes":354,"name":"mccain"},
{"votes":258,"name":"romney"},
{"votes":124,"name":"huckabee"},
{"votes":116,"name":"giuliani"},
{"votes":110,"name":"paul"},
{"votes":16,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":984,"precincts":
{"total":1,"reporting":1},
"name":"Hillsborough"},
"Unity":
{"votes":[
{"votes":81,"name":"mccain"},
{"votes":69,"name":"romney"},
{"votes":21,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":20,"name":"giuliani"}],
"total":212,"precincts":
{"total":1,"reporting":1},
"name":"Unity"},
"Jefferson":
{"votes":[
{"votes":135,"name":"mccain"},
{"votes":45,"name":"huckabee"},
{"votes":36,"name":"romney"},
{"votes":26,"name":"giuliani"},
{"votes":22,"name":"paul"},
{"votes":5,"name":"thompson"}],
"total":269,"precincts":
{"total":1,"reporting":1},
"name":"Jefferson"},
"Orange":
{"votes":[
{"votes":18,"name":"mccain"},
{"votes":12,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":5,"name":"giuliani"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"thompson"}],
"total":49,"precincts":
{"total":1,"reporting":1},
"name":"Orange"},
"Bath":
{"votes":[
{"votes":99,"name":"mccain"},
{"votes":44,"name":"huckabee"},
{"votes":29,"name":"romney"},
{"votes":24,"name":"giuliani"},
{"votes":20,"name":"paul"},
{"votes":6,"name":"thompson"}],
"total":222,"precincts":
{"total":1,"reporting":1},
"name":"Bath"},
"Canaan":
{"votes":[
{"votes":222,"name":"mccain"},
{"votes":105,"name":"romney"},
{"votes":89,"name":"paul"},
{"votes":59,"name":"huckabee"},
{"votes":44,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":536,"precincts":
{"total":1,"reporting":1},
"name":"Canaan"},
"Grantham":
{"votes":[
{"votes":299,"name":"mccain"},
{"votes":199,"name":"romney"},
{"votes":53,"name":"giuliani"},
{"votes":46,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":645,"precincts":
{"total":1,"reporting":1},
"name":"Grantham"},
"Lee":
{"votes":[
{"votes":269,"name":"mccain"},
{"votes":218,"name":"romney"},
{"votes":86,"name":"huckabee"},
{"votes":63,"name":"giuliani"},
{"votes":55,"name":"paul"},
{"votes":14,"name":"thompson"}],
"total":705,"precincts":
{"total":1,"reporting":1},
"name":"Lee"},
"Pittsfield":
{"votes":[
{"votes":226,"name":"mccain"},
{"votes":186,"name":"romney"},
{"votes":138,"name":"huckabee"},
{"votes":81,"name":"giuliani"},
{"votes":70,"name":"paul"},
{"votes":8,"name":"hunter"},
{"votes":4,"name":"thompson"}],
"total":713,"precincts":
{"total":1,"reporting":1},
"name":"Pittsfield"},
"Wolfeboro":
{"votes":[
{"votes":789,"name":"romney"},
{"votes":675,"name":"mccain"},
{"votes":161,"name":"huckabee"},
{"votes":149,"name":"giuliani"},
{"votes":116,"name":"paul"},
{"votes":19,"name":"thompson"},
{"votes":5,"name":"keyes"},
{"votes":2,"name":"hunter"}],
"total":1916,"precincts":
{"total":1,"reporting":1},
"name":"Wolfeboro"},
"Claremont":
{"votes":[
{"votes":593,"name":"mccain"},
{"votes":398,"name":"romney"},
{"votes":309,"name":"huckabee"},
{"votes":120,"name":"paul"},
{"votes":113,"name":"giuliani"},
{"votes":22,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1564,"precincts":
{"total":3,"reporting":3},
"name":"Claremont"},
"Haverhill":
{"votes":[
{"votes":405,"name":"mccain"},
{"votes":130,"name":"huckabee"},
{"votes":120,"name":"paul"},
{"votes":89,"name":"romney"},
{"votes":40,"name":"giuliani"},
{"votes":15,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":805,"precincts":
{"total":1,"reporting":1},
"name":"Haverhill"},
"Troy":
{"votes":[
{"votes":110,"name":"mccain"},
{"votes":67,"name":"romney"},
{"votes":58,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":25,"name":"giuliani"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"thompson"}],
"total":302,"precincts":
{"total":1,"reporting":1},
"name":"Troy"},
"Stoddard":
{"votes":[
{"votes":78,"name":"romney"},
{"votes":63,"name":"mccain"},
{"votes":32,"name":"huckabee"},
{"votes":18,"name":"giuliani"},
{"votes":12,"name":"paul"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":206,"precincts":
{"total":1,"reporting":1},
"name":"Stoddard"},
"Berlin":
{"votes":[
{"votes":333,"name":"mccain"},
{"votes":204,"name":"romney"},
{"votes":176,"name":"huckabee"},
{"votes":95,"name":"paul"},
{"votes":71,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":894,"precincts":
{"total":4,"reporting":4},
"name":"Berlin"},
"Weare":
{"votes":[
{"votes":662,"name":"mccain"},
{"votes":574,"name":"romney"},
{"votes":258,"name":"huckabee"},
{"votes":187,"name":"giuliani"},
{"votes":172,"name":"paul"},
{"votes":22,"name":"thompson"},
{"votes":14,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1891,"precincts":
{"total":1,"reporting":1},
"name":"Weare"},
"Deering":
{"votes":[
{"votes":122,"name":"mccain"},
{"votes":98,"name":"romney"},
{"votes":47,"name":"huckabee"},
{"votes":38,"name":"giuliani"},
{"votes":32,"name":"paul"},
{"votes":7,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":346,"precincts":
{"total":1,"reporting":1},
"name":"Deering"},
"Sandown":
{"votes":[
{"votes":469,"name":"romney"},
{"votes":338,"name":"mccain"},
{"votes":126,"name":"giuliani"},
{"votes":124,"name":"huckabee"},
{"votes":89,"name":"paul"},
{"votes":10,"name":"hunter"},
{"votes":4,"name":"keyes"},
{"votes":3,"name":"thompson"}],
"total":1163,"precincts":
{"total":1,"reporting":1},
"name":"Sandown"},
"Chatham":
{"votes":[
{"votes":29,"name":"mccain"},
{"votes":28,"name":"romney"},
{"votes":11,"name":"huckabee"},
{"votes":5,"name":"giuliani"},
{"votes":5,"name":"paul"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":81,"precincts":
{"total":1,"reporting":1},
"name":"Chatham"},
"Hart's Location":
{"votes":[
{"votes":6,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":4,"name":"paul"},
{"votes":1,"name":"romney"}],
"total":16,"precincts":
{"total":1,"reporting":1},
"name":"Hart's Location"},
"Bethlehem":
{"votes":[
{"votes":222,"name":"mccain"},
{"votes":57,"name":"giuliani"},
{"votes":53,"name":"huckabee"},
{"votes":44,"name":"romney"},
{"votes":42,"name":"paul"},
{"votes":9,"name":"thompson"}],
"total":427,"precincts":
{"total":1,"reporting":1},
"name":"Bethlehem"},
"South Hampton":
{"votes":[
{"votes":68,"name":"romney"},
{"votes":64,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":10,"name":"giuliani"},
{"votes":8,"name":"huckabee"},
{"votes":2,"name":"thompson"}],
"total":173,"precincts":
{"total":1,"reporting":1},
"name":"South Hampton"},
"Freedom":
{"votes":[
{"votes":155,"name":"mccain"},
{"votes":129,"name":"romney"},
{"votes":36,"name":"huckabee"},
{"votes":25,"name":"giuliani"},
{"votes":14,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":367,"precincts":
{"total":1,"reporting":1},
"name":"Freedom"},
"Northumberland":
{"votes":[
{"votes":116,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":37,"name":"romney"},
{"votes":27,"name":"paul"},
{"votes":25,"name":"giuliani"},
{"votes":2,"name":"thompson"}],
"total":255,"precincts":
{"total":1,"reporting":1},
"name":"Northumberland"},
"North Hampton":
{"votes":[
{"votes":470,"name":"mccain"},
{"votes":416,"name":"romney"},
{"votes":90,"name":"giuliani"},
{"votes":77,"name":"huckabee"},
{"votes":53,"name":"paul"},
{"votes":19,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":1127,"precincts":
{"total":1,"reporting":1},
"name":"North Hampton"},
"Seabrook":
{"votes":[
{"votes":460,"name":"mccain"},
{"votes":437,"name":"romney"},
{"votes":129,"name":"huckabee"},
{"votes":106,"name":"giuliani"},
{"votes":75,"name":"paul"},
{"votes":10,"name":"thompson"},
{"votes":8,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1227,"precincts":
{"total":1,"reporting":1},
"name":"Seabrook"},
"Bow":
{"votes":[
{"votes":828,"name":"mccain"},
{"votes":684,"name":"romney"},
{"votes":231,"name":"huckabee"},
{"votes":176,"name":"giuliani"},
{"votes":127,"name":"paul"},
{"votes":28,"name":"thompson"},
{"votes":8,"name":"hunter"}],
"total":2082,"precincts":
{"total":1,"reporting":1},
"name":"Bow"},
"Moultonborough":
{"votes":[
{"votes":520,"name":"mccain"},
{"votes":460,"name":"romney"},
{"votes":104,"name":"giuliani"},
{"votes":101,"name":"paul"},
{"votes":99,"name":"huckabee"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":1298,"precincts":
{"total":1,"reporting":1},
"name":"Moultonborough"},
"Windham":
{"votes":[
{"votes":1514,"name":"romney"},
{"votes":1065,"name":"mccain"},
{"votes":266,"name":"giuliani"},
{"votes":233,"name":"huckabee"},
{"votes":148,"name":"paul"},
{"votes":28,"name":"thompson"},
{"votes":8,"name":"hunter"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"tancredo"}],
"total":3268,"precincts":
{"total":1,"reporting":1},
"name":"Windham"},
"Chester":
{"votes":[
{"votes":439,"name":"romney"},
{"votes":353,"name":"mccain"},
{"votes":167,"name":"huckabee"},
{"votes":97,"name":"paul"},
{"votes":95,"name":"giuliani"},
{"votes":16,"name":"hunter"},
{"votes":16,"name":"thompson"},
{"votes":1,"name":"tancredo"}],
"total":1184,"precincts":
{"total":1,"reporting":1},
"name":"Chester"},
"East Kingston":
{"votes":[
{"votes":236,"name":"mccain"},
{"votes":224,"name":"romney"},
{"votes":54,"name":"paul"},
{"votes":46,"name":"huckabee"},
{"votes":43,"name":"giuliani"},
{"votes":7,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":613,"precincts":
{"total":1,"reporting":1},
"name":"East Kingston"},
"Hinsdale":
{"votes":[
{"votes":144,"name":"mccain"},
{"votes":68,"name":"huckabee"},
{"votes":56,"name":"romney"},
{"votes":40,"name":"giuliani"},
{"votes":31,"name":"paul"},
{"votes":5,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":346,"precincts":
{"total":1,"reporting":1},
"name":"Hinsdale"},
"Sunapee":
{"votes":[
{"votes":364,"name":"mccain"},
{"votes":241,"name":"romney"},
{"votes":79,"name":"giuliani"},
{"votes":75,"name":"huckabee"},
{"votes":34,"name":"paul"},
{"votes":7,"name":"thompson"},
{"votes":4,"name":"hunter"}],
"total":804,"precincts":
{"total":1,"reporting":1},
"name":"Sunapee"},
"Landaff":
{"votes":[
{"votes":45,"name":"mccain"},
{"votes":19,"name":"romney"},
{"votes":12,"name":"huckabee"},
{"votes":8,"name":"giuliani"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"thompson"}],
"total":89,"precincts":
{"total":1,"reporting":1},
"name":"Landaff"},
"Pelham":
{"votes":[
{"votes":1006,"name":"romney"},
{"votes":885,"name":"mccain"},
{"votes":195,"name":"huckabee"},
{"votes":195,"name":"giuliani"},
{"votes":139,"name":"paul"},
{"votes":32,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":2458,"precincts":
{"total":1,"reporting":1},
"name":"Pelham"},
"Warner":
{"votes":[
{"votes":218,"name":"mccain"},
{"votes":160,"name":"romney"},
{"votes":67,"name":"paul"},
{"votes":63,"name":"huckabee"},
{"votes":60,"name":"giuliani"},
{"votes":6,"name":"hunter"},
{"votes":6,"name":"thompson"},
{"votes":2,"name":"keyes"}],
"total":582,"precincts":
{"total":1,"reporting":1},
"name":"Warner"},
"Newington":
{"votes":[
{"votes":101,"name":"mccain"},
{"votes":75,"name":"romney"},
{"votes":32,"name":"giuliani"},
{"votes":17,"name":"paul"},
{"votes":15,"name":"huckabee"},
{"votes":5,"name":"thompson"}],
"total":245,"precincts":
{"total":1,"reporting":1},
"name":"Newington"},
"Madison":
{"votes":[
{"votes":223,"name":"mccain"},
{"votes":113,"name":"romney"},
{"votes":52,"name":"paul"},
{"votes":40,"name":"huckabee"},
{"votes":20,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":462,"precincts":
{"total":1,"reporting":1},
"name":"Madison"},
"Portsmouth":
{"votes":[
{"votes":1219,"name":"mccain"},
{"votes":728,"name":"romney"},
{"votes":325,"name":"giuliani"},
{"votes":221,"name":"paul"},
{"votes":196,"name":"huckabee"},
{"votes":26,"name":"thompson"},
{"votes":10,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":2728,"precincts":
{"total":5,"reporting":5},
"name":"Portsmouth"},
"Chichester":
{"votes":[
{"votes":251,"name":"mccain"},
{"votes":170,"name":"romney"},
{"votes":99,"name":"huckabee"},
{"votes":53,"name":"paul"},
{"votes":45,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":5,"name":"thompson"}],
"total":630,"precincts":
{"total":1,"reporting":1},
"name":"Chichester"},
"Londonderry":
{"votes":[
{"votes":1989,"name":"romney"},
{"votes":1757,"name":"mccain"},
{"votes":544,"name":"huckabee"},
{"votes":418,"name":"giuliani"},
{"votes":288,"name":"paul"},
{"votes":52,"name":"thompson"},
{"votes":19,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":5069,"precincts":
{"total":1,"reporting":1},
"name":"Londonderry"},
"Langdon":
{"votes":[
{"votes":57,"name":"mccain"},
{"votes":32,"name":"romney"},
{"votes":30,"name":"hunter"},
{"votes":11,"name":"paul"},
{"votes":10,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"keyes"}],
"total":147,"precincts":
{"total":1,"reporting":1},
"name":"Langdon"},
"Epping":
{"votes":[
{"votes":362,"name":"mccain"},
{"votes":324,"name":"romney"},
{"votes":152,"name":"huckabee"},
{"votes":89,"name":"paul"},
{"votes":81,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":9,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1028,"precincts":
{"total":1,"reporting":1},
"name":"Epping"},
"Windsor":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Windsor"},
"Dorchester":
{"votes":[
{"votes":29,"name":"mccain"},
{"votes":16,"name":"huckabee"},
{"votes":12,"name":"romney"},
{"votes":10,"name":"paul"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"thompson"}],
"total":72,"precincts":
{"total":1,"reporting":1},
"name":"Dorchester"},
"Middleton":
{"votes":[
{"votes":97,"name":"mccain"},
{"votes":62,"name":"huckabee"},
{"votes":61,"name":"romney"},
{"votes":25,"name":"paul"},
{"votes":14,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":3,"name":"thompson"}],
"total":269,"precincts":
{"total":1,"reporting":1},
"name":"Middleton"},
"Stratford":
{"votes":[
{"votes":24,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":10,"name":"romney"},
{"votes":5,"name":"giuliani"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"thompson"}],
"total":56,"precincts":
{"total":1,"reporting":1},
"name":"Stratford"},
"Amherst":
{"votes":[
{"votes":1250,"name":"mccain"},
{"votes":1140,"name":"romney"},
{"votes":287,"name":"giuliani"},
{"votes":257,"name":"huckabee"},
{"votes":197,"name":"paul"},
{"votes":34,"name":"thompson"},
{"votes":10,"name":"hunter"},
{"votes":5,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":3181,"precincts":
{"total":1,"reporting":1},
"name":"Amherst"},
"Warren":
{"votes":[
{"votes":81,"name":"mccain"},
{"votes":28,"name":"romney"},
{"votes":24,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":15,"name":"giuliani"},
{"votes":3,"name":"hunter"}],
"total":170,"precincts":
{"total":1,"reporting":1},
"name":"Warren"},
"Dummer":
{"votes":[
{"votes":19,"name":"huckabee"},
{"votes":17,"name":"mccain"},
{"votes":12,"name":"romney"},
{"votes":8,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"hunter"}],
"total":62,"precincts":
{"total":1,"reporting":1},
"name":"Dummer"},
"Westmoreland":
{"votes":[
{"votes":138,"name":"mccain"},
{"votes":95,"name":"romney"},
{"votes":45,"name":"huckabee"},
{"votes":22,"name":"giuliani"},
{"votes":14,"name":"paul"},
{"votes":4,"name":"tancredo"},
{"votes":3,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":323,"precincts":
{"total":1,"reporting":1},
"name":"Westmoreland"},
"Lancaster":
{"votes":[
{"votes":276,"name":"mccain"},
{"votes":102,"name":"romney"},
{"votes":83,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":55,"name":"giuliani"},
{"votes":7,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":594,"precincts":
{"total":1,"reporting":1},
"name":"Lancaster"},
"Springfield":
{"votes":[
{"votes":122,"name":"mccain"},
{"votes":74,"name":"romney"},
{"votes":30,"name":"paul"},
{"votes":27,"name":"giuliani"},
{"votes":19,"name":"huckabee"},
{"votes":4,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":278,"precincts":
{"total":1,"reporting":1},
"name":"Springfield"},
"Derry":
{"votes":[
{"votes":2093,"name":"romney"},
{"votes":1760,"name":"mccain"},
{"votes":531,"name":"huckabee"},
{"votes":412,"name":"paul"},
{"votes":376,"name":"giuliani"},
{"votes":74,"name":"thompson"},
{"votes":33,"name":"hunter"},
{"votes":5,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":5285,"precincts":
{"total":1,"reporting":1},
"name":"Derry"},
"Lyndeborough":
{"votes":[
{"votes":158,"name":"mccain"},
{"votes":139,"name":"romney"},
{"votes":43,"name":"huckabee"},
{"votes":41,"name":"giuliani"},
{"votes":34,"name":"paul"},
{"votes":6,"name":"thompson"}],
"total":421,"precincts":
{"total":1,"reporting":1},
"name":"Lyndeborough"},
"Thornton":
{"votes":[
{"votes":235,"name":"mccain"},
{"votes":88,"name":"romney"},
{"votes":53,"name":"huckabee"},
{"votes":34,"name":"paul"},
{"votes":31,"name":"giuliani"},
{"votes":2,"name":"thompson"}],
"total":443,"precincts":
{"total":1,"reporting":1},
"name":"Thornton"},
"New Durham":
{"votes":[
{"votes":194,"name":"mccain"},
{"votes":164,"name":"romney"},
{"votes":92,"name":"huckabee"},
{"votes":71,"name":"giuliani"},
{"votes":64,"name":"paul"},
{"votes":12,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":601,"precincts":
{"total":1,"reporting":1},
"name":"New Durham"},
"Stark":
{"votes":[
{"votes":34,"name":"mccain"},
{"votes":22,"name":"huckabee"},
{"votes":21,"name":"romney"},
{"votes":10,"name":"giuliani"},
{"votes":7,"name":"paul"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":98,"precincts":
{"total":1,"reporting":1},
"name":"Stark"},
"Richmond":
{"votes":[
{"votes":89,"name":"paul"},
{"votes":52,"name":"romney"},
{"votes":50,"name":"mccain"},
{"votes":36,"name":"huckabee"},
{"votes":11,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":248,"precincts":
{"total":1,"reporting":1},
"name":"Richmond"},
"Plaistow":
{"votes":[
{"votes":641,"name":"romney"},
{"votes":482,"name":"mccain"},
{"votes":124,"name":"giuliani"},
{"votes":99,"name":"paul"},
{"votes":97,"name":"huckabee"},
{"votes":15,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":1466,"precincts":
{"total":1,"reporting":1},
"name":"Plaistow"},
"Piermont":
{"votes":[
{"votes":56,"name":"mccain"},
{"votes":26,"name":"huckabee"},
{"votes":25,"name":"romney"},
{"votes":12,"name":"paul"},
{"votes":10,"name":"giuliani"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"thompson"}],
"total":135,"precincts":
{"total":1,"reporting":1},
"name":"Piermont"},
"Mont Vernon":
{"votes":[
{"votes":239,"name":"mccain"},
{"votes":107,"name":"romney"},
{"votes":80,"name":"huckabee"},
{"votes":54,"name":"paul"},
{"votes":31,"name":"giuliani"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":517,"precincts":
{"total":1,"reporting":1},
"name":"Mont Vernon"},
"Jackson":
{"votes":[
{"votes":103,"name":"mccain"},
{"votes":81,"name":"romney"},
{"votes":15,"name":"giuliani"},
{"votes":13,"name":"huckabee"},
{"votes":7,"name":"paul"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"tancredo"}],
"total":222,"precincts":
{"total":1,"reporting":1},
"name":"Jackson"},
"Orford":
{"votes":[
{"votes":89,"name":"mccain"},
{"votes":45,"name":"romney"},
{"votes":30,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":10,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":202,"precincts":
{"total":1,"reporting":1},
"name":"Orford"},
"Rollinsford":
{"votes":[
{"votes":172,"name":"mccain"},
{"votes":120,"name":"romney"},
{"votes":65,"name":"huckabee"},
{"votes":39,"name":"giuliani"},
{"votes":34,"name":"paul"},
{"votes":16,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":448,"precincts":
{"total":1,"reporting":1},
"name":"Rollinsford"},
"Temple":
{"votes":[
{"votes":124,"name":"mccain"},
{"votes":108,"name":"romney"},
{"votes":36,"name":"huckabee"},
{"votes":22,"name":"giuliani"},
{"votes":15,"name":"paul"},
{"votes":7,"name":"thompson"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":314,"precincts":
{"total":1,"reporting":1},
"name":"Temple"},
"Acworth":
{"votes":[
{"votes":79,"name":"mccain"},
{"votes":34,"name":"romney"},
{"votes":23,"name":"huckabee"},
{"votes":13,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"thompson"}],
"total":163,"precincts":
{"total":1,"reporting":1},
"name":"Acworth"},
"Stratham":
{"votes":[
{"votes":690,"name":"mccain"},
{"votes":608,"name":"romney"},
{"votes":255,"name":"giuliani"},
{"votes":79,"name":"huckabee"},
{"votes":76,"name":"paul"},
{"votes":16,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1732,"precincts":
{"total":1,"reporting":1},
"name":"Stratham"},
"Deerfield":
{"votes":[
{"votes":354,"name":"mccain"},
{"votes":328,"name":"romney"},
{"votes":145,"name":"huckabee"},
{"votes":118,"name":"giuliani"},
{"votes":88,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":5,"name":"hunter"}],
"total":1049,"precincts":
{"total":1,"reporting":1},
"name":"Deerfield"},
"Danbury":
{"votes":[
{"votes":88,"name":"mccain"},
{"votes":63,"name":"romney"},
{"votes":28,"name":"huckabee"},
{"votes":23,"name":"paul"},
{"votes":17,"name":"giuliani"},
{"votes":8,"name":"thompson"},
{"votes":4,"name":"hunter"}],
"total":231,"precincts":
{"total":1,"reporting":1},
"name":"Danbury"},
"Stewartstown":
{"votes":[
{"votes":53,"name":"mccain"},
{"votes":18,"name":"romney"},
{"votes":17,"name":"paul"},
{"votes":15,"name":"huckabee"},
{"votes":5,"name":"thompson"},
{"votes":4,"name":"keyes"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"hunter"}],
"total":117,"precincts":
{"total":1,"reporting":1},
"name":"Stewartstown"},
"Somersworth":
{"votes":[
{"votes":427,"name":"mccain"},
{"votes":322,"name":"romney"},
{"votes":197,"name":"huckabee"},
{"votes":118,"name":"paul"},
{"votes":111,"name":"giuliani"},
{"votes":36,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"tancredo"}],
"total":1217,"precincts":
{"total":5,"reporting":5},
"name":"Somersworth"},
"Tamworth":
{"votes":[
{"votes":225,"name":"mccain"},
{"votes":123,"name":"romney"},
{"votes":52,"name":"huckabee"},
{"votes":50,"name":"paul"},
{"votes":28,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":492,"precincts":
{"total":1,"reporting":1},
"name":"Tamworth"},
"Gilmanton":
{"votes":[
{"votes":300,"name":"mccain"},
{"votes":236,"name":"romney"},
{"votes":111,"name":"huckabee"},
{"votes":84,"name":"paul"},
{"votes":76,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":823,"precincts":
{"total":1,"reporting":1},
"name":"Gilmanton"},
"Northwood":
{"votes":[
{"votes":283,"name":"mccain"},
{"votes":224,"name":"romney"},
{"votes":128,"name":"huckabee"},
{"votes":79,"name":"giuliani"},
{"votes":60,"name":"paul"},
{"votes":13,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":788,"precincts":
{"total":1,"reporting":1},
"name":"Northwood"},
"Farmington":
{"votes":[
{"votes":263,"name":"mccain"},
{"votes":200,"name":"romney"},
{"votes":168,"name":"huckabee"},
{"votes":75,"name":"giuliani"},
{"votes":72,"name":"paul"},
{"votes":14,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":801,"precincts":
{"total":1,"reporting":1},
"name":"Farmington"},
"Littleton":
{"votes":[
{"votes":460,"name":"mccain"},
{"votes":202,"name":"romney"},
{"votes":200,"name":"huckabee"},
{"votes":79,"name":"giuliani"},
{"votes":79,"name":"paul"},
{"votes":13,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1035,"precincts":
{"total":1,"reporting":1},
"name":"Littleton"},
"Wilton":
{"votes":[
{"votes":283,"name":"mccain"},
{"votes":245,"name":"romney"},
{"votes":99,"name":"huckabee"},
{"votes":81,"name":"paul"},
{"votes":56,"name":"giuliani"},
{"votes":9,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":779,"precincts":
{"total":1,"reporting":1},
"name":"Wilton"},
"Bartlett":
{"votes":[
{"votes":256,"name":"mccain"},
{"votes":182,"name":"romney"},
{"votes":54,"name":"paul"},
{"votes":47,"name":"giuliani"},
{"votes":42,"name":"huckabee"},
{"votes":11,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":594,"precincts":
{"total":1,"reporting":1},
"name":"Bartlett"},
"Colebrook":
{"votes":[
{"votes":178,"name":"mccain"},
{"votes":67,"name":"romney"},
{"votes":59,"name":"huckabee"},
{"votes":35,"name":"paul"},
{"votes":29,"name":"giuliani"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":372,"precincts":
{"total":1,"reporting":1},
"name":"Colebrook"},
"Dover":
{"votes":[
{"votes":1779,"name":"mccain"},
{"votes":1102,"name":"romney"},
{"votes":458,"name":"huckabee"},
{"votes":388,"name":"giuliani"},
{"votes":369,"name":"paul"},
{"votes":59,"name":"thompson"},
{"votes":16,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":2,"name":"keyes"}],
"total":4175,"precincts":
{"total":6,"reporting":6},
"name":"Dover"},
"Dunbarton":
{"votes":[
{"votes":302,"name":"mccain"},
{"votes":243,"name":"romney"},
{"votes":98,"name":"huckabee"},
{"votes":70,"name":"giuliani"},
{"votes":49,"name":"paul"},
{"votes":2,"name":"hunter"}],
"total":764,"precincts":
{"total":1,"reporting":1},
"name":"Dunbarton"},
"Bradford":
{"votes":[
{"votes":117,"name":"mccain"},
{"votes":111,"name":"romney"},
{"votes":56,"name":"huckabee"},
{"votes":46,"name":"giuliani"},
{"votes":25,"name":"paul"},
{"votes":5,"name":"hunter"},
{"votes":3,"name":"thompson"}],
"total":363,"precincts":
{"total":1,"reporting":1},
"name":"Bradford"},
"Sutton":
{"votes":[
{"votes":160,"name":"mccain"},
{"votes":119,"name":"romney"},
{"votes":51,"name":"giuliani"},
{"votes":45,"name":"huckabee"},
{"votes":31,"name":"paul"},
{"votes":3,"name":"thompson"}],
"total":409,"precincts":
{"total":1,"reporting":1},
"name":"Sutton"},
"Lincoln":
{"votes":[
{"votes":145,"name":"mccain"},
{"votes":56,"name":"romney"},
{"votes":23,"name":"huckabee"},
{"votes":23,"name":"giuliani"},
{"votes":10,"name":"paul"},
{"votes":4,"name":"keyes"},
{"votes":1,"name":"thompson"}],
"total":262,"precincts":
{"total":1,"reporting":1},
"name":"Lincoln"},
"Hudson":
{"votes":[
{"votes":1518,"name":"romney"},
{"votes":1395,"name":"mccain"},
{"votes":454,"name":"huckabee"},
{"votes":326,"name":"giuliani"},
{"votes":307,"name":"paul"},
{"votes":57,"name":"thompson"},
{"votes":21,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":4080,"precincts":
{"total":1,"reporting":1},
"name":"Hudson"},
"Roxbury":
{"votes":[
{"votes":17,"name":"mccain"},
{"votes":6,"name":"romney"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"giuliani"},
{"votes":2,"name":"paul"}],
"total":31,"precincts":
{"total":1,"reporting":1},
"name":"Roxbury"},
"Litchfield":
{"votes":[
{"votes":717,"name":"romney"},
{"votes":583,"name":"mccain"},
{"votes":176,"name":"huckabee"},
{"votes":158,"name":"giuliani"},
{"votes":102,"name":"paul"},
{"votes":21,"name":"thompson"},
{"votes":15,"name":"hunter"}],
"total":1772,"precincts":
{"total":1,"reporting":1},
"name":"Litchfield"},
"Errol":
{"votes":[
{"votes":32,"name":"romney"},
{"votes":25,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":4,"name":"paul"},
{"votes":3,"name":"giuliani"}],
"total":71,"precincts":
{"total":1,"reporting":1},
"name":"Errol"},
"Laconia":
{"votes":[
{"votes":1124,"name":"mccain"},
{"votes":951,"name":"romney"},
{"votes":312,"name":"huckabee"},
{"votes":259,"name":"giuliani"},
{"votes":196,"name":"paul"},
{"votes":40,"name":"thompson"},
{"votes":11,"name":"hunter"}],
"total":2893,"precincts":
{"total":6,"reporting":6},
"name":"Laconia"},
"Marlow":
{"votes":[
{"votes":53,"name":"mccain"},
{"votes":28,"name":"romney"},
{"votes":23,"name":"paul"},
{"votes":17,"name":"huckabee"},
{"votes":12,"name":"giuliani"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":137,"precincts":
{"total":1,"reporting":1},
"name":"Marlow"},
"Wilmot":
{"votes":[
{"votes":124,"name":"mccain"},
{"votes":75,"name":"romney"},
{"votes":34,"name":"giuliani"},
{"votes":27,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":280,"precincts":
{"total":1,"reporting":1},
"name":"Wilmot"},
"New Hampton":
{"votes":[
{"votes":185,"name":"mccain"},
{"votes":131,"name":"romney"},
{"votes":64,"name":"huckabee"},
{"votes":50,"name":"paul"},
{"votes":45,"name":"giuliani"},
{"votes":9,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":489,"precincts":
{"total":1,"reporting":1},
"name":"New Hampton"},
"Franklin":
{"votes":[
{"votes":471,"name":"mccain"},
{"votes":300,"name":"romney"},
{"votes":187,"name":"huckabee"},
{"votes":108,"name":"giuliani"},
{"votes":95,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":6,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1184,"precincts":
{"total":3,"reporting":3},
"name":"Franklin"},
"Tuftonboro":
{"votes":[
{"votes":318,"name":"romney"},
{"votes":273,"name":"mccain"},
{"votes":58,"name":"huckabee"},
{"votes":52,"name":"giuliani"},
{"votes":48,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":759,"precincts":
{"total":1,"reporting":1},
"name":"Tuftonboro"},
"Lempster":
{"votes":[
{"votes":79,"name":"mccain"},
{"votes":51,"name":"romney"},
{"votes":39,"name":"huckabee"},
{"votes":19,"name":"giuliani"},
{"votes":18,"name":"paul"},
{"votes":3,"name":"thompson"}],
"total":209,"precincts":
{"total":1,"reporting":1},
"name":"Lempster"},
"Greenfield":
{"votes":[
{"votes":130,"name":"mccain"},
{"votes":117,"name":"romney"},
{"votes":38,"name":"huckabee"},
{"votes":30,"name":"paul"},
{"votes":26,"name":"giuliani"},
{"votes":8,"name":"thompson"}],
"total":349,"precincts":
{"total":1,"reporting":1},
"name":"Greenfield"},
"Conway":
{"votes":[
{"votes":571,"name":"mccain"},
{"votes":329,"name":"romney"},
{"votes":189,"name":"huckabee"},
{"votes":123,"name":"paul"},
{"votes":76,"name":"giuliani"},
{"votes":25,"name":"thompson"},
{"votes":4,"name":"hunter"}],
"total":1317,"precincts":
{"total":1,"reporting":1},
"name":"Conway"},
"Pittsburg":
{"votes":[
{"votes":95,"name":"mccain"},
{"votes":40,"name":"romney"},
{"votes":22,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":15,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":202,"precincts":
{"total":1,"reporting":1},
"name":"Pittsburg"},
"Lebanon":
{"votes":[
{"votes":726,"name":"mccain"},
{"votes":391,"name":"romney"},
{"votes":212,"name":"huckabee"},
{"votes":137,"name":"paul"},
{"votes":122,"name":"giuliani"},
{"votes":34,"name":"thompson"},
{"votes":6,"name":"hunter"}],
"total":1628,"precincts":
{"total":3,"reporting":3},
"name":"Lebanon"},
"Auburn":
{"votes":[
{"votes":507,"name":"mccain"},
{"votes":479,"name":"romney"},
{"votes":158,"name":"huckabee"},
{"votes":139,"name":"giuliani"},
{"votes":103,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":12,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":2,"name":"keyes"}],
"total":1417,"precincts":
{"total":1,"reporting":1},
"name":"Auburn"},
"Hebron":
{"votes":[
{"votes":99,"name":"mccain"},
{"votes":45,"name":"romney"},
{"votes":17,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":16,"name":"giuliani"},
{"votes":6,"name":"thompson"}],
"total":200,"precincts":
{"total":1,"reporting":1},
"name":"Hebron"},
"Croydon":
{"votes":[
{"votes":76,"name":"mccain"},
{"votes":40,"name":"romney"},
{"votes":23,"name":"paul"},
{"votes":13,"name":"huckabee"},
{"votes":8,"name":"giuliani"},
{"votes":1,"name":"thompson"}],
"total":161,"precincts":
{"total":1,"reporting":1},
"name":"Croydon"},
"Salem":
{"votes":[
{"votes":2245,"name":"romney"},
{"votes":1566,"name":"mccain"},
{"votes":416,"name":"giuliani"},
{"votes":402,"name":"huckabee"},
{"votes":270,"name":"paul"},
{"votes":34,"name":"thompson"},
{"votes":17,"name":"hunter"},
{"votes":9,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":4960,"precincts":
{"total":1,"reporting":1},
"name":"Salem"},
"New Ipswich":
{"votes":[
{"votes":432,"name":"romney"},
{"votes":257,"name":"huckabee"},
{"votes":256,"name":"mccain"},
{"votes":170,"name":"paul"},
{"votes":50,"name":"giuliani"},
{"votes":11,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1184,"precincts":
{"total":1,"reporting":1},
"name":"New Ipswich"},
"Barnstead":
{"votes":[
{"votes":270,"name":"mccain"},
{"votes":239,"name":"romney"},
{"votes":130,"name":"huckabee"},
{"votes":80,"name":"paul"},
{"votes":70,"name":"giuliani"},
{"votes":15,"name":"hunter"},
{"votes":13,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":818,"precincts":
{"total":1,"reporting":1},
"name":"Barnstead"},
"Sharon":
{"votes":[
{"votes":30,"name":"romney"},
{"votes":29,"name":"mccain"},
{"votes":14,"name":"huckabee"},
{"votes":8,"name":"paul"},
{"votes":4,"name":"giuliani"}],
"total":85,"precincts":
{"total":1,"reporting":1},
"name":"Sharon"},
"New Boston":
{"votes":[
{"votes":495,"name":"romney"},
{"votes":424,"name":"mccain"},
{"votes":141,"name":"huckabee"},
{"votes":124,"name":"giuliani"},
{"votes":90,"name":"paul"},
{"votes":21,"name":"thompson"},
{"votes":6,"name":"hunter"}],
"total":1301,"precincts":
{"total":1,"reporting":1},
"name":"New Boston"},
"New Castle":
{"votes":[
{"votes":188,"name":"mccain"},
{"votes":97,"name":"romney"},
{"votes":38,"name":"giuliani"},
{"votes":21,"name":"huckabee"},
{"votes":9,"name":"paul"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":355,"precincts":
{"total":1,"reporting":1},
"name":"New Castle"},
"Strafford":
{"votes":[
{"votes":308,"name":"mccain"},
{"votes":200,"name":"romney"},
{"votes":138,"name":"huckabee"},
{"votes":96,"name":"paul"},
{"votes":88,"name":"giuliani"},
{"votes":14,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":850,"precincts":
{"total":1,"reporting":1},
"name":"Strafford"},
"Alstead":
{"votes":[
{"votes":104,"name":"mccain"},
{"votes":58,"name":"romney"},
{"votes":37,"name":"huckabee"},
{"votes":31,"name":"giuliani"},
{"votes":19,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":3,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":257,"precincts":
{"total":1,"reporting":1},
"name":"Alstead"},
"Hopkinton":
{"votes":[
{"votes":616,"name":"mccain"},
{"votes":365,"name":"romney"},
{"votes":140,"name":"huckabee"},
{"votes":103,"name":"giuliani"},
{"votes":80,"name":"paul"},
{"votes":17,"name":"thompson"},
{"votes":10,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1333,"precincts":
{"total":1,"reporting":1},
"name":"Hopkinton"},
"Rye":
{"votes":[
{"votes":637,"name":"mccain"},
{"votes":503,"name":"romney"},
{"votes":124,"name":"giuliani"},
{"votes":97,"name":"huckabee"},
{"votes":67,"name":"paul"},
{"votes":13,"name":"thompson"},
{"votes":5,"name":"hunter"}],
"total":1446,"precincts":
{"total":1,"reporting":1},
"name":"Rye"},
"Merrimack":
{"votes":[
{"votes":2075,"name":"romney"},
{"votes":2046,"name":"mccain"},
{"votes":561,"name":"huckabee"},
{"votes":524,"name":"giuliani"},
{"votes":385,"name":"paul"},
{"votes":71,"name":"thompson"},
{"votes":41,"name":"hunter"},
{"votes":8,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":5712,"precincts":
{"total":1,"reporting":1},
"name":"Merrimack"},
"Lyme":
{"votes":[
{"votes":137,"name":"mccain"},
{"votes":52,"name":"romney"},
{"votes":20,"name":"huckabee"},
{"votes":18,"name":"giuliani"},
{"votes":18,"name":"paul"},
{"votes":6,"name":"thompson"}],
"total":251,"precincts":
{"total":1,"reporting":1},
"name":"Lyme"},
"Henniker":
{"votes":[
{"votes":322,"name":"mccain"},
{"votes":192,"name":"romney"},
{"votes":97,"name":"huckabee"},
{"votes":92,"name":"giuliani"},
{"votes":90,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":807,"precincts":
{"total":1,"reporting":1},
"name":"Henniker"},
"Atkinson":
{"votes":[
{"votes":763,"name":"romney"},
{"votes":676,"name":"mccain"},
{"votes":153,"name":"giuliani"},
{"votes":114,"name":"huckabee"},
{"votes":104,"name":"paul"},
{"votes":15,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":1828,"precincts":
{"total":1,"reporting":1},
"name":"Atkinson"},
"Plainfield":
{"votes":[
{"votes":175,"name":"mccain"},
{"votes":71,"name":"romney"},
{"votes":52,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":28,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":3,"name":"hunter"}],
"total":371,"precincts":
{"total":1,"reporting":1},
"name":"Plainfield"},
"Goffstown":
{"votes":[
{"votes":1258,"name":"romney"},
{"votes":1212,"name":"mccain"},
{"votes":417,"name":"huckabee"},
{"votes":308,"name":"giuliani"},
{"votes":260,"name":"paul"},
{"votes":30,"name":"thompson"},
{"votes":19,"name":"hunter"},
{"votes":2,"name":"tancredo"},
{"votes":2,"name":"keyes"}],
"total":3508,"precincts":
{"total":1,"reporting":1},
"name":"Goffstown"},
"Rumney":
{"votes":[
{"votes":141,"name":"mccain"},
{"votes":75,"name":"romney"},
{"votes":58,"name":"huckabee"},
{"votes":53,"name":"paul"},
{"votes":32,"name":"giuliani"},
{"votes":4,"name":"thompson"}],
"total":363,"precincts":
{"total":1,"reporting":1},
"name":"Rumney"},
"Danville":
{"votes":[
{"votes":338,"name":"romney"},
{"votes":321,"name":"mccain"},
{"votes":75,"name":"huckabee"},
{"votes":74,"name":"giuliani"},
{"votes":50,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":872,"precincts":
{"total":1,"reporting":1},
"name":"Danville"},
"Whitefield":
{"votes":[
{"votes":140,"name":"mccain"},
{"votes":77,"name":"huckabee"},
{"votes":52,"name":"romney"},
{"votes":40,"name":"giuliani"},
{"votes":36,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":3,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":355,"precincts":
{"total":1,"reporting":1},
"name":"Whitefield"},
"Loudon":
{"votes":[
{"votes":440,"name":"mccain"},
{"votes":291,"name":"romney"},
{"votes":190,"name":"huckabee"},
{"votes":99,"name":"paul"},
{"votes":86,"name":"giuliani"},
{"votes":15,"name":"thompson"},
{"votes":13,"name":"hunter"}],
"total":1134,"precincts":
{"total":1,"reporting":1},
"name":"Loudon"},
"Jaffrey":
{"votes":[
{"votes":345,"name":"mccain"},
{"votes":323,"name":"romney"},
{"votes":144,"name":"huckabee"},
{"votes":89,"name":"paul"},
{"votes":72,"name":"giuliani"},
{"votes":9,"name":"hunter"},
{"votes":6,"name":"thompson"}],
"total":988,"precincts":
{"total":1,"reporting":1},
"name":"Jaffrey"},
"Woodstock":
{"votes":[
{"votes":105,"name":"mccain"},
{"votes":57,"name":"romney"},
{"votes":24,"name":"huckabee"},
{"votes":23,"name":"giuliani"},
{"votes":12,"name":"paul"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":226,"precincts":
{"total":1,"reporting":1},
"name":"Woodstock"},
"Raymond":
{"votes":[
{"votes":618,"name":"mccain"},
{"votes":527,"name":"romney"},
{"votes":241,"name":"huckabee"},
{"votes":165,"name":"paul"},
{"votes":160,"name":"giuliani"},
{"votes":18,"name":"thompson"},
{"votes":10,"name":"hunter"}],
"total":1739,"precincts":
{"total":1,"reporting":1},
"name":"Raymond"},
"Alton":
{"votes":[
{"votes":512,"name":"romney"},
{"votes":475,"name":"mccain"},
{"votes":172,"name":"huckabee"},
{"votes":112,"name":"giuliani"},
{"votes":95,"name":"paul"},
{"votes":32,"name":"thompson"},
{"votes":11,"name":"hunter"}],
"total":1409,"precincts":
{"total":1,"reporting":1},
"name":"Alton"},
"Grafton":
{"votes":[
{"votes":74,"name":"mccain"},
{"votes":56,"name":"romney"},
{"votes":56,"name":"paul"},
{"votes":35,"name":"huckabee"},
{"votes":13,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":1,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":242,"precincts":
{"total":1,"reporting":1},
"name":"Grafton"},
"Millsfield":
{"votes":[
{"votes":3,"name":"mccain"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"romney"}],
"total":5,"precincts":
{"total":1,"reporting":1},
"name":"Millsfield"},
"Meredith":
{"votes":[
{"votes":653,"name":"mccain"},
{"votes":502,"name":"romney"},
{"votes":152,"name":"huckabee"},
{"votes":141,"name":"giuliani"},
{"votes":96,"name":"paul"},
{"votes":32,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":1585,"precincts":
{"total":1,"reporting":1},
"name":"Meredith"},
"Peterborough":
{"votes":[
{"votes":523,"name":"mccain"},
{"votes":344,"name":"romney"},
{"votes":97,"name":"giuliani"},
{"votes":95,"name":"huckabee"},
{"votes":83,"name":"paul"},
{"votes":10,"name":"thompson"}],
"total":1152,"precincts":
{"total":1,"reporting":1},
"name":"Peterborough"},
"Candia":
{"votes":[
{"votes":415,"name":"mccain"},
{"votes":368,"name":"romney"},
{"votes":149,"name":"huckabee"},
{"votes":135,"name":"giuliani"},
{"votes":109,"name":"paul"},
{"votes":14,"name":"hunter"},
{"votes":11,"name":"thompson"}],
"total":1201,"precincts":
{"total":1,"reporting":1},
"name":"Candia"},
"Brookfield":
{"votes":[
{"votes":71,"name":"mccain"},
{"votes":63,"name":"romney"},
{"votes":29,"name":"huckabee"},
{"votes":20,"name":"giuliani"},
{"votes":14,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":201,"precincts":
{"total":1,"reporting":1},
"name":"Brookfield"},
"Milton":
{"votes":[
{"votes":298,"name":"mccain"},
{"votes":167,"name":"romney"},
{"votes":141,"name":"huckabee"},
{"votes":48,"name":"paul"},
{"votes":44,"name":"giuliani"},
{"votes":14,"name":"thompson"},
{"votes":6,"name":"hunter"}],
"total":718,"precincts":
{"total":1,"reporting":1},
"name":"Milton"},
"Hanover":
{"votes":[
{"votes":740,"name":"mccain"},
{"votes":260,"name":"romney"},
{"votes":105,"name":"paul"},
{"votes":82,"name":"giuliani"},
{"votes":68,"name":"huckabee"},
{"votes":16,"name":"thompson"},
{"votes":13,"name":"keyes"},
{"votes":2,"name":"hunter"}],
"total":1286,"precincts":
{"total":1,"reporting":1},
"name":"Hanover"},
"Barrington":
{"votes":[
{"votes":576,"name":"mccain"},
{"votes":363,"name":"romney"},
{"votes":208,"name":"huckabee"},
{"votes":149,"name":"giuliani"},
{"votes":130,"name":"paul"},
{"votes":28,"name":"thompson"},
{"votes":11,"name":"hunter"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"tancredo"}],
"total":1468,"precincts":
{"total":1,"reporting":1},
"name":"Barrington"},
"Epsom":
{"votes":[
{"votes":339,"name":"mccain"},
{"votes":235,"name":"romney"},
{"votes":186,"name":"huckabee"},
{"votes":108,"name":"paul"},
{"votes":84,"name":"giuliani"},
{"votes":7,"name":"hunter"},
{"votes":7,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":967,"precincts":
{"total":1,"reporting":1},
"name":"Epsom"},
"Pembroke":
{"votes":[
{"votes":473,"name":"mccain"},
{"votes":383,"name":"romney"},
{"votes":161,"name":"huckabee"},
{"votes":151,"name":"giuliani"},
{"votes":136,"name":"paul"},
{"votes":16,"name":"thompson"},
{"votes":14,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":1335,"precincts":
{"total":1,"reporting":1},
"name":"Pembroke"},
"Keene":
{"votes":[
{"votes":1089,"name":"mccain"},
{"votes":738,"name":"romney"},
{"votes":374,"name":"huckabee"},
{"votes":218,"name":"giuliani"},
{"votes":204,"name":"paul"},
{"votes":48,"name":"thompson"},
{"votes":19,"name":"hunter"},
{"votes":5,"name":"keyes"}],
"total":2695,"precincts":
{"total":5,"reporting":5},
"name":"Keene"},
"Benton":
{"votes":[
{"votes":22,"name":"huckabee"},
{"votes":21,"name":"mccain"},
{"votes":16,"name":"romney"},
{"votes":14,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"thompson"}],
"total":76,"precincts":
{"total":1,"reporting":1},
"name":"Benton"},
"Wentworth":
{"votes":[
{"votes":62,"name":"mccain"},
{"votes":46,"name":"paul"},
{"votes":45,"name":"romney"},
{"votes":24,"name":"huckabee"},
{"votes":9,"name":"giuliani"},
{"votes":3,"name":"thompson"},
{"votes":1,"name":"hunter"}],
"total":190,"precincts":
{"total":1,"reporting":1},
"name":"Wentworth"},
"Hollis":
{"votes":[
{"votes":902,"name":"mccain"},
{"votes":786,"name":"romney"},
{"votes":195,"name":"giuliani"},
{"votes":156,"name":"huckabee"},
{"votes":124,"name":"paul"},
{"votes":14,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":2186,"precincts":
{"total":1,"reporting":1},
"name":"Hollis"},
"Plymouth":
{"votes":[
{"votes":316,"name":"mccain"},
{"votes":129,"name":"romney"},
{"votes":88,"name":"huckabee"},
{"votes":81,"name":"paul"},
{"votes":66,"name":"giuliani"},
{"votes":5,"name":"thompson"}],
"total":685,"precincts":
{"total":1,"reporting":1},
"name":"Plymouth"},
"Bristol":
{"votes":[
{"votes":233,"name":"mccain"},
{"votes":182,"name":"romney"},
{"votes":80,"name":"huckabee"},
{"votes":75,"name":"paul"},
{"votes":58,"name":"giuliani"},
{"votes":12,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":642,"precincts":
{"total":1,"reporting":1},
"name":"Bristol"},
"Ashland":
{"votes":[
{"votes":146,"name":"mccain"},
{"votes":94,"name":"romney"},
{"votes":78,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":22,"name":"giuliani"},
{"votes":5,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":390,"precincts":
{"total":1,"reporting":1},
"name":"Ashland"},
"Brentwood":
{"votes":[
{"votes":350,"name":"mccain"},
{"votes":312,"name":"romney"},
{"votes":85,"name":"huckabee"},
{"votes":72,"name":"giuliani"},
{"votes":68,"name":"paul"},
{"votes":11,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":904,"precincts":
{"total":1,"reporting":1},
"name":"Brentwood"},
"Greenland":
{"votes":[
{"votes":330,"name":"mccain"},
{"votes":278,"name":"romney"},
{"votes":80,"name":"giuliani"},
{"votes":70,"name":"huckabee"},
{"votes":39,"name":"paul"},
{"votes":14,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":813,"precincts":
{"total":1,"reporting":1},
"name":"Greenland"},
"Hampton":
{"votes":[
{"votes":1217,"name":"romney"},
{"votes":1217,"name":"mccain"},
{"votes":286,"name":"giuliani"},
{"votes":217,"name":"huckabee"},
{"votes":144,"name":"paul"},
{"votes":22,"name":"thompson"},
{"votes":7,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":3111,"precincts":
{"total":1,"reporting":1},
"name":"Hampton"},
"Hampton Falls":
{"votes":[
{"votes":315,"name":"romney"},
{"votes":213,"name":"mccain"},
{"votes":64,"name":"giuliani"},
{"votes":53,"name":"huckabee"},
{"votes":29,"name":"paul"},
{"votes":6,"name":"thompson"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"tancredo"}],
"total":683,"precincts":
{"total":1,"reporting":1},
"name":"Hampton Falls"},
"Francestown":
{"votes":[
{"votes":168,"name":"mccain"},
{"votes":133,"name":"romney"},
{"votes":43,"name":"paul"},
{"votes":40,"name":"giuliani"},
{"votes":39,"name":"huckabee"},
{"votes":4,"name":"hunter"},
{"votes":4,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":432,"precincts":
{"total":1,"reporting":1},
"name":"Francestown"},
"Nashua":
{"votes":[
{"votes":4447,"name":"romney"},
{"votes":4294,"name":"mccain"},
{"votes":1120,"name":"huckabee"},
{"votes":992,"name":"giuliani"},
{"votes":979,"name":"paul"},
{"votes":128,"name":"thompson"},
{"votes":62,"name":"hunter"},
{"votes":11,"name":"keyes"},
{"votes":3,"name":"tancredo"}],
"total":12036,"precincts":
{"total":9,"reporting":9},
"name":"Nashua"},
"Kingston":
{"votes":[
{"votes":468,"name":"romney"},
{"votes":432,"name":"mccain"},
{"votes":130,"name":"huckabee"},
{"votes":102,"name":"giuliani"},
{"votes":93,"name":"paul"},
{"votes":13,"name":"thompson"},
{"votes":6,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":1246,"precincts":
{"total":1,"reporting":1},
"name":"Kingston"},
"Surry":
{"votes":[
{"votes":74,"name":"mccain"},
{"votes":46,"name":"romney"},
{"votes":25,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":13,"name":"giuliani"},
{"votes":1,"name":"thompson"}],
"total":176,"precincts":
{"total":1,"reporting":1},
"name":"Surry"},
"Ellsworth":
{"votes":[
{"votes":10,"name":"mccain"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"paul"}],
"total":17,"precincts":
{"total":1,"reporting":1},
"name":"Ellsworth"},
"Gilford":
{"votes":[
{"votes":740,"name":"mccain"},
{"votes":735,"name":"romney"},
{"votes":139,"name":"huckabee"},
{"votes":139,"name":"giuliani"},
{"votes":78,"name":"paul"},
{"votes":21,"name":"thompson"},
{"votes":8,"name":"hunter"},
{"votes":1,"name":"tancredo"},
{"votes":1,"name":"keyes"}],
"total":1862,"precincts":
{"total":1,"reporting":1},
"name":"Gilford"},
"Salisbury":
{"votes":[
{"votes":116,"name":"mccain"},
{"votes":75,"name":"romney"},
{"votes":59,"name":"huckabee"},
{"votes":48,"name":"giuliani"},
{"votes":28,"name":"paul"},
{"votes":2,"name":"hunter"},
{"votes":2,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":331,"precincts":
{"total":1,"reporting":1},
"name":"Salisbury"},
"Lisbon":
{"votes":[
{"votes":106,"name":"mccain"},
{"votes":59,"name":"huckabee"},
{"votes":47,"name":"romney"},
{"votes":28,"name":"giuliani"},
{"votes":19,"name":"paul"},
{"votes":3,"name":"thompson"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"hunter"}],
"total":266,"precincts":
{"total":1,"reporting":1},
"name":"Lisbon"},
"Newport":
{"votes":[
{"votes":346,"name":"mccain"},
{"votes":231,"name":"romney"},
{"votes":126,"name":"huckabee"},
{"votes":106,"name":"paul"},
{"votes":88,"name":"giuliani"},
{"votes":10,"name":"thompson"},
{"votes":4,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":912,"precincts":
{"total":1,"reporting":1},
"name":"Newport"},
"Holderness":
{"votes":[
{"votes":220,"name":"mccain"},
{"votes":109,"name":"romney"},
{"votes":52,"name":"huckabee"},
{"votes":28,"name":"giuliani"},
{"votes":21,"name":"paul"},
{"votes":8,"name":"thompson"},
{"votes":2,"name":"hunter"}],
"total":440,"precincts":
{"total":1,"reporting":1},
"name":"Holderness"},
"Randolph":
{"votes":[
{"votes":33,"name":"mccain"},
{"votes":19,"name":"romney"},
{"votes":12,"name":"huckabee"},
{"votes":9,"name":"giuliani"},
{"votes":6,"name":"paul"},
{"votes":3,"name":"thompson"}],
"total":82,"precincts":
{"total":1,"reporting":1},
"name":"Randolph"},
"Hampstead":
{"votes":[
{"votes":929,"name":"romney"},
{"votes":769,"name":"mccain"},
{"votes":211,"name":"giuliani"},
{"votes":144,"name":"huckabee"},
{"votes":108,"name":"paul"},
{"votes":24,"name":"thompson"},
{"votes":9,"name":"hunter"},
{"votes":2,"name":"keyes"}],
"total":2196,"precincts":
{"total":1,"reporting":1},
"name":"Hampstead"},
"Monroe":
{"votes":[
{"votes":115,"name":"mccain"},
{"votes":36,"name":"huckabee"},
{"votes":34,"name":"romney"},
{"votes":18,"name":"paul"},
{"votes":12,"name":"giuliani"},
{"votes":2,"name":"hunter"},
{"votes":1,"name":"thompson"},
{"votes":1,"name":"keyes"}],
"total":219,"precincts":
{"total":1,"reporting":1},
"name":"Monroe"},
"Northfield":
{"votes":[
{"votes":289,"name":"mccain"},
{"votes":175,"name":"romney"},
{"votes":144,"name":"huckabee"},
{"votes":80,"name":"paul"},
{"votes":51,"name":"giuliani"},
{"votes":6,"name":"thompson"},
{"votes":5,"name":"hunter"},
{"votes":1,"name":"keyes"}],
"total":751,"precincts":
{"total":1,"reporting":1},
"name":"Northfield"}}})