GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":1943,"name":"mccain"},
{"votes":286,"name":"paul"}],
"name":"New Mexico","precincts":
{"total":1633,"reporting":69},
"delegates":32,"date":"06-03"},
"state":"NM","party":"gop","total":2229,"locals":
{"San Juan":
{"votes":[],
"total":0,"precincts":
{"total":78,"reporting":0},
"name":"San Juan"},
"Colfax":
{"votes":[],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Colfax"},
"Otero":
{"votes":[
{"votes":24,"name":"mccain"},
{"votes":4,"name":"paul"}],
"total":28,"precincts":
{"total":43,"reporting":2},
"name":"Otero"},
"Bernalillo":
{"votes":[],
"total":0,"precincts":
{"total":442,"reporting":0},
"name":"Bernalillo"},
"Grant":
{"votes":[
{"votes":233,"name":"mccain"},
{"votes":40,"name":"paul"}],
"total":273,"precincts":
{"total":47,"reporting":1},
"name":"Grant"},
"Union":
{"votes":[
{"votes":62,"name":"mccain"},
{"votes":20,"name":"paul"}],
"total":82,"precincts":
{"total":8,"reporting":1},
"name":"Union"},
"Rio Arriba":
{"votes":[],
"total":0,"precincts":
{"total":47,"reporting":0},
"name":"Rio Arriba"},
"DeBaca":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"DeBaca"},
"Guadalupe":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Guadalupe"},
"Eddy":
{"votes":[],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Eddy"},
"CD1":
{"votes":[],
"total":0,"name":"CD1"},
"CD2":
{"votes":[],
"total":0,"name":"CD2"},
"CD3":
{"votes":[],
"total":0,"name":"CD3"},
"Sierra":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Sierra"},
"Valencia":
{"votes":[],
"total":0,"precincts":
{"total":51,"reporting":0},
"name":"Valencia"},
"Mora":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Mora"},
"Torrance":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Torrance"},
"Taos":
{"votes":[],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Taos"},
"Lea":
{"votes":[],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Lea"},
"Cibola":
{"votes":[],
"total":0,"precincts":
{"total":30,"reporting":0},
"name":"Cibola"},
"Quay":
{"votes":[
{"votes":61,"name":"mccain"},
{"votes":17,"name":"paul"}],
"total":78,"precincts":
{"total":25,"reporting":7},
"name":"Quay"},
"Harding":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Harding"},
"Chaves":
{"votes":[
{"votes":1239,"name":"mccain"},
{"votes":158,"name":"paul"}],
"total":1397,"precincts":
{"total":53,"reporting":50},
"name":"Chaves"},
"Catron":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Catron"},
"Sandoval":
{"votes":[],
"total":0,"precincts":
{"total":92,"reporting":0},
"name":"Sandoval"},
"San Miguel":
{"votes":[
{"votes":14,"name":"mccain"},
{"votes":1,"name":"paul"}],
"total":15,"precincts":
{"total":41,"reporting":1},
"name":"San Miguel"},
"Socorro":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Socorro"},
"Dona Ana":
{"votes":[
{"votes":43,"name":"mccain"},
{"votes":10,"name":"paul"}],
"total":53,"precincts":
{"total":136,"reporting":1},
"name":"Dona Ana"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Lincoln"},
"Roosevelt":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Roosevelt"},
"Los Alamos":
{"votes":[],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Los Alamos"},
"Curry":
{"votes":[],
"total":0,"precincts":
{"total":48,"reporting":0},
"name":"Curry"},
"Santa Fe":
{"votes":[],
"total":0,"precincts":
{"total":92,"reporting":0},
"name":"Santa Fe"},
"Luna":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Luna"},
"McKinley":
{"votes":[],
"total":0,"precincts":
{"total":60,"reporting":0},
"name":"McKinley"},
"Hidalgo":
{"votes":[
{"votes":267,"name":"mccain"},
{"votes":36,"name":"paul"}],
"total":303,"precincts":
{"total":8,"reporting":6},
"name":"Hidalgo"}}})