GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":716912,"name":"clinton","delegates":501},
{"votes":496181,"name":"obama","delegates":430},
{"votes":24143,"name":"edwards"}],
"name":"Ohio","precincts":
{"total":11238,"reporting":6337},
"delegates":141,"date":"03-04"},
"state":"OH","party":"dem","total":1237236,"locals":
{"Preble":
{"votes":[
{"votes":4291,"name":"clinton"},
{"votes":1977,"name":"obama"},
{"votes":196,"name":"edwards"}],
"total":6464,"precincts":
{"total":45,"reporting":45},
"name":"Preble"},
"Richland":
{"votes":[
{"votes":11382,"name":"clinton"},
{"votes":8124,"name":"obama"},
{"votes":458,"name":"edwards"}],
"total":19964,"precincts":
{"total":113,"reporting":108},
"name":"Richland"},
"Shelby":
{"votes":[
{"votes":4037,"name":"clinton"},
{"votes":2698,"name":"obama"},
{"votes":249,"name":"edwards"}],
"total":6984,"precincts":
{"total":35,"reporting":35},
"name":"Shelby"},
"Union":
{"votes":[
{"votes":2304,"name":"clinton"},
{"votes":1803,"name":"obama"},
{"votes":68,"name":"edwards"}],
"total":4175,"precincts":
{"total":45,"reporting":29},
"name":"Union"},
"Paulding":
{"votes":[
{"votes":1333,"name":"clinton"},
{"votes":605,"name":"obama"},
{"votes":94,"name":"edwards"}],
"total":2032,"precincts":
{"total":18,"reporting":14},
"name":"Paulding"},
"Montgomery":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":548,"reporting":0},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":9474,"name":"clinton"},
{"votes":6032,"name":"obama"},
{"votes":312,"name":"edwards"}],
"total":15818,"precincts":
{"total":96,"reporting":96},
"name":"Wayne"},
"Brown":
{"votes":[
{"votes":5352,"name":"clinton"},
{"votes":1876,"name":"obama"},
{"votes":271,"name":"edwards"}],
"total":7499,"precincts":
{"total":35,"reporting":35},
"name":"Brown"},
"Champaign":
{"votes":[
{"votes":3513,"name":"clinton"},
{"votes":2197,"name":"obama"},
{"votes":161,"name":"edwards"}],
"total":5871,"precincts":
{"total":28,"reporting":28},
"name":"Champaign"},
"Defiance":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"Defiance"},
"Miami":
{"votes":[
{"votes":8817,"name":"clinton"},
{"votes":6312,"name":"obama"},
{"votes":357,"name":"edwards"}],
"total":15486,"precincts":
{"total":82,"reporting":82},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":4781,"name":"clinton"},
{"votes":3706,"name":"obama"},
{"votes":123,"name":"edwards"}],
"total":8610,"precincts":
{"total":63,"reporting":63},
"name":"Hancock"},
"Lorain":
{"votes":[
{"votes":22578,"name":"clinton"},
{"votes":15770,"name":"obama"},
{"votes":728,"name":"edwards"}],
"total":39076,"precincts":
{"total":239,"reporting":143},
"name":"Lorain"},
"Columbiana":
{"votes":[
{"votes":14454,"name":"clinton"},
{"votes":5433,"name":"obama"},
{"votes":571,"name":"edwards"}],
"total":20458,"precincts":
{"total":103,"reporting":103},
"name":"Columbiana"},
"Henry":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Henry"},
"Muskingum":
{"votes":[
{"votes":9263,"name":"clinton"},
{"votes":4224,"name":"obama"},
{"votes":343,"name":"edwards"}],
"total":13830,"precincts":
{"total":85,"reporting":85},
"name":"Muskingum"},
"Washington":
{"votes":[
{"votes":7166,"name":"clinton"},
{"votes":2631,"name":"obama"},
{"votes":277,"name":"edwards"}],
"total":10074,"precincts":
{"total":56,"reporting":50},
"name":"Washington"},
"Gallia":
{"votes":[
{"votes":2616,"name":"clinton"},
{"votes":672,"name":"obama"},
{"votes":106,"name":"edwards"}],
"total":3394,"precincts":
{"total":35,"reporting":27},
"name":"Gallia"},
"Marion":
{"votes":[
{"votes":4153,"name":"clinton"},
{"votes":2023,"name":"obama"},
{"votes":161,"name":"edwards"}],
"total":6337,"precincts":
{"total":84,"reporting":70},
"name":"Marion"},
"Allen":
{"votes":[
{"votes":7023,"name":"clinton"},
{"votes":6499,"name":"obama"},
{"votes":345,"name":"edwards"}],
"total":13867,"precincts":
{"total":121,"reporting":121},
"name":"Allen"},
"Huron":
{"votes":[
{"votes":4536,"name":"clinton"},
{"votes":2629,"name":"obama"},
{"votes":148,"name":"edwards"}],
"total":7313,"precincts":
{"total":52,"reporting":52},
"name":"Huron"},
"Darke":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Darke"},
"Warren":
{"votes":[
{"votes":11458,"name":"clinton"},
{"votes":8701,"name":"obama"},
{"votes":279,"name":"edwards"}],
"total":20438,"precincts":
{"total":182,"reporting":125},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":2579,"name":"clinton"},
{"votes":804,"name":"obama"},
{"votes":108,"name":"edwards"}],
"total":3491,"precincts":
{"total":42,"reporting":30},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":3818,"name":"clinton"},
{"votes":788,"name":"obama"},
{"votes":138,"name":"edwards"}],
"total":4744,"precincts":
{"total":36,"reporting":36},
"name":"Jackson"},
"Belmont":
{"votes":[
{"votes":5490,"name":"clinton"},
{"votes":1844,"name":"obama"},
{"votes":378,"name":"edwards"}],
"total":7712,"precincts":
{"total":83,"reporting":32},
"name":"Belmont"},
"Wyandot":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Wyandot"},
"Jefferson":
{"votes":[
{"votes":7213,"name":"clinton"},
{"votes":3306,"name":"obama"},
{"votes":582,"name":"edwards"}],
"total":11101,"precincts":
{"total":82,"reporting":55},
"name":"Jefferson"},
"Ashtabula":
{"votes":[
{"votes":11790,"name":"clinton"},
{"votes":5570,"name":"obama"},
{"votes":368,"name":"edwards"}],
"total":17728,"precincts":
{"total":127,"reporting":100},
"name":"Ashtabula"},
"Butler":
{"votes":[
{"votes":16504,"name":"clinton"},
{"votes":13041,"name":"obama"},
{"votes":358,"name":"edwards"}],
"total":29903,"precincts":
{"total":302,"reporting":179},
"name":"Butler"},
"Ross":
{"votes":[
{"votes":9190,"name":"clinton"},
{"votes":3712,"name":"obama"},
{"votes":302,"name":"edwards"}],
"total":13204,"precincts":
{"total":76,"reporting":76},
"name":"Ross"},
"Vinton":
{"votes":[
{"votes":1887,"name":"clinton"},
{"votes":448,"name":"obama"},
{"votes":107,"name":"edwards"}],
"total":2442,"precincts":
{"total":20,"reporting":20},
"name":"Vinton"},
"Hamilton":
{"votes":[
{"votes":12750,"name":"obama"},
{"votes":8389,"name":"clinton"},
{"votes":254,"name":"edwards"}],
"total":21393,"precincts":
{"total":880,"reporting":25},
"name":"Hamilton"},
"Scioto":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":92,"reporting":0},
"name":"Scioto"},
"Greene":
{"votes":[
{"votes":12365,"name":"clinton"},
{"votes":11546,"name":"obama"},
{"votes":327,"name":"edwards"}],
"total":24238,"precincts":
{"total":143,"reporting":143},
"name":"Greene"},
"Fulton":
{"votes":[
{"votes":4070,"name":"clinton"},
{"votes":2483,"name":"obama"},
{"votes":93,"name":"edwards"}],
"total":6646,"precincts":
{"total":35,"reporting":35},
"name":"Fulton"},
"Seneca":
{"votes":[
{"votes":5400,"name":"clinton"},
{"votes":3688,"name":"obama"},
{"votes":261,"name":"edwards"}],
"total":9349,"precincts":
{"total":52,"reporting":52},
"name":"Seneca"},
"Madison":
{"votes":[
{"votes":3120,"name":"clinton"},
{"votes":1544,"name":"obama"},
{"votes":88,"name":"edwards"}],
"total":4752,"precincts":
{"total":44,"reporting":44},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":1430,"name":"clinton"},
{"votes":862,"name":"obama"},
{"votes":42,"name":"edwards"}],
"total":2334,"precincts":
{"total":38,"reporting":22},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":15751,"name":"clinton"},
{"votes":10336,"name":"obama"},
{"votes":505,"name":"edwards"}],
"total":26592,"precincts":
{"total":100,"reporting":100},
"name":"Clark"},
"Trumbull":
{"votes":[
{"votes":27725,"name":"clinton"},
{"votes":11195,"name":"obama"},
{"votes":1080,"name":"edwards"}],
"total":40000,"precincts":
{"total":273,"reporting":187},
"name":"Trumbull"},
"Erie":
{"votes":[
{"votes":9742,"name":"clinton"},
{"votes":7231,"name":"obama"},
{"votes":298,"name":"edwards"}],
"total":17271,"precincts":
{"total":62,"reporting":62},
"name":"Erie"},
"Cuyahoga":
{"votes":[
{"votes":32044,"name":"clinton"},
{"votes":29880,"name":"obama"},
{"votes":871,"name":"edwards"}],
"total":62795,"precincts":
{"total":1434,"reporting":37},
"name":"Cuyahoga"},
"Meigs":
{"votes":[
{"votes":2774,"name":"clinton"},
{"votes":733,"name":"obama"},
{"votes":121,"name":"edwards"}],
"total":3628,"precincts":
{"total":27,"reporting":27},
"name":"Meigs"},
"Delaware":
{"votes":[
{"votes":7099,"name":"clinton"},
{"votes":6832,"name":"obama"},
{"votes":109,"name":"edwards"}],
"total":14040,"precincts":
{"total":131,"reporting":79},
"name":"Delaware"},
"Stark":
{"votes":[
{"votes":23220,"name":"clinton"},
{"votes":15110,"name":"obama"},
{"votes":1022,"name":"edwards"}],
"total":39352,"precincts":
{"total":364,"reporting":226},
"name":"Stark"},
"Fairfield":
{"votes":[
{"votes":7499,"name":"clinton"},
{"votes":4025,"name":"obama"},
{"votes":269,"name":"edwards"}],
"total":11793,"precincts":
{"total":125,"reporting":82},
"name":"Fairfield"},
"Geauga":
{"votes":[
{"votes":10309,"name":"clinton"},
{"votes":8299,"name":"obama"},
{"votes":245,"name":"edwards"}],
"total":18853,"precincts":
{"total":96,"reporting":96},
"name":"Geauga"},
"Coshocton":
{"votes":[
{"votes":4054,"name":"clinton"},
{"votes":1952,"name":"obama"},
{"votes":188,"name":"edwards"}],
"total":6194,"precincts":
{"total":43,"reporting":43},
"name":"Coshocton"},
"Lawrence":
{"votes":[
{"votes":8407,"name":"clinton"},
{"votes":2076,"name":"obama"},
{"votes":307,"name":"edwards"}],
"total":10790,"precincts":
{"total":84,"reporting":84},
"name":"Lawrence"},
"Fayette":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Fayette"},
"Medina":
{"votes":[
{"votes":17612,"name":"clinton"},
{"votes":10670,"name":"obama"},
{"votes":437,"name":"edwards"}],
"total":28719,"precincts":
{"total":151,"reporting":150},
"name":"Medina"},
"Van Wert":
{"votes":[
{"votes":2089,"name":"clinton"},
{"votes":1239,"name":"obama"},
{"votes":125,"name":"edwards"}],
"total":3453,"precincts":
{"total":39,"reporting":39},
"name":"Van Wert"},
"Pike":
{"votes":[
{"votes":4216,"name":"clinton"},
{"votes":1140,"name":"obama"},
{"votes":210,"name":"edwards"}],
"total":5566,"precincts":
{"total":24,"reporting":24},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":2793,"name":"clinton"},
{"votes":812,"name":"obama"},
{"votes":142,"name":"edwards"}],
"total":3747,"precincts":
{"total":35,"reporting":35},
"name":"Adams"},
"Clermont":
{"votes":[
{"votes":15285,"name":"clinton"},
{"votes":9382,"name":"obama"},
{"votes":415,"name":"edwards"}],
"total":25082,"precincts":
{"total":200,"reporting":197},
"name":"Clermont"},
"Licking":
{"votes":[
{"votes":11677,"name":"clinton"},
{"votes":7236,"name":"obama"},
{"votes":419,"name":"edwards"}],
"total":19332,"precincts":
{"total":129,"reporting":106},
"name":"Licking"},
"Lake":
{"votes":[
{"votes":28068,"name":"clinton"},
{"votes":16110,"name":"obama"},
{"votes":684,"name":"edwards"}],
"total":44862,"precincts":
{"total":215,"reporting":207},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":3496,"name":"clinton"},
{"votes":1776,"name":"obama"},
{"votes":167,"name":"edwards"}],
"total":5439,"precincts":
{"total":33,"reporting":33},
"name":"Morrow"},
"Summit":
{"votes":[
{"votes":54959,"name":"clinton"},
{"votes":44947,"name":"obama"},
{"votes":1556,"name":"edwards"}],
"total":101462,"precincts":
{"total":499,"reporting":395},
"name":"Summit"},
"Franklin":
{"votes":[
{"votes":69073,"name":"obama"},
{"votes":52234,"name":"clinton"},
{"votes":874,"name":"edwards"}],
"total":122181,"precincts":
{"total":879,"reporting":709},
"name":"Franklin"},
"Guernsey":
{"votes":[
{"votes":3335,"name":"clinton"},
{"votes":1242,"name":"obama"},
{"votes":167,"name":"edwards"}],
"total":4744,"precincts":
{"total":35,"reporting":30},
"name":"Guernsey"},
"Highland":
{"votes":[
{"votes":2246,"name":"clinton"},
{"votes":795,"name":"obama"},
{"votes":84,"name":"edwards"}],
"total":3125,"precincts":
{"total":37,"reporting":20},
"name":"Highland"},
"Holmes":
{"votes":[
{"votes":624,"name":"clinton"},
{"votes":478,"name":"obama"},
{"votes":35,"name":"edwards"}],
"total":1137,"precincts":
{"total":19,"reporting":8},
"name":"Holmes"},
"Morgan":
{"votes":[
{"votes":295,"name":"clinton"},
{"votes":128,"name":"obama"},
{"votes":11,"name":"edwards"}],
"total":434,"precincts":
{"total":22,"reporting":14},
"name":"Morgan"},
"Carroll":
{"votes":[
{"votes":2832,"name":"clinton"},
{"votes":1358,"name":"obama"},
{"votes":180,"name":"edwards"}],
"total":4370,"precincts":
{"total":26,"reporting":20},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":1098,"name":"clinton"},
{"votes":314,"name":"obama"},
{"votes":80,"name":"edwards"}],
"total":1492,"precincts":
{"total":16,"reporting":10},
"name":"Harrison"},
"Mercer":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":41,"reporting":0},
"name":"Mercer"},
"Mahoning":
{"votes":[
{"votes":47478,"name":"clinton"},
{"votes":25665,"name":"obama"},
{"votes":1426,"name":"edwards"}],
"total":74569,"precincts":
{"total":312,"reporting":296},
"name":"Mahoning"},
"Portage":
{"votes":[
{"votes":18012,"name":"clinton"},
{"votes":11120,"name":"obama"},
{"votes":651,"name":"edwards"}],
"total":29783,"precincts":
{"total":131,"reporting":121},
"name":"Portage"},
"Sandusky":
{"votes":[
{"votes":5560,"name":"clinton"},
{"votes":3842,"name":"obama"},
{"votes":184,"name":"edwards"}],
"total":9586,"precincts":
{"total":72,"reporting":68},
"name":"Sandusky"},
"Athens":
{"votes":[
{"votes":7019,"name":"clinton"},
{"votes":5978,"name":"obama"},
{"votes":347,"name":"edwards"}],
"total":13344,"precincts":
{"total":71,"reporting":71},
"name":"Athens"},
"Hocking":
{"votes":[
{"votes":2165,"name":"clinton"},
{"votes":890,"name":"obama"},
{"votes":100,"name":"edwards"}],
"total":3155,"precincts":
{"total":34,"reporting":20},
"name":"Hocking"},
"Wood":
{"votes":[
{"votes":10701,"name":"clinton"},
{"votes":6875,"name":"obama"},
{"votes":222,"name":"edwards"}],
"total":17798,"precincts":
{"total":97,"reporting":87},
"name":"Wood"},
"Crawford":
{"votes":[
{"votes":991,"name":"clinton"},
{"votes":619,"name":"obama"},
{"votes":62,"name":"edwards"}],
"total":1672,"precincts":
{"total":46,"reporting":12},
"name":"Crawford"},
"Williams":
{"votes":[
{"votes":2948,"name":"clinton"},
{"votes":2131,"name":"obama"},
{"votes":86,"name":"edwards"}],
"total":5165,"precincts":
{"total":44,"reporting":44},
"name":"Williams"},
"Noble":
{"votes":[
{"votes":1637,"name":"clinton"},
{"votes":522,"name":"obama"},
{"votes":142,"name":"edwards"}],
"total":2301,"precincts":
{"total":27,"reporting":27},
"name":"Noble"},
"Tuscarawas":
{"votes":[
{"votes":11464,"name":"clinton"},
{"votes":5925,"name":"obama"},
{"votes":705,"name":"edwards"}],
"total":18094,"precincts":
{"total":81,"reporting":79},
"name":"Tuscarawas"},
"Knox":
{"votes":[
{"votes":4595,"name":"clinton"},
{"votes":3484,"name":"obama"},
{"votes":162,"name":"edwards"}],
"total":8241,"precincts":
{"total":58,"reporting":58},
"name":"Knox"},
"Putnam":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Putnam"},
"Hardin":
{"votes":[
{"votes":376,"name":"clinton"},
{"votes":162,"name":"obama"},
{"votes":20,"name":"edwards"}],
"total":558,"precincts":
{"total":38,"reporting":1},
"name":"Hardin"},
"Lucas":
{"votes":[
{"votes":9526,"name":"obama"},
{"votes":5402,"name":"clinton"},
{"votes":98,"name":"edwards"}],
"total":15026,"precincts":
{"total":495,"reporting":100},
"name":"Lucas"},
"Ottawa":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Ottawa"},
"Auglaize":
{"votes":[
{"votes":2942,"name":"clinton"},
{"votes":2012,"name":"obama"},
{"votes":179,"name":"edwards"}],
"total":5133,"precincts":
{"total":40,"reporting":40},
"name":"Auglaize"},
"Ashland":
{"votes":[
{"votes":3793,"name":"clinton"},
{"votes":2485,"name":"obama"},
{"votes":135,"name":"edwards"}],
"total":6413,"precincts":
{"total":65,"reporting":48},
"name":"Ashland"},
"Pickaway":
{"votes":[
{"votes":5903,"name":"clinton"},
{"votes":2497,"name":"obama"},
{"votes":241,"name":"edwards"}],
"total":8641,"precincts":
{"total":48,"reporting":48},
"name":"Pickaway"},
"Logan":
{"votes":[
{"votes":2667,"name":"clinton"},
{"votes":1781,"name":"obama"},
{"votes":129,"name":"edwards"}],
"total":4577,"precincts":
{"total":44,"reporting":37},
"name":"Logan"},
"Monroe":
{"votes":[
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Monroe"}}})