GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":587802,"name":"mccain","delegates":85},
{"votes":305883,"name":"huckabee"},
{"votes":45319,"name":"paul"},
{"votes":32626,"name":"romney"},
{"votes":15337,"name":"thompson"}],
"name":"Ohio","precincts":
{"total":11238,"reporting":9917},
"delegates":85,"date":"03-04"},
"state":"OH","party":"gop","total":986967,"locals":
{"Preble":
{"votes":[
{"votes":3285,"name":"mccain"},
{"votes":2569,"name":"huckabee"},
{"votes":219,"name":"paul"},
{"votes":149,"name":"romney"},
{"votes":104,"name":"thompson"}],
"total":6326,"precincts":
{"total":45,"reporting":45},
"name":"Preble"},
"Richland":
{"votes":[
{"votes":7429,"name":"mccain"},
{"votes":4685,"name":"huckabee"},
{"votes":738,"name":"paul"},
{"votes":656,"name":"romney"},
{"votes":226,"name":"thompson"}],
"total":13734,"precincts":
{"total":113,"reporting":113},
"name":"Richland"},
"Shelby":
{"votes":[
{"votes":2724,"name":"mccain"},
{"votes":2139,"name":"huckabee"},
{"votes":275,"name":"paul"},
{"votes":146,"name":"romney"},
{"votes":77,"name":"thompson"}],
"total":5361,"precincts":
{"total":35,"reporting":35},
"name":"Shelby"},
"Union":
{"votes":[
{"votes":4907,"name":"mccain"},
{"votes":2701,"name":"huckabee"},
{"votes":296,"name":"paul"},
{"votes":268,"name":"romney"},
{"votes":150,"name":"thompson"}],
"total":8322,"precincts":
{"total":45,"reporting":45},
"name":"Union"},
"Paulding":
{"votes":[
{"votes":1145,"name":"mccain"},
{"votes":914,"name":"huckabee"},
{"votes":241,"name":"paul"},
{"votes":67,"name":"romney"},
{"votes":43,"name":"thompson"}],
"total":2410,"precincts":
{"total":18,"reporting":18},
"name":"Paulding"},
"Montgomery":
{"votes":[
{"votes":28110,"name":"mccain"},
{"votes":17448,"name":"huckabee"},
{"votes":1607,"name":"paul"},
{"votes":1447,"name":"romney"},
{"votes":658,"name":"thompson"}],
"total":49270,"precincts":
{"total":548,"reporting":534},
"name":"Montgomery"},
"Wayne":
{"votes":[
{"votes":7194,"name":"mccain"},
{"votes":5120,"name":"huckabee"},
{"votes":743,"name":"paul"},
{"votes":489,"name":"romney"},
{"votes":222,"name":"thompson"}],
"total":13768,"precincts":
{"total":96,"reporting":96},
"name":"Wayne"},
"Brown":
{"votes":[
{"votes":2520,"name":"mccain"},
{"votes":1901,"name":"huckabee"},
{"votes":171,"name":"paul"},
{"votes":101,"name":"romney"},
{"votes":69,"name":"thompson"}],
"total":4762,"precincts":
{"total":35,"reporting":35},
"name":"Brown"},
"Champaign":
{"votes":[
{"votes":3530,"name":"mccain"},
{"votes":2287,"name":"huckabee"},
{"votes":196,"name":"paul"},
{"votes":144,"name":"romney"},
{"votes":122,"name":"thompson"}],
"total":6279,"precincts":
{"total":28,"reporting":28},
"name":"Champaign"},
"Defiance":
{"votes":[
{"votes":2662,"name":"mccain"},
{"votes":1556,"name":"huckabee"},
{"votes":295,"name":"paul"},
{"votes":144,"name":"romney"},
{"votes":100,"name":"thompson"}],
"total":4757,"precincts":
{"total":42,"reporting":42},
"name":"Defiance"},
"Miami":
{"votes":[
{"votes":9117,"name":"mccain"},
{"votes":5558,"name":"huckabee"},
{"votes":516,"name":"paul"},
{"votes":497,"name":"romney"},
{"votes":214,"name":"thompson"}],
"total":15902,"precincts":
{"total":82,"reporting":82},
"name":"Miami"},
"Hancock":
{"votes":[
{"votes":6484,"name":"mccain"},
{"votes":3720,"name":"huckabee"},
{"votes":897,"name":"paul"},
{"votes":420,"name":"romney"},
{"votes":207,"name":"thompson"}],
"total":11728,"precincts":
{"total":63,"reporting":63},
"name":"Hancock"},
"Lorain":
{"votes":[
{"votes":9198,"name":"mccain"},
{"votes":3475,"name":"huckabee"},
{"votes":579,"name":"paul"},
{"votes":430,"name":"romney"},
{"votes":211,"name":"thompson"}],
"total":13893,"precincts":
{"total":239,"reporting":186},
"name":"Lorain"},
"Columbiana":
{"votes":[
{"votes":5163,"name":"mccain"},
{"votes":3192,"name":"huckabee"},
{"votes":621,"name":"paul"},
{"votes":299,"name":"romney"},
{"votes":199,"name":"thompson"}],
"total":9474,"precincts":
{"total":103,"reporting":103},
"name":"Columbiana"},
"Henry":
{"votes":[
{"votes":1870,"name":"mccain"},
{"votes":1053,"name":"huckabee"},
{"votes":125,"name":"romney"},
{"votes":111,"name":"paul"},
{"votes":39,"name":"thompson"}],
"total":3198,"precincts":
{"total":33,"reporting":33},
"name":"Henry"},
"Muskingum":
{"votes":[
{"votes":7044,"name":"mccain"},
{"votes":4705,"name":"huckabee"},
{"votes":471,"name":"paul"},
{"votes":311,"name":"romney"},
{"votes":180,"name":"thompson"}],
"total":12711,"precincts":
{"total":85,"reporting":85},
"name":"Muskingum"},
"Washington":
{"votes":[
{"votes":4622,"name":"mccain"},
{"votes":2459,"name":"huckabee"},
{"votes":467,"name":"paul"},
{"votes":195,"name":"romney"},
{"votes":105,"name":"thompson"}],
"total":7848,"precincts":
{"total":56,"reporting":56},
"name":"Washington"},
"Gallia":
{"votes":[
{"votes":2815,"name":"mccain"},
{"votes":1572,"name":"huckabee"},
{"votes":101,"name":"paul"},
{"votes":74,"name":"thompson"},
{"votes":69,"name":"romney"}],
"total":4631,"precincts":
{"total":35,"reporting":35},
"name":"Gallia"},
"Marion":
{"votes":[
{"votes":3879,"name":"mccain"},
{"votes":2333,"name":"huckabee"},
{"votes":214,"name":"romney"},
{"votes":193,"name":"paul"},
{"votes":121,"name":"thompson"}],
"total":6740,"precincts":
{"total":84,"reporting":84},
"name":"Marion"},
"Allen":
{"votes":[
{"votes":7053,"name":"mccain"},
{"votes":3957,"name":"huckabee"},
{"votes":803,"name":"paul"},
{"votes":637,"name":"romney"},
{"votes":273,"name":"thompson"}],
"total":12723,"precincts":
{"total":121,"reporting":121},
"name":"Allen"},
"Huron":
{"votes":[
{"votes":2218,"name":"mccain"},
{"votes":1395,"name":"huckabee"},
{"votes":231,"name":"paul"},
{"votes":107,"name":"romney"},
{"votes":85,"name":"thompson"}],
"total":4036,"precincts":
{"total":52,"reporting":52},
"name":"Huron"},
"Darke":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"thompson"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Darke"},
"Warren":
{"votes":[
{"votes":13984,"name":"mccain"},
{"votes":8863,"name":"huckabee"},
{"votes":769,"name":"paul"},
{"votes":759,"name":"romney"},
{"votes":302,"name":"thompson"}],
"total":24677,"precincts":
{"total":182,"reporting":150},
"name":"Warren"},
"Perry":
{"votes":[
{"votes":1990,"name":"mccain"},
{"votes":1395,"name":"huckabee"},
{"votes":136,"name":"paul"},
{"votes":87,"name":"thompson"},
{"votes":67,"name":"romney"}],
"total":3675,"precincts":
{"total":42,"reporting":42},
"name":"Perry"},
"Jackson":
{"votes":[
{"votes":2244,"name":"mccain"},
{"votes":1515,"name":"huckabee"},
{"votes":90,"name":"paul"},
{"votes":64,"name":"romney"},
{"votes":58,"name":"thompson"}],
"total":3971,"precincts":
{"total":36,"reporting":36},
"name":"Jackson"},
"Belmont":
{"votes":[
{"votes":1821,"name":"mccain"},
{"votes":823,"name":"huckabee"},
{"votes":123,"name":"thompson"},
{"votes":82,"name":"romney"},
{"votes":80,"name":"paul"}],
"total":2929,"precincts":
{"total":83,"reporting":60},
"name":"Belmont"},
"Wyandot":
{"votes":[
{"votes":1601,"name":"mccain"},
{"votes":958,"name":"huckabee"},
{"votes":173,"name":"paul"},
{"votes":99,"name":"romney"},
{"votes":73,"name":"thompson"}],
"total":2904,"precincts":
{"total":27,"reporting":27},
"name":"Wyandot"},
"Jefferson":
{"votes":[
{"votes":2655,"name":"mccain"},
{"votes":1376,"name":"huckabee"},
{"votes":190,"name":"paul"},
{"votes":185,"name":"romney"},
{"votes":110,"name":"thompson"}],
"total":4516,"precincts":
{"total":82,"reporting":82},
"name":"Jefferson"},
"Ashtabula":
{"votes":[
{"votes":4304,"name":"mccain"},
{"votes":2667,"name":"huckabee"},
{"votes":610,"name":"paul"},
{"votes":180,"name":"romney"},
{"votes":124,"name":"thompson"}],
"total":7885,"precincts":
{"total":127,"reporting":127},
"name":"Ashtabula"},
"Butler":
{"votes":[
{"votes":22342,"name":"mccain"},
{"votes":13645,"name":"huckabee"},
{"votes":1133,"name":"romney"},
{"votes":1103,"name":"paul"},
{"votes":487,"name":"thompson"}],
"total":38710,"precincts":
{"total":302,"reporting":302},
"name":"Butler"},
"Ross":
{"votes":[
{"votes":3602,"name":"mccain"},
{"votes":2557,"name":"huckabee"},
{"votes":185,"name":"paul"},
{"votes":169,"name":"romney"},
{"votes":87,"name":"thompson"}],
"total":6600,"precincts":
{"total":76,"reporting":76},
"name":"Ross"},
"Vinton":
{"votes":[
{"votes":857,"name":"mccain"},
{"votes":559,"name":"huckabee"},
{"votes":31,"name":"thompson"},
{"votes":31,"name":"paul"},
{"votes":30,"name":"romney"}],
"total":1508,"precincts":
{"total":20,"reporting":20},
"name":"Vinton"},
"Hamilton":
{"votes":[
{"votes":52051,"name":"mccain"},
{"votes":18105,"name":"huckabee"},
{"votes":3259,"name":"paul"},
{"votes":3042,"name":"romney"},
{"votes":1030,"name":"thompson"}],
"total":77487,"precincts":
{"total":880,"reporting":880},
"name":"Hamilton"},
"Scioto":
{"votes":[
{"votes":3310,"name":"mccain"},
{"votes":2608,"name":"huckabee"},
{"votes":108,"name":"paul"},
{"votes":83,"name":"romney"},
{"votes":72,"name":"thompson"}],
"total":6181,"precincts":
{"total":92,"reporting":90},
"name":"Scioto"},
"Greene":
{"votes":[
{"votes":12600,"name":"mccain"},
{"votes":8211,"name":"huckabee"},
{"votes":670,"name":"paul"},
{"votes":607,"name":"romney"},
{"votes":275,"name":"thompson"}],
"total":22363,"precincts":
{"total":143,"reporting":143},
"name":"Greene"},
"Fulton":
{"votes":[
{"votes":2906,"name":"mccain"},
{"votes":2056,"name":"huckabee"},
{"votes":293,"name":"paul"},
{"votes":206,"name":"romney"},
{"votes":117,"name":"thompson"}],
"total":5578,"precincts":
{"total":35,"reporting":35},
"name":"Fulton"},
"Seneca":
{"votes":[
{"votes":4613,"name":"mccain"},
{"votes":2365,"name":"huckabee"},
{"votes":486,"name":"paul"},
{"votes":372,"name":"romney"},
{"votes":176,"name":"thompson"}],
"total":8012,"precincts":
{"total":52,"reporting":52},
"name":"Seneca"},
"Madison":
{"votes":[
{"votes":2955,"name":"mccain"},
{"votes":1621,"name":"huckabee"},
{"votes":157,"name":"paul"},
{"votes":133,"name":"romney"},
{"votes":91,"name":"thompson"}],
"total":4957,"precincts":
{"total":44,"reporting":44},
"name":"Madison"},
"Clinton":
{"votes":[
{"votes":1448,"name":"mccain"},
{"votes":1007,"name":"huckabee"},
{"votes":72,"name":"paul"},
{"votes":54,"name":"romney"},
{"votes":41,"name":"thompson"}],
"total":2622,"precincts":
{"total":38,"reporting":22},
"name":"Clinton"},
"Clark":
{"votes":[
{"votes":8642,"name":"mccain"},
{"votes":5579,"name":"huckabee"},
{"votes":438,"name":"paul"},
{"votes":407,"name":"romney"},
{"votes":221,"name":"thompson"}],
"total":15287,"precincts":
{"total":100,"reporting":100},
"name":"Clark"},
"Trumbull":
{"votes":[
{"votes":6614,"name":"mccain"},
{"votes":3783,"name":"huckabee"},
{"votes":755,"name":"paul"},
{"votes":370,"name":"romney"},
{"votes":215,"name":"thompson"}],
"total":11737,"precincts":
{"total":273,"reporting":273},
"name":"Trumbull"},
"Erie":
{"votes":[
{"votes":3845,"name":"mccain"},
{"votes":1681,"name":"huckabee"},
{"votes":270,"name":"paul"},
{"votes":209,"name":"romney"},
{"votes":80,"name":"thompson"}],
"total":6085,"precincts":
{"total":62,"reporting":62},
"name":"Erie"},
"Cuyahoga":
{"votes":[
{"votes":22336,"name":"mccain"},
{"votes":5118,"name":"huckabee"},
{"votes":1262,"name":"paul"},
{"votes":904,"name":"romney"},
{"votes":252,"name":"thompson"}],
"total":29872,"precincts":
{"total":1434,"reporting":496},
"name":"Cuyahoga"},
"Meigs":
{"votes":[
{"votes":2287,"name":"mccain"},
{"votes":1121,"name":"huckabee"},
{"votes":146,"name":"paul"},
{"votes":84,"name":"thompson"},
{"votes":61,"name":"romney"}],
"total":3699,"precincts":
{"total":27,"reporting":27},
"name":"Meigs"},
"Delaware":
{"votes":[
{"votes":15688,"name":"mccain"},
{"votes":6632,"name":"huckabee"},
{"votes":1040,"name":"paul"},
{"votes":827,"name":"romney"},
{"votes":336,"name":"thompson"}],
"total":24523,"precincts":
{"total":131,"reporting":131},
"name":"Delaware"},
"Stark":
{"votes":[
{"votes":23869,"name":"mccain"},
{"votes":11929,"name":"huckabee"},
{"votes":2098,"name":"paul"},
{"votes":1513,"name":"romney"},
{"votes":627,"name":"thompson"}],
"total":40036,"precincts":
{"total":364,"reporting":363},
"name":"Stark"},
"Fairfield":
{"votes":[
{"votes":13076,"name":"mccain"},
{"votes":6706,"name":"huckabee"},
{"votes":908,"name":"paul"},
{"votes":568,"name":"romney"},
{"votes":342,"name":"thompson"}],
"total":21600,"precincts":
{"total":125,"reporting":125},
"name":"Fairfield"},
"Geauga":
{"votes":[
{"votes":6598,"name":"mccain"},
{"votes":2343,"name":"huckabee"},
{"votes":618,"name":"paul"},
{"votes":368,"name":"romney"},
{"votes":135,"name":"thompson"}],
"total":10062,"precincts":
{"total":96,"reporting":96},
"name":"Geauga"},
"Coshocton":
{"votes":[
{"votes":2524,"name":"mccain"},
{"votes":1600,"name":"huckabee"},
{"votes":217,"name":"paul"},
{"votes":107,"name":"romney"},
{"votes":81,"name":"thompson"}],
"total":4529,"precincts":
{"total":43,"reporting":43},
"name":"Coshocton"},
"Lawrence":
{"votes":[
{"votes":4039,"name":"mccain"},
{"votes":2760,"name":"huckabee"},
{"votes":181,"name":"paul"},
{"votes":179,"name":"romney"},
{"votes":121,"name":"thompson"}],
"total":7280,"precincts":
{"total":84,"reporting":84},
"name":"Lawrence"},
"Fayette":
{"votes":[
{"votes":2190,"name":"mccain"},
{"votes":1341,"name":"huckabee"},
{"votes":102,"name":"paul"},
{"votes":94,"name":"romney"},
{"votes":65,"name":"thompson"}],
"total":3792,"precincts":
{"total":26,"reporting":26},
"name":"Fayette"},
"Medina":
{"votes":[
{"votes":11789,"name":"mccain"},
{"votes":4922,"name":"huckabee"},
{"votes":935,"name":"paul"},
{"votes":787,"name":"romney"},
{"votes":331,"name":"thompson"}],
"total":18764,"precincts":
{"total":151,"reporting":151},
"name":"Medina"},
"Van Wert":
{"votes":[
{"votes":2561,"name":"mccain"},
{"votes":1470,"name":"huckabee"},
{"votes":295,"name":"paul"},
{"votes":170,"name":"romney"},
{"votes":93,"name":"thompson"}],
"total":4589,"precincts":
{"total":39,"reporting":39},
"name":"Van Wert"},
"Pike":
{"votes":[
{"votes":1050,"name":"mccain"},
{"votes":913,"name":"huckabee"},
{"votes":41,"name":"paul"},
{"votes":34,"name":"thompson"},
{"votes":26,"name":"romney"}],
"total":2064,"precincts":
{"total":24,"reporting":24},
"name":"Pike"},
"Adams":
{"votes":[
{"votes":1681,"name":"mccain"},
{"votes":1487,"name":"huckabee"},
{"votes":65,"name":"paul"},
{"votes":65,"name":"romney"},
{"votes":29,"name":"thompson"}],
"total":3327,"precincts":
{"total":35,"reporting":35},
"name":"Adams"},
"Clermont":
{"votes":[
{"votes":15597,"name":"mccain"},
{"votes":8588,"name":"huckabee"},
{"votes":986,"name":"paul"},
{"votes":923,"name":"romney"},
{"votes":464,"name":"thompson"}],
"total":26558,"precincts":
{"total":200,"reporting":197},
"name":"Clermont"},
"Licking":
{"votes":[
{"votes":13053,"name":"mccain"},
{"votes":6805,"name":"huckabee"},
{"votes":1163,"name":"paul"},
{"votes":664,"name":"romney"},
{"votes":378,"name":"thompson"}],
"total":22063,"precincts":
{"total":129,"reporting":129},
"name":"Licking"},
"Lake":
{"votes":[
{"votes":13605,"name":"mccain"},
{"votes":4718,"name":"huckabee"},
{"votes":1074,"name":"paul"},
{"votes":588,"name":"romney"},
{"votes":290,"name":"thompson"}],
"total":20275,"precincts":
{"total":215,"reporting":215},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":2542,"name":"mccain"},
{"votes":1994,"name":"huckabee"},
{"votes":248,"name":"paul"},
{"votes":149,"name":"romney"},
{"votes":95,"name":"thompson"}],
"total":5028,"precincts":
{"total":33,"reporting":33},
"name":"Morrow"},
"Summit":
{"votes":[
{"votes":23747,"name":"mccain"},
{"votes":10167,"name":"huckabee"},
{"votes":1814,"name":"paul"},
{"votes":1650,"name":"romney"},
{"votes":553,"name":"thompson"}],
"total":37931,"precincts":
{"total":499,"reporting":499},
"name":"Summit"},
"Franklin":
{"votes":[
{"votes":43277,"name":"mccain"},
{"votes":17772,"name":"huckabee"},
{"votes":3123,"name":"paul"},
{"votes":2044,"name":"romney"},
{"votes":983,"name":"thompson"}],
"total":67199,"precincts":
{"total":879,"reporting":769},
"name":"Franklin"},
"Guernsey":
{"votes":[
{"votes":1979,"name":"mccain"},
{"votes":1430,"name":"huckabee"},
{"votes":135,"name":"paul"},
{"votes":104,"name":"romney"},
{"votes":82,"name":"thompson"}],
"total":3730,"precincts":
{"total":35,"reporting":35},
"name":"Guernsey"},
"Highland":
{"votes":[
{"votes":2932,"name":"mccain"},
{"votes":2121,"name":"huckabee"},
{"votes":102,"name":"romney"},
{"votes":99,"name":"paul"},
{"votes":83,"name":"thompson"}],
"total":5337,"precincts":
{"total":37,"reporting":37},
"name":"Highland"},
"Holmes":
{"votes":[
{"votes":2030,"name":"mccain"},
{"votes":1506,"name":"huckabee"},
{"votes":219,"name":"paul"},
{"votes":142,"name":"romney"},
{"votes":83,"name":"thompson"}],
"total":3980,"precincts":
{"total":19,"reporting":19},
"name":"Holmes"},
"Morgan":
{"votes":[
{"votes":1349,"name":"mccain"},
{"votes":869,"name":"huckabee"},
{"votes":166,"name":"paul"},
{"votes":34,"name":"thompson"},
{"votes":34,"name":"romney"}],
"total":2452,"precincts":
{"total":22,"reporting":22},
"name":"Morgan"},
"Carroll":
{"votes":[
{"votes":1982,"name":"mccain"},
{"votes":1249,"name":"huckabee"},
{"votes":230,"name":"paul"},
{"votes":109,"name":"romney"},
{"votes":80,"name":"thompson"}],
"total":3650,"precincts":
{"total":26,"reporting":26},
"name":"Carroll"},
"Harrison":
{"votes":[
{"votes":897,"name":"mccain"},
{"votes":478,"name":"huckabee"},
{"votes":57,"name":"paul"},
{"votes":44,"name":"romney"},
{"votes":35,"name":"thompson"}],
"total":1511,"precincts":
{"total":16,"reporting":16},
"name":"Harrison"},
"Mercer":
{"votes":[
{"votes":2642,"name":"mccain"},
{"votes":1571,"name":"huckabee"},
{"votes":368,"name":"paul"},
{"votes":128,"name":"romney"},
{"votes":58,"name":"thompson"}],
"total":4767,"precincts":
{"total":41,"reporting":41},
"name":"Mercer"},
"Mahoning":
{"votes":[
{"votes":6999,"name":"mccain"},
{"votes":3917,"name":"huckabee"},
{"votes":667,"name":"paul"},
{"votes":415,"name":"romney"},
{"votes":188,"name":"thompson"}],
"total":12186,"precincts":
{"total":312,"reporting":312},
"name":"Mahoning"},
"Portage":
{"votes":[
{"votes":5808,"name":"mccain"},
{"votes":2558,"name":"huckabee"},
{"votes":563,"name":"paul"},
{"votes":342,"name":"romney"},
{"votes":138,"name":"thompson"}],
"total":9409,"precincts":
{"total":131,"reporting":121},
"name":"Portage"},
"Sandusky":
{"votes":[
{"votes":3962,"name":"mccain"},
{"votes":2335,"name":"huckabee"},
{"votes":439,"name":"paul"},
{"votes":323,"name":"romney"},
{"votes":150,"name":"thompson"}],
"total":7209,"precincts":
{"total":72,"reporting":72},
"name":"Sandusky"},
"Athens":
{"votes":[
{"votes":1821,"name":"mccain"},
{"votes":950,"name":"huckabee"},
{"votes":353,"name":"paul"},
{"votes":60,"name":"romney"},
{"votes":39,"name":"thompson"}],
"total":3223,"precincts":
{"total":71,"reporting":71},
"name":"Athens"},
"Hocking":
{"votes":[
{"votes":1419,"name":"mccain"},
{"votes":944,"name":"huckabee"},
{"votes":156,"name":"paul"},
{"votes":42,"name":"thompson"},
{"votes":36,"name":"romney"}],
"total":2597,"precincts":
{"total":34,"reporting":34},
"name":"Hocking"},
"Wood":
{"votes":[
{"votes":7127,"name":"mccain"},
{"votes":3531,"name":"huckabee"},
{"votes":877,"name":"paul"},
{"votes":639,"name":"romney"},
{"votes":269,"name":"thompson"}],
"total":12443,"precincts":
{"total":97,"reporting":97},
"name":"Wood"},
"Crawford":
{"votes":[
{"votes":1493,"name":"mccain"},
{"votes":1106,"name":"huckabee"},
{"votes":123,"name":"paul"},
{"votes":105,"name":"romney"},
{"votes":66,"name":"thompson"}],
"total":2893,"precincts":
{"total":46,"reporting":37},
"name":"Crawford"},
"Williams":
{"votes":[
{"votes":2745,"name":"mccain"},
{"votes":1662,"name":"huckabee"},
{"votes":269,"name":"paul"},
{"votes":161,"name":"romney"},
{"votes":80,"name":"thompson"}],
"total":4917,"precincts":
{"total":44,"reporting":44},
"name":"Williams"},
"Noble":
{"votes":[
{"votes":1286,"name":"mccain"},
{"votes":725,"name":"huckabee"},
{"votes":73,"name":"paul"},
{"votes":70,"name":"thompson"},
{"votes":40,"name":"romney"}],
"total":2194,"precincts":
{"total":27,"reporting":27},
"name":"Noble"},
"Tuscarawas":
{"votes":[
{"votes":4041,"name":"mccain"},
{"votes":2753,"name":"huckabee"},
{"votes":375,"name":"paul"},
{"votes":207,"name":"romney"},
{"votes":105,"name":"thompson"}],
"total":7481,"precincts":
{"total":81,"reporting":81},
"name":"Tuscarawas"},
"Knox":
{"votes":[
{"votes":4156,"name":"mccain"},
{"votes":2766,"name":"huckabee"},
{"votes":514,"name":"paul"},
{"votes":215,"name":"romney"},
{"votes":141,"name":"thompson"}],
"total":7792,"precincts":
{"total":58,"reporting":58},
"name":"Knox"},
"Putnam":
{"votes":[
{"votes":3308,"name":"mccain"},
{"votes":1782,"name":"huckabee"},
{"votes":355,"name":"paul"},
{"votes":226,"name":"romney"},
{"votes":74,"name":"thompson"}],
"total":5745,"precincts":
{"total":35,"reporting":35},
"name":"Putnam"},
"Hardin":
{"votes":[
{"votes":2133,"name":"mccain"},
{"votes":1270,"name":"huckabee"},
{"votes":236,"name":"paul"},
{"votes":146,"name":"romney"},
{"votes":85,"name":"thompson"}],
"total":3870,"precincts":
{"total":38,"reporting":38},
"name":"Hardin"},
"Lucas":
{"votes":[
{"votes":12889,"name":"mccain"},
{"votes":5705,"name":"huckabee"},
{"votes":1444,"name":"paul"},
{"votes":1203,"name":"romney"},
{"votes":357,"name":"thompson"}],
"total":21598,"precincts":
{"total":495,"reporting":428},
"name":"Lucas"},
"Ottawa":
{"votes":[
{"votes":2202,"name":"mccain"},
{"votes":1037,"name":"huckabee"},
{"votes":191,"name":"paul"},
{"votes":181,"name":"romney"},
{"votes":77,"name":"thompson"}],
"total":3688,"precincts":
{"total":44,"reporting":44},
"name":"Ottawa"},
"Auglaize":
{"votes":[
{"votes":2904,"name":"mccain"},
{"votes":1641,"name":"huckabee"},
{"votes":472,"name":"paul"},
{"votes":193,"name":"romney"},
{"votes":68,"name":"thompson"}],
"total":5278,"precincts":
{"total":40,"reporting":40},
"name":"Auglaize"},
"Ashland":
{"votes":[
{"votes":3747,"name":"mccain"},
{"votes":2689,"name":"huckabee"},
{"votes":507,"name":"paul"},
{"votes":240,"name":"romney"},
{"votes":121,"name":"thompson"}],
"total":7304,"precincts":
{"total":65,"reporting":65},
"name":"Ashland"},
"Pickaway":
{"votes":[
{"votes":2786,"name":"mccain"},
{"votes":1908,"name":"huckabee"},
{"votes":163,"name":"paul"},
{"votes":98,"name":"romney"},
{"votes":86,"name":"thompson"}],
"total":5041,"precincts":
{"total":48,"reporting":48},
"name":"Pickaway"},
"Logan":
{"votes":[
{"votes":3858,"name":"mccain"},
{"votes":2544,"name":"huckabee"},
{"votes":260,"name":"paul"},
{"votes":247,"name":"romney"},
{"votes":135,"name":"thompson"}],
"total":7044,"precincts":
{"total":44,"reporting":44},
"name":"Logan"},
"Monroe":
{"votes":[
{"votes":445,"name":"mccain"},
{"votes":337,"name":"huckabee"},
{"votes":46,"name":"paul"},
{"votes":33,"name":"romney"},
{"votes":19,"name":"thompson"}],
"total":880,"precincts":
{"total":29,"reporting":29},
"name":"Monroe"}}})