GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":296181,"name":"obama","delegates":22},
{"votes":212525,"name":"clinton","delegates":12}],
"name":"Oregon","precincts":
{"total":1000,"reporting":752},
"delegates":52,"date":"05-20"},
"state":"OR","party":"dem","total":508706,"locals":
{"Wheeler":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wheeler"},
"Jackson":
{"votes":[
{"votes":14262,"name":"obama"},
{"votes":9496,"name":"clinton"}],
"total":23758,"precincts":
{"total":57,"reporting":38},
"name":"Jackson"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Grant"},
"Union":
{"votes":[
{"votes":1670,"name":"obama"},
{"votes":1339,"name":"clinton"}],
"total":3009,"precincts":
{"total":7,"reporting":5},
"name":"Union"},
"Deschutes":
{"votes":[
{"votes":10107,"name":"obama"},
{"votes":6685,"name":"clinton"}],
"total":16792,"precincts":
{"total":43,"reporting":29},
"name":"Deschutes"},
"Lane":
{"votes":[
{"votes":33733,"name":"obama"},
{"votes":20773,"name":"clinton"}],
"total":54506,"precincts":
{"total":97,"reporting":58},
"name":"Lane"},
"Douglas":
{"votes":[
{"votes":6883,"name":"clinton"},
{"votes":6550,"name":"obama"}],
"total":13433,"precincts":
{"total":31,"reporting":24},
"name":"Douglas"},
"Klamath":
{"votes":[
{"votes":3267,"name":"clinton"},
{"votes":2775,"name":"obama"}],
"total":6042,"precincts":
{"total":17,"reporting":14},
"name":"Klamath"},
"Wasco":
{"votes":[
{"votes":1976,"name":"obama"},
{"votes":1915,"name":"clinton"}],
"total":3891,"precincts":
{"total":7,"reporting":7},
"name":"Wasco"},
"Jefferson":
{"votes":[
{"votes":1114,"name":"obama"},
{"votes":1045,"name":"clinton"}],
"total":2159,"precincts":
{"total":5,"reporting":5},
"name":"Jefferson"},
"Hood River":
{"votes":[
{"votes":2236,"name":"obama"},
{"votes":1465,"name":"clinton"}],
"total":3701,"precincts":
{"total":5,"reporting":5},
"name":"Hood River"},
"Coos":
{"votes":[
{"votes":4991,"name":"clinton"},
{"votes":4130,"name":"obama"}],
"total":9121,"precincts":
{"total":18,"reporting":14},
"name":"Coos"},
"Multnomah":
{"votes":[
{"votes":84461,"name":"obama"},
{"votes":45971,"name":"clinton"}],
"total":130432,"precincts":
{"total":196,"reporting":174},
"name":"Multnomah"},
"Columbia":
{"votes":[
{"votes":3265,"name":"clinton"},
{"votes":2866,"name":"obama"}],
"total":6131,"precincts":
{"total":14,"reporting":13},
"name":"Columbia"},
"Crook":
{"votes":[
{"votes":1143,"name":"clinton"},
{"votes":962,"name":"obama"}],
"total":2105,"precincts":
{"total":6,"reporting":4},
"name":"Crook"},
"Sherman":
{"votes":[
{"votes":156,"name":"clinton"},
{"votes":115,"name":"obama"}],
"total":271,"precincts":
{"total":1,"reporting":1},
"name":"Sherman"},
"Linn":
{"votes":[
{"votes":6530,"name":"clinton"},
{"votes":6176,"name":"obama"}],
"total":12706,"precincts":
{"total":29,"reporting":23},
"name":"Linn"},
"Lincoln":
{"votes":[
{"votes":5123,"name":"obama"},
{"votes":4437,"name":"clinton"}],
"total":9560,"precincts":
{"total":13,"reporting":13},
"name":"Lincoln"},
"Wallowa":
{"votes":[
{"votes":642,"name":"obama"},
{"votes":454,"name":"clinton"}],
"total":1096,"precincts":
{"total":2,"reporting":2},
"name":"Wallowa"},
"Baker":
{"votes":[
{"votes":1117,"name":"obama"},
{"votes":1086,"name":"clinton"}],
"total":2203,"precincts":
{"total":5,"reporting":5},
"name":"Baker"},
"Clatsop":
{"votes":[
{"votes":2252,"name":"obama"},
{"votes":1989,"name":"clinton"}],
"total":4241,"precincts":
{"total":11,"reporting":5},
"name":"Clatsop"},
"Benton":
{"votes":[
{"votes":11132,"name":"obama"},
{"votes":4840,"name":"clinton"}],
"total":15972,"precincts":
{"total":23,"reporting":16},
"name":"Benton"},
"Lake":
{"votes":[
{"votes":325,"name":"clinton"},
{"votes":280,"name":"obama"}],
"total":605,"precincts":
{"total":2,"reporting":1},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":573,"name":"clinton"},
{"votes":353,"name":"obama"}],
"total":926,"precincts":
{"total":2,"reporting":2},
"name":"Morrow"},
"Malheur":
{"votes":[
{"votes":837,"name":"clinton"},
{"votes":706,"name":"obama"}],
"total":1543,"precincts":
{"total":6,"reporting":3},
"name":"Malheur"},
"Umatilla":
{"votes":[
{"votes":3123,"name":"clinton"},
{"votes":2470,"name":"obama"}],
"total":5593,"precincts":
{"total":16,"reporting":13},
"name":"Umatilla"},
"Curry":
{"votes":[
{"votes":1598,"name":"obama"},
{"votes":1492,"name":"clinton"}],
"total":3090,"precincts":
{"total":7,"reporting":4},
"name":"Curry"},
"Clackamas":
{"votes":[
{"votes":20419,"name":"obama"},
{"votes":18179,"name":"clinton"}],
"total":38598,"precincts":
{"total":103,"reporting":60},
"name":"Clackamas"},
"Gilliam":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Gilliam"},
"Harney":
{"votes":[
{"votes":365,"name":"clinton"},
{"votes":351,"name":"obama"}],
"total":716,"precincts":
{"total":2,"reporting":2},
"name":"Harney"},
"Josephine":
{"votes":[
{"votes":5624,"name":"obama"},
{"votes":5347,"name":"clinton"}],
"total":10971,"precincts":
{"total":24,"reporting":21},
"name":"Josephine"},
"Washington":
{"votes":[
{"votes":39121,"name":"obama"},
{"votes":27018,"name":"clinton"}],
"total":66139,"precincts":
{"total":127,"reporting":99},
"name":"Washington"},
"Tillamook":
{"votes":[
{"votes":2037,"name":"clinton"},
{"votes":1974,"name":"obama"}],
"total":4011,"precincts":
{"total":7,"reporting":5},
"name":"Tillamook"},
"Yamhill":
{"votes":[
{"votes":6018,"name":"obama"},
{"votes":5285,"name":"clinton"}],
"total":11303,"precincts":
{"total":23,"reporting":17},
"name":"Yamhill"},
"Marion":
{"votes":[
{"votes":18472,"name":"obama"},
{"votes":15834,"name":"clinton"}],
"total":34306,"precincts":
{"total":70,"reporting":54},
"name":"Marion"},
"Polk":
{"votes":[
{"votes":5396,"name":"obama"},
{"votes":4380,"name":"clinton"}],
"total":9776,"precincts":
{"total":20,"reporting":16},
"name":"Polk"}}})