GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":144011,"name":"mccain"},
{"votes":22946,"name":"paul"}],
"name":"Oregon","precincts":
{"total":1000,"reporting":334},
"delegates":30,"date":"05-20"},
"state":"OR","party":"gop","total":166957,"locals":
{"Wheeler":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wheeler"},
"Jackson":
{"votes":[
{"votes":12847,"name":"mccain"},
{"votes":2349,"name":"paul"}],
"total":15196,"precincts":
{"total":57,"reporting":33},
"name":"Jackson"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Grant"},
"Union":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Union"},
"Deschutes":
{"votes":[
{"votes":11944,"name":"mccain"},
{"votes":1475,"name":"paul"}],
"total":13419,"precincts":
{"total":43,"reporting":29},
"name":"Deschutes"},
"Lane":
{"votes":[
{"votes":12237,"name":"mccain"},
{"votes":1971,"name":"paul"}],
"total":14208,"precincts":
{"total":97,"reporting":31},
"name":"Lane"},
"Douglas":
{"votes":[],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Douglas"},
"Klamath":
{"votes":[
{"votes":5628,"name":"mccain"},
{"votes":771,"name":"paul"}],
"total":6399,"precincts":
{"total":17,"reporting":10},
"name":"Klamath"},
"Wasco":
{"votes":[
{"votes":1757,"name":"mccain"},
{"votes":347,"name":"paul"}],
"total":2104,"precincts":
{"total":7,"reporting":5},
"name":"Wasco"},
"Jefferson":
{"votes":[
{"votes":1521,"name":"mccain"},
{"votes":220,"name":"paul"}],
"total":1741,"precincts":
{"total":5,"reporting":3},
"name":"Jefferson"},
"Hood River":
{"votes":[
{"votes":1563,"name":"mccain"},
{"votes":202,"name":"paul"}],
"total":1765,"precincts":
{"total":5,"reporting":4},
"name":"Hood River"},
"Coos":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Coos"},
"Multnomah":
{"votes":[
{"votes":18044,"name":"mccain"},
{"votes":3195,"name":"paul"}],
"total":21239,"precincts":
{"total":196,"reporting":14},
"name":"Multnomah"},
"Columbia":
{"votes":[],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Columbia"},
"Crook":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Crook"},
"Sherman":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sherman"},
"Linn":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Linn"},
"Lincoln":
{"votes":[
{"votes":3204,"name":"mccain"},
{"votes":474,"name":"paul"}],
"total":3678,"precincts":
{"total":13,"reporting":8},
"name":"Lincoln"},
"Wallowa":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Wallowa"},
"Baker":
{"votes":[
{"votes":2142,"name":"mccain"},
{"votes":420,"name":"paul"}],
"total":2562,"precincts":
{"total":5,"reporting":4},
"name":"Baker"},
"Clatsop":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Clatsop"},
"Benton":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Benton"},
"Lake":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Lake"},
"Morrow":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Morrow"},
"Malheur":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Malheur"},
"Umatilla":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Umatilla"},
"Curry":
{"votes":[
{"votes":2383,"name":"mccain"},
{"votes":518,"name":"paul"}],
"total":2901,"precincts":
{"total":7,"reporting":4},
"name":"Curry"},
"Clackamas":
{"votes":[
{"votes":13994,"name":"mccain"},
{"votes":2185,"name":"paul"}],
"total":16179,"precincts":
{"total":103,"reporting":41},
"name":"Clackamas"},
"Gilliam":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Gilliam"},
"Harney":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Harney"},
"Josephine":
{"votes":[],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Josephine"},
"Washington":
{"votes":[
{"votes":25769,"name":"mccain"},
{"votes":4055,"name":"paul"}],
"total":29824,"precincts":
{"total":127,"reporting":77},
"name":"Washington"},
"Tillamook":
{"votes":[
{"votes":2011,"name":"mccain"},
{"votes":412,"name":"paul"}],
"total":2423,"precincts":
{"total":7,"reporting":5},
"name":"Tillamook"},
"Yamhill":
{"votes":[
{"votes":6314,"name":"mccain"},
{"votes":1040,"name":"paul"}],
"total":7354,"precincts":
{"total":23,"reporting":15},
"name":"Yamhill"},
"Marion":
{"votes":[
{"votes":16881,"name":"mccain"},
{"votes":2361,"name":"paul"}],
"total":19242,"precincts":
{"total":70,"reporting":37},
"name":"Marion"},
"Polk":
{"votes":[
{"votes":5772,"name":"mccain"},
{"votes":951,"name":"paul"}],
"total":6723,"precincts":
{"total":20,"reporting":14},
"name":"Polk"}}})