GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":228283,"name":"mccain"},
{"votes":39025,"name":"paul"}],
"name":"Oregon","precincts":
{"total":1000,"reporting":743},
"delegates":30,"date":"05-20"},
"state":"OR","party":"gop","total":267308,"locals":
{"Wheeler":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wheeler"},
"Jackson":
{"votes":[
{"votes":13539,"name":"mccain"},
{"votes":2510,"name":"paul"}],
"total":16049,"precincts":
{"total":57,"reporting":38},
"name":"Jackson"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Grant"},
"Union":
{"votes":[
{"votes":2707,"name":"mccain"},
{"votes":566,"name":"paul"}],
"total":3273,"precincts":
{"total":7,"reporting":5},
"name":"Union"},
"Deschutes":
{"votes":[
{"votes":11944,"name":"mccain"},
{"votes":1475,"name":"paul"}],
"total":13419,"precincts":
{"total":43,"reporting":29},
"name":"Deschutes"},
"Lane":
{"votes":[
{"votes":19086,"name":"mccain"},
{"votes":3024,"name":"paul"}],
"total":22110,"precincts":
{"total":97,"reporting":55},
"name":"Lane"},
"Douglas":
{"votes":[
{"votes":11776,"name":"mccain"},
{"votes":2373,"name":"paul"}],
"total":14149,"precincts":
{"total":31,"reporting":24},
"name":"Douglas"},
"Klamath":
{"votes":[
{"votes":7291,"name":"mccain"},
{"votes":1017,"name":"paul"}],
"total":8308,"precincts":
{"total":17,"reporting":14},
"name":"Klamath"},
"Wasco":
{"votes":[
{"votes":2067,"name":"mccain"},
{"votes":407,"name":"paul"}],
"total":2474,"precincts":
{"total":7,"reporting":7},
"name":"Wasco"},
"Jefferson":
{"votes":[
{"votes":1760,"name":"mccain"},
{"votes":253,"name":"paul"}],
"total":2013,"precincts":
{"total":5,"reporting":5},
"name":"Jefferson"},
"Hood River":
{"votes":[
{"votes":1707,"name":"mccain"},
{"votes":237,"name":"paul"}],
"total":1944,"precincts":
{"total":5,"reporting":5},
"name":"Hood River"},
"Coos":
{"votes":[
{"votes":4620,"name":"mccain"},
{"votes":1100,"name":"paul"}],
"total":5720,"precincts":
{"total":18,"reporting":14},
"name":"Coos"},
"Multnomah":
{"votes":[
{"votes":21343,"name":"mccain"},
{"votes":3868,"name":"paul"}],
"total":25211,"precincts":
{"total":196,"reporting":174},
"name":"Multnomah"},
"Columbia":
{"votes":[
{"votes":2075,"name":"mccain"},
{"votes":403,"name":"paul"}],
"total":2478,"precincts":
{"total":14,"reporting":12},
"name":"Columbia"},
"Crook":
{"votes":[
{"votes":2009,"name":"mccain"},
{"votes":211,"name":"paul"}],
"total":2220,"precincts":
{"total":6,"reporting":4},
"name":"Crook"},
"Sherman":
{"votes":[
{"votes":308,"name":"mccain"},
{"votes":50,"name":"paul"}],
"total":358,"precincts":
{"total":1,"reporting":1},
"name":"Sherman"},
"Linn":
{"votes":[
{"votes":8456,"name":"mccain"},
{"votes":1220,"name":"paul"}],
"total":9676,"precincts":
{"total":29,"reporting":23},
"name":"Linn"},
"Lincoln":
{"votes":[
{"votes":3983,"name":"mccain"},
{"votes":619,"name":"paul"}],
"total":4602,"precincts":
{"total":13,"reporting":13},
"name":"Lincoln"},
"Wallowa":
{"votes":[
{"votes":1163,"name":"mccain"},
{"votes":315,"name":"paul"}],
"total":1478,"precincts":
{"total":2,"reporting":1},
"name":"Wallowa"},
"Baker":
{"votes":[
{"votes":2224,"name":"mccain"},
{"votes":445,"name":"paul"}],
"total":2669,"precincts":
{"total":5,"reporting":5},
"name":"Baker"},
"Clatsop":
{"votes":[
{"votes":1625,"name":"mccain"},
{"votes":266,"name":"paul"}],
"total":1891,"precincts":
{"total":11,"reporting":5},
"name":"Clatsop"},
"Benton":
{"votes":[
{"votes":5244,"name":"mccain"},
{"votes":974,"name":"paul"}],
"total":6218,"precincts":
{"total":23,"reporting":16},
"name":"Benton"},
"Lake":
{"votes":[
{"votes":980,"name":"mccain"},
{"votes":109,"name":"paul"}],
"total":1089,"precincts":
{"total":2,"reporting":1},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":793,"name":"mccain"},
{"votes":222,"name":"paul"}],
"total":1015,"precincts":
{"total":2,"reporting":2},
"name":"Morrow"},
"Malheur":
{"votes":[
{"votes":2227,"name":"mccain"},
{"votes":463,"name":"paul"}],
"total":2690,"precincts":
{"total":6,"reporting":3},
"name":"Malheur"},
"Umatilla":
{"votes":[
{"votes":4656,"name":"mccain"},
{"votes":713,"name":"paul"}],
"total":5369,"precincts":
{"total":16,"reporting":13},
"name":"Umatilla"},
"Curry":
{"votes":[
{"votes":2383,"name":"mccain"},
{"votes":518,"name":"paul"}],
"total":2901,"precincts":
{"total":7,"reporting":4},
"name":"Curry"},
"Clackamas":
{"votes":[
{"votes":17765,"name":"mccain"},
{"votes":2816,"name":"paul"}],
"total":20581,"precincts":
{"total":103,"reporting":60},
"name":"Clackamas"},
"Gilliam":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Gilliam"},
"Harney":
{"votes":[
{"votes":1146,"name":"mccain"},
{"votes":157,"name":"paul"}],
"total":1303,"precincts":
{"total":2,"reporting":2},
"name":"Harney"},
"Josephine":
{"votes":[
{"votes":8705,"name":"mccain"},
{"votes":2324,"name":"paul"}],
"total":11029,"precincts":
{"total":24,"reporting":21},
"name":"Josephine"},
"Washington":
{"votes":[
{"votes":27499,"name":"mccain"},
{"votes":4400,"name":"paul"}],
"total":31899,"precincts":
{"total":127,"reporting":95},
"name":"Washington"},
"Tillamook":
{"votes":[
{"votes":2011,"name":"mccain"},
{"votes":412,"name":"paul"}],
"total":2423,"precincts":
{"total":7,"reporting":5},
"name":"Tillamook"},
"Yamhill":
{"votes":[
{"votes":6897,"name":"mccain"},
{"votes":1162,"name":"paul"}],
"total":8059,"precincts":
{"total":23,"reporting":17},
"name":"Yamhill"},
"Marion":
{"votes":[
{"votes":21610,"name":"mccain"},
{"votes":3228,"name":"paul"}],
"total":24838,"precincts":
{"total":70,"reporting":54},
"name":"Marion"},
"Polk":
{"votes":[
{"votes":6684,"name":"mccain"},
{"votes":1168,"name":"paul"}],
"total":7852,"precincts":
{"total":20,"reporting":16},
"name":"Polk"}}})