GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":201480,"name":"mccain"},
{"votes":33793,"name":"paul"}],
"name":"Oregon","precincts":
{"total":1000,"reporting":511},
"delegates":30,"date":"05-20"},
"state":"OR","party":"gop","total":235273,"locals":
{"Wheeler":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wheeler"},
"Jackson":
{"votes":[
{"votes":12847,"name":"mccain"},
{"votes":2349,"name":"paul"}],
"total":15196,"precincts":
{"total":57,"reporting":33},
"name":"Jackson"},
"Grant":
{"votes":[],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Grant"},
"Union":
{"votes":[
{"votes":2229,"name":"mccain"},
{"votes":442,"name":"paul"}],
"total":2671,"precincts":
{"total":7,"reporting":3},
"name":"Union"},
"Deschutes":
{"votes":[
{"votes":11944,"name":"mccain"},
{"votes":1475,"name":"paul"}],
"total":13419,"precincts":
{"total":43,"reporting":29},
"name":"Deschutes"},
"Lane":
{"votes":[
{"votes":15297,"name":"mccain"},
{"votes":2475,"name":"paul"}],
"total":17772,"precincts":
{"total":97,"reporting":40},
"name":"Lane"},
"Douglas":
{"votes":[
{"votes":11242,"name":"mccain"},
{"votes":2251,"name":"paul"}],
"total":13493,"precincts":
{"total":31,"reporting":20},
"name":"Douglas"},
"Klamath":
{"votes":[
{"votes":6622,"name":"mccain"},
{"votes":925,"name":"paul"}],
"total":7547,"precincts":
{"total":17,"reporting":12},
"name":"Klamath"},
"Wasco":
{"votes":[
{"votes":1757,"name":"mccain"},
{"votes":347,"name":"paul"}],
"total":2104,"precincts":
{"total":7,"reporting":5},
"name":"Wasco"},
"Jefferson":
{"votes":[
{"votes":1586,"name":"mccain"},
{"votes":231,"name":"paul"}],
"total":1817,"precincts":
{"total":5,"reporting":4},
"name":"Jefferson"},
"Hood River":
{"votes":[
{"votes":1656,"name":"mccain"},
{"votes":231,"name":"paul"}],
"total":1887,"precincts":
{"total":5,"reporting":4},
"name":"Hood River"},
"Coos":
{"votes":[
{"votes":4026,"name":"mccain"},
{"votes":913,"name":"paul"}],
"total":4939,"precincts":
{"total":18,"reporting":10},
"name":"Coos"},
"Multnomah":
{"votes":[
{"votes":19133,"name":"mccain"},
{"votes":3396,"name":"paul"}],
"total":22529,"precincts":
{"total":196,"reporting":59},
"name":"Multnomah"},
"Columbia":
{"votes":[
{"votes":1790,"name":"mccain"},
{"votes":342,"name":"paul"}],
"total":2132,"precincts":
{"total":14,"reporting":10},
"name":"Columbia"},
"Crook":
{"votes":[
{"votes":1673,"name":"mccain"},
{"votes":156,"name":"paul"}],
"total":1829,"precincts":
{"total":6,"reporting":3},
"name":"Crook"},
"Sherman":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sherman"},
"Linn":
{"votes":[
{"votes":6888,"name":"mccain"},
{"votes":997,"name":"paul"}],
"total":7885,"precincts":
{"total":29,"reporting":16},
"name":"Linn"},
"Lincoln":
{"votes":[
{"votes":3533,"name":"mccain"},
{"votes":534,"name":"paul"}],
"total":4067,"precincts":
{"total":13,"reporting":9},
"name":"Lincoln"},
"Wallowa":
{"votes":[
{"votes":1163,"name":"mccain"},
{"votes":315,"name":"paul"}],
"total":1478,"precincts":
{"total":2,"reporting":1},
"name":"Wallowa"},
"Baker":
{"votes":[
{"votes":2142,"name":"mccain"},
{"votes":420,"name":"paul"}],
"total":2562,"precincts":
{"total":5,"reporting":4},
"name":"Baker"},
"Clatsop":
{"votes":[
{"votes":1625,"name":"mccain"},
{"votes":266,"name":"paul"}],
"total":1891,"precincts":
{"total":11,"reporting":5},
"name":"Clatsop"},
"Benton":
{"votes":[
{"votes":4604,"name":"mccain"},
{"votes":810,"name":"paul"}],
"total":5414,"precincts":
{"total":23,"reporting":14},
"name":"Benton"},
"Lake":
{"votes":[
{"votes":980,"name":"mccain"},
{"votes":109,"name":"paul"}],
"total":1089,"precincts":
{"total":2,"reporting":1},
"name":"Lake"},
"Morrow":
{"votes":[
{"votes":749,"name":"mccain"},
{"votes":217,"name":"paul"}],
"total":966,"precincts":
{"total":2,"reporting":1},
"name":"Morrow"},
"Malheur":
{"votes":[
{"votes":2227,"name":"mccain"},
{"votes":463,"name":"paul"}],
"total":2690,"precincts":
{"total":6,"reporting":3},
"name":"Malheur"},
"Umatilla":
{"votes":[
{"votes":3366,"name":"mccain"},
{"votes":512,"name":"paul"}],
"total":3878,"precincts":
{"total":16,"reporting":9},
"name":"Umatilla"},
"Curry":
{"votes":[
{"votes":2383,"name":"mccain"},
{"votes":518,"name":"paul"}],
"total":2901,"precincts":
{"total":7,"reporting":4},
"name":"Curry"},
"Clackamas":
{"votes":[
{"votes":15240,"name":"mccain"},
{"votes":2344,"name":"paul"}],
"total":17584,"precincts":
{"total":103,"reporting":45},
"name":"Clackamas"},
"Gilliam":
{"votes":[],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Gilliam"},
"Harney":
{"votes":[
{"votes":1146,"name":"mccain"},
{"votes":157,"name":"paul"}],
"total":1303,"precincts":
{"total":2,"reporting":2},
"name":"Harney"},
"Josephine":
{"votes":[
{"votes":6885,"name":"mccain"},
{"votes":1779,"name":"paul"}],
"total":8664,"precincts":
{"total":24,"reporting":17},
"name":"Josephine"},
"Washington":
{"votes":[
{"votes":25769,"name":"mccain"},
{"votes":4055,"name":"paul"}],
"total":29824,"precincts":
{"total":127,"reporting":77},
"name":"Washington"},
"Tillamook":
{"votes":[
{"votes":2011,"name":"mccain"},
{"votes":412,"name":"paul"}],
"total":2423,"precincts":
{"total":7,"reporting":5},
"name":"Tillamook"},
"Yamhill":
{"votes":[
{"votes":6314,"name":"mccain"},
{"votes":1040,"name":"paul"}],
"total":7354,"precincts":
{"total":23,"reporting":15},
"name":"Yamhill"},
"Marion":
{"votes":[
{"votes":16881,"name":"mccain"},
{"votes":2361,"name":"paul"}],
"total":19242,"precincts":
{"total":70,"reporting":37},
"name":"Marion"},
"Polk":
{"votes":[
{"votes":5772,"name":"mccain"},
{"votes":951,"name":"paul"}],
"total":6723,"precincts":
{"total":20,"reporting":14},
"name":"Polk"}}})