GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":468825,"name":"clinton","delegates":49},
{"votes":386724,"name":"obama","delegates":43}],
"name":"Pennsylvania","precincts":
{"total":9268,"reporting":3892},
"delegates":158,"date":"04-22"},
"state":"PA","party":"dem","total":855549,"locals":
{"Lancaster":
{"votes":[],
"total":0,"precincts":
{"total":234,"reporting":0},
"name":"Lancaster"},
"Elk":
{"votes":[
{"votes":2849,"name":"clinton"},
{"votes":1518,"name":"obama"}],
"total":4367,"precincts":
{"total":32,"reporting":25},
"name":"Elk"},
"Perry":
{"votes":[
{"votes":191,"name":"clinton"},
{"votes":132,"name":"obama"}],
"total":323,"precincts":
{"total":32,"reporting":6},
"name":"Perry"},
"Cumberland":
{"votes":[
{"votes":4431,"name":"clinton"},
{"votes":4262,"name":"obama"}],
"total":8693,"precincts":
{"total":101,"reporting":40},
"name":"Cumberland"},
"Susquehanna":
{"votes":[
{"votes":405,"name":"clinton"},
{"votes":280,"name":"obama"}],
"total":685,"precincts":
{"total":43,"reporting":10},
"name":"Susquehanna"},
"Union":
{"votes":[
{"votes":118,"name":"obama"},
{"votes":108,"name":"clinton"}],
"total":226,"precincts":
{"total":27,"reporting":2},
"name":"Union"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Potter"},
"Delaware":
{"votes":[
{"votes":13914,"name":"clinton"},
{"votes":12879,"name":"obama"}],
"total":26793,"precincts":
{"total":425,"reporting":151},
"name":"Delaware"},
"Philadelphia":
{"votes":[
{"votes":172041,"name":"obama"},
{"votes":116594,"name":"clinton"}],
"total":288635,"precincts":
{"total":1681,"reporting":1115},
"name":"Philadelphia"},
"Montgomery":
{"votes":[],
"total":0,"precincts":
{"total":413,"reporting":0},
"name":"Montgomery"},
"Lawrence":
{"votes":[
{"votes":6996,"name":"clinton"},
{"votes":2398,"name":"obama"}],
"total":9394,"precincts":
{"total":106,"reporting":67},
"name":"Lawrence"},
"Jefferson":
{"votes":[
{"votes":2391,"name":"clinton"},
{"votes":1325,"name":"obama"}],
"total":3716,"precincts":
{"total":37,"reporting":31},
"name":"Jefferson"},
"Forest":
{"votes":[
{"votes":281,"name":"clinton"},
{"votes":120,"name":"obama"}],
"total":401,"precincts":
{"total":9,"reporting":4},
"name":"Forest"},
"Butler":
{"votes":[
{"votes":2562,"name":"clinton"},
{"votes":1479,"name":"obama"}],
"total":4041,"precincts":
{"total":85,"reporting":19},
"name":"Butler"},
"Indiana":
{"votes":[],
"total":0,"precincts":
{"total":69,"reporting":0},
"name":"Indiana"},
"Somerset":
{"votes":[],
"total":0,"precincts":
{"total":68,"reporting":0},
"name":"Somerset"},
"Dauphin":
{"votes":[
{"votes":4568,"name":"obama"},
{"votes":1806,"name":"clinton"}],
"total":6374,"precincts":
{"total":159,"reporting":22},
"name":"Dauphin"},
"Juniata":
{"votes":[
{"votes":619,"name":"clinton"},
{"votes":247,"name":"obama"}],
"total":866,"precincts":
{"total":20,"reporting":10},
"name":"Juniata"},
"Tioga":
{"votes":[],
"total":0,"precincts":
{"total":43,"reporting":0},
"name":"Tioga"},
"Montour":
{"votes":[
{"votes":385,"name":"clinton"},
{"votes":218,"name":"obama"}],
"total":603,"precincts":
{"total":15,"reporting":6},
"name":"Montour"},
"Columbia":
{"votes":[
{"votes":5034,"name":"clinton"},
{"votes":3075,"name":"obama"}],
"total":8109,"precincts":
{"total":42,"reporting":39},
"name":"Columbia"},
"Schuylkill":
{"votes":[
{"votes":4962,"name":"clinton"},
{"votes":1590,"name":"obama"}],
"total":6552,"precincts":
{"total":167,"reporting":63},
"name":"Schuylkill"},
"Centre":
{"votes":[
{"votes":398,"name":"clinton"},
{"votes":284,"name":"obama"}],
"total":682,"precincts":
{"total":89,"reporting":6},
"name":"Centre"},
"Crawford":
{"votes":[
{"votes":1706,"name":"clinton"},
{"votes":998,"name":"obama"}],
"total":2704,"precincts":
{"total":67,"reporting":24},
"name":"Crawford"},
"Blair":
{"votes":[
{"votes":6320,"name":"clinton"},
{"votes":3439,"name":"obama"}],
"total":9759,"precincts":
{"total":97,"reporting":75},
"name":"Blair"},
"Fayette":
{"votes":[
{"votes":2925,"name":"clinton"},
{"votes":743,"name":"obama"}],
"total":3668,"precincts":
{"total":105,"reporting":10},
"name":"Fayette"},
"Cambria":
{"votes":[
{"votes":11526,"name":"clinton"},
{"votes":4401,"name":"obama"}],
"total":15927,"precincts":
{"total":165,"reporting":95},
"name":"Cambria"},
"York":
{"votes":[
{"votes":1856,"name":"obama"},
{"votes":1837,"name":"clinton"}],
"total":3693,"precincts":
{"total":159,"reporting":13},
"name":"York"},
"Franklin":
{"votes":[
{"votes":492,"name":"clinton"},
{"votes":229,"name":"obama"}],
"total":721,"precincts":
{"total":74,"reporting":10},
"name":"Franklin"},
"Lebanon":
{"votes":[
{"votes":4831,"name":"clinton"},
{"votes":3704,"name":"obama"}],
"total":8535,"precincts":
{"total":55,"reporting":39},
"name":"Lebanon"},
"Carbon":
{"votes":[
{"votes":2510,"name":"clinton"},
{"votes":770,"name":"obama"}],
"total":3280,"precincts":
{"total":45,"reporting":18},
"name":"Carbon"},
"Venango":
{"votes":[
{"votes":1040,"name":"clinton"},
{"votes":417,"name":"obama"}],
"total":1457,"precincts":
{"total":48,"reporting":17},
"name":"Venango"},
"Bradford":
{"votes":[
{"votes":72,"name":"clinton"},
{"votes":37,"name":"obama"}],
"total":109,"precincts":
{"total":61,"reporting":1},
"name":"Bradford"},
"Pike":
{"votes":[
{"votes":90,"name":"clinton"},
{"votes":67,"name":"obama"}],
"total":157,"precincts":
{"total":18,"reporting":1},
"name":"Pike"},
"Bucks":
{"votes":[
{"votes":4043,"name":"clinton"},
{"votes":1971,"name":"obama"}],
"total":6014,"precincts":
{"total":301,"reporting":19},
"name":"Bucks"},
"Wyoming":
{"votes":[
{"votes":2130,"name":"clinton"},
{"votes":930,"name":"obama"}],
"total":3060,"precincts":
{"total":31,"reporting":30},
"name":"Wyoming"},
"Adams":
{"votes":[
{"votes":1045,"name":"clinton"},
{"votes":716,"name":"obama"}],
"total":1761,"precincts":
{"total":48,"reporting":10},
"name":"Adams"},
"Bedford":
{"votes":[
{"votes":1353,"name":"clinton"},
{"votes":660,"name":"obama"}],
"total":2013,"precincts":
{"total":40,"reporting":18},
"name":"Bedford"},
"Clearfield":
{"votes":[
{"votes":3547,"name":"clinton"},
{"votes":1571,"name":"obama"}],
"total":5118,"precincts":
{"total":71,"reporting":32},
"name":"Clearfield"},
"Northumberland":
{"votes":[
{"votes":7322,"name":"clinton"},
{"votes":2884,"name":"obama"}],
"total":10206,"precincts":
{"total":94,"reporting":86},
"name":"Northumberland"},
"Clarion":
{"votes":[
{"votes":1923,"name":"clinton"},
{"votes":960,"name":"obama"}],
"total":2883,"precincts":
{"total":41,"reporting":25},
"name":"Clarion"},
"Greene":
{"votes":[
{"votes":3855,"name":"clinton"},
{"votes":1320,"name":"obama"}],
"total":5175,"precincts":
{"total":44,"reporting":34},
"name":"Greene"},
"Washington":
{"votes":[
{"votes":8676,"name":"clinton"},
{"votes":3577,"name":"obama"}],
"total":12253,"precincts":
{"total":185,"reporting":60},
"name":"Washington"},
"Westmoreland":
{"votes":[
{"votes":7330,"name":"clinton"},
{"votes":3157,"name":"obama"}],
"total":10487,"precincts":
{"total":306,"reporting":61},
"name":"Westmoreland"},
"Snyder":
{"votes":[
{"votes":121,"name":"clinton"},
{"votes":61,"name":"obama"}],
"total":182,"precincts":
{"total":25,"reporting":3},
"name":"Snyder"},
"Berks":
{"votes":[
{"votes":11429,"name":"clinton"},
{"votes":8536,"name":"obama"}],
"total":19965,"precincts":
{"total":193,"reporting":75},
"name":"Berks"},
"Fulton":
{"votes":[
{"votes":3,"name":"clinton"},
{"votes":1,"name":"obama"}],
"total":4,"precincts":
{"total":13,"reporting":1},
"name":"Fulton"},
"Lackawanna":
{"votes":[
{"votes":4678,"name":"clinton"},
{"votes":1333,"name":"obama"}],
"total":6011,"precincts":
{"total":163,"reporting":21},
"name":"Lackawanna"},
"Erie":
{"votes":[
{"votes":21606,"name":"clinton"},
{"votes":13373,"name":"obama"}],
"total":34979,"precincts":
{"total":155,"reporting":65},
"name":"Erie"},
"Clinton":
{"votes":[
{"votes":1610,"name":"clinton"},
{"votes":679,"name":"obama"}],
"total":2289,"precincts":
{"total":36,"reporting":18},
"name":"Clinton"},
"Armstrong":
{"votes":[
{"votes":4094,"name":"clinton"},
{"votes":1894,"name":"obama"}],
"total":5988,"precincts":
{"total":74,"reporting":53},
"name":"Armstrong"},
"Luzerne":
{"votes":[
{"votes":40960,"name":"clinton"},
{"votes":13207,"name":"obama"}],
"total":54167,"precincts":
{"total":189,"reporting":161},
"name":"Luzerne"},
"Lycoming":
{"votes":[
{"votes":5421,"name":"clinton"},
{"votes":3952,"name":"obama"}],
"total":9373,"precincts":
{"total":86,"reporting":62},
"name":"Lycoming"},
"Huntingdon":
{"votes":[
{"votes":818,"name":"clinton"},
{"votes":642,"name":"obama"}],
"total":1460,"precincts":
{"total":58,"reporting":19},
"name":"Huntingdon"},
"Northampton":
{"votes":[
{"votes":1671,"name":"clinton"},
{"votes":1268,"name":"obama"}],
"total":2939,"precincts":
{"total":149,"reporting":14},
"name":"Northampton"},
"Mifflin":
{"votes":[
{"votes":1312,"name":"clinton"},
{"votes":571,"name":"obama"}],
"total":1883,"precincts":
{"total":30,"reporting":15},
"name":"Mifflin"},
"Sullivan":
{"votes":[
{"votes":9,"name":"obama"},
{"votes":8,"name":"clinton"}],
"total":17,"precincts":
{"total":15,"reporting":1},
"name":"Sullivan"},
"Chester":
{"votes":[],
"total":0,"precincts":
{"total":224,"reporting":0},
"name":"Chester"},
"Lehigh":
{"votes":[
{"votes":3190,"name":"clinton"},
{"votes":1973,"name":"obama"}],
"total":5163,"precincts":
{"total":151,"reporting":19},
"name":"Lehigh"},
"Wayne":
{"votes":[
{"votes":226,"name":"clinton"},
{"votes":194,"name":"obama"}],
"total":420,"precincts":
{"total":37,"reporting":6},
"name":"Wayne"},
"Cameron":
{"votes":[
{"votes":110,"name":"clinton"},
{"votes":62,"name":"obama"}],
"total":172,"precincts":
{"total":10,"reporting":4},
"name":"Cameron"},
"Beaver":
{"votes":[
{"votes":11644,"name":"clinton"},
{"votes":4358,"name":"obama"}],
"total":16002,"precincts":
{"total":129,"reporting":60},
"name":"Beaver"},
"Allegheny":
{"votes":[
{"votes":114807,"name":"clinton"},
{"votes":90239,"name":"obama"}],
"total":205046,"precincts":
{"total":1321,"reporting":941},
"name":"Allegheny"},
"McKean":
{"votes":[
{"votes":20,"name":"clinton"},
{"votes":19,"name":"obama"}],
"total":39,"precincts":
{"total":42,"reporting":1},
"name":"McKean"},
"Mercer":
{"votes":[
{"votes":2468,"name":"clinton"},
{"votes":1080,"name":"obama"}],
"total":3548,"precincts":
{"total":100,"reporting":22},
"name":"Mercer"},
"Monroe":
{"votes":[
{"votes":1400,"name":"clinton"},
{"votes":1010,"name":"obama"}],
"total":2410,"precincts":
{"total":50,"reporting":10},
"name":"Monroe"},
"Warren":
{"votes":[
{"votes":2730,"name":"clinton"},
{"votes":1322,"name":"obama"}],
"total":4052,"precincts":
{"total":33,"reporting":27},
"name":"Warren"}}})