GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":268262,"name":"mccain"},
{"votes":58378,"name":"paul"},
{"votes":44829,"name":"huckabee"}],
"name":"Pennsylvania","precincts":
{"total":9268,"reporting":5613},
"delegates":74,"date":"04-22"},
"state":"PA","party":"gop","total":371469,"locals":
{"Lancaster":
{"votes":[
{"votes":2494,"name":"mccain"},
{"votes":840,"name":"paul"},
{"votes":386,"name":"huckabee"}],
"total":3720,"precincts":
{"total":234,"reporting":33},
"name":"Lancaster"},
"Elk":
{"votes":[
{"votes":2025,"name":"mccain"},
{"votes":387,"name":"huckabee"},
{"votes":303,"name":"paul"}],
"total":2715,"precincts":
{"total":32,"reporting":32},
"name":"Elk"},
"Perry":
{"votes":[
{"votes":876,"name":"mccain"},
{"votes":323,"name":"paul"},
{"votes":175,"name":"huckabee"}],
"total":1374,"precincts":
{"total":32,"reporting":11},
"name":"Perry"},
"Cumberland":
{"votes":[
{"votes":10969,"name":"mccain"},
{"votes":3189,"name":"paul"},
{"votes":1692,"name":"huckabee"}],
"total":15850,"precincts":
{"total":101,"reporting":79},
"name":"Cumberland"},
"Susquehanna":
{"votes":[
{"votes":525,"name":"mccain"},
{"votes":145,"name":"huckabee"},
{"votes":134,"name":"paul"}],
"total":804,"precincts":
{"total":43,"reporting":10},
"name":"Susquehanna"},
"Union":
{"votes":[
{"votes":1044,"name":"mccain"},
{"votes":235,"name":"huckabee"},
{"votes":168,"name":"paul"}],
"total":1447,"precincts":
{"total":27,"reporting":8},
"name":"Union"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Potter"},
"Delaware":
{"votes":[
{"votes":14428,"name":"mccain"},
{"votes":2478,"name":"paul"},
{"votes":1083,"name":"huckabee"}],
"total":17989,"precincts":
{"total":425,"reporting":151},
"name":"Delaware"},
"Philadelphia":
{"votes":[
{"votes":16650,"name":"mccain"},
{"votes":2927,"name":"paul"},
{"votes":1315,"name":"huckabee"}],
"total":20892,"precincts":
{"total":1681,"reporting":1517},
"name":"Philadelphia"},
"Montgomery":
{"votes":[
{"votes":6639,"name":"mccain"},
{"votes":1275,"name":"paul"},
{"votes":710,"name":"huckabee"}],
"total":8624,"precincts":
{"total":413,"reporting":57},
"name":"Montgomery"},
"Lawrence":
{"votes":[
{"votes":4053,"name":"mccain"},
{"votes":803,"name":"huckabee"},
{"votes":627,"name":"paul"}],
"total":5483,"precincts":
{"total":106,"reporting":101},
"name":"Lawrence"},
"Jefferson":
{"votes":[
{"votes":3701,"name":"mccain"},
{"votes":813,"name":"huckabee"},
{"votes":528,"name":"paul"}],
"total":5042,"precincts":
{"total":37,"reporting":37},
"name":"Jefferson"},
"Forest":
{"votes":[
{"votes":406,"name":"mccain"},
{"votes":82,"name":"paul"},
{"votes":69,"name":"huckabee"}],
"total":557,"precincts":
{"total":9,"reporting":7},
"name":"Forest"},
"Butler":
{"votes":[
{"votes":6609,"name":"mccain"},
{"votes":1331,"name":"paul"},
{"votes":1243,"name":"huckabee"}],
"total":9183,"precincts":
{"total":85,"reporting":59},
"name":"Butler"},
"Indiana":
{"votes":[
{"votes":575,"name":"mccain"},
{"votes":135,"name":"huckabee"},
{"votes":105,"name":"paul"}],
"total":815,"precincts":
{"total":69,"reporting":17},
"name":"Indiana"},
"Somerset":
{"votes":[
{"votes":4453,"name":"mccain"},
{"votes":931,"name":"huckabee"},
{"votes":897,"name":"paul"}],
"total":6281,"precincts":
{"total":68,"reporting":43},
"name":"Somerset"},
"Dauphin":
{"votes":[
{"votes":5691,"name":"mccain"},
{"votes":1655,"name":"paul"},
{"votes":969,"name":"huckabee"}],
"total":8315,"precincts":
{"total":159,"reporting":71},
"name":"Dauphin"},
"Juniata":
{"votes":[
{"votes":1176,"name":"mccain"},
{"votes":556,"name":"paul"},
{"votes":268,"name":"huckabee"}],
"total":2000,"precincts":
{"total":20,"reporting":16},
"name":"Juniata"},
"Tioga":
{"votes":[
{"votes":1904,"name":"mccain"},
{"votes":467,"name":"paul"},
{"votes":351,"name":"huckabee"}],
"total":2722,"precincts":
{"total":43,"reporting":23},
"name":"Tioga"},
"Montour":
{"votes":[
{"votes":521,"name":"mccain"},
{"votes":93,"name":"huckabee"},
{"votes":92,"name":"paul"}],
"total":706,"precincts":
{"total":15,"reporting":9},
"name":"Montour"},
"Columbia":
{"votes":[
{"votes":3006,"name":"mccain"},
{"votes":813,"name":"paul"},
{"votes":632,"name":"huckabee"}],
"total":4451,"precincts":
{"total":42,"reporting":42},
"name":"Columbia"},
"Schuylkill":
{"votes":[
{"votes":3788,"name":"mccain"},
{"votes":668,"name":"paul"},
{"votes":562,"name":"huckabee"}],
"total":5018,"precincts":
{"total":167,"reporting":97},
"name":"Schuylkill"},
"Centre":
{"votes":[
{"votes":2879,"name":"mccain"},
{"votes":587,"name":"paul"},
{"votes":568,"name":"huckabee"}],
"total":4034,"precincts":
{"total":89,"reporting":34},
"name":"Centre"},
"Crawford":
{"votes":[
{"votes":1104,"name":"mccain"},
{"votes":430,"name":"paul"},
{"votes":307,"name":"huckabee"}],
"total":1841,"precincts":
{"total":67,"reporting":24},
"name":"Crawford"},
"Blair":
{"votes":[
{"votes":6043,"name":"mccain"},
{"votes":1450,"name":"huckabee"},
{"votes":1167,"name":"paul"}],
"total":8660,"precincts":
{"total":97,"reporting":75},
"name":"Blair"},
"Fayette":
{"votes":[
{"votes":497,"name":"mccain"},
{"votes":101,"name":"paul"},
{"votes":85,"name":"huckabee"}],
"total":683,"precincts":
{"total":105,"reporting":20},
"name":"Fayette"},
"Cambria":
{"votes":[
{"votes":5372,"name":"mccain"},
{"votes":1145,"name":"huckabee"},
{"votes":906,"name":"paul"}],
"total":7423,"precincts":
{"total":165,"reporting":147},
"name":"Cambria"},
"York":
{"votes":[
{"votes":5254,"name":"mccain"},
{"votes":1353,"name":"paul"},
{"votes":920,"name":"huckabee"}],
"total":7527,"precincts":
{"total":159,"reporting":50},
"name":"York"},
"Franklin":
{"votes":[
{"votes":3132,"name":"mccain"},
{"votes":786,"name":"huckabee"},
{"votes":484,"name":"paul"}],
"total":4402,"precincts":
{"total":74,"reporting":32},
"name":"Franklin"},
"Lebanon":
{"votes":[
{"votes":6441,"name":"mccain"},
{"votes":1894,"name":"paul"},
{"votes":1486,"name":"huckabee"}],
"total":9821,"precincts":
{"total":55,"reporting":44},
"name":"Lebanon"},
"Carbon":
{"votes":[
{"votes":1486,"name":"mccain"},
{"votes":280,"name":"paul"},
{"votes":279,"name":"huckabee"}],
"total":2045,"precincts":
{"total":45,"reporting":33},
"name":"Carbon"},
"Venango":
{"votes":[
{"votes":2942,"name":"mccain"},
{"votes":915,"name":"huckabee"},
{"votes":911,"name":"paul"}],
"total":4768,"precincts":
{"total":48,"reporting":40},
"name":"Venango"},
"Bradford":
{"votes":[
{"votes":594,"name":"mccain"},
{"votes":112,"name":"huckabee"},
{"votes":86,"name":"paul"}],
"total":792,"precincts":
{"total":61,"reporting":8},
"name":"Bradford"},
"Pike":
{"votes":[
{"votes":456,"name":"mccain"},
{"votes":67,"name":"paul"},
{"votes":40,"name":"huckabee"}],
"total":563,"precincts":
{"total":18,"reporting":4},
"name":"Pike"},
"Bucks":
{"votes":[
{"votes":4964,"name":"mccain"},
{"votes":1025,"name":"paul"},
{"votes":588,"name":"huckabee"}],
"total":6577,"precincts":
{"total":301,"reporting":64},
"name":"Bucks"},
"Wyoming":
{"votes":[
{"votes":2523,"name":"mccain"},
{"votes":676,"name":"paul"},
{"votes":556,"name":"huckabee"}],
"total":3755,"precincts":
{"total":31,"reporting":31},
"name":"Wyoming"},
"Adams":
{"votes":[
{"votes":982,"name":"mccain"},
{"votes":258,"name":"paul"},
{"votes":197,"name":"huckabee"}],
"total":1437,"precincts":
{"total":48,"reporting":10},
"name":"Adams"},
"Bedford":
{"votes":[
{"votes":3044,"name":"mccain"},
{"votes":754,"name":"huckabee"},
{"votes":317,"name":"paul"}],
"total":4115,"precincts":
{"total":40,"reporting":27},
"name":"Bedford"},
"Clearfield":
{"votes":[
{"votes":4066,"name":"mccain"},
{"votes":971,"name":"huckabee"},
{"votes":633,"name":"paul"}],
"total":5670,"precincts":
{"total":71,"reporting":41},
"name":"Clearfield"},
"Northumberland":
{"votes":[
{"votes":5402,"name":"mccain"},
{"votes":1055,"name":"paul"},
{"votes":967,"name":"huckabee"}],
"total":7424,"precincts":
{"total":94,"reporting":94},
"name":"Northumberland"},
"Clarion":
{"votes":[
{"votes":2792,"name":"mccain"},
{"votes":649,"name":"huckabee"},
{"votes":593,"name":"paul"}],
"total":4034,"precincts":
{"total":41,"reporting":33},
"name":"Clarion"},
"Greene":
{"votes":[
{"votes":1383,"name":"mccain"},
{"votes":258,"name":"huckabee"},
{"votes":211,"name":"paul"}],
"total":1852,"precincts":
{"total":44,"reporting":44},
"name":"Greene"},
"Washington":
{"votes":[
{"votes":4519,"name":"mccain"},
{"votes":791,"name":"huckabee"},
{"votes":768,"name":"paul"}],
"total":6078,"precincts":
{"total":185,"reporting":112},
"name":"Washington"},
"Westmoreland":
{"votes":[
{"votes":5058,"name":"mccain"},
{"votes":959,"name":"paul"},
{"votes":846,"name":"huckabee"}],
"total":6863,"precincts":
{"total":306,"reporting":118},
"name":"Westmoreland"},
"Snyder":
{"votes":[
{"votes":659,"name":"mccain"},
{"votes":193,"name":"huckabee"},
{"votes":128,"name":"paul"}],
"total":980,"precincts":
{"total":25,"reporting":7},
"name":"Snyder"},
"Berks":
{"votes":[
{"votes":9382,"name":"mccain"},
{"votes":3874,"name":"paul"},
{"votes":1493,"name":"huckabee"}],
"total":14749,"precincts":
{"total":193,"reporting":134},
"name":"Berks"},
"Fulton":
{"votes":[
{"votes":484,"name":"mccain"},
{"votes":132,"name":"huckabee"},
{"votes":50,"name":"paul"}],
"total":666,"precincts":
{"total":13,"reporting":7},
"name":"Fulton"},
"Lackawanna":
{"votes":[
{"votes":2705,"name":"mccain"},
{"votes":469,"name":"paul"},
{"votes":377,"name":"huckabee"}],
"total":3551,"precincts":
{"total":163,"reporting":75},
"name":"Lackawanna"},
"Erie":
{"votes":[
{"votes":9862,"name":"mccain"},
{"votes":2321,"name":"paul"},
{"votes":2117,"name":"huckabee"}],
"total":14300,"precincts":
{"total":155,"reporting":98},
"name":"Erie"},
"Clinton":
{"votes":[
{"votes":1686,"name":"mccain"},
{"votes":317,"name":"huckabee"},
{"votes":266,"name":"paul"}],
"total":2269,"precincts":
{"total":36,"reporting":24},
"name":"Clinton"},
"Armstrong":
{"votes":[
{"votes":4007,"name":"mccain"},
{"votes":756,"name":"paul"},
{"votes":729,"name":"huckabee"}],
"total":5492,"precincts":
{"total":74,"reporting":71},
"name":"Armstrong"},
"Luzerne":
{"votes":[
{"votes":11782,"name":"mccain"},
{"votes":2688,"name":"paul"},
{"votes":1640,"name":"huckabee"}],
"total":16110,"precincts":
{"total":189,"reporting":176},
"name":"Luzerne"},
"Lycoming":
{"votes":[
{"votes":10317,"name":"mccain"},
{"votes":1702,"name":"paul"},
{"votes":1580,"name":"huckabee"}],
"total":13599,"precincts":
{"total":86,"reporting":80},
"name":"Lycoming"},
"Huntingdon":
{"votes":[
{"votes":1932,"name":"mccain"},
{"votes":534,"name":"huckabee"},
{"votes":310,"name":"paul"}],
"total":2776,"precincts":
{"total":58,"reporting":45},
"name":"Huntingdon"},
"Northampton":
{"votes":[
{"votes":4793,"name":"mccain"},
{"votes":1279,"name":"paul"},
{"votes":645,"name":"huckabee"}],
"total":6717,"precincts":
{"total":149,"reporting":96},
"name":"Northampton"},
"Mifflin":
{"votes":[
{"votes":2269,"name":"mccain"},
{"votes":478,"name":"huckabee"},
{"votes":316,"name":"paul"}],
"total":3063,"precincts":
{"total":30,"reporting":25},
"name":"Mifflin"},
"Sullivan":
{"votes":[
{"votes":253,"name":"mccain"},
{"votes":50,"name":"huckabee"},
{"votes":44,"name":"paul"}],
"total":347,"precincts":
{"total":15,"reporting":6},
"name":"Sullivan"},
"Chester":
{"votes":[],
"total":0,"precincts":
{"total":224,"reporting":0},
"name":"Chester"},
"Lehigh":
{"votes":[
{"votes":2085,"name":"mccain"},
{"votes":437,"name":"paul"},
{"votes":253,"name":"huckabee"}],
"total":2775,"precincts":
{"total":151,"reporting":44},
"name":"Lehigh"},
"Wayne":
{"votes":[
{"votes":874,"name":"mccain"},
{"votes":137,"name":"huckabee"},
{"votes":127,"name":"paul"}],
"total":1138,"precincts":
{"total":37,"reporting":12},
"name":"Wayne"},
"Cameron":
{"votes":[
{"votes":498,"name":"mccain"},
{"votes":102,"name":"huckabee"},
{"votes":42,"name":"paul"}],
"total":642,"precincts":
{"total":10,"reporting":10},
"name":"Cameron"},
"Beaver":
{"votes":[
{"votes":5618,"name":"mccain"},
{"votes":1298,"name":"paul"},
{"votes":1040,"name":"huckabee"}],
"total":7956,"precincts":
{"total":129,"reporting":105},
"name":"Beaver"},
"Allegheny":
{"votes":[
{"votes":26352,"name":"mccain"},
{"votes":5894,"name":"paul"},
{"votes":3203,"name":"huckabee"}],
"total":35449,"precincts":
{"total":1321,"reporting":941},
"name":"Allegheny"},
"McKean":
{"votes":[
{"votes":444,"name":"mccain"},
{"votes":96,"name":"paul"},
{"votes":59,"name":"huckabee"}],
"total":599,"precincts":
{"total":42,"reporting":8},
"name":"McKean"},
"Mercer":
{"votes":[
{"votes":5473,"name":"mccain"},
{"votes":1336,"name":"huckabee"},
{"votes":1116,"name":"paul"}],
"total":7925,"precincts":
{"total":100,"reporting":88},
"name":"Mercer"},
"Monroe":
{"votes":[
{"votes":2004,"name":"mccain"},
{"votes":434,"name":"paul"},
{"votes":280,"name":"huckabee"}],
"total":2718,"precincts":
{"total":50,"reporting":29},
"name":"Monroe"},
"Warren":
{"votes":[
{"votes":2317,"name":"mccain"},
{"votes":512,"name":"paul"},
{"votes":467,"name":"huckabee"}],
"total":3296,"precincts":
{"total":33,"reporting":27},
"name":"Warren"}}})