GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":343763,"name":"mccain"},
{"votes":75440,"name":"paul"},
{"votes":56073,"name":"huckabee"}],
"name":"Pennsylvania","precincts":
{"total":9268,"reporting":6699},
"delegates":74,"date":"04-22"},
"state":"PA","party":"gop","total":475276,"locals":
{"Lancaster":
{"votes":[
{"votes":6898,"name":"mccain"},
{"votes":2208,"name":"paul"},
{"votes":1058,"name":"huckabee"}],
"total":10164,"precincts":
{"total":234,"reporting":70},
"name":"Lancaster"},
"Elk":
{"votes":[
{"votes":2025,"name":"mccain"},
{"votes":387,"name":"huckabee"},
{"votes":303,"name":"paul"}],
"total":2715,"precincts":
{"total":32,"reporting":32},
"name":"Elk"},
"Perry":
{"votes":[
{"votes":876,"name":"mccain"},
{"votes":323,"name":"paul"},
{"votes":175,"name":"huckabee"}],
"total":1374,"precincts":
{"total":32,"reporting":11},
"name":"Perry"},
"Cumberland":
{"votes":[
{"votes":13904,"name":"mccain"},
{"votes":3912,"name":"paul"},
{"votes":2089,"name":"huckabee"}],
"total":19905,"precincts":
{"total":101,"reporting":92},
"name":"Cumberland"},
"Susquehanna":
{"votes":[
{"votes":1272,"name":"mccain"},
{"votes":270,"name":"paul"},
{"votes":145,"name":"huckabee"}],
"total":1687,"precincts":
{"total":43,"reporting":21},
"name":"Susquehanna"},
"Union":
{"votes":[
{"votes":1044,"name":"mccain"},
{"votes":235,"name":"huckabee"},
{"votes":168,"name":"paul"}],
"total":1447,"precincts":
{"total":27,"reporting":8},
"name":"Union"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":33,"reporting":0},
"name":"Potter"},
"Delaware":
{"votes":[
{"votes":30518,"name":"mccain"},
{"votes":5246,"name":"paul"},
{"votes":2554,"name":"huckabee"}],
"total":38318,"precincts":
{"total":425,"reporting":320},
"name":"Delaware"},
"Philadelphia":
{"votes":[
{"votes":16902,"name":"mccain"},
{"votes":3014,"name":"paul"},
{"votes":1355,"name":"huckabee"}],
"total":21271,"precincts":
{"total":1681,"reporting":1615},
"name":"Philadelphia"},
"Montgomery":
{"votes":[
{"votes":6639,"name":"mccain"},
{"votes":1275,"name":"paul"},
{"votes":710,"name":"huckabee"}],
"total":8624,"precincts":
{"total":413,"reporting":57},
"name":"Montgomery"},
"Lawrence":
{"votes":[
{"votes":4053,"name":"mccain"},
{"votes":803,"name":"huckabee"},
{"votes":627,"name":"paul"}],
"total":5483,"precincts":
{"total":106,"reporting":101},
"name":"Lawrence"},
"Jefferson":
{"votes":[
{"votes":3701,"name":"mccain"},
{"votes":813,"name":"huckabee"},
{"votes":528,"name":"paul"}],
"total":5042,"precincts":
{"total":37,"reporting":37},
"name":"Jefferson"},
"Forest":
{"votes":[
{"votes":406,"name":"mccain"},
{"votes":82,"name":"paul"},
{"votes":69,"name":"huckabee"}],
"total":557,"precincts":
{"total":9,"reporting":7},
"name":"Forest"},
"Butler":
{"votes":[
{"votes":9342,"name":"mccain"},
{"votes":1790,"name":"paul"},
{"votes":1665,"name":"huckabee"}],
"total":12797,"precincts":
{"total":85,"reporting":74},
"name":"Butler"},
"Indiana":
{"votes":[
{"votes":2081,"name":"mccain"},
{"votes":464,"name":"huckabee"},
{"votes":381,"name":"paul"}],
"total":2926,"precincts":
{"total":69,"reporting":41},
"name":"Indiana"},
"Somerset":
{"votes":[
{"votes":4453,"name":"mccain"},
{"votes":931,"name":"huckabee"},
{"votes":897,"name":"paul"}],
"total":6281,"precincts":
{"total":68,"reporting":43},
"name":"Somerset"},
"Dauphin":
{"votes":[
{"votes":5691,"name":"mccain"},
{"votes":1655,"name":"paul"},
{"votes":969,"name":"huckabee"}],
"total":8315,"precincts":
{"total":159,"reporting":71},
"name":"Dauphin"},
"Juniata":
{"votes":[
{"votes":1176,"name":"mccain"},
{"votes":556,"name":"paul"},
{"votes":268,"name":"huckabee"}],
"total":2000,"precincts":
{"total":20,"reporting":16},
"name":"Juniata"},
"Tioga":
{"votes":[
{"votes":1904,"name":"mccain"},
{"votes":467,"name":"paul"},
{"votes":351,"name":"huckabee"}],
"total":2722,"precincts":
{"total":43,"reporting":23},
"name":"Tioga"},
"Montour":
{"votes":[
{"votes":521,"name":"mccain"},
{"votes":93,"name":"huckabee"},
{"votes":92,"name":"paul"}],
"total":706,"precincts":
{"total":15,"reporting":9},
"name":"Montour"},
"Columbia":
{"votes":[
{"votes":3006,"name":"mccain"},
{"votes":813,"name":"paul"},
{"votes":632,"name":"huckabee"}],
"total":4451,"precincts":
{"total":42,"reporting":42},
"name":"Columbia"},
"Schuylkill":
{"votes":[
{"votes":6095,"name":"mccain"},
{"votes":1106,"name":"paul"},
{"votes":934,"name":"huckabee"}],
"total":8135,"precincts":
{"total":167,"reporting":129},
"name":"Schuylkill"},
"Centre":
{"votes":[
{"votes":2879,"name":"mccain"},
{"votes":587,"name":"paul"},
{"votes":568,"name":"huckabee"}],
"total":4034,"precincts":
{"total":89,"reporting":34},
"name":"Centre"},
"Crawford":
{"votes":[
{"votes":3033,"name":"mccain"},
{"votes":1097,"name":"paul"},
{"votes":749,"name":"huckabee"}],
"total":4879,"precincts":
{"total":67,"reporting":48},
"name":"Crawford"},
"Blair":
{"votes":[
{"votes":8275,"name":"mccain"},
{"votes":1943,"name":"huckabee"},
{"votes":1552,"name":"paul"}],
"total":11770,"precincts":
{"total":97,"reporting":97},
"name":"Blair"},
"Fayette":
{"votes":[
{"votes":497,"name":"mccain"},
{"votes":101,"name":"paul"},
{"votes":85,"name":"huckabee"}],
"total":683,"precincts":
{"total":105,"reporting":20},
"name":"Fayette"},
"Cambria":
{"votes":[
{"votes":5372,"name":"mccain"},
{"votes":1145,"name":"huckabee"},
{"votes":906,"name":"paul"}],
"total":7423,"precincts":
{"total":165,"reporting":147},
"name":"Cambria"},
"York":
{"votes":[
{"votes":11835,"name":"mccain"},
{"votes":3160,"name":"paul"},
{"votes":1916,"name":"huckabee"}],
"total":16911,"precincts":
{"total":159,"reporting":98},
"name":"York"},
"Franklin":
{"votes":[
{"votes":4286,"name":"mccain"},
{"votes":1052,"name":"huckabee"},
{"votes":688,"name":"paul"}],
"total":6026,"precincts":
{"total":74,"reporting":41},
"name":"Franklin"},
"Lebanon":
{"votes":[
{"votes":8074,"name":"mccain"},
{"votes":2312,"name":"paul"},
{"votes":1809,"name":"huckabee"}],
"total":12195,"precincts":
{"total":55,"reporting":50},
"name":"Lebanon"},
"Carbon":
{"votes":[
{"votes":1486,"name":"mccain"},
{"votes":280,"name":"paul"},
{"votes":279,"name":"huckabee"}],
"total":2045,"precincts":
{"total":45,"reporting":33},
"name":"Carbon"},
"Venango":
{"votes":[
{"votes":2942,"name":"mccain"},
{"votes":915,"name":"huckabee"},
{"votes":911,"name":"paul"}],
"total":4768,"precincts":
{"total":48,"reporting":40},
"name":"Venango"},
"Bradford":
{"votes":[
{"votes":2850,"name":"mccain"},
{"votes":525,"name":"huckabee"},
{"votes":464,"name":"paul"}],
"total":3839,"precincts":
{"total":61,"reporting":35},
"name":"Bradford"},
"Pike":
{"votes":[
{"votes":456,"name":"mccain"},
{"votes":67,"name":"paul"},
{"votes":40,"name":"huckabee"}],
"total":563,"precincts":
{"total":18,"reporting":4},
"name":"Pike"},
"Bucks":
{"votes":[
{"votes":4964,"name":"mccain"},
{"votes":1025,"name":"paul"},
{"votes":588,"name":"huckabee"}],
"total":6577,"precincts":
{"total":301,"reporting":64},
"name":"Bucks"},
"Wyoming":
{"votes":[
{"votes":2523,"name":"mccain"},
{"votes":676,"name":"paul"},
{"votes":556,"name":"huckabee"}],
"total":3755,"precincts":
{"total":31,"reporting":31},
"name":"Wyoming"},
"Adams":
{"votes":[
{"votes":4683,"name":"mccain"},
{"votes":1230,"name":"paul"},
{"votes":860,"name":"huckabee"}],
"total":6773,"precincts":
{"total":48,"reporting":38},
"name":"Adams"},
"Bedford":
{"votes":[
{"votes":3044,"name":"mccain"},
{"votes":754,"name":"huckabee"},
{"votes":317,"name":"paul"}],
"total":4115,"precincts":
{"total":40,"reporting":27},
"name":"Bedford"},
"Clearfield":
{"votes":[
{"votes":5114,"name":"mccain"},
{"votes":1242,"name":"huckabee"},
{"votes":794,"name":"paul"}],
"total":7150,"precincts":
{"total":71,"reporting":62},
"name":"Clearfield"},
"Northumberland":
{"votes":[
{"votes":5402,"name":"mccain"},
{"votes":1055,"name":"paul"},
{"votes":967,"name":"huckabee"}],
"total":7424,"precincts":
{"total":94,"reporting":94},
"name":"Northumberland"},
"Clarion":
{"votes":[
{"votes":2792,"name":"mccain"},
{"votes":649,"name":"huckabee"},
{"votes":593,"name":"paul"}],
"total":4034,"precincts":
{"total":41,"reporting":33},
"name":"Clarion"},
"Greene":
{"votes":[
{"votes":1383,"name":"mccain"},
{"votes":258,"name":"huckabee"},
{"votes":211,"name":"paul"}],
"total":1852,"precincts":
{"total":44,"reporting":44},
"name":"Greene"},
"Washington":
{"votes":[
{"votes":5633,"name":"mccain"},
{"votes":1019,"name":"huckabee"},
{"votes":943,"name":"paul"}],
"total":7595,"precincts":
{"total":185,"reporting":141},
"name":"Washington"},
"Westmoreland":
{"votes":[
{"votes":8474,"name":"mccain"},
{"votes":1674,"name":"paul"},
{"votes":1448,"name":"huckabee"}],
"total":11596,"precincts":
{"total":306,"reporting":189},
"name":"Westmoreland"},
"Snyder":
{"votes":[
{"votes":659,"name":"mccain"},
{"votes":193,"name":"huckabee"},
{"votes":128,"name":"paul"}],
"total":980,"precincts":
{"total":25,"reporting":7},
"name":"Snyder"},
"Berks":
{"votes":[
{"votes":13166,"name":"mccain"},
{"votes":5401,"name":"paul"},
{"votes":2131,"name":"huckabee"}],
"total":20698,"precincts":
{"total":193,"reporting":177},
"name":"Berks"},
"Fulton":
{"votes":[
{"votes":484,"name":"mccain"},
{"votes":132,"name":"huckabee"},
{"votes":50,"name":"paul"}],
"total":666,"precincts":
{"total":13,"reporting":7},
"name":"Fulton"},
"Lackawanna":
{"votes":[
{"votes":2705,"name":"mccain"},
{"votes":469,"name":"paul"},
{"votes":377,"name":"huckabee"}],
"total":3551,"precincts":
{"total":163,"reporting":75},
"name":"Lackawanna"},
"Erie":
{"votes":[
{"votes":9862,"name":"mccain"},
{"votes":2321,"name":"paul"},
{"votes":2117,"name":"huckabee"}],
"total":14300,"precincts":
{"total":155,"reporting":98},
"name":"Erie"},
"Clinton":
{"votes":[
{"votes":1686,"name":"mccain"},
{"votes":317,"name":"huckabee"},
{"votes":266,"name":"paul"}],
"total":2269,"precincts":
{"total":36,"reporting":24},
"name":"Clinton"},
"Armstrong":
{"votes":[
{"votes":4303,"name":"mccain"},
{"votes":807,"name":"paul"},
{"votes":787,"name":"huckabee"}],
"total":5897,"precincts":
{"total":74,"reporting":74},
"name":"Armstrong"},
"Luzerne":
{"votes":[
{"votes":11782,"name":"mccain"},
{"votes":2688,"name":"paul"},
{"votes":1640,"name":"huckabee"}],
"total":16110,"precincts":
{"total":189,"reporting":176},
"name":"Luzerne"},
"Lycoming":
{"votes":[
{"votes":10614,"name":"mccain"},
{"votes":1754,"name":"paul"},
{"votes":1648,"name":"huckabee"}],
"total":14016,"precincts":
{"total":86,"reporting":82},
"name":"Lycoming"},
"Huntingdon":
{"votes":[
{"votes":1932,"name":"mccain"},
{"votes":534,"name":"huckabee"},
{"votes":310,"name":"paul"}],
"total":2776,"precincts":
{"total":58,"reporting":45},
"name":"Huntingdon"},
"Northampton":
{"votes":[
{"votes":4793,"name":"mccain"},
{"votes":1279,"name":"paul"},
{"votes":645,"name":"huckabee"}],
"total":6717,"precincts":
{"total":149,"reporting":96},
"name":"Northampton"},
"Mifflin":
{"votes":[
{"votes":2269,"name":"mccain"},
{"votes":478,"name":"huckabee"},
{"votes":316,"name":"paul"}],
"total":3063,"precincts":
{"total":30,"reporting":25},
"name":"Mifflin"},
"Sullivan":
{"votes":[
{"votes":253,"name":"mccain"},
{"votes":50,"name":"huckabee"},
{"votes":44,"name":"paul"}],
"total":347,"precincts":
{"total":15,"reporting":6},
"name":"Sullivan"},
"Chester":
{"votes":[],
"total":0,"precincts":
{"total":224,"reporting":0},
"name":"Chester"},
"Lehigh":
{"votes":[
{"votes":3380,"name":"mccain"},
{"votes":740,"name":"paul"},
{"votes":450,"name":"huckabee"}],
"total":4570,"precincts":
{"total":151,"reporting":68},
"name":"Lehigh"},
"Wayne":
{"votes":[
{"votes":874,"name":"mccain"},
{"votes":137,"name":"huckabee"},
{"votes":127,"name":"paul"}],
"total":1138,"precincts":
{"total":37,"reporting":12},
"name":"Wayne"},
"Cameron":
{"votes":[
{"votes":498,"name":"mccain"},
{"votes":102,"name":"huckabee"},
{"votes":42,"name":"paul"}],
"total":642,"precincts":
{"total":10,"reporting":10},
"name":"Cameron"},
"Beaver":
{"votes":[
{"votes":5618,"name":"mccain"},
{"votes":1298,"name":"paul"},
{"votes":1040,"name":"huckabee"}],
"total":7956,"precincts":
{"total":129,"reporting":105},
"name":"Beaver"},
"Allegheny":
{"votes":[
{"votes":38472,"name":"mccain"},
{"votes":8564,"name":"paul"},
{"votes":4746,"name":"huckabee"}],
"total":51782,"precincts":
{"total":1321,"reporting":1253},
"name":"Allegheny"},
"McKean":
{"votes":[
{"votes":444,"name":"mccain"},
{"votes":96,"name":"paul"},
{"votes":59,"name":"huckabee"}],
"total":599,"precincts":
{"total":42,"reporting":8},
"name":"McKean"},
"Mercer":
{"votes":[
{"votes":5902,"name":"mccain"},
{"votes":1455,"name":"huckabee"},
{"votes":1175,"name":"paul"}],
"total":8532,"precincts":
{"total":100,"reporting":100},
"name":"Mercer"},
"Monroe":
{"votes":[
{"votes":2004,"name":"mccain"},
{"votes":434,"name":"paul"},
{"votes":280,"name":"huckabee"}],
"total":2718,"precincts":
{"total":50,"reporting":29},
"name":"Monroe"},
"Warren":
{"votes":[
{"votes":3559,"name":"mccain"},
{"votes":775,"name":"paul"},
{"votes":688,"name":"huckabee"}],
"total":5022,"precincts":
{"total":33,"reporting":33},
"name":"Warren"}}})