GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":29583,"name":"clinton"},
{"votes":17179,"name":"obama"},
{"votes":349,"name":"edwards"},
{"votes":319,"name":"uncommitted-d"}],
"name":"Rhode Island","precincts":
{"total":179,"reporting":50},
"delegates":21,"date":"03-04"},
"state":"RI","party":"dem","total":47430,"locals":
{"Middletown":
{"votes":[
{"votes":840,"name":"clinton"},
{"votes":749,"name":"obama"},
{"votes":14,"name":"edwards"},
{"votes":10,"name":"uncommitted-d"}],
"total":1613,"precincts":
{"total":4,"reporting":2},
"name":"Middletown"},
"Cumberland":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Cumberland"},
"Hopkinton":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hopkinton"},
"Central Falls":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Central Falls"},
"Barrington":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Barrington"},
"Richmond":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Richmond"},
"Providence":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Providence"},
"Foster":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Foster"},
"Warwick":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Warwick"},
"Jamestown":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Jamestown"},
"Smithfield":
{"votes":[
{"votes":1977,"name":"clinton"},
{"votes":986,"name":"obama"},
{"votes":29,"name":"edwards"},
{"votes":15,"name":"uncommitted-d"}],
"total":3007,"precincts":
{"total":4,"reporting":3},
"name":"Smithfield"},
"Mail Ballots - CD2":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD2"},
"Cranston":
{"votes":[
{"votes":865,"name":"clinton"},
{"votes":491,"name":"obama"},
{"votes":13,"name":"edwards"},
{"votes":10,"name":"uncommitted-d"}],
"total":1379,"precincts":
{"total":10,"reporting":1},
"name":"Cranston"},
"East Providence":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"East Providence"},
"Mail Ballots - CD1":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD1"},
"Glocester":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Glocester"},
"Little Compton":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Little Compton"},
"West Greenwich":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"West Greenwich"},
"Charlestown":
{"votes":[
{"votes":203,"name":"obama"},
{"votes":202,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":1,"name":"uncommitted-d"}],
"total":409,"precincts":
{"total":3,"reporting":1},
"name":"Charlestown"},
"North Smithfield":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Smithfield"},
"Lincoln":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Lincoln"},
"Coventry":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Coventry"},
"South Kingstown":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"South Kingstown"},
"West Warwick":
{"votes":[
{"votes":1732,"name":"clinton"},
{"votes":798,"name":"obama"},
{"votes":22,"name":"edwards"},
{"votes":17,"name":"uncommitted-d"}],
"total":2569,"precincts":
{"total":5,"reporting":3},
"name":"West Warwick"},
"Burrillville":
{"votes":[
{"votes":1205,"name":"clinton"},
{"votes":584,"name":"obama"},
{"votes":18,"name":"uncommitted-d"},
{"votes":18,"name":"edwards"}],
"total":1825,"precincts":
{"total":4,"reporting":3},
"name":"Burrillville"},
"Newport":
{"votes":[
{"votes":1154,"name":"obama"},
{"votes":913,"name":"clinton"},
{"votes":13,"name":"uncommitted-d"},
{"votes":4,"name":"edwards"}],
"total":2084,"precincts":
{"total":4,"reporting":2},
"name":"Newport"},
"Bristol":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Bristol"},
"Johnston":
{"votes":[
{"votes":4581,"name":"clinton"},
{"votes":1368,"name":"obama"},
{"votes":51,"name":"uncommitted-d"},
{"votes":47,"name":"edwards"}],
"total":6047,"precincts":
{"total":5,"reporting":4},
"name":"Johnston"},
"Scituate":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Scituate"},
"New Shoreham":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"New Shoreham"},
"Exeter":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Exeter"},
"North Providence":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Providence"},
"Westerly":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Westerly"},
"North Kingstown":
{"votes":[
{"votes":1906,"name":"clinton"},
{"votes":1897,"name":"obama"},
{"votes":21,"name":"uncommitted-d"},
{"votes":18,"name":"edwards"}],
"total":3842,"precincts":
{"total":4,"reporting":3},
"name":"North Kingstown"},
"Portsmouth":
{"votes":[
{"votes":31,"name":"obama"},
{"votes":17,"name":"clinton"},
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"}],
"total":48,"precincts":
{"total":5,"reporting":1},
"name":"Portsmouth"},
"Narragansett":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Narragansett"},
"Tiverton":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Tiverton"},
"Woonsocket":
{"votes":[
{"votes":3233,"name":"clinton"},
{"votes":1595,"name":"obama"},
{"votes":44,"name":"edwards"},
{"votes":38,"name":"uncommitted-d"}],
"total":4910,"precincts":
{"total":8,"reporting":7},
"name":"Woonsocket"},
"East Greenwich":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"East Greenwich"},
"Pawtucket":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Pawtucket"},
"Warren":
{"votes":[
{"votes":0,"name":"uncommitted-d"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"clinton"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Warren"}}})