GoogleElectionMap.votesReady({"status":"ok","totals":
{"date":"03-04","votes":[
{"votes":17342,"name":"mccain"},
{"votes":5766,"name":"huckabee"},
{"votes":1761,"name":"paul"},
{"votes":1173,"name":"romney"},
{"votes":565,"name":"uncommitted-r"},
{"votes":114,"name":"keyes"},
{"votes":24,"name":"cort"}],
"precincts":
{"total":179,"reporting":176},
"name":"Rhode Island"},
"state":"RI","party":"gop","total":26745,"locals":
{"Middletown":
{"votes":[
{"votes":413,"name":"mccain"},
{"votes":106,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":23,"name":"romney"},
{"votes":13,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":590,"precincts":
{"total":4,"reporting":4},
"name":"Middletown"},
"Cumberland":
{"votes":[
{"votes":612,"name":"mccain"},
{"votes":166,"name":"huckabee"},
{"votes":58,"name":"paul"},
{"votes":52,"name":"romney"},
{"votes":13,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":904,"precincts":
{"total":5,"reporting":5},
"name":"Cumberland"},
"Hopkinton":
{"votes":[
{"votes":164,"name":"mccain"},
{"votes":94,"name":"huckabee"},
{"votes":22,"name":"paul"},
{"votes":8,"name":"uncommitted-r"},
{"votes":4,"name":"romney"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":293,"precincts":
{"total":1,"reporting":1},
"name":"Hopkinton"},
"Central Falls":
{"votes":[
{"votes":61,"name":"mccain"},
{"votes":18,"name":"huckabee"},
{"votes":8,"name":"uncommitted-r"},
{"votes":6,"name":"paul"},
{"votes":5,"name":"romney"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":100,"precincts":
{"total":5,"reporting":5},
"name":"Central Falls"},
"Barrington":
{"votes":[
{"votes":674,"name":"mccain"},
{"votes":177,"name":"huckabee"},
{"votes":41,"name":"romney"},
{"votes":39,"name":"paul"},
{"votes":18,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"cort"}],
"total":952,"precincts":
{"total":3,"reporting":3},
"name":"Barrington"},
"Richmond":
{"votes":[
{"votes":173,"name":"mccain"},
{"votes":77,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":11,"name":"romney"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":291,"precincts":
{"total":1,"reporting":1},
"name":"Richmond"},
"Providence":
{"votes":[
{"votes":600,"name":"mccain"},
{"votes":197,"name":"huckabee"},
{"votes":90,"name":"paul"},
{"votes":32,"name":"romney"},
{"votes":25,"name":"uncommitted-r"},
{"votes":6,"name":"keyes"},
{"votes":2,"name":"cort"}],
"total":952,"precincts":
{"total":31,"reporting":28},
"name":"Providence"},
"Foster":
{"votes":[
{"votes":101,"name":"mccain"},
{"votes":39,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":167,"precincts":
{"total":1,"reporting":1},
"name":"Foster"},
"Warwick":
{"votes":[
{"votes":1654,"name":"mccain"},
{"votes":614,"name":"huckabee"},
{"votes":157,"name":"paul"},
{"votes":119,"name":"romney"},
{"votes":55,"name":"uncommitted-r"},
{"votes":13,"name":"keyes"},
{"votes":2,"name":"cort"}],
"total":2614,"precincts":
{"total":9,"reporting":9},
"name":"Warwick"},
"Jamestown":
{"votes":[
{"votes":261,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":12,"name":"romney"},
{"votes":9,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":347,"precincts":
{"total":1,"reporting":1},
"name":"Jamestown"},
"Smithfield":
{"votes":[
{"votes":432,"name":"mccain"},
{"votes":191,"name":"huckabee"},
{"votes":45,"name":"romney"},
{"votes":45,"name":"paul"},
{"votes":9,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"cort"}],
"total":726,"precincts":
{"total":4,"reporting":4},
"name":"Smithfield"},
"Mail Ballots - CD2":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD2"},
"Cranston":
{"votes":[
{"votes":1166,"name":"mccain"},
{"votes":479,"name":"huckabee"},
{"votes":111,"name":"paul"},
{"votes":65,"name":"romney"},
{"votes":51,"name":"uncommitted-r"},
{"votes":7,"name":"keyes"},
{"votes":3,"name":"cort"}],
"total":1882,"precincts":
{"total":10,"reporting":10},
"name":"Cranston"},
"East Providence":
{"votes":[
{"votes":548,"name":"mccain"},
{"votes":240,"name":"huckabee"},
{"votes":68,"name":"paul"},
{"votes":26,"name":"romney"},
{"votes":14,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":1,"name":"cort"}],
"total":900,"precincts":
{"total":4,"reporting":4},
"name":"East Providence"},
"Mail Ballots - CD1":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD1"},
"Glocester":
{"votes":[
{"votes":169,"name":"mccain"},
{"votes":73,"name":"huckabee"},
{"votes":33,"name":"paul"},
{"votes":20,"name":"romney"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"cort"}],
"total":302,"precincts":
{"total":1,"reporting":1},
"name":"Glocester"},
"Little Compton":
{"votes":[
{"votes":193,"name":"mccain"},
{"votes":43,"name":"huckabee"},
{"votes":18,"name":"paul"},
{"votes":15,"name":"romney"},
{"votes":3,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":272,"precincts":
{"total":1,"reporting":1},
"name":"Little Compton"},
"West Greenwich":
{"votes":[
{"votes":142,"name":"mccain"},
{"votes":69,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":255,"precincts":
{"total":1,"reporting":1},
"name":"West Greenwich"},
"Charlestown":
{"votes":[
{"votes":244,"name":"mccain"},
{"votes":75,"name":"huckabee"},
{"votes":33,"name":"paul"},
{"votes":11,"name":"uncommitted-r"},
{"votes":8,"name":"romney"},
{"votes":1,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":372,"precincts":
{"total":3,"reporting":3},
"name":"Charlestown"},
"North Smithfield":
{"votes":[
{"votes":302,"name":"mccain"},
{"votes":87,"name":"huckabee"},
{"votes":42,"name":"paul"},
{"votes":17,"name":"romney"},
{"votes":16,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"cort"}],
"total":467,"precincts":
{"total":3,"reporting":3},
"name":"North Smithfield"},
"Lincoln":
{"votes":[
{"votes":466,"name":"mccain"},
{"votes":149,"name":"huckabee"},
{"votes":43,"name":"paul"},
{"votes":32,"name":"romney"},
{"votes":16,"name":"uncommitted-r"},
{"votes":5,"name":"keyes"},
{"votes":1,"name":"cort"}],
"total":712,"precincts":
{"total":5,"reporting":5},
"name":"Lincoln"},
"Coventry":
{"votes":[
{"votes":638,"name":"mccain"},
{"votes":274,"name":"huckabee"},
{"votes":71,"name":"paul"},
{"votes":51,"name":"romney"},
{"votes":22,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":1060,"precincts":
{"total":5,"reporting":5},
"name":"Coventry"},
"South Kingstown":
{"votes":[
{"votes":572,"name":"mccain"},
{"votes":160,"name":"huckabee"},
{"votes":59,"name":"paul"},
{"votes":39,"name":"romney"},
{"votes":21,"name":"uncommitted-r"},
{"votes":9,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":860,"precincts":
{"total":3,"reporting":3},
"name":"South Kingstown"},
"West Warwick":
{"votes":[
{"votes":346,"name":"mccain"},
{"votes":153,"name":"huckabee"},
{"votes":36,"name":"paul"},
{"votes":31,"name":"romney"},
{"votes":17,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":584,"precincts":
{"total":5,"reporting":5},
"name":"West Warwick"},
"Burrillville":
{"votes":[
{"votes":230,"name":"mccain"},
{"votes":98,"name":"huckabee"},
{"votes":38,"name":"paul"},
{"votes":22,"name":"romney"},
{"votes":11,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":399,"precincts":
{"total":4,"reporting":4},
"name":"Burrillville"},
"Newport":
{"votes":[
{"votes":549,"name":"mccain"},
{"votes":100,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":32,"name":"romney"},
{"votes":10,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":739,"precincts":
{"total":4,"reporting":4},
"name":"Newport"},
"Bristol":
{"votes":[
{"votes":407,"name":"mccain"},
{"votes":104,"name":"huckabee"},
{"votes":42,"name":"paul"},
{"votes":29,"name":"romney"},
{"votes":7,"name":"uncommitted-r"},
{"votes":1,"name":"cort"},
{"votes":1,"name":"keyes"}],
"total":591,"precincts":
{"total":3,"reporting":3},
"name":"Bristol"},
"Johnston":
{"votes":[
{"votes":282,"name":"mccain"},
{"votes":134,"name":"huckabee"},
{"votes":32,"name":"paul"},
{"votes":16,"name":"romney"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":471,"precincts":
{"total":5,"reporting":5},
"name":"Johnston"},
"Scituate":
{"votes":[
{"votes":344,"name":"mccain"},
{"votes":132,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":26,"name":"romney"},
{"votes":13,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":563,"precincts":
{"total":2,"reporting":2},
"name":"Scituate"},
"New Shoreham":
{"votes":[
{"votes":44,"name":"mccain"},
{"votes":4,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":52,"precincts":
{"total":1,"reporting":1},
"name":"New Shoreham"},
"Exeter":
{"votes":[
{"votes":149,"name":"mccain"},
{"votes":82,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":5,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":270,"precincts":
{"total":1,"reporting":1},
"name":"Exeter"},
"North Providence":
{"votes":[
{"votes":282,"name":"mccain"},
{"votes":101,"name":"huckabee"},
{"votes":33,"name":"paul"},
{"votes":15,"name":"romney"},
{"votes":10,"name":"uncommitted-r"},
{"votes":1,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":442,"precincts":
{"total":3,"reporting":3},
"name":"North Providence"},
"Westerly":
{"votes":[
{"votes":499,"name":"mccain"},
{"votes":163,"name":"huckabee"},
{"votes":32,"name":"romney"},
{"votes":31,"name":"paul"},
{"votes":19,"name":"uncommitted-r"},
{"votes":9,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":753,"precincts":
{"total":3,"reporting":3},
"name":"Westerly"},
"North Kingstown":
{"votes":[
{"votes":856,"name":"mccain"},
{"votes":264,"name":"huckabee"},
{"votes":99,"name":"paul"},
{"votes":61,"name":"romney"},
{"votes":22,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":1306,"precincts":
{"total":4,"reporting":4},
"name":"North Kingstown"},
"Portsmouth":
{"votes":[
{"votes":726,"name":"mccain"},
{"votes":145,"name":"huckabee"},
{"votes":49,"name":"romney"},
{"votes":49,"name":"paul"},
{"votes":13,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":984,"precincts":
{"total":5,"reporting":5},
"name":"Portsmouth"},
"Narragansett":
{"votes":[
{"votes":300,"name":"mccain"},
{"votes":88,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":23,"name":"romney"},
{"votes":8,"name":"uncommitted-r"},
{"votes":1,"name":"cort"},
{"votes":1,"name":"keyes"}],
"total":445,"precincts":
{"total":2,"reporting":2},
"name":"Narragansett"},
"Tiverton":
{"votes":[
{"votes":380,"name":"mccain"},
{"votes":113,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":22,"name":"romney"},
{"votes":10,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":552,"precincts":
{"total":4,"reporting":4},
"name":"Tiverton"},
"Woonsocket":
{"votes":[
{"votes":403,"name":"mccain"},
{"votes":185,"name":"huckabee"},
{"votes":59,"name":"paul"},
{"votes":29,"name":"romney"},
{"votes":22,"name":"uncommitted-r"},
{"votes":4,"name":"cort"},
{"votes":3,"name":"keyes"}],
"total":705,"precincts":
{"total":8,"reporting":8},
"name":"Woonsocket"},
"East Greenwich":
{"votes":[
{"votes":548,"name":"mccain"},
{"votes":134,"name":"huckabee"},
{"votes":34,"name":"romney"},
{"votes":30,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":754,"precincts":
{"total":2,"reporting":2},
"name":"East Greenwich"},
"Pawtucket":
{"votes":[
{"votes":483,"name":"mccain"},
{"votes":214,"name":"huckabee"},
{"votes":60,"name":"paul"},
{"votes":41,"name":"romney"},
{"votes":24,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":824,"precincts":
{"total":17,"reporting":17},
"name":"Pawtucket"},
"Warren":
{"votes":[
{"votes":209,"name":"mccain"},
{"votes":58,"name":"huckabee"},
{"votes":18,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":305,"precincts":
{"total":3,"reporting":3},
"name":"Warren"}}})