GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":4338,"name":"mccain"},
{"votes":1539,"name":"huckabee"},
{"votes":527,"name":"paul"},
{"votes":300,"name":"romney"},
{"votes":146,"name":"uncommitted-r"},
{"votes":33,"name":"keyes"},
{"votes":7,"name":"cort"}],
"name":"Rhode Island","precincts":
{"total":179,"reporting":38},
"delegates":20,"date":"03-04"},
"state":"RI","party":"gop","total":6890,"locals":
{"Middletown":
{"votes":[
{"votes":161,"name":"mccain"},
{"votes":54,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":248,"precincts":
{"total":4,"reporting":1},
"name":"Middletown"},
"Cumberland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Cumberland"},
"Hopkinton":
{"votes":[
{"votes":164,"name":"mccain"},
{"votes":94,"name":"huckabee"},
{"votes":22,"name":"paul"},
{"votes":8,"name":"uncommitted-r"},
{"votes":4,"name":"romney"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":293,"precincts":
{"total":1,"reporting":1},
"name":"Hopkinton"},
"Central Falls":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Central Falls"},
"Barrington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Barrington"},
"Richmond":
{"votes":[
{"votes":172,"name":"mccain"},
{"votes":77,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":11,"name":"romney"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":290,"precincts":
{"total":1,"reporting":1},
"name":"Richmond"},
"Providence":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Providence"},
"Foster":
{"votes":[
{"votes":101,"name":"mccain"},
{"votes":39,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":1,"name":"uncommitted-r"},
{"votes":1,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":167,"precincts":
{"total":1,"reporting":1},
"name":"Foster"},
"Warwick":
{"votes":[
{"votes":181,"name":"mccain"},
{"votes":89,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":19,"name":"romney"},
{"votes":7,"name":"uncommitted-r"},
{"votes":4,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":324,"precincts":
{"total":9,"reporting":1},
"name":"Warwick"},
"Jamestown":
{"votes":[
{"votes":261,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":25,"name":"paul"},
{"votes":12,"name":"romney"},
{"votes":9,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":347,"precincts":
{"total":1,"reporting":1},
"name":"Jamestown"},
"Smithfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Smithfield"},
"Mail Ballots - CD2":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD2"},
"Cranston":
{"votes":[
{"votes":112,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"uncommitted-r"},
{"votes":7,"name":"paul"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":184,"precincts":
{"total":10,"reporting":1},
"name":"Cranston"},
"East Providence":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"East Providence"},
"Mail Ballots - CD1":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mail Ballots - CD1"},
"Glocester":
{"votes":[
{"votes":169,"name":"mccain"},
{"votes":73,"name":"huckabee"},
{"votes":33,"name":"paul"},
{"votes":20,"name":"romney"},
{"votes":4,"name":"keyes"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"cort"}],
"total":302,"precincts":
{"total":1,"reporting":1},
"name":"Glocester"},
"Little Compton":
{"votes":[
{"votes":193,"name":"mccain"},
{"votes":43,"name":"huckabee"},
{"votes":18,"name":"paul"},
{"votes":15,"name":"romney"},
{"votes":3,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":272,"precincts":
{"total":1,"reporting":1},
"name":"Little Compton"},
"West Greenwich":
{"votes":[
{"votes":142,"name":"mccain"},
{"votes":69,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":13,"name":"romney"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":255,"precincts":
{"total":1,"reporting":1},
"name":"West Greenwich"},
"Charlestown":
{"votes":[
{"votes":244,"name":"mccain"},
{"votes":75,"name":"huckabee"},
{"votes":33,"name":"paul"},
{"votes":11,"name":"uncommitted-r"},
{"votes":8,"name":"romney"},
{"votes":1,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":372,"precincts":
{"total":3,"reporting":3},
"name":"Charlestown"},
"North Smithfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Smithfield"},
"Lincoln":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Lincoln"},
"Coventry":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Coventry"},
"South Kingstown":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"South Kingstown"},
"West Warwick":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"West Warwick"},
"Burrillville":
{"votes":[
{"votes":188,"name":"mccain"},
{"votes":87,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":21,"name":"romney"},
{"votes":9,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":342,"precincts":
{"total":4,"reporting":3},
"name":"Burrillville"},
"Newport":
{"votes":[
{"votes":195,"name":"mccain"},
{"votes":32,"name":"huckabee"},
{"votes":16,"name":"romney"},
{"votes":14,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":262,"precincts":
{"total":4,"reporting":1},
"name":"Newport"},
"Bristol":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Bristol"},
"Johnston":
{"votes":[
{"votes":169,"name":"mccain"},
{"votes":68,"name":"huckabee"},
{"votes":20,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":2,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":269,"precincts":
{"total":5,"reporting":2},
"name":"Johnston"},
"Scituate":
{"votes":[
{"votes":344,"name":"mccain"},
{"votes":132,"name":"huckabee"},
{"votes":45,"name":"paul"},
{"votes":27,"name":"romney"},
{"votes":13,"name":"uncommitted-r"},
{"votes":3,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":564,"precincts":
{"total":2,"reporting":2},
"name":"Scituate"},
"New Shoreham":
{"votes":[
{"votes":44,"name":"mccain"},
{"votes":4,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":52,"precincts":
{"total":1,"reporting":1},
"name":"New Shoreham"},
"Exeter":
{"votes":[
{"votes":149,"name":"mccain"},
{"votes":82,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":6,"name":"romney"},
{"votes":5,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":270,"precincts":
{"total":1,"reporting":1},
"name":"Exeter"},
"North Providence":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"North Providence"},
"Westerly":
{"votes":[
{"votes":181,"name":"mccain"},
{"votes":70,"name":"huckabee"},
{"votes":16,"name":"paul"},
{"votes":8,"name":"uncommitted-r"},
{"votes":7,"name":"romney"},
{"votes":5,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":287,"precincts":
{"total":3,"reporting":1},
"name":"Westerly"},
"North Kingstown":
{"votes":[
{"votes":167,"name":"mccain"},
{"votes":37,"name":"huckabee"},
{"votes":20,"name":"paul"},
{"votes":11,"name":"romney"},
{"votes":5,"name":"uncommitted-r"},
{"votes":2,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":242,"precincts":
{"total":4,"reporting":1},
"name":"North Kingstown"},
"Portsmouth":
{"votes":[
{"votes":215,"name":"mccain"},
{"votes":48,"name":"huckabee"},
{"votes":16,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":3,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":296,"precincts":
{"total":5,"reporting":1},
"name":"Portsmouth"},
"Narragansett":
{"votes":[
{"votes":152,"name":"mccain"},
{"votes":46,"name":"huckabee"},
{"votes":12,"name":"romney"},
{"votes":9,"name":"paul"},
{"votes":4,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":224,"precincts":
{"total":2,"reporting":1},
"name":"Narragansett"},
"Tiverton":
{"votes":[
{"votes":77,"name":"mccain"},
{"votes":15,"name":"huckabee"},
{"votes":7,"name":"romney"},
{"votes":5,"name":"uncommitted-r"},
{"votes":4,"name":"paul"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"}],
"total":108,"precincts":
{"total":4,"reporting":1},
"name":"Tiverton"},
"Woonsocket":
{"votes":[
{"votes":348,"name":"mccain"},
{"votes":159,"name":"huckabee"},
{"votes":55,"name":"paul"},
{"votes":26,"name":"romney"},
{"votes":20,"name":"uncommitted-r"},
{"votes":4,"name":"cort"},
{"votes":3,"name":"keyes"}],
"total":615,"precincts":
{"total":8,"reporting":7},
"name":"Woonsocket"},
"East Greenwich":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"East Greenwich"},
"Pawtucket":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"uncommitted-r"},
{"votes":0,"name":"mccain"},
{"votes":0,"name":"cort"},
{"votes":0,"name":"keyes"},
{"votes":0,"name":"paul"}],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Pawtucket"},
"Warren":
{"votes":[
{"votes":209,"name":"mccain"},
{"votes":58,"name":"huckabee"},
{"votes":18,"name":"romney"},
{"votes":13,"name":"paul"},
{"votes":6,"name":"uncommitted-r"},
{"votes":1,"name":"keyes"},
{"votes":0,"name":"cort"}],
"total":305,"precincts":
{"total":3,"reporting":3},
"name":"Warren"}}})