GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":28812,"name":"clinton","delegates":8},
{"votes":22493,"name":"obama","delegates":6}],
"name":"South Dakota","precincts":
{"total":762,"reporting":358},
"delegates":15,"date":"06-03"},
"state":"SD","party":"dem","total":51305,"locals":
{"Bon Homme":
{"votes":[
{"votes":285,"name":"clinton"},
{"votes":143,"name":"obama"}],
"total":428,"precincts":
{"total":5,"reporting":2},
"name":"Bon Homme"},
"Hughes":
{"votes":[
{"votes":775,"name":"clinton"},
{"votes":739,"name":"obama"}],
"total":1514,"precincts":
{"total":15,"reporting":14},
"name":"Hughes"},
"Deuel":
{"votes":[
{"votes":393,"name":"clinton"},
{"votes":224,"name":"obama"}],
"total":617,"precincts":
{"total":11,"reporting":11},
"name":"Deuel"},
"Lyman":
{"votes":[
{"votes":266,"name":"obama"},
{"votes":218,"name":"clinton"}],
"total":484,"precincts":
{"total":7,"reporting":7},
"name":"Lyman"},
"Grant":
{"votes":[
{"votes":533,"name":"clinton"},
{"votes":215,"name":"obama"}],
"total":748,"precincts":
{"total":11,"reporting":7},
"name":"Grant"},
"Union":
{"votes":[
{"votes":767,"name":"clinton"},
{"votes":588,"name":"obama"}],
"total":1355,"precincts":
{"total":13,"reporting":9},
"name":"Union"},
"Clay":
{"votes":[
{"votes":1051,"name":"obama"},
{"votes":928,"name":"clinton"}],
"total":1979,"precincts":
{"total":7,"reporting":7},
"name":"Clay"},
"Miner":
{"votes":[
{"votes":293,"name":"clinton"},
{"votes":188,"name":"obama"}],
"total":481,"precincts":
{"total":8,"reporting":8},
"name":"Miner"},
"Edmunds":
{"votes":[
{"votes":402,"name":"clinton"},
{"votes":234,"name":"obama"}],
"total":636,"precincts":
{"total":7,"reporting":7},
"name":"Edmunds"},
"Douglas":
{"votes":[
{"votes":144,"name":"clinton"},
{"votes":99,"name":"obama"}],
"total":243,"precincts":
{"total":5,"reporting":5},
"name":"Douglas"},
"Hamlin":
{"votes":[
{"votes":310,"name":"clinton"},
{"votes":152,"name":"obama"}],
"total":462,"precincts":
{"total":7,"reporting":6},
"name":"Hamlin"},
"Jerauld":
{"votes":[
{"votes":265,"name":"clinton"},
{"votes":182,"name":"obama"}],
"total":447,"precincts":
{"total":5,"reporting":5},
"name":"Jerauld"},
"McCook":
{"votes":[
{"votes":495,"name":"clinton"},
{"votes":286,"name":"obama"}],
"total":781,"precincts":
{"total":6,"reporting":6},
"name":"McCook"},
"Brookings":
{"votes":[
{"votes":496,"name":"obama"},
{"votes":368,"name":"clinton"}],
"total":864,"precincts":
{"total":15,"reporting":5},
"name":"Brookings"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Jackson"},
"McPherson":
{"votes":[
{"votes":80,"name":"clinton"},
{"votes":59,"name":"obama"}],
"total":139,"precincts":
{"total":6,"reporting":3},
"name":"McPherson"},
"Sully":
{"votes":[
{"votes":100,"name":"clinton"},
{"votes":88,"name":"obama"}],
"total":188,"precincts":
{"total":4,"reporting":4},
"name":"Sully"},
"Brown":
{"votes":[
{"votes":373,"name":"clinton"},
{"votes":283,"name":"obama"}],
"total":656,"precincts":
{"total":22,"reporting":2},
"name":"Brown"},
"Minnehaha":
{"votes":[
{"votes":5045,"name":"clinton"},
{"votes":4246,"name":"obama"}],
"total":9291,"precincts":
{"total":66,"reporting":0},
"name":"Minnehaha"},
"Pennington":
{"votes":[
{"votes":1283,"name":"obama"},
{"votes":1082,"name":"clinton"}],
"total":2365,"precincts":
{"total":49,"reporting":0},
"name":"Pennington"},
"Custer":
{"votes":[
{"votes":71,"name":"obama"},
{"votes":59,"name":"clinton"}],
"total":130,"precincts":
{"total":10,"reporting":2},
"name":"Custer"},
"Lawrence":
{"votes":[
{"votes":490,"name":"obama"},
{"votes":413,"name":"clinton"}],
"total":903,"precincts":
{"total":12,"reporting":3},
"name":"Lawrence"},
"Yankton":
{"votes":[
{"votes":1570,"name":"clinton"},
{"votes":1195,"name":"obama"}],
"total":2765,"precincts":
{"total":13,"reporting":13},
"name":"Yankton"},
"Aurora":
{"votes":[
{"votes":317,"name":"clinton"},
{"votes":220,"name":"obama"}],
"total":537,"precincts":
{"total":7,"reporting":7},
"name":"Aurora"},
"Hand":
{"votes":[
{"votes":234,"name":"clinton"},
{"votes":194,"name":"obama"}],
"total":428,"precincts":
{"total":10,"reporting":8},
"name":"Hand"},
"Walworth":
{"votes":[
{"votes":186,"name":"clinton"},
{"votes":136,"name":"obama"}],
"total":322,"precincts":
{"total":15,"reporting":10},
"name":"Walworth"},
"Codington":
{"votes":[
{"votes":1223,"name":"clinton"},
{"votes":896,"name":"obama"}],
"total":2119,"precincts":
{"total":33,"reporting":21},
"name":"Codington"},
"Haakon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Haakon"},
"Butte":
{"votes":[
{"votes":115,"name":"clinton"},
{"votes":92,"name":"obama"}],
"total":207,"precincts":
{"total":16,"reporting":5},
"name":"Butte"},
"Day":
{"votes":[
{"votes":277,"name":"clinton"},
{"votes":150,"name":"obama"}],
"total":427,"precincts":
{"total":14,"reporting":5},
"name":"Day"},
"Dewey":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Dewey"},
"Jones":
{"votes":[
{"votes":57,"name":"clinton"},
{"votes":34,"name":"obama"}],
"total":91,"precincts":
{"total":3,"reporting":3},
"name":"Jones"},
"Davison":
{"votes":[
{"votes":1373,"name":"clinton"},
{"votes":936,"name":"obama"}],
"total":2309,"precincts":
{"total":8,"reporting":8},
"name":"Davison"},
"Lincoln":
{"votes":[
{"votes":1119,"name":"clinton"},
{"votes":788,"name":"obama"}],
"total":1907,"precincts":
{"total":29,"reporting":18},
"name":"Lincoln"},
"Spink":
{"votes":[
{"votes":690,"name":"clinton"},
{"votes":444,"name":"obama"}],
"total":1134,"precincts":
{"total":9,"reporting":9},
"name":"Spink"},
"Corson":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Corson"},
"Hutchinson":
{"votes":[
{"votes":389,"name":"clinton"},
{"votes":235,"name":"obama"}],
"total":624,"precincts":
{"total":7,"reporting":7},
"name":"Hutchinson"},
"Lake":
{"votes":[
{"votes":692,"name":"clinton"},
{"votes":424,"name":"obama"}],
"total":1116,"precincts":
{"total":10,"reporting":8},
"name":"Lake"},
"Roberts":
{"votes":[
{"votes":612,"name":"obama"},
{"votes":573,"name":"clinton"}],
"total":1185,"precincts":
{"total":14,"reporting":7},
"name":"Roberts"},
"Meade":
{"votes":[
{"votes":242,"name":"clinton"},
{"votes":213,"name":"obama"}],
"total":455,"precincts":
{"total":37,"reporting":7},
"name":"Meade"},
"Mellette":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Mellette"},
"Faulk":
{"votes":[
{"votes":211,"name":"clinton"},
{"votes":132,"name":"obama"}],
"total":343,"precincts":
{"total":7,"reporting":7},
"name":"Faulk"},
"Hanson":
{"votes":[
{"votes":117,"name":"clinton"},
{"votes":86,"name":"obama"}],
"total":203,"precincts":
{"total":5,"reporting":0},
"name":"Hanson"},
"Gregory":
{"votes":[
{"votes":365,"name":"clinton"},
{"votes":299,"name":"obama"}],
"total":664,"precincts":
{"total":3,"reporting":3},
"name":"Gregory"},
"Buffalo":
{"votes":[
{"votes":173,"name":"obama"},
{"votes":120,"name":"clinton"}],
"total":293,"precincts":
{"total":3,"reporting":3},
"name":"Buffalo"},
"Ziebach":
{"votes":[
{"votes":21,"name":"clinton"},
{"votes":21,"name":"obama"}],
"total":42,"precincts":
{"total":8,"reporting":1},
"name":"Ziebach"},
"Tripp":
{"votes":[
{"votes":483,"name":"clinton"},
{"votes":329,"name":"obama"}],
"total":812,"precincts":
{"total":13,"reporting":13},
"name":"Tripp"},
"Brule":
{"votes":[
{"votes":368,"name":"clinton"},
{"votes":274,"name":"obama"}],
"total":642,"precincts":
{"total":5,"reporting":4},
"name":"Brule"},
"Sanborn":
{"votes":[
{"votes":221,"name":"clinton"},
{"votes":144,"name":"obama"}],
"total":365,"precincts":
{"total":4,"reporting":4},
"name":"Sanborn"},
"Harding":
{"votes":[
{"votes":15,"name":"obama"},
{"votes":10,"name":"clinton"}],
"total":25,"precincts":
{"total":4,"reporting":1},
"name":"Harding"},
"Clark":
{"votes":[
{"votes":216,"name":"clinton"},
{"votes":98,"name":"obama"}],
"total":314,"precincts":
{"total":13,"reporting":6},
"name":"Clark"},
"Fall River":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fall River"},
"Marshall":
{"votes":[
{"votes":249,"name":"obama"},
{"votes":237,"name":"clinton"}],
"total":486,"precincts":
{"total":9,"reporting":5},
"name":"Marshall"},
"Beadle":
{"votes":[
{"votes":1616,"name":"clinton"},
{"votes":894,"name":"obama"}],
"total":2510,"precincts":
{"total":14,"reporting":14},
"name":"Beadle"},
"Potter":
{"votes":[
{"votes":161,"name":"clinton"},
{"votes":121,"name":"obama"}],
"total":282,"precincts":
{"total":6,"reporting":6},
"name":"Potter"},
"Charles Mix":
{"votes":[
{"votes":743,"name":"clinton"},
{"votes":614,"name":"obama"}],
"total":1357,"precincts":
{"total":13,"reporting":12},
"name":"Charles Mix"},
"Perkins":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Perkins"},
"Hyde":
{"votes":[
{"votes":74,"name":"clinton"},
{"votes":54,"name":"obama"}],
"total":128,"precincts":
{"total":5,"reporting":4},
"name":"Hyde"},
"Kingsbury":
{"votes":[
{"votes":247,"name":"clinton"},
{"votes":166,"name":"obama"}],
"total":413,"precincts":
{"total":6,"reporting":4},
"name":"Kingsbury"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Todd"},
"Campbell":
{"votes":[
{"votes":46,"name":"obama"},
{"votes":40,"name":"clinton"}],
"total":86,"precincts":
{"total":5,"reporting":5},
"name":"Campbell"},
"Stanley":
{"votes":[
{"votes":61,"name":"clinton"},
{"votes":60,"name":"obama"}],
"total":121,"precincts":
{"total":8,"reporting":3},
"name":"Stanley"},
"Turner":
{"votes":[
{"votes":493,"name":"clinton"},
{"votes":316,"name":"obama"}],
"total":809,"precincts":
{"total":8,"reporting":7},
"name":"Turner"},
"Moody":
{"votes":[
{"votes":573,"name":"clinton"},
{"votes":404,"name":"obama"}],
"total":977,"precincts":
{"total":6,"reporting":5},
"name":"Moody"},
"Shannon":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Shannon"},
"Bennett":
{"votes":[
{"votes":50,"name":"clinton"},
{"votes":46,"name":"obama"}],
"total":96,"precincts":
{"total":8,"reporting":2},
"name":"Bennett"}}})