GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":20053,"name":"clinton","delegates":8},
{"votes":15849,"name":"obama","delegates":6}],
"name":"South Dakota","precincts":
{"total":762,"reporting":239},
"delegates":15,"date":"06-03"},
"state":"SD","party":"dem","total":35902,"locals":
{"Bon Homme":
{"votes":[
{"votes":285,"name":"clinton"},
{"votes":143,"name":"obama"}],
"total":428,"precincts":
{"total":5,"reporting":2},
"name":"Bon Homme"},
"Hughes":
{"votes":[
{"votes":608,"name":"clinton"},
{"votes":601,"name":"obama"}],
"total":1209,"precincts":
{"total":15,"reporting":11},
"name":"Hughes"},
"Deuel":
{"votes":[
{"votes":308,"name":"clinton"},
{"votes":169,"name":"obama"}],
"total":477,"precincts":
{"total":11,"reporting":9},
"name":"Deuel"},
"Lyman":
{"votes":[
{"votes":184,"name":"clinton"},
{"votes":145,"name":"obama"}],
"total":329,"precincts":
{"total":7,"reporting":6},
"name":"Lyman"},
"Grant":
{"votes":[
{"votes":374,"name":"clinton"},
{"votes":141,"name":"obama"}],
"total":515,"precincts":
{"total":11,"reporting":4},
"name":"Grant"},
"Union":
{"votes":[
{"votes":348,"name":"clinton"},
{"votes":282,"name":"obama"}],
"total":630,"precincts":
{"total":13,"reporting":5},
"name":"Union"},
"Clay":
{"votes":[
{"votes":1051,"name":"obama"},
{"votes":928,"name":"clinton"}],
"total":1979,"precincts":
{"total":7,"reporting":7},
"name":"Clay"},
"Miner":
{"votes":[
{"votes":293,"name":"clinton"},
{"votes":188,"name":"obama"}],
"total":481,"precincts":
{"total":8,"reporting":8},
"name":"Miner"},
"Edmunds":
{"votes":[
{"votes":295,"name":"clinton"},
{"votes":184,"name":"obama"}],
"total":479,"precincts":
{"total":7,"reporting":5},
"name":"Edmunds"},
"Douglas":
{"votes":[
{"votes":124,"name":"clinton"},
{"votes":83,"name":"obama"}],
"total":207,"precincts":
{"total":5,"reporting":4},
"name":"Douglas"},
"Hamlin":
{"votes":[
{"votes":229,"name":"clinton"},
{"votes":119,"name":"obama"}],
"total":348,"precincts":
{"total":7,"reporting":4},
"name":"Hamlin"},
"Jerauld":
{"votes":[
{"votes":231,"name":"clinton"},
{"votes":165,"name":"obama"}],
"total":396,"precincts":
{"total":5,"reporting":4},
"name":"Jerauld"},
"McCook":
{"votes":[
{"votes":356,"name":"clinton"},
{"votes":209,"name":"obama"}],
"total":565,"precincts":
{"total":6,"reporting":5},
"name":"McCook"},
"Brookings":
{"votes":[
{"votes":282,"name":"obama"},
{"votes":233,"name":"clinton"}],
"total":515,"precincts":
{"total":15,"reporting":3},
"name":"Brookings"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Jackson"},
"McPherson":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"McPherson"},
"Sully":
{"votes":[
{"votes":16,"name":"obama"},
{"votes":15,"name":"clinton"}],
"total":31,"precincts":
{"total":4,"reporting":1},
"name":"Sully"},
"Brown":
{"votes":[
{"votes":163,"name":"clinton"},
{"votes":134,"name":"obama"}],
"total":297,"precincts":
{"total":22,"reporting":1},
"name":"Brown"},
"Minnehaha":
{"votes":[
{"votes":3231,"name":"clinton"},
{"votes":2909,"name":"obama"}],
"total":6140,"precincts":
{"total":66,"reporting":0},
"name":"Minnehaha"},
"Pennington":
{"votes":[
{"votes":1283,"name":"obama"},
{"votes":1082,"name":"clinton"}],
"total":2365,"precincts":
{"total":49,"reporting":0},
"name":"Pennington"},
"Custer":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Custer"},
"Lawrence":
{"votes":[
{"votes":419,"name":"obama"},
{"votes":317,"name":"clinton"}],
"total":736,"precincts":
{"total":12,"reporting":2},
"name":"Lawrence"},
"Yankton":
{"votes":[
{"votes":1045,"name":"clinton"},
{"votes":811,"name":"obama"}],
"total":1856,"precincts":
{"total":13,"reporting":5},
"name":"Yankton"},
"Aurora":
{"votes":[
{"votes":171,"name":"clinton"},
{"votes":115,"name":"obama"}],
"total":286,"precincts":
{"total":7,"reporting":4},
"name":"Aurora"},
"Hand":
{"votes":[
{"votes":172,"name":"clinton"},
{"votes":151,"name":"obama"}],
"total":323,"precincts":
{"total":10,"reporting":6},
"name":"Hand"},
"Walworth":
{"votes":[
{"votes":109,"name":"clinton"},
{"votes":79,"name":"obama"}],
"total":188,"precincts":
{"total":15,"reporting":7},
"name":"Walworth"},
"Codington":
{"votes":[
{"votes":788,"name":"clinton"},
{"votes":612,"name":"obama"}],
"total":1400,"precincts":
{"total":33,"reporting":14},
"name":"Codington"},
"Haakon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Haakon"},
"Butte":
{"votes":[
{"votes":15,"name":"clinton"},
{"votes":13,"name":"obama"}],
"total":28,"precincts":
{"total":16,"reporting":1},
"name":"Butte"},
"Day":
{"votes":[
{"votes":182,"name":"clinton"},
{"votes":98,"name":"obama"}],
"total":280,"precincts":
{"total":14,"reporting":3},
"name":"Day"},
"Dewey":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Dewey"},
"Jones":
{"votes":[
{"votes":57,"name":"clinton"},
{"votes":34,"name":"obama"}],
"total":91,"precincts":
{"total":3,"reporting":3},
"name":"Jones"},
"Davison":
{"votes":[
{"votes":1373,"name":"clinton"},
{"votes":936,"name":"obama"}],
"total":2309,"precincts":
{"total":8,"reporting":8},
"name":"Davison"},
"Lincoln":
{"votes":[
{"votes":532,"name":"clinton"},
{"votes":265,"name":"obama"}],
"total":797,"precincts":
{"total":29,"reporting":10},
"name":"Lincoln"},
"Spink":
{"votes":[
{"votes":419,"name":"clinton"},
{"votes":282,"name":"obama"}],
"total":701,"precincts":
{"total":9,"reporting":5},
"name":"Spink"},
"Corson":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Corson"},
"Hutchinson":
{"votes":[
{"votes":261,"name":"clinton"},
{"votes":175,"name":"obama"}],
"total":436,"precincts":
{"total":7,"reporting":6},
"name":"Hutchinson"},
"Lake":
{"votes":[
{"votes":610,"name":"clinton"},
{"votes":370,"name":"obama"}],
"total":980,"precincts":
{"total":10,"reporting":7},
"name":"Lake"},
"Roberts":
{"votes":[
{"votes":408,"name":"obama"},
{"votes":370,"name":"clinton"}],
"total":778,"precincts":
{"total":14,"reporting":4},
"name":"Roberts"},
"Meade":
{"votes":[
{"votes":120,"name":"clinton"},
{"votes":116,"name":"obama"}],
"total":236,"precincts":
{"total":37,"reporting":4},
"name":"Meade"},
"Mellette":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Mellette"},
"Faulk":
{"votes":[
{"votes":112,"name":"clinton"},
{"votes":68,"name":"obama"}],
"total":180,"precincts":
{"total":7,"reporting":3},
"name":"Faulk"},
"Hanson":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Hanson"},
"Gregory":
{"votes":[
{"votes":177,"name":"clinton"},
{"votes":154,"name":"obama"}],
"total":331,"precincts":
{"total":3,"reporting":2},
"name":"Gregory"},
"Buffalo":
{"votes":[
{"votes":49,"name":"clinton"},
{"votes":31,"name":"obama"}],
"total":80,"precincts":
{"total":3,"reporting":2},
"name":"Buffalo"},
"Ziebach":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Ziebach"},
"Tripp":
{"votes":[
{"votes":338,"name":"clinton"},
{"votes":237,"name":"obama"}],
"total":575,"precincts":
{"total":13,"reporting":8},
"name":"Tripp"},
"Brule":
{"votes":[
{"votes":128,"name":"clinton"},
{"votes":71,"name":"obama"}],
"total":199,"precincts":
{"total":5,"reporting":3},
"name":"Brule"},
"Sanborn":
{"votes":[
{"votes":177,"name":"clinton"},
{"votes":106,"name":"obama"}],
"total":283,"precincts":
{"total":4,"reporting":3},
"name":"Sanborn"},
"Harding":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Harding"},
"Clark":
{"votes":[
{"votes":137,"name":"clinton"},
{"votes":78,"name":"obama"}],
"total":215,"precincts":
{"total":13,"reporting":5},
"name":"Clark"},
"Fall River":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fall River"},
"Marshall":
{"votes":[
{"votes":249,"name":"obama"},
{"votes":237,"name":"clinton"}],
"total":486,"precincts":
{"total":9,"reporting":5},
"name":"Marshall"},
"Beadle":
{"votes":[
{"votes":1394,"name":"clinton"},
{"votes":751,"name":"obama"}],
"total":2145,"precincts":
{"total":14,"reporting":12},
"name":"Beadle"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Potter"},
"Charles Mix":
{"votes":[
{"votes":551,"name":"clinton"},
{"votes":503,"name":"obama"}],
"total":1054,"precincts":
{"total":13,"reporting":11},
"name":"Charles Mix"},
"Perkins":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Perkins"},
"Hyde":
{"votes":[
{"votes":41,"name":"clinton"},
{"votes":24,"name":"obama"}],
"total":65,"precincts":
{"total":5,"reporting":2},
"name":"Hyde"},
"Kingsbury":
{"votes":[
{"votes":149,"name":"clinton"},
{"votes":116,"name":"obama"}],
"total":265,"precincts":
{"total":6,"reporting":2},
"name":"Kingsbury"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Todd"},
"Campbell":
{"votes":[
{"votes":18,"name":"clinton"},
{"votes":18,"name":"obama"}],
"total":36,"precincts":
{"total":5,"reporting":3},
"name":"Campbell"},
"Stanley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Stanley"},
"Turner":
{"votes":[
{"votes":397,"name":"clinton"},
{"votes":252,"name":"obama"}],
"total":649,"precincts":
{"total":8,"reporting":6},
"name":"Turner"},
"Moody":
{"votes":[
{"votes":295,"name":"clinton"},
{"votes":182,"name":"obama"}],
"total":477,"precincts":
{"total":6,"reporting":3},
"name":"Moody"},
"Shannon":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Shannon"},
"Bennett":
{"votes":[
{"votes":25,"name":"clinton"},
{"votes":21,"name":"obama"}],
"total":46,"precincts":
{"total":8,"reporting":1},
"name":"Bennett"}}})