GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":21734,"name":"clinton","delegates":8},
{"votes":17111,"name":"obama","delegates":6}],
"name":"South Dakota","precincts":
{"total":762,"reporting":266},
"delegates":15,"date":"06-03"},
"state":"SD","party":"dem","total":38845,"locals":
{"Bon Homme":
{"votes":[
{"votes":285,"name":"clinton"},
{"votes":143,"name":"obama"}],
"total":428,"precincts":
{"total":5,"reporting":2},
"name":"Bon Homme"},
"Hughes":
{"votes":[
{"votes":685,"name":"clinton"},
{"votes":675,"name":"obama"}],
"total":1360,"precincts":
{"total":15,"reporting":12},
"name":"Hughes"},
"Deuel":
{"votes":[
{"votes":393,"name":"clinton"},
{"votes":224,"name":"obama"}],
"total":617,"precincts":
{"total":11,"reporting":11},
"name":"Deuel"},
"Lyman":
{"votes":[
{"votes":184,"name":"clinton"},
{"votes":145,"name":"obama"}],
"total":329,"precincts":
{"total":7,"reporting":6},
"name":"Lyman"},
"Grant":
{"votes":[
{"votes":482,"name":"clinton"},
{"votes":179,"name":"obama"}],
"total":661,"precincts":
{"total":11,"reporting":5},
"name":"Grant"},
"Union":
{"votes":[
{"votes":407,"name":"clinton"},
{"votes":319,"name":"obama"}],
"total":726,"precincts":
{"total":13,"reporting":6},
"name":"Union"},
"Clay":
{"votes":[
{"votes":1051,"name":"obama"},
{"votes":928,"name":"clinton"}],
"total":1979,"precincts":
{"total":7,"reporting":7},
"name":"Clay"},
"Miner":
{"votes":[
{"votes":293,"name":"clinton"},
{"votes":188,"name":"obama"}],
"total":481,"precincts":
{"total":8,"reporting":8},
"name":"Miner"},
"Edmunds":
{"votes":[
{"votes":295,"name":"clinton"},
{"votes":184,"name":"obama"}],
"total":479,"precincts":
{"total":7,"reporting":5},
"name":"Edmunds"},
"Douglas":
{"votes":[
{"votes":124,"name":"clinton"},
{"votes":83,"name":"obama"}],
"total":207,"precincts":
{"total":5,"reporting":4},
"name":"Douglas"},
"Hamlin":
{"votes":[
{"votes":272,"name":"clinton"},
{"votes":143,"name":"obama"}],
"total":415,"precincts":
{"total":7,"reporting":5},
"name":"Hamlin"},
"Jerauld":
{"votes":[
{"votes":265,"name":"clinton"},
{"votes":182,"name":"obama"}],
"total":447,"precincts":
{"total":5,"reporting":5},
"name":"Jerauld"},
"McCook":
{"votes":[
{"votes":356,"name":"clinton"},
{"votes":209,"name":"obama"}],
"total":565,"precincts":
{"total":6,"reporting":5},
"name":"McCook"},
"Brookings":
{"votes":[
{"votes":455,"name":"obama"},
{"votes":346,"name":"clinton"}],
"total":801,"precincts":
{"total":15,"reporting":4},
"name":"Brookings"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Jackson"},
"McPherson":
{"votes":[
{"votes":38,"name":"clinton"},
{"votes":27,"name":"obama"}],
"total":65,"precincts":
{"total":6,"reporting":1},
"name":"McPherson"},
"Sully":
{"votes":[
{"votes":16,"name":"obama"},
{"votes":15,"name":"clinton"}],
"total":31,"precincts":
{"total":4,"reporting":1},
"name":"Sully"},
"Brown":
{"votes":[
{"votes":163,"name":"clinton"},
{"votes":134,"name":"obama"}],
"total":297,"precincts":
{"total":22,"reporting":1},
"name":"Brown"},
"Minnehaha":
{"votes":[
{"votes":3231,"name":"clinton"},
{"votes":2909,"name":"obama"}],
"total":6140,"precincts":
{"total":66,"reporting":0},
"name":"Minnehaha"},
"Pennington":
{"votes":[
{"votes":1283,"name":"obama"},
{"votes":1082,"name":"clinton"}],
"total":2365,"precincts":
{"total":49,"reporting":0},
"name":"Pennington"},
"Custer":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Custer"},
"Lawrence":
{"votes":[
{"votes":490,"name":"obama"},
{"votes":413,"name":"clinton"}],
"total":903,"precincts":
{"total":12,"reporting":3},
"name":"Lawrence"},
"Yankton":
{"votes":[
{"votes":1274,"name":"clinton"},
{"votes":987,"name":"obama"}],
"total":2261,"precincts":
{"total":13,"reporting":6},
"name":"Yankton"},
"Aurora":
{"votes":[
{"votes":310,"name":"clinton"},
{"votes":209,"name":"obama"}],
"total":519,"precincts":
{"total":7,"reporting":6},
"name":"Aurora"},
"Hand":
{"votes":[
{"votes":172,"name":"clinton"},
{"votes":151,"name":"obama"}],
"total":323,"precincts":
{"total":10,"reporting":6},
"name":"Hand"},
"Walworth":
{"votes":[
{"votes":126,"name":"clinton"},
{"votes":86,"name":"obama"}],
"total":212,"precincts":
{"total":15,"reporting":8},
"name":"Walworth"},
"Codington":
{"votes":[
{"votes":830,"name":"clinton"},
{"votes":655,"name":"obama"}],
"total":1485,"precincts":
{"total":33,"reporting":15},
"name":"Codington"},
"Haakon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Haakon"},
"Butte":
{"votes":[
{"votes":30,"name":"clinton"},
{"votes":21,"name":"obama"}],
"total":51,"precincts":
{"total":16,"reporting":2},
"name":"Butte"},
"Day":
{"votes":[
{"votes":225,"name":"clinton"},
{"votes":124,"name":"obama"}],
"total":349,"precincts":
{"total":14,"reporting":4},
"name":"Day"},
"Dewey":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Dewey"},
"Jones":
{"votes":[
{"votes":57,"name":"clinton"},
{"votes":34,"name":"obama"}],
"total":91,"precincts":
{"total":3,"reporting":3},
"name":"Jones"},
"Davison":
{"votes":[
{"votes":1373,"name":"clinton"},
{"votes":936,"name":"obama"}],
"total":2309,"precincts":
{"total":8,"reporting":8},
"name":"Davison"},
"Lincoln":
{"votes":[
{"votes":594,"name":"clinton"},
{"votes":315,"name":"obama"}],
"total":909,"precincts":
{"total":29,"reporting":11},
"name":"Lincoln"},
"Spink":
{"votes":[
{"votes":488,"name":"clinton"},
{"votes":323,"name":"obama"}],
"total":811,"precincts":
{"total":9,"reporting":6},
"name":"Spink"},
"Corson":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Corson"},
"Hutchinson":
{"votes":[
{"votes":261,"name":"clinton"},
{"votes":175,"name":"obama"}],
"total":436,"precincts":
{"total":7,"reporting":6},
"name":"Hutchinson"},
"Lake":
{"votes":[
{"votes":610,"name":"clinton"},
{"votes":370,"name":"obama"}],
"total":980,"precincts":
{"total":10,"reporting":7},
"name":"Lake"},
"Roberts":
{"votes":[
{"votes":408,"name":"obama"},
{"votes":370,"name":"clinton"}],
"total":778,"precincts":
{"total":14,"reporting":4},
"name":"Roberts"},
"Meade":
{"votes":[
{"votes":120,"name":"clinton"},
{"votes":116,"name":"obama"}],
"total":236,"precincts":
{"total":37,"reporting":4},
"name":"Meade"},
"Mellette":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Mellette"},
"Faulk":
{"votes":[
{"votes":132,"name":"clinton"},
{"votes":86,"name":"obama"}],
"total":218,"precincts":
{"total":7,"reporting":4},
"name":"Faulk"},
"Hanson":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Hanson"},
"Gregory":
{"votes":[
{"votes":177,"name":"clinton"},
{"votes":154,"name":"obama"}],
"total":331,"precincts":
{"total":3,"reporting":2},
"name":"Gregory"},
"Buffalo":
{"votes":[
{"votes":49,"name":"clinton"},
{"votes":31,"name":"obama"}],
"total":80,"precincts":
{"total":3,"reporting":2},
"name":"Buffalo"},
"Ziebach":
{"votes":[
{"votes":21,"name":"clinton"},
{"votes":21,"name":"obama"}],
"total":42,"precincts":
{"total":8,"reporting":1},
"name":"Ziebach"},
"Tripp":
{"votes":[
{"votes":418,"name":"clinton"},
{"votes":283,"name":"obama"}],
"total":701,"precincts":
{"total":13,"reporting":9},
"name":"Tripp"},
"Brule":
{"votes":[
{"votes":128,"name":"clinton"},
{"votes":71,"name":"obama"}],
"total":199,"precincts":
{"total":5,"reporting":3},
"name":"Brule"},
"Sanborn":
{"votes":[
{"votes":177,"name":"clinton"},
{"votes":106,"name":"obama"}],
"total":283,"precincts":
{"total":4,"reporting":3},
"name":"Sanborn"},
"Harding":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Harding"},
"Clark":
{"votes":[
{"votes":137,"name":"clinton"},
{"votes":78,"name":"obama"}],
"total":215,"precincts":
{"total":13,"reporting":5},
"name":"Clark"},
"Fall River":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fall River"},
"Marshall":
{"votes":[
{"votes":249,"name":"obama"},
{"votes":237,"name":"clinton"}],
"total":486,"precincts":
{"total":9,"reporting":5},
"name":"Marshall"},
"Beadle":
{"votes":[
{"votes":1466,"name":"clinton"},
{"votes":802,"name":"obama"}],
"total":2268,"precincts":
{"total":14,"reporting":13},
"name":"Beadle"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Potter"},
"Charles Mix":
{"votes":[
{"votes":551,"name":"clinton"},
{"votes":503,"name":"obama"}],
"total":1054,"precincts":
{"total":13,"reporting":11},
"name":"Charles Mix"},
"Perkins":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Perkins"},
"Hyde":
{"votes":[
{"votes":54,"name":"clinton"},
{"votes":34,"name":"obama"}],
"total":88,"precincts":
{"total":5,"reporting":3},
"name":"Hyde"},
"Kingsbury":
{"votes":[
{"votes":149,"name":"clinton"},
{"votes":116,"name":"obama"}],
"total":265,"precincts":
{"total":6,"reporting":2},
"name":"Kingsbury"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Todd"},
"Campbell":
{"votes":[
{"votes":37,"name":"obama"},
{"votes":32,"name":"clinton"}],
"total":69,"precincts":
{"total":5,"reporting":4},
"name":"Campbell"},
"Stanley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Stanley"},
"Turner":
{"votes":[
{"votes":493,"name":"clinton"},
{"votes":316,"name":"obama"}],
"total":809,"precincts":
{"total":8,"reporting":7},
"name":"Turner"},
"Moody":
{"votes":[
{"votes":391,"name":"clinton"},
{"votes":254,"name":"obama"}],
"total":645,"precincts":
{"total":6,"reporting":4},
"name":"Moody"},
"Shannon":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Shannon"},
"Bennett":
{"votes":[
{"votes":25,"name":"clinton"},
{"votes":21,"name":"obama"}],
"total":46,"precincts":
{"total":8,"reporting":1},
"name":"Bennett"}}})