GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":36504,"name":"mccain"},
{"votes":8152,"name":"paul"},
{"votes":3721,"name":"huckabee"},
{"votes":1622,"name":"romney"},
{"votes":1530,"name":"uncommitted-r"}],
"name":"South Dakota","precincts":
{"total":762,"reporting":631},
"delegates":27,"date":"06-03"},
"state":"SD","party":"gop","total":51529,"locals":
{"Bon Homme":
{"votes":[
{"votes":324,"name":"mccain"},
{"votes":103,"name":"paul"},
{"votes":59,"name":"huckabee"},
{"votes":15,"name":"romney"},
{"votes":15,"name":"uncommitted-r"}],
"total":516,"precincts":
{"total":5,"reporting":5},
"name":"Bon Homme"},
"Hughes":
{"votes":[
{"votes":2613,"name":"mccain"},
{"votes":314,"name":"paul"},
{"votes":221,"name":"huckabee"},
{"votes":103,"name":"uncommitted-r"},
{"votes":77,"name":"romney"}],
"total":3328,"precincts":
{"total":15,"reporting":15},
"name":"Hughes"},
"Deuel":
{"votes":[
{"votes":187,"name":"mccain"},
{"votes":66,"name":"paul"},
{"votes":28,"name":"huckabee"},
{"votes":12,"name":"uncommitted-r"},
{"votes":9,"name":"romney"}],
"total":302,"precincts":
{"total":11,"reporting":11},
"name":"Deuel"},
"Lyman":
{"votes":[
{"votes":202,"name":"mccain"},
{"votes":54,"name":"paul"},
{"votes":17,"name":"huckabee"},
{"votes":14,"name":"uncommitted-r"},
{"votes":4,"name":"romney"}],
"total":291,"precincts":
{"total":7,"reporting":7},
"name":"Lyman"},
"Grant":
{"votes":[
{"votes":327,"name":"mccain"},
{"votes":81,"name":"paul"},
{"votes":40,"name":"huckabee"},
{"votes":19,"name":"uncommitted-r"},
{"votes":13,"name":"romney"}],
"total":480,"precincts":
{"total":11,"reporting":11},
"name":"Grant"},
"Union":
{"votes":[
{"votes":1085,"name":"mccain"},
{"votes":151,"name":"paul"},
{"votes":112,"name":"huckabee"},
{"votes":75,"name":"romney"},
{"votes":48,"name":"uncommitted-r"}],
"total":1471,"precincts":
{"total":13,"reporting":10},
"name":"Union"},
"Clay":
{"votes":[
{"votes":528,"name":"mccain"},
{"votes":88,"name":"paul"},
{"votes":40,"name":"romney"},
{"votes":39,"name":"huckabee"},
{"votes":23,"name":"uncommitted-r"}],
"total":718,"precincts":
{"total":7,"reporting":7},
"name":"Clay"},
"Miner":
{"votes":[
{"votes":72,"name":"mccain"},
{"votes":23,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":1,"name":"uncommitted-r"}],
"total":126,"precincts":
{"total":8,"reporting":8},
"name":"Miner"},
"Edmunds":
{"votes":[
{"votes":290,"name":"mccain"},
{"votes":55,"name":"paul"},
{"votes":40,"name":"huckabee"},
{"votes":29,"name":"uncommitted-r"},
{"votes":12,"name":"romney"}],
"total":426,"precincts":
{"total":7,"reporting":7},
"name":"Edmunds"},
"Douglas":
{"votes":[
{"votes":264,"name":"mccain"},
{"votes":48,"name":"paul"},
{"votes":34,"name":"huckabee"},
{"votes":12,"name":"romney"},
{"votes":12,"name":"uncommitted-r"}],
"total":370,"precincts":
{"total":5,"reporting":5},
"name":"Douglas"},
"Hamlin":
{"votes":[
{"votes":266,"name":"mccain"},
{"votes":119,"name":"paul"},
{"votes":24,"name":"huckabee"},
{"votes":19,"name":"uncommitted-r"},
{"votes":12,"name":"romney"}],
"total":440,"precincts":
{"total":7,"reporting":7},
"name":"Hamlin"},
"Jerauld":
{"votes":[
{"votes":179,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":9,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":225,"precincts":
{"total":5,"reporting":5},
"name":"Jerauld"},
"McCook":
{"votes":[
{"votes":266,"name":"mccain"},
{"votes":57,"name":"paul"},
{"votes":43,"name":"huckabee"},
{"votes":14,"name":"romney"},
{"votes":10,"name":"uncommitted-r"}],
"total":390,"precincts":
{"total":6,"reporting":6},
"name":"McCook"},
"Brookings":
{"votes":[
{"votes":1225,"name":"mccain"},
{"votes":273,"name":"paul"},
{"votes":160,"name":"huckabee"},
{"votes":53,"name":"romney"},
{"votes":51,"name":"uncommitted-r"}],
"total":1762,"precincts":
{"total":15,"reporting":15},
"name":"Brookings"},
"Jackson":
{"votes":[
{"votes":52,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":5,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"uncommitted-r"}],
"total":82,"precincts":
{"total":8,"reporting":2},
"name":"Jackson"},
"McPherson":
{"votes":[
{"votes":393,"name":"mccain"},
{"votes":74,"name":"paul"},
{"votes":41,"name":"huckabee"},
{"votes":21,"name":"romney"},
{"votes":11,"name":"uncommitted-r"}],
"total":540,"precincts":
{"total":6,"reporting":6},
"name":"McPherson"},
"Sully":
{"votes":[
{"votes":220,"name":"mccain"},
{"votes":43,"name":"paul"},
{"votes":22,"name":"huckabee"},
{"votes":14,"name":"romney"},
{"votes":13,"name":"uncommitted-r"}],
"total":312,"precincts":
{"total":4,"reporting":4},
"name":"Sully"},
"Brown":
{"votes":[
{"votes":613,"name":"mccain"},
{"votes":110,"name":"paul"},
{"votes":50,"name":"huckabee"},
{"votes":28,"name":"romney"},
{"votes":21,"name":"uncommitted-r"}],
"total":822,"precincts":
{"total":22,"reporting":7},
"name":"Brown"},
"Minnehaha":
{"votes":[
{"votes":4644,"name":"mccain"},
{"votes":1163,"name":"paul"},
{"votes":543,"name":"huckabee"},
{"votes":289,"name":"romney"},
{"votes":183,"name":"uncommitted-r"}],
"total":6822,"precincts":
{"total":66,"reporting":58},
"name":"Minnehaha"},
"Pennington":
{"votes":[
{"votes":5364,"name":"mccain"},
{"votes":967,"name":"paul"},
{"votes":330,"name":"huckabee"},
{"votes":246,"name":"romney"},
{"votes":226,"name":"uncommitted-r"}],
"total":7133,"precincts":
{"total":49,"reporting":44},
"name":"Pennington"},
"Custer":
{"votes":[
{"votes":397,"name":"mccain"},
{"votes":97,"name":"paul"},
{"votes":23,"name":"huckabee"},
{"votes":22,"name":"romney"},
{"votes":12,"name":"uncommitted-r"}],
"total":551,"precincts":
{"total":10,"reporting":6},
"name":"Custer"},
"Lawrence":
{"votes":[
{"votes":1739,"name":"mccain"},
{"votes":532,"name":"paul"},
{"votes":99,"name":"huckabee"},
{"votes":95,"name":"uncommitted-r"},
{"votes":57,"name":"romney"}],
"total":2522,"precincts":
{"total":12,"reporting":9},
"name":"Lawrence"},
"Yankton":
{"votes":[
{"votes":969,"name":"mccain"},
{"votes":303,"name":"paul"},
{"votes":89,"name":"huckabee"},
{"votes":55,"name":"romney"},
{"votes":49,"name":"uncommitted-r"}],
"total":1465,"precincts":
{"total":13,"reporting":13},
"name":"Yankton"},
"Aurora":
{"votes":[
{"votes":158,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":19,"name":"paul"},
{"votes":10,"name":"romney"},
{"votes":5,"name":"uncommitted-r"}],
"total":221,"precincts":
{"total":7,"reporting":7},
"name":"Aurora"},
"Hand":
{"votes":[
{"votes":431,"name":"mccain"},
{"votes":70,"name":"paul"},
{"votes":55,"name":"huckabee"},
{"votes":20,"name":"romney"},
{"votes":13,"name":"uncommitted-r"}],
"total":589,"precincts":
{"total":10,"reporting":10},
"name":"Hand"},
"Walworth":
{"votes":[
{"votes":609,"name":"mccain"},
{"votes":161,"name":"paul"},
{"votes":61,"name":"huckabee"},
{"votes":27,"name":"romney"},
{"votes":26,"name":"uncommitted-r"}],
"total":884,"precincts":
{"total":15,"reporting":14},
"name":"Walworth"},
"Codington":
{"votes":[
{"votes":667,"name":"mccain"},
{"votes":226,"name":"paul"},
{"votes":74,"name":"huckabee"},
{"votes":33,"name":"romney"},
{"votes":22,"name":"uncommitted-r"}],
"total":1022,"precincts":
{"total":33,"reporting":33},
"name":"Codington"},
"Haakon":
{"votes":[
{"votes":115,"name":"mccain"},
{"votes":41,"name":"paul"},
{"votes":13,"name":"huckabee"},
{"votes":5,"name":"romney"},
{"votes":1,"name":"uncommitted-r"}],
"total":175,"precincts":
{"total":6,"reporting":3},
"name":"Haakon"},
"Butte":
{"votes":[
{"votes":509,"name":"mccain"},
{"votes":203,"name":"paul"},
{"votes":34,"name":"huckabee"},
{"votes":24,"name":"uncommitted-r"},
{"votes":18,"name":"romney"}],
"total":788,"precincts":
{"total":16,"reporting":11},
"name":"Butte"},
"Day":
{"votes":[
{"votes":230,"name":"mccain"},
{"votes":71,"name":"paul"},
{"votes":39,"name":"huckabee"},
{"votes":10,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":356,"precincts":
{"total":14,"reporting":14},
"name":"Day"},
"Dewey":
{"votes":[
{"votes":90,"name":"mccain"},
{"votes":23,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":3,"name":"huckabee"}],
"total":120,"precincts":
{"total":13,"reporting":7},
"name":"Dewey"},
"Jones":
{"votes":[
{"votes":110,"name":"mccain"},
{"votes":21,"name":"paul"},
{"votes":11,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":3,"name":"uncommitted-r"}],
"total":148,"precincts":
{"total":3,"reporting":3},
"name":"Jones"},
"Davison":
{"votes":[
{"votes":816,"name":"mccain"},
{"votes":136,"name":"paul"},
{"votes":90,"name":"huckabee"},
{"votes":37,"name":"romney"},
{"votes":33,"name":"uncommitted-r"}],
"total":1112,"precincts":
{"total":8,"reporting":8},
"name":"Davison"},
"Lincoln":
{"votes":[
{"votes":1689,"name":"mccain"},
{"votes":342,"name":"paul"},
{"votes":158,"name":"huckabee"},
{"votes":81,"name":"romney"},
{"votes":60,"name":"uncommitted-r"}],
"total":2330,"precincts":
{"total":29,"reporting":29},
"name":"Lincoln"},
"Spink":
{"votes":[
{"votes":333,"name":"mccain"},
{"votes":50,"name":"paul"},
{"votes":38,"name":"huckabee"},
{"votes":23,"name":"uncommitted-r"},
{"votes":14,"name":"romney"}],
"total":458,"precincts":
{"total":9,"reporting":9},
"name":"Spink"},
"Corson":
{"votes":[
{"votes":77,"name":"mccain"},
{"votes":33,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":4,"name":"romney"},
{"votes":2,"name":"uncommitted-r"}],
"total":126,"precincts":
{"total":17,"reporting":12},
"name":"Corson"},
"Hutchinson":
{"votes":[
{"votes":396,"name":"mccain"},
{"votes":93,"name":"paul"},
{"votes":87,"name":"huckabee"},
{"votes":25,"name":"uncommitted-r"},
{"votes":14,"name":"romney"}],
"total":615,"precincts":
{"total":7,"reporting":7},
"name":"Hutchinson"},
"Lake":
{"votes":[
{"votes":707,"name":"mccain"},
{"votes":153,"name":"paul"},
{"votes":98,"name":"huckabee"},
{"votes":41,"name":"romney"},
{"votes":24,"name":"uncommitted-r"}],
"total":1023,"precincts":
{"total":10,"reporting":10},
"name":"Lake"},
"Roberts":
{"votes":[
{"votes":245,"name":"mccain"},
{"votes":50,"name":"paul"},
{"votes":23,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":8,"name":"uncommitted-r"}],
"total":334,"precincts":
{"total":14,"reporting":11},
"name":"Roberts"},
"Meade":
{"votes":[
{"votes":922,"name":"mccain"},
{"votes":320,"name":"paul"},
{"votes":60,"name":"huckabee"},
{"votes":31,"name":"uncommitted-r"},
{"votes":19,"name":"romney"}],
"total":1352,"precincts":
{"total":37,"reporting":13},
"name":"Meade"},
"Mellette":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Mellette"},
"Faulk":
{"votes":[
{"votes":166,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":31,"name":"paul"},
{"votes":12,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":254,"precincts":
{"total":7,"reporting":7},
"name":"Faulk"},
"Hanson":
{"votes":[
{"votes":208,"name":"mccain"},
{"votes":46,"name":"paul"},
{"votes":21,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"uncommitted-r"}],
"total":290,"precincts":
{"total":5,"reporting":5},
"name":"Hanson"},
"Gregory":
{"votes":[
{"votes":251,"name":"mccain"},
{"votes":39,"name":"huckabee"},
{"votes":27,"name":"paul"},
{"votes":10,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":332,"precincts":
{"total":3,"reporting":3},
"name":"Gregory"},
"Buffalo":
{"votes":[
{"votes":17,"name":"mccain"},
{"votes":15,"name":"paul"},
{"votes":3,"name":"huckabee"},
{"votes":1,"name":"uncommitted-r"}],
"total":36,"precincts":
{"total":3,"reporting":3},
"name":"Buffalo"},
"Ziebach":
{"votes":[
{"votes":44,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":7,"name":"huckabee"},
{"votes":3,"name":"uncommitted-r"},
{"votes":2,"name":"romney"}],
"total":80,"precincts":
{"total":8,"reporting":6},
"name":"Ziebach"},
"Tripp":
{"votes":[
{"votes":699,"name":"mccain"},
{"votes":132,"name":"paul"},
{"votes":70,"name":"huckabee"},
{"votes":21,"name":"uncommitted-r"},
{"votes":14,"name":"romney"}],
"total":936,"precincts":
{"total":13,"reporting":13},
"name":"Tripp"},
"Brule":
{"votes":[
{"votes":276,"name":"mccain"},
{"votes":35,"name":"paul"},
{"votes":27,"name":"huckabee"},
{"votes":15,"name":"romney"},
{"votes":9,"name":"uncommitted-r"}],
"total":362,"precincts":
{"total":5,"reporting":5},
"name":"Brule"},
"Sanborn":
{"votes":[
{"votes":101,"name":"mccain"},
{"votes":13,"name":"paul"},
{"votes":12,"name":"huckabee"},
{"votes":11,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":143,"precincts":
{"total":4,"reporting":4},
"name":"Sanborn"},
"Harding":
{"votes":[
{"votes":114,"name":"mccain"},
{"votes":60,"name":"paul"},
{"votes":7,"name":"huckabee"},
{"votes":6,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":190,"precincts":
{"total":4,"reporting":4},
"name":"Harding"},
"Clark":
{"votes":[
{"votes":250,"name":"mccain"},
{"votes":78,"name":"paul"},
{"votes":32,"name":"huckabee"},
{"votes":7,"name":"romney"},
{"votes":6,"name":"uncommitted-r"}],
"total":373,"precincts":
{"total":13,"reporting":13},
"name":"Clark"},
"Fall River":
{"votes":[
{"votes":405,"name":"mccain"},
{"votes":130,"name":"paul"},
{"votes":35,"name":"huckabee"},
{"votes":26,"name":"uncommitted-r"},
{"votes":8,"name":"romney"}],
"total":604,"precincts":
{"total":16,"reporting":5},
"name":"Fall River"},
"Marshall":
{"votes":[
{"votes":204,"name":"mccain"},
{"votes":26,"name":"huckabee"},
{"votes":26,"name":"paul"},
{"votes":8,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":270,"precincts":
{"total":9,"reporting":9},
"name":"Marshall"},
"Beadle":
{"votes":[
{"votes":633,"name":"mccain"},
{"votes":105,"name":"huckabee"},
{"votes":85,"name":"paul"},
{"votes":29,"name":"romney"},
{"votes":25,"name":"uncommitted-r"}],
"total":877,"precincts":
{"total":14,"reporting":14},
"name":"Beadle"},
"Potter":
{"votes":[
{"votes":478,"name":"mccain"},
{"votes":75,"name":"paul"},
{"votes":44,"name":"huckabee"},
{"votes":16,"name":"romney"},
{"votes":14,"name":"uncommitted-r"}],
"total":627,"precincts":
{"total":6,"reporting":6},
"name":"Potter"},
"Charles Mix":
{"votes":[
{"votes":363,"name":"mccain"},
{"votes":53,"name":"huckabee"},
{"votes":48,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":7,"name":"uncommitted-r"}],
"total":480,"precincts":
{"total":13,"reporting":13},
"name":"Charles Mix"},
"Perkins":
{"votes":[
{"votes":165,"name":"mccain"},
{"votes":111,"name":"paul"},
{"votes":25,"name":"huckabee"},
{"votes":8,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":312,"precincts":
{"total":10,"reporting":6},
"name":"Perkins"},
"Hyde":
{"votes":[
{"votes":162,"name":"mccain"},
{"votes":38,"name":"paul"},
{"votes":22,"name":"huckabee"},
{"votes":10,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":237,"precincts":
{"total":5,"reporting":5},
"name":"Hyde"},
"Kingsbury":
{"votes":[
{"votes":340,"name":"mccain"},
{"votes":111,"name":"paul"},
{"votes":40,"name":"huckabee"},
{"votes":13,"name":"uncommitted-r"},
{"votes":11,"name":"romney"}],
"total":515,"precincts":
{"total":6,"reporting":6},
"name":"Kingsbury"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Todd"},
"Campbell":
{"votes":[
{"votes":209,"name":"mccain"},
{"votes":49,"name":"paul"},
{"votes":24,"name":"huckabee"},
{"votes":14,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":301,"precincts":
{"total":5,"reporting":5},
"name":"Campbell"},
"Stanley":
{"votes":[
{"votes":316,"name":"mccain"},
{"votes":68,"name":"paul"},
{"votes":24,"name":"huckabee"},
{"votes":9,"name":"romney"},
{"votes":5,"name":"uncommitted-r"}],
"total":422,"precincts":
{"total":8,"reporting":8},
"name":"Stanley"},
"Turner":
{"votes":[
{"votes":388,"name":"mccain"},
{"votes":101,"name":"paul"},
{"votes":77,"name":"huckabee"},
{"votes":16,"name":"romney"},
{"votes":14,"name":"uncommitted-r"}],
"total":596,"precincts":
{"total":8,"reporting":8},
"name":"Turner"},
"Moody":
{"votes":[
{"votes":204,"name":"mccain"},
{"votes":43,"name":"paul"},
{"votes":37,"name":"huckabee"},
{"votes":7,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":296,"precincts":
{"total":6,"reporting":6},
"name":"Moody"},
"Shannon":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Shannon"},
"Bennett":
{"votes":[
{"votes":188,"name":"mccain"},
{"votes":33,"name":"paul"},
{"votes":16,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":6,"name":"uncommitted-r"}],
"total":249,"precincts":
{"total":8,"reporting":8},
"name":"Bennett"}}})