GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":7772,"name":"mccain"},
{"votes":1631,"name":"paul"},
{"votes":886,"name":"huckabee"},
{"votes":356,"name":"romney"},
{"votes":344,"name":"uncommitted-r"}],
"name":"South Dakota","precincts":
{"total":762,"reporting":154},
"delegates":27,"date":"06-03"},
"state":"SD","party":"gop","total":10989,"locals":
{"Bon Homme":
{"votes":[
{"votes":137,"name":"mccain"},
{"votes":53,"name":"paul"},
{"votes":16,"name":"huckabee"},
{"votes":5,"name":"uncommitted-r"},
{"votes":4,"name":"romney"}],
"total":215,"precincts":
{"total":5,"reporting":2},
"name":"Bon Homme"},
"Hughes":
{"votes":[
{"votes":1314,"name":"mccain"},
{"votes":170,"name":"paul"},
{"votes":114,"name":"huckabee"},
{"votes":50,"name":"uncommitted-r"},
{"votes":40,"name":"romney"}],
"total":1688,"precincts":
{"total":15,"reporting":8},
"name":"Hughes"},
"Deuel":
{"votes":[
{"votes":135,"name":"mccain"},
{"votes":48,"name":"paul"},
{"votes":23,"name":"huckabee"},
{"votes":10,"name":"uncommitted-r"},
{"votes":7,"name":"romney"}],
"total":223,"precincts":
{"total":11,"reporting":7},
"name":"Deuel"},
"Lyman":
{"votes":[
{"votes":172,"name":"mccain"},
{"votes":39,"name":"paul"},
{"votes":15,"name":"huckabee"},
{"votes":12,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":241,"precincts":
{"total":7,"reporting":4},
"name":"Lyman"},
"Grant":
{"votes":[
{"votes":162,"name":"mccain"},
{"votes":40,"name":"paul"},
{"votes":13,"name":"huckabee"},
{"votes":12,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":232,"precincts":
{"total":11,"reporting":3},
"name":"Grant"},
"Union":
{"votes":[
{"votes":173,"name":"mccain"},
{"votes":37,"name":"paul"},
{"votes":27,"name":"huckabee"},
{"votes":12,"name":"romney"},
{"votes":12,"name":"uncommitted-r"}],
"total":261,"precincts":
{"total":13,"reporting":3},
"name":"Union"},
"Clay":
{"votes":[
{"votes":213,"name":"mccain"},
{"votes":38,"name":"paul"},
{"votes":19,"name":"romney"},
{"votes":14,"name":"huckabee"},
{"votes":3,"name":"uncommitted-r"}],
"total":287,"precincts":
{"total":7,"reporting":4},
"name":"Clay"},
"Miner":
{"votes":[
{"votes":72,"name":"mccain"},
{"votes":23,"name":"huckabee"},
{"votes":21,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":1,"name":"uncommitted-r"}],
"total":126,"precincts":
{"total":8,"reporting":8},
"name":"Miner"},
"Edmunds":
{"votes":[
{"votes":153,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":23,"name":"uncommitted-r"},
{"votes":20,"name":"huckabee"},
{"votes":3,"name":"romney"}],
"total":223,"precincts":
{"total":7,"reporting":3},
"name":"Edmunds"},
"Douglas":
{"votes":[
{"votes":57,"name":"mccain"},
{"votes":12,"name":"paul"},
{"votes":7,"name":"huckabee"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":84,"precincts":
{"total":5,"reporting":1},
"name":"Douglas"},
"Hamlin":
{"votes":[
{"votes":206,"name":"mccain"},
{"votes":90,"name":"paul"},
{"votes":15,"name":"huckabee"},
{"votes":8,"name":"romney"},
{"votes":7,"name":"uncommitted-r"}],
"total":326,"precincts":
{"total":7,"reporting":5},
"name":"Hamlin"},
"Jerauld":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Jerauld"},
"McCook":
{"votes":[
{"votes":114,"name":"mccain"},
{"votes":18,"name":"huckabee"},
{"votes":17,"name":"paul"},
{"votes":7,"name":"romney"},
{"votes":3,"name":"uncommitted-r"}],
"total":159,"precincts":
{"total":6,"reporting":3},
"name":"McCook"},
"Brookings":
{"votes":[
{"votes":95,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":14,"name":"huckabee"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":141,"precincts":
{"total":15,"reporting":2},
"name":"Brookings"},
"Jackson":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Jackson"},
"McPherson":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"McPherson"},
"Sully":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Sully"},
"Brown":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Brown"},
"Minnehaha":
{"votes":[
{"votes":746,"name":"mccain"},
{"votes":147,"name":"paul"},
{"votes":73,"name":"huckabee"},
{"votes":40,"name":"romney"},
{"votes":31,"name":"uncommitted-r"}],
"total":1037,"precincts":
{"total":66,"reporting":14},
"name":"Minnehaha"},
"Pennington":
{"votes":[],
"total":0,"precincts":
{"total":49,"reporting":0},
"name":"Pennington"},
"Custer":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Custer"},
"Lawrence":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Lawrence"},
"Yankton":
{"votes":[
{"votes":484,"name":"mccain"},
{"votes":146,"name":"paul"},
{"votes":42,"name":"huckabee"},
{"votes":26,"name":"romney"},
{"votes":23,"name":"uncommitted-r"}],
"total":721,"precincts":
{"total":13,"reporting":4},
"name":"Yankton"},
"Aurora":
{"votes":[
{"votes":58,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"paul"},
{"votes":1,"name":"romney"}],
"total":65,"precincts":
{"total":7,"reporting":3},
"name":"Aurora"},
"Hand":
{"votes":[
{"votes":179,"name":"mccain"},
{"votes":24,"name":"paul"},
{"votes":18,"name":"huckabee"},
{"votes":9,"name":"romney"},
{"votes":2,"name":"uncommitted-r"}],
"total":232,"precincts":
{"total":10,"reporting":4},
"name":"Hand"},
"Walworth":
{"votes":[
{"votes":180,"name":"mccain"},
{"votes":50,"name":"paul"},
{"votes":19,"name":"huckabee"},
{"votes":12,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":266,"precincts":
{"total":15,"reporting":4},
"name":"Walworth"},
"Codington":
{"votes":[
{"votes":286,"name":"mccain"},
{"votes":75,"name":"paul"},
{"votes":49,"name":"romney"},
{"votes":34,"name":"huckabee"},
{"votes":6,"name":"uncommitted-r"}],
"total":450,"precincts":
{"total":33,"reporting":11},
"name":"Codington"},
"Haakon":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Haakon"},
"Butte":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Butte"},
"Day":
{"votes":[
{"votes":26,"name":"mccain"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"uncommitted-r"}],
"total":30,"precincts":
{"total":14,"reporting":1},
"name":"Day"},
"Dewey":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Dewey"},
"Jones":
{"votes":[
{"votes":80,"name":"mccain"},
{"votes":16,"name":"paul"},
{"votes":10,"name":"huckabee"},
{"votes":3,"name":"uncommitted-r"},
{"votes":2,"name":"romney"}],
"total":111,"precincts":
{"total":3,"reporting":2},
"name":"Jones"},
"Davison":
{"votes":[
{"votes":816,"name":"mccain"},
{"votes":136,"name":"paul"},
{"votes":90,"name":"huckabee"},
{"votes":37,"name":"romney"},
{"votes":33,"name":"uncommitted-r"}],
"total":1112,"precincts":
{"total":8,"reporting":8},
"name":"Davison"},
"Lincoln":
{"votes":[
{"votes":105,"name":"mccain"},
{"votes":29,"name":"paul"},
{"votes":8,"name":"huckabee"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":149,"precincts":
{"total":29,"reporting":5},
"name":"Lincoln"},
"Spink":
{"votes":[
{"votes":57,"name":"mccain"},
{"votes":11,"name":"paul"},
{"votes":6,"name":"huckabee"},
{"votes":5,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":82,"precincts":
{"total":9,"reporting":2},
"name":"Spink"},
"Corson":
{"votes":[],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Corson"},
"Hutchinson":
{"votes":[
{"votes":186,"name":"mccain"},
{"votes":38,"name":"paul"},
{"votes":37,"name":"huckabee"},
{"votes":16,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":283,"precincts":
{"total":7,"reporting":3},
"name":"Hutchinson"},
"Lake":
{"votes":[
{"votes":237,"name":"mccain"},
{"votes":62,"name":"paul"},
{"votes":47,"name":"huckabee"},
{"votes":9,"name":"romney"},
{"votes":9,"name":"uncommitted-r"}],
"total":364,"precincts":
{"total":10,"reporting":4},
"name":"Lake"},
"Roberts":
{"votes":[
{"votes":87,"name":"mccain"},
{"votes":9,"name":"paul"},
{"votes":6,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":2,"name":"uncommitted-r"}],
"total":107,"precincts":
{"total":14,"reporting":2},
"name":"Roberts"},
"Meade":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Meade"},
"Mellette":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Mellette"},
"Faulk":
{"votes":[],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Faulk"},
"Hanson":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Hanson"},
"Gregory":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Gregory"},
"Buffalo":
{"votes":[],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Buffalo"},
"Ziebach":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Ziebach"},
"Tripp":
{"votes":[
{"votes":396,"name":"mccain"},
{"votes":71,"name":"paul"},
{"votes":25,"name":"huckabee"},
{"votes":14,"name":"uncommitted-r"},
{"votes":6,"name":"romney"}],
"total":512,"precincts":
{"total":13,"reporting":5},
"name":"Tripp"},
"Brule":
{"votes":[
{"votes":41,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":6,"name":"paul"}],
"total":53,"precincts":
{"total":5,"reporting":3},
"name":"Brule"},
"Sanborn":
{"votes":[
{"votes":5,"name":"mccain"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"uncommitted-r"},
{"votes":1,"name":"paul"},
{"votes":1,"name":"romney"}],
"total":13,"precincts":
{"total":4,"reporting":1},
"name":"Sanborn"},
"Harding":
{"votes":[],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Harding"},
"Clark":
{"votes":[
{"votes":15,"name":"mccain"},
{"votes":11,"name":"paul"},
{"votes":5,"name":"huckabee"},
{"votes":2,"name":"romney"}],
"total":33,"precincts":
{"total":13,"reporting":2},
"name":"Clark"},
"Fall River":
{"votes":[],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Fall River"},
"Marshall":
{"votes":[
{"votes":82,"name":"mccain"},
{"votes":11,"name":"paul"},
{"votes":8,"name":"huckabee"},
{"votes":4,"name":"romney"},
{"votes":3,"name":"uncommitted-r"}],
"total":108,"precincts":
{"total":9,"reporting":3},
"name":"Marshall"},
"Beadle":
{"votes":[
{"votes":273,"name":"mccain"},
{"votes":52,"name":"huckabee"},
{"votes":50,"name":"paul"},
{"votes":12,"name":"uncommitted-r"},
{"votes":10,"name":"romney"}],
"total":397,"precincts":
{"total":14,"reporting":5},
"name":"Beadle"},
"Potter":
{"votes":[],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Potter"},
"Charles Mix":
{"votes":[
{"votes":99,"name":"mccain"},
{"votes":14,"name":"huckabee"},
{"votes":13,"name":"paul"},
{"votes":4,"name":"romney"},
{"votes":3,"name":"uncommitted-r"}],
"total":133,"precincts":
{"total":13,"reporting":8},
"name":"Charles Mix"},
"Perkins":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Perkins"},
"Hyde":
{"votes":[],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Hyde"},
"Kingsbury":
{"votes":[
{"votes":102,"name":"mccain"},
{"votes":37,"name":"paul"},
{"votes":13,"name":"huckabee"},
{"votes":4,"name":"uncommitted-r"},
{"votes":3,"name":"romney"}],
"total":159,"precincts":
{"total":6,"reporting":1},
"name":"Kingsbury"},
"Todd":
{"votes":[],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Todd"},
"Campbell":
{"votes":[
{"votes":82,"name":"mccain"},
{"votes":20,"name":"paul"},
{"votes":11,"name":"huckabee"},
{"votes":7,"name":"uncommitted-r"},
{"votes":5,"name":"romney"}],
"total":125,"precincts":
{"total":5,"reporting":2},
"name":"Campbell"},
"Stanley":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Stanley"},
"Turner":
{"votes":[
{"votes":134,"name":"mccain"},
{"votes":45,"name":"paul"},
{"votes":34,"name":"huckabee"},
{"votes":5,"name":"romney"},
{"votes":2,"name":"uncommitted-r"}],
"total":220,"precincts":
{"total":8,"reporting":3},
"name":"Turner"},
"Moody":
{"votes":[
{"votes":13,"name":"mccain"},
{"votes":6,"name":"paul"},
{"votes":2,"name":"huckabee"}],
"total":21,"precincts":
{"total":6,"reporting":1},
"name":"Moody"},
"Shannon":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Shannon"},
"Bennett":
{"votes":[],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Bennett"}}})