GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":525034,"name":"obama","delegates":457},
{"votes":440330,"name":"clinton","delegates":474},
{"votes":7397,"name":"edwards"},
{"votes":2900,"name":"richardson"},
{"votes":1510,"name":"biden"},
{"votes":1022,"name":"dodd"}],
"name":"Texas","precincts":
{"total":8247,"reporting":186},
"delegates":193,"date":"03-04"},
"state":"TX","party":"dem","total":978193,"locals":
{"Wilson":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Wilson"},
"Zapata":
{"votes":[
{"votes":1002,"name":"clinton"},
{"votes":278,"name":"obama"},
{"votes":21,"name":"edwards"},
{"votes":15,"name":"richardson"},
{"votes":10,"name":"biden"},
{"votes":4,"name":"dodd"}],
"total":1330,"precincts":
{"total":8,"reporting":1},
"name":"Zapata"},
"Bowie":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Bowie"},
"Brewster":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Brewster"},
"Gonzales":
{"votes":[
{"votes":625,"name":"clinton"},
{"votes":509,"name":"obama"},
{"votes":71,"name":"edwards"},
{"votes":31,"name":"richardson"},
{"votes":9,"name":"dodd"},
{"votes":7,"name":"biden"}],
"total":1252,"precincts":
{"total":15,"reporting":1},
"name":"Gonzales"},
"Burnet":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Burnet"},
"Duval":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Duval"},
"Smith":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":78,"reporting":0},
"name":"Smith"},
"Chambers":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Chambers"},
"Erath":
{"votes":[
{"votes":704,"name":"clinton"},
{"votes":432,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"biden"}],
"total":1161,"precincts":
{"total":14,"reporting":1},
"name":"Erath"},
"Tyler":
{"votes":[
{"votes":849,"name":"clinton"},
{"votes":371,"name":"obama"},
{"votes":92,"name":"edwards"},
{"votes":25,"name":"richardson"},
{"votes":17,"name":"dodd"},
{"votes":15,"name":"biden"}],
"total":1369,"precincts":
{"total":18,"reporting":1},
"name":"Tyler"},
"Hill":
{"votes":[
{"votes":766,"name":"clinton"},
{"votes":318,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":1099,"precincts":
{"total":24,"reporting":1},
"name":"Hill"},
"Kent":
{"votes":[
{"votes":76,"name":"clinton"},
{"votes":28,"name":"obama"},
{"votes":9,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"dodd"}],
"total":122,"precincts":
{"total":7,"reporting":1},
"name":"Kent"},
"Bailey":
{"votes":[
{"votes":77,"name":"clinton"},
{"votes":53,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":137,"precincts":
{"total":5,"reporting":1},
"name":"Bailey"},
"Robertson":
{"votes":[
{"votes":627,"name":"obama"},
{"votes":597,"name":"clinton"},
{"votes":75,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":9,"name":"biden"},
{"votes":5,"name":"dodd"}],
"total":1323,"precincts":
{"total":16,"reporting":1},
"name":"Robertson"},
"Hudspeth":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Hudspeth"},
"La Salle":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"La Salle"},
"Throckmorton":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Throckmorton"},
"Henderson":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Henderson"},
"Irion":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Irion"},
"Brown":
{"votes":[
{"votes":655,"name":"clinton"},
{"votes":300,"name":"obama"},
{"votes":18,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":1,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":979,"precincts":
{"total":19,"reporting":1},
"name":"Brown"},
"Sabine":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Sabine"},
"Angelina":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":47,"reporting":0},
"name":"Angelina"},
"Goliad":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Goliad"},
"Upton":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Upton"},
"Live Oak":
{"votes":[
{"votes":135,"name":"clinton"},
{"votes":96,"name":"obama"},
{"votes":4,"name":"edwards"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":236,"precincts":
{"total":15,"reporting":1},
"name":"Live Oak"},
"Brooks":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Brooks"},
"Victoria":
{"votes":[
{"votes":1610,"name":"clinton"},
{"votes":1170,"name":"obama"},
{"votes":66,"name":"biden"},
{"votes":61,"name":"edwards"},
{"votes":17,"name":"dodd"},
{"votes":14,"name":"richardson"}],
"total":2938,"precincts":
{"total":36,"reporting":1},
"name":"Victoria"},
"Montague":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Montague"},
"El Paso":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":171,"reporting":0},
"name":"El Paso"},
"Harris":
{"votes":[
{"votes":110072,"name":"obama"},
{"votes":66221,"name":"clinton"},
{"votes":500,"name":"edwards"},
{"votes":156,"name":"richardson"},
{"votes":106,"name":"dodd"},
{"votes":76,"name":"biden"}],
"total":177131,"precincts":
{"total":875,"reporting":1},
"name":"Harris"},
"Fisher":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Fisher"},
"Crane":
{"votes":[
{"votes":282,"name":"clinton"},
{"votes":235,"name":"obama"},
{"votes":32,"name":"edwards"},
{"votes":29,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":1,"name":"dodd"}],
"total":583,"precincts":
{"total":5,"reporting":5},
"name":"Crane"},
"De Witt":
{"votes":[
{"votes":220,"name":"clinton"},
{"votes":162,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":394,"precincts":
{"total":10,"reporting":1},
"name":"De Witt"},
"Dimmit":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Dimmit"},
"Shackelford":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Shackelford"},
"Matagorda":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Matagorda"},
"Childress":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Childress"},
"Culberson":
{"votes":[
{"votes":102,"name":"clinton"},
{"votes":64,"name":"obama"},
{"votes":10,"name":"richardson"},
{"votes":6,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"dodd"}],
"total":186,"precincts":
{"total":6,"reporting":1},
"name":"Culberson"},
"Uvalde":
{"votes":[
{"votes":1420,"name":"clinton"},
{"votes":763,"name":"obama"},
{"votes":68,"name":"edwards"},
{"votes":33,"name":"richardson"},
{"votes":21,"name":"biden"},
{"votes":13,"name":"dodd"}],
"total":2318,"precincts":
{"total":15,"reporting":1},
"name":"Uvalde"},
"Ector":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Ector"},
"Camp":
{"votes":[
{"votes":349,"name":"clinton"},
{"votes":251,"name":"obama"},
{"votes":21,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"richardson"}],
"total":625,"precincts":
{"total":5,"reporting":1},
"name":"Camp"},
"Kerr":
{"votes":[
{"votes":1181,"name":"obama"},
{"votes":1005,"name":"clinton"},
{"votes":23,"name":"edwards"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"richardson"}],
"total":2220,"precincts":
{"total":21,"reporting":1},
"name":"Kerr"},
"Scurry":
{"votes":[
{"votes":211,"name":"clinton"},
{"votes":88,"name":"obama"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":304,"precincts":
{"total":12,"reporting":1},
"name":"Scurry"},
"Navarro":
{"votes":[
{"votes":1537,"name":"clinton"},
{"votes":1069,"name":"obama"},
{"votes":56,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":8,"name":"richardson"},
{"votes":3,"name":"dodd"}],
"total":2686,"precincts":
{"total":35,"reporting":12},
"name":"Navarro"},
"Burleson":
{"votes":[
{"votes":358,"name":"clinton"},
{"votes":234,"name":"obama"},
{"votes":15,"name":"edwards"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":609,"precincts":
{"total":16,"reporting":1},
"name":"Burleson"},
"Tarrant":
{"votes":[
{"votes":50855,"name":"obama"},
{"votes":35092,"name":"clinton"},
{"votes":280,"name":"edwards"},
{"votes":89,"name":"richardson"},
{"votes":64,"name":"biden"},
{"votes":22,"name":"dodd"}],
"total":86402,"precincts":
{"total":639,"reporting":0},
"name":"Tarrant"},
"San Jacinto":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"San Jacinto"},
"Montgomery":
{"votes":[
{"votes":6904,"name":"clinton"},
{"votes":6427,"name":"obama"},
{"votes":60,"name":"edwards"},
{"votes":16,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":3,"name":"biden"}],
"total":13415,"precincts":
{"total":86,"reporting":3},
"name":"Montgomery"},
"Upshur":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Upshur"},
"Colorado":
{"votes":[
{"votes":254,"name":"clinton"},
{"votes":252,"name":"obama"},
{"votes":4,"name":"edwards"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":512,"precincts":
{"total":13,"reporting":1},
"name":"Colorado"},
"Parker":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":44,"reporting":0},
"name":"Parker"},
"Aransas":
{"votes":[
{"votes":569,"name":"clinton"},
{"votes":527,"name":"obama"},
{"votes":12,"name":"edwards"},
{"votes":9,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":1119,"precincts":
{"total":7,"reporting":1},
"name":"Aransas"},
"Moore":
{"votes":[
{"votes":136,"name":"clinton"},
{"votes":70,"name":"obama"},
{"votes":7,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":217,"precincts":
{"total":8,"reporting":1},
"name":"Moore"},
"Armstrong":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":2},
"name":"Armstrong"},
"Freestone":
{"votes":[
{"votes":454,"name":"clinton"},
{"votes":358,"name":"obama"},
{"votes":32,"name":"edwards"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"biden"}],
"total":852,"precincts":
{"total":16,"reporting":1},
"name":"Freestone"},
"Panola":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Panola"},
"Potter":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Potter"},
"Hall":
{"votes":[
{"votes":125,"name":"clinton"},
{"votes":63,"name":"obama"},
{"votes":19,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":223,"precincts":
{"total":8,"reporting":1},
"name":"Hall"},
"Milam":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Milam"},
"Marion":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Marion"},
"Jasper":
{"votes":[
{"votes":1465,"name":"clinton"},
{"votes":1000,"name":"obama"},
{"votes":263,"name":"edwards"},
{"votes":53,"name":"richardson"},
{"votes":28,"name":"biden"},
{"votes":27,"name":"dodd"}],
"total":2836,"precincts":
{"total":21,"reporting":1},
"name":"Jasper"},
"Lampasas":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Lampasas"},
"Hemphill":
{"votes":[
{"votes":25,"name":"clinton"},
{"votes":17,"name":"obama"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"edwards"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":46,"precincts":
{"total":9,"reporting":1},
"name":"Hemphill"},
"McLennan":
{"votes":[
{"votes":4229,"name":"obama"},
{"votes":3876,"name":"clinton"},
{"votes":85,"name":"edwards"},
{"votes":12,"name":"richardson"},
{"votes":7,"name":"dodd"},
{"votes":4,"name":"biden"}],
"total":8213,"precincts":
{"total":93,"reporting":1},
"name":"McLennan"},
"Hartley":
{"votes":[
{"votes":80,"name":"clinton"},
{"votes":28,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":115,"precincts":
{"total":7,"reporting":1},
"name":"Hartley"},
"Newton":
{"votes":[
{"votes":459,"name":"clinton"},
{"votes":180,"name":"obama"},
{"votes":50,"name":"edwards"},
{"votes":14,"name":"richardson"},
{"votes":10,"name":"biden"},
{"votes":9,"name":"dodd"}],
"total":722,"precincts":
{"total":23,"reporting":1},
"name":"Newton"},
"Jackson":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Jackson"},
"Schleicher":
{"votes":[
{"votes":65,"name":"clinton"},
{"votes":46,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"}],
"total":120,"precincts":
{"total":5,"reporting":1},
"name":"Schleicher"},
"Pecos":
{"votes":[
{"votes":480,"name":"clinton"},
{"votes":285,"name":"obama"},
{"votes":38,"name":"edwards"},
{"votes":20,"name":"richardson"},
{"votes":8,"name":"biden"},
{"votes":4,"name":"dodd"}],
"total":835,"precincts":
{"total":10,"reporting":1},
"name":"Pecos"},
"Caldwell":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":27,"reporting":0},
"name":"Caldwell"},
"Oldham":
{"votes":[
{"votes":24,"name":"clinton"},
{"votes":16,"name":"obama"},
{"votes":4,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"}],
"total":44,"precincts":
{"total":8,"reporting":1},
"name":"Oldham"},
"Deaf Smith":
{"votes":[
{"votes":210,"name":"clinton"},
{"votes":100,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":318,"precincts":
{"total":5,"reporting":1},
"name":"Deaf Smith"},
"Mills":
{"votes":[
{"votes":174,"name":"clinton"},
{"votes":102,"name":"obama"},
{"votes":18,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":309,"precincts":
{"total":7,"reporting":1},
"name":"Mills"},
"Liberty":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Liberty"},
"Mason":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Mason"},
"Anderson":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":25,"reporting":0},
"name":"Anderson"},
"Jefferson":
{"votes":[
{"votes":13282,"name":"obama"},
{"votes":7358,"name":"clinton"},
{"votes":204,"name":"edwards"},
{"votes":93,"name":"richardson"},
{"votes":30,"name":"biden"},
{"votes":26,"name":"dodd"}],
"total":20993,"precincts":
{"total":117,"reporting":1},
"name":"Jefferson"},
"Dickens":
{"votes":[
{"votes":81,"name":"clinton"},
{"votes":49,"name":"obama"},
{"votes":15,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"}],
"total":153,"precincts":
{"total":7,"reporting":1},
"name":"Dickens"},
"Orange":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Orange"},
"Hardin":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":20,"reporting":0},
"name":"Hardin"},
"Howard":
{"votes":[
{"votes":658,"name":"clinton"},
{"votes":335,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"dodd"}],
"total":1030,"precincts":
{"total":6,"reporting":1},
"name":"Howard"},
"Nacogdoches":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Nacogdoches"},
"Lamar":
{"votes":[
{"votes":1575,"name":"clinton"},
{"votes":979,"name":"obama"},
{"votes":123,"name":"edwards"},
{"votes":37,"name":"biden"},
{"votes":25,"name":"richardson"},
{"votes":14,"name":"dodd"}],
"total":2753,"precincts":
{"total":32,"reporting":1},
"name":"Lamar"},
"Lee":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":16,"reporting":0},
"name":"Lee"},
"Motley":
{"votes":[
{"votes":32,"name":"clinton"},
{"votes":16,"name":"obama"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"}],
"total":48,"precincts":
{"total":7,"reporting":3},
"name":"Motley"},
"Maverick":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Maverick"},
"Sherman":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Sherman"},
"Crockett":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Crockett"},
"Andrews":
{"votes":[
{"votes":227,"name":"clinton"},
{"votes":157,"name":"obama"},
{"votes":37,"name":"edwards"},
{"votes":12,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":1,"name":"dodd"}],
"total":438,"precincts":
{"total":5,"reporting":1},
"name":"Andrews"},
"Jeff Davis":
{"votes":[
{"votes":141,"name":"obama"},
{"votes":133,"name":"clinton"},
{"votes":22,"name":"edwards"},
{"votes":12,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":313,"precincts":
{"total":6,"reporting":2},
"name":"Jeff Davis"},
"Trinity":
{"votes":[
{"votes":1178,"name":"clinton"},
{"votes":689,"name":"obama"},
{"votes":189,"name":"edwards"},
{"votes":49,"name":"richardson"},
{"votes":28,"name":"biden"},
{"votes":17,"name":"dodd"}],
"total":2150,"precincts":
{"total":20,"reporting":1},
"name":"Trinity"},
"Terry":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Terry"},
"Randall":
{"votes":[
{"votes":2556,"name":"clinton"},
{"votes":1679,"name":"obama"},
{"votes":33,"name":"edwards"},
{"votes":20,"name":"richardson"},
{"votes":9,"name":"biden"},
{"votes":4,"name":"dodd"}],
"total":4301,"precincts":
{"total":30,"reporting":3},
"name":"Randall"},
"Ward":
{"votes":[
{"votes":485,"name":"clinton"},
{"votes":319,"name":"obama"},
{"votes":122,"name":"edwards"},
{"votes":44,"name":"richardson"},
{"votes":21,"name":"biden"},
{"votes":12,"name":"dodd"}],
"total":1003,"precincts":
{"total":9,"reporting":1},
"name":"Ward"},
"Reeves":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Reeves"},
"Rusk":
{"votes":[
{"votes":836,"name":"clinton"},
{"votes":791,"name":"obama"},
{"votes":42,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":3,"name":"biden"}],
"total":1687,"precincts":
{"total":23,"reporting":1},
"name":"Rusk"},
"McMullen":
{"votes":[
{"votes":36,"name":"obama"},
{"votes":35,"name":"clinton"},
{"votes":9,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"dodd"}],
"total":88,"precincts":
{"total":6,"reporting":1},
"name":"McMullen"},
"Johnson":
{"votes":[
{"votes":3267,"name":"clinton"},
{"votes":1547,"name":"obama"},
{"votes":33,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"richardson"}],
"total":4858,"precincts":
{"total":22,"reporting":1},
"name":"Johnson"},
"Hopkins":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Hopkins"},
"Menard":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Menard"},
"Stonewall":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Stonewall"},
"Knox":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Knox"},
"Baylor":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Baylor"},
"Archer":
{"votes":[
{"votes":121,"name":"clinton"},
{"votes":43,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":175,"precincts":
{"total":15,"reporting":1},
"name":"Archer"},
"Castro":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Castro"},
"Clay":
{"votes":[
{"votes":240,"name":"clinton"},
{"votes":87,"name":"obama"},
{"votes":31,"name":"edwards"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"richardson"}],
"total":368,"precincts":
{"total":17,"reporting":1},
"name":"Clay"},
"Comal":
{"votes":[
{"votes":1852,"name":"obama"},
{"votes":1690,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":8,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":3579,"precincts":
{"total":23,"reporting":1},
"name":"Comal"},
"Frio":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Frio"},
"Webb":
{"votes":[
{"votes":21251,"name":"clinton"},
{"votes":5752,"name":"obama"},
{"votes":286,"name":"edwards"},
{"votes":185,"name":"richardson"},
{"votes":101,"name":"biden"},
{"votes":55,"name":"dodd"}],
"total":27630,"precincts":
{"total":58,"reporting":1},
"name":"Webb"},
"Winkler":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Winkler"},
"Madison":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Madison"},
"Taylor":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Taylor"},
"Van Zandt":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Van Zandt"},
"Polk":
{"votes":[
{"votes":1844,"name":"clinton"},
{"votes":992,"name":"obama"},
{"votes":77,"name":"edwards"},
{"votes":27,"name":"richardson"},
{"votes":14,"name":"biden"},
{"votes":10,"name":"dodd"}],
"total":2964,"precincts":
{"total":21,"reporting":1},
"name":"Polk"},
"Briscoe":
{"votes":[
{"votes":35,"name":"clinton"},
{"votes":24,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"}],
"total":62,"precincts":
{"total":6,"reporting":1},
"name":"Briscoe"},
"Collingsworth":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Collingsworth"},
"Bosque":
{"votes":[
{"votes":294,"name":"clinton"},
{"votes":187,"name":"obama"},
{"votes":43,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":533,"precincts":
{"total":17,"reporting":1},
"name":"Bosque"},
"Kendall":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Kendall"},
"Refugio":
{"votes":[
{"votes":662,"name":"clinton"},
{"votes":459,"name":"obama"},
{"votes":45,"name":"edwards"},
{"votes":9,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"biden"}],
"total":1182,"precincts":
{"total":11,"reporting":5},
"name":"Refugio"},
"Cameron":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":99,"reporting":0},
"name":"Cameron"},
"Nueces":
{"votes":[
{"votes":13964,"name":"clinton"},
{"votes":7288,"name":"obama"},
{"votes":127,"name":"edwards"},
{"votes":81,"name":"richardson"},
{"votes":28,"name":"biden"},
{"votes":13,"name":"dodd"}],
"total":21501,"precincts":
{"total":127,"reporting":1},
"name":"Nueces"},
"Wilbarger":
{"votes":[
{"votes":467,"name":"clinton"},
{"votes":247,"name":"obama"},
{"votes":72,"name":"edwards"},
{"votes":21,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":3,"name":"dodd"}],
"total":816,"precincts":
{"total":7,"reporting":1},
"name":"Wilbarger"},
"Hidalgo":
{"votes":[
{"votes":37645,"name":"clinton"},
{"votes":12520,"name":"obama"},
{"votes":347,"name":"edwards"},
{"votes":311,"name":"richardson"},
{"votes":117,"name":"biden"},
{"votes":57,"name":"dodd"}],
"total":50997,"precincts":
{"total":141,"reporting":1},
"name":"Hidalgo"},
"Gillespie":
{"votes":[
{"votes":578,"name":"obama"},
{"votes":449,"name":"clinton"},
{"votes":10,"name":"edwards"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":1042,"precincts":
{"total":7,"reporting":1},
"name":"Gillespie"},
"Lamb":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Lamb"},
"Bexar":
{"votes":[
{"votes":56013,"name":"clinton"},
{"votes":46218,"name":"obama"},
{"votes":434,"name":"edwards"},
{"votes":380,"name":"richardson"},
{"votes":139,"name":"dodd"},
{"votes":129,"name":"biden"}],
"total":103313,"precincts":
{"total":623,"reporting":0},
"name":"Bexar"},
"McCulloch":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"McCulloch"},
"Midland":
{"votes":[
{"votes":1613,"name":"clinton"},
{"votes":1538,"name":"obama"},
{"votes":23,"name":"edwards"},
{"votes":15,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"biden"}],
"total":3199,"precincts":
{"total":11,"reporting":1},
"name":"Midland"},
"Dallas":
{"votes":[
{"votes":81245,"name":"obama"},
{"votes":41318,"name":"clinton"},
{"votes":324,"name":"edwards"},
{"votes":155,"name":"biden"},
{"votes":139,"name":"richardson"},
{"votes":79,"name":"dodd"}],
"total":123260,"precincts":
{"total":695,"reporting":0},
"name":"Dallas"},
"Cherokee":
{"votes":[
{"votes":908,"name":"clinton"},
{"votes":633,"name":"obama"},
{"votes":44,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":3,"name":"dodd"}],
"total":1606,"precincts":
{"total":29,"reporting":1},
"name":"Cherokee"},
"Collin":
{"votes":[
{"votes":21719,"name":"obama"},
{"votes":14533,"name":"clinton"},
{"votes":117,"name":"edwards"},
{"votes":36,"name":"richardson"},
{"votes":17,"name":"dodd"},
{"votes":17,"name":"biden"}],
"total":36439,"precincts":
{"total":163,"reporting":1},
"name":"Collin"},
"Martin":
{"votes":[
{"votes":96,"name":"clinton"},
{"votes":45,"name":"obama"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"edwards"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":159,"precincts":
{"total":7,"reporting":1},
"name":"Martin"},
"Young":
{"votes":[
{"votes":560,"name":"clinton"},
{"votes":254,"name":"obama"},
{"votes":21,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"dodd"}],
"total":844,"precincts":
{"total":7,"reporting":1},
"name":"Young"},
"Parmer":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Parmer"},
"Guadalupe":
{"votes":[
{"votes":3176,"name":"obama"},
{"votes":2541,"name":"clinton"},
{"votes":35,"name":"edwards"},
{"votes":8,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":4,"name":"biden"}],
"total":5769,"precincts":
{"total":39,"reporting":1},
"name":"Guadalupe"},
"San Augustine":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"San Augustine"},
"Hockley":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Hockley"},
"Palo Pinto":
{"votes":[
{"votes":578,"name":"clinton"},
{"votes":225,"name":"obama"},
{"votes":9,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":819,"precincts":
{"total":31,"reporting":1},
"name":"Palo Pinto"},
"Starr":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Starr"},
"Shelby":
{"votes":[
{"votes":636,"name":"clinton"},
{"votes":274,"name":"obama"},
{"votes":33,"name":"edwards"},
{"votes":6,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":955,"precincts":
{"total":15,"reporting":1},
"name":"Shelby"},
"Dallam":
{"votes":[
{"votes":27,"name":"clinton"},
{"votes":13,"name":"obama"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"}],
"total":40,"precincts":
{"total":5,"reporting":1},
"name":"Dallam"},
"Tom Green":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":61,"reporting":0},
"name":"Tom Green"},
"Wharton":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":21,"reporting":0},
"name":"Wharton"},
"Hamilton":
{"votes":[
{"votes":290,"name":"clinton"},
{"votes":207,"name":"obama"},
{"votes":32,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"dodd"}],
"total":541,"precincts":
{"total":5,"reporting":1},
"name":"Hamilton"},
"Gregg":
{"votes":[
{"votes":3283,"name":"obama"},
{"votes":2102,"name":"clinton"},
{"votes":31,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"biden"}],
"total":5429,"precincts":
{"total":24,"reporting":1},
"name":"Gregg"},
"Wheeler":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Wheeler"},
"Ochiltree":
{"votes":[
{"votes":24,"name":"clinton"},
{"votes":12,"name":"obama"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"}],
"total":39,"precincts":
{"total":5,"reporting":1},
"name":"Ochiltree"},
"Fayette":
{"votes":[
{"votes":650,"name":"clinton"},
{"votes":582,"name":"obama"},
{"votes":59,"name":"edwards"},
{"votes":23,"name":"richardson"},
{"votes":14,"name":"dodd"},
{"votes":10,"name":"biden"}],
"total":1338,"precincts":
{"total":27,"reporting":1},
"name":"Fayette"},
"Medina":
{"votes":[
{"votes":987,"name":"clinton"},
{"votes":670,"name":"obama"},
{"votes":20,"name":"edwards"},
{"votes":12,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"dodd"}],
"total":1693,"precincts":
{"total":18,"reporting":1},
"name":"Medina"},
"Blanco":
{"votes":[
{"votes":230,"name":"obama"},
{"votes":182,"name":"clinton"},
{"votes":4,"name":"edwards"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":417,"precincts":
{"total":5,"reporting":1},
"name":"Blanco"},
"Jim Hogg":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Jim Hogg"},
"Floyd":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Floyd"},
"Garza":
{"votes":[
{"votes":104,"name":"clinton"},
{"votes":77,"name":"obama"},
{"votes":44,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"dodd"}],
"total":235,"precincts":
{"total":7,"reporting":1},
"name":"Garza"},
"Sterling":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Sterling"},
"Kenedy":
{"votes":[
{"votes":34,"name":"clinton"},
{"votes":19,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":62,"precincts":
{"total":7,"reporting":1},
"name":"Kenedy"},
"Jim Wells":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Jim Wells"},
"Kinney":
{"votes":[
{"votes":195,"name":"clinton"},
{"votes":185,"name":"obama"},
{"votes":17,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":5,"name":"dodd"},
{"votes":1,"name":"biden"}],
"total":414,"precincts":
{"total":5,"reporting":1},
"name":"Kinney"},
"Borden":
{"votes":[
{"votes":20,"name":"clinton"},
{"votes":7,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":30,"precincts":
{"total":8,"reporting":1},
"name":"Borden"},
"Eastland":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Eastland"},
"Houston":
{"votes":[
{"votes":478,"name":"obama"},
{"votes":460,"name":"clinton"},
{"votes":39,"name":"edwards"},
{"votes":8,"name":"dodd"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"richardson"}],
"total":994,"precincts":
{"total":22,"reporting":1},
"name":"Houston"},
"King":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"King"},
"Delta":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Delta"},
"Stephens":
{"votes":[
{"votes":240,"name":"clinton"},
{"votes":116,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":388,"precincts":
{"total":7,"reporting":1},
"name":"Stephens"},
"Bee":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Bee"},
"Rains":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Rains"},
"Somervell":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Somervell"},
"Franklin":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Franklin"},
"Gaines":
{"votes":[
{"votes":163,"name":"clinton"},
{"votes":66,"name":"obama"},
{"votes":9,"name":"edwards"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":241,"precincts":
{"total":9,"reporting":1},
"name":"Gaines"},
"Walker":
{"votes":[
{"votes":1093,"name":"obama"},
{"votes":971,"name":"clinton"},
{"votes":25,"name":"edwards"},
{"votes":7,"name":"richardson"},
{"votes":5,"name":"biden"},
{"votes":3,"name":"dodd"}],
"total":2104,"precincts":
{"total":19,"reporting":1},
"name":"Walker"},
"Terrell":
{"votes":[
{"votes":55,"name":"clinton"},
{"votes":26,"name":"obama"},
{"votes":8,"name":"edwards"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"},
{"votes":0,"name":"richardson"}],
"total":91,"precincts":
{"total":5,"reporting":1},
"name":"Terrell"},
"Austin":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Austin"},
"Carson":
{"votes":[
{"votes":89,"name":"clinton"},
{"votes":51,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":143,"precincts":
{"total":10,"reporting":1},
"name":"Carson"},
"Llano":
{"votes":[
{"votes":608,"name":"clinton"},
{"votes":436,"name":"obama"},
{"votes":8,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":1055,"precincts":
{"total":10,"reporting":1},
"name":"Llano"},
"Washington":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":34,"reporting":0},
"name":"Washington"},
"Cottle":
{"votes":[
{"votes":85,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":13,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":1,"name":"dodd"}],
"total":157,"precincts":
{"total":6,"reporting":1},
"name":"Cottle"},
"Reagan":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Reagan"},
"Leon":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Leon"},
"Kaufman":
{"votes":[
{"votes":2170,"name":"clinton"},
{"votes":2010,"name":"obama"},
{"votes":30,"name":"edwards"},
{"votes":11,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"biden"}],
"total":4227,"precincts":
{"total":42,"reporting":1},
"name":"Kaufman"},
"Bandera":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Bandera"},
"Crosby":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Crosby"},
"Harrison":
{"votes":[
{"votes":2023,"name":"clinton"},
{"votes":1933,"name":"obama"},
{"votes":130,"name":"edwards"},
{"votes":48,"name":"richardson"},
{"votes":20,"name":"biden"},
{"votes":9,"name":"dodd"}],
"total":4163,"precincts":
{"total":26,"reporting":1},
"name":"Harrison"},
"Brazoria":
{"votes":[
{"votes":8013,"name":"obama"},
{"votes":6845,"name":"clinton"},
{"votes":103,"name":"edwards"},
{"votes":34,"name":"richardson"},
{"votes":23,"name":"biden"},
{"votes":9,"name":"dodd"}],
"total":15027,"precincts":
{"total":72,"reporting":1},
"name":"Brazoria"},
"Hardeman":
{"votes":[
{"votes":640,"name":"clinton"},
{"votes":246,"name":"obama"},
{"votes":139,"name":"edwards"},
{"votes":38,"name":"richardson"},
{"votes":17,"name":"biden"},
{"votes":6,"name":"dodd"}],
"total":1086,"precincts":
{"total":6,"reporting":6},
"name":"Hardeman"},
"San Patricio":
{"votes":[
{"votes":2191,"name":"clinton"},
{"votes":943,"name":"obama"},
{"votes":50,"name":"edwards"},
{"votes":30,"name":"richardson"},
{"votes":10,"name":"biden"},
{"votes":7,"name":"dodd"}],
"total":3231,"precincts":
{"total":26,"reporting":1},
"name":"San Patricio"},
"Hood":
{"votes":[
{"votes":1200,"name":"clinton"},
{"votes":714,"name":"obama"},
{"votes":23,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"biden"}],
"total":1949,"precincts":
{"total":17,"reporting":1},
"name":"Hood"},
"Red River":
{"votes":[
{"votes":181,"name":"obama"},
{"votes":55,"name":"edwards"},
{"votes":47,"name":"clinton"},
{"votes":14,"name":"richardson"},
{"votes":13,"name":"biden"},
{"votes":7,"name":"dodd"}],
"total":317,"precincts":
{"total":23,"reporting":1},
"name":"Red River"},
"Rockwall":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":17,"reporting":0},
"name":"Rockwall"},
"Ellis":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":46,"reporting":0},
"name":"Ellis"},
"Sutton":
{"votes":[
{"votes":87,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":133,"precincts":
{"total":7,"reporting":1},
"name":"Sutton"},
"Galveston":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":102,"reporting":0},
"name":"Galveston"},
"Lubbock":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":92,"reporting":0},
"name":"Lubbock"},
"Edwards":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Edwards"},
"Calhoun":
{"votes":[
{"votes":939,"name":"clinton"},
{"votes":572,"name":"obama"},
{"votes":85,"name":"edwards"},
{"votes":23,"name":"richardson"},
{"votes":10,"name":"dodd"},
{"votes":5,"name":"biden"}],
"total":1634,"precincts":
{"total":26,"reporting":1},
"name":"Calhoun"},
"Swisher":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Swisher"},
"Lipscomb":
{"votes":[
{"votes":14,"name":"clinton"},
{"votes":7,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"}],
"total":23,"precincts":
{"total":8,"reporting":1},
"name":"Lipscomb"},
"Karnes":
{"votes":[
{"votes":435,"name":"clinton"},
{"votes":303,"name":"obama"},
{"votes":42,"name":"edwards"},
{"votes":11,"name":"biden"},
{"votes":10,"name":"richardson"},
{"votes":4,"name":"dodd"}],
"total":805,"precincts":
{"total":16,"reporting":1},
"name":"Karnes"},
"Wood":
{"votes":[
{"votes":672,"name":"clinton"},
{"votes":417,"name":"obama"},
{"votes":12,"name":"edwards"},
{"votes":3,"name":"biden"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"richardson"}],
"total":1104,"precincts":
{"total":13,"reporting":1},
"name":"Wood"},
"Donley":
{"votes":[
{"votes":102,"name":"clinton"},
{"votes":34,"name":"obama"},
{"votes":9,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":1,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":151,"precincts":
{"total":5,"reporting":1},
"name":"Donley"},
"Coleman":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":6,"reporting":0},
"name":"Coleman"},
"Glasscock":
{"votes":[
{"votes":1,"name":"clinton"},
{"votes":1,"name":"obama"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"}],
"total":2,"precincts":
{"total":5,"reporting":1},
"name":"Glasscock"},
"Loving":
{"votes":[
{"votes":7,"name":"obama"},
{"votes":5,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":22,"precincts":
{"total":5,"reporting":5},
"name":"Loving"},
"Real":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":5,"reporting":0},
"name":"Real"},
"Williamson":
{"votes":[
{"votes":13985,"name":"obama"},
{"votes":9313,"name":"clinton"},
{"votes":81,"name":"edwards"},
{"votes":23,"name":"richardson"},
{"votes":14,"name":"biden"},
{"votes":7,"name":"dodd"}],
"total":23423,"precincts":
{"total":100,"reporting":0},
"name":"Williamson"},
"Runnels":
{"votes":[
{"votes":130,"name":"clinton"},
{"votes":92,"name":"obama"},
{"votes":9,"name":"edwards"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":233,"precincts":
{"total":11,"reporting":1},
"name":"Runnels"},
"Travis":
{"votes":[
{"votes":63154,"name":"obama"},
{"votes":33401,"name":"clinton"},
{"votes":378,"name":"edwards"},
{"votes":141,"name":"richardson"},
{"votes":77,"name":"biden"},
{"votes":48,"name":"dodd"}],
"total":97199,"precincts":
{"total":211,"reporting":0},
"name":"Travis"},
"Coke":
{"votes":[
{"votes":125,"name":"clinton"},
{"votes":73,"name":"obama"},
{"votes":45,"name":"edwards"},
{"votes":10,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":3,"name":"dodd"}],
"total":263,"precincts":
{"total":5,"reporting":1},
"name":"Coke"},
"Brazos":
{"votes":[
{"votes":2849,"name":"obama"},
{"votes":1801,"name":"clinton"},
{"votes":31,"name":"edwards"},
{"votes":7,"name":"richardson"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"dodd"}],
"total":4694,"precincts":
{"total":43,"reporting":1},
"name":"Brazos"},
"Falls":
{"votes":[
{"votes":333,"name":"clinton"},
{"votes":321,"name":"obama"},
{"votes":22,"name":"edwards"},
{"votes":7,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":1,"name":"biden"}],
"total":687,"precincts":
{"total":14,"reporting":1},
"name":"Falls"},
"Cochran":
{"votes":[
{"votes":40,"name":"clinton"},
{"votes":25,"name":"obama"},
{"votes":4,"name":"edwards"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":71,"precincts":
{"total":6,"reporting":1},
"name":"Cochran"},
"Nolan":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Nolan"},
"Hale":
{"votes":[
{"votes":480,"name":"clinton"},
{"votes":281,"name":"obama"},
{"votes":14,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"biden"}],
"total":785,"precincts":
{"total":6,"reporting":1},
"name":"Hale"},
"Jack":
{"votes":[
{"votes":157,"name":"clinton"},
{"votes":104,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":5,"name":"richardson"},
{"votes":1,"name":"biden"},
{"votes":0,"name":"dodd"}],
"total":277,"precincts":
{"total":7,"reporting":1},
"name":"Jack"},
"Denton":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":123,"reporting":0},
"name":"Denton"},
"Titus":
{"votes":[
{"votes":771,"name":"clinton"},
{"votes":622,"name":"obama"},
{"votes":97,"name":"edwards"},
{"votes":33,"name":"richardson"},
{"votes":15,"name":"dodd"},
{"votes":10,"name":"biden"}],
"total":1548,"precincts":
{"total":20,"reporting":1},
"name":"Titus"},
"Jones":
{"votes":[
{"votes":245,"name":"clinton"},
{"votes":70,"name":"obama"},
{"votes":12,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":330,"precincts":
{"total":15,"reporting":1},
"name":"Jones"},
"Lynn":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Lynn"},
"Hutchinson":
{"votes":[
{"votes":385,"name":"clinton"},
{"votes":178,"name":"obama"},
{"votes":7,"name":"edwards"},
{"votes":7,"name":"richardson"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":577,"precincts":
{"total":9,"reporting":1},
"name":"Hutchinson"},
"Wise":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Wise"},
"Hansford":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":2},
"name":"Hansford"},
"Fort Bend":
{"votes":[
{"votes":24419,"name":"obama"},
{"votes":10283,"name":"clinton"},
{"votes":64,"name":"edwards"},
{"votes":19,"name":"richardson"},
{"votes":12,"name":"dodd"},
{"votes":10,"name":"biden"}],
"total":34807,"precincts":
{"total":140,"reporting":1},
"name":"Fort Bend"},
"Hays":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Hays"},
"Hunt":
{"votes":[
{"votes":1210,"name":"clinton"},
{"votes":831,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"biden"}],
"total":2077,"precincts":
{"total":37,"reporting":1},
"name":"Hunt"},
"Wichita":
{"votes":[
{"votes":3145,"name":"clinton"},
{"votes":2185,"name":"obama"},
{"votes":105,"name":"edwards"},
{"votes":20,"name":"richardson"},
{"votes":13,"name":"biden"},
{"votes":12,"name":"dodd"}],
"total":5480,"precincts":
{"total":36,"reporting":1},
"name":"Wichita"},
"Willacy":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Willacy"},
"Concho":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":9,"reporting":0},
"name":"Concho"},
"Grayson":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":55,"reporting":0},
"name":"Grayson"},
"Morris":
{"votes":[
{"votes":513,"name":"clinton"},
{"votes":282,"name":"obama"},
{"votes":62,"name":"edwards"},
{"votes":15,"name":"richardson"},
{"votes":8,"name":"biden"},
{"votes":2,"name":"dodd"}],
"total":882,"precincts":
{"total":10,"reporting":1},
"name":"Morris"},
"Bell":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":50,"reporting":0},
"name":"Bell"},
"Cass":
{"votes":[
{"votes":689,"name":"clinton"},
{"votes":299,"name":"obama"},
{"votes":81,"name":"edwards"},
{"votes":13,"name":"biden"},
{"votes":8,"name":"richardson"},
{"votes":5,"name":"dodd"}],
"total":1095,"precincts":
{"total":21,"reporting":1},
"name":"Cass"},
"Waller":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":19,"reporting":0},
"name":"Waller"},
"Yoakum":
{"votes":[
{"votes":184,"name":"clinton"},
{"votes":67,"name":"obama"},
{"votes":12,"name":"edwards"},
{"votes":6,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"}],
"total":271,"precincts":
{"total":7,"reporting":1},
"name":"Yoakum"},
"Gray":
{"votes":[
{"votes":263,"name":"clinton"},
{"votes":171,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":447,"precincts":
{"total":8,"reporting":1},
"name":"Gray"},
"Kleberg":
{"votes":[
{"votes":2132,"name":"clinton"},
{"votes":1002,"name":"obama"},
{"votes":78,"name":"edwards"},
{"votes":27,"name":"richardson"},
{"votes":16,"name":"biden"},
{"votes":13,"name":"dodd"}],
"total":3268,"precincts":
{"total":21,"reporting":7},
"name":"Kleberg"},
"Mitchell":
{"votes":[
{"votes":250,"name":"clinton"},
{"votes":112,"name":"obama"},
{"votes":37,"name":"edwards"},
{"votes":14,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"dodd"}],
"total":418,"precincts":
{"total":7,"reporting":1},
"name":"Mitchell"},
"Dawson":
{"votes":[
{"votes":487,"name":"clinton"},
{"votes":238,"name":"obama"},
{"votes":22,"name":"edwards"},
{"votes":9,"name":"dodd"},
{"votes":9,"name":"richardson"},
{"votes":5,"name":"biden"}],
"total":770,"precincts":
{"total":12,"reporting":6},
"name":"Dawson"},
"Grimes":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Grimes"},
"Comanche":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Comanche"},
"Roberts":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":2,"reporting":2},
"name":"Roberts"},
"Limestone":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Limestone"},
"Val Verde":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":14,"reporting":0},
"name":"Val Verde"},
"Zavala":
{"votes":[
{"votes":1610,"name":"clinton"},
{"votes":509,"name":"obama"},
{"votes":33,"name":"edwards"},
{"votes":21,"name":"richardson"},
{"votes":18,"name":"biden"},
{"votes":8,"name":"dodd"}],
"total":2199,"precincts":
{"total":7,"reporting":1},
"name":"Zavala"},
"Presidio":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Presidio"},
"Coryell":
{"votes":[
{"votes":1093,"name":"obama"},
{"votes":955,"name":"clinton"},
{"votes":25,"name":"edwards"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":2,"name":"dodd"}],
"total":2086,"precincts":
{"total":21,"reporting":1},
"name":"Coryell"},
"Atascosa":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":24,"reporting":0},
"name":"Atascosa"},
"Fannin":
{"votes":[
{"votes":819,"name":"clinton"},
{"votes":354,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"dodd"},
{"votes":2,"name":"biden"}],
"total":1207,"precincts":
{"total":20,"reporting":1},
"name":"Fannin"},
"Foard":
{"votes":[
{"votes":147,"name":"clinton"},
{"votes":60,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":5,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":2,"name":"dodd"}],
"total":246,"precincts":
{"total":5,"reporting":4},
"name":"Foard"},
"Kimble":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":8,"reporting":0},
"name":"Kimble"},
"Haskell":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Haskell"},
"Bastrop":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Bastrop"},
"Callahan":
{"votes":[
{"votes":251,"name":"clinton"},
{"votes":128,"name":"obama"},
{"votes":14,"name":"edwards"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":395,"precincts":
{"total":8,"reporting":1},
"name":"Callahan"},
"Cooke":
{"votes":[
{"votes":0,"name":"clinton"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"obama"}],
"total":0,"precincts":
{"total":26,"reporting":0},
"name":"Cooke"},
"San Saba":
{"votes":[
{"votes":26,"name":"clinton"},
{"votes":10,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"}],
"total":37,"precincts":
{"total":5,"reporting":1},
"name":"San Saba"},
"La Vaca":
{"votes":[
{"votes":456,"name":"clinton"},
{"votes":272,"name":"obama"},
{"votes":54,"name":"edwards"},
{"votes":15,"name":"richardson"},
{"votes":10,"name":"biden"},
{"votes":2,"name":"dodd"}],
"total":809,"precincts":
{"total":20,"reporting":1},
"name":"La Vaca"}}})