GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":5355,"name":"clinton","delegates":12},
{"votes":4773,"name":"obama","delegates":13},
{"votes":396,"name":"edwards"},
{"votes":31,"name":"uncommitted-d"},
{"votes":5,"name":"kucinich"},
{"votes":0,"name":"gravel"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"}],
"precincts":
{"total":0,"reporting":0}},
"state":"US","party":"dem","total":10560,"locals":
{"Nevada":
{"name":"Nevada","precincts":
{"total":1797,"reporting":1762},
"votes":[
{"votes":5355,"name":"clinton","delegates":12},
{"votes":4773,"name":"obama","delegates":13},
{"votes":396,"name":"edwards"},
{"votes":31,"name":"uncommitted-d"},
{"votes":5,"name":"kucinich"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"gravel"}],
"delegates":25,"date":"01-19","type":"caucus"}}})