GoogleElectionMap.votesReady({"status":"ok","totals":
{"date":"03-04","votes":[
{"votes":21632,"name":"obama"},
{"votes":19331,"name":"clinton"},
{"votes":4603,"name":"edwards"},
{"votes":460,"name":"kucinich"}],
"precincts":
{"total":260,"reporting":260},
"name":"Vermont"},
"state":"VT","party":"dem","total":46026,"locals":
{"Albany":
{"votes":[
{"votes":98,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"obama"}],
"total":98,"precincts":
{"total":1,"reporting":1},
"name":"Albany"},
"Sheldon":
{"votes":[
{"votes":66,"name":"obama"},
{"votes":39,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"}],
"total":107,"precincts":
{"total":1,"reporting":1},
"name":"Sheldon"},
"Jay":
{"votes":[
{"votes":6,"name":"kucinich"},
{"votes":6,"name":"edwards"},
{"votes":6,"name":"clinton"},
{"votes":6,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Jay"},
"Arlington":
{"votes":[
{"votes":168,"name":"edwards"},
{"votes":7,"name":"clinton"},
{"votes":5,"name":"kucinich"},
{"votes":5,"name":"obama"}],
"total":185,"precincts":
{"total":1,"reporting":1},
"name":"Arlington"},
"Barnet":
{"votes":[
{"votes":86,"name":"clinton"},
{"votes":44,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":132,"precincts":
{"total":1,"reporting":1},
"name":"Barnet"},
"Montgomery":
{"votes":[
{"votes":88,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":4,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":103,"precincts":
{"total":1,"reporting":1},
"name":"Montgomery"},
"Newark":
{"votes":[
{"votes":18,"name":"clinton"},
{"votes":6,"name":"obama"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Newark"},
"Morristown":
{"votes":[
{"votes":242,"name":"obama"},
{"votes":22,"name":"clinton"},
{"votes":15,"name":"edwards"},
{"votes":2,"name":"kucinich"}],
"total":281,"precincts":
{"total":1,"reporting":1},
"name":"Morristown"},
"Craftsbury":
{"votes":[
{"votes":67,"name":"clinton"},
{"votes":46,"name":"obama"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"}],
"total":115,"precincts":
{"total":1,"reporting":1},
"name":"Craftsbury"},
"Barre":
{"votes":[
{"votes":361,"name":"clinton"},
{"votes":85,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":471,"precincts":
{"total":3,"reporting":3},
"name":"Barre"},
"Victory":
{"votes":[
{"votes":20,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":2,"name":"clinton"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Victory"},
"Rutland":
{"votes":[
{"votes":593,"name":"obama"},
{"votes":515,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":1108,"precincts":
{"total":4,"reporting":4},
"name":"Rutland"},
"Brunswick":
{"votes":[
{"votes":9,"name":"edwards"},
{"votes":7,"name":"clinton"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Brunswick"},
"Brookfield":
{"votes":[
{"votes":130,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"},
{"votes":1,"name":"obama"}],
"total":133,"precincts":
{"total":1,"reporting":1},
"name":"Brookfield"},
"Shelburne":
{"votes":[
{"votes":410,"name":"clinton"},
{"votes":256,"name":"obama"},
{"votes":82,"name":"edwards"},
{"votes":2,"name":"kucinich"}],
"total":750,"precincts":
{"total":1,"reporting":1},
"name":"Shelburne"},
"Addison":
{"votes":[
{"votes":91,"name":"obama"},
{"votes":44,"name":"clinton"},
{"votes":9,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":144,"precincts":
{"total":1,"reporting":1},
"name":"Addison"},
"Winhall":
{"votes":[
{"votes":94,"name":"obama"},
{"votes":18,"name":"clinton"},
{"votes":4,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":116,"precincts":
{"total":1,"reporting":1},
"name":"Winhall"},
"Chittenden":
{"votes":[
{"votes":155,"name":"clinton"},
{"votes":14,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":171,"precincts":
{"total":1,"reporting":1},
"name":"Chittenden"},
"Kirby":
{"votes":[
{"votes":15,"name":"edwards"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"clinton"},
{"votes":3,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Kirby"},
"Chelsea":
{"votes":[
{"votes":59,"name":"obama"},
{"votes":46,"name":"clinton"},
{"votes":6,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":111,"precincts":
{"total":1,"reporting":1},
"name":"Chelsea"},
"Irasburg":
{"votes":[
{"votes":28,"name":"clinton"},
{"votes":20,"name":"obama"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":48,"precincts":
{"total":1,"reporting":1},
"name":"Irasburg"},
"Waterbury":
{"votes":[
{"votes":174,"name":"edwards"},
{"votes":58,"name":"clinton"},
{"votes":58,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":290,"precincts":
{"total":1,"reporting":1},
"name":"Waterbury"},
"Lyndon":
{"votes":[
{"votes":117,"name":"obama"},
{"votes":76,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":193,"precincts":
{"total":1,"reporting":1},
"name":"Lyndon"},
"East Montpelier":
{"votes":[
{"votes":210,"name":"obama"},
{"votes":35,"name":"edwards"},
{"votes":10,"name":"kucinich"},
{"votes":6,"name":"clinton"}],
"total":261,"precincts":
{"total":1,"reporting":1},
"name":"East Montpelier"},
"Isle La Motte":
{"votes":[
{"votes":57,"name":"obama"},
{"votes":45,"name":"clinton"},
{"votes":8,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":110,"precincts":
{"total":1,"reporting":1},
"name":"Isle La Motte"},
"Orwell":
{"votes":[
{"votes":120,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":129,"precincts":
{"total":1,"reporting":1},
"name":"Orwell"},
"Dorset":
{"votes":[
{"votes":158,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":6,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":184,"precincts":
{"total":1,"reporting":1},
"name":"Dorset"},
"Rockingham":
{"votes":[
{"votes":189,"name":"obama"},
{"votes":136,"name":"clinton"},
{"votes":8,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":334,"precincts":
{"total":1,"reporting":1},
"name":"Rockingham"},
"West Rutland":
{"votes":[
{"votes":53,"name":"clinton"},
{"votes":51,"name":"edwards"},
{"votes":51,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":155,"precincts":
{"total":1,"reporting":1},
"name":"West Rutland"},
"Holland":
{"votes":[
{"votes":16,"name":"edwards"},
{"votes":4,"name":"clinton"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Holland"},
"Charlotte":
{"votes":[
{"votes":182,"name":"obama"},
{"votes":131,"name":"clinton"},
{"votes":18,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":332,"precincts":
{"total":1,"reporting":1},
"name":"Charlotte"},
"Bristol":
{"votes":[
{"votes":245,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":269,"precincts":
{"total":1,"reporting":1},
"name":"Bristol"},
"Cavendish":
{"votes":[
{"votes":108,"name":"obama"},
{"votes":29,"name":"edwards"},
{"votes":2,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":140,"precincts":
{"total":1,"reporting":1},
"name":"Cavendish"},
"Newport":
{"votes":[
{"votes":207,"name":"clinton"},
{"votes":57,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":271,"precincts":
{"total":1,"reporting":1},
"name":"Newport"},
"Northfield":
{"votes":[
{"votes":221,"name":"obama"},
{"votes":81,"name":"clinton"},
{"votes":11,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":313,"precincts":
{"total":1,"reporting":1},
"name":"Northfield"},
"Topsham":
{"votes":[
{"votes":36,"name":"clinton"},
{"votes":35,"name":"edwards"},
{"votes":35,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":106,"precincts":
{"total":1,"reporting":1},
"name":"Topsham"},
"Waltham":
{"votes":[
{"votes":16,"name":"clinton"},
{"votes":15,"name":"edwards"},
{"votes":15,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":46,"precincts":
{"total":1,"reporting":1},
"name":"Waltham"},
"Bridport":
{"votes":[
{"votes":128,"name":"clinton"},
{"votes":6,"name":"edwards"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"obama"}],
"total":134,"precincts":
{"total":1,"reporting":1},
"name":"Bridport"},
"Sudbury":
{"votes":[
{"votes":86,"name":"clinton"},
{"votes":7,"name":"edwards"},
{"votes":7,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":100,"precincts":
{"total":1,"reporting":1},
"name":"Sudbury"},
"Goshen":
{"votes":[
{"votes":22,"name":"clinton"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Goshen"},
"Grand Isle":
{"votes":[
{"votes":156,"name":"clinton"},
{"votes":10,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":168,"precincts":
{"total":1,"reporting":1},
"name":"Grand Isle"},
"Duxbury":
{"votes":[
{"votes":110,"name":"obama"},
{"votes":11,"name":"edwards"},
{"votes":2,"name":"clinton"},
{"votes":0,"name":"kucinich"}],
"total":123,"precincts":
{"total":1,"reporting":1},
"name":"Duxbury"},
"Cornwall":
{"votes":[
{"votes":68,"name":"obama"},
{"votes":60,"name":"clinton"},
{"votes":9,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":137,"precincts":
{"total":1,"reporting":1},
"name":"Cornwall"},
"Groton":
{"votes":[
{"votes":79,"name":"obama"},
{"votes":23,"name":"clinton"},
{"votes":10,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":112,"precincts":
{"total":1,"reporting":1},
"name":"Groton"},
"Washington":
{"votes":[
{"votes":87,"name":"obama"},
{"votes":24,"name":"clinton"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":112,"precincts":
{"total":1,"reporting":1},
"name":"Washington"},
"Montpelier":
{"votes":[
{"votes":492,"name":"clinton"},
{"votes":381,"name":"obama"},
{"votes":118,"name":"edwards"},
{"votes":9,"name":"kucinich"}],
"total":1000,"precincts":
{"total":1,"reporting":1},
"name":"Montpelier"},
"Andover":
{"votes":[
{"votes":92,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":2,"name":"clinton"},
{"votes":0,"name":"kucinich"}],
"total":100,"precincts":
{"total":1,"reporting":1},
"name":"Andover"},
"Rupert":
{"votes":[
{"votes":66,"name":"clinton"},
{"votes":52,"name":"obama"},
{"votes":3,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":122,"precincts":
{"total":1,"reporting":1},
"name":"Rupert"},
"Troy":
{"votes":[
{"votes":16,"name":"clinton"},
{"votes":4,"name":"edwards"},
{"votes":4,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Troy"},
"Walden":
{"votes":[
{"votes":96,"name":"obama"},
{"votes":16,"name":"edwards"},
{"votes":4,"name":"clinton"},
{"votes":0,"name":"kucinich"}],
"total":116,"precincts":
{"total":1,"reporting":1},
"name":"Walden"},
"Manchester":
{"votes":[
{"votes":260,"name":"obama"},
{"votes":21,"name":"kucinich"},
{"votes":13,"name":"clinton"},
{"votes":10,"name":"edwards"}],
"total":304,"precincts":
{"total":1,"reporting":1},
"name":"Manchester"},
"Shrewsbury":
{"votes":[
{"votes":86,"name":"edwards"},
{"votes":23,"name":"clinton"},
{"votes":21,"name":"kucinich"},
{"votes":21,"name":"obama"}],
"total":151,"precincts":
{"total":1,"reporting":1},
"name":"Shrewsbury"},
"Vershire":
{"votes":[
{"votes":88,"name":"clinton"},
{"votes":11,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":100,"precincts":
{"total":1,"reporting":1},
"name":"Vershire"},
"Panton":
{"votes":[
{"votes":69,"name":"clinton"},
{"votes":26,"name":"obama"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"edwards"}],
"total":101,"precincts":
{"total":1,"reporting":1},
"name":"Panton"},
"Windsor":
{"votes":[
{"votes":185,"name":"obama"},
{"votes":104,"name":"clinton"},
{"votes":13,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":302,"precincts":
{"total":1,"reporting":1},
"name":"Windsor"},
"Warren":
{"votes":[
{"votes":147,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":5,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":157,"precincts":
{"total":1,"reporting":1},
"name":"Warren"},
"Guildhall":
{"votes":[
{"votes":35,"name":"edwards"},
{"votes":4,"name":"clinton"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"obama"}],
"total":45,"precincts":
{"total":1,"reporting":1},
"name":"Guildhall"},
"Brattleboro":
{"votes":[
{"votes":618,"name":"obama"},
{"votes":277,"name":"clinton"},
{"votes":32,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":927,"precincts":
{"total":3,"reporting":3},
"name":"Brattleboro"},
"Rochester":
{"votes":[
{"votes":77,"name":"clinton"},
{"votes":53,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":131,"precincts":
{"total":1,"reporting":1},
"name":"Rochester"},
"Whitingham":
{"votes":[
{"votes":78,"name":"obama"},
{"votes":57,"name":"clinton"},
{"votes":7,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":142,"precincts":
{"total":1,"reporting":1},
"name":"Whitingham"},
"Bakersfield":
{"votes":[
{"votes":96,"name":"obama"},
{"votes":8,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":108,"precincts":
{"total":1,"reporting":1},
"name":"Bakersfield"},
"Bridgewater":
{"votes":[
{"votes":91,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":113,"precincts":
{"total":1,"reporting":1},
"name":"Bridgewater"},
"Bennington":
{"votes":[
{"votes":374,"name":"clinton"},
{"votes":303,"name":"obama"},
{"votes":69,"name":"edwards"},
{"votes":4,"name":"kucinich"}],
"total":750,"precincts":
{"total":1,"reporting":1},
"name":"Bennington"},
"Brandon":
{"votes":[
{"votes":202,"name":"clinton"},
{"votes":78,"name":"obama"},
{"votes":1,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":281,"precincts":
{"total":1,"reporting":1},
"name":"Brandon"},
"Hyde Park":
{"votes":[
{"votes":179,"name":"clinton"},
{"votes":6,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":187,"precincts":
{"total":1,"reporting":1},
"name":"Hyde Park"},
"Williamstown":
{"votes":[
{"votes":86,"name":"obama"},
{"votes":73,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":164,"precincts":
{"total":1,"reporting":1},
"name":"Williamstown"},
"Granby":
{"votes":[
{"votes":22,"name":"obama"},
{"votes":2,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Granby"},
"Burlington":
{"votes":[
{"votes":1709,"name":"clinton"},
{"votes":1688,"name":"obama"},
{"votes":103,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":3500,"precincts":
{"total":7,"reporting":7},
"name":"Burlington"},
"Peru":
{"votes":[
{"votes":21,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"},
{"votes":1,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Peru"},
"Granville":
{"votes":[
{"votes":12,"name":"clinton"},
{"votes":12,"name":"obama"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":82,"name":"obama"},
{"votes":21,"name":"clinton"},
{"votes":9,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":113,"precincts":
{"total":1,"reporting":1},
"name":"Orange"},
"Norton":
{"votes":[
{"votes":16,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Norton"},
"Reading":
{"votes":[
{"votes":89,"name":"clinton"},
{"votes":10,"name":"edwards"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"obama"}],
"total":103,"precincts":
{"total":1,"reporting":1},
"name":"Reading"},
"Belvidere":
{"votes":[
{"votes":20,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Belvidere"},
"Burke":
{"votes":[
{"votes":79,"name":"clinton"},
{"votes":45,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":126,"precincts":
{"total":1,"reporting":1},
"name":"Burke"},
"Ira":
{"votes":[
{"votes":34,"name":"obama"},
{"votes":12,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":46,"precincts":
{"total":1,"reporting":1},
"name":"Ira"},
"Canaan":
{"votes":[
{"votes":85,"name":"obama"},
{"votes":16,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":105,"precincts":
{"total":1,"reporting":1},
"name":"Canaan"},
"Eden":
{"votes":[
{"votes":14,"name":"clinton"},
{"votes":8,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Eden"},
"Pittsfield":
{"votes":[
{"votes":27,"name":"clinton"},
{"votes":16,"name":"edwards"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"obama"}],
"total":49,"precincts":
{"total":1,"reporting":1},
"name":"Pittsfield"},
"Sheffield":
{"votes":[
{"votes":18,"name":"obama"},
{"votes":6,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Sheffield"},
"Mount Tabor":
{"votes":[
{"votes":6,"name":"kucinich"},
{"votes":6,"name":"edwards"},
{"votes":6,"name":"clinton"},
{"votes":6,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Mount Tabor"},
"Guilford":
{"votes":[
{"votes":124,"name":"obama"},
{"votes":25,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":170,"precincts":
{"total":1,"reporting":1},
"name":"Guilford"},
"Stowe":
{"votes":[
{"votes":304,"name":"obama"},
{"votes":24,"name":"edwards"},
{"votes":24,"name":"clinton"},
{"votes":4,"name":"kucinich"}],
"total":356,"precincts":
{"total":1,"reporting":1},
"name":"Stowe"},
"Barnard":
{"votes":[
{"votes":115,"name":"edwards"},
{"votes":5,"name":"clinton"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"obama"}],
"total":126,"precincts":
{"total":1,"reporting":1},
"name":"Barnard"},
"Clarendon":
{"votes":[
{"votes":256,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"edwards"}],
"total":264,"precincts":
{"total":1,"reporting":1},
"name":"Clarendon"},
"Berlin":
{"votes":[
{"votes":135,"name":"obama"},
{"votes":31,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":170,"precincts":
{"total":1,"reporting":1},
"name":"Berlin"},
"Danby":
{"votes":[
{"votes":53,"name":"clinton"},
{"votes":42,"name":"obama"},
{"votes":23,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":119,"precincts":
{"total":1,"reporting":1},
"name":"Danby"},
"Thetford":
{"votes":[
{"votes":256,"name":"obama"},
{"votes":16,"name":"clinton"},
{"votes":8,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":280,"precincts":
{"total":1,"reporting":1},
"name":"Thetford"},
"Colchester":
{"votes":[
{"votes":649,"name":"obama"},
{"votes":91,"name":"edwards"},
{"votes":7,"name":"kucinich"},
{"votes":3,"name":"clinton"}],
"total":750,"precincts":
{"total":1,"reporting":1},
"name":"Colchester"},
"Castleton":
{"votes":[
{"votes":120,"name":"clinton"},
{"votes":78,"name":"edwards"},
{"votes":73,"name":"obama"},
{"votes":2,"name":"kucinich"}],
"total":273,"precincts":
{"total":1,"reporting":1},
"name":"Castleton"},
"Weybridge":
{"votes":[
{"votes":71,"name":"clinton"},
{"votes":50,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":122,"precincts":
{"total":1,"reporting":1},
"name":"Weybridge"},
"Moretown":
{"votes":[
{"votes":95,"name":"edwards"},
{"votes":20,"name":"clinton"},
{"votes":19,"name":"kucinich"},
{"votes":19,"name":"obama"}],
"total":153,"precincts":
{"total":1,"reporting":1},
"name":"Moretown"},
"Johnson":
{"votes":[
{"votes":98,"name":"edwards"},
{"votes":31,"name":"clinton"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"obama"}],
"total":135,"precincts":
{"total":1,"reporting":1},
"name":"Johnson"},
"Highgate":
{"votes":[
{"votes":111,"name":"obama"},
{"votes":26,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":137,"precincts":
{"total":1,"reporting":1},
"name":"Highgate"},
"Barton":
{"votes":[
{"votes":98,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"obama"}],
"total":133,"precincts":
{"total":1,"reporting":1},
"name":"Barton"},
"Wheelock":
{"votes":[
{"votes":22,"name":"clinton"},
{"votes":1,"name":"edwards"},
{"votes":1,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Wheelock"},
"Jericho":
{"votes":[
{"votes":158,"name":"clinton"},
{"votes":140,"name":"obama"},
{"votes":43,"name":"edwards"},
{"votes":2,"name":"kucinich"}],
"total":343,"precincts":
{"total":1,"reporting":1},
"name":"Jericho"},
"Woodford":
{"votes":[
{"votes":20,"name":"obama"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Woodford"},
"Windham":
{"votes":[
{"votes":19,"name":"obama"},
{"votes":3,"name":"clinton"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Windham"},
"Glover":
{"votes":[
{"votes":63,"name":"clinton"},
{"votes":36,"name":"edwards"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"obama"}],
"total":103,"precincts":
{"total":1,"reporting":1},
"name":"Glover"},
"Poultney":
{"votes":[
{"votes":172,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"edwards"}],
"total":180,"precincts":
{"total":1,"reporting":1},
"name":"Poultney"},
"Westfield":
{"votes":[
{"votes":29,"name":"clinton"},
{"votes":17,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":47,"precincts":
{"total":1,"reporting":1},
"name":"Westfield"},
"Wardsboro":
{"votes":[
{"votes":90,"name":"obama"},
{"votes":6,"name":"clinton"},
{"votes":4,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":100,"precincts":
{"total":1,"reporting":1},
"name":"Wardsboro"},
"Cambridge":
{"votes":[
{"votes":95,"name":"clinton"},
{"votes":72,"name":"obama"},
{"votes":11,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":179,"precincts":
{"total":1,"reporting":1},
"name":"Cambridge"},
"Londonderry":
{"votes":[
{"votes":87,"name":"obama"},
{"votes":31,"name":"clinton"},
{"votes":6,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":124,"precincts":
{"total":1,"reporting":1},
"name":"Londonderry"},
"Essex":
{"votes":[
{"votes":504,"name":"obama"},
{"votes":335,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":839,"precincts":
{"total":2,"reporting":2},
"name":"Essex"},
"Danville":
{"votes":[
{"votes":101,"name":"edwards"},
{"votes":33,"name":"obama"},
{"votes":7,"name":"clinton"},
{"votes":5,"name":"kucinich"}],
"total":146,"precincts":
{"total":1,"reporting":1},
"name":"Danville"},
"Shaftsbury":
{"votes":[
{"votes":155,"name":"edwards"},
{"votes":63,"name":"clinton"},
{"votes":62,"name":"obama"},
{"votes":15,"name":"kucinich"}],
"total":295,"precincts":
{"total":1,"reporting":1},
"name":"Shaftsbury"},
"South Burlington":
{"votes":[
{"votes":370,"name":"obama"},
{"votes":354,"name":"clinton"},
{"votes":24,"name":"edwards"},
{"votes":2,"name":"kucinich"}],
"total":750,"precincts":
{"total":1,"reporting":1},
"name":"South Burlington"},
"Dummerston":
{"votes":[
{"votes":132,"name":"obama"},
{"votes":24,"name":"edwards"},
{"votes":2,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":159,"precincts":
{"total":1,"reporting":1},
"name":"Dummerston"},
"Huntington":
{"votes":[
{"votes":100,"name":"clinton"},
{"votes":55,"name":"obama"},
{"votes":14,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":170,"precincts":
{"total":1,"reporting":1},
"name":"Huntington"},
"Pawlet":
{"votes":[
{"votes":68,"name":"obama"},
{"votes":64,"name":"clinton"},
{"votes":12,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":145,"precincts":
{"total":1,"reporting":1},
"name":"Pawlet"},
"Tinmouth":
{"votes":[
{"votes":14,"name":"obama"},
{"votes":8,"name":"clinton"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Tinmouth"},
"Chester":
{"votes":[
{"votes":146,"name":"obama"},
{"votes":105,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":254,"precincts":
{"total":1,"reporting":1},
"name":"Chester"},
"Hinesburg":
{"votes":[
{"votes":158,"name":"clinton"},
{"votes":149,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":314,"precincts":
{"total":1,"reporting":1},
"name":"Hinesburg"},
"Sharon":
{"votes":[
{"votes":65,"name":"clinton"},
{"votes":53,"name":"obama"},
{"votes":11,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":130,"precincts":
{"total":1,"reporting":1},
"name":"Sharon"},
"Middlebury":
{"votes":[
{"votes":417,"name":"clinton"},
{"votes":71,"name":"edwards"},
{"votes":8,"name":"kucinich"},
{"votes":4,"name":"obama"}],
"total":500,"precincts":
{"total":1,"reporting":1},
"name":"Middlebury"},
"West Windsor":
{"votes":[
{"votes":100,"name":"obama"},
{"votes":18,"name":"clinton"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":119,"precincts":
{"total":1,"reporting":1},
"name":"West Windsor"},
"Ripton":
{"votes":[
{"votes":70,"name":"obama"},
{"votes":28,"name":"edwards"},
{"votes":6,"name":"clinton"},
{"votes":4,"name":"kucinich"}],
"total":108,"precincts":
{"total":1,"reporting":1},
"name":"Ripton"},
"Derby":
{"votes":[
{"votes":182,"name":"obama"},
{"votes":56,"name":"clinton"},
{"votes":19,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":258,"precincts":
{"total":1,"reporting":1},
"name":"Derby"},
"Pomfret":
{"votes":[
{"votes":60,"name":"edwards"},
{"votes":20,"name":"kucinich"},
{"votes":20,"name":"clinton"},
{"votes":20,"name":"obama"}],
"total":120,"precincts":
{"total":1,"reporting":1},
"name":"Pomfret"},
"Woodstock":
{"votes":[
{"votes":361,"name":"clinton"},
{"votes":23,"name":"edwards"},
{"votes":11,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":395,"precincts":
{"total":1,"reporting":1},
"name":"Woodstock"},
"Fairfield":
{"votes":[
{"votes":66,"name":"obama"},
{"votes":47,"name":"clinton"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"edwards"}],
"total":119,"precincts":
{"total":1,"reporting":1},
"name":"Fairfield"},
"Richmond":
{"votes":[
{"votes":310,"name":"clinton"},
{"votes":2,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":314,"precincts":
{"total":1,"reporting":1},
"name":"Richmond"},
"Peacham":
{"votes":[
{"votes":74,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":10,"name":"obama"},
{"votes":2,"name":"kucinich"}],
"total":113,"precincts":
{"total":1,"reporting":1},
"name":"Peacham"},
"Fairlee":
{"votes":[
{"votes":108,"name":"clinton"},
{"votes":9,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":119,"precincts":
{"total":1,"reporting":1},
"name":"Fairlee"},
"Mount Holly":
{"votes":[
{"votes":119,"name":"clinton"},
{"votes":10,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":131,"precincts":
{"total":1,"reporting":1},
"name":"Mount Holly"},
"St. Johnsbury":
{"votes":[
{"votes":262,"name":"clinton"},
{"votes":211,"name":"obama"},
{"votes":26,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":500,"precincts":
{"total":1,"reporting":1},
"name":"St. Johnsbury"},
"Waterford":
{"votes":[
{"votes":82,"name":"obama"},
{"votes":47,"name":"clinton"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":130,"precincts":
{"total":1,"reporting":1},
"name":"Waterford"},
"Shoreham":
{"votes":[
{"votes":90,"name":"obama"},
{"votes":31,"name":"clinton"},
{"votes":4,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":126,"precincts":
{"total":1,"reporting":1},
"name":"Shoreham"},
"Starksboro":
{"votes":[
{"votes":94,"name":"obama"},
{"votes":46,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"}],
"total":142,"precincts":
{"total":1,"reporting":1},
"name":"Starksboro"},
"Alburg":
{"votes":[
{"votes":90,"name":"edwards"},
{"votes":35,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":130,"precincts":
{"total":1,"reporting":1},
"name":"Alburg"},
"Newbury":
{"votes":[
{"votes":85,"name":"obama"},
{"votes":58,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":143,"precincts":
{"total":1,"reporting":1},
"name":"Newbury"},
"Barre Town":
{"votes":[
{"votes":297,"name":"obama"},
{"votes":142,"name":"clinton"},
{"votes":14,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":454,"precincts":
{"total":1,"reporting":1},
"name":"Barre Town"},
"Bethel":
{"votes":[
{"votes":131,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"},
{"votes":1,"name":"obama"}],
"total":134,"precincts":
{"total":1,"reporting":1},
"name":"Bethel"},
"Proctor":
{"votes":[
{"votes":100,"name":"clinton"},
{"votes":34,"name":"edwards"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"obama"}],
"total":142,"precincts":
{"total":1,"reporting":1},
"name":"Proctor"},
"Berkshire":
{"votes":[
{"votes":84,"name":"clinton"},
{"votes":25,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":110,"precincts":
{"total":1,"reporting":1},
"name":"Berkshire"},
"Hubbardton":
{"votes":[
{"votes":29,"name":"obama"},
{"votes":15,"name":"clinton"},
{"votes":4,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":49,"precincts":
{"total":1,"reporting":1},
"name":"Hubbardton"},
"Marlboro":
{"votes":[
{"votes":60,"name":"obama"},
{"votes":51,"name":"clinton"},
{"votes":22,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":134,"precincts":
{"total":1,"reporting":1},
"name":"Marlboro"},
"St. Albans":
{"votes":[
{"votes":344,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":4,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":354,"precincts":
{"total":1,"reporting":1},
"name":"St. Albans"},
"Brookline":
{"votes":[
{"votes":15,"name":"obama"},
{"votes":9,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Brookline"},
"South Hero":
{"votes":[
{"votes":118,"name":"edwards"},
{"votes":17,"name":"clinton"},
{"votes":14,"name":"kucinich"},
{"votes":14,"name":"obama"}],
"total":163,"precincts":
{"total":1,"reporting":1},
"name":"South Hero"},
"Readsboro":
{"votes":[
{"votes":62,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":27,"name":"obama"},
{"votes":2,"name":"kucinich"}],
"total":118,"precincts":
{"total":1,"reporting":1},
"name":"Readsboro"},
"Searsburg":
{"votes":[
{"votes":9,"name":"edwards"},
{"votes":7,"name":"clinton"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Searsburg"},
"Lunenburg":
{"votes":[
{"votes":70,"name":"edwards"},
{"votes":15,"name":"clinton"},
{"votes":14,"name":"kucinich"},
{"votes":14,"name":"obama"}],
"total":113,"precincts":
{"total":1,"reporting":1},
"name":"Lunenburg"},
"Bloomfield":
{"votes":[
{"votes":14,"name":"obama"},
{"votes":10,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Bloomfield"},
"Bradford":
{"votes":[
{"votes":66,"name":"clinton"},
{"votes":66,"name":"obama"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":135,"precincts":
{"total":1,"reporting":1},
"name":"Bradford"},
"Sutton":
{"votes":[
{"votes":26,"name":"clinton"},
{"votes":22,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":49,"precincts":
{"total":1,"reporting":1},
"name":"Sutton"},
"Lincoln":
{"votes":[
{"votes":104,"name":"clinton"},
{"votes":38,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":148,"precincts":
{"total":1,"reporting":1},
"name":"Lincoln"},
"Tunbridge":
{"votes":[
{"votes":95,"name":"obama"},
{"votes":20,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":118,"precincts":
{"total":1,"reporting":1},
"name":"Tunbridge"},
"Roxbury":
{"votes":[
{"votes":92,"name":"obama"},
{"votes":8,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":104,"precincts":
{"total":1,"reporting":1},
"name":"Roxbury"},
"Killington":
{"votes":[
{"votes":72,"name":"obama"},
{"votes":42,"name":"clinton"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"edwards"}],
"total":120,"precincts":
{"total":1,"reporting":1},
"name":"Killington"},
"Corinth":
{"votes":[
{"votes":59,"name":"obama"},
{"votes":44,"name":"clinton"},
{"votes":25,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":129,"precincts":
{"total":1,"reporting":1},
"name":"Corinth"},
"Townshend":
{"votes":[
{"votes":103,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":3,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":109,"precincts":
{"total":1,"reporting":1},
"name":"Townshend"},
"Stannard":
{"votes":[
{"votes":18,"name":"clinton"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"edwards"},
{"votes":2,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Stannard"},
"Vernon":
{"votes":[
{"votes":103,"name":"clinton"},
{"votes":76,"name":"obama"},
{"votes":11,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":190,"precincts":
{"total":1,"reporting":1},
"name":"Vernon"},
"Westford":
{"votes":[
{"votes":77,"name":"obama"},
{"votes":68,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":148,"precincts":
{"total":1,"reporting":1},
"name":"Westford"},
"Jamaica":
{"votes":[
{"votes":67,"name":"clinton"},
{"votes":38,"name":"obama"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":105,"precincts":
{"total":1,"reporting":1},
"name":"Jamaica"},
"Weathersfield":
{"votes":[
{"votes":112,"name":"clinton"},
{"votes":76,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":190,"precincts":
{"total":1,"reporting":1},
"name":"Weathersfield"},
"Stratton":
{"votes":[
{"votes":8,"name":"edwards"},
{"votes":8,"name":"clinton"},
{"votes":8,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Stratton"},
"Calais":
{"votes":[
{"votes":101,"name":"obama"},
{"votes":66,"name":"clinton"},
{"votes":8,"name":"edwards"},
{"votes":2,"name":"kucinich"}],
"total":177,"precincts":
{"total":1,"reporting":1},
"name":"Calais"},
"Bolton":
{"votes":[
{"votes":102,"name":"clinton"},
{"votes":17,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"obama"}],
"total":121,"precincts":
{"total":1,"reporting":1},
"name":"Bolton"},
"Braintree":
{"votes":[
{"votes":107,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":2,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":112,"precincts":
{"total":1,"reporting":1},
"name":"Braintree"},
"Greensboro":
{"votes":[
{"votes":64,"name":"obama"},
{"votes":38,"name":"clinton"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":104,"precincts":
{"total":1,"reporting":1},
"name":"Greensboro"},
"North Hero":
{"votes":[
{"votes":66,"name":"clinton"},
{"votes":39,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":106,"precincts":
{"total":1,"reporting":1},
"name":"North Hero"},
"Winooski":
{"votes":[
{"votes":258,"name":"obama"},
{"votes":9,"name":"clinton"},
{"votes":7,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":274,"precincts":
{"total":1,"reporting":1},
"name":"Winooski"},
"Landgrove":
{"votes":[
{"votes":6,"name":"kucinich"},
{"votes":6,"name":"edwards"},
{"votes":6,"name":"clinton"},
{"votes":6,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Landgrove"},
"Cabot":
{"votes":[
{"votes":96,"name":"edwards"},
{"votes":13,"name":"clinton"},
{"votes":10,"name":"kucinich"},
{"votes":10,"name":"obama"}],
"total":129,"precincts":
{"total":1,"reporting":1},
"name":"Cabot"},
"West Haven":
{"votes":[
{"votes":21,"name":"obama"},
{"votes":2,"name":"clinton"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"West Haven"},
"Brownington":
{"votes":[
{"votes":27,"name":"obama"},
{"votes":14,"name":"clinton"},
{"votes":6,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":47,"precincts":
{"total":1,"reporting":1},
"name":"Brownington"},
"Brighton":
{"votes":[
{"votes":89,"name":"obama"},
{"votes":27,"name":"clinton"},
{"votes":15,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":131,"precincts":
{"total":1,"reporting":1},
"name":"Brighton"},
"Enosburgh":
{"votes":[
{"votes":117,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"},
{"votes":1,"name":"obama"}],
"total":120,"precincts":
{"total":1,"reporting":1},
"name":"Enosburgh"},
"Concord":
{"votes":[
{"votes":111,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":4,"name":"clinton"},
{"votes":0,"name":"kucinich"}],
"total":121,"precincts":
{"total":1,"reporting":1},
"name":"Concord"},
"Maidstone":
{"votes":[
{"votes":6,"name":"kucinich"},
{"votes":6,"name":"edwards"},
{"votes":6,"name":"clinton"},
{"votes":6,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Maidstone"},
"St. George":
{"votes":[
{"votes":6,"name":"kucinich"},
{"votes":6,"name":"edwards"},
{"votes":6,"name":"clinton"},
{"votes":6,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"St. George"},
"Sandgate":
{"votes":[
{"votes":19,"name":"obama"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Sandgate"},
"Fairfax":
{"votes":[
{"votes":206,"name":"clinton"},
{"votes":40,"name":"obama"},
{"votes":28,"name":"edwards"},
{"votes":2,"name":"kucinich"}],
"total":276,"precincts":
{"total":1,"reporting":1},
"name":"Fairfax"},
"Halifax":
{"votes":[
{"votes":99,"name":"obama"},
{"votes":12,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":0,"name":"kucinich"}],
"total":114,"precincts":
{"total":1,"reporting":1},
"name":"Halifax"},
"Benson":
{"votes":[
{"votes":113,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"},
{"votes":0,"name":"obama"}],
"total":113,"precincts":
{"total":1,"reporting":1},
"name":"Benson"},
"Lemington":
{"votes":[
{"votes":14,"name":"clinton"},
{"votes":10,"name":"obama"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Lemington"},
"Royalton":
{"votes":[
{"votes":143,"name":"obama"},
{"votes":28,"name":"clinton"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"edwards"}],
"total":175,"precincts":
{"total":1,"reporting":1},
"name":"Royalton"},
"West Fairlee":
{"votes":[
{"votes":102,"name":"clinton"},
{"votes":1,"name":"edwards"},
{"votes":1,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":104,"precincts":
{"total":1,"reporting":1},
"name":"West Fairlee"},
"Middlesex":
{"votes":[
{"votes":103,"name":"obama"},
{"votes":55,"name":"clinton"},
{"votes":10,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":168,"precincts":
{"total":1,"reporting":1},
"name":"Middlesex"},
"Strafford":
{"votes":[
{"votes":76,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":16,"name":"clinton"},
{"votes":10,"name":"kucinich"}],
"total":127,"precincts":
{"total":1,"reporting":1},
"name":"Strafford"},
"Waitsfield":
{"votes":[
{"votes":123,"name":"clinton"},
{"votes":44,"name":"obama"},
{"votes":8,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":175,"precincts":
{"total":1,"reporting":1},
"name":"Waitsfield"},
"Waterville":
{"votes":[
{"votes":32,"name":"clinton"},
{"votes":10,"name":"obama"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":45,"precincts":
{"total":1,"reporting":1},
"name":"Waterville"},
"Putney":
{"votes":[
{"votes":231,"name":"obama"},
{"votes":17,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":2,"name":"kucinich"}],
"total":253,"precincts":
{"total":1,"reporting":1},
"name":"Putney"},
"Newfane":
{"votes":[
{"votes":100,"name":"clinton"},
{"votes":47,"name":"edwards"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"obama"}],
"total":153,"precincts":
{"total":1,"reporting":1},
"name":"Newfane"},
"Westmore":
{"votes":[
{"votes":17,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Westmore"},
"Westminster":
{"votes":[
{"votes":146,"name":"clinton"},
{"votes":113,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":265,"precincts":
{"total":1,"reporting":1},
"name":"Westminster"},
"Plainfield":
{"votes":[
{"votes":63,"name":"clinton"},
{"votes":56,"name":"obama"},
{"votes":10,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":130,"precincts":
{"total":1,"reporting":1},
"name":"Plainfield"},
"Georgia":
{"votes":[
{"votes":187,"name":"clinton"},
{"votes":59,"name":"obama"},
{"votes":8,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":255,"precincts":
{"total":1,"reporting":1},
"name":"Georgia"},
"Stockbridge":
{"votes":[
{"votes":13,"name":"obama"},
{"votes":9,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Stockbridge"},
"Fletcher":
{"votes":[
{"votes":92,"name":"obama"},
{"votes":5,"name":"clinton"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"edwards"}],
"total":105,"precincts":
{"total":1,"reporting":1},
"name":"Fletcher"},
"Fair Haven":
{"votes":[
{"votes":171,"name":"clinton"},
{"votes":1,"name":"kucinich"},
{"votes":1,"name":"edwards"},
{"votes":1,"name":"obama"}],
"total":174,"precincts":
{"total":1,"reporting":1},
"name":"Fair Haven"},
"Mendon":
{"votes":[
{"votes":109,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"obama"}],
"total":133,"precincts":
{"total":1,"reporting":1},
"name":"Mendon"},
"Springfield":
{"votes":[
{"votes":463,"name":"obama"},
{"votes":140,"name":"clinton"},
{"votes":138,"name":"edwards"},
{"votes":9,"name":"kucinich"}],
"total":750,"precincts":
{"total":1,"reporting":1},
"name":"Springfield"},
"Pownal":
{"votes":[
{"votes":181,"name":"obama"},
{"votes":7,"name":"clinton"},
{"votes":5,"name":"kucinich"},
{"votes":5,"name":"edwards"}],
"total":198,"precincts":
{"total":1,"reporting":1},
"name":"Pownal"},
"Lowell":
{"votes":[
{"votes":35,"name":"clinton"},
{"votes":10,"name":"obama"},
{"votes":1,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":46,"precincts":
{"total":1,"reporting":1},
"name":"Lowell"},
"Hartland":
{"votes":[
{"votes":251,"name":"obama"},
{"votes":6,"name":"kucinich"},
{"votes":5,"name":"clinton"},
{"votes":3,"name":"edwards"}],
"total":265,"precincts":
{"total":1,"reporting":1},
"name":"Hartland"},
"Marshfield":
{"votes":[
{"votes":70,"name":"obama"},
{"votes":40,"name":"clinton"},
{"votes":14,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":124,"precincts":
{"total":1,"reporting":1},
"name":"Marshfield"},
"Woodbury":
{"votes":[
{"votes":62,"name":"clinton"},
{"votes":34,"name":"obama"},
{"votes":8,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":104,"precincts":
{"total":1,"reporting":1},
"name":"Woodbury"},
"St. Albans Town":
{"votes":[
{"votes":144,"name":"obama"},
{"votes":92,"name":"clinton"},
{"votes":73,"name":"edwards"},
{"votes":2,"name":"kucinich"}],
"total":311,"precincts":
{"total":1,"reporting":1},
"name":"St. Albans Town"},
"Grafton":
{"votes":[
{"votes":83,"name":"obama"},
{"votes":21,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":0,"name":"kucinich"}],
"total":107,"precincts":
{"total":1,"reporting":1},
"name":"Grafton"},
"Elmore":
{"votes":[
{"votes":37,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":4,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":47,"precincts":
{"total":1,"reporting":1},
"name":"Elmore"},
"Wells":
{"votes":[
{"votes":66,"name":"clinton"},
{"votes":57,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":125,"precincts":
{"total":1,"reporting":1},
"name":"Wells"},
"Hartford":
{"votes":[
{"votes":426,"name":"obama"},
{"votes":310,"name":"clinton"},
{"votes":7,"name":"kucinich"},
{"votes":7,"name":"edwards"}],
"total":750,"precincts":
{"total":1,"reporting":1},
"name":"Hartford"},
"East Haven":
{"votes":[
{"votes":6,"name":"kucinich"},
{"votes":6,"name":"edwards"},
{"votes":6,"name":"clinton"},
{"votes":6,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"East Haven"},
"Vergennes":
{"votes":[
{"votes":116,"name":"clinton"},
{"votes":38,"name":"obama"},
{"votes":12,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":166,"precincts":
{"total":1,"reporting":1},
"name":"Vergennes"},
"Athens":
{"votes":[
{"votes":15,"name":"clinton"},
{"votes":3,"name":"kucinich"},
{"votes":3,"name":"edwards"},
{"votes":3,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Athens"},
"Ferrisburg":
{"votes":[
{"votes":145,"name":"obama"},
{"votes":46,"name":"edwards"},
{"votes":5,"name":"clinton"},
{"votes":2,"name":"kucinich"}],
"total":198,"precincts":
{"total":1,"reporting":1},
"name":"Ferrisburg"},
"Hancock":
{"votes":[
{"votes":12,"name":"edwards"},
{"votes":7,"name":"obama"},
{"votes":3,"name":"clinton"},
{"votes":2,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Hancock"},
"Milton":
{"votes":[
{"votes":289,"name":"obama"},
{"votes":56,"name":"edwards"},
{"votes":4,"name":"kucinich"},
{"votes":4,"name":"clinton"}],
"total":353,"precincts":
{"total":1,"reporting":1},
"name":"Milton"},
"Middletown Springs":
{"votes":[
{"votes":93,"name":"obama"},
{"votes":18,"name":"edwards"},
{"votes":4,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":116,"precincts":
{"total":1,"reporting":1},
"name":"Middletown Springs"},
"Hardwick":
{"votes":[
{"votes":132,"name":"obama"},
{"votes":18,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":153,"precincts":
{"total":1,"reporting":1},
"name":"Hardwick"},
"Ryegate":
{"votes":[
{"votes":94,"name":"obama"},
{"votes":3,"name":"clinton"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"edwards"}],
"total":101,"precincts":
{"total":1,"reporting":1},
"name":"Ryegate"},
"Swanton":
{"votes":[
{"votes":155,"name":"clinton"},
{"votes":110,"name":"obama"},
{"votes":18,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":283,"precincts":
{"total":1,"reporting":1},
"name":"Swanton"},
"Coventry":
{"votes":[
{"votes":19,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Coventry"},
"Wilmington":
{"votes":[
{"votes":155,"name":"obama"},
{"votes":7,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":167,"precincts":
{"total":1,"reporting":1},
"name":"Wilmington"},
"Ludlow":
{"votes":[
{"votes":176,"name":"obama"},
{"votes":70,"name":"clinton"},
{"votes":4,"name":"kucinich"},
{"votes":2,"name":"edwards"}],
"total":252,"precincts":
{"total":1,"reporting":1},
"name":"Ludlow"},
"Monkton":
{"votes":[
{"votes":81,"name":"clinton"},
{"votes":64,"name":"obama"},
{"votes":6,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":151,"precincts":
{"total":1,"reporting":1},
"name":"Monkton"},
"Newport Town":
{"votes":[
{"votes":80,"name":"obama"},
{"votes":32,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":112,"precincts":
{"total":1,"reporting":1},
"name":"Newport Town"},
"Plymouth":
{"votes":[
{"votes":88,"name":"clinton"},
{"votes":11,"name":"obama"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":102,"precincts":
{"total":1,"reporting":1},
"name":"Plymouth"},
"Morgan":
{"votes":[
{"votes":13,"name":"clinton"},
{"votes":12,"name":"kucinich"},
{"votes":12,"name":"edwards"},
{"votes":12,"name":"obama"}],
"total":49,"precincts":
{"total":1,"reporting":1},
"name":"Morgan"},
"Charleston":
{"votes":[
{"votes":44,"name":"obama"},
{"votes":3,"name":"clinton"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"edwards"}],
"total":47,"precincts":
{"total":1,"reporting":1},
"name":"Charleston"},
"Underhill":
{"votes":[
{"votes":279,"name":"clinton"},
{"votes":7,"name":"edwards"},
{"votes":2,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":288,"precincts":
{"total":1,"reporting":1},
"name":"Underhill"},
"Baltimore":
{"votes":[
{"votes":22,"name":"clinton"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"},
{"votes":0,"name":"obama"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Baltimore"},
"Dover":
{"votes":[
{"votes":112,"name":"clinton"},
{"votes":23,"name":"obama"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":137,"precincts":
{"total":1,"reporting":1},
"name":"Dover"},
"Richford":
{"votes":[
{"votes":66,"name":"obama"},
{"votes":48,"name":"clinton"},
{"votes":26,"name":"edwards"},
{"votes":2,"name":"kucinich"}],
"total":142,"precincts":
{"total":1,"reporting":1},
"name":"Richford"},
"New Haven":
{"votes":[
{"votes":82,"name":"obama"},
{"votes":45,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":130,"precincts":
{"total":1,"reporting":1},
"name":"New Haven"},
"Wallingford":
{"votes":[
{"votes":190,"name":"obama"},
{"votes":4,"name":"clinton"},
{"votes":2,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":196,"precincts":
{"total":1,"reporting":1},
"name":"Wallingford"},
"Whiting":
{"votes":[
{"votes":20,"name":"clinton"},
{"votes":2,"name":"edwards"},
{"votes":2,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":24,"precincts":
{"total":1,"reporting":1},
"name":"Whiting"},
"Leicester":
{"votes":[
{"votes":95,"name":"obama"},
{"votes":5,"name":"kucinich"},
{"votes":5,"name":"edwards"},
{"votes":5,"name":"clinton"}],
"total":110,"precincts":
{"total":1,"reporting":1},
"name":"Leicester"},
"Pittsford":
{"votes":[
{"votes":94,"name":"clinton"},
{"votes":60,"name":"obama"},
{"votes":22,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":177,"precincts":
{"total":1,"reporting":1},
"name":"Pittsford"},
"Norwich":
{"votes":[
{"votes":361,"name":"obama"},
{"votes":100,"name":"clinton"},
{"votes":36,"name":"edwards"},
{"votes":3,"name":"kucinich"}],
"total":500,"precincts":
{"total":1,"reporting":1},
"name":"Norwich"},
"Weston":
{"votes":[
{"votes":53,"name":"clinton"},
{"votes":48,"name":"obama"},
{"votes":3,"name":"edwards"},
{"votes":0,"name":"kucinich"}],
"total":104,"precincts":
{"total":1,"reporting":1},
"name":"Weston"},
"Fayston":
{"votes":[
{"votes":90,"name":"clinton"},
{"votes":21,"name":"edwards"},
{"votes":2,"name":"kucinich"},
{"votes":2,"name":"obama"}],
"total":115,"precincts":
{"total":1,"reporting":1},
"name":"Fayston"},
"Sunderland":
{"votes":[
{"votes":86,"name":"clinton"},
{"votes":18,"name":"edwards"},
{"votes":9,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":113,"precincts":
{"total":1,"reporting":1},
"name":"Sunderland"},
"Stamford":
{"votes":[
{"votes":92,"name":"obama"},
{"votes":9,"name":"clinton"},
{"votes":7,"name":"edwards"},
{"votes":3,"name":"kucinich"}],
"total":111,"precincts":
{"total":1,"reporting":1},
"name":"Stamford"},
"Salisbury":
{"votes":[
{"votes":88,"name":"clinton"},
{"votes":39,"name":"obama"},
{"votes":5,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":133,"precincts":
{"total":1,"reporting":1},
"name":"Salisbury"},
"Worcester":
{"votes":[
{"votes":62,"name":"clinton"},
{"votes":31,"name":"edwards"},
{"votes":31,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":124,"precincts":
{"total":1,"reporting":1},
"name":"Worcester"},
"Williston":
{"votes":[
{"votes":703,"name":"clinton"},
{"votes":38,"name":"edwards"},
{"votes":9,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":750,"precincts":
{"total":1,"reporting":1},
"name":"Williston"},
"Wolcott":
{"votes":[
{"votes":91,"name":"clinton"},
{"votes":5,"name":"edwards"},
{"votes":5,"name":"obama"},
{"votes":0,"name":"kucinich"}],
"total":101,"precincts":
{"total":1,"reporting":1},
"name":"Wolcott"},
"Randolph":
{"votes":[
{"votes":181,"name":"obama"},
{"votes":97,"name":"edwards"},
{"votes":5,"name":"clinton"},
{"votes":4,"name":"kucinich"}],
"total":287,"precincts":
{"total":1,"reporting":1},
"name":"Randolph"},
"Rutland Town":
{"votes":[
{"votes":253,"name":"clinton"},
{"votes":226,"name":"obama"},
{"votes":20,"name":"edwards"},
{"votes":1,"name":"kucinich"}],
"total":500,"precincts":
{"total":1,"reporting":1},
"name":"Rutland Town"},
"Franklin":
{"votes":[
{"votes":85,"name":"obama"},
{"votes":15,"name":"edwards"},
{"votes":3,"name":"clinton"},
{"votes":1,"name":"kucinich"}],
"total":104,"precincts":
{"total":1,"reporting":1},
"name":"Franklin"}}})