GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":1840,"name":"mccain"},
{"votes":421,"name":"huckabee"},
{"votes":169,"name":"paul"},
{"votes":142,"name":"romney"},
{"votes":64,"name":"giuliani"}],
"name":"Vermont","precincts":
{"total":260,"reporting":33},
"delegates":"17","date":"03-04"},
"state":"VT","party":"gop","total":2636,"locals":
{"Albany":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Albany"},
"Sheldon":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sheldon"},
"Jay":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Jay"},
"Arlington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Arlington"},
"Barnet":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Barnet"},
"Montgomery":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":2,"name":"romney"},
{"votes":0,"name":"giuliani"}],
"total":43,"precincts":
{"total":1,"reporting":1},
"name":"Montgomery"},
"Newark":
{"votes":[
{"votes":26,"name":"mccain"},
{"votes":14,"name":"paul"},
{"votes":5,"name":"huckabee"},
{"votes":1,"name":"romney"},
{"votes":0,"name":"giuliani"}],
"total":46,"precincts":
{"total":1,"reporting":1},
"name":"Newark"},
"Morristown":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Morristown"},
"Craftsbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Craftsbury"},
"Barre":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Barre"},
"Victory":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Victory"},
"Rutland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":4,"reporting":0},
"name":"Rutland"},
"Brunswick":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Brunswick"},
"Brookfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Brookfield"},
"Shelburne":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Shelburne"},
"Addison":
{"votes":[
{"votes":111,"name":"mccain"},
{"votes":28,"name":"huckabee"},
{"votes":14,"name":"romney"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"giuliani"}],
"total":156,"precincts":
{"total":1,"reporting":1},
"name":"Addison"},
"Winhall":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Winhall"},
"Chittenden":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Chittenden"},
"Kirby":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Kirby"},
"Chelsea":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Chelsea"},
"Irasburg":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Irasburg"},
"Waterbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Waterbury"},
"Lyndon":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Lyndon"},
"East Montpelier":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"East Montpelier"},
"Isle La Motte":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Isle La Motte"},
"Orwell":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Orwell"},
"Dorset":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Dorset"},
"Rockingham":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Rockingham"},
"West Rutland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"West Rutland"},
"Holland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Holland"},
"Charlotte":
{"votes":[
{"votes":40,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"romney"}],
"total":47,"precincts":
{"total":1,"reporting":1},
"name":"Charlotte"},
"Bristol":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bristol"},
"Cavendish":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Cavendish"},
"Newport":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Newport"},
"Northfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Northfield"},
"Topsham":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Topsham"},
"Waltham":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Waltham"},
"Bridport":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bridport"},
"Sudbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sudbury"},
"Goshen":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Goshen"},
"Grand Isle":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Grand Isle"},
"Duxbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Duxbury"},
"Cornwall":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Cornwall"},
"Groton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Groton"},
"Washington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Washington"},
"Montpelier":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Montpelier"},
"Andover":
{"votes":[
{"votes":36,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":47,"precincts":
{"total":1,"reporting":1},
"name":"Andover"},
"Rupert":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Rupert"},
"Troy":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Troy"},
"Walden":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Walden"},
"Manchester":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Manchester"},
"Shrewsbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Shrewsbury"},
"Vershire":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Vershire"},
"Panton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Panton"},
"Windsor":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Windsor"},
"Warren":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Warren"},
"Guildhall":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Guildhall"},
"Brattleboro":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":3,"reporting":0},
"name":"Brattleboro"},
"Rochester":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Rochester"},
"Whitingham":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Whitingham"},
"Bakersfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bakersfield"},
"Bridgewater":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bridgewater"},
"Bennington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bennington"},
"Brandon":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Brandon"},
"Hyde Park":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hyde Park"},
"Williamstown":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Williamstown"},
"Granby":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Granby"},
"Burlington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":7,"reporting":0},
"name":"Burlington"},
"Peru":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"paul"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"romney"}],
"total":25,"precincts":
{"total":1,"reporting":1},
"name":"Peru"},
"Granville":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Granville"},
"Orange":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Orange"},
"Norton":
{"votes":[
{"votes":16,"name":"mccain"},
{"votes":2,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"paul"},
{"votes":0,"name":"giuliani"}],
"total":21,"precincts":
{"total":1,"reporting":1},
"name":"Norton"},
"Reading":
{"votes":[
{"votes":38,"name":"mccain"},
{"votes":4,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"giuliani"}],
"total":47,"precincts":
{"total":1,"reporting":1},
"name":"Reading"},
"Belvidere":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Belvidere"},
"Burke":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Burke"},
"Ira":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Ira"},
"Canaan":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Canaan"},
"Eden":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Eden"},
"Pittsfield":
{"votes":[
{"votes":32,"name":"mccain"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"giuliani"},
{"votes":0,"name":"romney"}],
"total":36,"precincts":
{"total":1,"reporting":1},
"name":"Pittsfield"},
"Sheffield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sheffield"},
"Mount Tabor":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mount Tabor"},
"Guilford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Guilford"},
"Stowe":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Stowe"},
"Barnard":
{"votes":[
{"votes":57,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":2,"name":"paul"},
{"votes":0,"name":"giuliani"}],
"total":78,"precincts":
{"total":1,"reporting":1},
"name":"Barnard"},
"Clarendon":
{"votes":[
{"votes":169,"name":"mccain"},
{"votes":47,"name":"huckabee"},
{"votes":14,"name":"romney"},
{"votes":11,"name":"paul"},
{"votes":7,"name":"giuliani"}],
"total":248,"precincts":
{"total":1,"reporting":1},
"name":"Clarendon"},
"Berlin":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Berlin"},
"Danby":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Danby"},
"Thetford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Thetford"},
"Colchester":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Colchester"},
"Castleton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Castleton"},
"Weybridge":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Weybridge"},
"Moretown":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Moretown"},
"Johnson":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Johnson"},
"Highgate":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Highgate"},
"Barton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Barton"},
"Wheelock":
{"votes":[
{"votes":37,"name":"mccain"},
{"votes":15,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":1,"name":"giuliani"},
{"votes":0,"name":"romney"}],
"total":59,"precincts":
{"total":1,"reporting":1},
"name":"Wheelock"},
"Jericho":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Jericho"},
"Woodford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Woodford"},
"Windham":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Windham"},
"Glover":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Glover"},
"Poultney":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Poultney"},
"Westfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Westfield"},
"Wardsboro":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wardsboro"},
"Cambridge":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Cambridge"},
"Londonderry":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Londonderry"},
"Essex":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":2,"reporting":0},
"name":"Essex"},
"Danville":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Danville"},
"Shaftsbury":
{"votes":[
{"votes":186,"name":"mccain"},
{"votes":40,"name":"huckabee"},
{"votes":20,"name":"romney"},
{"votes":9,"name":"paul"},
{"votes":4,"name":"giuliani"}],
"total":259,"precincts":
{"total":1,"reporting":1},
"name":"Shaftsbury"},
"South Burlington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"South Burlington"},
"Dummerston":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Dummerston"},
"Huntington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Huntington"},
"Pawlet":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Pawlet"},
"Tinmouth":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Tinmouth"},
"Chester":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Chester"},
"Hinesburg":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hinesburg"},
"Sharon":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sharon"},
"Middlebury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Middlebury"},
"West Windsor":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"West Windsor"},
"Ripton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Ripton"},
"Derby":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Derby"},
"Pomfret":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Pomfret"},
"Woodstock":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Woodstock"},
"Fairfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Fairfield"},
"Richmond":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Richmond"},
"Peacham":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Peacham"},
"Fairlee":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Fairlee"},
"Mount Holly":
{"votes":[
{"votes":71,"name":"mccain"},
{"votes":17,"name":"huckabee"},
{"votes":15,"name":"paul"},
{"votes":6,"name":"giuliani"},
{"votes":6,"name":"romney"}],
"total":115,"precincts":
{"total":1,"reporting":1},
"name":"Mount Holly"},
"St. Johnsbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"St. Johnsbury"},
"Waterford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Waterford"},
"Shoreham":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Shoreham"},
"Starksboro":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Starksboro"},
"Alburg":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Alburg"},
"Newbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Newbury"},
"Barre Town":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Barre Town"},
"Bethel":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bethel"},
"Proctor":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Proctor"},
"Berkshire":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Berkshire"},
"Hubbardton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hubbardton"},
"Marlboro":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Marlboro"},
"St. Albans":
{"votes":[
{"votes":229,"name":"mccain"},
{"votes":35,"name":"huckabee"},
{"votes":24,"name":"paul"},
{"votes":19,"name":"romney"},
{"votes":9,"name":"giuliani"}],
"total":316,"precincts":
{"total":1,"reporting":1},
"name":"St. Albans"},
"Brookline":
{"votes":[
{"votes":26,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":36,"precincts":
{"total":1,"reporting":1},
"name":"Brookline"},
"South Hero":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"South Hero"},
"Readsboro":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Readsboro"},
"Searsburg":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Searsburg"},
"Lunenburg":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Lunenburg"},
"Bloomfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bloomfield"},
"Bradford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bradford"},
"Sutton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sutton"},
"Lincoln":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Lincoln"},
"Tunbridge":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Tunbridge"},
"Roxbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Roxbury"},
"Killington":
{"votes":[
{"votes":58,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":4,"name":"giuliani"},
{"votes":4,"name":"romney"},
{"votes":4,"name":"paul"}],
"total":77,"precincts":
{"total":1,"reporting":1},
"name":"Killington"},
"Corinth":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Corinth"},
"Townshend":
{"votes":[
{"votes":32,"name":"mccain"},
{"votes":10,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"romney"}],
"total":50,"precincts":
{"total":1,"reporting":1},
"name":"Townshend"},
"Stannard":
{"votes":[
{"votes":11,"name":"mccain"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"paul"},
{"votes":0,"name":"giuliani"}],
"total":14,"precincts":
{"total":1,"reporting":1},
"name":"Stannard"},
"Vernon":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Vernon"},
"Westford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Westford"},
"Jamaica":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Jamaica"},
"Weathersfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Weathersfield"},
"Stratton":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"}],
"total":27,"precincts":
{"total":1,"reporting":1},
"name":"Stratton"},
"Calais":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Calais"},
"Bolton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Bolton"},
"Braintree":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Braintree"},
"Greensboro":
{"votes":[
{"votes":27,"name":"mccain"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"romney"},
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"}],
"total":32,"precincts":
{"total":1,"reporting":1},
"name":"Greensboro"},
"North Hero":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"North Hero"},
"Winooski":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Winooski"},
"Landgrove":
{"votes":[
{"votes":9,"name":"mccain"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"paul"}],
"total":12,"precincts":
{"total":1,"reporting":1},
"name":"Landgrove"},
"Cabot":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Cabot"},
"West Haven":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"West Haven"},
"Brownington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Brownington"},
"Brighton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Brighton"},
"Enosburgh":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Enosburgh"},
"Concord":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Concord"},
"Maidstone":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Maidstone"},
"St. George":
{"votes":[
{"votes":24,"name":"mccain"},
{"votes":4,"name":"huckabee"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"paul"}],
"total":31,"precincts":
{"total":1,"reporting":1},
"name":"St. George"},
"Sandgate":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sandgate"},
"Fairfax":
{"votes":[
{"votes":178,"name":"mccain"},
{"votes":54,"name":"huckabee"},
{"votes":23,"name":"paul"},
{"votes":17,"name":"romney"},
{"votes":7,"name":"giuliani"}],
"total":279,"precincts":
{"total":1,"reporting":1},
"name":"Fairfax"},
"Halifax":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Halifax"},
"Benson":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Benson"},
"Lemington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Lemington"},
"Royalton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Royalton"},
"West Fairlee":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"West Fairlee"},
"Middlesex":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Middlesex"},
"Strafford":
{"votes":[
{"votes":26,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":4,"name":"romney"},
{"votes":1,"name":"paul"},
{"votes":0,"name":"giuliani"}],
"total":37,"precincts":
{"total":1,"reporting":1},
"name":"Strafford"},
"Waitsfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Waitsfield"},
"Waterville":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Waterville"},
"Putney":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Putney"},
"Newfane":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Newfane"},
"Westmore":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Westmore"},
"Westminster":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Westminster"},
"Plainfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Plainfield"},
"Georgia":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Georgia"},
"Stockbridge":
{"votes":[
{"votes":28,"name":"mccain"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"romney"},
{"votes":0,"name":"giuliani"}],
"total":33,"precincts":
{"total":1,"reporting":1},
"name":"Stockbridge"},
"Fletcher":
{"votes":[
{"votes":26,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":6,"name":"paul"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"}],
"total":45,"precincts":
{"total":1,"reporting":1},
"name":"Fletcher"},
"Fair Haven":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Fair Haven"},
"Mendon":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Mendon"},
"Springfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Springfield"},
"Pownal":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Pownal"},
"Lowell":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Lowell"},
"Hartland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hartland"},
"Marshfield":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Marshfield"},
"Woodbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Woodbury"},
"St. Albans Town":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"St. Albans Town"},
"Grafton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Grafton"},
"Elmore":
{"votes":[
{"votes":22,"name":"mccain"},
{"votes":7,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":1,"name":"paul"},
{"votes":0,"name":"giuliani"}],
"total":32,"precincts":
{"total":1,"reporting":1},
"name":"Elmore"},
"Wells":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wells"},
"Hartford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hartford"},
"East Haven":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"East Haven"},
"Vergennes":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Vergennes"},
"Athens":
{"votes":[
{"votes":18,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":1,"name":"paul"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"}],
"total":25,"precincts":
{"total":1,"reporting":1},
"name":"Athens"},
"Ferrisburg":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Ferrisburg"},
"Hancock":
{"votes":[
{"votes":11,"name":"mccain"},
{"votes":3,"name":"paul"},
{"votes":1,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"}],
"total":15,"precincts":
{"total":1,"reporting":1},
"name":"Hancock"},
"Milton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Milton"},
"Middletown Springs":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Middletown Springs"},
"Hardwick":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Hardwick"},
"Ryegate":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Ryegate"},
"Swanton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Swanton"},
"Coventry":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Coventry"},
"Wilmington":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wilmington"},
"Ludlow":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Ludlow"},
"Monkton":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Monkton"},
"Newport Town":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Newport Town"},
"Plymouth":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Plymouth"},
"Morgan":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Morgan"},
"Charleston":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Charleston"},
"Underhill":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Underhill"},
"Baltimore":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Baltimore"},
"Dover":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Dover"},
"Richford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Richford"},
"New Haven":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"New Haven"},
"Wallingford":
{"votes":[
{"votes":141,"name":"mccain"},
{"votes":35,"name":"huckabee"},
{"votes":12,"name":"giuliani"},
{"votes":12,"name":"romney"},
{"votes":7,"name":"paul"}],
"total":207,"precincts":
{"total":1,"reporting":1},
"name":"Wallingford"},
"Whiting":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Whiting"},
"Leicester":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Leicester"},
"Pittsford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Pittsford"},
"Norwich":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Norwich"},
"Weston":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Weston"},
"Fayston":
{"votes":[
{"votes":33,"name":"mccain"},
{"votes":8,"name":"huckabee"},
{"votes":4,"name":"paul"},
{"votes":1,"name":"giuliani"},
{"votes":0,"name":"romney"}],
"total":46,"precincts":
{"total":1,"reporting":1},
"name":"Fayston"},
"Sunderland":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Sunderland"},
"Stamford":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Stamford"},
"Salisbury":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Salisbury"},
"Worcester":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Worcester"},
"Williston":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Williston"},
"Wolcott":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Wolcott"},
"Randolph":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Randolph"},
"Rutland Town":
{"votes":[
{"votes":0,"name":"huckabee"},
{"votes":0,"name":"giuliani"},
{"votes":0,"name":"romney"},
{"votes":0,"name":"paul"},
{"votes":0,"name":"mccain"}],
"total":0,"precincts":
{"total":1,"reporting":0},
"name":"Rutland Town"},
"Franklin":
{"votes":[
{"votes":56,"name":"mccain"},
{"votes":28,"name":"huckabee"},
{"votes":6,"name":"romney"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"giuliani"}],
"total":95,"precincts":
{"total":1,"reporting":1},
"name":"Franklin"}}})