GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":646007,"name":"obama","delegates":"42"},
{"votes":452795,"name":"clinton","delegates":"32"},
{"votes":6673,"name":"edwards"},
{"votes":2644,"name":"kucinich"},
{"votes":756,"name":"biden"},
{"votes":535,"name":"richardson"},
{"votes":518,"name":"gravel"},
{"votes":498,"name":"dodd"}],
"name":"Wisconsin","precincts":
{"total":3570,"reporting":3570},
"delegates":"74","date":"02-19"},
"state":"WI","party":"dem","total":1110426,"locals":
{"Marinette":
{"votes":[
{"votes":3798,"name":"clinton"},
{"votes":3504,"name":"obama"},
{"votes":43,"name":"edwards"},
{"votes":19,"name":"kucinich"},
{"votes":8,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"gravel"}],
"total":7383,"precincts":
{"total":32,"reporting":32},
"name":"Marinette"},
"Chippewa":
{"votes":[
{"votes":5518,"name":"obama"},
{"votes":4744,"name":"clinton"},
{"votes":60,"name":"edwards"},
{"votes":10,"name":"kucinich"},
{"votes":8,"name":"biden"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":10348,"precincts":
{"total":37,"reporting":37},
"name":"Chippewa"},
"Jackson":
{"votes":[
{"votes":1804,"name":"obama"},
{"votes":1642,"name":"clinton"},
{"votes":23,"name":"edwards"},
{"votes":17,"name":"kucinich"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":0,"name":"richardson"}],
"total":3495,"precincts":
{"total":27,"reporting":27},
"name":"Jackson"},
"Richland":
{"votes":[
{"votes":1730,"name":"obama"},
{"votes":1401,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"biden"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"gravel"}],
"total":3159,"precincts":
{"total":33,"reporting":33},
"name":"Richland"},
"Grant":
{"votes":[
{"votes":4548,"name":"obama"},
{"votes":3163,"name":"clinton"},
{"votes":67,"name":"edwards"},
{"votes":17,"name":"kucinich"},
{"votes":10,"name":"richardson"},
{"votes":8,"name":"gravel"},
{"votes":5,"name":"dodd"},
{"votes":5,"name":"biden"}],
"total":7823,"precincts":
{"total":55,"reporting":55},
"name":"Grant"},
"Iron":
{"votes":[
{"votes":651,"name":"clinton"},
{"votes":640,"name":"obama"},
{"votes":14,"name":"edwards"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"gravel"}],
"total":1314,"precincts":
{"total":19,"reporting":19},
"name":"Iron"},
"Portage":
{"votes":[
{"votes":8993,"name":"obama"},
{"votes":6707,"name":"clinton"},
{"votes":115,"name":"edwards"},
{"votes":43,"name":"kucinich"},
{"votes":13,"name":"gravel"},
{"votes":11,"name":"biden"},
{"votes":8,"name":"dodd"},
{"votes":8,"name":"richardson"}],
"total":15898,"precincts":
{"total":38,"reporting":38},
"name":"Portage"},
"Burnett":
{"votes":[
{"votes":1265,"name":"clinton"},
{"votes":1077,"name":"obama"},
{"votes":29,"name":"edwards"},
{"votes":9,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"gravel"}],
"total":2388,"precincts":
{"total":24,"reporting":24},
"name":"Burnett"},
"Lincoln":
{"votes":[
{"votes":3493,"name":"obama"},
{"votes":2995,"name":"clinton"},
{"votes":66,"name":"edwards"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"dodd"},
{"votes":0,"name":"gravel"}],
"total":6568,"precincts":
{"total":25,"reporting":25},
"name":"Lincoln"},
"Douglas":
{"votes":[
{"votes":4756,"name":"clinton"},
{"votes":3549,"name":"obama"},
{"votes":77,"name":"edwards"},
{"votes":15,"name":"kucinich"},
{"votes":14,"name":"biden"},
{"votes":5,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":8421,"precincts":
{"total":31,"reporting":31},
"name":"Douglas"},
"Outagamie":
{"votes":[
{"votes":18359,"name":"obama"},
{"votes":12317,"name":"clinton"},
{"votes":160,"name":"edwards"},
{"votes":49,"name":"kucinich"},
{"votes":20,"name":"biden"},
{"votes":11,"name":"richardson"},
{"votes":10,"name":"gravel"},
{"votes":7,"name":"dodd"}],
"total":30933,"precincts":
{"total":90,"reporting":90},
"name":"Outagamie"},
"Bayfield":
{"votes":[
{"votes":2157,"name":"obama"},
{"votes":1731,"name":"clinton"},
{"votes":30,"name":"edwards"},
{"votes":12,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":3944,"precincts":
{"total":29,"reporting":29},
"name":"Bayfield"},
"Sauk":
{"votes":[
{"votes":6931,"name":"obama"},
{"votes":4829,"name":"clinton"},
{"votes":86,"name":"edwards"},
{"votes":21,"name":"kucinich"},
{"votes":7,"name":"biden"},
{"votes":7,"name":"richardson"},
{"votes":5,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":11890,"precincts":
{"total":55,"reporting":55},
"name":"Sauk"},
"Jefferson":
{"votes":[
{"votes":8382,"name":"obama"},
{"votes":6020,"name":"clinton"},
{"votes":111,"name":"edwards"},
{"votes":31,"name":"kucinich"},
{"votes":9,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":14570,"precincts":
{"total":36,"reporting":36},
"name":"Jefferson"},
"Forest":
{"votes":[
{"votes":1105,"name":"clinton"},
{"votes":839,"name":"obama"},
{"votes":25,"name":"edwards"},
{"votes":6,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"biden"}],
"total":1982,"precincts":
{"total":18,"reporting":18},
"name":"Forest"},
"Waushara":
{"votes":[
{"votes":1835,"name":"obama"},
{"votes":1743,"name":"clinton"},
{"votes":29,"name":"edwards"},
{"votes":13,"name":"kucinich"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"gravel"},
{"votes":0,"name":"dodd"}],
"total":3626,"precincts":
{"total":26,"reporting":26},
"name":"Waushara"},
"Fond du Lac":
{"votes":[
{"votes":8330,"name":"obama"},
{"votes":6785,"name":"clinton"},
{"votes":88,"name":"edwards"},
{"votes":33,"name":"kucinich"},
{"votes":10,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":6,"name":"gravel"},
{"votes":4,"name":"dodd"}],
"total":15262,"precincts":
{"total":74,"reporting":74},
"name":"Fond du Lac"},
"Crawford":
{"votes":[
{"votes":1559,"name":"obama"},
{"votes":1349,"name":"clinton"},
{"votes":29,"name":"edwards"},
{"votes":20,"name":"kucinich"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"gravel"},
{"votes":0,"name":"dodd"}],
"total":2960,"precincts":
{"total":27,"reporting":27},
"name":"Crawford"},
"Racine":
{"votes":[
{"votes":20620,"name":"obama"},
{"votes":16294,"name":"clinton"},
{"votes":227,"name":"edwards"},
{"votes":75,"name":"kucinich"},
{"votes":20,"name":"richardson"},
{"votes":17,"name":"dodd"},
{"votes":16,"name":"biden"},
{"votes":13,"name":"gravel"}],
"total":37282,"precincts":
{"total":64,"reporting":64},
"name":"Racine"},
"Waupaca":
{"votes":[
{"votes":4575,"name":"obama"},
{"votes":3344,"name":"clinton"},
{"votes":36,"name":"edwards"},
{"votes":16,"name":"kucinich"},
{"votes":7,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"}],
"total":7990,"precincts":
{"total":38,"reporting":38},
"name":"Waupaca"},
"Dodge":
{"votes":[
{"votes":6867,"name":"obama"},
{"votes":6055,"name":"clinton"},
{"votes":83,"name":"edwards"},
{"votes":32,"name":"kucinich"},
{"votes":14,"name":"biden"},
{"votes":8,"name":"dodd"},
{"votes":6,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":13067,"precincts":
{"total":55,"reporting":55},
"name":"Dodge"},
"Brown":
{"votes":[
{"votes":24737,"name":"obama"},
{"votes":18606,"name":"clinton"},
{"votes":249,"name":"edwards"},
{"votes":70,"name":"kucinich"},
{"votes":24,"name":"biden"},
{"votes":23,"name":"dodd"},
{"votes":21,"name":"gravel"},
{"votes":18,"name":"richardson"}],
"total":43748,"precincts":
{"total":91,"reporting":91},
"name":"Brown"},
"Eau Claire":
{"votes":[
{"votes":12950,"name":"obama"},
{"votes":7044,"name":"clinton"},
{"votes":87,"name":"edwards"},
{"votes":47,"name":"kucinich"},
{"votes":14,"name":"dodd"},
{"votes":12,"name":"richardson"},
{"votes":11,"name":"gravel"},
{"votes":9,"name":"biden"}],
"total":20174,"precincts":
{"total":55,"reporting":55},
"name":"Eau Claire"},
"Iowa":
{"votes":[
{"votes":2891,"name":"obama"},
{"votes":2126,"name":"clinton"},
{"votes":29,"name":"edwards"},
{"votes":16,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":1,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"gravel"}],
"total":5066,"precincts":
{"total":35,"reporting":35},
"name":"Iowa"},
"Dunn":
{"votes":[
{"votes":4129,"name":"obama"},
{"votes":2716,"name":"clinton"},
{"votes":41,"name":"edwards"},
{"votes":22,"name":"kucinich"},
{"votes":6,"name":"gravel"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"dodd"}],
"total":6922,"precincts":
{"total":35,"reporting":35},
"name":"Dunn"},
"Barron":
{"votes":[
{"votes":3970,"name":"obama"},
{"votes":3397,"name":"clinton"},
{"votes":63,"name":"edwards"},
{"votes":26,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"richardson"}],
"total":7467,"precincts":
{"total":36,"reporting":36},
"name":"Barron"},
"Buffalo":
{"votes":[
{"votes":1163,"name":"obama"},
{"votes":1091,"name":"clinton"},
{"votes":15,"name":"edwards"},
{"votes":7,"name":"kucinich"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"}],
"total":2283,"precincts":
{"total":23,"reporting":23},
"name":"Buffalo"},
"Manitowoc":
{"votes":[
{"votes":8370,"name":"obama"},
{"votes":6868,"name":"clinton"},
{"votes":137,"name":"edwards"},
{"votes":26,"name":"kucinich"},
{"votes":14,"name":"dodd"},
{"votes":9,"name":"gravel"},
{"votes":8,"name":"biden"},
{"votes":5,"name":"richardson"}],
"total":15437,"precincts":
{"total":42,"reporting":42},
"name":"Manitowoc"},
"Oconto":
{"votes":[
{"votes":3528,"name":"clinton"},
{"votes":3459,"name":"obama"},
{"votes":55,"name":"edwards"},
{"votes":19,"name":"kucinich"},
{"votes":8,"name":"richardson"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":3,"name":"gravel"}],
"total":7082,"precincts":
{"total":29,"reporting":29},
"name":"Oconto"},
"Walworth":
{"votes":[
{"votes":9766,"name":"obama"},
{"votes":6462,"name":"clinton"},
{"votes":103,"name":"edwards"},
{"votes":35,"name":"kucinich"},
{"votes":12,"name":"gravel"},
{"votes":11,"name":"richardson"},
{"votes":9,"name":"dodd"},
{"votes":8,"name":"biden"}],
"total":16406,"precincts":
{"total":43,"reporting":43},
"name":"Walworth"},
"Vernon":
{"votes":[
{"votes":2805,"name":"obama"},
{"votes":2225,"name":"clinton"},
{"votes":27,"name":"edwards"},
{"votes":24,"name":"kucinich"},
{"votes":5,"name":"dodd"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":5093,"precincts":
{"total":33,"reporting":33},
"name":"Vernon"},
"Sheboygan":
{"votes":[
{"votes":10918,"name":"obama"},
{"votes":9493,"name":"clinton"},
{"votes":129,"name":"edwards"},
{"votes":44,"name":"kucinich"},
{"votes":23,"name":"biden"},
{"votes":13,"name":"richardson"},
{"votes":13,"name":"gravel"},
{"votes":5,"name":"dodd"}],
"total":20638,"precincts":
{"total":58,"reporting":58},
"name":"Sheboygan"},
"Waukesha":
{"votes":[
{"votes":37648,"name":"obama"},
{"votes":34003,"name":"clinton"},
{"votes":307,"name":"edwards"},
{"votes":105,"name":"kucinich"},
{"votes":41,"name":"biden"},
{"votes":31,"name":"richardson"},
{"votes":23,"name":"dodd"},
{"votes":21,"name":"gravel"}],
"total":72179,"precincts":
{"total":208,"reporting":208},
"name":"Waukesha"},
"Milwaukee":
{"votes":[
{"votes":132239,"name":"obama"},
{"votes":72890,"name":"clinton"},
{"votes":907,"name":"edwards"},
{"votes":517,"name":"kucinich"},
{"votes":142,"name":"biden"},
{"votes":109,"name":"dodd"},
{"votes":86,"name":"gravel"},
{"votes":75,"name":"richardson"}],
"total":206965,"precincts":
{"total":491,"reporting":491},
"name":"Milwaukee"},
"Rusk":
{"votes":[
{"votes":1370,"name":"obama"},
{"votes":1274,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":14,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"gravel"}],
"total":2685,"precincts":
{"total":33,"reporting":33},
"name":"Rusk"},
"Pierce":
{"votes":[
{"votes":3076,"name":"obama"},
{"votes":2583,"name":"clinton"},
{"votes":42,"name":"edwards"},
{"votes":15,"name":"kucinich"},
{"votes":7,"name":"biden"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"}],
"total":5733,"precincts":
{"total":28,"reporting":28},
"name":"Pierce"},
"Vilas":
{"votes":[
{"votes":2732,"name":"obama"},
{"votes":1991,"name":"clinton"},
{"votes":36,"name":"edwards"},
{"votes":8,"name":"kucinich"},
{"votes":7,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"}],
"total":4779,"precincts":
{"total":15,"reporting":15},
"name":"Vilas"},
"Adams":
{"votes":[
{"votes":2105,"name":"clinton"},
{"votes":1783,"name":"obama"},
{"votes":48,"name":"edwards"},
{"votes":6,"name":"kucinich"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"dodd"}],
"total":3951,"precincts":
{"total":20,"reporting":20},
"name":"Adams"},
"Trempealeau":
{"votes":[
{"votes":2690,"name":"clinton"},
{"votes":2629,"name":"obama"},
{"votes":39,"name":"edwards"},
{"votes":17,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"richardson"}],
"total":5391,"precincts":
{"total":26,"reporting":26},
"name":"Trempealeau"},
"Florence":
{"votes":[
{"votes":429,"name":"obama"},
{"votes":385,"name":"clinton"},
{"votes":7,"name":"edwards"},
{"votes":3,"name":"kucinich"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"gravel"}],
"total":826,"precincts":
{"total":8,"reporting":8},
"name":"Florence"},
"Oneida":
{"votes":[
{"votes":4578,"name":"obama"},
{"votes":3383,"name":"clinton"},
{"votes":72,"name":"edwards"},
{"votes":15,"name":"kucinich"},
{"votes":7,"name":"dodd"},
{"votes":6,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":3,"name":"gravel"}],
"total":8070,"precincts":
{"total":29,"reporting":29},
"name":"Oneida"},
"Sawyer":
{"votes":[
{"votes":1468,"name":"obama"},
{"votes":1195,"name":"clinton"},
{"votes":24,"name":"edwards"},
{"votes":5,"name":"kucinich"},
{"votes":4,"name":"richardson"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"biden"},
{"votes":1,"name":"dodd"}],
"total":2704,"precincts":
{"total":21,"reporting":21},
"name":"Sawyer"},
"Door":
{"votes":[
{"votes":4196,"name":"obama"},
{"votes":2767,"name":"clinton"},
{"votes":49,"name":"edwards"},
{"votes":14,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":7038,"precincts":
{"total":29,"reporting":29},
"name":"Door"},
"Green":
{"votes":[
{"votes":4321,"name":"obama"},
{"votes":2898,"name":"clinton"},
{"votes":39,"name":"edwards"},
{"votes":12,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":2,"name":"gravel"}],
"total":7283,"precincts":
{"total":24,"reporting":24},
"name":"Green"},
"Kenosha":
{"votes":[
{"votes":15467,"name":"obama"},
{"votes":14552,"name":"clinton"},
{"votes":218,"name":"edwards"},
{"votes":44,"name":"kucinich"},
{"votes":28,"name":"biden"},
{"votes":12,"name":"gravel"},
{"votes":11,"name":"dodd"},
{"votes":8,"name":"richardson"}],
"total":30340,"precincts":
{"total":82,"reporting":82},
"name":"Kenosha"},
"Rock":
{"votes":[
{"votes":17525,"name":"obama"},
{"votes":13134,"name":"clinton"},
{"votes":206,"name":"edwards"},
{"votes":53,"name":"kucinich"},
{"votes":16,"name":"dodd"},
{"votes":16,"name":"biden"},
{"votes":13,"name":"richardson"},
{"votes":11,"name":"gravel"}],
"total":30974,"precincts":
{"total":88,"reporting":88},
"name":"Rock"},
"Langlade":
{"votes":[
{"votes":1913,"name":"obama"},
{"votes":1879,"name":"clinton"},
{"votes":23,"name":"edwards"},
{"votes":14,"name":"kucinich"},
{"votes":6,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"gravel"}],
"total":3837,"precincts":
{"total":27,"reporting":27},
"name":"Langlade"},
"Columbia":
{"votes":[
{"votes":6064,"name":"obama"},
{"votes":4618,"name":"clinton"},
{"votes":77,"name":"edwards"},
{"votes":31,"name":"kucinich"},
{"votes":8,"name":"biden"},
{"votes":6,"name":"richardson"},
{"votes":6,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":10813,"precincts":
{"total":37,"reporting":37},
"name":"Columbia"},
"Dane":
{"votes":[
{"votes":95359,"name":"obama"},
{"votes":44168,"name":"clinton"},
{"votes":752,"name":"edwards"},
{"votes":527,"name":"kucinich"},
{"votes":95,"name":"gravel"},
{"votes":78,"name":"richardson"},
{"votes":74,"name":"biden"},
{"votes":73,"name":"dodd"}],
"total":141126,"precincts":
{"total":223,"reporting":223},
"name":"Dane"},
"La Crosse":
{"votes":[
{"votes":13068,"name":"obama"},
{"votes":9189,"name":"clinton"},
{"votes":140,"name":"edwards"},
{"votes":46,"name":"kucinich"},
{"votes":21,"name":"gravel"},
{"votes":17,"name":"biden"},
{"votes":14,"name":"richardson"},
{"votes":8,"name":"dodd"}],
"total":22503,"precincts":
{"total":40,"reporting":40},
"name":"La Crosse"},
"Green Lake":
{"votes":[
{"votes":1577,"name":"obama"},
{"votes":1265,"name":"clinton"},
{"votes":20,"name":"edwards"},
{"votes":4,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"kucinich"}],
"total":2871,"precincts":
{"total":16,"reporting":16},
"name":"Green Lake"},
"Menominee":
{"votes":[
{"votes":206,"name":"obama"},
{"votes":190,"name":"clinton"},
{"votes":3,"name":"edwards"},
{"votes":1,"name":"kucinich"},
{"votes":0,"name":"dodd"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"richardson"},
{"votes":0,"name":"gravel"}],
"total":400,"precincts":
{"total":5,"reporting":5},
"name":"Menominee"},
"Taylor":
{"votes":[
{"votes":1668,"name":"obama"},
{"votes":1378,"name":"clinton"},
{"votes":33,"name":"edwards"},
{"votes":8,"name":"kucinich"},
{"votes":2,"name":"biden"},
{"votes":2,"name":"gravel"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"dodd"}],
"total":3092,"precincts":
{"total":30,"reporting":30},
"name":"Taylor"},
"Calumet":
{"votes":[
{"votes":4648,"name":"obama"},
{"votes":3460,"name":"clinton"},
{"votes":45,"name":"edwards"},
{"votes":13,"name":"kucinich"},
{"votes":4,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":2,"name":"dodd"}],
"total":8178,"precincts":
{"total":35,"reporting":35},
"name":"Calumet"},
"Clark":
{"votes":[
{"votes":2613,"name":"obama"},
{"votes":2233,"name":"clinton"},
{"votes":54,"name":"edwards"},
{"votes":10,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"gravel"},
{"votes":3,"name":"richardson"}],
"total":4927,"precincts":
{"total":58,"reporting":58},
"name":"Clark"},
"St. Croix":
{"votes":[
{"votes":5468,"name":"obama"},
{"votes":4899,"name":"clinton"},
{"votes":79,"name":"edwards"},
{"votes":59,"name":"kucinich"},
{"votes":15,"name":"biden"},
{"votes":6,"name":"dodd"},
{"votes":5,"name":"richardson"},
{"votes":4,"name":"gravel"}],
"total":10535,"precincts":
{"total":38,"reporting":38},
"name":"St. Croix"},
"Lafayette":
{"votes":[
{"votes":1662,"name":"obama"},
{"votes":1347,"name":"clinton"},
{"votes":30,"name":"edwards"},
{"votes":10,"name":"kucinich"},
{"votes":3,"name":"dodd"},
{"votes":3,"name":"richardson"},
{"votes":0,"name":"biden"},
{"votes":0,"name":"gravel"}],
"total":3055,"precincts":
{"total":29,"reporting":29},
"name":"Lafayette"},
"Pepin":
{"votes":[
{"votes":629,"name":"obama"},
{"votes":590,"name":"clinton"},
{"votes":11,"name":"edwards"},
{"votes":9,"name":"kucinich"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"gravel"},
{"votes":0,"name":"dodd"}],
"total":1242,"precincts":
{"total":11,"reporting":11},
"name":"Pepin"},
"Washington":
{"votes":[
{"votes":10529,"name":"obama"},
{"votes":9676,"name":"clinton"},
{"votes":108,"name":"edwards"},
{"votes":36,"name":"kucinich"},
{"votes":19,"name":"biden"},
{"votes":9,"name":"richardson"},
{"votes":8,"name":"dodd"},
{"votes":8,"name":"gravel"}],
"total":20393,"precincts":
{"total":36,"reporting":36},
"name":"Washington"},
"Ozaukee":
{"votes":[
{"votes":9816,"name":"obama"},
{"votes":7608,"name":"clinton"},
{"votes":89,"name":"edwards"},
{"votes":26,"name":"kucinich"},
{"votes":10,"name":"gravel"},
{"votes":9,"name":"richardson"},
{"votes":7,"name":"biden"},
{"votes":6,"name":"dodd"}],
"total":17571,"precincts":
{"total":47,"reporting":47},
"name":"Ozaukee"},
"Ashland":
{"votes":[
{"votes":1800,"name":"obama"},
{"votes":1583,"name":"clinton"},
{"votes":30,"name":"edwards"},
{"votes":13,"name":"kucinich"},
{"votes":6,"name":"biden"},
{"votes":4,"name":"gravel"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"dodd"}],
"total":3439,"precincts":
{"total":26,"reporting":26},
"name":"Ashland"},
"Shawano":
{"votes":[
{"votes":3316,"name":"obama"},
{"votes":2977,"name":"clinton"},
{"votes":39,"name":"edwards"},
{"votes":13,"name":"kucinich"},
{"votes":8,"name":"richardson"},
{"votes":3,"name":"biden"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"}],
"total":6360,"precincts":
{"total":43,"reporting":43},
"name":"Shawano"},
"Wood":
{"votes":[
{"votes":9082,"name":"obama"},
{"votes":6327,"name":"clinton"},
{"votes":159,"name":"edwards"},
{"votes":32,"name":"kucinich"},
{"votes":11,"name":"richardson"},
{"votes":10,"name":"dodd"},
{"votes":6,"name":"biden"},
{"votes":5,"name":"gravel"}],
"total":15632,"precincts":
{"total":34,"reporting":34},
"name":"Wood"},
"Marathon":
{"votes":[
{"votes":13363,"name":"obama"},
{"votes":11090,"name":"clinton"},
{"votes":168,"name":"edwards"},
{"votes":38,"name":"kucinich"},
{"votes":17,"name":"biden"},
{"votes":10,"name":"richardson"},
{"votes":6,"name":"dodd"},
{"votes":4,"name":"gravel"}],
"total":24696,"precincts":
{"total":142,"reporting":142},
"name":"Marathon"},
"Winnebago":
{"votes":[
{"votes":18265,"name":"obama"},
{"votes":11878,"name":"clinton"},
{"votes":173,"name":"edwards"},
{"votes":43,"name":"kucinich"},
{"votes":24,"name":"biden"},
{"votes":11,"name":"gravel"},
{"votes":9,"name":"dodd"},
{"votes":8,"name":"richardson"}],
"total":30411,"precincts":
{"total":74,"reporting":74},
"name":"Winnebago"},
"Juneau":
{"votes":[
{"votes":1910,"name":"clinton"},
{"votes":1819,"name":"obama"},
{"votes":27,"name":"edwards"},
{"votes":12,"name":"kucinich"},
{"votes":1,"name":"biden"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"gravel"},
{"votes":0,"name":"dodd"}],
"total":3771,"precincts":
{"total":28,"reporting":28},
"name":"Juneau"},
"Marquette":
{"votes":[
{"votes":1457,"name":"obama"},
{"votes":1353,"name":"clinton"},
{"votes":12,"name":"kucinich"},
{"votes":10,"name":"edwards"},
{"votes":3,"name":"gravel"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"biden"}],
"total":2837,"precincts":
{"total":19,"reporting":19},
"name":"Marquette"},
"Washburn":
{"votes":[
{"votes":1537,"name":"obama"},
{"votes":1423,"name":"clinton"},
{"votes":34,"name":"edwards"},
{"votes":17,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":3019,"precincts":
{"total":29,"reporting":29},
"name":"Washburn"},
"Polk":
{"votes":[
{"votes":3503,"name":"clinton"},
{"votes":3232,"name":"obama"},
{"votes":88,"name":"edwards"},
{"votes":36,"name":"kucinich"},
{"votes":11,"name":"biden"},
{"votes":5,"name":"richardson"},
{"votes":5,"name":"gravel"},
{"votes":3,"name":"dodd"}],
"total":6883,"precincts":
{"total":36,"reporting":36},
"name":"Polk"},
"Price":
{"votes":[
{"votes":1789,"name":"obama"},
{"votes":1453,"name":"clinton"},
{"votes":29,"name":"edwards"},
{"votes":8,"name":"kucinich"},
{"votes":5,"name":"biden"},
{"votes":1,"name":"dodd"},
{"votes":1,"name":"richardson"},
{"votes":0,"name":"gravel"}],
"total":3286,"precincts":
{"total":44,"reporting":44},
"name":"Price"},
"Monroe":
{"votes":[
{"votes":3167,"name":"obama"},
{"votes":2811,"name":"clinton"},
{"votes":56,"name":"edwards"},
{"votes":10,"name":"kucinich"},
{"votes":3,"name":"biden"},
{"votes":2,"name":"dodd"},
{"votes":2,"name":"richardson"},
{"votes":1,"name":"gravel"}],
"total":6052,"precincts":
{"total":34,"reporting":34},
"name":"Monroe"},
"Kewaunee":
{"votes":[
{"votes":2031,"name":"obama"},
{"votes":1887,"name":"clinton"},
{"votes":29,"name":"edwards"},
{"votes":4,"name":"dodd"},
{"votes":4,"name":"kucinich"},
{"votes":3,"name":"richardson"},
{"votes":2,"name":"biden"},
{"votes":0,"name":"gravel"}],
"total":3960,"precincts":
{"total":14,"reporting":14},
"name":"Kewaunee"}}})