GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":150391,"name":"clinton"},
{"votes":63011,"name":"obama"},
{"votes":16488,"name":"edwards"}],
"name":"West Virginia","precincts":
{"total":1894,"reporting":1221},
"delegates":28,"date":"05-13"},
"state":"WV","party":"dem","total":229890,"locals":
{"Summers":
{"votes":[
{"votes":351,"name":"clinton"},
{"votes":151,"name":"obama"},
{"votes":48,"name":"edwards"}],
"total":550,"precincts":
{"total":15,"reporting":4},
"name":"Summers"},
"Jackson":
{"votes":[
{"votes":3602,"name":"clinton"},
{"votes":1178,"name":"obama"},
{"votes":379,"name":"edwards"}],
"total":5159,"precincts":
{"total":34,"reporting":34},
"name":"Jackson"},
"Braxton":
{"votes":[
{"votes":753,"name":"clinton"},
{"votes":246,"name":"obama"},
{"votes":117,"name":"edwards"}],
"total":1116,"precincts":
{"total":22,"reporting":9},
"name":"Braxton"},
"Grant":
{"votes":[
{"votes":456,"name":"clinton"},
{"votes":188,"name":"obama"},
{"votes":55,"name":"edwards"}],
"total":699,"precincts":
{"total":15,"reporting":15},
"name":"Grant"},
"Pendleton":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pendleton"},
"Wyoming":
{"votes":[
{"votes":2309,"name":"clinton"},
{"votes":313,"name":"obama"},
{"votes":275,"name":"edwards"}],
"total":2897,"precincts":
{"total":36,"reporting":29},
"name":"Wyoming"},
"Calhoun":
{"votes":[
{"votes":1070,"name":"clinton"},
{"votes":356,"name":"obama"},
{"votes":178,"name":"edwards"}],
"total":1604,"precincts":
{"total":10,"reporting":10},
"name":"Calhoun"},
"Hampshire":
{"votes":[
{"votes":298,"name":"clinton"},
{"votes":119,"name":"obama"},
{"votes":32,"name":"edwards"}],
"total":449,"precincts":
{"total":23,"reporting":4},
"name":"Hampshire"},
"Mason":
{"votes":[
{"votes":3051,"name":"clinton"},
{"votes":784,"name":"obama"},
{"votes":365,"name":"edwards"}],
"total":4200,"precincts":
{"total":38,"reporting":37},
"name":"Mason"},
"Roane":
{"votes":[
{"votes":1899,"name":"clinton"},
{"votes":602,"name":"obama"},
{"votes":179,"name":"edwards"}],
"total":2680,"precincts":
{"total":20,"reporting":20},
"name":"Roane"},
"Wirt":
{"votes":[
{"votes":724,"name":"clinton"},
{"votes":228,"name":"obama"},
{"votes":115,"name":"edwards"}],
"total":1067,"precincts":
{"total":9,"reporting":9},
"name":"Wirt"},
"Wood":
{"votes":[
{"votes":8391,"name":"clinton"},
{"votes":3201,"name":"obama"},
{"votes":930,"name":"edwards"}],
"total":12522,"precincts":
{"total":84,"reporting":84},
"name":"Wood"},
"Ohio":
{"votes":[
{"votes":5061,"name":"clinton"},
{"votes":3075,"name":"obama"},
{"votes":540,"name":"edwards"}],
"total":8676,"precincts":
{"total":39,"reporting":39},
"name":"Ohio"},
"Nicholas":
{"votes":[
{"votes":1456,"name":"clinton"},
{"votes":454,"name":"obama"},
{"votes":197,"name":"edwards"}],
"total":2107,"precincts":
{"total":28,"reporting":11},
"name":"Nicholas"},
"Putnam":
{"votes":[
{"votes":2382,"name":"clinton"},
{"votes":983,"name":"obama"},
{"votes":205,"name":"edwards"}],
"total":3570,"precincts":
{"total":48,"reporting":13},
"name":"Putnam"},
"McDowell":
{"votes":[
{"votes":794,"name":"clinton"},
{"votes":174,"name":"obama"},
{"votes":55,"name":"edwards"}],
"total":1023,"precincts":
{"total":42,"reporting":11},
"name":"McDowell"},
"Greenbrier":
{"votes":[
{"votes":1201,"name":"clinton"},
{"votes":748,"name":"obama"},
{"votes":155,"name":"edwards"}],
"total":2104,"precincts":
{"total":36,"reporting":6},
"name":"Greenbrier"},
"Gilmer":
{"votes":[
{"votes":369,"name":"clinton"},
{"votes":109,"name":"obama"},
{"votes":64,"name":"edwards"}],
"total":542,"precincts":
{"total":12,"reporting":4},
"name":"Gilmer"},
"Fayette":
{"votes":[
{"votes":3693,"name":"clinton"},
{"votes":1289,"name":"obama"},
{"votes":404,"name":"edwards"}],
"total":5386,"precincts":
{"total":39,"reporting":10},
"name":"Fayette"},
"Monongalia":
{"votes":[
{"votes":8123,"name":"clinton"},
{"votes":5642,"name":"obama"},
{"votes":945,"name":"edwards"}],
"total":14710,"precincts":
{"total":72,"reporting":72},
"name":"Monongalia"},
"Tucker":
{"votes":[
{"votes":911,"name":"clinton"},
{"votes":262,"name":"obama"},
{"votes":176,"name":"edwards"}],
"total":1349,"precincts":
{"total":11,"reporting":8},
"name":"Tucker"},
"Barbour":
{"votes":[
{"votes":2069,"name":"clinton"},
{"votes":581,"name":"obama"},
{"votes":203,"name":"edwards"}],
"total":2853,"precincts":
{"total":22,"reporting":22},
"name":"Barbour"},
"Berkeley":
{"votes":[
{"votes":3915,"name":"clinton"},
{"votes":2710,"name":"obama"},
{"votes":445,"name":"edwards"}],
"total":7070,"precincts":
{"total":66,"reporting":49},
"name":"Berkeley"},
"Brooke":
{"votes":[
{"votes":3866,"name":"clinton"},
{"votes":1577,"name":"obama"},
{"votes":426,"name":"edwards"}],
"total":5869,"precincts":
{"total":27,"reporting":27},
"name":"Brooke"},
"Ritchie":
{"votes":[
{"votes":707,"name":"clinton"},
{"votes":211,"name":"obama"},
{"votes":83,"name":"edwards"}],
"total":1001,"precincts":
{"total":15,"reporting":15},
"name":"Ritchie"},
"Pocahontas":
{"votes":[
{"votes":1318,"name":"clinton"},
{"votes":557,"name":"obama"},
{"votes":214,"name":"edwards"}],
"total":2089,"precincts":
{"total":15,"reporting":15},
"name":"Pocahontas"},
"Wayne":
{"votes":[
{"votes":3481,"name":"clinton"},
{"votes":681,"name":"obama"},
{"votes":332,"name":"edwards"}],
"total":4494,"precincts":
{"total":37,"reporting":15},
"name":"Wayne"},
"Lincoln":
{"votes":[
{"votes":3296,"name":"clinton"},
{"votes":510,"name":"obama"},
{"votes":344,"name":"edwards"}],
"total":4150,"precincts":
{"total":35,"reporting":28},
"name":"Lincoln"},
"Mineral":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Mineral"},
"Harrison":
{"votes":[
{"votes":5074,"name":"clinton"},
{"votes":1636,"name":"obama"},
{"votes":607,"name":"edwards"}],
"total":7317,"precincts":
{"total":89,"reporting":21},
"name":"Harrison"},
"Hancock":
{"votes":[
{"votes":3487,"name":"clinton"},
{"votes":1318,"name":"obama"},
{"votes":438,"name":"edwards"}],
"total":5243,"precincts":
{"total":28,"reporting":22},
"name":"Hancock"},
"Kanawha":
{"votes":[
{"votes":15866,"name":"clinton"},
{"votes":9871,"name":"obama"},
{"votes":1042,"name":"edwards"}],
"total":26779,"precincts":
{"total":160,"reporting":99},
"name":"Kanawha"},
"Pleasants":
{"votes":[
{"votes":933,"name":"clinton"},
{"votes":372,"name":"obama"},
{"votes":170,"name":"edwards"}],
"total":1475,"precincts":
{"total":11,"reporting":11},
"name":"Pleasants"},
"Raleigh":
{"votes":[
{"votes":9716,"name":"clinton"},
{"votes":3871,"name":"obama"},
{"votes":1101,"name":"edwards"}],
"total":14688,"precincts":
{"total":63,"reporting":63},
"name":"Raleigh"},
"Morgan":
{"votes":[
{"votes":1178,"name":"clinton"},
{"votes":718,"name":"obama"},
{"votes":152,"name":"edwards"}],
"total":2048,"precincts":
{"total":13,"reporting":13},
"name":"Morgan"},
"Clay":
{"votes":[
{"votes":1162,"name":"clinton"},
{"votes":261,"name":"obama"},
{"votes":201,"name":"edwards"}],
"total":1624,"precincts":
{"total":13,"reporting":9},
"name":"Clay"},
"Webster":
{"votes":[
{"votes":1343,"name":"clinton"},
{"votes":242,"name":"obama"},
{"votes":152,"name":"edwards"}],
"total":1737,"precincts":
{"total":13,"reporting":10},
"name":"Webster"},
"Wetzel":
{"votes":[
{"votes":2571,"name":"clinton"},
{"votes":1030,"name":"obama"},
{"votes":392,"name":"edwards"}],
"total":3993,"precincts":
{"total":22,"reporting":22},
"name":"Wetzel"},
"Upshur":
{"votes":[
{"votes":413,"name":"clinton"},
{"votes":171,"name":"obama"},
{"votes":35,"name":"edwards"}],
"total":619,"precincts":
{"total":29,"reporting":6},
"name":"Upshur"},
"Taylor":
{"votes":[
{"votes":404,"name":"clinton"},
{"votes":93,"name":"obama"},
{"votes":33,"name":"edwards"}],
"total":530,"precincts":
{"total":18,"reporting":4},
"name":"Taylor"},
"Lewis":
{"votes":[
{"votes":196,"name":"clinton"},
{"votes":65,"name":"obama"},
{"votes":22,"name":"edwards"}],
"total":283,"precincts":
{"total":24,"reporting":3},
"name":"Lewis"},
"Marshall":
{"votes":[
{"votes":2548,"name":"clinton"},
{"votes":1053,"name":"obama"},
{"votes":346,"name":"edwards"}],
"total":3947,"precincts":
{"total":45,"reporting":30},
"name":"Marshall"},
"Mingo":
{"votes":[
{"votes":4587,"name":"clinton"},
{"votes":523,"name":"obama"},
{"votes":259,"name":"edwards"}],
"total":5369,"precincts":
{"total":39,"reporting":18},
"name":"Mingo"},
"Cabell":
{"votes":[
{"votes":4902,"name":"clinton"},
{"votes":2301,"name":"obama"},
{"votes":424,"name":"edwards"}],
"total":7627,"precincts":
{"total":71,"reporting":40},
"name":"Cabell"},
"Tyler":
{"votes":[
{"votes":766,"name":"clinton"},
{"votes":311,"name":"obama"},
{"votes":116,"name":"edwards"}],
"total":1193,"precincts":
{"total":12,"reporting":12},
"name":"Tyler"},
"Hardy":
{"votes":[
{"votes":1208,"name":"clinton"},
{"votes":381,"name":"obama"},
{"votes":295,"name":"edwards"}],
"total":1884,"precincts":
{"total":18,"reporting":9},
"name":"Hardy"},
"Logan":
{"votes":[
{"votes":2268,"name":"clinton"},
{"votes":275,"name":"obama"},
{"votes":148,"name":"edwards"}],
"total":2691,"precincts":
{"total":35,"reporting":10},
"name":"Logan"},
"Jefferson":
{"votes":[
{"votes":4322,"name":"clinton"},
{"votes":4015,"name":"obama"},
{"votes":398,"name":"edwards"}],
"total":8735,"precincts":
{"total":31,"reporting":31},
"name":"Jefferson"},
"Marion":
{"votes":[
{"votes":9347,"name":"clinton"},
{"votes":3421,"name":"obama"},
{"votes":996,"name":"edwards"}],
"total":13764,"precincts":
{"total":76,"reporting":76},
"name":"Marion"},
"Doddridge":
{"votes":[
{"votes":421,"name":"clinton"},
{"votes":187,"name":"obama"},
{"votes":60,"name":"edwards"}],
"total":668,"precincts":
{"total":12,"reporting":12},
"name":"Doddridge"},
"Boone":
{"votes":[
{"votes":3092,"name":"clinton"},
{"votes":594,"name":"obama"},
{"votes":273,"name":"edwards"}],
"total":3959,"precincts":
{"total":37,"reporting":21},
"name":"Boone"},
"Mercer":
{"votes":[],
"total":0,"precincts":
{"total":61,"reporting":0},
"name":"Mercer"},
"Randolph":
{"votes":[
{"votes":4322,"name":"clinton"},
{"votes":1705,"name":"obama"},
{"votes":637,"name":"edwards"}],
"total":6664,"precincts":
{"total":27,"reporting":27},
"name":"Randolph"},
"Preston":
{"votes":[
{"votes":2878,"name":"clinton"},
{"votes":1061,"name":"obama"},
{"votes":456,"name":"edwards"}],
"total":4395,"precincts":
{"total":35,"reporting":35},
"name":"Preston"},
"Monroe":
{"votes":[
{"votes":1841,"name":"clinton"},
{"votes":607,"name":"obama"},
{"votes":274,"name":"edwards"}],
"total":2722,"precincts":
{"total":17,"reporting":17},
"name":"Monroe"}}})