GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":117137,"name":"clinton"},
{"votes":50167,"name":"obama"},
{"votes":12960,"name":"edwards"}],
"name":"West Virginia","precincts":
{"total":1894,"reporting":925},
"delegates":28,"date":"05-13"},
"state":"WV","party":"dem","total":180264,"locals":
{"Summers":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Summers"},
"Jackson":
{"votes":[
{"votes":2571,"name":"clinton"},
{"votes":828,"name":"obama"},
{"votes":279,"name":"edwards"}],
"total":3678,"precincts":
{"total":34,"reporting":22},
"name":"Jackson"},
"Braxton":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Braxton"},
"Grant":
{"votes":[
{"votes":290,"name":"clinton"},
{"votes":127,"name":"obama"},
{"votes":35,"name":"edwards"}],
"total":452,"precincts":
{"total":15,"reporting":9},
"name":"Grant"},
"Pendleton":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pendleton"},
"Wyoming":
{"votes":[
{"votes":935,"name":"clinton"},
{"votes":141,"name":"obama"},
{"votes":109,"name":"edwards"}],
"total":1185,"precincts":
{"total":36,"reporting":13},
"name":"Wyoming"},
"Calhoun":
{"votes":[
{"votes":1070,"name":"clinton"},
{"votes":356,"name":"obama"},
{"votes":178,"name":"edwards"}],
"total":1604,"precincts":
{"total":10,"reporting":10},
"name":"Calhoun"},
"Hampshire":
{"votes":[
{"votes":71,"name":"clinton"},
{"votes":31,"name":"obama"},
{"votes":6,"name":"edwards"}],
"total":108,"precincts":
{"total":23,"reporting":1},
"name":"Hampshire"},
"Mason":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Mason"},
"Roane":
{"votes":[
{"votes":1242,"name":"clinton"},
{"votes":397,"name":"obama"},
{"votes":131,"name":"edwards"}],
"total":1770,"precincts":
{"total":20,"reporting":14},
"name":"Roane"},
"Wirt":
{"votes":[
{"votes":724,"name":"clinton"},
{"votes":228,"name":"obama"},
{"votes":115,"name":"edwards"}],
"total":1067,"precincts":
{"total":9,"reporting":9},
"name":"Wirt"},
"Wood":
{"votes":[
{"votes":8391,"name":"clinton"},
{"votes":3201,"name":"obama"},
{"votes":930,"name":"edwards"}],
"total":12522,"precincts":
{"total":84,"reporting":84},
"name":"Wood"},
"Ohio":
{"votes":[
{"votes":5061,"name":"clinton"},
{"votes":3075,"name":"obama"},
{"votes":540,"name":"edwards"}],
"total":8676,"precincts":
{"total":39,"reporting":39},
"name":"Ohio"},
"Nicholas":
{"votes":[
{"votes":1456,"name":"clinton"},
{"votes":454,"name":"obama"},
{"votes":197,"name":"edwards"}],
"total":2107,"precincts":
{"total":28,"reporting":11},
"name":"Nicholas"},
"Putnam":
{"votes":[
{"votes":1421,"name":"clinton"},
{"votes":617,"name":"obama"},
{"votes":123,"name":"edwards"}],
"total":2161,"precincts":
{"total":48,"reporting":4},
"name":"Putnam"},
"McDowell":
{"votes":[
{"votes":794,"name":"clinton"},
{"votes":174,"name":"obama"},
{"votes":55,"name":"edwards"}],
"total":1023,"precincts":
{"total":42,"reporting":11},
"name":"McDowell"},
"Greenbrier":
{"votes":[
{"votes":1201,"name":"clinton"},
{"votes":748,"name":"obama"},
{"votes":155,"name":"edwards"}],
"total":2104,"precincts":
{"total":36,"reporting":6},
"name":"Greenbrier"},
"Gilmer":
{"votes":[
{"votes":369,"name":"clinton"},
{"votes":109,"name":"obama"},
{"votes":64,"name":"edwards"}],
"total":542,"precincts":
{"total":12,"reporting":4},
"name":"Gilmer"},
"Fayette":
{"votes":[],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Fayette"},
"Monongalia":
{"votes":[
{"votes":7769,"name":"clinton"},
{"votes":5505,"name":"obama"},
{"votes":911,"name":"edwards"}],
"total":14185,"precincts":
{"total":72,"reporting":69},
"name":"Monongalia"},
"Tucker":
{"votes":[
{"votes":741,"name":"clinton"},
{"votes":215,"name":"obama"},
{"votes":149,"name":"edwards"}],
"total":1105,"precincts":
{"total":11,"reporting":5},
"name":"Tucker"},
"Barbour":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Barbour"},
"Berkeley":
{"votes":[],
"total":0,"precincts":
{"total":66,"reporting":0},
"name":"Berkeley"},
"Brooke":
{"votes":[
{"votes":3866,"name":"clinton"},
{"votes":1577,"name":"obama"},
{"votes":426,"name":"edwards"}],
"total":5869,"precincts":
{"total":27,"reporting":27},
"name":"Brooke"},
"Ritchie":
{"votes":[
{"votes":418,"name":"clinton"},
{"votes":127,"name":"obama"},
{"votes":62,"name":"edwards"}],
"total":607,"precincts":
{"total":15,"reporting":14},
"name":"Ritchie"},
"Pocahontas":
{"votes":[
{"votes":1318,"name":"clinton"},
{"votes":557,"name":"obama"},
{"votes":214,"name":"edwards"}],
"total":2089,"precincts":
{"total":15,"reporting":15},
"name":"Pocahontas"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Wayne"},
"Lincoln":
{"votes":[
{"votes":3296,"name":"clinton"},
{"votes":510,"name":"obama"},
{"votes":344,"name":"edwards"}],
"total":4150,"precincts":
{"total":35,"reporting":28},
"name":"Lincoln"},
"Mineral":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Mineral"},
"Harrison":
{"votes":[
{"votes":5074,"name":"clinton"},
{"votes":1636,"name":"obama"},
{"votes":607,"name":"edwards"}],
"total":7317,"precincts":
{"total":89,"reporting":21},
"name":"Harrison"},
"Hancock":
{"votes":[
{"votes":3487,"name":"clinton"},
{"votes":1318,"name":"obama"},
{"votes":438,"name":"edwards"}],
"total":5243,"precincts":
{"total":28,"reporting":22},
"name":"Hancock"},
"Kanawha":
{"votes":[
{"votes":11663,"name":"clinton"},
{"votes":7126,"name":"obama"},
{"votes":745,"name":"edwards"}],
"total":19534,"precincts":
{"total":160,"reporting":65},
"name":"Kanawha"},
"Pleasants":
{"votes":[
{"votes":933,"name":"clinton"},
{"votes":372,"name":"obama"},
{"votes":170,"name":"edwards"}],
"total":1475,"precincts":
{"total":11,"reporting":11},
"name":"Pleasants"},
"Raleigh":
{"votes":[
{"votes":7826,"name":"clinton"},
{"votes":3192,"name":"obama"},
{"votes":904,"name":"edwards"}],
"total":11922,"precincts":
{"total":63,"reporting":50},
"name":"Raleigh"},
"Morgan":
{"votes":[
{"votes":710,"name":"clinton"},
{"votes":456,"name":"obama"},
{"votes":95,"name":"edwards"}],
"total":1261,"precincts":
{"total":13,"reporting":9},
"name":"Morgan"},
"Clay":
{"votes":[
{"votes":1162,"name":"clinton"},
{"votes":261,"name":"obama"},
{"votes":201,"name":"edwards"}],
"total":1624,"precincts":
{"total":13,"reporting":9},
"name":"Clay"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Webster"},
"Wetzel":
{"votes":[
{"votes":1917,"name":"clinton"},
{"votes":715,"name":"obama"},
{"votes":296,"name":"edwards"}],
"total":2928,"precincts":
{"total":22,"reporting":15},
"name":"Wetzel"},
"Upshur":
{"votes":[
{"votes":73,"name":"clinton"},
{"votes":35,"name":"obama"},
{"votes":2,"name":"edwards"}],
"total":110,"precincts":
{"total":29,"reporting":1},
"name":"Upshur"},
"Taylor":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Taylor"},
"Lewis":
{"votes":[
{"votes":196,"name":"clinton"},
{"votes":65,"name":"obama"},
{"votes":22,"name":"edwards"}],
"total":283,"precincts":
{"total":24,"reporting":3},
"name":"Lewis"},
"Marshall":
{"votes":[
{"votes":2548,"name":"clinton"},
{"votes":1053,"name":"obama"},
{"votes":346,"name":"edwards"}],
"total":3947,"precincts":
{"total":45,"reporting":30},
"name":"Marshall"},
"Mingo":
{"votes":[
{"votes":4587,"name":"clinton"},
{"votes":523,"name":"obama"},
{"votes":259,"name":"edwards"}],
"total":5369,"precincts":
{"total":39,"reporting":18},
"name":"Mingo"},
"Cabell":
{"votes":[
{"votes":4902,"name":"clinton"},
{"votes":2301,"name":"obama"},
{"votes":424,"name":"edwards"}],
"total":7627,"precincts":
{"total":71,"reporting":40},
"name":"Cabell"},
"Tyler":
{"votes":[
{"votes":356,"name":"clinton"},
{"votes":157,"name":"obama"},
{"votes":64,"name":"edwards"}],
"total":577,"precincts":
{"total":12,"reporting":7},
"name":"Tyler"},
"Hardy":
{"votes":[
{"votes":1041,"name":"clinton"},
{"votes":302,"name":"obama"},
{"votes":234,"name":"edwards"}],
"total":1577,"precincts":
{"total":18,"reporting":6},
"name":"Hardy"},
"Logan":
{"votes":[
{"votes":2268,"name":"clinton"},
{"votes":275,"name":"obama"},
{"votes":148,"name":"edwards"}],
"total":2691,"precincts":
{"total":35,"reporting":10},
"name":"Logan"},
"Jefferson":
{"votes":[
{"votes":4322,"name":"clinton"},
{"votes":4015,"name":"obama"},
{"votes":398,"name":"edwards"}],
"total":8735,"precincts":
{"total":31,"reporting":31},
"name":"Jefferson"},
"Marion":
{"votes":[
{"votes":9347,"name":"clinton"},
{"votes":3421,"name":"obama"},
{"votes":996,"name":"edwards"}],
"total":13764,"precincts":
{"total":76,"reporting":76},
"name":"Marion"},
"Doddridge":
{"votes":[
{"votes":421,"name":"clinton"},
{"votes":187,"name":"obama"},
{"votes":60,"name":"edwards"}],
"total":668,"precincts":
{"total":12,"reporting":12},
"name":"Doddridge"},
"Boone":
{"votes":[
{"votes":3092,"name":"clinton"},
{"votes":594,"name":"obama"},
{"votes":273,"name":"edwards"}],
"total":3959,"precincts":
{"total":37,"reporting":21},
"name":"Boone"},
"Mercer":
{"votes":[],
"total":0,"precincts":
{"total":61,"reporting":0},
"name":"Mercer"},
"Randolph":
{"votes":[
{"votes":4322,"name":"clinton"},
{"votes":1705,"name":"obama"},
{"votes":637,"name":"edwards"}],
"total":6664,"precincts":
{"total":27,"reporting":27},
"name":"Randolph"},
"Preston":
{"votes":[
{"votes":2878,"name":"clinton"},
{"votes":1061,"name":"obama"},
{"votes":456,"name":"edwards"}],
"total":4395,"precincts":
{"total":35,"reporting":35},
"name":"Preston"},
"Monroe":
{"votes":[
{"votes":1008,"name":"clinton"},
{"votes":420,"name":"obama"},
{"votes":162,"name":"edwards"}],
"total":1590,"precincts":
{"total":17,"reporting":11},
"name":"Monroe"}}})