GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":82818,"name":"clinton"},
{"votes":38158,"name":"obama"},
{"votes":9173,"name":"edwards"}],
"name":"West Virginia","precincts":
{"total":1894,"reporting":661},
"delegates":28,"date":"05-13"},
"state":"WV","party":"dem","total":130149,"locals":
{"Summers":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Summers"},
"Jackson":
{"votes":[
{"votes":2571,"name":"clinton"},
{"votes":828,"name":"obama"},
{"votes":279,"name":"edwards"}],
"total":3678,"precincts":
{"total":34,"reporting":22},
"name":"Jackson"},
"Braxton":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Braxton"},
"Grant":
{"votes":[
{"votes":178,"name":"clinton"},
{"votes":58,"name":"obama"},
{"votes":20,"name":"edwards"}],
"total":256,"precincts":
{"total":15,"reporting":6},
"name":"Grant"},
"Pendleton":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pendleton"},
"Wyoming":
{"votes":[
{"votes":935,"name":"clinton"},
{"votes":141,"name":"obama"},
{"votes":109,"name":"edwards"}],
"total":1185,"precincts":
{"total":36,"reporting":13},
"name":"Wyoming"},
"Calhoun":
{"votes":[
{"votes":1070,"name":"clinton"},
{"votes":356,"name":"obama"},
{"votes":178,"name":"edwards"}],
"total":1604,"precincts":
{"total":10,"reporting":10},
"name":"Calhoun"},
"Hampshire":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Hampshire"},
"Mason":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Mason"},
"Roane":
{"votes":[
{"votes":897,"name":"clinton"},
{"votes":277,"name":"obama"},
{"votes":81,"name":"edwards"}],
"total":1255,"precincts":
{"total":20,"reporting":10},
"name":"Roane"},
"Wirt":
{"votes":[
{"votes":724,"name":"clinton"},
{"votes":228,"name":"obama"},
{"votes":115,"name":"edwards"}],
"total":1067,"precincts":
{"total":9,"reporting":9},
"name":"Wirt"},
"Wood":
{"votes":[
{"votes":4275,"name":"clinton"},
{"votes":1664,"name":"obama"},
{"votes":469,"name":"edwards"}],
"total":6408,"precincts":
{"total":84,"reporting":54},
"name":"Wood"},
"Ohio":
{"votes":[
{"votes":5061,"name":"clinton"},
{"votes":3075,"name":"obama"},
{"votes":540,"name":"edwards"}],
"total":8676,"precincts":
{"total":39,"reporting":39},
"name":"Ohio"},
"Nicholas":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Nicholas"},
"Putnam":
{"votes":[
{"votes":1421,"name":"clinton"},
{"votes":617,"name":"obama"},
{"votes":123,"name":"edwards"}],
"total":2161,"precincts":
{"total":48,"reporting":4},
"name":"Putnam"},
"McDowell":
{"votes":[
{"votes":794,"name":"clinton"},
{"votes":174,"name":"obama"},
{"votes":55,"name":"edwards"}],
"total":1023,"precincts":
{"total":42,"reporting":11},
"name":"McDowell"},
"Greenbrier":
{"votes":[],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Greenbrier"},
"Gilmer":
{"votes":[
{"votes":369,"name":"clinton"},
{"votes":109,"name":"obama"},
{"votes":64,"name":"edwards"}],
"total":542,"precincts":
{"total":12,"reporting":4},
"name":"Gilmer"},
"Fayette":
{"votes":[],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Fayette"},
"Monongalia":
{"votes":[
{"votes":7769,"name":"clinton"},
{"votes":5505,"name":"obama"},
{"votes":911,"name":"edwards"}],
"total":14185,"precincts":
{"total":72,"reporting":69},
"name":"Monongalia"},
"Tucker":
{"votes":[
{"votes":434,"name":"clinton"},
{"votes":155,"name":"obama"},
{"votes":90,"name":"edwards"}],
"total":679,"precincts":
{"total":11,"reporting":2},
"name":"Tucker"},
"Barbour":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Barbour"},
"Berkeley":
{"votes":[],
"total":0,"precincts":
{"total":66,"reporting":0},
"name":"Berkeley"},
"Brooke":
{"votes":[
{"votes":2551,"name":"clinton"},
{"votes":1049,"name":"obama"},
{"votes":280,"name":"edwards"}],
"total":3880,"precincts":
{"total":27,"reporting":20},
"name":"Brooke"},
"Ritchie":
{"votes":[
{"votes":283,"name":"clinton"},
{"votes":91,"name":"obama"},
{"votes":46,"name":"edwards"}],
"total":420,"precincts":
{"total":15,"reporting":9},
"name":"Ritchie"},
"Pocahontas":
{"votes":[
{"votes":769,"name":"clinton"},
{"votes":377,"name":"obama"},
{"votes":146,"name":"edwards"}],
"total":1292,"precincts":
{"total":15,"reporting":10},
"name":"Pocahontas"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Wayne"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Lincoln"},
"Mineral":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Mineral"},
"Harrison":
{"votes":[
{"votes":3062,"name":"clinton"},
{"votes":1024,"name":"obama"},
{"votes":343,"name":"edwards"}],
"total":4429,"precincts":
{"total":89,"reporting":8},
"name":"Harrison"},
"Hancock":
{"votes":[
{"votes":1087,"name":"clinton"},
{"votes":448,"name":"obama"},
{"votes":137,"name":"edwards"}],
"total":1672,"precincts":
{"total":28,"reporting":8},
"name":"Hancock"},
"Kanawha":
{"votes":[
{"votes":9161,"name":"clinton"},
{"votes":5550,"name":"obama"},
{"votes":582,"name":"edwards"}],
"total":15293,"precincts":
{"total":160,"reporting":45},
"name":"Kanawha"},
"Pleasants":
{"votes":[
{"votes":933,"name":"clinton"},
{"votes":372,"name":"obama"},
{"votes":170,"name":"edwards"}],
"total":1475,"precincts":
{"total":11,"reporting":11},
"name":"Pleasants"},
"Raleigh":
{"votes":[
{"votes":4977,"name":"clinton"},
{"votes":2393,"name":"obama"},
{"votes":589,"name":"edwards"}],
"total":7959,"precincts":
{"total":63,"reporting":30},
"name":"Raleigh"},
"Morgan":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Morgan"},
"Clay":
{"votes":[
{"votes":852,"name":"clinton"},
{"votes":211,"name":"obama"},
{"votes":157,"name":"edwards"}],
"total":1220,"precincts":
{"total":13,"reporting":6},
"name":"Clay"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Webster"},
"Wetzel":
{"votes":[
{"votes":1536,"name":"clinton"},
{"votes":575,"name":"obama"},
{"votes":220,"name":"edwards"}],
"total":2331,"precincts":
{"total":22,"reporting":10},
"name":"Wetzel"},
"Upshur":
{"votes":[
{"votes":73,"name":"clinton"},
{"votes":35,"name":"obama"},
{"votes":2,"name":"edwards"}],
"total":110,"precincts":
{"total":29,"reporting":1},
"name":"Upshur"},
"Taylor":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Taylor"},
"Lewis":
{"votes":[
{"votes":196,"name":"clinton"},
{"votes":65,"name":"obama"},
{"votes":22,"name":"edwards"}],
"total":283,"precincts":
{"total":24,"reporting":3},
"name":"Lewis"},
"Marshall":
{"votes":[
{"votes":1636,"name":"clinton"},
{"votes":660,"name":"obama"},
{"votes":216,"name":"edwards"}],
"total":2512,"precincts":
{"total":45,"reporting":20},
"name":"Marshall"},
"Mingo":
{"votes":[
{"votes":1336,"name":"clinton"},
{"votes":205,"name":"obama"},
{"votes":90,"name":"edwards"}],
"total":1631,"precincts":
{"total":39,"reporting":5},
"name":"Mingo"},
"Cabell":
{"votes":[
{"votes":3341,"name":"clinton"},
{"votes":1838,"name":"obama"},
{"votes":295,"name":"edwards"}],
"total":5474,"precincts":
{"total":71,"reporting":30},
"name":"Cabell"},
"Tyler":
{"votes":[
{"votes":356,"name":"clinton"},
{"votes":157,"name":"obama"},
{"votes":64,"name":"edwards"}],
"total":577,"precincts":
{"total":12,"reporting":7},
"name":"Tyler"},
"Hardy":
{"votes":[
{"votes":645,"name":"clinton"},
{"votes":218,"name":"obama"},
{"votes":141,"name":"edwards"}],
"total":1004,"precincts":
{"total":18,"reporting":2},
"name":"Hardy"},
"Logan":
{"votes":[
{"votes":2268,"name":"clinton"},
{"votes":275,"name":"obama"},
{"votes":148,"name":"edwards"}],
"total":2691,"precincts":
{"total":35,"reporting":10},
"name":"Logan"},
"Jefferson":
{"votes":[
{"votes":3063,"name":"clinton"},
{"votes":2918,"name":"obama"},
{"votes":281,"name":"edwards"}],
"total":6262,"precincts":
{"total":31,"reporting":19},
"name":"Jefferson"},
"Marion":
{"votes":[
{"votes":9347,"name":"clinton"},
{"votes":3421,"name":"obama"},
{"votes":996,"name":"edwards"}],
"total":13764,"precincts":
{"total":76,"reporting":76},
"name":"Marion"},
"Doddridge":
{"votes":[
{"votes":421,"name":"clinton"},
{"votes":187,"name":"obama"},
{"votes":60,"name":"edwards"}],
"total":668,"precincts":
{"total":12,"reporting":12},
"name":"Doddridge"},
"Boone":
{"votes":[
{"votes":1815,"name":"clinton"},
{"votes":297,"name":"obama"},
{"votes":161,"name":"edwards"}],
"total":2273,"precincts":
{"total":37,"reporting":6},
"name":"Boone"},
"Mercer":
{"votes":[],
"total":0,"precincts":
{"total":61,"reporting":0},
"name":"Mercer"},
"Randolph":
{"votes":[
{"votes":3301,"name":"clinton"},
{"votes":1340,"name":"obama"},
{"votes":470,"name":"edwards"}],
"total":5111,"precincts":
{"total":27,"reporting":20},
"name":"Randolph"},
"Preston":
{"votes":[
{"votes":2878,"name":"clinton"},
{"votes":1061,"name":"obama"},
{"votes":456,"name":"edwards"}],
"total":4395,"precincts":
{"total":35,"reporting":35},
"name":"Preston"},
"Monroe":
{"votes":[
{"votes":433,"name":"clinton"},
{"votes":204,"name":"obama"},
{"votes":67,"name":"edwards"}],
"total":704,"precincts":
{"total":17,"reporting":5},
"name":"Monroe"}}})