GoogleElectionMap.votesReady({"status":"ok","totals":
{"votes":[
{"votes":25227,"name":"mccain"},
{"votes":3379,"name":"huckabee","delegates":18},
{"votes":1740,"name":"romney"},
{"votes":1665,"name":"paul"},
{"votes":875,"name":"giuliani"},
{"votes":414,"name":"keyes"},
{"votes":203,"name":"curry"}],
"name":"West Virginia","precincts":
{"total":1,"reporting":1},
"delegates":18,"date":"05-13"},
"state":"WV","party":"gop","total":33503,"locals":
{"Summers":
{"votes":[],
"total":0,"precincts":
{"total":15,"reporting":0},
"name":"Summers"},
"Jackson":
{"votes":[
{"votes":1279,"name":"mccain"},
{"votes":182,"name":"huckabee"},
{"votes":76,"name":"paul"},
{"votes":73,"name":"romney"},
{"votes":40,"name":"giuliani"},
{"votes":15,"name":"keyes"},
{"votes":10,"name":"curry"}],
"total":1675,"precincts":
{"total":34,"reporting":13},
"name":"Jackson"},
"Braxton":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Braxton"},
"Grant":
{"votes":[
{"votes":723,"name":"mccain"},
{"votes":88,"name":"huckabee"},
{"votes":24,"name":"romney"},
{"votes":13,"name":"giuliani"},
{"votes":12,"name":"curry"},
{"votes":9,"name":"paul"},
{"votes":6,"name":"keyes"}],
"total":875,"precincts":
{"total":15,"reporting":6},
"name":"Grant"},
"Pendleton":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Pendleton"},
"Wyoming":
{"votes":[
{"votes":36,"name":"mccain"},
{"votes":4,"name":"paul"},
{"votes":1,"name":"romney"},
{"votes":1,"name":"huckabee"},
{"votes":1,"name":"giuliani"},
{"votes":1,"name":"curry"}],
"total":44,"precincts":
{"total":36,"reporting":4},
"name":"Wyoming"},
"Calhoun":
{"votes":[],
"total":0,"precincts":
{"total":10,"reporting":0},
"name":"Calhoun"},
"Hampshire":
{"votes":[],
"total":0,"precincts":
{"total":23,"reporting":0},
"name":"Hampshire"},
"Mason":
{"votes":[],
"total":0,"precincts":
{"total":38,"reporting":0},
"name":"Mason"},
"Roane":
{"votes":[
{"votes":216,"name":"mccain"},
{"votes":38,"name":"huckabee"},
{"votes":17,"name":"giuliani"},
{"votes":12,"name":"romney"},
{"votes":8,"name":"paul"},
{"votes":2,"name":"curry"},
{"votes":1,"name":"keyes"}],
"total":294,"precincts":
{"total":20,"reporting":5},
"name":"Roane"},
"Wirt":
{"votes":[
{"votes":428,"name":"mccain"},
{"votes":57,"name":"huckabee"},
{"votes":34,"name":"paul"},
{"votes":20,"name":"giuliani"},
{"votes":12,"name":"romney"},
{"votes":6,"name":"curry"},
{"votes":3,"name":"keyes"}],
"total":560,"precincts":
{"total":9,"reporting":9},
"name":"Wirt"},
"Wood":
{"votes":[
{"votes":2777,"name":"mccain"},
{"votes":459,"name":"huckabee"},
{"votes":266,"name":"romney"},
{"votes":236,"name":"paul"},
{"votes":111,"name":"giuliani"},
{"votes":46,"name":"keyes"},
{"votes":16,"name":"curry"}],
"total":3911,"precincts":
{"total":84,"reporting":54},
"name":"Wood"},
"Ohio":
{"votes":[
{"votes":3019,"name":"mccain"},
{"votes":294,"name":"huckabee"},
{"votes":260,"name":"romney"},
{"votes":164,"name":"paul"},
{"votes":89,"name":"giuliani"},
{"votes":71,"name":"keyes"},
{"votes":12,"name":"curry"}],
"total":3909,"precincts":
{"total":39,"reporting":39},
"name":"Ohio"},
"Nicholas":
{"votes":[],
"total":0,"precincts":
{"total":28,"reporting":0},
"name":"Nicholas"},
"Putnam":
{"votes":[
{"votes":788,"name":"mccain"},
{"votes":92,"name":"huckabee"},
{"votes":55,"name":"paul"},
{"votes":42,"name":"romney"},
{"votes":13,"name":"keyes"},
{"votes":10,"name":"giuliani"},
{"votes":3,"name":"curry"}],
"total":1003,"precincts":
{"total":48,"reporting":4},
"name":"Putnam"},
"McDowell":
{"votes":[],
"total":0,"precincts":
{"total":42,"reporting":0},
"name":"McDowell"},
"Greenbrier":
{"votes":[],
"total":0,"precincts":
{"total":36,"reporting":0},
"name":"Greenbrier"},
"Gilmer":
{"votes":[],
"total":0,"precincts":
{"total":12,"reporting":0},
"name":"Gilmer"},
"Fayette":
{"votes":[],
"total":0,"precincts":
{"total":39,"reporting":0},
"name":"Fayette"},
"Monongalia":
{"votes":[
{"votes":2313,"name":"mccain"},
{"votes":331,"name":"huckabee"},
{"votes":226,"name":"paul"},
{"votes":213,"name":"romney"},
{"votes":111,"name":"giuliani"},
{"votes":55,"name":"keyes"},
{"votes":17,"name":"curry"}],
"total":3266,"precincts":
{"total":72,"reporting":60},
"name":"Monongalia"},
"Tucker":
{"votes":[
{"votes":144,"name":"mccain"},
{"votes":10,"name":"huckabee"},
{"votes":3,"name":"romney"},
{"votes":3,"name":"giuliani"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"keyes"},
{"votes":1,"name":"curry"}],
"total":166,"precincts":
{"total":11,"reporting":2},
"name":"Tucker"},
"Barbour":
{"votes":[],
"total":0,"precincts":
{"total":22,"reporting":0},
"name":"Barbour"},
"Berkeley":
{"votes":[],
"total":0,"precincts":
{"total":66,"reporting":0},
"name":"Berkeley"},
"Brooke":
{"votes":[
{"votes":251,"name":"mccain"},
{"votes":28,"name":"huckabee"},
{"votes":18,"name":"romney"},
{"votes":18,"name":"paul"},
{"votes":11,"name":"giuliani"},
{"votes":2,"name":"keyes"},
{"votes":2,"name":"curry"}],
"total":330,"precincts":
{"total":27,"reporting":10},
"name":"Brooke"},
"Ritchie":
{"votes":[
{"votes":443,"name":"mccain"},
{"votes":46,"name":"huckabee"},
{"votes":37,"name":"paul"},
{"votes":22,"name":"romney"},
{"votes":15,"name":"giuliani"},
{"votes":9,"name":"keyes"},
{"votes":1,"name":"curry"}],
"total":573,"precincts":
{"total":15,"reporting":6},
"name":"Ritchie"},
"Pocahontas":
{"votes":[
{"votes":295,"name":"mccain"},
{"votes":49,"name":"huckabee"},
{"votes":18,"name":"paul"},
{"votes":11,"name":"romney"},
{"votes":6,"name":"curry"},
{"votes":5,"name":"giuliani"},
{"votes":2,"name":"keyes"}],
"total":386,"precincts":
{"total":15,"reporting":10},
"name":"Pocahontas"},
"Wayne":
{"votes":[],
"total":0,"precincts":
{"total":37,"reporting":0},
"name":"Wayne"},
"Lincoln":
{"votes":[],
"total":0,"precincts":
{"total":35,"reporting":0},
"name":"Lincoln"},
"Mineral":
{"votes":[],
"total":0,"precincts":
{"total":32,"reporting":0},
"name":"Mineral"},
"Harrison":
{"votes":[],
"total":0,"precincts":
{"total":89,"reporting":0},
"name":"Harrison"},
"Hancock":
{"votes":[
{"votes":244,"name":"mccain"},
{"votes":31,"name":"huckabee"},
{"votes":29,"name":"paul"},
{"votes":23,"name":"romney"},
{"votes":11,"name":"giuliani"},
{"votes":6,"name":"keyes"},
{"votes":1,"name":"curry"}],
"total":345,"precincts":
{"total":28,"reporting":8},
"name":"Hancock"},
"Kanawha":
{"votes":[
{"votes":3145,"name":"mccain"},
{"votes":392,"name":"huckabee"},
{"votes":271,"name":"paul"},
{"votes":251,"name":"romney"},
{"votes":91,"name":"giuliani"},
{"votes":39,"name":"keyes"},
{"votes":34,"name":"curry"}],
"total":4223,"precincts":
{"total":160,"reporting":45},
"name":"Kanawha"},
"Pleasants":
{"votes":[],
"total":0,"precincts":
{"total":11,"reporting":0},
"name":"Pleasants"},
"Raleigh":
{"votes":[
{"votes":1422,"name":"mccain"},
{"votes":233,"name":"huckabee"},
{"votes":62,"name":"paul"},
{"votes":48,"name":"romney"},
{"votes":22,"name":"giuliani"},
{"votes":10,"name":"keyes"},
{"votes":7,"name":"curry"}],
"total":1804,"precincts":
{"total":63,"reporting":30},
"name":"Raleigh"},
"Morgan":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Morgan"},
"Clay":
{"votes":[
{"votes":181,"name":"mccain"},
{"votes":28,"name":"huckabee"},
{"votes":6,"name":"keyes"},
{"votes":5,"name":"romney"},
{"votes":4,"name":"giuliani"},
{"votes":3,"name":"paul"},
{"votes":2,"name":"curry"}],
"total":229,"precincts":
{"total":13,"reporting":6},
"name":"Clay"},
"Webster":
{"votes":[],
"total":0,"precincts":
{"total":13,"reporting":0},
"name":"Webster"},
"Wetzel":
{"votes":[
{"votes":195,"name":"mccain"},
{"votes":29,"name":"huckabee"},
{"votes":19,"name":"romney"},
{"votes":7,"name":"paul"},
{"votes":5,"name":"giuliani"},
{"votes":1,"name":"keyes"}],
"total":256,"precincts":
{"total":22,"reporting":5},
"name":"Wetzel"},
"Upshur":
{"votes":[],
"total":0,"precincts":
{"total":29,"reporting":0},
"name":"Upshur"},
"Taylor":
{"votes":[],
"total":0,"precincts":
{"total":18,"reporting":0},
"name":"Taylor"},
"Lewis":
{"votes":[
{"votes":121,"name":"mccain"},
{"votes":3,"name":"huckabee"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"curry"}],
"total":127,"precincts":
{"total":24,"reporting":3},
"name":"Lewis"},
"Marshall":
{"votes":[
{"votes":176,"name":"mccain"},
{"votes":27,"name":"huckabee"},
{"votes":10,"name":"paul"},
{"votes":9,"name":"giuliani"},
{"votes":4,"name":"romney"},
{"votes":1,"name":"keyes"}],
"total":227,"precincts":
{"total":45,"reporting":5},
"name":"Marshall"},
"Mingo":
{"votes":[
{"votes":57,"name":"mccain"},
{"votes":5,"name":"huckabee"},
{"votes":2,"name":"romney"},
{"votes":2,"name":"giuliani"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"paul"}],
"total":68,"precincts":
{"total":39,"reporting":5},
"name":"Mingo"},
"Cabell":
{"votes":[
{"votes":886,"name":"mccain"},
{"votes":102,"name":"huckabee"},
{"votes":86,"name":"paul"},
{"votes":67,"name":"romney"},
{"votes":29,"name":"giuliani"},
{"votes":19,"name":"keyes"},
{"votes":9,"name":"curry"}],
"total":1198,"precincts":
{"total":71,"reporting":20},
"name":"Cabell"},
"Tyler":
{"votes":[
{"votes":700,"name":"mccain"},
{"votes":93,"name":"huckabee"},
{"votes":44,"name":"romney"},
{"votes":43,"name":"paul"},
{"votes":22,"name":"giuliani"},
{"votes":15,"name":"keyes"},
{"votes":15,"name":"curry"}],
"total":932,"precincts":
{"total":12,"reporting":7},
"name":"Tyler"},
"Hardy":
{"votes":[
{"votes":40,"name":"mccain"},
{"votes":6,"name":"huckabee"},
{"votes":5,"name":"romney"},
{"votes":3,"name":"giuliani"},
{"votes":1,"name":"curry"},
{"votes":1,"name":"paul"}],
"total":56,"precincts":
{"total":18,"reporting":1},
"name":"Hardy"},
"Logan":
{"votes":[
{"votes":109,"name":"mccain"},
{"votes":13,"name":"huckabee"},
{"votes":6,"name":"giuliani"},
{"votes":4,"name":"romney"},
{"votes":2,"name":"keyes"},
{"votes":2,"name":"paul"},
{"votes":1,"name":"curry"}],
"total":137,"precincts":
{"total":35,"reporting":10},
"name":"Logan"},
"Jefferson":
{"votes":[],
"total":0,"precincts":
{"total":31,"reporting":0},
"name":"Jefferson"},
"Marion":
{"votes":[
{"votes":1162,"name":"mccain"},
{"votes":139,"name":"huckabee"},
{"votes":99,"name":"romney"},
{"votes":75,"name":"giuliani"},
{"votes":47,"name":"paul"},
{"votes":29,"name":"keyes"},
{"votes":6,"name":"curry"}],
"total":1557,"precincts":
{"total":76,"reporting":41},
"name":"Marion"},
"Doddridge":
{"votes":[
{"votes":1133,"name":"mccain"},
{"votes":134,"name":"huckabee"},
{"votes":70,"name":"paul"},
{"votes":60,"name":"romney"},
{"votes":28,"name":"giuliani"},
{"votes":15,"name":"keyes"},
{"votes":12,"name":"curry"}],
"total":1452,"precincts":
{"total":12,"reporting":12},
"name":"Doddridge"},
"Boone":
{"votes":[
{"votes":135,"name":"mccain"},
{"votes":11,"name":"huckabee"},
{"votes":10,"name":"paul"},
{"votes":9,"name":"romney"},
{"votes":6,"name":"giuliani"}],
"total":171,"precincts":
{"total":37,"reporting":6},
"name":"Boone"},
"Mercer":
{"votes":[],
"total":0,"precincts":
{"total":61,"reporting":0},
"name":"Mercer"},
"Randolph":
{"votes":[
{"votes":900,"name":"mccain"},
{"votes":118,"name":"huckabee"},
{"votes":55,"name":"romney"},
{"votes":38,"name":"paul"},
{"votes":31,"name":"giuliani"},
{"votes":6,"name":"curry"},
{"votes":5,"name":"keyes"}],
"total":1153,"precincts":
{"total":27,"reporting":20},
"name":"Randolph"},
"Preston":
{"votes":[
{"votes":1662,"name":"mccain"},
{"votes":294,"name":"huckabee"},
{"votes":85,"name":"paul"},
{"votes":80,"name":"romney"},
{"votes":79,"name":"giuliani"},
{"votes":39,"name":"keyes"},
{"votes":18,"name":"curry"}],
"total":2257,"precincts":
{"total":35,"reporting":20},
"name":"Preston"},
"Monroe":
{"votes":[
{"votes":247,"name":"mccain"},
{"votes":46,"name":"huckabee"},
{"votes":12,"name":"paul"},
{"votes":8,"name":"romney"},
{"votes":4,"name":"giuliani"},
{"votes":1,"name":"keyes"},
{"votes":1,"name":"curry"}],
"total":319,"precincts":
{"total":17,"reporting":5},
"name":"Monroe"}}})